J02-3001:1	22:696	Systems for booking airplane information use domain-specific frames with slots like origcity, destcity,ordepart time (Stallard 2000).
---------------------------------------------------
W02-0209:2	75:117	The dialog history is reminiscent of BBN s state manager (Stallard 2000), but the latter also includes many dialog management responsibilities that we reserve to tasks.
---------------------------------------------------
H05-1078:3	6:199	1 Introduction With recent advances in speech recognition, parsing, and information extraction, some domain-specific interactive systems are now of practical use for tasks such as question-answering, flight booking, or restaurant reservation (Stallard, 2000).
---------------------------------------------------
