Stevenson and Gaizauskas (2000) use TiMBL (Daelemans et al. , 2000) to identify sentence boundaries in speech recognizer output, and Gotoh and Renals (2000) use a statistical approach to identify sentence boundaries in automatic speech recognition transcripts of broadcast speech.


6 Future Work and Conclusion The experiments reported here  like much of the previous work in comma restoration (Beeferman et al. , 1998) and sentence boundary disambiguation and restoration (Stolcke and Shriberg, 1996; Shriberg et al. , 2001; Gotoh and Renals, 2000; Stevenson and Gaizauskas, 2000) (though not all (Christensen et al. , 2001; Stolcke et al. , 1998; Kim and Woodland, 2001))  assume an ideal reference transcription of the text.


Stevenson and Gaizauskas (Stevenson and Gaizauskas, 2000) and Goto and Renals (Gotoh and Renals, 2000) address the sentence boundary detection problem directly, again using lexical and, in the latter, prosodic cues.


The experimental results show that humans do not always agree on the insertion of punctuation symbols, and that their segmentation performance is not very good (Stevenson and Gaizauskas, 2000).


