Computer dialogue is now used at production stage for applications such as tutorial dialogue  that helps teaching students (Freedman, 2000)  task-oriented dialogue  that achieves a particular, limited task, such as booking a trip (Allen et al., 2000)  and chatbot dialogue (Levy et al., 1997)  that is used within entertainment and help systems.


Even if our ITS does not currently allow for student input, our generation architecture is inspired by state-of-the art tutorial dialog management (Freedman, 2000; Jordan et al., 2001; Zinn et al., 2002).


