Many different dialogue systems have been built according to this general approach (e.g. , (Cooper and Larsson, 1999; Matheson et al. , 2000; Lemon et al. , 2001; Johnston et al. , 2002; Traum and Rickel, 2002; Purver, 2002)).


We address how this information might be modelled in the PTT (Poesio and Traum, 1998) model of dialogue by adapting the Information State (IS) (Matheson et al. , 2000) in order to facilitate more responsive generation from the system upon hearing the DofE.


We show how the Information State (IS) (Matheson et al. , 2000) representing the state of the dialogue in the PTT (Poesio and Traum, 1998) model of dialogue must be updated to reflect this new information, with Conversational Acts (Matheson et al. , 2000) that do not simply indicate DofE as in (Thomas and Matheson, 2003), but also annotate the relation underlying the expectation being denied.


(Bohlin et al. , 1999; Matheson et al. , 2000)).


