(2000) that draws on a stochastic tagger (see Cutting et al.


(2000) that draws on a stochastic tagger (see (Cutting et al. , 1992) for details) as well as the SPECIALIST Lexicon5, a large syntactic lexicon of both general and medical English that is distributed with the UMLS.


For example, for a gene or protein name recognized in a text, Termino will return the database identifiers of this term in the HUGO Nomenclature database (Wain et al. , 2002) and the OMIM database (Online Mendelian Inheritance in Man, OMIM (TM), 2000).


This has led to an increased interest in the application of natural language processing techniques for the automatic capture of biomedical content from journal abstracts, complete papers, and other textual documents (Gaizauskas et al. , 2003; Hahn et al. , 2002; Pustejovsky et al. , 2002; Rindflesch et al. , 2000).


(2000), Thomas et al.


