This is very important for applications such as TransType (Foster et al. , 1997; Langlais et al. , 2000), where the task is to make real-time predictions of the text a human translator will type next, based on the source text under translation and some prefix of the target text that has already been typed.


For example, we can use such a translation model to help complete target text being drafted by a human translator (Langlais et al. , 2000).


A very similar study but with weaker results is derscribed in (Langlais et al. , 2000), in the framework of the TransType project.


The potential gain from multiple-word predictions (Langlais et al. , 2000) can be appreciated in the one-sentence translation task reported in table 1, where a hypothetical user saves over 60% of the keystrokes needed to produce a translation in a word completion scenario, and about 75% in a "unit" completion scenario 2.2 System Viewpoint The core of TRANSTYPE is a completion engine which comprises two main parts: an evaluator which assigns probabilistic scores to completion 47 This bill is very similar to its companion bill which we dealt with yesterday in the house of commons word-completion task.


