P09-1015:1	130:221	In this paper, we apply the ALINE algorithm to the task of L2P alignment (Kondrak, 2000; Inkpen et al., 2007).
---------------------------------------------------
W07-1308:2	104:211	The algorithm used in this study is a similarity-based approach, not unlike ALINE (Kondrak, 2000).
---------------------------------------------------
P07-1109:3	109:221	4.2 ALINE Unlike other algorithms presented here, the ALINE algorithm (Kondrak, 2000) operates in the phonetic, rather than the orthographic, domain.
---------------------------------------------------
D07-1095:4	17:200	Metrics based on algorithms that learn from examples of strings that should match (Bilenko et al. , 2003; Ristad and Yianilos, 1998) and metrics that use phonetic similarity criterion, e.g., (Kondrak, 2000) are no less expensive than edit distance.
---------------------------------------------------
W06-1107:5	159:207	ALINE denotes the algorithm for aligning phonetic sequences (Kondrak, 2000) described in Section 2.1.
---------------------------------------------------
W06-1107:6	29:207	2.1 ALINE The ALINE algorithm (Kondrak, 2000) assigns a similarity score to pairs of phonetically-transcribed words on the basis of the decomposition of phonemes into elementary phonetic features.
---------------------------------------------------
N09-1008:7	15:289	There has been work attempting to automate part (Durham and Rogers, 1969; Eastlack, 1977; Lowe and Mazaudon, 1994; Covington, 1998; Kondrak, 2002) or all of the process (Oakes, 2000; Bouchard-Cote et al., 2008).
---------------------------------------------------
N09-1008:8	281:289	This feature set is reminiscent of the featurized representation of Kondrak (2000).
---------------------------------------------------
C04-1137:9	30:217	For the detection of sound-alike confusion pairs, we apply the ALINE phonetic aligner (Kondrak, 2000), which estimates the similarity between two phonetically-transcribed words.
---------------------------------------------------
C04-1137:10	63:217	3 Phonetic Similarity: ALINE The ALINE cognate matching algorithm (Kondrak, 2000) assigns a similarity score to pairs of phonetically-transcribed words on the basis of the decomposition of phonemes into elementary phonetic features.
---------------------------------------------------
N01-1014:11	52:212	Melamed (1999) uses the Longest Common Subsequence Ratio (LCSR) defined as LCSRa0 xa1 ya2a4a3 a5 LCS a0 x a1 ya2a8a5 maxa0 a5 xa5a12a1a13a5 ya5a14a2 where LCS(x,y) is the longest common subsequence of x and y. ALINE (Kondrak, 2000), is an example of the phonetic approach.
---------------------------------------------------
N01-1014:12	26:212	words that are unrelated.1 In this paper, I present COGIT, a cognate-identification system that combines ALINE (Kondrak, 2000), a feature-based algorithm for measuring phonetic similarity, with a novel procedure for estimating semantic similarity that employs keyword selection and WordNet.
---------------------------------------------------
N01-1014:13	117:212	The implementation of ALINE is described in (Kondrak, 2000).
---------------------------------------------------
N01-1014:14	164:212	The salience settings were the same as in (Kondrak, 2000), except that the salience of feature Long was set to 5.
---------------------------------------------------
W05-0805:15	19:198	Kondrak (2000) presents an algorithm to align phonetic sequences by computing the similarities of these words.
---------------------------------------------------
C02-1016:16	29:163	2 Related work In a schematic description of the comparative method, the two steps that precede the determination of correspondences are the identification of cognate pairs (Kondrak, 2001), and their phonetic alignment (Kondrak, 2000).
---------------------------------------------------
C02-1016:17	73:163	The introduction of the no-crossing-links constraint on alignments not only leads to a dramatic reduction of the search space, but also makes it possible to replace the approximate competitive-linking algorithm of Melamed with a variant of the well-known dynamic programming algorithm (Wagner and Fischer, 1974; Kondrak, 2000), which computes the optimal alignment between two strings in polynomial time.
---------------------------------------------------
W05-0606:18	183:196	We also include the results obtained by the ALINE word aligner (Kondrak, 2000) on phonetically-transcribed word lists.
---------------------------------------------------
W08-1402:19	52:182	Earlier research by (Kondrak 2000) used dynamic programming to align strings of phonemes, representing the phonemes as vectors of phonological features, which are associated with scores to produce similarity values.
---------------------------------------------------
N09-3008:20	9:144	Algorithms for aligning pairs of words have been proposed by Covington (1996) and Kondrak (2000).
---------------------------------------------------
