3ThePOS taggers The two POS taggers used in the experiments are TNT, a publicly available Markov model tagger (Brants, 2000), and a reimplementation of the maximum entropy (ME) tagger MXPOST (Ratnaparkhi, 1996). 
B3: Tag the tokens with PTB-style POS tags using a tagger (Brants, 2000). 
For English we use the TnT PoS tagger (Brants, 2000) and WordNet for lemmatization (Miller et al. , 1990). 
We used TnT (Brants, 2000) for PoS tagging. 
The TnT tagger (Brants, 2000), used as distributed with its model trained on the Wall Street Journal portion of the Penn treebank, was used to obtain part-of-speech tags for the English side of the parallel text. 
