Blaheta and Charniak (2000) presented the first method for assigning Penn functional tags to constituents identified by a parser. 
Like previous work (Blaheta and Charniak, 2000), we complete the sets of syntactic and semantic labels by labelling constituents that do not bear any function label with a NULL label.3 2.3 Evaluation To evaluate the performance of our function parsing experiments, we will use several measures. 
Many researchers ((Blaheta and Charniak 2000), (Gildea and Jurafsky 2000), showed that lexical and syntactic information is very useful for predicateargument recognition tasks, such as semantic roles. 
Blaheta, D. and E. Charniak (2000) Assigning function tags to parsed text. 
Following (Blaheta and Charniak, 2000), we concentrate on syntactic and semantic function labels. 
