Answer extraction based on grammatical information is also promoted by the system described in (Clarke et al. , 2000). 
3.1 Feature Representation Our feature representation was designed to capture the information sources that prior work (Hirschman et al. , 1999; Cha_niak et al. , 2000; Riloff and Thelen, 2000) used in their computations or rules. 
For comparison, the HumSent scores reported in the work of (Hirschm~.n et al. , 1999), (Charniak et al. , 2000), (Riloff and Thelen, 2000), and (Wang et al. , 2000) are 36.3%, 41%, 39.7%, and 14%, respectively. 
3 Unlike Prager et al. , our reimplementation does not use a ranking function (Radev et al. , 2000). 
The one notable exception is the work of (Wang et al. , 2000), which attempted a machine learning approach to question answering for the same reading comprehension task. 
