This approach was adopted in (Kupiec, 1993; Abney et al. , 2000; Cardie et al. , 2000; Moldovan et al. , 2000).


(Cardie et al. , 2000) presents a method of extracting answers as noun phrases in a novel way.


Cardie et al. [2000] pointed out that building open-ended question answering systems that allow users to pose questions of any type and in any language, without domain restrictions, is still beyond the scope of any QA system today (p. 180).


