Dependency relations have also been found to be useful in information extraction (Culotta and Sorensen, 2004; Yangarber et al. , 2000). 
In this section, we review two of the previous models in detail, namely the Predicate-Argument model (Yangarber et al. , 2000) and the Chain model (Sudo et al. , 2001). 
In the prior work on extraction pattern acquisition, the representation model of the patterns was based on a fixed set of pattern templates (Riloff, 1996), or predicate-argument relations, such as subject-verb, and object-verb (Yangarber et al. , 2000). 
3Yangarber refers this as a noun phrase pattern in (Yangarber et al. , 2000). 
There are many existing works on obtaining extraction patterns for pre-defined relations (Riloff, 1996; Yangarber et al. , 2000; Agichtein and Gravano, 2000; Sudo et al. , 2003). 
