As for other retrieval tasks, when creating a document categorization system, we did gain some benefits when weighting terms found in headlines and leading text in news documents a bit higher (Wasson, 2000), but that effect is limited to news data.


Neither of these were evaluated from multiple user perspectives, although in the case of Wasson (2000) the original project goal was to identify and categorize only highly relevant documents 8 Conclusion Customers of online services approach their information seeking tasks from many perspectives, and yet most IR evaluations are conducted from a single user perspective.


