1 Introduction The recent great advances in speech and language technologies have made it possible to build fully implemented spoken dialogue systems (Aust et al. , 1995; Allen et al. , 1996; Zue et al. , 2000; Walker et al. , 2000). 
(2000b) aim at detecting problems at the utterance level, based on data obtained with AT&Ts How May I Help You (HMIHY) system (Gorin et al. 1997). 
Many researchers have tackled this problem by developing ASR confidence measures based on utterance-level information and dialogue-level information (Litman et al., 1999; Walker et al., 2000). 
In addition, previous research (Litman, Walker, and Kearns 1999; Walker et al. 2000) has shown that features of the dialogue as a whole and features of more local context can be helpful in predicting problematic dialogues. 
This sort of How may I help you? system is easily within current dialogue system expertise (Walkeret al. , 2000),buthas notseen widespreadcommercial deployment. 
