Most NLP systems capable of semantic analysis employ representational formalisms with ties to classical logic, including semantic grammars (Friedman et al. , 1994), unificationbased semantics (Moore, 1989), and description logics (Romacker and Hahn, 2000).


P  -I deliver-recipient spcc\[ificr\] /I l, :  ~ L Figure 3: Relating Grammatical (left box) and Conceptual I(nowledge (right box) each lexical ambiguity is processed independent.ly within set)arate (:ontext partitions of the km)wledge base (Romacker and Hahn, 2000a).


