The large size of this list contributed significantly to the NERs resulting accuracy and compares favourably with previously compiled lists (Stevenson and Gaizauskas, 2000).


Our approach has points of similarity to the methods described by Stevenson and Gaizauskas (2000), who suggest matching text against name dictionaries, filtering out names that are also common words or appear as non-names in high proportion in the training data.


