J04-4001:1	44:256	We regard Chengs (2000) work on the interaction of centering preferences and aggregation in text planning as complementary to our enterprise.
---------------------------------------------------
J04-4001:2	113:256	A possible future development is to supplement our CT-based text planner with a more sophisticated pronominalization algorithm as proposed by Henschel, Cheng, and Poesio (2000) or Callaway and Lester (2002).
---------------------------------------------------
J04-4001:3	21:256	Previous algorithms for pronominalization such as those of McCoy and Strube (1999), Henschel, Cheng, and Poesio (2000), and Callaway and Lester (2002) have addressed the task of deciding whether to realize an entity as a pronoun on the basis of given factors such as its syntactic role and discourse history within a given text structure; what is essentially novel in our approach is that we treat referential coherence as a planning problem, on the assumption that obtaining a favorable ordering of clauses, and of arguments within clauses, is likely to increase opportunities for nonambiguous pronoun use.
---------------------------------------------------
W00-1411:4	72:183	With a few exceptions (e.g. , Mittal et al 1998, Kibble 1999, Kibble and Power 1999, Cheng 2000) NLG researchers have interpreted CT as a theory of pronominalisation only (e.g. , Dale 1992).
---------------------------------------------------
