Ando and Lees (2000) kanji segmenter.)


However, to compare with related work, we will also adopt boundary F-measure Fb = 2RbPb=(Rb + Pb), where the boundary recall Rb and boundary precision Pb are, respectively, the proportions of the correctly recognized boundaries to all boundaries in the goldstandard and a segmenters output (Ando and Lee, 2000).


We also discussed an intuitive algorithm for Japanese segmentation drawn from one of my own recent research collaborations (Ando and Lee, 2000), and how word statistics were applied to determining the authorship of the Federalist Papers (Mosteller and Wallace, 1984).


Some works are based on in-word branching frequencies formulated in an original evaluation function, as in (Ando and Lee, 2000) (boundary precision=84.5%,recall=78.0%, tested on 12500 Japanese ideogram words).


These scoresarealsoutilized especially in previous works on unsupervised segmentation (Ando and Lee, 2000) (Sun et al. , 1998).


