Answer extraction based on grammatical information is also promoted by the system described in (Clarke et al. , 2000). 
For a system based on language models, a feature exclusion approach is used to re-train the models, excluding features related to the case information [Kubala et al. 1998] [Miller et al. 2000] [Palmer et al. 2000]. 
This approach was adopted in (Kupiec, 1993; Abney et al. , 2000; Cardie et al. , 2000; Moldovan et al. , 2000). 
If the expected answer types are typical named entities, information extraction engines (Bikel et al. 1999, Srihari and Li 2000) are used to extract candidate answers. 
We have also implemented the traditional NE-retraining approach proposed by [Kubala et al. 1998] [Miller et al. 2000] [Palmer et al. 2000] and the re-trained NE model leads to 3 In fact, positive effects are observed in some cases. 
