In the disambiguation of capitalized words, the most widespread method is POS tagging, which achieves about a 3% error rate on the Brown corpus and a 5% error rate on the WSJ corpus, as reported in Mikheev (2000).


This is where robust syntactic systems like SATZ (Palmer and Hearst 1997) or the POS tagger reported in Mikheev (2000), which do not heavily rely on word capitalization and are not sensitive to document length, have an advantage.


Unlike other POS taggers, this POS tagger (Mikheev 2000) was also trained to disambiguate sentence boundaries.


Mikheev (2000, 2002) describes the combination of a trigram tagger with his document-centered approach to abbreviation detection and proper name identification.


However, this list of features has already given good performance, comparing favorably with previous approaches (see (Reynar and Ratnaparkhi, 1997; Mikheev, 2000) and references therein).


