We can also remark that our results are not in contradiction with the claims of (Nederhof and Satta, 2000) in which they argue that Earley algorithm and related standard parsing techniques [.


Second, our method as a whole clearly does not process the input text from left-to-right and thus does not enter in the categories studied in (Nederhof and Satta, 2000).


This reputation is not only based upon experimental results (van Noord, 1997) but also upon mathematical arguments in (Nederhof and Satta, 2000).


