This approach has been used in several systems, CommandTalk (Moore et al. 1997), RIALIST PSA simulator (Rayner et al. 2000), WITAS (Lemon et al. 2001), and SETHIVoice (Gauthron and Colineau 1999).


The statistical approach is unworkable in such cases for both the commercial developers and for some research systems (Moore et al. 1997, Rayner et al. 2000, Lemon et al. 2001, Gauthron and Colineau 1999).


3 Architecture This spoken dialogue system shares a common architecture with several prior systems: CommandTalk (Stent et al. , 1999), PSA (Rayner et al. , 2000), WITAS (Lemon et al. , 2001), and the Intelligent Procedure Assistant (Aist et al. , 2002).


