 interpretation of the input query, including parsing and semantic disambiguation, semantic interpretation and transformation of the query to an intermediary logical form (Hendrix et al. , 1978; Zhang et al. , 1999; Tang and Mooney, 2001; Popescu et al. , 2003; Kate et al. , 2005);  translation to a database query language (Lowden et al. , 1991; Androutsopoulos, 1992);  portability (Templeton and Burger, 1983; Kaplan, 1984; Hafner and Godden, 1985; Androutsopoulos et al. , 1993; Popescu et al. , 2003) In order to recover from errors in any either of these steps, most advanced NLIDB systems will also incorporate some sort of cooperative user feedback module that will inform the user of the inability of the system to construct their query and ask for clarification.


So now the time has come to show the open problems and what we have learned as did the EUFID group when they accomplished their system (Templeton, Burger 1983).


Most of the problems listed by Robert Moore at ACL-82 (Moore 1982) fall into this class, as do many of those identified by, for example, Templeton and Burger (1983).


