J83-3003:1	100:696	The EPISTLE project (Jensen and Heidorn 1983, Miller et al. 1981) employs this alternative for grammatical violations.
---------------------------------------------------
J83-3003:2	101:696	DYPAR (Carbonell et al. 1983) has taken this approach in an interface to an expert system.
---------------------------------------------------
A83-1014:3	25:82	Application area and responding to ill-formedness Ill-formedness processing has been examined in many ~pplication areas, including data base access (Hendrix, et al. , 1978), building a data base (Marsh, 1983), grammar checking (Jensen and Heidorn, 1983),.
---------------------------------------------------
A83-1014:4	26:82	generating well-formed messages from ill-formed and incomplete ones (Granger, et al. , 1983) and intelligent computer-assisted language instruction (Weiachedel, et al. , 1978).
---------------------------------------------------
