Other technologies such as lexical-transfer MT (Nirenburg et al. , 1995; Frederking and Brown, 1996; MacDonald, 1963), and Example-Based MT (EBMT) (Brown, 1996; Na61 gao, 1984: Sato and Nagao, 1990) provide lowerquality general-purpose translations, unless they are incorporated into human-assisted MT systems (Frederking et al. , 1993; Melby, 1983), but can be used in non-domain-restricted translation applications.


