at which point the user might say the dept of Bob is equal to the dept of Jill 10, Related Work Some of the systems which, like TELI, seek to provide for user customization within the context of database query are ASK (Thompson and Thompson 1983, 1985), formerly REL (Thompson and Thompson, 1975), from Caltech; INTELLECT, formerly Robot (Harris, 1977), marketed by Artificial Intelligence Corporation; IRUS (Bates and Bobrow, 1983; Bates, Moser, and Stallard 1984), from BBN Laboratories; TQA (Damerau, 1985), formerly REQUEST (Plath, 1976), from IBM Yorktown Heights; TEAM (Martin et al, 1983; Grosz et al, 1985), from SRI International; and USL (Lehmann, 1978), from IBM Heidleberg.


Accordingly, prototype systems that permit user customizations or rapid customizations by a designer have included REL, POL and ASK (Thompson and Thompson 1975, 1981, 1983), CONSUL (Mark 1981; Wilczynski 1981), IRUS (Bates and Bobrow 1983), KLAUS (Haas and Hendrix 1980), TEAM (Hendrix and Lewis 1981; Grosz 1983), a system developed at Bell Labs (Ginsparg 1983), and our own LDC system (Ballard 1982, 1984; Ballard and 1 This research was supported in part by the National Science Foundation under Grant Numbers MCS-81-16607 and IST-83-01994 and in part by the Air Force Office of Scientific Research under Grant Number 81-0221.


Some of the systems which, like TEL1, seek to provide for user customization within the context of database query are ASK (Thompson and Thompson 1983, 1985).


Thompson and Thompson, 1975, 1983, 1985; Johnson, 1985).


