(1981), Bennett (1982), and Slocum (1983, 1984, 1985) present more details about the METAL system.


Related Work The parsing approach closest in spirit to our fitting procedure is that described in Slocum (1983, p. 170): the LRC Machine Translation System uses a "shortest path" technique to construct a "phrasal analysis" of ungrammatical input.


Likewise, it is funny to see practical implementation considerations brought to bear in defending TG against the phrase structure backlash, when (a) no formalized version of modern TG exists, let alone being available for implementation, and (b) large phrase structure grammars.are being implemented on computers and shown to run very fast (see e.g. Slocum 1983, who reports an all-paths, bottom-up parser actually running in linear time using a CFPSG with 400 rules and i0,000 lexical entries).


