1 The purpose of the experiment was to test the usefulness of our proposed system and to gather data for the designers of the natural language processor we planned to implement (Biermann et al. 1983).


Computational Linguistics Volume 10, Number 2, April-June 1984 85 Bruce W. Ballard and Nancy L. Tinkham A Phrase-Structured Grammatical Framework for Transportable NLP Since the problem of mis-recognitions is especially troublesome in our projected voice-input environment (Biermann et al. 1983), this distinction can be important.


