Application area and responding to ill-formedness Ill-formedness processing has been examined in many ~pplication areas, including data base access (Hendrix, et al. , 1978), building a data base (Marsh, 1983), grammar checking (Jensen and Heidorn, 1983),.


Examples of sublanguages that have been studied are weather reports (Chevalier et al. 1978), aircraft maintenance manuals (Lehrberger 1983), medical reports (Hirschman and Sager 1983), and equipment failure reports (Marsh, Hamburger, and Grishman 1984).


We used the NYU Linguistic String Project medical grammar, which is a modification of the Linguistic String Project English grammar including the sentence fragments and other constructs (such as descriptions of medication dosages) that appear in medical reports but not in standard English (Marsh 1983).


