Part-of-speech tagging systems have used either a statistical approach where a large corpora has been used to train a probabilistic model which then has been used to tag new text, assigning the most likely tag for a given word in a given context (e.g. , Church (1988), Cutting et al. 
Previous Works Church (1988) proposes a part of speech tagger and a simple noun phrase extractor. 
Methods using the short context of a word in order to resolve ambiguity (usually categorical ambiguity) are very common in English and other languages (DeRose 1988; Church 1988; Karlsson 1990). 
This method is commonly used for part-of-speech tagging (Church, 1988). 
In the statistical approach a hand tagged corpus is used to train a probabilistic model which is then used to select the best tags in unseen text (Church, 1988; Hakkani-Tcurrency1ur et al. , 2002). 
