A92-1015:1	79:306	The system presented here employs a correction mechanism based on both a variation of trigram analysis (Angell et al. , 1983) and triphone analysis (Van Berkel and De Smedt, 1988), extended with a scoring and ranking mechanism.
---------------------------------------------------
A00-1035:2	36:151	The algorithm used is based on trigram and triphone analysis (van Berkel and Smedt, 1988), and takes into account the orthographic strings corresponding to the invalid word under consideration and its possible replacement, as well as the phonetic representations of the same two words.
---------------------------------------------------
C88-1028:3	189:231	Spelling Error Correction A spelling error correction algorithm based on the idea that people write what they heat' if they do not know the spelling of a word has teen developed by Van Berkel /Van Berkel and De Smedt, 1988/.
---------------------------------------------------
P92-1021:4	99:153	Other work (e.g. Veronis, 1988, Emirkanian and Bouchard, 1988, van Berkel and De Smedt, 1988) emphasizes the former, often on the grounds that competence errors are both harder for the user to correct and tend to make a worse impression on a human reader.
---------------------------------------------------
