This approach produces an effect similar to Bear and Hobbs (1988), only without requiring special mechanisms.


(v=, v)fo~Cy, =) ~ --(=, y) Syntactic Ambiguity: Some of the most common types of syntactic ambiguity, including prepositional phrase and other attachment ambiguities and very compound nominal ambiguities, can be converted into constrained coreference problems (see Bear and Hobbs, 1988).


This formalism, used in the implementation of TACITUS (Hobbs, 1986-2), accommodates a large variety of discourse inferences and, moreover, provides an elegant manner of localizing ambiguities, as was shown in (Bear and Hobbs, 1988).


