Within the taxonomy of normal forms .(NF) defreed by relational data base theo~, dictionary entries are 'unnormalized relations in which attributes can contain other relations, rather than simple scalar values; LDB's, therefore, cannot be correctly viewed as relational data bases (see Neff et al. , 1988).


Fox et al. 1988).


Fox \[1980, 1988\], Nutter et al. \[1988\] and Wang et al. \[1985\] have used thesaurus information to improve the results of an information retrieval system.


3 Entries for Phrases We have been concerned for several years with the design of entries for phrases; it seems apparent that we need to record the same kind of information for phrases as for single word entries and that they are involved in the same lexical relations as other words and more besides \[Markowitz et al. 1988; Ahlswede et al. 1988\].


