domain (Catach 1984; Danlos et al. 1986; Koskenniemi 1983; Laporte 1988; Ritchle et al. 1987, Tufts 1989; V6ronls 1988) are based on the availability of local rules whose combination, either through direct interpretation or by being compiled, form the target transducer.


For example, the grapheme-to-phoneme transcription may recognize the original language of a word while translating It (Oshlka et al. 1988): the "French" nouns "meeting" and "carpacclo" have kept respectively their original English and Italian form II1 and pronunciation, etc. The learned automaton is symmetrical, thus it Is also reversible.


