First, the projects: we received requests for information from NIA' projects such as the experimental English-toGerman machine translation system I,MT /McCord 1988/, the natural language data hase query project TQA/Damerau et al. 1982, Johnson 1984/, the kind-types Knowledge Representation system KT /Dahlgrcn and McDowell 1986/, and others.


IJltimately, COMPLEX structures will be placed in a lx~xieal Data Base so they can be queried by the Ivxical Query Language /Nell" et al. 1988/.


Research efforts at IBM \[Chodorow, et al. 1988; Neff, et al. 1989\], Bell Labs \[Church, et al. 1989\], New Mexico State University \[Wilks 1987\], and elsewhere have used mechanical processing of on-line dictionaries to infer at least minimal syntactic and semantic information from dictionary definitions.


