These include the availability of efficient and high precision word segmentation methods for Chinese text \[Chang et al. , 1991; Sproat and Shih, 1990; Wang et al. , 1990\], the availability of statistical analysis of a Chinese corpus \[Liu et al. , 1975\] and large-scale electronic Chinese dictionaries with partof-speech information \[Chang et al. , 1988; BDC, 1992\], the corpus-based statistical part-of-speech tagger \[Church, 1988; DeRose, 1988; Beale, 1988\], as well as phrasal and clausal analyzers \[Church 1988; Ejerhed 1990\] 2.


At about the same time, Ejerhed (1988), working with Church, performed comparisons between finite state methods and Church's stochastic models for identifying both non-recursive clauses and non-recursive NPs in English text.


