Though syntactic input can of course be added (e.g. Hurum 1988), doing so amounts to an admission that the translation was premature.


al. 1987, Moran 1988, and Hurum 1988).


See e.g. van Lehn (1978), Woods (1978), Allen (1987), Hurum (1988), Moran (1988).


Since then, most work on disambiguation has focused on syntactic clues for determining which readings of an ambiguous statement are possible, and of the set of possible readings, which ones are preferred (Van Lehn, 1978; Hobbs and Shieber, 1987; Poesio, 1993a; Hurum, 1988; Moran, 1988).


