on Applied NLP (1988) Newman, P. "Symmetric Slot Grammar", to appear in Proe 3rd Intn'l Conf on 7'heoretieal and Methodological Issues in Machine 7>anslation of Natural Languages June 1990 Pollard, C. and 1.


The preferential ordering rules are used in the analysis phase to detect textual features, and are applied after a postparse disambiguation analysis (based on a heuristic search algorithm described in (Newman 1988)).


