The coding subsystem of Slocum (1988) is represented by the so-called paradigm matrix of Humor systems. 
In addition to the well-known two-level morphology (Koskenniemi 1983) and its modifications (Karttunen 1993) it is worth mentioning the Nabu system (Slocum 1988). 
Applying a rule "in reverse" means that the word is matched 3This class matching is equivalent"alphabet subsets" in KIMMO \[Karttunen et al. , 1983\], "restricted variables" in NABU \[Slocum, 1988\], and "sla'ing vats" in DIMORPH \[Gibson, 1991\]. 
DESIGN PHILOSOPHY OF HUMOR Several philosophical commitments regarding the NLP systems are summarized in Slocum (1988). 
Besides the well-known two-level morphology (Koskenniemi 1983) and its modifications (Katlttmen 1985, 1993) we mention the Nabu system (Slocum 1988). 
