These tools are: the Lexical Database for Basque (EDBL) (Agirre et al. , 1994), the morphological analyser based on the Two-Level Morphology (Agirre et al. , 1992), the lemmatiser (Aldezabal et al. , 1994) and some parts of the Constraint Grammar for Basque (Alegria et al. , 1996) (Karlsson et hi.


It has been estimated that nouns may mathematically have even 458,683 inflected forms in Basque language, taking into account two levels .of recursion, (Agirre et al. , 1992).


