W94-0324:1	362:448	pages 72-79, ACL, Trento, Italy, 1992 \[Fawcett et al. , 1988\] Robin P. Fawcett, Anita van der Mije, and Carla van Wissen.
---------------------------------------------------
P96-1037:2	8:203	In the implemented voice dialogue system "The Circuit Fix-it Shop" (Smith et al. , 1992; Smith and Hipp, 1995), the dialogue fragment given in Figure 1 occurs between a human user and a computer collaborator.
---------------------------------------------------
