The knowledge based methods are morphosyntactic processing \[Basili et al, 1992b\] and some shallow level of semantic categorisation. 
(Basili et al. 1992 b) R. Basili, M. T. Pazienza, P. Velardi, (1992), Computational Lexicons: the neat examples and the odd exemplars, Prec. 
Semantic tags are assigned from on-line thesaura like WordNet (Basili et al, 1996) (Resnik, 1995), Roget's categories (Yarowsky 1992) (Chen and Chen, 1996), the Japanese BGH (Utsuro et al, 1993), or assigned manually (Basili et al, 1992) 1. 
However, it is very difficult to gather sufficient co-occurrences to calculate similarities reliably \[Resnik, 1992; Basili et al. , 1992\]. 
20 References \[Basili et al. , 1992\] Basili, R. , Pazienza, M. , and Velardi, P. Computational lexicons: The neat examples and the odd exemplars. 
