A97-1052:1	130:163	We randomly selected a test set of 250 in-coverage sentences (of lengths 3-56 tokens, mean 18.2) from the Susanne treebank, retagged with possibly multiple tags per word, and measured the 'baseline' accuracy of the unlexicalized parser on the sentences using the now standard PARSEVAL/GEIG evaluation metrics of mean crossing brackets per sentence and (unlabelled) bracket recall and precision (e.g. Grishman et al. , 1992); see figure 65.
---------------------------------------------------
A00-2032:2	102:159	The first, a crossing bracket, is a proposed bracket that overlaps but is not contained within an annotation bracket (Grishman et al. , 1992).
---------------------------------------------------
W05-0211:3	33:173	The former has its roots in the Grammar Evaluation Interest Group (GEIG) scheme (Grishman et al. , 1992) developed to compare parsers with dierent underlying grammatical formalisms.
---------------------------------------------------
