Zero pronoun resolution for machine translation reported by Nakaiwa and Ikehara (Nakaiwa and Ikehara, 1992) used only semantic attributes of verbs in a restricted domain.


To overcome these kinds of problems, several methods to resolve zero pronouns which consider applications for a practical machine translation system with an unlimited translation target area, have been proposed (Nakaiwa and Ikehara, 1992; Nakaiwa and Ikehara, 1995; Nakaiwa and Ikehara, 1996).


Regarding type (b), Nakaiwa and Ikehara (1992) proposed a method to determine the intersentential antecedents us-ing verbal semantic attributes.


127 To overcome these kinds of problems, several methods to resolve zero pronouns which consider appl/cations for a practical machine translation system with an n~\]imJted translation target area, have been proposed (Nakaiwa and Ikehara, 1992; Nakaiwa and Ikehara, 1995; Nakalwa and Ikehara, 1996).


