The limitations of these simple models have been discussed at length, and more complex models have been proposed (Kelleher, 2003; Schmidtke, 2001; Crawford et al. , 2000; Matsakis and Wendling, 1999; Fuhr et al. , 1995; Abella and Kender, 1993; Wazinski, 1992).


We can refer not only to features of an object in a scene, but also to tidal ures of the graphical model, Ihcir interprclalion ~md to the position of picture objects within the picture, scc ~dso (Wazinski, 1992).


