P98-1010:1	167:194	4 Related Work Two previous methods for learning local syntactic patterns follow the transformation-based paradigm introduced by Brill (1992).
---------------------------------------------------
P97-1030:2	13:188	1 Introduction The last few years have seen the great success of stochastic part-of-speech (POS) taggers (Church, 1988: Kupiec, 1992; Charniak et M. , 1993; Brill, 1992; Nagata, 1994).
---------------------------------------------------
P98-1063:3	59:137	, 1992), at least when applied to English, but when we try to apply them to Basque we encounter additional problems; on the other hand, some rule-based systems (Brill, 1992; Voutilainen et aL, 1992) are at least as good as statistical systems and are better adapted to free-order languages and agglutinative languages.
---------------------------------------------------
W04-0810:4	38:93	As part of this step, sentences were preprocessed: tokenized (separating punctuation from words) using the Penn Treebank guidelines, tagged with Brills tagger (Brill, 1992) and then parsed with Collins statistical parser (Collins, 1996).
---------------------------------------------------
J98-1005:5	81:530	We restrict the test to senses within a single part of speech to focus the work on the harder part of the disambiguation problem--the accuracy of simple stochastic part-of-speech taggers such as Brill's (Brill 1992) suggests that distinguishing among senses with different parts of speech can readily be accomplished.
---------------------------------------------------
C00-2156:6	69:116	However, wc invented novel way of using the decision tree as trmlsibrmation-t)ased rule induction (Brill, 1992).
---------------------------------------------------
C00-1032:7	81:123	We used 1;t5(; Brill t)a.rt-ofSt)ee(:h Tagger (Brill, 1992) trained for l,en(:h by (Le(:olntc~ and Pm'out)ek, 1996)) and the lelmnatizer (h> veh)ped t)y F. Na.mer (\[Ibussaint et M. , 1998).
---------------------------------------------------
I08-2130:8	10:148	Rule based POS tagging methods extratct rules from training corpus and use these rules to tag new sentences(Brill, 1992)(Brill, 1994).
---------------------------------------------------
P96-1048:9	62:78	The tagger we use is the one developped by Eric Brill (Brill, 1992) with a set of tags indicating the grammatical categories as well as other information such as the number and the gender for nouns and adjectives.
---------------------------------------------------
C96-2105:10	7:158	Phonological rewrite-rules (Kaplan and Kay, 1994), two-level rules (Koskenniemi 1983), syntactic disarnbiguation rules (Kar\]sson et al 1994, Koskenniemi, Tapanainen, and Voutilainen 1992), and part-of-speech assignment rules (Brill 1992, Roche and Schabes 1995) are examples of replacement in context of finite-state grammars.
---------------------------------------------------
P96-1050:11	42:118	On-line lists can quickly provide useful features such as cities, family names, nationalities, etc. Proven POS taggers (Farwell et al. , 1994; Brill, 1992; Matsumoto et al. , 1992) predetermine POS features.
---------------------------------------------------
P98-2228:12	36:113	3.1 Preprocessing Before the filters or partial taggers are applied the text is tokenised, lemmatised, split into sentences and part-of-speech tagged using the Brill part-ofspeech tagger (Brill, 1992).
---------------------------------------------------
A00-1013:13	54:156	1.1.1 The syntactic analysis component We used Eric Brill's rule-based word tagger (1992, 1994a, 1994b), the de facto state of the art tagging system, to break the questions down into part-ofspeech categories.
---------------------------------------------------
C96-1041:14	12:246	'\['here are three main approaches in tagging problem: rule-based approach (Klein and Simmons 1%3; Brodda 1982; Paulussen and Martin 1992; Brill et al. 1990), statistical approach (Church :1988; Merialdo 1994; Foster 1991; Weischedel et al. 1993; Kupiec 1992) and connectionist approach (Benello et al. 1989; Nakanmra et al. 1989).
---------------------------------------------------
W03-1308:15	66:124	Following on from previous studies in named entity we chose a set of linguistically motivated wordlevel features that include surface word forms, part of speech tags using the Brill tagger (Brill, 1992) and orthographic features.
---------------------------------------------------
P09-1086:16	68:176	This in turn was adapted from the general-purpose algorithm introduced by Brill (1992).
---------------------------------------------------
P09-1086:17	41:176	2 Transformation-Based Learning Brills tagger introduced the concept of Transformation-Based Learning (TBL) (Brill, 1992).
---------------------------------------------------
A00-1040:18	51:167	Part of speech tagger The text is the part of speech tagged using the Brill tagger (Brill, 1992).
---------------------------------------------------
W05-1308:19	39:62	Information extraction from free-text utilizes shallow-parsing techniques (Daelemans, Buchholz et al. 1999), Parts-of-Speech tagging(Brill 1992), noun and verb phrase chunking (Mikheev and Finch 1997), verb subject and object relationships (Daelemans, Buchholz et al. 1999), and learned (Califf and Mooney 1998; Craven and Kumlein 1999; Seymore, McCallum et al. 1999) or hand-build patterns to automate the creation of specialized databases.
---------------------------------------------------
P03-2002:20	46:186	To gather these candidates we used the Brill transformational tagger (Brill, 1992) for the part-ofspeech step and the CASS partial parser for the parsing step (Abney, 1994).
---------------------------------------------------
C02-1085:21	127:211	All 15,863 documents were tagged by a part-of-speech tagger(Brill, 1992) and stemmed using WordNet information(Fellbaum, 1998).
---------------------------------------------------
C00-1046:22	7:140	M~tior works done to create English POS taggers (henceforth, "taggers"), for example, include (Church 1988), (Kupicc 1992), (Brill 1992)and (Voutilaincn et al. 1992).
---------------------------------------------------
W05-1303:23	22:264	After training on hand-tagged sentences from biomedical text, it applies a Brill-style tagger (Brill, 1992) and manually generated postprocessing rules.
---------------------------------------------------
P96-1006:24	29:198	Making such an assumption is reasonable since POS taggers that can achieve accuracy of 96% are readily available to assign POS to unrestricted English sentences (Brill, 1992; Cutting et al. , 1992).
---------------------------------------------------
W98-1110:25	137:167	The training is leveraged (Brill, 1992) so the error-correcting rules are gradually learned as the statistical tagged texts are corrected by the rules learned so far.
---------------------------------------------------
W98-1110:26	88:167	The error-corrector is a rule-based transformer (Brill, 1992), and it corrects the mis-tagged morphemes by considering the lexical patterns and the necessary contextual information.
---------------------------------------------------
W98-1110:27	29:167	performance is usually no better than the statistical counterparts (Brill, 1992).
---------------------------------------------------
W98-1110:28	122:167	Instead, we adopted Brill's approach (Brill, 1992) to auto.
---------------------------------------------------
E95-1022:29	30:171	157 ena or the linguist's abstraction capabilities (e.g. knowledge about what is relevant in the context), they tend to reach a 95-97% accuracy in the analysis of several languages, in particular English (Marshall 1983; Black et aL 1992; Church 1988; Cutting et al. 1992; de Marcken 1990; DeRose 1988; Hindle 1989; Merialdo 1994; Weischedel et al. 1993; Brill 1992; Samuelsson 1994; Eineborg and Gamb~ick 1994, etc.).
---------------------------------------------------
E95-1022:30	17:171	Corpus-based information can be represented e.g. as neural networks (Eineborg and Gamb/~c k 1994; Schmid 1994), local rules (Brill 1992), or collocational matrices (Garside 1987).
---------------------------------------------------
W01-1015:31	2:166	Universidad 30 Legans 28911, Madrid, Spain pmf@inf.uc3m.es G47G88G76G86G3G53G82G71G85G76G74G82 ISYS Group AI Department Technical University of Madrid Boadilla del Monte, 28660 Madrid, Spain lrodrigo@isys.dia.fi.upm.es G36G69G86G87G85G68G70G87 This paper presents the adaptation and customization of two lexical resources: Brill tagger, Brill (1992), and EuroWordNet, Vossen et al.
---------------------------------------------------
W01-1015:32	95:166	This has been carried out considering the information in Brill (1992), Brill (1994) and Brill (1995), taken as a reference starting point.
---------------------------------------------------
W01-1015:33	59:166	G23G3 G36G71G68G83G87G76G81G74G3G37G85G76G79G79G3G55G68G74G74G72G85 The Brill tagger, Brill (1992), is a rule-based part of speech tagger programmed in Perl for English language.
---------------------------------------------------
W01-1015:34	19:166	At current state two linguistic resources have been analyzed and adapted in order to be incorporated into the ADVICE project: Brill tagger, Brill (1992), and EuroWordNet, Vossen et al.
---------------------------------------------------
W97-0208:35	90:113	The text is tagged using the Brill tagger (Brill, 1992) and a translation is carried out using a manually defined mapping from the syntactic tags assigned by Briil (Penn Tree Bank tags (Marcus, Santorini, and Marcinkiewicz, 1993)) onto the simpler part-of-speech categories associated with LDOCE senses.
---------------------------------------------------
W97-0208:36	70:113	Simmulated annealing, a numerical optimisation algorithm, was used to make this process practical (Cowie, Guthrie, and Guthri~, 1992), choosing an assignment of senses from as many as 10 l choices.
---------------------------------------------------
W97-0104:37	178:235	IB \[Bri92\] Eric Briil (1992).
---------------------------------------------------
C96-1069:38	111:171	4.1 Data The training tort)us we have used ix the 1988, 1!)89 WSJ ill ACL/DCI CD-IOM whi(.h ('onsists of al)out 280,000 1)art-of-spee('h tagged sentences (Brill, 1992).
---------------------------------------------------
C04-1080:39	30:115	Derived from his supervised transformation-based tagger (Brill, 1992), UTBL uses information from the distribution of unambiguously tagged data to make informed labeling decisions in ambiguous contexts.
---------------------------------------------------
C04-1080:40	52:115	4 Unsupervised Tagging: A Comparison 4.1 Corpora and Lexicon Construction For our comparison of unsupervised tagging methods, we implemented the HMM taggers described in Merialdo (1991) and Kupiec (1992), as well as the UTBL tagger described in Brill (1995).
---------------------------------------------------
P98-1081:41	8:162	Recent work (e.g. Brill 1992) has demonstrated clearly that this categorization is in fact a mix-up of two distinct Categorization systems: on the one hand there is the representation used for the language model (rules, Markov model, neural net, case base, etc).
---------------------------------------------------
P08-1087:42	106:143	When needed, part-of-speech (POS) tags were acquired by using Brills tagger (Brill, 1992) on v1.14.
---------------------------------------------------
A00-1020:43	141:217	The English texts were parsed with Brill's part-ofspeech tagger (Brill 1992) and the noun phrases were identified by the grammar rules implemented in the phrasal parser of FASTUS (Appelt et al. , 1993).
---------------------------------------------------
W96-0203:44	23:240	(Brill and Resnik, 1994) use transformationbased error-driven learning (Brill, 1992) to derive disambiguation rules based on simple context information (e.g. right and left adjacent words or POSs).
---------------------------------------------------
W03-0613:45	52:187	We split the returned documents into classes encompassing n-grams (terms of word length n), adjectives (using a part-of-speech tagger (Brill, 1992)) and noun phrases (using a lexical chunker (Ramshaw and Marcus, 1995)).
---------------------------------------------------
W09-1707:46	91:163	The CONLL 2000 tags against which we measure our own results are in fact assigned by the Brill tagger (Brill 1992), and while these may not correlate perfectly with those that would have been assigned by a human linguist, we believe that the correlation is likely to be good enough to allow for an informative evaluation of our method.
---------------------------------------------------
C96-2192:47	18:98	(Brodda 1982; Karlsson 1990; Koskennienfi 1990; Brill 1992).
---------------------------------------------------
P96-1018:48	70:249	2We use in this phase the JUMAN morphological analyzing system (Kurohashi et al. , 1994) for tagging Japanese texts and Brill's transformation-based tagger (Brill, 1992; Brill, 1994) for tagging English texts (JUMAN: ftp://ftp.aist-nara.ac.jp/pub/nlp/tools/juman/ Brih ftp://ftp.cs.jhu.edu/pub/brill).
---------------------------------------------------
C02-1161:49	124:181	a0 Tagging accuracy  manually-corrected tagging versus automatic PoS tagging (Brill, 1992), which tagged correctly 84% of the queries.
---------------------------------------------------
C02-1161:50	36:181	Syntactic information for each query was obtained from Brills part-of-speech (PoS) tagger (Brill, 1992).
---------------------------------------------------
W97-0202:51	75:153	A simple example is the richer part-of-speech tags produced by Brill's tagger (1992).
---------------------------------------------------
P97-1059:52	19:219	Among others, it can be composed with transducers that encode:  correction rules for the most frequent tagging errors which are automatically generated (Brill, 1992; Roche and Schabes, 1995) or manually written (Chanod and Tapanainen, 1995), in order to significantly improve tagging accuracy 2.
---------------------------------------------------
P97-1059:53	148:219	These rules can be either extracted automatically from a corpus (Brill, 1992) or written manually (Chanod and Tapanainen, 1995).
---------------------------------------------------
P97-1059:54	170:219	Brill, Eric (1992).
---------------------------------------------------
W96-0102:55	215:379	Compared to learning rule-based approaches such as the one by Brill (1992), a k-nn approach provides a uniform approach for all disambiguation tasks, more flexibility in the engineering of case representations, and a more elegant approach to handling of unknown words (see e.g. Cardie 1994).
---------------------------------------------------
W96-0102:56	21:379	These rules can either be hand-crafted (Garside et al. , 1987; Klein & Simmons, 1963; Green & Rubin, 1971), or learned, as in Hindle (1989) or the transformation-based error-driven approach of Brill (1992).
---------------------------------------------------
P97-1029:57	163:190	This is very similar to Brill's use of contexts to induce transformation rules for his tagger (Brill, 1992; Brill, 1995), but instead of generating transformation rules from a training text, we gather statistics and apply them to parses in the text being disambiguated.
---------------------------------------------------
P97-1029:58	7:190	There has been a large number of studies in tagging and morphological disambiguation using various techniques such as statistical techniques, e.g., (Church, 1988; Cutting et al. , 1992; DeRose, 1988), constraint-based techniques (Karlsson et al. , 1995; Voutilainen, 1995b; Voutilainen, Heikkil/i, and Anttila, 1992; Voutilainen and Tapanainen, 1993; Oflazer and KuruSz, 1994; Oflazer and Till 1996) and transformation-based techniques (Brilt, 1992; Brill, 1994; Brill, 1995).
---------------------------------------------------
W05-0207:59	33:166	Our approach identi es useful linguistic information without incurring the computational cost of full text parsing; it uses context-free grammars to perform highlevel syntactic analysis of part-of-speech tagged text (Brill, 1992).
---------------------------------------------------
W00-1107:60	121:270	Currently, the Brill Tagger (Brill, 1992) (with minor postprocessing) is used for the part-of-speech (POS) tagging.
---------------------------------------------------
W96-0101:61	11:213	1 Introduction In the part-of-speech hterature, whether taggers are based on a rule-based approach (Klein and Simmons, 1963), (Brill, 1992), (Voutilainen, 1993), or on a statistical one (Bahl and Mercer, 1976), (Leech et al. , 1983), (Merialdo, 1994), (DeRose, 1988), (Church, 1989), (Cutting et al. , 1992), there is a debate as to whether more attention should be paid to lexical probabilities rather than contextual ones.
---------------------------------------------------
J04-3002:62	217:617	Before we continue, there are a few more technical items to mention concerning the data preparation and experimental design:  All of the data sets are stemmed using Karps morphological analyzer (Karp et al. 1994) and part-of-speech tagged using Brills (1992) tagger.
---------------------------------------------------
W00-1104:63	164:284	The part-of-speech tagging task is performed with high accuracy using an improved version of Brill's tagger (Brill, 1992).
---------------------------------------------------
W97-1304:64	89:150	1) Analysis of Japanese and English sentences In this step, I use morphological, syntactic and semantic analyzers of Japanese in ALT-J/E for the analysis of Japanese sentences and Brill's English tagger (Brill, 1992) for the analysis of English sentences ~.
---------------------------------------------------
H01-1039:65	204:251	REFERENCES [1] Brill, Eric (1992).
---------------------------------------------------
W97-0205:66	113:166	3.2 Class-Sensitive Pattern Matching The pattern matcher runs over corpora that are: part-of-speech tagged using a widely used tagger (Brill, 1992); stemmed by using an experimental system that extends the Porter stemmer, a stemming algorithm widely used in information retrieval, with the Celex database on English morphology; (partly) semantically tagged using the CORELEX set of underspecified semantic tags as discussed in the previous section.
---------------------------------------------------
A97-1040:67	113:227	(Brill, 1992).
---------------------------------------------------
E99-1028:68	86:132	6.1 Data The data we have used is 1989 Wall Street Journal (WSJ) in ACL/DCI CD-ROM which consists of 2,878,688 occurrences of part-of-speech tagged words (Brill, 1992).
---------------------------------------------------
C96-1009:69	131:183	Brill's t)art-of-speeeh tagger, (Brill, 1992), was used to remove the ngrams that had an article as their last wor(1.
---------------------------------------------------
J95-2004:70	161:471	6. Tagging Unknown Words The rule-based system described by Brill (1992) contains a module that operates after all known words--that is, words listed in the dictionary--have been tagged with their most frequent tag, and before contextual rules are applied.
---------------------------------------------------
J95-2004:71	16:471	Recently, Brill (1992) described a rule-based tagger that performs as well as taggers based upon probabilistic models and overcomes the limitations common in rule-based approaches to language processing: it is robust and the rules are automatically ac* Mitsubishi Electric Research Laboratories, 201 Broadway, Cambridge, MA 02139.
---------------------------------------------------
J95-2004:72	178:471	All three taggers have approximately the same 5 Our current implementation is functionally equivalent to the tagger as described by Brill (1992).
---------------------------------------------------
J95-2004:73	197:471	7 An extended discussion of the precision of the rule-based tagger can be found in Brill (1992).
---------------------------------------------------
P97-1031:74	205:213	The more similar conditions reported in previous work are those experiments performed on the WSJ corpus: (Brill, 1992) reports 3-4% error rate, and (Daelemans et al. , 1996) report 96.7% accuracy.
---------------------------------------------------
C08-1006:75	178:202	Part of speech tags are assigned by Brills tagger (Brill, 1992).
---------------------------------------------------
A94-1024:76	34:168	Brill (Brill, 1992) has designed a rule-based tagger for English.
---------------------------------------------------
W95-0101:77	27:188	Transformation-based error-driven learning has been applied to a number of natural language problems, including part of speech tagging, prepositional phrase attachment disambiguation, speech generation and syntactic parsing \[Brill, 1992; Brill, 1994; Ramshaw and Marcus, 1994; Roche and Schabes, 1995; Brill and Resnik, 1994; Huang et al. , 1994; Brill, 1993a; Brill, 1993b\].
---------------------------------------------------
A97-1017:78	102:179	3 A RULE-BASED EXPERIMENT FOR CZECH A simple rule-based part of speech (RBPOS) tagger is introduced in (Brill, 1992).
---------------------------------------------------
A97-1017:79	20:179	Given the comparability of the accuracy of the rule-based part-of-speech (POS) tagger (Brill, 1992) with the accuracy of the stochastic tagIThe development of automatic tagging of Czech is/was supported fully or partially by the following grants/projects: Charles University GAUK 39/94, Grant Agency of the Czech Republic GACR 405/96/K214 and Ministry of Education VS96151.
---------------------------------------------------
J01-2002:80	260:621	A tagger generator using this learning method is described in Brill (1992, 1994).
---------------------------------------------------
A00-1012:81	25:173	Part of speech taggers typically require input in the format of a single sentence per line (for example Brill's tagger (Brill, 1992)) and parsers generally aim to produce a tree spanning each sentence.
---------------------------------------------------
D07-1082:82	109:195	In order to extract the linguistic features necessary for the ME model, all sentences containing the target word were automatically partof-speech (POS) tagged using the Brill POS tagger (Brill, 1992).
---------------------------------------------------
I08-1048:83	89:153	In order to extract the linguistic features necessary for the ME model in WSD tasks, all sentences containing the target word are automatically part-ofspeech (POS) tagged using the Brill POS tagger (Brill, 1992).
---------------------------------------------------
W96-0207:84	16:304	Brill (1992; 1994; 1995a) has presented a transformation-based learning approach, which induces rules from tagged corpora.
---------------------------------------------------
W01-1626:85	139:251	All corpora were stemmed (Karp et al. , 1992) and part-of-speech tagged (Brill, 1992).
---------------------------------------------------
W97-0114:86	109:203	(,~oox) \[CASE : case-2 case relation : r~SJECT \[NP : ~1 (Semantic Constraints: HUMAN) 3.2 Analysis of English Sentences The English sentences are analyzed using Brill's English ta~er (Bri\]l, 1992) and partially parsed using the tamed information for each English word.
---------------------------------------------------
P97-1016:87	157:215	5.1 Integration of Rule-Based Part-of-Speech Tagger To accommodate the part-of-speech input to the parser, we have integrated the rule-based part-of-speech tagger, (Brill, 1992), (Brill, 1995), as a preprocessor to the language understanding system TINA, as in Figure 8.
---------------------------------------------------
J95-4004:88	144:404	Part-of-speech tagging is an active area of research; a great deal of work has been done in this area over the past few years (e.g. , Jelinek 1985; Church 1988; Derose 1988; Hindle 1989; DeMarcken 1990; Merialdo 1994; Brill 1992; Black et al. 1992; Cutting et al. 1992; Kupiec 1992; Charniak et al. 1993; Weischedel et al. 1993; Schutze and Singer 1994).
---------------------------------------------------
J95-4004:89	33:404	This algorithm has been applied to a number of natural language problems, including part-of-speech tagging, prepositional phrase attachment disambiguation, and syntactic parsing (Brill 1992; Brill 1993a; Brill 1993b; Brill and Resnik 1994; Brill 1994).
---------------------------------------------------
J95-4004:90	163:404	9 Earlier versions of this work were reported in Brill (1992, 1994).
---------------------------------------------------
J95-4004:91	10:404	A number of part-of-speech taggers are readily available and widely used, all trained and retrainable on text corpora (Church 1988; Cutting et al. 1992; Brill 1992; Weischedel et al. 1993).
---------------------------------------------------
W06-3402:92	76:135	In order to include features describing verb tense, we use Brills part-of-speech tagger (Brill, 1992) . Each part of speech (POS) is taken to be a feature, whose value is a count of the number of occurrences in the given utterance.
---------------------------------------------------
C02-2018:93	48:129	(Brill, 1992)).
---------------------------------------------------
P03-1010:94	81:256	We use Brills tagger (Brill, 1992) to POS-tag the English sentences, extract content words, and use WordNets library7 to obtain lemmas of the words, which consists of Ei.
---------------------------------------------------
W00-0404:95	155:312	A set of 25 target events were defined 2 All documents were tagged by the tagger (Brill, 1992).
---------------------------------------------------
W98-1001:96	35:105	Such methods can achieve better performance, reaching a tagging accuracy of up to 85% on unknown words for English \[Brill 1992; Weischedel et al. , 1993\].
---------------------------------------------------
W09-2403:97	65:153	TBL tagger (Brill, 1992)7, and a TnT-style trigram tagger (Halacsy et al., 2007).8 The baseline was a unigram tagger which selects the most frequentlyoccurring tag of singletons when dealing with unseen words.
---------------------------------------------------
W09-2403:98	55:153	We looked at three di erent lemmatizers: the lemmatizing backend of the XTAG project (XTAG Research Group, 2001)4, Celex (Baayen et al., 1995), and the lemmatizing component of an enhanced TBL tagger (Brill, 1992).5 We then employed a voting system on these three components, taking the lemma from the most individual lemmatizers.
---------------------------------------------------
W01-1011:99	47:172	The noun phrase extraction module uses Brill's POS tagger [Brill (1992)]and a base NP chunker [Ramshaw and Marcus (1995)].
---------------------------------------------------
P07-1071:100	131:200	We trained on the training set of PropBank supplemented with the Brown corpus, resulting in a test accuracy on the test set of PropBank of 96.85% which compares to 96.66% using the Brill tagger (Brill, 1992).
---------------------------------------------------
J95-2001:101	11:410	Rule-based taggers (Brill 1992; Elenius 1990; Jacobs and Zernik 1988; Karlsson 1990; Karlsson et al. 1991; Voutilainen, Heikkila, and Antitila 1992; Voutilainen and Tapanainen 1993) use POS-dependent constraints defined by experienced linguists.
---------------------------------------------------
I08-3015:102	16:172	The rules in a rule-based system are usually difficult to construct and typically are not very robust (Brill, 1992).
---------------------------------------------------
I08-3015:103	14:172	There are many POS taggers developed using different techniques for many major languages such as transformation-based error-driven learning (Brill, 1995), decision trees (Black et al., 1992), Markov model (Cutting et al., 1992), maximum entropy methods (Ratnaparkhi, 1996) etc for English.
---------------------------------------------------
I08-3015:104	18:172	In a stochastic tagger, tens of thousands of lines of statistical information are needed to capture the contextual information (Brill, 1992).
---------------------------------------------------
W06-2201:105	180:237	Infuturework, weplantoidentify such adjectives in Google excerpts using a Part of Speech tagger (Brill, 1992).
---------------------------------------------------
W06-2201:106	48:237	Automated part of speech tagging (Brill, 1992) is a useful technique in term extraction (Frantzi et al. , 2000), a domain closely related to namedentity recognition.
---------------------------------------------------
W98-1205:107	186:205	These rules can either be extracted automatically from a corpus (Brill, 1992) or written manually (Chanod and Tapanalnen, 1995).
---------------------------------------------------
W98-1205:108	15:205	Among others, it can be composed with transducers that encode:  correction rules for the most frequent tagging errors which are automatically generated (Brill, 1992; Roche and Schabes, 1995) or manually written (Chanod and Tapanainen, 1995), in order to significantly improve tagging accuracy -9 . These rules may include long-distance dependencies not handled by ttMM taggers, and can conveniently be expressed by the replace operator (Kaplan and Kay, 1994; Karttunen, 1995; Kempe and Karttunen, 1996).
---------------------------------------------------
I08-2118:109	9:167	Some problems in text mining where rule-based systems have been successfully used are part of speech tagging (Brill, 1992), named entity annotation (Grishman, 1997; Appelt et al., 1995), information extraction (Maynard et al., 2001), question answering (Riloff and Thelen, 2000)andclassification(Hanetal., 2003; Li and Yamanishi, 1999; Sasaki and Kita, 1998).
---------------------------------------------------
W04-0829:110	35:85	Unfortunately, we didnt have the time to finish a collocation detection procedure, we just had enough time to POS-tag the text with the Brill tagger (Brill, 1992) and parse it with the Collins parser (Collins, 1999).
---------------------------------------------------
P06-1050:111	86:216	The lemma of the token is extracted from parse trees generated by the CONTEX parser (Hermjakob and Mooney, 1997) which includes rich context information in parse trees, and the Brill tagger (Brill, 1992) is used for POS tagging.
---------------------------------------------------
A94-1009:112	151:191	Table 3: Baum-Welch patterns (summary) Degradation D0+T0 D0+T1 D2+T0 D2+T1 Corpus relation Same I, I E, E Similar I, E E, E Different E, E E, E C, C C, C C, C C, C C, C C, C References Eric Brill and Mitch Marcus (1992).
---------------------------------------------------
A94-1009:113	30:191	With the availability of large corpora and fast computers, there has been a recent resurgence of interest, and a number of variations on and alter53 natives to the FB, Viterbi and BW algorithms have been tried; see the work of, for example, Church (Church, 1988), Brill (Brill and Marcus, 1992; Brill, 1992), DeRose (DeRose, 1988) and gupiec (Kupiec, 1992).
---------------------------------------------------
A94-1009:114	154:191	Eric Brill (1992).
---------------------------------------------------
C00-1077:115	74:197	Evaluation The SNC-Value method wan initially t(;sted on a eorl)US of 800,000 eye t)athoh)gy reI)ortn, which had 1)een tagged with the Brill t)art-of-nl)eeeh tagger (Brill, 1992).
---------------------------------------------------
