5 Discussion As tar as we know, only one T/L for medical English exists (Paulussen and Martin, 1992), which has recently been adapted to medical Dutch and extended with semantic lal)elling (Maks and Mar-tin, 1996).


For that purpose we use an adapted version of Dilemma (see Martin e.a. 1988 and Paulussen-Martin 1992).


Two main approaches have generally been considered: rule-based (Klein and Simmons 1963; Brodda 1982; Paulussen and Martin 1992; Brill et al. 1990) probabilistic (Bahl and Mercer 1976; Debili 1977; Stolz, Tannenbaum, and Carstensen 1965; Marshall 1983; Leech, Garside, and Atwell 1983; Derouault and Merialdo 1986; DeRose 1988; Church 1989; Beale 1988; Marcken 1990; Merialdo 1991; Cutting et al. 1992).


