See (Bouillon et al. , 1992), (Busa, 1996) for accounts on nominals.


77 1 Introduction The analysis of nominal compound constructions has proven to be a recalcitrant problem for linguistic semantics (Bergsten 1911, Jespersen 1942, Marchand 1970, Lees 1970, Downing 1977, Levi 1978, Warren 1987), and their analysis has presented a serious challenge for natural language processing systems (Finin 1980, McDonald 1982, Isabelle 1984, Alshawi 1987, Hobbs et al 1993, Bouillon et al 1992, Jones 1995, Johnston, Boguraev, and Pustejovsky 1995).


Nous avons dejh montr6 que les bulletins d'avalanches constituent une application idtale pour la traduction automatique (BOUILLON et al. , 1991 et 1992a, BOESEFELDT et al. , 1991).


