The ACQUILI'~X l,exicon l)evelopment Environmen| uses typed graph unilication with inheritance as its lexical representation htnguage (for details, see Copestake (1992), Sanfiliplm & l'oznafiski (1992), and pal)ers by Copestake, de Paiva and Sanfilippo in Briscoe el al. 
Related Research In (Copestake e~ al. , 1992) the notion of a llink is introduced. 
SeverM lexical representation formalisms addressing these desiderata have been proposed, e.g. DATR \[Evans and Gazdar 1989a, 1989b, 1990\]; LRL \[Copestake, 1992\]; \[Russell et al. 1991\]. 
1) P\[modified, preposition, complement\] 2) below\[motion-verb, \[path,dest\],place\] The notation here is an informal representation of the typed feature structures described in (Briscoe et al. , 1992) and (Copestake, 1992). 
We used the LKB system (Copestake, 1992, 1999) as an experimentation platform since it provides a parameterisable bottom-up chart parser and precise, fine-grained profiling facilities (Oepen & Flickinger, 1998). 
