Besides the copying task, it can be exploited in various other ways, both to further the readibility of the documentation and to support the task of grammar writing (see also the suggestions by Erbach (1992)).8 Snapshots Grammar documentation is much easier to read if pictures of cand f-structures illustrate the analyses of example sentences.


Similar to common grammar-specific tools that are provided by grammar development environments, we propose a grammar-specific documentation technique (which ought to be integrated into the grammar development environments, as also suggested by Erbach and Uszkoreit (1990), Erbach (1992)).


3.1 Grammar engineering with TuLiPA As advocated by Erbach (1992), grammar engineering needs tools for testing the grammar with respect to consistency, coverage, overgeneration and accuracy.


Developing such resources is known to be a complex task that needs useful tools such as parsers and generators (Erbach, 1992).


