For both the language modeling and information extraction (the shaded boxes in Figure 2), we are using the partial parser Sparser (McDonald 1992). 
" The source structures are represented in a Kl-one derived system called Krisp (McDonald 1994s), and the parser that produces the corpus-based lattice of realization types is Sparser (McDonald 1992, 1994a)mtwo complete, mature systems. 
Although this can be considered a kind of partial parsing technique (McDonald, 1992; Lavie, 1996; Abney, 1996), the SUs obtained by ISSS are not always subsentential phrases; they are sometimes full sentences. 
For both the language modeling and information extraction, we are using the partial parser Sparser (McDonald 1992). 
Given such architectures, the move to properly reversible rules awaits only a declarative statement of the few .~'emaining parts of these systems where the mappin~ s have been formulated procedurally--a project that is already well advanced (McDonald 1991, 1992b). 
