The logical conclusions of these experiments are:  the statistical approach might not be a good approach for agglutinative and free-order languages -as pointed out by Oflazer and KuruOz (1994).


2 Previous work on Manipuri POS tagger  Morphology based POS tagging of some languages like Turkish (Oflazer and Kuruoz, 1994), Czech (Hajic, et al., 2001) has been tried out using a combination of hand-crafted rules and statistical learning.


