Among a number of existing categorization methods, we experimentally used one proposed by Iwayama and Tokunaga (1994), which formulates P(c|d) as in Equation (2).


Among a number of existing categorization methods, we experimentally used one proposed by Iwayama and Tokunaga (1994), which formulates P (c|d) as in Equation (2).


 In text categorization (Lewis and GMe, 1994; Iwayama and Tokunaga, 1994): P(tlC), where t is a term in the document to be categorized, and C is a candidate category label.


