(2005), Nakov and Hearst (2005)), similarity-based approaches incorporating orthographical, morpho-syntactic, and syntactic similarity criteria (e.g., Agarwal and Boggess (1992), Okumura and Muraki (1994)), as well as a combination of distribution information and syntactic criteria (Hogan, 2007a).


Okumura and Muraki (1994) estimate the similarity of candidate conjuncts by means of a similarity function which incorporates syntactic, orthographical, and semantic information about the conjuncts.


Other studies on coordination include (Agarwal and Boggess, 1992; Chantree et al., 2005; Goldberg, 1999; Okumura and Muraki, 1994).


Earlier studies (Agarwal and Boggess, 1992; Okumura and Muraki, 1994) attempted to find heuristic rules to disambiguate coordinations.


hashi and Nagao, 1994; Nakov and Hearst, 2005; Okumura and Muraki, 1994; Resnik, 1999).


