The uses of this procedure include information retrieval (Hearst and Plaunt, 1993; Hearst, 1994; Yaari, 1997; Reynar, 1999), summarization (Reynar, 1998), text understanding, anaphora resolution (Kozima, 1993), language modelling (Morris and Hirst, 1991; Beeferman et al. , 199717) and improving document navigation for the visually disabled (Choi, 2000). 
it marks a sentence boundary is at issue (Palmer and Hearst, 1994; Reynar and Ratnaparkhi, 1997)). 
Palmer and Hearst (1994) applied a neural network to the problem. 
Lexical cohesion methods are typically used for segmenting written text in a collection to improve information retrieval (Hearst, 1994; Reynat, 1998). 
E-marl: hearst@parc.xerox.com 1 There is some recent research in aligning bilingual corpora without relying on sentence boundaries (Fung and Church 1994; Fung and McKeown 1994). 
