Concepts are presented to the user through diagrammatic trees with natural language labels (Caldwell and Korelsky, 1994).


4 Graphical representations of content Symbolic authoring systems typically make use of graphical representations of the content of the domain modelfor example, conceptual graphs (Caldwell and Korelsky, 1994).


(Vega, 1990; Caldwell & Korelsky, 1994).


This work shares the interface orientation of Caldwell and Korelsky (1994), but is more abstract and flexible in that userspecifications are independent of, and combinable with, domain plans.


