Toward these problems, there were several attempts developed for automatically learning grammars based on rule-based approach(Ootani and Nakagawa, 1995), corpus-based approach(Srill, 1992)(Mori and Nagao, 1995) or hybrid approach(Kiyono and Tsujii, 1994b)(Kiyono and Tsujii, 1994a).


In this framework, a whole grammar is not acquired from scratch(Mori and Nagao, 1995) or an initial grammar does not need to be assumed(Kiyono and Tsujii, 1994a).


This hypothesis generation is similar to one applied in (Kiyono and Tsujii, 1994a).


