Word shape token processing has been proven to be of use for European language identification (Nakayama and Spitz, 1993; Sibun and Spitz, 1994).


A variant of the problem is considered by Sibun and Spitz (1994), and Sibun and Reynar (1996), who look at it from the point of view of Optical Character Recognition (OCR).


Word shape tokens are a potential alternative to character coded words when they are used for language determination and part-of-speech tagging (Nakayama and Spitz, 1993; Sibun and Spitz, this volume; Sibun and Farrar, 1994).


