As a number of researchers have shown, the highly defaulty character of lexical phonology and morphophonology makes DATR a very suitable medium of representation (Bleiching 1992, 1994; Cahill 1993b; Gibbon 1990, 1992; Gibbon and Bleiching 1991; Reinhard 1990; Reinhard and Gibbon 1991).


At the time of writing, we know of a dozen different implementations of the language, some of which have been used with large DATR lexicons in the context of big NLP systems (e.g. , Andry et al. 1992; Cahill 1993a, 1994; Cahill and Evans 1990).


There are around a dozen different implementations of the language and large DATR lexicons have been constructed for use in a variety of applications (Cahill and Evans, 1990; Andry et al. , 1992; Cahill, 1994).


There are around a dozen different implementations of DATR in existence and largescale DATR lexicons have been designed for use in a number of natural language processing applications (Cahill and Evans, 1990; Andry et al. , 1992; Cahill, 1994).


