Another project with instant understanding is GLOSSER, whose prototype (Nerbonne et al. 1997) performs morphological analysis of the sentence containing the selected word in a similar manner.


Its prototype (Nerbonne et al. 1997) carries out a morphological analysis of the sentence in which the selected word occurs and a stochastic disambiguation of the word class information.


Applications where word order is not essential include  cross-language information retrieval (e.g. , McCarley 1999),  multilingual document filtering (e.g. , Oard 1997),  computer-assisted language learning (e.g. , Nerbonne et al. 1997),  certain machine-assisted translation tools (e.g. , Macklovitch 1994; Melamed 1996a),  concordancing for bilingual lexicography (e.g. , Catizone, Russell, and Warwick 1989; Gale and Church 1991), 222 Melamed Models of Translational Equivalence  corpus linguistics (e.g. , Svartvik 1992),  "crummy" machine translation (e.g. , Church and Hovy 1992; Resnik 1997).


