This limitation can be partly alleviated by either only considering adjacent models and limiting the length to 5-6 words, or using a forward or backward sequential search proposed by (Pedersen et al. , 1997) for the problem of selecting models for the Word Sense Disambiguation task.


This data set was subsequently used for word sense disambiguation experiments by (Ng and Lee, 1996), (Pedersen et al. , 1997), and (Pedersen and Bruce, 1997).


A similar finding has emerged in word sense disambiguation, where a number of comparative studies have all reported that no method achieves significantly greater accuracy than the Naive Bayesian classifier (e.g. , (Leacock et al. , 1993), (Mooney, 1996), (Ng and Lee, 1996), (Pedersen and Bruce, 1997)).


(Pedersen et al. , 1997) and (Pedersen and Bruce, 1997) present studies that utilize the original Bruce and Wiebe feature set and include the interest data.


