(Zajac et al. , 1997) present Corelli, another TIPSTER compliant architecture implemented in Java (see (Basili et al. , 1999) for a comparison).


Another problem may arise when the architecture includes facilities for distributed processing (Zajac et al. , 1997; Zajac, 1997), as it is not obvious how the linear model currently embodied in the graphs could be extended to support non-linear control strucures.


