(forthcoming)) \[2\] LINLIN (Ahrenberg et al. 1990, Jonsson 1993, 1996) \[3\] EVAR German Train-Timetable Spoken Dialogue Information System (Eckert et al. 1993, Boros et al. 1996) \[4\] VERBMOBIL dialogue component (Alexandersson et al. 1996,1997) \[5\] The Slovenian Dialog System for Air Flight Inquiries (Ipsic et al. 1997, Pepelnjak et al. 1996) \[6\] SAPLEN Sistema Automatico de Pedidos en Lenguaje Natural (Lopez-Cozar(forthcoming)) Table 2: Features ranked in 6 DMSs Feature A B C D E F G Eli 2 1 1 2 3 2 2 \[2\] 2 1 1 2 2 2 2 \[3\] 2 1 1 1 3 1 1 \[4\] 1 1 1 6 2 \[5\] 3 6 6 5 3 2 \[6\] 3 5 5 5 5.


Others have used temporal annotation schemes for the much more constrained domain of meeting scheduling, e.g., [Wiebe et al. 1998], [Alexandersson et al. 1997], [Busemann et al. 1997]; our scheme has been applied to such domains as well.


Others have used temporal annotation schemes for the much more constrained domain of meeting scheduling, e.g., (Wiebe et al. 1998), (Alexandersson et al. 1997), (Busemann et al. 1997).


Basic processing entity for some comPonents is the so-called dialogue act \[Bunt 1981, Jekat et al. 1995, Alexandersson et al. 1997\].


