A recent paper by (Sekine, 1997) explores the domain dependence of parsing. 
The genre dependency of parsers is an accepted fact and has been described by, among others, Sekine (1997) and Gildea (2001). 
To date, a thorough study of the domain dependence of WSD --in the style of other studies devoted to parsing (Sekine, 1997)-has not been carried out. 
As mentioned above, Sekine (1997) and Gildea (2001) directly address the relation between NLP systems and text type; one further such item is Roland et al. 
We think that the study of the domain dependence of WSD --in the style of other studies devoted to parsing (Sekine, 1997; Ratnaparkhi, 1999)-is needed to assure the validity of the supervised approach, and to determine to which extent a tuning pre-process is necessary to make real WSD systems portable. 
