The only research that we are aware of is the work of (Hurst and Douglas, 1997; Douglas and Hurst, 1996; Douglas et al. , 1995).


The work of (Hurst and Douglas, 1997; Douglas and Hurst, 1996; Douglas et al. , 1995) also deals with plain texts.


Previous papers employ grammars (Green and Krishuainoorthy, 1995), string-based cohesion measures (Hurst and Douglas, 1997), and learning methods (Ng, Lim and Koo, 1999) to deal with table recognition.


Of the papers on table extractions (Douglas, Hurst and Quinn, 1995; Douglas and Hurst 1996; Hurst and Douglas, 1997; Ng, Lim and Koo, 1999), plain texts arc their targets.


