Utsuro and Matsumoto (1997) present a very interesting mechanism for learning semantic case frames for Japanese verbs: each case frame is a tuple of independent component frames (each of which may have an n-tuple of slots).


2Details of the method of statistically identifying the dependencies of the cases in verb.noun collocations are ~ven in Utsuro and Matsumoto (1997).


The probability of generating a verbnoun collocation from (partial) subcategorization frames is simply estimated as the product of the probabilities 4.2.2 Subcategorization Preference Test using Positive/Negative Examples The other type of the model evaluation criterion is the performance in the subcategorization preference test presented in Utsuro and Matsumoto (1997), in which the goodness of tile model is measured according to how many of the positive examples can be judged as more appropriate than the negative examples.


Some of these methods make use of prior knowledge in the form of an existing thesaurus (Resnik 1993a, 1993b; Framis 1994; Almuallim et al. 1994; Tanaka 1996; Utsuro and Matsumoto 1997), while others do not rely on any prior knowledge (Pereira, Tishby, and Lee 1993; Grishman and Sterling 1994; Tanaka 1994).


For the extraction problem, there have been various methods proposed to date, which are quite adequate (Hindle and Rooth 1991; Grishman and Sterling 1992; Manning 1992; Utsuro, Matsumoto, and Nagao 1992; Brent 1993; Smadja 1993; Grefenstette 1994; Briscoe and Carroll 1997).


