CommandTalk (Moore et al. , 1997), Circuit Fix-It Shop (Smith, 1997) and TRAINS-96 (Traum and Allen, 1994; Tranm and Andersen, 1999) are spoken language systems but they interface to simulation or help facilities rather than semi-autonomous agents. 
113 The speech and language processing architecture is based on that of the SRI CommandTalk system (Moore et al. , 1997; Stent et al. , 1999). 
Unlike other simulation systems, such as QuickSet (Cohen et al. , 1997), CommandTalk has extensive dialogue capabilities. 
CommandTalk (Moore et al. , 1997), Circuit Fix-It Shop (Smith, 1997) and Tl:tAINS-96 (Traum and Allen, 1994; Traum and Andersen, 1999) are spoken language systems but they interface to simulation or help facilities rather than semi-autonomous agents. 
The speech and language processing architecture is based on that of the SRI CommandTalk system (Moore et al. , 1997; Stent et al. , 1999). 
