Nymble (Bikel et al. , 1997), a system which uses HMMs is one of the most successflfl such systems and trains on a corpus of marked-up text, using only character features in addition to word bigrams. 
These include rule-based systems \[Krupka 1998\], Hidden Markov Models (HMM) \[Bikel et al. 1997\] and Maximum Entropy Models (MaxEnt) \[Borthwick 1998\]. 
Our named entity recognition module uses the HMM approach of (Bikel et al. , 1999; Bikel et al. , 1997), which learns from a tagged corpus of named entities. 
In this regard, we are similar to (Bikel et al, 1997), which also uses a probabilistic method in their HMM based system. 
Many of the previous studies of Bio-NER tasks have been based on machine learning techniques including Hidden Markov Models (HMMs) (Bikel et al. , 1997), the dictionary HMM model (Kou et al. , 2005) and Maximum Entropy Markov Models (MEMMs) (Finkel et al. , 2004). 
