2 Full parsing The analyzer used for this work is the Conexors FDG Parser (Pasi Tapanainen and Timo Jarvinen, 1997). 
Some relatively recent rule-based full dependency parsers are Kurohashi and Nagao (1994) for Japanese, Oflazer (1999) for Turkish, Tapanainen and Jarvinen (1997) for English and Elworthy (2000) for English and Japanese. 
We start by parsing the corpus with a dependency parser (we use Connexors FDG (Tapanainen and Jarvinen, 1997)), treating every verb with its dependent constituents as a clause. 
Conexor FDG (Tapanainen and Jarvinen, 1997) is a commercial parser and grammar, based on the theory of Functional Dependency Grammar, and was originally developed at the University of Helsinki. 
To identify associative constructions, we first process our texts using Conexors FDG parser (Tapanainen and Jarvinen, 1997). 
