More recently, Theron and Cloete (1997) have presented a scheme for obtaining two-level morphology rules from a set of aligned segmented and surface pairs.


3.4 Mixed context representation The mixed context representation used by Theron and Cloete (1997) folds the letters of a word around a pivot letter: it enumerates alternately the next letter on the right then on the left, until it reaches the word boundaries, which are marked with special symbols (here, CM for start of word, and $ for end of word).


We then designed two methods that can learn accenting rules for the remaining unknown words: B4CXB5 adapting a POS-tagging method (Brill, 1995) (section 3.3); B4CXCXB5 adapting a method designed for learning morphological rules (Theron and Cloete, 1997) (section 3.4).


