(Agirre and Martinez, 2000), (Al-Halimi and Kazman, 1998), (Artale, et al. , 1997), (Basili et al. , 1997), (Berwick, et al. , 1990), (Burg and van de Riet 1998), (Cucchiarelli and Velardi 1997), (Fellbaum 1990), (Gonzalo, et al. , 1998), (Harabagiu and Moldovan, 1996) Its coverage, which is comparable to that of a collegiate dictionary, extends over some 130,000 word forms.


It is potentially useful in other natural language processing tasks, such as the problem of estimating n-gram models (Brown et al. 1992) or the problem of semantic tagging (Cucchiarelli and Velardi 1997).


For a formal definition of these four measures, see (Cucchiarelli and Velardi, 1997).


