The use of SMES in COSMA, semantic analysis and inference, the dialogue model mapping between human and machine dialogue structures, utterance generation, the architectural framework of the server, and the PASHA agent system are described in (Busemann et al. , 1997). 
Others have used temporal annotation schemes for the much more constrained domain of meeting scheduling, e.g., [Wiebe et al. 1998], [Alexandersson et al. 1997], [Busemann et al. 1997]; our scheme has been applied to such domains as well. 
In (1) SMES is embedded in the COSMA system, a German language server for existing appointment scheduling agent systems (see (Busemann et al. , 1997), this volume, for more information). 
(1997), and Busemann et al. 
A client may connect to the server and open up a dialogue (see Figure 1 in (Busemann et al. , 1997)). 
