W04-0508:1	89:182	Next the entire corpus is chunked into nominal and verbal chunks using LT Chunk (Finch and Mikheev, 1997).
---------------------------------------------------
A97-1034:2	45:229	Other of our software packages such as LT POS (a part of speech tagger) and LT WB (Mikheev&Finch, 1997) also use the LT NSL library.
---------------------------------------------------
A97-1034:3	194:229	See also (Mikheev&Finch, 1995), (Mikheev&Finch, 1997) for other uses of the LT NSL tools in annotating linguistic structures of interest and extracting statistics from that markup.
---------------------------------------------------
W05-1308:4	39:62	Information extraction from free-text utilizes shallow-parsing techniques (Daelemans, Buchholz et al. 1999), Parts-of-Speech tagging(Brill 1992), noun and verb phrase chunking (Mikheev and Finch 1997), verb subject and object relationships (Daelemans, Buchholz et al. 1999), and learned (Califf and Mooney 1998; Craven and Kumlein 1999; Seymore, McCallum et al. 1999) or hand-build patterns to automate the creation of specialized databases.
---------------------------------------------------
P05-2009:5	73:193	For some experiments, relations were considered between noun phrases, labelled using LT CHUNK (Mikheev and Finch, 1997).
---------------------------------------------------
W04-1007:6	122:211	The next stage in the linguistic analysis module performs noun group and verb group chunking using fsgmatch with the specialised hand-written rule sets which were the core part of LT CHUNK (Finch and Mikheev, 1997).
---------------------------------------------------
W06-1807:7	17:129	36 KRAQ06 for generic XML manipulation (LTXML (Thompson et al. , 1997)) as well as NLP-specific XML tools (LT-TTT (Grover et al. , 2000), LT-CHUNK (Finch and Mikheev, 1997)).
---------------------------------------------------
