, 1994; Lauer, 1995; Zhai, 1997). 
Linguistically motivated syntactic units such as noun phrases (Zhai, 1997), head-modifier pairs (Fagan, 1987; Strzalkowski et al. , 1996) and subjectverb-object triples (Katz and Lin, 2003) have also been integrated in information retrieval. 
Zhai (1997) rst identi ed the importance of syntactic query/corpus parsing for information retrieval, but did not consider query segmentation itself. 
Recently it has been shown that noun phrase analysis is effecrive for the improvement of the application of natural language processing such as information retrieval (Zhai, 1997). 
For example, Zhai (1997) pointed out that indexing on single-word symbols is not able to distinguish a search for bank terminology from one for terminology bank. 
