For type precision and recall, we used 14 verbs selected by Briscoe & Carroll (1997) and evaluated our results against SCF entries in COMLEX (Grishman et al. , 1994). 
The SCF acquisition system has been evaluated elsewhere (Briscoe and Carroll, 1997). 
4.2 SCF Extraction System We briefly outline our SCF extraction system for automatically extracting SCFs from corpora, which was based on the design proposed in Briscoe and Carroll (1997). 
This can be done automatically with unparsed corpora (Briscoe and Carroll 1997, Manning 1993, Ushioda et al. 1993), from parsed corpora such as Marcus et al.'s (1993) Treebank (Merlo 1994, Franlis 1994) or manually as was done for COMLEX (Macleod and Grishman 1994). 
2.2 Filtering Methods 2.2.1 Binomial Hypothesis Test Briscoe and Carroll (1997) used a binomial hypothesis test (BHT) to filter the acquired SCFs. 
