But many systems are similar to STOP in that they generate texts -such as descriptions of software models (Lavoie et al. , 1997) and customised descriptions of museum items (0berlander et al. , 1998) -which are useful in principle but are not currently writ l}en by humans, perhaps because of cost or response-time issues.


8 Status The system is fully operational, runs on PC as well as on UNIX work stations, and is currently used in an application we have developed (Lavoie et al. , 1997) as well as in several on-going projects (weather report generation, machine translation, project report generation).


So far the framework has been used successfully for building a wide variety of applications in different domains and for different languages: NLG:  Realization of English DSyntSs via SSyntS level for the domains of meteorology (MeteoCogent; Kittredge and Lavoie, 1998) and object modeling (ModelExplainer; Lavoie et al. , 1997).


PRESENTOR has been used with success in different domains including object model description (Lavoie et al., 1997), weather forecasting (Kittredge and Lavoie, 1998) and system requirements summarization (Ehrhart et al., 1998; Barzilay et al., 1998).


