Stage 1 of the planning procedure is described elsewhere (Power, 2000); we focus here on stages 2 and 3, in which the text planner enumerates the possible assignments of centers and evaluates which is the best. 
1991; Bouayad-Agha, Power, and Scott 2000). 
Precursors to current approaches were Hovys PAULINE which kept track of the satisfaction status of global rhetorical goals (Hovy, 1988), and Power et al.s ICONOCLAST which allowed users to fine-tune different combinations of global constraints (Power, 2000). 
Formal Theory of Document Structure We will describe here the formal theory of document structure that we have developed as part of the ICONOCLAST system (Power 2000; Bouayad-Agha, Power, and Scott 2000; Bouayad-Agha 2000; Bouayad-Agha, Scott, and Power 2001), which generates multiple versions of the same message in different styles (i.e. , with different wording and layout). 
For further discussion see Bouayad-Agha, Power, and Scott (2000). 
