Comparable corpora have been studied extensively in the literature (e.g. ,(Fung, 1995; Rapp, 1995; Tanaka and Iwasaki, 1996; Franz et al. , 1998; Ballesteros and Croft, 1998; Masuichi et al. , 2000; Sadat et al. , 2003)), but transliteration in the context of comparable corpora has not been well addressed.


Comparable corpora have been studied extensively in the literature  e.g.,(Fung, 1995; Rapp, 1995; Tanaka and Iwasaki, 1996; Franz et al. , 1998; Ballesteros and Croft, 1998; Masuichi et al. , 2000; Sadat et al. , 2004), but transliteration in the context of comparable corpora has not been well addressed.


