So far, the larger group of related publications has focused on the task of selecting, from a set of translation candidates obtained from different engines, one translation that looks most promising (Tidhar and Kussner, 2000; Akiba et al. , 2001; Callison-Burch and Flournoy, 2001; Akiba et al. , 2002; Nomoto, 2004).


Multiengine systems can be roughly divided into simple 1See (Hutchins et al. , 2006) for a list of commercial MT systems 2See http://www.euromatrix.net 193 Figure 1: Architecture for multi-engine MT driven by a SMT decoder architectures that try to select the best output from a number of systems, but leave the individual hypotheses as is (Tidhar and Kussner, 2000; Akiba et al. , 2001; Callison-Burch and Flournoy, 2001; Akiba et al. , 2002; Nomoto, 2004; Eisele, 2005) and more sophisticated setups that try to recombine the best parts from multiple hypotheses into a new utterance that can be better than the best of the given candidates, as described in (Rayner and Carter, 1997; Hogan and Frederking, 1998; Bangalore et al. , 2001; Jayaraman and Lavie, 2005; Matusov et al. , 2006; Rosti et al. , 2007).


