(Niessen and Ney, 2000) or adjective compounds such as ?multidimensionale??


Niessen and Ney (2000; 2004) report work on German-English translation, where they investigate various types of morphosyntactic restructuring, including merging German verbs with their detached prefixes, annotating a handful of frequent ambiguous German words with POS tags, combining idiomatic multi-word expressions into single words, and undoing question in676 version and do-insertion in both German and English.


Symmetrization of linguistic structures can also be found in (Niessen and Ney 2000).


