??UNL (Universal Networking Language (Serasset and Boitet, 2000)), is a French to disambiguated English dictionary for machine translation, which contains syntactic information in its French part (see table 1 for a UNL example entry).


The French-UNL dictionary (Serasset and Boitet, 2000) also contains prepositions, but its coverage is quite limited and the quality of its entries is not homogeneous.


Within the UNL project, a number of software tools exist for dierent languages, mainly dictionnaries and deconverters (for French (Serasset and Boitet, 2000), for Tamil (Dhanabalan and Geeta, 2003), etc.).


