To remove these noisy remaining contexts, we set up a dropping threshold using normal distribution of similarity values as follows (Ko and Seo, 2000): } ),( max Cc i  +  i cXsim (10) where i) X is a remaining context, ii)  is an average of similarity values, iii)  is a standard deviation of similarity values, and iv)  is a numerical value corresponding to the threshold (%) in normal distribution table.


The approach of categorizing texts based on lists of keywords has been attempted rather rarely in the literature (McCallum and Nigam, 1999; Ko and Seo, 2000; Liu et al. , 2004; Ko and Seo, 2004).


