This is essentially similar to the approach in (Osborne, 2000), where there is an infeasibly large number of training events, only part of which is used in the estimation step. 
(1999) and Osborne (2000). 
Another approach to estimating log-linear models for HPSG is to extract a small informative sample from the original set CCB4D7B5 (Osborne, 2000). 
In (Osborne, 1999), the DCG is mapped to a SCFG to compute probabilities, in very recent work a stochastic attribute-value grammar is used (Osborne, 2000). 
4Another possible solution would be to use sampling methods, e.g. Osborne (2000). 
