A very common technique for combination in such a case is by voting (Brill and Wu, 1998; van Halteren et al. , 1998; Sang et al. , 2000). 
3.3 Weighted Voting Tjong Kim Sang et al. report that they achieve higher accuracy by applying weighted voting of systems which are trained using distinct chunk representations and different machine learning algorithms, such as MBL, ME and IGTree(Tjong Kim Sang, 2000a; Tjong Kim Sang et al. , 2000). 
The IBM-CT Corpus The Chinese Treebank (Xia et al. , 2000), available from Linguistic Data Consortium, consists of a 100,000 word (approximately 160,000 characters) corpus annotated with word segmentation, part-ofspeech tags, and syntactic bracketing. 
In the course of this project we have evaluated another combination method: BEST-N MAJORITY VOTING (Tjong Kim Sang et al. , 2000). 
(2000) for base noun phrase chunking, and Florian et al. 
