3Using ChaSen morphological-analysis software for the Japanese language (Asahara and Matsumoto, 2000). 
For example, the ChaSen package for segmenting Japanese input into words and morphemes (Asahara & Matsumoto, 2000) has been linked to at least the LKB and PET systems. 
For Asian languages, we integrated Chasen (Asahara and Matsumoto, 2000) for Japanese and Shanxi (Liu, 2000) for Chinese. 
We use the following systems for comparison: ChaSen The word segmentation and POS-tagging system based on extended Markov models (Asahara and Matsumoto, 2000; Matsumoto et al. , 2001). 
using the ChaSen Japanese morphological analyzer (Asahara and Matsumoto, 2000) and syntactic clues (such as word order, syntactic category and specific prepositions). 
