The DOP model has also been tested as a model for human sentence processing (Bod 2000d). 
This result is promising since TreeDOP has been shown to obtain state-of-the-art performance on the Wall Street Journal corpus (see Bod 2000a). 
Most probability models for DOP use the relative frequency estimator to estimate fragment probabilities, although Bod (2000b) trains fragment probabilities by a maximum likelihood reestimation procedure belonging to the class of expectation-maximization algorithms. 
This phenomenon is also known as the DOP hypothesis (Bod 1998), and has been confirmed for Tree-DOP on the ATIS, OVIS and Wall Street Journal treebanks (see Bod 1993, 1998, 1999, 2000a; Sima'an 1999; Bonnema et al. 1997; Hoogweg 2000). 
Bonnema et al. 1997; Bod 2000a). 
