Stochastic methods for NLG may provide such automaticity, but most previous work (Knight and Hatzivassiloglou, 1995), (Langkilde and Knight, 1998), (Oh and Rudnicky, 2000), (Uchimoto et al. , 2000), (Bangalore and Rambow, 2000) concentrate on the speci cs of individual stochastic methods, ignoring other issues such as integrability, portability, and e ciency.


(Uchimoto et al. , 2001; Uchimoto et al. , 1999; Uchimoto et al. , 2000b).


The word-order model proposed by Uchimoto et al. can also generate surface text in a natural order (Uchimoto et al. , 2000a).


