Alignment quality was evaluated by computing Alignment Error Rate (AER) (Och and Ney, 2000) relative to the manual alignments. 
Och is the HMM alignment model of (Och and Ney, 2000b). 
Och and Ney (2000a) introduce a NULL-alignment capability to the HMM alignment model. 
Reasons to introduce phrase level translation knowledge sources have been adequately shown and confirmed by (Och, Ney, 2000), and we focus on methods to build these sources from existing, mature components within the translation process. 
Our test data consists of a191 a179a6a179 manually aligned sentences which are the same data set used by (Och and Ney, 2000b).6 In the annotated sentences every alignment between two words is labeled as either a sure (S) or possible (P) alignment. 
