A side benefit of our construction is a far simpler implementation of directional OT (Eisner, 2000). 
More generally, different constraints can usefully be applied with different Hs (Eisner, 2000). 
For example, we obtain a transparent algebraic version of Eisners (2000) unbearably technical automaton construction for his proposed formalism of directional OT. Computational Linguistics (ACL), Philadelphia, July 2002, pp. 
Eisner (2000) proved that o> was a regular operator for directional H, by making use of a rather different insight, but that machine-level construction was highly technical. 
To consider recent constructions that cut through this problem (Frank and Satta, 1998; Karttunen, 1998; Eisner, 2000; Gerdemann and van Noord, 2000). 
