Automatic detection of such argument alternations is important to acquisition of verb lexical semantics (Dang et al. , 2000; Dorr and Jones, 2000; Merlo and Stevenson, 2001; Schulte im Walde and Brew, 2002; Tsang et al. , 2002), and moreover, may play a role in automatic processing of language for applied tasks, such as question-answering (Katz et al. , 2001), information extraction (Riloff and Schmelzenbach, 1998), detection of text relations (Teufel, 1999), and determination of verbparticle constructions (Bannard, 2002).


Correspondingly, the relation between alternation patterns and meaning is a key focus in the computational study of the lexical semantics of verbs (e.g. , Allen, 1997; Dang et al. , 2000; Dorr and Jones, 2000; Merlo and Stevenson, 2001; Schulte im Walde and Brew, 2002; Tsang et al. , 2002).


This paper explores fine-grained lexical semantic representationsapproaches that view a verb as more than a simple predicate of its arguments (e.g. , Dang et al. , 2000).


While I may disagree with the technical details, I believe that the approach taken by (Dang et al. , 2000) is on the right path.


