Apart from the above research with a classificatory flavour, other lines of research exploited lexical relations among adjectives for Word Sense Disambiguation (Justeson and Katz, 1995; Chao and Dyer, 2000).


Chao and Dyer (2000) propose a method for the disambiguation of polysemous adjectives in adjective-noun combinations that also uses Bayesian networks and WordNets taxonomic information.


Previous work in word sense disambiguation has not tackled explicitly the ambiguity problems arising from Levins classification, although methods for deriving informative priors in an unsupervised manner have been proposed by Ciaramita and Johnson (2000) and Chao and Dyer (2000) within the context of noun and adjective sense disambiguation, respectively.


The models proposed by Chao and Dyer (2000) and Ciaramita and Johnson (2000) are not directly applicable to Levins classification, as the latter is not a hierarchy (and therefore not a DAG) and cannot be straightforwardly mapped into a Bayesian network.


