2 Topic Signatures Topic Signatures (TS) are word vectors related to a particular topic (Lin and Hovy, 2000). 
Lin and Hovy (2000) first introduced topic signatures which are topic relevant terms for summarization. 
Log-likelihood ratio for words in the input Number of topic signature words (Lin and Hovy, 2000; Conroy et al., 2006) and percentage of signature words in the vocabulary. 
2 Topic Signatures Topic Signatures (TS) are word vectors related to a particular topic (Lin and Hovy, 2000). 
In this regard, we use a method similar to Lin and Hovy (2000) to identify signature terms and subsequently use them  2  http://ir.ohsu.edu/genomics/ to discard sentences that contain none or few such terms. 
