CLLS descriptions can be derived compositionally and have been used to deal with a rich class of linguistic phenomena (Koller et al. , 2000; Koller and Niehren, 2000).


One can then strengthen the underspecified description to efficiently eliminate subsets of readings that were not intended in the given context (Koller and Niehren, 2000; Koller and Thater, 2006); so when the individual readings are eventually computed, the number of remaining readings is much smaller and much closer to the actual perceived ambiguity of the sentence.


Such inferences could already take place on the level of the underspecified description (Koller and Niehren, 2000).


Such new edges on SC could come from inferences with world or discourse knowledge (Koller and Niehren, 2000), scope preferences, or interactions with information structure (Duchier and Kruijff, 2003).


