Church 2000). 
Since words that occur once are likely to occur again (Church, 2000), the Polya model is better suited to model the occurrences of words and users. 
Church (2000) introduces such a diagnostic for lexical priming: adaptation probabilities. 
5.5.4 noriega and said These terms were studied in the context of an adaptive language model to demonstrate the fact that the probability of a repeat occurrence of a term in a document defies the bag of words independence assumption (Church, 2000). 
Church (2000) proposes adaptive language models to account for lexical adaptation. 
