Identification of semantically similar situations can be also improved by the use of segment-matching algorithms as employed in Example-Based MT (EBMT) and translation memories (Planas and Furuse, 2000; Carl and Way, 2003).


1 Introduction It is widely acknowledged that human translators can benefit from a wide range of applications in computational linguistics, including Machine Translation (Carl and Way, 2003), Translation Memory (Planas and Furuse, 2000), etc. There have been recent research on tools detecting translation equivalents for technical vocabulary in a restricted domain, e.g.


Identification of semantically similar situations can be improved by the use of segmentmatching algorithms as employed in ExampleBased MT and translation memories (Planas and Furuse, 2000; Carl and Way, 2003).


