8 However, if we break down the performance, we see that recall of 8 The difference between the two results is significant (p <.05) according to the randomized test described in Yeh (2000). 
4We measured significance with the randomized significance test of (Yeh, 2000). 
Table 5 shows a 0.4 percent F-score improvement over the baseline for that section, which is statistically significant at p < 0.001, using the stratified shuffling test (Yeh, 2000). 
A stratified shuffling-based randomization test (Yeh, 2000) shows that the differences are statistically significant (p < 0.05). 
It is also interesting to note that the best result on the validation set for estimation 4We measured significance of all the experiments in this paper with the randomized significance test (Yeh, 2000). 
