3.4 Decoding The decoding algorithm employed for this chunkbased statistical translation is based on the beam search algorithm for word alignment statistical translation presented in (Tillmann and Ney, 2000), which generates outputs in left-to-right order by consuming input in an arbitrary order. 
It is faster because the search problem for noisychannel models is NP-complete (Knight, 1999), and even the fastest dynamic-programming heuristics used in statistical MT (Niessen et al. , 1998; Tillmann and Ney, 2000), are polynomial in Jfor instance O(mJ4V 3) in (Tillmann and Ney, 2000). 
(2001), Wang and Waibel (1997), Tillmann and Ney (2000) GarciaVarea and Casacuberta (2001) and Germann et al. 
We call this selection of highly probable words observation pruning (Tillmann and Ney 2000). 
The generation of possible output chunks is estimated through an inverted lexicon model and sequences of inserted strings (Tillmann and Ney, 2000). 
