The MDA system developed at XRCE (Dymetman et al. , 2000; Brun et al. , 2000) uses a formalism inspired from Definite Clause Grammars (Pereira and Warren, 1980) that encodes both the abstract semantic syntax of well-formed documents and the concrete syntax for the documents in several languages.5 MDA grammars contain the definition of semantic objects of a given semantic type, which are used to build typed abstract semantic trees.


The MDA (Multilingual Document Authoring) system (Dymetman et al. , 2000; Brun et al. , 2000) follows the WYSIWYM approach, but puts a strong emphasis on the well-formedness of document semantic content.


2 Document normalization system A MDA grammar can enumerate the wellformed content representations for documents of a given class and associate textual realizations to them (Dymetman et al. , 2000).


