2 The DOP1 Model To-date, the Data Oriented Parsing model has mainly been applied to corpora of trees whose labels consist of primitive symbols (but see Bod & Kaplan 1998; Bod 2000c, 2001). 
This result is promising since TreeDOP has been shown to obtain state-of-the-art performance on the Wall Street Journal corpus (see Bod 2000a). 
We used the technique in Bod (1998, 2000) to include unknown subtrees. 
Bonnema et al 1999), including maximum likelihood estimation (Bod 2000b). 
The DOP model has also been tested as a model for human sentence processing (Bod 2000d). 
