Multimodal integration and interpretation for such interfaces is elegantly expressed using multimodal grammars (Johnston and Bangalore, 2000). 
Figure 2: Multimodal Architecture 2.2 Multimodal Integration and Understanding Our approach to integrating and interpreting multimodal inputs (Johnston et al. , 2002b; Johnston et al. , 2002a) is an extension of the finite-state approach previously proposed (Bangalore and Johnston, 2000; Johnston and Bangalore, 2000). 
These are then combined and assigned a meaning representation using a multimodal finite-state device (MMFST) (Johnston and Bangalore, 2000; Johnston et al. , 2002b). 
Johnston and Bangalore describe a multimodal parsing algorithm that is built using a 3-tape, finite state transducer (FST) (Johnston and Bangalore, 2000). 
One major motivation for developing multimodal interfaces for mobile devices is the lack of a keyboard or mouse (Oviatt and Cohen, 2000; Johnston and Bangalore, 2000). 
