The Czech grammar resources used in tactical generation have been built up along with Bulgarian and Russian grammar resources as described in (Kruijff et al. , 2000), reusing the NIGEL grammar for English.


AGILEs graphical user interface (Hartley, Power et al. , 2000) closely resembles the interface that was developed for an earlier system, DRAFTER, which generates software manuals in English and French (Paris et al. , 1995).


We go beyond our recent experience of evaluating the AGILE system for producing multilingual versions of software user manuals (Hartley, Scott et al. , 2000; Kruijff et al. , 2000) and raise some open questions about how best to evaluate the faithfulness of an output text with respect to its input specification.


Figure 5: fragment of a typical feedback text 6 See Hartley et al (2000) for further discussion of this issue and the results of the AGILE evaluation.


