C02-2022:1	16:124	Tiberius and Cahill (2000) described the vowel metaphonemes for these three languages.
---------------------------------------------------
C02-2022:2	5:124	1 Introduction Tiberius and Cahill (2000) presented the theory of cross-linguistic phoneme correspondences (metaphonemes) with an example pilot study of the vowels of Dutch, English and German.
---------------------------------------------------
C02-2022:3	99:124	As Tiberius and Cahill (2000) described, using metaphonemes for the vowels alone increased the amount of phonological definitions that could be shared by around 25%.
---------------------------------------------------
