W01-1402:1	8:164	Some of these employ parsers to produce dependency structures for the sentence pairs in aligned bilingual corpora, which are then aligned to obtain transfer rules or examples (Meyers et al. 2000; Watanabe et al. 2000).
---------------------------------------------------
W01-1402:2	11:164	The efforts that report accuracy results for fully automatic example extraction (Meyers et al. 2000; Watanabe et al. 2000) do so for very modest amounts of training data (a few thousand sentence pairs).
---------------------------------------------------
P03-1057:3	11:230	There are two approaches to overcoming incorrect/redundant rules:  Selecting appropriate rules in a disambiguation process during the translation (on-line processing, (Meyers et al. , 2000)).
---------------------------------------------------
I08-1069:4	132:166	The English and target syntactic structures form parallel treebanks, from which transfer rules and translation lexicon can be extracted and used for machine translation (e.g., (Meyers et al., 2000; Menezes, 2002; Xia and McCord, 2004)).
---------------------------------------------------
W02-1601:5	136:162	Synchronous correspondence sn G41 st G41 (0-1,0-1) (0-4 0-1 2-3 34, 0-6 0-1 2-3 3-4 4-5) (0-1,0-1) (2-3,2-3) (2-3,2-3) beschenkte [v] (1-2/0-4) Er [n] (0-1/0-1) reichlich[adj] (3-4/3-4) Hans [n] (2-3/2-3) 0 Er 1 beschenkte 2 Hans 3 reichlich 4 give[v] (1-2/0-6) He [n] (0-1/0-1) John [n] (2-3/2-3) present [n] (5-6/3-6) an[det] (3-4/3-4) expansive[adj] (4-5/4-5) 0 He 1 gave 2 John 3 an 4 expansive 5 5 present 6 (3-4,4-5) (0-4,0-6) (3-4,4-5) 2000), (Meyers et al. , 2000), (Matsumoto et al. , 1993) and (kaji et al. , 1992).
---------------------------------------------------
W02-1601:6	71:162	For example, such schema can serve as a mean to represent translation examples, or find structural correspondences for the purpose of transfer grammar learning (Menezes & Richardson, 2001), (Aramaki et al. , 2001), (Watanabe et al. , 2000), (Meyers et al. , 2000), (Matsumoto et al. , 1993), (kaji et al. , 1992), and example-base machine translation EBMT 3 (Sato & Nagao, 1990), (Sato, 1991), (Richardson et al. , 2001), (Al-Adhaileh & Tang, 1999).
---------------------------------------------------
