For parsing, we use a version of the Backward Beam Search Algorithm (Sekine et al. , 2000) developed for Japanese dependency analysis adapted to our representations of the morphological structureofthewords. 
2 Dependency Parsing for Thai The dependency structure for Thai is more flexible than some languages like Japanese (Sekine et al., 2000), Turkish (Eryigit and Oflazer, 2006), while it is close to Chinese (Cheng et al., 2005) and English (Nivre and Scholz, 2004). 
KM02 = Kudo and Matsumoto 2002, KM00 = Kudo and Matsumoto 2000, USI99 = Uchimoto et al. 1999, and Seki00 = Sekine 2000. 
(1999) used the backward beam search with ME. According to (Sekine et al. , 2000), the analyzing time followed a quadratic curve. 
Most of the modern dependency parsers for Japanese require bunsetsu chunking (base phrase chunking) before dependency parsing (Sekine et al., 2000; Kudo and Matsumoto, 2002; Sassano, 2004). 
