Answer extraction based on grammatical information is also promoted by the system described in (Clarke et al. , 2000). 
This is generally a very good strategy, that has been exploited successfully in a number of automated QA systems that appeared in recent years, especially in the context of TREC QA 1 evaluations (Harabagiu et al. , 2000; Hovy et al. , 2000; Prager at al. , 2001). 
Two classes of similar dependencies are considered for the abduction of answers, performed in a manner similar to the justifications described in (Harabagiu et al. , 2000).a26 Class L3-1: is characterized by the need for contextual information, brought forward by reference resolution. 
Harabagiu et al. [2000] indicated that advanced tools (such as dialog understanding and text mining) are essential for the success of future QA systems. 
(Gaizauskas and Humphreys, 2000) (Harabagiu et al. , 2000)) and used later in extracting the answer (cf. 
