However, it is not feasible to define such keywords in retrieval for operation manuals (Komatani et al. , 2002) or WWW pages, where the target of retrieval is not organized and is written as natural language text.


Many studies have been conducted on efficient dialogue strategies (Walker et al. , 1998; Litman et al. , 2000; Komatani et al. , 2002), but it is not clear how to accomplish a more human-like enthusiasm for a conversational dialogue.


