For the extraction of anaphor-antecedent candidates, we used a chunked version of the corpus (Muller and Ule, 2002).


For this reason, we used KaRoPars (Muller and Ule, 2002), a partial parser for German, to parse the sentences.


functions) 75.79% Fa0 73.70 Table 1: Results for the memory-based parser (Kubler, 2004a; Kubler, 2004b) and KaRoPars (Muller and Ule, 2002; Muller, 2005).


The investigation on the usefulness of chunk sequences was performed on the data of the German treebank TuBa-D/Z (Telljohann et al. , 2004) and on output from KaRoPars, a partial parser for German (Muller and Ule, 2002).


3.2 Partially Parsed Data KaRoPars (Muller and Ule, 2002) is a partial parser for German, based on the finite-state technology of the TTT suite of tools (Grover et al. , 1999).


