The approach is now being actively explored for a wide range of semantics-related tasks including automatic construction of thesauri (Lin, 1998; Caraballo, 1999), their enrichment (Alfonseca and Manandhar, 2002; Pekar and Staab, 2002), acquisition of bilingual lexica from nonaligned (Kay and Rscheisen, 1993) and nonparallel corpora (Fung and Yee, 1998), learning of information extraction patterns from un-annotated text (Riloff and Schmelzenbach, 1998).


