One of the solutions is to use dictionaries developed for a corpus on another domain to reduce the number of unknown words, but the improvement achieved is slight (Uchimoto et al. , 2002).


However, Uchimoto et al. reported that the accuracy of automatic word segmentation and POS tagging was 94 points in F-measure (Uchimoto et al. , 2002).


The terms used in the table are basically as same as those that Uchimoto et al. used (Uchimoto et al. , 2002).


