Numerous methods to select features exist (Hisamitsu and Niwa, 2002) (Yang and Pedersen, 1997).


1 Introduction Modeling term co-occurrence is important for many natural language applications, such as topic segmentation (Ferret, 2002), query expansion (Vechtomova et al. , 2003), machine translation (Tanaka, 2002), language modeling (Dagan et al. , 1999; Yuret, 1998), and term weighting (Hisamitsu and Niwa, 2002).


