In addition to sentence fusion, compression algorithms (Chandrasekar, Doran, and Bangalore 1996; Grefenstette 1998; Mani, Gates, and Bloedorn 1999; Knight and Marcu 2002; Jing and McKeown 2000; Reizler et al. 2003) and methods for expansion of a multiparallel corpus (Pang, Knight, and Marcu 2003) are other instances of such methods.


This provides a diverse collection of translation hypotheses for MT system combination (Bangalore et al. , 2002; Sim et al. , 2007; Matusov et al. , 2006; Macherey and Och, 2007).


Lattices have proven advantageous in a number of NLP contexts (Mangu et al. , 2000; Bangalore et al. , 2002; Barzilay and Lee, 2002; Pang et al. , 2003), but were usually produced from (multi-)parallel data, which may not be readily available for many applications.


There has also been recent work that combines 1-best hypotheses from multiple translation systems (Bangalore et al. , 2002); this approach uses string-edit distance to align the hypotheses and rescores the resulting lattice with a language model.


