(2003) and Becker and Frank (2002). 
We report the results of topological field parsing of German using the unlexicalized, latent variable-based Berkeley parser (Petrov et al., 2006) Without any languageor model-dependent adaptation, we achieve state-of-the-art results on the TuBa-D/Z corpus, and a modified NEGRA corpus that has been automatically annotated with topological fields (Becker and Frank, 2002). 
 40) 89.54 88.14 88.83 This work (all) 90.29 90.51 90.40 BF02 (all) 89.07 87.80 88.43 Table 3: BF02 = (Becker and Frank, 2002). 
Becker and Frank (2002). 
In (Becker and Frank, 2002) we present a corpusdriven stochastic topological parser for German, based on a topological restructuring of the NEGRA corpus (Brants et al. , 1999). 
