1 Introduction Spoken dialogue systems are emerging as an intuitive interface for providing conversational access to online information sources (Eckert et al. , 1997; Gorin et al. , 1997; Dahlback et al. , 1999; Zue et al. , 2000; Walker et al. , 2001; Glass and Seneff, 2003; Pieraccini et al. , 1997; Quast et al. , 2003; J. Gustafson, 1999; Polifroni and Chung, 2002; Denecke, 2002; Seneff, 2002; Zue and Glass, 2000).


While some are concerned with the generation of systems from on-line content (Feng et al. , 2003), others have addressed portability issues within the dialog manager (Denecke et al. , 2002) and the understanding components (Dzikovska et al. , 2003).


