J03-2002:1	545:649	OAA makes it convenient to combine different components that are required in natural language process205 Bos Implementing Binding and Accommodation Theory ing, such as speech recognition or parsing, the presupposition resolution component, and theorem provers, because OAA agents can be implemented in different programming languages and run simultaneously on different machines (Bos and Oka 2002).
---------------------------------------------------
W03-2123:2	186:196	tion with domestic appliances, as initiated by the EU project DHomme (Bos and Oka, 2002), ex- plaining route descriptions to a mobile robot in a miniature town, an EPSRC-funded project (Lauria et al., 2001), and meaningful conversation with a mobile robot in the basement of our department (Theobalt et al., 2002).
---------------------------------------------------
W08-1308:3	43:137	(2005) or Bos and Oka (2002), but we leave the relevant evaluation for future work.
---------------------------------------------------
W06-1309:4	55:198	(Bos and Oka, 2002) uses first-order logic in a DRT environment to reason about the logical satisfiability of a new utterance given a previous discourse.
---------------------------------------------------
