The efficacy of this approach has been well-established in many areas, including automated evaluation of machine translation systems (Kauchak and Barzilay, 2006), text summarization (Kittredge, 2002), question answering (Rinaldi et al. , 2003), document retrieval (Zukerman and Raskutti, 2002), and many others.


Another application of paraphrasing is to canonicalize many expressions that have the same semantics, supporting information retrieval or question answering (Zukerman and Raskutti, 2002; Torisawa, 2002).


In the context of IR, efforts have been made to use syntactic information to enhance retrieval (Smeaton, 1999; Strzalkowski, 1996; Zukerman and Raskutti, 2002), but not by using POS block-based distribution representations.


Several solutions to this problem have been proposed including query expansion (Riezler et al., 2007; Fang, 2008), query reformulation or paraphrasing (Hermjakob et al., 2002; Tomuro, 2003; Zukerman and Raskutti, 2002) and semantic information retrieval (Muller et al., 2007).


The typical way to address variability in IR is to use lexical query expansion (Lytinen et al. , 2000; Zukerman and Raskutti, 2002).


