So, direct application of (Riloff et al. , 2002) is not suitable for this experiment. 
3 Cross-lingual Information Extraction (Riloff et al. , 2002) present several approaches to cross-lingual information extraction (CLIE). 
Also related are the areas of word alignment for machine translation (Och and Ney, 2000), induction of translation lexicons (Schafer and Yarowsky, 2002), and cross-language annotation projections to a second language (Riloff et al., 2002; Hwa et al., 2002; Mohammad et al., 2007). 
To remedy this problem, we incorporated crosslanguage projection (Riloff et al. , 2002) only for Named Entities. 
(Riloff et al., 2002) extends the ideas in (Yarowsky et al., 2001), by showing how it can be used, in conjunction with an automatically trained information extraction system on the source language, to bootstrap the annotation of resources in the target language. 
