3 The Hinoki Treebank The structure of our treebank is inspired by the Redwoods treebank of English in which utterances are parsed and the annotator selects the best parse from the full analyses derived by the grammar (Oepen et al. , 2002). 
As a test corpus, we use the Redwoods Treebank (Oepen et al. , 2002) which contains 6612 sentences. 
However, despite research on HPSG processing efficiency (Oepen et al. , 2002a), the application of HPSG parsing is still limited to specific domains and short sentences (Oepen et al. , 2002b; Toutanova and Manning, 2002). 
Furthermore, to test the grammar precision and accuracy, we use two treebanks: Redwoods (Oepen et al. , 2002) for English and Hinoki (Bond et al. , 2004) for Japanese. 
The actual annotation process uses the same tools as the Redwoods treebank of English (Oepen et al. , 2002). 
