Whereas a parallel corpus assumes translation equivalence, a comparable corpus is simply a crosslingual pairing of corpora from the same domain (Fung and McKeown, 1997; Rapp, 1999; Tanaka and Matsuo, 1999; Tanaka, 2002).


Indeed, Tanaka (2002) successfully combines synonym-substitution with translation selection and achieves appreciable gains in accuracy.


1 Introduction Modeling term co-occurrence is important for many natural language applications, such as topic segmentation (Ferret, 2002), query expansion (Vechtomova et al. , 2003), machine translation (Tanaka, 2002), language modeling (Dagan et al. , 1999; Yuret, 1998), and term weighting (Hisamitsu and Niwa, 2002).


