Although Matsubara and colleagues did investigate dependency structures in spontaneous speech (Matsubara et al. , 2002), the target speech was dialogues where the utterances were short and sentence boundaries could be easily defined based on turn-taking data.


Dependency parsing is done based on a statistical approach (Matsubara et al. , 2002).


5.1 Experimental Data An in-car speech dialogue corpus which has been constructed at CIAIR (Kawaguchi et al. , 0.4 0.45 0.5 0.55 0.6 0.65 0.7 0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1 weight coefficient <W a c cura cy recall precision Figure 4: Relation between the weight coecient  and the accuracy ( =0.3) 2001), was used as a corpus with intention tags, and analyzed based on Japanese dependency grammar (Matsubara et al. , 2002).


