For instance, these loose (and therefore many) paraphrases are more eective in the case of reluctant processing, where we must necessarily change an expression for various reasons such as our requirement in paraphrase-based machine translation (Yamamoto, 2002).


To resolve this problem, we have proposed a paraphrasing approach in which the utterances are automatically paraphrased prior to transfer (Yamamoto et al. , 2001; Yamamoto, 2002).


