We have been building the Sandglass MT system for the Japanese-Chinese, ChineseJapanese language pairs (Yamamoto et al. , 2001; Zhang and Yamamoto, 2002).


These, however, tend to be rather restricted in their domain (e.g. the ATR English-Chinese paraphrase corpus, which con9 sists of translations of travel phrases (Zhang & Yamamoto, 2002)), are limited to short handcrafted predicates (e.g. the ATR JapaneseEnglish corpus (Shirai, et al. , 2002)), or exhibit quality problems stemming from insufficient command of the target language by the translators of the documents in question, e.g. the Linguistic Data Consortiums Multiple-Translation Chinese Corpus (Huang et al. , 2002).


