Kiss and Strunk (2002a, 2002b) characterize abbreviations as collocations and use Dunnings log-likelihood ratio (log ) to detect them on the type level.


This opinion was, for example, held by a reviewer of Kiss and Strunk (2002a).


(2001) and Kiss and Strunk (2002b), segmentation errors propagate into further components, which rely on accurate sentence segmentation, and subsequent analyses are affected negatively.


