5This observation is at the phrase level and not at the word (Zipf, 1932) or even n-gram level (Ha et al., 2002).


Afterwards, we select and remove a subset of highly informative sentences from U, and add those sentences together with their human-provided translations to L. This process is continued iteratively until a certain level of translation quality is met (we use the BLEU score, WER and PER) (Papineni et al., 2002).


In (Ha et al. , 2002), Zipfs law is extended to words and phrases, showing its validity for syllable-class based languages when conducting the extension.


Another study found that term frequency rank distribution was a better fit Zipfs Law when the term space comprised both words and phrases (Ha et al, 2002).


