During our participation in different international evaluation campaigns such as the TREC Genomics track (Hersh, 2005), the BioCreative initiative (Hirschman et al. , 2005), as well as in our attempts to deliver advanced search tools for biologists (Ruch, 2006) and healthcare providers (Ruch, 2002) (Ruch, 2004), we were more concerned with domain-specific information retrieval in which systems must return a ranked list of MEDLINE records in response to an experts information request.


As for setting the weighting factors, we ob6We use the SMART representation for expressing statistical weighting factors: a formal description can be found in (Ruch, 2002).


Beyond these well-known targets, researchers (see de Bruijn and Martin, 2002, or Hirschman and al. 2002, for a survey) interested in information extraction and retrieval for biomedical applications have mostly focused on studying specific biological interactions (Stapley and Benoit, 2000; Ndellec et al. , 2002; Dobrokhotov et al. , 2003) and related entities (Collier et al. , 2000; Humphreys et al. , 2000; Yu et al. , 2002; Yamamoto et al. , 2003; Albert et al. , 2003) or using terms in biomedical vocabularies (Nazarenko et al. , 2001; Ruch et al. , 2004; Srinivasan and Hristovski, 2004).


Table 1 gives the most common term weighting factors (atc.atn, ltc.atn); the first letter triplet applies to the document, the second letter triplet applies to the query (Ruch, 2002).


