Our developing approach to metaphor handling in the affect detection module is partly to look for stock metaphorical phraseology and straightforward variants of it, and partly to use a simple version of the more open-ended, reasoning-based techniques taken from the ATT-Meta project (Barnden et al. , 2002; 2003; 2004).


We have developed an AI system called ATT-Meta for metaphor interpretation (Barnden et al. , 2002) that employs reasoning within the terms of the source domain using various sources of information including world and linguistic knowledge.


3 Related Work Earlier projects annotating metaphor in corpora include (Martin, 1994) and (Barnden et al. , 2002).


