The concept discovery algorithm is essentially the same as used by (Davidov and Rappoport, 2006) and has some similarity with the one used by (Widdows and Dorow, 2002). 
This metric was reported to be 82% in (Widdows and Dorow, 2002). 
Widdows and Dorow (2002) use a graph model for unsupervised lexical acquisition. 
We took the exact 10 WN subsets referred to as subjects in (Widdows and Dorow, 2002), and removed all multi-word items. 
The evaluation protocol and metrics were very similar to (Davidov and Rappoport, 2006; Widdows and Dorow, 2002) which allowed us to do indirect comparison to previous work. 
