Cahill and Tiberius (2002) use a manually compiled cognate list of Dutch, English and German cognates and extract crosslinguistic phoneme correspondences.


Cahill and Tiberius (2002) is based on mere counts of phoneme correspondences; Kondrak (2003) generates Algonquian phoneme correspondences which are possible according to his translation models; Kondrak (2004) measures if two words are possible cognates; and Knight and Graehl (1998) focus on the back-transliteration of Japanese words to English.


