Bond and Vatikiotis-Bateson (2002) determine a nouns countability preferences from its semantic class, and show that semantics predicts (5-way) countability 78% of the time with their ontology. 
Several researchers have explored automatically learning the countability of English nouns (Bond and Vatikiotis-Bateson, 2002; Schwartz, 2002; Baldwin and Bond, 2003). 
Bond and Vatikiotis-Bateson (2002) determine a nouns countability preferencesas defined in a 5-way classificationfrom its semantic class in the ALT-J/E lexicon, and show that semantics predicts countability 78% of the time. 
Bond and Vatikiotis-Bateson (2002) infer five types of countability distinctions using NT&Ts Japanese to English transfer dictionary, including the categories strongly countable, weakly countable, and plural only. 
In the final system configuration, the system accuracy was 94.6%, comparing favourably with the 78% accuracy reported by Bond and Vatikiotis-Bateson (2002), 89.5% of OHara et al. 
