P06-1041:1	107:175	can be automatically extracted from large corpora of trees or even raw text: prepositions that tend to occur in the vicinity of specific nouns or verbs more often than chance would suggest can be assumed to modify those words preferentially (Volk, 2002).
---------------------------------------------------
P06-2029:2	151:176	Combining both methods can lead to a further improvement (Volk, 2002; Kokkinakis, 2000), a finding confirmed by our experiments.
---------------------------------------------------
P06-2029:3	110:176	The performance achieved falls somewhat short of the highest figures reported previously for PP attachment for German (Volk, 2002); this is at least in part due to our simple model that ignores the kernel noun of the PP.
---------------------------------------------------
P06-2029:4	150:176	Both supervised and unsupervised training procedures for PP attachment have been investigated and compared in a number of studies, with supervised methods usually being slightly superior (Ratnaparkhi, 1998; Pantel and Lin, 2000), with the notable exception of (Volk, 2002), who obtained a worse accuracy in the supervised case, obviously caused by the limited size of the available treebank.
---------------------------------------------------
P06-2029:5	106:176	(Volk, 2002) already suggested that this counting method introduced a general bias toward verb attachment, and when comparing the results for very frequent words (for which more reliable evidence is available from the treebank) we find that verb attachments are in fact systematically overestimated.
---------------------------------------------------
P06-2029:6	154:176	The best result for German achieved so far is the accuracy of 80.89% obtained by (Volk, 2002).
---------------------------------------------------
W06-2112:7	15:234	We investigated similar methods for German (Volk, 2001; Volk, 2002).
---------------------------------------------------
