For comparable English text the figure is considerably less than one percent (Gamon et al. , 2002).


We chose to model extraposition as an iterative movement process from the original attachment site to the next higher node in the tree (for an alternative one-step solution and a comparison of the two approaches see (Gamon et al. , 2002a)).


In contrast, the sentence realization system code-named Amalgam (A Machine Learned Generation Module) (Corston-Oliver et al. , 2002; Gamon et al. , 2002b) employs a series of linguistic operations which map a semantic representation to a surface syntactic tree via intermediate syntactic representations.


We profiled data from various domains (Gamon et al. 2002a) to substantiate this linguistic claim (see Uszkoreit et al. 1998 for similar results).


We exploit the full set of features and attributes available in the analysis, instead of pre-determining a small set of potentially relevant features (Gamon et al. , 2002b).


