6 Related Work The most relevant previous works include word sense translation and translation disambiguation (Li & Li 2003; Cao & Li 2002; Koehn and Knight 2000; Kikui 1999; Fung et al. , 1999), frame semantic induction (Green et al. , 2004; Fung & Chen 2004), and bilingual semantic mapping (Fung & Chen 2004; Huang et al. 2004; Ploux & Ji, 2003, Ngai et al. , 2002; Palmer & Wu 1995).


Consequently, cognitive scientists and computational linguists alike have been interested in the study of semantic mapping between languages (Ploux and Ji, 2003, Dorr et al. , 2002, Ngai et al. , 2002, Boas 2002, Palmer and Wu, 1995).


