The system is guided by the joint actions of the inquiries and choosers of the system (Fawcett, 1987; Matthiessen and Bateman, 1991; Bateman, 2000; Yang & Bateman, 2002).


The ASF of a specific aspect assumed by the present research is, therefore, principally composed of two sets of predicates: one set of predicates for testing temporal relations (Allen, 1984; Yang & Bateman, 2002), another for testing the values, i.e. conceptual features, of parameters associated with the aspect.


