P03-1016:1	16:213	They are used in information retrieval and question answering (Kiyota et al. , 2002; Dragomia et al. , 2001) to bridge the expression gap between the query space and the document space.
---------------------------------------------------
P03-2027:2	36:126	Our system also uses question types, product names, and synonymous expression dictionary as described in (Kiyota et al. , 2002).
---------------------------------------------------
P03-2027:3	66:126	The algorithm is described in (Kiyota et al. , 2002).
---------------------------------------------------
H05-1126:4	51:238	Dialog Navigator (Kiyota et al. , 2002) has been developed at University of Tokyo as a retrieval system for this KB.
---------------------------------------------------
C04-1158:5	44:200	The Dialog Navigator (Kiyota et al. , 2002) was developed in the University of Tokyo as a Table 1: Document set (Knowledge base) Text collection # of texts # of characters Glossary 4,707 700,000 FAQ 11,306 6,000,000 Support articles 23,323 22,000,000 text retrieval system for this knowledge base.
---------------------------------------------------
W03-1610:6	8:186	In information retrieval and question answering, the synonymous words are employed to bridge the expressions gaps between the query space and the document space (Mandala et al. , 1999; Radev et al. , 2001; Kiyota et al. , 2002).
---------------------------------------------------
