Both of these steps, identifying antecedents and parsing sentences into clauses, can be completed, in theory, by automatic, computational methods (Huls, Bos, and Claassen 1995; Nakaiwa and Shirai 1996; Paul and Sumita 2001; Yamura-Takei et al. 2002), but the success rate of these approaches is not high enough to rely on them for completely accurate analyses of this type of corpus at this time.


Semantic constraints (Yamura-Takei et al. , 2002; Yoshino, 2001): If a zero is the subject of eat, its antecedent is probably a person or an animal, and so on.


