2 Automatically Constructed Case Frames We employ automatically constructed case frames (Kawahara and Kurohashi, 2002) for our model of Table 1: Case frame examples (examples are expressed only in English for space limitation.). 
The process of case structure analysis in this table is a similarity-based method (Kawahara and Kurohashi, 2002). 
In addition, existing Japanese dictionaries such as the IPAL (monolingual) dictionary (technology Promotion Agency, 1987) or previously acquired case information reported in (Kawahara and Kurohashi, 2002). 
Whereasverbalcaseframeconstructionusesarguments of each verb (Kawahara and Kurohashi, 2002), nominal case frame construction basically uses adnominal constituents of each noun. 
We construct case frames from a large raw corpus by using the method proposed by Kawahara and Kurohashi (2002), and use them for case structure analysis and zero anaphora resolution. 
