We next tested UDOP on two additional domains from Chinese and German which were also used in Klein and Manning (2002, 2004): the Chinese treebank (Xue et al. 2002) and the NEGRA corpus (Skut et al. 1997). 
The Chinese dependency parser using case structures is evaluated by Penn Chinese Treebank 5.1 (Xue et al., 2002). 
We follow the experimental setup in (Reichart and Rappoport, 2008), running the algorithm on English, German and Chinese corpora: the WSJ Penn Treebank (English), the Negra corpus (Brants, 1997) (German), and version 5.0 of the Chinese Penn Treebank (Xue et al., 2002). 
The PCTB uses Head-driven Phrase Structure Grammar (HPSG) to create Chinese texts with syntactic bracketing (Xia et al, 2000; Xue et al, 2002). 
Lower accuracies have been reported in the literature for Mandarin POS tagging (Tseng et al. , 2005; Xue et al. , 2002). 
