In future work, we would like to classify verbs into alternation classes on a per-token basis (as is done in the approach taken by Gildea (2002)) rather than the per-type we currently employ and also incorporate information about word senses in order to feasibly include verb alternation information in a statistical parser.


Recent years have seen a wealth of research on one important component of semantic interpretationautomatic role labelling (e.g. , Gildea and Jurafsky, 2002; Pradhan et al. , 2004; Hacioglu et al. , 2004, and additional papers from Carreras and Marquez, 2004).


In related unsupervised tasks, Riloff and colleagues have learned case frames for verbs (e.g. , Riloff and Schmelzenbach, 1998), while Gildea (2002) has learned roleslot mappings (but does not apply the knowledge for the labelling task).


