W08-0336:1	12:196	Chinese information retrieval (IR) systems benefit from a segmentation that breaks compound words into shorter words (Peng et al., 2002), paralleling the IR gains from compound splitting in languages like German (Hollink et al., 2004), whereas automatic speech recognition (ASR) systems prefer having longer words in the speech lexicon (Gao et al., 2005).
---------------------------------------------------
D08-1111:2	20:190	There are some researches show that when compound words are split into smaller constituents, better retrieval results can be achieved (Peng et al., 2002a).
---------------------------------------------------
D08-1111:3	15:190	There are many researches on the relationship between word segmentation and Chinese information retrieval (Foo and Li, 2004; Peng et al., 2002a; Peng et al., 2002b; Jin and Wong, 2002).
---------------------------------------------------
W03-1106:4	164:166	It has been found that word segmentation in Chinese text retrieval is tricky and the relationship between word segmentation and retrieval performance is not monotonic (Peng et al. , 2002).
---------------------------------------------------
