W07-1801:1	146:177	We carry compositional semantic interpretation through left-recursion elimination using the same idea as the UNIANCE grammar compiler (Bos, 2002), though our version handles both direct and indirect left-recursion.
---------------------------------------------------
W07-1801:2	141:177	The UNIANCE grammar compiler (Bos, 2002) uses that approach.
---------------------------------------------------
W08-1702:3	26:139	In terms of ideas (though not code), Regulus is a descendent of SRI Internationals CLE and Gemini platforms (Alshawi, 1992; Dowding et al., 1993); other related systems are LKB (Copestake, 2002), XLE (Crouch et al., 2008) and UNIANCE (Bos, 2002).
---------------------------------------------------
