Minimizing word sense ambiguity by focusing on a specific domain was later seen in the work of Liakata and Pulman (2008), who performed hierarchical clustering using output from their KNEXT-like system first described in (Liakata and Pulman, 2002).


In practice, (Liakata and Pulman, 2002) report, it is by no means easy to do this.


Previous work, such as Liakata and Pulman (2002) and Cahill et al.


