Phillips and Riloff (2002) and Pantel and Lin (2002) also describe work on clustering nouns to derivesemantic classes. 
Previous works aimed at identifying  through clusters of words  concepts, sub-topics or themes that are prominent within a corpus of texts (e.g. , Pereira et al. , 1993; Li, 2002; Lin and Pantel, 2002). 
2.3 Evaluation Method Evaluation for hypernymy and synonymy usually uses WordNet (Lin and Pantel, 2002; Widdows and Dorow, 2002; Davidov and Rappoport, 2006). 
For CBC we simply used the same parameter values as reported in (Lin and Pantel, 2002). 
19 semantic clustering (e.g., (Lin, 1998; Lin and Pantel, 2002; Davidov and Rappoport, 2006; Davidov et al., 2007)), however clustering methods may or may not produce the types and granularities of semantic classes desired by a user. 
