It is based on the sense-vs.-clue correlation matrix calculation method we originally developed for unsupervised WSD (Kaji and Morimoto, 2002).


The second one is a newly devised method using the ratio of associated words that suggest each translation equivalent; it was inspired by a research on word-sense disambiguation using bilingual comparable corpora (Kaji and Morimoto 2002).


This can be done by using the sense-vs.-clue correlation algorithm that the author developed for unsupervised word-sense disambiguation (Kaji and Morimoto 2002).


