P04-1033:1	130:141	The TCFP classifier with robustness from noisy data Here, we simply describe the TCFP classifier using the feature projection technique (Ko and Seo, 2002; 2004).
---------------------------------------------------
P04-1033:2	11:141	For example, there are Naive Bayes (McCallum and Nigam, 1998), Rocchio (Lewis et al. , 1996), Nearest Neighbor (kNN) (Yang et al. , 2002), TCFP (Ko and Seo, 2002), and Support Vector Machine (SVM) (Joachims, 1998).
---------------------------------------------------
