Cao and Li (2002) described a new method for base noun phrase translation by using Web data. 
In this paper, we evaluate the approach proposed in (Cao and Li, 2002) by introducing a total scoring function 17 that is based on validating translation candidates directly through the search engine. 
On the other hand, the work of (Cao and Li, 2002; Fung and Yee, 1998; Koehn and Knight, 2002; Rapp, 1995; Rapp, 1999) used the context of w to locate its translation in a second language. 
(Cao and Li, 2002) proposed a method of compositional translation estimation for compounds. 
Cao and Li (2002) propose a new method to translate base noun phrases. 
