The work in [Chen et al. , 2002] generated sentences in 0.28 seconds for an Air-Travel Domain. 
This problem was not discussed in (Chen et al. , 2002). 
Most recently, Chen et al. utilized FERGUS (Bangalore and Rambow, 2000) and attempted to make it more domain independent in (Chen et al. , 2002). 
(Chen et al. , 2002) is the first paper to this authors knowledge that attempts to create a stochastic domain independent generator for dialogue systems. 
[Chen et al. , 2002] John Chen, Srinivas Bangalore, Owen Rambow, and Marilyn A. Walker. 
