Support Vector Machines (SVMs) have shown good performance in various tasks in Natural Language Processing (Kudo and Matsumoto, 2001; Isozaki and Kazawa, 2002; Hirao et al. , 2002).


Furthermore, analyzing the trained ranking models allows us to calculate the weights given to the features (Hirao et al., 2002).


Analyzing the ranking model trained by the ranking SVM allows us to calculate the weights given to the features (Hirao et al. , 2002).


