Also, Roth and Yih (2002) learn a Bayesian network to tag entities and their relations simultaneously. 
The learning algorithm used is a variation of the Winnow update rule incorporated in SNoW (Roth, 1998; Roth and Yih, 2002), a multi-class classifier that is specifically tailored for large scale learning tasks. 
This work can also be viewed as part of a trend to perform joint inference across multiple language processing tasks (Miller et al. , 2000; Roth and tau Yih, 2002; Sutton and McCallum, 2004). 
Roth and Yih (2002) learned the entities and relations together. 
2 SNoW Learning Architecture The learning algorithm used is a variation of the Winnow update rule incorporated in SNoW (Roth, 1998; Roth and Yih, 2002), a multi-class classifier that is specifically tailored for large scale learning tasks. 
