They have also been used to solve the word alignment problem (Garcia-Varea et al. , 2002; Ittycheriah and Roukos, 2005; Liu et al. , 2005), but a sentence-level approach to combining knowledge sources is used rather than a word-level approach.


stance, the IBM models (Brown et al. , 1993) can be improved by adding more context dependencies into the translation model using a ME framework rather than using only p(f j |e i ) (Garcia-Varea et al. , 2002).


