We used BitPar (Schmid, 2004) for our unlexicalized experiments. 
(Schmid, 2004) and (Schiehlen, 2004)), an efficient parser for treebank grammars in order to induce a grammar and parse the treebank. 
We use the BitPar parser (Schmid, 2004) which is based on a bit-vector implementation (cf. 
Compact binarization (Schmid, 2004) tries to minimize the size of the binarized grammar. 
To obtain a parse of each German sentence in the training, dev and test corpora, we employed the IfNLP BitPar probabilistic parser (Schmid, 2004), using models learned from the Tiger Treebank for German. 
