Increasingly, parallel corpora are becoming available for many language pairs and SMT systems have been built for French-English, German-English, Arabic-English, Chinese-English, Hindi-English and other language pairs (Brown et al. , 1993), (AlOnaizan et al. , 1999), (Udupa, 2004).


Decoding is an integral component of all SMT systems (Wang, 1997), (Tillman, 2000), (Och et al. , 2001), (Germann et al. , 2003), (Udupa et al. , 2004).


The models are then used to decode, i.e. translate texts from the source language to the target language 1 (Tillman, 2001), (Wang, 1997), (Germann et al. , 2003), (Udupa et al. , 2004).


