Currently 58.5% of the pairs extracted for nouns are linked to nodes in the Goi-Taikei ontology (Bond et al. , 2004b).


We have constructed a linguistically enriched treebank named Hinoki (Bond et al. , 2004a), which is based on the same framework as the Redwoods treebank (Oepen et al. , 2002) and uses the Japanese grammar JACY (Siegel and Bender, 2002) to construct the treebank.1 In the construction process, we have also encountered the problem just mentioned.


Secondly, we extract words that are judged to belong to a given lexical type and sentences that contains the words (Example (3b)) from the treebank database compiled from the Hinoki treebank (Bond et al. , 2004a).


1 Introduction Treebanks constructed with detailed linguistic information play an important role in various aspects of natural language processing; for example, grammatical knowledge acquisition; world knowledge acquisition (Bond et al. , 2004b); and statistical language model induction.


