Several methods exist to do this  e.g. producing RMRS output from RASP (Briscoe et al., 2006) is described in Frank (2004).


For instance, Copestake (2003) and Frank (2004) use it to specify semantic components to shallow parsers ranging in depth from POS taggers to chunk parsers and intermediate parsers such as RASP (Briscoe et al., 2006).


2.4.1 Robust Minimal Recursion Semantics Robust Minimal Recursion Semantics is a form of flat semantics which is designed to allow deep and shallow processing to use a compatible semantic representation, with fine-grained atomic components of semantic content so shallow methods can contribute just what they know, yet with enough expressive power for rich semantic content including generalized quantifiers (Frank, 2004).


Next, we applied parsing techniques developed for deep parsing, including quick check (Malouf et al. , 2000), large constituent inhibition (Kaplan et al. , 2004) and hybrid parsing with a CFG chunk parser (Daum et al. , 2003; Frank et al. , 2003; Frank, 2004).


HPSG parsing with a CFG chunk parser A hybrid of deep parsing and shallow parsing was recently found to improve the efficiency of deep parsing (Daum et al. , 2003; Frank et al. , 2003; Frank, 2004).


