We rst explain the greedy algorithm applied to text summarization by Filatova and Hatzivassiloglou (2004). 
We introduce conceptual units (Filatova and Hatzivassiloglou, 2004), which compose the meaning of a sentence. 
This system has its roots in event-based summarization (Filatova and Hatzivassiloglou, 2004) for the news domain. 
Filatova and Hatzivassiloglou (2004) rst formulated text summarization as MCKP. 
That is, we can obtain a document comprising a complete answer on the basis of a request (i.e. , reuse an answer to a previous request), or we can obtain individual sentences and then combine them to compose an answer, as is done in multidocument summarization (Filatova and Hatzivassiloglou, 2004). 
