There has been a recent emergence of distancebased language modelling techiques in NLP (Savicki and Hlavacova, 2002; Terra and Clarke, 2004) in which the number of tokens separating words is the essential quantity.


The idea of using distance as an alternative to frequency for modelling language has been touched upon in recent literature (Savicki and Hlavacova, 2002; Terra and Clarke, 2004; Hardcastle, 2005).


Terra & Clarke (2004) use a very similar approach in order to generate a probabilistic language model, where previously n-gram models have been used, The allusion to proximity as a fundamental indicator of lexical association does in fact per863 meate the literature.


To address this problem, a simple significance 2 This constraint, which was independently adopted by Terra & Clarke (2004), has significant computational advantages as it effectively limits the search distance for frequent words.


