In order to tackle this problem, a number of soft pattern matching approaches which aim to improve recall with minimized precision loss have been applied to the linear vector pattern models by introducing a probabilistic model (Xiao et al., 2004) or a sequence alignment algorithm (Kim et al., 2008).


Previous approaches to IE relied on cooccurrence (Xiao et al. , 2004) and dependency (Zhang et al. , 2006) relations between entities.


