Comparable results in the literature are Schiehlens (2004) 81.03% dependency fscore reached on the German NEGRA treebank and Collins et al.s (1999) 80.0% labelled accuracy on the Czech PDT treebank. 
In this way, the parser can learn to associate the subcategorization requirements of a word with its local syntactic context (Schiehlen, 2004). 
A similar improvement has been independently noted by Schiehlen (2004). 
4.4 Discussion Overall, the best-performing model, using Brants smoothing, achieves a labelled bracketing F-score of 76.2, higher than earlier results reported by Dubey and Keller (2003) and Schiehlen (2004). 
1 Introduction There have been a number of recent studies on probabilistic treebank parsing of German (Dubey, 2005; Dubey and Keller, 2003; Schiehlen, 2004; Schulte im Walde, 2003), using the Negra treebank (Skut et al. , 1997) as their underlying data source. 
