Multilingual ontology, such as Eurovoc, is also popular for MLDC (Pouliquen et al., 2004).


We work with the daily clusters computed by the NewsExplorer application (Pouliquen et al. 2004).


To achieve this, we produce three different language-independent vector representations for each cluster (for details, see Pouliquen et al. 2004): a weighted list of Eurovoc subject domain descriptors (eurov, available only for EU languages), a frequency list of person and organisation names (ent), and a weighted list of direct or indirect references to countries (geo).


This optimised threshold was established by evaluating cluster linking in several languages (see Pouliquen et al. 2004).


We additionally enrich the vector space representation of each cluster with country information (see Pouliquen et al., 2004), based on log-likelihood-weighted, automatically recognised and disambiguated location and country names (see Pouliquen et al. 2006).


