H05-1081:1	8:230	It was shown that the identification of such event frames has a significant contribution for many Natural Language Processing (NLP) applications such as Information Extraction (Surdeanu et al. , 2003) and Question Answering (Narayanan and Harabagiu, 2004).
---------------------------------------------------
D09-1133:2	11:236	In particular, the well-defined semantic role labeling (SRL) task has been drawing more and more attention in recent years due to its importance in deep NLP applications, such as question answering (Narayanan and Harabagiu, 2004), information extraction (Surdeanu et al., 2003), and co-reference resolution (Ponzetto and Strube, 2006).
---------------------------------------------------
D07-1002:3	61:241	Our approach is less domain dependent and resource intensive than Narayanan and Harabagiu (2004), it solely employs a dependency parser and the FrameNet database.
---------------------------------------------------
D07-1002:4	23:241	Question answering (QA) is often cited as an obvious beneficiary of semantic 12 role labeling (Gildea and Jurafsky, 2002; Palmer et al. , 2005; Narayanan and Harabagiu, 2004).
---------------------------------------------------
D07-1002:5	49:241	Narayanan and Harabagiu (2004) were the first to stress the importance of semantic roles in answering complex questions.
---------------------------------------------------
W08-1810:6	7:192	Thus, Narayanan and Harabagiu (2004) apply the argument-predicate relationship from PropBank (Palmer et al., 2005) together with the semantic frames from FrameNet (Baker et al., 1998) to create an inference mechanism to improve QA.
---------------------------------------------------
J08-2001:7	16:86	With the advent of supporting resources, SRL has become a well-dened task with a substantial body of work and comparative evaluation (see, among others, Gildea and Jurafsky [2002], Surdeanu et al.[2003], Xue and Palmer [2004], Pradhan et al.[2005a], the CoNLL Shared Task in 2004 and 2005, and Senseval-3 and SemEval-2007).The identication of event frames may potentially benet many natural language processing (NLP) applications, such as information extraction (Surdeanu et al.2003), question answering (Narayanan and Harabagiu 2004), summarization (Melli et al.2005), and machine translation (Boas 2002).Related work on classifying the semantic relations in noun phrases has also been encouraging for NLP tasks (Moldovan et al.2004; Rosario and Hearst 2004).
---------------------------------------------------
H05-1084:8	8:183	The benefit of semantic roles has already been demonstrated for a number of tasks, among others for machine translation (Boas, 2002), information extraction (Surdeanu et al. , 2003), and question answering (Narayanan and Harabagiu, 2004).
---------------------------------------------------
W06-3504:9	20:172	Semantic types and role labelling are helpful in both deep (Tetreault, 2005) and shallow interpretation tasks (Narayanan and Harabagiu, 2004).
---------------------------------------------------
P09-1003:10	11:214	Resolving surface divergence of texts (e.g., voice of verbs and nominalizations) into unified semantic representations, SRL has attracted much attention from researchers into various NLP applications including question answering (Narayanan and Harabagiu, 2004; Shen and Lapata, 2007; buy.v PropBank FrameNet Frame buy.01 Commerce buy Roles ARG0: buyer Buyer ARG1: thing bought Goods ARG2: seller Seller ARG3: paid Money ARG4: benefactive Recipient   Figure 1: A comparison of frames for buy.v defined in PropBank and FrameNet Moschitti et al., 2007), and information extraction (Surdeanu et al., 2003).
---------------------------------------------------
P05-1026:11	133:232	Such interrogations are based on (1) associations between the answer type (e.g. DATE) and the question stem (e.g. when and (2) the relation between predicates, question stem and the words that determine the answer type (Narayanan and Harabagiu, 2004).
---------------------------------------------------
W06-0704:12	14:191	Systems for addressing complex information needs are interesting because they provide an opportunity to explore the role of semantic structures in question answering, e.g., (Narayanan and Harabagiu, 2004).
---------------------------------------------------
P06-2068:13	186:198	These are difficult challenges, but recent work on applying semantic models to QA (Narayanan and Harabagiu, 2004; Lin and Demner-Fushman, 2006a) provide a promising direction.
---------------------------------------------------
W06-3506:14	12:197	One such question answering system (Narayanan andHarabagiu, 2004)takesPropBank/FrameNetannotations as input, uses the PropBank targets to indicate which actions are being described with which arguments and produces an answer using probabilistic models of actions as the tools of inference.
---------------------------------------------------
D08-1055:15	6:129	1 Introduction Recently, predicate argument structure analysis has attracted the attention of researchers because this information can increase the precision of text processing tasks, such as machine translation, information extraction (Hirschman et al., 1999), question answering (Narayanan and Harabagiu, 2004) (Shen and Lapata, 2007), and summarization (Melli et al., 2005).
---------------------------------------------------
W06-3502:16	27:176	Lexical semantic features are known to be helpful in both deep (Tetreault, 2005) and shallow interpretation tasks (Narayanan and Harabagiu, 2004).
---------------------------------------------------
N07-1070:17	10:232	1 Introduction Automatic, accurate and wide-coverage techniques that can annotate naturally occurring text with semantic argument structure play a key role in NLP applications such as Information Extraction (Surdeanu et al. , 2003; Harabagiu et al. , 2005), Question Answering (Narayanan and Harabagiu, 2004) and Machine Translation (Boas, 2002; Chen and Fung, 2004).
---------------------------------------------------
D08-1034:18	15:270	Typical tags include Agent, Patient, Source, etc. and some adjuncts such as Temporal, Manner, Extent, etc. Since the arguments can provide useful semantic information, the SRL is crucial to many natural language processing tasks, such as Question and Answering (Narayanan and Harabagiu 2004), Information Extraction (Surdeanu et al. 2003),  and Machine Translation(Boas 2002).
---------------------------------------------------
W06-0705:19	13:205	Harabagiu, 2004) computed automatically from collections of documents relevant to a scenario in order to approximate the semantic content of a scenario, (Narayanan and Harabagiu, 2004) employed formal models of the interrelated events, actions, states, and relations implicit to a scenario in order to produce ne-grained, contextsensitive inferences that could be used to answer questions.
---------------------------------------------------
D09-1002:20	9:240	Examples include information extraction (Surdeanu et al., 2003), question answering (Narayanan and Harabagiu, 2004), machine translation (Boas, 2005), and summarization (Melli et al., 2005).
---------------------------------------------------
H05-1108:21	7:204	For instance, information extraction (Surdeanu et al. , 2003), question answering (Narayanan and Harabagiu, 2004) and machine translation (Boas, 2002) could stand to benefit from broad coverage semantic processing.
---------------------------------------------------
