Seattle, WA, pp 224--231.</rawString> </citation> <citation valid="true"> <authors> <author>A Esuli</author> <author>F Sebastiani</author> </authors> <title>SentiWordNet: A publicly Available Lexical Resourced for Opinion Mining</title> <date>2006</date> <booktitle>In Proceedings of LREC2006</booktitle> <pages>417--422</pages> <location>Genoa, Italy</location> <contexts> <context> As the example above shows, the Romanian WordNet contains not only the Princeton WordNet specific data but also the IRST DOMAIN (Bentivogli et al, 2004), SUMO (Niles &amp; Pease, 2001) and SentiWordnet (Esuli &amp; Sebastiani, 2006) annotations.


As the example above shows, the Romanian WordNet contains not only the Princeton WordNet specific data but also the IRST DOMAIN (Bentivogli et al, 2004), SUMO (Niles &amp; Pease, 2001) and SentiWordnet (Esuli &amp; Sebastiani, 2006) annotations.


As the example above shows, the Romanian WordNet contains not only the Princeton WordNet specific data but also the IRST DOMAIN (Bentivogli et al, 2004), SUMO (Niles &amp; Pease, 2001) and SentiWordnet (Esuli &amp; Sebastiani, 2006) annotations.


