8 Related Work ILP has been applied to various NLP problems including semantic role labeling (Punyakanok et al. , 2004), which is similar to dependency labeling: both can benefit from verb specific information. 
Punyakanok et al. , (2004) further showed that constituent-by-constituent (Cby-C) tagging is better than P-by-P. 
Some other work paid much attention to the robust SRL (Pradhan et al. , 2005b) and post inference (Punyakanok et al. , 2004). 
7 Related Work ILP has been applied to various NLP problems, including semantic role labeling (Punyakanok et al. , 2004), extraction of predicates from parsetrees (Klenner, 2005) and discourse ordering in generation (Althaus et al. , 2004). 
From the point of view of learning architectures and study of feature relevance, it is also worth mentioning the following recent works (Punyakanok et al. , 2004; Moschitti, 2004; Xue and Palmer, 2004; Pradhan et al. , 2005a). 
