Following Hacioglu (2004), we consider the labeling of semantic roles as a classification problem of dependency relations into one of several semantic roles. 
Similar to the approach taken in Hacioglu (2004), we use a statistical classifier to select from a set of candidate nodes in a dependency tree. 
2.3 Features Some of the features are borrowed from Hacioglu (2004) with some additional features motivated by constituent structure tree-based SRL (Pradhan et al 2005; Xue and Palmer, 2004). 
Hacioglu (2004) utilized predicate-argument structure and map dependency relations to semantic roles. 
In Hacioglu (2004), a simple pruning algorithm is applied to filter out unlikely dependency relation nodes in a dependency tree by only keeping the parent/children/grand-children of the predicate, the siblings of the predicates, and the children/grandchildren of the siblings. 
