The closest to our problem is (Fernandez et al. , 2004b), which discusses classifying certain types of fragments, namely questions of the type Who?, When?, etc.


While some systems that automatically resolve such fragments have recently been developed (Schlangen and Lascarides, 2002; Fernandez et al. , 2004a), they have the drawback that they require deep linguistic processing (full parses, and also information about discourse structure) and hence are not very robust.


It is possible to analyse this as an answer to the question under discussion what shall we organise for the party?, as (Fernandez et al. , 2004a) would do; a question, however, which is only implicitly posed by the previous discourse, and hence this is an example of an NSU that does not have an overt antecedent.


