We build upon the Extensible Dependency Grammar (XDG) (Debusmann et al. , 2004b; Debusmann et al. , 2004a; Debusmann et al. , 2005) model and its CP implementation in Oz (Van Roy and Haridi, 2004), namely the XDG Development Toolkit1 (XDK) (Debusmann et al. , 2004c).


Examples include MeaningText Theory (Melcuk, 1988), Discontinuous Grammar (BuchKromann, 2006), Extensible Dependency Grammar (Debusmann et al., 2004), and the Functional Generative Description (Sgall et al., 1986) which forms the theoretical foundation of the Prague Dependency Treebank (Hajic, 1998).


This type of constraint was used in the development of a rule-based dependency parser (Debusmann et al., 2004).


