We measured the coverage of the construction of TDL semantic representations, in the manner described in a previous study (Bos et al. , 2004). 
3Method In this section, we present a method to derive TDL semantic representations from HPSG parse trees, adopting, in part, a previous method (Bos et al. , 2004). 
Examples include DELPH-IN grammars such as the English Resource Grammar (Flickinger, 2002; Uszkoreit, 2002), the various PARGRAM grammars (Butt et al. , 1999), and the Edinburgh CCG parser (Bos et al. , 2004). 
3 Deep Semantic Analysis 3.1 Semantic Interpretation We use a robust wide-coverage CCG-parser (Bos et al. , 2004) to generate fine-grained semantic representations for each T/H-pair. 
Despite some recent advances in this direction (Bos et al. , 2004), it is still the case that it is hard to obtain deep semantic analyses which are accurate enough to support logical inference (Lev et al. , 2004). 
