Similarly to Fung and Chen (2004) we automatically inducesemanticroleannotationsforatargetlanguage. 
An example bilingual frame We previously proposed using the Chinese HowNet and a bilingual lexicon to map the English FrameNet into a bilingual BiFrameNet (Fung and Chen 2004). 
An exception is Fung and Chen (2004), who also attempt to induce FrameNet-style annotations in Chinese. 
Translation accuracies of the most ambiguous words in FrameNet We compare our results to that of our previous work (Fung and Chen 2004), by using the same bilingual lexicon. 
Our method improves word sense translation precision over Fung and Chen (2004). 
