An exception is the model reported by Kanayama et al.(2004), which uses a component of an existing MT system to identify the aspect argument of a given evaluation predicate.


(Kanayama and Nasukawa, 2004; Hu and Liu, 2004; Tateishi et al. , 2001)).


Varying  from 0.05 to 10The human evaluation result for digital camera domain (Kanayama et al. , 2004).


According to the evaluation of the MT method (Kanayama et al. , 2004), highprecision sentiment analysis had been achieved using the polar atoms and patterns, where the splendid light have-zoom small-LCD  satisfied  high-price a73a27 a9 Inter-sentential Context a54 a54 Intra-sentential Context Figure 2: The concept of the intraand intersentential contexts, where the polarities are perfectly coherent.


This section describes the last two processes, which are based on a deep sentiment analysis method analogous to machine translation (Kanayama et al. , 2004) (hereafter the MT method).


