For each task, two metrics are used, the strict measure and the relaxed measure (see also (Muller and Tannier, 2004)).


We are only able to complete relative dates when it refers to the document creation time, and to infer new relations with the help of composition rules, by saturating the graph of temporal relations (Muller and Tannier, 2004).


494 This choice is explained in more details in (Muller and Tannier, 2004).


