While there has been research on generative summarisation, much of this has been focused on sentence extraction followed by some rewrite operation (e.g., sentence shortening (Vanderwende et al., 2007; Zajic et al., 2006; Conroy et al., 2004), aggregation (Barzilay, 2003) or reference regeneration (Siddharthan et al., 2004; Nenkova and McKeown, 2003)).


On the other hand, the wider variety of grammatical constructions used may motivate more complex syntactic features, for instance as proposed by (Siddharthan et al. , 2004) in sentence clustering.


It has been observed (Siddharthan et al. , 2004) that on average these constructs occur 2.3 times less frequently in human summaries than in machine summaries.


Clustering methods have previously been used for event identification (Hatzivassiloglou et al., 2000; Siddharthan et al., 2004).


