Asahara and Matsumoto (2004) used them as a feature of character-based chunking of unknown words using Support Vector Machines.


Although some previous studies emphasized correct identification of low frequency terms (Nagata, 1999; Asahara and Matsumoto, 2004), it is no longer necessary because very large scale web texts are available today.


Japanese morphological analysis has successfully adopted dictionary-based approaches (Kurohashi et al., 1994; Asahara and Matsumoto, 2000; Kudo et al., 2004).


Asahara and Matsumoto (2004) proposed a technique of SVM-based chunking to identify unknown words from Japanese texts.


