4.1 Retrieval engine and indexing units The easyIR system is a standard vector-space engine (Ruch, 2004), which computes stateof-the-art tf.idf and probabilistic weighting schema.


During our participation in different international evaluation campaigns such as the TREC Genomics track (Hersh, 2005), the BioCreative initiative (Hirschman et al. , 2005), as well as in our attempts to deliver advanced search tools for biologists (Ruch, 2006) and healthcare providers (Ruch, 2002) (Ruch, 2004), we were more concerned with domain-specific information retrieval in which systems must return a ranked list of MEDLINE records in response to an experts information request.


liometrics and related-article search (Tbahriti et al. , 2004) (Tbahriti et al. , 2005), information extraction and passage retrieval (Ruch et al. , 2005b).


