2 Related Work Text Structuring The insertion task is closely related to the extensively studied problem of sentence ordering.3 Most of the existing algorithms represent text structure as a linear sequence and are driven by local coherence constraints (Lapata, 2003; Karamanis et al. , 2004; Okazaki et al. , 2004; Barzilay and Lapata, 2005; Bollegala et al. , 2006; Elsner and Charniak, 2007).


2 Related Work Existing methods for sentence ordering are divided into two approaches: making use of chronological information (McKeown et al. , 1999; Lin 385 and Hovy, 2001; Barzilay et al. , 2002; Okazaki et al. , 2004); and learning the natural order of sentences from large corpora not necessarily based on chronological information (Lapata, 2003; Barzilay and Lee, 2004).


Precedence criterion measures the substitutability of the presuppositional information of segment B (eg, the sentences appearing before sentence b) as segment A. This criterion is a formalization of the sentence-ordering algorithm proposed by Okazaki et al, (2004).


Intrinsic evaluation that involves human judges to rank a set of sentence orderings is a necessary approach to this task (Barzilay et al. , 2002; Okazaki et al. , 2004).


