This can be seen as an extension of the deterministic dependency parser of Nivre and Scholz (2004) to full constituent parsing. 
We also include the dependency accuracy from Yamada and Matsumotos (2003) SVM-based dependency parser, and Nivre and Scholzs (2004) MBL-based dependency parser. 
(2004) and Nivre and Scholz (2004). 
3 Memory-Based Dependency Parsing In the experiments below, we employ a data-driven deterministic dependency parser producing labeled projective dependency graphs,3 previously tested on Swedish (Nivre et al. , 2004) and English (Nivre and Scholz, 2004). 
(2004) (for Swedish) and Nivre and Scholz (2004) (for English). 
