They have been used in three ways: as a postprocess for parse selection (Toutanova et al. , 2005; Riezler et al. , 2000; Riezler et al. , 2002), a preprocess to find more probable bracketing structures (Swift et al. , 2004), and online to rank each constituent produced, as in Tsuruoka et al.


We have used the Collins parser as a preprocessor to extract hypotheses for the three constituents (NP, VP, and ADVP) which in pretests had a precision greater than 60% (Swift et al., 2004).


Much work has been done related to enhancing the ef ciency of deep interpretation systems (Copestake and Flickinger, 2000; Swift et al. , 2004; Maxwell and Kaplan, 1994), which forms the foundation that we build on in this work.


For our comparison we used an excerpt from the Monroe corpus that has been used in previous TRIPS research on parsing speed and accuracy (Swift et al. , 2004) consisting of dialogues s2, s4, s16 and s17.


3 Evaluation Our evaluation data is an excerpt from the Monroe corpus that has been used in previous TRIPS research on parsing speed and accuracy (Swift et al. , 2004).


