Additionally, query words can further be expanded by the concept hierarchy within general-purpose ontologies such as WordNet (Fellbaum, 1998), or automatically constructed ontologies (Yeh et al. , 2004).


A possible solution to reducing the problem is to use a general-purpose ontology 945 such as WordNet (Fellbaum, 1998), or a domainspecific ontology constructed using automatic approaches (Yeh et al. , 2004).


