Moreover, previous experiments on different datasets (Boleda et al. , 2004; Boleda et al. , 2005) provided some evidence that distributional information outperforms morphological information for our task.


In previous research (Boleda et al. , 2004), we developed a three-way classification according to generally accepted adjective properties (see Section 2), and applied a cluster analysis to further examine the classes.


This result backs up previous experimentation with clustering (Boleda et al. , 2004), where half of the event adjectives were systematically clustered together with basic adjectives.11 Pol10Note, however, that in 6 other cases with the same polysemy, syntax does tell them apart from typical object adjectives, and are classified as basic (such as the puntual case discussed above; see discussion in next Section).


