P06-1022:1	61:186	However, since some methods for detecting sentence boundaries have already been proposed (Huang and Zweig, 2002; Shitaoka et al. , 2004), we assume that they can be detected automatically before dependency parsing.
---------------------------------------------------
P06-2042:2	22:130	(Shitaoka et al. , 2004).
---------------------------------------------------
P06-2042:3	101:130	First, we detected sentence boundaries by using the method (Shitaoka et al. , 2004) and analyzed the dependency structure of each sentence by the method described in Section 3.1 without using information on quotations and inserted clauses.
---------------------------------------------------
