Basic models in two translation directions are trained simultaneously where statistics of two directions are shared to learn symmetric translation lexicon and word alignments with high precision motivated by (Zens et al. , 2004) and (Liang et al. , 2006).


Symmetrization can also be realized during alignment model training (Liang et al., 2006; Zens et al., 2004).


Work in (Al-Onaizan and Kishore, 2006; Xiong et al., 2006; Zens et al., 2004; Kumar and Byrne, 2005; Tillmann and Zhang, 2005) modeled the limited information available at phrase-boundaries.


(Zens et al. , 2004) introduced a model featuring a symmetrized lexicon.


These models took advantage of features derived from both training directions, similar to the symmetrized lexicons of (Zens et al. , 2004), including features derived from the HMM model and Model 4.


