van Halteren and Oostdijk, 2004), and possibly also for other text classification tasks, such as language or language variety recognition, genre recognition, or document classification for IR purposes.


3.2 Linguistic Profiling The second classification system was Linguistic Profiling, which was previously shown to be useful for language verification (van Halteren and Oostdijk, 2004), a task which is similar to the current task.


