Many publications (Cavar et al. , 2004; Brent et al. , 1995; Goldsmith et al. , 2001; Dejean, 1998; Snover et al. , 2002; Argamon et al. , 2004; Goldsmith, 2001; Creutz and Lagus, 2005; Neuvel and Fulop, 2002; Baroni, 2003; Gaussier, 1999; Sharma et al. , 2002; Wicentowski, 2002; Oliver, 2004), and various other works by the same authors, describe strategies that use frequencies, probabilities, and optimization criteria, often Minimum Description Length (MDL), in various combinations.


, 2002; Clark, 2001; KazakovandManandhar, 1998; Dejean, 1998; Oliver, 2004; Creutz and Lagus, 2002; Creutz and Lagus, 2003; Creutz and Lagus, 2004; Hirsimaki et al. , 2003; Creutz and Lagus, 2005; Argamon et al. , 2004; Gaussier, 1999; Lehmann, 1973; Langer, 1991; Flenner, 1995; Klenk and Langer, 1989; Goldsmith, 2001; Goldsmith, 2000; Hu et al. , 2005b; Hu et al. , 2005a; Brent et al. , 1995), as they are described, have threshold-parameters of some sort, explicitly claim not to work well for an open set of languages, or require noise-free all-form input (Albright, 2002; Manning, 1998; Borin, 1991).


Several researchers propose algorithms based on the minimum description length (MDL) principle, achieving reasonable success in discovering regular morphological patterns (Brent et al. , 1995; Goldsmith, 2000; Creutz and Lagus, 2002; Argamon et al. , 2004).


