The motivation for leaving aside segmenting were both practical  previous discourse parsing efforts (Soricut and Marcu, 2003; LeThanh et al., 2004) already provide alternatives for standalone segmenting tools  and scientific, namely, the greater need for improvements in labeling.


In accord with previous research (Soricut and Marcu, 2003; Reitter, 2003b; LeThanh et al., 2004), we turned all nary rhetorical relations into nested binary relations (a trivial graph transformation), resulting in more algorithmically manageable binary trees.


Our paraphrase generator links an existing general-purpose discourse parser  DAS (Le Thanh et al. , 2004)2  which builds a discourse tree automatically from an input text, to an existing NLG system ICONOCLAST (Power et al. , 2003)  which generates a wide range of 2Similar parsers have been developed by Marcu (2000) and Corston-Oliver (1998) 78 formulations for a given discourse structure.


