where S is the stack that keeps the words being under consideration, I is the list of reDA RA CR (Yamada and Matsumoto, 2003) 90.3 91.6 38.4 (Nivre and Scholz, 2004) 87.3 84.3 30.4 (Isozaki et al. , 2004) 91.2 95.7 40.7 (McDonald et al. , 2005) 90.9 94.2 37.5 (McDonald and Pereira, 2006) 91.5 N/A 42.1 (Corston-Oliver et al. , 2006) 90.8 93.7 37.6 Our Base Parser 90.9 92.6 39.2 Table 2: Comparison of parser performance.


Dependency parsing has been actively studied in recent years (Yamada and Matsumoto, 2003; Nivre and Scholz, 2004; Isozaki et al. , 2004; McDonald et al. , 2005; McDonald and Pereira, 2006; Corston-Oliver et al. , 2006).


Such solution had also been applied to English Treebank where a polynomial kernel SVM was used (Isozaki et al., 2004).


As observed by (Isozaki et al. , 2004), incorporating both top-down (root find) and bottomup (base-NP) can yield better improvement over the Yamadas parsing algorithm.


