Goto et al.(2004) proposed a similar method, utilizing surrounding characters.


Most previous studies have focused on backtransliteration (Knight and Graehl, 1998; Goto et al., 2004), which has the goal of generating a source word (s) for a Japanese term (t).


However, ouraccuracylevels were at least as good as those in previous studies (64% by (Knight and Graehl, 1998) and 87.7% by (Goto et al., 2004)).


