P08-1096:1	12:242	An alternative learning model that can overcome this problem performs coreference resolution based on entity-mention pairs (Luo et al., 2004; Yang et al., 2004b).
---------------------------------------------------
P08-1096:2	232:242	This supports the claims in (Yang et al., 2004a) that coreferential information is an important factor to evaluate a candidate antecedent in pronoun resolution.
---------------------------------------------------
P08-1096:3	40:242	Different from (Luo et al., 2004), the entitylevel features are computed using a Most-X strategy, that is, two given entities would have a feature X, if most of the mention pairs from the two entities have the feature X. Yang et al.
---------------------------------------------------
D09-1101:4	20:257	(2004), Yang et al.
---------------------------------------------------
D09-1101:5	61:257	In Yang et al.s (2004) entity-mention model, a training instance is composed of an active mention mk, a preceding cluster C, and a mention mj in C that is closest in distance to mk in the associated text.
---------------------------------------------------
D09-1101:6	111:257	Motivated by previous work (Luo et al., 2004; Culotta et al., 2007; Yang et al., 2008), we create cluster-level features from mention-pair features using four predicates: NONE, MOST-FALSE, MOST-TRUE, and ALL.
---------------------------------------------------
D09-1101:7	41:257	While entity-mention models have previously been shown to be worse or at best marginally better than their mention-pair counterparts (Luo et al., 2004; Yang et al., 2008), our cluster-ranking models, which are a natural extension of entity-mention models, significantly outperformed all competing approaches.
---------------------------------------------------
