4 Previous Work Much of the work involving comparable corpora has focused on extracting word translations (Fung and Yee, 1998; Rapp, 1999; Diab and Finch, 2000; Koehn and Knight, 2000; Gaussier et al. , 2004; Shao and Ng, 2004; Shinyama and Sekine, 2004). 
(Shinyama and Sekine, 2004) used the idea to discover NEs, but in a single language, English, across two news sources. 
The extraction proceeds either iteratively by starting from a few seed extraction rules (Collins and Singer, 1999), or by mining named entities from comparable news articles (Shinyama and Sekine, 2004) or from multilingual corpora (Klementiev and Roth, 2006). 
(Shinyama and Sekine, 2004) used the idea to discover NEs, but in a single language, English, across two news sources. 
Besides, as we want to focus on corpus-specific NEs, our work is also related to (Shinyama and Sekine, 2004). 
