Case element remembers the bi-lexical dependency relation between all types of headmodifier pairs, which is also recognized in previous work (Wu, 2003; Han et al., 2004; Kawahara and Kurohashi, 2006(a); Abekawa and Okumura, 2006).


In this paper, we propose a new type of Chinese case structure, which is different from those presented in previous work (Wu, 2003; Han et al., 2004; Kawahara and Kurohashi, 2006(a); Abekawa and Okumura, 2006) in two aspects: (1) It relaxes the predicate of a case structure to be all types of words which behaves as a head; (2) It is not categorized by semantic roles but marked by the neighboring modifiers attached to a head.


al, 2002), and Chinese (Han et al, 2004).


At present, automatically acquired verb lexicons with SCF information have already proved accurate and useful enough for some NLP purposes (Korhonen, 2001; Han et al, 2004).


