The queries in this corpus are more complex than those in the ATIS database-query corpus used in the speech community (Zue and Glass, 2000) which makes the GEOQUERY problem harder, as also shown by the results in (Popescu et al. , 2004).


These systems support preferably task oriented dialog systems, e.g., the ATIS task as in (Popescu et al. , 2004) and (Milward, 2000), or virtual world scenarios (Gorniak and Roy, 2005), which do not have to deal with uncertain visual input.


Some of the previous work on semantic parsing has focused on fairly simple domains, primarily, ATIS (Air Travel Information Service) (Price, 1990)whosesemanticanalysisisequivalenttofilling a single semantic frame (Miller et al. , 1996; Popescu et al. , 2004).


