The first algorithm is TV_LinkA which takes CS and CD into consideration and performs well (Yang et al., 2008).


Relevance between term candidate and sentences, referred to as CS, is calculated using the TV_HITS (Term Verification  HITS) algorithm proposed in (Yang et al., 2008) based on  Hyperlink-Induced Topic Search (HITS) algorithm (Kleinberg, 1997).


For comparison to previous work, all term candidates are extracted from the same domain corpora using the delimiter based algorithm TCE_DI (Term Candidate Extraction  Delimiter Identification) which is efficient according to (Yang et al., 2008).


