W09-1901:1	24:147	2 Anaphora resolution model We have inplemented a probabilistic model for anaphora resolution in the biomedical domain (Gasperin and Briscoe, 2008).
---------------------------------------------------
W09-1901:2	47:147	For more detail on the decomposition process refer to (Gasperin and Briscoe, 2008).
---------------------------------------------------
D09-1151:3	7:264	Bridging anaphora (Clark, 1975) represents a special part of the general problem of anaphora resolution, which has been studied and discussed for various languages and domains (Hahn et al., 1996; Murata et al., 1999; Poesio et al., 2004; Gasperin and Vieira, 2004; Gasperin and Briscoe, 2008).
---------------------------------------------------
W09-1418:4	185:209	We expect that several studies addressing anaphora resolution in biomedical text (Castano et al., 2002; Gasperin and Briscoe, 2008) will inform our near future efforts in this area.
---------------------------------------------------
