Identifying and extracting such attributes relative to a set of flat (i.e., nonhierarchically organized) labeled classes of instances has been extensively studied, using a variety of data, e.g., Web search query logs (Pasca and Van Durme, 2008), Web documents (Yoshinaga and Torisawa, 2007), and Wikipedia (Suchanek et al., 2007; Wu and Weld, 2008).


Previous literature in attribute extraction takes advantage of a range of data sources and extraction procedures (Chklovski and Gil, 2005; Tokunaga et al., 2005; Pasca and Van Durme, 2008; Yoshinaga and Torisawa, 2007; Probst et al., 2007; Van Durme et al., 2008; Wu and Weld, 2008).


