Please note that our approach is very different from other approaches to context dependent rule selection such as (Ittycheriah and Roukos, 2007) and (He et al., 2008). 
Thus, we can compute the source dependency LM score in the same way we compute the target side score, using a procedure described in (Shen et al., 2008). 
In (He et al., 2008), lexical 72 features were limited on each single side due to the feature space problem. 
2 Linguistic and Context Features 2.1 Non-terminal Labels In the original string-to-dependency model (Shen et al., 2008), a translation rule is composed of a string of words and non-terminals on the source side and a well-formed dependency structure on the target side. 
In (Post and Gildea, 2008; Shen et al., 2008), target trees were employed to improve the scoring of translation theories. 
