We define a unary template as a template consisting of one argument slot and one predicate, following Szpektor and Dagan (2008). 
In our framework we follow (Szpektor and Dagan, 2008) and use only rules between unary templates, containing a single argument. 
As defined in earlier works, an entailment rule specifies an inference relation between an entailing template and an entailed template, where templates are parse subtrees with argument variables (Szpektor and Dagan, 2008). 
Szpektor and Dagan (2008) also proposed a unary template, which is defined as a template consisting of one argument slot and one predicate phrase. 
We acquired a rule-set containing the top 300 rules for every unary template in the Reuters RCV1 corpus5 by implementing the unary-DIRT algorithm (Szpektor and Dagan, 2008), which was shown to have relatively high recall compared to other algorithms. 
