(2008) test their approach on relatively simple and objective  categories  like  states,  countries (both 836 closed sets), singers and fish (both open, the former more so than the latter), but not on complex categories in which members are tied both to a general category, like food, and to a stereotypical property, like sweet (Veale and Hao, 2007).


Veale and Hao (2008) go on to argue that similes offer a very concise snapshot of those widely-held beliefs that are the cornerstone of everyday reason1 2 3 4 5 0.40 0.45 0.50 0.55 0.60 0.65 0.70 0.75 0.80 0.85 0.90 WordNet Simile ConceptNet Bootstrapping Cycle Co ve ra ge 1 2 3 4 5 0.40 0.50 0.60 0.70 0.80 0.90 1.00 WordNet Simile ConceptNet Poesio & Alm.


Furthermore, bootstrapping from the simile seed yields higher cluster accuracy on the 402noun data-set than Veale and Hao (2008) themselves achieve with their simile data on the same test-set (69.85%).


