When this assumption fails, one can parse opinions at a finer-level 2http://www.nist.gov/tac/ (Jindal and Liu, 2006; Stoyanov and Cardie, 2008) In this study, we look at an extractive summarization setting where S is built by extracting representative bits of text from the set D, subject to pre-specified length constraints. 
The term topic has also been used by some researchers (e.g., Kim and Hovy, 2004; Stoyanov and Cardie, 2008). 
(Hu and Liu, 2004; Popescu and Etzioni, 2005; Kobayashi, Inui and Matsumoto, 2007; Stoyanov and Cardie, 2008) have studied topic/feature extraction. 
The problem of automatically identifying features or topics being spoken about in a sentence has been studied in (Hu and Liu, 2004; Popescu and Etzioni, 2005; Stoyanov and Cardie, 2008). 
Stoyanov and Cardie (2008) work on opinion co-reference; however, we need to identify the specific target. 
