Turney (2008) is the first, to the best of our knowledge, to raise the issue of a unified approach. 
Turney (2008) has recently proposed a simpler SVM-based algorithm for analogical classification called PairClass. 
Turney (2008) argues that many NLP tasks can be formulated in terms of analogical reasoning, and he applies his PairClass algorithm to a number of problems including SAT verbal analogy tests, synonym/antonym classification and distinction between semantically similar and semantically associated words. 
2 Related work Turney (2008) recently advocated the need for a uniform approach to corpus-based semantic tasks. 
In NLP community, it has been shown that having more data results in better performance (Ravichandran et al., 2005; Brants et al., 2007; Turney, 2008). 
