D09-1027:1	65:269	Wan and Xiao (Wan and Xiao, 2008b) use a small number of nearest neighbor documents to provide more knowledge to improve graph-based keyphrase extraction algorithm for single document.
---------------------------------------------------
D09-1027:2	66:269	Motivated by similar idea, Wan and Xiao (Wan and Xiao, 2008a) propose to adopt clustering methods to find a small number of similar documents to provide more knowledge for building word graphs for keyword extraction.
---------------------------------------------------
D09-1027:3	72:269	As described in (Wan and Xiao, 2008b), when two annotators were asked to label keyphrases on 308 documents, the Kappa statistic for measuring interagreement among them was only 0.70.
---------------------------------------------------
