Due to its strict compositional nature, TErequiresanaccuratesemanticanalysisofallsentence parts, since, for example, one misanalysed negation or counterfactual embedding can invert the entailment status (MacCartney and Manning, 2008).


However, entailment relations are more sensitive to the contribution of individualwords(MacCartneyandManning,2008).


lists of DE(ND) operators that are used by textualentailment systems are significantly smaller than that depicted in Table 1; for example, MacCartney and Manning (2008) use only about a dozen (personal communication).


(This list is based on the list of DE operators used by the RTE system presented in MacCartney and Manning(2008).)


Yet to date, only a few systems attempt to handle the phenomenon in a general way, i.e., to consider more than simple direct negation (Nairn, Condoravdi, and Karttunen, 2006; MacCartney and Manning, 2008; Christodoulopoulos, 2008; Bar-Haim, Berant, Dagan, Greental, Mirkin, Shnarch, and Szpektor, 2008).


