N09-1066:1	19:220	More recently, Qazvinian and Radev (2008) argue that citation texts are useful in creating a summary of the important contributions of a research paper.
---------------------------------------------------
N09-1066:2	109:220	4.3 Cluster Summarizers: C-LexRank, C-RR Two clustering methods proposed by Qazvinian and Radev (2008)C-RR and C-LexRankwere used to create summaries.
---------------------------------------------------
N09-1066:3	65:220	Citation texts have also been used to create summaries of single scientific articles in Qazvinian and Radev (2008) and Mei and Zhai (2008).
---------------------------------------------------
N09-1066:4	143:220	This evaluation approach is similar to the one adopted by Qazvinian and Radev (2008), but adapted here for use in the multi-document case.
---------------------------------------------------
