This is a safe assumption to make as the non-projectivity in English is only used to account for Long-Distance Dependencies and such cases are low in number (Guo et al., 2008).


However, our approach is still tractable because of the low values of n. We plan to reduce the search space complexity by using Viterbi search (Guo et al., 2008), and examine the drop in results because of that.


Our work is similar to a recently published work by Guo (Guo et al., 2008).


Guo (Guo et al., 2008) conduct their experiments by considering gold data as input.


We have taken the Table-3 from (Guo et al., 2008), which shows the BLEU scores of different Paper BLEU score Langkilde(2002) 0.757 Nakanishi(2005) 0.705 Cahill(2006) 0.6651 Hogan(2007) 0.6882 White(2007) 0.5768 Guo(2008) 0.7440 Our Model 0.8156 Table 3: Comparsion of results for English WSJ section 23 systems on section 23 of PTB.


