This is perhaps unsurprising, as the finer-grained distinctions in corpora seem to be based on lexical properties more than on additional context (see, e.g., Dickinson, 2008). 
Dickinson, 2008). 
It has been recognized for some time that wider contexts result in better induction models (e.g., Parisien et al., 2008; Redington et al., 1998), but many linguistic distinctions rely on lexical information that cannot be inferred from additional context (Dickinson, 2008), so focusing on short contexts can provide many insights. 
Dickinson, 2008). 
The use of frames allows for frequent recurrent contexts and awaytoinvestigatecorpuscategories, orPOStags (cf., e.g., Dickinson and Jochim, 2008). 
