The results of other methods, such as SaRAD, NT, and OZ, are reproduced for this corpus based on their papers (Okazaki et al., 2008).


We prepared six state-of-the-art abbreviation recognizers as baselines: Schwartz and Hearsts method (SH) (2003), SaRAD (Adar, 2004), ALICE (Ao and Takagi, 2005), Chang and Schutzes method (CS) (Chang and Schutze, 2006), Nadeau and Turneys method (NT) (Nadeau and Turney, 2005), and Okazaki et al.s method (OZ) (Okazaki et al., 2008).


