c 2009 Association for Computational Linguistics Positive Results for Parsing with a Bounded Stack using a Model-Based Right-Corner Transform William Schuler Dept. of Computer Science and Engineering Minneapolis, MN schuler@cs.umn.edu Abstract Statistical parsing models have recently been proposed that employ a bounded stack in timeseries (left-to-right) recognition, using a rightcorner transform defined over training trees to minimize stack use (Schuler et al., 2008).


1 Introduction Statistical parsing models have recently been proposed that employ a bounded stack in time-series (left-to-right) recognition, in order to directly and tractably incorporate incremental phenomena such as (co-)reference or disfluency into parsing decisions (Schuler et al., 2008; Miller and Schuler, 2008).


As mentioned above, both Hale and colleagues (2006) and Miller and Schuler (2008) showed that speech repairs contain syntactic regularities, which can improve the parsing of transcribed speech with repairs when modeled properly.


constituents in fluent and disfluent speech can also improve parsing accuracy (Miller and Schuler, 2008).


