We proposed a probabilistic model for Japanese zero anaphora resolution based upon case frames (Sasano et al., 2008). 
P(ICAk|ENT,CFl,DCAk) denotes the probability to generate indirect case assignment when existing discourse entities, a case frame and 4For details see (Sasano et al., 2008). 
3 Probabilistic Model In this study, we apply a lexicalized probabilistic model for zero anaphora resolution proposed in (Sasano et al., 2008) to associative anaphora resolution. 
For details see (Sasano et al., 2008). 
Here, we introduce our model for zero anaphora resolution (Sasano et al., 2008). 
