All of the translations I)roduced 1)3: the various engines a,re pla.ced in a chart data struci;ure (Kay, 1967; Winograd, 1983), indexed by the'Jr position i\]\] the input uttera.nce. 
The parser and function processor are USAGE (User Application Generator), developed at the IBM Paris Scientific Center, along the principles of Kay (1967), with considerable modifications and extensions. 
Cstructure construction is based on a chart parser, that allows the system to represent syntactic ambiguities (Kay, 1967), (Winograd, 1983). 
The most important is a non-deterministic tree transducer, implementing a general re-write system, which does not differ in any interesting way from Colmerauer's Q-system (1971) or Kay's powerful parser (1967). 
Assuming that indices are just unbound variables (thus coindexing is unification and contraindexing is an inequality constraint), an interesting technical problem arises if the basic parsing engine uses a chart (Kay 1967, 1980). 
