Borkowski, C. , "An Experimental System for Automatic Identification of personal Nsm~s and Personal Titles in Newspaper Te~ts", American Docgmentation~ 18 (No. 3): 131-138 (1967).


Borkowski, C. , "An Experimental System for Autnmatic Recognition of Personal Names in Newspaper Texts", Deuxieme Conference International sur le TTaitement Autcmatique des Laugues (Proceedings), (Section 25: 1-15), Grenoble (1967).


