We conclude this paper by raising an issue that was already discussed by Gammon (1969), and might well be tackled with our methodology.


The second approach is based on the predictability strategy, which assumes that speech should be segmented at locations where some measure of the uncertainty about the next symbol (phoneme or syllable for instance) is high (Harris, 1955; Gammon, 1969; Sa ran et al. , 1996; Hutchens and Adler, 1998; Xanthos, 2003).


2 Description of the algorithms 2.1 Segmentation by thresholding Many distributional segmentation algorithms described in the literature can be seen as instances of the following abstract procedure (Harris, 1955; Gammon, 1969; Sa ran et al. , 1996; Hutchens and Adler, 1998; Bavaud and Xanthos, 2002).


