Some examples of initial trees are (for simplicity, we have omitted unification equations associated with the trees): 5 4In some earlier work of Joshi (1969, 1973), the use of the two operations 'adjoining' and 'replacement' (a restricted case of substitution) was investigated both mathematically and linguistically.


Examples of auxiliary trees (they are predicates taking sentential complements, 8-10, or modifiers, 11-12): S S S NPo$ VP NPo$ VP NPo$ VP S N A A (9) ~ (10) A (11) A V Sl (8) V Sl V NPi$ S2 Adv S A N I I I I I thinks saw promise maybe beautiful (12) 2In some earlier work of Joshi (1969, 1973), the use of the two operations 'adjoining' and 'replacement' (a restricted case of substitution) was investigated both mathematically and linguistically.


