3.1 Hewson's Proto-Algonkian Experiment The "proto-projection" techniques used by RE were implemented earlier by John Hewson and others at the Memorial University of Newfoundland (Hewson 1973, 1974).


Recognizing that "the end result of such a programme would be almost nil" (Hewson 1973:266), the team developed another approach in which the program generated all possible proto-projections for the 3,403 modern forms.


The opposition of upstream and downstream, suggested to us by John Hewson, one of the developers of the first "Electronic Neogrammarian," (Hewson 1973) is much more intuitive.


PEQTAAXKWIHCINWA BUMP (*-AAXKW) M (Menomini) P3QTAAHKIHSEN HE BUMPS INTO A TREE OR SOLID  O (Ojibwa) PATTAKKOCCIN BUMP/KNOCK AGAINST \[STHG\] Figure 6 Proto-Algonkian cognate set (after Hewson 1973:273).


