P84-1105:1	10:95	provide semantic representations that are produced as an interim data structure of their Japanese/English MT system ATLAS/II (Uchida & Sugiyama, 1980).
---------------------------------------------------
C92-2117:2	19:184	An interlingual approach (e.g. Uchida and Sugiyama (1980), Lytinen and Shank (1982), R6sner (1986), Nirenburg et al.
---------------------------------------------------
