5 A primary area of activity during the 1980s involved attempts to automatically extract lexical and semantic knowledge bases from MRDs (Michiels, Mullenders, and No61 1980; Calzolari 1984; Chodorow, Byrd, and Heidon 1985; Markowitz, Ahlswede, and Evens 1986; Byrd et al. 1987; Nakamura and Nagao 1988; Klavans, Chodorow, and Wacholder 1990; Wilks et al. 1990).


(ed), STUDIES IN SYNTAX AND SI~4ANTICS, D. Reidel, Dordrecht, Holland, 1969 Michiels 1982 = Michiels, A. , EXPLOITING A IARGE DICTIONARY DATA BASE, Ph D thesis, University of Liege, 1982 (mimeographed) Michiels et al. 1980 = Michiel$, A. , Mullemxlers, J. , No~l, J. , Exploiting a large data base by Longman) in COLING 80, 1980, p. 573-582 Michiels et al. 1981 = Michiels, A. , No~l, J).


