Weischedel and Black (1980) allow for such cases by having each instance of a test individually predicated. 
Because control is such an important issue, thorough, rigorous empirical studies are Many alternatives exist for these decisions; an overview of them appears in Sondheimer and Weischedel (1980). 
Currently, we use a method also used by Weischedel and Black (1980) of selecting the alternative with the longest path, i.e., the one with the deepest penetration in the network. 
The theme of the final point is further developed in Sondheimer and Weischedel (1980). 
This is similar to a method of Weischedel and Black (1980). 
