I. The approach The empirical analysis of discourse and the formal representation of vague word meanings in natural language texts as a system of interrelated concepts (RIEGER 1980) is based on a WITTGENSTEINian assumption according to which a great number of texts analysed for any of the employed terms' usage regularztie~ will reveal essential parts of the concepts and hence the meanings conveyed.


It has been shown elsewhere (RIEGER 1980), that in a sufficiently large sample of pragmatically homogeneous texts,called corpus, only a restricted vocabulary, i.e. a limited number of lexical items will be used by the interlocutors however comprehensive their personal vocabularies in general might be.


