2.1 Functional Collocations (2,174) We call expressions which work like a particle relational collocation and expressions which work like an auxiliary verb at the end of the predicate auxiliary predicative collocation \[Shudo, K. et al., 1980\].


The technological framework of the system is based on extended bunsetsu (ebunsetsu) model \[Shudo, K. et al., 1980\] for the unit of the segmentation of the input Kana string, and on minimum cost method \[Yoshimura, K. et al., 1987\] combined with Viterbi's algorithn~ \[Viterbi, A,, J., 19671 for the reduction of the ambiguity of the segmentation.


(Shudo et al. , 1980, 1988; Shudo, 1989; Yasutake et al. , 1997).


We leave its detail to (Shudo et al. , 1980).


