Explicitation sets the stage for representing the meaning of a proposition through the use of test-score semantics (Zadeh, 1978, 1982).


As a simple illustration, consider the familiar example d A snow is white which we interpret as a disposition whose intended meaning is the proposition p A usually snow is white . To represent the meaning of p, we assume that the ezplanatory database, EDF (Zadeh, 1982), consists of the following relations whose meaning is presumed to be known EDF A WHITE \[Sample;p\] + USUALLY\[Proportion;p\], in which + should be read as and.


First, the suppressed fuzzy quantifiers in d are restored, resulting in a fuzzily quantified proposition p. Then, the meaning of p is represented -through the use of test-score semantics (Zadeh, 1978, 1982) as a procedure which acts on a collection of relations in an explanatory database and returns a test score which represents the degree of compatibility of p with the database.


