Therefore, we have taken inspiration from a simple model of semantic network ; for the same reasons, the initial parser based on an Augmented Transition Network (Woods, 1970) and implemented on an IBM 370 (Memmi and Mariani, 1982) was replaced by another less timeand memory-consuming one.


In the same time, the amelioration of the microprocessor technology has allowed the implantation of word recognition and text-to-speech synthesis systems on single boards (Li~nard and Mariani, 1982 ; Gauvain, 1983 ; Asta and Li~nard, 1979) ; in our laboratory, such modules have been integrated into a compact unit that forms an autonomous vocal processor which has applications in a number of varied domains : vocal command of cars, of planes, office automation and computer-aided learning (N~el et al. , 1982).


