Some work continues at BYU, but at a very much reduced level and degree of aspiration (e.g. , Melby 1982).


A.Melby (1982), "Mul t l-level translation aids in a dlstr Ibuted system", Proceedings COLING82, North-Holland, 215-220, Prague, July 82.


This sort of system is different from the widely promoted 'Translator's Workbench' idea (e.g. Kay 1980, Melby 1982), the main aims of which are to help translators to translate texts.


19\] Melby, A. K., (1982).


