If a machine translation system uses analysis-tree structures as intermediate structures (Lehmann et al. 1981; Nitta et al. 1982), wide-range restructuring can be introduced appropriately at the surface level.


14 ~16\] for a good survey and discussion on this problem; and see also \[Nitta, et al. 1982\] for the discussion on a typical (classical) structure-bound translation mechanism,i.e, local rearrangement method).


