Consider the following requests from PEARL (Lehnert and Shvartz 1982; Shwartz 1982) when it operates in the domain of geological map generation: 60 (3) Show ss ell oil veils from 1970 to 1980.


EXPLORER: A Natural Language Processing System for Oil Exploration Wendy G. Lehnert Department of Computer and Information Sciences Graduate Research Center University of Massachusetts Amherst, Mass. 01003 Steven P. Shwartz Cognitive Systems Inc. 234 Church Street New Haven, Ct. 06510 EXPLORER (Lehnert and Sbwartz, 1982; Shwartz 1982) is a non-fragile, 'bands-on" language analysis system that allows oil explorationists with no knowledge of computers or computer progra-.-ing to create customized maps.


