In addition, while there are many proposals in the literature for algorithms for dialogue strategies that are cooperative, collaborative or helpful to the user (Webber and Joshi, 1982; Pollack, Hirschberg, and Webber, 1982; Joshi, Webber, and Weischedel, 1984; Chu-Carrol and Carberry, 1995), very few of these strategies have been evaluated as to whether they improve any measurable aspect of a dialogue interaction.


Webber and Joshi (1982) have noted the importance of a cooperative system providing support for its responses.


