Incremental Generation Incremental generation has been introduced (Kempen and Hoenkamp 1982) on psychological grounds, and several reports of surface generators have emphasised this property (e.g. Reithinger, 1991, de Smedt and Kempen, 1991, van de Veen forthcoming).


EXPERIMENTS WITH OTHER GENERATION MODULES We recently studied three generation modules (running in Lisp on our SYMBOLICS 3600) with the objective to find out, whether they could serve as a generation front end for SEMSYN: SUTRA (Busemann, 1983), the German version of IPG (Kempen & Hoenkamp, 1982), and MUMBLE (McDonald, 1983).


(Kempen and Hoenkamp 1982)).


