Lexical resources for computer use thus need considerable manipulation, customisation, and supplementation (e.g. Calzolari, 1982).


After the first work on machine-readable dictiona,'ies (MRI)s) in the seventies (see Olney 1972, Sherman 1974), and with the recent development oI~the concept of'a lexical database (l.l)B) in which interaction, flexibility and multidiinensionality can be achieved, but everything must be explicitly stated in advance (see e.g. Amsler 1980, Byrd 1983, Calzolari 1982, Michiels 1980), a new possibility which is now emerging is that o1" a procedural exploitation of the lull range of semantic intbrmation implicitly contained in MRI)s (see Wilks 1987, Binot 1987, Alshawi forthcoming, Calzolari forthcoming).


