The experimental system of automatic question-answering T\[BAQ (Text-and-Inference Based Answering of Questions, cf, Sgall 1982, Hajicova and Sgall 1984) has no prearranged data base, its input consisting only of natural language sentences (statements) from technical texts.


In this enriched set suitable TR's for direct and indirect answers to the given question are retrieved, and then transfered by a synthesis procedure into the output (surface) form if sentences (for an outline of the method as such, see Haji~ov~, 197~; 3aji~ov~ and Sgall, 19~i; Sgall, 1982).


