Within all modern M(A)T systems, including EUROTRA (now in the specification phase), a text is viewed, from an ~IJt~point of view, as a set of decorated nodes, organized according to a particular geometrical distribution (often a tree structure, as in ARIANE-78 (Boitet et al. , 1982)).


WHAT COULD BE DONE IN EUROTRA ? Our proposals are based on our experience with GETA's ARIANE-78 system (Boitet et aL. , 1982), but also on some others approaches (Morin, 1978 ; Bennett et al. , 1984 ; Hawes, 1983 ; Hundt, 1982).


For French, there is currently a version under development of an enconverter that uses the Ariane-G5 platform (Boitet et al. , 1982), an environment for multilingual machine translation, for the analysis of the natural language input.


BOITET et al. , 1982\].In this paper, we will present three software tools for this environment which have been requested by the systemts users.


