The latter has developed a practical system for translating English titles of scientific and technical papers into Japanese (Nagao 1980, 1982), and is working on other applications of English-Japanese (Tsujii 1982) as well as Japanese-English (Nagao 1981).


This view is countered by Tsujii (1982:382), who claims that with only the shallow meaning representation afforded by Case, one does not avoid the necessity to look still at specific verbs in order to interpret the case labels and so to determine the appropriate strategy.


