(von Hahn, 1986 p. 523) One way of tackling this problem is to simulate the man-machine dialogue by letting users communicate with a background system through an interface which they have been told is a natural language interface, but which in reality is a person simulating such a device (sometimes called a Wizard of Oz experiment, see Guindon, Shuldberg, and Conner, 1987).


von Hahn, W. , (1986) Pragmatic considerations in man-machine discourse.


The basic critique has always been aimed at the lack of realism (for example, von Hahn 1986).


