Feature structures can be defined using a description language, such as the one found in PATR-II (Shieber 1986a) or in Kasper and Rounds (1986; 1990). 
325 Computational Linguistics Volume 18, Number 3 4.1 Defaults and Reentrancy The notion of 'default extension' employed here resembles the 'priority union' of Kaplan (1987: 180f) and the 'conservative addition' of Shieber (1986b). 
Shieber, Stuart (1986b). 
Shieber (1986a) proposes an operation.rid conservatively, which adds information of a feature structure A to a feature structure B, in as far as this information is not in conflict with information In B. Suggestions for similar operations can be found in Shivber (1986b:59-61) (the overwrite option of PATR-II) and Kaplan (1987) (priority union). 
From the examples given in Shieber (1986a) it seems as if overwriting can only be used to add or substitute (nonmonotonically) one atomic feature value in a given (possibly complex) feature structure (which acts as default). 
