1 Background and System Overview FoG (for Forecast Generator) was developed during 1985-89 (Kittredge et al. , 1986; Bourbeau et al. , 1990).


Unlike the typical content specification modules (e.g. , Kukich, 1983; Kittredge et al. 1986), our system relies on an authoring workstation environment equipped with a knowledge elicitation scenario for joint humancomputer content specification (see Sheremetyeva et al. , submitted 1996, for the details of the knowledge elicitation scenario).


This is analogous to Kittredge's et al. \[1986\] weather reports which indicate warnings first and then WINDS > CLOUD-COVER > PRECIPITATION > FOG&MIST > VISIBILITY.


The weather domain has proven to be a fruitful domain for further research as witnessed e.g. by the system for generating marine forecasts presented by Kittredge et al (1986), by the work by Goldberg et al (1988), by the system generating public weather reports in Bulgarian reported on by Mitkov (1991) and the system translating Finnish marine forecasts into Swedish by Bl~tberg (1988).


