Dahlgren and McDowell(1986) present a system for reasoning about natural language texts.


The theoretical underpinnings and practical work on the KT system have been reported extensively elsewhere, in conference papers (Dahlgren and McDowell 1986a, 1986b; McDowell and Dahlgren 1987) and in a book (Dahlgren 1988a).


Here the commonsense knowledge base is accessed to apply rules for prepositional phrase attachment (Dahlgren and McDowell 1986b) and word sense disambiguation (Dahlgren 1988a), as well as to assign the correct scope properties to operators and quantifiers.


This facility exploits the fact that possible feature types for any term are constrained by the ontological attachment of the term, by the Kind Type to which they belong (Dahlgren & McDowell 1986a; Dahlgren 1988a).


The analysis work was originally reported in Dahlgren and McDowell (1986b).


