A detailed discussion on how to produce such translations can be found in Strzalkowski and Cercone (1986) and Strzalkowski (1986). 
In any practical application, this transformation must be accompanied by a pragmatic process, as described in Strzalkowski (1986). 
A formal definition of A is given in Strzalkowski and Cercone (1986). 
Before a translation rule like one of these presented in this paper can be used, a sentence must undergo numerous transformations within the Stratified Model (Strzalkowski 1986). 
In Strzalkowski (1986) and Strzalkowski and Cercone (1986) we introduced a rigorous method for handling certain cases of extrasentential dependencies in discourse, within a general framework, which we call the Stratified Model. 
