Auxiliaries are subject control verWs (of Netter1986, 1988, and Bresnan 1982).


A discussion of its application in the LFG framework to infinitival complements can be found in/Johnson 1986/for Dutch and/Netter 1986/for German;/Karttunen (in press)/ discusses how similar extensions to Categorial Unification Grammar (CUG) can account in a simple way for related facts in Finnish that would otherwise require type-raising.


