4 IMPLEMENTATION OF THE WIDE-RANGE RESTRUCTURING FUNCTION A prototype English-to-Japanese machine translation system, SHALT (Tsutsumi 1986), is based on the two-step transfer method described in Section 3.2.


Other machine translation systems have also chosen the domain of computer manuals for their translation systems because of the relatively unambiguous and narrow sublanguage used (Tsutsumi, 1986).


