Tile discourse base was modeled after the discourse mechanism in LaPolla (1986).


If the above statement is accepted then one might ehmaeterize a discourse as a session where particular slices of memory are accessed and ehauged~ Since this actz~nulated store Of information in memory is presumably very large and has a complicated Structure, it i~ nsefill ff the commmricator can first identify tile locations in metuory that are to be modified or added to before inu'odncing rite modifications 372 or Mdifions (\[lajicov,5 and Vbmv~ 1981; LaPolla 1986).


4ot Detailed Overview NOSVO's grammar is segmented into two parts: i) plain vanilla SVO rules, e.g. S -> NP verb PP, "A little angel stood outside" (Green 1980, page 582), "Uncle Jack lives around the bend" (LaPolla forth coming), and it) so called old information first syntax, e.g. S -> PP verb NP, "Outside stood a little angel" (Green 1980, page 582), "Around the bend lives Uncle Jack" (LaPolla 1986 and 1988).


As Prince (1978) shows for clefts and as LaPolla (19861 shows for inversion and prepositional phrase fronting this need not be the case.


The listener wonkl have to wait uhtil the old inlbrmation is uttered to locate where the new information isto be used (LaPolla 1986).


