This tendency has manifested itself with respect to linguistic tools, perhaps seen most clearly in the evolution from ATNs with their strongly procedural grammars to PATR-II in its various incarnations (Shieber et al. 1983, Karttunen 1986), and to logic-based formalisms such as DCG (Pereira and Warren 1980). 
Implemeatation RUG is currently implemented in REGDPATR, an extension of the D-PATR gl'ammar development environment/Karttunen 1986/. 
(1986) and Karttunen (1986). 
Some implementations (e.g. , Karttunen 1986) build threading into the grammar compiler directly, but this can lead to inefficiency if features are threaded where they are never used. 
2The formst is that of D-PATR/Karttunen 1986/. 
