(These, and other problems associated with robust parsing of speech are further described in \[Eastman and McLean, 1981\], \[Hayes et aL, 1986\], and \[Young et al. , 1989\]).


Conceptually it is a semantic case-frame parser (Hayes et al. , 1986).


Most of the approaches based on this idea (e.g. \[Hayes et al. 1986\]) are characterized by the use of knowledge engineering techniques at both levels, while our recognition stage is based on a probabilistic technique, the hidden Markov models (HMM).


Finally, in the continuous speech recognition project at CMU (Hayes et al. 1986), the on-line parsing algoComputational Linguistics, Volume 13, Numbers 1-2, January-June 1987 45 Masaru Tomita An Efficient Augmented-Context-Free Parsing Algorithm rithm is being extended to handle speech input, to make the speech parsing process efficient and capable of being pipelined with lower level processes such as acoustic/phonetic level recognition (Tomita 1986).


