J90-4003:1	42:73	Most dependency parsers have followed a "principle of adjacency" that requires every word plus all its direct and indirect dependents to form a contiguous substring (Hays and Ziehe 1960; Starosta and Nomura 1986; Fraser 1989; but not Hellwig 1986 and possibly not J/ippinen et al. 1986).
---------------------------------------------------
J92-2001:2	290:441	Parsers based on the theories of Lexicase (Starosta and Nomura 1986) and Word Grammar (Fraser 1989; Hudson 1989) have also been developed.
---------------------------------------------------
