In this way complex structural transfer (as discussed in Nagao and Tsujii, 1986) can be avoided, but in some cases the dependency between the grammars may complicate individual grammars.


Nagao and Tsujii, 1986).


Nagao, Makoto, and Jun-ichi Tsujii (1986) "The Transfer Phase of the Mu Machine Translation System", Eleventh International Conference on Computational Linguistics (COLING-86), Bonn, pp.


Syntactic phrase structure transfer, or deepsyntax transfer (e.g. Thurmair 1990, Nagao and Tsujii 1986) results in complex transfer rules, and the predicate-argument structure which is required for the application of sortal restrictions is not represented.


