Depending on the criteria used for operating this kind of decomposition, several approaches may result, each one featuring specific characteristics (Cullingford, 1981; Huang and Guthrie, 1986; Small, 1981; Slack, 1986; Waltz and Pollack, 1985).


These ~:wo addressing functions can be distinguished ~y usm~ the labels COMP and COMP to 1 P g ~,enote the local and global addresses, respectively in encoding f--structures at the CS level, each sub-structure maps onto a separate :uperpositon space (Slack, 1986).


