For automatic processing this classification is not sufficient: H. Somers (1986) showed that a more flexible classification lead to better results, especially with respect to machine translation.


On the other hand many authors are advocates pro case relations, even in MT (e. g. Nagao 1986, Somers 1986).


The function of predicate-argument structures, especially in connection with semantic casls is another interesting research topic (as suggested by Somers (1986) which can be addressed in the present context, especially as the two components involved share their essential notions of predicate-argument structures from systemic linguistics.


