1.2 Morphological Preprocessing It has been argued that using morphological information is important for languages where morphology has an important influence on pronunciation, syllabification and word stress such as German, Dutch, Swedish or, to a smaller extent, also English (Sproat, 1996; Mobius, 2001; Pounder and Kommenda, 1986; Black et al. , 1998; Taylor, 2005).


Vowel length and quality has been argued to also depend on morphological structure (Pounder and Kommenda, 1986).


