Statistical methods have proven their value in automatic speech recognition (Bahl et al. 1983) and have recently been applied to lexicography (Sinclair 1985) and to natural language processing (Baker 1979; Ferguson 1980; Garside et al. 1987; Sampson 1986; Sharman et al. 1988).


A crude pilot version of the APRIL system was described in Sampson (1986)).


As adumbrated in Sampson (1986), we expect to make the dynamic annealing parser more efficient by exploiting the insight of Marcus (1980) that back'wacking ~.is rarely needed in natural language parsing: a gradient of processing intensity will be imposed on the annealing window, with most processing occuning in the "newest" parts of the current tree where valuable moves are most likely to be found.


Our current evaluation method is only slightly more elaborate than the technique described in Sampson (1986), whereby the prohability of a woducfion was derived exclusively from the observed frequencies of the various pairwise transitions between daughter-labels within the production (that is, for any production m--->dodt d.d.+t, where do and d.+t are boundary symbols, the estimated probability was the product of the observed frequencies of the various transitions m-+d~ di+x (O~gi ~;n) with zeroes replaced by small positive values).


