Habel, Christopher (1986): Prinzipien der Referentialit/it.


Habel, Christopher (1986a): Plurals, Cardinalities, and Structures of Determination.


2 The SYNPHONICS Conceptualizer The conceptual input into the Formulator in short: CS for "conceptual structure" is represented in the RefO/RetN format (Habel 1982, 1986a/b; Eschenbach et al. 1989).


(For a detailed description see Habel 1982, 1986a, 1986b and Eschenbach 1988).


