The system developed by Polanyi & Scha (1984) uses five different levels to hierarchically structure a dialogue and LOKI (Wachtel, 1986) uses four.


This idea has becn investigated here at UMIST in the context of a research programme for British Telecom (Jones & Tsujii 1990), and has significantly influcnc(xt the research reported here (a similar idea for 'automated text composition' in Japanese has tven suggested by Suite & Tomita 1986).


