For overviews see (Weir, 1988), (VijayShanker et al. , 1986) and (van Noord, 1993).


1 Some of the linguistic formalisms illustrating the increased use of lexical information are: lexical rules in LFG (Kaplan and Bresnan 1983), GPSG (Gazdar et al. 1985), HPSG (Pollard and Sag 1987), Categorial Grammars (Steedman 1987; Karttunen 1986), some versions of GB theory (Chomsky 1981), and Lexicon-Grammars (Gross 1984).


This observation stems from the equivalence of TAG and head grammars (Vijay-Shanker et al. 1986).


