In this paper, we will suggest an alternative approach based on the 'Recotmaissance-Attack' model described in Kac et al. 1986 (and more fully :in Rindflesch forthcoming), designed to skirt many of the problems associated with more traditional designs.


In Kac et al. 1986, it is argued that there are advantages to parsing in a series of graded stages such that at each stage onlay a particular, restricted type of structural infornlation (e.g. information about relations of subordination among verb!)


