/Abney 1986/, /Berwick 1987/, /Correa 1987/, /Kashket 1987/,/Kuhns 1986/,/Sharp.1985/,/Stabler 1987/,/Thiersch 1988/, and/%'ehrli I984/.


Although the parser is not yet complete, we expect that its breath of coverage of the language will be substantially larger than that of other Government-binding parsers recently reported in the literature (Kashket (1986), Kuhns (1986), Sharp (1985), and Wehrli (1984)).


The parser is a prlnclple-based GB parser and is a substantially revised "version of /Kuhns 1986/.


(/Kuhns 1986/describes an earlier implementation of GB Theory).


