On the contrary, constraint unification (CU) (Hasida 1986, Tuda et al. 1989), a disjunctive unification method, makes full use of term unification advantages. 
Such a method of satisfaction is called constraint transformation (Hasida, 1986). 
There are also several disjunctive unification algorithms that exploit independence, such as constraint unification (Hasida 1986; Nakano 1991), contexted unification (Maxwell and Kaplan 1989), and unification based on disjunctive feature logic (D6rre and Eisele 1990). 
Some constraint transformation methods whose resulting constraints are compact have been proposed (Hasida, 1986; Nakano, 1991). 
3 Constraint Unification and Its Problem This section explains constraint unification ~ (Hasida 1986, Tuda et al. 1989), a method of disjunctive unification, and indicates its disadvantage. 
