, 1989), e.g, lexicography (Church and Hanks, 1990), information retrieval (Salton, 1986a), text input (Yamashina and Obashi, 1988), etc. This paper will touch on its feasibility in topic identification.


267 The importance of a specific verb or noun is defined by Inverse Document Frequency (IDF) (Salton, 1986b): IDF(W) = log((P O(W)) / O(W)) + c (1) where P is the number of documents in LOB Corpus, i.e. 500, O(I4/) is the number of documents with word W, and c is a threshold value.


