Arnold et al. 1986) formerly nsed in EUROTRA. 
A unification-based formalism has many well-known virtues: it is declarative, monotonic, reversible (in principle at least); it has a well-understood formal interpretation (Shieber 1986, Smolka 1992, Johnson 1988); and there exist well-understood and relatively efficient parsing and generation algorithms for grammars using such a formalism (Shieber 1988; Haas 1989; Alshawi 1992; Shieber et al. 1990, inter alia). 
D. ARNOLD et al. 1986 3. 
In some unification-based formalisms (e.g. Briscoe et al. 1987; Arnold et al. 1986) Kleene operators have been included. 
for UCG (1988), Dorr for GB (1989) and Arnold et al. for Eurotra (1986). 
