On the other hand, some purely syntactic accounts require that antecedents for zeros be realized as the grammatical TOPIC, and thus cannot explain the above example because Taroo is never explicitly marked as the topic (Yoshimoto 1988). 
Several methods have been proposed with regard to this problem (Kameyama, 1986) (Walker et al. , 1990) (Yoshimoto, 1988) (Dousaka, 1994). 
On the basis of a unification parser developed at ATR (Kogure et al. 1988), the grammar has been written and proven capable of analyzing all fundamental sentence patterns in spoken-style Japanese conversation (Yoshimoto, Kogure and Iida 1989). 
A polar focus is to concentrate on the role of syntactic information such as what was previously the topic or subject (Hobbs 1976b; Kameyama 1985; Yoshimoto 1988). 
Several methods have been proposed with regard to this problem (Kameyama, 1986; Walker et al. , 1990; Yoshimoto, 1988; Dousaka, 1994). 
