The conceptual similarity measure is also used for lexical ambiguity resolution (see Fass 1988c). 
Fuller and more general descriptions of the four components appear in Fass (1988a; 1989b). 
Some argue that metaphor is a kind of metonymy, and others propose that metonymy is a kind of metaphor, while still others suggest that they are quite different (see Fass 1988c). 
PREMO: A ROBUST PARSER OF MESSAGES PREMO: the PREference Machine Organization is a knowledge-based Preference Semantics parser (Wilks 1972, 1975, 1978; Boguraev 1979; Carter 1984, 1987; Fass 1986, 1987, 1988; Huang 1984, 1988; Slator 1988a, 1988c) due to Brian Slator, with access to the large, text-specific, lexical semantic knowledge base created by the lexicon-provider of the CRL project on large scale lexical extraction from machine readable dictionaries (Wilks et al. in press). 
For more detail on cell matches, see Fass (1988a). 
