3 An HPSG implementation of a discourse grammar Following Scha ~ Polanyi (1988) and Priist et al (1994), our model of discourse consists of units called Discourse Constituent Units (ecus) which are related by various temporal and rhetorical relations. 
A second question is how this conception of discourse processing may be integrated with theories of discourse structure (Grosz and Sidner, 1986; Scha and Polanyi, 1988; Webber, 1991). 
also Mann and Thompson 1987, Scha and Polanyi 1988). 
Our central model of a discourse grammar is the Linguistic Discourse Model (LDM) most often associated with Scha, Polanyi, and their coworkers (Polanyi and Scha 1984, Scha and Polanyi 1988, Priist 1992, and most recently in Priist, Scha and van den Berg 1994). 
This process is reliant on performing comparison and generalization operations on the corresponding representations (Scha and Polanyi, 1988; Hobbs, 1990; Priist, 1992; Asher, 1993). 
