This at least allows to considerably soften the strong limitations of the approach in Menzel (1988), which are imposed by the restriction to fixed syntactic environments.


A procedure of this kind }\]as been successfully pursued in an earlier paper on the diagnosis of agreement errors in fixed syntactic environments (Menzel 1988).


Provision can be taken for these premises to be fulfilled in artificially limited domains of natural language, e.g. for agreement errors C c.f. Menzel 1988).


