It differs in many critical respects from e.g Bech & Nygaard (1988).


These are explicit levels and a transfer mechanism allows a mapping between them (Arnold, 1987, Bech& Nygaard, 1988).


2 The projects involved 2.1 Eurotra-D Analysis Module The German analysis module of our proposed MT system is based on the Eurotra Engineering Framework (Bech and Nygaard, 1988) enhanced by a semantic component derived from systemic theory.


The general route of the EFW to solving these problems is to separate the output of the t-grammar from the finished representation in the following way, as described in Bech & Nygaard (1988): (3) Repni I t-grammar DI'~SCIIIP'I'OR~ I g r gill lit arj J. II,epn~ The RtIS of each t-rule specifies a local part of a special representation called a DESCRIPTOR.


ological issues, CUP, Cambridge, 114-135 Arnold, D, L des Tombe & L Jaspaert (1985) "Eurotra Linguistic Specifications Version 3", DG XIII, CEC, Luxembourg Arnold, D, S Krauwer, L des Tombe & L Sadler (1988), "'Relaxed' Compositionality in Machine Translation", in Second International Conference on Theoretical and Methodological Issues in Machine Translation of Natural Languages, Carnegie Mellon Univ, Pittsburgh Arnold, D, S Krauwer, M Rosner, L des Tombe & G B Varile (1986) "The iC,AL,T Framework in EU ROTRA: A Theoretically Committed Notation for MT", in Proceedings of the llth International Conference on Computational Linguistics (COLING 86), Association for Computational Linguistics Arnold, D, & L Sadler (1989) "MiMo: Theoretical Aspects of the System", Working Papers in Language Processing 6, Dept of Language & Linguistics, Univ of Essex Bech, A, & A Nygaard (1988) "The E-Framework: A Formalism for Natural Language Proces~ing', in Proceedings of the 12th International Confer.


