C92-3141:1	141:179	Another possible method is to employ ntnnelical estimates of syntactic preference (set, for example, Tsejtin 1975; Kulagiua 1987, 1990; Tsujii et al. 1988).
---------------------------------------------------
C96-2131:2	119:164	The parser intensively exploits the idea of syntactic preference used in a wide range of systems based on various principles (see, for example, Tsejtin 1975; Kulagina 1987, 1990; Tsujii et al. 1988; llobbs and Bear 1990).
---------------------------------------------------
