Constraints imposed by Wedekind (1988) and van Noord (to appear) exclude certain linguistic analyses from generation. 
Wedekind (1988) achieves the reordering by first generating nodes that are connected, that is, whose semantics is instantiated. 
In particular, generation from grammars with recursions whose welbfoundedness relies on lexical information will terminate; top-down generation regimes such as those of Wedekind (1988) or Dymetman and Isabelle (1988) lack this property, discussed further in Section 3.1. 
Busemann, 1987; van Nonrd, to appear;, Dymetmann & Isabelle, 1988; and Wedekind, 1988). 
Wedekind (1988) achieves this goal by expanding first nodes that are connected, that is, whose semantics is instantiated. 
