Zernik and Brown 1988:802), the system initially assumes "the child" to be the agent since the "default voice" is considered to be "active". 
For a recent approach in this direction, see Zernik and Brown (1988). 
INTEGRATION WITH A REASON MAINTENANCE SYSTEM Zernik and Brown (1988) have described a possible integration of default reasoning in natural language processing. 
2.2 Problems This section dis'cusses some general problems of JTMSs and JTMS-style approaches to incrementM parsing with special reference to the framework of Zernik and Brown (1988) whose notion of parsing comes closest to the one considered here. 
Conflicting information is simply thrown away, ~hus in a sense making the system even More recently, Zernik and Brown (1988) suggest a coupling of a DCG parser with a JTMS, both of which are embedded in a Prolog system. 
