Several efforts have been conducted to achieve this objective ((Lang, 1988; Saito and Tomita, 1988), for example).


In specifying the equations, we exploit techniques used in the parsing of incomplete input (Lang, 1988).


Cycles might emerge to treat unknown sequences of words, i.e. sentences with unknown parts of unknown lengths (Lang, 1988).


The present paper extends Lounsburys original idea to infinite languages, by applying two classical ideas in (probabilistic) formal language theory: Grenanders (1967) closed-form solution for the entropy of a nonterminal in a probabilistic context-free phrase structure grammar, and Langs (1974; 1988) insight that an intermediate parser state is itself a specification of a grammar.


Lang and Billot observe (1974; 1988; 1989) that the incremental state of a parser can be described by another, related grammar.


