One exception is the DLT project which uses Esperanto as a pseudo interlingua (Witkam, 1988); a choice of representation which has "aroused a lot of skepticism" in the community (op cit.


At the same time, but independently, the authors and their colleagues at BSO/Research have been experimenting with bilingual corpora as a potential knowledge source for the Distributed Language Translation system (for an overview of this machine translation project, see Witkam 1988).


