(Markowitz e~ al. 1986), (Jensen & Binot 1987), and (Nakamura & Nagao 1988) also use pattern recognition to extract semantic relations such as taxonomy from various dictionaries. 
Nakamura & Nagao (1988) call them Function Nouns. 
2.1 Synonym/hypernym Extraction from an Ordinary Dictionary Although there were some attempts to extract synonymous expressions from a dictionary (Nakamura and Nagao, 1988; Tsurumaru et al., 1986), they extracted only hypernym-hyponym relations from the limited entries. 
Nakamura & Nagao (1988) identify 41 different function nouns and replace the IS-A link in their taxonomy with various other links in these cases (except in the "kind of", "type of", etc. , definitions). 
(1987), Markowitz, Ahlswede, and Evens (1986), and Nakamura and Nagao (1988) showed that taxonomic information and certain semantic relations can be extracted from MRDs using fairly simple techniques. 
