This issue is not discussed in Correa (1988), since this paper is strictly focused on syntax and binding. 
Correa (1988)). 
When an NP j is found: a. Copy: Leave a copy of A (if NP j is a short-distance reflexive) or B (if it is a pronoun) at the NP j. 3 Correa (1988, page 123) observes that although the integration of binding constraints into rules which may be used to derive structure that already satisfies the [constraints] is not a straightforward task, that should be the path to follow, a point also strongly stressed in subsequent elaboration on this issue by Merlo (1993). 
As discussed in Correa (1988), this procedure is grossly inefficient: its complexity was shown in Fong (1990) to be of exponential order. 
The other two proposals are presented in Correa (1988), and in lngria and Stallard (1989). 
