Shieber (1988) argues for a uniform architecture for parsing in generation. 
In addition to exploiting the formal MRL grammar, our approach also allows the same learned grammar to be used for both parsing and generation, an elegant property that has been widely advocated (Kay, 1975; Jacobs, 1985; Shieber, 1988). 
1This issue of canonicality of logical forms is discussed by Shieber (1988). 
1 Charts Shieber (1988) showed that parsing charts can be also used in generation and raised the question, which we take up again here, of whether they constitute a natural uniform architecture for parsing and generation. 
In previous work, one of us noted that generation according to an augmented context-free grammar can be made more efficient by requiring the grammar to be semantically monotonic (Shieber, 1988); the derived semantics for an expression must include, in an appropriate sense, the semantic material of all its subconstituents. 
