2 Yet despite this enormous body of work, the issue of word access has not been addressed at all within this community, not even in Wards extensive problem catalog (Ward 1988).


Appropriate word choice is, of course, a function of numerous factors and considerations (/Ward 1988/, /Pustejovsky and Nirenburg 1987/,/Danlos 1987/), but, in any case, the selection process makes sense only if the incoming semantic representation provides for there to be a distinction that is later reflected as a lexical distinction.


Elsewhere I argue that FIG points the way to accurate and flexible word choice (Ward 1988), producing naturalsounding output for machine translation (Ward 1989c), and modeling the key aspects of the human language production process (Ward 1989a).


Thanks to this sort of activation flow FIG tends to select and emit an appropriate word in an appropriate form (Ward 1988).


