We rely on the French and English LTAG grammars (Abeille \[1988\], Abeille \[1.990 (b)\], Abeilld et al. \[1990\], Abeill6 and Schabes \[1989, 1990\]) that have been designed over the past two years jointly at University of Pennsylvania and University of Paris 7-Jussieu.


Using Lexicalized Tags for Machine Translation * Anne Abeilld University of Paris 7-Jussieu LADL 2 place Jussieu, 75005 Paris France abeilleC~franz.ibp.fr Yves Schabes University of Pennsylvania Dept of Computer & Information Science Philadelphia PA 19104-6389 schabes@linc.cis.upenn.edu Aravind K. Joshi University of Pennsylvania Dept of Computer & Information Science Philadelphia PA 19104-6389 joshi@linc.cis.upenn.edu Abstract Lexicalized Tree Adjoining Grammar (LTAG) is an attractive formalism for linguistic description mainly because cff its extended domain of locality and its factoring recursion out from the domain of local dependencies (Joshi, 1985, Kroch and Joshi, 1985, Abeilld, 1988).


Parsing Strategies with 'Lexicalized' Grammars: Application to Tree Adjoining Grammars * Yves SCHABES, Anne ABEILLE**and Aravind K. JOSHI Department of Computer and Information Science University of Pennsylvania Philadelphia PA 19104-6389 USA schabes~linc.cis.upenn.edu abeille~cis.upenn.edu joshi~eis.upenn.edu ABSTRACT In this paper we present a general parsing strategy that arose from the development of an Earley-type parsing algorithm for TAGs (Schabes and Joshi 1988) and from recent linguistic work in TAGs (Abeille 1988).


