Such explicit implementations of abstraction levels can indeed be witnessed in many state-of-theart speech synthesisers, implemented as (sequential) modules (Allen, Hunnicutt, and Klatt, 1987; Daelemans, 1988).


Model 'BP 91.3 Generalisation Accuracy on Phonemes IBL 93.4 TABLE 95.1 3.2 The Linguistic Knowledge-Based Approach The traditional linguistic knowledge-based approach of grapheme-phoneme conversion has produced various examples of combined rule-based and lexiconbased models, e.g. MITALK (\[Allen et al. , 1987\]) for English, GRAFON-D (\[Daelemans, 1988\]), and MORPA-CUM-MORPHON (\[Nunn and Van Heuven, 1993\]) for Dutch.


