Pustejovsky, James and Peter Anick (1988) The Semantic Interpretation of Nominals, COLING '88. 
In conclusion, it should be pointed out that the entire lexicon is organized around such logical ambiguities, which Pustejovsky and Anick (1988) call Lexical Conceptual Paradigms. 
The use of domain knowledge can enhance the effectiveness of a full-text system by providing related terms that can be used to broaden, narrow, or refocus a query at retrieval time (Debili, Fluhr, and Radasua 1988; Anick et al. 1989. 
In Pustejovsky (1989b) and Pustejovsky and Anick (1988), I suggest that there is a system of relations that characterizes the semantics of nominals, very much like the argument structure of a verb. 
Following Pustejovsky and Anick (1988), we call such meta-entries lexical conceptuM paradigms (LCPs). 
