In English, e.g., the two aspect constructions perfective and progressive can be seen as realizing the basic contrast of the action viewed as complete or as incomplete (for details see van Eynde 1988).


van Eynde, 1988) and the Nigel approach (cL Matthiessen, 1984) grew out of a critical appraisal of the Reichenbachian framework, although they took quite different directions from there, with Mar~hiessen following essentially SFG lines.


In some of these domains it has already become accepted to appeal to an abstract representation that is essentially language independent, as in the work of van Eynde on tense and aspect (e.g. 1988).


