In this paper we present Uni cational Combinatory Categorial Grammar (UCCG), which integrates aspects of Combinatory Categorial Grammar (Steedman, 2000), Uni cation Categorial Grammar (Zeevat, 1988; Calder et al. , 1988), and Discourse Representation Theory (Kamp and Reyle, 1993). 
1986, Calder et al. 1988. 
Uni cation Categorial Grammar (UCG) uses Head-Driven Phrase Structure Grammar type of feature structures, called signs, to represent the categories of lexical items (Zeevat, 1988; Calder et al. , 1988). 
Introductions to UCG and InL can be found in Calder et al (1988b) and Zeevat (1988). 
1 Preliminaries CATEGORIAL UNIFICATION GRAMMAR Unificationbased versions of Categorial Grammar, known as CUG or UCG, have attracted considerable attention recently (see, for instance, Uszkoreit, 1986, Karttunen, 1986, Bouma, 1988, Bouma et al. , 1988, and Calder et al. , 1988). 
