Furthermore, in some other approaches to increase the flexibility of the slot and filler principle, such as island parsing (Stock, 1988) and discontinuous segmented parsing (Hellwig, 1988), the augmented chart proposed here can also be easily extended and applied.


Hellwig 1988), which allows to use the same format of parser output for the style analysis of different languages.


Dependency Unification Grammar (Hellwig, 1988) defines a tree-like data structure for the representation of syntactic analyses.


