J96-1003:1	123:187	Veronis (1988) presents a method for handling quite complex combinations of typographical and phonographic errors (phonographic errors are the kind usually made by language learners using computer-aided instruction).
---------------------------------------------------
C96-1031:2	29:146	(Veronis, 1988) claims that native writers are unlikely to produce errors involving morphological features, while (Vosse, 1992) acce.t)ts such morpho-syntactic errors, in spite of tile fact that an examination of texts by the author revealed that their appearance in native writer's texts is not frequent.
---------------------------------------------------
C96-1031:3	83:146	(;ht(m are sha.p(~(\[ as scores in the a,t)proa.ch a(h)I)t;(~(l tt)l' ~l, gt'(K':lItClll; (~,l'l'()l'S, D31(1, ill LIIis seltse, ollr heurisLi('.s is clos('xl to 1;he inel;ri(: Ol)erations 1)('af()rm(!(1 1)y ol;h(*'r/ffm)nnar checkers tmsed on Nil,l ) t:edmiques (Veronis, 1988), (Bolioli ct al. , \]992), (Vosse, \]!).()2), ((~('.nl;hia\] (;I, al. , t994).
---------------------------------------------------
P92-1021:4	90:153	3 3This is the reverse of Veronis' (1988) algorithm, where roots are matched before affixes.
---------------------------------------------------
P92-1021:5	99:153	Other work (e.g. Veronis, 1988, Emirkanian and Bouchard, 1988, van Berkel and De Smedt, 1988) emphasizes the former, often on the grounds that competence errors are both harder for the user to correct and tend to make a worse impression on a human reader.
---------------------------------------------------
