(1988) suggest and as Brown et al. 
In general a statistical machine translation system is composed of three components: a language model, a translation model, and a decoder (Brown et al. , 1988). 
INTRODUCTION An alluring aspect of the statistical ~pproach to machine translation rejuvenated by Brown et al. \[Brown et al. , 1988, Brown et al. , 1990\] is the systematic framework it provides for attacking the problem of lexical disambiguation. 
1 Introduction Over the past decade, researchers at IBM have developed a series of increasingly sophisticated statistical models for machine translation (Brown et al. , 1988; Brown et al. , 1990; Brown et al. , 1993a). 
INTRODUCTION Recent work by Brown et al. , \[Brown et al. , 1988, Brown et al. , 1990\] has quickened anew the long dormant idea of using statistical techniques to carry out machine translation from one natural language to another. 
