Keywords: unification, machine translation, transfer, bilingual lexicon I. Unification based transfer Our approach is more transfer oriented than some other unification based approaches to MT (e.g. , Beaven and Whitelock 1988).


These include the kind of structural correspondence used for relating syntax and semantics in recent work on LFG (Halvorsen 1987, Kaplan & Halvorsen 1988, Kaplan, Netter, Wedekind & Zaenen 1989) and also bilingual lexical entries as in Beaven & Whitelock (1988).


