The interest in developing authoring systems (i.e. , systems where an individual writes a text in the source language with a 'guarantee' that the translation will be correct) is an attempt to assure that the analysis of the text is not ambiguous and does have a translation (McGee Wood & Chandler, 1988).


In this respect we are following the line taken by Johnson & Whitelock (1987), and the work here at UMIST on the ENtran project (Whitelock et al. 1986, Wood & Chandler 1988) developing an MT system for a monolingual user.


At the structural level, ambiguities can also be referred to the user for disam.biguation~ as is done in Ntran, an English-to-Japanese prototype MT system for monolingual users (Wood and Chandler, 1988).


\[6\] Chandler, B. & Wood, M. , (1988).


