bustness features competes with algorithnfic approaches to robustness where parsing algorithms, (usually chart parsers except in Tomabechi and Tomita (1988) where LR(k) parsing is advocated) are extended to inelude robustness features (Mellish 1989, Long 1988) and/or heuristics to handle defect cases (Banger 1990, Stock et al. 1988).


To compare with a similar approach, in Stock's island-driven bidirectional chart (Stock et al. 1988), the searching actions are triggered by islands (an island is a more reliable word hypothesis resulting from speech recognition) and the searching directions may be bidirectional; i.e., an active edge may search for constituents on both sides as shown in Figure 6.


