Meteer and Shaked (1988) propose an approach where during the repeated parse of an ambiguous utterance potential sources of ambiguity can be detected.


Our paraphrasing component (Meteer and Shaked, 1988) already uses the discourse entities to a limited extent.


Applications include summarization (Knight and Marcu, 2000) and rewriting (Chandrasekar and Bangalore, 1997): both could employ such a mechanism to produce candidate sentence paraphrases that other system components would filter for length, sophistication level, and so forth.1 Not surprisingly, therefore, paraphrasing has been a focus of generation research for quite some 1Another interesting application, somewhat tangential to generation, would be to expand existing corpora by providing time (McKeown, 1979; Meteer and Shaked, 1988; Dras, 1999).


(McKeown 1979), (Meteer & Shaked 1988).


