13th Int'l Conf Computational Linguistics (COLING 90), Helsinki, August 20-25, 1990 . [4] Sager, N. Natural Language Information Processing, Addison-Wesley, 1981 . 193 [5] Grishman, R. , and Sterling, J . Acquisition of Selectional Patterns . Proc.


Proc . DARPA Speech and Natural Language Workshop, Morgan Kaufman, 1990 (proceedings of the conference at Harwich Port, MA, Oct . 15-18, 1989) . [3] Grishman, R. , and Sterling, J . Information Extraction and Semantic Constraints . Proc . 13th Int' I Conf Computational Linguistics (COLING 90), Helsinki, August 20-25, 1990 . [4] Sager, N . Natural Language Information Processing, Addison-Wesley, 1981 .


