Termination for reversible transfer grammars is discussed in van Noord (1990). 
The semantic-head-driven generation strategy (van Noord, 1989; Calder ef al. , 1989; Shieber et al. , 1989; van Noord, 1990a; Shieber et al. , 1990) faces problems in case semantic heads are 'displaced', and this displacement is analyzed using threading. 
van Noord, Gertjan (1990). 
For generation headdriven generators can be used (van Noord, 1989; Calder et al. , 1989; Shieber et al. , 1990). 
van Noord (1990b) and also Thompson (1991, this volume). 
