In Finkler and Neumann (1989) and Neumann and Finkler (1990) we have already described an implemented generation system (named POPEL-HOW) that realizes an incremental and bidirectional flow of control based on a uniform parallel processing model.


1Besides these two classes there are also systems that use different knowledge sources that are compiled from the same source (e.g. , Horacek and Pyka 1988) and systems that use common basic representation devices  (e.g. , Lancel et,al. 1988; Neumann and Finkler 1990).


(Newman, 1990), (Dymetman et al. , 1990)) and the performing of specific processing strategies (e.g. , incremental and parallel generation, (Neumann and Finkler, 1990)).


