5 Related work Previous natural language acquisition models couht be characterized as interactive acquisition \[tang & tIirschman, 1988; Liu & Soo, I993a, 1993b; Velardi ct al. , 1991\], corpus-based acquisition \[Brent, 1993; 3acobs & Zernik, 1988; Zernik, 1989\], dictionary-based acquisition \[Montemagni & Vanderwende, 1992; Sanfilippo & Pozanski, 1992\], statistics-based acquisition \[Smadja, 1991; Sekine et al, 1992\], and connectionistbased acquisition \[Paisal & Kwasny, 1990; McClelland & Kawamoto, 1986\].


