J94-4005:1	13:230	Although multiple functions have been used in other systems (for example, McCord 1990; Hobbs and Bear 1990), little is typically said about how the functions are combined to produce the overall score for an analysis, the weights presumably being determined by intuition or trial and error.
---------------------------------------------------
W07-2211:2	35:238	Hobbs and Bear (1990) provide a useful summary of the evolved principles.
---------------------------------------------------
W07-2211:3	49:238	For example, Hobbs and Bear (1990) say only that "When a 1 The idea has also been used directly in stochastic parsers that consider all possible attachments, for example, by McDonald et al.
---------------------------------------------------
C92-3141:4	167:179	As regards the last type, preference for the predicate-argument interpretation of word combinations was orlon noted in the literature (this preference is a particular case of the Most Restrictive Context Principle proposed by Hobhs and Bear (1990)).
---------------------------------------------------
W93-0307:5	16:166	Discussions of sentence processing have focused primarily on structurally-based preference strategies such as right association and minimal attachment \[Kimball, 1973; Frazier, 1979; Ford et al. , 1982\]; \[Hobbs and Bear, 1990\], while acknowledging the importance of semantics and pragmatics in attachment decisions, propose two syntactically-based attachment rules that are meant to be generalizations of those structural strategies.
---------------------------------------------------
A92-1026:6	103:248	 The scores derived from the preference heuristics that have been encoded in DIALOGIC over the years, described and systematized in Hobbs and Bear (1990).
---------------------------------------------------
J92-2005:7	249:347	12 See also Shieber (1983) and Hobbs and Bear (1990).
---------------------------------------------------
J92-2005:8	243:347	Firstly, from empirical, corpusbased studies it may be concluded that lexical preferences are successful heuristics for resolving ambiguity (Whittemore, Ferrara, and Brunner 1990; Hobbs and Bear 1990).
---------------------------------------------------
J92-2005:9	205:347	11 Inclusion of a notion of dependency constituency (Barry and Pickering 1990) excludes strings such as John loves the from being a constituent in contrast to the original M-calculus.
---------------------------------------------------
W05-1504:10	35:345	(1) helps explain the late closure or attach low heuristic (e.g. , Frazier, 1979; Hobbs and Bear, 1990): a modifier such as a PP is more likely to attach to the closest appropriate head.
---------------------------------------------------
W96-0112:11	12:254	The Lexical Preference Rule (LPR) (Ford et al. , 1982), the Right Association Principle (RAP) (Kimball, 1973), and the Attach Low and Parallel Principle (ALPP, an extension of RAP) (Hobbs and Bear, 1990) have been proposed, and it is thought that we might resolve ambiguities quite satisfactorily if we could implement these principles sufficiently (Hobbs and Bear, 1990; Whittemore et al. , 1990).
---------------------------------------------------
W96-0112:12	58:254	According to Whittemore et al. and Hobbs & Bear, nearly all of the ambiguities can be resolved by first applying LPR and then RAP and ALPP (Hobbs and Bear, 1990; Whittemore et al. , 1990).
---------------------------------------------------
W96-0112:13	33:254	Hobbs & Bear have generalized RAP to the Attach Low and Parallel Principle (ALPP) (Hobbs and Bear, 1990).
---------------------------------------------------
W96-0112:14	60:254	While there are also other principles proposed in the literature, including the Minimal Attachment Principle (Frazier and Fodor, 1979), they are generally either not highly functional or are covered by the above three principles in any case (Hobbs and Bear, 1990; Whittemore et al. , 1990).
---------------------------------------------------
W96-0112:15	45:254	LPR is a lexical semantic principle, while RAP and ALPP are syntactic ones, and in psycholinguistics it is commonly claimed that LPR overrides RAP and ALPP (Hobbs and Bear, 1990).
---------------------------------------------------
W96-0112:16	193:254	These two kinds of ambiguities are typical, and other ambiguities can be resolved in the same way (Hobbs and Bear, 1990).
---------------------------------------------------
A92-1032:17	42:60	These phenomena are handled by employing preference schemes improved by semantic control (Hobbs and Bear, 1990).
---------------------------------------------------
P92-1041:18	36:64	PARSING PREFERENCES Many preference strategies have been proposed in the literature for guiding parsers (Hobbs and Bear (1990) present a review).
---------------------------------------------------
P93-1008:19	160:196	In this respect, our approach differs from many other approaches to the problem of parse preferences, which make their preference decisions as parsing progresses, pruning subsequent parsing paths (Frazier and Fodor, 1978), (Hobbs and Bear, 1990), (Marcus 1980).
---------------------------------------------------
C96-2131:20	119:164	The parser intensively exploits the idea of syntactic preference used in a wide range of systems based on various principles (see, for example, Tsejtin 1975; Kulagina 1987, 1990; Tsujii et al. 1988; llobbs and Bear 1990).
---------------------------------------------------
J98-2002:21	259:393	It has been empirically verified that the use of lexical semantic knowledge is effective in structural disambiguation, such as the PP-attachment problem (Hobbs and Bear 1990; Whittemore, Ferrara, and Brunner 1990).
---------------------------------------------------
