One of the crucial points is that tagged text should be represented by FSA in order to be disambiguated (disambiguated texts are already in this form in Rimon and Herz 1991 and K. Koskenniemi 1990). 
Our algorithm resembles the method of Koskenniemi (1990) and later work. 
In practice, the set of structurally correct solutions may be computed, for example, through the intersection or composition of finite-state automata as in the formalism of finite-state intersection grammars (Koskenniemi, 1990). 
In the last several years, there have been a number of studies on developing finite-state parsing systems (Koskenniemi 1990; Koskenniemi, Tapanainen, and Voutilainen 1992; Grefenstette 1996; Chanod and Tapanainen 1996; Ait-Mokhtar and Chanod 1997; Hobbs et al. 1997). 
At tile same time, it is in its very essence not incompatible with Constraint Grannnar (Karlsson 1990, Koskenniemi 1990). 
