This gives the possibility to define more general relations, and in particular functions can be defined in a way similar to, for example, (Johnson and Rosner, 1989) and (Emele and Zajac, 1990). 
Other formalisms are STUF (Beierle et al. , 1988), TFS (Emele & Zajac, 1990), CUF (D6rre & Eisele, 1991) and, ALE (Carpenter, 1992). 
Emele, Martin, and Zajac, R6mi (1990a). 
935 (9) sign(v, agr(sing, 3rd), sign(_, agr(sing, 3rd), _)) Feature structure (8) is a O'ped feature structure used in typed unification grammars (Emele and Zajac, 1990). 
This resulted in formalisms as, for example, (Johnson and Rosner, 1989), (Emele and Zajac, 1990), (DSrre and Dorna, 1993) and (Carpenter, 1992). 
