Dagan and Itai (1990) proposed a heuristics-based approach to pronoun resolution. 
Dagan and Itai (1990), for example, developed a statistical approach for pronominal anaphora, but the information they used was simply the patterns obtained from the previous analysis of the text. 
Owing to lack of syntactic information, this preference is somewhat weaker than the collocation preference described in (Dagan & Itai 1990). 
A number of proposals in the 1990s deliberately limited the extent to which they relied on domain and/or linguistic knowledge and reported promising results in knowledge-poor operational environments (Dagan and Itai 1990, 1991; Lappin and Leass 1994; Nasukawa 1994; Kennedy and Boguraev 1996; Williams, Harvey, and Preston 1996; Baldwin 1997; Mitkov 1996, 1998b). 
On more syntactic note, Dagan and Itai 1990 use statistical methods over linguistically parsed text (Jensen 1986) to resolve anaphorie reference. 
