Pustejovsky's solution to this problem (outlined also in (Pustejovsky, 1990)) is a "generative lexicon", which organizes lexical items with respect to one or more of: (1) argument structure, (2) event structure, (3) qualia structure, and (4) lexical inheritance structure. 
Pustejovsky and Anick (1988), Bogutaev and Pustejovsky (1990)). 
This investigation will benefit from the work of several researchers in the field of automatic lexicon construction, most notably, Brent (1993), Boguraev and Briscoe (1989), Boguraev and Pustejovsky (1990), Briscoe and Copestake (1990), Byrd et al. 
Anick and Pustejovsky (1990) for one such algorithm). 
5.3 Boguraev and Pustejovsky Boguraev and Pustejovsky (1990) argue that the normal conceptions of the structure of the lexicon are impoverished for two major reasons. 
