5 Status of Implementation A first prototype of the system described above has been developed in C under UNIX within the ESPRIT II project 2315 "Translator's Workbench" (TWB) as one of several separate modules checking basic as well as higher levels of various languages Ilike grammar and style; see (Thurmair, 1990) and (Winkelmann, 1990)\].


4 Status of Implementation A first prototype of the system described above has been developed in C under UNIX within the ESPRIT I1 project 2315 "Translator's Workbench" (TWB) as one of several orthogonal modules checking basic as well as higher levels (like grammar and style; see (Thurmair, 1990) and (Winkelmann, 1990)) of various languages.


