Other NLG systems that extract and summarise information have been developed in other research, particularly by CoGenTex; their systems include, for example, FOG (Bourbeau et al. , 1990), which produced weather reports; LFS (Iordanskaja et al. , 1992), which summarised employment statistics; and Joyce (Rambow and Korelsky, 1992), which summarised software designs from a security perspective.


There are various projects concerning the production of weather reports, each of them setting specific goals 48 The RAREAS, RAREAS-2 and FoG series of systems (Bourbeau et al. , 1990) developed by one of the most successful groups in weather report generation shares many concepts with the current project, the main differences lying in the specification of the product and in the modality of the generated documents.


At least four previous systems developed elsewhere use natural language to sum475 Computational Linguistics Volume 24, Number 3 marize quantitative data, including ANA (Kukich 1983), SEMTEX (R6sner 1987), FOG (Bourbeau et al. 1990), and LFS (Iordanskaja et al. 1994).


