1See Goeser (1990) for a more formal discussion of PAn(C).


Grammar based robustness tools have been explored in a variety of formalisms, e.g. the metarule device within the ATN formalism (Weischedel and Sondheimer 1898), entity data structures in a case frame approach (Hayes 1984) or the weak description approach in unification based grammars (Kudo et al. 1988, Goeser 1990).


On the other hand, there are spoken language constructions (Lindgren 1987, Goeser 1991, Langer 1990) and various kinds of "fragmentary utterances" (Cnrbonell and ltnyes 1983) that definitively show configurational properties.


