We believe that, just to take one example, a poor knowledge of the results and methods of lexicography, linguistics, and cognitive science in part motivates the nonstriking success of NLP in developing large-scale systems (Velardi 1990).


The NLP system is described in Fasolo (1990) and is similar to the one described in Velardi (1988) and Antonacci (1989) and in the other papers on the DANTE system, except for the use of shallow methods in syntax and the ability to produce partial interpretations if parts of a text are not understood.


