Computational instances of systemic grammar are successfully employed in some of the largest and most influential text generation projects--such as, for example, PENMAN (Mann, 1983), COMMUNAL (Fawcett and Tucker, 1990), TECHDOC (KSsner and Stede, 1994), Drafter (Paris and Vander Linden, 1996), and Gist (Not and Stock, 1994).


Other systems do not allow generation independent from user interaction, for instance, Genesys (Faw41 cett & Tucker 1990) requires the user to make decisions throughout the generation process.


Fawcett, Robin P. Gordon H. Tucker (1990) "Demonstration of GENESYS: a very large semantically based Systemic Functional Grammar".


