Others such as Lesk (1986), Walker (1987), Veronis and Ide (1990), and Guthrie et al. 
Another related line of work is the word sense disambiguation algorithm proposed in (Veronis and Ide, 1990), where a large neural network is built by relating words through their dictionary definitions. 
A common approach to disambiguation is to select among the homographs and senses provided by a machine-readable dictionary (e.g. Lesk \[1986\], Byrd \[1989\], Krovetz \[1989\], Slator \[1989\], Guthrie et al. \[1990\], Ide and Veronis \[1990\], and Veronis and Ide \[1990\]. 
Attempts to alleviate this tagbottleneck i~lude tmotstr~ias (Te~ ot ill,, 1996; Hearst, 1991) and unsupervised algorith~ (Yarowsky, 199s) Dictionary-based approaches rely on linguistic knowledge sources such as ma~l~i,~e-readable dictionaries (Luk, 1995; Veronis and Ide, 1990) and WordNet (Agirre and Rigau, 1996; Resnik, 1995) and e0(ploit these for word sense disaznbiguation. 
(1991), Veronis and Ide (1990), and Slator (1991). 
