(1988) and Chen (1990), the processing of head movement is based on GPSG like slash features.


Many word segmentation techniques (Chen & Liu, 1992; Chiang et al. , 1992; Sproat & Shih, 1990) have been developed.


Introduction A Chinese sentence is composed of a string of characters without any word boundaries, so that to segment Chinese sentences is indispensable in Chinese language processing (Chen, 1990; Chen, 1994).


