As with Lewin's scoping algorithm, (Lewin 1990), there are no constraints built explicitly into the QLF semantics on where a quantification rule for a term may be applied, or indeed on the number of times it may be applied.


The version proposed here combines a basic insight from Lewin (1990) with higher-order unification to give an analysis that has a strong resemblance to that proposed in Pereira (1990, 1991), with some differences that are commented on below.


In this case we obtain: 12) gives(< V,X,ITIall(X)>,< 3,y,book(y)>,< -~,z,'l'>) Scoped propositions can then be obtained by using an outside-in quantifier scoping algorithm (Lewin, 1990), or an inside-out algorithm with a free w~riable constraint (IIobbs and Shieber, 1987).


