Karlsson (Karlsson, 1990) has used a rule-based approach where the central idea is to maximize the use of morphological information. 
For a description of the Constraint Grammar approach we refer the reader to (Karlsson, 1990). 
Our work is based on work done with ENGCG, the Constraint Grammar Parser of English \[Karlsson, 1990; Karlsson, 1994; Karlsson et al. , 1994; Voutilainen, 1994\]. 
At tile same time, it is in its very essence not incompatible with Constraint Grannnar (Karlsson 1990, Koskenniemi 1990). 
For a description of the Constraint Grammar approach we refer the reader to (Karlsson, 1990). 
