In previous researches, some tended to simplify the problem by treating only special types of MWTUs, while others had some recognition errors and took too much recognition time because they did not restrict the recognition scope (D.Santos,1990; Yoon Sung Hee,1992; Ha Gyu Lee, 1994; Seen-He Kim, 1997).


Although some researches (D.Santos,1990; Linden E. ,1990; Yoon Sung Hoe, 1992; Ha Gyu Lee, 1994; D.Arnold,1994) employ the term "idiom" for these units, we prefer MWTU (Multi-Word Translation Unit) because it is a more general and broader term for MT environment.


4.2 Decomposition versus Ideutificatiou There are mainly two opposing views on how one should deal with English idioms, which have been identified as compound tokens in our framework: one stresses the decomposltlonality of idioms into constituent parts (Wasow, Sag, and Nunberg 1983; Gazxlar et al 1985; Stock 19891; another considers idioms as units of language as basic as word and wholly non-compositional In meaning (Wood 1986; Linden et al 1990; Santos 1990).


Santos (1990) explored a pragmatic way to transfer English idioms and fixed expressions in the domain of machine translation.


