(~) 1994 Association for Computational Linguistics Computational Linguistics Volume 20, Number 3 parsing (e.g. chart parsing \[Church 1987\]), or where a formal system developed for semantic representations of tense is applied to the temporal structure of phonology (Bird and Klein 1990), or where complex arrangements of phonological features are represented in the familiar notation of attribute-value matrices (Wiese 1990).


