This can be made precise for instance along the lines of Manaster-Ramer and Zadrozny (1990), where we argue that one can compare expressive power of various grammatical formalisms in terms of relations that they allow us to define; the same approach can be applied to semantics, as we show it below.


A. Manaster-Ramer & W. Zadrozny (1990).


We first convert an attribute value grammar into an equivalent non-attributed grammar by creating new non-terminals and encoding the attributes in the names of the new non-terminals (see Manaster Ramer and Zadrozny (1990) and Pollard and Sag (1994)).


