Existing approaches to IMT (Blanchon, 1994; Boitet, 1990; Brown and Nirenburg, 1990; Kay, 1973; Maruyama and Watanabe, 1990; Whitelock et al. , 1986; Zajac, 1988) place the MT system in control of the translation process and for the most part limit the human's role to performing various source language disambiguations on deman& Although this arrangement is appropriate for some applications, notably those in which the user's knowledge of tile target language may be limited, or where there are multiple target, languages, it is not well suited to tile needs of professional oi' other highly skilled translators.


\[5\] Brown, R. D. & Nirenburg, S. , (1990).


IMT first appeared as part of Kay's MIND system (Kay, 1973), where the user's role was to help the computer analyze the source text by answering questions about word sense, ellipsis, phrasal attachments, etc. Most later work on IMT, eg (Blanchon, 1991; Brown and Nirenburg, 1990; Maruyama and Watanabe, 1990; Whitelock et al. , 1986), has followed in this vein, concentrating on improving the question/answer process by having less questions, more friendly ones, etc. Despite progress in these endeavors, systems of this sort are generally unsuitable as tools for skilled trans\]\[ators because the user serves only as an advisor, with the MT components keeping overall control over the translation process.


