1 Background and System Overview FoG (for Forecast Generator) was developed during 1985-89 (Kittredge et al. , 1986; Bourbeau et al. , 1990).


Since conceptual structures are used for example in text generation (Bourbeau et al. 1990) or knowledge-based machine translation (Nirenburg et al. 1992), typed feature structures provide an attractive alternative to current procedural implementations.


Examples of these tasks include construing the speaker's situation in realizable terms given the available vocabulary and syntactic resources (an especially important task when the source is raw data, e.g., precisely what points of the compass make the wind "easterly," \[Bourbeau et al. 1990\]); selecting the information to include in the utterance and deciding whether it should be stated explicitly or left for inference; distributing the information into sentences and giving it an organization that reflects the intended rhetorical force, coherence, and necessary cohesion given the prior discourse; and finding a mapping of the information to linguistic resources that is collectively expressible (i.e. , has a surface realization; see Meteer 1992).


A few start with an unanalyzed body of numerical data (e.g. Bourbeau et al. 1990; Kukich 1988).


This is the approach used in the systems TEXT (McKeown 1985), GENARO-MUMBLE (Conklin 1983; Meteer et al. 1987), PENMAN (The Penman NLG 1989), SPOKESMAN (Meteer 1990), EPICURE (Dale 1992), KALIPSOS (Nogier 1990) and in the generators based on the Meaning-Text Theory (MTT) (Mel'Suk and Pertsov 1987) such as: FOC (Bourbeau et al. 1990), GossIP (Carcagno and Iordanskaja 1993) and LFS (Iordanskaja et al. 1994).


