J92-2005:1	110:347	In the hierarchical lexicon, the principle of priority to the instance 4 See van der Linden and Kraaij (1990) and van der Linden (1991) for a more extensive comparison of this definition and the traditional one.
---------------------------------------------------
J92-2005:2	287:347	Van der Linden and Kraaij (1990) discuss two alternative formalizations for conventionality.
---------------------------------------------------
