W97-0902:1	32:125	It is doubtful whether a complete parse of a sentence conraining these kinds of errors can be achieved with today's technology (Thurmair 1990).
---------------------------------------------------
A92-1017:2	88:129	5 Status of Implementation A first prototype of the system described above has been developed in C under UNIX within the ESPRIT II project 2315 "Translator's Workbench" (TWB) as one of several separate modules checking basic as well as higher levels of various languages Ilike grammar and style; see (Thurmair, 1990) and (Winkelmann, 1990)\].
---------------------------------------------------
C92-3160:3	66:82	4 Status of Implementation A first prototype of the system described above has been developed in C under UNIX within the ESPRIT I1 project 2315 "Translator's Workbench" (TWB) as one of several orthogonal modules checking basic as well as higher levels (like grammar and style; see (Thurmair, 1990) and (Winkelmann, 1990)) of various languages.
---------------------------------------------------
