Di Eugenio claims that discourse sequences in Italian that are not discourse-coherent according to centering theory produce a garden-path effect (Di Eugenio 1990). 
This analysis provides support for Shibatani's claim that the interpretation of the topic marker, wa, depends on the discourse context (Shibatani 1990). 
Thus in 17 cases, an adequate retrieval cue is constructed from processing the pronoun and the matrix verb (Di Eugenio 1990). 
I build on my previous work (Di gugenio, 1990) that accounted for the alternation of null and strong prottouns in subject position. 
222 Barbara J. Grosz et al. Centering follow-on research can be roughly grouped in a few main areas:  Cross-linguistic work on centering: 25 (German, Hebrew, Italian, Japanese, Korean, and Turkish): Di Eugenio (1990); Hoffman and Turan (1993); Kameyama (1985, 1986, 1988); Rambow (1993); Walker, Iida, and Cote (1990, 1994); Yongkyoon (1991); Ziv and Grosz (1994). 
