The augmented grammar compilation procedure presented here is already quite general: it appears to subsume both the static compilation procedure of Strzalkowski (1990c), and the head-driven grammar evaluation technique of Shieber et al. 
The general algorithm has been described in (StrTalkowski, 1990c; Strzalkowski and Peng, 1990). 
Strzalkowski (1990) and Strzalkowski/Peng (1990) describe a compiler that transforms a grammar originally written for parsing into an efficient generator. 
ESSENTIAL ARGUMENTS: AN EXTENSION The notion of an essential argument in a PROLOG literal has been first introduced in (Strzalkowski, 1989), and subsequently extended in (Strzalkowski, 1990bc; Sttzalkowski and Peng, 1990). 
12 yj may be partially "out"; see (Strzalkowski, 1990c) for the definition of delayed "out" status. 
