Finally, navigation through COGNITERM is facilitated by CODE's Browser, which allows the knowledge to be accessed either by names of concepts or names of their characteristics, both of which can be presented in a conceptual (i.e. hierar3 This first phase of our research has already been documented elsewhere: a general technical description of CODE can be found in Skuce (in press b); an analysis of the relationship between terminology and knowledge engineering can be found in Meyer 1991 and (in press); the three terminology-intensive applications are described in Skuce and Meyer 1990a/b (term bank construction), Skuce (in preparation) (software engineering), and Downs et al. 1991 (database design).


A GENERIC TOOL FOR TERMINOLOGY-ORIENTED KNOWLEDGE MANAGEMENT As has been argued elsewhere (e.g. Ahmad et al. 1989, Czap and Nedobity 1990, Meyer and Paradis 1991, Parent 1989, Skuce and Meyer 1990a/b, Wijnands 1989), the knowledge management problems of terminology are not unique to this field.


CODE has been tested in two terminology applications: a bilingual vocabulary project at the Department of the Secretary of State of Canada (Meyer and Paradis 1991, Skuce and Meyer 1990a/b) and a software documentation project at Bell Northern Research, the Canadian counterpart of Bell Labs (Skuce 1991).


