Carter (1990) has made a development of this algorithm which improves the efficiency when nsed together with bottom-up parsing.


This is a generalization of the notion called am consistency (Mackworth 1977) or pair-wise cousisteucy, and is equlva\]ent tn the flrst two steps of Ka.sper's (1987) successive aptnvximatimL Algo rithms for achieving more global consistency by look: ins at mnltlple constraint matrices are possibh+, but as Carter (1990) argues in his paper on the experimen.


Prolog CU CP 3.88 6.88 5.64 29.84 19.54 12.49 (out of memory) 245.34 17.32 65.27 19.34 14.66 Table h Computation Time 6 Related Work In the context of graph unification, Carter (1990) proposed a bottom-up parsing method which abandons information irrelevant to the mother structures.


