P93-1019:1	146:147	One symptom of the problem is seen in the treatment of nonphonologically conditioned allomorphy, such as German umlaut, which (Trost 1990) correctly criticizes as ad hoc in finite-state morphology because the latter deals only in phonological (or graphemic) categories.
---------------------------------------------------
P93-1019:2	105:147	Therefore some allomorphic rules 97r* denotes the Kleene closure over alphabet 11" and A the complement of A with respect to ~r. 144 are restricted in nonphonological ways, applying only to certain word classes, so that some stems admit idiosyncratic exceptions with respect to the applicability of rules (see Bear 1988, Emele 1988, Trost 1991) To overcome the first difficulty, a number of researchers have suggested augmenting FA with "word grammars", expressed in terms of feature formalisms like PATR II (Bear 1986) or HPSG (Trost 1990).
---------------------------------------------------
W98-1312:3	59:109	Feature-unification notation, as in D-PATR, has been proposed and even implemented in a number of morphology systems for constraining morphotactic dependencies (Karttunen, 1984; Karttunen, 1986; Bear, 1986; Kataja and Kbskenniemi, 1988; Beesley et al. , 1989; Trost, 1990).
---------------------------------------------------
E95-1028:4	7:189	The original formulation has been extended to allow morphotactic constraints to be expressed by feature specification (Trost, 1990; A1shawi et al, 1991) rather than Koskenniemi's less perspicuous device of continuation classes.
---------------------------------------------------
E95-1028:5	9:189	The automata may be derived from the rules alone (Trost, 1990), or involve composition with the lexicon (Karttunen, Kaplan and Zaenen, 1992).
---------------------------------------------------
E91-1023:6	107:209	These include two-level morphology with continuation lexica and two-level rules (Koskenniemi 1983), its derivates with feature-based lexicon and two-level rules (Karttunen 1987, Bear 1986, Trost 1990), and Cahill's DATR-driven morphology with phonological descriptions in MOLUSC (1990).
---------------------------------------------------
