A variety of SPE implementations exist (independently of the finite-state transducer model) starting from Bobrow and Fraser (1968) and including models for applying rules in reverse (Bear 1990; Maxwell 1991).


Via the work of Johnson (1972), Koskenniemi (1984), and Kaplan and Kay--the latter in circulation since the early eighties but appearing in published form for the first time in the present collection--one could reasonably argue that SPE gave rise to finite-state morphology (Antworth 1990; Ritchie et al. 1992; Sproat 1992).


Examples of the second type are all symbolic (Johnson 1984; Dresher and Kaye 1990; Ellison 1993; Bird 1994).


