(Boitet, 1989; Somers et al. , 1990)).


An interactive dependency parser reported in (Maruyama et al. , 1990), is based on an interface like Kana-Kanji conversion, and shares characteristics described above 2.


7 Discussion Interactive method in machine translation have been pursued by many people (Kay, 1973; Melby et al. , 1980; Tomita, 1984; Huang, 1990; Somerset al. , 1990a; Boitet et al. , 1995).


A user-driven approach to interactive translation, proposed by (Somerset al. , 1990b), is based on cut and paste operations, where the content of copy buffer is translated when it is pasted.


