For example, the analysis of conjunctions in LFG (Kaplan and Maxwell 1988b) and the formalizations of Discourse Representation Theory (Kamp 1981) presented in Johnson and Klein (1986) and Johnson and Kay (1990) require additional mechanisms for representing and manipulating aggregates or sets of values in ways that are beyond the capability of such "pure" attribute-value systems.


Johnson and Klein (1986) and Johnson and Kay (1990) show how "set-valued" features can be used to express Discourse Representation Theory (Kamp 1981) in a complex-feature based grammar formalism.


Weathra also features a dynamic discourse representation including the discourse objects which may be referred to by the words and anaphora in the text (cf Karttunen, 1976, Johnson & Kay, 1990).


