2Again our T is similar to Wedekind (1988)'s adequacy condition C. 53 Wedekind 1988, Momma and DSrre 1987, Shieber, van Noord, Pereira and Moore 1990, Estival 1990, Gardent & Plainfoss~ 1990) have taken the adequacy condition T to be strict isomorphism, possibly of some formalismspecific sub-part of the structures Xs and X, e.g. the f-structure part in the case of Wedekind (1988) and Momma and DSrre (1987).


Some of the recent resea~h in this area is reported in (Calder et al. , 1989; Dymetman and Isabelle, 1988; Dymetman et al. , 1990; Estival, 1990; Hasida and Isizaki, 1987; Ishizaki, 1990; Shieber, 1988; Shieber et al. , 1990; Strzalkowski, 1990a-c; Strzalkowski and Peng, 1990; van Noord, 1990; and Wedekind, 1988).


ELU ELU exploits the parser and unifier of UD (Johnson and Rosner, 1989), but differs from that earlier system in the addition of a generator (Russell et al. , 1990) and a transfer component (Estival et al. , 1990; Russell et al. , 1989).


Transfer reversibility is a working hypothesis we are pursuing (Estival et al. , 1990), but its consequences are harder to foresee; only experimentation will help us to (possibly) identify classes of natural language phenomena where the translation relation cannot be reversed.


