In fact, we also show that the formalism defined in Harbusch (1990) (where only one feature structure is associated with every node) turns out to be similar to the use of FTAG with an additional decision to merge every pair of quasi-nodes by default.


The above description essentially captures the definition of the formalism presented by Harbusch (1990).


In fact, Harbusch (1990) defined such a treatment of TAG where only one feature structure is associated with each node.


