In Japanese, the similarity is used for analyzing conjunctive structures and the method is found effective(Kurohashi and Nagao, 1992).


If words can be defined with concepts in a hierarchical structure, it is possible to measure the meaning similarity between words with an information measure based on WordNet (Resnik, 1993), or structure level information based on a thesaurus (Kurohashi and Nagao, 1992).


Kurohashi and Nagao (1992) work on the same problem for Japanese.


Following Kurohashi and Nagao (1992), Resnik makes decisions based on similarity of form (i.e. , number agreement: P=53%, R=90.6%), similarity of meaning (P=66%, R=71.2%) and conceptual association Example Predicts P(%) R(%) (buy) and sell orders NO ellipsis 33.33 1.40 buy (and sell orders) NO ellipsis 70.00 4.67 buy: and sell orders NO ellipsis 0.00 0.00 buy; and sell orders NO ellipsis 66.67 2.80 buy.


