This feature differentiates collaborative negotiation from argumentation (Birnbaum, Flowers, and McGuire 1980; Reichman 1981; Flowers and Dyer 1984; Cohen 1987; Quilici 1992).


5 The argumentation system described in (Quilici, 1992) used a plan-based model of the user's beliefs to recognize the justification for-a user's proposal and provide its own justifications.


Several researchers have dealt with different aspects of argumentation; e.g., (Flowers et al. , 1982; Quilici, 1992; Chu-Carroll and Carberry, 1995; Carberry and Lambert, 1999).


This differentiates collaborative negotiation from argumentation (Birnbaum et al. , 1980; Reichman, 1981; Cohen, 1987; Quilici, 1992).


2 Related Work Researchers have studied the analysis and generation of arguments (Birnbaum et al. , 1980; Reichman, 1981; Cohen, 1987; Sycara, 1989; Quilici, 1992; Maybury, 1993); however, agents engaging in argumentative dialogues are solely interested in winning an argument and thus exhibit different behavior from collaborative agents.


