Moreover, some recent thinking on the phonology-phonetics interface supports this view (Pierrehumbert 1990; Coleman 2 (Bach and Wheeler 1981; Wheeler 1981; Bird 1990; Cahill 1990; Coleman 1991; Scobbie 1991; Bird 1992; Walther 1992; Mastroianni 1993; Russell 1993) 456 Steven Bird and Ewan Klein Phonological Analysis in Typed Feature Systems 1992).


We approach these challenges by adopting a formal, nonprocedural, nonlinear model of phonology and showing how it can be integrated into HPSG, following on the heels of recent work by the authors (Bird and Klein 1990; Bird 1992; Klein 1992).


