We implemented an accurate sentiment analyzer by making use of an existing transfer-based machine translation engine (Watanabe, 1992), replacing the translation patterns and bilingual lexicons with sentiment patterns and a sentiment polarity lexicon.


Recent work in the example-based I'ramework inchldes memory-based translation (Sate & Nagao 1990), similarity-driven translation (Watanabe 1992), transl'cr-driven nlachine translation (Furusc & Iida 1996), and patten>based machine translation (Watanabe & Takeda 1998).


