In a methodology similar to that used by Power (1979), Carletta (1992) and Walker (1993), knowledge is distributed by a random process between agents, and the resulting interaction between these collaborating agents is observed.


In this example, repetition functions as an effective turn release, signalling to the partner that she needs to confirm the information in a more convincing way  In NL generationl conversational aspects have been addressed especially in interactive explanation and instruction generation (Cawsey, 1993; Carletta, 1992; Moore, 1995; Inui et al. , 1996).


The choice between the different control strategies is related to system's overall behaviour: communication between TM and DM takes time, and the dialogues become cumbersome if the user's knowledge is constantly queried, but if too much is assumed, backtracking and repairs may be necessary (Carletta, 1992).


