Dependency grammar (DG) takes as fundamental ~This approach of 'normal form parsing' has been applied to the associative Lambek calculus in (K6nig, 1989), (Hepple, 1990), (Hendriks, 1992), and to Combinatory Categorial Grammar in (Hepple & Morrill, 1989), (Eisner, 1996).


For earlier work on chart-parsing type-logical formalisms, specifically the associative Lambek calculus, see KSnig (1990), Hepple (1992), K5nig (1994).


Such a formalisation should readily provide the basis for a chart based approach to parsing hybrid logic grammars, after the manner of existing chart methods for use with L (KSnig 1990; Hepple 1992).


The method of Hepple (1992) avoids this complicated book-keeping, and also rules out some useless subderivations allowed by Khnig's method, but does so at the cost of computing a representation of all the possible category sequences that might be tested in an exhaustive sequent proof search.


aThis 'excision' step has parallels to the 'emit' step used in the chart-parsing approaches for the associative Lambek calculus of (KSnig, 1994) and (Hepple, 1992), although the latters differs in that there is no removal of the relevant subformula, i.e. tile 'emitting formula' is not simplified, remaining higher-order.


