The sharing version of Copy is similar to the variant in (Tomabechi, 1992).


We will adopt the same terminology as Tomabechi in (Tomabechi, 1992).


The conditions for sharing mentioned in (Tomabechi, 1992) are: (1) bottom and atomic nodes can be shared; (2) complex nodes can be shared unless they are modi ed.


To distinguish structure sharing at the implementation level fl'om that at the logical lew'l (that is, coreference relations between feature-addresses), the lbrmer is called data-structure sharing and the latter is called feature-structure sharing (Tomabechi, 1992).


These algorithms are b0,sed on Wroblewski's algorithm, and Tomabechi (1992) has proposed a data-structure-sharing version of his quasi-destructive unification.


