There are some morphological description systems showing some features in common with Humor 99 like paradigmatic morphology (Calder 1989), or the Paradigm Description Language (Anick & Artemieff 1992) but they don't have 12 The meta-dictionary shown in the example compiles with Humor's lexicon compiler without any changes.


Molphological description systems without lmge implementations (like the paradigmatic morphology of Calder (1989), or Paradigm Description Language of Anick and Artemieff(1992) are not listed here, because their importance is mainly theoretical (at least, for the time being).


