2 PriorPictorialCommunicationWork At one extreme, there has been significant prior workontext-to-scenetypesystems,whichwere oftenintendedtoaidgraphicdesignersinplacing objectsina3Denvironment.ExamplesystemsincludeNALIG(Adornietal.,1983),SPRINT(Yamada et al., 1992), Put (Clay and Wilhelms, 1996), and others (Brown and Chandrasekaran, 1981).Perhapsthebestknownsystemofthistype, WordsEye(CoyneandSproat,2001),usesalarge manuallytaggedcollectionof3Dpolyhedralmodelstocreatephoto-realisticscenes.Similarly,CarSim (Johansson et al., 2005) can create animated scenes,butoperatesexclusivelyinthelimiteddomainofreconstructingroadaccidentsfromtraffic reports.Thesesystemscatertodetaileddescriptive textwithvisualandspatialelements.


Different types of text and of images have been considered, for example: narrative text and motion pictures (Kahn, 1979; Abraham and Descl~s, 1992), spatial descriptions and 3-dimensional sketches (Yamada et al. , 1992; Arnold and Lebrun, 1992), 2-dimensional spatial scenes and linguistic descriptions (Andr~ et al. , 1987), 2-dimensional image sequences and linguistic reports (Andr~ et al. , 1988).


