Elhadad (1992) draws a similar conclusion (though his list of potentially argumentative relations is somewhat shorter).


In 1096 related work, this abstract structure is often lost certainly in coherence relation based NLG (such as operational RST), but also in (Elhadad, 1992) (which captures some, but not all of the commonly found argument structures) and in (Maybury, 1993) (which fails to capture the hierarchical nature of argument).


In contrast to, e.g., \[Fawcett et al. , 1992\] and \[Elhadad and Robin, 1_992\], who deal with lexically biased sentence organization within the grammar, we take a radically lexicalist position (similar to that of \[McDonald, 1991\]) in that we assume that lexicalization has to take place before grammatical realization; and that it is the words chosen, which dictate the possible syntactic realizations of a content to be communicated.


Elhadad's prol)osal (Elhadad, 1992)to use 7bpoi (inference,'ules that encode relations between t)ropo sitk)ns incorporating lexical material) as discourse structure relations is aimed at exploiting lexical phenomena for discourse organization.


