3 Related Work There is a growing body of research into approaches ibr generating text surrmmries, including approaches based on sentence extraction (Kupice et al., 1995), text generation from templates (McKeown and Radev, 1995) and machine-assisted abstraction (Tsou ct al., 1992).


Results of discourse analysis can be used to solve many important NLP problems such as anaphoric reference (Hirst 1981), tense and aspect analysis (Hwang and Schubert 1992), intention recognition (Grosz and Sidner 1986; Litman and Allen 1990), or'can be directly applied to computational NLP applications such as text abstraction (Ono et al. 1994; T'sou et al. 1996) and text generation (McKeown 1985; Lin et al. 1991).


