In (Wang et al. , 1992), a title driven method was used to identify personal names.


Recent work includes (Sproat et al. , 1994) and (Wang et al. , 1992).


In a more recent study than Chang et al. , Wang, Li, and Chang (1992) propose a surname-driven, non-stochastic, rule-based system for identifying personal names.


ACKNOWLEDGEMENTS We thank United Informatics for providing us with our corpus of Chinese text, and BDC for the 'Behav5We were recently pointed to (Wang et al. , 1992), which we had unfortunately missed in our previous literature search.


