also (Bateman, 1991: Bateman et al. , 1992; Henschel, 1995; Teich, in press)): the grammatical types in SI:G, however, are functionally rather than surface-syntactically motivated.


terms of Penman-style 'preselection', althoush nondirectional relations such as those suggested in \[Bateman et al. , 1992\] are both necessary and under investigation.


The system processes are based on the PENMAN generation system \[Mann and Matthiessen, 1985\] as extended for multilinguality by \[Zeng, 1992\], and includes work on multilinguality and text planning undertaken within the KOMET project \[Bateman et al. , 1993\].


Since conceptual structures are used for example in text generation (Bourbeau et al. 1990) or knowledge-based machine translation (Nirenburg et al. 1992), typed feature structures provide an attractive alternative to current procedural implementations.


