 Use of recta-programming for self-monitoring to ensure generation of unambiguous utterances (Neumann and van Noord, 1992)  Work in the area of Explanation-Based Learning (EBL) to learn frequently used' structures (Samuelsson, 1994)  Tabulation techniques, from the use of wellformed substring tables to the latest developments in Earley deduction, and memoing techniques for logic programming (Neumann, 1994)  Work based on Constraint Logic Programming (CLP) to provide processing models for principle-based grammars (Matiasek, 1994)  Using coroutining (dif, freeze etc).


