,1996) and for the representations used for transfer in Shake-and-Bake translation (Whitelock, 1992). 
2.2 Suitable Grammars The Shake-and-Bake system of (Whitelock, 1992) employs a bag generation algorithm because it is assumed that the input to the generator is no more than a collection of instantiated signs. 
2s The important point is that this entire concept is fully 27 A related, but more general, strategy would be to handle such cases in bilingual lexical entries (see, for example, Beaven 1992a, 1992b; Whitelock 1992; Trujillo 1992). 
Hence, information access for transformation processes like transfer is not as straightforward as it could be when using flat set representations (Beaven, 1992; Whitelock, 1992). 
However, the Shake-and-Bake generation algorithm of (Whitelock, 1992) is NPcomplete. 
