Other variations of EBMT systems are hybrids that integrate an EBMT component as one of multiple sources of transfer knowledge (in addition to other transfer rule or knowledge based components) used during translation (Frederking et al. 1994; Takeda et al. 1992).


3.2 Results We have implemented this method on an English-toJapanese machine translation system called Shalt2 (Takeda et al. , 1992), and conducted experiments to evaluate the effectiveness of this method.


