2 Related Work Because a quantified expression refers to multiple entities in a domain, our work can be categorized as referring expression generation (Dale, 1992; Reiter and Dale, 1992; Horacek, 1997). 
2 Overview of Prior Approaches The incremental algorithm (Reiter and Dale, 1992) is the most widely discussed attribute selection algorithm. 
Reiter and Dale 1992). 
Reiter and Dale (1992) describe a fast algorithm for generating referring expressions in the context of a natural language generation system. 
 the Incremental Algorithm (Reiter and Dale, 1992; Dale and Reiter, 1995) considers the available properties to be used in a description via a preference ordering over those properties; see Algorithm 3. 
