Full details of the parser can be found in (Strzalkowski, 1992).


1992; Strzalkowski 1992).


TFP stands for Tagged Text Parser, and it has I:een described in detail in (Strzalkowski, 1992) and ev~duated in (Strzalkowski & Scheyen, 1993).


4 A complete description can be found in (Strzalkowski, 1992).


5 Full details of TTP parser have been described in the TREC-1 report (Strzalkowski, 1993a), as well as in other works (Strzalkowski, 1992; Strzalkowski & Scheyen, 1993).


