The T/L, able to analyse words lacking from the dictionary, is intended to fimction primarily as a lexical front-end for the DMIA ) syntactic analyser (Spyns and Adriaens, 1992).


As the syntactic level uses a "logic variant" of the LSP grammar formalism (Hirschman and Dowding, 1990), the Dutch morpho-syntactic module (Spyns and Adriaens, 1992) can replace the LSP parser.


For Dutch, a limited prototype has been developed (Spyns, 1991), (Spyns and Adriaens, 1992).


