P98-1022:1	6:178	Bod 1992, 95; Scha 1992; Sima'an 1995; Rajman 1995).
---------------------------------------------------
P98-1010:2	182:194	We refer here only to the DOP (Data Oriented Parsing) method (Bod, 1992) which, like the present work, is a memory-based approach.
---------------------------------------------------
W09-0906:3	11:149	DOP was first proposed by Scha (1990), and implemented and developed by Bod (1992, 1998).
---------------------------------------------------
W09-0906:4	3:149	1  1 Introduction Data-Oriented Parsing (DOP) is a state-of-the art approach to both supervised and unsupervised parsing (Bod1992, 1998, 2006a, 2006b, 2007a, 2007b, Zollman and Simaan 2005), which has mostly been developed within a technologicallyoriented computer science context.
---------------------------------------------------
P01-1010:5	154:160	context-free rules Charniak (1996) Collins (1996), Eisner (1996) context-free rules, headwords Charniak (1997) context-free rules, headwords, grandparent nodes Collins (2000) context-free rules, headwords, grandparent nodes/rules, bigrams, two-level rules, two-level bigrams, nonheadwords Bod (1992) all fragments within parse trees Scope of Statistical Dependencies Model Figure 4.
---------------------------------------------------
E93-1011:6	117:117	In that sense, our method can be viewed as a particular implementation of a model of language Performance (Bod, 1992), and may belong to the family of Data-Oriented methods in Computational Linguistics.
---------------------------------------------------
E93-1006:7	90:164	In (Bod, 1992b) superstrong equivalence relations between other stochastic grammars are studied.
---------------------------------------------------
E93-1006:8	19:164	Data Oriented Parsing fDOP) (Scha, 1990; Bod, 1992a), distinguishes itself from other statistical approaches in that it omits the step of inferring a grammar from a corpus.
---------------------------------------------------
E93-1006:9	91:164	4 Monte Carlo Parsing It is easy to show that an input string can be parsed with conventional parsing techniques, by applying subtrees instead of rules to the input string (Bod, 1992a).
---------------------------------------------------
E93-1006:10	42:164	For a treatment of DOP in more formal terms we refer to (Bod, 1992a).
---------------------------------------------------
W06-2903:11	80:150	As is true for many other grammar formalisms in which there is a derivation / parse distinction, an alternative to finding the most probable parse is to find the most probable derivation (Vijay-Shankar and Joshi, 1985; Bod, 1992; Steedman, 2000).
---------------------------------------------------
W00-0737:12	51:107	Such works include Bod(1992) for parsing, Argamon et a1.(1998) for shallow natural language patterns and Daelemans et a1.(1999) for shallow parsing.
---------------------------------------------------
E95-1015:13	2:230	(Scha, 1990; Bod, 1992, 1993a).
---------------------------------------------------
E95-1015:14	11:230	1 Data-Oriented Parsing A Data-Oriented Parsing model (Scha, 1990; Bod, 1992, 1993a) is characterized by a corpus of analyzed language utterances, together with a set of operations that combine sub-analyses from the corpus into new analyses.
---------------------------------------------------
P98-1021:15	23:195	Bod (1992) demonstrated that DOP can be implemented using conventional context-free parsing techniques.
---------------------------------------------------
P98-1021:16	11:195	Bod 1992, 1995; Bod & Kaplan 1998; Scha 1992; Sima'an 1995, 1997; Rajman 1995) is a probabilistic parsing model which does not single out a narrowly predefined set of structures as the statistically significant ones.
---------------------------------------------------
P98-1021:17	131:195	Next, parsing proceeds with the subtrees that are triggered by the dialogue context C (provided that all subtrees are converted into equivalent rewrite rules -see Bod 1992, Sima'an 1995).
---------------------------------------------------
C00-1011:18	24:160	Probabilistic vs. Non-Probabilistic Data-Oriented Parsing Both probabilistic and non-probabilistic DOP are based on the DOP model in Bod (1992) which extracts a Stochastic Tree-Substitution Grammar fi'om a treebank ("STSG-DOP").
---------------------------------------------------
N06-1045:19	16:166	It occurs because many systems, such astheonesproposedby(Bod,1992),(Galley,et.
---------------------------------------------------
C96-2215:20	2:167	Abstract This paper studies the computational complexity of disambiguation under probabilistic tree-grammars as in (Bod, 1992; Schabes and Waters, 1993).
---------------------------------------------------
C96-2215:21	8:167	Due to this extension, the one to one mapping between a derivation and a parsetree, which holds in CFGs, does not hold any more; many derivations might generate the same parse-tree, rl'his seemingly spurious ambiguity turns out crucial for statistical disambiguation as defined in (Bod, 1992) and in (Schabes and Waters, 1993), where the derivations are considered different stochastic processes and their probabilities all contribute to the probability of the generated parse.
---------------------------------------------------
W96-0111:22	43:275	Bod (1992, 1993a) shows that conventional context-free parsing techniques can be used in creating a parse forest for a sentence in DOP1.
---------------------------------------------------
W96-0111:23	23:275	In Bod (1992, 1993a), a first instantiation of this model is given, called DOP1, which uses (1) labelled trees for the utterance analyses, (2) subtrees for the fragments, (3) nodesubstitution for combining subtrees, and (4), the sum of the probabilities of all distinct ways of generating an analysis as a def'mition of the probability of that analysis.
---------------------------------------------------
W96-0111:24	10:275	1 Introduction The Data-Oriented Parsing (DOP) method suggested in Scha (1990) and developed in Bod (19921995) is a probabilistic parsing strategy which does not single out a narrowly predefined set of structures as the statistically significant ones.
---------------------------------------------------
W99-0629:25	45:225	memory-based approaches to parsing, see (Bod, 1992) and (Sekine, 1998).
---------------------------------------------------
P97-1021:26	21:230	For the syntactic dimension of language, various instantiations of this data-oriented processing or "DOP" approach have been worked out (e.g. Bod (1992-1995); Charniak (1996); Tugwell (1995); Sima'an et al.
---------------------------------------------------
P97-1021:27	26:230	We first summarize the first fully instantiated DOP model as presented in Bod (1992-1993).
---------------------------------------------------
