Studies of robust parsing within unification-based grammars have been explored by many researchers (Douglas and Dale, 1992; Imaichi and Matsumoto, 1995).


To handle such sentences, most previous approaches apply various heuristic rules (Jensen et al. , 1992; Douglas and Dale, 1992; Richardson and Braden-Harder, 1988), including  Relaxing constraints in the condition part of a grammatical rule, such as number and gender constraints  Joining partial parses by using meta rules.


Regarding their treatment, different approaches have been proposed:  The relaxation of syntactic constraints (Douglas and Dale 1992).


Although attempts have been made to modify PS grammars/parsers to cope with extragrammatical input, e.g. \[Carbonell and Hayes1983, Douglas and Dale1992, Jensen et al.1983, Mellish1989\], this is a feature which has to be 'added on' and tends to affect the statement of the grammar.


