But Lascarides and Oberlander (1992a) urge that the temporal coherence of text is characterised in terms of, among other things, the stronger basic relation of causal proximity.


Let (% ~,fl) be the update function, which means "the representaXLascaxides and Asher (1991a) introduces the general framework and applies it to interpretation; Oberlander and Lascaxides (1992) and Lascarides and Oberlander (1992b) use the framework for generation.


We also need better techniques for communicating the temporal relationships between events in cases where they are not listed in chronological order (Oberlander and Lascarides, 1992).


