Guthrie, and Guthrie, 1992), (Bruce and Wiebe, 1994)). 
Simmulated annealing, a numerical optimisation algorithm, was used to make this process practical (Cowie, Guthrie, and Guthri~, 1992), choosing an assignment of senses from as many as 10 l choices. 
We are implementing a simple algorithm which prefers close senses in our domain hierarchy which was derived from LDOCE (Bruce and Guthrie, 1992). 
The semantic classes in LDOCE are not provided with a hierarchy, but, Bruce and Guthrie (Bruce and Guthrie, 1992) manually identified hierarchical relations between tile semantic classes, constructing them into a hierarchy which we use to resolve the restrictions. 
Recent examples of this work include (Bruce and Guthrie, 1992), (Bruce and Wiebe, 1994), (McRoy, 1992). 
