We have (11) Hypernym Patterns based on patterns proposed by (Hearst, 1992) and (Snow et al., 2005), (12) Sibling Patterns which are basically conjunctions, and (13) Part-of Patterns based on patterns proposed by (Girju et al., 2003) and (Cimiano and Wenderoth, 2007). 
Hearst (1992) explored the use of lexical patterns for extracting hyponym relations, with patterns such as such as. Berland and Charniak (1999) extract part-of relations. 
86 Girju, Badulescu, and Moldovan Automatic Discovery of PartWhole Relations In computational linguistics, although a considerable amount of work has been done on semantic relation detection, 7 the work most similar to the task of identifying partwhole semantic relations is that of Hearst (1992) and Berland and Charniak (1999). 
This rule is also described in (Hearst, 1992). 
For example, Hearst (1992) used the pattern such as to discover hyponyms and Berland and Charniak (1999) used the pattern of the to discover meronyms. 
