One especially interesting possibility is to apply multiple-pass techniques to formalisms that require >> O(n 3) parsing time, such as Stochastic Bracketing Transduction Grammar (SBTG) (Wu, 1996) and Stochastic Tree Adjoining Grammars (STAG) (Resnik, 1992; Schabes, 1992). 
2.3 TAG Model The model of (Chiang, 2000) is based on stochastic TAG (Resnik, 1992; Schabes, 1992). 
So although it is now possible to extract at least subcategorisation data from large corpora 2 with 2Grishman & Sterling (1992), Poznanski & Sanfilippo (1993), Resnik (1993), Pdbas (1994), McCarthy (1997) and others have shown that it is possible also to a119 some degree of reliability, it would be difficult to integrate the data into this type of parsing system. 
See Resnik (1992), Schabes (1992), and Schabes and Waters (1993) for work on stochastic tree-adjoining grammars. 
2The work described here is completely different from the work reported in (Resnik, 1992) and (Schabes, 1992) concerning stochastic TAGs. 
