C96-2153:1	31:164	(Block and Schachtl, 1992), produce packed representations of this kind.
---------------------------------------------------
C96-1024:2	88:151	5 Syntax-Semantics Interface and Implementation 5.1 Grammar The LUD semantic construction component has been implemented in the grammar formalism TUG, Trace and Unification Grammar (Block and Schachtl, 1992), in a system called TrUG (in cooperation with Siemens AG, Munich, who provided the German syntax and the TrUG system).
---------------------------------------------------
