Regression methods were pioneered by Yang and Chute (1992) and Yang and Chute (1993) for information retrieval purposes, but the predicted continuous variable was not an end in itself in that work.


To improve classification accuracy, a variety of learning techniques are developed, including regression models (Yang and Chute, 1992), nearest neighbour classification (Yang and Liu, 1999), Bayesian approaches (Lewis and Ringuetee, 1994; McCallum et al. , 1998), decision trees (Lewis and Ringuetee 1994), neural networks (Wiener et al. ,1995) and support vector machines (Dumais and Chen, 2000).


