The '90s have in fact seen a renewed interest in grammar checking, and proposals have been made for systems covering English (Bernth, 1997) and other languages such as Italian (Bolioli et al. , 1992), Spanish and Greek (Bustamante and Ldon, 1996), Czech (Holan et al. , 1997) and Swedish (Hein, 1998).


In some case.s, these have be.en incorporated to traditional parsing techniques, as it is the case with feature relaxation in the context of unification-based formalisms (Bolioli et al. , 1992), or the addition of a set of catching error rules si)ecially handling the deviant constructions (Thurlnair, 1990).


The corrector is based on the general idea widely used in this kind of systems: if an input sentence is syntactically ill-formed, i.e. it cannot be assigned a syntactic structure (SyntS), the system considers minimal changes that enable it to construct a SyntS, and presents them as possible corrections (see, for example, Carbonell and Hayes 1983; Jensen et al. 1983; Weiscbedel and Sondheimer 1983; Mellish 1989; Bolioli et al. 1992).


