J06-3001:1	9:790	From multilingual texts, translation lexica can be generated (Gale and Church 1991; Kupiec 1993; Kumano and Hirakawa 1994; Boutsis, Piperidis, and Demiros 1999; Grefenstette 1999).
---------------------------------------------------
P96-1018:2	11:249	1 Introduction Corpus-based approaches based on bilingual texts are promising for various applications(i.e. , lexical knowledge extraction (Kupiec, 1993; Matsumoto et al. , 1993; Smadja et al. , 1996; Dagan and Church, 1994; Kumano and Hirakawa, 1994; Haruno et al. , 1996), machine translation (Brown and others, 1993; Sato and Nagao, 1990; Kaji et al. , 1992) and information retrieval (Sato, 1992)).
---------------------------------------------------
P95-1032:3	11:188	Existing lexicon compilation methods (Kupiec 1993; Smadja & McKeown 1994; Kumano & Hirakawa 1994; Dagan et al. 1993; Wu & Xia 1994) all attempt to extract pairs of words or compounds that are translations of each other from previously sentencealigned, parallel texts.
---------------------------------------------------
W95-0114:4	13:142	Most previous automatic lexicon compilation techniques require a sentence-aligned clean parallel bilingual corpus (Kupiec 1993; Smadja & McKeown 1994; Kumano & Hirakawa 1994; Dagan et al. 1993; Wu & Xia 1994).
---------------------------------------------------
W95-0114:5	21:142	In parallel corpora, this feature could be the positional co-occurrence of a word and its translation in the other language in the same sentences (Kupiec 1993; Smadja & McKeown 1994; Kumano & Hirakawa 1994; Dagan et al. 1993; Wu & Xia 1994) or in the same segments (Fung & Church 1994; Fung 1995).
---------------------------------------------------
W98-1107:6	256:279	This work also has ties to the work on automatic construction of translation lexicons (Wu and Xia, 1995; Melamed, 1995; Kumano and Hirakawa, 1994; Catizone et al. , 1993: Gale and Church, 1991).
---------------------------------------------------
W01-1411:7	12:168	2 Previous Work The most common approach to deriving translation lexicons from empirical data (Catizone, Russell, and Warwick, 1989; Gale and Church, 1991; Fung, 1995; Kumano and Hirakawa, 1994; Wu and Xia, 1994; Melamed, 1995) is to use some variant of the following procedure: 1 AF Pick a good measure of the degree of association between words in language C4 BD and words in language C4 BE in aligned sentences of a parallel bilingual corpus.
---------------------------------------------------
P97-1063:8	19:218	2 Co-occurrence With the exception of (Fung, 1998b), previous methods for automatically constructing statistical translation models begin by looking at word cooccurrence frequencies in bitexts (Gale & Church, 1991; Kumano & Hirakawa, 1994; Fung, 1998a; Melamed, 1995).
---------------------------------------------------
J00-2004:9	125:517	4.2 Nonprobabilistic Translation Lexicons Many researchers have proposed greedy algorithms for estimating nonprobabilistic word-to-word translation models, also known as translation lexicons (e.g. , Catizone, Russell, and Warwick 1989; Gale and Church 1991; Fung 1995; Kumano and Hirakawa 1994; Melamed 1995; Wu and Xia 1994).
---------------------------------------------------
