Finally, there is another approach that identifies them after the tagging process, allowing the correction of some tagging errors (Leech et al. , 1994).


I therefore chose to use an objective statistical measure, the perplexity of a very simple finite state model, to compare the tags generated with this clustering technique against the BNC tags, which uses the CLAWS-4 tag set (Leech et al. , 1994) which had 76 tags.


However, the issue of multiple markers, like those in the example above, is only now beginning 1British National Corpus (Leech et al. , 1994) 41 to be addressed.


