Grishman & Sterling (1992), Poznanski & Sanfilippo (1993), Resnik (1993), Ribas (1994) and others have shown that it is possible to acquire selection preferences from (partially) parsed data.


Ribas (1994) presented an approach which takes into account the syntactic position of the elements whose semantic relation is to be acquired.


Closely related proposals have been applied in syntactic disambiguation (Resnik, 1993b; Lauer, 1994) and to automatic acquisition of more KatzFodoresque selection restrictions in the form of weighted disjunctions (Ribas, 1994).


Some of these methods make use of prior knowledge in the form of an existing thesaurus (Resnik 1993a, 1993b; Framis 1994; Almuallim et al. 1994; Tanaka 1996; Utsuro and Matsumoto 1997), while others do not rely on any prior knowledge (Pereira, Tishby, and Lee 1993; Grishman and Sterling 1994; Tanaka 1994).


f(s): uulnber of times the franle type appeared, since the frequency of a. frame type equals the frequency of that frame with a certain slot marked The fi'equencies of a semantic class concerning an argument slot, of a frame type (dependent or independent of a verb) were calculated by all approach slightly difl'erent to Resnik's, originally proposed by (Ribas, 1994)/(Ribas, 1995).


