6.5 N-gram Model We first explored the use of trigram model of supertag disambiguation in Joshi and Srinivas (1994). 
Joshi and Srinivas (1994) define supertagging as the process of assigning the best supertag to each word. 
However, the problem of grammar size in TAG has to some extent been addressed both with respect to grammar encoding (Evans et al. , 1995; Candito, 1996) and parsing (Joshi and Srinivas, 1994; Evans and Weir, 1998). 
6.1 Early Work As reported in Joshi and Srinivas (1994), we experimented with a trigram model as well as the dependency model for supertag disambiguation. 
Joshi and Srinivas (Joshi and Srinivas, 1994) have developed a method called supertagging that similarly attaches complex syntactic tags (supertags) to words. 
