Nomoto and Nitta (1994) attempt to use Youmans' algorithm for distinguishing entire articles from one another when they are concatenated into a single file. 
Nomoto and Nitta (1994) implement the tf.idf version of TextTiling from Hearst (1993) and Hearst and Plaunt (1993) and evaluate it this way on Japanese newswire text. 
E-mail: hearst@sims.berkeley.edu c 2002 Association for Computational Linguistics Computational Linguistics Volume 28, Number 1 of it, for subtopic segmentation (Nomoto and Nitta 1994; Hasnah 1996; Richmond, Smith, and Amitay 1997; Heinonen 1998; Boguraev and Neff 2000). 
This approach differs from that of Youmans (1991) and Nomoto and Nitta (1994) in two main ways. 
Overall the scores are much stronger than those reported in Reynar (1994), and are comparable to those of Nomoto and Nitta (1994) whose best precision/recall trade-off on a collection of approximately 80 articles is approximately .50 precision and .81 recall. 
