d.bigrsm 7q \[E3 D L__I L___I \[__l L__J  =' I; I I, j J L Jr \]~  Figure l: i)-bigram 3.3 Calculation Mutual InfiJrmation with Distance Expression (1) iv for calculating mutual intbrmation between two events(Nobesawa et al. , 1994): l'(ai, bj, d) bj, d) = log v(.d/'(b,) (1) ai : a letter P(ai) : the possibility the letter ai appears l(ai, bj, d) : the possibility ai and bj appear together with the distance d in a sentence The parameter d shows the distance between two events.


