Such simplifications make it possible to encode morphemes on the Korean syllable-based alphabet, and are compatible with syllable-based models (Kang and Kim, 1994).


The following approaches belong to this group: longest matching algorithm, tabular parsing method using CYK algorithm (Kim, 1986), dictionary based approach (Kwon, 1991), two-level morphology(Lee, 1992), and syllable-based approach (Kang and Kim, 1994).


