W04-1101:1	59:218	Jones (1994) successfully shows that grammar with punctuation outperforms one without punctuation.
---------------------------------------------------
C96-2102:2	124:147	However, as pointed out by Jones (1994), it is difficult to see how this would be feasible in practice and there is little linguistic or psychological motivation for such a separation of lexicM text and punctuation.
---------------------------------------------------
C96-2102:3	18:147	They also point out some fundamental problems of the approach adopted by Jones (1994).
---------------------------------------------------
C96-2102:4	21:147	In addition, the basic implementation of Nunberg's punctuation linguistics seems untenable, certainly on a computational level, since it stipulates that punctuation phenomena should be treated on a seperate level to the lexical words in the sentence (Jones, 1994).
---------------------------------------------------
C96-2102:5	27:147	The major problem of the ewduatory studies, (Dale (199l), Jones (1994), and to a far lesser: extent Briscoe & Carroll (1995)), was that their coverage and use of pun<:tuation was rather poor, being necessarily based on human intuitions and possible idiosyncrasies.
---------------------------------------------------
C96-2102:6	16:147	In the field of syntax Jones (1994) has shown, through a comparison of the performance of a grammar that uses punctuation and one which does not, that for the more complex sentences of real language, parsing with a punctuated grammar yields around two orders of magnitude fewer parses than parsing with an nnpunctuated grammar, and that additionally the punctuated parses better reflect the linguistic structure of the sentences.
---------------------------------------------------
P96-1052:7	16:68	shown the benefits of using punctuation in the fields of discourse structure and semantics, and Jones (1994) has shown in the field of syntax that using a grammar that includes punctuation yields around two orders of magnitude fewer parses than one which does not.
---------------------------------------------------
P96-1052:8	65:68	To avoid dealing with idiosyncratic tagging of words, and over-complicated sentences, we shall follow Briscoe and Carroll (1995) rather than Jones (1994) and use 35,000 prepared sentences from the Susanne corpus rather than using the Spoken English Corpus.
---------------------------------------------------
