(1992) and Kurohashi and Nagao (1994). 
4 Anaphora Resolution System 4.1 Procedure Before referents are determined, sentences are transformed into a case structure by the c~e structure analyzer (Kurohashi and Nagao 1994). 
In the past researches (Kurohashi and Nagao, 1994; Cohen, 1987), the weights for each cue tend to be determined by intuition or trial and error. 
Kurohashi and Nagao (1994) describe a discourse structure generator that builds discourse trees in an incremental fashion. 
5 Experiment and Discussion 5.1 ExI)eriment Before det, ermining the referents of noun phrases, sentences were at first transformed into a case structure by the case structure analyzer (Kurohashi and Nagao 1994). 
