This approach took inspiration from the pioneering work by (Dolan 1994), but it is also fundamentally different, because instead of grouping similar senses together, the CoreLex approach groups together words according to all of their senses. 
Furthermore, as pointed out in Dolan (1994), the sense division in an MRD is frequently too fine-grained for the purpose of WSD. 
Dolan (1994) described a heuristic approach to forming unlabeled clusters of closely related senses in a MRD. 
Much work has gone into methods for measuring synset similarity; early work in this direction includes (Dolan, 1994), which attempted to discover sense similarities between dictionary senses. 
Dolan (1994) observed that sense division in MRD is frequently too free for the purpose of WSD. 
