The present paper offers a similarity1With the exception of dependency-grammar-based parsers (Tapanainen and Jarvinen, 1997; Broker et al. , 1994; Lesmo and Lombardo, 2000), where functional labels are treated as first-class citizens as relations between words, and recent work on a semi-automatic method for treebank construction (Brants et al. , 1997), little has been reported on based algorithm for assigning functional labels such as subject, object, head, complement, etc. to complete syntactic structures on the basis of pre-chunked input.


