This decision tree was called the case frame tree (Tanaka, 1994) and we follow that convention in this paper, too. 
Some of these methods make use of prior knowledge in the form of an existing thesaurus (Resnik 1993a, 1993b; Framis 1994; Almuallim et al. 1994; Tanaka 1996; Utsuro and Matsumoto 1997), while others do not rely on any prior knowledge (Pereira, Tishby, and Lee 1993; Grishman and Sterling 1994; Tanaka 1994). 
The most popular touchstone in this field is the verbal case fl'ame or the translation rules (Tanaka, 1994). 
Several methods have been proposed with regard to acquiring various kinds of rules such as translation rules, grammar rules, dictionary entries and so on from bilingual corpora (Dagan et al. , 1991; Dagan and Church, 1994; Fung and Church, 1994; Tanaka, 1994; Yamada et al. , 1995). 
Although the tree has some attractive features mentioned in (Tanaka, 1994), it suffers from two problems. 
