Roche and Schabes (1994) have shown that in the unweighted case this allows to parse context-free grammars with finite-state transducers; in our case, a cost can be added to the parse.


(Roche, 1994) uses the fix point of a finite-state transducer.


FSTs may also be used to parse restricted classes of context-free grammars (Pereira 1991; Roche 1994; Laporte 1996).


Roche built an English syntactic mmlyzer by finding a fixed point in a non-deterministic FST (Roche, 1994).


