Sentence alignment (Chen & Chen, 1994) is important in 228 setup of a bilingual corpus.


Such a rigid treatment will be helpful for further applications such as anaphora resolution (Chen, 1992), sentence alignment (Chert & Chert, 1994; Chen& Wu, 1995), etc. Section 2 describes the training corpora and the testing corpus we used.


Introduction A Chinese sentence is composed of a string of characters without any word boundaries, so that to segment Chinese sentences is indispensable in Chinese language processing (Chen, 1990; Chen, 1994).


