More information can be found in (Guthrie and Walker, 1994).


1 Introduction There has been quite a lot of research concerned with automatic clustering of articles or autonmtic identification of selnantically similar articles(Walker, 1986), (Guthrie, 1994), (Yuasa, 1995).


Method based on hard clustering In order to address the above difficulty, Guthrie et.al, have proposed a method based on hard clustering of words (Guthrie, Walker, and Guthrie, 1994) (hereafter we will refer to this method as HCM).


In order to address this difficulty, (Guthrie, Walker, and Guthrie, 1994) have proposed using distributions based on what we refer to as hard 1A related issue is the retrieval, from a data base, of documents which are relevant to a given query (pseudodocument) (e.g. ,(Deerwester et al. , 1990; Fuhr, 1989; Robertson and Jones, 1976; Salton and McGill, 1983; Wong and Yao, 1989)).


