3 Benefits of this approach include the ability to exploit the maturity and efficiency of database technology, easy modelling of blackboard-type distributed control regimes (of the type proposed by: (Boitet and Seligman, 1994) and in the section on control in (Black ed.


An impressive core of linguistic knowledge is available but has not yet been experimented on in building language learning software, though work is underway for integration of heterogeneous NLP components, Boitet & Seligman (1994).


In order to maintain the cooperative benefits of a blackboard system while enhancing modularity and facilitating central coordination or control of components, (Seligman and Boitet 1994 and Boitet and Seligman 1994) proposed and demonstrated a "whiteboard" architecture for speech translation.


