3 The methodology of the Legal Taxonomy Syllabus A standard way to properly manage large multilingual lexical databases is to do a clear distinction among terms and their interlingual acceptions (or axies) (Serasset, 1994; Lyding et al. , 2006).


2 The Papillon Multilingual Dictionary 2.1 Macrostructure The architecture of the Papillon multilingual dictionary is based on Gilles Srasset (1994) and has been prototyped by Blanc (1999).


For this, we chose to use acceptions as they are defined in the Papillon dictionary (Serasset, 1994) to represent the equivalence links between concepts of the different legal systems (Arntz, 1993).


(Serasset1994)), ourmethodisautomatic.


