J98-4002:1	267:389	To avoid this problem, we could apply a method used in efficient database search techniques, by which the system can search for neighbor examples of x with optimal time complexity (Utsuro et al. 1994).
---------------------------------------------------
J98-4002:2	282:389	This can be a critical problem for statistics-based approaches, as the reconstruction 12 Utsuro's method requires the constiuction of large-scale similarity templates prior to similarity computation (Utsuro et al. 1994), and this is what we would like to avoid.
---------------------------------------------------
