Some research in genre classification has included the recognition of subjective genres such as editorials (e.g. , (Karlgren and Cutting, 1994; Kessler et al. , 1997; Wiebe et al. , 2001)). 
Exceptions focusing on genre include Kessler, Nunberg, and Sch utze (1997) and Karlgren and Cutting (1994). 
3.2.1 Structural Cues In order to see whether our easily-computable surface cues are comparable in power to the structural cues used in Karlgren and Cutting (1994), we also ran LR with the cues used in their experiment. 
Another, more related area of research is that of determining the genre of texts; subjective genres, such as \editorial", are often one of the possible categories (Karlgren and Cutting, 1994; Kessler et al. , 1997; Finn et al. , 2002). 
Karlgren and Cutting (1994) take a comtmtationally tractable set of these properties and use them to compute a score to recognize text genre using discriminant analysis. 
