The labels attached to senses in the MRD, coupled with these inter-sense relations, can then support and realize automatic sense shifts advocated in Putstejovsky and Bouillon (1994).


The topical clusters of MRD senses, coupled with the topical description of sense-shift knowledge, can support and realize automatic sense extension, as advocated in Putstejovsky and Bouillon (1994), and prevent a proliferation of senses in the semantic lexicon.


