5 Related Work The idea of example based machine translation systems was first proposed by (Nagao, 1984), and preliminary systems that appeared about ten years (Sato and Nagao, 1990; Sadler and Vendelmans, 1990; Maruyama and Watanabe, 1992; Furuse and Iida, 1994) showed the basic feasibility of the idea.


Ambiguities, which occur during parsing or mapping, are resolved by selecting the rules that minimize the semantic distance between the input words and source examples (real examples in the training corpus) of the transfer rules (Furuse and Iida, 1994).


In this case, we introduce the notion of a constituent boundary proposed by Furuse and Iida 1 http://www-nagao.kuee.kyoto-u.ac.jp /nl-resource/juman-e.html 2 http://www-nagao.kuee.kyoto-u.ac.jp /nl-resource/knp-e.html (1994), which is a virtual functional marker inserted between two consecutive content words, in order to more easily analyze a sentence.


