The encoding of lexical rules used in the covariation approach is related to the work of van Noord and Bouma (1994), who describe the hand-encoding of a single lexical rule as definite relations and show how these relations can be used to constrain a lexical entry. 
 Constraint-based Categorial Grammar, with delayed evaluation of constraints (Bouma and van Noord, 1994). 
van Noord/Bouma (1994) who show some other cases where recursive lexical rules are useful and deal with processing issues as well. 
 HPSG with lexical rules as delayed constraints (van Noord and Bouma, 1994). 
One possibility is to annotate the lexical rule encoding with such criteria by means of delay statements, as, for example, suggested by van Noord and Bouma (1994). 
