 The grammar database contains the actual implementation of the grammar, written as typed feature structures using TDL (Krieger and Schafer, 1994).


1 Specifying tree-based grammars Whilst the development of standard unificationbased grammars is well supported by the design of formalisms such as PATR-II, Ale or TDL (Krieger and Schafer, 1994), the situation is less well established for Tree-Based Grammars such as Tree Adjoining Grammars (Joshi and Schabes, 1997), Tree Description Grammars (Kallmeyer, 1996) or Interaction Grammars (Perrier, 2003).


