(Utsuro et al. , 1994) introduced a statistical postprocessing step to tackle the problem.


Sentential alignment (Brown et al. , 1991; Gale and Church, 1993; Kay and Roscheisen, 1993; Utsuro et al. , 1994; Haruno and Yamazaki, 1996) is commonly used as a starting point for finding the translations of words or expressions from bilingual corpora.


First, we use a method based on CLIR to align Japanese and English articles (Collier et al. , 1998; Matsumoto and Tanaka, 2002) and then a method based on DP matching to align Japanese and English sentences (Gale and Church, 1993; Utsuro et al. , 1994) in these articles.


We first aligned the articles using a method based on CLIR (Collier et al. , 1998; Matsumoto and Tanaka, 2002) and then aligned the sentences in these articles by using a method based on dynamic programming (DP) matching (Gale and Church, 1993; Utsuro et al. , 1994).


3.2 Sentence alignment The sentences5 in the aligned Japanese and English articles are aligned by a method based on DP matching (Gale and Church, 1993; Utsuro et al. , 1994).


