We parsed a 125-million word newspaper corpus with Minipar, 1 a descendent of Principar (Lin, 1993; Lin, 1994), and extracted dependency relationships from the parsed corpus. 
For the co-occurrence model, we used Minipar (Lin 1994), a broad coverage parser, to parse each data set. 
English dependency trees are supplied by Minipar (Lin, 1994). 
We use a broad-coverage parser (Lin, 1993; Lin, 1994) to extract dependency triples from the text corpus. 
5.1 Experimental Setup We used Minipar (Lin 1994), a broad coverage parser, to parse two 3GB corpora (TREC-9 and TREC-2002). 
