It incorporates 168 SCF distinctions, a superset of those found in the COMLEX Syntax (Grishman et al. , 1994) and ANLT (Boguraev et al. , 1987) dictionaries. 
as it is processed by AUTOSEM using the CARMEL grammar and lexicon, which is built on top of the COMLEX lexicon (Grishman et al. , 1994). 
We also experimented with other features such as augmenting the model with verb-preposition preferences derived from Comlex (Grishman et al., 1994), and querying the Google Terabyte N-gram corpuswiththesamepatternsusedinthecombination features. 
Lapata determined thresholds for each SCF using the frequency of the SCF in COMLEX Syntax dictionary (Grishman et al. , 1994). 
The lexicon is based on COMLEX (Grishman et al. , 1994). 
