The range of reports for any given patient at any given point in their illness thus present a special class of paraphrase, with a looser adherance to semantic equivalence between versions than is typically found in other paraphrase generators, for example Kozlowski et al (2003), McKeown et al (1994), Power, Scott and Bouyaad-Agha (2003), Rosner and Stede (1994),(1996), and Scott and Souza (1990).


 Lexical and syntactic realization resources (e.g. , English PENMAN/German NIGEL in [Rosner and Stede, 1994]) As an MLG system, our system also includes similar modules.


MLG systems share a common architecture consisting of the following modules:  A language-independent underlying knowledge representation: knowledge represented as AI plans [Rosner and Stede, 1994] [Delin et al. , 1994], [Paris and Vander Linden, 1996], knowledge bases (or ontologies) such as LOOM, the Penman Upper-model and other (domain-specific) concepts and instances [Rosner and Stede, 1994].


 Sentence planning different languages can express the same content in various rhetorical structures, and planning must take it into consideration: either by avoiding the tailoring of structure to a specific language [Rosner and Stede, 1994] or by taking advantage of knowledge on different realizations of rhetorical structures in different languages at the underlying representation [Delin et al. , 1994].


