To the best of our knowledge, there are two preceding research papers on word sense acquisition (Fukumoto and Tsujii, 1994; Pantel and Lin, 2002).


The approach proposed in this paper explicitly introduces new entities, i.e. hypothetical verbs when an entity is judged polysemous and associates them with contexts which are sub-contexts of the context of the original entity Our algorithm has two basic operations, splitting and lumping Splitting means to divide a polysemous verb into two hypothetical verbs and lumping means to combine two hypothetical verbs to make one verb out of them (Fukumoto and Tsujii, 1994).


This CCD factor is taken into account 2 Note that unlike the automatic acquisition of word sense definitions (Fukumoto and Tsujii 1994; Pustejovsky and Boguraev 1993; Utsuro 1996; Zernik 1989), the task of the system is to identify the best matched category with a given input, from predefined candidates.


