For example, Sanfilippo (1994) argues against this instrument on the grounds that there is no general control regime on lexical rules that would deterministically restrict any polysemic expansion.


The use of lexical rules to generate different uses of a word fl'om a kernel entry (Copestake gg Briscoe, 199l; Sanfilippo, 1994) provides a 1)rincipled alternative to word sense enumeration and can be made to eater for uovel uses of words.


Similarly, the option of either a noun or verb phrase complement for enjoy can be extended to many other psychological verbs with experiencer subjects (e.g. hale, like, lnvfeO, and verbs of undirected motion in English (e.g. carry, drive, float, push, run, swim, walk) can subcategorize for an expression of completed path so as to yield a telic/directed interpretation (Tahny, 1985; Sanfilippo el al. , 1992; Sanfilippo, 11994).


