These methods use categorized semantic and pragmatic constraints such as verbal semantic attributes (Nakaiwa et al. , 1994) and types of modal expressions and conjunctions as a condition for anaphora resolution of zero pronouns and determine antecedents of zero pronouns depending on the typical category of three types of semantic and pragmatic constraints.


In the implementation in ALT-J/E, the rules are extracted using the case type of the zero pronoun, the verbal semantic attributes (VSA; 107 categories) of the verb which governs the zero pronoun (Nakaiwa et al. , 1994) and categorized types of modal expression (134 categories) in the unit sentence which contains the zero pronoun (Kawai, 1987) and categorized types of conjunction (56 categories) which are directly connected to the unit sentence.


These methods use categorized semantic and pragznatic constraints such as verbal semantic attributes (Nakaiwa et al. , 1994) and types of modal expressions and conjunctions as a condition for anaphora resolution of zero pronouns.


