1 Introduction In Japanese, around 95% word segmentation accuracy is reported by using a word-based language model and the Viterbi-like dynamic programming procedures (Nagata, 1994; Yamamoto, 1996; Takeuchi and Matsumoto, 1997; Haruno and Matsumoto, 1997). 
This is achieved by introducing an explicit statistical model of unknown words, and by using an Nbest word segmentation algorithm (Nagata, 1994) as an approximation of the generalized ForwardBackward algorithm. 
52 0.2 \[~i -~ 0.1 ~ ~ Figure 5: An example of computing the expected word frequencies N-best word segmentation hypotheses can be obtained by using the Forward-DP Backward-A* algorithm (Nagata, 1994). 
It is used,as tagging mode\[ in English (Church, 1988; Cutting et al. , 1992) and morphological analysis nlodel (word segmentation and tagging) in Japanese (Nagata, 1994). 
(1994) and Nagata (1994), among others, for details of automatic segmentation methods). 
