Further examples include systems that combine associative Lambek calculus with special connectives for discontinuity (e.g. Morrill & Solias 1993; Hepple 1994).


2 Moortgat & Oehrle (1993;1994) and Hepple (1993) propose general approaches for combining substructural logics into multimodal systems, where 'movement between levels' (enabled by structural modalities in the earlier work) is freely allowed, provided it accords with what are seen to be 'natural relations' between the levels in terms of the relative informativeness of their descriptions.


Other lexicalized grammars collapse syntactic and ordering information an(t are fbI'ced to represent ordering alternatives by lexical ambiguity, most notable L-TAG (Schabes et al., 1988) and some versions of CG (Hepple, 1994).


