5 Processing Model Our attachment system is all extension of the rule-based system for VNPN binary prepositional phrase attachment described in (Brill and Resnik, 1994). 
The overall disambiguation accuracy achieved by our method is 85.2%, which compares favorably against the accuracy (82.4%) obtained by the state-of-the-art disambiguation method of (Brill and Resnik, 1994). 
The other methods for which results have been reported on this dataset include decision trees, Maximum Entropy (Ratnaparkhi, Reynar, and Roukos, 1994), and Error-Driven TransformationBased Learning (Brill and Resnik, 1994), 3 which were clearly outperformed by both IB1 and IBI-IG, even though e.g. Brill ~ Resnik used more elaborate feature sets (words and WordNet classes). 
Rule based systems (Boggess et al. , 1991), (Brill and Resnik, 1994) 2. 
et al., 1994; Brill and Resnik, 1994; Collins and Brooks, 1995; Merlo et al., 1997). 
