Similar strategies have been adopted in several recent works in anaphor resolution, such as T. Nasukawa (1994), R. Mitkov (1996), R. Vieira & M. Poesio (1997) and others.


A number of proposals in the 1990s deliberately limited the extent to which they relied on domain and/or linguistic knowledge and reported promising results in knowledge-poor operational environments (Dagan and Itai 1990, 1991; Lappin and Leass 1994; Nasukawa 1994; Kennedy and Boguraev 1996; Williams, Harvey, and Preston 1996; Baldwin 1997; Mitkov 1996, 1998b).


