For example, (Briscoe and Carroll, 1993) train an LR parser based on a general grammar to be able to distinguish between likely and unlikely sequences of parsing actions; (Andry et al. , 1994) automatically infer sortal constraints, that can be used to rule out otherwise grammatical constituents; and (Grishman et al. , 1984) describes methods that reduce the size of a general grammar to include only rules actually useful for parsing the training corpus.


