C96-2138:1	23:166	Also, its feasibility for content characterization has been discussed with the use of controlled (noise-free) on-line data set (Nakayama, 1994; Nakayama 1995; Sibun and Farrar, 1994).
---------------------------------------------------
A94-1003:2	34:197	While our initial goal has been to use it for language identification, in support of downstream OCR pro15 cesses, we are finding that this representation may itself be sufficient for natural language applications such as document indexing and content characterization (see Nakayama (this volume), Sibun & Farrar 1994).
---------------------------------------------------
A94-1004:3	18:135	Word shape tokens are a potential alternative to character coded words when they are used for language determination and part-of-speech tagging (Nakayama and Spitz, 1993; Sibun and Spitz, this volume; Sibun and Farrar, 1994).
---------------------------------------------------
