For example, speech repairs, particle omission, and fillers can be dealt with in the framework of unification grammar (Nakano et al. , 1994; Nakano and Shimazu, 1999).


Such a 'syntax' of discourse markers naturally has an important bearing on constructing a grammar of natural, spoken discourse \[Nakano et al. , 1994\].


But such a rule will be useful in devising a 'grammar' of the spontaneously spoken language taken in its totality, an attempt made by, for example, \[Nakano et al. , 1994\].


