This requires a procedure for determining the best "cover" of an input text by segments of sentences contained in the database (Nirenburg, S. Domashnev, C. , Grannes, D. 1993), (Cranias, L. et al 1994), (Frederking, R. , Nirenburg, S. , 1994), (Sato, S. 1995).


In EBMT (example-based machine translation), the longer a sentence is, the less possible it is that the sentence has an exact match in the translation archive, and the less flexible an EBMT system will be (Cranias et al. , 1994).


It is interesting to constrast this method with the "parse-parse-match" approaches that have been reported recently for producing parallel bracketed corpora (Sadler & Vendelmans 1990; Kaji et al. 1992; Matsumoto et al. 1993; Cranias et al. 1994; Gfishman 1994).


