While many NLG researchers have attempted to transfer the ideas of Centering Theory to generation (Not, 1996; Yeh and Mellish, 1997; McCoy and Strube, 1999; Henschel et al. , 2000; Kibble and Power, 2000), there has yet been no substantial return contribution to the field of anaphora resolution.


Finally, there are significant obstacles to verifying the correctness of existing pronominalization algorithms for any pronominalization theory (Not, 1996; Yeh and Mellish, 1997; McCoy and Strube, 1999; Henschel et al. , 2000; Kibble and Power, 2000): the lack of natural language generation systems that can produce large enough texts to bring discourse-level processes into play.


