Currently, the adaptation process includes manual tuning followed by corpus bootstrapping using an unsupervised learning method (Strzalkowski & Wang, 1996). 
(Strzalkowski and Wang, 1996) and (Collins and Singer, 1999) tried to obtain either lexical or contextual knowledge from a seed given by hand. 
Currently, the adaptation process includes manual tuning followed by corpus bootstrapping using an unsupervised learning method (Strzalkowski & Wang, 1996). 
For the specific task of named entity annotation, some researchers have emphasized the creation of taggers from minimal seed sets (Strzalkowski and Wang, 1996; Collins and Singer, 1999; Lin et al. , 2003) while another line of inquiry (which we are pursuing) has sought to improve on high-performance baseline taggers (Miller et al. , 2004). 
(Strzalkowski and Wang, 1996) proposed a method for learning concepts belonging to a given semantic class. 
