The General Architecture for Text Engineering (GATE)3 is a theory-neutral framework for the management and integration of NLP components and documents on which they operate (Cunningham et al. , 1996; Cunningham, 2000; Bontcheva et al. , 2002; Cunningham et al. , 2002; Maynard et al. , forthcoming).


Even more recent is the work on GATE (Cunningham et al. , 1996) which allows the user to combine different modules in a simple way.


This is a much enhanced version of the analyser originally developed for tile GATE system (Cunningham et al. , 1996).


For more details of this process see (Cunningham et al. , 1996).


