Hiromi Nakaiwa and Satoshi Shirai (1996) Anaphora Resolution of Japanese Zero Pronouns with Deictic Reference. 
Nakaiwa and Shirai (1996) use this sort of resolution model, which involves the use of semantic and pragmatic constraints, such as constraints based on modal expressions, or constraints based on verbal semantic attributes or conjunctions. 
Moreover, clues are used about the grammatical and pragmatic functions of expressions as in (Grosz et al. , 1995), (Strube, 1998), "or (Azzam et al. , 1998) as well as rule-based empirical approaches like (Nakaiwa and Shirai, 1996) or (Murata and Nagao, 1997), to determine the most salient referent. 
For instance, Nakaiwa and Shirai (1996) attempted to resolve Japanese ellipsis in the source language analysis of J-to-E MT, despite utilizing targetdependent resolution candidates. 
Nakaiwa et.al.(Nakaiwa and Shirai, 1996) also propose the method which is based on semantic and pragmatic constraints. 
