One candidate is Strube and Hahn's (1996) reformulation of the notions of 76 0 0 0 0 @ 0 @ 0 @ 0 @ 0 @ 0 0 0 0 0 @ @ 0 @ 0 @ 0 0 0 0 @ 0 @ 0 O @ O O O e O @ O O O O O O @ O O O O e O @ O O O O O O O O O O O O O O O O O Text Planning 1.


The result is as follows: UI : Cb f a, Cp = a U2:Cb=a, Cp=b U3 : Cb f b, Cp = b U4 : Cb = b, Cp = b In terms of the conventional transitions this works out as U~/U2: RET^IN U2/U3: SMOOTH SHIFT us/u~: COnTINUa This is consistent with Strube and Hahn's (1996) observation that "a II~rAIN transition ideally predicts a SMOOTH ssw'r in the following utterance".


So the next stage in this research will Concentrate on developing a characterisation of Cb based on semantic content and information structure, taking account of e.g. the proposals of Strube and Hahn (1996) and experimenting with optlmisation algorithms as discussed in section 3.1.2 above.


2.2 Deconstructing the transitions Strube and Hahn (1996) question the canonical ordering of transitions, partly on the grounds that this ordering fails to predict the P~TAIN SHIFT pattern which has been claimed by many researchers to signal a segment boundary or the introduction of a new =discourse topic".


This work has led to several analyses employing centering theory and extensions of it, particularly in the area of pronoun interpretation (Kameyama 1986; Brennan, Friedman, and Pollard 1987; Di Eugenio 1990, 1996; Walker, Iida, and Cote 1994; Strube and Hahn 1996, inter alia; see also citations within GJW, forthcoming papers in Walker, Joshi, and Prince in press, and psycholinguistic studies described in Hudson-D'Zmura 1989, Gordon, Grosz, and Gilliom 1993, and Brennan 1995).


