We have also employed a scheme for ranking dependency parses using the total link length of the dependency trees, as originally suggested by Lin (1996), with quite promising results. 
Dependency-based statistical language modeling and parsing have also become quite popular in statistical natural language processing (Lafferty, Sleator, and Temperley 1992; Eisner 1996; Chelba et al. 1997; Collins 1996; Collins et al. 1999). 
To impose a ranking on the parses generated based on just structural properties of the dependency tree, we employed Lins (1996) notion of structural complexity. 
Dependency-based statistical language modeling and analysis have also become quite popular in statistical natural language processing (Lafferty et al. , 1992; Eisner, 1996; Chelba and et al. , 1997). 
Inspired by Lin's notion of structural complexity (Lin, 1996), measured by the total length of the links in a dependency parse, we ordered the parses of a sentence using this measure. 
