This technique has been partially outlined in (Mikheev 1996a, 1996b) and, along with a level of accuracy for the induced rules that is higher than any previously quoted, it has an advantage in terms of quantity and simplicity of annotation of data for training.


More sophisticated guessers further examine the prefixes of unknown words (Mikheev, 1996) and the categories of contextual tokens (Brill, 1995; Daelemans et aL, 1996).


Currently, JUMAN3.5 (Kurohashi ~z Nagao 1998) is used for Japanese and LT_POS/LT_CHUNK (Mikheev 1996) is used for English.


