For the three areas Fish, Mushrooms, and Neurology, the secondary corpora were retrieved using the following refined procedure: Starting from a small tagged seed corpus for the given domain, we mechanically extracted terminological open compounds for English (Sornlertlamvanich and Tanaka 1996; Smadja and McKeown 1990) and compound nouns for German.


2 Previous Works Reviewing the previous works on Thai word extraction, we found only the work of Sornlertlamvanich and Tanaka (1996).


