, 1993), QJP (Kameda, 1996)) -advantages: long enough for accurate recognition, captures common patterns disadvantages: requires dictionary entry for each possible phrase; vocabulary explosion  "Word" level: (JANUS (Schultz and Koll, Mayfield Tomokiyo ~ Ries 60 Learning base units in Japanese Laura Mayfield Tomokiyo and Klaus Ries (1997) What makes a word: Learning base units in Japanese for speech recognition.


Third, a number of existing NLP tools such as JUMAN (a morphological analyzer) (Matsumoto et al. 1993) and QJP (a morphological and syntactic analyzer) (Kameda 1996) could broaden the coverage of our system, as inputs are currently limited to simple, morphologically analyzed sentences.


