P06-1119:1	196:233	Others have made similar mutual-translation assumptions for lexical acquisition (Echizen-ya, et al. , 2005; Kaji & Aizono, 1996; Rapp, 1999; Tanaka & Iwasaki, 1996).
---------------------------------------------------
C04-1105:2	16:171	Several researchers have developed a contextual-similarity-based method for extracting pairs of translation equivalents (Kaji and Aizono 1996; Fung and McKeown 1997; Fung and Yee 1998; Rapp 1999).
---------------------------------------------------
C02-1020:3	68:141	They are based on the idea that the context of the words which appear in neighborhood looks like each other for the translation pairs although expressed in the two di erent languages (Kaji and Aizono, 1996).
---------------------------------------------------
C02-1020:4	124:141	Like our method, researches which are not based on the assumption of the sentence alignments for parallel corpora have been done (Kaji and Aizono, 1996; Tanaka and Iwasaki, 1996; Fung, 1997).
---------------------------------------------------
C02-1020:5	6:141	Therefore, researches of extracting translation pairs from parallel corpora automatically become active recently (Gale and Church, 1991; Kaji and Aizono, 1996; Tanaka and Iwasaki, 1996; Kitamura and Matsumoto, 1996; Fung, 1997; Melamed, 1997; Sato and Nakanishi, 1998).
---------------------------------------------------
C02-1020:6	126:141	(Kaji and Aizono, 1996) has proposed the correspondence level calculated by the size of intersection between co-occurrence sets with the word included in an existing translation dictionary.
---------------------------------------------------
P98-2191:7	15:80	However, since this work requires a great deal of labor and it is difficult to keep description of dictionaries consistent, the researches of automatical dictionaries making for machine translation (translation rules) from corpora become active recently (Kay and RSschesen, 1993; Kaji and Aizono, 1996).
---------------------------------------------------
