In (Torisawa and Tsujii, 1996), an efficient HPSG parser is proposed, and our preliminary experiments show that the parsing time of the efficient parser is about three times shorter than that of the naive one.


 A parser based on the Torisawa's parsing algorithm (Torisawa and Tsujii, 1996).


The first approach to mention is the radical one of converting HPSG into something else before generation, such as Tree Adjoining Grammar (Kasper et al. , 1995)Though this seems to support the view that HPSG is unsuitable for generation, it is in fact a valuable contribution to work on compiling HPSG grammars for efficient processing, whether for parsing (Torisawa and Tsujii, 1996) or for generation.


Similar work on compiling HPSG for efficient parsing (Torisawa and Tsujii, 1996) should be equally applicable to generation.


For realizing efficient NLP systems, I am currently building an efficient parser by integrating the packing method with the compilation method for HPSG (Torisawa and Tsujii, 1996).


