W06-1522:1	49:126	This is where our approach differs strongly from (Sarkar and Joshi, 1996).
---------------------------------------------------
W06-1522:2	51:126	148 the conjoin operation defined in (Sarkar and Joshi, 1996) involves merging nodes from different trees while the tree anchored by a coordinator acts similarly to an auxiliary tree with two foot nodes.
---------------------------------------------------
W06-1522:3	8:126	We first briefly discuss the linguistic motivations behind the resolution mechanism we propose, then introduce the fusion operation and show how it can be compared to the analysis of (Dalrymple et al. , 1991) and (Steedman, 1990) and we show how it differs from (Sarkar and Joshi, 1996).
---------------------------------------------------
W06-1505:4	94:109	To handle the coordination of the constituent containing the clefted constituent and the cleft clause, as illustrated in (15), we propose to use Node Contraction and Conjoin proposed in Sarkar and Joshi (1996).
---------------------------------------------------
H05-1102:5	35:366	Conjunction is similar to what was originally proposed in (Sarkar and Joshi, 1996).
---------------------------------------------------
E06-2008:6	17:86	In current sentence generators, the coordinative ellipsis rules are often inextricably intertwined with the rules for generating nonelliptical coordinate structures, so that they cannot easily be ported to other grammar formalisms  e.g., Sarkar & Joshi (1996) for Tree Adjoining Grammar; Steedman (2000) for Combinatory Categorial Grammar; Bateman, Matthiessen & Zeng (1999) for Functional Grammar.
---------------------------------------------------
W00-1307:7	168:249	(T2) Coordination in XTAG: the templates for coordinations in XTAG are generated on the fly while parsing (Sarkar and Joshi, 1996), and are not part of the 1004 templates.
---------------------------------------------------
