There has been a growing interest in corpus-based approaches which retrieve collocations from large corpora (Nagao and Mori, 1994), (Ikehara et al. , 1996) (Kupiec, 1993), (Fung, 1995), (Kitamura and Matsumoto, 1996), (Smadja, 1993), (Smadja et al. , 1996), (Haruno et al. , 1996). 
(Haruno et al. , 1996) constructed collocations by combining a couple of strings 4 of high mutual information iteratively. 
(Haruno et al. , 1996) proposes an efficient n-gram based method to extract bilingual collocations from sentence aligned bilingual corpora. 
4 Related work Algorithms for retrieving collocations has been described (Smadja, 1993) (Haruno et al. , 1996). 
(Haruno et al. , 1996),:onstructed collocations by combining adjacent n-grams with high value of mutual information. 
