There has been a growing interest in corpus-based approaches which retrieve collocations from large corpora (Nagao and Mori, 1994), (Ikehara et al. , 1996) (Kupiec, 1993), (Fung, 1995), (Kitamura and Matsumoto, 1996), (Smadja, 1993), (Smadja et al. , 1996), (Haruno et al. , 1996).


Collocation Data Unlike the recent works on the automatic extraction of collocations from corpus \[Church, K. W, et al, 1990, Ikehara, S. et al, 1996, etc.\], our data have been collected manually through the intensive investigation of various texts, spending years on it.


text ntr|hg (I oharaoter~: I bytes) la, ol.ter table Figure 1: Nagao's Approach To settle this problem, (Ikehara et al. , 1996) proposed a method to extract only useful strings.


5 Related Work Although there have been many studies on collocation extraction and mining using only statistical approaches (Church and Hanks, 1990; Ikehara et al. , 1996), there has been much less work on collocation acquisition which takes into account the linguistic properties typically associated with collocations.


