5 Related Work Vilain and Day (Vilain and Day, 1996) report on an approach which learns and applies rule sequences for the name tagging task (based on Eric Brill's rule sequence work (Brill, 1993)). 
Vilain and Day (1996) identify (and classify) name phrases such as company names, locations, etc. Ramshaw and Marcus (1995) detect noun phrases, by classifying each word as being inside a phrase, outside or on the boundary between phrases. 
Named-entity recognition in Alembic (Vilain and Day, 1996) uses the transformation-based rule learning approach introduced in Brills work on part-of-speech tagging (Brill, 1993). 
Surprisingly, though, rather little work has been devoted to learning local syntactic patterns, mostly noun phrases (Ramshaw and Marcus, 1995; Vilain and Day, 1996). 
The Alembic natural language analyzer (Aberdeen et al. 1995; Vilain and Day 1996) processes the zoned messages to identify paragraph, sentence, and word boundaries as well as part-of-speech tags. 
