A detailed account of the removal of idiosyncratic, incorrect and exceptional rulepatterns, with justifications, is reported in (Jones, 1996).


These generalised punctuation rules, described in more detail in (Jones, 1996), are given below for colons (6), semicolons (7), full-stops (8), dashes (9,10), commas (11), basic quotation(12) and stressmarkers (13-15).


Nevertheless, since Nunbergs monograph (Nunberg, 1990), the importance of the comma has been undeniable, mainly in these two as pects: i) as a due to the syntax of the sentence (Nunberg, 1990; Bayraktar et al. , 1998; Garzia, 1997), and ii) as a basis to improve some natural language processing tools (syntactic analysers, error detection tools), as well as to develop some new ones (Briscoe and Carroll, 1995; Jones, 1996).


