Finally, the closest coupling takes place in architectures where most or all components are allowed to talk to each other, such as the German Verbmobil speech translation system (Gorz et al. , 1996).


distributed processing and incremental interpretation (Gorz et al. , 1996): distribution to contribute to processing speed in what is a very compute-intensive application area; incremental interpretation both for speed reasons and to facilitate feedback of results from downstream modules to upstream ones (e.g. to inform the selection of word interpretations from phone lattices using partof-speech information).


