Other work has focused on the cross-linguistic realisations of two specific semantic relations (generation and enablement) (Delin et al. , 1994; Delia et al. , 1996), in a more general corpus of instructions for household appliances.


Accordingly, we advocate a flexible order of decisiommaking, as it can be realized in a blackboard-based architecture such as proposed by DIOGENES \[Nirenburg et al. 1989\] and HealthDoc \[Wanner and Hovy 1996\].


Second, a number of studies take particular (RST-)relati0ns as a starting-point, and examine how these relations are signalled on the linguistic surface; examples are the PURPOSE, RESULT and PRECONDITION relations \[Vander Linden 1994\], the CONCESSION relation \[Grote et al. 1997\], and the subject-matter relations occurring in a technical domain \[RSsner and Stede 1992, Delin et al. 1996\].


22 2 Related work Work on discourse marker generation in general has focussed on marker selection, mainly for causal relations (Elhadad and McKeown 1990; Vander Linden and Martin 1995), and on the realization of RST's subject-matter relations (Rhsner and Stede 1992; Delin et al. 1996).


(BNC) 1 Previous studies have accounted for a wide range of phenomena, from choosing between similar discourse markers (Fraser, 1998; Sanders et al. , 1992) to abstracting away from discourse markers and using syntax to signal underlying discourse relations (Delin et al. , 1996).


