Several approaches aim at proceeding a step further, by attempting to build a transfer-rule base in the form of abstract representations through different types of generalization processes applied on the available corpora relying on different levels of linguistic information and processing (Kaji et al. 92), (Juola, P. 1994), (Furuse, O. , Iida, H. 1996), (Veale, T. and Way, A. 1997), (McTait, K. , et al. 1999), thus providing more complete "context" information to the translation phase.


The source pattern consists of variables and constituent boundaries (Furuse and Iida, 1996).


