P08-1056:1	12:204	These belong to two main categories based on machine learning (Bikel et al., 1997; Borthwick, 1999; McCallum and Li, 2003) and language or domain specific rules (Grishman, 1995; Wakao et al., 1996).
---------------------------------------------------
I08-5004:2	42:240	There are several rulebased NER systems, containing mainly lexicalized grammar, gazetteer lists, and list of trigger words, which are capable of providing 88%-92% f-measure accuracy for English (Grishman, 1995; McDonald, 1996; Wakao et al., 1996).
---------------------------------------------------
I08-5004:3	50:240	Both the linguistic approach (Grishman, 1995; Wakao et al., 1996) and the ML based approach (Borthwick, 1999; Srihari et al., 2000) use gazetteer lists.
---------------------------------------------------
A00-1040:4	46:167	2.2 A Full NE system The NE system used in this paper is based on Sheffield's LaSIE system (Wakao et al. , 1996), versions of which have participated in MUC and HUB4 evaluation exercises (Renals et al. , 1999).
---------------------------------------------------
W98-1208:5	170:258	The text is first processed by a namedentity identifier, which we developed as part of Sheffield's entry for MUC-6 (Wakao, Gaizauskas, and Humphries, 1996; Gaizauskas et al. , 1996).
---------------------------------------------------
I08-5005:6	20:163	There are several rule based NER systems, containing mainly lexicalized grammar, gazetteer lists, and list of trigger words, which are capable of providing upto 92% fmeasure accuracy for English (McDonald, 1996; Wakao et al., 1996).
---------------------------------------------------
