2 Syntactic Transfer This section presents a simple bidirectional translation between LFG f-structures and term representations which serve as input to and output of a transfer component developed within the Verbmobil project (Dorna and Emele, 1996a). 
(1995) and Dorna and Emele (1996). 
The actual translation operation is performed in the transfer module as a mapping between semantic representations of the source and target languages, see (Dorna and Emele, 1996). 
(1995) and Dorna and Emele (1996). 
The rest of this paper is concerned with the extension of a Shake-andBake like transfer approach (Whitelock, 1992; Beaven, 1992) or the kind of semantic-based transfer approach as described for example in Dorna and Emele (1996) to cope with local ambiguities. 
