Vander Linden and Di Eugenio (Vander Linden and Di Eugenio, 1996) studied negative imperatives 3Absolute rejection may be expressed as doubt for the sake of politeness.


For example, researchers have devised algorithms for generating the surface form of explanations and instructions from underlying intention-based representations by tagging naturally occurring discourses for surface form features, informational relations, and intentional relations (Vander Linden and Di Eugenio 1996; Moser and Moore 1995; Moore and Pollack 1992; Paris and Scott 1994).


