2.2 Enhancing Named Entity Taggers There have been a very large number of NE tagger implementations since this task was introduced at MUC-6 (Grishman and Sundheim, 1996). 
The prototypical IE tasks are those specified in the Message Understanding Conference (MUC) evaluations (DARPA, 1995; Grishman and Sundheim, 1996). 
For illustration purposes, we extended it here by MUC (Grishman and Sundheim, 1996) entity types such as Person, Organization, etc. This scheme is still under construction and will soon also incorporate the representation of relationships between entities and domain-specific events. 
5.1 LaSIE LaSIE was designed as a research system for investigating approaches to information extraction and to be entered into the MUC-6 conference (Grishman and Sundheim, 1996). 
2 Event Scope and Representation The topic of the sixth MUC (MUC-6) was management succession events (Grishman and Sundheim, 1996). 
