There are already other grammar developing tools, such as a grammar writer of XTAG (Paroubek et al. , 1992), ALEP (Schmidt et al. , 1996), ConTroll (Gotz and Meurers, 1997), a tool by Nara Institute of Science and Technology (Miyata et al. , 1999), and [incr tsdb()] (Oepen et al. , 2002).


The LS-GRAM project (Schmidt et al. , 1996), funded by the EU-Commission under LRE (Linguistic Research and Engineering), was concerned with the development of grammatical resources for nine European languages: Danish, Dutch, English, French, German, Greek, Italian, Portuguese, and Spanish.


, for instance, (Schmidt et al. , 1996a) and (Schmidt et al. , 1996b)).


2 The Uni cationbased Grammar Thedevelopmentofthegrammarthatservedas thebasisofourresearchworkwasdonein the frameworkoftheAdvancedLanguageEngineering Platform (ALEP) (Simpkins et al. , 1993) during the project LSGRAM (LRE 61029) (Schmidt et al. , 1996) and it was used in the project MELISSA (ESPRIT 22252) (Bredenkamp et al. , 1998) for the rst time in an industrial context.


