9 10 Conclusion We have shown how the linear categorial deduction method of (Hepple, 1996) can be modified to allow incremental derivation, and specified an incremental normal form for proofs of the system. 
3 First-order Compilation for Implicational Linear Logic Hepple (1996) shows how deductions in implicational linear logic can be recast as deductions involving only first-order formulae, using only a single inference rule (a variant of o-E). 
See (Hepple, 1996) for more details, including a precise statement of the compilation procedure. 
Hepple (1996) introduces a linear deduction method, involving compilation to first order formulae, which can be combined with various labelling disciplines. 
Hepple (1996) shows how deductions in implicational linear logic can be recast as deductions involving only first-order formulae. 
