In some experiments of syntactic disambiguation (subject/object assignment in Italian, Montemagni 1995, Montemagni et al. 1996), we tried to combine both taxonomical and distributional measures in such a way that the system retied on taxonomical information first, to turn to distributional evidence only when the first step was not conclusive.


, 1996a\]; \[Montemagni et al. , 1996\]) for carrying out WSD on the basis of distributional evidence.


