A97-2006:1	12:50	Echizen-ya and others previously proposed a method of Machine Translation using Inductive Learning with Genetic Algorithms (GA-ILMT), and this method has been evaluated(Echizen-ya et al. , 1996).
---------------------------------------------------
C02-1158:2	70:146	First, the system evaluatesthetranslationruleswithoutvariables by using the results of combinations between the translation rules with variables and the translation rules without variables(Echizen-ya et al. , 1996).
---------------------------------------------------
