Also, a number of parsers have been developed for some dependency frameworks (Covington 1990) (Kwon, Yoon 1991) (Sleator, Temperley 1993) (Hahn et al. 1994) (Lombardo, Lesmo 1996), including a stochastic treatment (Eisner 1996) and an object-oriented parallel parsing method (Neuhaus, Hahn 1996).


This is the reason why the PARSETALK text understanding system (Neuhaus & Hahn, 1996) utilizes special heuristics in a heterogeneous chartand backtrackingbased parsing approach.


