A97-1020:1	30:109	(Nerbonne and Smit, 1996) provides more on the ICALL background against which GLOSSER was developed.
---------------------------------------------------
P98-2174:2	16:144	Such a glosser may be used as a tool for second-language improvement (Nerbonne and Smit, 1996), and thus provide an educational alternative to the passive consumption of a (usually low quality) translation.
---------------------------------------------------
