We exploit and extend the Generative Lexicon Theory (Pustejovsky, 1995; Bouillon, 1996) to develop a formal description of adnominal constituents in a lexicon which can offer a solution to these problems.


3 Classification of Problematic Behavior of Japanese Adnominal Constituents It is important for the analysis of adjectives to consider what its head noun denotes in the sentence (Bouillon, 1996).


Bouillon (Bouillon, 1996) applied this theory to the adnominal constituent of mental states.


