This type of pragmatic information has been noted to be very important for automatically synthesizing utterance with appropriate intonation (Prevost, 1996), and for generating sentences with appropriate word order in free word order languages such as Turkish (Hoffman, 1996).


In order to analyze Turkish texts, Hoffman (1996, 1998) distinguishes between the information structure of utterances and centering, since both constructs are assigned different functions for text understanding.


Both Rambow (1983) as well as Hoffman (1996, 1998) argue for a correlation between the information structure of utterances and centering.


In this section, we first discuss two studies in which the information structure of utterances is already integrated into the centering model (Rambow 1993; Hoffman 1996, 1998).


