C96-2133:1	11:173	The semantic construction is represented by LUD, Language for Underspecified Discourse Representation Structures (Bos et al. , 1996), which takes discourse representation This research was funded by the German Federal Ministry of Education, Science, Research, and Technology (BMBF) under grant number 01 IV 101 R. A big bunch of thanks goes to Johan Bos, Bj6rn Gambck, Claire Gardent, Christian Lieske, Manfred Pinkal and Karsten Worm for their valuable comments, and to Feiyu Xu and Julia Heine for a kind help editing the text.
---------------------------------------------------
C96-2133:2	76:173	As further described in (Bos et al. , 1996), LUD is a declarative description language for underspeeifled DRSs.
---------------------------------------------------
P98-1072:3	122:130	The resolution algorithm has been implemented in Verbmobil in both the German semantic processing (Bos et al. , 1996) and the (substantially smaller) Japanese one (Gamb~ick et al. , 1996).
---------------------------------------------------
P98-1060:4	23:158	Work in the literature include the QLF representations (Alshawi, 1992), the work on Underspecified Discourse Representation Structures (UDRS) (Reyle, 1993; Bos et al. , 1996), and the collection of papers in van Deemter and Peters (1996).
---------------------------------------------------
P98-1056:5	67:147	The representations (Bos et al. , 1996) are UDRS variants (Reyle, 1993).
---------------------------------------------------
W00-1409:6	62:142	It can easily be added to a RAGSlike system whose whiteboard is perfectly suited for lVerbmobil Interface Term, (Bos et al. , 1996; Dorna, 1996) the transformations that the robustness preprocessing module performs.
---------------------------------------------------
C96-1054:7	23:201	In order to allow for underspecification, variants of Underspecified Discourse Representation Structures (UDRS) (Reyle, 1993) are employed as semantic formalisms in the different analysis components (Bos et al. , 1996; Egg and Lebeth, 1995; Copestake et al. , 1995).
---------------------------------------------------
C96-1054:8	36:201	(Bos et al. , 1996; Egg and Lebeth, 1995; Copestake et al. , 1995).
---------------------------------------------------
W00-1420:9	36:201	The linguistic information within this track is encoded in a so-called VIT 2 (Bos et al. , 1996; Dorna, 1996) which is a formalism following DRT.
---------------------------------------------------
P98-2229:10	29:111	(1) vit(vitID(sid(l,a,ge,O,20,l,ge,y, semantics), \[word(montag, 13, \[II16\]), word(ist,14, \[ii17\]), word(gut,15, \[lllOl)l), index(lll3,1109,il04), \[decl(lll2,hl05), gut(lllO,il05), dofw(lll6,ilO5,mon), support(lll7,il04,1110), indef(llll,ilO5,1115,hl06)\], \[ccom_plug(hl05,1114), ccom_plug(h106,1109), in g(ii12,1113), in_g(lll7,1109), in_g(lll6,1115), in_g(llll,lll4), leq(lll4,hlO5),leq(llO9,hl06), leq(llOg,hl05)\], Is sort(ilO5,time)l, \[\], \[num(ilO5,sg),pers(il05,3)\], \[ta_mood(ilO4,ind), ta_tense(ilO4,pres), ta_perf(ilO4,nonperf)\], \[\] ) The VIT can be viewed as a theory-independent representation for underspecified semantic representations (Bos et al. , 1996).
---------------------------------------------------
P97-1053:11	12:175	of the grammar, time-constraints for parsing, and most importantly the kind of incompleteness, uncertainty, and inconsistency, coming with spoken input are coming more into the focus of semantic processing (Bos et al. , 1996; Pinkal, 1995).
---------------------------------------------------
