used for machine translation (Copestake et al. , 1996; Shemtov, 1996).


The core properties of this new method are:  prototypical occuring grammatical constructions can automatically be extracted;  generation of these constructions is vastly sped up using simple but efficient mechanisms; the new method supports partial matching, in the sense that new semantic input need not be completely covered by previously trained examples;  it can easily be integrated with recently developed chart-based generators as described in, 214 e.g., (Neumann, 1994b; Kay, 1996; Shemtov, 1996).


Kay (1996) and Shemtov (1996)).


The work in Kay (1996) and the extension to ambiguous input in Shemtov (1996) and Shemtov (1997) describes a chartbased generation process which takes packed representations as input and generates all paraphrases without expanding first into disjunctive normal form.


Shemtov (1996) describes extensions to a chart structure for generation originally presented in (Kay, 1996) that is used to generate multiple paraphrases from a semantic input.


