(Stuckardt, 1996a)) may get lost.


Among the most promising practical work are approaches relying on the availability of syntactic surface structure by employing coindexing restrictions, salience criteria, and parallelism heuristics (Lappin and Leass, 1994; Stuckardt, 1996b).


This architecture, however, tacitly ignores evidence for structural disambiguation that may be contributed by strong expectations at the referential layer (Stuckardt, 1996a).


4.4 An Implementation The above technique for achieving robustness according to the deficient description model has been integrated into an anaphor resolution system for German text (Stuckardt, 1996b).


Under this architecture, evidence for structural disambiguation that may be contributed by strong expectations at the referential layer is not taken into account (Stuckardt 1996).


