The algorithm has been applied to part-of-speech tagging (Padr6, 1996), and to shallow parsing (Voutilainen and Padro.


To improve the objectivity of the evaluation, the benchmark corpus (as well as parser outputs) have been made available from the following URLs: http://www.ling.helsinki.fi/-avoutila/anlp97.html http://www-lsi.upc.es/-lluisp/anlp97.html 7 Experiments and results We tested linguistic, statistical and hybrid language models, using the CG-2 parser (Tapanainen, 1996) and the relaxation labelling algorithm described in Section 2.


