For example, corpus-based methods are employed to extract Chinese personal names, and rule-based methods are used to extract Chinese date/time expressions and monetary and percentage expressions (Chen and Lee, 1996; Chen, Ding and Tsai, 1998). 
(4) Word boundary in queries of some languages (Chen and Lee, 1996) is not clear, thus segmentation is required. 
For example, corpus-based methods are employed to extract Chinese personal names, and rule-based methods are used to extract Chinese date/time expressions and monetary and percentage expressions (Chen and Lee, 1996; Chen, Ding and Tsai, 1998). 
In other words, it is necessary to segment Chinese sentence before tagging and parsing (Chen and Liu, 1992; Sproat, et al. , 1994; Chen and Lee, 1996). 
The statistical methods are commonly used for identifying proper names (Chen & Lee 1996, Chang ct al. 1994, Sun et al. 1994). 
