Furthermore, most implementations either contain no evaluation (Fass 1991; Inverson and Helmreich 1992; Hobbs et al. 1993) or report results on the development data (Bouaud, Bachimont, and Zweigenbaum 1996).


Previous approaches to processing metonymy typically rely heavily on the availability of manually constructed knowledge bases or semantic networks (Fass 1991; Inverson and Helmreich 1992; Bouaud, Bachimont, and Zweigenbaum 1996; Hobbs et al. 1993).


