For a different formalization of this and other models proposed by McCarthy, but using techniques that go beyond finite-state power, see Kiraz (1996).


Kiraz (1996) uses multi-~tape two-level morphology to analyze some Arabic data, but despite the suggestive title must simulate prosodic operations such as 'add a mora' by their extensionalized rule counterparts, which refer to C or V segments instead of moras.


For extensions of this multi-tape approach see Kiraz (1994; 1996).


