This is especially so for a large semantic and syntactic tagset such as the roughly-3000-tag ATR General English Tagset (Black et al. , 1996; Black et al. , 1998). 
The corpus, a subset s of the ATl{\]Lancaster (~eneralEnglish Treebank (Black et al., 1996), consists of a sequence of sentences which have been tagged and parsed by human experts in terms of the ATR English Grammar, a broad coverage granmtar of English with a high level of analytic detail (Black et al., 1996; Black et al., 1997). 
Our word bits construction algorithm (Ushioda 1996) is a modification and an extension 29 of the mutual information (MI) clustering algorithm proposed by Brown et al. 
For detailed presentations, see (Black et al. , 1998; Black et al. , 1996). 
We develop this method starting from a state-of-the-art maximum entropy POS tagger which itself outperforms previous attempts to tag this data (Black et al. , 1996b). 
