ATC in our system is performed using a hierarchical clustering method in which clusters are merged based on average mutual information measuring how strongly terms are related to one another (Ushioda, 1996). 
Our word bits construction algorithm (Ushioda 1996) is a modification and an extension 29 of the mutual information (MI) clustering algorithm proposed by Brown et al. 
The ATC method is based on the Ushiodas AMI (Average Mutual Information) hierarchical clustering method (Ushioda (1996)). 
This criticism leads us to automatic approaches for building thesauri from large corpora \[Hirschman et al. , 1975; Hindle, 1990; Hatzivassiloglou and McKeown, 1993; Pereira et al. , 1993; Tokunaga et aL, 1995; Ushioda, 1996\]. 
The ATC method is based on Ushiodas AMI (Average Mutual Information)-hierarchical clustering method (Ushioda, 1996). 
