The ROSE approach was developed in the context of the JANUS large-scale multi-lingual machine translation system (Lavie et al. , 1996; Woszcyna et al. , 1993; Woszcyna et al. , 1994).


The work described was conducted within the JANUS multi-lingual speech-to-speech translation system designed to translate spontaneous dialogue in a limited domain (Lavie et al 1996).


1 Introduction Iu this paper we discuss lt.OSE, all interactive ap1)roach to robust interpretation developed in the context of the JANUS speech-to-speech translation system (Lavie et al., 1996).


