Okumura and Tamura (1996) experimented on the roles of conjunctive postpositions in complex sentences. 
Some of these works are based on the Centering Theory (e.g. Okumura and Tamura (1996)). 
One method is to integrate different knowledge sources or factors (e.g. gender and number agreement, c-command constraints, semantic information) that discount unlikely candidates until a minimal set of plausible candidates is obtained (Grosz et al. , 1995; Lappin and Leass, 1994; Okumura and Tamura, 1996; Walker et al. , 1998; Yeh and Chen, 2001). 
Conjunct The latest conjunctive postposition in the sentence and its classification (Okumura and Tamura, 1996; Yoshimoto, 1986). 
Manabu Okumura and Kouji Tamura (1996) Zero Pronoun Resolution in Japanese Discourse Based on Centering Theory. 
