Almost always, I think, by using one or another kind of analogy. Hofstadter (2007) claimed, all meaning comes from analogies. In NLP, analogical algorithms have been applied to machine translation (Lepage and Denoual, 2005), morphology (Lepage, 1998), and semantic relations (Turney and Littman, 2005). 
To solve this problem, we exploit a property on symbol counts that an analogical relation must fulfill (Lepage, 1998): [x : y = z : t]|x|c +|t|c =|y|c +|z|c cA 3The authors proposed to sample x and y among the closest forms in terms of edit-distance to I(u). 
See (Lepage, 1998) or (Stroppa and Yvon, 2005) for possible interpretations. 
3.1 The solver Lepage (1998) proposed an algorithm for solving an analogical equation [x : y = z : ?]. 
Lepage (1998) proposes a less general definition, which is faster to check. 
