This separation allows for an easy adaptation of the system to other languages and domains (see \[Becker et al. 1998\]).


The processing is .based,on a fully lexicatized TreeAdjoining Grammar derived from the HPSG grammar used in the deep-processing parser module (Kasper~et aL, 1995; Becker, 1998).


For an easy adaptation to other domains and languages, we have emphasized an organization based on a general kernel system and the declarativity of knowledge sources (Becker et al. , 1998).


We first present our classical generator architecture (see also (Becker et al. , 1998; Becker et al. , 2000)) in terms of the RAGS architecture and then discuss its extension to the task-inherent problems.


realized into text by the existing VERBMOBIL generator (Becker et al. , 1998).


