Call routing task (Chu-Carroll and Carpenter, 1998) can be regarded as the specialcase.


Our approach to call routing is novel in its application of vector-based information retrieval techniques to the routing process, and in its extension of the vectorbased representation for dynamically generating disambiguation queries (Chu-Carroll and Carpenter 1998).


We evaluated the routing module performance on both transcriptions of caller utterances as well as output of the Bell Labs Automatic Speech Recognizer (Reichl et al. 1998) based on speech input of caller utterances (Carpenter and Chu-Carroll 1998).


