In contrast to many previous approaches to automated essay grading (Burstein et al. , 1998; Foltz et al. , 1998; Larkey, 1998), our goal is not to assign a letter grade to student essays. 
Introduction Research and development in automated essay scoring has begun to flourish in the past five years or so, bringing about a whole new field of interest to the NLP community (Burstein, et al (1998a, 1998b and 1998c), Foltz, et al (1998), Larkey (1998), Page and Peterson (1995)). 
In previous studies of holistically scored essays (Burstein, et al (1998a, 1998b and 1998c)), we have examined e-rater's agreement with two individual human readers. 
In contrast to many previous approaches to automated essay grading (Burstein et al. , 1998; Foltz et al. , 1998; Larkey, 1998), our goal is not to assign a letter grade to student essays. 
That is, computer-generated scores tend to matchhuman expert scores as frequently as twohuman scores match each other #28Burstein et al. , 1998#29. 
