The wildcards generation started to be rened with Barg and Walther (1998).


As discussed in (Barg and Walther, 1998), our system has been implemented in MicroCUF, a derivative of the tbrmalism CUF of (DSrre and Dorna, 1993).


Barg and Walther (1998)).


All, hough we deal here with German noun inttection, in a ti'amework close to that of (Riehemann, 1998) and (Koenig, 1999), the techniques are language-indel)endent and al)ply to other ldnds of lexical inibrmation as well, as is shown in (Walther and Barg, 1998) with respect to valency intbnnation.


Erbach (1990), Barg and Walther (1998) and Fouvry (2003) followed a unification-based symbolic approach to unknown word processing for constraint-based grammars.


