Combination techniques have been successfully applied to part of speech tagging (van Halteren et al. , 1998; Brill and Wu, 1998; van Halteren et al. , 2001). 
For part-of-speech tagging, a significant increase in accuracy through combining the output of different taggers was first demonstrated in van Halteren, Zavrel, and Daelemans (1998) and Brill and Wu (1998). 
5.4 Using MMVC in Classifier Combination The investigated MMVC model proves to be a very effective participant in classifier combination, with substantially different output to Nave Bayes (9.6% averaged complementary rate, as defined in Brill and Wu (1998)). 
This is discussed in the context of combining part-of-speech taggers in (Brill and Wu, 1998). 
Combination techniques have earlier been applied to various applications including machine translation (Jayaraman and Lavie, 2005), part-of-speech tagging (Brill and Wu, 1998) and base noun phrase identification (Sang et al., 2000). 
