There are some glossing programs in research laboratories (RXCE, see Feldweg and Breidt 1996; or Sharp, see Poznanski et al, 1998) that access dictionaries with a context-sensitive look-up procedure.


One early example was MindNet (Richardson et al., 1998), which was based on collecting 24 semantic role relations from MRDs such as the American Heritage Dictionary.


An adaptation similar to that described for disambiguating the Ragazzini/Biagi can be employed for mapping pairs of lexical resources (e.g. FrameNet (Baker et al., 1998) to WordNet), thus contributing to the beneficial knowledge integration process.


