I08-1037:1	20:205	In (Chen et al., 1998), the authors romanized Chinese NEs and selected their English transliterations from English NEs extracted from the Web by comparing their phonetic similarities with Chinese NEs.
---------------------------------------------------
W03-1501:2	10:222	In the past, named entity extraction mainly focuses on general domains and is employed to various applications such as information retrieval (Chen, Ding and Tsai, 1998), question-answering (Lin, et al. , 2001), and so on.
---------------------------------------------------
W03-1501:3	16:222	Lin and Chen (2000) further classified the works into two directions  say, forward transliteration (Wan and Verspoor, 1998) and backward transliteration (Chen et al. , 1998; Knight and Graehl, 1998), and proposed a phoneme-based model.
---------------------------------------------------
D07-1092:4	211:365	Several authors have for instance proposed approaches for translating proper names and named entities (Chen et al. , 1998; AlOnaizan and Knight, 2002).
---------------------------------------------------
D07-1092:5	26:365	Specific solutions have been proposed for those token types (Chen et al. , 1998; Al-Onaizan and Knight, 2002; Koehn and Knight, 2003).
---------------------------------------------------
W03-0317:6	15:170	Recently, much research has been done on machine transliteration for many language pairs, such as English/Arabic (Al-Onaizan and Knight, 2002), English/Chinese (Chen et al. , 1998; Lin and Chen, 2002; Wan and Verspoor, 1998), English/Japanese (Knight and Graehl, 1998), and English/Korean (Lee and Choi, 1997; Oh and Choi, 2002).
---------------------------------------------------
W03-0317:7	130:170	In the first experiment, we analyze the convergence characteristics of this model training based on a similarity-based framework (Chen et al. , 1998; Lin and Chen, 2002).
---------------------------------------------------
W99-0605:8	28:162	For problem (2), we use "transliteration" (Chen et al. , 1998; Knight and Graehl, 1998; Wan and Verspoor, 1998).
---------------------------------------------------
C04-1119:9	25:165	There are also methods that select English words from an English word list, e.g., Japaneseto-English (Fujii and Ishikawa, 2001) and Chinese-to-English (Chen et al. , 1998).
---------------------------------------------------
P08-1045:10	11:197	Here are four reference translations taken from the same corpus, with mistakes underlined: Ref1 composers such as Bach, missing name Chopin, Beethoven, Shumann, Rakmaninov, Ravel and Prokoviev Ref2 musicians such as Bach, Mozart, Chopin, Bethoven, Shuman, Rachmaninoff, Rafael and Brokoviev Ref3 composers including Bach, Mozart, Schopen, Beethoven, missing name Raphael,Rahmaniev and Brokofien Ref4 composers such as Bach, Mozart, missing name Beethoven, Schumann, Rachmaninov, Raphael and Prokofiev The task of transliterating names (independent of end-to-end MT) has received a significant amount of research, e.g., (Knight and Graehl, 1997; Chen et al., 1998; Al-Onaizan, 2002).
---------------------------------------------------
