Veins of child nodes are computed recursively according to the rules described by Cristea et al.(1998). 
This is consistent with tile distinction between "direct" and "indirect" references discussed by Cristea, et al.(1998). 
The units that hierarchically precede a given unit are determined according to Veins Theory (VT) (Cristea et al. , 1998), which is described briefly below. 
Referential expressions surrounded by boxes refer to Mr: Casey; those surrounded by ellipses refer to Genetic Thercq~y Inc. are computed recursively according to tile rules described by Cristea et al.(1998). 
This is consistent with the distinction between "direct" and "indirect" references discussed in (Cristea, et al. , 1998). 
