The generalisation of vibhakti to account for word order essentially introduces a facility analogous to topological fields (as found in Topological Dependency Grammar (Duchier and Debusmann, 2001) and DACHS (Broker, 1998)) to PGF.


More recent versions of dependency grammars (see e.g.(Kahane et al. , 1998; Lombardo and Lesmo, 1998; Broker, 1998)) impose on nonprojective D-trees some constraints weaker than projectivity (cf.


