Ambiguity preserving semantic transfer can be devised on sets of meaning constructors rather than disambiguated meanings (Genabith et al., 1998).


To this purpose it provides parallelism constraints (Niehren and Koller, 1998) of the form X/X'~Y/Y' reminiscent to equality up-to constraints (Niehren et al., 1997a), and anaphoric bindings constraints of the form ante(X)=Xq As proved in (Niehren and Koller, 1998), CLLS extends the expressiveness of context unification (Niehren et al., 1997a).


The insights of the CU-analysis in (Niehren et al., 1997b) carry over to CLLS, but the awkward second-order equations for expressing dominance in CU can be omitted (Niehren and Koller, 1998).


The linguistic analysis part consists of several parsers which, in turn, also operate ill parallel (Ruland et al. , 1998).


Each translation inodule chooses independently a path through the WItG, and a possible segmentation according to its grammar and to the prosody information (Buckow et al. , 1998).


