1 Introduction Although several researchers (Kawai et al. , 1984; McCoy et al. , 1996; Schneider and McCoy, 1998; Tschichold et al. , 1997) have shown that rulebased methods are effective to detecting grammatical errors in the writing of learners of English, it has been pointed out that it is hard to write rules for detecting errors concerning the articles and singular plural usage.


On the other hand, much work has leveraged statistical methods in detecting properties of student essays via stylometrics (Aaronson, 2001) 1, latent semantic indexing (Wiemer-Hastings et al. , 1998), and feature analysis.


For example, the knowledge-based engines have been used for analyzing essays: parsers (Carbonell and Hayes, 1984; Schneider and McCoy, 1998), grammar and spelling checkers (Park et al. , 1997), discourse processing analyzers (Miltsakaki and Kukich, 2000), and other hand-crafted linguistic knowledge sources.


2 Background Various strategies exist to build robustness into the parsing process: grammar constraints can be relaxed (Fouvry, 2003), partial parses can be concatenated to form a full parse (Penstein Rose and Lavie, 1997), the input sentence can itself be transformed until a parse can be found (Lee et al., 1995), and mal-rules describing particular error patterns can be included in the grammar (Schneider and McCoy, 1998).


