H05-1102:1	53:366	Thus, the LTAGspinal parsing model to be proposed in Section 3 can be viewed as a parser at the meta-grammar (Candito, 1998; Kinyon and Prolo, 2002) level for traditional LTAG.
---------------------------------------------------
W06-1503:2	7:108	In this paper, we extend some earlier work on multilingual MGs (Candito, 1998; Kinyon and Rambow, 2003) by proposing crosslinguistic and framework-neutral syntactic invariants, which we apply to TAG.
---------------------------------------------------
C02-1153:3	18:188	Several approaches have been proposed in the literature describing compact representations methods for LTAGs, perhaps the best known being (VijayShanker and Schabes, 1992), (Candito, 1996; Candito, 1998), (Evans et al. , 1995; Evans et al. , 2000), (Xia et al. , 1998; Xia, 2001), and (Becker, 1993; Becker, 1994; Becker, 2000).
---------------------------------------------------
J00-2004:4	86:517	There are many plausible representations, such as pairs of trees from synchronous tree adjoining grammars (Abeill6 et al. 1990; Shieber 1994; Candito 1998), lexical conceptual structures (Dorr 1992) and WordNet synsets (Fellbaum 1998; Vossen 1998).
---------------------------------------------------
W06-1520:5	7:78	Large scale handcrafted grammars for many languages have been built based on this paradigm (Joshi, 2001; XTAG Research Group, 2001; Kroch and Joshi, 1985; Abeille and Candito, 2000; Candito, 1998; Becker, 1993; Frank, 2002; Joshi and Schabes, 1997; Abeille and Rambow, 2000) as well as grammars extracted from corpora (Chen and Vijay-Shanker, 2000; Chiang, 2000; Hwa, 1999; Xia et al. , 2001; Xia, 2001).
---------------------------------------------------
W06-1520:6	11:78	Although we can think of simply inserting functional labels in elementary trees or use them in a meta-level to generate the grammar, such as in (Candito, 1998; Kinyon, 2000; Clement and Kinyon, 2003), such tags are generally not seen as an essential part of the derivational process.
---------------------------------------------------
