2.3 Partial Analyses and the Syntax-Semantics Interface Our architecture requires that the linguistic analysis module is capable of delivering not just analyses of complete utterances, but also of phrases and even of lexical items in the special interface format of VITs (VERBMOBIL Interface Terms) (Bos et al. , 1998).


The underspecified semantic representation technique we have used in this paper reflects the core semantic part of the Verbmobil Interface Term, VIT (Bos et al., 1998).


In particular, the module has been designed so as to process input fl'om  tree banks  a statistic context-free parser trained on these tree banks  a finite-state parser  a traditional feature-structure parser The semantic representations which the module constructs m'e so-called Verbmobil Inter~&ce \[\[~Ol'lllS (\\[Irl~s) (BOS et al. , 1998), (l)uilding on Reyle's Underspecified Discourse R,epresentation Structures (1993), see an example, in Figure 1).


3 The VIT Format The VIT (short for Verbmobil h~terface Term) was designed as a common output format for the two alternative and independently developed syntacticsemantic analysis components of the first project phase (Bos et al., 1998).


