The most commonly used are Karttunnens chart subsumption check (White and Baldridge, 2003; Hockenmaier and Steedman, 2002) and Eisners normal-form constraints (Bozsahin, 1998; Clark and Curran, 2007).


Bozsahin (1998) presents work on using CCG to model languages with free word order.


Our lexical type assignment to case morphemes (24ef) departs from other CCG analyses of case (e.g. , Steedman 1985, 1991a, Bozsahin 1998).


These studies correlate morphological case with type raising of arguments, in the case of Bozsahin (1998), via a value-raised category assignment to case morphemes.


