ture that uses '% pragmatic adaptation" (LuperFoy and others, 1998), and Mima et al. proposed a method that uses "situational information" (Mima and others, 1997).


We choose to focus on building this class of dialogue systems because we share with (Allen et al. , 2001), a version of the the Practical Dialogue 5Compare this with the motivation behind the Pragmatic Adapter idea of (LuperFoy et al. , 1998).


For these sorts of reasons it is clear that formfilling or data-base query style dialogues (e.g. the CSLU Toolkit, (McTear, 1998)) will not suffice here (see (Elio and Haddadi, 1999; Allen et al. , 2001) for similar arguments).


