In other words, we are measuring the contribution of this long-range information over and above a model which uses local tag-n-grams as context, rather than measuring the gain over a naive model which does not take context into account, as was the case with the mutual information experiments in (Black et al. , 1998). 
Lower-order n-grams which are closer to word being tagged offer the greatest predictive power (Black et al. , 1998). 
Where these intrasentential words were included, they 1 (Black et al. , 1998) determined a 6-sentence window to be optimal for this task. 
And in fact, (Black et al. , 1998) demonstrate a significant "tag trigger-pair" effect. 
This experiment measures the effect of employing the triggers specified in (Black et al. , 1998) --i.e. the presence (or absence) in the previous 6 sentences of each tag in the tagset, in turn-to assist a real tagger, as opposed to simply measuring their mutual information. 
