Baggas corpus is a document collection for the English personal name John Smith that was used by Bagga & Baldwin (1998). 
Four-fold crossvalidation is employed and B-CUBED metric (Bagga and Baldwin, 1998) is adopted to evaluate the clustering results. 
Previous research for cross-document name disambiguation applies vector space model (VSM) for context similarity, only using co-occurring words [Bagga & Baldwin 1998]. 
Some of very few works we are aware of that works directly with text data and across documents, are (Bagga and Baldwin, 1998; Mann and Yarowsky, 2003), which consider one aspect of the problem  that of distinguishing occurrences of identical names in different documents, and only of people. 
Bagga and Baldwin (1998b) produced one of the first works in cross-document co-reference. 
