This paper presents an investigation into the extent to which the EDOL reduces the need for feature passing in two existing wide-coverage grammars: the XTAG grammar (XTAG-Group, 1995), and the LEXSYS grammar (Carroll et al. , 1998).


However, the problem of grammar size in TAG has to some extent been addressed both with respect to grammar encoding (Evans et al. , 1995; Candito, 1996) and parsing (Joshi and Srinivas, 1994; Evans and Weir, 1998).


