The phonemebased transliteration models in the literature correspond to either M(E G ,C P ) (Wan and Verspoor, 1998; Lee and Chang, 2003; Jiang et al., 2007) or M(E P ,C P ) (Meng et al., 2001; Gao et al., 2004; 7 In our test set, an English word corresponds to one reference Chinese transliteration.


A variety of Englishto-Chinese machine transliteration models has been proposed in the last decade (Meng et al., 2001; Gao et al., 2004; Jiang et al., 2007; Lee and Chang, 2003; Li et al., 2004; Li et al., 2007; Wan and Verspoor, 1998; Virga and Khudanpur, 2003).


They can be categorized into those based on Chinese phonemes (Meng et al., 2001; Gao et al., 2004; Jiang et al., 2007; Lee and Chang, 2003; Wan and Verspoor, 1998; Virga and Khudanpur, 2003) and those that dont rely on Chinese phonemes (Li et al., 2004; Li et al., 2007).


Chinese phonemebased transliteration models in the literature fall into either M(E G ,C P ) or M(E P ,C P ) (Meng et al., 2001; Gao et al., 2004; Jiang et al., 2007; Lee and Chang, 2003; Wan and Verspoor, 1998; Virga and Khudanpur, 2003).


