The fact that current anaphora resolution systems rely exclusively on the linear nature of texts in Order to determine the LPA of an anaphor seems odd, given that several studies have claimed that there is a strong relation between discourse structure and reference (Sidner, 1981; Gmsz and Sidner, 1986; Grosz et aL, 1995; Fox, 1987; Vonk et al. , 1992; Azzam et al. , 1998; Hitzeman and P.oesio, 1998).


The fact that current anaphora resolution systems rely exclusively on the linear nature of texts in order to determine the LPA of an anaphor seems odd, given flint several studies have claimed that there is a strong relation between discourse structure and reference (Sidner, 1981 ; Grosz and Sidner, 1986; Grosz et al. , 1995; Fox, 1987; Vonk ct al. , 1992; Azzam el al. , 1998; Hitzcman and Pocsio, 1998).


Moreover, clues are used about the grammatical and pragmatic functions of expressions as in (Grosz et al. , 1995), (Strube, 1998), "or (Azzam et al. , 1998) as well as rule-based empirical approaches like (Nakaiwa and Shirai, 1996) or (Murata and Nagao, 1997), to determine the most salient referent.


Here, we compare VT to stack-based models of discourse structure based on Grosz and Sidner's (1986) (G&S) focus spaces (e.g. , Hahn and Strbe, 1997; Azzam, et al. , 1998).


ated focus-based algorithm for the resolution of pronominal anaphora (Azzam et al. , 1998).


