(Collier et al., 1998a),(Collier et al., 1998b), for aligning texts in non-cognate languages at the article level.


First, we use a method based on CLIR to align Japanese and English articles (Collier et al. , 1998; Matsumoto and Tanaka, 2002) and then a method based on DP matching to align Japanese and English sentences (Gale and Church, 1993; Utsuro et al. , 1994) in these articles.


We first aligned the articles using a method based on CLIR (Collier et al. , 1998; Matsumoto and Tanaka, 2002) and then aligned the sentences in these articles by using a method based on dynamic programming (DP) matching (Gale and Church, 1993; Utsuro et al. , 1994).


