Langlais and Patry (2007) deal with an input space in the order of tens of thousand forms (the typical size of a vocabulary) using following strategy for EI(u). 
Langlais and Patry (2007) applied it to the task of translating unknown words in several European languages, an idea investigated as well by Denoual (2007) for a Japanese to English translation task. 
Instead, Langlais and Patry (2007) proposed to solve analogical equations [y : x = t : ?] for some pairsx,ybelonging to the neighborhood3 of I(u), denotedN(t). 
Langlais and Patry (2007) applied it to the task of translating unknown words in several European languages, an idea investigated as well by Denoual (2007) for a Japanese to English translation task. 
A search strategy is proposed which outperforms the one described in (Langlais and Patry, 2007). 
