W08-1003:1	166:178	WhilePARSEVAL (Blacket al., 1991) isstilloneofthemostimportantmetrics,othermeasuresmaybe moreadaptedto our problem(Carroll et al.,2002;RehbeinandvanGenabith,2007).
---------------------------------------------------
W08-1007:2	12:179	By contrast, Rehbein and van Genabith (2007) study different parser evaluation metrics by simulating parser errors on two German treebanks (with different treebank annotation schemes) and they claim that the question whether German is harder to parse than English is still undecided.
---------------------------------------------------
W08-1006:3	101:136	In particular, Rehbein and van Genabith (2007) correctly emphasize how F1 scores are very dependent on the amount of branching structure in a treebank, and are hence not validly comparable across annotation styles.
---------------------------------------------------
W08-1006:4	105:136	Broadly consistent with the results of Rehbein and van Genabith (2007), Table 9 shows that the disparity in performance between TuBa-D/Z and Tiger is much smaller when measuring dependency accuracy rather than labeled bracketing F1, especially when using gold tags.
---------------------------------------------------
W08-1004:5	107:182	Asmentionedpreviously, RehbeinandvanGenabith (2007a) showed that PARSEVAL is affected by the ratio of terminal to non-terminal nodes, so these results are not expected to indicate the quality of the parses.
---------------------------------------------------
W08-1004:6	27:182	(2006).2 In recent related work, Rehbein and van Genabith (2007a) demonstrate using the Tiger and TuBa-D/Z 1The evaluation is based only on the grammatical function; it does not identify the dependency pair that it labels.
---------------------------------------------------
W08-1004:7	125:182	As discussed in Rehbein and van Genabith (2007b), labels such as subject (SB for Negra, ON for TuBa-D/Z) are not necessarily comparable in all instances, but such cases are infrequent.
---------------------------------------------------
W08-1004:8	135:182	In keeping with the results from Rehbein and van Genabith (2007a), we find that PARSEVAL is not an adequate predictor of performance in an evaluation targeting the functorargument structure of the sentence for comparisons between PCFG parsers trained on corpora with different annotation schemes.
---------------------------------------------------
