From this we extracted grammar rules following the technique described in Cohn and Lapata (2007). 
3 Basic Model Our work builds on the model developed by Cohn and Lapata (2007). 
Instead, we use Cohn and Lapatas (2007) extractive model as a baseline. 
4 Extensions In this section we present our extensions of Cohn and Lapatas (2007) model. 
Cohn and Lapata (2007) extract a STSG from a parsed, word-aligned corpus of source and target sentences. 
