Task (ii) imitates the evaluation reported by Shimbo and Hara (2007), and to compare our method with their coordination analysis method. 
The proposed method outperformed Shimbo-Hara method in this task, although the setting of this task is mostly identical to (Shimbo and Hara, 2007) and does not include nested coordinations. 
Shimbo and Hara (2007) considered many features for coordination disambiguation and automatically optimized their weights, which were heuristically determined in Kurohashi and Nagao (1994), using a discriminative learning model. 
(2007; 2008) and Shimbo and Hara (2007) applied discriminative learning methods to coordinate structure analysis. 
4.2 Difference from Shimbo and Haras method The method proposed in this paper extends the work of Shimbo and Hara (2007). 
