W09-1125:1	152:184	Giuliano and Gliozzo (2007) propose an unsupervised approach based on lexical entailment, consisting in assigning an entity to the category whose lexicalization can be replaced with its occurrences in a corpus preserving the meaning.
---------------------------------------------------
W09-1125:2	11:184	Consequently, in the literature, supervised approaches are confined to classify entities into broad categories, such as persons, locations, and organizations, while the fine-grained classification has been approached with minimally supervised (e.g., Tanev and Magnini (2006) and Giuliano and Gliozzo (2008)) and unsupervised learning algorithms (e.g., Cimiano and Volker (2005) and Giuliano and Gliozzo (2007)).
---------------------------------------------------
C08-1034:3	155:167	More recently, Giuliano and Gliozzo (2007) proposed an unsupervised approach based on lexical entailment, consisting in assigning an entity to the category whose lexicalization can be replaced with its occurrences in a corpus preserving the meaning.
---------------------------------------------------
C08-1034:4	99:167	5.2 Accuracy Table 1 shows microand macro-averaged results of the proposed method obtained on the Tanev and Magnini (2006) benchmark and compares them with the class-example (Tanev and Magnini, 2006), IBLE (Giuliano and Gliozzo, 2007), and class-word (Cimiano and Volker, 2005) methods, respectively.
---------------------------------------------------
E09-1064:5	222:230	Other related instance-based evaluations (Giuliano and Gliozzo, 2007; Connor and Roth, 2007) performed lexical substitutions, but did not handle the non-substitutable cases.
---------------------------------------------------
