This model is used by Marinov (2007) and in component parsers of the Nilsson ensemble system (Hall etal.


5.2.2 Inference The most common inference technique in transitionbased dependency parsing is greedy deterministic search, guided by a classifier for predicting the next transition given the current parser state and history, processing the tokens of the sentence in sequential left-to-right order7 (Hall et al. , 2007a; Mannem, 2007; Marinov, 2007; Wu et al. , 2007).


A more orthodox implementation of Covingtons algorithms for data-driven dependency parsing is found in Marinov (2007).


