Data-driven grammar-based parsers, such as Bick (2007), Schneider et al.


The best performing system on the CHILDES corpus is an open system (Bick, 2007), but the distance to the top closed system is approximately 1 percentage point.


Bick(2007)usedahybridapproach, whereadatadriven parser trained on the labeled training data was given access to the output of a Constraint Grammar parser for English run on the same data.


