5.3.3 Learning Most of the graph-based parsers were trained using an online inference-based method such as passiveaggressive learning (Nguyen et al. , 2007; Schiehlen and Spranger, 2007), averaged perceptron (Carreras, 2007), or MIRA (Shimizu and Nakagawa, 2007), while some systems instead used methods based on maximum conditional likelihood (Nakagawa, 2007; Hall et al. , 2007b).


Maximum spanning tree algorithms can be used for finding the highest scoring non-projective tree in a first-order model (Hall et al. , 2007b; Nguyen et al. , 2007; Canisius and Tjong Kim Sang, 2007; Shimizu and Nakagawa, 2007), while Eisners dynamic programming algorithm solves the problem for a first-order factorization in the projective case (Schiehlen and Spranger, 2007).


This type of scoring function is often referred to as a firstorder model.8 Several systems participating in this yearssharedtaskusedfirst-ordermodels(Schiehlen and Spranger, 2007; Nguyen et al. , 2007; Shimizu and Nakagawa, 2007; Hall et al. , 2007b).


