In this table, rule-coord-w/sim represents a rule-based dependency parser; prob-coord-w/sim represents the probabilistic parser of dependency, coordinate and case structure (Kawahara and Kurohashi, 2007); and prob-coord-wo/sim represents our proposed model. 
We used hand-annotated 759 web sentences, which was used by Kawahara and Kurohashi (2007). 
We used two baseline systems for comparative purposes: a rule-based dependency parser (Kurohashi and Nagao, 1994) and the probabilistic generative model of dependency, coordinate and case structure analysis (Kawahara and Kurohashi, 2007)5. 
Figure 4 also in4Note that Kawahara and Kurohashi (2007) exclude the dependencybetweenthelasttwobunsetsu, sinceJapaneseisheadnal and thus the second last bunsetsu unambiguously depends on the last bunsetsu. 
5.2 Our Model We employ a probabilistic generative dependency parser (Kawahara and Kurohashi, 2007) as a base model. 
