The feature set used herein is similar to several state-of-the-art WSD systems (Lee and Ng., 2002; Ando, 2006; Tratz et al., 2007; Cai et al., 2007; Agirre and Lopez de Lacalle, 2007; Specia et al., 2007), which is further integrated into a Nave Bayes classifier (Lee and Ng., 2002; Mihalcea, 2007).


In Cai et al (2007), LDA is utilized to capture the global context information as the topic features for better performing the WSD task.


