Another innovation was the use of k-best spanning tree algorithms for inference with a non-projective first-order model (Hall et al. , 2007b). 
This technique is used by Sagae and Tsujii (2007) and in the Nilsson system (Hall et al. , 2007a). 
For languages with non-projective dependencies, graphs therefore need to be projectivized for training and deprojectivized for testing (Hall et al. , 2007a; Johansson and Nugues, 2007b; Titov and Henderson, 2007). 
Data-driven grammar-based parsers, such as Bick (2007), Schneider et al. 
In the case of grammarbased parsers, a classifier is used to disambiguate in cases where the grammar leaves some ambiguity (Schneider et al. , 2007; Watson and Briscoe, 2007) 5.2.3 Learning Transition-based parsers either maintain a classifier that predicts the next transition or a global probabilistic model that scores a complete parse. 
