W08-0301:1	115:195	The decoder in the experiments is our reimplementation of HIERO (Chiang, 2007), augmented with a 5-gram language model and a reordering model based on (Zhang et al., 2007).
---------------------------------------------------
P08-2038:2	16:101	Different from (Zhang et al., 2007), our annotation algorithm is able to label both syntactic and non-syntactic phrases.
---------------------------------------------------
