D07-1096:1	273:410	Canisius and Tjong Kim Sang (2007) cast the same type of arc-based factorization as a weighted constraint satisfaction problem.
---------------------------------------------------
D07-1096:2	279:410	Maximum spanning tree algorithms can be used for finding the highest scoring non-projective tree in a first-order model (Hall et al. , 2007b; Nguyen et al. , 2007; Canisius and Tjong Kim Sang, 2007; Shimizu and Nakagawa, 2007), while Eisners dynamic programming algorithm solves the problem for a first-order factorization in the projective case (Schiehlen and Spranger, 2007).
---------------------------------------------------
W09-1203:3	18:146	Memory-based algorithms have been previously applied to semantic role labeling and parsing separately (Morante et al., 2008; Canisius and Tjong Kim Sang, 2007).
---------------------------------------------------
