This distinguishes e-negotiations from agentcustomer phone conversations studied in (Takeuchi et al, 2007), where an agent follows the call flow pre-defined by his companys policy.


We claim that the language capturedine-negotiationtextualdatachangesasanegotiation progresses, and that this is clearly detectable, even though it does not follow a sequential-stage model common in face-to-face-negotiations (Adair and Brett, 2005) or an agent-customer interaction call flow recommended by a company (Takeuchi et al, 2007).


