The best performing (closed class) system in the domain adaptation track used a combination of colearningandactivelearningbytrainingtwodifferent parsers on the labeled training data, parsing the unlabeled domain data with both parsers, and adding parsed sentences to the training data only if the two parsers agreed on their analysis (Sagae and Tsujii, 2007). 
See Sagae and Tsujii (2007) for more information on the parser. 
Finally, in table 1 we also show results obtained with standard bottom-up shift-reduce dependency parsing for trees, using the parser described in (Sagae and Tsujii, 2007). 
Sagae and Tsujii applied an ensemble method to the domain adaptation track and achieved the highest score (Sagae and Tsujii, 2007). 
However, we did not use the same parsing algorithms as the ones used by Sagae and Tsujii (2007). 
