For more detail, see Chen & Martin (2007). 
For example, the topics Sport and Education are important cues for differentiating mentions of Michael Jordan, which may refer to a basketball player, a computer science professor, etc. Second, as noted in the top WePS run (Chen and Martin, 2007), feature development is important in achieving good coreference performance. 
Chen & Martin (2007) introduced one of those similarity schemes, ?two-level SoftTFIDF?? 
We base our work partly on previous work done by Bagga and Baldwin (Bagga and Baldwin, 1998), which has also been used in later work (Chen and Martin, 2007). 
Chen and Martin (2007) explored the use of a range of syntactic and semantic features in unsupervised clustering of documents. 
