Finally, twosystemsusemodelsbased on LR parsing (Sagae and Tsujii, 2007; Watson and Briscoe, 2007).


In a similar fashion, Watson and Briscoe (2007) used a variant of self-training to make use of the unlabeled target data.


In the case of grammarbased parsers, a classifier is used to disambiguate in cases where the grammar leaves some ambiguity (Schneider et al. , 2007; Watson and Briscoe, 2007) 5.2.3 Learning Transition-based parsers either maintain a classifier that predicts the next transition or a global probabilistic model that scores a complete parse.


(2007), and Watson and Briscoe (2007), need preand post-processing in order to map the dependency graphs provided as training data to a format compatible with the grammar used, and vice versa.


To train these classifiers and probabilitistic models several approaches were used: SVMs (Duan et al. , 2007; Hall et al. , 2007a; Sagae and Tsujii, 2007), modified finite Newton SVMs (Wu et al. , 2007), maximum entropy models (Sagae and Tsujii, 2007), multiclass averaged perceptron (Attardi et al. , 2007) and maximum likelihood estimation (Watson and Briscoe, 2007).


