The aim was to come as close as possible within our framework to the system proposed by Yamamoto and Sumita (2007).


Both Yamamoto and Sumita (2007) and Foster and Kuhn (2007), extended this to include the translation model.


Recently, experiments in the field of machine translation (Hasan and Ney, 2005; Yamamoto and Sumita, 2007; Finch et al. 2007, Foster and Kuhn, 2007) have shown that classspecific models are also useful for translation.


In the method proposed by Yamamoto and Sumita (2007), topic dependency was implemented by partitioning the data into sets before the decoding process commenced, and subsequently decoding these sets independently using different models that were specific to the class predicted for the source sentence by a classifier that was run over the source sentences in a pre-processing pass.


