In works such as (Xia and McCord, 2004; Collins et al., 2005; Wang et al., 2007; Habash, 2007), reordering decisions are done deterministically, thus placing these decisions outside the actual PSMT system by learning to translate from a reordered source language. 
Finding the Main Verb Position Chinese ordering differs from English mainly in clause ordering (Wang et al., 2007) and within the noun phrase. 
(Collinsetal., 2005; Wang et al., 2007) do this using manually created rules, and (Xia and McCord, 2004) and (Habash, 2007) use automatically extracted rules. 
baseline is the heuristic rules in (Wang et al., 2007). 
In works such as (Xia and McCord, 2004; Collins et al., 2005; Wang et al., 2007; Habash, 2007), reordering decisions are done deterministically, thus placing these decisions outside the actual PSMT system by learning to translate from a reordered source language. 
