D09-1043:1	163:172	Also related to the present work is discriminative training in syntax-based MT (Turian et al., 2007; Watanabe et al., 2007; Blunsom et al., 2008; Chiang et al., 2009).
---------------------------------------------------
D08-1076:2	159:206	The incorporation of a large number of sparse feature functions is described in (Watanabe et al., 2007).
---------------------------------------------------
P08-1024:3	55:227	Both the global models (Liang et al., 2006; Watanabe et al., 2007) use fairly small training sets, and there is no evidence that their techniques will scale to larger data sets.
---------------------------------------------------
P08-1024:4	18:227	For this reason, to our knowledge, all discriminative models proposed to date either side-step the problem by choosing simple model and feature structures, such that spurious ambiguity is lessened or removed entirely (Ittycheriah and Roukos, 2007; Watanabe et al., 2007), or else ignore the problem and treat derivations as translations (Liang et al., 2006; Tillmann and Zhang, 2007).
---------------------------------------------------
P08-1024:5	50:227	To our knowledge no systems directly address Problem 1, instead choosing to ignore the problem by using one or a small handful of reference derivations in an n-best list (Liang et al., 2006; Watanabe et al., 2007), or else making local independence assumptions which side-step the issue (Ittycheriah and Roukos, 2007; Tillmann and Zhang, 2007; Wellington et al., 2006).
---------------------------------------------------
I08-2087:6	29:170	The use of structured prediction to SMT is also investigated by (Liang et al. 2006; Tillmann and Zhang 2006; Watanabe et al. 2007).
---------------------------------------------------
D08-1024:7	165:186	We also tested some of the differences between our training method and Watanabe et al.s (2007); the results are shown in Table 2.
---------------------------------------------------
D08-1024:8	139:186	It is worth noting that this experimentation is on a larger scale than Watanabe et al.s (2007), and considerably larger than Marton and Resniks (2008).
---------------------------------------------------
D08-1024:9	16:186	This paper continues a line of research on online discriminative training (Tillmann and Zhang, 2006; Liang et al., 2006; Arun and Koehn, 2007), extending that of Watanabe et al.
---------------------------------------------------
