2.4 Factor Model Decomposition Factored translation models (Koehn and Hoang, 2007) extend the phrase-based model by integrating word level factors into the decoding process. 
Decoding is carried-out using the Moses decoder (Koehn and Hoang, 2007). 
In their presentation of the factored SMT models, Koehn and Hoang (2007) describe experiments for translating from English to German, Spanish and Czech, using morphology tags added on the morphologically rich side, along with POS tags. 
Koehn and Hoang (2007) present Factored Translation Models as an extension to phrase-based statistical machine translation models. 
Decoding is carried-out using the Moses decoder (Koehn and Hoang, 2007). 
