3 Experiments 3.1 Data set We experiment on the data set published by (Bergsma and Wang, 2007).


There are few related studies on query segmentation in spite of its importance and applicability in many query analysis tasks such as query suggestion, query substitution, etc. To our knowledge, three approaches have been studied in previous works: MI (Mutual Information) approach (Jones et al., 2006; Risvik et al., 2003), supervised learning approach (Bergsma and Wang, 2007) and EM optimization approach (Tan and Peng, 2008).


