We pruned the generated phrase tables following the method introduced in (Johnson et al. , 2007). 
Various filtering techniques, such as (Johnson et al., 2007) and (Chen et al., 2008), have been applied to eliminate a large portion of the translation rules that were judged unlikely to be of value for the current translation. 
(Johnson et al., 2007) has presented a technique for pruning the phrase table in a phrasebased SMT system using Fishers exact test. 
In this paper, we extend the work in (Johnson et al., 2007) to a hierarchical phrase-based translation model, which is built on synchronous contextfree grammars (SCFG). 
In the word-alignment derived phrase extraction approach, precision can be improved by filtering out most of the entries by using a statistical significance test (Johnson et al., 2007). 
