(Patwardhan and Riloff, 2007) propose a supervised approach for IE, in which relevant text regions for a target relation are identified prior to applying extraction rules. 
For example, most readers would agree that sentence (1) below is describing a terrorist event, while sen6A similar strategy was used in previous work (Patwardhan and Riloff, 2007) to generate a test set for the evaluation of a relevant region classifier. 
Our previous work in event-based IE (Patwardhan and Riloff, 2007) also used a pattern-based approach that applied semantic affinity patterns to relevant regions in text. 
For example, Patwardhan and Riloff (2007) identify categories like Terrorist organization as participants in terror-related semantic relations, which consists predominantly of named entities. 
In addition, Patwardhan and Riloff (2007) also demonstrated that selectively applying event patterns to relevant regions can improve MUC event extraction. 
