Such work is extremely useful, given the harmfulness of annotation errors for training, including the learning of noise (e.g., Hogan, 2007; Habash et al., 2007), and for evaluation (e.g., Padro and Marquez, 1998).


For example, nominal case markers in Arabic have been shown to be automatically determinable from syntax and word morphology and neednt be manually annotated (Habash et al., 2007a).


3Arabic transliterations are in the Habash-SoudiBuckwalter transliteration scheme (Habash et al., 2007b).


