Theglobalfeatures that used in our system are based on (Johansson and Nugues, 2008) that used for re-ranking. 
And the inside grandchildren features are related to all the children of t. This is different from the models used by Carreras (2007) and Johansson and Nugues (2008). 
To the best of our knowledge, three 118 types of joint approaches have been proposed: N-best based approach (Johansson and Nugues, 2008), synchronous joint approach (Henderson et al., 2008), and a joint approach where parsing and SRL are performed simultaneously (Llus and M`arquez, 2008). 
Rather than only using the left-most and rightmost grandchildren as Carreras (2007) and Johansson and Nugues (2008) did, we use all left and right grandchildren in our model. 
Previous research dealt with such information using re-ranking (Toutanova et al., 2005; Johansson and Nugues, 2008). 
