(2001), Ng and Cardie (2002b), Bengtson and Roth (2008)), and are computed automatically.


Bengtson and Roth (2008) simply discard twinless CEs, but this solution is likely too lenient  it doles no punishment for mistakes on twinless annotated or extracted CEs and it would be tricked, for example, by a system that extracts only the CEs about which it is most confident.


This system is a classification-based coreference resolver, modeled after the systems of Ng and Cardie (2002b) and Bengtson and Roth (2008).


fairly comprehensive set of 61 features introduced in previous coreference resolution systems (see Bengtson and Roth (2008)).


(2003); for state-ofthe-art performance on the ACE data sets see, e.g. Bengtson and Roth (2008) and Luo (2007).


