Automatic metrics have been criticized for a variety of reasons (Babych and Hartley, 2004; Callison-Burch et al., 2006; Chiang et al., 2008), and it is clear that they only loosely approximate human judgments.


2.3 Avoiding the loss of entities Deleted and spurious content is a well known problem for statistical models (Chiang et al., 2008).


(Callison-Burch et al., 2006; Chiang et al., 2008).


