(2002), Choi and Cardie (2008)). 
Content-word negators are words that are not function words, but act semantically as negators (Choi and Cardie, 2008).3 Although it is possible to artificially construct a very convolutedsentence with lots of negations, it is unlikely for multiple layers of negations to appear very often in natural language (Pickett et al. 
(2005) with General Inquirer dictionary as suggested by Choi and Cardie (2008). 
Indeed better accuracies in phrase semantic orientation annotation can be obtained by using supervised classifiers and more sophisticated context features (Choi and Cardie, 4http://www.cs.pitt.edu/mpqa 2008). 
Choi and Cardie (2008) also focus on the expression-level polarity classification, but their evaluation setting is not as practical as ours in that they assume the inputsare guaranteed to be either strongly positive or negative. 
