The questions were taken from the question data in Rimell and Clark (2008), which was obtained from various years of the TREC QA track.


Use of the C&C questionmodelmadeahugedifferenceforthe whobject construction (81.2% vs. 27.5%), showing that adaptation techniques specific to a particular 818 construction can be successful (Rimell and Clark, 2008).


One possibility is to create more training data targeting these constructions  effectively active learning by construction  in the way that Rimell and Clark (2008) were able to build a question parser.


