We compare two aligners: a one-to-one aligner, which cannot construct MWE alignments (UNIQ), and a many-to-many aligner (MANLI) (MacCartney et al., 2008), which can.


(2009) mentioned two alignment modules, one is a phrase-based alignment system called MANLI (MacCartney et al., 2008), and the other is a stochastic aligner based on dependency graphs.


Systems based on lexical (word-based or phrase-based) matching of h in t typically applied only lexical rules (without vari1063 ables), where both sides of the rule are matched directly in t and h (Haghighi et al., 2005; MacCartney et al., 2008).


