P09-1039:1	191:228	Comparing with the baselines, we observe that our full model outperforms that of McDonald and Pereira (2006), and is in line with the most accurate dependency parsers (Nivre and McDonald, 2008; Martins et al., 2008), obtained by combining transition-based and graph-based parsers.14 Notice that our model, compared with these hybrid parsers, has the advantage of not requiring an ensemble configuration (eliminating, for example, the need to tune two parsers).
---------------------------------------------------
P09-1039:2	201:228	The three baselines are the second order model of McDonald and Pereira (2006) and the hybrid models of Nivre and McDonald (2008) and Martins et al.
---------------------------------------------------
P09-1039:3	185:228	baselines, allofthemstate-of-the-artparsersbased on non-arc-factored models: the second order model of McDonald and Pereira (2006), the hybrid model of Nivre and McDonald (2008), which combines a (labeled) transition-based and a graphbased parser, and a refinement of the latter, due to Martins et al.
---------------------------------------------------
D09-1086:4	120:269	2In the diagonal cells, source and target styles match, so training the QG parser amounts to a stacking technique (Martins et al., 2008).
---------------------------------------------------
E09-1037:5	99:224	Also relevant are stacked learning (Cohen and Carvalho, 2005), interpretable as approximation of non-local feature values (Martins et al., 2008), and M-estimation (Smith et al., 2007), which allows training without inference.
---------------------------------------------------
E09-1023:6	13:204	A recent innovation in dependency parsing, relevant here, is to use the predictions made by one model to refine another (Nivre and McDonald, 2008; Torres Martins et al., 2008).
---------------------------------------------------
E09-1023:7	89:204	The output from one classifier is used as a feature in the next one (see also Torres Martins et al., 2008).
---------------------------------------------------
P09-1059:8	75:154	This coincides with the stacking method for combining dependency parsers (Martins et al., 2008; Nivre and McDonsource corpus train with normal features source classifier train with additional features target classifier target corpus source annotationclassification result Figure 2: The pipeline for training.
---------------------------------------------------
