As with the previous work of (Li and Roth, 2002; Li and Roth, 2006; Krishnan et al., 2005; Moschitti et al., 2007), we propose a feature driven statistical question classifier (Huang et al., 2008).


The individual feature contributions were discussed in greater detail in (Huang et al., 2008).


More detailed information can be found at (Huang et al., 2008).


We used our QC system presented in (Huang et al., 2008), which classifies each question into 6-coarse categories (i.e., abbr., entity, human, location, number, description) as well as 50-fine categories (i.e., color, food, sport, manner, etc.) with almost 90% accuracy.


In order to improve QA systems performance many research focus on different structures such as question processing (Huang et al., 2008), information retrieval (Clarke et al., 2006), information extraction (Saggion and Gaizauskas, 2006), textual entailment (TE) (Harabagiu and Hickl, 2006) for ranking, answer extraction, etc. Our QA system has a similar pipeline structure and implements a new TE module for information extraction phase of the QA task.


