While temporal transition rules can also be captured with an Integer Linear Programming approach (Chambers and Jurafsky, 2008), Markov Logic has at least two advantages.


Moreover, our global Markov Logic 14See (Chambers and Jurafsky, 2008) for a detailed discussion of this problem, and a possible solution for it.


In order to repair the contradictions that the local classifier predicts, Chambers and Jurafsky (2008) proposed a global framework based on Integer Linear Programming (ILP).


By contrast, in a Local Classifier + ILP-based approach as followed by Chambers and Jurafsky (2008) it is less clear how to proceed in the case of soft rules.


Most previous work on temporal relation identification (Boguraev and Ando, 2005; Mani et al., 2006; Chambers and Jurafsky, 2008) is based on the TimeBank corpus.


