4 From document normalization to ITU A first route towards achieving an ITU system is through an extension of ongoing work on document normalization [Max and Dymetman 2002, Max 2003]. 
Details on the implementation using MDA grammars have been described elsewhere (Max, 2003a; Max, 2003b). 
Our approach to normalize documents has been described in (Max, 2003b). 
2.1 Finding candidate document representations: fuzzy inverted generation The MDA grammar used is flrst precompiled oine by a separate tool, in order to associate proflles of text descriptors to semantic objects and types in the grammar (see (Max, 2003b) for details). 
Also, a corpus study of drug lea ets that we conducted (Max, 2003a) showed that documents from the same class of documents could contain a lot of variation, which can hamper the readers understanding. 
