For example, Dickinson and Meurers (2003) used variation to describe POS (Part-of-Speech) inconsistency in an annotated corpus. 
The idea that variation in annotation can indicate annotation errors has been explored to detect errors in part-of-speech (POS) annotation (van Halteren, 2000; Eskin, 2000; Dickinson and Meurers, 2003a) and syntactic annotation (Dickinson and Meurers, 2003b). 
In Dickinson and Meurers (2003), contexts are composed of words, and identity of the context is required. 
The difference in PoS tags between the strings is called a variation and the word(s) exhibiting the variation is called a variation nucleus (Dickinson and Meurers, 2003). 
In this paper we discuss how the variation n-gram error detection approach (Dickinson and Meurers, 2003a) can be extended to discontinuous structural annotation. 
