In this approach (Gardent and Kallmeyer, 2003), the TAG used integrates syntactic and semantic information as follows. 
To associate semantic representations with natural language expressions, the FTAG is modified as proposed in (Gardent and Kallmeyer, 2003). 
The semantic formula and the tree are distinct objects but in the approach to semantic construction described in (Gardent and Kallmeyer, 2003), they share some semantic indices. 
This module assumes a TAG of the type described in (Gardent and Kallmeyer, 2003; Gardent, 2006) 5ThecorrespondingsystemiscalledSemConst(cf section 6). 
To associate semantic representations with natural language expressions, the FTAG is modified as proposed in (Gardent and Kallmeyer, 2003). 
