We use a bootstrap approach in which we first extract 1-to-n word alignments using an existing word aligner, and then estimate the confidence of those alignments to decide whether or not the n words have to be grouped; if so, this group is conwould thus be completely driven by the bilingual alignment process (see also (Wu, 1997; Tiedemann, 2003) for related considerations). 
Tiedemann (2003) introduced a word alignment approach based on combination of association clues. 
We have used the Uplug word alignment system (Tiedemann 2003a), for the creation of the dictionaries. 
2 Word alignment with clues The clue alignment approach has been presented in (Tiedemann, 2003). 
We have used the Uplug word alignment system (Tiedemann 2003a), for the creation of the dictionaries. 
