end for Bootstrapping was previously used by (Carreras et al. , 2003), who were interested in recognizing Catalan names using Spanish resources. 
5 Using Spanish resources In this section we extend our previous work on NE recognition (Carreras et al. , 2003) to obtain a bilingual NE classification model. 
Carreras et al. presented results of a NER system for Catalan using Spanish resources (Carreras et al. , 2003a). 
The strategy used for training the bilingual NE classification models has been also applied with good results to NE recognition in (Carreras et al. , 2003), a work that can be considered complementary to this one. 
They have been used in some previous works allowing significant improvements for the Spanish NERC task (Carreras et al. , 2002; Carreras et al. , 2003). 
