As outlined in Penn and Haji-Abdolhosseini (2003), the predictive step from a state consisting of CWC6BNBVBNCACX using an immediate dominance rule, C6 BC AX C6 BD BMBMBMC6 CZ, with CZBQBD and no linear precedence constraints transits to a state CWC6 BD BNBVBNAUCX provided that C6 is compatible with C6 BC.


In the 2 Actually, Penn and Haji-Abdolhosseini (2003) use CanBV and OptBV, which can be defined as BVCPD2BUCE CK CACTD5BUCE.


If CWC6 CZ BNBV CZA0BD BNCA CZA0BD CX succeeds with CD CZ,then CWC6BNBVBNCACX succeeds with CD BD CJBMBMBMCJCD CZ . 11 2.3 Active Edge Subsumption Revisited So far, this is very similar to the strategy outlined in Penn and Haji-Abdolhosseini (2003).


10 Following Penn and Haji-Abdolhosseini (2003), we can characterize a search state under these assumptions using one non-terminal, C6,and two subsets/bit vectors, the CanBV and ReqBV.


