HPSG parsing with a CFG chunk parser A hybrid of deep parsing and shallow parsing was recently found to improve the efficiency of deep parsing (Daum et al. , 2003; Frank et al. , 2003; Frank, 2004). 
Similar results were reported in (Daum et al. , 2003) for integration of chunkand dependency parsing. 
(Foth and Hagenstrom, 2002; Daum et al. , 2003) showed that the correct balance between the new knowledge and the existing grammar is crucial for successful integration. 
5 Related work There are other approaches that combine shallow processing with deep parsing (Crysmann et al. , 2002; Frank et al. , 2003; Daum et al. , 2003) to improve parsing efficiency. 
This compares to a speed-up factor of 2.26 reported in (Daum et al. , 2003), by integration of PoS guidance into a dependency parser. 
