1.2 Related Work In one of the first efforts to enrich the source in word-based SMT, Ueffing and Ney (2003) used partof-speech (POS) tags, in order to deal with the verb conjugation of Spanish and Catalan; so, POS tags were used to identify the pronoun+verb sequence and splice these two words into one term.


71 6 Related Work The approach to deal with inflected forms presented in (Ueffing and Ney, 2003) is similar in that it also tackles verbs in an English  Spanish task.


Some address the generation challenge when translating from English into Spanish (Ueffing and Ney, 2003; de Gispert and Marino, 2008).


