Much research has been done on using parallel corpora to learn bilingual lexicons (Melamed, 1997; Moore, 2003).


The figure of merit considers the Model 1 scores of not only the words inside a given cell, but also all the words not included in the source and target spans, as in Moore (2003) and Vogel (2005).


For example, Moores work (Moore, 2003) uses a bilingual parallel aligned English-French corpora, and applying different statistical techniques, he obtains a French form for each English entity.


But besides using that data source, we decided also to resort to the web as a complementary data set too, as in (Moore, 2003).


The corpora can be parallel corpora [Moore et al., 2003] or contentaligned corpora [Kumano et al., 2004].


