One of the domains SUMTIME is working in is weather forecasts, and in this domain we acquired a corpus of 1119 weather forecasts (for off-shore oil rigs) written by five professional meteorologists (Sripada et al. , 2002; Sripada et al. , 2003b). 
We have published other papers that have summarised our key findings, notably variation between individuals (Reiter and Sripada, 2002a; Reiter and Sripada, 2002b); and also described the corpus itself (Sripada et al. , 2003b). 
Unfortunately in this domain, as in many other NLG applications (Reiter et al. , 2003), there is no existing corpus of manually written texts describing the input data. 
However, a preliminary analysis has suggested to us that we cannot conduct such an analysis until we remove non-physiological events from the data (Sripada et al. , 2003a). 
SUMTIME is also working on generating textual summaries of gas turbine sensor data (Yu et al. , 2003). 
