3 Experimental Classes and Verbs We use the same classes and example verbs as in the supervised experiments of Joanis and Stevenson (2003) to enable a comparison between the performance of the unsupervised and supervised methods. 
(Stevenson and Joanis, 2003) investigate the applicability of this general feature space to unsupervised verb clustering tasks. 
These are the same tasks performed in the supervised setting of Joanis and Stevenson (2003). 
In future work, it would be particularly interesting to compare empiricallyderived verb clusters to verb classes derived from theoretical considerations (Levin, 1993), and to the automated verb classification techniques that use these classes (Joanis and Stevenson, 2003). 
To overcome this drawback, (Joanis and Stevenson, 2003) develop a general feature space for supervised verb classification. 
