The codecs for MRS and Hole Semantics are based on the (non-trivial) translations in (Koller et al. , 2003; Niehren and Thater, 2003) and are only defined on nets, i.e. constraints whose graphs satisfy certain structural restrictions.


Hnc graphs are equivalent to chain-connected dominance constraints (Koller et al. , 2003), and areclosely relatedto dominance nets (Niehrenand Thater, 2003).


It shows the equivalence of a large fragment of MRSs and a corresponding fragment of normal dominance constraints, which in turn is equivalent to a large fragment of Hole Semantics (Bos, 1996) as proven in (Koller et al. , 2003).


The previous proof techniques for normal dominance constraints (Koller et al. , 2003) do not apply.


The requirement of hypernormal connections in islands replaces the notion of chain-connectedness in (Koller et al. , 2003), which fails to apply to dominance constraints with weak dominance edges.


