In addition, at least as far back as Rich Pitos 1992 tgrep, distributed with the Penn Treebank, computationally sophisticated linguists have had the option of looking at naturally occurring data rather than relying on constructed sentences and introspective judgments (e.g. , Christ, 1994; Corley et al. , 2001; Blaheta, 2002; Kehoe and Renouf 2002; Knig and Lezius, 2002; Fletcher 2002; Kilgarriff 2003).


