In order to solve this problem, we proposed an approach of taking bilingual news articles on Web news sites as a source for translation knowledge acquisition (Utsuro et al. , 2003). 
An additional boost can be achieved by retrieving content-related document pairs using CLIR techniques (Utsuro et al. , 2003). 
2.2 Cross-Language Retrieval of Relevant News Articles This section gives the overview of our framework of cross-language retrieval of relevant news articles from Web news sites (Utsuro et al. , 2003). 
3 We also applied another technique based on contextual vector similarities (Utsuro et al. , 2003), which First, we concatenate constituent Japanese articles of D i J into one article D primei J, and regard the article pair d i E and D primei J as a pseudo-parallel sentence pair. 
This technique is less eective than the one we describe here (Utsuro et al. , 2003). 
