But as Clark (2003) observes, this approach has several defects. 
We used Alexander Clarkes software,1 based on (Clark, 2003), to cluster the words, and then allow each word to be labeled with any part of speech tag seen in the data with any other word in the same cluster. 
The POS tags we use are induced by the unsupervised tagger of (Clark, 2003)3. 
2.3 Systems with Morphology Clark (2003) presents several part-of-speech induction systems which incorporate morphological as well as distributional information. 
1 Introduction and Motivation Category induction techniques generally rely on local contexts, i.e., surrounding words, to cluster word types together (e.g., Clark, 2003; Schutze, 1995), using information of a kind also found in human category acquisition tasks (e.g., Mintz, 2002, 2003). 
