The performance, shown in table 2, is, according to (Preiss, 2003), similar to a large selection of statistical parsers and a grammatical relation finder. 
These figures are more informative than overall Fscore (Preiss, 2003). 
Preiss (2003) compares the parsers of Collins (2003) and Charniak (2000), the GR finder of Buchholz et al. 
Such conversions have been performed for other parsers, including parsers producing phrase structure output (Kaplan et al. , 2004; Preiss, 2003). 
These results, slightly lower than state-of-the-art ((Lin, 1998), (Preiss, 2003)), are least merit figures or a proof of concept rather than accurate figures. 
