The earliest efforts in this direction are those of Zhao and Vogel (2002) and Utiyama and Isahara (2003).


Several researchers (Zhao and Vogel, 2002; Vogel, 2003; Resnik and Smith, 2003; Fung and Cheung, 2004a; Wu and Fung, 2005; Munteanu and Marcu, 2005) have shown how fairly good-quality parallel sentence pairs can be automatically extracted from comparable corpora, and used to improve the performance of machine translation (MT) systems.


In a subsequent publication, Vogel (2003) evaluates these sentences in the context of an MT system and shows that they bring improvement under special circumstances (i.e. , a language model constructed from reference translations) designed to reduce the noise introduced by the automatically extracted corpus.


