There is, however, also an increasing interest in the topic from both computational linguists and psycholinguists (e.g. Kaiser and Trueswell (submitted); Keller (2000); Kruiff and Duchier (2003); Pechmann et al.


Most recently, (Debusmann and Duchier, 2003) have presented a new formulation of dependency grammar which generalises multi-stratal approaches to an n-dimensional formalism of interacting dependency graphs.


The transformation, whose details we omit due to lack of space, closely follows previous work on axiomatising dependency parsing (Duchier, 2003) and includes the use of the selection constraint to efficiently handle lexical ambiguity.


Such new edges on SC could come from inferences with world or discourse knowledge (Koller and Niehren, 2000), scope preferences, or interactions with information structure (Duchier and Kruijff, 2003).


