Alterf (Rayner and Hockey, 2003) extends the paradigm to 30 ID Rec Features Classifier Error rates Classification Task In domain Out Av Good Bad 1 SLM Confidence Threshold 5.5% 59.1% 16.5% 11.8% 10.1% 2 GLM Confidence Threshold 7.1% 48.7% 8.9% 9.4% 7.0% 3 SLM Confidence + Lexical Linear SVM 2.8% 37.1% 9.0% 6.6% 7.4% 4 GLM Confidence + Lexical Linear SVM 2.8% 48.5% 8.7% 6.3% 6.2% 5 SLM Confidence + Lexical Quadratic SVM 2.6% 23.6% 8.5% 5.5% 6.9% 6 GLM Confidence + Lexical Quadratic SVM 4.3% 28.1% 4.7% 5.5% 5.4% Table 2: Performance on accept/reject classification and the top-level task, on six different configurations.


4 ALTERF ALTERF (Rayner and Hockey, 2003) is another Open Source toolkit, whose purpose is to allow a clean combination of rule-based and corpus-driven processing in the semantic interpretation phase.


The issue of combining rule-based and data-driven approaches has received less attention, with the exception of a few (Wang et al. , 2000; Rayner and Hockey, 2003; Wang and Acero, 2003).


In a recent paper (Rayner and Hockey, 2003), the authors address this issue by employing a decision-list-based speech understanding system as a means of progressing from rule-based models to data-driven models when data becomes available.


This has lead to the idea of trying to combine both approaches, as shown in (Rayner & Hockey, 2003).


