A number of interaction-management techniques are present in the current implementation, including: a0 A back-up recognition pass, using statistical processing to extend grammar-based coverage and provide immediate user  help feedback for unrecognized utterances (Hockey et al., 2003); a0 Turn management timing of system output is governed by monitoring the speech channel and the (prioritized) agenda of speech outputs.


For full details of the evaluation see (Hockey et al., 2003).


Following prior research (Gorrell et al. , 2002; Hockey et al. , 2003), we sought to improve partial recognitions so that the system could provide feedback to users on what was recognized, and to encourage them to stay within the C&C syntax.


3.5 Related research In related research, several researchers have investigated using both a CFG and a domain-trained SLM simultaneously for recognition (Gorrell et al. , 2002; Hockey et al. , 2003).


