The present state of the Szeged Corpus (Alexin et al. , 2003) is the result of three national projects and the cooperation of the University of Szeged, Department of Informatics, MorphoLogic Ltd. Budapest, and the Research Institute for Linguistics at the Hungarian Academy of Sciences.


Later, as the Hungarian National Corpus (V aradi, 2002) and the Manually Annotated Hungarian Corpus (the Szeged Corpus) (Alexin et al. , 2003) became available, an opportunity was provided to test the results on bigger corpora (153M and 1.2M words, respectively).


