W03-1007:1	87:203	We use the YASMET MEtagger (Bender et al. , 2003) to perform the Viterbi search.
---------------------------------------------------
N03-2008:2	43:81	The YASMET MEtagger was used to apply an ngram tag model to the classification task (Bender et al. , 2003).
---------------------------------------------------
W06-2606:3	95:179	(Bender et al. , 2003).
---------------------------------------------------
W06-2606:4	10:179	As methodologies deriving well-formedness of a sentence we use supertagging (Bangalore and Joshi, 1999) with lightweight dependency analysis (LDA)1 (Bangalore, 2000), link grammars (Sleator and Temperley, 1993) and a maximumentropy (ME) based chunk parser (Bender et al. , 2003).
---------------------------------------------------
W06-2606:5	87:179	For the experiments, we apply a maximumentropy based tagger which has been successfully evaluated on natural language understanding and named entity recognition (Bender et al. , 2003).
---------------------------------------------------
C04-1179:6	114:187	For testing, we use the YASMET MEtagger (Bender et al. 2003) to perform the Viterbi search for choosing the most probable tag sequence for a sentence using the probabilities from training.
---------------------------------------------------
W04-0832:7	17:94	We use the YASMET MEtagger (Bender et al. 2003) to perform the Viterbi search for choosing the most probable tag sequence for a sentence using the probabilities computed during training.
---------------------------------------------------
