(2000); Piwek (2003) uses personality variables to affect the linguistic behaviour of conversational agents, but they did not systematically manipulate parameters, and their generators were not evaluated.


A distinct line of research has explored methods for automatically generating language that varies along personality dimensions, targeting applications such as computer gaming and educational virtual worlds (Andre et al. , 2000; Isard et al. , 2006; Loyall and Bates, 1997; Piwek, 2003; Walker et al. , 1997) inter alia.


While handcrafted rule-based approaches are limited to variation along a small number of discrete points (Hovy, 1988; Walker et al., 1997; Lester et al., 1997; Power et al., 2003; Cassell and Bickmore, 2003; Piwek, 2003; Mairesse and Walker, 2007; Rehm and Andre, in press), we learn models that predict parameter values for any arbitrary value on the variation dimension scales.


This is not only because some systems combine standard NLG with templates and canned text (Piwek 2003), but also because modern template-based systems tend to use syntactically structured templates and allow the gaps in them to be filled recursively (i.e. , by filling a gap, a new gap may result).


