My approach is closely related to work in statistical parsing known as Data-Oriented Parsing (DOP), an empirically highly successful approach with labeled recall and precision scores on the Penn Tree Bank that are among the best currently obtained (Bod, 2003). 
But equally important is the fact that this new DOP* model does not suffer from a decrease in parse accuracy if larger subtrees are included, whereas the original DOP model needs to be redressed by a correction factor to maintain this property (Bod 2003). 
Our best performing model is more accurate than all these previous models except (Bod, 2003). 
In other words, the Zollmann & Simaan method, and other methods that converge to the complete parse tree solution such as LS-DOP (Bod, 2003) and BackOff-DOP (Simaan and Buratto, 2003), are inconsistent in the weight-distribution test. 
This result is only slightly higher than the highest reported result for this test-set, Bods (.907) (Bod, 2003). 
