There have already been experimental machine translation systems MAGENTA (Hajic et al. , 2002) and DBMT ( Cmejrek et al. , 2003) confirming the exploitability of the corpus and showing that we are capable of performing automatic transformations from phrase structures to dependency representation with an acceptable, though still not impeccable quality.


Since there is no standard collection of texts used for benchmarking all MT systems, it is not clear how a system that achieves, e.g., BLEUr4n4 1 score 0.556 tested on 490 utterances selected from the WSJ (Cmejrek et al, 2003:89) may be compared to another system which achieves, e.g., the BLEUr1n4 score 0.240 tested on 10,150 sentences from the Basic Travel Expression Corpus (Imamura et al. , 2003:161).


Based on previous results (Al-Onaizan et al. , 1999; Cmejrek et al. , 2003), we expected that this transformation would lead to an improvement in translation quality due to reduction of data sparseness.


 Dependency-based Translation ( Cmejrek et al. , 2003): This model assumes a dependency parser for the foreign language.


