As shown in (Merlo, 2003; Merlo and Esteve-Ferrer, 2004) this difference does not correspond to the difference between arguments and adjuncts.


However, based on the previous experiments, which showed a limited amount of dependence between the two tasks, previous work on a similar data set (Merlo 2003), and general wisdom in machine learning, there is reason to believe that it is better to solve the four-way classification problem directly rather than first solving a more general problem and then specializing the classification.


In recent preliminary work, however, we have succeeded in distinguishing arguments from adjuncts using corpus evidence (Merlo and Leybold 2001; Merlo 2003).


