One way to approach this discrepancy is to assume a preceding phase of morphological segmentation for extracting the different lexical items that exist at the token level (as is done, to the best of our knowledge, in all parsing related work on Arabic and its dialects (Chiang et al., 2006)).


2 Related Work This paper is part of a larger investigation into parsing Arabic dialects (Rambow et al. , 2005; Chiang et al. , 2006).


