Indeed, the dialogue community has been addressing the problem of information seeking for decades, often with very satisfying commercial products able to interact not only in text but especially via spoken interfaces (Gupta et al., 2006; Traum, 1996).


In particular, the problem of addressing definition questions has received great attention from the research community (Chen et al., 2006; Moschitti et al., 2007), while less research has been conducted so far on other types of non-factoid QA, such as whyquestions (Verberne et al., 2007; Pechsiri et al., 2008) and procedural (also called how-to) questions (Yin, 2006; Delpech and Saint-Dizier, 2008).


