Birke and Sarkar (2006) also used WSD. 
Current state of art in metaphor detection therefore tends to be localistic  the distributional profile of the target word in its immediate grammatical or collocational context in a background corpus or a database like WordNet is used to determine metaphoricity (Mason, 2004; Krishnakumaran and Zhu, 2007; Birke and Sarkar, 2006; Gedigian et al., 2006; Fass, 1991). 
However, there hasbeen a growing interest in idiom token identification in recent times (Katz and Giesbrecht, 2006; Hashimoto et al., 2006b; Hashimoto et al., 2006a; Birke and Sarkar, 2006; Cook et al., 2007). 
We will also investigate the use or adaptation of other researchers automated detection/mining techniques (e.g. Birke and Sarkar, 2006; Gedigian et al., 2006). 
Birke and Sarkar (2006) requires WordNet. 
