E09-1013:1	42:247	The size of the context windowalsovaries,itcanbearelativelysmall,suchas two words before and after the target word (Gauch and Futrelle, 1993), the sentence within which the targetisfound(Bordag,2006),orevenlarger,such as the 20 surrounding words on either side of the target (Purandare and Pedersen, 2004).
---------------------------------------------------
W06-3812:2	174:195	To judge results, the methodology of (Bordag, 2006) is adopted: To evaluate word sense induction, two sub-graphs induced by the neighborhood of different words are merged.
---------------------------------------------------
W06-3812:3	181:195	% (Bordag, 2006) Chinese Whispers POS P R rP rR P R rP rR N 87.0 86.7 90.9 64.2 90.0 79.5 94.8 71.3 V 78.3 64.3 80.2 55.2 77.6 67.1 87.3 57.9 A 88.6 71.0 88.0 65.4 92.2 61.9 89.3 71.9 Table 3: Disambiguation results in % dependent on word class (nouns, verbs, adjectives) % (Bordag, 2006) Chinese Whispers freq P R rP rR P R rP rR high 93.7 78.1 90.3 80.7 93.7 72.9 95.0 73.8 med 84.6 85.2 89.9 54.6 80.7 83.8 91.0 55.7 low 74.8 49.5 71.0 41.7 74.1 51.4 72.9 56.2 Table 4: Disambiguation results in % dependent on frequency Results (tables 3 and 4) suggest that both algorithms arrive at about equal overall performance (P and R).
---------------------------------------------------
N07-3010:4	68:83	Clustering this graph with CW and regarding clusters as senses, this method yields comparable results to Bordag (2006), tested using the unsupervised evaluation framework presented there.
---------------------------------------------------
