The corpora will be demonstrated in the main EACL conference (Baroni and Kilgarriff 2006).


1.2 Experiments We experimented with the 100M-word BNC2, 1Bword Oxford English Corpus3 (OEC), and 1.9Bword Itwac (Baroni and Kilgarriff, 2006).


Automatically compiled Web corpora have become increasingly popular in recent years and have been used for many different purposes (Kilgarriff and Grefenstette, 2003; Baroni and Bernardini, 2006).


