For MWTs of length a3 , (Robitaille et al., 2006) produce all the combinations of shorter multi-word unit elements of a length less than or equal to a3 . For 97 example, the French MWT syndrome de fatigue chronique (chronic fatigue disorder) yields the following four combinations: i) a36syndrome de fatigue chroniquea37, ii)a36syndrome de fatiguea37a38a36chroniquea37, iii) a36syndromea37a39a36fatigue chroniquea37 and iv) a36syndromea37 a36fatiguea37a40a36chroniquea37.


chronique fatigue a23a33a24a16a26a34a28 a12a14a13 a29a16a30 a12a14a13 a23a33a24a16a26a34a28 a12a33a15 a29a16a30 a12a33a15 a23a33a24a16a26a34a28 a17a19a18 a29a16a30 a17a19a18 a23a33a24a16a26a34a28 a20a35a21 a29a16a30 a20a35a21 Table 1: Illustration of the compositional method (the underlined Japanese MWT actually exists) This approach also differs from that used by (Robitaille et al., 2006) for French-Japanese translation.


For an MWT of length a25, (Robitaille et al. , 2006) produce all the combinations of MWU elements of a length less than or equal to a25 . For example, the French term syndrome de fatigue chronique (chronic fatigue disease) yields the following four combinations: i) a27syndrome de fatigue chroniquea28, ii) a27syndrome de fatiguea28a29a27chroniquea28, iii) a27syndromea28a30a27fatigue chroniquea28 and iv) a27syndromea28 a27fatiguea28a31a27chroniquea28 . We limit ourselves to the combination of type iv) above since 90% of the candidate terms provided by the term extraction process, after clustering, are only composed of two content words.


This approach differs from that used by (Robitaille et al. , 2006) for French/Japanese translation.


