Recently, confusion-network-based system combination algorithms have been developed to combine outputs of multiple machine translation (MT) systems to form a consensus output (Bangalore, et al. 2001, Matusov et al., 2006, Rosti et al., 2007, Sim et al., 2007). 
So far, confusion networks have been applied in MT system combination using three different alignment procedures: WER (Bangalore et al. , 2001), GIZA++ alignments (Matusov et al. , 2006) and TER (Sim et al. , 2007). 
word-based combination techniques using confusion networks (Matusov et al., 2006; Sim et al., 2007; Rosti et al., 2007b). 
4 System combination For system combination we used the approach described in (Matusov et al., 2006). 
The recent approaches used pair-wise alignment algorithms based on symmetric alignments from a HMM alignment model (Matusov et al., 2006) or edit distance alignments allowing shifts (Rosti et al., 2007). 
