This procedure was described in some detail elsewhere (Zuidema, 2006b); here I only sketch the basic idea.


Zuidema (2006a) shows that also the estimator (Bod, 2003) uses is biased and inconsistent, and will, even in the limit of in nite data, not correctly identify many possible distributions over trees.


In Zuidema (2006b) we give a qualitative analysis of the subtrees with the highest scores as induced from the ATIS treebank, which include many of its frequent constructions including show me NP, I would like NP, ights from NP to NP.


We refer to Zollmann and Sima'an (2005) for a recently proposed estimator that is statistically consistent (though it is not yet known how this estimator performs on the WSJ) and to Zuidema (2006) for a theoretical comparison of existing estimators for DOP.


In (Zuidema, 2006) we evaluate existing estimation methods for Data-Oriented Parsing, and show that they are ill-suited for learning tasks such as studied in this paper.


