E09-1041:1	58:242	Kozareva (2006) generates gazetteer lists for person and location names from unlabeled data using common patterns and a graph exploration algorithm.
---------------------------------------------------
I08-7002:2	52:231	Kozareva (2006) described a methodology to generate gazetteer lists automatically for Spanish and to build NER system with labeled and unlabeled data.
---------------------------------------------------
P09-1050:3	233:239	We have also illustrated that ASIA outperforms three other English systems (Kozareva et al., 2008; Pasca, 2007b; Snow et al., 2006), even though many of these use more input than just a semantic class name.
---------------------------------------------------
P09-1050:4	113:239	3.4 Bootstrapper Bootstrapping (Etzioni et al., 2005; Kozareva, 2006; Nadeau et al., 2006) is an unsupervised iterative process in which a system continuously consumes its own outputs to improve its own performance.
---------------------------------------------------
