Our feature set incorporates information which has proven useful in meeting segmentation (Galley et al., 2003) and the task of detecting addressees of a specific utterance in a meeting (Jovanovic et al., 2006).


However, this results in a very skewed class distribution because the next speaker is the intended addressee 41% of the time, and 38% of instances are plural the 3Addressee annotations are not provided for some dialogue act types see (Jovanovic et al., 2006b).


While there is an increasing body of work concerning addressee identification (Katzenmaier et al. , 2004; Jovanovic et al. , 2006), there is very little investigating the problem of second-person pronoun resolution, and it is this that we address here.


