This small corpus of transcribed spoken human-machine dialogues in the domain of hotel/restaurant/bar search is gathered using the TownInfo tourist information system (Lemon et al., 2006).


The domaingeneral DM was mostly abstracted from the TALK system (Lemon et al., 2006).


This is a domain-neutral abstraction of the ISU dialogue managers implemented for the FLIGHTS and TALK systems (Moore et al. , 2004; Lemon et al. , 2006).


