Recently, Verberne (2006; 2007a)has been intensivelyworkingon whyQA based on the Rhetorical Structure Theory (RST) (Mann and Thompson, 1988).


1 Introduction Following the trend of non-factoid QA, we are seeing the emergence of work on why-QA; e.g., answering generic why X? questions (Verberne, 2006).


However, there are other relations, such as purpose, that may also be related to causality (Verberne, 2006).


