Characterlevel models have successfully been used for namedentity recognition (Klein et al., 2003), predicting authorship (Keselj et al., 2003; Stamatatos, 2006), text categorization (Zhang and Lee, 2006), web page genre identification (Kanaris and Stamatatos, 2007), and sentence-level subjectivity recognition (Raaijmakers and Kraaij, 2008) In spoken-language data, Hsueh (2008) achieves good results using chains of phonemes to automatically segment meetings according to topic.


While progress has been made on recognizing primarily objective meeting content, for example, information about the topics that are discussed (Hsueh and Moore, 2006) and who is assigned to work on given tasks (Purver et al., 2006), there has been 1This work was supported by the Dutch BSIK-project MultimediaN, and the European IST Programme Project FP60033812.


2 Segmentation While much work in dialogue segmentation centers around topic (e.g. Galley et  al. 2003, Hsueh et al. 2006, Purver et al. 2006), we decided to examine dialogue at a more finegrained level.


Practical applications of topic segmentation typically relate to more informal documents such as blogs or speech transcripts (Hsueh et al., 2006), as formal texts such as books already contain segmentation markings provided by the author.


