(Foster and Oberlander, 2006).


In a previous study using the same video recordings but a different, simpler scheme (Foster and Oberlander, 2006), facial displays could only be associated with single leaf nodes (i.e. , words); that is, in the terminology of Ekman (1979), all motions were considered to be batons rather than underliners.


FosterandOberlander (2006), intheirstudyof facial gestures, have also noted that humans do not mind and indeed in some cases prefer variation, whereas corpus-based evaluations give higher ratings to systems which follow corpus frequency.


