Computationally, it is possible to describe the grammar and heuristic rules for these constraints by ATN networks, logic grarnmars~ HPSG~ and categorical grammars(Kosy, 1986; Fong and Berwick, 1985; Huang, 1984; Boguraev et al. , 1983; Blackwell, 1981; Niimi et al. , 1986).


2 Problems of the conjunctions Coordinate conjunctions for MT systems present three difficulties(Kosy, 1986; Huang, 1983; Niimi et al. , 1986; Okumura et ai.


