Academic Press (1976) pp 27-55 \[Chomsky 82\] Chomsky N. "Some Concepts and Consequences of the Theory of Government and Binding" Linguistic Inquiry monograph, N  6 Cambridge, Mass. , MIT Press (1982) \[Corbett & Chang 83\] Corbett A.T et Chang F.R Disambiguation : Accessing potentials antecedents" Memory And Cognition 11(3), pp 283-294 (1983) "P'fonoun \[Danlos 85\] Danlos L. Gdndration automatique de Texte en Langage Naturel Masson (1985) \[Ducrot 72\] Ducrot O. Dire et ne pas Dire Hermann (1972) \[Firbas 64\] Firbas J "on defining the theme in functionnal sentence analysis" Travaux linguistiques de Prague, 1 Prague 64 \[Garrod & Sanford 85\] Garrod S. et Sanford A.J "On the Realtime Character of Interpretation during Reading" Language and Cognitive Processes Vol NI, pp 43-59 (1985) \[Grosz, Joshi & Weinstein 87\] Grosz B. , Joshi A.K et Weinstein S. "Towards a Computational Theory qI~ Discourse Interpretation" Preliminary Draft \[Guenthner & Lehmann 83\] Guenthner F. et Lehmann tt.


Kamp (1981) and Guenthner and Lehmann (1983).


Guenthner and Lehmann (1983) use a similar salience ranking of grammatical roles to formulate rules of anaphora resolution.


