Jacobs notes that other systems ~ have shared at least part of the linguistic information for parsing and generation; for instance, the HAM-ANS \[Wahlster et al. , 1983\]'a;nd VII~-LANG \[Steinacker and Buchberger, 1983\] systems utilize the same lexical information for both tasks.


The VIE-LANG system (Steinacker and Buchberger 1983) shares a "syntacticosemantic" lexicon, but the generator accesses this lexicon using a discrimination net with specialized choice knowledge.


