The LFG parser of the kind used in BUILDRS has already been discussed in detail by Frey and Reyfe (1983), Frey (1985) and Reyle (1985).


Frey, W. , and U. Reyle, (1983) "A PROLOG Implementation of Lexical Functional Grammar as a Base for a Natural Language Processing System".


It is therefore not surprising that F. Pereira (1981), W. Frey and U. Reyle (1983), L. Karttunen (1985) and J. Calder et al.


