Brodda, 1983, Kfillgren, 1984a, Kfillgren, 1984b and Brodda, 1988), it is still in surface oriented analysis (not necessarily confined to the word level) that its virtues become most apparent, although it may be used also for traditional parsing, traditional morphological analysis, etc. During the years 1980-88 further development of the program was done oll a DEC 10 computer, and a version called BetaText eventually emerged, which had several features specifically aimed at facilitating "corpus work", i.e. the processing and/or analysis of text corpora of the Brown, London-Oslo-Bergen, l.xmdon-Lund types (cf.


K~illgren 1984a,b,1990, Brodda 1983).


