We shall consider them in turn: 2.1.1 Monolingual lexicons We assume a static or relational conception of morphology, along the lines of Jackendoff (1975), Wehrli (1985).


INTRODUCTION For highly Inflexlonal languages, encoding all word forms Into a word lexicon (declarative morphology approach) appears to be a poor solution not only due to a great redundancy (which for some languages is prohibitive (Japplnen,t983)) but also with respect to some theoretical aspects (as for Instance descriptional adequacy (Wehrli,1985)).


