Work on incremental parsing and interpretation is typically motivated by a desire to model, or mimic, (aspects of) this behaviour, for example, Bobrow and Webber (1980), Ades and Steedman (1982), Mellish (1985), Pulman (1985), and Haddock (1987~ 1988~ 1990).


The first sense stresses that input should be analysed in a piecemeal fashion, for example Bobrow and Webber (1980), Mellish (1985), Pulman (1085, 1987), Hirst (1987), Haddock (1987).


