These kinds of considerations fit nicely inside a probabilistic formulation of the problem (Beale 1985; Garside and Leech 1985), which offers the following advantages:  a sound theoretical framework is provided  the approximations are clear  the probabilities provide a straightforward way to disambiguate  the probabilities can be estimated automatically from data.


Though several studies with similar objectives have been reported \[Church, 1988\], \[Zernik and Jacobs, 1990\], \[Calzolari and Bindi, 1990\], \[Garside and Leech, 1985\], \[Hindle and Rooth, 1991\], \[Brown et al. , 1990\], they require that sample corpora be correctly analyzed or tagged in advance.


The methodology is a simple version of Garside and Leech's probabilistic parser (1985).


