McDonald & Pustejovsky (1985a) "SAMSON: a computational theory of prose style in generation", Proceedings of the 1985 meeting of the European Association for Computational Linguistics.


The processor, on the other hand, must be constructed so that it can accommodate lexical gaps by being able to build the most appropriate phrase to insert in the slot for which no single lexical unit can be selected (perhaps, along the lines of McDonald and Pustejovsky, 1985a).


Thus, MUMBLE concentrates on gr:~mmar-intensive control decisions (McDonald and Pustejovsky, 1985a) and some stylistic considerations (McDonald and Pustejovsk'y, 1985b); TEXT (McKeown, 1985) stresses the strategical level of control decisions about the overall textual shape of the generation output.


These discrimination nets are distinct from the choosers in NIGEL's choice systems, where grammatical knowledge is not systematically separated from the lexical semantic knowledge (for a discussion of problems inherent in this approach see McDonald, Vaughau and Pustejovsky, 1986); the pragmatic nature of some of the tests, as well ms the fine level of detail of knowledge representation is what distinguishes our approach from previous conceptual generators, notably PHRED (Jscobs, 1985)).


In McDonald and Pustejovsky (1985b) a heursitic was given for deciding when to generate a full NP and when a pronoun.


