The development of CLOCKWISE is part of the grammar development project in the LINLIN project at LinkSping University (/Ahrenberg 1987/).


A more interesting fact is that we often need an understanding of context in order to get at the information which is relevant for determining the referent /Moore, 1981; Ahrenberg a 1987a,b; Pulman, 1987/.


14 string c structure f structure d-structure content structure LEXICAL-FUNCTIONAL GRAMMAR MORPH DICTIONARY LEXEME \] DICTIONARY g PROTOTYPES ) DISCOURSE i STATE Figure 1: Structural aspects and their correspondencaL The ideas presented here have been partially implemented in a system called FALIN, which is developed as a precursor to an understanding component of a dialog system (Ahrenberg, 1987a).


