(Rnsso, 1987), M. Russo, "A generative grammar approach for the morphologic and morphosyntactic analysis of the Italian langnage" (1987).


2.1 Morphology The morphologic analyzer (Marziali, 1992) derives from the work on a generative approach to the Italian morphology (Russo, 1987), first used in DANTE, a NLP system for analysis of short narrative texts in the financial domain (Antonacci et al. 1989).


The hypothesis of hand-entering a type hierarchy would not require an unreasonable amount of time, because the task is comparable to entering a morphologic lexicon (Russo 1987).


158 Velardi et al. Encoding Semantic Knowledge example 1 from (Velardi 1988) agreement = is_a decision_act participant person, organization theme transaction cause communication_exchange manner interesting important effective  example 2 from (Niremburg 1987): person = isa creature agent_of take put find speech-action mental-action consist_of hand foot source_of speech-action destination_of speech-action power human speed slow mass human Figure 2 Examples of collocative meaning representation in the literature 4.1 What Is Given The input to the system is: . a list of syntactic collocates, e.g. subject-verb, verb-object, noun-preposition-noun, noun-adjective, etc. extracted through morphologic (Russo 1987) and syntactic analysis of the selected corpus.


Once a good morphologic analyzer is available (the one used in our work is very well tested, and has first described in (Russo,1987)), problems such as verb detection, raised in (Brent, 1991), are negligible.


