we make use of a substantial lexical database of English derived from machine-readable versions of the Longman Dictionary of Contonporary English (see Boguracv et aL, 1987; Boguraev & Briscoe, 1989) and of the Medical Research Council's psycholinguistic database (Wilson, 1988), which incorporates word frequency information.


In addition, a fully flexible access system allows the retrieval of dictionary entries on the basis of constraints specifying any combination of phonetic, lexical, syntactic, and semantic information (Boguraev et al. , 1987).


The research described below is taking place in the context of three collaborative projects (Boguraev, 1987; Russell et al. , 1986; Phillips and Thompson, 1986) to develop a general-purpose, wide coverage morphological and syntactic analyser for English.


More recently, a dictionary server, of the kind described by Kay (1984b), was implemented and installed as a background process on a Xerox workstation networked together with the rest of the equipment dedicated to natural language processing applications (Boguraev et al. , 1987).


