/Appelo, et al. 1987/), GETA (cf. 
Rosetta tackles this problem by distinguishing between rules that are significant with respect to the composRionality of translation, so-called meaningful rules, and rules that are not, referred to as transformations (Appelo et al. 1987); in this way the system is not compositional in the strict sense anymore. 
Suggestions for grammar constraints in the form of termination conditions for parsing and generation are given in Appelo et al.(1987). 
6 Other examples of basing MT on state of the art CL methods and theories include the use of situation schemata as the basis for translation Rupp (1989), defining transfer over 'quasi logical forms' developed at SRI, Cambridge (Alshawi et al. , 1991) and derivation trees of a Montague style (Landsbergen, 1987 & Appelo, et al. , 1989). 
Appelo et al.(1987) introduces some extensions of the formalism, which make it possible to assign more structure to an M-grammar. 
