Baschung et al. 1987 present a UCG treatment with a more restricted coverage which considers objeet citrics as functors taking (on their right) a verb expecting an NP (or PP) argument on its right and returning a more saturated verb.


The xesulting, computationally efficient, system provkles an explicit tbmml fi'amework fbr linguistic description, within which large grammar ti'agnrents lbr French (Baschung et al. 1987) and F.nglish (Calder, Moens and Jmevat 1986) have already been developed.


(1987), Baschung et al.


