These algorithms may also consult input symbols from left to right, but the processing that takes place to the right of some position i does not strictly depend on the processing that has taken place to the left of i. Examples are pure bottom-up methods, such as left-corner parsing without topdown filtering (Wiren, 1987).


Parsing goes basically bottom-up, with top-down confirmation, with an improvement of the so-called left corner technique, a version of which is referred to in Wiren (1987).


Wiren (1987) compares a number of proposals.


