C88-1066:1	7:100	The CCR formalism The CCR formalism, introduced in Kilbury (1986, 1987), has its origin in Generalized Phrase Structure Grammar (GPSG; cf Gazdar et al. 1985, henceforth 'GKPS') and is a special type of unification grammar (cf Shieber 1986).
---------------------------------------------------
C88-1066:2	96:100	See Wir~n (1987) fk)r a discussion of such top-down filtering and of" the advantages of a modification of the Earley p~dictor proposed in Kilbury (1985).
---------------------------------------------------
C88-1066:3	12:100	Although it is not intended as a vehicle for the implementation of other grammar formalisms, it is 'tooloriented' in the sense of Shieber (1986) in that it provides a clearer picture of the relation GPSG has to other formalisms (cf Kilbury 1987).
---------------------------------------------------
C88-1066:4	35:100	For the corresponding notion of' unification and for the analysis of" LP statements as CCRs see Kilbury (1987); the reformulation of" I,P,';tatements will be omitted in the following sections.
---------------------------------------------------
