Tile formalism was first introduced in (Black et al. , 1987), was adapted by (Ruessink, 1989), and an extended version of it was proposed for use in the European Commission's ALEP language engineering platform (Pulman, 1991).


These are detailed more fully in (Black et al. , 1987, pp.


For example, spies and spy+s may be partitioned as follows: s p y + ss p ie epsilon1 s The partition-based approach was rst proposed by (Black et al. , 1987) and further improved by (Pulman and Hepple, 1993) and (Grimley-Evans et al. , 928 1996).


3.3 Previous Formalisms \[Black et al. 1987\] pointed out ttmt previous two-level rules ((cf.


