The idea is similar to Finkler and Neumann (1988), though simplified for our purposes; Carter (1989) in his VEX system also uses the method of giving sunple questions to the user (supposedly non-linguist) to learn about word's behaviour, but it is for English and primarily intended for assigning syntax properties rather than morphological.


The default methods, all of which may be switched on or off using system commands, supply facilities for inferring entries through access to an external machine-readable dictionary; for defining sequences of capitalized tokens as proper names; for spelling correction (described in detail in the next section); and for interacting with the user who may suggest a replacement word or phrase or enter the VEX lexical acquisition subsystem (Carter, 1989) to create the required entries.


