It may be appropriate, for example in morphology, to use an auxiliary lexicon (Ritchle et al. 1987; Ritchie 1989) which allows to discard certain translation results.


Indeed, this method, which was successfully applied to morphologically rich natural languages (Koskenniemi 1983), Is based upon a two-level rule formalism for which there exist a way to compile them into the language of finite state automata (FSA) (Ritchie 1989).


We shall ignore this issue here (but see Ritchie 1989 and Ritchie et al. 1991 for a formal statement of two possible lexical interfaces).


The usual assumed interface to a lexicon (e.g. Koskenniemi 1983a, 1983b; Karttunen 1983) is via sublexicons for different lexeme classes, with cross-pointers indicating allowable sequences of lexemes (a formal definition of this can be found in Ritchie 1989).


(This is a slight generalization of the presentation in Ritchie 1989).


