See also Johnson and Rosner (1989) for a description of the earlier UD system on which ELU is based. 
This resulted in formalisms as, for example, (Johnson and Rosner, 1989), (Emele and Zajac, 1990), (DSrre and Dorna, 1993) and (Carpenter, 1992). 
This grammar is primarily intended to be one of the components of a machine translation system built using ELU, 1 an enhanced PATR-II style unification grammar linguistic environment based on the LID system described in Johnson and Rosner (1989), but it is also part of our more general experimentation with fully reversible grammars. 
See also Johnson and Rosner (1989) for a description of the earlier UD system on which ET.u is based. 
This gives the possibility to define more general relations, and in particular functions can be defined in a way similar to, for example, (Johnson and Rosner, 1989) and (Emele and Zajac, 1990). 
