The grouping of these referents may depend on many factors: it may be explicit if they were syntactically coordinated or juxtaposed or implicit if they just share common semantic features (Eschenbach et al. , 1989).


Eschenbach et al. 1989 and 1990).


2 The SYNPHONICS Conceptualizer The conceptual input into the Formulator in short: CS for "conceptual structure" is represented in the RefO/RetN format (Habel 1982, 1986a/b; Eschenbach et al. 1989).


