The head-corner parser knows about strings and performs operations on them; in the types of grammars defined here these operations are replaced by general constraint-solving techniques (HShfeld and Smolka, 1988; Tuda et al. , 1989; Damas et al. , 1991).


The associated interpreter is a Prolog like topdown backtrack interpreter where term unification is replaced by more general constraintsolving techniques~, (HShfeld and Smolka, 1988; Tuda et aL, 1989; Damas et al. , 1991).


On the contrary, constraint unification (CU) (Hasida 1986, Tuda et al. 1989), a disjunctive unification method, makes full use of term unification advantages.


3 Constraint Unification and Its Problem This section explains constraint unification ~ (Hasida 1986, Tuda et al. 1989), a method of disjunctive unification, and indicates its disadvantage.


