W90-0102:1	9:162	Semantichead-driven generation (Shieber et al. , forthcoming; Calder et al. , 1989) uses semantic heads and their complements as a locus of semantic locality.
---------------------------------------------------
W91-0112:2	15:244	Some of the recent resea~h in this area is reported in (Calder et al. , 1989; Dymetman and Isabelle, 1988; Dymetman et al. , 1990; Estival, 1990; Hasida and Isizaki, 1987; Ishizaki, 1990; Shieber, 1988; Shieber et al. , 1990; Strzalkowski, 1990a-c; Strzalkowski and Peng, 1990; van Noord, 1990; and Wedekind, 1988).
---------------------------------------------------
W91-0105:3	4:280	given logical form & that are logically equivalent to ~ (see also (Shieber, 1988), (Calder et al. , 1989)).
---------------------------------------------------
W91-0105:4	105:280	So most of the currently developed generators and uniform algorithms assume more or less explictly an all-paraphrases strategy (e.g. , (Shieber, 1988), (Calder et al. , 1989), (Shieber et al. , 1989), (Dymetman et al. , 1990), (Emele and Zajac, 1990)).
---------------------------------------------------
P90-1028:5	7:186	1 INTRODUCTION Algorithms for tactical generation are becoming an increasingly important subject of research in computational linguistics (Shieber, 1988; Shieber et al. , 1989; Calder et al. , 1989).
---------------------------------------------------
P90-1028:6	69:186	Calder et al. conjecture that their algorithm "() extends naturally to the rules of composition, division and permutation of Combinatory Categorial Grammar (Steedman, 1987) and the Lambek Calculus (1958)" (Calder et al. , 1989, p. 23 ).
---------------------------------------------------
E91-1020:7	28:187	Recent work on semantic-head-driven generation \[Shieber et al. 1990, Calder et al. 1989, Noord 1990, Russell et al. 1990\] provides a very promising step towards efficient, goal-directed reconstruction of LF that is espescially suited for lexicon-centered grammar formalisms such as IIPSG or UCG.
---------------------------------------------------
C94-1078:8	107:131	2An instance of our head-corner generator (without an integrated treatment of movement) is the UCG-generator by Calder et al. \[Calder et al. , 1989\] (modulo the use of unary category transformation rules) which relies, in addition, on the symmetry of syntactic and semantic head.
---------------------------------------------------
P91-1015:9	18:246	The semantic-head-driven generation strategy (van Noord, 1989; Calder ef al. , 1989; Shieber et al. , 1989; van Noord, 1990a; Shieber et al. , 1990) faces problems in case semantic heads are 'displaced', and this displacement is analyzed using threading.
---------------------------------------------------
P91-1015:10	48:246	The algorithm is closely related to head-driven generators (van Noord, 1989; Calder et al. , 1989; Shieber et al. , 1989; van Noord, 1990a; Shieber et ai.
---------------------------------------------------
W91-0103:11	79:255	For generation headdriven generators can be used (van Noord, 1989; Calder et al. , 1989; Shieber et al. , 1990).
---------------------------------------------------
W91-0103:12	95:255	The meta-interpreter defines a head-driven bottom-up strategy with top-down prediction (figure 2), and is a generalization of the head-driven generator (van Noord, 1989; Calder et al. , 1989; van Noord, 1990a) and the head-corner parser (Kay, 1989; van Noord, 1991).
---------------------------------------------------
W91-0103:13	8:255	Such an organization of a grammar is the starting point of a class of generation algorithms that have become popular recently (Calder et al. , 1989; Shieber et al. , 1989; Shieber el al. , 1990).
---------------------------------------------------
C92-2117:14	138:184	The appropriate preposition (<cite> = L I), is an element with 'identity semantics' (Calder et al. 1989), so its index is equated in the monolingual lexicon with that of its syntactic object.
---------------------------------------------------
C92-2117:15	40:184	1992 inference needed to compute one from the other is clearly undecidable in the general case for logics rich enough to represent linguistic meaning (Shieber, 1988), and intractable even in the simplest cases, with associativity and commutativity of conjunction (Calder et al. 1989).
---------------------------------------------------
