As other researchers have noted (Whittaker and Stenton 1989; Dahlback, J6nsson, and Ahrenberg 1993; Fraser and Gilbert 1991), when the WOZ simulations are convincing, they obtain data that are a more accurate predictor of actual human-computer interaction than human-human dialogues because speakers adapt to the perceived characteristics of their conversational partners.


2 Fundamentals in Evaluation 2.1 Linguistic Coverage A forward looking view of evaluation is offered by (Whittaker and Stenton, 1989).


In some cases, the resulting corpus provides training data for spoken language systems (Hirschman et al. 1993), is used as a target for improved systems (Moore, Lemaire, and Rosenblum 1996), or forms a test set for evaluating the performance of an existing natural language system (Whittaker and Stenton 1989; Hirschman et al. 1993).


In the Wizard-of-Oz (WOZ) approach, a human wizard simulates the behavior of a program interacting with a human to carry out a particular task in a particular domain (Dahlb~ick and Jonsson 1989; Hirschman et al. 1993; Oviatt and Cohen 1989; Whittaker and Stenton 1989).


