and has been exemplified by Kaplan, et al. , (1989) for LFG, Beaven etal. 
Kaplan et al (1989) extend this approach to Machine Translation by defining two translation functions "~ (between f-structures) and "~' (between semantic structures). 
1987\] who annotate contextfree rules of Lexical Functional Grammar with ftmctional as well as semantic descriptiotm, wlfich allows for the simultaneous construction of f-structures and situation schemata; an application to trmisfer has been proposed by \[I(APLAN ET AL. 1989\], where f-structures for different languages are simtdtm~eously built up. 
Kaplan et al (1989) allow multiple levels of representation to take part in the transfer relation. 
Constraint Based Approaches In this section, we will outline the approach to the translation of non-local reentrances proposed in Kaplan et al (1989). 
