domain (Catach 1984; Danlos et al. 1986; Koskenniemi 1983; Laporte 1988; Ritchle et al. 1987, Tufts 1989; V6ronls 1988) are based on the availability of local rules whose combination, either through direct interpretation or by being compiled, form the target transducer.


The PARADIGM system, described in Tufts (1989) and Tufis (1990) allows a novice user to informally teach the program how to (de)compose inflexionai word-forms, that is to enable the morphological processing by a natural language processor.


