The following is a detail of the syntactic feature hierarchy used for one type of linguistic sign in one of the grammars implemented in CLG(2): Sign = ( phon, syn, sem,dtrs); phon = word list; syn = ( local, bind); local = ( head, compls, funhead, select, lex ); head = ( vform, inv, agr, tense); vform = {fin, bse, psp, prp, pas, inf, ger }; inv= {-,+ }; agr = ( num, prs ); num= { sg, pl }; prs = { fst, snd, thrd }; tense = { past, pre}; compls = Sign list; lex = (+,-}; bind = (slash, subj, wh); slash = Sign list; subj = Sign list; wh = {rei, que}; dtrs = (head._dtr,compl_dtrs) head._dtr = Sign ; compldtrs = Sign list; Other systems require typing information, including HPSG (Pollard & Sag 1987) and UCG (Moens et al. 1989).


cit., Moens et al. , 1989) in grammars; although the present transfer rule format does not, they are clearly a desirable addition, since they would provide a means of exerting control over rule interactions.


It can be seen as a further contribution to the use of unification-based formahsms in linguistic description and specifically as an enriching of the minimal sort-based lexical semantic taxonomy incorporated into the Esprit ACORD system (Moens et al. , 1989) and the SRI (Cambridge) CLE system (Alshawi et al. , 1989).


(1990), who all use a semantics based on Ait-Kaci (1984); the use of sorts in Unification Categorial Grammar (Moens et al. 1989); the CLE project (Alshawi et al. 1989) and theoretical work by Smolka (1988).


