'I wonder what's gotten to him' 3Another interesting example of idiom with fixed subject is la moutarde monte au nez de NP ("NP looses his temper"), discussed in Abeille and Schabes (1989).


4 Conventional combination in SPUD Because LTAG can associate multiple iexical items to a single tree, it is straightforward to list frozen idioms, like call number, in the lexicon (Abeille and Schabes, 1989).


(Abeille and Schabes, 1989)) nor with a grammar allowing for trace anchored lexical entries.


Furthermore, as argued in (Abeille and Schabes, 1989), these trees can have multiple lexical anchors.


