First I show how Reape's analysis of Dutch and German verb raising constructions can be incorporated in the current grammar (Reape, 1989; Reape, 1990a). 
Reape (1989) proposes a different strategy for treating partially free word order. 
The parser is a generalization of the left-corner parser (Matsumoto et al. , 1983) and can be used for grammars written in powerful formalisms such as non-concatenative versions of HPSG (Pollard, 1984; Reape, 1989). 
Mike Reape uses an operation called 'sequence union' to analyse Germanic semi-free word order constructions (l~ape, 1989; Reape, 1990a). 
We follow a sign-based approach for the description of linguistic entities based on Headdriven Phrase Structure Grammar (Pollard and Sag, 1987) and the variant described in Reape (1989). 
