For example, Gibbon and Reinhard have proposed inheritance-based solutions to problems of phonology and prosody (Gibbon 1990; Reinhard and Gibbon 1991). 
2 Additionally, it has been shown how a computational inheritance model can be used for structuring lexical information relevant for phonology (Reinhard & Gibbon, 1991). 
Reinhard and Gibbon 1991 for another sort of DATR-based allomorphy Gerdemann 1993) and phonology (Bird 1992) have been taken. 
Research has focused on unification-based formalisms for inheritance network representation (e.g.\[Flickinger et al. , 1985; Shieber, 1986; Porter, 1987; Evans and Gazdar, 1990; Bird and Blackburn, 1990; Reinhard and Gibbon, 1991\]). 
Thus Gibbon and Reinhard have made extensive use of DATR networks to describe lexical morphophonological phenomena such as German umlaut, Kikuyu tone, and Arabic vowel intercalation (Gibbon 1990b, in press; Reinhard 1990; Reinhard and Gibbon 1991). 
