Further advantages are mentioned in Neumann (1991).


With few exceptions (e.g. , (Appelt, 1985)) the following two components are assumed:  'what to say' part (strategic component)  'how to say it' part (tactical component) But, as it has been demonstrated by some authors ((hppelt, 1985), (Hovy, 1987), (P~ubinoff, 1988), (Neumann, 1991), (Reithinger, 1991))it is not possible to separate the two phases of the generation process completely, e.g., in the case of lexieal gaps, choice between near synonyms or paraphrases.


In (Hovy, 1987), (Finkler and Neumann, 1989) and (Reithinger, 1991) approaches are described how such more flexible components can be achieved.


