J00-4002:1	204:700	3.3 Ellipsis Not surprisingly, we can adapt a version of the HOU approach to ellipsis resolution (Dalrymple, Shieber, and Pereira 1991; Pulman 1991; Gawron 1992, 1995) very easily within this framework.
---------------------------------------------------
J00-4002:2	73:700	Determining whether an equivalence applies to a QLF or an RLF is done by higher-order unification (henceforth, HOU) (Huet 1975; Miller and Nadathur 1986; Pulman 1991; Dalrymple, Shieber, and Pereira 1991; Gawron 1992) of the logical form with the relevant pattern.
---------------------------------------------------
