4.1 Redundancy elimination Redundancy elimination (Vestre, 1991; Chaves, 2003; Koller and Thater, 2006) is the problem of deriving from an USR U another USR Uprime, such that the readings of Uprime are a proper subset of the readings of U, but every reading in U is semantically equivalent to some reading in Uprime.


It is an improvement over earlier algorithms for enumerating irredundant readings (Vestre, 1991; Chaves, 2003) in that it maintains underspecifiedness; note that these earlier papersnevermadeanyclaimswithrespectto,orevaluated, completeness.


There has been previous research on enumerating only some representatives of each equivalence class (Vestre, 1991; Chaves, 2003), but these approaches dont maintain underspecification: After running their algorithms, they are left with a set of readings rather than an underspecified representation, i.e. we could no longer run other algorithms on an USR.


And there are computational approaches that screen unavailable and/or redundant semantic forms (Hobbs Shieber, 1987; Moran, 1988; Vestre, 1991).


