Tsujii and Fujita (1991)).


Classification of Machine Translation Divergences The divergence problem in machine translation has received increasingly greater attention in recent literature (see, for example, Barnett et al. 1991a, 1991b; Beaven 1992a, 1992b; Dorr 1990a, 1990b; Kameyama et al. 1991; Kinoshita, Phillips, and Tsujii 1992; Lindop and Tsujii 1991; Tsujii and Fujita 1991; Whitelock 1992; related discussion can also be found in work by Melby \[1986\] and Nirenburg and Nirenburg \[1988\]).


At minimum, equivalent words may have overlapping or properly subsuming senses rather than identical senses (see e.g Tsujii and Fujita (1991)), but more radical, structural differences are commonplace.


See also bilingual signs (Tsujii and Fujita, 1991) for a discussion of the importance of combining the appropriate domain of locality and synchronization.


