The rules below provide a natural deduction formulation of L (Morrill et al. 1990; Barry et al. 1991), where dots above a type represent a proof of that type.


Amongst the various enrichments that have been proposed (see e.g. \[van Benthem, 1989; Morrill et al. , 1990; Barry et al. , 1991; Morrill, 1990a; Morrill, 1990b; Moortgat and Morrill, 1991; Morrill, 1992a; Morrill, 1992b\]), \[Moortgat, 1988\] advanced earlier discussion of discontinuity in e.g. \[Bach, 1981; Bach, 1984\] with a proposal for infixing and wrapping operators.


