The sampling error can be dealt with (Brent, 1991) but predetermined cutoff percentages stir require eye-bailing the data.


There is a growing literature on corpus-based acquisition and tuning (Smadja 1991a; Zernik and Jacobs 1991; Brent 1991; as well as Grishman and Sterling 1992).


Brent (Brent, 1991) discusses an implemented program that automatically classifies verbs into two groups, stative vs. non-stative, on the basis of their syntactic contexts.


