9 It is a generalization of the algorithm described in Hegner (1991), which treats Horn combinations of attribute-value constraints.


Kasper (1988) and Hegner (1991) point out that Horn clauses, although technically disjunctions, can be handled considerably more efficiently than general disjunctive constraints.


However, the Horn extended feature structures described in (Hegner, 1991) can be thought of as adding guards to feature structures.


