Rather, I shall loosely classify a selection of the work based on the formal method used: unification (Carson 1988; Chung 1990; Coleman 1991; Scobbie 1991; Broe 1993; Walther 1993), predicate logic (Bird 1990; Bouma 1991; Russell 1993), modal logic (Bird and Blackburn 1991; Calder and Bird 1991), type theory (Klein 1991; Mastroianni 1993), categorial grammar/logic (Wheeler 1981; Dogil 1984; van der Linden 1991; Oehrle 1991; Steedman 1991; Moortgat and Morrill to appear), finite-state devices (Kay 1987; Kornai 1991; Wiebe 1992; Bird and Ellison 1994), electrical circuitry (Gilbers 1992), and formal language theory (Ristad 1990; Kornai 1991; Ritchie 1992; Wiebe 1992).


Research has focused on unification-based formalisms for inheritance network representation (e.g.\[Flickinger et al. , 1985; Shieber, 1986; Porter, 1987; Evans and Gazdar, 1990; Bird and Blackburn, 1990; Reinhard and Gibbon, 1991\]).


