In Horacek's,approach to generating concise explanations (Horacek 1991), a set of propositions representing the full explanation is pruned by eliminating propositions that can be derived from the remaining ones by a set of contextual rules.


3 Comparison to Past Research Most previous work in computational or formal linguistics on particularized conversational implicature (Green, 1990; Horacek, 1991; Joshi, Webber & Weischedel, 1984a; .\]oshi, Webber Weischedel, 1984b; Reiter, 1990; Whiner & Maida, 1991) has treated other kinds of implicature than we consider here.


