Difficulties with the correspondence approach This proposal for correspondence-based translation has been scrutinized by a number of researchers (e.g. Sadler et al. , 1989, Sadler et al. , 1990, Sadler and Thompson, 1991), and several difficulties have been pointed out. 
(1989, 1990), Sadler and Thompson (1991). 
The original co-description based approach in (Kaplan et al., 1989) faced problems when it came to examples involving embedded head-switching and multiple adjuncts (Sadler and Thompson, 1991), which led to the introduction of a restriction operator, to enable transfer on partial f-structures or semantic structures (Kaplan and Wedekind, 1993). 
3 See Sadler,t a/ (1990), Sadler and Thompson (1991), and Fmdler (1991) for further disctmaion of this apl~oach to MT. ACtES DI" COLING-92, NAmEs. 
(1989) and Sadler and Thompson (1991) point out a significant inadequacy of both these arrangements. 
