Another system for the treatment of spoken dialogues is reported in Bilange (1991). 
Dialogue grammars have previously been used to manage dialogue (Bunt, 1989; Bilange, 1991; Traum and Hinkelman, 1992; JSnsson, 1993; Mast et al. , 1994; Novick and Sutton, 1994; Chino and Tsuboi, 1996), but we are not aware of an approach where speech acts are translated into a collection of primitives with propositional content. 
6 Conclusion and future extensions Dialogue processing in VERBMOBIL poses problems that differ from other systems like (Mast, 1993) and (Bilange, 1991). 
For example, the same dialog manager software module has been used in each prototype with minor customizations for each language (Bilange 1991; McGlashan et al. 1992). 
3 Complex and compound interventions \[B ilange, 91 \] Bilange, 1 ~.( 1991). 
