We assume an analysis involving the restriction operator in the LFG description language (Wedekind & Kaplan, 1993) and selnantic form indexing (II<> @) e.g. by string position) as introduced by (Kaplan & Bresnan, 1982).


Like (Halvorsen, 1983; Wedekind & Kaplan, 1993) our approach fails int;o the description by analysis 1)aradigln.


Previous approaches to providing semantic components for LFGs concentrated on providing schemas for relating (or translating) fstructures (in)to sets of disambiguated semantic representations which are then interpreted model theoretically (Halvorsen, 1983; Halvorsen and Kaplan, 1988; Fenstad et al. , 1987; Wedekind and Kaplan, 1993; Dalrymple et al. , 1996).


, e.g., Creary an(1 Pollard (\]9S5), ~.'~ooIx, (i\[989), \])ah'yllll)le (1.992), Wedekind and Kaplan (1993)).


