454 van Noord Efficient Head-Corner Parsing Acknowledgments Some of the introductory material of this article is a modified and extended version of the introduction of Bouma and van Noord (1993).


A head-corner parser (Kay, 1989; Bouma and van Noord, 1993) is a special type of head-driven parser.


Previous comparisons have either focussed on context-free (CF) or augmented CF parsing (Tomita, 1987; Billot & Lang, 1989), or have used relatively small, limited-coverage unification grammars and lexicons (Shann, 1989; Bouma & van Noord, 1993; Maxwell & Kaplan, 1993).


 Definite-clause Grammar (Pereira and Warren, 1980) for Dutch to illustrate semantic-headdriven generation (Shieber et al. , 1989), and to compare different parsers for speed (Bouma and van Noord, 1993).


