Third, this research needs to be integrated into a more complete plan-based approach to language, and needs to be extended so as to handle more general discourse plan failures (McRoy and Hirst 1993; McRoy and Hirst 1995; Horton and Hirst 1991; Heeman 1993; Edmonds 1994; Hirst et al. 1994).


3.3 Pragmatic inferences in sequences of utterances We have already mentioned that speech repairs constitute a good benchmark for studying the genera148 tion and cancellation of pragmatic inferences along sequences of utterances (McRoy and Hirst, 1993).


