In 2These examples have been taken or adapted from Kehler (1993b). 
resolution to an account of discourse structure and coherence, namely our previous account (Kehler, 1993b) and the accounts of Priist (1992) and Asher (1993). 
Most work on ellipsis (Fiengo and May, 1994; Lappin, 1993; Dalrymple et al. , 1991; Kehler, 1993; Shieber et al. , 1996) is aimed at discerning the procedures and the level of language processing at which ellipsis resolution takes place, or ambiguous and difficult cases. 
This analysis agrees with the proposal made in (Kehler, 1993; Kehler, 1995). 
These are exactly the same readings as \[l)alrylnple et al. , 1991\], \[Kehler, 1993\] and \[Sem, 1993\] get in their analysis. 
