2 INTEGRATING MULTI-ENGINE OUTPUT In our experiment we used three MT engines: * a knowledge-based MT (KBMT) system, the mainline Pangloss engine (Frederking et al. , 1993b);  an example-based MT (EBMT) system (see (Nirenburg et al. , 1993; Nirenburg et al. , 1994b); the original idea is due to Nagao (Nagao, 1984)); and  a lexical transfer system, fortified with morphological analysis and synthesis modules and relying on a number of databases -a machine-readable dictionary (the Collins Spanish/English), the lexicons used by the KBMT modules, a large set of user-generated bilingual glossaries as well as a gazetteer and a list of proper and organization names.


3 TRANSLATION DELIVERY SYSTEM Results of multi-engine MT were fed in our experiment into a translator's workstation (TWS) (Cohen et al. , 1993), through which a translator either approved the system's output or modified it.


