2(Kay, 1987), (Kataja and Koskenniemi, 1988), (Beesley et al. , 1989), (Lavie et al. , 1990), (Beesley, 1990), (Beesley, 1991), (Kornai, 1991), (Wiebe, 1992), (Pulman and Hepple, 1993), (Narayanan and Hashem, 1993), and (Bird and Ellison, 1994).


aNon-linear proposals include (Kay, 1987), (Kornai, 1991), (Wiebe, 1992), (Narayanan and Hashem, 1993), (Bird and Ellison, 1994) and (Kiraz, 1994).


23 The reader interested in other finite-state models of Arabic phonology is directed to the work of Narayanan and Hashem (1993), Beesley, Buckwater, and Newton (1989), and Beesley (1990).


