Investigations into the interpretation of narrative discourse (Lascarides & Asher 1993, Reyle & Rossdeutscher 2000) have, however, shown that very specific lexical information plays an important role in determining temporal interpretation.


We will extend the logical engine used to infer rhetorical relations--DiCE (Lascarides and Asher 1991, 1993a, 1993b, Lascarides and Oberlander 1993)--to model inferences about intentional structure and its interaction with informational structure.


A logical framework in which all those plausible relations between constituents that are consistent with each other are inferred, such as a nonmonotonic logic like that in DICE (Lascarides and Asher, 1993a), would achieve this.


