Finally, Bouma and Nerbonne (1994, 47) comment that "in spite of Kilgarriff's (1993) interesting work on modelling some derivational relations in the pure inheritance machinery of DATR, we know of no work attempting to model potentially recursive derivational relations, and we remain sceptical about relying on inheritance alone for this".


Following LTAG conventions (for the time being), the node labels here are gross syntactic category specifications to which additional featural information may be added 5, and are annotated to indicate node type: <> indicates an anchor node, and I indicates a substitution node (where a 3See, for example, Bleiching (1992; 1994), Brown & Hippisley (1994), Corbett & Fraser (1993), Cahill (1990; 1993), Cahill &: Evans (1990), Fraser &= Corbett (in press), Gibbon (1992), Kilgarriff (1993), Kilgarriff & Gazdar (1995), Reinhard & Gibbon (1991).


The most common linguistic application for default inheritance is to encode lexical generalizations (e.g. , Boguraev and Pustejovsky 1990; Briscoe, Copestake, and Boguraev 1990; Vossen and Copestake 1993; Daelemans 1987; Evans and Gazdar 1989a, 1989b, 1996; Flickinger, Pollard, and Wasow 1985; Flickinger 1987; Flickinger and Nerbonne 1992; Kilgarriff 1993; Krieger and Nerbonne 1993; Sanfilippo 1993; Shieber 1986a), but defaults have also been used for specification in syntactic theory (e.g. , Gazdar 1987; Shieber 1986b), and for the analysis of gapping constructions (Kaplan 1987) and ellipsis (Grover et al. 1994).


