For the semantics of a discourse segment, Nomoto and Nitta (1993) observes an interesting tendency that zero (elliptical) anapl,ora occurring within the segment do not refer across the segment boundary; that is, their references tend to be resolved internally 1.


It is quite possible that a set of discourse segments are not aggregated into a single discourse but may have diverse discourse groupings (Nomoto and Nitta, 1993).


It derives a linguistic motivation front the view that discourse consists of what we call discourse segments, minimal coherent mtits of discourse (Nomoto and Nitta, 1993), while statistically it is guided by ideas from intbrmatiou retrieval (Salton, 1988).


The approach builds on tile ttleory of discourse segment (Nomoto and Nitta, 1993), incorporating ideas from the research on information retrieval (Salton, 1988).


