2 Related Work Temporal ordering has been extensively studied in computational linguistics (Passonneau, 1988; Webber, 1988; Hwang and Schubert, 1992; Lascarides and Asher, 1993; Lascarides and Oberlander, 1993).


Lascarides & Oberlander (1993), for instance, note that sentences containing temporal connectives expressing the same temporal structure may not describe a coherent discourse in certain contexts.


There exists a large body of research in NLU on analysing the temporal structure of texts, including the role of temporal markers, though again restricted to English (Moens and Steedman 1988; Lascarides and Oberlander 1993; Hitzeman et al. 1995).


This phenomenon interacts with other discourse phenomena, for instance, given and new information, and--when placed in a larger discourse context--with presuppositions and their accommodation (Lascarides and Oberlander 1993).


We will extend the logical engine used to infer rhetorical relations--DiCE (Lascarides and Asher 1991, 1993a, 1993b, Lascarides and Oberlander 1993)--to model inferences about intentional structure and its interaction with informational structure.


