A new data-oriented version of MORPA (\[Heemskerk, 1993\]) assigns a priority ordering to the set of morphological decomSin a different set of experiments, we successfully applied the IBL approach and two other data-oriented algorithms, analogical modeling and backprop, to the stress assignment problem (see \[Gillis et al. , 1992\], \[Daelemans et al. , 1993\], but we have not yet tried to combine the two tasks.


We have not made a conversion of our output to Heemskerk's (1993).


Previous approaches to Dutch morphological analysis have been based on finite-state transducers (e.g. , XEROX'es morphological analyzer), or on parsing with context-free word grammars interleaved with exploration of possible spelling changes (e.g. Heemskerk and van Heuven (1993); or see Heemskerk (1993) for a probabilistic variant).


We briefly note that Heemskerk (1993) reports a correct word score of 92% on free text test material yielded by the probabilistic morphological analyzer MORPA.


