SIMR is equipped with several "plug-in" matching heuristic modules which are based on cognates (Davis et al. , 1995; Simard et al. , 1992; Melamed, 1995) and/or "seed" translation lexicons (Chen, 1993).


On the other end of the spectrum, character-based bitext mapping algorithms (Church, 1993; Davis et al. , 1995) are limited to language pairs where cognates are common; in addition, they may easily be misled by superficial differences in formatting and page layout and must sacrifice precision to be computationally tractable.


