Name recognition is made harder in the closed caption domain by the fact that no capitalization information is given, thus making unusable all methods that rely on capitalization as the main way to identify candidates (Wolinski et al. , 1995) (Wacholder et al. , 1997).


It has been used continuously since 1995 in several real-time document filtering applications (Wolinski et al. , 2000).


3.2 The French NERC System The French NERC system has been implemented with the use of a rule-based inference engine (Wolinski et al. , 1995).


The semantic categories of proper nouns are crucial information for text understanding \[Wolinski et al. , 1995\] and information extraction \[Cowie and Lehnert,1996\].


