This would force the f-structures of the surface realizations of a semantic representation ~' given by {q~ I ~' G ~ A 3w(Ac(w, ~))} to be included in a finite and computable set of structurally related f-structures {q~ I ~' _G q~ A I~I < kI~'I}Since the generation problem is decidable (Wedekind 1995), i.e., {w I At(w, ~)} = 0 is decidable for any given f-structure {b, and only a finite number of structurally related f-structures q~ has to be tested for {w I At(w, ~)} ---0, semantic-driven generation must be decidable.


\e also \]lave gtll exl)lanation for another observation of Wedekind (1995).


Disambiguation is the major formal obstacle in this approach, since parsing algorithms exist when the grammatical formalisms are off-line parsable (Kaplan and Bresnan 1982), and the generation problem is known to be decidable even without the off-line parsable restriction (Wedekind 1995).


