Though CCG-MM is more powerful than CCG and LIG, the rules in (35) reveal a significant property of Partially Linear Indexed Grammar (PLIG) (Keller and Weir, 1995), an extension of LIG whose productions are allowed to have two or more daughters sharing stack features with each other but these stacks are not shared with their mother as shown in (36).


From (Keller and Weir, 1995), we can position the CCG-MM in the Chomskys hierarchy as follows: CFG < CCG = TAG = HG = LIG < CCG-MM  PLIG  LCFRS < CSG.


