3.2 Implementation I have implemented the algorithm in Prolog and coded the HPSG feature structure in the way described using ProFIT (Erbach, 1995). 
Indeed we have successfully extended the ProFIT typed feature formalism (Erbach, 1995) with the constructs described in this paper. 
For uniformity~ the algorithms are implemented m Prolog and the grammars are implemented in ProFIT (Erbach, 1995). 
ICONOCLAST is implemented in ProFIT (Erbach, 1995), so that feature structures are represented by Prolog terms and can be unified efficiently through Prolog term unification. 
Although we did not treat type hierarchies in this paper, we can incorporate them by using the method proposed by Erbach (1995). 
