A more detailed description of the process for uncovering corpus regularities can be found in (Mikheev&Finch, 1995).


See also (Mikheev&Finch, 1995), (Mikheev&Finch, 1997) for other uses of the LT NSL tools in annotating linguistic structures of interest and extracting statistics from that markup.


, 1995), acquim'tion of domain knowledge (Mikheev and Finch, 1995) and improvement of parsing accuracy through the speci~cation of selectional restrictions (Grishman and Sterling, 1994; Gri~h,n~n aud Sterling, 1992).


In future, we intend to investigate the effect of more sophisticated cohesion measures, including the use of thesaural information from domainindependent sources and corpus-based Knowlege Acquisition, e.g., (Mikheev and Finch, 1995), which should form better approximations to the supertype/subtype distinction.


