AIM Sentences best portraying the particular (main) research goal of the article TEXTUAL Explicit statements about the textual section structure of the paper CONTRAST Sentences contrasting own work to other work; sentences pointing out weaknesses in other research; sentences stating that the research task of the current paper has never been done before; direct comparisons BASIS Statements that the own work uses some other work as its basis or starting point, or gets support from this other work Figure 1: Overview of the annotation scheme FULL SCHEME 1997; Alexandersson et al. , 1995; Jurafsky et al. , 1997), but our task is more difficult since it requires more subjective interpretation.


116 An overview of the dialogue component is given in (Alexandersson et al. , 1995).


