Note that the extent of incrementality allowed by using 'generalised composition' in the compiled firstorder system should not be equated with that which 7For an example of a system allowing word-by-word incrementality, see (Milward, 1995).


To fulfill the requirement, the system needs to understand spoken language at least incrementally (Allen et al. , 2001; Inagaki and Matsubara, 1995; Milward and Cooper, 1994), that is, to analyze each input sentence from left to right and acquire the content.


Several incremental parsing methods have been proposed to date (Costa et al. , 2001; Haddock, 1987; Matsubara et al. , 1997; Milward, 1995; Roark, 2001).


Such models have also been explored computationally (Milward (1995), Crocker (1991)).


