While there has been some previous work in sense discrimination (e.g. , (Schutze, 1992), (Pedersen and Bruce, 1997), (Pedersen and Bruce, 1998), (Schutze, 1998), (Fukumoto and Suzuki, 1999)), by comparison it is much less than that devoted to word sense disambiguation, which is the process of assigning a meaning to a word from a predefined set of possibilities.


4 Related Work Besides the two works (Pantel and Lin, 2002; Schutze, 1998), there are other related efforts on word sense discrimination (Dorow and Widdows, 2003; Fukumoto and Suzuki, 1999; Pedersen and Bruce, 1997).


In (Fukumoto and Suzuki, 1999), a term weight learning algorithm was proposed for verb sense disambiguation, which can automatically extract nouns co-occurring with verbs and identify the number of senses of an ambiguous verb.


(Fukumoto and Suzuki, 1999) describe a method for discriminating among verb senses based on determining which nouns cooccur with the target verb.


