The part used in our experiments are the biological paper abstracts from the GENIA corpus (Collier et al., 1999). 
The paper first presents our approach and compares it with the one developed in the framework of a similar project called Genia (Collier et al. 1999). 
The BioScope corpus consists of three parts: clinical free-texts (radiology reports), biological full papers and biological paper abstracts from the GENIA corpus (Collier et al., 1999). 
2.3 Comparison with the Genia project Our approach is very close to the one of the Genia project (Collier et al. , 1999). 
The BioScope corpus consists of three parts: clinical free-texts (radiology reports), biological full papers and biological paper abstracts from the GENIA corpus (Collier et al., 1999). 
