ES99 define the following *I predicates (Eckert and Strube, 1999b)\[p. 40\]: Equating constructions where a pronominal referent is equated with an abstract object, e.g., x is making it easy, x is a suggestion. 
Then I present an adaptation to Danish of Eckert and Strube's algorithm for resolving anaphora referring to individual NPs and abstract objects in English dialogues (Eckert and Strube, 1999b; Eckert and Strube, 1999a). 
Predicates that are preferentially associated with individual objects are the following (Eckert and Strube, 1999b)\[p. 40\]: Equating constructions where a pronominal referent is equated with a concrete individual referent, e.g., x is a ear. 
Eckert and Strube (1999a; 1999b), henceforth ES99, describe an algorithm for resolving anaphors referring to individual NPs and abstract objects in English dialogues. 
In (Eckert and Strube, 1999a) these tasks have been accomplished by two annotators. 
