There are some models which calculate the likelihood values of a dependency between bunsetsu i and j as in (6), such as a decision tree model (Haruno et al. , 1998), a maximum entropy model (Uchimoto et al. , 1999), a model based on distance and lexical information (Pujio and Matsumoto, 1998). 
The static features are basically taken from Uchimotos list (Uchimoto et al. , 1999). 
The attribute that indicates whether a head bunsetsu is a sentence-end bunsetsu has often been used in conventional sentence-by-sentence parsing methods (e.g. Uchimoto et al. , 1999). 
KM02 = Kudo and Matsumoto 2002, KM00 = Kudo and Matsumoto 2000, USI99 = Uchimoto et al. 1999, and Seki00 = Sekine 2000. 
Decision Trees(Haruno et al. , 1998) and Maximum Entropy models(Ratnaparkhi, 1997; Uchimoto et al. , 1999; Charniak, 2000) have been applied to dependency or syntactic structure analysis. 
