The number of Srinivas(97) is based on footnote 1 of (Chen et al. , 1999).


In Chen, Bangalore, and Vijay-Shanker (1999), classifier combination is used to overcome the sparse data problem when using more contextual information in supertagging, an approach in which parsing is reduced to tagging with a complex tagset (consisting of partial parse trees associated with lexical items).


Second, the second baseline is slightly better than the first baseline, indicating using ~Noticeably, the results we report on Srinivas' data, 85.78% on Section 23 and 85.53% on Section 22, axe lower than 92.2% reported in (Srinivas, 1997) and 91.37% in (Chen et al. , 1999).


As for Srinivas' results, we did not use the results reported in (Srinivas, 1997) and (Chen et al. , 1999) because they are based on different training and testing data.


