Figure 1: AZ Annotation Scheme (Teufel et al. 1999). 
(Teufel et al. , 1999) reports on interannotator agreement studies with this scheme. 
That means that parts of the AZ scheme are similar to citation function classification schemes from the area of citation content analysis (Garfield, 1965; Weinstock, 1971; Spiegel-Rusing, 1977), and to automatic citation function classification (Nanba and Okumura, 1999; Garzone and Mercer, 2000; Teufel et al., 2006). 
A study of human agreement on AZ annotation exists (Teufel et al., 1999), but this uses articles from only one discipline, namely computational linguistics. 
2 Human Annotation of Argumentative Zones We have previously evaluated the scheme empirically by extensive experiments with three subjects, over a range of 48 articles (Teufel et al. , 1999). 
