2.4 Chunking as Sequential Classification Our protein name tagging is formulated as IOB2/IOE2 chunking (Tjong Kim Sang and Veenstra, 1999). 
4 Classification Process The training data was converted to use the IOB2 phrase model (Tjong Kim Sang and Veenstra, 1999). 
(Tjong Kim Sang and Veenstra, 1999) compare different data representations for this task. 
There are four kinds of chunk tags in the CoNLL-1999 dataset, namely IOB1, IOB2, IOE1, and IOE2 (Tjong Kim Sang and Veenstra, 1999). 
1http://chasen.org/ taku/software/yamcha/ 2http://chasen.org/ taku/software/TinySVM/ 197 a0 Bracketed representation of roles was converted into IOB2 representation (Ramhsaw and Marcus, 1995) (Sang and Veenstra, 1999). 
