(Cut-free) proof nets exhibit no spurious ambiguity and play the role in categorial grammar that parse trees play in phrase structure grammar. Surveys and articles on the topic include Lamarche and Retor (1996), de Groote and Retor (1996), and Morrill (1999).


From the parsing perspective, the redundancy of analyses can be controlled by (1) grammar rewriting (Wittenburg 1987), (2) checking the chart for PAS equivalence (Karttunen 1989; Komagata 1997), (3) making the processor parsimonious on using long-distance compositions (Pareschi and Steedman 1987), or (4) parsing into normal forms (Eisner 1996; Hepple 1990b; Hepple and Morrill 1989; Konig 1989; Morrill 1999).


