Similarly, a decision-tree approach was used to solve the POS disambiguation and unknown word guessing in (Orphanos and Christodoulakis, 1999).


There have been many studies on POS guessing of unknown words (Mori and Nagao, 1996; Mikheev, 1997; Chen et al. , 1997; Nagata, 1999; Orphanos and Christodoulakis, 1999).


Orphanos and Christodoulakis presented a POS tagger for Modern Greek and focused on a data-driven approach for the induction of decision trees used as disambiguation or guessing devices (G. Orphanos and D. Christodoulakis, 1999).


Many methods used in machine learning, such The 6th Workshop on Asian Languae Resources, 2008 18 as Decision Tree, Support Vector Machines (SVM) and k-Nearest-Neighbors (k-NN), were used for guessing possible POS tags of words (G. Orphanos and D. Christodoulakis, 1999; Nakagawa T, 2001; Maosong Sun et al., 2000).


