Finally, Brants (Brmlts, 1999) described a German clumker which was implemented with cascaded Markov Models. 
As per (Brants, 1999), each layers chunk bracketing of Cascaded Markov Models is dependent because the output of a lower layer is passed as input to the next higher layer. 
More recently, Brants (1999) used a cascaded Markov model to parse German text. 
1 Introduction Chunk parsing (Tjong Kim Sang, 2001; Brants, 1999) is a simple parsing strategy both in implementation and concept. 
Brants (1999) described a parser that encoded the grammar as a set of cascaded Markov models. 
