Such features are of similar interest in text processing  in particular, automated genre classification (Dewdney et al., 2001; Finn and Kushmerick, 2006; Kessler et al., 1997; Stamatatos et al., 2000; Wolters and Kirsten, 1999)  which relies on there being reliably detectable features that can beusedtodistinguishoneclassfromanother.


Fortunately, there is a growing body of work on genre-based text classification, including (Dewdney et al., 2001; Finn and Kushmerick, 2006; Kessler et al., 1997; Stamatatosetal.,2000; WoltersandKirsten, 1999).


See (Wolters and Kirsten, 1999) who, following this approach, already used POS frequency as a source for genre classification, a task which goes beyond the scope of the given paper.


Further determiners of style are the domain or genre (Karlgren and Cutting, 1994; Wolters and Kirsten, 1999), the modalities (speech only vs. speech and visual interfaces) (Fais et al. , 1996; Oviatt et al. , 1994), and the degree of interactivity (Oviatt and Cohen, 1991) which are more or less determined by the application scenario of a spoken dialogue system.


