Further details of the design principles of the system are described in (Lavie et al. , 2001).


uses a client-server architecture (Lavie et al. , 2001) to enable users who are browsing the web pages of a service provider (e.g. a tourism bureau) to seamlessly connect to a human agent who speaks a different language.


2000; Lavie et al. 2001).


(Wahlster, 2000; Lavie et al. , 2001) usually employ complex architectures combining statistical and rule-based methods, successful practical examples like Phraselator and S-MINDS (Phraselator, 2005; Sehda, 2005) are typically phrasal translators with grammar-based recognizers.


