Sentence ordering is much harder for multi-document summarization than for single-document summarization (McKeown et al., 2001; Barzilay and Lapata, 2005). 
[Barzilay et al, 2001] evaluated three algorithms for sentence ordering in multi-document summaries. 
Concurrent work analyzing constraints on ordering of sentences in summarization found that a coherence constraint that ensures that blocks of sentences on the same topic tend to occur together (Barzilay et al. , 2001). 
al (1999), Zha (2002), Barzilay et al. , (2001)). 
Majority ordering is one way of sentence ordering (McKeown et al., 2001; Barzilay et al., 2002). 
