The results of several studies have veri ed its eciency(James and Reischel, 2001)(Tanaka-Ishii et al. , 2000), so the technology looks promising in the context of mobile phones.


The earliest appearance of this idea was at the beginning of the 80's in Japan, in discussions of processing systems for Japanese text(Co.Ltd. , 1982);; more recent work has been concerned with mobile phones (James and Reischel, 2001)(Tanaka-Ishii et al. , 2000).


PPM has successfully been adapted to the user-interface domain in certain previous works(Tanaka-Ishii et al. , 2001)(Ward et al. , 2000).


