These patterns were extracted by pattern discovery during information extraction (Sudo et al. , 2001). 
Chains: A pattern is defined as a path between a verb node and any other node in the dependency tree passing through zero or more intermediate nodes (Sudo et al. , 2001). 
The compared models are the direct predicate-argument model (PA)9, and the Chain model (CH) in (Sudo et al. , 2001). 
A number of pattern induction approaches have recently been researched based on the dependency analysis (Yangarber, 2003) (Sudo et al., 2001) (Greenwood and Stevenson, 2006) (Sudo et al., 2003). 
Chains: A pattern is defined as a path between a verb node and any other node in the dependency tree passing through zero or more intermediate nodes (Sudo et al. , 2001). 
