2In (Walker and Passonneau, 2001) we didnt distinguish the price subtask from the itinerary presentation subtask.


See (Walker and Passonneau, 2001) for more detail.


Practical use of speech act theories in spoken language processing (Stolcke et al. 2000; Walker and Passonneau 2001; Wu et al. , 2004) have given both insight and deeper understanding of verbal communication.


(Core and Allen, 1997; Di Eugenio et al., 1998; Traum, 1996; Walker et al., 1996; MacWhinney, 1996; Jekat et al., 1995; Anderson et al., 1991; Condon and Cech, 1996; van Vark et al., 1996; Walker and Passonneau, 2001).


