The University of Colorado framework also has a form-based architecture (Pellom et al. 2001), while CMU and Bell Labs frameworks allow the specification of deep task hierarchies (Wei and Rudnicky 2000, Potamianos et al. 2000).


2http://www.ldc.upenn.edu Colorado Sonic speech recognizer (Pellom et al. , 2001).


Using a Chinese character-to-pinyin dictionary and a handconstructed mapping of pinyin sequences to ARPABET phonemes, the transcribed text was then force-aligned to the corresponding audio segments using the language porting mechanism in the University of Colorado Sonic speech recognizer (Pellom et al. , 2001).


