We are pursuing another line of research which looks at automatic error detection, described in (Aberdeen et al. , 2001).


In addition, we are beginning to look at two new aspects of these dialogues: task complexity and conversational failure analysis (at the turn level, (Aberdeen et al. , 2001)).


However, a number of studies have been done on predicting speci c errors in a dialogue, using a variety of automatic and handlabelled features, such as ASR con dence and semantic labels (Aberdeen et al. , 2001; Hirschberg et al. , 2000; Levow, 1998; Litman et al. , 1999).


