Zhu and Rosenfeld (2001) use Web-based n-gram counts for language modeling. 
1 Introduction Vector-based models of word co-occurrence have proved a useful representational framework for a variety of natural language processing (NLP) tasks such as word sense discrimination (Schtze, 1998), text segmentation (Choi et al. , 2001), contextual spelling correction (Jones and Martin, 1997), automatic thesaurus extraction (Grefenstette, 1994), and notably information retrieval (Salton et al. , 1975). 
3.1 Introduction to Minipar Minipar is a principle-based, broad-coverage parser for English (Lin, 2001). 
460 Computational Linguistics Volume 29, Number 3 and Zhu and Rosenfeld (2001) use Web-based n-gram counts to improve language modeling. 
Similar to Lin and Pantel (2001), we define the contexts of a word to be the undirected paths in dependency trees involving that word at either the beginning or the end. 
