2.1 Deep Linguistic Analysis We use SERIF (Ramshaw et al. , 2001), a linguistic analysis engine, to perform full parsing, name entity detection, relation detection, and co-reference resolution.


Coreference is determined using an information extraction engine, SERIF (Ramshaw et al. , 2001).


A detailed description of the algorithm is documented 308 Question Classification Document Retrieval Linguistic Analysis Semantic Processing Phrase Ranking Redundancy Remove Lists of Response Answer Annotation Name Tagging Parsing Preposition finding Coreference Relation Extraction Training data TreeBank Name Annotation Linguistic motivated Pattern motivated Question Pattern MatchingPattern Learning Figure 1: Question answering system structure in (Ramshaw et al. , 2001).


