Finally, our work is also related to research on title generation (Banko et al. , 2000; Jin and Hauptmann, 2001; Dorr et al. , 2003).


This task has been extensively studied over the last six years (Banko et al. , 2000; Jin and Hauptmann, 2001).


3 Related Work Decoding for selection-and-ordering problems is commonly implemented using beam search (Banko et al. , 2000; Corston-Oliver et al. , 2002; Jin and Hauptmann, 2001).


