N. Morgan et al. 2001.


Until recently, empirical research was only possible using single-speaker and dialog corpora, but now there are many hours of data being collected in multi-talker environments (Morgan et al, 2001; Schultz et al, 2001).


4 Experiments We evaluated on two tasks: 1) Switchboard (Godfrey et al. , 1992), specifically the HUB5 eval 2001 set having a total of 60K words spoken by 120 speakers, and 2) an ICSI Meeting recorder (Morgan et al, 2001) eval set having a total of 44K words spoken by 25 speakers.


First we extended the baseline vocabulary with words from a small in-domain training corpus (Schwarm and Ostendorf, 2002), and then we used N-grams with these new words in our web queries, e.g. wireless mikes like, I know that recognizer for a meeting transcription task (Morgan et al, 2001).


2 Approach Our experiments are based on a subset of meeting recordings collected and transcribed by ICSI (Morgan et al. , 2001).


