This is the method proposed by (Kawahara and Kurohashi, 2001). 
Various methods of creating detailed entries have been suggested, such as the extraction of candidates from corpora (Manning, 1993; Utsuro et al. , 1997; Kawahara and Kurohashi, 2001), and the automatic and semi-automatic induction of semantic constraints (Akiba et al. , 2000). 
This is the first stage of our two-stage approach, and is performed by the method proposed by (Kawahara and Kurohashi, 2001). 
See (Kawahara and Kurohashi, 2001) for the details. 
We proposed a method to construct a Japanese case frame dictionary automatically by arranging large volumes of parse results by coupling a verb and its closest case component (Kawahara and Kurohashi, 2001). 
