P04-1027:1	165:190	(Khandelwal et al. , 2001) propose a task, called Temporal Summarization, that combines summarization and topic tracking.
---------------------------------------------------
P04-1027:2	169:190	There are, at least, two reasons to explain this: (Khandelwal et al. , 2001) work on an average of 43 documents, half the size of the topics in our corpus.
---------------------------------------------------
