Others make simplifying assumptions about the search space (Garca-Varea, Casacuberta, and Ney 1998; Garca-Varea et al. 2001), as does the original IBM stack search decoder (Berger et al. 1994).


Therefore, we integrate an admissible estimation of the remaining probabilities to arrive at a complete translation (Section 5.6) Many of the other search approaches suggested in the literature do not meet the described aims:  Neither optimal A* search (Och, Ueffing, and Ney 2001) nor optimal integer programming (Germann et al. 2001) for statistical MT allows efficient search for long sentences.


Och, Ueffing, and Ney (2001) have described an admissible heuristic function for Model 4 of Brown et al.


