For instance, in Information Extraction relations allows for recognizing dierent guises in which an event can appear regardless of the several dierent syntactic patterns that can be used to specify it (Palmer et al. , 2001) 2 .In Question Answering, systems usually use forms of relation-based structured representations of the input texts (i.e. questions and answers) and try to match those representations (see e.g.


Fillmores FRAMENET, the PropBank as a further stage of the development of the Penn Treebank (Palmer et al. , 2001) and Levins verb classes (Levin, 1993) on which the LCS Database (Dorr, 2001) is based.


