Venkatapathy and Joshi (2005) combine different statistical and distributional methods using support vector machines (SVMs) for identifying noncompositional verb-object combinations. 
The work most similar to ours is that of Venkatapathy and Joshi (2005). 
the same LSA approach, but considering the similarity of the verb-object pair with the verbal form of the object (to capture support verb constructions e.g. give a smile Venkatapathy and Joshi (2005) produced a dataset of verb-object pairs with human judgements of compositionality. 
Venkatapathy and Joshi (2005) combine aspects of the above-mentioned work, by incorporatinglexical fixedness, collocation-based, anddistributional similarity measures into a set of features which are used to rank verb+noun combinations according to their compositionality. 
Venkatapathy and Joshi (2005) suggest that an expression is likely to be relatively more compositional if it is decomposable. 
