We have used this method to analyze the output of two different statistical machine translation models (Chiang et al. , 2005).


These features are commonly used in the state-of-the-art systems (Koehn et al., 2005; Chiang et al., 2005).


However, they are not specially designed for BTG-based SMT and can also be easily integrated into other systems with different underlying translation strategies, such as the state-of-the-art phrasebased system (Koehn et al., 2007), syntax-based systems (Chiang et al., 2005; Marcu et al., 2006; Liu et al., 2006).


Some recent models permit discontiguous phrases (Chiang, 2007; Quirk et al. , 2005; Simard et al. , 2005).


Some grammar-based models such as the hierarchical model (Chiang, 2005) and the syntactified target language phrases model (Marcu et al., 2006) have shownbetterperformancethanphrase-basedmodels on certain language pairs.


