Other previous research focuses only on the extraction of opinion expressions (e.g. Kim and Hovy (2005a), Munson et al. 
We present two baseline methods for the joint opinion-source recognition task that use a state-of-the-art SRL system (Punyakanok et al. , 2005), and describe two additional methods for incorporating SRL into our ILP-based system. 
We evaluate entity and link extraction using both an overlap and exact matching scheme.12 Because the exact start and endpoints of the manual annotations are somewhat arbitrary, the overlap scheme is more reasonable for our task (Wiebe et al. , 2005). 
SRL baselines Next, we consider two baselines that use a state-of-the-art SRL system (Punyakanok et al. , 2005). 
For source extraction in particular, our system achieves an F-measure of 78.1, significantly outperforming previous results in this area (Choi et al. , 2005), which obtained an F-measure of 69.4 on the same corpus. 
