That is, it is 4 Bunescu and Mooney (2005) used the ACE 2002 corpus, including 422 documents, which is known to have many inconsistencies than the 2003 version. 
3.4 Shortest Path Dependency Kernel The shortest path dependency kernel proposed by Bunescu & Mooney (2005a) also works with dependency parse trees. 
Recently, kernel 49 methods are also becoming widely used for relation extraction (Bunescu and Mooney, 2005; Zhao and Grishman, 2005). 
3.2 Subsequence Kernel The subsequence kernel introduced in (Bunescu and Mooney, 2005b) is a generalization of the string kernel first introduced by Lodhi et al. 
Bunescu and Mooney (2005a) proposed a shortest path dependency kernel. 
