It has been shown empirically that, while the significance of particular features might vary between domains and tasks, certain generalized classes of features retain their importance across domains (Minkov et al., 2005). 
 Email: A collection of 10,000 emails obtained from the publicly available Enron email collection (Minkov et al., 2005). 
Indeed, in practical usage of CRF, the main challenge is to come up with additional complex features (often in the form of dictionary and regex patterns) that need to be given to the CRF (Minkov et al., 2005). 
The Cspace corpus contains email messages collected from a management course conducted at Carnegie Mellon University in 1997 (Minkov et al. , 2005). 
We also incorporate the following additional knowledge into the CRFs features referring to (Minkov et al. , 2005; Rosenfeld et al. , 61 Figure 6: The recall-precision curve of InventorOf relation. 
