Moreover, the answers of all testing questions are named entities identified by [Youzheng Wu, et al. 2005]. 
A method of incorporating heuristic human knowledge into a statistical model was proposed in (Wu et al., 2005). 
Chinese NER tool [Wu et al. 2005]. 
Some machine learning algorithms also have been investigated in Chinese NER, including HMM (Yu et al. , 1998; Jing et al. , 2003), class-based language model (Gao et al. , 2005; Wu et al. , 2005), RRM (Guo et al. , 2005; Jing et al. , 2003), etc. However, when a machine learning-based NER system is directly employed in a new domain, its performance usually degrades. 
A first-stage Google search (FGS) is applied to extract n candidate answers fc1,c2,,,cng from the top m Google snippets fs1,s2,,,smg by a NER tool [Wu et al. 2005]. 
