Examples of such efforts include work on the induction of synchronous grammars (Wu and Wong, 1998; Chiang, 2005) and learning multilingual lexical resources (Genzel, 2005).


Multilingual learning has been successful for other linguistic induction tasks such as lexicon acquisition, morphological segmentation, and part-of-speech tagging (Genzel, 2005; Snyder and Barzilay, 2008; Snyder et al., 2008; Snyder 1Code and the outputs of our experiments are available at http://groups.csail.mit.edu/rbg/code/multiling induction.


For instance, Genzel (2005) describes a method for inducing a multilingual lexicon from a group of related languages.


