P07-1086:1	45:191	3 Modelling Symmetry Between Conjuncts There is often a considerable bias toward symmetry in the syntactic structure of two conjuncts, see for example (Dubey et al. , 2005).
---------------------------------------------------
P06-1053:2	181:235	While the effect is not always strong, we expect positive adaptation to be higher than negative adaptation (Dubey et al. , 2005).
---------------------------------------------------
E06-1036:3	209:230	Due to some kind of priming (syntactic, phonetic, lexical, etc.), the comprehension and the production of a parallel utterance is made faster (Dubey et al. , 2005).
---------------------------------------------------
E06-1036:4	9:230	Based on psycholinguistics studies (Dubey et al. , 2005), our intuition isthat similarities concerning the surface, the content and the structure of textual units can be a way for authors to explicit their intention toconsider these units withthesamerhetorical importance.
---------------------------------------------------
P07-1102:5	61:233	Specific competing constructions such as active/passive, verbal particle placement or thatdeletion in English are often the object of study (Szmrecsanyi, 2005; Gries, 2005; Dubey et al. , 2005; Jager, 2006), but the effect can also be generalized to syntactic phrase-structure rules or combinatorial categories (Reitter et al. , 2006a).
---------------------------------------------------
