Another area of research on opinion mining is to extract and summarize users opinions from product reviews (Hu and Liu, 2004; Liu et al. , 2005; Popescu and Etzioni, 2005). 
(2003), Popescu and Etzioni (2005)). 
Some researchers are starting to work on this problem (e.g. , Popescu and Etzioni (2005)). 
Beyond document level sentiment classification in online product reviews, (Hu and Liu, 2004; Popescu and Etzioni, 2005) concentrated on mining and summarizing reviews by extracting opinion sentences regarding product features. 
Popescu and Etzioni (2005) achieved high-precision opinion phrases extraction by using relaxation labeling. 
