Mihalcea (2005) reports an overall score of 52.2% for this data. 
The TexRank algorithm (Mihalcea, 2005) for WSD creates a complete weighted graph (e.g. a graph where every pair of distinct vertices is connected by a weighted edge) formed by the synsets of the words in the input context. 
Recent work has applied random walks to NLP tasks such as PP attachment (Toutanova et al. , 2004), word sense disambiguation (Mihalcea, 2005; Tarau et al. , 2005), and query expansion (Collins-Thompson and Callan, 2005). 
(Mihalcea, 2005) and (Sinha and Mihalcea, 2007) use WordNet relations as a knowledge source, but neither of them specify which particular version did they use. 
These results are not the same as those reported in (Mihalcea, 2005) for the Senseval 2 data (nouns 57.5%, verbs: 36.5%, adjective: 56.7%, adverb: 70.9%, for an average precision of 54.2%), because of the difference in computing word similarities. 
