This assumption is very common in multilingual parsing (see, for example, Cowan et al. , 2005, and Buchholz et al. , 2006). 
In sequential tagging models such as (Adler and Elhadad, 2006; Bar-Haim et al., 2007; Smith et al., 2005) weights are assigned according to a language model based on linear context. 
There are also morphological disambiguators designed specifically for Hebrew (Segal, 2000; Bar-Haim et al. , 2005). 
(2005) in including case, mood, and nunation 4Smith et al. 
The MA used is the open-source hunmorph analyzer (Tron et al. , 2005) with the morphdb.hu Hungarian morphological resource, the ME is the OpenNLP package (Baldridge et al. , 2001). 
