2 Related work Many approaches have been proposed for WSD, but only a few are designed for specific applications, such as MT. Existing multilingual approaches can be classified as (a) knowledge-based approaches, which make use of linguistic knowledge manually codified or extracted from lexical resources (Pedersen, 1997; Dorr and Katsova, 1998); (b) corpus-based approaches, which make use of knowledge automatically acquired from text using machine learning algorithms (Lee, 2002; Vickrey et al. , 2005); and (c) hybrid approaches, which employ techniques from the two other approaches (Zinovjeva, 2000).


Recent studies have also shown that WSD can bene t machine translation (Vickrey et al. , 2005) and information retrieval (Stokoe, 2005).


Note that the experiments in (Carpuat and Wu, 2005) did not use a state-of-the-art MT system, while the experiments in (Vickrey et al. , 2005) were not done using a full-fledged MT system and the evaluation was not on how well each source sentence was translated as a whole.


In another work (Vickrey et al. , 2005), the WSD problem was recast as a word translation task.


Applications such as machine translation (Vickrey et al. , 2005) and information retrieval (Stokoe, 2005) have also been shown to benefit from WSD.


