This approach was successfully used in large vocabulary speech recognition (Schwenk and Gauvain, 2005), and we are interested here if similar ideas can be applied to statistical machine translation.


4.2 Using the continuous space language model The continuous space language model was trained on exactly the same data than the back-off reference language model, using the resampling algorithm described in (Schwenk and Gauvain, 2005).


Training is done using a resampling algorithm (Schwenk and Gauvain, 2005).


They have previously been shown to outperform standard back-off models in terms of perplexity and word error rate on medium and large speech recognition tasks (Xu et al. , 2003; Emami and Jelinek, 2004; Schwenk and Gauvain, 2004; Schwenk, 2005).


