E06-1043:1	198:209	Lin (1999) and Wermter and Hahn (2005) go one step further and look into a linguistic property of non-compositional compoundstheir lexical fixednessto identify them.
---------------------------------------------------
P06-1099:2	17:105	(2004), Wermter and Hahn (2005)).
---------------------------------------------------
P06-1099:3	31:105	Although Evert and Krenn (2001) and Wermter and Hahn (2004) provide significance testing of some AMs with respect to mere frequency counting for collocation extraction, they do not differentiate whether this is due to differences in the ranking of true positives or true negatives or a combination thereof.2 As for studies on ATR (e.g. , Wermter and Hahn (2005) or Nenadic et al.
---------------------------------------------------
P06-1099:4	23:105	Recently, more linguistically informed algorithms have been introduced both for CE (Wermter and Hahn, 2004) and for ATR (Wermter and Hahn, 2005), which have been shown to outperform several of the statisticsonly metrics.
---------------------------------------------------
P06-1099:5	55:105	Concerning more recent linguistically grounded AMs, we looked at limited syntagmatic modifiability (LSM) for CE (Wermter and Hahn, 2004) and limited paradigmatic modifiability (LPM) for ATR (Wermter and Hahn, 2005).
---------------------------------------------------
P06-1099:6	48:105	As for domain-specific automatic term recognition (ATR), we used a biomedical term candidate set put forth by Wermter and Hahn (2005), who, after shallow syntactic analysis, extracted 31,017 trigram term candidates occurring at least eight times out of a 104-million-word MEDLINE corpus.
---------------------------------------------------
P06-1099:7	54:105	Evert and Krenn (2001) and Krenn and Evert (2001)) and also for ATR (see Wermter and Hahn (2005)).
---------------------------------------------------
