However sense-tagged data is expensive and furthermore the predominant sense of a word will vary depending on the domain (Koeling et al., 2005; Chan and Ng, 2007). 
The experiments were performed on a publicly available corpus which was designed to study the effect of domain in WSD (Koeling et al., 2005). 
In addition, supervised techniques may not yield reliable results when the distributions of the semantic classes are different in the training and test datasets (Agirre and Martinez, 2004; Koeling et al., 2005). 
The fact that the selected nouns are related to the target domain makes the (Koeling et al., 2005) corpus more demanding than the DSO corpus, because one would expect the performance of a generic WSD system to drop when moving to the domain corpus for domainrelated words (cf. 
We performed on a publicly available corpus which was designed to study the effect of domains in WSD (Koeling et al., 2005). 
