P06-2034:1	63:160	The syntactic features introduced by Collins (2000) for reranking syntactic parse trees have been proven successfully in both English and Spanish (Cowan and Collins, 2005).
---------------------------------------------------
P06-2018:2	82:184	In comparison, Cowan and Collins (2005) report an f-score of 85.1% ( 70) using a version of Collins parser adapted for Cast3LB, and using reranking to boost perforsuch as grup.nom.ms (masculine singular), grup.nom.fs (feminine singular), grup.nom.mp (masculine plural) etc. This number and gender information is already encoded in the POS tags of nouns heading these constituents.
---------------------------------------------------
P06-2018:3	74:184	Prior to parsing, we perform one of the tree transformations described by Cowan and Collins (2005), i.e. we add a CP and SBAR nodes to subordinate and relative clauses.
---------------------------------------------------
W06-2920:4	43:416	Collins (1997)s parser and its reimplementation and extension by Bikel (2002) have by now been applied to a variety of languages: English (Collins, 1999), Czech (Collins et al. , 1999), German (Dubey and Keller, 2003), Spanish (Cowan and Collins, 2005), French (Arun and Keller, 2005), Chinese (Bikel, 2002) and, according to Dan Bikels web page, Arabic.
---------------------------------------------------
C08-1081:5	120:137	With regard to morphological features this is in line with a number of recent studies showing the importance of morphology for parsing languages with less rigid word order, including work on Spanish (Cowan and Collins, 2005), Hebrew (Tsarfaty, 2006; Tsarfaty and Simaan, 2007), Turkish (Eryigit et al., 2006), and Swedish (vrelid and Nivre, 2007).
---------------------------------------------------
N07-1051:6	198:232	5 Multilingual Parsing Most research on parsing has focused on English and parsing performance on other languages is generally significantly lower.3 Recently, there have been some attempts to adapt parsers developed for English to other languages (Levy and Manning, 2003; Cowan and Collins, 2005).
---------------------------------------------------
