Two such algorithms for segmentation are described in (Foltz, 1998) and (Olney and Cai, 2005). 
Following (Olney and Cai, 2005), we built our LSA space using dialogue contributions as the atomic text unit. 
The first corpus, which we call the Olney & Cai corpus, is a set of dialogues selected randomly from the same corpus Olney and Cai obtained their corpus from (Olney and Cai, 2005). 
Two LSA-based algorithms for segmentation are described in (Foltz, 1998) and (Olney and Cai, 2005). 
Following (Olney and Cai, 2005), we built our LSA space using dialogue contributions as the atomic text unit. 
