1.2 Related Work Recently, discriminative methods for alignment have rivaled the quality of IBM Model 4 alignments (Liu et al., 2005; Ittycheriah and Roukos, 2005; Taskar et al., 2005; Moore et al., 2006; Fraser and Marcu, 2007b). 
The first baseline, matching is the matching SVM described in Section 4.2.1, which is a re-implementation of the state-of-theart work in (Taskar et al. , 2005)3. 
Discriminative models have been tried recently for word-alignment (Taskar et al. , 2005; Moore, 2005) as these models give the ability to harness variety of complex features which cannot be provided in the generative models. 
We use an online learning framework called MIRA (McDonald et al. , 2005; Crammer and Singer, 2003) for training a discriminative model for the word alignment task (Taskar et al. , 2005; Moore, 2005). 
Permutation space methods include weighted maximum matching (Taskar et al. , 2005), and approximations to maximum matching like competitive linking (Melamed, 2000). 
