P07-1097:1	49:204	2.2 The Pyramid Extension The vital/okay distinction has been identified as a weakness in the TREC nugget-based evaluation methodology (Hildebrandt et al. , 2004; Lin and Demner-Fushman, 2005; Lin and DemnerFushman, 2006).
---------------------------------------------------
N07-4015:2	16:40	QA and summarization evaluations (Lin and Demner-Fushman, 2005; Nenkova and Passonneau, 2004) have been carried out by using a set of manually created nuggets and the comparison procedure itself is either automatic using n-gram overlap counting or manually performed.
---------------------------------------------------
N07-1027:3	132:209	We employed POURPRE (Lin and Demner-Fushman, 2005), a recently developed method for automatically evaluating answers to complex questions.
---------------------------------------------------
H05-1039:4	125:207	Recently, researchers have started automatic question answering evaluation (Xu et al. , 2004; Lin and Demner-Fushman, 2005; Soricut and Brill, 2004).
---------------------------------------------------
P06-2068:5	55:198	However, the recent introduction of POURPRE, an automatic evaluation metric for the nugget-based evaluation methodology (Lin and Demner-Fushman, 2005), fills this evaluation gap and makes possible the work reported here; cf.
---------------------------------------------------
N06-1049:6	43:176	This human involvement has been identified as a bottleneck in the evaluation process, although we have recently developed an automatic scoring metric called POURPRE that correlates well with human judgments (Lin and Demner-Fushman, 2005a).
---------------------------------------------------
N06-1049:7	47:176	Previously, we have argued that the vital/okay distinction is a source of instability in the nuggetbased evaluation methodology, especially given the manner in which F-score is calculated (Hildebrandt et al. , 2004; Lin and Demner-Fushman, 2005a).
---------------------------------------------------
N06-1049:8	23:176	The nugget-based paradigm has been previously detailed in a number of papers (Voorhees, 2003; Hildebrandt et al. , 2004; Lin and Demner-Fushman, 2005a); here, we present only a short summary.
---------------------------------------------------
N06-1049:9	70:176	As an example of this intellectual discourse, the recently-developed POURPRE metric for automatically evaluating answers to complex questions (Lin and Demner-Fushman, 2005a) employs n-gram overlap to compare system responses to reference output, an idea originally implemented in the ROUGE metric for summarization evaluation (Lin and Hovy, 2003).
---------------------------------------------------
N06-1048:10	34:178	(Breck et al. , 2000; Lin and Demner-Fushman, 2005).
---------------------------------------------------
N06-1048:11	90:178	Pourpre and Rouge scores reproduced from (Lin and Demner-Fushman, 2005).
---------------------------------------------------
N06-1048:12	22:178	1 Nuggeteer implements the pyramid scoring system from (Lin and Demner-Fushman, 2006), designed to soften the dis375 Qid 87.8: other question for target Enrico Fermi 1 vital belived in particals existence and named it neutrino 2 vital Called the atomic Bomb an evil thing 3 okay Achieved the first controlled nuclear chain reaction 4 vital Designed and built the first nuclear reactor 5 okay Concluded that the atmosphere was in no real danger before Trinity test 6 okay co-developer of the atomic bomb 7 okay pointed out that the galaxy is 100,000 light years across Figure 1: The answer key to an other question from 2005.
---------------------------------------------------
N07-2055:13	21:106	Similarly, in question-answering (QA) evaluations, gold-standard answers use manually created nuggets and compare them against system-produced answers broken down into n-gram pieces, as shown in POURPRE (Lin and Demner-Fushman, 2005) and NUGGETEER (Marton and Radul, 2006).
---------------------------------------------------
J07-1005:14	150:684	This section, which elaborates on preliminary results reported in Demner-Fushman and Lin (2005), describes extraction algorithms for population, problems, interventions, outcomes, and the strength of evidence.
---------------------------------------------------
J07-1005:15	553:684	We have noted that many of these desiderata make complex question answering quite similar to multi-document summarization (Lin and Demner-Fushman 2005b), but these features are also beyond the capabilities of current summarization systems.
---------------------------------------------------
J07-1005:16	640:684	A number of studies (e.g., Hildebrandt, Katz, and Lin 2004) have pointed out shortcomings of the original nugget scoring model, although a number of these issues have been recently addressed (Lin and Demner-Fushman 2005a, 2006b).
---------------------------------------------------
