Since 2004, the main task at the TREC QA tracks has consisted of question series organized around topics (called targets)which can be people, organizations, entities, or events (Voorhees, 2004; Voorhees, 2005). 
Also, a score distribution heavily skewed towards zero makes meta-analyses of evaluation stability difficult to perform (Voorhees, 2005). 
The current TREC QA test set contains factoid and list questions grouped into different series, where each series has the target of a definition associated with it (Overview of the TREC 2004 Question Answering Track, Voorhees 2005). 
Also, as pointed out by Voorhees (2005), a score distribution heavily skewed towards zero makes meta-analysis of evaluation stability hard to perform. 
The so-called definition or other questions at recent TREC evaluations (Voorhees, 2005) serve as good examples: good answers to these questions include interesting nuggets about a particular person, organization, entity, or event. 
