W06-3702:1	40:160	Resource grammars are now available for several languages, including English, Japanese (Rayner et al. , 2005b), French (Bouillon et al. , 2006) and Spanish.
---------------------------------------------------
W06-3702:2	12:160	Even though statistical systems exhibit many desirable properties (purely datadriven, domain independence), grammar-based systems utilizing probabilistic context-free grammar tuning appear to deliver better results when training data is sparse (Rayner et al. , 2005a).
---------------------------------------------------
W06-3702:3	43:160	In previous studies (Rayner et al. , 2005a; Starlander et al. , 2005), we showed that the grammar-based recognizer performs much better than the statistical one on in-coverage utterances, and rather worse on out-of-coverage ones.
---------------------------------------------------
W06-3702:4	56:160	We have focused on performance metrics defined in terms of recognition and translation quality, and tested the system on nave users without any medical background (Bouillon et al. , 2005; Rayner et al. , 2005a; Starlander et al. , 2005).
---------------------------------------------------
