To our knowledge, the growth ratio and the number of extracted facts are several orders of magnitude higher than in any of the previous studies on fact extraction based on either hand-written extraction rules (Cafarella et al. , 2005), or bootstrapping for relation and information extraction (Agichtein and Gravano, 2000; Lita and Carbonell, 2004). 
As such, the resulting metric for evaluating recall used in (Cafarella et al. , 2005) is somewhat similar to, though more relaxed than, the recall score over the Gold set introduced in the previous section. 
A detailed description of KNOWITNOW appears in (Cafarella et al. , 2005). 
Examples include fact extraction systems such as (Cafarella et al., 2005) and entity extraction systems such as (Pasca, 2007). 
This approach is very common in both the NLP and Semantic Web communities (Cimiano and Staab, 2004; Cafarella et al., 2005; Pantel and Pennacchiotti, 2006; Pasca et al., 2006). 
