Previous work mined web data for aspects associated with topics (Hu and Liu, 2004; Popescu et al., 2005).


A number of works in product review mining (Hu and Liu, 2004; Popescu et al., 2005; Kobayashi et al., 2005; Bloom et al., 2007) automatically find features of the reviewed products.


Product review mining work has explored finding opinions with respect to, or in conjunction with, aspects (Hu and Liu, 2004; Popescu et al., 2005); however, in our work, we need to find 232 information in the other direction  that is, given the opinion, what is the opinion about.


