Morphological analysis has been used for improving Arabic-English translation (Lee, 2004), for SerbianEnglish translation (Popovic et al. , 2005) as well as for Czech-English translation (Goldwater and McClosky, 2005). 
Goldwater and Mcclosky (2005) improved Czech-English translation by applying different heuristics to increase the equivalence of Czech and English text. 
Some used stem and morphological analysis for UNKs such as (Goldwater and McClosky, 2005). 
This reduction can be achieved by increasing training data or via morphologically driven preprocessing (Goldwater and McClosky, 2005). 
Recent publications on the effect of morphology on SMT quality focused on morphologically rich languages such as German (Nieen and Ney, 2004); Spanish, Catalan, and Serbian (Popovic and Ney, 2004); and Czech (Goldwater and McClosky, 2005). 
