html 3 http://www.cis.upenn.edu/~treebank/tokenization.html 4 http://www.nist.gov/speech/tests/ace 125 ERT 5 (Hacioglu et al. 2005; Chen & Hacioglu, 2006).


It turns out though, (Hacioglu, 2005) that the cascade model in (Hacioglu et al. , 2005) did not change to a mention view sequence classification6 (as we did in Section 3.3) in the tasks following the entity detection, to allow the system to use longer range features.


In our approach, all documents are preprocessed with a syntactic phrase chunker (Hacioglu, 2004) and the EXERT 1 system (Hacioglu et al. 2005; Chen & Hacioglu, 2006), a named-entity detection and co-reference resolution system that was developed for the ACE 2 project.


