P08-2055:1	86:95	So, our algorithm would also help the best parsing algorithms during rescoring (Charniak et al., 2005; McClosky et al., 2006).
---------------------------------------------------
P08-2055:2	47:95	In our work, we use a version of the Charniaks parser from (Aug. 16, 2005) to parse the re-segmented SWBD corpus (Kahn et al., 2005), and extract the parse sub-trees from the parse trees as experimental data.
---------------------------------------------------
P08-2055:3	6:95	Using Conditional Maximum Entropy (CME) classifier with all the selected features, we reached an annotation error rate of 26.0% in the SWBD corpus, compared with a subtree error rate of 41.91%, a closely related benchmark with the Charniak parser from (Kahn et al., 2005).
---------------------------------------------------
P08-2055:4	27:95	Long distance structural features in statistical parsing lead to significant improvements (Collins et al., 2000; Charniak et al., 2005).
---------------------------------------------------
P08-2055:5	48:95	The parsers training procedure is the same as (Kahn et al., 2005).
---------------------------------------------------
N06-2019:6	18:84	Moreover, this work showed that collateral damage to parse accuracy caused by repairs could be averted by deleting them prior to parsing, and this finding has been confirmed in subsequent studies (Kahn et al. , 2005; Harper et al. , 2005).
---------------------------------------------------
N06-2019:7	62:84	Results shown for repair detection accuracy and its impact on parsing are consistent with previous work (Charniak and Johnson, 2001; Kahn et al. , 2005; Harper et al. , 2005).
---------------------------------------------------
N06-2019:8	79:84	Alternative methods of integrating detected filler information, such as parse reranking (Kahn et al. , 2005), also merit investigation.
---------------------------------------------------
W05-1519:9	11:152	A clear benefit of having accurate edited regions for parsing has been demonstrated by a concurrent effort on parsing conversational speech [Kahn et al 2005].
---------------------------------------------------
W05-1519:10	9:152	Because of the availability of the Switchboard corpus [Godfrey et al. 1992] and other conversational telephone speech (CTS) corpora, there has been an increasing interest in improving the performance of identifying the edited regions for parsing disfluent sentences [Charniak and Johnson 2001, Johnson and Charniak 2004, Ostendorf et al. 2004, Liu et al. 2005].
---------------------------------------------------
W05-1519:11	133:152	[Kahn et al. 2005] also showed that prosody information could help parse disfluent sentences.
---------------------------------------------------
D09-1080:12	23:179	State-ofthe-art methods for edit region detection such as (Johnson and Charniak, 2004; Zhang and Weng, 2005; Kahn et al., 2005; Honal and Schultz, 2005) model speech disfluencies as a noisy channel model, though direct classification models have also shown promise (Fitzgerald et al., 2009; Liu et al., 2004).
---------------------------------------------------
D09-1080:13	48:179	While the SWBD corpus has been used in some previous simple disfluency labeling work (e.g., Johnson and Charniak, 2004; Kahn et al., 2005), we consider the SSR for its fine-grained error annotations.
---------------------------------------------------
P06-1071:14	162:208	When Gaussian smoothing (Chen and Rosenfeld, 1999), labeled as +Gau, and postprocessing (Zhang and Weng, 2005), labeled as +post, are added, we observe 17.66% relative improvement (or 3.85% absolute) over the previous best f-score of 78.2 from Kahn et al.
---------------------------------------------------
P06-1071:15	113:208	The resulting sentences fit more closely with the boundaries that can be detected through automatic procedures (e.g. , Liu et al. , 2005).
---------------------------------------------------
P06-1071:16	132:208	In particular, 4 and p have f-scores of about 70% and 60% respectively (Wong et al. , 2005).
---------------------------------------------------
P06-1071:17	185:208	We apply the latest version of Charniaks parser (2005-08-16) and the same procedure as Charniak and Johnson (2001) and Kahn et al.
---------------------------------------------------
P06-1071:18	6:208	When additional features and their combinations are used, the PFS gives 17.66% relative improvement over the previously reported best result in edit region identification on Switchboard corpus (Kahn et al. , 2005), which leads to a 20% relative error reduction in parsing the Switchboard corpus when gold edits are used as the upper bound.
---------------------------------------------------
P06-1071:19	137:208	4.3 Experiments The best result on the UW Switchboard for edit region identification uses a TAG-based approach (Kahn et al. , 2005).
---------------------------------------------------
P06-1021:20	46:158	A classifier was developed to predict three break indices at each word boundary based on variations in pitch, duration and energy associated with word, syllable or sub-syllabic constituents (Shriberg et al. , 2005; Sonmez et al. , 1998).
---------------------------------------------------
P06-1021:21	64:158	gory et al. , 2004; Lease et al. , 2005; Kahn et al. , 2005) as described further in Section 6.
---------------------------------------------------
P06-1021:22	157:158	The strengths of these simple tree-based techniques should be combinable with sophisticated string-based (Johnson and Charniak, 2004; Liu, 2004; Zhang and Weng, 2005) approaches by applying the methods of Wieling et al.
---------------------------------------------------
P06-1021:23	59:158	Random forests and hidden Markov models provide marginal improvements at considerable computational cost (Harper et al. , 2005).
---------------------------------------------------
