This corresponds to the factorial CRF structure described in Sutton and McCallum (2005).


 multi-task learning (Ando and Zhang, 2005; Caruana, 1997; Sutton and McCallum, 2005; Zhang et al., 2005) in which the task (and label set) is allowed to vary from source to target.


Similar to (Sutton and McCallum, 2005), in our system we also train a cascade of linear-chain CRF for the subtasks.


Sutton and McCallum (Sutton and McCallum, 2005) suggested that in many cases exact inference can be too expensive and thus formidable.


Hinging on this idea, one way to avoid error propagation in chaining subtasks such as segmentation and POS tagging is to exploit the learning transfer (Sutton and McCallum, 2005) among subtasks, typically through joint inference.


