Data For training and testing our algorithm, we employed a corpus of football game summaries collected by Barzilay and Lapata (2005). 
Barzilay and Lapata (2005) extended this approach but applying it to a sports domain (American football), similarly viewing content selection as a classification task and additionally taking account of contextual dependencies between data, and found that this improved results compared to a content-agnostic baseline. 
Since our system involves data-to-text NLG, content determination has more in common with the twostage process of (Sripada, Reiter et al, 2001) than the classification process of (Barzilay and Lapata, 2005). 
The dataset we used was collected by Barzilay and Lapata (2005). 
Similar methods for this problem have been employed by Barzilay and Lapata (2005) and Duboue and McKeown (2003). 
