The elements include source of opinions who expresses an opinion (Choi et al., 2005); target of opinions which is a receptor of an opinion (Popescu and Etzioni, 2005); opinion expression which delivers an opinion (Wilson et al., 2005b). 
3 Related Work Please see (Wiebe and Riloff, 2005; Choi et al. , 2005; Wilson et al. , 2005) for discussions of related work in automatic opinion and sentiment analysis. 
Kim and Hovy (2005b) and Choi et al. 
Previous workonsentimentanalysishascoveredawiderange of tasks, including polarity classification (Pang et al. , 2002; Turney, 2002), opinion extraction (Pang and Lee, 2004), and opinion source assignment (Choi et al. , 2005; Choi et al. , 2006). 
Another related works are (Choi et al. , 2005; Kim and Hovy, 2005). 
