With the goal of improving robustness to ASR errors, (Favre et al., 2005) described a finite-state machine based approach to take as input ASR n-best strings and extract the NEs.


Most previous studies of the NER of speech data used generative models such as hidden Markov models (HMMs) (Miller et al. , 1999; Palmer and Ostendorf, 2001; Horlock and King, 2003b; Bechet et al. , 2004; Favre et al. , 2005).


Generative NER models were used for multipass ASR and NER searches using word lattices (Horlock and King, 2003b; Bechet et al. , 2004; Favre et al. , 2005).


