The advantages of the LF notation are mantfold: a0 it allows a simple syntax/semantics interface a0 it is user friendly a0 it has positional syntactic arguments that ease other NLP tasks such as textual interpretationa and textual inference a0 if predicates are disambiguated with respect to a general ontology such as WordNet it leads to concept predicates a0 it is easily customizable (for example to distinguish between arguments and adjuncts) For details about the principles of Logic Forms read Chapter 2 in (Rus, 2002), (Rus and Moldovan, 2002) and (Hobbs, 1986).


This has involved building a large knowledge base of commonsense and domain knowledge (see Hobbs et al. , 1986), and developing procedures for using this knowledge for the interpretation of discourse.


It has been implemented in the TACITUS System (Stickel, 1982; Hobbs, 1986; Hobbs and Martin, 1987) and has been and is being used to solve a variety of interpretation problems in casualty reports, which are messages about breakdowns in machinery, as well as in other texts3 It~ is well-known that people understand discourse so well ~ because they know so much.


This formalism, used in the implementation of TACITUS (Hobbs, 1986-2), accommodates a large variety of discourse inferences and, moreover, provides an elegant manner of localizing ambiguities, as was shown in (Bear and Hobbs, 1988).


In these examples the system effectively performs coercion of the verb arguments (Hobbs, 1986).


