The tuples are formatted according the Common Answer Specification (GAS) format (Boisen et al, 1989).


Special provision is made for single element answers, sc that a scalar REF and a HYP which is a table containing a single element are judged to be equivalent That is, a scalar REF will match either a scalar or a single elemenl 1The first implementation of this software was by Lance Ramshaw (Boisen et al. , 19891.


The content of this reference answer is determined both by domainindependent linguistic principles (Boisen et al. , 1989) and domain-specific stipulation.


Boisen et al. had outlined such a procedure at the October 1989 DARPA Workshop \[4\], and Lyn outlined some of the details of the present implementation for the ATIS domain.


