5 Other Evaluation Methodologies This approach to evaluation shares many characteristics with the methods used for the DARPA-sponsored Message Understanding Conferences (Sundheim, 1989; Sundheim, 1991). 
It is necessary to define the evaluation in term:; of a task that is being performed (Sundheim 1989; Napier 1989). 
Application and Evaluation This approach has been implemented as part of the PROTEUS message understanding system, and evaluated as part of the recent MUCK-II conference (Sundheim 1989a). 
There is no consensus on how to evaluate the correctness of semantic representations, so output has to be in terms of some specific application task such as databzse answering or template fill (Sundheim 1989). 
This conference involved the development of a system for processing Navy OPREP (OPerational REPort) messages; these messages are reports of sightings and engagements at sea (Sundheim 1989b). 
