WORDS AND WORD CLASSES We have also used the Learner to acquire a set of vocabulary items and word classes for a class grammar (Derr and Schwartz, 1989) for use in HARC, the BBN Spoken Language System (Boisen, et al, 1989a), which incorporates the ACFG system as its natural language component.


\[4\] Derr, A. and R.M. Schwartz (1989) "A Statistical Class Grammar for Measunng Speech Recognition Perforrnance" Elsewhere in these Proceedings of the Oct. 1989 DARPA Speech and Natural Language Workshop Morgan Kaulinann Publishers, Inc. , Oct. 1989.


