(Moore et al. , 1989)) argue that grammatical analysis may improve recognition accuracy, our current experiments have as yet not been able to reveal a clear advantage in this respect.


The use of concept spotting is common in spokenlanguage information systems (Ward, 1989; Jackson et al. , 1991; Aust et al. , 1995; Allen et al. , 1996).


2 Corpus For our corpus of sentences we selected a subset of a corpus developed previously (see Price et aL 1989) for investigating the perceptual role of prosodic information in disambiguating sentences.


We used the DECIPHER system (Weintraub et al. 1989) to label and time-align the speech, and verified that the sentences were, by this measure as well as by the earlier perceptual verification, truly ambiguous phonetically.


