In the 21 category model reported in Kupiec (1989) only 129 equivalence classes were required to cover a 30,000 word dictionary. 
The results suggest that a completely unconstrained initial model does not produce good quality results, and that one 1The technique was originally developed by Kupiec (Kupiec, 1989). 
The tagger itself is based on the Hidden Markov Model (Baum, 1972) and word equivalence classes (Kupiec, 1989). 
2 Background Trigger-pair modelling research has been pursued within the field of language modelling for speech recognition over the last decade (Beeferman et ah, 1997; Della Pietra et al., 1992; Kupiec, 1989; Lau, 1994; Lau et ah, 1993; Rosenfeld, 1996). 
In this regard, word equivalence 92 classes were used (Kupiec, 1989). 
