Traditionally such semantic knowledge is handcrafted, though some software aids exist to enable greater productivity (Ayuso et al. , 1987; Bates, 1989; Grishman et al. , 1986; Weischedel, et al. , 1989).


Our own natural language database query systems, JANUS (Weischedel et al. 1989), ParlanceTM, 1 and Delphi (Stallard 1989), have used these techniques quite successfully.


Traditionally such semantic knowledge is handcrafted, though some software aids exist to enable greater productivity (Ayuso, Shaked, and Weischedel 1987; Bates 1989; Grishman, Hirschman, and Nhan 1986; Weischedel et al. 1989).


2 Weischedel, et al. 1989.


