Working from the 1979 edition of the Collins Dictionary of the English Language available through ACL-DCI (Liberman, 1989), we constructed lexicons for PC-KIMMO (Antworth, 1990), a public domain implementation of a two-level processor.


Les tables ont dtd construites  l'aide de dietionaires dlectroniques (en particulier "Collins Dictionary of the English Language, 1979 edition") distribu6es par ACL DCI (Liberman, 1989).


