Traditionally such semantic knowledge is handcrafted, though some software aids exist to enable greater productivity (Ayuso et al. , 1987; Bates, 1989; Grishman et al. , 1986; Weischedel, et al. , 1989).


First, it suggests that the great boost in productivity reported in (Bates, 1989) by using the Learner to port the Parlance system may be extended to the ACFG system.


Previous work with the Learner (Bates, 1989) has demonstrated a speed-up of ten times or more, compared to manual acquisition of the same information.


BBN has developed a software package, the Learner, as a porting tool for non-expert users (Bates, 1989; BBN Parlance Learner Manual, 1989).


Traditionally such semantic knowledge is handcrafted, though some software aids exist to enable greater productivity (Ayuso, Shaked, and Weischedel 1987; Bates 1989; Grishman, Hirschman, and Nhan 1986; Weischedel et al. 1989).


