Although the heuristic of choosing tile longest possible substring beginning at the left, that can be parsed as a sentence could be tried (e.g. Grishman and Sterling, 1989), solnetimes, the best fraglnentary analysis of a sentence can only be found by parsing an intermediate or terminal substring that excludes the leftmost words.


It was run as a preprocessor to Grishman's Proteus system for the MUC-3 competition (Grishman and Sterling 1989).


Proc . DARPA Speech and Natural Language Workshop, Morgan Kaufman, 1990 (proceedings of the conference at Harwich Port, MA, Oct . 15-18, 1989) . [3] Grishman, R. , and Sterling, J . Information Extraction and Semantic Constraints . Proc . 13th Int' I Conf Computational Linguistics (COLING 90), Helsinki, August 20-25, 1990 . [4] Sager, N . Natural Language Information Processing, Addison-Wesley, 1981 .


