The use of concept spotting is common in spokenlanguage information systems (Ward, 1989; Jackson et al. , 1991; Aust et al. , 1995; Allen et al. , 1996).


The ARGOT dialogue system (Litman & Allen, 1989) takes one important step toward recognizing discourse structures by distinguishing the speaker's domain plan, such as for assembling parts, from his or her discourse plan, such as to clarify which domain plans are being performed.


Furthermore, it has become clear that the algorithms and heuristics needed to design spoken language systems will be different from those required for keyboard system s (Cohen, 1984; Hindle, 1983; Oviatt & Cohen, 1988 ~: 1989; Ward, 1989).


