J93-2006:1	40:573	The effectiveness of such models is well known (DeRose 1988; Church 1988; Kupiec 1989; Jelinek 1985), and they are currently in use in parsers (e.g. de Marcken 1990).
---------------------------------------------------
H91-1046:2	20:136	Kupiec (1989) has experimented with the inclusion of networks to model mixed-order dependencies.
---------------------------------------------------
H91-1046:3	59:136	The vocabulary entry may be a word or an equivalence class based on categories (Kupiec, 1989).
---------------------------------------------------
J93-1001:4	132:408	As a result, the empirical approach has been adopted by almost all contemporary part-of-speech programs: Bahl and Mercer (1976), Leech, Garside, and Atwell (1983), Jelinek (1985), Deroualt and Merialdo (1986), Garside, Leech, and Sampson (1987), Church (1988), DeRose (1988), Hindle (1989), Kupiec (1989, 1992), Ayuso et al.
---------------------------------------------------
C92-1060:5	134:200	Instead, only common words are represented individually; the rest of the words in the dictionary are partitioned into word equivalence classes (Kupiec, 1989) such that all words that can function as a particular set of part-of-speech categori~ are given the same label.
---------------------------------------------------
W93-0111:6	186:372	This approach is similar in spirit to the iterative computational approaches of the Hidden Markov Models (Kupiec, 1989; Kupiec, 1992; Rabiner, 1989), though our zeroth order solution begins quite close to the desired result, so it should converge very close to a global optimum.
---------------------------------------------------
