In \[Church et al. , 1989\] and \[Church'et ai. 
7 PREPROCESSING WITH A PARSER Hindle (Church et al. 1989) has found it helpful to preprocess the input with the Fidditch parser (Hindle 1983a, 1983b) to identify associations between verbs and arguments, and postulate semantic classes for nouns on this basis. 
Church and ttanks 1989 and Church et al. 1990 develop a battery of statistical methods to induce linguistic regularities. 
We can mentionhere only part of this work: (Berry-Rogghe, 1973; Church et al. , 1989; Smadja,1993;Lin,1998;KrennandEvert,2001) for monolingualextraction, and (Kupiec, 1993; Wu,1994;Smadjaetal. 
90% Accuracy is Not Enough Existing pre-processors \[Church et al. , 1989; Zernik et al. , 1991\] which have used corpusbased collocations, have attained levels of acACRES BE COLING-92, NANTES, 23-28 Ao~r 1992 1 3 0 9 I'~toc. 
