Recently, we have begun porting our ACFG natural language system (Boisen, et al, 1989b) to a personnel database domain, a domain for which Parlance had been configured using the Learner.


WORDS AND WORD CLASSES We have also used the Learner to acquire a set of vocabulary items and word classes for a class grammar (Derr and Schwartz, 1989) for use in HARC, the BBN Spoken Language System (Boisen, et al, 1989a), which incorporates the ACFG system as its natural language component.


