Other well-known instances are Voyager (Zue et al. 1989) and the individual ATIS collections (Hirschman et al. 1993) which involved up to a hundred subjects or (again) up to 12,000 utterances.


The recognizer for these systems is the SUMMIT system (Zue et al. 1989), which uses a segmental-based framework and includes an auditory model in the front-end processing.


Subsequent processing by the natural language and response generation components was done automatically by the computer (Zue et al. 1989).


