We are particularly exploring probabilistic models for this processing, and have described experiments with various probabilistie models elsewhere (Aynso, et al, 1990; Meteer, et al. , 1991).


(Sinclair et al. 1987; p. xv) The experience of writing the COBUILD dictionary is documented in Sinclair (1987), a collection of articles from the COBUILD project; see Boguraev (1990) for a strong positive review of this collection.


(Waibel and Lee 1990; p. 4) A number of data collection efforts have helped to bring about this change in the speech community, especially the Texas Instruments' Digit Corpus (Leonard 1984), TIMIT and the DARPA Resource Management (RM) Database (Price et al. 1988).


