Experiments on the ATIS corpus For our experiments we used part-of-speech sequences of spoken-language transcriptions from the Air Travel Information System (ATIS) corpus (Hemphill et al. , 1990), with the labeled-bracketings of those sequences in the Penn Treebank (Marcus, 1991). 
This practical application of (Ward, 1990; Knight et al, 2001; Rayner et al, 2005; ten Bosch, 2005) is cast as an upgrade problem which must obey the following constraints. 
Work on more radical domain variance and on adapting treebank-induced LFG resources to analyse ATIS (Hemphill et al. , 1990) question material is described in Judge et al. 
The study is conducted on both a simple Air Travel Information System (ATIS) corpus (Hemphill et al. , 1990) and the more complex Wall Street Journal (WSJ) corpus (Marcus et al. , 1993). 
The examples given in this paper are taken from the ATIS (Air Travel Inquiry System; Hemphill et al, 1990) domain. 
