(1989), Wettler & Rapp (1989) and Church & Hanks (1990) describe algorithms which do this. 
Such preference information is very useful for natural language processing (Church K.W. et al. 1990; Hiddle D. et al. 1993; Rosenfeld R. 1994 and Zhou G.D. et al.1998). 
Among various language modeling approaches, ngram modeling has been widely used in many applications, such as speech recognition, machine translation (Katz 1987; Jelinek 1989; Gale and Church 1990; Brown et al. 1992; Yang et al. 1996; Bai et al 1998; Zhou et al 1999; Rosenfeld 2000; Gao et al 2002). 
Stochastic part-of-speech taggers such as those in Church (1988) and 6 This fact is being seriously challenged by current research (e.g. , Abney 1990; Hindle 1983), and might not be true in the near future. 
Such preference information is very useful for natural language processing (Church K.W. et al. 1990; Hiddle D. et al. 1993; Rosenfeld R. 1994 and Zhou G.D. et al.1998). 
