Bobrow (1990) and Chitrao and Grishman (1990) introduced statistical agendabased parsing techniques. 
The introduction of statistical parsing brought with an obvious tactic for ranking the agenda: (Bobrow, 1990) and (Chitrao and Grishman, 1990) first used probabilistic context free grammars (PCFGs) to generate probabilities for use in a figure of merit (FOM). 
Furthermore, there are observations by, for example, Chitrao and Grishman (1990), Tjong Kim Sang (1998, Sections 3.1 and 3.4), and van Noord et al. 
This can result in a "thrashing" effect as noted in Chitrao and Grishman (1990), where the system parses short constituents, even very low-probability ones, while avoiding combining them into longer constituents. 
Bobrow (1990) and Chitrao and Grishman (1990) introduced statistical agenda-based parsing techniques. 
