Pallett, et al. , "DARPA ATIS Test Results June 1990", in Proc.


Pallett, D.S., et al. "DARPA ATIS Test Results: June 1990" in Proceedings of the DARPA\] Speech and Natural Language Workshop" June 1990, pp.


The most commonly used method is probably hidden Markov models (HMM) (see, e.g., Bahl et al. 1983, Rabiner 1989, Picone 1990).


Speech Recognition For several years, the best performing speech recognition systems have been based on statistical pattern matching techniques (Pallett et al. 1990, Pallett 1991, Pallett et al. 1992, Pallett et al. 1993, Pallett et al. 1994).


There is also much current work using other pattern matching techniques (see, e.g., Ostendorf and Roukos 1989, Zue et al. 1992), including neural network-based approaches (see e.g., Hampshire and Weibel 1990) and hybrid HMM/neural network approaches (see e.g., Abrash et al. 1994).


