Some of them have been fully tested in real size texts (e.g. statistical methods (Yarowsky, 1992), (Yarowsky, 1994), (Miller and Teibel, 1991), knowledge based methods (Sussna, 1993), (Agirre and Rigau, 1996), or mixed methods (Richardson et al. , 1994), (Resnik, 1995)).


The arguments of prepositional relations are automatically categorized into semantically equivalent classes of WordNet (Miller and Teibel, 1991) concepts.


