A00-1014:1	70:168	(Seneff et al. , 1991; Lamel, 1998)), which represents an utterance as a set of attribute-value pairs.
---------------------------------------------------
J92-1004:2	429:508	However, the method we are currently using in the ATIS domain (Seneff et al. 1991) represents our most promising approach to this problem.
---------------------------------------------------
J92-1004:3	467:508	The second one, ATIS (Seneff et al. 1991), is a system for accessing data in the Official 80 Stephanie Seneff TINA: A Natural Language System for Spoken Language Applications Airline Guide and booking flights.
---------------------------------------------------
J92-1004:4	418:508	The recognizer can continue to propose hypotheses until one 78 Stephanie Seneff TINA: A Natural Language System for Spoken Language Applications successfully parses, or until a quitting criterion is reached, such as an upper bound on N. Whereas in the loosely coupled system the parser acts as a filter only on completed candidate solutions (Zue et al. 1991), the tightly coupled system allows the parser to discard partial theories that have no way of continuing.
---------------------------------------------------
