Later work introduced other FOMs formed from PCFG data (Kochman and Kupin, 1991); (Magerman and Marcus, 1991); and (Miller and Fox, 1994).


Magerman and Marcus (1991) use the geometric mean to compute a figure of merit that is independent of constituent length.


1991: Magerman and 127 Marcus, 1991).


and (Magerman and Marcus, 1991; Magerman and Weir, 1992) use the contextual information for struct;nral disambiguation.


292 Caraballo and Charniak Figures of Merit Magerman and Marcus (1991) use the geometric mean to compute a figure of merit that is independent of constituent length.


