J96-3007:1	10:137	Kupiec extended a SCFG that worked on CNF to a general CFG (Kupiec 1991).
---------------------------------------------------
J93-1002:2	503:516	By combining such techniques and relaxing the CNF constraint, for example, by adopting the trellis algorithm version of Baum-Welch re-estimation (Kupiec 1991), it might be possible to create a computationally tractable system operating with a realistic NL grammar that would only infer a new rule from a finite space of linguistically motivated possibilities in the face of parse failure or improbability.
---------------------------------------------------
J93-1002:3	56:516	Kupiec (1991) extends Baum-Welch re-estimation to arbitrary (nonCNF) CFGs.
---------------------------------------------------
C92-1060:4	71:200	The algorithm was originally formulated using solely the trellis representation (Kupiec, 1991) however the definitions that follow will Network NP =a. ADJP ' and (~ Det (~ Noun Q big black cat Figure 4: A Path through a Trelli= Diagram NP ADJP / AdJ AdJ Noun big black cat Figure 5: The EquivMent Tree ACRES DE COLING-92, NANTES, 23-28 Ao~r 1992 3 8 9 PROC.
---------------------------------------------------
C94-2138:5	15:118	Kupiec (1991) introduced a trellis based es-.
---------------------------------------------------
