(1990), Bates and Ayuso (1991), Pallett (1991)).


Recent work includes discussion of appropriate statistical methods and metrics for spoken dialogue systems (Bates and Ayuso 1993; Danieli et al. 1992; Hirschman et al. 1990; Hirschman and Pao 1993; Simpson and Fraser 1993), information extraction systems (Lewis 1991; Chinchor, Hirschman, and Lewis 1993; Chinchor and Sundheim 1995), and tagging reliability (Carletta 1996).


