Related Work 2.1 Modeling Collaboration Allen (1991) proposed a discourse model that differentiates among the shared and individual beliefs that agents might hold during collaboration.


3) Collaborative agents are interested in 1The notion of shared plan has been used in (Grosz and Sidner, 1990; Allen, 1991).


On the other hand, they may propose problem-solving actions (Allen, 1991; Lambert and Carberry, 1991; Ramshaw, 1991) that contribute not directly to the agents' domain goal, but to how they would go about achieving this goal, such as "Let's look at the first \[problem\]first".


