The use of concept spotting is common in spokenlanguage information systems (Ward, 1989; Jackson et al. , 1991; Aust et al. , 1995; Allen et al. , 1996).


Because the Semantic Linker uses the same set of realization rules as the rest of the system, when the system is ported to a new domain the Semantic Linker can be used immediately a distinct advantage over some other approaches to fallback understanding, such as (Stallard and Bobrow, 1992) or (Jackson et al, 1991).


Such strategies involve deemphasizing the role of syntactic analysis (Jacobs et al. , 1991), producing partial parses with stochastic or heuristic parsers (de Marcken, 1990; Weischedel et al 1991) or resorting to weaker syntactic processing methods such as conceptual or case-frame based parsing (e.g. , Schank and Riesbeck, 1981) or template matching techniques (Jackson et M. , 1991).


