P99-1066:1	15:110	Later work introduced other FOMs formed from PCFG data (Kochman and Kupin, 1991); (Magerman and Marcus, 1991); and (Miller and Fox, 1994).
---------------------------------------------------
W96-0212:2	100:121	Kochman and Kupin (1991) propose a figure of merit closely related to our prefix estimate.
---------------------------------------------------
J98-2004:3	246:313	Kochman and Kupin (1991) propose a figure of merit closely related to our prefix estimate.
---------------------------------------------------
