Because the Semantic Linker uses the same set of realization rules as the rest of the system, when the system is ported to a new domain the Semantic Linker can be used immediately a distinct advantage over some other approaches to fallback understanding, such as (Stallard and Bobrow, 1992) or (Jackson et al, 1991).


3 Ill-Formedness Handling: The Semantic Linker When an utterance cannot be parsed with Delphi's bestfirst parser (Bobrow, 1991) either because it is illformed, mis-recognized by the speech system, or simply because it is outside the coverage of the grammar it can still be partially understood by the system, often well enough to give the correct response.


133 Subcategorization constraints in Delphi are encoded in lexical entries using a structure called a "map" (Stallard and Bobrow, 1991).


The use of probabilistic context-free grammars (PCFGs) involves simple CF rule probabilities to form a FOM (Chitrao and Grishman, 1990; Bobrow, 1991).


