Speech Recognition For several years, the best performing speech recognition systems have been based on statistical pattern matching techniques (Pallett et al. 1990, Pallett 1991, Pallett et al. 1992, Pallett et al. 1993, Pallett et al. 1994).


Other systems, however, claim improved performance through the selection of units or combination of units determined automatically or semiautomatically (see, e.g., Bahl et al. 1991).


