The novel aspect in PLUM is that the case frames for verbs were hypothesized by a statistical induction algorithm \[Weischedel, et al. , 1991a\]. 
In approaching the problem of unrestricted texts, we agree with those researchers (Hobbs, 1991; Grishman et al. , 1991) who think that it is possible to build correct parses and interpretations for realworld texts. 
Based on local syntactic and semantic information, a fragment combining algorithm combines phrases to provide more complete analyses of the input \[Weischedel, et al. , 1991a\]. 
Earlier papers have focused on the probabilistic aspects of the system \[Weischedel et al. , 1991; de Marcken, 1990\]; here we focus on the other two design features. 
This problem of recombining parts is in general a difficulty that is faced by parsers thai, produce phrasal rather than sentential parses (e.g. , Weischedel et al. , 1991). 
