5.1 Evaluation Measures The Parseval measures (Black et al. , 1991) are used to evaluate a parsers phrase-structure trees againstagoldstandard. 
Besides an exact match accuracy metric, we also used a more fine-grained score based on the well-known PARSEVAL metrics that evaluate phrase-structure trees (Black et al. 1991). 
We obtained 80.02% and 79.64% labeled bracketing precision and recall respectively (as defined in (Black et al. , 1991)). 
(1991), and Black et al. 
In glass-box evaluation, researchers have developed a parse evaluation methodology (Black et al. 1991) that is now in use. 
