The initial results described here suggest many more experiments, some of which are already u~nderway (see Brent and Berwick, 1991).


PREVIOUS WORK While work has been done on various sorts of collocation information that can be obtained from text corpora, the only research that I am aware of that has dealt directly with the problem of the automatic acquisition of subcategorization frames is a series of papers by Brent (Brent and Berwick 1991, Brent 1991, Brent 1992).


