 History-based feature models for predicting the next parser action (Black et al. , 1992). 
For handling word identities, one could follow the approach used for handling the POS tags (e.g. , Black et al. 1992; Magerman 1994) and view the POS tags and word identities as two separate sources of information. 
In this way, our approach can be seen as a form of history-based parsing (Black et al. , 1992; Magerman, 1995). 
(1992) and Magerman (1994) used the clustering algorithm of Brown et al. 
 History-based feature models for predicting the next parser action (Black et al. , 1992). 
