There is a long history of work on ontolo,~ies for CL, including/he important work at Carnegie-Meffbn University over many years, that of Dahlgren and her collea,~ues (e.g. Dahlgren 1988) and the current Pangloss ProjecT, as described in Hovy and Nirenburg 1992, Hovy and Knight 1993 and Knight 1993.


We shall focusparticularly on the types of relations that need to be recogmsed as holding between the 'concepts' in an ontology or rather, between the gene,ric, objects (in contrast with specific objects), such as dog, realized as dogs, as in I like dogs.2 2 Why the discussion remains open Hovy and Nirenburg (1992), in clearing the ground for their discussion of the principles that should guide the construction of an ontology, suggest that most ontologies and domain models to date have been assembled based primarily on introspection, and often reflect the idiosyncrasies of the builders more than the requirements of the application (such as MT).


In fact, as Hovy and KnigSht (19~) state, the 'ontology base' in Pangloss is in part based on Penman (being a merger of this, the semantic categories from the Longman Dictionary of Contemporary English (LDOCE), which is intended as a taxonomy for the nouns of English), and ULTRA (Nirenburg and Defrise 1992)which itself draws on the LDOCE categories).


This seems to be the case with the Pangloss project (Hovy and Nirenburg 1992, Hovy and Knight 1993, Knight 1993), whose explicit goal is to combine the best features of these sources.


