The most common technique is using the Inside-Outside algorithm (e.g. Pereira & Schabes 1992, Mark, et al. 1992) to infer a grammar over bracketed texts or to obtain MaximumLikelihood estimates for a highly ambiguous grammar.


Mark, et al. 1992).


The most common technique is using the Inside-Outside algorithm (e.g. Pereira & Schabes 1992, Mark, et al. 1992) to infer a grammar over bracketed texts or to obtain MaximumLikelihood estimates for a highly ambiguous grammar.


