Chunks correspond to prosodic phrases (Abney 1992) and can be assembled into complete parse trees by adding headhead dependencies.


Just as there are ways to transform syntactic structures to prosodic structures (e.g. Abney 1992), prosodic structures can also provide clues to syntactic structures.


Thesystemwepresentisinspiredby(Abney, 1992)andit is in accordancewith (Srinivas et al. ,1997;;CiravegnaandLavelli,1997;;Yoonet al. ,1999;;Venkova,2000;;Watanabe,2000;;Prins andNoord,2001;;GroverandLascarides,2001;; Crysmannetal.


