Many systems (Carbonell and Hayes, 1983), (Hobbs et al. , 1992), (Seneff, 1992), (Stallard and Bobrow, 1992) have added robustness with a similar postprocessing phase.


6 Discussion Although we are not aware of any attempts to address the issue of robust understanding in the context of multimodal systems, this issue has been of great interest in the context of speech-only conversational systems (Dowding et al. , 1993; Seneff, 1992; Allen et al. , 2000; Lavie, 1996).


