J93-2005:1	136:423	It is these lexical structures that are then statistically tuned against the corpus, following the methods outlined in Anick and Pustejovsky (1990) and Pustejovsky (1992).
---------------------------------------------------
J93-2005:2	301:423	14 Imagine being able to take the V-O pairs 14 This section presents an abridged version of material reported on in Pustejovsky (1992).
---------------------------------------------------
J93-2005:3	167:423	This process and the corpus tuning for both argument typing and subcategorization acquisition are described in Cowie, Guthrie, and Pustejovsky (1992) and Pustejovsky et al.
---------------------------------------------------
P95-1038:4	7:76	Several researchers (Lang and Hirschman, 1988; Rau et al. , 1989; Pustejovsky, 1992; Grishman and Sterling, 1993; Basili et al. , 1994), either directly or indirectly, have addressed issues that assist in making it easier to move an NLP system from one domain to another.
---------------------------------------------------
M92-1031:5	36:73	This is a statistically-encoded structure o f all admissible semantic collocations associated with the lexical item . The initial seeding of the LS's is being done from lexical entries in the Longman Dictionary of Con temporary English [Proctor et al 1978], largely using tools described in [Wilks et al 1990] . These are then automatically adapted to the format of generative lexical structures . It is these lexical structures which ar e then statistically tuned against the corpus, following the methods outlined in [Pustejovsky 1992] and [Anic k and Pustejovsky 1990] . Semantic features for a lexical item which are missing or only partially specifie d from dictionary seeding are, where possible, induced from a semantic model of the corpus . 230 O. MESSAGE: ID TST2-MUC4-0048 1.
---------------------------------------------------
M92-1031:6	71:73	(1978) . Longman Dictionary of Contemporary English, Longman Group Limited: Harlow, Essex, England . Pustejovsky, James (1991) "The Generative Lexicon," Computational Linguistics, 17.4, 1991 . Pustejovsky, James (1992) "The Acquisition of Lexical Semantic Knowledge from Large Corpora ", in Proceedings of the DARPA Spoken and Written Language Workshop, Arden House, New York, February, 1992, Morgan Kaufmann . Wilks, Y. , Fass, D. , C-M.
---------------------------------------------------
