C04-1116:1	69:154	The words we want to aggregate for text analysis are not rigorous synonyms, but the role is the same, so we have to consider the syntactic relation based on the assumptions that words with the same role tend to modify or be modified by similar words (Hindle, 1990; Strzalkowski, 1992).
---------------------------------------------------
A94-1019:2	164:188	Strzalkowski and Vauthey (1992) follow the way suggested by Sparck Jones and Tait (1984) at the end of their paper.
---------------------------------------------------
C94-1100:3	20:223	TFP stands for Tagged Text Parser, and it has I:een described in detail in (Strzalkowski, 1992) and ev~duated in (Strzalkowski & Scheyen, 1993).
---------------------------------------------------
C92-1033:4	164:255	TIP has been used as front-end of a natural language processing component to a traditional document-based information retrieval system (Strzalkowski and Vauthey, 1992).
---------------------------------------------------
