In addition to its original use in language modeling for speech recognition, Grishman and Sterling (1993) applied the cooccurrence smoothing technique to estimate the likelihood of selectional patterns.


Euclidean distance L1 norm cosine Jaccard's coefficient L2(q,r) = Ll(q,r) = cos(q, r) = Jac(q, r) = ~v (q(v) r(v)) 2 Iq(v) r(v)l V ~-~v q(v)r(v) X/~-~v q(v) 2 V/Y~-v r(v) 2 Iv : q(v) > 0 and r(v) > 0}l Iv I q(v) > 0 or r(v) > O}l Figure 1: Well-known functions The confusion probability has been used by several authors to smooth word cooccurrence probabilities (Sugawara et al. , 1985; Essen and Steinbiss, 1992; Grishman and Sterling, 1993); it measures the degree to which word m can be substituted into the contexts in which n appears.


Several researchers (Lang and Hirschman, 1988; Rau et al. , 1989; Pustejovsky, 1992; Grishman and Sterling, 1993; Basili et al. , 1994), either directly or indirectly, have addressed issues that assist in making it easier to move an NLP system from one domain to another.


