A strategy to combat this problem is a lattice-based interface (Murveit et al. 1993).


The work of Cohen (e.g. , Cohen et al. 1987, Cohen 1989) and others (sce, e.g., Withgott and Chen 1993) attempts to address some of these issues, but solutions are not simple and significant performance gains have been hard to come by.


Significant effort has been spent on managing this search: depth-first vs. breadth first, beam search (which prunes hypotheses if they are enough b~low the best-scoring hypothesis), and, recently, various schemes for making multiple passes using coarser models at first to narrow the search and progressively more detailed models to further narrow tile pruned search space (see, e.g., Murveit et al. 1993, Nguyell et al. 1993).


The speech understanding community is quite active in refining evaluation measures and in developing new ones (see e.g., Price et al. 1992, Hirschman et al. 1993, Dahl et al. 1994).


Speech Recognition For several years, the best performing speech recognition systems have been based on statistical pattern matching techniques (Pallett et al. 1990, Pallett 1991, Pallett et al. 1992, Pallett et al. 1993, Pallett et al. 1994).


