The scheme is fully implemented within a version of the Spoken Language Translator system (Rayner et al. , 1993; Agniis et al. , 1994), and is normally applied to input in the form of small lattices of hypotheses produced by a speech recognizer.


These points will be discussed in the context of the Spoken Language Translator (SLT) (Rayner, Alshawi eta/, 1993; Agn~s et al. , 1994; Rayner and Carter, 1997), a customizable speech translator built as a pipelined sequence of generalpurpose components.


