A well known issue in the WSD area is the one sense per collocation claim (Yarowsky, 1993) stating that the word meanings are strongly associated with the particular collocation in which the word is located. 
(1991) and Yarowsky (1993) (see Section 2.3). 
A pseudo-word is an artificially created ambiguous word, like for example "banana-door" (pseudo-words have been introduced for the first time in (Yarowsky, 1993), as means of testing WSD accuracy without the costs associated with the acquisition of sense tagged corpora). 
This is similar to one sense per collocation idea of Yarowsky (1993). 
3 3 One Sense Per Collocation The strong tendency for words to exhibit only one sense in a given collocation was observed and quantified in (Yarowsky, 1993). 
