The next version, used in MUC-5 (Appelt et al. , 1993), had a graphical interface for defining state changes and allowed blocks of code to be associated with transitions.


However, only recently has work been done on the automatic computation of such relationships from text, quantifying similarity between words and clustering them ( (Brown et aL, 1992), (Pereira et al. , 1993)).


(Hobbs et aL, 1993) who call it a noun group), mostly because of the relative ease with which it can be identified.


