al., 1991, 1993),  learning word and word group associations (Matsukawa, 1993),  an example-based correction technique for segmentation and part-of-speech labeling for Japanes e (Matsukawa, Miller, and Weischedel, 1993), an d  induction of a statistical grammar and parser from training data (Magerman, 1995).


Much research has been carried out recently in this area (Hughes and Atwell 1994; Finch and Chater 1994; Redington, Chater, and Finch 1993; Brill et al. 1990; Kiss 1973; Pereira and Tishby 1992; Resnik 1993; Ney, Essen, and Kneser 1994; Matsukawa 1993).


(Matsukawa, 1993)).


