For example, coarse-to-fine search using a sequence of lowerorder to higher-order language models has been shown to be an efficient way of constraining highdimensional search spaces for speech recognition (Murveit et al., 1993) and machine translation (Petrov et al., 2008).


Progressive search has been used for HMMs in speech recognition (Murveit et al., 1993).


The general bigram-to-trigram technique is common in speech recognition (Murveit et al., 1993), where lattices from a bigram-based decoder are re-scored with a trigram language model.


