Lappin and Leass (1994) extracted rules from the output of the English Slot Grammar (ESG) (McCord, 1993). 
For a discussion of ESG's parsing accuracy, see McCord (1993). 
~English Slot Grammar (McCord 1980, 1990, 1993) 159 2 Controlled Language Checker or Grammar Checker? 
And for pars2 McCord (1993) also includes some corpus-based information, but to a very limited extent. 
This deep analysis is provided by English Slot Grammar (ESG) (McCord 1980, 1990, 1993) in the form of parse trees expressed as a network structure. 
