Heeman and Allen, 1994b); words 3They referred to modification repairs as nontrivial repairs, and to abridged repairs as trivial repairs; however, these terms are misleading.


Further details are given in Heeman and Allen (1994c).


(Further details of this scheme can be found in (Heeman and Allen, 1994a)).


At this time, we made no attempt to address any of the problems related to spontaneous speech, such as disfluencies and self-repairs (e.g. , Oviatt, 1994; Heeman & Allen, 1994).


