W94-0111:1	4:188	upenn, edu Introduction Eric Brill in his recent thesis (1993b) proposed an approach called "transformation-based error-driven learning" that can statistically derive linguistic models from corpora, and he has applied the approach in various domains including part-of-speech tagging (Brill, 1992; Brill, 1994) and building phrase structure trees (Brill, 1993a).
---------------------------------------------------
W99-0633:2	14:185	The tagger has been trained for tagging English texts with an accuracy of 97% (Brill, 1994).
---------------------------------------------------
H01-1001:3	99:245	The tagger uses the code by Brill (1994).
---------------------------------------------------
