In Section 5 we evaluate the complete extracted lexicon against the COMLEX resource (MacLeod et al. , 1994).


5 COMLEX Evaluation We evaluated our induced (verbal) semantic forms against COMLEX (MacLeod et al. , 1994).


Passive frames are marked p. We carried out a comprehensive evaluation of the automatically acquired verbal semantic forms against the COMLEX Resource (Macleod et al. , 1994) for the 2992 active verb lemmas that both resources have in common.


Briscoe and Carroll (1997) predefine 163 verbal subcategorization frames, obtained by manually merging the classes exemplified in the COMLEX (MacLeod, Grishman, and Meyers 1994) and ANLT (Boguraev et al. 1987) dictionaries and adding around 30 frames found by manual inspection.


Another notable related work is the COMLEX syntax project (Macleod et al. , 1994).


