The most promising possibilities are:  re-ranking the confusion set (and assigning new confidence-values to its entries), and,  deleting low-confidence entries from the confusion set (after applying contextual knowledge) Several researchers in NLP have acknowledged the relevance of context in disambiguating natural language input ((Evett et al. , 1991); (Zernik, 1991); (Hindle & Rooth, 1993); (Rosenfeld, 1994)).


Evidence from different knowledge sources can be combined in an attempt to optimize the selection of correct hypotheses; see e.g. Alshawi and Carter (1994); Rayner et al (1994); Rosenfeld (1994).


Cache language models (Kuhn and de Mori (1992),Rosenfeld (1994)) try to overcome this limitation by boosting the probability of the words already seen in the history; trigger models (Lau et al.


