In (Okumura and Hovy, 1994) (semi)automatic methods for associating a Japanese lexicon to an English ontology using a bilingual dictionary are described.


(Okumura & Hovy 1994) describes a semi-automatic method for associating a Japanese lexicon to an ontology using a Japanese/English bilingual dictionary as a 'bridge'.


We are introducing some semantic taxonomy and the semantic distance measurement algorithm(Knight, 1993; Okumura and Hovy, 1994; Resnik, 1993).


Using bilingual dictionaries for mapping words or senses of a language to English counterparts is not new (Okumura and Hovy, 1994; Asanoma, 2001).


