P96-1030:1	123:171	Care was taken to ensure not just that the utterances themselves, but also the speakers of the utterances were disjoint between test and training data; as pointed out in (Rayner et al. , 1994a), failure to observe these precautions can result in substantial spurious improvements in test data results.
---------------------------------------------------
P96-1030:2	39:171	The scheme is fully implemented within a version of the Spoken Language Translator system (Rayner et al. , 1993; Agniis et al. , 1994), and is normally applied to input in the form of small lattices of hypotheses produced by a speech recognizer.
---------------------------------------------------
W97-0615:3	7:192	On the one hand, the speech recognition task can benefit from linguistic decision to uncover the correct utterance, see (Rayner et al. , 1994) among others.
---------------------------------------------------
J94-4005:4	224:230	The method for computing scaling factors described here has more recently been applied to optimizing preference selection for the task of choosing between analyses arising from different word hypotheses in a speech recognition system (Rayner et al. 1994) and is applicable to other problems, such as choosing between possible target representations in a machine translation system.
---------------------------------------------------
P98-2145:5	18:171	Since determining weights by hand is a labor-intensive task and the weights do not always to achieve optimal or even near-optimal performance(Rayner et al. , 1994), we think it is better to determine the weights automatically in order to both avoid the need for expert hand tuning and achieve performance that is at least locally optimal.
---------------------------------------------------
H05-1006:6	21:182	(Rayner et al. , 1994; Carpenter et al. , 2001; Sarikaya et al. , 2003).
---------------------------------------------------
H05-1006:7	36:182	Most of features were extracted from the output of syntactic or semantic parsers, including full/robust/no parse, number of words parsed, gap number, slot number, grammar rule used, and so on (Rayner et al. , 1994; Pao et al. , 1998; Carpenter et al. , 2001; San-Segundo et al. , 2001).
---------------------------------------------------
H05-1006:8	48:182	However, such features have only been discussed in the context of conversational dialogue in specific domains such as ATIS (Rayner et al. , 1994), JUPITER (Pao et al. , 1998), and Communicator (Carpenter et al. , 2001; SanSegundo et al. , 2001; Zhang and Rudnicky, 2001; Sarikaya et al. , 2003).
---------------------------------------------------
A94-1010:9	144:154	This is consistent with experience (Rayner et al, 1994) that, for the ATIS domain, trigrams model inter-word effects much better than bigrams do, but that extending the N-gram model beyond N = 3 is much less beneficial.
---------------------------------------------------
A94-1010:10	10:154	Evidence from different knowledge sources can be combined in an attempt to optimize the selection of correct hypotheses; see e.g. Alshawi and Carter (1994); Rayner et al (1994); Rosenfeld (1994).
---------------------------------------------------
