Processing in Japanese proceeds as follows: (1) we process the Japanese with the Juman segmenter (Kuro151 Type Prec Rec F No Function Tags Version Aggr 8431374 = 61.4% 8431352 = 62.4% 61.8% Aver 62.3% 63.5% 63.6% Function Tags Version Aggr 10311415 = 72.9% 10311352 = 76.3% 74.5% Aver 73.0% 75.3% 74.9% Table 3: 53 Chinese Newswire Sentences: Aggregate and Average Sentence Scores hashi et al., 1994) and KNP parser 2.0 (Kurohashi and Nagao, 1998), which has reported accuracy of 91.32% F score for dependency accuracy, as reported in (Noro et al., 2005).


For example, one sentence in Titech Corpus (Noro et al. , 2005) with 22 words and 87 nodes includes 8,213,574,246 subtrees.


Titech corpus (Noro et al. , 2005) consists of about 20,000 sentences of Japanese newspaper articles (Mainiti Shimbun).


