For Chinese, finally, the accuracy for SVM with model 5 is about one percentage point lower than the best reported results, achieved with a deterministic classifier-based approach using SVM and preprocessing to detect root nodes (Cheng et al. , 2005a), although these results are not based on exactly the same dependency conversion and data split as ours.


2 Dependency Parsing for Thai The dependency structure for Thai is more flexible than some languages like Japanese (Sekine et al., 2000), Turkish (Eryigit and Oflazer, 2006), while it is close to Chinese (Cheng et al., 2005) and English (Nivre and Scholz, 2004).


Nivres parser has been tested for Swedish (Nivre et al. , 2004), English (Nivre and Scholz, 2004), Czech (Nivre and Nilsson, 2005), Bulgarian (Marinov and Nivre, 2005) and Chinese Cheng et al.


Over the past few years, several research studies had addressed the use of shift-reduce and edgefactored-based approaches attend fairly accurate performance in Chinese (Cheng et al., 2005; Hall,   2008.


