The basic segmentation in (Kang and Lim, 2005) has performed by bigram features together with space tags, and the trigram features has been used as a postprocessing of correcting the segmentation errors.


While we develop the system, we found that ngram-based algorithm was exactly applicable to the Chinese word segmentation and we have participated the bakeoff (Kang and Lim, 2005).


4  t i-2 c i-2 t i-1 c i-1 t i c i t i+1 c i+1 t i+2 c i+2  In our previous work of (Lim and Kang, 2005), n-gram features (a) and (b) are used.


