The scoring function D is a variant of the model proposed by (Tonoike et al. , 2005) and E corresponds to the bilingual lexicon score of the scoring function D.


T ) translation set (language T ) web (language S ) web (language S ) existing bilingual lexicon X S M (# of translations is more than one) Y S (# of translations is zero) web (language T ) web (language T ) looking up bilingual lexicon validating translation candidates web (language T ) web (language T ) Figure 1: Compilation of a Domain/TopicSpecific Bilingual Lexicon using the Web before translation estimation, then generated translation candidates are validated against the domain/topic-specific corpus (Tonoike et al. , 2005).


