3 Off-line answer extraction Off-line extraction of answers to frequent question types can be based on dependency patterns and coreference resolution (Bouma et al. , 2005; Mur and van der Plas, 2006), leading to higher recall (compared to systems using surface patterns).


For instance, in van der Plas and Bouma (2005) it is shown that automatically acquired class-labels for named entities improve the accuracy of answering general WH-questions (i.e. Which ferry sank in the Baltic Sea)?


Van der Plas and Bouma (2005) employed noun distribution characteristics for extending the Dutch part of EuroWordNet.


