Rather, their semantic role labels are directly extracted from a human annotated 926 corpus, the English Proposition Bank (Palmer et al, 2005), citing the inadequate accuracy of automatic semantic role labeling systems.


This supports previous arguments for word-specific feature design and parametric modeling for WSD tasks (Chen and Palmer, 2005; Hoste et al. 2002).


However, this result assumes the human annotation of the Penn English Propbank (Palmer et al, 2005).


