The comparative system is the WP identifier (Tsai, 2005). 
We conduct STW experiments to show the tonal and toneless STW accuracies of a commercial input product (Microsoft Input Method Editor 2003, MSIME), and an optimized bigram model, BiGram (Tsai, 2005), can both be improved by our WSM and achieve better STW improvements than that of these systems with the WP identifier. 
This observation is similarly with that of (Tsai, 2005). 
Since the identified character ratio of the WP identifier (Tsai, 2005) is about 55%, there are still about 15% improving room left. 
In our previous work (Tsai, 2005), a wordpair (WP) identifier was proposed and shown a simple and effective way to improve Chinese input systems by providing tonal and toneless STW accuracies of 98.5% and 90.7% on the identified poly-syllabic words, respectively. 
