Another direction for unsupervised relation learning was taken in (Hasegawa, Sekine et al. 2004; Chen, Ji et al. 2005).


Another direction for unsupervised relation learning was taken in (Hasegawa, Sekine et al. 2004; Chen, Ji et al. 2005).


For estimating the number of clusters k, we apply the stability-based criteria from (Chen et al., 2005) to decide the number of optimal clusters k automatically.


Then all the collected terms of all concept pairs are combined and ranked using an entropybased algorithm which is described in (Chen et al., 2005).


