Before the subword-based tagging, the character-based IOB tagging approach has been widely used in Chinese word segmentation recently (Xue and Shen, 2003; Peng and McCallum, 2004; Tseng et al., 2005). 
Chinese sentences are segmented by Stanford Chinese word segmenter (Tseng et al., 2005), and parsed by Stanford Chinese parser (Levy and Manning, 2003). 
In the results of the closed test in Bakeoff 2005 (Emerson, 2005), the work of (Tseng et al. , 2005), using CRFs for the IOB tagging, yielded a very high R-oov in all of the four corpora used, but the R-iv rates were lower. 
The FBIS-corpus was used as training corpus and all Chinese sentences were word segmented with the Stanford Segmenter (Tseng et al., 2005). 
1 Introduction The character-based IOB tagging approach has been widely used in Chinese word segmentation recently (Xue and Shen, 2003; Peng and McCallum, 2004; Tseng et al. , 2005). 
