The OntoNotes terms are represented in the 110,000-node Omega ontology (Philpot et al. , 2005), under continued construction and extension at ISI.


Building on results in grouping fine-grained WordNet senses into more coarse-grained senses that led to improved inter-annotator agreement (ITA) and system performance (Palmer et al. , 2004; Palmer et al. , 2006), we have developed a process for rapid sense inventory creation and annotation that includes critical links between the grouped word senses and the Omega ontology (Philpot et al. , 2005; see Section 5 below).


