There has been substantial progress in automatic pitch accent recognition for native speech, achieving accuracies above 80% for acousticfeature based recognition in multi-speaker corpora (Sridhar et al., 2007; Levow, 2008).


Thus, in this work, we employ a rich contextual feature set, based on that in (Levow, 2008).


These levels are consistent with syllable-, acousticfeature-based prosodic recognition reported in the literature (Levow, 2008).


The use of prosodic and coarticulatory context has improved the effectiveness of tone and pitch accent recognition in a range of languages (Mandarin (Wang and Seneff, 2000), English (Sun, 2002)) and learning frameworks (decision trees (Sun, 2002), HMMs (Wang and Seneff, 2000), and CRFs (Levow, 2008)).


