Identifying our coreferential chunks is even harder than the conventional coreference resolution, and we made a simplifying assumption as in Nenkova (2008) with some additional conditions that were obtained through our preliminary experiments.


Although NP elaboration such as in (Nenkova 2008) is of great importance, there are other useful syntactic types for revision.


Unlike many other methods that directly utilize noun phrase (NP) coreference (Nenkova 2008; Mani et al. 1999), we propose a method that employs insertion and substitution of phrases that modify the same chunk in the lead and other sentences.


Nenkova (2008) proposed a revision idea that utilizes noun coreference with linguistic quality improvements in mind.


