As seen in (Zhu et al., 2008a), sometimes min-err indeed stops later than desired and ZWH2008 must (by nature of how it operates) stop at least as late as min-err does.


(Bloodgood and Vijay-Shanker, 2009; Baldridge and Osborne, 2008; Zhu et al., 2008a)).


For WebKB, as in (McCallum and Nigam, 1998; Zhu et al., 2008a; Zhu et al., 2008b) we use the four largest categories.


8Following (Zhu et al., 2008b), we set the starting accuracy threshold to 0.9 when reimplementing their method.


Zhu and colleagues (Zhu and Hovy, 2007; Zhu et al., 2008a; Zhu et al., 2008b) introduce max-confidence, min-error, minimum expected error strategy, overall-uncertainty, and classificationchange as means to terminate AL. They primarily use a single-classifier approach to word sense disambiguation and text classification in their experiments.


