P09-1007:1	41:206	The first is usually focus on exploiting automatic generated labeled data from the unlabeled data (Steedman et al., 2003; McClosky et al., 2006; Reichart and Rappoport, 2007; Sagae and Tsujii, 2007; Chen et al., 2008), the second is on combining supervised and unsupervised methods, and only unlabeled data are considered (Smith and Eisner, 2006; Wang and Schuurmans, 2008; Koo et al., 2008).
---------------------------------------------------
P09-1007:2	169:206	Table 5: Comparison against the state-of-the-art full up to 40 (McDonald and Pereira, 2006)a 0.825 (Wang et al., 2007) 0.866 (Chen et al., 2008) 0.852 0.884 Ours 0.861 0.889 aThis results was reported in (Wang et al., 2007).
---------------------------------------------------
P09-1007:3	167:206	However, our results is only slightly better than that of (Chen et al., 2008) as only sentences whose lengths are less than 40 are considered.
---------------------------------------------------
D09-1060:4	178:253	(2007), Chen2008 refers to the parser of Chen et al.
---------------------------------------------------
D09-1060:5	124:253	The data partition and part-of-speech settings were chosen to match previous work (Chen et al., 2008; Yu et al., 2008).
---------------------------------------------------
