To solve the former, word-order related, problem, we use a preprocessing technique, which we have discussed in (Ananthakrishnan et al., 2008).


3 Motivation The fundamental differences between English and Hindi are:  English follows SVO order, whereas Hindi follows SOV order  English uses post-modifiers, whereas Hindi uses pre-modifiers  Hindi allows greater freedom in word-order, identifying constituents through case marking  Hindi has a relatively richer system of morphology We resolve the first two syntactic differences by reordering the English sentence to conform to Hindi word-order in a preprocessing step as described in (Ananthakrishnan et al., 2008).


Our earlier work (Ananthakrishnan et al., 2008) describes syntactic reordering and morphological suffix separation for English-Hindi SMT.


