, the automatic annotation of dialogue acts and the use of dialogue act speci c language models in speech recognition (Stolcke et al. , 2000). 
This paper describes the parameters and tagsets (analogous to \Dialogue Act" tagging (Stolcke et al 2000)), which they and three other groups have developed for this highly specialised domain. 
(The set of forty-two Dialogue Act labels used by Stolcke et al (2000) shows some similar mixing of levels, including both purely syntactic tags (such as Declarative Yes-No Question) and a ective tags (such as Appreciation).) 
Some of the problems are discussed in (Jurafsky et al. , 1998; Stolcke et al. , 2000; Jurafsky and Martin, 2000; Jurafsky, 2002). 
These can be used in dialogue act classification to predict the next act in a series of utterances (Stolcke et al., 2000). 
