Methods such as (Wu, 1997), (Alshawi et al. , 2000) and (Lopez et al. , 2002) employ a synchronous parsing procedure to constrain a statistical alignment. 
Previous work in statistical synchronous grammars has been limited to forms of synchronous context-free grammar (Wu, 1997; Alshawi et al. , 2000; Yamada and Knight, 2001). 
One is the statistical dependency transduction model (Alshawi and Douglas, 2000; Alshawi et al. , 2000b), a trainable generative statistical translation model using head transducers (Alshawi, 1996). 
Whereas language generation has benefited from syntax [Wu, 1997; Alshawi et al. , 2000], the performance of statistical phrase-based machine translation when relying solely on syntactic phrases has been reported to be poor [Koehn et al. , 2003]. 
This is the subject of existing studies, such as (Alshawi et al. , 2000). 
