Our implementation uses the multitape approach of Kiraz (2000). 
This is the first large-scale implementation of (Kiraz, 2000). 
One approach is to make use of separate tapes for root and pattern at the lexical level (Kiraz, 2000). 
While the original Two-Level formulation (Koskenniemi, 1983) of finite-state technology for morphology was not particularly well suited to Semitic languages (Lavie et al. , 1988), modifications of the Two-Level paradigm and more advanced finite-state implementations have been applied successfully to a variety of Semitic languages, including Ancient Akkadian (Kataja and Koskenniemi, 1988), Syriac (Kiraz, 2000) and Arabic. 
Kiraz (2000,2001) extends Kays 682 approach and implements a small working multitape system for MSA and Syriac. 
