W08-1116:1	187:227	126 Rather than explore surface features of language which are easier to recognise, I believe we should be either:  building discourse-level tree-banks of real texts, to provide real information to inform the automatic derivation of evaluation functions, or,  building tools to automatically recognise discourse structure of text, (RST, focus movement, etc.) Daniel Marcu has been a leader in both directions, working both on building an RST-tagged corpus, and also exploring the automatic recognition of rhetorical structure (Marcu 2000).
---------------------------------------------------
W05-0305:2	104:201	4 4 This distinction is hard to capture in an RST-based parsing framework (Marcu, 2000).
---------------------------------------------------
P09-2004:3	74:102	These results amount to a 10% absolute improvement over those obtained by Marcu (2000) in his corpus-based approach which achieves an f-score of 84.9%3 for identifying discourse connectives in text.
---------------------------------------------------
P09-2004:4	23:102	The only comprehensive study of discourse vs. non-discourse usage in written text1 was done in the context of developing a complete discourse parser for unrestricted text using surface features (Marcu, 2000).
---------------------------------------------------
W06-3401:5	22:142	2 Previous Research Early work on automatic RST analysis relied heavily on discourse cues to identify relations (CorstonOliver, 1998; Knott and Sanders, 1998; Marcu, 1997; Marcu, 1999; Marcu, 2000) (e.g. , however signaling an antithesis or contrast relation.
---------------------------------------------------
N03-2011:6	2:72	1 Introduction The task of rhetorical parsing, i.e., automatically determining discourse structure, has been shown to be relevant, inter alia, for automatic summarization (e.g. , Marcu, 2000).
---------------------------------------------------
N03-2011:7	67:72	segment rst_tree mc macro_seg non_rst_tree pp sc Fig 3: Simplified inheritance hierarchy for cat 4 Related work Similar to Marcu (2000) we assume discourse markers as indicators for rhetorical relations.
---------------------------------------------------
E06-1024:8	28:188	Moreover, it is well known that human-human interaction employs a variety of dialogue structuring mechanisms, ranging from meta-talk to discourse markers, and that some of these can usefully be employed for automatic analysis (Marcu, 2000).
---------------------------------------------------
P06-2097:9	41:192	Marcu performed rhetorical parsing in the framework of Rhetorical Structure Theory (RST) based on a discourse-annotated corpus (Marcu, 2000).
---------------------------------------------------
P05-3004:10	25:103	These items are maintained in lists; the growing lists constitute a documents discourse structure and are used, e.g., in resolving anaphora and establishing coreferents (implementing techniques inspired by Marcu (2000) and Tetreault (2001)).
---------------------------------------------------
W04-1002:11	42:166	For example, (Marcu, 2000) presents algorithms for automatically identifying the rhetorical structure of a text and argues that the hypothesized rhetorical structure can be successfully used in text summarization.
---------------------------------------------------
I08-1019:12	11:253	The discourse structure of one document has been the target of the traditional discourse analysis (Marcu, 2000; Marcu and Echihabi, 2002; Yokoyama et al., 2003), based on rhetorical structure theory (RST) (Mann and Thompson, 1987).
---------------------------------------------------
