Another stream of work in using finite-state methods in parsing is based on approximating context-free grammars with finite-state grammars, which are then processed by efficient methods for such grammars (Black 1989; Pereira and Wright 1997; Grimley-Evans 1997; Johnson 1998; Nederhof 1998, 2000). 
1 In Nederhof (2000), several methods of approximation were discussed that lead to determinized approximating FAs that can be much larger than the input CFGs. 
This construction is in many ways similar to similar constructions proposed for CFGs, in particular that of (Nederhof, 2000). 
4 Finite-state approximation There are several methods to approximate context-free grammars by regular languages (Nederhof, 2000). 
One is an extension with probabilities of existing work on approximation of CFGs by means of FAs (Nederhof 2000). 
