We considered a data set used by (Stamatatos et al. , 2000) consisting of 20 texts written by 10 different modern Greek authors (totaling 200 documents). 
This result compares favorably to the 72% accuracy reported in (Stamatatos et al. , 2000) which is based on linear least square fit (LLSF). 
Such techniques are currently being applied in many areas, including language identification, authorship attribution (Stamatatos et al. , 2000), text genre classification (Kesseler et al. , 1997; Stamatatos et al. , 2000), topic identification (Dumais et al. , 1998; Lewis, 1992; McCallum, 1998; Yang, 1999), and subjective sentiment classification (Turney, 2002). 
We considered a Greek data set used by (Stamatatos et al. , 2000) consisting of 20 texts of 10 different styles extracted from various sources (200 documents total). 
The 86% accuracy obtained with bi-gram models compares favorably to the 82% reported in (Stamatatos et al. , 2000), which again is based on a much deeper NLP analysis. 
