In our shift-reduce-style parser, planarity is maintained by a stack in the usual way (Morrill 2000).


It is instructive at this point to make a comparison with incremental parsing based on extended categorial grammar, where the structures in (67) would normally be handled by some kind of concatenation (or product), which does not correspond to any real semantic combination of the constituents (Steedman, 2000; Morrill, 2000).


