In the last decade or so research on lexical semantics has focused more on sub-problems like word sense disambiguation (Yarowsky, 1995; Stevenson and Wilks, 2001), named entity recognition (Collins and Singer, 1999), and vocabulary construction for information extraction (Riloff, 1996). 
Previous research (Ng and Lee, 1996; Stevenson and Wilks, 2001; Florian et al. , 2002; Lee and Ng, 2002) has shown that a combination of knowledge sources improves WSD accuracy. 
and it has been previously used to integrate heterogeneous knowledge sources for WSD (Stevenson and Wilks, 2001). 
653 McCarthy and Carroll Disambiguating Using Selectional Preferences other knowledge sources (Stevenson and Wilks 2001). 
Previous work has shown that using different combinations of features is advantageous for word sense disambiguation (e.g. , (McRoy, 1992), (Ng and Lee, 1996), (Stevenson and Wilks, 2001), (Yarowsky and Florian, 2002)). 
