In its present form, the formalism is tree-substitution grammar (Schabes, 1990) with an additional operation called sister-adjunction (Rambow et al. , 2001).


One grammatical formalism that is well-suited for our purposes is the D-Tree Substitution Grammars #28DSG, #28Rambow et al. , 2001#29#29, a variant of Tree-Adjoining Grammars #28TAG#29.


See (Rambow and Joshi, 1997) for a discussion related to TAG, and see (Rambow et al. , 2001) for the definition of a tree-rewriting system which can be used to develop grammars whose derivations faithfully mirror syntactic dependency.


Tree-substitution grammar (Schabes, 1990) is TAG without auxiliary trees or adjunction; instead we include a weaker composition operation, sister-adjunction (Rambow et al. , 2001), in which an initial tree is inserted between two sister nodes (see Figure 4).


