For example, by using simple voting (in which each tagger votes for a tag 525 and the tag with the highest number of votes is selected by the combined tagger), the tagging accuracy can increase significantly (van Halteren et al., 2001; Loftsson, 2006). 
These sentences received no contextual labels and thus not all of the training data used in (van Halteren et al. , 2001) could be used in the Wotan experiment. 
Combination techniques have been successfully applied to part of speech tagging (van Halteren et al. , 1998; Brill and Wu, 1998; van Halteren et al. , 2001). 
The Wotan data is annotated with a tagset consisting of 345 tags (although a number of 341 is reported in (van Halteren et al. , 2001)). 
In the Wotan experiment, 36K sentences (628K words) are used for training (compared to 640K words in (van Halteren et al. , 2001)), and 4176 sentences (72K words) are used for testing. 
