Several researchers have worked on unsupervised learning of phonotactic constraints and word segmentation (Elman, 2003; Brent, 1999; Venkataraman, 2001), but to our knowledge there is no previously published work on unsupervised learning of syllable structure.


Brent (1999) and Venkataraman (2001) present incremental splitting algorithms with BF about 82% 3 on the Bernstein-Ratner (BR87) corpus of infant-directed English with disfluencies and interjections removed (Bernstein Ratner, 1987; Brent, 1999).


5Other types of learning methods have been employed successfully, for example, Venkataraman (2001) and Seginer (2007).


These methods aim to infer vocabulary from unsegmented audio streams by analyzing regularities in pattern distribution (de Marcken, 1996; Brent, 1999; Venkataraman, 2001).


Two successful word segmentation systems based on explicit probabilistic models are those of Brent (1999) and Venkataraman (2001).


