We implemented the perceptron approach with the same feature set as that of an existing generative model (Roark, 2001a), and show that the perceptron model gives performance competitive to that of the generative model on parsing the Penn treebank, thus demonstrating that an unnormalized discriminative parsing model can be applied with heuristic search. 
At each word in the string, the Roark (2001) top-down parser provides access to the weighted set of partial analyses in the beam; the set of complete derivations consistent with these is not immediately accessible, hence additional work is required to calculate such measures. 
Several incremental parsing methods have been proposed so far (Collins and Roark, 2004; Roark, 2001; Roark, 2004). 
Many recent studies (e.g. , Chelba and Jelinek, 2000; Charniak, 2001; Roark, 2001) adopt this approach. 
Second, their language models were used to rescore n-best speech lists (supplied by Brian Roark, see Roark (2001)). 
