[Cucchiarelli & Velardi 2001] discussed boosting the performance of an existing NE tagger by unsupervised learning based on parsing structures.


(Cucchiarelli & Velardi 2001) discussed boosting the performance of an existing NE tagger by unsupervised learning based on parsing structures.


Other scoring approaches can be used see for example (Cucchiarelli and Velardi, 2001).


Our proposal is close to (Cucchiarelli and Velardi, 2001) as it uses syntactic relations (2.2) and as it relies on existing NER systems (2.6.2).


