The Boas project (Oflazer et al. , 2001), (HakkaniTur et al. , 2000), and (Oflazer and Nirenburg, 1999) has produced excellent results bootstrapping a morphological analyzer, but rely on direct human supervision to produce two-level rules (Koskenniemi, Barcelona, July 2004 Association for Computations Linguistics ACL Special Interest Group on Computational Phonology (SIGPHON) Proceedings of the Workshop of the 1983) which are then compiled into a finite state machine.


An example of the team approach was the BOAS project (Oflazer et al., 2001).


