ROSANA, an algorithm for anaphora resolution that focuses on robustness against information deficiency in the parsed output, is described in (Stuckardt, 2001).


Previous pronoun resolution work (Hobbs, 1976; Lappin and Leass, 1994; Ge et al. , 1998; Stuckardt, 2001) explicitly utilized syntactic information before.


Feature weights are automatically trained in our system while (Lappin and Leass, 1994; Stuckardt, 2001) assign weights manually.


This contrasts with the approach of extracting rules and assigning weights to these rules by hand (Lappin and Leass, 1994; Stuckardt, 2001).


These feature functions bear similarity to rules used in other coreference systems (Lappin and Leass, 1994; Mitkov, 1998; Stuckardt, 2001), except that the feature weights fig are automatically trained over a corpus with coreference information.


