Tetreault (2001) is one of the few papers that use the (Ge et al., 1998) corpus used here. 
And centering algorithms (Brennan et al. , 1987; Strube, 1998; Tetreault, 2001), sort the antecedent candidates based on the ranking of the forward-looking or backwardlooking centers. 
We believe this is, in fact, the standard (Mitkov, personal communication), although there are a few papers (Tetreault, 2001; Yang et al., 2006) which do the opposite and many which simply do not discuss this case. 
We considered two proposals for orderings of form: preferring pronouns and proper names over other NPs over indefinite NPs (Tetreault, 2001) (NF) or preferring pronouns over all other NPs (Tetreault, 2001) (NP). 
A cheap way to model information status is to consider the form of an antecedent (Tetreault, 2001; Soon et al. , 2001; Strube and Mller, 2003). 
