3Computational models of verb selectional preference have been evaluated through disambiguation tasks (Li and Abe, 1998; Abney and Light, 1999; Ciaramita and Johnson, 2000; Clark and Weir, 2002), but for to evaluate our cognitive model, the experiments from Resnik (1996) are the most interesting. 
The joint probability model achieved 85.3% on this data set, also significantly outperforming Clark and Weir (2002) ( 2 (1)=119.35, p <.01). 
It is worth noting that the method of Clark and Weir (2002) does not yield a tree cut, but instead generally populates the WordNet hierarchy with non-zero probabilities. 
5 Experimental Evaluation We evaluate the SPD method on selectional profiles created using the method of Clark and Weir (2002), with comparison to the other distance measures as explained above. 
8 Clark and Weir (2002) use a setting similar to that of Rooth et al. 
