P07-1087:1	53:258	Mikheev (2002) proposes using not only local information but also global information in a document in case restoration.
---------------------------------------------------
P07-1087:2	49:258	See also (Mikheev, 2000; Mikheev, 2002).
---------------------------------------------------
W09-1317:3	61:224	4 Biologicaltext preprocessing 4.1 Sentencepreparation A heuristic method is implementedto detect sentence boundaries(Mikheev, 2002) based on the assumption that sentencesare usually demarcatedby some indicative delimitingpunctuationmarks in order to segment the biological texts into sentence units.
---------------------------------------------------
J06-4003:4	613:730	The fact that it can recognize new abbreviations on the fly is especially a great advantage because the results of the RE system on the Lacio-Web corpus and our own experiments in Section 6.4.4 show that rule or list-based systems are often not sufficient to cover the productivity of abbreviation use in new corpora and languages; compare also Mikheev (2002, pages 298, 299, and 311) and Silla and Kaestner (2004).
---------------------------------------------------
J06-4003:5	703:730	He places an arbitrary length limit on possible abbreviations by applying his document-centered approach to abbreviation detection only to candidates that have a maximal length of four letters (Mikheev 2002, page 299).
---------------------------------------------------
J06-4003:6	665:730	This points to the general problem that supervised systems that are not able to dynamically incorporate new knowledge, for example, by discovering abbreviation types on the fly, cannot be expected to perform reliably on new corpora if the specific domain or genre is not known beforehand; compare also Mikheev (2002, pages 298, 314).
---------------------------------------------------
J06-4003:7	712:730	Mikheevs strong reliance on capitalization also renders his approach unsuitable for single-case text and leads to some problems for German where all nouns are always capitalized and not only proper names (Mikheev 2002, page 315).
---------------------------------------------------
J06-4003:8	695:730	13 Mikheev himself admits that the use of an additional domain-specific abbreviation list, which has to be recreated for every new domain, is not always possible, especially if the system is expected to handle documents from unknown origin (Mikheev 2002, pages 305, 306).
---------------------------------------------------
J06-4003:9	253:730	In contrast to Mikheev (2002, page 297), we do not extract the list of frequent sentence starters from an additional corpus but use the test corpus itself.
---------------------------------------------------
J06-4003:10	685:730	7.3.1 Mikheev (2002).
---------------------------------------------------
J06-4003:11	165:730	In contrast to other proposals such as the one by Mikheev (2002, page 299), we refrain from using a fixed maximum length for abbreviations.
---------------------------------------------------
J06-4003:12	359:730	The third baseline algorithm (TypeBL) is based on a method described by Grefenstette (1999) and also by Mikheev (2002, page 299).
---------------------------------------------------
J06-4003:13	52:730	and Mikheev (2002, page 291).
---------------------------------------------------
J06-4003:14	714:730	Mikheev (2000, 2002) describes the combination of a trigram tagger with his document-centered approach to abbreviation detection and proper name identification.
---------------------------------------------------
N09-2061:15	27:96	(Mikheev, 2002) describes a document241 centered approach to SBD, using a set of heuristics to guess which words correspond to abbreviations and names.
---------------------------------------------------
W03-0505:16	201:233	A state-of-the-art approach is included in our XML pipeline (Mikheev, 2002).
---------------------------------------------------
