We pursue a methodology based on Teufel and Moens (2002) where sentences are classified according to their argumentative role. 
3 Related work Previous work has focused on the analysis of citation and collaboration networks (Teufel et al., 2006; Newman, 2001) and scientific article summarization (Teufel and Moens, 2002). 
3 The Sentence Classifier 3.1 Feature Sets The feature set described in Teufel and Moens (2002) includes many of the features which are typically used in sentence extraction approaches to automatic summarisation as well as certain other features developed specifically for rhetorical role classification. 
This technique is the focus of one of the articles in this special issue (Teufel and Moens 2002), which shows how particular types of rhetorical relations in the genre of scientific journal articles can be reliably identified through the use of classification. 
7.1 AZ Data The evaluation corpus used is the one from Teufel and Moens (2002). 
