5.1 Future work on lexical choice Including lexical choice in our models will not be easy because true synonyms and paraphrases are rare [Edmonds and Hirst, 2002]. 
In principle, it can handle any level of granularity given sucient training data; however, addressing distinctions at the level of nearsynonyms (Edmonds and Hirst, 2002) might require customized analysis for each cluster of nearly synonymous words. 
Edmonds and Hirst (2002) modified this model to account for near-synonymy. 
1.2 The Clustered Model of Lexical Knowledge Hirst (1995) and Edmonds and Hirst (2002) show that current models of lexical knowledge used in computational systems cannot account well for the properties of near-synonyms. 
Following the analysis of the distinctions among near-synonyms of Edmonds and Hirst (2002), we derived the class hierarchy of 225 Computational Linguistics Volume 32, Number 2 distinctions presented in Figure 2. 
