Tag sets in previous Korean morphological analysers were unstructured or hierarchical (Lee et al. , 2002), not feature-based. 
Therefore we need to separate the functional words from an NE instance to detect the boundary of the NE instance and this is achieved by a part-of-speech tagger, POSTAG, which can detect unknown words (Lee et al. , 2002). 
They convey more information than adjacency symbols, but they are less numerous: 59 to be compared to 300 (Lee et al. , 2002). 
First, a morphological analysis is performed, which segments a sentence of words into morphemes, and adds POS tags to the morphemes (Lee et al. , 2002). 
It has been claimed that morphological annotation of Korean text could only be performed this way, because a lexicon of words would be too 38 large (e.g. Lee et al. , 2002; Han and Palmer, 2005). 
