to incorporate the pre-processing components used by Zechner (2002) and evaluate their contribution to our task. 
Work on spoken dialogue summarization is still in its infancy (Reithinger et al. , 2000; Zechner, 2002). 
However, overall most of the issues tackled by Zechner (2002) are not relevant to email summarization. 
Relatively few attempts have been made at summarizing less structured genres, some of them being dialogue and speech summarization (Zechner, 2002; Koumpis et al. 2001). 
Zechner (2002), for example, presents a meeting summarization system which uses the MMR algorithm to find sentences that are most similar to the segment and most dissimilar to each other. 
