Bozsahin (2002) presents a version of CCG where saturated category symbols are modified by unary modalities annotated with morphosyntactic features. 
3 For the same reason,Bozsahin (2002) uses morphemes as sublexical constituents in a CCG framework. 
TheT-CCGformalismisequivalenttothemorphosyntacticCCGformalismofBozsahin(2002), where features are ordered in a join semi-lattice. 
Bozsahin (2002) employed morphemes overtly as lexical units in a CCG framework to account for a variety of linguistic phenomena in a prototype implementation. 
A lexical entry with 76 category (NP/NP)a21 (Sa21 NP) is created and added to the lexicon to give the categories in (10) following Bozsahin (2002).3 (10) Oku -dugum kitap yand.Sa21 NP (NP/NP)a21 (Sa21 NP) NP Sa21 NP 4 Results The output is a file with all the words and their CCG categories. 
