However, many lexical replacement errors simply reflected the lexical preferences of individual forecasters [Reiter and Sripada, 2002]. 
This very small corpus showed that once again there were major differences between individuals (Reiter and Sripada, 2002a), but the corpus is too small to allow meaningful statistical analysis of word meanings. 
We have discussed lexical replacement errors in detail elsewhere [Reiter and Sripada, 2002]. 
This matching/alignment procedure is different in detail from the preliminary analysis procedure reported in (Reiter and Sripada, 2002b). 
Our analysis of manually written forecasts [Reiter and Sripada, 2002] had highlighted a number of noise elements that made it more difficult to extract information from such corpora. 
