According to (Radev et al., 2002), all methods that are not explicitly extractive are categorized as abstractive.


Usually it is no longer than half of the original text(s) or, significantly less (Radev et al., 2002).


3 Legal Document Summarization Extraction of sentences in the generation of a summary at different percentage levels of text is one of the widely used methods in document summarization (Radev et al., 2002).


389 390 Tatar, Mihis, and Serban 1 Introduction Text summarization has become the subject of an intense research in the last years and it is still an emerging field (Orasan, 2006; Radev et al., 2002; Hovy, 2003; Mani, 2001).


Such an extraction-based de nition of summarization has also been quite common in most existing general summarization work (Radev et al., 2002).


