2 Method Following Keller and Lapata (2003), web counts for ngrams were obtained using a simple heuristic based on queries to the search engine Altavista.1 In this approach, the web count for a given n-gram is simply the number of hits (pages) returned by the search engine for the queries generated for this n-gram. 
2003), Keller and Lapata (2003) show that Web counts correlate well with counts collected from a balanced corpus: the size of the Web compensates for the noise in the data. 
Keller and Lapata (2003) showed that web frequencies correlate reliably with standard corpus frequencies. 
More recently, Keller and Lapata (2003) evaluate the utility of using Web search engines for obtaining frequencies for unseen bigrams. 
(Keller and Lapata, 2003) show that Web page counts and n-gram frequency counts are highly correlated in a log scale. 
