This meant that the clauses linked syntactically were also related at the discourse level (Webber et al. , 2003). 
Following the approach towards discourse structure in (Webber et al. , 2003), the PDTB takes a lexicalized approach, treating discourse connectives as the anchors of the relations and thus as discourse-level predicates taking two Abstract Objects as their arguments. 
For example, in (Webber et al. , 2003), the tree in Figure 4 is the discourse structure associated with (1). 
The annotators are also informed that in some cases, an argument of a connective must be derived from the selected textual span (Webber et al. , 1999a; Webber et al. , 2003). 
This DAG could be said to be linguistically realized in (8a): since 11Among discourse connectives, (Webber et al. , 2003) distinguish structural connectives (e.g. subordinating conjunctions) from discourse adverbials including then, also, otherwise, . . . 
