Weighted dominance graphs can be used to encode the standard models of scope preferences (Pafel, 1997; Higgins and Sadock, 2003).


For example, Higgins and Sadock (2003) present a machine learning approach for determining pairwise preferences as to whether a quantifier Q1 dominates another quantifier Q2, Q2 dominates Q1, or neither (i.e. they are disjoint).


Furthermore, we show how to define a PCFG-style cost model on RTGs and compute best readings of deterministic RTGs efficiently, and illustrate this model on a machine learning based model 218 of scope preferences (Higgins and Sadock, 2003).


