Some approaches reuse parts of other algorithms: the Branch and Bound algorithm (Krahmer et al. , 2003) uses the Full Brevity algorithm, but is able to generate referring expressions with both attributes and relational descriptions using a graph-based technique. 
Krahmer et al. 2003). 
Two recent works describe algorithms that deal with this problem (Krahmer et al., 2003; Croitoru and van Deemter, 2007). 
In order to refer to an intended object (the target) among others (distractors), most past work (Appelt, 1985; Dale and Haddock, 1991; Dale, 1992; Dale and Reiter, 1995; Heeman and Hirst, 1995; Horacek, 1997; Krahmer and Theune, 2002; van Deemter, 2002; Krahmer et al. , 2003) utilized attributes of the target and binary relations between the target and distractors. 
The use of vertex facts indicates that the representation is inspired by the Graph approach to referring expression generation [Krahmer et al. , 2003]. 
