6 Related Work The most relevant previous works include word sense translation and translation disambiguation (Li & Li 2003; Cao & Li 2002; Koehn and Knight 2000; Kikui 1999; Fung et al. , 1999), frame semantic induction (Green et al. , 2004; Fung & Chen 2004), and bilingual semantic mapping (Fung & Chen 2004; Huang et al. 2004; Ploux & Ji, 2003, Ngai et al. , 2002; Palmer & Wu 1995). 
BiFrameNet ontology induction Ploux and Ji, (2003) proposed a spatial model for matching semantic values between French and English. 
Moreover, as some researches propose, synonyms can be used to construct the semantic space for a given word (Ploux and Victorri, 1998, Ploux and Ji, 2003). 
Bilingual Semantic Mapping Ploux and Ji, (2003) proposed a spatial model for matching semantic values between French and English. 
Ploux and Ji (2003) investigated the question of which words should be considered near-synonyms, without interest in their nuances of meaning. 
