W07-1313:1	53:123	Construction of VoNet: Many typological studies (Lindblom and Maddieson, 1988; Ladefoged and Maddieson, 1996; Hinskens and Weijer, 2003; Choudhury et al. , 2006; Mukherjee et al. , 2006a; Mukherjee et al. , 2006b) of segmental inventories have been carried out in past on the UCLA Phonological Segment Inventory Database (UPSID) (Maddieson, 1984).
---------------------------------------------------
W07-1313:2	11:123	Of late, there have been some attempts to explain the vowel systems through multi agent simulations (de Boer, 2000) and genetic algorithms (Ke et al. , 2003); all of these experiments also use the principle of perceptual contrast for optimization purposes.
---------------------------------------------------
