Oflazers dependency parser (2003) used IGs as units between which dependency relations were established. 
The most reliable data set for Turkish is the Metu-Sabanc Turkish Treebank (Oflazer et al. , 2003) consisting of 5635 sentences annotated with dependency structures. 
Additionally, we have adopted solutions to overcome problems that have emerged in doing this analysis (such as discontinuous constituents, subordinate clauses, etc. This approach has been used in several projects (Jrvinen & Tapanainen, 1998; Oflazer, 2003). 
3Only 2.5% of the dependencies in the Turkish treebank (Oflazer et al. , 2003) actually cross another dependency link. 
The dependency structure of Turkish has been mentioned in many studies (Oflazer et al. , 2003; Oflazer, 2003; Eryigit et al. , 2006) and it is argued that for Turkish, it is not just enough to determine the relationships between words and one should also determine the relationships between inflectional groups. 
