Hwa (2004) used uncertainty sampling with the tree entropy (TE) selection function1 to select training samples for the Collins parser. 
AL has been successfully applied already for a wide range of NLP tasks, including POS tagging (Engelson and Dagan, 1996), chunking (Ngai and Yarowsky, 2000), statistical parsing (Hwa, 2004), and named entity recognition (Tomanek et al., 2007). 
The authors test two novel methods, along with the tree entropy (TE) method of (Hwa, 2004). 
Hwa (2004) (to whom we compare our results) used the gold standard POS tags for the same sections in her work6. 
The work most closely related to this paper is Hwas (Hwa, 2004), which proposed a sophisticated method for selective sampling for statistical parsing. 
