First, since centering information is now available (the Cb and Cp of each proposition can be computed), the evaluation of solutions can take account of the centering preferences proposed by Kibble and Power (2004). 
1 Introduction Models of coherent discourse are central to several tasks in natural language processing: such models have been used in text generation (Kibble and Power, 2004) and evaluation of human-produced text in educational applications (Miltsakaki and Kukich, 2004; Higgins et al. , 2004). 
Our approach is similar to Kibble and Power (2004) in that we dont use the concept of centering transitions. 
Metrics of coherence are used in other work on text generation, too (Mellish et al. 1998; Kibble and Power 2000, 2004; Cheng 2002). 
Centering Theory has been adapted to NLG by Kibble (1999; 2001), and implemented in Kibble and Power (2004). 
