7 Related Work Previous work on automated metaphor detection includes Fass (1991), Martin (1990), and Mason (2004). 
al., 2000; Nissim&Markert, 2003; Mason, 2004). 
By finding semantic differences between the selectional preferences, it can articulate the higher-order structure of conceptual metaphors ((Mason, 2004), p. 24), finding mappings like LIQUIDMONEY. 
Our method is different from automated work on metaphor recognition such as (Mason, 2004) and (Gedigian et al. , 2006) in that it includes nouns as parts of speech. 
al., 2000; Nissim & Markert, 2003; Mason, 2004). 
