Brutus uses the CCG parser of (Clark and Curran, 2007, henceforth the C&C parser), Charniaks parser (Charniak, 2001) for additional CFG-based features, and MALT parser (Nivre et al., 2007) for dependency features, while (Punyakanok et al., 2008) use results from an ensemble of parses from Charniaks Parser and a Collins parser (Collins, 2003; Bikel, 2004). 
We used Bikels reimplementation of Collins parsing model 2 (Bikel, 2004). 
2This is the standard Charniak parser (without the parser of Bikel (2004). 
% Turian and Melamed (2005) 87.13 86.47 87.80 Bikel (2004) 88.30 87.85 88.75 Taskar et al. 
Parsing As our baseline parsers, we use two state-of-theart lexicalised parsing models, namely the Bikel parser (Bikel, 2004) and Charniak parser (Charniak, 2000). 
