Niessen and Ney, 2004). 
Niessen and Ney (2004) describe an approach for translation from German to English that combines verbs with associated particles, and also reorders questions. 
2 Related Work A number of researchers (Brown et al. , 1992; Berger et al. , 1996; Niessen and Ney, 2004; Xia and McCord, 2004; Collins et al. , 2005) have described approaches that preprocess the source language input in SMT systems. 
Niessen and Ney (2004) have used morphological decomposition to improve alignment quality. 
In addition, Niessen and Ney (2004) decompose German words into a hierarchical representation using lemmas and morphological tags, and use a MaxEnt model to combine the different levels of representation in the translation model. 
