But Di Eugenio and Glass (2004) have found that this interpretation does not hold true for all tasks. 
2.2 Chance-Corrected Agreement: Unequal Coder Category Distribution The second class of agreement measure recommended in Di Eugenio and Glass (2004) is that of chance-corrected tests that do not assume an equal distribution of categories between coders. 
As per ((Di Eugenio & Glass, 2004), cf. 
Di Eugenio and Glass (2004) perceive this as an unpleasant behavior of chancecorrected tests, one that prevents us from concluding that the example given in Table 1 shows satisfactory levels of agreement. 
Di Eugenio and Glass (2004) conclude with the proposal that these three forms of agreement measure collectively provide better means with which to judge agreement than any individual test. 
