The result also holds for the relative weighted frequency estimator introduced in (Chi, 1999) as a generalization of the maximum likelihood estimator, and for the estimator introduced in (Nederhof, 2005) already discussedintheintroduction.


This line of research was started in (Nederhof, 2005), investigating the problem of training an input probabilistic finite automaton from an infinite tree distribution specified by means of an input probabilistic context-free grammar.


Under this condition, quantities outG(A) can be exactly computed by solving the following system of linear equations (see also (Nederhof, 2005)) outG(S) = 1; (14) for each A negationslash= S outG(A) = = summationdisplay B outG(B)f(A,)pG(B  ).(15) 338 We can now prove the equality Hd(pG) = H(pT ||pG), (16) where G is the PCFG estimated by minimizing the cross-entropy in (5), as described in Section 3.


It can also be used to approximate a context-free grammar with a finite state automaton (Nederhof, 2005).


The earliest work that we are aware of on estimating models from models in this way is that of Nederhof (2005), who considers the case of learning language models from other language models.


