Daume III and Marcu (2005) propose a model that encodes how likely it is that different sized spans of text are skipped to reach words and phrases to recycle.


This upper bound is consistent with the upper limit of 50% found by Daume III and Marcu (2005) which takes into account stemming differences.


The closest work is that of Jing and McKeown (1999) and Daume III and Marcu (2005), in which multiple sentences are processed, with fragments within them being recycled to generate the novel generated text.


