This feature passing is technically achieved by articulating the VP spine with the feature MINS (much like the use of the P feature in English for adverbial scope in Kallmeyer and Romero, 2005), and by adding the feature NEXT for passing between NP substitution nodes (since substitution nodes do not have T and B features that allow feature percolations between mothers and daughters). 
2 English quantifier scope in LTAG We use the LTAG semantics framework from (Kallmeyer and Romero, 2004; Kallmeyer and Romero, 2005). 
This can be remedied by adopting the nodesharing relation proposed by (Kallmeyer, 2005). 
As a sample derivation let us sketch the analysis of quantificational NPs in English from (Kallmeyer, 2005). 
(Kallmeyer and Romero, 2005) model this by defining a scope window delimited by some maximal scope (global feature MAXS and some minimal scope (global feature MINS) for a quantifier. 
