We use Propbank (Palmer et al., 2005), a corpus of newswire text annotated with verb predicate semantic role information that is widely used in the SRL literature (M`arquez et al., 2008). 
This is supported by the similarity of common predicateargument paths between this data and the PropBank WSJ annotations (Palmer et al., 2005) and the consistency of other features currently emphasized in automatic SRL work on clean text data. 
2.2 Semantic Role Labeling The task of semantic role labeling in the context of PropBank (Palmer et al., 2005) is to label tree nodes with semantic roles in a syntactic parse tree. 
Our results also confirm the findings in (Palmer et al. , 2005). 
 Proposition Bank I (PropBank)  The PropBank annotation (Palmer et al., 2005) classifies the arguments of all the main verbs in the Penn Treebank corpus, other than be. 
