(2001), Markert and Nissim (2005)). 
However, this issue was recently addressed by Markert and Nissim (2005) by extending their work on Other-Anaphora using lexico syntactic pattern X and other Ys to antecedent selection for definite NP coreference. 
In fact, different sources of lexical knowledge have been evaluated for anaphora resolution (Poesio et al. , 2002; Markert and Nissim, 2005; Bunescu, 2003). 
Markert and Nissim (2005) compared three systems for other-anaphora resolution, using the same data set as in (Modjeska et al., 2003). 
We compare this approach with a WordNet-based algorithm and with an approach presented by Markert and Nissim (2005) on resolving definite NP coreference that makes use of lexico-syntactic patterns such as X and Other Ys as utilized by Hearst (1992). 
