Secondly, unlike in the RST corpus (Carlson et al. , 2003) or the Discourse GraphBank (Wolf and Gibson, 2005), discourse segments are not separately annotated, with annotators then identifying what discourse relations hold between them. 
Other work uses human-annotated corpora, such as the RST Bank (Carlson et al. , 2001), used by Soricut and Marcu (2003), the GraphBank (Wolf and Gibson, 2005), used by Wellner et al. 
There are a number of corpora annotated with discourse structure, including the well-known RST Treebank (Carlson et al. , 2002); the Discourse GraphBank (Wolf and Gibson, 2005); and the Penn Discourse Treebank (Miltsakaki et al. , 2004). 
al., 2003; Wolf and Gibson, 2005). 
While most work on textual discourse parsing has made use of the RST-DT corpus, the Discourse GraphBank corpus provides a competing annotation that is not constrained to tree structures (Wolf and Gibson, 2005). 
