Lastly, rule composition and different amounts of lexicalization (Galley et al., 2006; Marcu et al., 2006; DeNeefe et al., 2007) or context modeling (Marino et al., 2006) have been successful with other models.


So far, though, most work in this area has been either more linguistic than statistical (Abeille et al., 1990) or statistically-based, but linguistically light (Nesson et al., 2006).


There are several important differences between our grammars and the ones of Nesson et al.(2006): Richer, Linguistic Trees: Our grammars have a 728 PennTreebank-style linguistic tree onthe English (target) side, and ahierarchical structure using only a single non-terminal symbol (X) on the source side.


Default decoding options were used (20 alternatives per phrase, maximum distortion distance of 7, etc.) 2.5 A N-code baseline N-code implements the n-gram-based approach to Statistical Machine Translation (Mario et al., 2006).


