A measure of rank correlation (called Kendalls ), which was subsequently shown to correlate reliably with human ratings and reading times (Lapata 2006), was used to estimate the distance between orderings. 
Kendalls  can be interpreted as the difference between the probability that in the dataset two variables are in the same order versus the probability that they are in different orders (see (Lapata, 2006) for details). 
2(Lapata, 2006) found that human ratings are significantly correlated with self-paced reading times, a more direct measure of processing effort which we plan to explore in future work. 
Kendalls ,  = 1  4 tN(N1) where t is the minimum number of interchanges of consecutive elements to achieve the right order (Kendall, 1938; Lapata, 2006). 
We can compare the two rankings using Kendalls  (see Lapata (2006) for an overview), a nonparametric measure of correspondence for rankings. 
