E09-1036:1	29:205	A third approach makes use of a finite set of registers that the FST can write to and read from (Cohen-Sygal and Wintner, 2006).
---------------------------------------------------
E09-1036:2	122:205	Each has an explicit mechanism for keeping the root and pattern distinct: separate tapes in the case of Kiraz (2000) and separate memory registers in the case of Cohen-Sygal & Wintner (2006).
---------------------------------------------------
E09-1036:3	121:205	The other two approaches discussed in 1.2, that of Kiraz (2000) and that of Cohen-Sygal & Wintner (2006), are closer to what is proposed here.
---------------------------------------------------
