We use the unsupervised Punkt system (Kiss and Strunk, 2006).


At the least, (Kiss and Strunk, 2006) have labeled over 243 Corpus Examples in S SVM Err NB Err WSJ 26977 74% 0.25% 0.35% Brown 53688 91% 0.36% 0.45% Poe 11249 95% 0.52% 0.44% Table 3: SVM and Naive Bayes classification error rates on different corpora using a model trained from a disjoint WSJ data set.


Punkt (Kiss and Strunk, 2006) uses a set of loglikelihood-based heuristics to infer abbreviations and common sentence starters from a large text corpus.


