Kwasny and Sondheimer (1979) have extended our notion of selectively relaxing predicates to deal with American Journal of Computational Linguistics, Volume 6, Number 2, April-June 1980 107 Ralph M. Weischedel and John E. Black Responding Intelligently to Unparsabla Inputs co-occurrence violations and relaxation of expected word categories.


Research reported in Joshi and Weischedel (1977) and Weischedel (1979) demonstrated how to organize an augmented transition network and lexicon to compute the given and new information of a sentence.


