J89-1002:1	20:437	All-path parsing algorithms explore all possible paths in parallel without backtracking (Early 1970; Kay 1980; Chester 1980; Tomita 1985).
---------------------------------------------------
J94-4006:2	53:214	The approach taken in this paper is to combine an all-path parsing algorithm (Chester 1980; Earley 1970; Kay 1980; Seo and Simmons 1989; Tomita 1985) with routines for generating logical representations in order to create a shared-packed parse forest annotated with the logical representations for the constituents in the forest (i.e. , an annotated shared-packed parse forest).
---------------------------------------------------
C82-1054:3	138:144	Bibliography Chester, D. , A parsing algorithm that extends phrases, American Journal of Computational Linguistics, 6-2 (1980) 87-96.
---------------------------------------------------
C82-1054:4	5:144	Chester (1980) proposes a modification to the Griffiths and Petrick algorithm which "combines phrases before it has found all of their components".
---------------------------------------------------
