Focusing techniques (Grosz 1977; Sidner 1981; Robinson 1981; McKeown 1985; Carberry 1988) are necessary in order to identify that portion of the underlying plan to which a fragmentary utterance refers.


Grosz (1977) and Robinson (1981) used models of the speaker's task in apprentice-expert dialogs to determine the referents of definite noun phrases and verb phrases.


Focusing mechanAas have been employed by Gross(1977) in identifying the referents of definite noun phrases, by Robinson(1981) in interpreting verb p~vases, by ~ner( 1981 ) in anaphora resolution, by CarberrT(1983) in plan inference, and by McKeown(19fl~) in natural lan&uage generat~on.


Robinson (Robinson et al. 1980, Robinson 1981) extended Grosz's work and developed a process model for determining the referents of verb phrases, such as variants of do in the utterance "I've done it".


226 American Journal of Computational Linguistics, Volume 7, Number 4, October-December 1981 Candace L. Sidner Focusing for Interpretation of Pronouns basis of research that has been reported elsewhere (see Sidner 1979, Robinson 1981).


