J95-3001:1	738:965	For example, Damerau (1981), Miller, Herschman, and Kelly (1978) on the LADDER system, and Biermann, Ballard, and Sigmon (1983) reported software failures at the rates of approximately 5, 2, and 2 percents, respectively.
---------------------------------------------------
J81-1004:2	13:105	Damerau (1981) summarizes experience with the Transformational Question Answering System (TQA) during the first full year of operation, 1978.
---------------------------------------------------
