In the study by Eastman and McLean (1981) this occurred in 3.3% of all queries. 
In another experiment (Eastman and McLean 1981), 693 English queries to a data base system were analyzed. 
If one includes telegraphic and elliptical constructions in the class of absolute ill-formedness, then case s~udies reported in Thompson (1980) and Eastman and McLean (1981) indicate that as much as 25% of queries to questionanswering systems are absolutely illformed. 
In one study (Eastman and McLean 1981), subject-verb disagreement occurred in 2.3% of the English queries. 
American Journal of Computational Linguistics, Volume 9, Numbers 3-4, July-December 1983 163 Ralph M. Weischedel and Norman K. Sondheimer Meta-rules as a Basis for Processing Ill-Formed Input Nor does a metric reflect the fact that there are clear patterns of error, such as those that have been reported in linguistic studies (Fromkin 1973) and in application studies (Thompson 1980, Eastman and McLean 1981). 
