(Hirst, 1981) discusses several early approaches to anaphora resolution in discourses.


\[3\] Hirst, G. , Discourse-Oriented Anaphora Resolution, American Journal of Computational Linguistics 7.2 (1981) 85-98.


Results of discourse analysis can be used to solve many important NLP problems such as anaphoric reference (Hirst 1981), tense and aspect analysis (Hwang and Schubert 1992), intention recognition (Grosz and Sidner 1986; Litman and Allen 1990), or'can be directly applied to computational NLP applications such as text abstraction (Ono et al. 1994; T'sou et al. 1996) and text generation (McKeown 1985; Lin et al. 1991).


Yet, it is well known that pragmatic and structure parallelism considerations may allow a pronoun to be non ambiguous even if L3 has more than one element (G. Hirst 1981, C. Sidner 1981, K. McKeown 1985, L. Danlos 1987a).


