We compare our treatment of revision with those of Mann and Moore (1981), Gabriel (1984), and Mann (1983). 
We further show that many earlier approaches to generating complex sentences (Derr & McKeown, 1984; Davey, 1974; Kukich, 1985; Mann & Moore, 1981) have architectural limitations that would keep them from handling these types of constructions with any generality. 
We can see elements of such a language in the "realization specifications" of McDonald and Conklin (1982) and in the "protosentences" of Mann and Moore (1981). 
I. Constructing the meaning of sentences Most work on natural language generation has been concerned with the production of connected text (Davey, 1979; Goldman, 1975; Mann and Moore, 1981; Meehan, 1977) or with language generation as a goal-directed, planned activity (Appelt, 1980; Mann and Moore, 1981). 
Mann, William & James Moore (1981), "Computer Generation of Multi-paragraph English Text". 
