A third problem, mentioned in Kaan, Kas & Puhland (1990), is that in practice, e.g. in implementations, one is tempted to make rough translations, and to neglect nuances or strong conversational implicalures in natural language, when one is limited to 3 and V. So, for instance, in Warren & Pereira (1982) %', 'some' and 'the' all are simply interpreted as ~. 
CHAT-80 (Warren & Pereira, 1982) was a DCG-based NLquery system about world geography, entirely in Prolog. 
Many database interfaces have such capabilities, McCord (1982), Dahl (1982) and Warren and Pereira (1982) inter a//a. 245 Semantics. 
CHAT-80 (Warren & Pereira, 1982), for instance, was a DCG-based NL-query system about world geography, entirely in Prolog. 
Warren, D.H.D. & F.C.N. Pereira (1982), "An Efficient Easily Adaptable System for Interpreting Natural Language Queries", American Journal of Computational Linguistics 8, 110-119. 
