J84-3001:1	210:379	Tree Adjunct Grammar The tree adjunct grammars (TAG) of Joshi and his colleagues (1982, 1984) provide a different way of accounting for syntactic dependencies.
---------------------------------------------------
J84-3001:2	220:379	The formal properties of TALs are fully discussed by Joshi, Levy, and Takahashi (1975); Joshi and Levy (1982); and Yokomori and Joshi (to appe~ar).
---------------------------------------------------
P83-1002:3	7:194	In a cree-adJoinlng grammar (TAG), which has been introduced earlier in (Joshi,1982), unhoundedness is achieved by factoring the dependencies and recursion in a novel and, we belleve, in a linguistically interesting manner.
---------------------------------------------------
J89-1001:4	25:552	Given the present tendency to emphasize the reducibility of natural language to tractable formal languages (see, for instance, Joshi and Levy 1982), and the high level of ambiguity typical of natural language, this is a fairly natural choice.
---------------------------------------------------
J89-1001:5	17:552	In recent years work on a number of languages other than English, the renewed interest in nontransformational grammars, and the taking into account of the experience in parsing have influenced the appearance of new linguistic theories, such as lexical-functional grammar (Kaplan and Bresnan 1982), generalized phrase structure grammar (GPSG) (Gazdar and Pullum 1982), functional unification grammar (FUG) (Kay 1979), definite clause grammar (DCG) (Pereira and Warren 1980), and tree adjoining grammar (TAG) (Joshi and Levy 1982).
---------------------------------------------------
J83-2002:6	373:383	This is contrary to what seems to be the general tendency today, both in theoretical linguistics (for example, Gazdar 1981) and in computational linguistics (for example, Hirshman and Puder 1982, Joshi and Levy 1982, Robinson American Journal of Computational Linguistics, Volume 9, Number 2, April-June 1983 79 Veronica Dahl and Michael C. McCord Treating Coordination in Logic Grammars 1982, Schubert and Pelletier 1982), towards using context-free grammars (which, however, are often augmented in some way through restrictions, local constraints, rule schemata, metarules, etc. compensating for the lack of expressiveness in simple contextfree grammars).
---------------------------------------------------
