Schubert, L.K. & F.J. Pelletier (1982) "From English to Logic: Context-Free Computation of 'Conventional' Logical Translation" American Journal of Computational Linguistics 8, 26-44. 
(Systems operating in more or less this manner are described in Rosenschein and Shieber 1982, Gawron et al. 1982 and Schubert and Pelletier 1982. 
Schubert, L.K. & F.J. Pelletier (1982), "From English to Logic: Context-Free Computation of 'Conventional' Logical Translation", American Journal of Computational Linguistics 8, 26-44. 
1981, Schubert & Pelletier 1982, Gawron et al 1982, Rosenschein & Shieber 1982). 
Schubert L.K. and Pelletier F.J. \[1982\] From English to Logic: Context-free Computation of 'Conventional' Logical Translation, American Journal of Computational Linguistics, Vol 8, NO 1, (Jan-Mar 1982), 27-44. 
