The problem of handling ill-formed input has been studied by Carbonell and Hayes (1983), Granger (1983), Jensen et al. 
Carbonell and Hayes (1983) describe research extending that reported by Hayes and Carbonell (1981). 
1 Introduction ExtragrammaticM sentences include patently ungrammatical constructions as well as utterances that may be grammaticMly acceptable but are beyond the syntactic coverage of a parser, and any other difficult ones that are encountered in parsing (Carbonell and Hayes, 1983). 
The same is true of many other systems for dealing with ill-formed input (e.g. Carhonell and Hayes (1983), Jensen et al. 
Carbonell and Hayes (1983) briefly describe recovery strategies for broken-off and restarted utterances in textual input. 
