(Fass and Wilks, 1983) proposes the use of preference semantics for metaphor recognition. 
Unlike other systems that 862 have focused on error recovery at a particular level (Damerau, 1964; Mellish, 1989; Fass and Wilks, 1983), CHAPTER uses an integrated agenda system, which integrates lexical, syntactic, surface case, and semantic processing. 
Another strategy is based on Preference Semantics (Wilks, 1975, 1978) (Fass & Wilks, 1983). 
Various systems have focused on the recovery of ill-formed text at the morphosyntactic level (Vosse, 1992), the syntactic level (Irons, 1963; Lyon, 1974), and the semantic level (Fass and Wilks, 1983; Carbonell and Hayes, 1983). 
(iv) Preference Semantics Preference Semantics has claimed that appropriate structurings can be obtained using essentially semantic information, given also a rule of preferring the most densely connected representations that can be constructed from such semantic information (Wilks 1975, Fass & Wilks 1983). 
