14 A similar definition is given in Berwick (1984, p. 198) and in Berwick and Weinberg (1984, p. 113).


The importance of this property becomes clear in contrasting theories underlying GPSG (Gazdar, Klein, Pullum, and Sag, 1985), and GB (as described by Berwick, 1984) with those underlying LFG and FUG.


4.2 Semilinearity of LCFRL's Semillnearity and the closely related constant growth property (a consequence of semilinearity) have been discussed in the context of grammars for naUtral languages by Joshi (1983185) and Berwick and Weinberg (1984).


For example, Gazdar (1985) discusses the applicability of Indexed Grammars (IG's) to Natural Language in terms of the structural descriptions assigned; and Berwick (1984) discusses the strong generative capacity of Lexical-Functional Grammar CLFG) and Government and Bindings grammars (GB).


However, the recognition complexity of GB languages, as formalized in Berwick (1984) or in more "faithful" models, remains open, and may arise from other constraints.


