As Cohen claimed that it is useful to understand referring expressions from the viewpoint of speech act planning (Cohen, 1984), it is not so ridiculous to go one step further and to consider the entire sequence of actions, including attention shifts, as an instance of a plan for object referring. 
A description about the collection of these excerpts can be found in Cohen (1984). 
It has provided the basis for a previous research report (Cohen, 1984) that compared communicative indirection and illocutionary style in the keyboard and telephone conditions. 
There is evidence presented by Cohen (1981, 1984) that a speaker attempts as a separate step in his overall plan of communication to get a hearer to identify a referent. 
A large corpus of dialogues concerning this task was collected by Cohen (see Cohen 1981, 1984; Cohen, Fertig, and Starr 1982). 
