Two new arguments, Higginbotham's (1984) one involving such that relativization and Postal and Langendoen's (1984) one about sluicing were dismissed on grounds of descriptive inadequacy by Pullum (1984a), who, however, suggested that the Langendoen and Postal (1984) argument about the doubling relativization construction may be correct (all these arguments deal with English).


Langendoen and Postal (1984) consider sentences like Joe was talking about some bourbon-lover, but WHICH bourbon-lover is unknown, and argue that a compound noun of any length can replace the first occurrence of bourbon-lover provided the same string is substituted for the second occurrence as well.


Two entirely new arguments on the topic have recently appeared: one by Postal and Langendoen (in this issue) and one by Higginbotham (1984).


3 A refinement of the context of discussion which l will ignore here is that these authors have argued that natural languages contain sentences of infinite length (e.g. , infinite coordinations, see Langendocn and Postal (1984)), which means they are not recursively enumerable, and not even sets.


