Two new arguments, Higginbotham's (1984) one involving such that relativization and Postal and Langendoen's (1984) one about sluicing were dismissed on grounds of descriptive inadequacy by Pullum (1984a), who, however, suggested that the Langendoen and Postal (1984) argument about the doubling relativization construction may be correct (all these arguments deal with English).


Pullum (1984b) likewise heaped scorn on my argument that English reshmuplicative constructions show non-CFness, but he accepted (1984a; 1984b) Culy's (1985) argument about noun reduplication in Bambara and Shieber's (1985) one about Swiss German cross-serial constructions of causative and perception verbs and their objects.


With this richer conception of PSG it is not at all obvious whether natural languages can be described by context-free grammars (see e .g . Pullum, 1984) . Generalized Phrase-Structure Grammar (GPSG; Gazdar et al. , 1985), represents a recent attempt to provide a theoretically acceptable account of natural-language syntax in the form of a phrase-structure grammar.


