J91-1003:1	39:818	Space does not permit discussion of other AI work on metaphor by, e.g., Russell (1976) and Weiner (1984; 1985).
---------------------------------------------------
J88-3005:2	259:440	Other work, such as Carbonnell and Collins (1970) and Weiner (1984), has hand-encoded salience values for attributes of individual objects directly into the knowledge base, permanently setting the ffunction.
---------------------------------------------------
J88-3005:3	234:440	Several systems that do assess object similarity (Rumelhart and Abrahamson 1973, McKeown 1982, Carberry 1984, Weiner 1984) use a metric based on distance in some space.
---------------------------------------------------
