J89-1003:1	787:810	Prior to the development of Prolog, Alain Colmerauer worked in the period 1967-70 on a machine translation project, the TAUM project--Traduction Automatique Universit6 de Montr6al (Colmerauer et al. 1971, Kittredge, Boutbeau and Isabelle 1973, Isabelle and Bourbeau 1985).
---------------------------------------------------
J90-2001:2	34:265	Some papers have mentioned limited restructuring of intermediate representations (Bennett and Slocum 1985; Vauquois and Boitet 1985; Isabelle and Bourbeau 1985; Nagao et al. 1985; McCord 1985; Nomura et al. 1986).
---------------------------------------------------
