For example, Carroll (1966) used a nine-point scale where point 1 was defined as hopelessly unintelligible and point 9 as perfectly clear and intelligible; Nagao and colleagues (Nagao et al. , 1985), in contrast, used a five-point scale, while Arnold and his colleagues (Arnold et al. , 1994) suggest a four-point discrimination. 
The Mu system (Nagao et al. 1985) has two specific restructuring functions, before and after the transfer phase, mainly to handle exceptional cases. 
Transferbased MT (e.g. Vauquois and Boitet (1985), Nagao et al. 
Usually, the two texts in question are the source (i.e. , original) text and the (machine-)translated text and the judges are expert translators who are again invited to rate the relative information content of pairs of sentences on an anchored scale (e.g. , Nagao et al. , 1985). 
(Vauquois and Boi~et, 1985; Nagao et al. , 1985), is based on con~rastive bilingual corpus analyses from which a bilingual lexicon of transfer equivalences is derived. 
