In the long run it is likely that these disambignation rules should be done away with, substituting disambiguation by side effect as proposed by Milne (1986).


An ambiguous lexleal entry has features for all of its potential types associated wlth that item and lexlcal ambiguity resolution procedures choose the appropriate features during the parse(/Milne 1983/ and /Milne 1986/).


Extensions to PARSIFAL have been researched independently including the parsing of ungrammatical sentences in PARAGRAM (Charniak, 1983), the resolution of lexical ambiguities in ROBIE (Milne, 1986), and the acquiring of syntactic rules from examples in LPARSIFAL (Berwick, 1985).


