At other times, IP will be uncertain whether the description is sufficiently detailed; she could go to the extreme and include every detail at her disposal, but this may confuse the listener and hamper identification (Goodman 1986).


In constructing a description, IP uses knowledge about the listener (Appelt 1985, Goodman 1986) to produce a concise reference that she believes will be acceptable.


An approach that fits better to our intentions is the work by Goodman [1987], which emphasizes reference identification and associated failures in task-oriented dialogs [Goodman 1986].


