Earlier researchers who have investigated this insight are \[Erman et al. , 1980\], \[Walker, 1978\], \[Fink and Biermann, 1986\], \[Mudler and Paulus, 1988\], \[Carbonell and Pierrel, 1988\], \[Young et al. , 1989\], and \[Young and Proctor, 1989\].


This information has long been used to discriminate between ambiguous interpretations and correct mistakes made by the speech recognizer (Fink and Biermann 1986; Smith 1992).


(1980), Walker (1978), Fink and Biermann (1986), Mudler and Paulus (1988), Carbonell and Pierrel (1988), Young (1990), and Young et al.


