by J.Slocum, Cambridge University Press, 1988 (Niremburg 1987) S. Nirenburg, V. Raskin The subworld concept lexicon a~d the Lexicon management S=ystem in C~_A~utational Li_~uistics n. 13, 1987 (Niremburg 1989) Niremburg S. , Raskin V. , McCardetl R. Ontology based lexical ac_.c_quisition in Proc.


The types of activities in generation often differ from those in analysis (see, e.g., Nirenburg and Raskin, 1987).


The decision to assign a word to a category is far from being straightforward (Nirenburg and Raskin (1987)) and often the lexicon builders do not use consistent classification pfincipia.


