\[MEL'CUK/POLGUERE 1987\]:271f themselves stress the advantage of describing collocations with lexical functions within language generation and machine translation: they give the example of OPER (*QUESTION*), realized as  English ask a question,  French poser une question,  Spanish hacer una pregunta and  Russian zadat' vopros respectively 11 . 3.1 Lexicon structure and possible generalizations On the basis of the analysis of some entries in \[MEL'CUK et al. 1984\] and of material we 11Here *QUI~STION* refers to a concept that stands for the language-specific items.


