Generalized LR Parsing Tomita /Tomita 1985/, /Tomita 1987b/ introduced the Generalized LR Parsing Algorithm for Augmented Context-Free Grammars, which can ingeniously handle nondeterminism and ambiguity with a graph-structured  stack. 
3 The QLR Translation Module The (\]LR.* parser (Lavie and Tomita 11993; I,avie 1994) is a parsing system based on Tomita's Generalized LI~ parsing algorithm (Tomita 1987). 
24 constructed from this backbone (Tomita, 1987). 
Similar to the work of Lang (1974) and Tomita (1987) extending LR parsers for arbitrary CFGs, the LR parsers for TAGs can be extended to solve by pseudo-parallelism the conflicts of moves. 
Chart (Kaplan 1973) and shared, packed forest (Tomita 1987) are packed data structures for context-free parsing. 
