Comp,'tred with other logic programming approaches/Matsumoto 1983, McCord 1987, Pereira 1981, Stabler 1987/, especially RLGs/Stabler 1987/, GBLGs have the following features: (1) the uniform treatments of leftward movement and the rightward movement, (2) the arbitrary number of movement non-terminals in the det man who 2 3 w w noun rel_gronoun cut trace 10~ np J he met trace 4~ 6~ pronoun tv np vp(trace).\x~ 8 s(trace),,'," tel .\~,, ,' I ~ce t6,~ S is a teacher tv det noun np  i ts;~ vp Figure 2.


/Abney 1986/, /Berwick 1987/, /Correa 1987/, /Kashket 1987/,/Kuhns 1986/,/Sharp.1985/,/Stabler 1987/,/Thiersch 1988/, and/%'ehrli I984/.


Stabler, 1987) in order to delimit the new territory, can be shown to be inadequate for this purpose, since it is provable that the class of languages generable by XGs coincides with Type 0 (i,e. XGs have the power of Turing machines), whereas the increase of power by the stack mechanism is not even enough to generate all Type 1 languages (see below).


