Boguraev and Briscoe (1987)discusses interpreting the information published in on-line dictionaries, while Zernik a/~d Dyer (1987) discuss tutored learning in a con.


Zernik and Dyer (1987) present lexical representations for idioms, but do not discuss ambiguity.


It is therefore possible to relate the syntactic category of the idiom to that of its head (see also Zernik and Dyer 1987).


Failure to apply either A-raising or so-called It-Extraposition 3 Earlier work using a lexical hierarchy and inheritance in natural language processing includes Wilensky (1981), Jacobs (1985) and Zernik and Dyer (1987).


More specifically, the notion of the phrasal lexicon (used first by Becker 1975) has been used successfully in a number of areas:  Learnability (Zernik and Dyer 1987)  Text generation (Hovy 1988; Milosavljevic, Tulloch, and Dale 1996)  Speech generation (Rayner and Carter 1997)  Localization (Schaler 1996) More recently, Simard and Langlais (2001) have proposed the exploitation of TMs at a subsentential level, while Carl, Way, and Schaler (2002) and Schaler, Way, and Carl (2003, pages 108109) describe how phrasal lexicons might come to occupy a central place in a future hybrid integrated translation environment.


