a context tree (Carberry 1988) representing IS's inferred underlying task-related plan; 2. 
See, for example, Allen and Perrault (1980), Allen (1983), Kautz (1991), Litman and Allen (1987), Pollack (1986), and Carberry (1988, 1990). 
This is called plan recognition in the literature and has been the object of much study (Allen and Perrault, 1980; Litman and Allen, 1987; Pollack, 1986; Carberry, 1988; Carberry, 1990). 
The context tree is inferred and constructed from the preceding dialog using the incremental plan recognition algorithm implemented in the TRACK system and described in Carberry (1988). 
A related problem, that of understanding pragmatically ill-formed utterances (utterances that violate the system's model of the world), is addressed in Carberry (1988). 
