The construction is defined in Fillmore's (1988) Construction Grammar as "a pairing of a syntactic pattern with a meaning structure"; they are similar to signs in HPSG (Pollard & Sag 1987) and pattern-concept pairs (Wilensky & Arens 1980; Wilensky et al. 1988).


DIRC is essentially "empty-UC" (UNIX Consultant, Wilensky et al. , 1988).


DIRC is essentially "emptyoUC" (UNIX Consultant, Wilensky et al. , 1988).


