W03-2107:1	25:248	In order to adapt the systems behavior to individ- ual users, it is necessary to model the users patterns (Kass and Finin, 1988).
---------------------------------------------------
P03-1033:2	20:207	In order to adapt the systems behavior to individual users, it is necessary to model the users patterns (Kass and Finin, 1988).
---------------------------------------------------
