McCoy(1988) uses the system's model of the user's domain knowledge to determine possible reasons for a detected misconception and to provide appropriate explanations to correct the misconception.


2.2 Cooperative Response Generation Many researchers (McKeown, Wish, and Matthews 1985; Paris 1988; McCoy 1988; Sarner and Carberry 1990; Zukerman and McConachy 1993; Logan et al. 1994) have argued that information from the user model should affect a generation system's decision on what to say and how to say it.


Several correction strategies have been suggested:  Generalize a description by selectively ignoring some constraints (see Goodman 1985; McCoy 1985, 1986, 1988; Carberry 1988; Calistri-Yeh 1991; Eller and Carberry 1992),  Make a description more specific by adding extra constraints (see Eller and Carberry 1992), and  Choose a conceptual "sibling", by combining generalization and constraint operations.


A number of important contributions have been made in the area of user modeling (Kobsa and Wahlster 1988; Rich 1988; Paris 1988; McCoy 1988).


