A92-1027:1	207:253	A recent, comparably systematic system where closed class words are used is described by O'Shaughnessy (1989).
---------------------------------------------------
J90-3003:2	372:623	And while researchers in text-tospeech synthesis have adopted a variety of approaches to prosodic phrase generation--from the simple punctuationbased rules and function word listings of existing commercial systems to the sophisticated prosodic heuristics described in Emorine and Martin (1988) and O'Shaughnessy (1989)---the generation of appropriate prosodic phrasing in unres~tricted text has remained a problem.
---------------------------------------------------
E91-1025:3	47:100	(Garside 1987, Marshall 1987, DeRose 1988, Church 1988, Ejerhed 1987, O'Shaughnessy 1989).
---------------------------------------------------
J94-1002:4	78:484	Motivated by similar principles and using only a 300-word dictionary, O'Shaughnessy (1989) proposes a somewhat more sophisticated parser for English based on function word identification, number agreement, and suffix identification.
---------------------------------------------------
J94-1002:5	178:484	Commas (and other punctuation) can be very useful for prosodic boundary prediction when they are available, and they are used in other algorithms (e.g. , Allen, Hunnicutt, and Klatt 1987; O'Shaughnessy 1989; Bachenko and Fitzpatrick 1990).
---------------------------------------------------
