\[Carberry 891 Carberry, S. : A Pragmatics-Based Approach to Ellipsis Resolution, Computational Linguistics, Vol.15, No.2, pp75-96(1989).


A common, generally applicable'approach is to use plan-inference as a basis for reasoning:about intentions of the user as proposed by, for instance, Allen & Perrault (1980), Litman (1986), Carberry (1989) and Pollack (1986).


Domain and problemsolving actions have been investigated by many researchers (Allen and Perrault 1980; Perrault and Allen 1980; Wilensky 1981; Litman and Allen 1987; van Beek and Cohen 1986; Ramshaw 1989; Carberry 1990).


In our earlier work (Carberry 1985, 1989), we claimed that a cooperative participant must accept a response or pursue discourse goals directed toward being able to accept the response.


