As Savitch (1989, p. 255) comments, " in some circles \[being a full AFL\] invests the class \[of languages\] with a certain respectability".


Since the reduplication languages (Savitch, 1989) are central to the point of this paper we define them-the languages homomorphic to the set of strings {ww\[w 6 {a,b}*}.


(1989) conjecture that there is actually a convergence in expressive power among the 'mildly context sensitive' (MCS) languages, but other work points out exceptions (Savitch, 1989; Vogel and Erjavec, 1994).


The family that we characterized above in terms of graInntars arc tn'operly a sullset of the languages recognized by R.PDA, a restrk:tion of RPDA languages which Savitch (1989) terlns simple R, PDA lanqu,.qes.


Savitch (1989) does exactly that by prese, nting the model of con> put;at|on required for the class of languages delined by augment;ing the CFLs with redut)lication: a Reduplicat;ion PDA (RPDA).


