Stock In Stock's (1989) approach to ambiguity resolution, firstly, the idiomatic and the non-idiomatic analysis are processed in parallel. 
A study on a set of sentences of TUT shows that the basic word order for Italian is SubjectVerb-Complement (SVC), as known in literature (Renzi, 1988), (Stock, 1989), but in more than a quarter of declarative sentences it is violated (see the following table 6 ). 
In Stock's (1989) approach to ambiguity resolution the idiomatic and the nonidiomatic analyses are processed in parallel. 
Lexical preferencing (Stock 1989) (van der Linden 1991) is particularly useful for the treatment of idiomatic expressions. 
(1995), Laporte (1988), Schenk (1995), Stock (1989), among others. 
