Recently, a new version (McCord 1989b, 1990) was developed in a logic programming framework, in connection with the machine translation system LMT (McCord 1989a, 1989c, 1989d). 
See (McCord 1989b) for more discussion of the relation of Slot Grammar to other systems. 
Recently, a new version (McCord 1989b) was developed in a logic programming framework, in connection with fhe machine translation system LMT (McCord 1989a,c,d). 
See McCord (1989b) for more discussion of the relation of Slot Grammar to other systems. 
Three examples of such systems are (1) GETA/ARIANE (Vauquois and Boitet 1985; Boitet 1987); (2) LMT (McCord 1989); and (3) METAL (Alonso 1990; Thurmair 1990). 
