Text generators specifically designed for instructional text, such as Mellish and Evans' generator (Mellish and Evans 1989), EPICURE (Dale 1992), COMET (McKeown et al. 1990), and TECHDOC (R6sner and Stede 1992b), display similar characteristics.


In computational linguistics, on the other hand, positive imperatives have been extensively investigated, both from the point of view of interpretation (Vere and Bickmore, 1990; Alterman et al. , 1991; Chapman, 1991; Di Eugenio, 1993) and generation (Mellish and Evans, 1989; McKeown et al. , 1990; Paris et al. , 1995; Vander Linden and Martin, 1995).


