In addition, it has a relatively simple method of computing possible quantifier scoping, drawing from the approaches by (Hobbs & Shieber, 1987) and (Alshawi, 1990). 
Examples are Quasi Logical Forms (Alshawi, 1990), Dynamic Predicate Logic (Groenendijk and Stokhof, 1991), and Underspecified Discourse Representation Theory (Reyle, 1993). 
The grammar describes the relation between a subset of German and a subset of QLF, the intermediate semantic form that is used in the Care Language Engine of SRI Cambridge (Alshawi 1990). 
In addition to syntactic clues, other studies have noted that the choice of quantifier has a significant effect on scope disambiguation (e.g., each has a greater tendency for wide scope than every) (Van Lehn, 1978; Alshawi, 1990). 
Alshawi, Hiyan (1990) "Resolving Quasi Logical Forms". 
