The most detailed description of grammatical regularities and an associated parsing procedure has been supplied by Lappin and McCord (1990). 
This is essentially the strategy outlined by Lappin and McCord (1990). 
 A morphological filter for ruling out anaphoric dependence of a pronoun on an NP due to non-agreement of person, number, or gender features  A procedure for identifying pleonastic (semantically empty) pronouns  An anaphor binding algorithm for identifying the possible antecedent binder of a lexical anaphor (reciprocal or reflexive pronoun) within the same sentence (This algorithm is presented in Lappin and McCord 1990b). 
Lappin and McCord (1990, p.205) for a similar argument). 
Lappin and McCord (1990) present an algorithm for VP ellipsis which contains a partial treatment of this problem. 
