Computational approaches are mostly concerned with inferring implicitly expressed metonymic relations in English texts (Fass 1991), Hobbs (Hobbs et al. 1993) (Lakoff and Johnson 1980), (Nunberg 1993, 1995), (Pustejovsky 1991), and (Wilks 1975) are prominent representatives. 
Related Work Two of the most broadly effective computational models of metaphor are Fass (1991) and Martin (1990), in both of which metaphors are detected through selectionalpreference violations and interpreted using an ontology. 
All of the 25 sentences which are used in the survey are taken from metonymy examples in English in previous works (Lakoff and Johnson 1980, Fass 1991, Yamanashi 1987). 
Fass (Fass, 1991) uses selectional preference violation technique to detect metaphors. 
In his program met*, (Fass 1991) makes use of formal definitions of several kinds of metonymic relations; met* also allows chaining metonymic relations in order to fill in implicitly expressed knowledge. 
