Their results show that logical metonymy is a relatively widespread phenomenon and that most metonymic examples can be interpreted on the basis of the head nouns qualia structure, assuming a theoretical framework similar to Pustejovskys (1991). 
We will assume, for this paper, the general framework of a generative lexicon as outlined in Pustejovsky (1991). 
This brings compound interpretation under the same rubric as other forms of composition in natural language, including argument selection, adjectival modification, and type coercion (Pustejovsky (1991,1995), Bouillon 1995). 
These aspects of TAGs are crucial to SPUD, as they are to (McDonald and Pustejovsky, 1985; Joshi, 1987; Yang et al. , 1991; Nicolov et al. , 1995; Wahlster et al. , 1991; Danlos, 1996). 
The class of phenomena that Pustejovsky (1991, 1995) has called logical metonymy is one such example. 
