 In many languages, general-purpose graphemeto-phoneme rules are to a significant extent inappropriate for names (Macchi and Spiegel, 1990; Vitale, 1991).


Various reasons are given in the research literature (Carlson, GranstrSm, and LindstrSm, 1989; Macchi and Spiegel, 1990; Vitale, 1991; van Coile, Leys, and Mortier, 1992; Coker, Church, and Liberman, 1990; Belhoula, 1993):  Names can be of very diverse etymological origin and can surface in another language without undergoing the slow linguistic process of assimilation to the phonological system of the new language.


(1976), Hertz (1979, 1981, 1982, 1983, 1985), Hunnicutt (1976, 1980), Levin (1963), McCormick and Hertz (1989), McIlroy (1974), O'Malley (1990), Venezky (1962, 1967a, 1967b, 1967c, 1970), Venezky and Weir (1966), Vitale (1991), Weir (1964); for French: Auberg4 (1991), B4chet, Spriet, and E1-B~ze (1996), Catach (1989), Catach and Catach (1992), Cotto (1992), Divay (1984, 1985, 1990a, 1990b, 1991, 1994), Laporte (1988), Prouts (1980), Yvon (1996).


For example, there are roughly 1.5 million different surnames in the US alone (Spiegel 1985; Spiegel and Machi 1990; Vitale 1991); moreover, one-third of these surnames are unique in that they are singletons.


There have been successful attempts to automatically detect the ethnic group of a proper name for use in anglophone countries like the United States, and to apply a different set of rules depending on that group (Church 1985, Vitale 1991).


