We are currently experimenting the way techniques of computer-aided acquisition for learning conceptual relations fi'om syntactic collocates (Velardi et al. 1991) can be applied to N N associations.


5 Related work Previous natural language acquisition models couht be characterized as interactive acquisition \[tang & tIirschman, 1988; Liu & Soo, I993a, 1993b; Velardi ct al. , 1991\], corpus-based acquisition \[Brent, 1993; 3acobs & Zernik, 1988; Zernik, 1989\], dictionary-based acquisition \[Montemagni & Vanderwende, 1992; Sanfilippo & Pozanski, 1992\], statistics-based acquisition \[Smadja, 1991; Sekine et al, 1992\], and connectionistbased acquisition \[Paisal & Kwasny, 1990; McClelland & Kawamoto, 1986\].


Most existing computational natural language acquisition models also assumed various kinds of the extra input (e.g. semantic associations \[Siskind, 1990; Webster & Marcus, 1989; Zernik, 1987\] and syntactic structures \[Berwick, 1985; Liu & Soo, 1992a\] of input sentences) and human intervention (e.g. information interactively given by the trainer \[tang & Ilirschman, 1988; Velardi et al. , 1991\]) during learning.


Although the current prototype uses a hand-written knowledge base, some techniques for semi-automatic extraction of semantic knowledge from our large corpus have been studied in our project (Velardi et al. , 1991).


