The 1Compare the cogent argument for a inheritance-based lexicon in (Flickinger and Nerbonne, 1992), much of which can be applied unchanged to the taxonomy of SCFs.


So far, lexicons have been structured in syntactic inheritance hierarchies, in which more or less abstract syntactic classes form the upper nodes and actual words are associated with the leaf nodes (Flickinger and Nerbonne, 1992; Russell et al. , 1992).


This theory guides the structuring of lexical information and also decides what information should be available to the user (Andry et al. , 1992; Flickinger and Nerbonne, 1992; Mel'Suk and Polgu~re, 1987; Russell et ~l. , 1992; Krieger and Nerbonne, 1991).


The most common linguistic application for default inheritance is to encode lexical generalizations (e.g. , Boguraev and Pustejovsky 1990; Briscoe, Copestake, and Boguraev 1990; Vossen and Copestake 1993; Daelemans 1987; Evans and Gazdar 1989a, 1989b, 1996; Flickinger, Pollard, and Wasow 1985; Flickinger 1987; Flickinger and Nerbonne 1992; Kilgarriff 1993; Krieger and Nerbonne 1993; Sanfilippo 1993; Shieber 1986a), but defaults have also been used for specification in syntactic theory (e.g. , Gazdar 1987; Shieber 1986b), and for the analysis of gapping constructions (Kaplan 1987) and ellipsis (Grover et al. 1994).


