However, as Vijay-Shanker (1992) observes, the TAG composition operations are not used uniformly: while substitution is used only to add a (nominal) complement, adjunction is used both for modification and (clausal) complementation. 
3 Tree Descriptions Tree Description Grammars (TDGs) were inspired by so-called quasi-trees (Vijay-Shanker, 1992). 
The language of this description and its semantic is given by Rogers and Vijay-Shanker (1992). 
1.3 The DTG Approach Vijay-Shanker (1992) points out that use of adjunction for clausal complementation in TAG corresponds, at the level of dependency structure, to substitution at the foot node s of the adjoined tree. 
D-trees are descriptions of trees, in particular, certain types of expressions in a tree description language such as that of Rogers and Vijay-Shanker (1992). 
