Other relevant recent work not found there includes Bouma (1993), Briscoe, Copestake, and Lascarides (1995), Calder (1994), Copestake (1992), Daelemans (1994), Daelemans and De Smedt (1994), Ide, Le Maitre, and V6ronis (1994), Lascarides et al.


1 Introduction Several authors have highlighted the importance of using defaults in the representation of linguistic knowledge, in order to get linguistically adequate descriptions for some natural language phenomena ((Gazdar, 1987), (Bouma, 1992), (Daelemans et al, 1992), (Briscoe, 1993)).


Such an approach to representing the lexicon has some advantages, like its ability to capture linguistic generalisations, conciseness, uniformity, ease of maintenance and modification, and modularity (Daelemans et al, 1992).


The most common linguistic application for default inheritance is to encode lexical generalizations (e.g. , Boguraev and Pustejovsky 1990; Briscoe, Copestake, and Boguraev 1990; Vossen and Copestake 1993; Daelemans 1987; Evans and Gazdar 1989a, 1989b, 1996; Flickinger, Pollard, and Wasow 1985; Flickinger 1987; Flickinger and Nerbonne 1992; Kilgarriff 1993; Krieger and Nerbonne 1993; Sanfilippo 1993; Shieber 1986a), but defaults have also been used for specification in syntactic theory (e.g. , Gazdar 1987; Shieber 1986b), and for the analysis of gapping constructions (Kaplan 1987) and ellipsis (Grover et al. 1994).


2 Inheritance Lexica Research directed at reducing redundancy in the lexicon has come up with the idea of organizing the information hierarchically making use of inheritance (see, e.g. \[Daelemans et al. , 1992; Russell et al. , 1992\]).


