A third interesting project has produced the TINA system (Seneff 1992), which uses probabilistic networks to parse token sequences provided by a speech recognition system, SUMMIT, created by Zue et al. 
The resulting N-best hypotheses are processed by the TINA language understanding component (Seneff, 1992). 
Speech recognition results were parsed by the TINA parser (Seneff, 1992) using a hand-crafted grammar. 
Seneff (1992) describes the use of Markov models for rule generation, which is closely related to the Markov-style rules in the models in the current article. 
The input utterance is processed through the speech recognizer and language understanding (Seneff, 1992) components, to achieve a simple encoding of its meaning. 
