C96-2122:1	36:137	Less constrained dependency formalisms exist in the literature (Mel'cuk 1988) (Fraser, Hudson 1992), but no mathematical studies on their expressive power exist.
---------------------------------------------------
W98-0505:2	79:208	3.1 Coordinate structure: the limit of dependency in WG Word grammar (Hudson, 1984; Fraser and Hudson, 1992) strives to account for all grammatical relations by head-dependent relations.
---------------------------------------------------
W98-0510:3	84:174	He points out that in his theory, Word Grammar, multiple relations between two elements are allowed, and that a word may depend on more than one head simultaneously (see the discussion in Hudson 1992, p.145).
---------------------------------------------------
P98-2130:4	5:186	Introduction Many authors have developed dependency theories that cover cross-linguistically the most significant phenomena of natural language syntax: the approaches range from generative formalisms (Sgall et al. 1986), to lexically-based descriptions (Mel'cuk 1988), to hierarchical organizations of linguistic knowledge (Hudson 1990) (Fraser, Hudson 1992), to constrained categorial grammars (Milward 1994).
---------------------------------------------------
