Because of these benefits, we have designed a program to generate a sharedpacked parse forest annotated with the logical form developed by Harper (1990, 1992).


However, for multiple logical representations to share the logical representation of a child node, that representation cannot be affected by the process of constructing the logical form for the parent node, an assumption that does not always hold (e.g. , Harper 1990, 1992).


Combining Logical Form with Forests: A Case Study Previously, our logical form routines were interfaced with a one-parse-tree-at-a-time, top-down ATN parser (Harper 1990, 1992).


654 Mary P. Harper Storing Logical Form in a Shared-Packed Forest Unlike the ATN parser used by Harper (1990, 1992), the Tomita parser is a bottomup, all-path parsing algorithm that creates a parse forest by packing parse nodes together to save space and time.


In such an oversimplified model, quantifier ambiguity has often been translated to scoping ambiguity, and elaborate models were developed to remedy the problem, by semanticists (Cooper, 1983; Le Pore et al, 1983; Partee, 1984) as well as computational linguists (Harper, 1992; Alshawi, 1990; Pereira, 1990; Moran, 1988).


