We propose a corpus-based method (Biber,1993; Nagao,1993; Smadja,1993) which generates Noun Classifier Associations (NCA) to overcome the problems in classifier assignment and semantic construction of noun phrase.


Biber (1993) applies factor analysis to collocations of two target words ("certain" and "right") with their immediate neighbors.


In a previous paper (Schfitze, 1993), we trained a neural network to disambiguate part-of-speech *Although Biber (1993) classifies collocations, these can also be ambiguous.


A number of researchers have worked on mining collocations from text to extend lexicographic resources for machine translation and word sense disambiguation (e.g. , Smajda 1993; Lin 1999; Biber 1993).


