P00-1055:1	39:162	Martin Kay and Martin Rscheisen (1993) also needed clearly delimited sentences.
---------------------------------------------------
P00-1055:2	41:162	Two sentences were aligned if the number of correspondence points associating them was greater than an empirically defined threshold: [] more than some minimum number of times [] (Martin Kay and Martin Rscheisen, 1993, p.128).
---------------------------------------------------
C96-1006:3	16:170	Although a number of automatic sentence alignment methods have been proposed (Brown et al. 1991 ; Gale & Church 1991 b; Kay & Roscheisen 1993; Chen 1993), they are not very reliable for real noisy bilingual texts.
---------------------------------------------------
A94-1006:4	114:178	3 Bilingual Task: An Application for Word Alignment 3.1 Sentence and word alignment Bilingual alignment methods (Warwick et al. , 1990; Brown et al. , 1991a; Brown et al. , 1993; Gale and Church, 1991b; Gale and Church, 1991a; Kay and Roscheisen, 1993; Simard et al. , 1992; Church, 1993; Kupiec, 1993a; Matsumoto et al. , 1993; Dagan et al. , 1993).
---------------------------------------------------
J97-2004:5	13:485	For MT and other purposes, many methods have been proposed for sentence alignment of the Hansards, an English-French corpus of Canadian parliamentary debates (Brown, Lai, and Mercer 1991; Gale and Church 1991a; Sirnard, Foster, and Isabelle 1992; Chen 1993; Gale and Church 1993), and for other language pairs, including English-German, EnglishChinese, and English-Japanese (Kay and ROscheisen 1993; Church, Dagan, Gale, Fung, Helfman, and Satish 1993; Fung and McKeown 1994; Wu 1994).
---------------------------------------------------
C04-1154:6	12:166	(Kay and Roscheisen, 1993; Gale & Church, 1993), no methods exist for aligning non-isomorphic phrasestructure (PS) tree fragments at sub-sentential level for use in MT.
---------------------------------------------------
W06-1630:7	29:170	Recently, a Pearson correlation method was proposed to mine word pairs from comparable corpora (Tao and Zhai, 2005); this idea is similar to the method used in (Kay and Roscheisen, 1993) for sentence alignment.
---------------------------------------------------
D07-1041:8	106:222	3.1.1 Dice alignments A dictionary file is built using the variation of the Dice Coefficient (Dice (1945)) used by Kay and Roscheisen (1993): D(v,w) = 2cN A(v) +NB(w)   Here, c is the number of cooccurring positions and NT(x) is the number of occurrences of word x in corpus T. c is calculated only once for redundant occurrences in an aligned sentence pair.
---------------------------------------------------
P06-2092:9	34:152	The third approach uses bilingual lexical information, e.g. estimated from the corpus (Kay and Roscheisen, 1993; Fung and Church, 1994; Fung and McKeown, 1994).
---------------------------------------------------
P06-1062:10	58:173	(Kay & Roscheisen 1993; and Chen 1993) used lexical information for sentence alignment.
---------------------------------------------------
W09-0430:11	58:224	Several automatic sentence alignment approaches have been proposed based on sentence length (Brown et al., 1991) and lexical information (Kay and Roscheisen, 1993).
---------------------------------------------------
W03-1503:12	18:189	Sentential alignment (Brown et al. , 1991; Gale and Church, 1993; Kay and Roscheisen, 1993; Utsuro et al. , 1994; Haruno and Yamazaki, 1996) is commonly used as a starting point for finding the translations of words or expressions from bilingual corpora.
---------------------------------------------------
P06-1010:13	30:188	The general idea of exploiting frequency correlations to acquire word translations from comparable corpora has been explored in several previous studies (e.g. , (Fung, 1995; Rapp, 1995; Tanaka and Iwasaki, 1996)).Recently, a method based on Pearson correlation was proposed to mine word pairs from comparable corpora (Tao and Zhai, 2005), an idea similar to the method used in (Kay and Roscheisen, 1993) for sentence alignment.
---------------------------------------------------
W05-0808:14	28:193	Kay and Roscheisen (1993) tried lexical methods for sentence alignment.
---------------------------------------------------
W05-0808:15	16:193	(1991), Kay and Roscheisen (1993), Warwick et al.
---------------------------------------------------
J03-3004:16	84:536	3 Kay and Roscheisen (1993) attempt to extract a bilingual dictionary using a hybrid method of sentence and word alignment on the assumption that the source, target words have a similar distribution.
---------------------------------------------------
P96-1018:17	170:249	Our evaluation focuses on much smaller texts than those used in other study(Brown and others, 1993; Gale and Church, 1993; Wu, 1994; Fung, 1995; Kay and Roscheisen, 1993) because our main targets are well-separated articles.
---------------------------------------------------
P96-1018:18	123:249	We construct the initial ASM using such a function that pairs sentences near the middle of the two anchors with as many as O(~/~) (L is the number of sentences existing between two anchors) sentences in the other text because the maximum deviation can be stochastically modeled as O(~rL) (Kay and Roscheisen, 1993).
---------------------------------------------------
P96-1018:19	31:249	(Kay and Roscheisen, 1993) proposed a relaxation method to iteratively align bilingual texts using the word correspondences acquired during the alignment process.
---------------------------------------------------
P96-1018:20	88:249	These two parameters permit more effective relaxation than the single parameter used in conventional methods(Kay and Roscheisen, 1993).
---------------------------------------------------
P96-1018:21	183:249	This is identical to Kay's method (Kay and Roscheisen, 1993) except for the statistics used.
---------------------------------------------------
W02-1211:22	84:150	Kay & Roscheisen (1993) use a partial alignment of lexical items induce a maximum likelihood at sentence level.
---------------------------------------------------
W05-0816:23	26:198	Word correspondence was used by Kay (Kay, 1991; Kay and Roscheisen, 1993).
---------------------------------------------------
