2.2 Three Treebanks The Treebanks that we used in this paper are the English Penn Treebank II (Marcus et al. , 1993), the Chinese Penn Treebank (Xia et al. , 2000b), and the Korean Penn Treebank (Chung-hye Han, 2000). 
The Penn Wall Street Journal treebank (Marcus et al. 1993) was used as training and test data. 
Ralph Weischedel et al. 1993. 
4 Experiments The Penn Treebank (Marcus et al. , 1993) is used as the testing corpus. 
The data for all our experiments was extracted from the Penn Treebank II Wall Street Journal (WSJ) corpus (Marcus et al. , 1993). 
