This system incorporates sophisticated ambiguitymanagement technology so that all possible syntactic analyses of a sentence are computed in an efficient, packed representation (Maxwell and Kaplan, 1993). 
and grammar development platform (Maxwell and Kaplan, 1993) to develop deep grammars for six languages. 
This system incorporates sophisticated ambiguity-management technology so that all possible syntactic analyses of a sentence are computed in an efficient, packed representation (Maxwell and Kaplan, 1993). 
In this paper, we report on the the XLE system (Maxwell and Kaplan, 1993), a parser and grammar development platform for Lexical Functional Grammars. 
The key argument for using this linguistic workbench is the ability to produce packed representations for ambiguous utterances using techniques described in Maxwell III and Kaplan (1993) and the availability of a generator which generates utterances from f-structure descriptions. 
