Several researchers have tackled the syntactic analysis (Lauer, 1995), (Pustejovsky et al. , 1993), (Liberman and Church, 1992), usually using a variation of the idea of finding the subconstituents elsewhere in the corpus and using those to predict how the larger compounds are structured. 
The simplest of these is reported in Pustejovsky et al (1993). 
Finally, (Pustejovsky et al. , 1993) present an interesting framework for the acquisition of semantic relations from corpora not only relying on statistics, but guided by theoretical lexicon principles. 
Severalresearchers have tackled the syntactic analysis (Lauer, 1995; Pustejovsky et al. , 1993; Liberman and Sproat, 1992), usually using a variation of the idea of nding the subconstituents elsewhere in the corpus and using those to predict how the larger compounds are structured. 
\[Utsuro et al. , 1993\] categorise words using the "Bunrui Goi Hyou" (Japanese) thesaurus. 
