More recently, Bird and Ellison (1994) show that a one-level finite-state automaton can model richer phonological structure, such as the multitier representations of autosegmental phonology. 
This shift has, however, had relatively little impact upon computational work (but see Bird and Ellison 1994). 
Examples of the second type are all symbolic (Johnson 1984; Dresher and Kaye 1990; Ellison 1993; Bird 1994). 
As a starting point, I adopt Bird & Ellison (1994)'s One-Level Phonology, a monostratal constraintbased framework where phonological representations, morphemes and generalizations are all finitestate automata (FSAs) and constraint combination is accomplished via automata intersection. 
This choice has no theoretical consequences but is merely a convenience for grammar development (Bird and Ellison, 1994). 
