1 Introduction Subjectivity in natural language refers to aspects of language used to express opinions and evaluations (Ban eld, 1982;; Wiebe, 1994). 
Wiebe (1994), studies methods to track the change of point of view in narrative text (fiction). 
In contrast, experiments of Bruder and Wiebe (1990) and Wiebe (1994) show that paragraph breaks help readers to interpret private-state sentences in narratives, i.e., sentences about psychological states such as wanting and perceptual states such as seeing. 
The intellectual-attribution distinction we make is comparable with Wiebe's (1994) distinction into subjective and objective statements. 
In natural language, opinions, emotions and other private states are expressed using subjective lan- guage (Banfield, 1982; Wiebe, 1994). 
