P03-2003:1	11:143	They were proven to have recognition algorithms with time complexity O(n6) (Satta, 1994).
---------------------------------------------------
P98-2192:2	8:156	More generally, in (Satta, 1994) it has been argued that methods for TAG parsing running in time asymptotically faster than O(n 6) are unlikely to have small hidden constants.
---------------------------------------------------
P98-2192:3	9:156	A careful inspection of the proof provided in (Satta, 1994) reveals that the source of the claimed computational complexity of TAG parsing resides in the fact that auxiliary trees can get adjunctions at (at least) two distinct nodes in their spine (the path connecting the root and the foot nodes).
---------------------------------------------------
J99-3002:4	211:226	As shown by Nederhof and Satta (1994), a family of parsing algorithms (topdown, left-corner, PLR, ELR, and LR parsing \[Nederhof 1994\]) can be carried over to head-driven parsing.
---------------------------------------------------
J99-3002:5	13:226	Surprisingly, it has been claimed by Schabes and Waters (1995) that this property is problematic for the mildly contextsensitive languages represented by tree-adjoining grammars (TAGs): the best practical parsing algorithms for TAGs have time complexity Cg(n 6) (Vijay-Shankar and Joshi \[1985\]; see Satta \[1994\] and Rajasekaran and Yooseph \[1995\] for lower theoretical upper bounds), whereas the only published algorithm with the correct-prefix property--that by Schabes and Joshi (1988)--has complexity O(n9).
---------------------------------------------------
P97-1002:6	35:197	487), and Satta (1994) makes this assumption as well.
---------------------------------------------------
P97-1002:7	19:197	Our technique, adapted from that used by Satta (1994) for tree-adjoining grammar (TAG) parsing, is to show that BMM can be efficiently reduced to CFG parsing.
---------------------------------------------------
P97-1002:8	32:197	Secondly, a parser should create an output structure from which information about constituents can be retrieved in an efficient way -Satta (1994) points out an observation of Lang to the effect that one can consider the input string itself to be a retrievalinefficient representation of parse information.
---------------------------------------------------
P97-1002:9	47:197	Our method, adapted from that of Satta (1994) (who considered the problem of parsing with tree-adjoining grammars), is to encode information about Boolean matrices into a CFG.
---------------------------------------------------
