Constraints filter the candidate list of improbable antecedents, while preferences encourage selection of antecedents that are more recent, frequent, etc. Implementation of constraints and preferences can be based on empirical insight (Lappin and Leass, 1994), or machine learning from a reference88 annotated corpus (Ge et al. , 1998). 
Lappin and Leass (1994) implemented and tested Hobbs's algorithm, and reported results that were about 4% less than that of Lappin and Leass (1994). 
Syntactic Parallelism (Lappin and Leass, 1994): As per this heuristic, preference is given to noun phrases with the same syntactic function as the anaphor. 
3.3 Salience Score Filtering Previous work has reported the usefulness of salience for anaphora resolution (Lappin and Leass, 1994; Mitkov et al., 2002). 
ExtrAns adopts an anaphora resolution algorithm (Moll a et al. , 2003) that is based on Lappin and Leass approach (Lappin and Leass, 1994). 
