For example, Dagan and Itai (1994) carried out WSD experiments using monolingual corpora, a bilingual lexicon and a parser for the source language. 
The first baseline method is similar to (Dagan et al. , 1991; Dagan and Itai, 1994; Ballesteros and Croft, 1998; Smadja et al. , 1996), where we use the nearest neighboring word of the secondary language word C as feature for disambiguation. 
, 1998), (Dagan and Itai, 1994), (Tanaka and Iwasaki, 1996), (Kikui, 1998)), this section focuses on other related research. 
Introduction Treatment of lexical ambiguity such as WSD has been found useful in many NLP applications, including information retrieval (McRoy 1992; Krovetz and Croft 1992) and machine translation (Brown et al. 1991; Dagan et al. 1991; Dagan and Itai 1994). 
Dagan and Itai (1994) proposed an approach to WSD using monolingual corpora, a bilingual lexicon and a parser for the source language. 
