D08-1109:1	49:232	Unsupervised Part-of-Speech Tagging Since the work of Merialdo (1994), the HMM has been the model of choice for unsupervised tagging (Banko and Moore, 2004).
---------------------------------------------------
W02-0102:2	253:264	39Advanced students might also want to read about a modern supervised trigram tagger (Brants, 2000), or the mixed results when one actually trains trigram taggers by EM (Merialdo, 1994).
---------------------------------------------------
W05-0615:3	174:205	We have shown that, despite previous discouraging results (Carroll and Charniak, 1992; Merialdo, 1994), it is possible to achieve good results using EM to learn linguistic structures in an unsupervised way.
---------------------------------------------------
W05-0615:4	18:205	Merialdo (1994) showed that with only a tiny amount of tagged training data, supervised training of an HMM part-of-speech tagger outperformed unsupervised EM training.
---------------------------------------------------
W04-2602:5	127:214	While the literature suggests that Baum-Welch training can degrade performance on the tagging task (Elworthy, 1994; Merialdo, 1994), we have found in early experiments that agreement between a tagger trained in this way and the tagger from the XTag Project consistently increases with each iteration of Baum-Welch, eventually reaching a plateau, but not decreasing.
---------------------------------------------------
P08-1100:6	68:214	cussed by many authors (Merialdo, 1994; Smith and Eisner, 2005; Haghighi and Klein, 2006).2 To confront the question of specifically how the likelihood diverges from prediction accuracy, we perform the following experiment: we initialize EM with the supervised estimate3 gen = argmax Elogp(x,y), which acts as a surrogate for p.
---------------------------------------------------
W99-0615:7	11:151	appropriate smoothing techniques show better performance than the first order models and is considered a state-of-the-art technique (Merialdo, 1994; Brants, 1996).
---------------------------------------------------
I08-2130:8	9:148	There are two main approaches for POS tagging: rule-based and statistical algorithms(Merialdo, 1994).
---------------------------------------------------
P98-2132:9	6:92	Several kinds of POS taggers using rule-based (e.g. , Brill et al. , 1990), statistical (e.g. , Merialdo, 1994), memory-based (e.g. , Daelemans, 1996), and neural network (e.g. , Schmid, 1994) models have been proposed for some languages.
---------------------------------------------------
P06-2028:10	63:163	5 External Knowledge Sources 5.1 Lexical Dependencies Features derived from n-grams of words and tags in the immediate vicinity of the word being tagged have underpinned the world of POS tagging for many years (Kupiec, 1992; Merialdo, 1994; Ratnaparkhi, 1996), and have proven to be useful features in WSD (Yarowsky, 1993).
---------------------------------------------------
P06-2028:11	15:163	The basic engine used to perform the tagging in these experiments is a direct descendent of the maximum entropy (ME) tagger of (Ratnaparkhi, 1996) which in turn is related to the taggers of (Kupiec, 1992) and (Merialdo, 1994).
---------------------------------------------------
C96-1041:12	12:246	'\['here are three main approaches in tagging problem: rule-based approach (Klein and Simmons 1%3; Brodda 1982; Paulussen and Martin 1992; Brill et al. 1990), statistical approach (Church :1988; Merialdo 1994; Foster 1991; Weischedel et al. 1993; Kupiec 1992) and connectionist approach (Benello et al. 1989; Nakanmra et al. 1989).
---------------------------------------------------
P98-2123:13	71:123	Although more sophisticated algorithms for unsupervised learning which can be trained on plain text instead on manually tagged corpora are well established (see e.g. Merialdo, 1994), we decided not to use them.
---------------------------------------------------
P05-1001:14	9:242	Although useful under some circumstances, when a relatively large amount of labeled data is available, the procedure often degrades performance (e.g. Merialdo (1994)).
---------------------------------------------------
P03-1011:15	116:135	As seen for other tasks (Carroll and Charniak, 1992; Merialdo, 1994), the likelihood criterion used in EM training may not be optimal when evaluating a system against human labeling.
---------------------------------------------------
E95-1022:16	30:171	157 ena or the linguist's abstraction capabilities (e.g. knowledge about what is relevant in the context), they tend to reach a 95-97% accuracy in the analysis of several languages, in particular English (Marshall 1983; Black et aL 1992; Church 1988; Cutting et al. 1992; de Marcken 1990; DeRose 1988; Hindle 1989; Merialdo 1994; Weischedel et al. 1993; Brill 1992; Samuelsson 1994; Eineborg and Gamb~ick 1994, etc.).
---------------------------------------------------
E95-1022:17	15:171	The learning corpus can consist of plain text, but the best results seem achievable with annotated corpora (Merialdo 1994; Elworthy 1994).
---------------------------------------------------
P04-1062:18	112:264	This experiment is inspired by the experiments in Merialdo (1994).
---------------------------------------------------
P04-1062:19	13:264	Moreover, maximizing likelihood is not equivalent to maximizing task-defined accuracy (e.g. , Merialdo, 1994).
---------------------------------------------------
P09-2008:20	32:81	There is little discrepancy in accuracy when using ML-decoding, as compared to Viterbidecoding, as mentioned in (Merialdo, 1994).1 Let o1,n be a sequence of n-character user input without WBMs, xt be the best word spacing state for ot where 1  t  n. Assume that xt is either 1 (space after ot) or 0 (no space after ot).
---------------------------------------------------
D07-1070:21	263:458	Merialdo (1994) saw a similar degradation over small (and large) seed sets in HMM POS tagging.
---------------------------------------------------
C96-1011:22	139:151	, 1992) and Melialdo (Merialdo, 1994) used IIMM to learn English POS taggers while Chanod and 'I'apanainen (Chanod and Tapanainen, 1995), Feldweg (Feldweg, 1995), and Ledn and Serrano (l,e6n and Serrano, 1995) ported tile Xerox tagger (Cutting et aal.
---------------------------------------------------
W03-1702:23	15:147	As noted in Merialdo (1994), even minimal hand tagging improved on the results of unsupervised methods.
---------------------------------------------------
I05-2007:24	57:188	A training process with a tagged corpus gives much better performance than unsupervised training (Merialdo, 1994).
---------------------------------------------------
C96-2192:25	26:98	Of these two methods, R.F training seelns to give better estilnations while t)eing more labor intensive (Merialdo 1994).
---------------------------------------------------
C96-2192:26	16:98	(DeRose 1988; Cutting et al 1992; Merialdo 1994).
---------------------------------------------------
A00-2013:27	5:145	1 Full Morphological Tagging English Part of Speech (POS) tagging has been widely described in the recent past, starting with the (Church, 1988) paper, followed by numerous others using various methods: neural networks (Julian Benello and Anderson, 1989), HMM tagging (Merialdo, 1992), decision trees (Schmid, 1994), transformation-based error-driven learning (Brill, 1995), and maximum entropy (Ratnaparkhi, 1996), to select just a few.
---------------------------------------------------
D07-1031:28	24:275	Most previous work exploiting unsupervised training data for inferring POS tagging models has focused on semi-supervised methods in the in which the learner is provided with a lexicon specifying the possible tags for each word (Merialdo, 1994; Smith and Eisner, 2005; Goldwater and Griffiths, 2007) or a small number of prototypes for each POS (Haghighi and Klein, 2006).
---------------------------------------------------
D07-1031:29	10:275	1 Introduction It is well known that Expectation-Maximization (EM) performs poorly in unsupervised induction of linguistic structure (Carroll and Charniak, 1992; Merialdo, 1994; Klein, 2005; Smith, 2006).
---------------------------------------------------
I08-4033:30	82:113	Differing from the interpolation smoothing algorithm used in(Merialdo, 1994), both p(T) and p(W|T) were smoothed by back-off methods(Katz, 1987).
---------------------------------------------------
I08-1069:31	136:166	The first category (e.g., (Kupiec, 1992; Merialdo, 1994; Banko and Moore, 2004; Wang and Schuurmans, 2005)) assumes there is a lexicon that lists the allowable tags for each word in the text.
---------------------------------------------------
W96-0102:32	18:379	Most work on statistical methods has used n-gram models or Hidden Markov Model-based taggers (e.g. Church, 1988; DeRose, 1988; Cutting et al. 1992; Merialdo, 1994, etc.).
---------------------------------------------------
W96-0213:33	92:123	Comparison With Previous Work Most of the recent corpus-based POS taggers in the literature are either statistically based, and use Markov Model(Weischedel et al. , 1993, Merialdo, 1994) or Statistical Decision Tree(Jelinek et al. , 1994, Magerman, 1995)(SDT) techniques, or are primarily rule based, such as Drill's Transformation Based Learner(Drill, 1994)(TBL).
---------------------------------------------------
C96-1020:34	3:125	Treebanks have been used within the field of natural language processing as a source of training data for statistical part og speech taggers (Black et al. , 1992; Brill, 1994; Merialdo, 1994; Weischedel et al. , 1993) and for statistical parsers (Black et al. , 1993; Brill, 1993; aelinek et al. , 1994; Magerman, 1995; Magerman and Marcus, 1991).
---------------------------------------------------
W96-0101:35	11:213	1 Introduction In the part-of-speech hterature, whether taggers are based on a rule-based approach (Klein and Simmons, 1963), (Brill, 1992), (Voutilainen, 1993), or on a statistical one (Bahl and Mercer, 1976), (Leech et al. , 1983), (Merialdo, 1994), (DeRose, 1988), (Church, 1989), (Cutting et al. , 1992), there is a debate as to whether more attention should be paid to lexical probabilities rather than contextual ones.
---------------------------------------------------
C00-1081:36	12:207	, 1992; Merialdo, 1994; l)ennatas and Kokkinakis, 1.995).
---------------------------------------------------
C08-1042:37	19:202	In the first, tag induction systems are allowed the use of a tagging dictionary, which specifies for each word a set of possible parts-of-speech (Merialdo, 1994; Smith and Eisner, 2005; Goldwater and Griffiths, 2007).
---------------------------------------------------
C02-1132:38	118:204	A perspective on this work can be gained by comparison with attempts at unsupervised learning of other natural language phenomena including partof-speech tagging (Merialdo, 1994) and syntactic dependencies (Carroll and Charniak, 1992; Paskin, 2001).
---------------------------------------------------
P05-1044:39	158:262	5.1 Comparison with EM Our experiments are inspired by those in Merialdo (1994); we train a trigram tagger using only unlabeled data, assuming complete knowledge of the tagging dictionary.5 In our experiments, we varied the amount of data available (12K96K words of WSJ), the heaviness of smoothing, and the estimation criterion.
---------------------------------------------------
P05-1044:40	10:262	Even when they avoid local maxima (e.g. , through clever initialization) they typically deviate from human ideas of what the right structure is (Merialdo, 1994).
---------------------------------------------------
P09-1057:41	20:223	The classic approach (Merialdo, 1994) is expectation-maximization (EM), where we estimate grammar and dictionary probabilities in order to maximize the probability of the observed word sequence: P(w1wn) = summationdisplay t1tn P(t1tn)P(w1wn|t1tn)  summationdisplay t1tn nproductdisplay i=1 P(ti|ti2 ti1)P(wi|ti) Goldwater and Griffiths (2007) report 74.5% accuracy for EM with a 3-gram tag model, which we confirm by replication.
---------------------------------------------------
P09-1057:42	7:223	We adopt the problem formulation of Merialdo (1994), in which we are given a raw word sequence and a dictionary of legal tags for each word type.
---------------------------------------------------
P09-1057:43	32:223	EM-HMM tagger provided with good initial conditions (Goldberg et al., 2008) 91.4* (*uses linguistic constraints and manual adjustments to the dictionary) Figure 1: Previous results on unsupervised POS tagging using a dictionary (Merialdo, 1994) on the full 45-tag set.
---------------------------------------------------
W06-2005:44	179:217	Some have assumed only partially tagged training corpora (Merialdo, 1994); some have begun with small tagged seed wordlists (Cucerzan and Yarowsky, 1999) for named-entity tagging, while others have exploited the automatic transfer of an already existing annotated resource in a min e-even e-cognates Tag: 56.9 77.2 82.1 POS: 65.3 84.2 87.6 SubPOS: 61.7 83.3 86.9 gender: 70.4 87.3 90.2 number: 78.3 95.3 96.0 case: 93.8 96.8 97.2 possessors num: 85.4 96.7 97.0 form: 92.9 99.2 99.2 person: 74.5 91.2 92.7 tense: 90.7 95.1 96.1 mood: 91.5 95.0 96.0 participle: 99.9 100.0 100.0 Table 4: Tagging Brazilian Portuguese different genres or a different language (e.g. crosslanguage projection of morphological and syntactic information in (Yarowsky et al. , 2001; Yarowsky and Ngai, 2001), requiring no direct supervision in the target language).
---------------------------------------------------
J02-1004:45	161:289	(1)) Eojeol 86.80 90.48 89.40 89.62 91.73 92.48 Morpheme 91.32 94.93 94.40 94.48 95.77 96.12 possible for training gives much better performance than unsupervised training using the Baum-Welch reestimation algorithm (Merialdo 1994).
---------------------------------------------------
N01-1023:46	28:209	The experiments in (Merialdo, 1994; Elworthy, 1994) showed that only in very specific cases HMMs were effective in combining labeled and unlabeled data.
---------------------------------------------------
P08-1085:47	43:220	Merialdo (1994) reports an accuracy of 86.6% for an unsupervised token-based EMestimated HMM, trained on a corpus of about 1M words, over a tagset of 159 tags.
---------------------------------------------------
P08-1085:48	9:220	Unsupervised POS tagging has been traditionally approached with relative success (Merialdo, 1994; Kupiec, 1992) by HMM-based generative models, employing EM parameters estimation using the Baum-Welch algorithm.
---------------------------------------------------
W07-2203:49	28:177	Elworthy (1994) and Merialdo (1994) demonstrated that Baum-Welch does not necessarily improve the performance of an HMM part-ofspeech tagger when deployed in an unsupervised or semi-supervised setting.
---------------------------------------------------
W07-2203:50	168:177	Our findings support those of Elworthy (1994) and Merialdo (1994) for POS tagging and suggest that EM is not always the most suitable semi-supervised training method (especially when some in-domain training data is available).
---------------------------------------------------
W95-0101:51	11:188	It is possible to use unsupervised learning to train stochastic taggers without the need for a manually annotated corpus by using the Baum-Welch algorithm \[Baum, 1972; Jelinek, 1985; Cutting et al. , 1992; Kupiec, 1992; Elworthy, 1994; Merialdo, 1995\].
---------------------------------------------------
W95-0101:52	6:188	Almost all of the work in the area of automatically trained taggers has explored Markov-model based part of speech tagging \[Jelinek, 1985; Church, 1988; Derose, 1988; DeMarcken, 1990; Cutting et al. , 1992; Kupiec, 1992; Charniak et al. , 1993; Weischedel et al. , 1993; Schutze and Singer, 1994; Lin et al. , 1994; Elworthy, 1994; Merialdo, 1995\].
---------------------------------------------------
P06-1084:53	19:201	Merialdo (1994) reports an accuracy of 86.6% for an unsupervised word-based HMM, trained on a corpus of 42,186 sentences (about 1M words), over a tag set of 159 different tags.
---------------------------------------------------
P07-1094:54	23:195	Perhaps the most well-known is that of Merialdo (1994), who used MLE to train a trigram hidden Markov model (HMM).
---------------------------------------------------
P07-1094:55	104:195	3 Fixed Hyperparameter Experiments 3.1 Method Our initial experiments follow in the tradition begun by Merialdo (1994), using a tag dictionary to constrain the possible parts of speech allowed for each word.
---------------------------------------------------
C00-2089:56	25:178	In the second one, the model is learned using the Baunl-\elch algorithm from an initial model which is estimated using labelled corpora (Merialdo, 1994).
---------------------------------------------------
P96-1042:57	48:240	The methods we investi1This gives the Viterbi model (Merialdo, 1994), which we use here.
---------------------------------------------------
P96-1042:58	195:240	Parame6As noted above, we smooth the MLE estimates by interpolation with a uniform probability distribution (Merialdo, 1994).
---------------------------------------------------
P96-1042:59	15:240	The ultimate reduction in annotation cost is achieved by unsupervised training methods, which do not require an annotated corpus at all (Kupiec, 1992; Merialdo, 1994; Elworthy, 1994).
---------------------------------------------------
P96-1042:60	83:240	For each such binomial, we approximate P(ai = ai\[S) as a trun3In the implementation we smooth the MLE by interpolation with a uniform probability distribution, following Merialdo (1994).
---------------------------------------------------
P96-1004:61	60:173	Although these tags were corrected by hand, part-ofspeech tagging can be automatically performed with an error rate of 3 to 4 percent (Merialdo, 1994; Brill, 1994).
---------------------------------------------------
J95-4004:62	144:404	Part-of-speech tagging is an active area of research; a great deal of work has been done in this area over the past few years (e.g. , Jelinek 1985; Church 1988; Derose 1988; Hindle 1989; DeMarcken 1990; Merialdo 1994; Brill 1992; Black et al. 1992; Cutting et al. 1992; Kupiec 1992; Charniak et al. 1993; Weischedel et al. 1993; Schutze and Singer 1994).
---------------------------------------------------
J95-4004:63	154:404	Almost all recent work in developing automatically trained part-of-speech taggers has been on further exploring Markovmodel based tagging (Jelinek 1985; Church 1988; Derose 1988; DeMarcken 1990; Merialdo 1994; Cutting et al. 1992; Kupiec 1992; Charniak et al. 1993; Weischedel et al. 1993; Schutze and Singer 1994).
---------------------------------------------------
J95-4004:64	162:404	However, it appears to be the case that directly estimating probabilities from even a very small manually tagged corpus gives better results than training a hidden Markov model on a large untagged corpus (see Merialdo (1994)).
---------------------------------------------------
W03-0408:65	31:194	The adaption idea in (Gales and Woodland, 1996) is also closely related to the idea of combining supervised and unsupervised learning in the same domain (Merialdo, 1994).
---------------------------------------------------
E09-1042:66	32:182	For instance, Merialdo (1994) uses maximum likelihood estimation to train a trigram HMM.
---------------------------------------------------
W99-0607:67	35:130	Our model exploits the same kind of tag-n-gram information that forms the core of many successful tagging models, for example, (Kupiec, 1992), (Merialdo, 1994), (Ratnaparkhi, 1996).
---------------------------------------------------
W02-2006:68	9:120	Some have assumed only partially tagged training corpora (Merialdo, 1994), while others have begin with small tagged seed wordlists (such as Collins and Singer (1999) and Cucerzan and Yarowsky (1999) for named-entity tagging).
---------------------------------------------------
J95-2001:69	18:410	In the case where additionally raw untagged text is available, the Maximum Likelihood training can be used to reestimate the parameters of HMM taggers (Merialdo 1994).
---------------------------------------------------
J95-2001:70	38:410	When the training text is adequate to estimate the tagger parameters, more efficient stochastic taggers (Dermatas and Kokkinakis 1994; Maltese and Mancini 1991; Weischedel et al. 1993) and training methods can be implemented (Merialdo 1994).
---------------------------------------------------
C04-1004:71	10:125	In recent years, HMMs have enjoyed great success in many tagging applications, most notably part-of-speech (POS) tagging (Church 1988; Weischedel et al 1993; Merialdo 1994) and named entity recognition (Bikel et al 1999; Zhou et al 2002).
---------------------------------------------------
W96-0113:72	173:265	6 Discussion and Future Work Merialdo (1994) and Elworthy (1994) have insisted, based on their experimental results, that the maximum likelihood training using an untagged corpus does not necessarily improve tagging accuracy.
---------------------------------------------------
W96-0113:73	15:265	However, Merialdo (1994) and Elworthy (1994) have criticized methods of estimation from an untagged corpus based on the maximum likelihood principle.
---------------------------------------------------
W96-0113:74	196:265	On this point, I agree with Merialdo (1994) and Elworthy (1994).
---------------------------------------------------
W03-0407:75	164:172	This finding is in accord with earlier work on bootstrapping taggers using EM (Elworthy, 1994; Merialdo, 1994).
---------------------------------------------------
A94-1009:76	53:191	Work similar to that described here has been carried out by Merialdo (1994), with broadly similar conclusions.
---------------------------------------------------
A94-1009:77	186:191	Bernard Merialdo (1994).
---------------------------------------------------
A94-1009:78	137:191	Similar results are presented by Merialdo (1994), who describes experiments to compare the effect of training from a hand-tagged corpora and using the Baum-Welch algorithm with various initial conditions.
---------------------------------------------------
A94-1009:79	12:191	The conclusions are broadly in agreement with those of Merialdo (1994), but give greater detail about the contributions of different parts of the model.
---------------------------------------------------
