3.2 Replace Rules On the other hand the replace rules were introduced by Karttunen in 1995 motivated by the rewrite rules model developed by Kay and Kaplan (1994). 
For example, the sequence \[i,0\] represents a non-marker use of the symbol I. 2.1.3 Utilities Before describing the algorithm, it will be helpful to have at our disposal a few general tools, most of which were described already in Kaplan and Kay (1994). 
1This is similar to the operator Intro in (Kaplan and Kay, 1994). 
These rules are then composed into one finite-state transducer (Kaplan and Kay 1994). 
The result of the computation described by Kaplan and Kay (1994) is not necessarily a p-subsequential transducer. 
