Despite the fact that the sophisticated models of suprasegmental phonology developed more than a quarter of a century ago within Autosegmental 28 Theory (Goldsmith, 1976; Leben, 1973) have already been rigorously formalised in the nineties in the context of feature-structure-based computational phonology (Bird, 1995; Scobbie, 1991; Bird and Klein, 1994; Walther, 1999), the representation of tone and length has received little or no attention in the area of grammar engineering.


Previous proposals to cast phonological structure in a typed feature system can be found in Bird and Klein (1994) and Walther (1999).


Since here the crucial inheritance relationships are induced automatically, we elaborate on work by Walther (1999) where a complex hand-crafted type hierarchy for internal segmental structure is mentioned instead of simple appropriateness declarations (Bird and Klein, 1994).


In agreement with (Bird and Klein, 1994) and (Er\]avec, 1996), we capture such alternations declaratively in a one-level model without recourse to transducers.


