Semantic triples: relations between word senses mediated usually by an argument position, preposition or conjunction (Alshawi and Carter, 1994). 
(1993), Nagao (1994), Alshawi and Carter (1994), and Srinivas, Doran, and Kulick (1995). 
In (Alshawi and Carter, 1994), the collocations and their associated scores were evaluated indirectly by their use in parse tree selection. 
453 2.4 Word Similarity Another important group of related work is on using syntactic dependency features in a vector-space model for measuring word similarity, e.g., (Alshawi and Carter, 1994), (Grishman and Sterling, 1994), (Ruge, 1992), and (Lin, 1998). 
Many statistical taggers and parsers have been trained on it, e.g. Ramshaw and Marcus (1995), Srinivas (1997) and Alshawi and Carter (1994). 
