The Reconstruction Engine of Lowe and Mazaudon (1994) requires the linguist to specify hypothetical sound changes and canonical syllable structure. 
Parts of the Comparative Method have been computerized by Frantz (1970), Hewson (1974), Wimbish (1989), and Lowe and Mazaudon (1994), but none of them have tackled the alignment step. 
The Reconstruction Engine of Lowe and Mazaudon (1994) uses a similar strategy of generating proto-projections to establish cognate sets. 
Several methods for constructing comparative dictionaries have been proposed and applied to specific languagefamilies: Algonquian(Hewson, 1974), Yuman (Johnson, 1985), Tamang (Lowe and Mazaudon, 1994), and Malayo-Javanic (Oakes, 2000). 
The Reconstruction Engine (Lowe and Mazaudon, 1994), a set of programs designed to be an aid in language reconstruction, requires a set of correspondences to be provided beforehand. 
