W00-1016:1	76:215	Input Analyzer: The user utterance is transformed into a dependency structure by a robust parser, KNP (Kurohashi and Nagao, 1994; Kurohashi and Nagao, 1998), and utterance-pattern rules are applied to extract the utterance type and the utterance content.
---------------------------------------------------
P03-2027:2	35:126	In this section, we describe the score calculation method, giving large points to modifier-head relations between bunsetsu 1 based on the parse results of KNP (Kurohashi and Nagao, 1994), to improve precision of text retrieval.
---------------------------------------------------
N06-1023:3	30:177	On the other hand, unlexicalizedparsersachievedanalmostequivalentaccuracy to such lexicalized parsers (Klein and Manning, 2003; Kurohashi and Nagao, 1994).
---------------------------------------------------
N06-1023:4	130:177	In the table, baseline means the rule-based syntactic parser, KNP (Kurohashi and Nagao, 1994), and proposed represents the proposed method.
---------------------------------------------------
W03-0312:5	58:158	The Japanese parser outputs the phrasal dependency structure of an input, and that is used as is. We used The Japanese parser KNP (Kurohashi and Nagao, 1994) and The English nl-parser (Charniak, 2000).
---------------------------------------------------
I08-1025:6	62:200	2.2 Construction of Web Standard Format Data Collection We have crawled 218 million web pages over three months, May July in 2007, by using the ShimCrawler,2 and then converted these pages into web standard format data with results of a Japanese parser, KNP (Kurohashi and Nagao, 1994), through ourconversiontools.
---------------------------------------------------
I08-2080:7	67:170	4.3 Syntactic, Case and Coreference Analyses syntacticanalysis Syntactic analysis is performed by using the Japanese parser KNP (Kurohashi and Nagao, 1994).
---------------------------------------------------
P06-1022:8	169:186	To resolve the syntactic ambiguity of a long sentence, some of them have focused attention on the clause. First, there are the studies that focused attention on compound clauses (Agarwal and Boggess, 1992; Kurohashi and Nagao, 1994).
---------------------------------------------------
E09-1047:9	201:241	Our experiments using scope information are similar to the approaches of Kurohashi and Nagao (1994) and Agarwal and Bogges (1992) in that they try to identify coordinate structure bracketings.
---------------------------------------------------
D07-1032:10	46:195	Kurohashi and Nagao proposed a Japanese parsing method that included coordinate structure detection (Kurohashi and Nagao, 1994).
---------------------------------------------------
D07-1032:11	149:195	We used two baseline systems for comparative purposes: the rule-based dependency parser, KNP (Kurohashi and Nagao, 1994), and the probabilistic model of syntactic and case structure analysis (Kawahara and Kurohashi, 2006b), in which coordination disambiguation is the same as that of KNP.
---------------------------------------------------
D07-1032:12	85:195	A similarity value between two bunsetsus is calculated on the basis of POS matching, exact word matching, and their semantic closeness in a thesaurus tree (Kurohashi and Nagao, 1994).
---------------------------------------------------
D07-1032:13	81:195	Therefore, we use a method to calculate the similarity between two whole coordinate conjuncts (KurohashiandNagao, 1994).
---------------------------------------------------
D07-1032:14	119:195	The generative probability of a coordinate structure, P(relihi|fi), is dened as follows: P(relihi|fi) = P(relihi|ki) (9) We classied coordination keys into 52 classes according to the classication proposed by (Kurohashi and Nagao, 1994).
---------------------------------------------------
D07-1032:15	16:195	Kurohashi and Nagao proposed a similarity-based method to resolve both of the two tasks for Japanese (Kurohashi and Nagao, 1994).
---------------------------------------------------
D07-1032:16	134:195	We used KNP2 (Kurohashi and Nagao, 1994) as the parser and a web corpus consisting of 470M Japanese sentences (Kawahara and Kurohashi, 2006a).
---------------------------------------------------
C00-2086:17	7:164	Previous work elnployed a 1)reproccssing module for parsing to work on a constrained range of the candidate conjmwts/disjuncts (Kurohashi & Nagao, 1994; Yang, 1995; Okmnura & Muraki, 1994).
---------------------------------------------------
C00-1063:18	65:156	3.1 Good parser NLP research group at Kyoto University has been developing a robust and accurate parsing system, KNP, over the last ten yem's (Kurohashi and Nagao, 1994; Kurohashi and Nagao, 1998).
---------------------------------------------------
C04-1002:19	206:263	If the current modifier bunsetsu is a distinctive key bunsetsu (Kurohashi and Nagao, 1994, page 510), these features are triggered.
---------------------------------------------------
C04-1002:20	203:263	Kurohashi and Nagao (1994) proposed a method to detect conjunctive structures by calculating similarity scores between two sequences of bunsetsus.
---------------------------------------------------
I05-4002:21	43:131	Conjunctive Structure: Conjunctive structure is not specified during syntactic parsing, instead their analysis is left for the subsequent processing (contrary to (Kurohashi and Nagao, 1994)).
---------------------------------------------------
P09-2002:22	27:88	Kurohashi and Nagao (1994) used a similar data structure in their rule-based method.
---------------------------------------------------
P09-2002:23	61:88	We also ran the Kurohashi-Nagao parser (KNP) 2.0 2 , a widely-used Japanese dependency parser to which Kurohashi and Nagaos (1994) rule-based coordination analysis method is built in.
---------------------------------------------------
P03-2037:24	78:94	The detector uses a morphological analyzer, Juman, and a syntactic analyzer, KNP (Kurohashi and Nagao, 1994).
---------------------------------------------------
I08-2110:25	70:139	In this paper, SYNID is denoted by using English gloss word, surrounded by  h i  . 3 SYNGRAPH 3.1 SYNGRAPH Data Structure SYNGRAPH data structure is an acyclic directed graph, and the basis of SYNGRAPH is the dependencystructureofanoriginalsentence(inthispaper, a robust parser (Kurohashi and Nagao, 1994) is always employed).
---------------------------------------------------
C04-1158:26	85:200	We use a syntactic parser KNP (Kurohashi and Nagao, 1994) to divide the ASR results into the phrases 2 . 1 Bunsetsu is a commonly used linguistic unit in Japanese, which consists of one or more content words and zero or more functional words that follow.
---------------------------------------------------
P98-2144:27	77:176	3.1 Postposition 'Wa' The main usage of the postposition 'wa' is divided into the following two patternsS:  If two PPs with the postposition 'wa' appear consecutively, we treat the first PP as 5These patterns are almost similar to the ones in (Kurohashi and Nagao, 1994).
---------------------------------------------------
P98-2144:28	168:176	In (Kurohashi and Nagao, 1994), the parser always attaches a phrase with a comma to the second nearest possible phrase.
---------------------------------------------------
E09-1020:29	205:226	For French, the SYGMART parser (Chauche, 1984) and for Japanese, the KNP parser (Kurohashi and Nagao, 1994).
---------------------------------------------------
E09-1020:30	105:226	We segmented all the Japanese data with the automatic segmenter Juman (Kurohashi and Nagao, 1994).
---------------------------------------------------
I08-2097:31	89:160	number of conjunctions (and/or): Sentences with coordinate structures are also difcult to parse (Kurohashi and Nagao, 1994).
---------------------------------------------------
P06-2097:32	90:192	We first process them with the Japanese morphological analyzer, JUMAN (Kurohashi et al. , 1994), and make syntactic/case analysis and anaphora resolution with the Japanese analyzer, KNP (Kurohashi and Nagao, 1994).
---------------------------------------------------
P07-2057:33	9:124	Popular parsers are CaboCha (Kudo and Matsumoto, 2002) and KNP (Kurohashi and Nagao, 1994), which were developed to analyze formal written language expressions such as that in newspaper articles.
---------------------------------------------------
D07-1063:34	154:243	Table 3 shows that the proposed method outperforms conventional methods except Sassano (2004)2, while Sassano (2004) used richer features which are not used in the proposed method, such as features for conjunctive structures based on Kurohashi and Nagao (1994), features concerning the leftmost content word in the candidate modifiee.
---------------------------------------------------
C08-1054:35	55:221	Shimbo and Hara (2007) considered many features for coordination disambiguation and automatically optimized their weights, which were heuristically determined in Kurohashi and Nagao (1994), using a discriminative learning model.
---------------------------------------------------
C08-1054:36	179:221	We used two baseline systems for comparative purposes: a rule-based dependency parser (Kurohashi and Nagao, 1994) and the probabilistic generative model of dependency, coordinate and case structure analysis (Kawahara and Kurohashi, 2007)5.
---------------------------------------------------
C08-1054:37	9:221	Semanticsimilarities are acquired from thesauri (Kurohashi and Nagao, 1994; Resnik, 1999) or distributional similarity (Chantree et al., 2005).
---------------------------------------------------
C08-1054:38	159:221	The generative probability of a dependency relation, P(relihi|fi), is dened as follows: P(relihi|fi) = P(relihi|ki) (4) We classied coordination keys into 52 classes according to the classication described in (Kurohashi and Nagao, 1994).
---------------------------------------------------
C08-1054:39	51:221	Kurohashi and Nagao proposed a Japanese parsing method that included coordinate structure detection (Kurohashi and Nagao, 1994).
---------------------------------------------------
C08-1054:40	133:221	This base model measures similarities between conjuncts in the same way as (Kurohashi and Nagao, 1994), and calculates probabilities of generating these similarities.
---------------------------------------------------
N04-4039:41	57:123	Linguistic Analysis: Each bunsetsu unit was automatically annotated with linguistic information using a Japanese syntactic analyzer (Kurohashi & Nagao, 1994) 2.
---------------------------------------------------
P09-1109:42	44:210	Shimbo and Haras approach has its root in Kurohashi and Nagaos (1994) rule-based method for Japanese coordinations.
---------------------------------------------------
D07-1064:43	28:279	The state space of our model resembles that of Kurohashi and Nagaos Japanese coordination detection method (Kurohashi and Nagao, 1994).
---------------------------------------------------
P06-2082:44	51:197	Conventional methods of dependency analysis have assumed the following three syntactic constraints (Kurohashi and Nagao, 1994a): 1.
---------------------------------------------------
P06-2082:45	160:197	These verbs tend to form conjunctive structures and it is known that analyzing conjunctive structure is difficult (Kurohashi and Nagao, 1994b).
---------------------------------------------------
C04-1050:46	109:249	3.2 Matching input case components with case slots in the case frame We match case components of the target verb with case slots in the case frame (Kurohashi and Nagao, 1994a).
---------------------------------------------------
C04-1050:47	59:249	A large raw corpus is parsed by the Japanese parser, KNP (Kurohashi and Nagao, 1994b), and reliable predicateargument examples are extracted from the parse results.
---------------------------------------------------
P99-1062:48	55:160	All definition sentences in RSK were analyzed by JUMAN, a Japanese morphological analyzer, and KNP, a Japanese syntactic and case analyzer (Kurohashi and Nagao, 1994; Kurohashi and Nagao, 1998).
---------------------------------------------------
C04-1174:49	128:198	An input sentence is parsed using the Japanese parser, KNP (Kurohashi and Nagao, 1994).
---------------------------------------------------
