In Hebrew, our model includes an improved version of the similar words algorithm of (Levinger et al., 1995), a model of lexical context, and a small set of tag ngrams. 
Furthermore, as mentioned above, even the use of a sophisticated context-free tagger, based on (Levinger et al. , 1995), gives low accuracy of 78.2%. 
Levinger et al. , 1995 demonstrate methods of eliminating syntactically incorrect morphological readings. 
They estimate an initial language model (using (Levinger et al., 1995)) and improve this model with EM. 
(Levinger et al., 1995; Goldberg et al., ; Adler et al., 2008)) will make the parser more robust and suitable for use in more realistic scenarios. 
