Peter Heeman and Graeme Hirst (1995) Collaborating on referring expressions. 
For that purpose, most past work (Appelt, 1985; Dale and Haddock, 1991; Dale, 1992; Dale and Reiter, 1995; Heeman and Hirst, 1995; Horacek, 1997; Krahmer and Theune, 2002; van Deemter, 2002; Krahmer et al. , 2003) makes use of attributes of an intended object (the target) and binary relations between the target and others (distractors) to distinguish the target from distractors. 
Heeman and Hirst (1995) model cooperation by the cycle Present-Judge-Refashion. 
Information-sharing subdialogues differ from information-seeking or clarification subdialogues (van Beek, Cohen, and Schmidt 1993; Raskutti and Zukerman 1993; Logan et al. 1994; Heeman and Hirst 1995). 
Heeman and Hirst (1995) investigated collaboration on referring expressions of objects copresent with the dialogue participants. 
