2.2 Transformation-Based Learning Transformation Based error-driven Learning (TBL) is a successful machine learning algorithm introduced by Eric Brill (Brill, 1995). 
We obtained the POS tags using Brills tagger (Brill, 1995). 
Meanwhile, we use Brill's tagger (Brill, 1995) to determine parts of speech (POS) of words in DQ/SQ. 
4.2 Transformation-based Learning Transformation-based learning (Brill, 1995), or TBL, is one of the most successful rule-based machine learning algorithms. 
The POS tags are determined automatically, using the Brill tagger (1995). 
