The first task, which is commonly achieved by giving simple imperative commands and statements of purpose, has received considerable attention in both the interpretation (e.g. , (Di Eugenio, 1993)) and the generation communities (e.g. , (Vander Linden and Martin, 1995)). 
et al (1992) Hirschberg and Litman (1993), Vander Linden and Martin (1995), Knott (1996) and Litman (1996)). 
This makes the network compatible with the DRAFTER micro-planner, a descendent of IMAGENE (Vander Linden and Martin, 1995). 
22 2 Related work Work on discourse marker generation in general has focussed on marker selection, mainly for causal relations (Elhadad and McKeown 1990; Vander Linden and Martin 1995), and on the realization of RST's subject-matter relations (Rhsner and Stede 1992; Delin et al. 1996). 
See, for example, \[Scott and de Souza, 1990\] for treatment of ELABORATION, \[Vander Linden and Martin, 1995\] of PURPOSE, and \[Grote et al. , 1995\] of CONCESSION. 
