The ability to determine lexical aspect, on a large scale and in the sentential context, therefore yields an important source of constraints for corpus analysis and psycholinguistic experimentation, as well as for NLP applications such as machine translation (Dorr et al. , 1995b) and foreign language tutoring (Dorr et al. , 1995a; Sams.


LCS composition is a fundamental operation in two applications for which the LCS serves as an interlingua: machine translation (Dorr et al 1993) and foreign language tutoring (Dorr et al. , 1995b: Sams.


Such cases arise, e.g., in the context of foreign language tutoring (Dorr et al. , 1995b; Sams, 1995; Weinberg et al. , 1995), where a a 'bounded' interpretation for an atelic verb, e.g., march, may be introduced by a path PP to the bridge or across the field or by a NP the length of the field: (1) The soldier marched to the bridge.


