The orthographic check is done in the spirit of Oflazer (1996). 
The candidate generation routine uses a modification of the standard edit distance and employs tile error-tolerant finite-state recognition algorithm (Oflazer, 1996) to generate candidate words. 
There have been some previous studies for spelling checking (Solak and Oflazer, 1993) and spelling correction (Oflazer, 1996). 
Our approach is as follows: we use the resulting morphological analyzer with an error-tolerant finite-state recognizer engine (Oflazer 1996). 
Some of the kinds of word level post-processing include the use of dictionary lookup, probabilistic relaxation, character and word n-gram frequency analysis (Hong, 1995), and morphological analysis (Oflazer, 1996). 
