For concreteness, we are assuming here that QLFs are built using a simple unification grammar formalism of the type described in Pulman (1996), and that a chart parser and semantic head-driven generator are 498 Pulman Bidirectional Contextual Resolution . . used for the analysis of sentences to QLFs and vice versa.


It uses a simple unification grammar (based on the formalism described in 516 Pulman Bidirectional Contextual Resolution (Pulman, 1996)) to produce QLFs.


Positional encoding of such information as in Pulman (1996) allows efficient term unification for the propagation of these features.


