McMahon and Smith (McMahon and Smith, 1996) also use the mutual information of a corpus to find the hierarchical clusters. 
A solution along this line was chosen for co-occurrence based clustering in (McMahon and Smith, 1996), where a first algorithm handles more frequent words, and a second algorithm adds the low-frequency words afterwards. 
McMahon and Smith also use the bigram statistics of a corpus to find the hierarchical clusters (McMahon, 1996). 
(McMahon and Smith, 1996) employ a similar algorithm to that of Brown et al., but use a top-down search in determining word clusters, rather than a bottom-up one. 
We performed an experiment analyzing a specific verb group produced by one semantic clustering program (McMahon and Smith, 1996). 
