(Rentzepopoulos and Kokkinakis, 1996) describes a hidden Markov model approach for phoneme-tographeme conversion, in seven European languages evaluated on a number of corpora.


For example, Rentzepopoulos and Kokkinakis (1996) use HMMs to convert phoneme sequences to their most likely orthographic forms in the absence of a lexicon.


Rentzepopoulos (Rentzepopoulos and Kokkinakis, 1996) describes a hidden Markov model approach for phoneme-to-grapheme conversion, in seven European languages on a number of corpora.


