Acknowledgments Ron Kaplan had the idea that the proof construction which we used in Wedekind and Kaplan (1996) might be useful for other purposes.


We give a much simpler undecidability proof of the emptiness problem using a reduction to the emptiness problem of the intersection of arbitrary context-free languages, a reduction that Wedekind and Kaplan (1996) used to show the undecidability of ambiguity-preserving generation.


