1 Both Gildea and Jurafsky (1996) and Nerbonne and Heeringa (1997) use distance functions based on binary features. 
Gildea and Jurafsky (1996) set it at one fourth of the maximum substitution cost. 
Since neither Gildea and Jurafsky (1996) nor Nerbonne and Heeringa (1997) present their feature vectors in sufficient detail to perform the calculations, I adopted a fairly standard set of 17 binary features from Hartman (1981). 
Gildea and Jurafsky (1996) counted the number of features whose values are different, and used them as a substitution cost. 
The function is often extended to cover pairs consisting of a segment and the null character, which correspond to the opera288 Algorithm Calculation Calculation Dynamic Phonological of alignment of distance programming features Covington (1996) Somers (1998) Nerbonne and Heeringa (1997) Gildea and Jurafsky (1996) explicit explicit implicit explicit Table 1: Comparison of lions of insertion and deletion (also called indels). 
