6.3 Text Segmentation A number of researchers, (e.g. , Li and Yamanishi (2000); Hearst (1997)), have developed text segmentation systems. 
DuetosomesimilaritieswithTextTiling algorithm for topic shifts detection of Hearst (1997), the method is called Cohesion TextTiling (CTT). 
For this purpose we refer to the concept of lexical cohesion introduced by (Halliday and Hasan, 1976); see (Morris and Hirst, 1991; Hearst, 1997; Marcu, 2000) who already use this concept for text segmentation. 
A more sophisticated approach to text segmentation is described in (Hearst, 1997). 
Thus previous work suggests that the Hearst (1997) method is superior to that of Foltz et al. 
