The first is BFP's limitation as a cognitive model since it makes no provision for incremental resolution of pronouns (Kehler 1997). 
Its incremental character seems to be an answer to the question Kehler (1997) recently raised. 
The creation of the LRC algorithm is motivated by BFP's limitation as a cognitive model in that it makes no provision for incremental resolution of pronouns (Kehler 1997). 
Kehler (1997)). 
It should be noted that BFP makes use of Centering Rule 2 (Grosz et al. , 1995), LRC does not use the transition generated or Rule 2 in steps 4 and 5 since Rule 2's role in pronoun resolution is not yet known (see Kehler 1997 for a critique of its use by BFP). 
