We originally thought to build a general letter-to-sound WFST (Divay and Vitale 1997), on the theory that while wrong (overgeneralized) pronunciations might occasionally be generated, Japanese transliterators also mispronounce words.


We further suggest that a large-scale database of maximally aligned G-P tuples has applications within the more conventional task of G-P translation (Klatt, 1987; Huang et al. , 1994; Divay and Vitale, 1997).


(1976), Hunnicutt (1976), and Divay and Vitale (1997).


For instance, Divay and Vitale (1997) recently wrote: "To our knowledge, learning algorithms, although promising, have not (yet) reached the level of rule sets developed by humans" (p. 520).


