When the large-scale bilingual corpus is unavailable, some researchers acquired class-based alignment rules with existing dictionaries to improve word alignment (Ker and Chang, 1997). 
Ker & Chang (1997) propose an approach to align Chinese English corpus based on semantic class. 
When the large-scale bilingual corpus is not available, some researchers use existing dictionaries to improve word alignment (Ker and Chang, 1997). 
This approach was firstly suggested by Sue J.Ker and Jason S. Chang (1997) in word alignment of English-Chinese bilingual corpus. 
When the large-scale bilingual corpus is not available, some researchers use existing dictionaries to improve word alignment (Ker and Chang, 1997). 
