Our method uses a modification of a tree generalization technique used in (Li and Abe, 1998), and generates a tree-cut, which is a list of clusters that partition a tree. 
Clark and Weir (2002) further compared their approach with Resniks (1993) selectional association model and Li and Abes (1998) tree cut model on the same data sets. 
3.1 TCMs This approach is a reimplementation of Li and Abe (1998). 
Our method uses a modification of a tree generalization technique used in (Li and Abe, 1998), and generates a tree-cut, which is a list of clusters that partition a tree. 
Li and Abe (1998) used a tree cut model over WordNet, based on the principle of Minimum Description Length (MDL). 
