3 OT-LFG Following (Bresnan, 2000; Kuhn, 2000; Kuhn, 2001), we define a restricted OT system based on Lexical-Functional Grammar (LFG) representations: c(ategory) structure/f(unctional) structure 2Most computational OT work so far focuses on candidates and constraints expressible as regular languages/rational relations, based on (Frank and Satta, 1998) (e.g. , (Eisner, 1997; Karttunen, 1998; Gerdemann and van Noord, 2000)). 
Y oo3 C: 3-bounded approximation (Karttunen, 1998; Frank and Satta, 1998). 
If C i is L;-txmnded, we use the construction of (Frank and Satta, 1998; Karttulmn, 1998). 
/ jason@cs.rochester.edu Weighted finite-state constraints that can count 1111boundedly many violations make Optimality Theory more powerful than tinite-state transduction (Frank and Satta, 1998). 
Y oo C: Binary approximation (Karttunen, 1998; Frank and Satta, 1998). 
