Figure 3: Induced sense hierarchy for the word vital 6 Related Work There is a distinguished history of research extracting lexical semantic relationships from bilingual dictionaries (Copestake et al. , 1995; Chen and Chang, 1998).


A number of simple linguistic techniques has been developed to alleviate such problems, ranging from the use of stemming, lexical chain and thesaurus (Jing & Tzoukermann, 1999; Green, 1999), to word-sense disambiguation (Chen & Chang, 1998; Leacock et al, 1998; Ide & Veronis, 1998) and context (Cohen & Singer, 1999; Jing & Tzoukermann, 1999).


2 Acquiring Conceptual Knowledge from MRD In this section we apply a so-called ?bpSense algorithm (Chen and Chang 1998) to acquire CR for MRD senses.


There is also work on grouping senses of other inventories using information in the inventory (Dolan, 1994) along with information retrieval techniques (Chen and Chang, 1998).


