Since data producing these summaries can be sourced in different documents, summary fusion techniques as proposed in (Radev and McKeown, 1998) can be employed. 
Later work merged information extraction approaches with regeneration of extracted text to improve summary generation (Radev and McKeown 1998). 
The summarization method proposed in this paper is related to multi-document summarization (MDS) (Mani, 2001; Radev and McKeown, 1998; Schiman et al. , 2001). 
Radev and McKeown (1998) have already addressed the issue of information fusion in the context of multidocument summarization in one specific domain (i.e. , terrorism): The fusion of information is achieved through the implementation of summary operators that integrate the information of different templates from different documents referring to the same event. 
The former, such as (Radev and McKeown, 1998), rely on an information extraction system to extract very specific aspects of some events and generate abstracts thereof. 
