These subtle changes of meaning are important in natural language generation (Stede, 1998).


Levins inventory of verbs and classes has been also useful for applications such as machine translation (Dorr 1997; Palmer and Wu 1995), generation (Stede 1998), information retrieval (Levow, Dorr, and Lin 2000), and document classification (Klavans and Kan 1998).


Verb classes have proved useful in various (multilingual) natural language processing (NLP) tasks and applications, such as computational lexicography (Kipper et al. , 2000), language generation (Stede, 1998), machine translation (Dorr, 1997), word sense disambiguation (Prescher et al. , 2000), document classi cation (Klavans and Kan, 1998), and subcategorization acquisition (Korhonen, 2002).


Other related work includes (Stede, 1998), which suggests a lexicon structure for multilingual generation in a knowledge-based generation system.


Because knowledge of argument structure captures fundamental participant/event relations, it is crucial in parsing and generation (e.g. , Srinivas and Joshi \[1999\]; Stede \[1998\]), in machine translation (Dorr 1997), and in information retrieval (Klavans and Kan 1998) and extraction (Riloff and Schmelzenbach 1998).


