The phonetic translation practice is referred to as transliteration; conversely, the process of recovering a word in its native language from a transliteration is called as back-transliteration (Zhang et al, 2004; Knight and Graehl, 1998). 
Most of the works are devoted to phoneme-based transliteration modeling (Knight and Graehl, 1998; Lee, 1999). 
Another interesting generative model can be found in Knight and Graehl (1998). 
The second task is back-transliteration (Fujii and Ishikawa, 2001; Jeong et al. , 1999; Knight and Graehl, 1998; Qu et al. , 2003), which identifies the source word corresponding to an existing transliterated word. 
(Knight and Graehl, 1998; Meng et al. , 2001; Al-Onaizan and Knight, 2002; Gao et al. , 2004)  has mostly assumed that one has a training lexicon of transliteration pairs, from which one can learn a model, often a sourcechannel or MaxEnt-based model. 
