1 Introduction WSD has been recognized as one of the most important subjects in natural language processing, especially in machine translation, information retrieval, and so on (Ide and Veronis, 1998). 
A review of methods for word sense disambiguation is presented by Ide and colleagues (Ide and Veronis, 1998). 
To alleviate this problem, class-based approaches augment word-level features with category-level ones (Ide and Veronis, 1998; Jurafsky and Martin, 2000). 
In general, following Ide and Veronis (1998) the various WSD approaches of the past can be divided into two types, i.e., dataand knowledge-based approaches. 
Within the past 10 years, original contributions have been made in the areas of compositional semantics and lexical context assignment (see Ide and Veronis [1998] for the state of the art on word sense disambiguation). 
