A sufficient condition for proper assignment is established by Chi and Geman (1998), who prove that production probabilities estimated by the maximum-likelihood (ML) estimation procedure (or relative frequency estimation procedure, as it is called in computational linguistics) always impose proper PCFG distributions. 
This even holds if the input grammar is non-tight, meaning that probability mass is lost in infinite derivations (Sanchez and Bened, 1997; Chi and Geman, 1998; Chi, 1999; Nederhof and Satta, 2003). 
Such maximization provides the estimator (see for instance (Chi and Geman, 1998)) pG(A  ) = f(A  ,T )f(A,T ) . 
The proof in (Sanchez and Bened, 1997) makes use of spectral analysis of expectation matrices, while the proof in (Chi and Geman, 1998)isbasedonasimplercountingargument. 
This simple estimator, as shown by Chi and Geman (1998), assigns proper production probabilities for PCFGs. 
