Heeman and Allen proposed an integrated model for the detection of speech repairs (Heeman and Allen, 1999). 
The transcription contains manually added punctuation, and it also explicitly records disfluencies and speech repairs by marking both interruption points and word fragments (Heeman & Allen, 1999). 
(Bed017) In this example, only one of the three instances of it is a referential pronoun: The first it appears in the reparandum part of a speech repair (Heeman & Allen, 1999). 
Heeman and Allen (1999) describe a noisy channel model of speech repairs, but leave \extending the model to incorporate higher level syntactic. 
The transcription contains capitalization and punctuation, and it also explicitly records interruption points and word fragments (Heeman & Allen, 1999), but not the extent of the related disfluencies. 
