Language users are sensitive to relative frequencies of variant forms and senses of lexical items (Briscoe and Copestake, 1999, p511).


We evaluated the performance of the model on all verbs listed in Levin (1993) that are polysemous (i.e. , members of more than one class) and take frames characteristic of the widely studied dative and benefactive alternations (Pinker 1989; Boguraev and Briscoe 1989; Levin 1993; Goldberg 1995; Briscoe and Copestake 1999) and of the less well-known conative and possessor object alternations (see examples (1)(4)).


(Briscoe and Copestake, 1999) propose using frequency information besides syntactic/semantic restrictions, but use only a priori sense frequencies without contextual features.


The transformation model approach is therefore a full stochastic treatment of lexicalized syntax apparently the first to treat lexical redundancy rules, although (Briscoe and Copestake, 1999) give an ad hoc approach.


