Bangalore and Joshi (1999) refer to supertagging as almost parsing, because once the correct lexical categories have been assigned, the parser is left with much less work to do. 
Supertagging was originally developed for Lexicalized Tree Adjoining Grammar (Bangalore and Joshi, 1999), but has been particularly successful for wide-coverage CCG parsing (Clark and Curran, 2007b). 
First, in order to limit the number of categories assigned to each word in the sentence, a supertagger (Bangalore and Joshi, 1999) assigns to each word a small number of possible lexical categories. 
Supertag This is a variant of the approach above, but using supertags (Bangalore and Joshi, 1999) instead of PoS tags. 
Hence the result of supertagging is termed as an almost parse (Bangalore and Joshi, 1999). 
