The existence of complex refusal acts has been remarked on by (Gree n and Carberry, 1999).


(Traum and Allen, 1994) have challenged intention-based approaches to dialog modeling ((Cohen and Levesque, 1990), (Lambert and Carberry, 1991), (Airenti et al. , 1993)) arguing that, in non-cooperative settings (i.e. , when the participants do not have 1 (Merrit, 1976) ~(Green and Carberry, 1999) shared goals), intention-based approaches leave unexplained why a participant should bother to be cooperative, both at the conversational and at the behavioral level.


