In earlier work on recognizing expressions of doubt, we developed an algorithm that combined linguistic, contextual, and world knowledge and applied it to the recognition of complex discourse acts(Carberry and Lambert, 1999).


Like BIAS, the system described in Carberry and Lambert (1999) combined linguistic and contextual knowledge to recognize a user's intentions from rejoinders.


Several researchers have dealt with different aspects of argumentation; e.g., (Flowers et al. , 1982; Quilici, 1992; Chu-Carroll and Carberry, 1995; Carberry and Lambert, 1999).


The system described in (Carberry and Lambert, 1999) recognized a users intentions during expertconsultation dialogues.


Plan recognition systems also generate one or more interpretations of a users utterances, employing different resources to ll in information omitted by the user, e.g., (Allen and Perrault, 1980; Litman and Allen, 1987; Carberry and Lambert, 1999; Raskutti and Zukerman, 1991).


