If arbitrary reorderings are allowed, the search problem is NP-complete (Knight, 1999). 
This exponential complexity comes as no surprise given that the problem of intersecting an ngram language model with a bag of words is known to be NP-complete (Knight, 1999). 
While certain similarities of SMT decoding and TSP were already pointed out in (Knight, 1999), where it was shown that any Traveling Salesman Problem may be reformulated as an instance of a (simplistic) SMT decoding task, and while certain techniques used for TSP were then adapted to word-based SMT decoding (Germann et al., 2001; Tillmann and Ney, 2003; Tillmann, 2006), we are not aware of any previous work that shows that SMT decoding can be directly reformulated as a TSP. 
Knight, 1999). 
If arbitrary reorderings are allowed, the search problem is NP-hard (Knight, 1999). 
