Semiring parsing (Goodman, 1999) is a general framework to describe such algorithms. 
As already remarked by Goodman (1999), deduction systems can also be extended to manipulate weights. 
This is similar to the k-best semiring defined by Goodman (1999). 
(1995) showed a connection between DP (specifically, as used in parsing) and logic programming, and Goodman (1999) augmented such logic programs with semiring weights, giving an algebraic explanation for the intuitive connections among classes of algorithms with the same logical structure. 
Our work is strongly influenced by Goodman (1999) and Eisner et al. 
