(2008), probably due to the difference in training data size (ours is 20,000 and Sumida et al.


Some regarded Wikipedia as the corpora and applied hand-crafted or machine-learned rules to acquire semantic relations (Herbelot and Copestake, 2006; Kazama and Torisawa, 2007; Ruiz-casado et al., 2005; Nastase and Strube, 2008; Sumida et al., 2008; Suchanek et al., 2007).


A layout structure is chosen 434 (a) Layout structure of article TIGER Range Siberian tiger Bengal tiger Subspecies Taxonomy Tiger Malayan tiger (b) Tree structure of Figure 4(a) Figure 4: Wikipedia article and its layout structure as a source of hyponymy relations because it can provide a huge amount of them (Sumida et al., 2008; Sumida and Torisawa, 2008) 1 , and recognition of the layout structure is easy regardless of languages.


