BNC sentences were also parsed with RASP (Andersen et al., 2008).


SVM classifiers were trained2 with the LIBLINEAR library (Fan et al., 2008) and learned to predict the frame name, role spans, and role labels.


With regard to semantic similarity, WordNet is a prime contender and indeed has been previously used to acquire new predicates in FrameNet (Pennacchiotti et al., 2008; Burchardt et al., 2005; Johansson and Nugues, 2007).


