To our knowledge, little extensive work exists in this field; an example is the TextCoop project (Delpech and Saint-Dizier, 2008) that produced a procedural tagger able to recognize and segment the main units found in French procedural text (titles, instructions, prerequisites, warnings and advice) via an ad hoc markup convention (see Table 1).


In particular, the problem of addressing definition questions has received great attention from the research community (Chen et al., 2006; Moschitti et al., 2007), while less research has been conducted so far on other types of non-factoid QA, such as whyquestions (Verberne et al., 2007; Pechsiri et al., 2008) and procedural (also called how-to) questions (Yin, 2006; Delpech and Saint-Dizier, 2008).


