For example, non-native speakers of English were found to take longer time to annotate part of 18 speech tags (Ringger et al., 2008).


(2008) and Ringger et al.


Annotation cost has been traditionally measured in terms of the number of examples annotated, but it has been widely acknowledged that different examples may require different annotation effort (Settles et al., 2008; Ringger et al., 2008).


