Taking the standard version of the CCGbank (Hockenmaier and Steedman, 2007) as input, our system then introduces greater depth of linguistic insight by augmenting it with attributes the original corpus lacks: Propbank roles and head lexicalization for case-marking prepositions (Boxwell and White, 2008), derivational re-structuring for punctuation analysis (White and Rajkumar, 2008), named entity annotation and lemmatization.


2.2 Realization from an Enhanced CCGbank Our starting point is an enhanced version of the CCGbank (Hockenmaier and Steedman, 2007)a corpus of CCG derivations derived from the Penn Treebankwith Propbank (Palmer et al., 2005) roles projected onto it (Boxwell and White, 2008).


Recent work (Boxwell and White, 2008) changes some structures in the CCGBank to correspond more closely with the Probbank annotations.


