The 20 meetings were labeled by a single annotator, though Wilson (2008) did conduct a study of annotator agreement on two meetings, reporting a  of 0.56 for detecting subjective utterances.


The definitions for positive and negative subjectivity mirrored those given by Wilson (2008).


This difference in pattern numbers can be explained by negative utterances being less common in the AMI meetings, as noted by Wilson (2008).


4.2 Subjectivity Annotation Wilson (2008) has annotated 20 AMI meetings for a variety of subjective phenomena which fall into the broad classes of subjective utterances, objective polar utterances and subjective questions.


