W09-1511:1	136:155	More recently, in biomedical domain, (Baumgartner et al., 2008) describes implementation of a framework and, although it is applied to a text mining task, the approach remains quite close in its foundations (evaluation oriented, iterative testing, modular framework, open source, corpora based, etc.) to ours and encourages these kind of initiative by showing the importance of continuous evaluation while coding parser and engineering grammar.
---------------------------------------------------
W09-1511:2	12:155	As shown by (Chatzichrisafis et al., 2008), where developers receive daily reports of systems performance for improving their system, systematic evaluation with regression testing has shown to be gainful to accelerate grammar engineering.
---------------------------------------------------
W09-1511:3	37:155	1.3 The Passage Project Our work is part of the Passage project (Clergerie et al., 2008b).
---------------------------------------------------
