A92-1025:1	87:200	4 Lexico-Semantic Patterns In SCISOR \[Jacobs and Rau, 1990\], MUC \[Jacobs et al. , 1991; Krupka et al. , 1991\], and other applications, we have found that lexically-driven pre-processing serves as a complement to parsing and semantic interpretation, both in identifying portions of relevant text and in marking the input text to make it easier to process.
---------------------------------------------------
A92-1025:2	17:200	Like Construe/TIS \[Hayes and Weinstein, 1990\], the work derives from, and coordinates with, NLP efforts, but the system primarily uses a lexicosemantic pattern matcher for categorization \[Jacobs et al. , 1991\].
---------------------------------------------------
H92-1043:3	16:201	An analysis of the MUC-3 evaluation suggests that all of the MUC-3 systems experienced significant difficulty with relevant text classification (Krupka et al. 1991).
---------------------------------------------------
