M93-1023:1	4:188	We employ a hybrid system architecture that combines selective concept extraction [Lehnert 1991] technologies developed at UMass with trainable classifier technologies develope d at Hughes [Dolan et al . 1991].
---------------------------------------------------
X93-1022:2	5:366	We employ a hybrid system architecture that combines selective concept extraction \[Lehnert 1991\] technologies developed at UMass with trainable classifier technologies developed at Hughes \[Dolan et al. 1991\].
---------------------------------------------------
