7 Fallout = (INC + SPU)/(NUMBER_POSSIBLE_INCORRECT) 6 A more detailed mathematical description of the evaluation metrics complete with examples can be found in Chinchor (1991a).


The systems scored higher on the simpler 11 The detailed results of the linguistic phenomena test experiment appear in the MUC-3 proceedings and contain the raw scores and plots of recall and precision (see Chinchor 1991b).


Additional features allowed the program to be adapted whenever the template design changed, allowed the scoring of subsets of slots and templates useful in linguistic phenomena testing (Chinchor 1991b), and allowed the merging of partial credit decisions across sites for more uniform scoring.


