In approaching the problem of unrestricted texts, we agree with those researchers (Hobbs, 1991; Grishman et al. , 1991) who think that it is possible to build correct parses and interpretations for realworld texts. 
We think that the same critique applies to skimmers (Lehnert et al. , 1991), but for very different reasons. 
An analysis of the MUC-3 evaluation suggests that all of the MUC-3 systems experienced significant difficulty with relevant text classification (Krupka et al. 1991). 
We are studying mechanisms under which the interpreter will override the parser and will get it out of trouble in processing very complex sentences (Krupka et al. , 1991; Jacobs et al. , 1991). 
In fact, it is hard for us to see how statistical methods (de Marcken, 1990; Church et al. , 1991) could be used for building knowledge-bases with sufficient expressive power to correctly answer questions posed by expert systems or human users. 
