2 The MUC-4 IE Task and Data The focus of our research is on the MUC-4 information extraction task (Sundheim, 1992), which is to extract information about terrorist events. 
6 Experiments and Results 6.1 Data Sets We evaluated the performance of our IE system on two data sets: the MUC-4 terrorism corpus (Sundheim, 1992), and a ProMed disease outbreaks corpus. 
Information extraction systems in international relations perform a similar task to those competing in early Message Understanding Competitions (Sundheim, 1991, 1992). 
Our system is aimed at documents typified by those in the MUC-4 corpus (Sundheim, 1992). 
Introduction One of the issues to emerge from recent evaluations of information extraction systems (Sundheim, 1992) is the importance of discourse processing (Iwafiska et al. , 1991) and, in particular, the ability to recognise multiple events in a text. 
