W97-0809:1	35:218	Ralph Grishman and his group at NYU reached the conclusion that "WordNet may be a good source of concepts, but that it will not be of net benefit unless manually reviewed with respect to a particular application" (Grishman et al. , 1992).
---------------------------------------------------
W97-0809:2	33:218	Some early work of applying WordNet for the lex~ ical semantic acquisition can be found in NYU's MUC-4 system (Grishman et al. , 1992), which c used WordNet hierarchies for semantic classification.
---------------------------------------------------
P98-1045:3	20:121	The highest performing systems include large numbers of handcoded rules, or patterns, such as VIE (Humphreys et al. 1996), the UMass system (Fisher et al. 1997) and Proteus (Grishman et al. 1992), but lately a high performance has been obtained by the use of statistical methods.
---------------------------------------------------
A97-1033:4	5:187	1 Introduction In our work to date on news summarization at Columbia University (McKeown and Radev, 1995; Radev, 1996), information is extracted from a series of input news articles (MUC, 1992; Grishman et al. , 1992) and is analyzed by a generation component to produce a summary that shows how perception of the event has changed over time.
---------------------------------------------------
