In addition, the performance of such systems varies greatly depending on various additional factors including known vocabulary, sentence length, the amount of training, quality of parsing, etc. Despite the great variations in the performances of such systems, it has been hypothesized that there are facts that are simply harder to extract than others (Hirschman, 1992).


There is active research in the evaluation of spoken language understanding: Hirschman et al. , 1992 and Price et al. , 1992.


The second test was an analysis of the effect of discourse complexity on the performance of the MUC-4 systems (Hirschman 1992).


