TECHNICAL APPROACH Our approach is a synthesis of statistical and linguistic models of language, embodied for MUC-6 in the PLU M system (Probabilistic Language Understanding Model) . We began this research in 1991 and applied it that year i n MUC-3 . Since that time, we have successfully applied probabilistic models to the following :  part of speech tagging, using Hidden Markov Models (Weischedel, et al ., 1993),  judgments of relevance of text (at the paragraph level) via a log odds model (Ayuso, et al ., 1992),  learning semantic information (selection restrictions, or case frames) from supervised training (Weischedel, et.


Techniques for proper noun extraction include the use of regular grammars to delimit and identify proper nouns (Mani et al. 1993; Paik et al. 1994), the use of extensive name lists, place names, titles and "gazetteers" in conjunction with partial grammars in order to recognize proper nouns as unknown words in close proximity to known words (Cowie et al. 1992; Aberdeen et al. 1992), statistical training to learn, for example, Spanish names, from on-line corpora (Ayuso 474 Radev and McKeown Generating Natural Language Summaries et al. 1992), and the use of concept-based pattern matchers that use semantic concepts as pattern categories as well as part-of-speech information (Weischedel et al. 1993; Lehnert et al. 1993).


1 Introduction In our work to date on news summarization at Columbia University (McKeown and Radev, 1995; Radev, 1996), information is extracted from a series of input news articles (MUC, 1992; Grishman et al. , 1992) and is analyzed by a generation component to produce a summary that shows how perception of the event has changed over time.


Techniques for proper noun extraction include the use of regular grammars to delimit and identify proper nouns (Mani et al. , 1993; Paik et al. , 1994), the use of extensive name lists, place names, titles and "gazetteers" in conjunction with partial grammars in order to recognize proper nouns as unknown words in close proximity to known words (Cowie et al. , 1992; Aberdeen et al. , 1992), statistical training to learn, for example, Spanish names, from online corpora (Ayuso et al. , 1992), and the use of concept based pattern matchers that use semantic concepts as pattern categories as well as part-of-speech information (Weischedel et al. , 1993; Lehnert et al. , 1993).


6.3.4 First Application of Statistical Text Classifier to Data Extraction from Text For MUC-4, we demonstrated the first technique for significantly varying the trade-off between recall and precision (Weischedel et al, 1992).


