The overall performance of recall and precision is defined by the Fomeasurement (Chinchor 1992), which is (~2 + 1.0)  P * R ~.P+R where P is precision, R is recall, 13 = 1 ff precision and recall are equally important.


The overall performance of recall and precision is defined by F-measurement (Chinchor, 1992), which is (/~2 + 1.0)  P  R /32*P+R where P is precision, R is recall,/~ = 1 if precision and recall are equally important.


