Our work is mostly influence by the work of (Hobbs, 1992; Appelt et al. , 1993; Grishman, 1995) as well as by the work described in (Anderson et al. , 1992; Dowding et al. , 1993).


These modules perform all but one o f the functions described by Hobbs (1993) for his generic information extraction systemwe omit the text filterin g phase.


Current approaches As an IE system processes a document, it typically creates a template for each sentence (Hobbs, 1993), a framelike data structure that contains a maximally explicit and regularised representation of the information the system is designed to extract.


Although more exotic forms of event recognition exist at varying levels of analysis (such as within the abductive reasoning mechanism of SRI's TACITUS system (Hobbs et al. , 1991), in a thesaurus-based lexical cohesion algorithm (Morris and Hirst, 1991) and in a semantic network (Kozima, 1993)), template merging is the most used method.


