These roles are well summarized by Chinchor and Dungca (1995), who refer specifically to the methods used for the U.S.-government-sponsored Message Understanding Conference (MUC) evaluations of information extraction (IE) technology: The resulting scores \[assigned by the MUC evaluation process\] are used for decision-making over the entire evaluation cycle, including refinement of the task definition based on interannotator comparisons, technology development using training data, validating answer keys, and benchrnarking both system and human capabilities on the test data.


This extraction exercise was modeled after the "Named Entity" task of the Message Understanding Conference (MUC) (Chinchor and Dungca, 1995).


