using the model-theoretic MUC scoring program (Vilain et al. , 1995). 
Decision tree algorithms were used for reference resolution by Aone and Bennett (1995, C4.5), McCarthy and Lehnert (1995, C4.5) and Soon et al. 
4.5 MUC-style results It is common practice to evaluate coreference resolution systems according to a scheme originally developed for MUC evaluation by (Vilain et al. , 1995). 
6.2 Experiments We used the MUC coreference scoring metric (Vilain et al 1995) to evaluate3 our systems. 
Results are shown in Table 2 (Duplicated Soon Baseline) where performance is reported in terms of recall, precision, and F-measure using the modeltheoretic MUC scoring program (Vilain et al. , 1995). 
