In fact, participants in that competition from the University of Durham (Morgan et al. , 1995) and from SRA (Krupka, 1995) report that gazetteers did not make that much of a difference to their system.


Secondly experience showed that the lexical ambiguity carried by generic dictionaries does not allow their direct use in computational systems (Basili and Pazienza, 1997; Morgan et al. , 1995).


