P98-1011:1	18:115	A set of Interpretation Rules (IRs) applies whenever an anaphor is encountered, proposing potential antecedents from the registers, from which one is chosen using other criteria: syntactic, semantic, inferential, etc. 74 2.1 Evaluating Focus-Based Approaches Sidner's algorithmic account, although not exhaustively specified, has lead to the implementation of focus-based approaches to anaphora resolution in several systems, e.g. PIE (Lin, 1995).
---------------------------------------------------
P02-1014:2	48:183	2.1 Baseline Experiments We evaluate the Duplicated Soon Baseline system using the standard MUC-6 (1995) and MUC7 (1998) coreference corpora, training the coreference classifier on the 30 dry run texts, and applying the coreference resolution algorithm on the 2030 formal evaluation texts.
---------------------------------------------------
P02-1014:3	15:183	Although the use of similar knowledge sources has been explored in the context of both pronoun resolution (e.g. Lappin and Leass (1994)) and NP coreference resolution (e.g. Grishman (1995), Lin (1995)), most previous work treats linguistic constraints as broadly and unconditionally applicable hard constraints.
---------------------------------------------------
P02-1014:4	51:183	Results are shown in Table 2 (Duplicated Soon Baseline) where performance is reported in terms of recall, precision, and F-measure using the modeltheoretic MUC scoring program (Vilain et al. , 1995).
---------------------------------------------------
P98-2172:5	89:151	An interesting solution has been proposed by Lin (1995) using constraint solving to group REs into MRs. While this idea fits the MR paradigm, it doesn't work well incrementally, which makes use of activation impossible.
---------------------------------------------------
