J02-3002:1	485:581	Named-entity recognition systems usually use sets of complex hand-crafted rules that employ a gazetteer and a local context (Krupa and Hausman 1998).
---------------------------------------------------
A00-1040:2	17:167	Krupke and Hausman (1998) made extensive use of name lists in their system.
---------------------------------------------------
E99-1001:3	27:225	The basic gazetteers in the Isoquest system for MUC7 contain 110,000 names, but Krupka and Hausman (1998) show that system performance does not degrade much when the Proceedings of EACL '99 gazetteers are reduced to 25,000 and 9,000 names; conversely, they also show that the addition of an extra 42 entries to the gazetteers improves performance dramatically.
---------------------------------------------------
E99-1001:4	223:225	Without further formal evaluations with externally supplied evaluation corpora it is difficult to judge how general this text type is. It is encouraging to note that Krupka and Hausman (1998) point out that the MUC-7 articles which we used in our experiments have less external evidence than do Wall Street Journal articles, which suggests that on Wall Street Journal articles our system might perform even better than on MUC-7 articles.
---------------------------------------------------
W98-1118:5	218:231	All three of these elements are present in systems such as IsoQuest's (Krupka and Hausman, 1998), and their absence from MENE probably explains much of the reason why the MENE-only system failed to perform at the state-of-the-art.
---------------------------------------------------
W98-1118:6	85:231	(Krupka and Hausman, 1998) shared with us the outputs of their systems on our training corpora as well as on various test corpora.
---------------------------------------------------
C02-1127:7	57:203	3 Lexical Grammar Processing in Local Context Named Entity tagging systems (Krupka and Hausman, 1998; Srihari et al. , 2000) attempt to tag information such as names of people, organizations, locations, time, etc. in running text.
---------------------------------------------------
W03-0808:8	16:225	The state-of-the-art exemplified by systems such as NetOwl [Krupka & Hausman 1998], IdentiFinder [Miller et al 1998] and InfoXtract [Srihari et al 2000] has reached near human performance, with 90% or above F-measure.
---------------------------------------------------
W03-1211:9	17:189	Almost all NE systems (e.g. [Bikel et al. 1997], [Krupka & Hausman 1998]) utilize case-related features.
---------------------------------------------------
A00-1023:10	41:155	The Textract NE tagger has achieved speed and accuracy comparable to that of the few deployed NE systems, such as NetOwl \[Krupka & Hausman 1998\] and Nymble \[Bikel et al 1997\].
---------------------------------------------------
W03-0106:11	43:130	The basic information extraction task is NE tagging [Krupka and Hausman 1998; Srihari et al. 2000].
---------------------------------------------------
W06-2918:12	35:203	However, some research has questioned the usefulness of gazetteers (Krupka and Hausman, 1998).
---------------------------------------------------
