We use Lins (1998b) MINIPAR dependency parser to extract grammatical relations.


We then infer the SC of a common noun as follows: (1) we compute the probability that the common noun co-occurs with each of the eight NE types6 based on the extracted appositive relations, and (2) if the most likely NE type has a co-occurrence probability above a certain threshold (we set it to 0.7), we create a INDUCED CLASS fea1This is motivated by Lins (1998c) observation that a coreference resolver that employs only the rst WordNet sense performs slightly better than one that employs more than one sense.


(7) NEIGHBOR: Research in lexical semantics suggests that the SC of an NP can be inferred from its distributionally similar NPs (see Lin (1998a)).


In addition, subsequent to the evaluation, the University of Manitoba (Lin, 1998) and IsoQuest, Inc.


Each triple has the form w1.R.w2 where w1 and w2 are chunks and R is a syntactic relation (Lin, 1998), (Kilgarriff et al., 2004).


