These relations are determined using techniques described in (Baldwin et al. , 1998).


The ECM-F scorer overcomes two shortcomings of the MUC scorer: not considering single mentions and treating every error as equally important (Baldwin et al. , 1998), which makes the ECM-F a more adequate measure of coreference.


This only shows that none of them is particularly poor, but it is not a relevant way of comparing methods the MUC metric has been found too indulgent by researchers ((Luo et al. , 2004), (Baldwin et al. , 1998)).


