If we consider the most complex MUC-7 task (i.e. , the Scenario Template task (MUC7, 1998)), the current technology is not able to provide results near an operational level (expected F(1)=75%; the best system scored about 50% (Aone et al. , 1998)).


It was implemented in the IE module of FACILE, a EU project for multilingual text classification and !E. 1 Introduction Most successful approaches in IE (Appelt et al. , 1993; Grishman, 1995; Aone et al. , 1998) make a very poor use of syntactic information.


Scenario Template recognition needs the correct treatment of syntactic relations at both sentence and text level (Aone et al. , 1998).


While the tagging component is similar to other pattern-based IE systems (e.g. , Appelt et al. 1995; Aone et al. 1998, Yangarber and Grishman 1998), our EventTagger is more portable through a lexicon-driven approach.


