On the other hand, we scored lower on all-caps than BBN's Identifinder in the MUC-7 formal evaluation for reasons which are probably similar to the ones discussed in section 9 in the comparison of our mixed case performances (Miller et al. , 1998) (Borthwick et al. , 1998). 
Borthwick, A. et al. 1998. 
More MENE test results and discussion of the formal run can be found in (Borthwick et al. , 1998). 
[MUC-7 1998] There is considerable research on NE tagging using supervised machine learning [e.g. Bikel et al. 1997; Borthwick 1998]. 
M.E. was first applied to named entity recognition at the MUC-7 conference by (Borthwick et al. , 1998) and (Mikheev and Grover, 1998). 
