While the tagging component is similar to other pattern-based IE systems (e.g. , Appelt et al. 1995; Aone et al. 1998, Yangarber and Grishman 1998), our EventTagger is more portable through a lexicon-driven approach.


This is the at)t)roa(:h used by our e.xtraction system (Grishman, 1995; Yangarber and Grishman, 1998).


Solne of this work has enli)hasized il\]teractive tools to (:onvert examples to extractioi~ t)atterlls (Yangarber and Grishman, 1997); nmch ot:' the re, search has focused on methods for automatically converting a cortms annotated with extraction examples into patterns (Lehnert et al. , 1992; Fisher et al. , 1995; Miller el; al. , 1998).


The internal and external evidence is being used by all NERC systems such as LTG (Mikheev et al. 1999), FASTUS (Hobbs et al. 1997), Proteus (Yangarber, Grishman, 1998).


