Recently, approaches for NER are a shift away from handcrafted rules[Grishman, et al. 1995] [Krupka, et al. 1998][Black et al. 1998] towards machine learning algorithms, i.e. unsupervised model like DL-CoTrain, CoBoost[Collins, 1999, 2002], supervised learning like Error-driven [Aberdeen, et al. 1995], Decision Tree [Sekine, et al. 1998], HMM[Bikel, et al. 1997] and Maximum Entropy[Borthwick, et al. 1999][Mikheev, et al.1998].


The escape probability[Black, et al. 1998] was adopted to smooth the statistical model shown as (15).


Early NER systems (Fisher et al. , 1997), (Black et al. , 1998) etc. , participating in Message Understanding Conferences (MUC), used linguistic tools and gazetteer lists.


