(see for example, Bagga, Baldwin, and Shelton \[1999\]), or before it extends the relation of coreference to cover whole/part and class/instance relations (e.g. Popescu-Belis 1998; Hirschman and Chinchor 1997).


We de ne this in terms of the speakers assumptions about the hearers knowledge/beliefs, and we express it by the well-known old/new distinction.2 3.1 Annotation Scheme Our annotation scheme for the discourse layer mainly builds on (Prince, 1992) and (Eckert and Strube, 2001), as well as on related work on annotation of anaphoric links (Passonneau, 1996; Hirschman and Chinchor, 1997; Davies et al. , 1998; Poesio, 2000).


