Integrated Model[Sun, et al. 2002] [Zhang, et al. 2003][Yu, et al. 1998][Chua, et al. 2002] deals with all kinds of entities in a unified statistical framework.


Some machine learning algorithms also have been investigated in Chinese NER, including HMM (Yu et al. , 1998; Jing et al. , 2003), class-based language model (Gao et al. , 2005; Wu et al. , 2005), RRM (Guo et al. , 2005; Jing et al. , 2003), etc. However, when a machine learning-based NER system is directly employed in a new domain, its performance usually degrades.


