QA is different than search engines in two aspects: (i) instead of a string of keyword search terms, the query is a natural language question, necessitating question parsing, (ii) instead of a list of documents or URLs, a list of candidate answers at phrase level or sentence level are expected to be returned in response to a query, hence the need for text processing beyond keyword indexing, typically supported by Natural Language Processing (NLP) and Information Extraction (IE) (Chinchor and Marsh 1998, Hovy, Hermjakob and Lin 2001, Li and Srihari 2000).


In the US, MUC [Chinchor & Marsh 1998] has been the driving force for developing this technology.


Typically QA is supported by Natural Language Processing (NLP) and IE [Chinchor & Marsh 1998] [Hovy et al. 2001] [Srihari & Li 2000].


