The supervised lexical sample system that participated in SENSEVAL-3 is the Duluth3 (English) or Duluth8 (Spanish) system as used in SENSEVAL2 (Pedersen, 2001b). 
This would not rule out the possibility that bigram presence is as equally useful a feature as unigram presence; in fact, Pedersen (2001) found that bigrams alone can be efiective features for word sense disambiguation. 
We also obtained salient bigrams in the context, with the methods and the software described in (Pedersen, 2001). 
Following the description in (Cabezas et al. , 2001), our own re-implementation of UMD-SST gives a recall of 58.6%, close to their reported figure of 56.8%. 
It should be noted that the experiments for the SENSEVAL-2 and SENSEVAL-1 data using unigrams and bigrams are re-implementations of (Pedersen, 2001a), and that our results are comparable. 
