W07-2069:1	29:92	In our preliminary experiments, we found that gain (Papineni, 2001) is the most effective term weighting scheme for generating feature vectors for clustering in this kind of task.
---------------------------------------------------
L08-1223:2	49:60	For machine translation, we calculated three commonly used automated MT metrics: BLEU (Papineni et al., 2001), METEOR (Banerjee and Lavie, 2004; Lavie et al., 2005), and TER (Snover et al., 2005), with both reference and hypothesis texts normalized much like they were normalized for ASR (see Condon, et al.,</context> </contexts> <marker>Papineni, Roukos, Ward, Zhu, 2001</marker> <rawString>Papineni, K., S. Roukos, T. Ward, and W. Zhu (2001).
---------------------------------------------------
N09-1060:3	35:178	They thus introduce the notion of residual IDF which measures exactly this deviation: residualIDFw=IDFwlog21et Papineni (2001) introduces the notion of gain: gainw=df wD df wD 1logdf wD  This measure tends to give low weights to very highand very lowfrequency words.
---------------------------------------------------
