W05-1611:1	38:285	In NLG machine learning methods have been used to solve single tasks such as content selection and ordering (e.g. [Duboue, 2004; Dimitromanolaki and Androutsopoulos, 2003]), lexicalization (e.g. [Reiter and Sripada, 2004]) and referring expressions generation (e.g. [Cheng et al. , 2001]).
---------------------------------------------------
W04-2327:2	6:49	The GNOME corpus has been used to study salience, particularly as formalized in Centering theory (Poesio et al. , 2004c), to develop statistical models of natural language generation (e.g. , (Poesio, 2000a; Henschel et al. , 2000; Cheng et al. , 2001; Cheng, 2001; Karamanis, 2003)) and to evaluate anaphora resolution systems, with a special focus on the resolution of bridging references (Poesio, 2003; Poesio and Alexandrov-Kabadjov, 2004; Poesio et al. , 2004b).
---------------------------------------------------
W06-1412:3	29:191	Another related study in statistical NP generation (Cheng et al. , 2001) focuses on choosing the modifiers to be included.
---------------------------------------------------
W04-0210:4	54:162	(6) <unit id="u1" utype="title">Side effects</unit> <p><s stype="decl"><unit> Side effects may occur <unit>when PRODUCTY is applied to large parts of the body,  </unit>  </unit>  </s>  </p> Problems with Attributes The most difficult attribute to mark was UTYPE, and our main problem was to distinguish between relative clauses and parentheticals, since its not always easy to tell whether a relative clause is restrictive or non-restrictive (see also (Cheng et al. , 2001)).
---------------------------------------------------
W04-0210:5	156:162	We started doing this for the annotation of modifiers (Cheng et al. , 2001), and developed an interface to WordNet, but too late to redo the whole corpus.
---------------------------------------------------
W04-0210:6	5:162	These results, and the annotated corpus, were used in the development of both symbolic and statistical natural language generation algorithms for sentence planning (Poesio, 2000a; Henschel et al. , 2000; Cheng et al. , 2001), aggregation (Cheng, 2001) and text planning (Karamanis, 2003).
---------------------------------------------------
