Some researchers have begun to apply statistical techniques to identify learner errors in the context of essay evaluation (Chodorow & Leacock, 2000; Lonsdale & Strong-Krause, 2003), to detect non-native text (Tomokiyo & Jones, 2001), and to support lexical selection by ESL learners through first-language translation (Liu et al. , 2000).


Proceedings of the Conference on Empirical Methods in Natural al. , 1998; Tomokiyo and Jones, 2001; Kessler et al. , 1997).


In this research, we allow unrestricted classes of errors1, and in this regard our goal is closest to that of (Tomokiyo and Jones, 2001).


