We represent each user turn using the feature set shown in Figure 2, which we previously found useful for predicting corrections (Hirschberg et al. , 2001). 
1 Introduction Interactive question answering (QA) has been identified as one of the important directions in QA research (Burger et al. , 2001). 
We also found that user corrections of system misrecognitions exhibit certain typical prosodic features, which can be used to identify such turns (Swerts et al. , 2000; Hirschberg et al. , 2001). 
To better facilitate user information needs, recent trends in QA research have shifted towards complex, context-based, and interactive question answering (Voorhees, 2001; Small et al. , 2003; Harabagiu et al. , 2005). 
In other papers (Swerts et al. , 2000;; Hirschberg et al. , 2001;; Litman et al. , 2001), we have already given some descriptive statistics on corrections and aware sites and we have been looking at methods to automatically predict these two utterance categories. 
