We used Florian and Ngais Fast TBL system (fnTBL) (Ngai and Florian, 2001) to train rules using dis uency annotated conversational speech data. 
1The PoS tagging was performed with the fnTBL toolkit (Ngai and Florian, 2001). 
items that did not occur in the same chunk, according to a chunker based on fnTBL 1.0 (Ngai and Florian, 2001), 2. 
To overcome the lengthy training time associated with this approach, we used fnTBL, a fast version of TBL that preserves the performance of the algorithm (Ngai and Florian, 2001). 
The Reuters Copus was first tagged and chunked using fnTBL (Ngai and Florian, 2001), and lemmatised using morph (Minnen et al. , 2001), while the Mainichi Shimbun was segmented and tagged using ChaSen (Matsumoto et al. , 1999). 
