Several different re-ranking methods have been proposed that show how recognition rates can be improved by letting external processes do the top N ranking and not the recognizer (Chotimongkol & Rudnicky, 2001; van Noord et al. , 1997).


An approach taken both in dialogue systems and dictation applications is to first write an interpretation grammar and from that generate an artificial corpus which is used as training corpus for the SLM (Raux et al, 2003; Pakhomov et al, 2001; Fosler-Lussier & Kuo, 2001).


In addition, the grammar-based approach in the experiments reported in (Knight et al, 2001) outperforms the SLM approach on semantic error rate on in-coverage data.


However, SLMs are more robust, can handle out-of-coverage output, perform better in difficult conditions and seem to work bet57 ter for naive users (see (Knight et al, 2001)) while speech recognition grammars are limited in their coverage depending on how well grammar writers succeed in predicting what users may say (Huang et al, 2001).


