(Charniak, 2001) presents a solution to the problem of name structure recognition by incorporating coreference information.


Models of the internal structure of names have been used for cross-document coreference (Li et al., 2004; Bhattacharya and Getoor, 2006) and a goal in their own right (Charniak, 2001).


Charniak (2001) uses a Markov chain to generate 6 different components of peoples names, again assuming that the class of personal names can be pre-distinguished using a name list.


last name or post-title (similar to (Charniak, 2001)).


We follow Charniak (2001) in assuming that two names are consistent (can be references to the same entity) if they do not have different expansions for any lexical symbol.


