We estimate the counts by using the Waterloo MultiText1 system (Clarke and Terra, 2003b) with a corpus of about one terabyte of text collected by a Web crawler. 
We tried only PMI because it is easy to compute on a Web corpus and because PMI performed better than other measures in (Clarke and Terra, 2003a). 
Considerable efforts have been devoted to measure word similarity based on cooccurrence frequency of two words in a window (Church and Hanks, 1989; Turney, 2001; Terra and Clarke, 2003; Matsuo et al., 2006). 
We estimated these probabilities using the Waterloo MultiText System with a corpus of about one terabyte of unlabeled text, collected by a web crawler (Clarke et al. , 1995; Clarke and Cormack, 2000; Terra and Clarke, 2003). 
On the TOEFL test GLSA achieves the best precision of 0.86, which is much better than our PMI baseline as well as the highest precision of 0.81 reported in (Terra and Clarke, 2003). 
