The FN data is being used for a variety of purposes, some of which we had foreseen and others which we had not; these include uses as teaching materials for lexical semantics classes, as a basis for developing multi-lingual lexica, as an interlingua for machine translation, and as training data for NLP systems that perform question answering, information retrieval (Mohit and Narayanan, 2003), and automatic semantic parsing (Gildea and Jurafsky, 2002).


