We do so using the combination of the morphological component of CELEX (Burnage, 1990), a lexical database, NOMLEX (Macleod et al. , 1998), a nominalisation database, and CATVAR (Habash and Dorr, 2003), an automatically constructed database of clusters of in ected words based on the Porter stemmer (Porter, 1997).


We use the Catvar database to identify verb derivations (Habash and Dorr, 2003).


Finally, the original cross-part-of-speech lexical coercion models presented in Section 4.3.3 have related work in the primarily-syntactic coercion models utilized by Dorr and Habash (2002) and Habash and Door (2003), although their induction and modelling are quite different from the approach here.


C ad c C ad o Verbal suffix Recall Precision Recall Precision ta (V a =yes) 3/13 3/3 1/6 1/1 ta (V a =no) 42/44 42/63 18/18 18/29 re-ru 12/14 12/19 7/13 7/11 ru 3/9 3/6 0/2 0/5 tei-ru 1/5 1/7 2/8 2/6 ta / tei-ru 2/4 2/2 1/2 1/1 No rule for 11 inputs for 7 inputs Total (RULE) 63/100 63/100 29/56 29/53 (63%) (63%) (52%) (55%) BL 57/100 57/148 24/56 24/83 (57%) (39%) (43%) (29%) Future work includes (i) to enlarge our two resources as in (Dorr, 1997; Habash and Dorr, 2003) evolving an effective construction method, (ii) intrinsic evaluation of those resources, and, of course, (iii) to enhance the paraphrasing models through further experiments with a larger test-set.


Five of these (Habash and Dorr 2003).


