Subsequently, either SVDPACK or the LSI tools were used by the majority of researchers in this area (Schutze, 1995; Landauer and Dumais, 1997; Landauer et al. , 1998; Coccaro and Jurafsky, 1998; Foltz et al. , 1998; Bellegarda, 2000; Deng and Khudanpur, 2003).


However, results from the speech recognition community show that the inclusion of latent semantic information can enhance the performance of their models (Coccaro and Jurafsky, 1998; Bellegarda, 2000; Deng and Khudanpur, 2003).


