2 Post-Processing System We use the noisy channel framework to formulate the correction problem, revising our previous model (Kolak et al. , 2003).


This is true both in resource acquisition, such as automated bilingual lexicon generation (Kolak et al. , 2003), and for end-user applications such as rapid machine translation (MT) in the battlefield for document filtering (Voss and Ess-Dykema, 2000).


