(1998) and Klein and Manning (2003b). 
We intend to explore other methods for pruning the space and agenda-based parsing, in particular A* parsing (Klein and Manning, 2003), which will allow only the most probablepartsofthecharttobebuilt,improvingefficiency while still ensuring the optimal derivation is found. 
We show that recent work in hierarchical A  (Felzenszwalb and McAllester, 2007) can naturally be applied to both the hierarchically refined grammars of Petrov and Klein (2007) as well as the lexicalized grammars of Klein and Manning (2003a). 
This is the same procedure as Klein and Manning (2003a). 
3.2 Lexicalized Parsing We also experimented with the lexicalized parsing model described in Klein and Manning (2003b). 
