1http://l2r.cs.uiuc.edu/cogcomp/Data/ QA/QC/ 315 Hacioglu and Ward (2003) used linear support vector machines (SVMs) with question word 2grams and error-correcting output codes (ECOC) but no NE tagger or related word dictionaryto get 80.282% accuracy.


We did not use ECOC (Hacioglu and Ward, 2003) because the reported gain is less than 1%.


With the increasing popularity of statistical NLP, Li and Roth (2002), Hacioglu and Ward (2003) and Zhang and Lee (2003) used supervised learning for question classification on a data set from UIUC that is now standard1.


Hacioglu and Ward (2003) used linear support vector machines with question word bigrams and error-correcting output to obtain accuracy of 80.2% to 82.0%.


QC systems have some restrictions (Hacioglu and Ward, 2003), such as:  Traditional question classification uses a set of rules, for instance questions that start with Who ask about a person.


