One example is the algorithm for clustering by committee described by Pantel and Lin (2003), which automatically discovers word senses from text.


Inference systems often incorporated this information, typically as top-k or threshold-based filters (Pantel and Lin, 2003; Roth and Sammons, 2007).


One example is the algorithm for clustering by committee described by Pantel and Lin (2003), which automatically discovers word senses from text.


