W04-3012:1	8:208	Alternatively, it may be included in the processing pipeline at a later stage, namely at the interface between the automatic speech recognizer and the spoken language understanding component (Gurevych et al. , 2003a; Gurevych and Porzel, 2003).
---------------------------------------------------
W04-3012:2	145:208	4.3 Word2Concept ratio In previous experiments (Gurevych et al. , 2003a), we found that when operating on sets of concepts as representations of speech recognition hypotheses, the ratio of the number of ontological concepts n in a given CR and the total number of words w in the respective SRH must be accounted for.
---------------------------------------------------
W04-2808:3	89:185	The ensuing distance between two concepts, e.g. a0a2a1a4a3a6a5a8a7a9a3a11a10a6a12 is then defined as the minimum score derived between a3a6a5 and a3a11a10 . So far, a number of additional normalization steps, contextual extensions and relation-specific weighted scores have been proposed and evaluated (Gurevych et al. , 2003a; Porzel et al. , 2003a; Loos and Porzel, 2004) The ONTOSCORE module currently employs two knowledge sources: an ontology (about 800 concepts and 200 relations) and a lexicon (ca.
---------------------------------------------------
W04-2808:4	176:185	Some of these tasks which are not mentioned herein are executed by different processing components that employ the same underlying knowledge model but apply different operations such as overlay and have been reported elsewhere (Alexandersson and Becker, 2001; Gurevych et al. , 2003b; Porzel et al. , 2003b).
---------------------------------------------------
W04-2808:5	4:185	The transition from the former to the later can be regarded as a scaling process, since virtually every processing technique applicable for restricted single domain user utterances has to be adopted to new challenges, i.e., varying context-dependencies (Porzel et al. , 2004) increasing levels of ambiguity (Gurevych et al. , 2003a; Loos and Porzel, 2004) and less predictable input (Loeckelt et al. , 2002).
---------------------------------------------------
W04-2808:6	58:185	Then, the existing ontology was adopted in the SMARTKOM project (Wahlster et al. , 2001) and modified to cover a number of new domains, e.g., new media and program guides, pedestrian and car navigation and more (Gurevych et al. , 2003b).
---------------------------------------------------
W04-2808:7	41:185	The knowledge-based approach employed herein (Gurevych et al. , 2003a) operates on an ontology partially derived from FrameNet data (Baker et al. , 1998) and is described by Gurevych et al.
---------------------------------------------------
W03-0809:8	129:177	The part of them containing the systems knowledge about application domains was obtained via the automatic transformation of an OIL-RDFS ontology (Gurevych et al. , 2003b).
---------------------------------------------------
W03-0809:9	171:177	E.g., it has been successfully applied to the task of scoring sets of concepts in terms of their semantic coherence (Gurevych et al. , 2003a).
---------------------------------------------------
W06-3505:10	105:282	Frequently, production systems (Engel, 2002), semantic chunkers (Bryant, 2004) or simple word-to-concept lexica (Gurevych et al. , 2003) are employed for this task.
---------------------------------------------------
W03-0903:11	127:198	5.1 Semantic Coherence Scoring We introduced the notion of semantic coherence as a special measurement which can be applied to estimate how well a given speech recognition hypothesis (SRH) fits with respect to the existing knowledge representation (Gurevych et al. , 2003).
---------------------------------------------------
W04-2312:12	54:186	The ontology-based system has been successfully used for a set of tasks such as finding the best speech recognition hypotheses from sets of competing SRHs, labeling SRHs as correct or incorrect representations of the users intention and for scoring their degree of contextual coherence (Gurevych et al. , 2003a; Porzel and Gurevych, 2003; Porzel et al. , 2003).
---------------------------------------------------
W04-2312:13	45:186	The knowledge-based approach employed herein (Gurevych et al. , 2003a) operates on an ontology partially derived from FrameNet data (Baker et al. , 1998) and described by Gurevych et al.
---------------------------------------------------
W04-2804:14	42:237	The interaction processing is based on M3L (Multimodal Markup Language), a complete XML language designed in the context of SMARTKOM that covers all data interfaces within the complex multimodal dialogue system (Gurevych et al. , 2003a).
---------------------------------------------------
W04-2804:15	194:237	Based on the domain we developed ends-based representations which have so far mostly been ontologies or ontology-like structures, e. g., (Gurevych et al. , 2003b) but which in fact could be event-based representations as well.
---------------------------------------------------
W03-2115:16	89:195	See also (Gurevych et al., 2003b) for a further de- scription of the ontology.
---------------------------------------------------
