Meteor , as well as several other proposed metrics such as GTM (Melamed et al., 2003), TER (Snover et al., 2006) and CDER (Leusch et al., 2006) aim to address some of these weaknesses. 
??GTM (Melamed et al. , 2003)?GTM generalizes precision, recall, and F-measure to measure overlap between strings, rather than overlap between bags of items. 
1 Introduction Over the last few years, several automatic metrics for machine translation (MT) evaluation have been introduced, largely to reduce the human cost of iterative system evaluation during the development cycle (Papineni et al. , 2002; Melamed et al. , 2003). 
Third, we computed the correspondence between each hypothesis sentence and each of its corresponding reference sentences using an approximation to maximum matching (Melamed et al. , 2003). 
Meteor, as well as several other proposed metrics such as GTM (Melamed et al. , 2003), TER (Snover et al. , 2006) and CDER (Leusch et al. , 2006) aim to address some of these weaknesses. 
