Support vector machines for semantic role chunking were first used This research was partially supported by the ARDA AQUAINT program via contract OCG4423B and by the NSF via grant IIS-9978025 in (Hacioglu and Ward, 2003) as word-by-word (W-byW) classifiers. 
In the W-by-W method (Hacioglu and Ward, 2003) the problem is formulated as a chunking task and the features are derived for each word (assuming part of speech tags and syntactic phrase chunks are available), and the word is classified into one of the semantic labels using an IOB2 representation. 
(2003); Hacioglu and Ward (2003); Thompson et al. 
Consequently, SVMs have been applied in many NLP tasks with great success (Joachims, 1998; Hacioglu & Ward, 2003). 
Here, we have illustrated that the Pby-P approach is a promising alternative to the recently proposed W-by-W approach (Hacioglu and Ward, 2003). 
