Availability SenseClusters is an open source software project that is freely distributed under the GNU Public License (GPL) via http://senseclusters.sourceforge.net/ SenseClusters is an ongoing project, and there are already a number of published papers based on its use (e.g. , (Purandare, 2003), (Purandare and Pedersen, 2004)).


(Schutze, 1998) points out that single link clustering tends to place all instances into a single elongated cluster, whereas (Pedersen and Bruce, 1997) and (Purandare, 2003) show that hierarchical agglomerative clustering using average link (via McQuittys method) fares well.


The second main trend, found in (Schtze, 1998), (Pedersen and Bruce, 1997) and (Purandare, 2003), represents each instance of a target word by a set of features that occur in its neighborhood and applies an unsupervised clustering algorithm to all its instances.


