Widdows (2003) uses a similar technique to insert words into the WORDNET hierarchy. 
This technique is similar to Hearst and Sch tze (1993) and Widdows (2003). 
The mathematical apparatus is covered in greater detail in (Widdows and Peters, 2003). 
It has been shown that local collocations and morphology of target word play important roles in word sense disambiguation or discrimination (Leacock et al. , 1998; Widdows, 2003). 
More details on the building of this vector space model can be found in (Widdows, 2003; Widdows and Peters, 2003). 
