In the two formal evaluations of definition questions that have been conducted at TREC (in 2003 and 2004), aninformationnuggetisoperationalizedasafactfor whichanassessorcouldmakeabinarydecisionasto whetheraresponsecontainedthatnugget(Voorhees, 2003b).


Since 1999, the NIST-organized question answering tracks at TREC (see, for example, Voorhees 2003a) have served as a focal point of research in the field, providing an annual forum for evaluating systems developed by teams from all over the world.


Using answer length as a proxy to precision appears to be a reasonable compromise because a pilot study demonstrated that it was impossible for humans to consistently enumerate the total number of nuggets in a response, a necessary step in calculating nugget precision (Voorhees, 2003b).


They are system-oriented rather than user-oriented, with a focus on evaluating techniques for answer extraction, rather than interaction and use (Voorhees, 2003).


