1Following (Kondrak et al. , 2003), we considered words of length 4 or more, we required the length ratio to be between 7 10 and 10 7, and we accepted as potential cognates all pairs forwhich the longest common subsequence ratio (LCSR) was 0.58 or more.


We used the method described in (Kondrak et al. , 2003) in order to extract cognates from the two data sets.


Previous research has shown that using cognates can yield better word alignments (AlOnaizan et al., 1999; Kondrak et al., 2003), which in turn often means higher-quality phrase pairs and better SMT systems.


Following (Al-Onaizan et al., 1999; Kondrak et al., 2003; Nakov et al., 2007) we filtered out the duplicates in C, and we added the remaining cognate pairs as additional sentence pairs to the bi-text in order to bias the subsequent training of the IBM word alignment models.


