This process is similar to the use of general pseudowords (Gale et al. , 1992b; Gaustad, 2001; Nakov and Hearst, 2003), but has some essential differences.


4 Methodology To date only Nakov and Hearst (2003) have looked into creating more plausible pseudowords.


Pseudowords should be plausible instances of the task (Gaustad, 2001; Nakov and Hearst, 2003): so it is deliberate that banana and wine share syntactic and semantic features, as senses of real ambiguous words often do.


With these pairs we are also following (Nakov and Hearst, 2003) who suggest that if one is introducing ambiguity by creating pseudowords or conflating names, then these words should be related in some way (in order to avoid the creation of very sharp or obvious sense distinctions).


