This is the model presented in (Tillmann and Xia, 2003). 
1 Introduction Possibly the most remarkable evolution of recent years in statistical machine translation is the step from word-based models to phrase-based models (Och et al. , 1999; Marcu and Wong, 2002; Yamada and Knight, 2002; Tillmann and Xia, 2003). 
We use a DP-based beam search procedure similar to the one presented in (Tillmann and Xia, 2003). 
In this paper, we present a phrase-based unigram system similar to the one in (Tillmann and Xia, 2003), which is extended by an unigram orientation model. 
Our baseline model is the unigram monotone model described in (Tillmann and Xia, 2003). 
