In recent work by Alshawi (2003) reported in this conference, new methods for unsupervised training of phone string recognizers have been developed, removing the need for word-level transcription.


The initial model used to start the iteration is, as in (Alshawi, 2003), an unweighted phone loop.


2 Unsupervised Phone Recognition Unsupervised recognition of phone sequences is carried out according to the method described by Alshawi (2003).


4 Experimental Setup The datasets tested on and the classifier used are the same as those in the experiments on phone sequence classification reported by Alshawi (2003).


