There are a large amount of published work (Morton, 2000; Soon et al. , 2001; Ng and Cardie, 2002; Yang et al. , 2003; Luo et al. , 2004; Kehler et al. , 2004) using machine-learning techniques in coreference resolution. 
However, Kehler et al. pointed out that this does not make the analysis more accurate (Kehler et al. , 2004). 
Due to the one-to-one entity alignment constraint, theF-measure here is more stringent than the accuracy (Ge et al. , 1998; Mitkov, 1998; Kehler et al. , 2004) computed on antecedent-pronoun pairs. 
1 Introduction The last years have seen a boost of work devoted to the development of machine learning based coreference resolution systems (Soon et al. , 2001; Ng & Cardie, 2002; Kehler et al. , 2004, inter alia). 
(2004), Kehler et al. 
