Recently, Pantel and Ravichandran (2004) extended this approach by making use of all syntactic dependency features for each noun. 
Pantel and Ravichandran (2004) have used a method that is not related to query expansion, but yet very related to our work. 
(Pantel and Ravichandran, 2004) have proposed an algorithm for labeling semantic classes, which can be viewed as a form of cluster. 
Weakly supervised corpus-based methods have utilized noun co-occurrence statistics (Riloff and Shepherd, 1997; Roark and Charniak, 1998), syntactic information (Widdows and Dorow, 2002; Phillips and Riloff, 2002; Pantel and Ravichandran, 2004; Tanev and Magnini, 2006), and lexico-syntactic contextual patterns (e.g., resides in <location> or moved to <location>) (Riloff and Jones, 1999; Thelen and Riloff, 2002). 
Recently, Pantel and Ravichandran (2004) extended this approach by making use of all syntactic dependency features for each noun. 
