N07-2019:1	9:73	Speaking style can vary greatly between speakers, and the discourse structure of multi-party interaction gives rise to crossspeaker effects that are difficult to model with standard N-gram models (Ji and Bilmes, 2004).
---------------------------------------------------
C04-1022:2	63:165	FLMs have been implemented as an add-on to the widely-used SRILM toolkit1 and have been used successfully for the purpose of morpheme-based language modeling (Bilmes and Kirchho, 2003), multi-speaker language modeling (Ji and Bilmes, 2004), and speech recognition (Kirchho et al. , 2003).
---------------------------------------------------
