4 Automatic Diacritization The performance of many natural language processing tasks, such as shallow parsing (Zhang et al. , 2002) and named entity recognition (Florian et al. , 2004), has been shown to depend on integrating many sources of information. 
473 and mention detection (Jing et al. , 2003; Florian et al. , 2004). 
In this case, we make use of the out-of-domain data by using features of the source domain taggers predictions in training and testing the target domain tagger (Florian et al. , 2004). 
Similar to the approaches described in (Florian et al., 2004) and (Zitouni et al., 2005), we decided to condition the output of the system on the segmented data: the text is segmented first into tokens and classification is then performed on tokens. 
These features were described in (Florian et al. , 2004), and are not discussed here. 
