In this work, we employ a syntax-based model that applies a series of tree/string (xRS) rules (Galley et al. , 2004; Graehl and Knight, 2004) to a source language string to produce a target language phrase structure tree. 
Such an algorithm is presented by Graehl and Knight (2004). 
Proposals include Eisners (2003) synchronous tree substitution grammar (STSG), Melameds (2004) multitext grammar, and Graehl and Knights (2004) tree-to-tree transducers. 
We therefore use the packed forest to store all the binarizations that operate on an e-parse in a compact way, and then use the inside-outside algorithm (Lari and Young, 1990; Knight and Graehl, 2004) for model estimation. 
The translation model we are using in this paper belongs to the xRs formalism (Knight and Graehl, 2004), which has been proved successful for machine translation in (Galley et al. , 2004; Galley et al. , 2006; Marcu et al. , 2006). 
