W08-1405:1	12:201	Uses of MDS systems vary widely, from summarisation of closed-domain documents, such as news documents (Evans et al., 2004), to aggregation of information from several sources in an open domain.
---------------------------------------------------
P06-1144:2	47:232	Columbias Newsblaster system (Kirk et al. , 2004) clusters news into events, it categorizes events into broad topic and summarizes multiple articles on each event.
---------------------------------------------------
