In order to ensure accuracy of the paraphrases, we use statistics gathered from the Web, using a variation of the approaches presented in Lapata and Keller (2004) and Nakov and Hearst (2005). 
4.2 Learning Models We have experimented with the support vector machines (SVM) model6 and compared the results against two state-of-the-art models: a supervised model, Semantic Scattering (SS), (Moldovan and Badulescu, 2005), and a web-based unsupervised model (Lapata and Keller, 2004). 
This is not surprising, given the previous results by Lapata and Keller (2004). 
Lapata and Keller (2004) rst used web-based co-occurrence counts for the bracketing of NCs. 
Lapata and Keller (2004) derive estimates from web counts, and only compare at a lexical level, achieving 78.7% accuracy. 
