In (Lin, 2004b), I argue that le is a reflex, rather than an overt realization of the underlying inchoative marker.


The following shows but a small range of possible resultative verb compounds with the dao3 fall result: (27) kan3 dao3 chop-fall to chop down zhuang4 dao3 crash-fall to knock over tui1 dao3 push-fall to push over la1 dao3 pull-fall to pull down In principle, verbal compound formation in Mandarin could be a lexical process, but I present elsewhere independent evidence for a non-lexicalist approach that captures these constraints in the theoretical framework of Distributed Morphology, an extension of Chomskys Minimalist Program (Lin, 2004a; Lin, 2004b).


Furthermore, this process is syntactic in nature (Lin, 2004b), governed by well-known syntactic processes such as MERGE (Chomsky, 1995) and subjected to well-studied constraints such as selectional restrictions and the Head Movement Constraint (Travis, 1984).


