The work that is most similar to ours is the recent research of (Huang et al. , 2004).


Some approaches combine lexical (phonetic and meaning) and semantic information to find corresponding translation of NEs in bilingual corpora (Feng et al. , 2004; Huang et al. , 2004; Lam et al. , 2004).


This idea is at the heart of several recent attempts to improve the handling of named entities in machine translation (Huang et al. , 2004; Lee and Chang, 2003).


The ability to find an optimal alignment between two sequences has found application in a number of areas of CL, including phonetic modeling (Ristad and Yianilos, 1998), name transcription (Huang et al. , 2004), and duplicate detection or information integration (Bilenko and Mooney, 2003; McCallum et al. , 2005).


 Models constructed from bilingual dictionaries of terms and names, e.g., (Knight and Graehl, 1998; Huang et al., 2004; Haizhou et al., 2004; Zelenko and Aone, 2006; Yoon et al., 2007; Li et al., 2007; Karimi et al., 2007; Sherif and Kondrak, 2007b; Goldwasser and Roth, 2008b).


