This is the same tokenization scheme used in the Arabic Treebank (Maamouri et al. , 2004). 
The POS tag set used is the reduced Arabic Treebank tag set (24 tags) (Maamouri et al. , 2004; Diab et al. , 2004). 
In (Lee et al. , 2003), (Diab et al. , 2004) and (Habash and Rambow, 2005) three supervised segmentation methods are introduced. 
, Daya et al. , 2004, who modeled interdigitation in Hebrew). 
Details can be found in (Daelemans et al. , 2004). 
