Recently, much research attention has been paid to aligning sentences in comparable documents (Utiyama et al 2003, Munteanu et al 2004).


2 Recent Approaches to Mining Non-parallel Corpora Recent work (Fung and Cheung 2004 [9]; Munteanu et al. 2004 [10]; Zhao and Vogel 2002 [11]) on extracting bi-sentences from comparable corpora is largely based on finding on-topic documents first through similarity matching and time alignment.


Among the applications of Model 1 are segmenting long sentences into subsentental units for improved word alignment (Nevado et al. , 2003), extracting parallel sentences from comparable corpora (Munteanu et al. , 2004), bilingual sentence alignment (Moore, 2002), aligning syntactictree fragments (Ding et al. , 2003), and estimating phrase translation probabilities (Venugopal et al. , 2003).


