4 Baseline Speech Recognition System The CLT uses the SONIC speech recognition system as a basis for providing real-time recognition of childrens speech (Pellom, 2001; Pellom and Hacioglu, 2003; Hagen et al. 2004) 4 . The recognizer implements an efficient timesynchronous, beam-pruned Viterbi token-passing search through a static re-entrant lexical prefix tree while utilizing continuous density mixture Gaussian Hidden Markov Models (HMMs).


