Certainly, prosodic cues are useful for sentence segmentation (Liu et al. , 2004), and the quality of automatic segmentation can have a significant impact on parser performance (Kahn et al. , 2004). 
They have subsequently presented an improved model for detecting edits (Johnson et al. , 2004), and our results here complement their analysis of the edit detection and parsing relationship, particularly with respect to the limitations of PCFGs in edit detection. 
Alternatively, it could be that including a representation of prosodic features as terminals in (Gregory et al. , 2004) displaces words in the parser n-gram model history. 
The strengths of these simple tree-based techniques should be combinable with sophisticated string-based (Johnson and Charniak, 2004; Liu, 2004; Zhang and Weng, 2005) approaches by applying the methods of Wieling et al. 
the impact of automatic segmentation is addressed in other work (Kahn et al. , 2004). 
