Initial work in (Levow, 2004) has shown that Mandarin words at story ending positions show a lower pitch as compared with words at non-story-ending positions.


Other prosodic cues (e.g. , pitch contour, energy) have been studied for their correlation with story segments in read speech (Tur et al. , 2001; Levow, 2004; Christensen et al. , 2005) and with theory-based discourse segments in spontaneous speech (e.g. , directiongiven monologue) (Hirschberg and Nakatani, 1996).


(Levow, 2004).


(Levow, 2004).


