But we are not sure whether N-Best approach (Zhai et al. , 2004) would be helpful. 
Extract new Chinese name entities (Zhai et al 2004); 2. 
Since then NBest methods have been widely used by other researchers (Collins, 2002; Zhai et al. , 2004). 
The Chinese name entities are extracted with the system described in (Zhai et al 2004). 
In order to deal with ASR errors two approaches have been proposed:  modeling explicitly the ASR errors, thanks to a development corpus and a set of confidence measures, in order to detect the possible errors of the 1-best word string hypothesis (with the type of errors) before extracting the NEs (Palmer and Ostendorf, 2001);  exploiting a search space bigger than the 1-best hypothesis alone, either by taking into account an n-best list (Zhai et al. , 2004) or the whole word lattice (Saraclar and Sproat, 2004). 
