Our review of the methods of chemical named entity recognition showed a consistent theme: the use of character-based n-Grams to identify chemical names via their constituent substrings (Wilbur et al., 1999; Vasserman, 2004; Townsend et al., 2005).


A few chemical named entity recognition (Corbett and Murray-Rust, 2006; Townsend et al. , 2005; Vasserman, 2004; Kemp and Lynch, 1998; Sun et al. , 2007) or classification (Wilbur et al. , 1999) systems have been published.


The usefulness of character-based a0 -grams has also been demonstrated elsewhere (Wilbur et al. , 1999; Vasserman, 2004; Townsend et al. , 2005).


