N07-1055:1	6:190	1 Introduction Models of coherent discourse are central to several tasks in natural language processing: such models have been used in text generation (Kibble and Power, 2004) and evaluation of human-produced text in educational applications (Miltsakaki and Kukich, 2004; Higgins et al. , 2004).
---------------------------------------------------
D08-1020:2	128:230	5Similar features have been used for automatic essay grading as well (Higgins et al., 2004).
---------------------------------------------------
P07-1046:3	233:259	Average (standard deviation) for objective metrics in the first problem 6 Related work Discourse structure has been successfully used in non-interactive settings (e.g. understanding specific lexical and prosodic phenomena (Hirschberg and Nakatani, 1996), natural language generation (Hovy, 1993), essay scoring (Higgins et al. , 2004) as well as in interactive settings (e.g. predictive/generative models of postural shifts (Cassell et al. , 2001), generation/interpretation of anaphoric expressions (Allen et al. , 2001), performance modeling (Rotaru and Litman, 2006)).
---------------------------------------------------
E09-1065:4	11:200	(Higgins et al., 2004)), and the assessment of short student answers (e.g., (Leacock and Chodorow, 2003; Pulman and Sukkarieh, 2005)), which is the focus of this paper.
---------------------------------------------------
W06-1611:5	13:230	The discourse structure hierarchy has been shown to be useful for other tasks: understanding specific lexical and prosodic phenomena (Hirschberg and Nakatani, 1996; Levow, 2004), natural language generation (Hovy, 1993), predictive/generative models of postural shifts (Cassell et al. , 2001), and essay scoring (Higgins et al. , 2004).
---------------------------------------------------
W08-0911:6	139:183	(2) She told me that a little white lie will come back to haunt me. Secondly, it is well known that there are aspects of textual coherence such as topic continuity and rhetorical structure which are not captured in counts of words and sentences (e.g., (Higgins et al., 2004), (Miltsakaki and Kukich, 2004)) Thirdly, readability formulas do not take into account the profile of the reader.
---------------------------------------------------
