Across these conditions, the parser training was held constant, but the test segmentation varied across three cases: (i) oracle, hand-labeled SU segmentation; (ii) automatic, SU segmentation from the automatic detection system using both prosody and lexical cues (Kim et al. , 2004); and (iii) nave, SU segmentation from a decision tree predictor using only pause duration cues.


2.2 SU and IP Detection The system used here for SU and IP detection is (Kim et al. , 2004), modulo differences in training data.


Experiments in both (Shriberg et al. , 2000) and (Kim et al. , 2004) find no conclusive winner among early fusion, additive late fusion, and multiplicative late fusion.


Prosody has been shown to improve performance on several NLP problems, such as topic and sentence segmentation (e.g. , (Shriberg et al. , 2000; Kim et al. , 2004)).


