Consider an example summary of a thread of email conversation produced by a sentence extraction based email thread summarization system developed at Columbia (Rambow et al. , 2004) shown in Figure 1. 
In (Nenkova and Bagga, 2003; Wan and McKeown, 2004; Rambow et al., 2004), email summaries were organized by extracting overview sentences as discussion issues. 
(Rambow et al. , 2004) show that sentence extraction techniques can work for summarizing email threads, but pro t from email-speci c features. 
In (Nenkova and Bagga, 2003; Wan and McKeown, 2004; Rambow et al., 2004), email summaries were organized by extracting overview sentences as discussion issues. 
2 Related Work Rambow et al. proposed a sentence extraction summarization approach for email threads (Rambow et al., 2004). 
