A perceptronlike algorithm that handles global features in the context of re-ranking is also presented in (Shen et al. , 2004). 
The second approach is to use reranking, in which a baseline classifier generates an n-best list of candidate translations, and a separate discriminative classifier chooses amongst them (Shen et al. , 2004; Och et al. , 2004). 
4 Related Work Various methods are used to optimize log-linear models in re-ranking (Shen et al., 2004; Venugopal et al., 2005; Smith and Eisner, 2006). 
(Och et al. , 2004) and (Shen et al. , 2004) describe the use of syntactic features in reranking the output of a full translation system, but the syntactic features give very small gains. 
Our modified training procedure is related to the discriminative re-ranking procedure presented in (Shen et al. , 2004). 
