P08-1016:1	90:268	He obtained similar results (Rytting, 2004) using phrase-final 3-phone sequences.
---------------------------------------------------
W04-0110:2	59:202	However, Rytting (2004) showed that this extra context, while certainly helpful, is not strictly necessary in the Greek corpus under question.
---------------------------------------------------
W04-0110:3	15:202	Previous research (Rytting, 2004) examined the role of utterance-boundary information in Modern Greek, implementing a variant of Aslin and colleagues (1996) model within a finite-state framework.
---------------------------------------------------
W04-0110:4	189:202	Previous research (Rytting, 2004) examined the role of utterance-final information in Greek, and found that this cue performs better than chance on its own.
---------------------------------------------------
