This has proved to be useful in several tasks, from verb classification (Chow and Webster, 2007) to semantic role labeling (Giuglea and Moschitti, 2006), open text semantic parsing (Shi and Mihalcea, 2004) and textual entailment (Burchardt and Frank, 2006).


Their mapping was used to develop a rulebased semantic parser (Shi and Mihalcea, 2004) as well as to detect target words and assign frames for verbs in an open text (Honnibal and Hawker, 2005).


Gildea and Jurafsky (Gildea and Jurafsky, 2002) describe a statistical approach for semantic role labelling using data collected from FrameNet by analysing a number of features such as phrase type, grammatical function, position in the sentence, etc. Shi and Mihalcea (Shi and Mihalcea, 2004) propose a rule-based approach for semantic parsing using FrameNet and WordNet.


