] is expected to have greater technological familiarity (Precoda et al. , 2004, 9) or that the medical care-giver will maintain the initiative in the dialogue, will have sole access to the controls and display of the translation device, and will operate the 1We give here one indicative reference for each system.


(2004:10) For translation output, some form of paraphrase or back-translation is offered, often facilitated by the Figure 4: Choice of recognizer outputs, from Precoda et al.


Systems that have been developed so far can be divided into those for use in the doctors office  notably, MedSLT (Rayner and Bouillon, 2002), CCLINC (Lee et al. , 2002), and (honourable mention) the early work done at CMU (Tomita et al. , 1988)1  and those for use for first contact with medical professionals in the field, developed under DARPAs CAST programme:2 MASTOR (Zhou et al. , 2004), Speechalator (Waibel et al. , 2003), Transonics (Narayanan et al. , 2004) and SRIs system (Precoda et al. , 2004).


