C04-1135:1	10:222	In a similar attempt, Shinzato and Torisawa proposed an automatic method to obtain a common hypernym of expressions in the same itemizations in HTML documents (Shinzato and Torisawa, 2004) by using statistical measures such as document frequencies and inverse document frequencies.
---------------------------------------------------
C04-1135:2	3:222	Our method is obtained by extending Shinzatos method (Shinzato and Torisawa, 2004) where a common hypernym for expressions in itemizations in HTML documents is obtained by using statistical measures.
---------------------------------------------------
P08-1047:3	12:254	For example, we can use automatically extracted hyponymy relations (Hearst, 1992; Shinzato and Torisawa, 2004), or automatically induced MN clusters (Rooth et al., 1999; Torisawa, 2001).
---------------------------------------------------
P05-1016:4	12:208	Ontologizing semantic resources Recently, researchers have applied textand web-mining algorithms for automatically creating lexical semantic resources like similarity lists (Lin 1998), semantic lexicons (Riloff and Shepherd 1997), hyponymy lists (Shinzato and Torisawa 2004; Pantel and Ravichandran 2004), partwhole lists (Girgu et al. 2003), and verb relation graphs (Chklovski and Pantel 2004).
---------------------------------------------------
J05-3004:5	594:629	The Webbased algorithms could similarly benefit from the exploration of different patterns and their combination, as well as from using non-pattern-based approaches for hyponymy detection (Shinzato and Torisawa 2004).
---------------------------------------------------
P09-1052:6	226:246	Second, there are pattern-based approaches in the literature which only do limited integration of RASCs (Shinzato and Torisawa, 2004; Shinzato and Torisawa, 2005; Pasca, 2004), as discussed in the introduction section.
---------------------------------------------------
P09-1052:7	8:246	1 Introduction Semantic class construction (Lin and Pantel, 2001; Pantel and Lin, 2002; Pasca, 2004; Shinzato and Torisawa, 2005; Ohshima et al., 2006) tries to discover the peer or sibling relationship among terms or phrases by organizing them into semantic classes.
---------------------------------------------------
C08-1024:8	46:189	Thus, we also use verb-noun dependencies as evidence in learning (Pantel and Ravichandran, 2004; Shinzato and Torisawa, 2004).
---------------------------------------------------
P06-2075:9	44:205	and/or Y, where X and Y are extracted as hyponyms of Z. Similar techniques were further applied to predict hyponymy and meronymy relationships using lexical or lexico-syntactic patterns (Berland and Charniak, 1999; Sundblad, 2002), and web page structure was exploited to extract hyponymy relationships by Shinzato and Torisawa (2004).
---------------------------------------------------
I08-2126:10	15:187	To reduce these costs, many methods have been proposed for automatically building thesauri (Hearst, 1992; Etzioni et al., 2005; Shinzato and Torisawa, 2004; Pantel and Pennacchiotti, 2006).
---------------------------------------------------
