3.5 Minimum Bayes risk decoding Although during minimum error training we assume a decoder that uses the maximum derivation decision rule, we find benefits to translating using a minimum risk decision rule on a test set (Kumar and Byrne, 2004). 
We then rescore the first 1000-best hypotheses with MBR, taking the negative sentence level BLEU score as the loss function to minimise (Kumar and Byrne, 2004). 
This list is then rescored using Minimum Bayes-Risk (MBR) decoding (Kumar and Byrne, 2004). 
In the area of statistical machine translation (SMT), recently a combination of the BLEU evaluation metric (Papineni et al. , 2001) and the bootstrap method for statistical significance testing (Efron and Tibshirani, 1993) has become popular (Och, 2003; Kumar and Byrne, 2004; Koehn, 2004b; Zhang et al. , 2004). 
2.1 Minimum Bayes Risk Decoding MinimumBayesriskdecodingwasproposedbyKumarandByrne(2004). 
