Active learning (e.g. Chen et al., 2006) is one approach to this problem. 
The previous techniques (Chan and Ng, 2007; Chen et al. 2006) require balanced positive and negative examples to estimate the score. 
has been widely studied in natural language processing (NLP) applications, such as word sense disambiguation (WSD) (Chen et al., 2006; Zhu and Hovy, 2007), text classification (TC) (Lewis and Gale, 1994; McCallum and Nigam, 1998a), named entity recognition (Shen et al., 2004), chunking (Ngai and Yarowsky, 2000), and statistical parsing (Tang et al., 2002). 
This is slightly higher than the 5.8 senses per verb in (Chen et al. , 2006), where the experiments were conducted using coarse-grained evaluation. 
The high scores here were foreshadowed in an evaluation involving a subset of the data last summer (Chen et al. , 2006). 
