For any projection of a grammar, we give a new method for efficiently estimating the projections parameters from the source PCFG itself (rather than a treebank), using techniques for infinite tree distributions (Corazza and Satta, 2006) and iterated fixpoint equations. 
The proofs of the general case are given in Corazza and Satta (2006), but the resulting procedure is quite intuitive. 
3.2.1 Estimating Projected Grammars Fortunately, there is a well worked-out notion of estimating a grammar from an infinite distribution over trees (Corazza and Satta, 2006). 
A full proof appears in (Corazza and Satta, 2006). 
Corazza and Satta (2006) extend these methods to the case of PCFGs and tree distributions. 
