W08-1406:1	32:135	Feature-based methods combine several types of features: current work uses lexical, acoustic/prosodic, structural, and discourse features to summarize documents from domains like broadcast news or meetings (Maskey and Hirschberg, 2005; Murray et al., 2006; Ribeiro and de Matos, 2007).
---------------------------------------------------
W08-1406:2	14:135	However, if on the one hand, recognition errors seem not to have a considerable impact on the summarization task (Murray et al., 2006; Murray et al., 2005), on the other hand, spoken language summarization systems often explore ways of minimizing that impact (Zechner and Waibel, 2000; Hori et al., 2003; Kikuchi et al., 2003).
---------------------------------------------------
P08-1054:3	69:176	(2005; 2006), in spite of the fact that Murray et al.
---------------------------------------------------
P08-1054:4	68:176	Interestingly, the interannotator agreement on SWITCHBOARD (a0a2a1 a3a5a4a7a6a9a8a9a6 ) is higher than on the lecture corpus (0.372) and higher than the a0 -score reported by Galley (2006) for the ICSI meeting data used by Murray et al.
---------------------------------------------------
P08-1054:5	20:176	In the years following this work, however, some research by others on speech summarization (Maskey and Hirschberg, 2005; Murray et al., 2005; Murray et al., 2006, inter alia) has focussed de rigueur on striving for and measuring the improvements attainable over the transcribe-thensummarize baseline with features available from non-transcriptional sources (e.g., pitch and energy of the acoustic signal) or those, while evident in textual transcripts, not germane to texts other than spoken language transcripts (e.g., speaker changes or question-answer pair boundaries).
---------------------------------------------------
D08-1081:6	105:213	(Maskey and Hirschberg, 2005; Murray et al., 2005a; Galley, 2006)).
---------------------------------------------------
D08-1081:7	83:213	3.3.1 Evaluating Meeting Summaries To evaluate meeting summaries we use the weighted f-measure metric (Murray et al., 2006).
---------------------------------------------------
