The citation processor developped in our group (Ritchie et al. , 2006) achieves high accuracy for this task (96% of citations recognized, provided the reference list was error-free).


Citation context has been explored in several studies (Nakov et al., 2004; Ritchie et al., 2006; Schwartz et al., 2007; Siddharthan and Teufel, 2007).


We are currently performing an experiment to see if citation processing can increase performance in a large-scale, real-world information retrieval task, by creating a test collection of researchers queries and relevant documents for these (Ritchie et al. , 2006a).


A more sophisticated, discourse-aware citation indexer which nds these sentences and associates them with the citation would add considerable value to the researchers bibliographic search (Ritchie et al. , 2006b).


