Previous work (Forbes-Riley and Litman, 2006) has suc88 cessfully used student learning as the performance metric in the PARADISE framework. 
The performance of our best model is comparable or higher than training performances reported in previous work (Forbes-Riley and Litman, 2006; Mller, 2005b; Walker et al. , 2001). 
Finally, similar to (Forbes-Riley and Litman, 2006), we are tackling a more problematic performance metric: the student learning gain. 
Also, previous studies have shown that tutoring specific parameters can improve the quality of SDS performance models that model the learning gain (Forbes-Riley and Litman, 2006). 
We also want to see if our results hold for performance metrics based on user satisfaction questionnaires; in the new ITSPOKE corpus we are currently annotating, each student also completed a user satisfaction survey (Forbes-Riley and Litman, 2006) similar to the one used in the DARPA Communicator multi-site evaluation (Walker et al. , 2002). 
