74 3 Semantic Relations Although verb nominalization is commonly considered to have arguments as the verb predicate, Xue(2006) finds that there tend to be fewer arguments and fewer types of adjuncts in verb nominalizations compared to verb predicates in Chinese. 
Chinese NomBank Chinese NomBank (Xue, 2006a) adopts similar semantic framework as NomBank, and focuses on Chinese nominal predicates with their arguments in Chinese TreeBank. 
However, Xue (2006b) found that simply adding the training instances for verbal SRL to the training data for nominal SRL and indiscriminately extracting the same features in both verbal and nominal SRLs hurt the performance. 
Finally, the predicate-argument structure of nominal predicates is more flexible and complicated than that of verbal predicates as illustrated in Xue (2006a). 
(Xue, 2006) uses the Chinese Nombank to label nominalizations in Chinese. 
