Semantic features are used for classifying entities into semantic types such as name of person, organization, or place, while syntactic features characterize the kinds of dependency 5It is worth noting that the present approach can be recast into one based on constraint relaxation (Tromble and Eisner, 2006).


1As do constraint relaxation (Tromble and Eisner, 2006) and forest reranking (Huang, 2008).


