Phrase-based rules have also been replaced with synchronous context free grammars (Chiang, 2005) and with tree fragments (Huang and Knight, 2006).


(Huang and Knight, 2006) and (Hassan et al., 2007) introduce relabeling and supertagging on the target side, respectively.


(Huang and Knight, 2006) also reported similar result by using sisterhood annotation on the target side.


Huang and Knight (2006) explored relabeling of nonterminal symbols to embed more information directly into the backbone of the grammar.


More recently, there is a significant effort focusing on integrating richer knowledge, such as syntactic parse trees (Huang and Knight, 2006) within the translation process to overcome the limitations of the phrase based models.


