Also, we have not attempted to replicate here the machine learning approaches described in (Ahn et al., 2005) and (Ahn et al., 2007), nor Hans use of constraint satisfaction problem methods (see (Han et al., 2006a)).


In example (5), the correct PP attachment is required in order to determine that Monday is in the 1In the literature, a variety of different terms are used: (Schilder and Habel, 2001) call these expressions indexicals, and (Han et al., 2006b) uses the term relative for what we call anaphoric references: in our terminology, both deictic and anaphorical expressions are relative.


