Moschitti (2006b) proposed a partial tree kernel which can partially match subtrees. 
It is worthy of note that in (Moschitti, 2006b) a sorting based method is proposed for the fast implementation of such tree kernels that reduces the average running time to )( 21 NNO + .  The generalized kernel can be converted to CD01 kernel by defining =)(ninw  and 1)( =nenw . Likewise, other definitions can be utilized to produce other useful sub-kernels. 
3.2 Fast Grammar-driven Convolution Tree Kernel II (FGTK-II) Our FGTK-II algorithm is motivated by the partial trees (PTs) kernel (Moschitti, 2006). 
Please note that the average  in natural language parse trees is very small and the overall complexity of the FGTKs can be further reduced by avoiding the computation of node pairs with different labels (Moschitti, 2006). 
Moschitti (2006) proposes a partial tree (PT) kernel which can carry out partial matching between sub-trees. 
