word type or wtp represents features of a word such as capitalization, the existence of digits, and punctuation as shown in (Sutton et al., 2006) without regular expressions.


However, without corresponding records for texts the model does not perform well as an extractor because it haslearnedtorelyontheDBrecordandalignment features (Sutton et al., 2006).


Examples of word type include whether the word is capitalized, contains digit or contains punctuation, which basically follows the baseline features of (Sutton et al. , 2006) without regular expressions.


