P09-1104:1	167:219	6.1 French Hansards Results The French Hansards data are well-studied data sets for discriminative word alignment (Taskar et al., 2005; Cherry and Lin, 2006; Lacoste-Julien et al., 2006).
---------------------------------------------------
J07-3002:2	162:164	F-Measure with an appropriate setting of  will be useful during the development process of new alignment models, or as a maximization criterion for discriminative training of alignment models (Cherry and Lin 2003; Ayan, Dorr, and Monz 2005; Ittycheriah and Roukos 2005; Liu, Liu, and Lin 2005; Fraser and Marcu 2006; Lacoste-Julien et al. 2006; Moore, Yih, and Bode 2006).
---------------------------------------------------
W09-1804:3	144:163	Alignment in the modified model of (Lacoste-Julien et al., 2006) can be mapped to a quadratic assignment problem and solved with linear programming tools.
---------------------------------------------------
D07-1089:4	68:343	Recently, several authors have described discriminative SMT alignment models (Moore, 2005; Lacoste-Julien et al. , 2006; Blunsom and Cohn, 2006).
---------------------------------------------------
D07-1006:5	175:193	(Lacoste-Julien et al. , 2006) created a discriminative model able to model 1-to-1, 1-to2 and 2-to-1 alignments for which the best results were obtained using features based on symmetric HMMs trained to agree, (Liang et al. , 2006), and intersected Model 4.
---------------------------------------------------
D07-1006:6	178:193	(Moore et al. , 2006) introduced a discriminative model of 1-to-N and M-to-1 alignments, and similarly to (Lacoste-Julien et al. , 2006) the best results were obtained using HMMs trained to agree and intersected Model 4.
---------------------------------------------------
W07-0407:7	28:217	(Lacoste-Julien et al. , 2006) extend the above approach to include features for fertility and first-order correlation between alignment links of consecutive words in the source sentence.
---------------------------------------------------
P09-1039:8	7:228	1 Introduction Much attention has recently been devoted to integer linear programming (ILP) formulations of NLP problems, with interesting results in applications like semantic role labeling (Roth and Yih, 2005; Punyakanok et al., 2004), dependency parsing (Riedel and Clarke, 2006), word alignment for machine translation (Lacoste-Julien et al., 2006), summarization (Clarke and Lapata, 2008), and coreference resolution (Denis and Baldridge, 2007), among others.
---------------------------------------------------
W08-0303:9	17:239	In recent years several authors (Moore et al., 2006; Lacoste-Julien et al., 2006; Blunsom and Cohn, 2006) proposed discriminative word alignment frameworks and showed that this leads to improved alignment quality.
---------------------------------------------------
P06-1065:10	175:192	(Lacoste-Julien et al. , 2006).
---------------------------------------------------
