Another extension would try to reorder not words but phrases, following (Xiong et al., 2006), or segment choice models (Kuhn et al., 2006), which assume a single segmentation of the words into phrases. 
Recently, a number of data-driven distortion models, based on lexical features and relative distance, have been proposed to compensate for this weakness (Tillman, 2004; Koehn et al., 2005; AlOnaizan and Papineni, 2006; Kuhn et al., 2006). 
Many state-of-the-art SMT systems do not use trees and base the ordering decisions on surface phrases (Och and Ney, 2004; Al-Onaizan and Papineni, 2006; Kuhn et al. , 2006). 
2.2 Feature-Rich DT-based distortion In a recent paper (Kuhn et al, 2006), we presented a newclassofprobabilisticSegmentChoiceModels (SCMs) for distortion in phrase-based systems. 
Note that the experiments reported in (Kuhn et al, 2006) focused on translation of Chinese into English. 
