After this procedure, when combining  4 For the detail, please refer to (Zhang et al., 2006a). 
If the confidence of a character is lower than the threshold, the tag of that character will be adjusted to the tag assigned by the Maximum Probability Segmentation (R. Zhang et al., 2006). 
In this paper,  = 0.8 and t = 0.7 (Parameters in two papers, Zhang et al. 2006a and Zhang et al. 2006b, are different. 
We show in this section that there is a representation flaw in the formula of confidence measure in (Zhang et al., 2006a). 
After we get word-based segmentation result, we use it to revise the CRF tagging result similar to (Zhang et al., 2006). 
