Recent NLP problems addressed by clustering include POS induction (Clark, 2003; Goldwater and Griffiths, 2007), word sense disambiguation (Shin and Choi, 2004), semantic role labeling (Baldewein et al., 2004), pitch accent type disambiguation (Levow, 2006) and grammar induction (Klein, 2005).


1 Introduction Clustering techniques have been used successfully for many natural language processing tasks, such as document clustering (Willett, 1988; Zamir and Etzioni, 1998; Cutting et al. , 1992; Vempala and Wang, 2005), word sense disambiguation (Shin and Choi, 2004), semantic role labeling (Baldewein et al. , 2004), pitch accent type disambiguation (Levow, 2006).


Similarly, Levow (2006) tried clustering based unsupervised approach on accent detection with only acoustic evidence and reported accuracy of 78.4% for accent detection compared with 80.1% using supervised learning.


