Liu (2006) combined a generative HMM approach with the conditional maximum entropy method to detect speaker roles in Mandarin BN, reporting a classification accuracy of 81.97% against the baseline of around 50%.


Previous work in this line includes speaker role detection (e.g. , Liu, 2006; Maskey and Hirschberg, 2006) and speaker diarization (e.g. , Canseco et al. , 2005).


In Maskey and Hirschberg (2006), the task is to recognize soundbites (which make up of a large portion of the other role category in Liu (2006)).


