D08-1091:1	93:223	In the present work, we exploit L1-regularization, though other techniques such as structural zeros (Mohri and Roark, 2006) could also potentially be used.
---------------------------------------------------
C08-5001:2	218:227	Applications of this algorithm include k-best parsing (McDonald et al., 2005; Mohri and Roark, 2006) and machine translation (Chiang, 2007).
---------------------------------------------------
N07-1051:3	48:232	It is interesting to note that these grammars capture many of the structural zeros described by Mohri and Roark (2006) and pruning rules with probability below e10 reduces the grammar size drastically without influencing parsing performance.
---------------------------------------------------
