(Ayan and Dorr, 2006) defined a discriminative model which learns how to combine the predictions of several alignment algorithms.


However, Ayan and Dorr (2006a) showed that a loose heuristic, allowing unaligned words at the phrase edges, improved accuracy by 3.7 BLEU with some alignments, again with much less training data.


We replace these with the maximum entropy aligments of Ayan and Dorr (2006b).


There has been recent work by Ayan and Dorr (2006) on combining word alignments from different alignment systems; this paper describes a maximumentropyframeworkforthiscombination.


