WordNet synonyms To maximize the number of matches between a translation and a reference, Kauchak and Barzilay (2006) use WordNet synonyms during evaluation. 
The efficacy of this approach has been well-established in many areas, including automated evaluation of machine translation systems (Kauchak and Barzilay, 2006), text summarization (Kittredge, 2002), question answering (Rinaldi et al. , 2003), document retrieval (Zukerman and Raskutti, 2002), and many others. 
Kauchak and Barzilay (2006) and Owczarzak et al. 
Kauchak and Barzilay (2006) used paraphrases of the reference translations to improve automatic MT evaluation. 
Deriving lexical relatedness between terms has been a topic of interest with applications in word sense disambiguation (Patwardhan et al., 2005), paraphrasing (Kauchak and Barzilay, 2006), question answering (Prager et al., 2001), and machine translation (Blatz et al., 2004) to name a few. 
