5 Experimental Setup 5.1 Evaluation Method Fact-based evaluation systems have been used in several past projects (Lin and Demner-Fushman, 2006; Marton and Radul, 2006), especially in the TREC question answering track.


(Lin and Demner-Fushman, 2006) use stemmed unigram similarity of responses with nugget descriptions to produce the evaluation results, whereas (Marton and Radul, 2006) uses both human judgments and human descriptions to evaluate a response.


Nuggeteer (Marton and Radul, 2006).


Similarly, in question-answering (QA) evaluations, gold-standard answers use manually created nuggets and compare them against system-produced answers broken down into n-gram pieces, as shown in POURPRE (Lin and Demner-Fushman, 2005) and NUGGETEER (Marton and Radul, 2006).


