UCDL is our method, KR06 is described in (Klementiev and Roth, 2006b) and GR08 in (Goldwasser and Roth, 2008b). 
5 Open Issues in NE pair Mining In this paper, we outline our experience in mining parallel NEs between English and Tamil, in an approach similar to the one discussed in [Klementiev and Roth, 2006]. 
This decision model is essentially equivalent to the transliteration models used in (Klementiev and Roth, 2006a; Goldwasser and Roth, 2008), in which a linear transliteration model was trained using a feature extraction method equivalent to AF. 
In the following section, we also improve on Klementiev and Roth (2006) by using a character-based string alignment to focus the features for discrimination. 
One system that can potentially provide this exibility is a discriminative string-similarity approach to named-entity transliteration by Klementiev and Roth (2006). 
