2 Data We employ a subset of the Boston Radio News Corpus (Ostendorf et al., 1995), employing data from speakers f1a, f2b, m1b, and m2b, for experimental consistency with (Chen et al., 2004; Rangarajan Sridhar et al., 2007).


(Chen et al., 2004; Rangarajan Sridhar et al., 2007) explored the integration of based prosodic and lexico-syntactic evidence in GMM-based and maximum entropy models respectively.


On this split, the best word-based accuracy incorporating both prosodic and lexico-syntactic information in a maximum entropy framework is 86.0% for binary pitch accent prediction and 93.1% for 220 recognition of boundary status (Rangarajan Sridhar et al., 2007).


4.2 Text-based Features We employ text-based models similar to those employed by (Sun, 2002; Rangarajan Sridhar et al., 2007).


There has been substantial progress in automatic pitch accent recognition for native speech, achieving accuracies above 80% for acousticfeature based recognition in multi-speaker corpora (Sridhar et al., 2007; Levow, 2008).


