Prior work on assessing reading level includes (Heilman et al., 2007) who experiment with a system that employs grammatical features and vocabulary to predict readability. 
Further recent refinements in methods for readability prediction include using machine learning methods such as Support Vector Machines (Schwarm and Ostendorf, 2005), log-linear models (Heilman et al., 2008), k-NN classifiers and combining semantic and grammatical features (Heilman et al., 2007). 
More complex measures (such as the presence of some syntactic structures (Heilman et al., 2007) or the characteristics of a syntactic-parsing tree) have been explored in the literature. 
(Heilman et al., 2007) experiment with a system for evaluation of reading difficulty which employs both grammatical features and vocabulary. 
(Heilman et al., 2007) find that while the vocabulary model alone outperformed the grammarbased model, the combined model performed best. 
