We have trained the DT with all the vectors of the word occurrences that we had in the different gold-standards, using their encoding for the supervised experiment in a 10-fold cross-validation testing (Bel et al. 2007).


As for the application of LMF to a particular domain, (Quochi et al., 2007) describes a large-scal</context> </contexts> <marker>Francopoulo, George, Calzolari, Monachini, Bel, Pet, Soria, 2006</marker> <rawString>Gil Francopoulo, Monte George, Nicoletta Calzolari, Monica Monachini, Nuria Bel, Mandy Pet, and Claudia Soria.


As for the application of LMF to a particular domain, (Quochi et al., 2007) describes a large-scal</context> </contexts> <marker>Francopoulo, George, Calzolari, Monachini, Bel, Pet, Soria, 2006</marker> <rawString>Gil Francopoulo, Monte George, Nicoletta Calzolari, Monica Monachini, Nuria Bel, Mandy Pet, and Claudia Soria.


