Notethattomakeourexperimentalresultsdirectly comparable to Wong and Mooney (2007), we used the identical training and test data splits for the 4 runs of 10-fold cross validation used by Wong and Mooney (2007) on both corpora. 
We also compare the tree CRFbased model against the previous state-of-the-art model of Wong and Mooney (2007). 
A third strategy is to use an example-based approach (Wong and Mooney, 2007; Stone, 2003; Varges and Mellish, 2001) in which the connection 77 between available application semantic representations and desired output utterances is specified by example. 
The BLEU and NIST scores of the WASP1++ system reported in this section are obtained from the published paper of Wong and Mooney (2007). 
4.2 Tree CRF-Based Model Based on the belief that using known phrases usually leads to better fluency in the NLG task (Wong and Mooney, 2007), we explore methods for generating an NL sentence at phrase level rather than at word level. 
