2.2.4 Compression Using Lexicalized Markov Grammars The last sentence compression method we use is the lexicalized Markov grammar-based approach (Galley and McKeown, 2007) with edit word detection (Charniak and Johnson, 2001). 
Many explicitly rely on a language model, usually a trigram model, to produce grammatical output (Knight & Marcu, 2002; Hori & Furui, 2004; Turner & Charniak, 2005; Galley & McKeown, 2007). 
Modifications of this model are reported in Turner and Charniak (2005) and Galley and McKeown (2007) with improved results. 
(Galley and McKeown, 2007) extended the noisy-channel approach and proposed a head-driven Markovization formulation of synchronous contextfree grammar (SCFG) deletion rules. 
25 2 Related Work Many existing compression systems use a noisychannel approach and rely on a language model to test the grammaticality of the output (Knight & Marcu, 2002; Turner & Charniak, 2005; Galley & McKeown, 2007). 
