Table 3 shows the results achieved by our method and other researchers (UAS with p), where Wang05 refers to (Wang et al., 2005), Wang07 refers 92 to (Wang et al., 2007), and McDonald&Pereira06 5 refers to (McDonald and Pereira, 2006).


We used the same rules for conversion and created the same data split as (Wang et al., 2007): files 1-270 and 400-931 as training, 271-300 as testing and files 301-325 as development.


30  40  50  60  70  80  90  100  0  5  10  15  20 F1 Dependency Length baseline OURS Figure 5: Improvement relative to dependency length 5 (Wang, 2007) reported this result.


