An existing framework which was originally developed for English (Ko et al. , 2007) was extended for Chinese and Japanese answer ranking by incorporating language-specific features.


In our previous work, we evaluated the performance of the framework for English QA using questions from past TREC evaluations (Ko et al. , 2007).


The source code of the answer extractors is included in OpenEphyra, an open source release of the system.2 The answer candidates from these extractors are combined and ranked by a statistical answer selection framework (Ko et al., 2007), which estimates the probability of an answer based on a number of answer validation and similarity features.


