The annotation guidelines for marking rationales are described in (Zaidan et al., 2007). 
The length of an example has often been substituted for the annotation cost (Kapoor et al., 2007; Tomanek et al., 2007). 
A rationale (Zaidan et al., 2007) is the span of text a user highlights in support of his/her annotation. 
Additionally, there has been recent work using explanation-based learning techniques to encode a more expressive feature space (Lim et al., 2007). 
In addition to voting positive or negative for a review, annotators also annotated rationales (Zaidan et al., 2007), spans of text in the review that support their vote. 
