Also, we have not attempted to replicate here the machine learning approaches described in (Ahn et al., 2005) and (Ahn et al., 2007), nor Hans use of constraint satisfaction problem methods (see (Han et al., 2006a)).


Approach F1 (detection) F1 (exact match) Ahn et al., 2005 0.914 0.798 Hacioglu et al., 2005 0.935 0.878 Poveda et al., 2007 0.986 0.757  Table 1.


Performance of Machine Learning Approaches with B-I-O Encoding  Constituent-based classification approach for temporal expression recognition was presented in (Ahn et al., 2007).


Machine learning recognition systems: Successful machine learning TIMEX recognition systems are described in (Ahn et al., 2005; Hacioglu et al., 2005; Poveda et al., 2007).


As reported in (Ahn et al., 2007) a precise recognition of temporal expressions is a prerequisite for accurate normalization.


