Various statistical User Simulations have been trained on corpora of dialogue data in order to simulate real user behaviour (Schatzmann et al., 2006; Young, 2006; Georgila et al., 2006; Young et al., 2007; Schatzmann et al., 2007). 
In this study, we build a simulated user similar to (Schatzmann et al., 2007) in which the simulated user keeps a list of its goals and another agenda of actions to complete the goals. 
2 Related work Several statistical user simulation models that model a users behaviour in a conversation have been proposed (Georgila et al., 2005; Schatzmann et al., 2006; Schatzmann et al., 2007). 
More recent research defines agenda for simulated users to complete a set of settled goals (Schatzmann et al., 2007). 
(Schatzmann et al., 2007) propose to bootstrap with a simulated user which is entirely hand-crafted. 
