Like previous Icelandic work (Loftsson, 2007), morphological analyzers disambiguate words before statistical tagging in Arabic (Habash and Rambow, 2005) and Czech (Hajic and Hladk, 1998).


While our tagger could be combined withtheselinguisticresourcesaswell,asinLoftsson (2007), weshowstateoftheartperformancewithout these resources.


Given these challenges, the most successful tagger is IceTagger (Loftsson, 2007), a linguistic rule based system with several linguistic resources: a morphological analyzer, a series of local rules and heuristics for handling PPs, verbs, and forcing agreement.


