This approach, called Morfessor Baseline is described in detail in (Creutz et al. , 2007). 
Then, for translation, Moses (Koehn et al., 2007) is trained on words and morphemes (derived from Morfessor Baseline(CreutzandLagus,2005)). 
These items would then be of more use when trying to predict unseen data(Creutz et al. , 2007). 
This is verified by recent empirical results, where gains obtained from simple morphological decomposition seem to be marginal(Kirchhoff et al. , 2006; Creutz et al. , 2007). 
Since morpheme segmentation is at least somewhat helpful in speech recognition (Creutz, 2006; Creutz et al., 2007), it should still be considered a potential component in speech-to-speech translation. 
