It can be recovered in the future by including the domain specific knowledge in the dynamic configuration of the Interpretation and Generation managers as suggested by Paulo Pardal (2007) An example of this process is the splitting of the parser specific code into several parsers: some domain-dependent, some domainindependent, while creating a mechanism to combine them in a configurable chain (through a pipes and filters architecture).


Namely, if they can be used to abstract knowledge sources allowing the system to focus only on dialogue phenomena rather than architecture adaptation, when including new domains (Paulo Pardal, 2007).


