C08-1086:1	34:180	One commonly used approach is to define a measure of novelty/semantic similarity between documents and to apply heuristics to reduce the relevance score of a result item (a hit) by a function of the similarity of this item to other results in the list (Carbonell and Goldstein 1998; Zhu et al. 2007).
---------------------------------------------------
E09-2002:2	28:107	(Zhu et al., 2007), assuming that redundancy should be the concept on what is based multi-document summarization, offered a method to deal with redundancy at the 5 same time as sentence selection.
---------------------------------------------------
