As Wikipedia also models relatedness between concepts, it is better suited for computing 5http://www.taz.de semantic relatedness than GermaNet (Zesch et al. , 2007b). 
For the evaluation, we use the Pearson (r) and Spearman () correlation coefficients, which are the standard metrics used in the past for the evaluation of semantic relatedness (Finkelstein et 1196 al., 2001; Zesch et al., 2008; Gabrilovich and Markovitch, 2007). 
Wikipedia shares many of its properties with other well known lexical semantic resources (like dictionaries, thesauri, semantic wordnets or conventional encyclopedias) (Zesch et al. , 2007a). 
The dataset is available only in English and has been widely used in previous semantic relatedness evaluations (e.g., (Resnik, 1995; Hughes and Ramage, 2007; Zesch et al., 2008)). 
Further research (Zesch et al. , 2007b) indicates that German wordnet and Wikipedia show different performance depending on the task at hand. 
