2.2 Revision Parser: DeSRrevisionrighttoleft Our second individual parsing model implements an alternative to the method of revising parse trees of Attardi and Ciaramita (2007) (see also (Hall & Novak, 2005)).


Attardi and Ciaramita proposed a method of tree revision learning for dependency parsing (Attardi and Ciaramita, 2007).


We then used a parsing revision technique (Attardi and Ciaramita, 2007) to learn how to correct these errors, producing a parse reviser called DesrReviser.


More details on such aspects of the DeSR parser can be found in (Ciaramita and Attardi 2007).


Attardi and Ciaramita (2007) showed that 80% of the corrections can be typically dealt with just 20 tree revision rules.


