Threeand five-dimensional EM-based clustering has been applied to monolingual phonological data (Muller et al. , 2000) and two-dimensional clustering to syntax (Rooth et al. , 1999).


Although some work has been done on syllabifying orthographic forms (Muller et al., 2000; Bouma, 2002; Marchand and Damper, 2007; Bartlett et al., 2008), syllables are, technically speaking, phonological entities that can only be composed of strings of phonemes.


