W03-0703:1	41:126	The most commonly used paradigm is that of Markov decision processes and partially observable Markov decision processes, where the entire dialog is modelled as a sequence of states and associated actions, each of which has a certain value (or reward) (Singh et al. , 1999; Roy et al. , 2000).
---------------------------------------------------
N01-1028:2	172:189	There has also been new research on how to model the dialogue with partially observable Markov models (Roy et al. , 2000).
---------------------------------------------------
W09-1503:3	65:190	Systems have been restricted to very simple domains (Roy et al., 2000; Zhang et al., 2001) and only recently have techniques been developed that show promise for use in real-world systems (Williams and Young, 2007; Gasic et al., 2008).
---------------------------------------------------
W08-0119:4	13:192	Hence, practical examples of their use were initially restricted to very simple domains (Roy et al., 2000; Zhang et al., 2001).
---------------------------------------------------
P09-1010:5	34:228	Reinforcement Learning for Language Processing Reinforcement learning has been previously applied to the problem of dialogue management (Scheffler and Young, 2002; Roy et al., 2000; Litman et al., 2000; Singh et al., 1999).
---------------------------------------------------
