W02-0503:1	15:217	Anne Roeck and Waleed Al-Fares (2000) developed a clustering algorithm for Arabic words sharing the same verbal root.
---------------------------------------------------
W06-1648:2	64:207	DeRoeck introduced a clustering technique tolerant of Arabics complex morphology (De Roeck and Al-Fares, 2000).
---------------------------------------------------
W05-0708:3	192:204	Other clustering algorithms (e.g. root-based clustering of Arabic (De Roeck and 61 Al-Fares, 2000)), may be used instead of, or in addition to, distribution-based clustering.
---------------------------------------------------
