A lot of research has been done on text segmentation (Kozima, 1993; Hearst, 1994; Okumura and Honda, 1994; Salton et al. , 1996; Yaari, 1997; Kan et al. , 1998; Choi, 2000; Nakao, 2000).


If a text segmentation system divides a given text into a relatively small number of segments, then a summary of the original text can be composed by combining summaries of the component segments (Kan et al. , 1998; Nakao, 2000).


Identifying and isolating topics by dividing documents, which is called text segmentation, is important for many natural language processing tasks, including information retrieval (Hearst and Plaunt, 1993; Salton et al. , 1996) and summarization (Kan et al. , 1998; Nakao, 2000).


