chart parsing (Tesar and Smolensky, 2000; Kuhn, 2000) and finite state OT (see Biro (2006b) for an overview)?require conditions met by several, but not by all linguistic models.


(Kuhn, 2000) excludes the application of such recursions by a similar condition as offline parsability (which excludes vacuous recursions over a string in parsing), but with the a1a3a2 construction, this condition is not necessary for decidability of the generation-based optimization task.


For computational OT syntax, an interleaving of candidate generation and constraint checking has been proposed (Kuhn, 2000).


3 OT-LFG Following (Bresnan, 2000; Kuhn, 2000; Kuhn, 2001), we define a restricted OT system based on Lexical-Functional Grammar (LFG) representations: c(ategory) structure/f(unctional) structure 2Most computational OT work so far focuses on candidates and constraints expressible as regular languages/rational relations, based on (Frank and Satta, 1998) (e.g. , (Eisner, 1997; Karttunen, 1998; Gerdemann and van Noord, 2000)).


