They do not indicate a preference for brief descriptions, a finding that echoes Jordans (2000), to the effect that speakers often relinquish brevity in favour of observing task or discourse constraints.


In corpus-based studies, it has been shown that logically redundant properties tend to be included when they fulfill one of a number of pragmatic functions, such as to indicate that a property is of particular importance to the speaker, or to highlight the speakers awareness that the referent has the property in question (Jordan 2000).


