Pantel, P. and D. Lin (2000) An unsupervised approach to prepositional phrase attachment using contextually similar words. 
Pantel and Lin (2000) obtained very good results using the distributional similarity measure defined by Lin (1998). 
Other approaches supplement this information with hand-built or automatically acquired lexical resources and collocation databases to determine the relationship between the lexemes, or, for lexemes unattested in the tuples, for semantically similar ones (Stetina and Nagao, 1997; Pantel and Lin, 2000). 
These kinds of errors on prepositional phrase attachment in MINIPAR were also mentioned in (Pantel and Lin, 2000). 
Pantel and Lin (2000) increased the training corpus, added a collocation database and a thesaurus which improved the accuracy to 84%. 
