2Jordan and Walker (2000) have demonstrated a significantly better match to the human data when task-related constraints are taken into account.


Someofthisworkismainlyorexclusively experimental (Jordan and Walker, 2000; Arts, 2004), but algorithmic consequences are also being explored (Horacek, 2005; Paraboni and van Deemter, 2002; van der Sluis and Krahmer, 2005).


Jordan and Walker (2000); Krahmer and Theune (2002)).


