Auxiliary verb presence and choice: My teacher does is a good teacher (my teacher is)  1 Liu et al. 2000 take a similar approach, retrieving example sentences from a large corpus.


Some researchers have begun to apply statistical techniques to identify learner errors in the context of essay evaluation (Chodorow & Leacock, 2000; Lonsdale & Strong-Krause, 2003), to detect non-native text (Tomokiyo & Jones, 2001), and to support lexical selection by ESL learners through first-language translation (Liu et al. , 2000).


