9 Mark Hepple, Independence and commitment: assumptions for rapid training and execution of rule-based POS taggers, Proceedings of the 38th Annual Meeting on Association for Computational Linguistics, p.278-277, October 03-06, 2000, Hong Kong 10 Kilgarriff (1997) Kilgarriff, A. , Foreground and background lexicons and word sense disambiguation for information extraction.


To determine the Part-of-Speech tags, the tagger described by (Hepple, 2000) is used.


