To convert Pinyin P to Chinese characters H, Chen and Lee (2000) used Bayes law to maximize Pr(H|P), in which a LM Pr(H) and a typing model Pr(P|H) are included.


And like the model in Pinyin IME (Chen and Lee, 2000), we also try to use a Hanja LM Pr(T), to measure the probabilities of hypothesized Hanja and/or Hangeul sequences.


Our experiment also shows that, compare to using only LM like it in Chen & Lee (2000), TM shows significantly better result in character accuracy (from 81.0% to 91.4% in our experiment: DU0 a18 DU1, table 4).


The character accuracy is lower than the typing and language model based Chinese Pinyin IME, which was 95% in Chen & Lee (2000).


So we assume the user input is perfect, and employ a transfer model instead of the typing model in Chen and Lee (2000).


