Following the empirical study in (Gao and Lee, 2000), we use K-Mixture (Katz, 1996) which estimate P i (k) as k ki kP ) 1 ( 1 )1()( 0, ++ +=     , (6) where  k,0 =1 if k=0, 0 otherwise.


Gao and Lee (2000) proposed a distributionbased pruning.


As Gao and Lee (2000) observed, even purported matched training data may exhibit topic, style, or temporal biases not present in the test set.


Following Gao and Lee (2000), we use K-Mixture (Katz 1996) which estimates P i (k)as P i (k) = (1  a) k,0 + a + 1 (  + 1 ) k, (15) where  k,0 =1 if k=0; 0, otherwise.


