More recently, other researchers (Garcia 1997), (Khoo et al. 2000) used linguistic patterns to identify explicit causation relations in text without any knowledge-based inference.


Other authors (Khoo et al. 2000) restricted their text corpus to a medical/business database and used hand-coded causation patterns that were mostly unambiguous.


2 Previous Work Although systems that can answer why-questions are emerging, they tend to have limitations in that they can answer questions only with causal verbs (Girju, 2003), in specific domains (Khoo et al., 418 2000), or questions covered by a specific knowledge base (Curtis et al., 2005).


