Finally, our work is also related to research on title generation (Banko et al. , 2000; Jin and Hauptmann, 2001; Dorr et al. , 2003). 
In the context of headline generation, simple statistical models are used for aligning documents and headlines (Banko, Mittal, and Witbrock 2000; Berger and Mittal 2000; Schwartz, Zajic, and Dorr 2002), based on IBM Model 1 (Brown et al. 1993). 
Previous studies on text-to-text abstracting (Banko et al., 2000; Knight and Marcu, 2000) have studied problems such as sentence compression and sentence combination but not the pasting procedure presented here. 
This task has been extensively studied over the last six years (Banko et al. , 2000; Jin and Hauptmann, 2001). 
Our method for estimation of selection-andordering preferences is based on the technique described in (Banko et al. , 2000). 
