Every account in which bridging references are addressed restricts allowable relationships to a small, relatively well-defined set (Vieira and Poesio 2001; Poesio et al. 2000; Murata, Isahara, and Nagao 1999; Strube and Hahn 1999).


The GNOME corpus has been used to study salience, particularly as formalized in Centering theory (Poesio et al. , 2004c), to develop statistical models of natural language generation (e.g. , (Poesio, 2000a; Henschel et al. , 2000; Cheng et al. , 2001; Cheng, 2001; Karamanis, 2003)) and to evaluate anaphora resolution systems, with a special focus on the resolution of bridging references (Poesio, 2003; Poesio and Alexandrov-Kabadjov, 2004; Poesio et al. , 2004b).


The scheme has served as the basis for a number of annotation projects, such as the development of the GNOME corpus (Poesio, 2000a) and, more recently, of the VENEX corpus of anaphora in Italian spoken dialogue and text (Poesio et al. , 2004a).


