2 Gildea and Jurafsky (2000) use 36995 training, 4000 development, and 3865 test sentences. 
Many researchers ((Blaheta and Charniak 2000), (Gildea and Jurafsky 2000), showed that lexical and syntactic information is very useful for predicateargument recognition tasks, such as semantic roles. 
The bulk of this recent work views semantic analysis as a tagging, or labeling problem, and has applied various supervised machine learning techniques to it (Gildea and Jurafsky (2000, 2002); Gildea and Palmer (2002); Surdeanu et al. 
Gildea and Jurafsky (2000) describe a system that uses completely syntactic features to classify the Frame Elements in a sentence. 
4 Selecting features Many researchers ((Blaheta-Charniak, 2000), (Gildea-Jurafsky, 2000), (Gildea-Palmer, 2002)) showed that lexical and syntactic information is very useful for predicate-argument recognition tasks. 
