7 Related Work 7.1 Unification Grammar Compilation Compilation of unification grammars to speech recognition grammars is well described in the literature (Moore, 1999; Dowding et al. , 2001).


We note, however, that these numbers differ from those presented in (Dowding et al. , 2001).


(Dowding et al. , 2001) compared (Moore, 1999)s approach to grammar approximation to (Kiefer and Krieger, 2000).


