5 Related work Previous work has proposed a large number of interaction parameters for SDS performance modeling (Mller, 2005a; Walker et al. , 2000; Walker et al. , 2001). 
1 Introduction Recent research on dialogue is based on the assumption that dialogue acts provide a useful way of characterizing dialogue behaviors in both humanhuman (HH) and human-computer (HC) dialogue (Isard and Carletta, 1995; Shriberg et al. , 2000; Di Eugenio et al. , 1998; Cattoni et al. , 2001). 
In order to label the HH corpus of 1062 utterances, we started with 10 dialogues (305 utterances) labelled with the CSTAR dialogue act tagging scheme (Finke et al. , 1998; Doran et al. , 2001). 
We use 2 user simulations learned from COMMUNICATOR data (Walker et al. , 2001; Georgila et al. , 2005b) to explore the effects of different features on learned dialogue strategies. 
This correlation methodology is commonly used in the tutoring research (Chi et al. , 2001). 
