1Brent (1999) originally described the novel word score as R(wk) = 6pi2  nkk  P(Wnk) 1nk1nk  summationtextnk j=1 P(Wj)  parenleftBig nk1 nk parenrightBig2 , where P is the probability of all the phonemes in the word occurring together, but the denominator of the third term was dropped in Brent and Tao (2001).


R(wk) = f(wk)k  parenleftbiggf(w k)1 f(wk) parenrightbigg2 (2) Otherwise, the word is novel, and its score is calculated using Equation 31 (Brent and Tao, 2001), R(wk) = 6 pi2  n k  P(a1)P(aq) 1P(#)  parenleftBign1 n parenrightBig2 (3) where P is the probability of a particular phoneme occurring in the text.


