This is inspired by the work (Corston-Oliver et al. , 2001) showing that function word density can be effective in distinguishing between human references and machine outputs. 
Lexical Collocation (LC) Lexical collocation error (Yukio et al. , 2001; Gui and Yang, 2003) is common in the writing of ESL learners, such as strong tea but not powerful tea. Our LSP features cannot capture all LCs since we replace some words with POS tags in mining LSPs. 
By far, the most widely used metric in recent literature is BLEU (Papineni et al., 2001). 
As for classi cation, one line of research in MT evaluation is to evaluate the uency of an output sentence without its reference translations, such as in (Corston-Oliver et al. , 2001) and (Gamon et al. , 2005). 
We adapt the frequent sequence mining algorithm in (Pei et al. , 2001) for mining LSPs with constraints. 
