(Ingrid Zukerman and Eric Horvitz, 2001) used decision tree to model and recognize the information need, question and answer coverage, topic, focus and restrictions of a question.


Recently, some pioneering studies have investigated approaches to automatically construct QA components from scratch by applying machine learning techniques to training data (Ittycheriah et al. , 2001a)(Ittycheriah et al. , 2001b)(Ng et al. , 2001) (Pasca and Harabagiu)(Suzuki et al. , 2002)(Suzuki 215 Table 1: Number of Questions in Question Types of CRL QA Data # of Questions # of Question Types Example 1-9 74 AWARD, CRIME, OFFENSE 10-50 32 PERCENT, N PRODUCT, YEAR PERIOD 51-100 6 COUNTRY, COMPANY, GROUP 100-300 3 PERSON, DATE, MONEY Total 115 et al. , 2003) (Zukerman and Horvitz, 2001)(Sasaki et al. , 2004).


