and Roth, 2000; Banko and Brill, 2001). 
With respect to the effect of corpus size on NLP tasks, Banko and Brill (2001a) showed that for content sensitive spelling correction, increasing the training data size improved the accuracy. 
Banko and Brill, (2001) also found this trend for the task of confusion set disambiguation on corpora of up to one billion words. 
Banko and Brill (2001) suggested that the development of very large training corpora may be most effective for progress in empirical natural language processing. 
Banko and Brill (2001) report on confusion set disambiguation experiments where they apply relatively simple learning methods to a one billion word training corpus. 
