W01-0801:1	28:33	Since this is crucial, increased attention needs to be paid to evaluation in generation (Bangalore et al. , 2000; Rambow et al. , 2001).
---------------------------------------------------
P04-1011:2	216:218	Previous work on SPoT also compared trainable sentence planning to a template-based generator that had previously been developed for the same application (Rambow et al. , 2001).
---------------------------------------------------
P08-1020:3	168:192	4 Conclusion We present a new method for generating linguistic variation projecting multiple personality traits continuously, by combining and extending previous research in statistical natural language generation (Paiva and Evans, 2005; Rambow et al., 2001; Isard et al., 2006; Mairesse and Walker, 2007).
---------------------------------------------------
P08-1020:4	181:192	There is only one other similar evaluation of an SNLG (Rambow et al., 2001).
---------------------------------------------------
P08-1020:5	12:192	Another thread investigates SNLG scoring models trained using higher-level linguistic features to replicate human judgments of utterance quality (Rambow et al., 2001; Nakatsu and White, 2006; Stent and Guo, 2005).
---------------------------------------------------
