The distribution is based on a seven-model model for the generation of hypothesis, which is heavily based upon the probability model presented in Snover and Brent (2001), with steps 1-3 of the generative procedure being the same. 
Several researchers (Brent, 1993; Brent et al. , 1995; Goldsmith, 2001) used Minimum Description Length (MDL) for morphology learning. 
Often the limiting assumption is made that words consist of only one stem followed by one (possibly empty) suffix (Dejean, 1998; Snover and Brent, 2001; Snover et al. , 2002). 
Lastly, and most importantly, all of the reviewed techniques (Wicentowski, 2004; Wicentowski, 2002; Snover et al. , 2002; Baroni et al. , 2002; Andreev, 1965; Cavar et al. , 2004; Snover and Brent, 2003; Snover and Brent, 2001; Snover, 2002; Schone and Jurafsky, 2001; Jacquemin, 1997; Goldsmith and Hu, 2004; Sharmaetal. 
Snover and Brent (2001) proposed a generative probability model to identify stems and suffixes. 
