The first one deals with identifying and extracting biographical sentences and treats the problem as a summarization task (Cowie et al., 2000, Schiffman et al., 2001, Zhou et al., 2004).


Biography generation is an exciting field that has attracted practitioners of NLG in the past (Kim et al. , 2002; Schiffman et al. , 2001; Radev and McKeown, 1997; Teich and Bateman, 1994).


Miles Davis birth day May 26(5), May 25(5) birth year 1926(82), 1967(18), 1969(9) occupation trumpeter(38), artist(10), player(5) birth place Alton(7), Illinois(6) Joerg Haider birth year 1950(6) occupation leader(198) politician(93) chairman(6) birth place Austria(1) Table 1: Extracted Biographical Information from 1000 Web Pages Another topic of recent interest is in producing biographical summaries from corpora (Schiffman et al. , 2001).


