Recent research [Yamamoto et al. , 2001] shows that using different clusters for predicted and conditional words can lead to cluster models that are superior to classical cluster models, which use the same clusters for both words [Brown et al. , 1992].


Although similar models have been used in previous studies [Goodman and Gao, 2000; Yamamoto et al. , 2001], several issues have not been completely investigated.


More recently, a method for clustering words at different positions was developed (Yamamoto et al. , 2001; Gao et al. , 2002).


