(Gardent and Thater, 2001).


In this section, we relate it to chart generation (Kay, 1996; Carroll et al. , 1999) and to another constraint-based approach (Gardent and Thater, 2001).


Gardent and Thater (2001) also propose a constraint based approach to generation working with a variant of TAG.


Working with derived trees, Gardent and Thater (2001) cannot ignore any information and have to keep track of the relationships between nodes at points where they are not relevant.


