A closely related line of research is on the automatic classication of discourse elements to assess the quality of a written genre (Burstein et al., 2001).


Thus, our focus is on the physics content and not the quality of the students writing, in contrast to (Burstein et al. , 2001).


 Previous research has shown that RST trees can play a crucial role in building natural language generation systems (Hovy, 1993; Moore and Paris, 1993; Moore, 1995) and text summarization systems (Marcu, 2000); can be used to increase the naturalness of machine translation outputs (Marcu et al. 2000); and can be used to build essayscoring systems that provide students with discourse-based feedback (Burstein et al. , 2001).


