P02-1056:1	175:178	There exists only very little other work that considers integration of shallow and deep NLP using an XMLbased architecture, most notably (Grover and Lascarides, 2001).
---------------------------------------------------
W02-1706:2	95:166	Space considerations preclude discussion of this topic here but see Grover and Lascarides (2001) for further details.
---------------------------------------------------
P03-1014:3	8:209	With the advent of XML-based hybrid shallowdeep architectures as presented in (Grover and Lascarides, 2001; Crysmann et al. , 2002; Uszkoreit, 2002) it has become possible to integrate the added value of deep processing with the performance and robustness of shallow processing.
---------------------------------------------------
P03-1014:4	11:209	While integration in (Grover and Lascarides, 2001) was still restricted to morphological and PoS information, (Crysmann et al. , 2002) extended shallow-deep integration at the lexical level to lexico-semantic information, and named entity expressions, including multiword expressions.
---------------------------------------------------
C02-1071:5	77:125	,1995;;MusicandNavarretta,1996;; Mitsuishi et al. , 1998;; Groverand Lascarides,2001).
---------------------------------------------------
C02-1071:6	10:125	Thesystemwepresentisinspiredby(Abney, 1992)andit is in accordancewith (Srinivas et al. ,1997;;CiravegnaandLavelli,1997;;Yoonet al. ,1999;;Venkova,2000;;Watanabe,2000;;Prins andNoord,2001;;GroverandLascarides,2001;; Crysmannetal.
---------------------------------------------------
