We use Charniaks parser (Charniak, 2001) to parse the example sentence. 
2 The Immediate-Head Parsing Model The language model we use is described in (Charniak, 2001). 
1 Introduction Much of the current research into probabilistic parsing is founded on probabilistic contextfree grammars (PCFGs) (Collins, 1996; Charniak, 1997; Collins, 1999; Charniak, 2000; Charniak, 2001; Klein and Manning, 2003). 
We use Charniaks parser (Charniak, 2001) to parse the example sentence. 
We use two language models here: a bigram language model, which is used in the search process, and a syntactic parser-based language model Charniak (2001), which is used to rescore a set of the most likely analysis obtained using the bigram model. 
