Alternatively, systems that need to generate texts with rich layout might prefer to interleave document structuring with rhetorical structuring (e.g. , Cahill et al. 2001).


In the RAGS reference architecture for NLG (Mellish et al. 2000; Cahill et al. 2001), document structure is distinguished from rhetorical structure as a data type, with no commitment as to when these two data structures are created during the generation process.


In all but a few recent cases (the ICONOCLAST system (Power 2000; Bouayad-Agha, Power, and Scott 2000; Bouayad-Agha, Scott, and Power 2001; Bouayad-Agha 2001) and the DArt bio system (Bateman et al. 2001)), this is achieved by mapping directly from the underlying discourse structure (Arens and  Information Technology Research Institute, University of Brighton, Lewes Road, Brighton BN2 4GJ, UK.


The module is re-used from the Riches system (Cahill et al. , 2001) and it generates either a definite description or a pronoun.


