Similar to our approach, Electric Knowledge transforms a natural language question into a series of increasingly more general keyword queries (Bierner, 2001).


Consider other NPs (Bierner 2001a; Bierner and Webber 2000; Modjeska 2001, 2002), as in: (26) Sue grabbed one phone, as Tom darted to the other phone.


556 Computational Linguistics Volume 29, Number 4 NPs with no postmodifying than phrase (example (30)), and the pronoun elsewhere (example (31)) (Bierner 2001b) (28) Some dogs are constantly on the move.


For a computational treatment of other-NPs with structural antecedents, see Bierner (2001).


For a computational treatment of other with structural antecedents see (Bierner, 2001).


