The approach we take is similar to Schmid and Rooths (2001) adaptation of the algorithm, where expected governors (similar to our GR specifications) are determined for each tree, and alternative nodes in the parse forest have the same lexical head.


Similar dynamic programming techniques that are variants of the IOA have been applied for related tasks, such as parse selection (Johnson, 2001; Schmid and Rooth, 2001; Geman and Johnson, 2002; Miyao and Tsujii, 2002; Kaplan et al. , 2004; Taskar et al. , 2004).


Recently, Schmid and Rooth (2001) have described an algorithm for computing expected governor labels for terminal words in labelled headed parse trees produced by a probabilistic context-free grammar.


Schmid, H. and M. Rooth (2001) Parse forest computation of expected governors.


