For these experiments we use the JACCARD (1) measure and the TTEST (2) weight, as Curran and Moens (2002a) found them to have the best performance in their comparison of many distance measures. 
Recent work has replicated their work on thesaurus extraction (Curran and Moens, 2002) and is-a relation extraction (Ravichandran et al. , 2004), showing that collecting data over a very large corpus significantly improves system performance. 
Curran and Moens (2002) found that increasing the volume of input data increased the accuracy of results generated using a full vector space model. 
Our previous work (Curran and Moens, 2002) has evaluated thesaurus extraction performance and ef ciency using several different context models. 
Curran and Moens (2002a) propose an initial heuristic comparison to reduce the number of full O(m) vector comparisons. 
