A Homogeneous Data Model Since the late 1990s, practically all corpus annotation formats have been realised as XML markup languages (Ide et al., 2000; Sperberg-McQueen and Burnard, 2002; Lehmberg and Wrner, 2007).


A Homogeneous Data Model Since the late 1990s, practically all corpus annotation formats have been realised as XML markup languages (Ide et al., 2000; Sperberg-McQueen and Burnard, 2002; Lehmberg and Wrner, 2007).


