W07-1527:1	14:168	Currently, the best-performing English NP interpretation methods in computational linguistics focus mostly on two consecutive noun instances (noun compounds) and are either (weakly) supervised, knowledge-intensive (Rosario and Hearst, 2001), (Rosario et al. , 2002), (Moldovan et al. , 2004), (Pantel and Pennacchiotti, 2006), (Pennacchiotti and Pantel, 2006), (Kim and Baldwin, 2006), (Snow et al. , 2006), (Girju et al. , 2005; Girju et al. , 2006), or use statistical models on large collections of unlabeled data (Berland and Charniak, 1999), (Lapata and Keller, 2004), (Nakov and Hearst, 2005), (Turney, 2006).
---------------------------------------------------
W06-3813:2	37:195	Such systems extract information from some types of syntactic units (clauses in (Fillmore and Atkins, 1998; Gildea and Jurafsky, 2002; Hull and Gomez, 1996); noun phrases in (Hull and Gomez, 1996; Rosario et al. , 2002)).
---------------------------------------------------
P06-2021:3	23:167	Section 6 compares our algorithm for compound disambiguation with one recently presented alternative, Rosario et al.s (2002) rule-based system for the disambiguation of noun-noun compounds.
---------------------------------------------------
P06-2021:4	134:167	6.1 Rule-based disambiguation algorithm Rosario et al.s (2002) general approach to nounnoun compound disambiguation is based, as ours is, on the semantic categories of the nouns making up a compound.
---------------------------------------------------
W04-2609:5	23:193	Other researchers have identified other sets of semantic relations (Levi 1979), (Vanderwende 1994), (Sowa 1994), (Baker, Fillmore, and Lowe 1998), (Rosario and Hearst 2001), (Kingsbury, et al. 2002), (Blaheta and Charniak 2000), (Gildea and Jurafsky 2002), (Gildea and Palmer 2002).
---------------------------------------------------
