Chieu and Ng used global information such as the occurrence of the same word with other capitalisation in the same document (Chieu and Ng, 2002a), and have also used a mixed-case classifier to teach a weaker classifier that did not use case information at all (Chieu and Ng, 2002b).


Research on case insensitive text has so far been restricted to NE and the feature exclusion approach [Chieu & Ng 2002] [Kubala et al. 1998] [Palmer et al. 2000] [Robinson et al. 1999].


(Chieu and Ng, 2002) attempted to extract named entities from non-cased text by using a weaker classifier but without focusing on regular text or case restoration.


