W04-1910:1	96:186	This idea was followed by (Hwa et al. , 2002) who investigated English to Chinese projections based on the direct correspondence assumption.
---------------------------------------------------
W06-2008:2	8:175	One possible option to enrich resource-poor languages consists in taking advantage of resourcerich/resource-poorlanguagealignedcorporatoinduce linguistic information for the resource-poor side from the resource-rich side (Yarowski et al. , 2001; Borin, 2002; Hwa et al. , 2002).
---------------------------------------------------
W06-2008:3	30:175	3 Projectingmorpho-syntactic annotations Wetakeasthestartingpointofannotationprojection the direct correspondence assumption as formulated in (Hwa et al. , 2002): fortwo sentences in parallel translation, the syntactic relationships in one language directly map the syntactic relationships in the other, and extend it to POS tags as well.
---------------------------------------------------
W08-0409:4	68:167	Given cJ1, eI1 and their syntactic dependency trees TcJ 1 , TeI 1 , if ei is aligned to cj and ei aligned to cj, according to the dependency correspondence assumption (Hwa et al., 2002), there exists a triple <cj,Rc,cj>.
---------------------------------------------------
H05-2007:5	21:47	2 Part-of-Speech Sequence Recall In developing a new analysis method, we are motivated in part by recent studies suggesting that word reorderings follow general patterns with respect to syntax, although there remains a high degree of flexibility (Fox, 2002; Hwa et al. , 2002).
---------------------------------------------------
H05-1107:6	18:248	Previous research on resource projection attempts to address these problems by redistributing the parameter values (Yarowsky and Ngai, 2001) or by applying transformation rules (Hwa et al. , 851 2002).
---------------------------------------------------
P04-1083:7	162:203	This kind of synchronizer stands in contrast to more ad-hoc approaches (e.g. , Matsumoto, 1993; Meyers, 1996; Wu, 1998; Hwa et al. , 2002).
---------------------------------------------------
H05-1098:8	8:140	The need for some way to model aspects of syntactic behavior, such as the tendency of constituents to move together as a unit, is widely recognizedthe role of syntactic units is well attested in recent systematic studies of translation (Fox, 2002; Hwa et al. , 2002; Koehn and Knight, 2003), and their absence in phrase-based models is quite evident when looking at MT system output.
---------------------------------------------------
H05-1098:9	85:140	782 5.1 A New Analysis Method In developing a new analysis method, we are motivated in part by recent studies suggesting that word reorderings follow general patterns with respect to syntax, although there remains a high degree of flexibility (Fox, 2002; Hwa et al. , 2002).
---------------------------------------------------
N07-1057:10	21:167	However, to what extent that assumption holds is tested only on a small number of language pairs using hand aligned data (Fox, 2002; Hwa et al. , 2002; Wellington et al. , 2006).
---------------------------------------------------
N07-1057:11	20:167	Many MT models implicitly make the so-called direct correspondence assumption (DCA) as defined in (Hwa et al. , 2002).
---------------------------------------------------
D09-1124:12	156:166	Also related are the areas of word alignment for machine translation (Och and Ney, 2000), induction of translation lexicons (Schafer and Yarowsky, 2002), and cross-language annotation projections to a second language (Riloff et al., 2002; Hwa et al., 2002; Mohammad et al., 2007).
---------------------------------------------------
D09-1124:13	9:166	Measures of cross-language relatedness are useful for a large number of applications, including cross-language information retrieval (Nie et al., 1999; Monz and Dorr, 2005), cross-language text classification (Gliozzo and Strapparava, 2006), lexical choice in machine translation (Och and Ney, 2000; Bangalore et al., 2007), induction of translation lexicons (Schafer and Yarowsky, 2002), cross-language annotation and resource projections to a second language (Riloff et al., 2002; Hwa et al., 2002; Mohammad et al., 2007).
---------------------------------------------------
I08-1069:14	15:166	IGTs unique structure  effectively each instance consists ofa bitext between Englishand some target language  can be easily enriched through alignment and projection (e.g., (Yarowsky and Ngai, 2001), (Hwa et al., 2002)).
---------------------------------------------------
P06-1146:15	14:209	A number of recent studies rely on this notion of parallelism and demonstrate that annotations can be adequately projected for parts of speech (Yarowsky and Ngai, 2001; Hi and Hwa, 2005),chunks(YarowskyandNgai,2001),anddependencies (Hwa et al. , 2002).
---------------------------------------------------
P06-1146:16	61:209	Previous research addresses this problem in a post-processing step, by reestimating parameter values (Yarowsky and Ngai, 2001), by applying transformation rules (Hwa et al. , 2002), by using manually labelled data (Hi and Hwa, 2005), or by relying on linguistic criteria (Pad and Lapata, 2005).
---------------------------------------------------
P06-1146:17	184:209	7 Related work Previous work has primarily focused on the projectionofgrammatical(YarowskyandNgai,2001) and syntactic information (Hwa et al. , 2002).
---------------------------------------------------
P03-1012:18	90:202	Given the dependency tree TE, the alignment can induce a dependency tree for F (Hwa et al. , 2002).
---------------------------------------------------
P05-2022:19	11:149	Moreover, as stressed in previous research, using syntactic dependencies seems to be particularly well suited to coping with the problem of linguistic variation across languages (Hwa et al. , 2002).
---------------------------------------------------
W02-1019:20	138:149	Recent work (Hwa et al. , 2002) suggests that translational corresponence of linguistic structures can indeed be useful in projecting parses across languages.
---------------------------------------------------
H05-1108:21	194:204	Similarly to previous work (Hwa et al. , 2002), we find that some mileage can be gained by assuming direct correspondence between two languages.
---------------------------------------------------
J03-3002:22	8:541	More recently, researchers at Johns Hopkins University and the University of Maryland have been exploring new ways to exploit parallel corpora in order to develop monolingual resources and tools, using a process of annotation, projection, and training: Given a parallel corpus in English and a less resource-rich language, we project English annotations across the parallel corpus to the second language, using word-level alignments as the bridge, and then use robust statistical techniques in learning from the resulting noisy annotations (Cabezas, Dorr, and Resnik 2001; Diab and Resnik 2002; Hwa et al. 2002; Lopez et al. 2002; Yarowsky, Ngai, and Wicentowski 2001; Yarowsky and Ngai 2001; Riloff, Schafer, and Yarowsky 2002).
---------------------------------------------------
