This evidencegoesagainstsomerecentproposalsforplural reference generation which emphasise brevity (Gardent, 2002). 
Several GRE algorithms have addressed the issue of generating locative expressions [Dale and Haddock, 1991; Horacek, 1997; Gardent, 2002; Krahmer and Theune, 2002; Varges, 2004]. 
To avoid the generation of redundant descriptions that is typical for incremental approaches, Gardent [2002] and Horacek [2003] proposed exhaustive resp. 
Work on reference to sets has also proceeded within this general framework (van Deemter, 2002; Gardent, 2002; Horacek, 2004). 
Following Dale (1989), and especially Dale and Reiter (1995), several contributions have extended the remit of ASGRE algorithms to handle relations (Dale and Haddock, 1991; Kelleher and Kruijff, 2006) and gradable attributes (van Deemter, 2006); and also to guarantee logical completeness of algorithms (van Deemter, 2002; Gardent, 2002; Horacek, 2004; Gatt and van Deemter, 2007). 
