Bilingual Bootstrapping We also used the same data in (Li and Li, 2002) to conduct bilingual bootstrapping and word sense disambiguation. 
The first voting model is a naive Bayes model, since Yarowsky and Florian (2002) found this model to be the most accurate classifier in a comparative study on a subset of Senseval-2 English lexical sample data. 
5 Related Work Li and Li (2002) proposed bilingual bootstrapping for word translation disambiguation. 
In addition, (Dagan and Itai, 1994) and (Li, 2002) propose using two monolingual corpora for word sense disambiguation. 
The Senseval system consists of an ensemble of four combined WSD models: The first model is a nave Bayes model, since Yarowsky and Florian (2002) found this model to be the most accurate classifier in a comparative study on a subset of Senseval-2 English lexical sample data. 
