2.3 Semantic Construction Baldridge and Kruijff (2002) show how HLDS representations can be built via CCG derivations. 
Internally, such graphs are represented using Hybrid Logic Dependency Semantics (HLDS), a dependency-based approach to representing linguistic meaning (Baldridge and Kruijff, 2002). 
We model meaning as an ontologically richly sorted, relational structure, using a description logic-like framework (Baldridge and Kruijff, 2002). 
[Baldridge and Kruijff, 2002; White and Baldridge, 2003] show how HLDS representations can be built compositionally with CCG using unification, and compare HLDS to other semantic formalisms like Minimal Recursion Semantics [Copestake et al. , 1997]. 
Internally, such graphs are represented using Hybrid Logic Dependency Semantics (HLDS), a dependency-based approach to representing linguistic meaning (Baldridge and Kruijff, 2002). 
