(2002) and Turney (2002) classified sentiment polarity of reviews at the document level. 
Turney (2002) showed that it is possible to use only a few of those semantically oriented words (namely, excellent and poor) to label other phrases co-occuring with them as positive or negative. 
This direction has been forming the mainstream of research on opinion-sensitive text processing (Pang et al. , 2002; Turney, 2002, etc.). 
TheauthorsapplySO-PMI-IR(Turney, 2002) to extract and determine the polarity of adjectives. 
(2002) and Turney (2002) classified sentiment polarity of reviews at the document level. 
