We use BLEU scores (Papineni et al. , 2002) to measure translation accuracy. 
(Case-sensitive) BLEU-4 (Papineni et al. , 2002) is used as the evaluation metric. 
6.1 Evaluation of Translation Performance We use the BLEU score (Papineni et al., 2002) to evaluate our systems. 
(Case-sensitive) BLEU-4 (Papineni et al. , 2002) is used as the evaluation metric. 
BLEU: Automatic evaluation by BLEU score (Papineni et al. , 2002). 
