Several methods for paraphrasing Japanese predicate phrases have been proposed (Kondo et al. , 1999; Kondo et al. , 2001; Kaji et al. , 2002; Fujita et al. , 2005).


3 Learning Predicate Paraphrase Pairs Kaji et al. proposed a method of paraphrasing predicates using a dictionary (Kaji et al. , 2002).


The procedure of the method is as follows: 1 (step 1) Paraphrase pairs of predicates 2 are learned from a dictionary using a method proposed by (Kaji et al. , 2002).


