Two tools are used: the GATE system (Cunningham et al., 2002) and a summarization toolkit (Saggion, 2002; Saggion and Gaizauskas, 2004) which is compatible with GATE. 
This information, together with tokenisation information (kind, orthography, and token length) is obtained by using the language processing components available with GATE, as part of the ANNIE system (Cunningham et al. , 2002). 
These named entities are tagged with GATE (Cunningham et al. , 2002). 
It provides a mature infrastructure for scalable and customizable information extraction as well as annotation and document management, based on GATE (Cunningham et al. , 2002). 
The semantic grammars and rules are developed in JAPE language (Java Annotations Pattern Engine) and executed by a GATE transducer (Cunningham et al. , 2002). 
