Solving largescale multi-class classification problem with SVMs requires substantial computational resources, so we use the revision learning method (Nakagawa et al. , 2002).


Examples include Part-of-Speech tagging (Nakagawa et al. , 2002) Text Chunking (Kudo and Matsumoto, 2001), Named Entity Recognition (Isozaki and Kazawa, 2002), and Japanese Dependency Parsing (Kudo and Matsumoto, 2000; Kudo and Matsumoto, 2002).


2.2 Revision Learning for POS tagging We use a revision learning method (Nakagawa et al. , 2002) for POS tagging with SVMs1.


There are several related methods for 1-best outputs, such as revision learning (Nakagawa et al., 2002) and transformation-based learning (Brill, 1995) for partof-speech tagging.


