The Gildea and Palmer (2002) system uses the same features and the same classification mechanism used by G&J. These results are reported on the December 2001 release of PropBank. 
This corpus contains about 53,700 sentences and a fixed split between training and testing which has been used in other researches (Gildea and Jurafsky, 2002; Surdeanu et al. , 2003; Hacioglu et al. , 2003; Chen and Rambow, 2003; Gildea and Hockenmaier, 2003; Gildea and Palmer, 2002; Pradhan et al. , 2003). 
for role labelling, Gildea and Palmer (2002) emphasise the role of deeper syntactic analysis for semantic role labelling. 
5 The Experiments In previous work using the PropBank corpus, Gildea and Palmer (2002) developed a system to predict semantic roles from sentences and their parse trees as determined by the statistical parser of Collins (1999). 
Most of previous SRL systems (Gildea and Jurafsky, 2002; Gildea and Palmer, 2002; Punyakanok et al., 2005; Pradhan   2008. 
