We used three methods to generate the views from the 25 features used by the coreference system: Mueller et al.s (2002) greedy method, random splitting of features into views, and splitting of features according to the feature type (i.e. lexicosyntactic vs. non-lexico-syntactic features).


Indeed, although the algorithm has been applied successfully to natural language processing (NLP) tasks that have a natural view factorization (e.g. web page classification (Blum and Mitchell, 1998) and named entity classification (Collins and Singer, 1999)), there has been little success, and a number of reported problems, when applying cotraining to NLP data sets for which no natural feature split has been found (e.g. anaphora resolution (Mueller et al. , 2002)).


