Byron (2002) proposed to identify the antecedents of pronominal references in spoken dialogues by utilizing discourse structures with discourse entities and semantic ltering. 
Inspired by the work of Eckert & Strube (2000) and Byron (2002), these features capture preferences for NPor nonNP-antecedents by taking a pronouns predicative context into account. 
The pronoun this in T2 is resolved anaphorically to the nearest consistent eventuality (Eckert and Strube 2000; Byron 2002) which in this case is interp(T1). 
Recently two algorithms for resolving APAs and IPAs in specific English dialogues have been proposed: Eckert and Strubes (2000) es00, Byrons (2002) phora. 
Byron (2002) presented a symbolic approach which resolves pronouns with NPand non-NPantecedents in spoken dialogue in the TRAINS domain. 
