W03-0807:1	85:127	The WHITEBOARD project (Crysmann et al. , 2002) uses monotonic XML annotation to integrate deep and shallow processing (Figure 2, middle).
---------------------------------------------------
P07-1079:2	147:260	5 Related work There are other approaches that combine shallow processing with deep parsing (Crysmann et al. , 2002; Frank et al. , 2003; Daum et al. , 2003) to improve parsing efficiency.
---------------------------------------------------
P03-1014:3	85:209	3.2 Annotation-based Integration In the annotation-based architecture of (Crysmann et al. , 2002), XML-encoded analysis results of all components are stored in a multi-layer XML chart.
---------------------------------------------------
P03-1014:4	8:209	With the advent of XML-based hybrid shallowdeep architectures as presented in (Grover and Lascarides, 2001; Crysmann et al. , 2002; Uszkoreit, 2002) it has become possible to integrate the added value of deep processing with the performance and robustness of shallow processing.
---------------------------------------------------
P03-1014:5	11:209	While integration in (Grover and Lascarides, 2001) was still restricted to morphological and PoS information, (Crysmann et al. , 2002) extended shallow-deep integration at the lexical level to lexico-semantic information, and named entity expressions, including multiword expressions.
---------------------------------------------------
P03-1014:6	86:209	The architecture employed in this paper improves on (Crysmann et al. , 2002) by providing a central Whiteboard Annotation Transformer (WHAT) that supports flexible and powerful access to and transformation of XML annotation based on standard XSLT engines 6 (see (Schafer, 2003) for more details on WHAT).
---------------------------------------------------
P03-1014:7	12:209	(Crysmann et al. , 2002) assume a vertical, pipeline scenario where shallow NLP tools provide XML annotations that are used by the DNLP system as a preprocessing and lexical interface.
---------------------------------------------------
W02-1503:8	28:209	There are some indications that the German and English grammars in ParGram exceed the HPSG grammars in coverage (see (Crysmann et al. , 2002) on the German HPSG grammar).
---------------------------------------------------
N09-2045:9	83:93	The idea of improving the performance of deep parsers through the integration of shallow and deep parsers has been reported in (Crysmann et al., 2002; Daum et al., 2003; Frank et al., 2003) for non-biomedical text.
---------------------------------------------------
W04-2312:10	22:186	Existing spoken language understanding systems, that are not shallow and thusly produce deep syntactic and semantic representations for multiple domains, e.g. the production system approach described by Engel (2002) or unification-based approaches described by Crysmann et al.
---------------------------------------------------
W03-0812:11	28:199	Even more demanding, recent hybrid NLP systems such as WHITEBOARD (Crysmann et al. , 2002) implement more complex interactions and loops, instead of using a simple pipeline of modules.
---------------------------------------------------
