The same corpus was also processed with a finite-state parser, performing at 80% dependency f-score (Schiehlen, 2003).


Building on past experiments (Schiehlen, 2003), we chose the nth-tag representation which consists of three pieces of information: the POS tag of the head, the direction in which the head lies (left or right), and the number of words with the same POS tag between head and dependent.


