This strategy has been successfully used in (Shen and Joshi, 2003).


Results of other supertaggers for automatically extest data accuracy (%) HPSG supertagger 22 87.51 (this paper) CCG supertagger 00/23 91.70 / 91.45 (Curran and Clark, 2003) LTAG supertagger 22/23 86.01 / 86.27 (Shen and Joshi, 2003) Table 5: Accuracy of single-tag supertaggers.


When compared with other supertag sets of automatically extracted lexicalized grammars, the (effective) size of our supertag set, 1,361 lexical entries, is between the CCG supertag set (398 categories) used by Curran and Clark (2003) and the LTAG supertag set (2920 elementary trees) used by Shen and Joshi (2003).


