We have applied structural patterns to the Penn Treebank, where like in perfect parses precision and recall are high, and where in addition functional labels and empty nodes are available, so that patterns similar to Johnsons but  like (Jijkoun, 2003)  relying on functional labels and empty nodes reach precision close to 100%.


Building on these ideas, Jijkoun (2003) used a machine learning classifier to detect matches.


Johnson (2002) and Jijkoun (2003) used pattern-matching on local phrase or dependency structures.


Pattern-matching approaches were used in (Johnson, 2002) and (Jijkoun, 2003) to recover non-local dependencies in phrase trees.


A common characteristic of all these approaches 1(Jijkoun, 2003; Jijkoun and Rijke, 2004) also describe postprocessing methods to recover NLDs, which are applied to syntactic dependency structures converted from CFG-trees.


