Niehren and Thater (2003) defined, in a theoretical paper, a translation from MRS into normal dominance constraints. 
Hnc graphs are equivalent to chain-connected dominance constraints (Koller et al. , 2003), and areclosely relatedto dominance nets (Niehrenand Thater, 2003). 
7 Conclusion We developed Niehren and Thaters (2003) theoretical translation into a practical system for translating MRS into dominance constraints, applied it systematically to MRSs produced by English Resource Grammar for the Redwoods treebank, and evaluated the results. 
An important class of dominance graphs are hypernormally connected dominance graphs, or dominance nets (Niehren and Thater, 2003). 
Definitions 1 and 2 generalize the idealized definition of MRS of Niehren and Thater (2003) by EP-conjunctions with a merging semantics. 
