We use the Hierarchical Directed Acyclic Graph (HDAG) Kernel (Suzuki et al. , 2003), which is suited to handle structured natural language data. 
For example, the kernels for structured natural language data, such as parse tree kernel (Collins and Duffy, 2001), string kernel (Lodhi et al. , 2002) and graph kernel (Suzuki et al. , 2003) are example instances of the wellknown convolution kernels 1 in NLP. 
Moreover, we can expand our proposals to hierarchically structured graph kernels (Suzuki et al. , 2003a) by using a simple extension to cover hierarchical structures. 
The Tree Kernel (Collins and Duffy, 2001), String Subsequence Kernel (SSK) (Lodhi et al. , 2002) and Graph Kernel (HDAG Kernel) (Suzuki et al. , 2003) are examples of convolution kernels instances in the NLP field. 
The same happens for the one proposed in (Suzuki et al., 2003) that is applicable to a particular class of graphs, i.e. the hierarchical directed acyclic graphs. 
