We used the Stanford Lexicalized Parser (Klein and Manning, 2003) to parse the question. 
(2005) and Klein and Manning (2003). 
This binarization is done in a similar way to Johnson (1998) and Klein and Manning (2003). 
Compared to a basic treebank grammar (Charniak, 1996), the grammars of highaccuracy parsers weaken independence assumptions by splitting grammar symbols and rules with either lexical (Charniak, 2000; Collins, 1999) or nonlexical (Klein and Manning, 2003; Matsuzaki et al. , 2005) conditioning information. 
To generate sampled parses, we used the Stanford parser (Klein and Manning, 2003). 
