[C. Niu et al. 2003] presented a bootstrapping approach for English named entity recognition using successive learners of parsing-based decision 40 System Statistical Model Linguistic Feature Combinative Points [Zhang et al. 2003] HMM semantic role, tokens pattern rules [Sun et al. 2002] class-based LM word form, NE category cue words list [Tsai et al. 2004] ME model tokens knowledge representation Table 1: Comparison between several Chinese NER systems1 list and HMM, and promising experiment results (F-measure: 69.8%) on product NE (corresponding to our PRO) were obtained.


