This is adopted from (Gabsdil, 2003), based on the fact that WER correlates with concept accuracy (CA, (Boros et al., 1996)).


Similar to (Gabsdil and Lemon, 2004; Jonson, 2006) we ascribe to each utterance either of the opt, pos, neg, ign labels according to the following schema:  opt: The hypothesis is perfectly aligned and semantically identical to the transcription  pos: The hypothesis is not entirely aligned (WER < 50) but is semantically identical to the transcription  neg: The hypothesis is semantically identical to the transcription but does not align well (WER > 50) or is semantically different to the transcription  ign: The hypothesis was not addressed to the system (crosstalk), or the user laughed, coughed, etc. The 50% value for the WER as a threshold for the distinction between the pos and neg category is adopted from (Gabsdil, 2003), based on the fact that WER is affected by concept accuracy (Boros et al., 1996).


This is adopted from (Gabsdil, 2003), based on the fact that WER correlates with concept accuracy (CA, (Boros et al. , 1996)).


