2 Extraction Pattern Learning We begin by outlining the general process of learning extraction patterns, similar to one presented by (Yangarber, 2003). 
A number of pattern induction approaches have recently been researched based on the dependency analysis (Yangarber, 2003) (Sudo et al., 2001) (Greenwood and Stevenson, 2006) (Sudo et al., 2003). 
For this reason, much of the following work on pattern acquisition has used this approach as a de facto evaluation standard (Yangarber, 2003; Stevenson and Greenwood, 2005). 
We also observe that the automatically acquired patterns in Riloff (1996), Yangarber (2003), Sudo et al. 
2 Semi-Supervised Learning of Extraction Patterns We begin by outlining the general process of learning extraction patterns using a semi-supervised algorithm, similar to one presented by Yangarber (2003). 
