Sato and Sasaki (2003) has proposed two metrics for evaluating the strength of the relation of two terms.


Based on the analysis above, we employ the metrics proposed by Sato and Sasaki (2003).


Suppose that we have sample terms of a specific domain/topic, technical terms to be listed as the headwords of a bilingual lexicon are collected from the Web by the related term collection method of (Sato and Sasaki, 2003).


2 Related Term Collection Given a translation pair of seed terms (s f, s j ), we use a search engine to gather a set F of French terms related to s f, and a set J of Japanese terms related to s j. The methods applied for both languages use the framework proposed by Sato and Sasaki (2003), outlined in Figure 1.


Suppose that we have sample terms of a specific domain/topic, then the technical terms that are to be listed as the headwords of a bilingual lexicon are collected from the Web by the related term collection method of (Sato and Sasaki, 2003).


