P06-2027:1	126:242	The procedure of substituting named entities with their respective tags previously proved to be useful for various tasks (Barzilay and Lee, 2003; Sudo et al. , 2003; Filatova and Prager, 2005).
---------------------------------------------------
P06-2027:2	90:242	Many of the current approaches of domain modeling collapse together different instances and make the decision on what information is important for a domain based on this generalized corpus (Collier, 1998; Barzilay and Lee, 2003; Sudo et al. , 2003).
---------------------------------------------------
P06-2027:3	114:242	Following (Sudo et al. , 2003) we are interested only in the lexemes which are near neighbors of the most frequent verbs.
---------------------------------------------------
N09-2043:4	15:72	The subtree model considers all subtrees as pattern candidates (Sudo et al., 2003).
---------------------------------------------------
N09-2043:5	7:72	A number of pattern induction approaches have recently been researched based on the dependency analysis (Yangarber, 2003) (Sudo et al., 2001) (Greenwood and Stevenson, 2006) (Sudo et al., 2003).
---------------------------------------------------
D07-1075:6	35:368	Examples of rule/pattern-based approaches to information extraction are FASTUS (Hobbs et al. , 1997), PALKA (Kim and Moldovan, 1993), LIEP (Huffman, 1996), CRYSTAL (Soderland et al. , 1995), AutoSlog/AutoSlog-TS (Riloff, 1993; Riloff, 1996), RAPIER (Califf and Mooney, 1999), WHISK (Soderland, 1999), ExDisco (Yangarber et al. , 2000), SNOWBALL (Agichtein and Gravano, 2000), (LP)2 (Ciravegna, 2001), subtree patterns (Sudo et al. , 2003), predicate-argument rules (Yakushiji et al. , 2006) and KnowItAll (Popescu et al. , 2004).
---------------------------------------------------
C08-1107:7	71:203	Given a dependency parse tree, any sub-tree can be a candidate template, setting some of its nodes as variables (Sudo et al., 2003).
---------------------------------------------------
C08-1107:8	63:203	We are further motivated by the fact that some (mostly supervised) works in IE found learning unary templates useful for recognizing relevant named entities (Riloff, 1996; Sudo et al., 2003; Shinyama and Sekine, 2006), though they did not attempt to learn generic knowledge bases of entailment rules.
---------------------------------------------------
P07-1058:9	60:205	One approach which was used for evaluating automatically acquired rules is to measure their contribution to the performance of specific systems, such as QA (Ravichandran and Hovy, 2002) or IE (Sudo et al. , 2003; Romano et al. , 2006).
---------------------------------------------------
C04-1040:10	15:230	(Suzuki et al. , 2003; Sudo et al. , 2003) Recently, Yamada and Matsumoto (2003) proposed a trainable English word dependency analyzer based on Support Vector Machines (SVM).
---------------------------------------------------
W06-0202:11	16:186	For example, Yangarber (2003) uses just subject-verb-object tuples while Sudo et al.
---------------------------------------------------
W06-0202:12	57:186	Subtrees: The final model to be considered is the subtree model (Sudo et al. , 2003).
---------------------------------------------------
W06-0202:13	14:186	Several recent approaches to IE have used patterns based on a dependency analysis of the input text (Yangarber, 2003; Sudo et al. , 2001; Sudo et al. , 2003; Bunescu and Mooney, 2005; Stevenson and Greenwood, 2005).
---------------------------------------------------
W06-0202:14	23:186	This has implications on the practical application for each approach, particularly when used for automatic acquisition of IE systems using learning methods (Yangarber et al. , 2000; Sudo et al. , 2003; Bunescu and Mooney, 2005).
---------------------------------------------------
W07-1211:15	75:181	However, Stevenson and Greenwood (2006) also found that the coverage of the chain model was significantly worse than the subtree model, although Sudo et al. 83 (2003) found that in some cases their performance could not be distinguished.
---------------------------------------------------
W07-1211:16	10:181	More recently researchers have begun to employ deeper syntactic analysis, such as dependency parsing (Yangarber et al. , 2000; Stevenson and Greenwood, 2005; Sudo et al. , 2001; Sudo et al. , 2003; Yangarber, 2003).
---------------------------------------------------
W07-1211:17	50:181	Subtrees: The final model to be considered is the subtree model (Sudo et al. , 2003).
---------------------------------------------------
N06-1039:18	22:236	There are many existing works on obtaining extraction patterns for pre-defined relations (Riloff, 1996; Yangarber et al. , 2000; Agichtein and Gravano, 2000; Sudo et al. , 2003).
---------------------------------------------------
W06-0204:19	74:153	(Sudo et al. , 2003; Bunescu and Mooney, 2005)).
---------------------------------------------------
W06-0204:20	138:153	The majority of previous semi-supervised approaches to IE have been evaluated over preliminary tasks such as the identification of event participants (Sudo et al. , 2003) or sentence filtering (Stevenson and Greenwood, 2005).
---------------------------------------------------
C04-1127:21	9:153	The idea of a self-customizing IE system emerged recently with the improvement of pattern acquisition techniques (Sudo et al. , 2003b), where the IE system customizes itself across domains given by the users query.
---------------------------------------------------
C04-1127:22	24:153	(Sudo et al. , 2003a)) consists of three phases to learn extraction patterns from the source documents for a scenario specified by the user.
---------------------------------------------------
P07-1074:23	114:211	4.2 Rule Validation: Ranking and Filtering Our ranking strategy has incorporated the ideas proposed by Riloff (1996), Agichtein and Gravano (2000), Yangarber (2003) and Sudo et al.
---------------------------------------------------
P07-1074:24	17:211	We also observe that the automatically acquired patterns in Riloff (1996), Yangarber (2003), Sudo et al.
---------------------------------------------------
P07-1074:25	12:211	Current semior unsupervised approaches to automatic pattern acquisition are either limited to a certain linguistic representation (e.g. , subject-verb-object), or only deal with binary relations, or cannot assign slot filler roles to the extracted arguments, or do not have good selection and filtering methods to handle the large number of tree patterns (Riloff, 1996; Agichtein and Gravano, 2000; Yangarber, 2003; Sudo et al. , 2003; Greenwood and Stevenson, 2006; Stevenson and Greenwood, 2006).
---------------------------------------------------
P07-1074:26	30:211	Therefore, our method is much more efficient than the subtree model of Sudo et al. , (2003), where all subtrees containing verbs are taken into account.
---------------------------------------------------
I05-2045:27	12:123	Due to the limitation of supervised methods, some weakly supervised (or semi-supervised) approaches have been suggested (Brin, 1998; Eugene and Luis, 2000; Sudo et al. , 2003).
---------------------------------------------------
W07-0909:28	76:167	Automatically Learning Entailment Rules from the Web Many algorithms for automatically learning paraphrases and entailment rules have been explored in recent years (Lin and Pantel, 2001; 1http://jakarta.apache.org/lucene/docs/index.html 67 Ravichandran and Hovy, 2002; Shinyama et al. , 2002; Barzilay and Lee, 2003; Sudo et al. , 2003; Szpektor et al. , 2004; Satoshi, 2005).
---------------------------------------------------
W07-0909:29	45:167	Although knowledge-bases of entailment-rules and paraphrases learned by acquisition algorithms were used in other NLP applications, such as QA (Lin and Pantel, 2001; Ravichandran and Hovy, 2002) and IE (Sudo et al. , 2003; Romano et al. , 2006), to the best of our knowledge the output of such algorithms was never applied to IR before.
---------------------------------------------------
I08-1021:30	41:178	In addition to the verb, many systems expand their representation by including named entity tags (Collier, 1998; Yangarber et al., 2000; Sudo et al., 2003; Filatova et al., 2006), as well as restricting matches (using constraints on subtrees (Sudo et al., 2003; Filatova et al., 2006), predicate argument structures (Collier, 1998; Riloff and Schmelzenbach, 1998; Yangarber et al., 2000; Harabagiu and Maiorano, 2002) or semantic roles).
---------------------------------------------------
I08-1021:31	50:178	Other systems (Collier, 1998; Sudo et al., 2003) do employ 158 lexical similarity but threshold it to obtain binary judgments.
---------------------------------------------------
