3.3 Method To allow comparisons with earlier work on NEGRA parsing, we use the same split of training, development and testing data as used in Dubey and Keller (2003). 
Whereas the best performing parsers for English all make use of lexical information,the real benets of lexicalization for English as well as other languages remains controversial (Dubey and Keller,2003; Klein and Manning 2003; Arun and Keller 2005). 
Research on German (Dubey and Keller, 2003) showed that lexicalization leads to no sizable improvement in parsing performance for this language. 
1 Introduction Recent research on German statistical parsing has shown that lexicalization adds little to parsing performance in German (Dubey and Keller, 2003; Beil et al. , 1999). 
Earlier studies by Dubey and Keller (2003) and Dubey (2005) using the Negra treebank (Skut et al., 1997) reports that lexicalization of PCFGs decrease the parsing accuracy when parsing Negras flat constituent structures. 
