Baldwin and Bond (2003) propose a method for automatically learning the countability of English nouns from the BNC. 
The models and their performance on the test set are Model Count Uncount Baseline 74.60 78.30 Best BNC 87.32 90.39 Best Altavista 88.38 91.22 Baldwin and Bond (2003) 93.90 95.20 Table 13: Performance comparison with the literature for noun countability detection listed in Table 12. 
This approach of classifying linguistic types by the distribution of linguistic tokens makes this research similar in spirit to that of Baldwin and Bond (2003) and Stevenson and Merlo (1999). 
In a separate evaluation, we took the bestperforming classifier (Dist(AllCON,SUITE)) and ran it over open data, using best-500 feature selection (Baldwin and Bond, 2003). 
Baldwin and Bond (2003a; 2003b) have proposed a method for automatically learning countability from corpus data. 
