TiMBL: my TiMBL results N&M: Nissim and Markerts (2003) results simple learning phase, TiMBL is able to replicate the results from Nissim and Markert (2003; 2005). 
Markert and Nissims (2002a) and Nissim and Markerts (2003) study is the only one to approach metonymy recognition from a data-driven, statistical perspective. 
To address this problem, Nissim and Markert (2003) proposed a word similarity-based method. 
3 Data We work with the data from the metonymy resolution task at SemEval 2007 (Markert and Nissim, 2007), generated based on a scheme developed by Markert and Nissim (2003). 
al., 2000; Nissim&Markert, 2003; Mason, 2004). 
