IE systems typically focus on information about events that are relevant to a specific domain, such as terrorism (Sundheim, 1992; Soderland et al. , 1995; Riloff, 1996; Chieu et al. , 2003), management succession (Sundheim, 1995; Yangarber et al. , 2000), or job announcements (Califf and Mooney, 1999; Freitag and McCallum, 2000). 
Similarly, classifierbased approaches (Freitag, 1998; Freitag and McCallum, 2000; Chieu et al., 2003; Bunescu and Mooney, 2004) rely on features in the immediate context of the candidate extractions. 
(2000), Califf and Mooney (2003)) or classifiers (e.g., Freitag (1998), Freitag and McCallum (2000), Chieu et al. 
7 Related Work (Chieu et al. , 2003) reported a feature-based SVM system (ALICE) to extract MUC-4 events of 7 terrorist attacks. 
Examples of classifier-based IE systems are SRV (Freitag, 1998), HMM approaches (Freitag and McCallum, 2000), ALICE (Chieu et al. , 2003), and Relational Markov Networks (Bunescu and Mooney, 2004). 
