It has been used in the area of natural language interface for database (NLIDB) (Jung et al. , 2003) and a TREC QA system for the purpose of matching the user query with the appropriate answer types at syntax/semantic level (Kim et al. , 2001; Lee et al. , 2001).


The common semantic tags again include attribute-values in databases, such as @corp for a company name like IBM, and pre-define 83 semantic category values, such as @location for location names like New York (Jung et al. , 2003).


NE tagging selects a semantic type for each word so that a sentence can be mapped into a suitable LSP sequence by searching several types in the semantic dictionaries (An et al. , 2003).


We consider only the generic newswire NER task, although domain-specific annotated corpora have been developed for applications such as bio-text mining (Kim et al., 2003).


