Monson (2004) describes how morpheme boundary links in a CIC lattice can be thought of as branchings in a vocabulary trie where identical subtries are conflated. 
Additional details concerning the candidate inflection class framework can be found in Monson (2004). 
Monson (2004) concentrated on languages with limited resources. 
[Monson 2004] presents a framework for unsupervised induction of natural language morphology, wherein candidate suffixes are grouped into candidate inflection classes, which are then placed in a lattice structure. 
These findings are promising for the application of this approach to under-resourced languages 1Monson (2004) suggests, but does not actually use, 2. 
