Most research efforts in the Question Answering community have focused on factoid questions and successful Question Answering systems tend to have similar underlying pipelines structures (Prager et al. , 2004; Xu et al. , 2003; Hovy et al. , 2000; Moldovan et al. , 2000). 
We have demonstrated elsewhere (Prager et al. 2004b) how using multiple corpora can improve QA performance, but in this paper we achieve similar goals without using additional corpora. 
The work here is a continuation of previous work described in (Prager et al. 2004a,b). 
The IBMs PIQUANT system (Chu-Carroll et al, 2003; Prager et al, 2004) adopts a QA-byDossier-with-Constraints approach, which utilizes the natural constraints between the answer to the main question and the answers to the auxiliary questions. 
More examples of this problem were given in (Prager et al. 2004a). 
