C08-1124:1	132:230	Probabilistic Support Vector Machine (PSVM)  is employed as supervised learning (Wu et al., 2004), while the co-training of PSVM and Nave Bayesian Classifier (NBC) is used for semi-supervised learning.
---------------------------------------------------
C08-1124:2	50:230	Recently, content features were also well studied, including centroid (Radev et al., 2004), signature terms (Lin and Hovy, 2000) and high frequency words (Nenkova e t al., 2006).
---------------------------------------------------
C08-1124:3	63:230	Recently, semi-structure events (Filatovia and Hatzivassiloglou, 2004; Li et al., 2006; Wu, 2006) have been investigated by many researchers as they balanced document representation with words and structures.
---------------------------------------------------
C08-1124:4	145:230	(Blum and Mitchell, 1998) trained two classifiers of same type on different features, and (Li et al., 2004) trained two classifiers of different types.
---------------------------------------------------
C08-1124:5	78:230	A number of successful studies emerged thereafter for other natural language processing tasks, such as text classification (Denis and Gilleron, 2003), noun phrase chunking (Pierce and Cardie, 2001), parsing (Sarkar, 2001) and reference or relation resolution (Muller et al., 2001; Li et al., 2004).
---------------------------------------------------
C08-1124:6	13:230	Two kinds of summarization approaches were suggested in the past, i.e., extractive (Radev et al., 2004; Li et al., 2006) and abstractive summarization (Dejong, 1978).
---------------------------------------------------
W06-0904:7	16:179	While there has been a spurt of recent research addressing the event ordering problem, e.g., (Mani and Wilson 2000) (Filatova and Hovy 2001) (Schilder and Habel 2001) (Li et al. 2001) (Mani et al. 2003) (Li et al. 2004) (Lapata and Lascarides 2004) (Boguraev and Ando 2005) (Mani et al. 2006), that research relies on qualitative temporal relations.
---------------------------------------------------
P06-1095:8	159:181	(Li et al. 2004) obtained 78-88% accuracy on ordering within-sentence temporal relations in Chinese texts.
---------------------------------------------------
