The authors thank Shankar Kumar, Charles Schafer, David Smith, and Roy Tromble for helpful comments and discussions; three ACL reviewers for advice that improved the paper; Eric Goldlust for keeping the Dyna compiler (Eisner et al. , 2004) up to date with the demands made by this work; and Dan Klein for sharing details of his CCM implementation.


In other cases (Smith and Eisner, 2004; Smith and Smith, 2004; Smith et al. , 2005), Dyna let us quickly replicate, tweak, and combine useful techniques from the literature.


Probabilistic FST weight training was accomplished using the Dyna modeling language and DynaMITE parameter optimization toolkit (Eisner et al, 2004).


