In particular, we are interested to find out whether we outperform McCarthy et al.s (2004) related method for predominant sense detection. 
Note, however, that (McCarthy et al. , 2004) used the information about distributionally similar words to approximate corpus frequencies for word senses, whereas we target the estimation of a property of a given word sense (the subjectivity). 
One reason for this is the highly skewed distribution of word senses (McCarthy et al. , 2004a). 
Because the SemCor corpus is relatively small (less than 700,00 words), it is not ideal for constructing a neighbor thesaurus appropriate for McCarthy et al.s (2004) method. 
We used WordNet 1.7.1 (Fellbaum, 1998) senses.3 We compared our results to a baseline that selects for each word type a random sense, assumes it is the dominant one, and uses it to disambiguate all instances of the target word (McCarthy et al. , 2004a). 
