The fourth model is a Kernel PCA-based model (Wu et al. , 2004). 
FY02 (Florian and Yarowsky, 2002), WSC04 (Wu et al. , 2004), LN02 (Lee and Ng, 2002) the unseen Senseval-3 test sets). 
The fourth voting model is a Kernel PCA-based model (Wu et al. , 2004). 
Bayes (Soft Tag) 68.9 SVM-Topic 66.0 SVM baseline 65.2 NB baseline 63.4 ASO(best configuration)(Ando, 2006) 68.1 Classifier Combination(Florian, 2002) 66.5 Polynomial KPCA(Wu et al. , 2004) 65.8 SVM(Lee and Ng, 2002) 65.4 Senseval-2 Best System 64.2 Table 4: Results (best configuration) compared to previous best systems on Senseval-2 English lexical sample task. 
The model consists of an ensemble of four highly accurate classifiers combined by majority vote: a naive Bayes classifier, a maximum entropy model (Jaynes, 1978), a boosting model (Freund and Schapire, 1997), and a Kernel PCA-based model (Wu et al. , 2004), which has the advantage of having a signficantly different bias. 
