N09-1048:1	16:229	The other is multilingual parallel and comparable corpora (e.g., Wikipedia1), wherein features such as cooccurrence frequency and context are popularly employed (Cheng et al., 2004; Shao and Ng, 2004; Cao et al., 2007; Lin et al., 2008).
---------------------------------------------------
W06-1664:2	39:246	2 Related Works A number of studies have explained the use of the web for NLP tasks e.g., creating multilingual translation lexicons (Cheng et al. , 2004), text classification (Huang et al. , 2004), and word sense disambiguation (Turney, 2004).
---------------------------------------------------
