In cognitive science, they have been used to account for the influence of context on human lexical processing (McDonald and Brew, 2004), and to model lexical priming (Lowe and McDonald, 2000).


An interesting alternative is offered by vector space models of word meaning (Lund and Burgess, 1996; McDonald and Brew, 2004) which characterize the meaning of a word entirely without reference to word senses.


McDonald and Brew (2004) present a similar model.


There have been several approaches in the literature (Smolensky, 1990; Schutze, 1998; Kintsch, 2001; McDonald and Brew, 2004; Mitchell and Lapata, 2008) that compute meaning in context from lemma vectors.


Similar to Brew and McDonald (2004), they predict most likely next words in a sequence, without taking syntax into account.


