Since named entities are very important in NLP, many studies define and discover relations between named entities (Hasegawa et al., 2004; Hassan et al., 2006). 
For comparison of the effect of the outer context of entity mention pairs, we conducted three different Table 5: Performance of our proposed method (Spectralbased clustering) compared with other unsupervised methods: ((Hasegawa et al. , 2004))s clustering method and K-means clustering. 
Many machine learning methods have been proposed to address this problem, e.g., supervised learning algorithms (Miller et al. , 2000; Zelenko et al. , 2002; Culotta and Soresen, 2004; Kambhatla, 2004; Zhou et al. , 2005), semi-supervised learning algorithms (Brin, 1998; Agichtein and Gravano, 2000; Zhang, 2004), and unsupervised learning algorithms (Hasegawa et al. , 2004). 
(2004)s method2 makes it outperform Hasegawa et al. 
Some existing studies use corpus-based statistics for relation extraction (Hasegawa et al. , 2004). 
