Siddharthan and Copestake (2004)), making use of the fact that words can be disambiguated by nearby words that are similar.


Secondly, most evaluations have focussed on the semantic content of the generated descriptions, as produced by the Content Determination stage of a GRE algorithm; this means that linguistic realisation (i.e. the choice of words and linguistic constructions) is usually not addressed (exceptions are: Stone and Webber (1998), Krahmer and Theune (2002), Siddharthan and Copestake (2004)).


[Siddharthan and Copestake, 2004] take a corpusbased perspective and essentially regard a text as a knowledge base from which descriptions of domain objects can be extracted.


Both the work reported in [Stone, 2003] and in [Siddharthan and Copestake, 2004] can be seen as attempts to deal with the lack of domain model information in situations where only the surface forms of referring expressions are given.


Webber, 1998; Krahmer and Theune, 2002; Siddharthan and Copestake, 2004)).


