For systems that perform only word segmentation, we find the following results in the literature: (Gao et al., 2004), who use TBL to adapt a general purpose segmenter to varying standards, report an SF of 95.5% on PKU data and an SF of 90.4% on CTB data. 
Among them, the machine learning-based techniques showed excellent performance in many research studies (Peng et al. , 2004; Zhou et al. , 2005; Gao et al. , 2004). 
(SVM) (Kudo and Matsumoto, 2001), conditional random fields (CRF) (Peng and McCallum, 2004), and minimum error rate training (Gao et al. , 2004). 
In more recent work, TBL was used for the adaption of the output of a statistical general purpose segmenter to standards that vary depending on the application that requires sentence segmentation (Gao et al., 2004). 
Among them, the machine learning-based techniques showed excellent performance in many recent research studies (Peng et al., 2004; Zhou et al., 2005; Gao et al., 2004). 
