Structural correspondence learning is most similar to that of Ando (2004), who analyzed a situation with no target domain labeled data.


One important advantage that this work shares with Ando (2004) is that an SCL model can be easily combined with all other domain adaptation techniques (Section 7.2).


In such cases, we must take steps to adapt a model trained on the source domain for use in the target domain (Roark and Bacchiani, 2003; Florian et al. , 2004; Chelba and Acero, 2004; Ando, 2004; Lease and Charniak, 2005; Daume III and Marcu, 2006).


We are also focusing on other potential applications, including chunking (Sha and Pereira, 2003), named entity recognition (Florian et al. , 2004; Ando and Zhang, 2005b; Daume III and Marcu, 2006), and speaker adaptation (Kuhn et al. , 1998).


