However, these studies showed that AER and BLEU do not correlate well (Callison-Burch et al. , 2004; Goutte et al. , 2004; Ittycheriah and Roukos, 2005).


The second strategy is to rely on a wordalignment method that naturally produces many-tomany alignments between non-contiguous words, such as the method described in (Goutte et al. , 2004).


Interestingly, in the experiments reported in (Goutte et al. , 2004), alignment method B did not compare favorably to A under the widely used Alignment Error Rate (AER) metric.


A second family of libraries was built using alignments B produced with the method in (Goutte et al. , 2004): these are the B libraries.


