However, our observation is confirmed by both Serafin and Eugenio (2004) and Ries (March 1999).


The tagging is doneintheFeatureLatentSemanticAnalysisframework (Serafin and Di Eugenio, 2004), augmented with additional prosodic and multi-modal features drawn from the annotation.


LSA has been successfully applied to tasks such as measuring semantic similarity among corpora of texts (Coccaro & Jurafsky, 1998), measuring cohesion (Foltz, Kintsch, & Landauer, 1998 ), assessing correctness of answers in tutoring systems (WiemerHastings & Graesser, 2000) and dialogue act classification (Serafin & Di Eugenio, 2004).


