(2003) and Culotta and Sorensen (2004) used tree kernels for relation extraction. 
Culotta and Sorensen (2004) generalize this kernel to estimate similarity between dependency trees. 
Culotta and Sorensen (2004) proposed a tree kernel for dependency trees. 
(Zelenko et al. , 2003; Culotta and Sorensen, 2004) further explored tree kernels for relation extraction. 
Culotta and Sorensen (2004) described a slightly generalized version of this kernel based on dependency trees. 
