4.2.1 Methodology Sentences containing discourse connectives were gathered from the British National Corpus and the world wide web, with discourse connectives identified on the basis of their syntactic contexts (for details, see Hutchinson (2004b)).


Only co-occurrences with dis153 0 0.5 1 1.5 2 2.5 0 1 2 3 4 5 Divergence of DM co-occurrences Similarity judgements best fit SYNONYM HYPONYM CONT SUBS EXCLUSIVE Figure 5: Similarity versus distributional divergence course adverbials and other structural discourse connectives were stored, as these had previously been found to be useful for predicting semantic features of connectives (Hutchinson, 2004a).


