3.2 The Convolution Tree Kernel Given the relation instances defined in the previous section, we use the same convolution tree kernel as the parse tree kernel (Collins and Duffy, 2001) and the semantic kernel (Moschitti, 2004). 
As this task is recognized as an important step after (or the last step of) syntactic analysis, many studies have been conducted to achieve accurate semantic role labeling (Gildea and Jurafsky, 2002; Moschitti, 2004; Hacioglu et al. , 2004; Punyakanok et al. , 2004; Pradhan et al. , 2005a; Pradhan et al. , 2005b; Toutanova et al. , 2005). 
The kernel that we employed in our experiments is based on the SCF structure devised in (Moschitti, 2004). 
Moschitti (2004) and Che et al. 
In addition, Moschitti (2004)s Tree Kernel Tool is used to compute the tree kernel function. 
