We will concentrate on features used in the creation model since those in the link model can be found in the literature (Soon et al. , 2001; Ng and Cardie, 2002b; Yang et al. , 2003; Luo et al. , 2004). 
Both tasks are performed with a statistical framework: the mention detection system is similar to the one presented in (Florian et al. , 2004) and the coreference resolution system is similar to the one described in (Luo et al. , 2004). 
Next, using these pairwise probabilities, we apply Luo et al.s (2004) Bell tree approach to coreference resolution to compute the N-best clusterings and their probabilities (see Section 2.4 for details). 
2.2 Feature Representation We duplicated the statistical model used by (Luo et al. , 2004), with three differences. 
The coreference system is similar to the one used in (Luo et al. , 2004). 
