Saric et al. developed a system to extract gene expression regulatory information in yeast as well as other regulatory mechanisms such phosphorylation (Saric et al. , 2004; Saric et al. , 2006).


For POS tagging, a decision tree based tagger developed by (Schmid, 1994) was used in combination with a model, which was trained on a corrected/revised GENIA corpus provided by (Saric et al. , 2004) and was reported to achieve 96.4% tagging accuracy (Saric et al. , 2006).


