Several studies claim that learning using tree kernels and other convolution kernels tends to overfit and propose selecting or restricting features (Cumby and Roth, 2003; Suzuki et al. , 2004; Kudo and Matsumoto, 2004).


Sometimes, the classification becomes faster as a result (Suzuki et al. , 2004; Kudo and Matsumoto, 2004).


In addition, a more interesting research topic is to study how to integrate linguistic knowledge and tree kernel methods to do feature selection for tree kernelbased NLP applications (Suzuki et al. , 2004).


Possible cures include extensive use of prior knowledge to guide the choice of relevant parts (Cumby and Roth, 2003; Frasconi et al. , 2004), the use of feature selection (Suzuki et al. , 2004), and soft matches (Saunders et al. , 2002).


However, the complexity burden of working in the dual space can be alleviated with recent approaches proposed in (Kudo and Matsumoto, 2003; Suzuki et al. , 2004).


