This has been seldom remarked (but see (Althaus et al., 2004)) and generic (out-ofthe-box) ILP implementations are used. 
To the best of our knowledge, linear programming has been used in an NLG related work only by [Althaus et al. , 2004] to solve a single task of determining the order of discourse constituents. 
7 Related Work ILP has been applied to various NLP problems, including semantic role labeling (Punyakanok et al. , 2004), extraction of predicates from parsetrees (Klenner, 2005) and discourse ordering in generation (Althaus et al. , 2004). 
(2004) and Althaus et al. 
Unfortunately, finding the optimal ordering according to a probabilistic model with local features is NP-complete and non-approximable (Althaus et al. , 2004). 
