P05-3020:1	38:97	1 An alternative to relying on this fortunate but somewhat unsatisfactory effect would be not to use global co-occurrence vectors but local ones, as successfully proposed in word sense induction (Rapp, 2004).
---------------------------------------------------
P05-3020:2	95:97	Whereas in a previous paper (Rapp, 2004) we found that for word sense induction the local clustering of local vectors is more appropriate than the global clustering of global vectors, for part-ofspeech induction our conclusion is that the situation is exactly the other way round, i.e. the global clustering of global vectors is more adequate (see footnote 1).
---------------------------------------------------
