In a recent experiment, we compared the performance of HALOGEN relative to the grammar-based FUF/SURGE surface realizer on the identical corpus and with a similar methodology [Callaway, 2003; 2004].


While we present the results of a manual analysis of the data in the next section, it is important to remember that the large majority of syntactic constructions, punctuation and morphology worked flawlessly in the evaluation of FUF/SURGE as described in [Callaway, 2004].


