This is the main reason why the weaker notion of comparable corpora is a matter of recent interest in the eld of Computational Linguistics (Gaussier et al. , 2004).


4 Previous Work Much of the work involving comparable corpora has focused on extracting word translations (Fung and Yee, 1998; Rapp, 1999; Diab and Finch, 2000; Koehn and Knight, 2000; Gaussier et al. , 2004; Shao and Ng, 2004; Shinyama and Sekine, 2004).


This is the main reason because the weaker notion of comparable corpora is a matter recent interest in the eld of Computational Linguistics (Gaussier et al. , 2004).


One approach focused on extracting word translations (Gaussier et al., 2004).


Related Work While there is a large body of work on bilingual comparable corpora, most of it is focused on learning word translations (Fung and Yee 1998; Rapp 1999; Diab and Finch 2000; Koehn and Knight 2000; Gaussier et al. 2004).


