In current work we replace the realizer model with an implemented generator that replicates the variation found in the SPaRKy realizer (Stent et al., 2004). 
e.g. [Stent et al. , 2004]. 
Our goal, however, is to employ a stochastic realizer for SDS, see for example (Stent et al., 2004). 
We also point out (4), how we can in principle train the planner, like e.g. [Stent et al. , 2004]. 
For training the planner we discuss in this paper, we are not only interested in ensuring that we obtain a logical form that is appropriate given the communicative goal to be expressed (or, in a more structured way, comparable to the rhetorical structures considered in [Stent et al. , 2004]); the logical form also needs to be appropriate given the context. 
