More details on our approach to parsing interleaved natural and symbolic expressions can be found in (Wolska and Kruijff-Korbayova, 2004a) and more information on investigation into tectogrammatical relations that build up linguistic meaning of informal mathematical text can be found in (Wolska and Kruijff-Korbayova, 2004b).


It has been argued previously (Wolska and Kruijff-Korbayova, 2004; Rose et al., 2003) that tutorial dialogue systems require deep understanding of student explanations, which can have significantly more complex structure than database queries in the information-seeking domain.


