E06-1009:1	75:298	Figure3: Dialoguebetweensimulator(M)andPolifroni system (S) Polifroni et al.s approach was extended by Chung (2004), who proposed a constraint relaxation strategy for coping with queries that are too restrictive to be satisfied by any option.
---------------------------------------------------
E06-1009:2	24:298	The system summarizes the clusters based on their attributes and then prompts the user to provide additional constraints (Polifroni et al. , 2003; Chung, 2004).
---------------------------------------------------
E06-1009:3	205:298	Each dialogue pair consisted of one dialogue between a user and our system and one dialogue between the same user and a system designed as described in (Polifroni et al. , 2003; Chung, 2004) (cf.
---------------------------------------------------
W08-0126:4	18:207	There are also studies that use user simulation to train speech recognition and understanding components (Chung, 2004).
---------------------------------------------------
W08-1503:5	49:247	Both Chung (2004) and Lopez-Cozar et., (2003; 2006) used rule based intention simulation.
---------------------------------------------------
W08-1503:6	46:247	Chung (2004) tried to use the natural language generation module of (Seneff, 2002) to generate this surface.
---------------------------------------------------
W08-1503:7	36:247	Other techniques use simulation techniques to investigate and improve the target dialog strategies by examining the results heuristically or automatically (Chung, 2004; Rieser and Lemon, 2006; Torres et al., 2008).
---------------------------------------------------
P08-1071:8	10:207	For example, (Levin et al., 2000) and (Scheffler, 2002) exploit user simulations to generate large corpora for using Reinforcement Learning to develop dialog strategies, while (Chung, 2004) implement user simulation to train the speech recognizer and understanding components.
---------------------------------------------------
