This 532 Marino et al. N-gram-based Machine Translation section briefly describes MARIE, the n-gram based search engine developed for our SMT system (Crego, Marino, and de Gispert 2005a).


Preliminary results on detecting and classifying verb forms have been presented by de Gispert (2005).


This problem is closely related to reordering, and some preliminary results have been presented by Crego, Marino, and de Gispert (2005b).


Each verb is reduced into its base form and reduced POS tag as explained in (de Gispert, 2005).


Improvements in word-toword alignments were achieved through verb group classi cation as described in (de Gispert, 2005).


