The rst class-based feature we use is based on word classes derived from the web corpus mentioned earlier and computed as described by (Ravichandran et al. , 2005). 
Web004 is of similar scale to the largest reported randomized technique (Ravichandran et al. 2005). 
Language modeling (Chen and Goodman, 1996), noun-clustering (Ravichandran et al., 2005), constructing syntactic rules for SMT (Galley et al., 2004), and finding analogies (Turney, 2008) are examples of some of the problems where we need to compute relative frequencies. 
Since this data set tends to focus mostly on person instances from news, we have additionally used similar data mined from a a112a73a113a49a114 GB web corpus, for which more general ISA relations were mined (Ravichandran et al. , 2005). 
Randomized Algorithms: Randomized techniques for approximating various similarity measures have been successfully applied to term similarity (Ravichandran et al. 2005; Gorman and Curran 2006). 
