It can be seen that the formalization in the loglinear combination of our hybrid model is very similar to that of LOP-CRFs (Smith et al. , 2005). 
Instead, we show that by training gazetteer features in a separate model to the other features, and decoding using a logarithmic opinion pool (LOP) (Smith et al. , 2005), much greater accuracy can be obtained. 
To do this we use a logarithmic opinion pool (LOP) (Smith et al. , 2005). 
An approach based on pairwise similarities, which encourage nearby data points to have the same class label, has been proposed as a way of incorporating unlabeled data discriminatively (Zhu et al. , 2003; Altun et al. , 2005; Brefeld and Scheffer, 2006). 
Moreover, LOP-CRF (Smith et al. , 2005) is also compared with our hybrid model, since the formalism of our hybrid model can be seen as an extension of LOP-CRFs as described in Section 3. 
