W08-2006:1	29:189	Deriving lexical relatedness between terms has been a topic of interest with applications in word sense disambiguation (Patwardhan et al., 2005), paraphrasing (Kauchak and Barzilay, 2006), question answering (Prager et al., 2001), and machine translation (Blatz et al., 2004) to name a few.
---------------------------------------------------
W07-2086:2	9:91	1 Introduction WordNet::SenseRelate::TargetWord1 (Patwardhan et al. , 2005; Patwardhan et al. , 2003) is an unsupervised Word Sense Disambiguation (WSD) system, which is based on the hypothesis that the intended sense of an ambiguous word is related to the words in its context.
---------------------------------------------------
