(2000) and Stevenson and Greenwood (2005), have not made use of these more complex extraction patterns. 
For this reason, much of the following work on pattern acquisition has used this approach as a de facto evaluation standard (Yangarber, 2003; Stevenson and Greenwood, 2005). 
Stevenson and Greenwood (2005) suggested an alternative method for ranking the candidate patterns. 
Stevenson and Greenwood (2005) propose a weakly supervised approach to sentence filtering that uses semantic similarity and bootstrapping to acquire IE patterns. 
(2000), Yangarber (2003) and Stevenson and Greenwood (2005), is to use subject-verb-object tuples from the dependency parse as extraction patterns. 
