N06-1003:1	66:146	We manage the parallel corpora with a suffix array -based data structure (Callison-Burch et al. , 2005).
---------------------------------------------------
W08-0333:2	144:168	Several authors have advocated indexing the training data with a suffix array and computing the necessary statistics during or immediately prior to decoding (Callison-Burch et al., 2005; Lopez, 2007).
---------------------------------------------------
N06-1002:3	68:217	Delayed phrase construction To avoid the major practical problem of phrasal SMTnamely large phrase tables, most of which are not useful to any one sentenceone can instead construct phrase tables on the fly using an indexed form of the training data (Zhang and Vogel 2005; Callison-Burch et al. 2005).
---------------------------------------------------
N07-2006:4	22:89	(in contrast to the proposed approaches to online phrase extraction (Zhang and Vogel, 2005; Callison-Burch et al. , 2005)).
---------------------------------------------------
W09-0424:5	116:121	The toolkit also implements suffixarray grammar extraction (Callison-Burch et al., 2005; Lopez, 2007) and minimum error rate training (Och, 2003).
---------------------------------------------------
N07-1062:6	43:255	Furthermore, the suffix array data structure of (Callison-Burch et al. , 2005) requires a fair amount of memory, about 2GB in their example, whereas our implementation will use only a tiny amount of memory, e.g. less than 20MB for the large Chinese-English NIST task.
---------------------------------------------------
N07-1062:7	40:255	The motivation in (Callison-Burch et al. , 2005) is that there are some long source phrases in the test data that also occur in the training data.
---------------------------------------------------
N07-1062:8	39:255	2 Related Work (Callison-Burch et al. , 2005) and (Zhang and Vogel, 2005) presented data structures for a compact representation of the word-aligned bilingual data, such that on-the-fly extraction of long phrases is possible.
---------------------------------------------------
