Further, the feature space could be enriched with syntactic features which are known to be useful (Collins et al. , 2005).


Several researchers have investigated techniques for improving automatic speech recognition (ASR) results by modeling the errors (Collins et al. , 2005; Shafran and Byrne, 2004).


Incorporating syntactic features into the context has been at the forefront of recent research (Collins et al. , 2005; Rosenfeld et al. , 2001; Chelba and Jelinek, 2000; Hall and Johnson, 2004).


One can address this problem by using a large number of modeling-training folds (Collins et al., 2005), but we do not do so here.


