ILP models have been successfully applied in several natural language processing tasks, including relation extraction (Roth and Yih, 2004), semantic role labeling (Punyakanok et al. , 2004) and the generation of route directions (Marciniak and Strube, 2005).


Many of these systems have been shown to be very effective (Evens and Michael,2006; Van Lehn et al., 2005; Di Eugenio et al., 2005; Mitrovic et al., 2004; Person et al., 2001).


