Another class of approaches has shown improvements in translation through reordering, where source language strings are parsed and then reordered, in an attempt to recover a word order that is closer to the target language (Collins et al. , 2005; Xia and McCord, 2004). 
This is because, in this study, we did not apply any pre-processing strategy that we know can improve performances, such as clause reordering or compound-word splitting (Collins et al. , 2005; Langlais et al. , 2005). 
Reordering approaches have given significant improvements in performance for translation from French to English (Xia and McCord, 2004) and from German to English (Collins et al. , 2005). 
Third, the improvements are always statistically significant for our method, according to (Collins et al., 2005)s sign test. 
The absolute improvement of 0.75 over using 1-best alignments (from 0.2826 to 0.2901) is statistically significant at p < 0.05 by using sign-test (Collins et al., 2005). 
