In the experiments, we compared our model with the probabilistic HPSG model of Miyao and Tsujii (2005). 
3.1 Off-line processing: HPSG parsing and term recognition We first parsed all sentences using an HPSG parser (Miyao and Tsujii, 2005) to obtain their predicate argument structures. 
4.2 Evaluation We evaluated the speed and accuracy of parsing with extremely lexicalized models by using Enju 2.1, the HPSG grammar for English (Miyao et al. , 2005; Miyao and Tsujii, 2005). 
time (%) (%) (%) (%) (%) (%) (ms) Miyao and Tsujii (2005)s model 87.26 86.50 86.88 90.73 89.93 90.33 604 Ninomiya et al. 
(2006)s model 3 was not as great as the difference from Miyao and Tsujii (2005)s model, but our model 1 achieved 0.56 points higher F-score, and our model 2 achieved 0.8 points higher F-score. 
