These reasons have led some researchers to opt for a manual evaluation of their algorithms (Neill, 2002; Rapp, 2004; Udani et al. , 2005).


As known from work on unsupervised part-of-speech tagging (Rohwer and Freitag, 2004; Rapp, 2005), the size of the window in which words will be found similar to the target word plays a decisive role.


They are all based on co-occurrence statistics, albeit using different context representations such as co-occurrence of words within phrases (Pantel and Lin, 2002; Dorow and Widdows, 2003; Velldal, 2005), bigrams (Schutze, 1998; Neill, 2002; Udani et al. , 2005), small windows around a word (Gauch and Futrelle, 1993), or larger contexts such as sentences (Bordag, 2003; Rapp, 2004) or large windows of up to 20 words (Ferret, 2004).


4 Results As our test vocabulary we chose a sample of 50 words taken from a previous study (Rapp, 2005).


More recent studies try to solve the problem of POS induction by combining distributional and morphological information (Clark, 2003; Freitag, 2004), or by clustering words and projecting them to POS vectors (Rapp, 2005).


