current models of this type are based on supervised approaches [Ittycheriah et al. 2001; Ng et al. 2001; Suzuki et al. 2002; and Sasaki et al. 2005] that are heavily dependent on hand-tagged questionanswer training pairs, which not readily available.


Second, the U-SVM automatically learns the unique questiondependent clusters and the pseudo-training for each 34 Table 1: Comparison of Various Machine Learning Techniques System Model Key Idea Training Data [Ittycheriah et al. 2001] ME Classifier Classifying candidates into positive and negative 5,000 English Q-A pairs [Suzuki et al. 2002] SVM Classifier Classifying candidates into positive and negative 1358 Japanese Q-A pairs [Echihabi et al. 2003] N-C Model Selecting correct answer by aligning question with sentences 90,000 English Q-A pairs [Sasaki et al. 2005] ME Classifier Classifying words in sentences into answer and non-answer words 2,000 Japanese Q-A pairs Our U-SVM Model SVM Classifier Classifying question into a set of question-dependent clusters No Q-A pairs question.


In recent years, many supervised machine learning techniques for answer selection in open-domain question answering have been investigated in some pioneering studies [Ittycheriah et al. 2001; Ng et al. 2001; Suzuki et al. 2002; Sasaki, et al. 2005; and Echihabi et al. 2003].


