The method for noun entailment acquisition by (Geffet and Dagan, 2005) is based on the idea of distributional inclusion, according to which one noun is entailed by the other if the set of occurrence contexts of the former subsumes that of the latter. 
The filter relies on the idea that two words that are similar will have similar feature vectors (see Geffet and Dagan, 2005). 
Geffet and Dagan (2005) have extended it to the distributional inclusion hypothesis for recognizing the direction of lexical entailment. 
A similar idea relying on word co-occurrence was proposed by Geffet and Dagan (Geffet and Dagan, 2005)but ourmethodis simpler and we expect it to be applicable to a wider range of vocabularies. 
Extending this rationale to the textual entailment setting, Geffet and Dagan (2005) expected that if the meaning of a word u entails that of v then all its prominent context features (under a certain notion of prominence) would be included in the feature vector of v as well. 
