We can see from Table 7 that the Boulis and Ostendorf (2005) Model Acc. 
Cumulatively up to 20% error reduction is achieved relative to the standard Boulis and Ostendorf (2005) algorithm for classifying individual conversations on Switchboard, and accuracy for gender detection on the Switchboard corpus (aggregate) and Gulf Arabic corpus exceeds 95%. 
8 Application to Arabic Language It would be interesting to see how the Boulis and Ostendorf (2005) model along with the partnerbased model and sociolinguistic features would extend to a new language. 
Cumulatively up to 20% error reduction is achieved relative to the standard Boulis and Ostendorf (2005) algorithm for classifying individual conversations on Switchboard, and accuracy for gender detection on the Switchboard corpus (aggregate) and Gulf Arabic exceeds 95%. 
We can see that the Boulis and Ostendorf (2005) model gives a reasonably high accuracy in Arabic as well. 
