They use a trigram language model and the Arabic morphological analyzer MADA (Habash and Rambow, 2005) respectively, to segment the Arabic side of their corpora. 
(Habash and Rambow, 2005) argue that the rich morphology of Arabic necessitates the use of a morphological analyzer in combination with POS tagging. 
In this paper, we use the MADA (Morphological Analysis and Disambiguation for Arabic) system to diacritize Arabic (Habash and Rambow, 2005; Habash and Rambow, 2007). 
The MorphPart label is positive if the analysis agrees with the gold for each of the 10 basic features used by Habash and Rambow (2005). 
We use the Morphological Analyzer MADA (Habash and Rambow, 2005) to decompose the Arabic source. 
