W07-1806:1	84:145	For example, the recognition grammar from (Rayner et al. , 2005a) is specialised to cover only second-person questions (Do you get headaches in the mornings?), while the generator grammar used in the present application covers only firstperson declarative statements (I visited the doctor last Monday.).
---------------------------------------------------
W07-1806:2	23:145	Our experience is that grammarbased systems which also incorporate probabilistic context-free grammar tuning deliver better results than purely statistical ones when training data are sparse (Rayner et al. , 2005a).
---------------------------------------------------
W07-1806:3	17:145	Regulus has also been used to build several other systems, including NASAs Clarissa (Rayner et al. , 2005b).
---------------------------------------------------
W07-1806:4	127:145	6 Evaluation In previous studies, we have evaluated speech recognition and speech understanding performance for physician-side questions in English (Bouillon et al. , 2005) and Spanish (Bouillon et al. , to appear 2007b), and investigated the impact on performance of the help system (Rayner et al. , 2005a; Starlander et al. , 2005).
---------------------------------------------------
W07-1806:5	80:145	The English (physician) side recogniser is compiled from the large English resource grammar described in Chapter 9 of (Rayner et al. , 2006), and was constructed in the same way as the one described in (Rayner et al. , 2005a), which was used for a headache examination task.
---------------------------------------------------
W09-1503:6	22:190	Prominent examples include NASAs Clarissa Procedure Navigator (Rayner et al., 2005), Geneva Universitys multi-modal mobile-platform Calendar application (Tsourakis et al., 2008), SDS, a prototype in-car system developed by UC Santa Cruz in collaboration with Ford Motors Research which was voted first in Fords 2007 internal technology fair, and Taxi, a speech-enabled game in which the user interacts with a simulated cab driver to navigate around a map of Manhattan.
---------------------------------------------------
W08-1702:7	28:139	Prominent examples are Geneva Universitys MedSLT medical speech translator (Bouillon et al., 2005), NASAs Clarissa procedure browser (Rayner et al., 2005) and Ford Researchs experimental SDS in-car spoken dialogue system, which was awarded first prize at the 2007 Ford internal demo fair.
---------------------------------------------------
W07-1807:8	6:91	Regulus has been used to build several large systems, including Geneva Universitys MedSLT medical speech translator (Bouillon et al. , 2005) and NASAs Clarissa procedure browser (Rayner et al. , 2005b)2.
---------------------------------------------------
W07-1807:9	16:91	In particular, recognisers built in this way are very competitive with ones created using statistical training methods (Rayner et al. , 2005a).
---------------------------------------------------
