Given a ranked selection of words, a language model would then order them appropriately, as described in work on sentence regeneration (for example, see Soricut and Marcu (2005); Wan et al. 
3 Search Algorithms for Coherent Discourses and Utility-Based Training The algorithms we propose use as input representation the IDL-expressions formalism (Nederhof and Satta, 2004; Soricut and Marcu, 2005). 
In the worst case, one can work with simple bags of words that encode no context 1111 preferences (Soricut and Marcu, 2005). 
In Figure 2, we show the IDL-graph corresponding to IDL-expression a15 . 3.2 Search Algorithms Algorithms that operate on IDL-graphs have been recently proposed by Soricut and Marcu (2005). 
The WIDL formalism (Soricut and Marcu, 2005) was proposed to efficiently encode constraints that restricted possible word sequences, for example dependency information. 
