Earlier studies by Dubey and Keller (2003) and Dubey (2005) using the Negra treebank (Skut et al., 1997) reports that lexicalization of PCFGs decrease the parsing accuracy when parsing Negras flat constituent structures. 
(2005)4 92.4 91.6 91.8 91.0 GERMAN Dubey (2005) F1 76.3 This Paper 80.8 80.7 80.1 80.1 CHINESE5 Chiang et al. 
The English, French, German and Spanish test sets were automatically parsedusinghighqualityparsersforthoselanguages (Bikel, 2002; Arun and Keller, 2005; Dubey, 2005; Bick, 2006). 
Combining treebank transformation techniques with a suffix analysis, (Dubey, 2005) trained a probabilistic parser and reached a labelled F-score of 76.3% on phrase structure annotations for a subset of the sentences used here (with a maximum length of 40). 
(2005) 92.4 91.6 91.8 91.0 GERMAN (NEGRA) Dubey (2005) F1 76.3 Petrov and Klein (2007) 80.8 80.7 80.1 80.1 CHINESE Chiang et al. 
