I08-2080:1	14:170	(Mohit and Hwa, 2005) uses syntactic features in building a semi-supervised NE tagger.
---------------------------------------------------
N06-1010:2	160:171	Recently there have been some studies on adapting NER systems to new domains employing techniques such as active learning and semi-supervised learning (Shen et al. , 2004; Mohit and Hwa, 2005), 80 or incorporating external lexical knowledge (Ciaramita and Altun, 2005).
---------------------------------------------------
