For the citation domain, when 20 labeled and 300 unlabeled samples are available, (Grenager et al. , 2005) observed an increase from 65.2% to 71.3%. 
We use the CLASSIFIEDS data (Grenager et al., 2005) which consists of 8767 ads for apartment rental. 
The task of automatically finding and labelling segments in object or event descriptions has been referred to as field segmentation (Grenager et al. , 2005).1 It can be seen as a sequence labelling problem, where each text is viewed as a sequence of tokens and the aim is to assign each token a label indicating to what segment the token belongs (e.g. , BIOTOPE or LOCATION). 
On the test set of (Grenager et al. , 2005), BASE scored an accuracy of 46.4%, comparable to Grenager et al. 
For example, (Grenager et al. , 2005) proposes Diagonal Transition Models for sequential labeling tasks where neighboring words tend to have the same labels. 
