W06-1107:1	198:207	We countered this by normalizing all scores, which was not done in (Filali and Bilmes, 2005).
---------------------------------------------------
W06-1107:2	189:207	In comparison with the results of Filali and Bilmes (2005), certain differences are apparent.
---------------------------------------------------
W06-1107:3	106:207	Filali and Bilmes (2005) proposed to use Dynamic Bayesian Nets (DBNs) for computing word similarity.
---------------------------------------------------
W06-1107:4	130:207	A more detailed description of the models can be found in (Filali and Bilmes, 2005).
---------------------------------------------------
