Its accuracy in some cases is close to that of Smith and Eisners (2005) discriminative model. 
CRF model trained using contrastive estimation (Smith and Eisner, 2005) 88.6 6. 
CE was found to outperform EM on the task of focus in this paper, when applied to English data (Smith and Eisner, 2005b). 
In the first, tag induction systems are allowed the use of a tagging dictionary, which specifies for each word a set of possible parts-of-speech (Merialdo, 1994; Smith and Eisner, 2005; Goldwater and Griffiths, 2007). 
The task in NLP is normally taken to be one of recovering appropriate annotations (Smith and Eisner, 2005) that normally represent constituent structure (strong learning), while in grammatical inference, researchers 126 are more interested in merely identifying the language (weak learning). 
