Prior feature-based methods for this task (Kambhatla 2004; Zhou et al. , 2005) employed a large amount of diverse linguistic features, varying from lexical knowledge, entity mention information to syntactic parse trees, dependency trees and semantic features. 
(2005) and Zhou et al. 
For each pair of entity mentions, we extract and compute various lexical and syntactic features, as employed in a state-of-the-art relation extraction system (Zhou et al., 2005). 
Feature-based methods (Kambhatla, 2004; Zhou et al. , 2005; Zhao and Grishman, 2005 2 ) for this task employ a large amount of diverse linguistic features, such as lexical, syntactic and semantic features. 
Typical works include Miller et al (2000), Zelenko et al (2003), Culotta and Sorensen (2004), Bunescu and Mooney (2005a), Bunescu and Mooney (2005b), Zhang et al (2005), Roth and Yih (2002), Kambhatla (2004), Zhao and Grisman (2005) and Zhou et al (2005). 
