Pantel (2005) defined the task of ontologizing a lexical semantic resource as linking its terms to the concepts in a WordNet-like hierarchy. 
Most recently, Pantel (2005) developed a method to propagate lexical cooccurrence vectors to WordNet synsets, forming ontological co-occurrence vectors. 
Pantel (2005) proposes a framework for ontologizing lexical resources. 
The second way in which word sense and vector space models have been related is to assign disambiguated feature vectors to WordNet concepts (Pantel, 2005; Patwardhan and Pedersen, 2006). 
The first algorithm that we explore, called the anchoring approach, was suggested as a promising avenue of future work in (Pantel 2005). 
