Paiva and Evans trainable generator (2005) produces outputs that correspond to a set of linguistic variables measured in a corpus of target texts.


Existing statistical NLG (i) uses corpus statistics to inform heuristic decisions in what is otherwise symbolic generation (Varges and Mellish, 2001; White, 2004; Paiva and Evans, 2005); (ii) applies n-gram models to select the overall most likely realisation after generation (HALOGEN family); or (iii) reuses an existing parsing grammar or treebank for surface realisation (Velldal et al. , 2004; Cahill and van Genabith, 2006).


4 Conclusion We present a new method for generating linguistic variation projecting multiple personality traits continuously, by combining and extending previous research in statistical natural language generation (Paiva and Evans, 2005; Rambow et al., 2001; Isard et al., 2006; Mairesse and Walker, 2007).


A third SNLG approach eliminates the overgeneration phase (Paiva and Evans, 2005).


Paiva and Evans technique doesnotovergenerate(2005),butitrequiresasearch for the optimal generation decisions according to the learned models.


