Like Zhang and Gildea (2005), it is used to prune bitext cells rather than score phrases. 
Many researchers build alignment links with bilingual corpora (Wu, 1997; Och and Ney, 2003; Cherry and Lin, 2003; Zhang and Gildea, 2005). 
The BOW approach is different from the parsing based approaches (Melamed, 2004; Zhang and Gildea, 2005; Cowan et al. , 2006) where the translation model tightly couples the syntactic and lexical items of the two languages. 
3.1 Pruning and Smoothing We apply one of the pruning techniques used in Zhang and Gildea (2005). 
In recent years, many researchers build alignment links with bilingual corpora (Wu, 1997; Och and Ney, 2003; Cherry and Lin, 2003; Wu et al. , 2005; Zhang and Gildea, 2005). 
