We use features developed in part from those described in Zhou et al (2005) and Wang et al (2006). 
For this task, we used pre-existing dependency converters for TIGER-style trees (Daum et al., 2004) and for TuBa-D/Zstyle trees (Versley, 2005). 
Full details of the classifier are given in Li et al (2005). 
For this task, we used pre-existing dependency converters for TIGER-style trees (Daum et al., 2004) and for TuBa-D/Zstyle trees (Versley, 2005). 
Academic Press, Boston, 1993.</rawString> </citation> <citation valid="true"> <authors> <author>J J Rodrguez</author> </authors> <date>2005</date> <marker>Rodrguez, 2005</marker> <rawString>Rodrguez J. J., et al. 
