For consistency with (Pang and Lee, 2005), supervised metric labeling results with this measure are reported under reg+PSP. Note this method does not use unlabeled data for training either. 
(2003), Pang and Lee (2004, 2005). 
For this we used four different data sets of sentences annotated with sentiment tags:  A set of movie review snippets (further: movie) from (Pang and Lee, 2005). 
In particular Pang and Lee proposed the rating-inference problem (2005). 
We compare our graph-based semi-supervised method with two previously studied methods: regression and metric labeling as in (Pang and Lee, 2005). 
