the dialogue can be mostly initiated by the doctor, with the patient giving only non-verbal responses (Bouillon et al. , 2005), or may be an explicit design decision: There is, however, an assymmetry in the dialogue management in control, given the desire for the English-speaking doctor to be in control of the device and the primary director of the dialog.


(Ettelaie et al. , 2005, 89) [emphasis added] It is understandable that as a regular user, the medical professional may eventually have more familiarity with the system, but this should be reflected in there being different user-interfaces (see Somers and Lovel 2003).


(2005) Incorporating more symbolic graphics into an interface is an area of complexity, as Johnson et al.


