Recently, the discourse coherence modeling community has started using the information ordering task as a testbed to test their discourse coherence models (Barzilay and Lapata, 2005; Soricut and Marcu, 2006). 
(2004) using the data of Barzilay and Lapata (2005). 
To model transitions in this entity grid model, Lapata and Barzilay (2005) takes a generative approach. 
Recently there has been a lot of work in discourse coherence modeling (Lapata, 2003; Barzilay and Lapata, 2005; Soricut and Marcu, 2006) that has used 173 information ordering to test the coherence models. 
4.ExperimentalData We made use of the data of Dimitromanolaki and Androutsopoulos (2003), the GNOME corpus (Poesio et al. 2004), and the two corpora that Barzilay and Lapata (2005) experimented with. 
