W06-2505:1	18:182	For multilingual applications, a popular approach is to carry out monolingual WSD and then map the source language senses into the corresponding target word translations (Carpuat and Wu, 2005; Montoyo et al. , 2002).
---------------------------------------------------
W06-2505:2	13:182	Conversely, Carpuat and Wu (2005) found that WSD does not yield significantly better translation quality than a statistical MT system alone.
---------------------------------------------------
W07-0719:3	207:244	5 Related Work Recently, there is a growing interest in the application of WSD technology to MT. For instance, Carpuat and Wu (2005b) suggested integrating WSD predictions into a SMT system in a ?hard??
---------------------------------------------------
W07-0719:4	214:244	In a later work, Carpuat and Wu (2005a) analyzed the converse question, i.e. they measured the WSD performance of SMT models.
---------------------------------------------------
E06-1032:5	156:157	For example, work which failed to detect improvements in translation quality with the integration of word sense disambiguation (Carpuat and Wu, 2005), or work which attempted to integrate syntactic information but which failed to improve Bleu (Charniak et al. , 2003; Och et al. , 2004) may deserve a second look with a more targeted manual evaluation.
---------------------------------------------------
I05-2021:6	133:135	Puzzlingly, in converse experiments, using a state-of-theart WSD model to choose translation candidates for a typical IBM SMT system, we find that WSD does not yield significantly better translation quality than the SMT system alone (Carpuat and Wu, 2005).
---------------------------------------------------
I05-2021:7	18:135	In other work, we have been conducting comparative studies testing whether state-of-the-art WSD mod120 els can improve SMT translation quality (Carpuat and Wu, 2005).
---------------------------------------------------
P07-1005:8	133:177	Though the improvement is modest, it is statistically significant and this positive result is important in view of the negative findings in (Carpuat and Wu, 2005) that WSD does not help MT. Furthermore, note that Hiero+WSD has higher n-gram precisions than Hiero.
---------------------------------------------------
P07-1005:9	123:177	This is higher than the score of 28.77 reported in (Chiang, 2005), perhaps due to differences in word segmentation, etc. Note that comparing with the MT systems used in (Carpuat and Wu, 2005) and (Cabezas and Resnik, 2005), the Hiero system we are using represents a much stronger baseline MT system upon which the WSD system must improve.
---------------------------------------------------
P07-1005:10	16:177	Carpuat and Wu (2005) integrated the translation predictions from a Chinese WSD system (Carpuat et al. , 2004) into a ChineseEnglish word-based statistical MT system using the ISI ReWrite decoder (Germann, 2003).
---------------------------------------------------
P07-1005:11	27:177	Note that the experiments in (Carpuat and Wu, 2005) did not use a state-of-the-art MT system, while the experiments in (Vickrey et al. , 2005) were not done using a full-fledged MT system and the evaluation was not on how well each source sentence was translated as a whole.
---------------------------------------------------
D07-1007:12	18:218	61 and unsupervised, on a Senseval WSD task (Carpuat and Wu, 2005a), and therefore suggest that WSD should have a role to play in state-of-the-art SMT systems.
---------------------------------------------------
D07-1007:13	26:218	Rather than using a generic Senseval WSD model as we did in Carpuat and Wu (2005b), here both the WSD training and the WSD predictions are integrated into the phrase-based SMT framework.
---------------------------------------------------
D07-1007:14	24:218	The main difference between this approach and several of our earlier approaches as described in Carpuat and Wu (2005b) and subsequently Carpuat et al.
---------------------------------------------------
D07-1007:15	11:218	On the one hand, in previous work (Carpuat and Wu, 2005b) we obtained disappointing results when using the predictions of a Senseval WSD system in conjunction with a standard word-based SMT system: we reported slightly lower BLEU scores despite trying to incorporate WSD using a number of apparently sensible methods.
---------------------------------------------------
H05-1097:16	223:225	Carpuat and Wu (2005) recently observed that simpler integration approaches, such as forcing the machine translation system to use the word translation models first choice, do not improve translation results.
---------------------------------------------------
H05-1097:17	133:225	For example, Carpuat and Wu (2005) obtain negative results for two methods of incorporating the output of a word-sense disambiguation system into a machine translation system.
---------------------------------------------------
