The development of an integrated multi-modal model of referring behavior can improve the performance of state-of-the-art computational models of communication currently used to support conversational interactions with an intelligent agent (Allen et al. , 2005; Devault et al. , 2005; Gorniak & Roy, 2004).


It was hooking students up with the systems that were being actively developed in ongoing research (DeVault et al. , 2005).


