P06-1047:1	58:181	The same idea was followed and investigated exten370 sively (Mihalcea, 2005).
---------------------------------------------------
D07-1047:2	20:279	Graph-based methods have also been employed (Erkan and Radev, 2004a; Erkan and Radev, 2004b; Mihalcea, 2005; Mihalcea and Tarau, 2005; Mihalcea and Radev, 2006).
---------------------------------------------------
D07-1047:3	29:279	Although some recent systems indicate an improvement over the baseline (Mihalcea, 2005; Mihalcea and Tarau, 2005), statistical significance has not been shown.
---------------------------------------------------
W07-0203:4	180:307	Since Mihalceas setting was kept unchanged, we just included in that table the same results presented in (Mihalcea, 2005), i.e., we did not run her systems all over again.
---------------------------------------------------
W07-0203:5	70:307	For this reason Mihalcea (2005) could use it to evaluate AS on texts in Brazilian Portuguese, besides reporting results on texts in English.
---------------------------------------------------
W07-0203:6	15:307	Usually, extractive AS does not take into account linguistic and semantic knowledge in order to be portable to distinct domains or languages (Mihalcea, 2005).
---------------------------------------------------
W07-0203:7	173:307	In our assessment, the same single-document summarization scenario posed by Mihalcea (2005) was adopted, namely: (a) we considered the Brazilian Portuguese TeMrio corpus (Pardo and Rino, 2003); (b) we used the same baseline, which selects top-first sentences to include in the extract; (c) we adopted a 70-75% compression rate, making it compatible with the compression rate of the reference summaries; and (d) ROUGE was used for evaluation in its Ngram(1,1) 95% confidence rate setting, without stopwords removal.
---------------------------------------------------
