The literature suggested two methods of determining polarity, and they are analogous to the distributional and co-occurrence-based approaches in word clustering (Takamura et al., 2005; Higashiyama et al., 2008). 
2.2 Identification of Semantic Orientations The semantic orientation classification of words has been pursued by several researchers (Hatzivassiloglou and McKeown, 1997; Turney and Littman, 2003; Kamps et al. , 2004; Takamura et al. , 2005). 
Takamura et al. built lexical network from not only such co-occurrence but other resources including thesaurus (Takamura et al. , 2005). 
Many papers assume that subjectivity recognition, i.e. separating subjective from objective words, has already been achieved prior to polarity recognition and test against word lists containing subjective words only (Hatzivassiloglou and McKeown, 1997; Takamura et al., 2005). 
Most recently, (Takamura et al. , 2005) reports on the use of spin models to infer the semantic orientation of words. 
