The application of world knowledge to pronoun resolution has been limited to the semantic compatibility between a candidate noun and the pronouns context (Yang et al. , 2005).


Ideally we would assess the bene t of our probabilistic features using the same state-of-the-art preprocessing modules employed by others such as (Yang et al. , 2005) (who additionally use a search engine for compatibility scoring).


For example, Yang et al (2005) proposed a template-based statistical approach to compute the semantic compatibility between a pronominal anaphor and an antecedent candidate, and Yang and Su (2007) explored semantic relatedness information from automatically discovered patterns, while Ng (2007) automatically induced semantic class knowledge from a treebank and explored its application in coreference resolution.


Besides the common practice of employing a thesaurus (e.g. WordNet) in semantic consistency checking, much research has been done to explore various kinds of semantic information, such as semantic similarity (Harabagiu et al 2000), semantic compatibility (Yang et al 2005, 2007), and semantic class information (Soon et al 2001; Ng 2007).


