Because the problem is NP-complete (Althaus et al. , 2005), it is critical how coherence model evaluation is intertwined with search: if the search for the best ordering is greedy and has many errors, one is not able to properly evaluate whether a model is better than another. 
To our knowledge, the best results on this dataset were obtained by the meta-classification scheme of Ng (2005). 
Using graph partitioning, McCallum & Wellner (2005) incorporated transitivity into pairwise classification and achieved the state-of-the-art result on the MUC-6 dataset, but their approach can only leverage one binary relation at a time, not arbitrary relations among mentions. 
Perhaps the most related is 86 learning as search optimization (LASO) (Daume III and Marcu, 2005b; Daume III and Marcu, 2005a). 
This could be incorporated in a ranking scheme, as in Ng (2005). 
