CRFs have been applied with impressive empirical results to the tasks of named entity recognition (McCallum and Li, 2003; Cohn et al. , 2005), part-of-speech (PoS) tagging (Lafferty et al. , 2001), noun phrase chunking (Sha and Pereira, 2003) and extraction of table data (Pinto et al. , 2003), among other tasks.


Usually these experts are designed to 4 See (Cohn et al. , 2005) for a scaling method allowing the full POS tagging task with CRFs.


