3 Paraphrasing with parallel corpora Bannard and Callison-Burch (2005) extract paraphrases from bilingual parallel corpora. 
Translation-based conditional probability Bannard and Callison-Burch (2005) proposed a probabilistic model for acquiring phrasal paraphrases 1 . The likelihood of t as a paraphrase of the given phrase s is defined as follows: P(t|s)= summationdisplay ftr(s)tr(t) P(t|f)P(f|s), where tr(e) stands for a set of foreign language phrases that are aligned with e in the given parallel corpus. 
Baseline  The paraphrase probability defined by Bannard and Callison-Burch (2005). 
In this approach proposed by (Bannard and Callison-Burch, 2005), the second language acts as a pivot, as illustrated on figure 1. 
Bannard and Callison-Burch (2005) first exploited bilingual corpora for phrasal paraphrase extraction. 
