D09-1119:1	64:258	SVMs with a polynomial kernel of degree 2 were shown to provide state-of-the-art performance in many NLP application, see for example (Kudo and Matsumoto, 2000; Nivre et al., 2006; Isozaki and Kazawa, 2002; Goldberg et al., 2006).
---------------------------------------------------
P07-1029:2	71:237	For the Hebrew experiments, we use the corpora of (Goldberg et al. , 2006).
---------------------------------------------------
P07-1029:3	83:237	These are the same settings as in (Kudo and Matsumoto, 2000; Goldberg et al. , 2006).
---------------------------------------------------
P07-1029:4	26:237	In (Goldberg et al. , 2006) we argued that it is not applicable to Hebrew, mainly because of the prevalence of the Hebrews construct state (smixut).
---------------------------------------------------
P07-1029:5	117:237	A 10-fold cross validation experiment on punctuation normalized HEBErr resulted in an F-Score of 92.2, improving the results reported by (Goldberg et al. , 227 2006) on the same setting (91.4).
---------------------------------------------------
P07-1029:6	11:237	In (Goldberg et al. , 2006), we established that the task is not trivially transferable to Hebrew, but reported that SVM based chunking (Kudo and Matsumoto, 2000) performs well.
---------------------------------------------------
W07-2219:7	50:344	To illustrate the extent and the complexity of that matter let us consider definiteness in MH, which is morphologically marked (as an h prefix to the stem, glossed here explicitly as the-) and behaves as a syntactic 3See (Wintner, 2000) and (Goldberg et al. , 2006) for formal and statistical accounts (respectively) of noun phrases in MH.
---------------------------------------------------
W07-2219:8	207:344	6 Related Work The MH treebank (Simaan et al. , 2001), a morphologically and syntactically annotated corpus, has been successfully used for various NLP tasks such as morphological disambiguation, POS tagging (BarHaim et al. , 2007) and NP chunking (Goldberg et al. , 2006).
---------------------------------------------------
