Exp. Learning algorithm F-measure # of samples to label 1 Supervised 0.739 80,094 2 Active Learning (Kuo et al., 2006) 0.710 8,191 3 Unsupervised (V1) 0.680 100 4 Co-training (V1+V4) 0.716 100 5 Co-training (V1+V2) 0.726 100 6 Co-EM (V1+V2) 0.725 100 Table 4. 
The live Web corpus was used in transliteration extraction using active learning (Kuo et al., 2006). 
We have 0H , which hypothesizes that CWand EW  form an E-C pair, and 1H , which hypothesizes otherwise, and use posterior odd  (Kuo et al., 2006) for hypothesis tests. 
Inspired by this observation in CJK texts, some algorithms were proposed (Kuo et al., 2006) to search over the close context of an English word in a Chinese predominant bilingual snippet for transliteration. 
We include the results from previously reported work (Kuo et al., 2006) into Table 4 (see Exp. 2) where multiple features are fused in a single active learning process. 
