P06-1131:1	163:192	We take R1 as first candidate landmark, and check for topological proximity in the scene as modeled in (Kelleher et al. , 2006).
---------------------------------------------------
P06-1131:2	110:192	We handle the issue of frame of reference ambiguity and model the semantics of projective prepostions using the framework developed in (Kelleher et al. , 2006).
---------------------------------------------------
P06-1131:3	192:192	For more detail, see (Kruijff et al. , 2006a; Kruijff et al. , 2006b).
---------------------------------------------------
P06-1131:4	106:192	We use the model of topological proximity developed in (Kelleher et al. , 2006) to model all the relations at this level.
---------------------------------------------------
