For ESL applications, this includes the detection of errors involving articles (Han et al., 2006; De Felice and Pulman, 2008; Gamon et al., 2008), prepositions (De Felice and Pulman, 2008; Gamon et al., 2008; Tetreault and Chodorow, 2008), verb forms (Lee and Seneff, 2008b), mass/count noun confusions(Brockett et al., 2006) and word order (Metcalf and Meurers, 2006).


Moreover, these approaches, e.g., (Izumi et al. , 2003; Brockett et al. , 2006) usually need errors to be specified and tagged in the training sentences, which requires expert help to be recruited and is time consuming and labor intensive.


Instead of asking experts to write hand-crafted rules, statistical approaches (Chodorow and Leacock, 2000; Izumi et al. , 2003; Brockett et al. , 2006; Nagata et al. , 2006) build statistical models to identify sentences containing errors.


The phrasal Statistical Machine Translation (SMT) technique is employed to identify and correct writing errors (Brockett et al. , 2006).


Some researchers explicitly focus on individual classes of er93 rors, e.g., mass vs count nouns in (Brockett et al. , 2006) and (Nagata et al. , 2006).


