Asforthequalitativedifferenceofcategorytypes, the result also shows the effectiveness of modication (ncmod) category, which is consistent with the result (Hagiwara et al., 2006) that mod is more contributing than subj and obj, which have been extensively used in the past.


There are also some existing studies which paid attention to the comparison of context categories for synonym acquisition (Curran and Moens, 2002a; Hagiwara et al., 2006).


