I08-1046:1	12:191	Our work sits squarely in the realm of work on regular IE done by (Zelenko et al., 2003; Zhou et al., 2005; Chen et al., 2006).
---------------------------------------------------
P07-1125:2	45:186	Other relevant recent work includes (Zhang, 2004), in which random feature projection and a committee of SVM classifiers is used in a hybrid co/self-training strategy for weakly supervised relation classification and (Chen et al. , 2006) where a graph based algorithm called label propagation is employed to perform weakly supervised relation extraction.
---------------------------------------------------
P07-1125:3	114:186	In the same vein, for the case of entity/relation extraction and classification (Collins and Singer, 1999; Zhang, 2004; Chen et al. , 2006) the context of the entity or entities in consideration provides a highly relevant feature space.
---------------------------------------------------
N07-1026:4	44:191	In NLP, label propagation has been used for word sense disambiguation (Niu et al. , 2005), document classi cation (Zhu, 2005), sentiment analysis (Goldberg and Zhu, 2006), and relation extraction (Chen et al. , 2006).
---------------------------------------------------
D09-1149:5	20:194	However, current systems (Zhang, 2004; Chen et al., 2006) use a randomly sampling strategy, which fails to explore the affinity nature among the training instances.
---------------------------------------------------
D09-1149:6	10:194	This paper focuses on the ACE RDC subtask, where many machine learning methods have been proposed, including supervised methods (Miller et al., 2000; Zelenko et al., 2002; Culotta and Soresen, 2004; Kambhatla, 2004; Zhou et al., 2005; Zhang et al., 2006; Qian et al., 2008), semi-supervised methods (Brin, 1998; Agichtein and Gravano, 2000; Zhang, 2004; Chen et al., 2006; Zhou et al., 2008), and unsupervised methods (Hasegawa et al., 2004; Zhang et al., 2005).
---------------------------------------------------
D09-1149:7	176:194	Comparison of Stratified Bootstrapping with Bootproject and Label propagation Table 4 compares Bootproject (Zhang, 2004), Label propagation (Chen et al., 2006) with our Stratified Bootstrapping on the 5 major types of the ACE RDC 2003 corpus.
---------------------------------------------------
D09-1149:8	185:194	By contrast, even small size of labeled instances can be fully utilized to correctly induce the unlabeled instances via LP algorithm due to its ability to exploit manifold structures of both labeled and unlabeled instances (Chen et al., 2006).
---------------------------------------------------
P09-1081:9	16:188	Recent research indicates that using labeled and unlabeled data in semi-supervised learning (SSL) environment, with an emphasis on graph-based methods, can improve the performance of information extraction from data for tasks such as question classification (Tri et al., 2006), web classification (Liu et al., 2006), relation extraction (Chen et al., 2006), passage-retrieval (Otterbacher et al., 2009), various natural language processing tasks such as partof-speech tagging, and named-entity recognition (Suzuki and Isozaki, 2008), word-sense disam719 biguation (Niu et al., 2005), etc. We consider situations where there are much more unlabeled data, XU, than labeled data, XL, i.e., nL lessmuch nU.
---------------------------------------------------
