of techniques have been considered including approaches based on machine translation techniques (Papineni et al. , 1997; Ramaswamy and Kleindienst, 2000; Wong and Mooney, 2006), parsing techniques (Miller et al. , 1996; Ge and Mooney, 2006), techniques that use inductive logic programming (Zelle and Mooney, 1996; Thompson and Mooney, 2002; Tang and Mooney, 2000; Kate et al. , 2005), and ideas from string kernels and support vector machines (Kate and Mooney, 2006; Nguyen et al. , 2006).


and Mooney, 2005; Nguyen et al., 2006).


