For example, some devise heuristic statistical scores and report their impact on precision (Chklovski and Pantel, 2005; Torisawa, 2006; Zanzotto et al., 2006).


Motivated by this issue, several research groups have reported their experiments on automatic acquisition of causal, temporal and entailment relations between event expressions (typically verbs or verb phrases) (Lin and Pantel, 2001; Inui et al., 2003; Chklovski and Pantel, 2005; Torisawa, 2006; Pekar, 2006; Zanzotto et al., 2006; Abe et al., 2008, etc.).


