While word alignments can help identifying semantic relations (van der Plas and Tiedemann, 2006), we proceed in the reverse direction.


All categorised named entities with relative frequencies under 0.05 3In van der Plas and Tiedemann (2006) there is more information on the syntax-based and alignment-based distributional methods.


Recently several studies have proposed to utilize a second language or several specified languages in order to extract or extend concepts (Vintar and Fiser, 2008; van der Plas and Tiedemann, 2006) or paraphrases (Bosma and Callison-Burch, 2007).


