W07-2052:1	75:76	We also tried to use features in verb ontology such as VERBOCEAN (Chklovsky and Pantel, 2004) which is used in (Mani et al. , 2006).
---------------------------------------------------
I08-4005:2	20:246	To extract temporal relations, several knowledge resources are necessary, such as tense and aspect of verbs, temporal adverbs, and world knowledge (Mani, et al., 2006).
---------------------------------------------------
P08-1090:3	160:258	793 There are a number of algorithms for determining the temporal relationship between two events (Mani et al., 2006; Lapata and Lascarides, 2006; Chambers et al., 2007), many of them trained on the TimeBank Corpus (Pustejovsky et al., 2003) which codes events and their temporal relationships.
---------------------------------------------------
W07-2014:4	15:139	TimeML and TimeBank have already been used as the basis for automatic time, event and temporal relation annotation tasks in a number of research projects in recent years (Mani et al. , 2006; Boguraev et al. , forthcoming).
---------------------------------------------------
P09-1046:5	8:207	With the introduction of the TimeBank corpus (Pustejovsky et al., 2003), a set of documents annotated with temporal information, it became possible to apply machine learning to temporal ordering (Boguraev and Ando, 2005; Mani et al., 2006).
---------------------------------------------------
P09-1046:6	46:207	Most previous work on temporal relation identification (Boguraev and Ando, 2005; Mani et al., 2006; Chambers and Jurafsky, 2008) is based on the TimeBank corpus.
---------------------------------------------------
I08-1064:7	64:193	We are using the components for timex recognition and normalisation (Mani and Wilson, 2000), event extraction (Saur et al., 2005a), and identification of modal contexts (Saur et al., 2006).3 3 Informed Projection 3.1 The Core Algorithm Recall that TimeML represents temporal entities with EVENT and TIMEX3 tags which are anchored to words in the text.
---------------------------------------------------
W07-2098:8	9:77	1 Introduction The Sheffield team were involved in TempEval as co-proposers/co-organisers of the task.1 For our participation in the task, we decided to pursue an MLbased approach, the benefits of which have been explored elsewhere (Boguraev and Ando, 2005; Mani et al. , 2006).
---------------------------------------------------
W06-0904:9	16:179	While there has been a spurt of recent research addressing the event ordering problem, e.g., (Mani and Wilson 2000) (Filatova and Hovy 2001) (Schilder and Habel 2001) (Li et al. 2001) (Mani et al. 2003) (Li et al. 2004) (Lapata and Lascarides 2004) (Boguraev and Ando 2005) (Mani et al. 2006), that research relies on qualitative temporal relations.
---------------------------------------------------
C08-3012:10	5:82	To explicitly mark the needed temporal relations the project delivered a series of tools for extracting time expressions, events, subordination relations and temporal relations (Verhagen et al., 2005; Mani et al., 2006; Saur et al., 2005; Saur et al., 2006a).
---------------------------------------------------
W09-2422:11	6:149	In recent years, with the advent of the TimeML markup language (Pustejovsky et al., 2003) and the creation of the TimeBank resource (Pustejovsky et al., 2003) interest has focussed on the application of a variety of automatic techniques to this task (Boguraev and Ando, 2005; Mani et al., 2006; Bramsen et al., 2006; Chambers et al., 2007; Lee and Katz, 2008).
---------------------------------------------------
C08-1108:12	21:208	This technical report addresses two problems found in (Mani et al., 2006): (1) feature vector duplication caused by the data normalization process (once fixed, the accuracy drops to 76.56% and 83.23%) and (2) a somewhat unrealistic evaluation scheme (we describe Mani et al.
---------------------------------------------------
C08-1108:13	20:208	(2006)s research is briefly described in (Mani et al., 2007).
---------------------------------------------------
C08-1108:14	54:208	We note that our experimental setup is closer to the one used in (Mani et al., 2006; Mani et al., 2007).
---------------------------------------------------
C08-1108:15	110:208	Unlike (Mani et al., 2006), the accuracy of Accuracy for event-event relations Training data Original test Closed test Train (845) (4,189) ME models Original (2,466) 50.4 46.1 83.3 Closed (8,616) 47.0 41.0 76.1 SVM models Original (2,466) 56.9 45.8 74.2 Closed (8,616) 52.4 52.0 77.5 Table 3: Event-event temporal resolution the learned classifiers drops when they are trained on the closed training dataset.
---------------------------------------------------
C08-1108:16	37:208	In (Mani et al., 2006; Mani et al., 2007), event-event temporal relations are discourse-wide, i.e. any pair of events can be temporally linked.
---------------------------------------------------
C08-1108:17	51:208	2.2 Data normalization Similar to (Mani et al., 2006; Mani et al., 2007), we use a normalized version of the 14 temporal relations annotated in TimeBank where the inverse relations are removed and simultaneous and identity are collapsed as well as during and is included.
---------------------------------------------------
P07-2044:18	10:115	The highest score reported on Timebank achieved 62.5% accuracy when using gold-standard features as marked by humans (Mani et al. , 2006).
---------------------------------------------------
I08-1054:19	39:141	As such, it emphasizes robustness at Web scale, without taking advantage of existing speci cation languages for representing events and temporal expressions occurring in text (Pustejovsky et al., 2003), and forgoing the potential bene ts of more complex methods that extract temporal relations from relatively clean text collections (Mani et al., 2006).
---------------------------------------------------
D08-1073:20	32:237	The first is based on previous work (Mani et al., 2006; Chambers et al., 2007) and the second is a novel contribution to event-event classification.
---------------------------------------------------
D08-1073:21	72:237	4.3 Transitive Closure In order to connect the event graph, we draw on work from (Mani et al., 2006) and apply transitive closure to our documents.
---------------------------------------------------
D08-1073:22	18:237	2 Previous Work Recent work on classifying temporal relations within the Timebank Corpus built 6-way relation classifiers over 6 of the corpus 13 relations (Mani et al., 2006; Mani et al., 2007; Chambers et al., 2007).
---------------------------------------------------
