However, the best Chinese parser ever reported (Wang et al., 2006) achieves 0.882 F-score for sentences with less than 40 words, we therefore conclude that the way using auto-parser for Chinese function labeling is not the optimal choice.


For Chinese segmentation, a maximum-entropy based parser was used (Wang et al. , 2006).


The TNT-based tagger provided 91.52% accuracy, the comparative result with (Wang et al., 2006).


4 To know whether our POS tagger is good, we also tested the TNT package on the standard training and testing sets for full parsing (Wang et al., 2006).


Table 3 shows the results achieved by our method and other researchers (UAS with p), where Wang05 refers to (Wang et al., 2005), Wang07 refers 92 to (Wang et al., 2007), and McDonald&Pereira06 5 refers to (McDonald and Pereira, 2006).


