The 307 relationship between word alignments and their impact on MT is also investigated in (Ayan and Dorr, 2006; Lopez and Resnik, 2006; Fraser and Marcu, 2006). 
From Ayan and Dorr (2006), grow-diag-final heuristic. 
This is similar to the loose phrases described in (Ayan and Dorr, 2006a), which increased the number of correct phrase translations and improved the translation quality. 
85 Recently some alignment evaluation metrics have been proposed which are more informative when the alignments are used to extract translation units (Fraser and Marcu, 2006; Ayan and Dorr, 2006). 
We replace these with the maximum entropy aligments of Ayan and Dorr (2006b). 
