4.3 Using Unlabeled Data for Parsing Recent studies on parsing indicate that the use of unlabeled data by self-training can help parsing on the WSJ data, even when labeled data is relatively large (McClosky et al., 2006a; Reichart and Rappoport, 2007). 
Theyalsoappliedself-training to domain adaptation of a constituency parser (McClosky et al., 2006b). 
Indeed, in the II scenario, (Steedman et al. , 2003a; McClosky et al. , 2006a; Charniak, 1997) reported no improvement of the base parser for small (500 sentences, in the first paper) and large (40K sentences, in the last two papers) seed datasets respectively. 
(2006) and McClosky et al. 
This second point is emphasized by the second paper on self-training for adaptation (McClosky et al., 2006b). 
