(2006) and Sekine (2006) used syntactic paraphrases to obtain patterns for extracting relations. 
Shinyama and Sekines preemptive IE system (2006) discovers relationships from sets of related news articles. 
This contrasts with Open Information Extraction (Banko and Etzioni, 2008) and On-Demand Information Extraction (Sekine, 2006), which aim to extract large databases of open-ended facts, and with supervised relation extraction, which requires additional supervised data to learn new relations. 
2 Related Work Our system was inspired by the preemptive and ondemand IE approaches by Sekine and Shinyama (Sekine, 2006; Shinyama, 2006) that cluster newspaper articles into classes of articles that talk about the same type of event. 
Sekine (2006) developed a paradigm for ondemand information extraction in order to reduce the amount of effort involved when porting IE systems to new domains. 
