1 Introduction Many studies in natural language processing are concerned with how to generate definite descriptions that evoke a discourse entity already introduced in the context (Dale, 1989; Dale and Haddock, 1991; Dale and Reiter, 1995; van Deemter, 2002; Krahmer et al., 2002; Gardent, 2002; Horacek, 2003), and more recently (Viethen and Dale, 2006; Gatt and van Deemter, 2006; Croitoru and van Deemter, 2007).


2 Spatial Relations in Referring Expression Generation The bulk of the existing literature on referring expression generation (see, for example, Dale (1989), Dale and Reiter (1995), van Deemter (2006), Horacek (2004), Gatt and van Deemter (2006)) generally focuses on the use of non-relational properties, which can either be absolute (for example, colour) or relative (for example, size).


1 Introduction In recent years, researchers working on referring expression generation have increasingly moved towards collecting their own data on the human production of referring expressions (REs) (Krahmer and Theune, 2002; van der Sluis and Krahmer, 2004; Gatt and van Deemter, 2006; Belz and Varges, 2007); and the recent Attribute Selection in the Generation of Referring Expressions (ASGRE) Challenge used the TUNA corpus (Gatt et al., 2007), which is the most extensive collection of referring expressions to date.


