This has the effect of enhancing the system performance and allow us to make a comparison with other systems, such as (Habash and Rambow, 2007) and (Zitouni et al. , 2006) . 
Much work has been done on automatic Arabic diacritization (Vergyri and Kirchhoff, 2004; Ananthakrishnan et al., 2005; Zitouni et al., 2006; Habash and Rambow, 2007). 
4 Related Work We review three approaches that are directly relevant to us; we refer to the excellent literature review in (Zitouni et al. , 2006) for a general review. 
There are many related works dealing with the problem of Arabic diacritization in general (Zitouni et al., 2006), (Habash and Rambow, 2007), (Ananthakrishnan, 2005), (Kirchhoff, 2005). 
Similar drops have been observed by other researchers (Nelken and Shieber, 2005; Zitouni et al. , 2006). 
