Features Our feature set consists of (1) baseline features motivated by those used in Dandapat et al.s (2007) Bengali POS tagger and Singh et al.s (2006) Hindi POS tagger, as well as (2) features derived from our induced affixes and the Wikipedia-induced list.


System using a decision tree based learning algorithm (CN2) has been developed for statistical Hindi POS tagging (Singh et al. , 2006).


A POS tagger for Hindi overcomes the handicap of annotated corpora scarcity by exploiting the rich morphology of the language (Singh et al., 2006).


