While several text segmentation systems have been proposed to date, we decided to use a graphbased segmentation algorithm using normalizedcuts (Malioutov and Barzilay, 2006), shown to exceed the performance of alternative segmentation methods. 
In the physics lecture corpus used by Malioutov and Barzilay (2006), there are roughly 100 sentences per segment. 
This is common practice for this task, as the desired number of segments may be determined by the user (Malioutov and Barzilay, 2006). 
uation uses source code provided by Malioutov and Barzilay (2006). 
For the segmentation task, we compare to BayesSeg (Eisenstein and Barzilay, 2008),10 a Bayesian topic-based segmentation model that outperforms previous segmentation approaches (Utiyama and Isahara, 2001; Galley et al., 2003; Purver et al., 2006; Malioutov and Barzilay, 2006). 
