These algorithms only recover the sequence of subtasks but not the hierarchical structure of subtasks similar to Bangalore et al.s (2006) chunk-based model.


Nevertheless, analyzing a corpus of dialogs by hand requires a great deal of human effort (Bangalore et al., 2006).


This is contrasted with a dialog structure recognition process (Alexandersson and Reithinger, 1997; 955 Bangalore et al., 2006; Hardy et al., 2004), where pre-specified dialog structure components are recognized as a dialog progresses.


We call this model a chunk-based dialog model (Bangalore et al., 2006).


In addition, there has been research on how to automatically learn models of taskoriented discourse structure using dialog act and task information (Bangalore et al., 2006).


