4Since in most word nets cross-POS relations are very sparse, researchers currently investigate relation types able to connect the noun, verb, and adjective sub-graphs (e.g. Marrafa and Mendes (2006) or Lemnitzer et al.


In related research over adjectives, Alonge et.al (2000), Solar (2003), Marrafa and Mendes (2006) suggested that WordNet and EuroWordNet lack sufficient adjectival classes and semantic relations, and  extended the resources over such relations.


