In future work we also intend to use feature selection techniques (e.g. correlation-based feature subset (CFS) evaluation (Rieser and Lemon, 2006)) on the COMMUNICATOR data (Georgila et al. , 2005a; Walker et al. , 2001) in order to identify additional context features that it may be effective to represent in the state. 
The simulations are evaluated using the SUPER metric proposed earlier (Rieser and Lemon, 2006a), which measures variance and consistency of the simulated behaviour with respect to the observed behaviour in the original data set. 
We also intend to use feature selection techniques (e.g. CFS subset evaluation (Rieser and Lemon, 2006)) on in order to determine which contextual features this suggests are important. 
For training, we therefore use a cluster-based user simulation method, see (Rieser 641 and Lemon, 2006a). 
As input features we use annotated dialogue context features, see (Rieser and Lemon, 2006b). 
