K?ubler (2005) and Maier (2006) show that treebank annotation schemes have considerable in uence on parsing results. 
comparable to Maier (2006), which found 36% improvement using an unlexicalized PCFG; these absolute improvements hold despite the fact that the Maier (2006) parser has results with 24% absolute lower F1 than those in this paper. 
There is evidence that the use of topological fields is advantageous also for other parsing approaches (Frank et al. , 2003; Kubler, 2005; Maier, 2006). 
5 Experiment II K?ubler (2005) and Maier (2006) assess the impact of the different treebank annotation schemes on PCFG parsing by conducting a number of modi cations converting the T?uBa-D/Z into a format more similar to the NEGRA (and hence TIGER) treebank. 
For this reason, Kubler (2005) and Maier (2006) tested a version of Negra which contained information of the original attachment site of these discontinuous constituents. 
