Figure 14 because they are similar to CEs. 1http://people.csail.mit.edu/jrennie/ 20Newsgroups 775 2.2 Other Settings For CE collection, character bigrams are chosen to be the indexing unit for its high performance (Li et al. , 2006); but the bigram term set suffers from its high dimensionality.


We choose a Chinese corpus as the primary document collection because Chinese text (as well as other Asian languages) has a very large term set and a satisfying subset is usually not smaller than 50000 (Li et al. , 2006); on the contrary, a dimensionality lower than 10000 suffices a general English text categorization (Yang and Pedersen, 1997; Rogati and Yang, 2002).


