Abekawa and Okumura (2006) proposed a reranking method of k-best dependency analyzer outputs using cooccurrence information.


Related research includes Abekawa and Okumura (2006) and Kawahara and Kurohashi (2006) where statistical information between verbs and case elements is collected on the basis of large automatically analysed corpora.


Case element remembers the bi-lexical dependency relation between all types of headmodifier pairs, which is also recognized in previous work (Wu, 2003; Han et al., 2004; Kawahara and Kurohashi, 2006(a); Abekawa and Okumura, 2006).


In this paper, we propose a new type of Chinese case structure, which is different from those presented in previous work (Wu, 2003; Han et al., 2004; Kawahara and Kurohashi, 2006(a); Abekawa and Okumura, 2006) in two aspects: (1) It relaxes the predicate of a case structure to be all types of words which behaves as a head; (2) It is not categorized by semantic roles but marked by the neighboring modifiers attached to a head.


Researchers have applied case structures to Japanese syntactic analysis and improved parsing accuracy successfully (Kawahara and Kurohashi, 2006(a); Abekawa and Okumura, 2006).


