Most related work deals with discovery of hypernymy (Hearst, 1992; Pantel et al, 2004), synonymy (Roark and Charniak, 1998; Widdows and Dorow, 2002; Davidov and Rappoport, 2006) and meronymy (Berland and Charniak, 1999). 
3.2 Pattern Specification To specify patterns, following (Davidov and Rappoport, 2006) we classify words into highfrequency words (HFWs) and content words (CWs). 
Our algorithm is based on the concept acquisition method of (Davidov and Rappoport, 2006). 
Davidov and Rappoport (2006) also used symmetric patterns for this task. 
Fully unsupervised semantic clustering (e.g., (Lin, 1998; Lin and Pantel, 2002; Davidov and Rappoport, 2006)) has the disadvantage that it may or may not produce the types and granularities of semantic classes desired by a user. 
