2 Previous work In the past, two major error mining techniques have been developed by Van Noord (2004) and Sagot and de la Clergerie (2006). 
The rst, already described in (Sagot and Villemonte de La Clergerie, 2006), mixes the detection resultsobtainedfromvariousparserswithdifferent grammars, hence with different shortcomings. 
To test this, we compared the method described by Van Noord (2004) and the iterative error miner of Sagot and de la Clergerie (2006). 
 The SXLFG-FR grammar (Boullier and Sagot, 2006), is an efcient deep nonprobabilistic LFG grammar. 
Some techniques, like van Noord (2004) or Sagot and Villemonte de La Clergerie (2006), bringaconvenientwaytoautomatically identify forms having potentially erroneous entries in a lexicon. 
