859 The phrase method proposed in this paper performs better than the word method proposed in (Wang et al. , 2006).


 = ' ),'( ),( )|( f efcount efcount efw (8) We also estimate the lexical translation probability )|( efw using the method described in (Wang et al. , 2006), which is shown in (9).


The data used for this experiment is the same as those used in (Wang et al. , 2006).


Pivot-based methods have also been used in other related areas, such as translation lexicon induction (Schafer and Yarowsky, 2002), word alignment (Wang et al. , 2006), and cross language information retrieval (Gollins and Sanderson, 2001).


