Nonparametricmodels (Teh, 2006) may be appropriate.


Gibbs sampling is not new to the natural language processing community (Teh, 2006; Johnson et al., 2007).


The relationship between Kneser-Ney smoothing to the Bayesian approach have been explored in (Goldwater et al., 2006; Teh, 2006) using Pitman-Yor processes.


Recent work has applied Bayesian non-parametric models to anaphora resolution (Haghighi and Klein, 2007), lexical acquisition (Goldwater, 2007) and language modeling (Teh, 2006) with good results.


