P07-1090:1	28:208	Proposals to alleviate this problem include utilizing bilingual phrase cluster or words at the phrase boundary (Nagata et al. , 2006) as the phrase identity.
---------------------------------------------------
P07-1090:2	55:208	We follow the notation in (Nagata et al. , 2006) and define the following bilingual orientation values given two neighboring source (Chinese) phrases: Monotone-Adjacent (MA); ReverseAdjacent (RA); Monotone-Gap (MG); and ReverseGap (RG).
---------------------------------------------------
W08-0405:3	26:208	The expression block is used here to emphasize that pairs of phrases (especially longer phrases) tend to form closely linked units in such a way that the translation process can be formalized as a block segmentation process (Nagata et al., 2006; Tillmann and Zhang, 2007).
---------------------------------------------------
