The above problems could be partially solved by introducing more resources into collocation extraction, such as chunker (Wermter and Hahn, 2004), parser (Lin, 1998; Seretan and Wehrli, 2006) and WordNet (Pearce, 2001).


The system is currently available for six languages (English, French, German, Italian, Spanish and Greek), and has been extensively used for terminology extraction (Seretan & Wehrli, 2006), as well as for terminology assistance and translation (Wehrli, 2004, 2006).


