A manual evaluation based on 30 of 54 BMJ-CE question-answer pairs in the presented test suite is described in (Demner-Fushman and Lin, 2006).


4 Strategies  for  Retrieving  MEDLINE Abstracts As with (Fiszman et al., 2007) and (Demner-Fushman and Lin 2006),  the current work starts with information retrieval.


3.2   Answering Clinical Questions   Demner-Fushman and Lin (2006) address superlative clinical questions of the type What is the best treatment for X by using a hybrid approach consisting of information retrieval and summarization.


