E09-1066:1	197:200	Also the use of PAS derived from FrameNet and PropBank (Giuglea and Moschitti, 2006) appears to be an interesting research line.
---------------------------------------------------
W08-2007:2	86:91	Both global and local structure is found, and we can speculate that this helps representing lexical units in semantic labeling (Giuglea and Moschitti, 2006) for machine learning tasks.
---------------------------------------------------
D09-1029:3	10:229	This has proved to be useful in several tasks, from verb classification (Chow and Webster, 2007) to semantic role labeling (Giuglea and Moschitti, 2006), open text semantic parsing (Shi and Mihalcea, 2004) and textual entailment (Burchardt and Frank, 2006).
---------------------------------------------------
P09-1003:4	26:214	Therefore, the generalization of semantic roles across different frames has been brought up as a critical issue for FrameNet (Gildea and Jurafsky, 2002; Shi and Mihalcea, 2005; Giuglea and Moschitti, 2006) In this paper, we explore several criteria for generalizing semantic roles in FrameNet.
---------------------------------------------------
P09-1003:5	40:214	Shi and Mihalcea (2005) and Giuglea and Moschitti (2006) employed VerbNet thematic roles as the target of mappings from the roles defined by the different semantic corpora.
---------------------------------------------------
W08-2004:6	59:142	3.1 Tree Kernels Tree Kernels (e.g. see NLP applications in (Giuglea and Moschitti, 2006; Zanzotto and Moschitti, 2006; Moschitti et al., 2007; Moschitti et al., 2006; Moschitti and Bejan, 2004)) represent trees in terms of their substructures (fragments) which are mapped into feature vector spaces, e.g. n. The kernel function measures the similarity between two trees by counting the number of their common fragments.
---------------------------------------------------
W07-0208:7	5:151	, 2005; GiugleaandMoschitti, 2006).
---------------------------------------------------
C08-1121:8	21:165	(Collins and Duffy 2002; Zelenko et al. 2003; Giuglea and Moschitti 2006; Zanzotto and Moschitti 2006; Moschitti et al. 2007).
---------------------------------------------------
W09-1127:9	9:211	In particular, resources annotated with the surface realization of semantic roles, like FrameNet (Baker et al., 1998) or PropBank (Palmer et al., 2005) have shown to convey an improvement in several NLP tasks, from question answering (Shen and Lapata, 2007) to textual entailment (Burchardt et al., 2007) and shallow semantic parsing (Giuglea and Moschitti, 2006).
---------------------------------------------------
N07-1072:10	49:189	Although there exists some automatic semantic role taggers (Gildea and Jurafsky, 2002; Giuglea and Moschitti, 2006), most of them were trained on PropBank (Palmer et.
---------------------------------------------------
