These include call type classification for the purpose of categorizing calls (Tang et al. , 2003) (Zweig et al. , 2006), call routing (Kuo and Lee, 2003) (Haffner et al. , 2003), obtaining call log summaries (Douglas et al. , 2005), agent assisting and monitoring (Mishne et al. , 2005), and building of domain models (Roy and Subramaniam, 2006).


However, it has recently been proposed to use an unsupervised technique to generate domain models automatically from call transcriptions (Roy and Subramaniam, 2006).


In the spoken dialog systems, these are manually designed for various purposes including dialog modeling (Bohus and Rudnicky, 2003, Lee et al., 2008), search space reduction (Young et al., 2007), domain knowledge (Roy and Subramaniam, 2006), and user simulation (Schatzmann et al., 2007).


