Knowledge about entailment is beneficial for NLP tasks such as Question Answering (Harabagiu and Hickl, 2006). 
Similar stories can also be found in paraphrasing (Quirk et al. , 2004; Wu, 2005) and textual entailment (Harabagiu and Hickl, 2006; Wu, 2005). 
2 Feature Extraction for Entailment Implementation of different TE models has previously shown to improve the QA task using supervised learning methods (Harabagiu and Hickl, 2006). 
Information about the presence or absence of entailment between two sentences has been found to be beneficial for a range of NLP tasks such as Word Sense Disambiguation or Question Answering (Dagan et al., 2006; Harabagiu and Hickl, 2006). 
3 Recognizing Textual Entailment Recent work in computational semantics (Haghighi et al. , 2005; Hickl et al. , 2006b; MacCartney et al. , 2006) has demonstrated the viability of supervised machine learning-based approaches to the recognition of textual entailment (TE). 
