(Chen et al. , 2006) defined the special features for coordinations for chunking. 
On the contrary, Chinese shallow parsing has gained a promising result (Chen et al., 2006); hence it is an alternative choice for Chinese SRL. 
We first extend the study on Chinese chunking presented in (Chen et al., 2006) by raising a set of additional features. 
We first extend the study on Chinese shallow parsing presented in (Chen et al., 2006) by raising a set of additional features. 
The new set of features yield improvement over the strong chunking system described in (Chen et al., 2006). 
