Novischi and Moldovan (2006) use a technique that builds on a combination of lexical chains and verb argument structures extracted from VerbNet to re-rank answer candidates.


However, the only previous work we are aware of that enriches WordNet with argument mappings is (Novischi and Moldovan, 2006).


59 60 Cramer 1 Introduction Various applications in Natural Language Processing, such as Question Answering (Novischi and Moldovan, 2006), Topic Detection (Carthy, 2004), and Text Summarization (Barzilay and Elhadad, 1997), rely on semantic relatedness (similarity or distance)1 measures either based on word nets and/or corpus statistics as a resource.


