FrameNet sentences were parsed with RASP (Briscoe et al., 2006). 
Different parsers produce different output, for example phrase structure trees (Collins, 2003), dependency trees (Nivre and Scholz, 2004), grammatical relations (Briscoe et al. , 2006), and formalismspecific dependencies (Clark and Curran, 2004b). 
In this paper the sophisticated parser RASP Toolkit 2 (Briscoe et al., 2006) was utilized to extract this kind of word relations. 
The GRs are described in Briscoe and Carroll (2006) and Briscoe et al. 
To compare with, we used RASP 2 (Briscoe et al. , 2006), a domain-independent robust parsing system for English. 
