A promising direction is the combination of different ranking models (Brody et al. , 2006) and the integration of dominant sense models with supervised WSD. 
Lexical chains (Galley and McKeown, 2003) may also provide a useful rst sense heuristic (Brody et al., 2006) but are produced usingWordNetrelations. 
Still, it is in our next plans and part of our future work to embed in our model some of the interesting WSD approaches, like knowledgebased (Sinha and Mihalcea, 2007; Brody et al., 2006), corpus-based (Mihalcea and Csomai, 2005; McCarthy et al., 2004), or combinations with very high accuracy (Montoyo et al., 2005). 
As explained in (Brody et al., 2006), there are generally two approaches to unsupervised WSD. 
There have also been promising results in recent work on the combination of unsupervised approaches that suggest the gap with respect to supervised systems is narrowing (Brody et al. , 2006). 
