(2008)s method is based on Pantel and Pennacchiotti (2006)s Espresso algorithm, which is originally designed to acquire relations between entities. 
Based on Hearsts work, Pantel and Pennacchiotti (2006) further give a method 529 which measures the reliability of the patterns based on the strength of association between patterns and instances, employing the pointwise mutual information (PMI). 
For the tasks of information extraction and relation extraction, bootstrapping approaches have been proven successful (Yangarber, 2003; Pantel and Pennacchiotti, 2006). 
Other researchers (Pantel and Pennacchiotti, 2006), (Snow et al. , 2006) use clustering techniques coupled with syntactic dependency features to identify IS-A relations in large text collections. 
Strategies were developed for discovery of multiple patterns for some specified lexical relationship (Pantel and Pennacchiotti, 2006) and for unsupervised pattern ranking (Turney, 2006). 
