In the experiments, we compared our model with other two types of probabilistic models using a supertagger (Ninomiya et al. , 2006). 
(2006)s model 1 87.23 86.47 86.85 90.05 89.27 89.66 129 Ninomiya et al. 
We also compared with a probabilistic model in (Ninomiya et al. , 2006). 
(2006)s model 1 87.23 86.47 86.85 90.05 89.27 89.66 129 Ninomiya et al. 
In the experiments, we compared our model with the probabilistic HPSG with a unigram reference distribution (Miyao and Tsujii, 2005) and the probabilistic HPSG with supertagging (Ninomiya et al. , 2006). 
