In this paper,  = 0.8 and t = 0.7 (Parameters in two papers, Zhang et al. 2006a and Zhang et al. 2006b, are different. 
Furthermore, our error analysis on the results of combination reveals that confidence measure in (Zhang et al., 2006a) has a representation flaw and we propose an EIV tag method to revise it. 
In (Zhang et al., 2006a), the above CT method is developed as subword-based tagging. 
Corpus RIV ROOV DS CT DS CT AS 0.982 0.967 0.038 0.647 CityU 0.989 0.967 0.164 0.736 MSRA 0.993 0.972 0.048 0.716 PKU 0.981 0.955 0.408 0.754 Table 1 IV and OOV recall in (Zhang et al.,   2006a)        The rest of this paper is organized as follows. 
3.2 Experiments and error analysis about combination We repeat the experiments about CM in Zhangs paper (Zhang et al., 2006a) and show that there is a representation flaw in the CM formula. 
