All the knowledge sources were made available to be used by the inference engine, since previous experiments showed that they are all relevant (Specia, 2006).


In addition to the consistency requirements for integration, this requirement is also motivated by empirical studies, which show that predefined translations derived from sense distinctions defined in monolingual ontologies do not match translation distinction made by human translators (Specia et al. , 2006).


(2005) and Specia (2006) proposed WSD systems designed for French to English, and Portuguese to English translation respectively, and present a more optimistic outlook for the use of WSD in MT, although these WSD systems have not yet been integrated nor evaluated in full-scale machine translation systems.


Specia (2006) describes an inductive logic programming-based WSD system,whichwasspecificallydesignedforthepurpose of Portuguese to English translation, but this system was also only evaluated on WSD accuracy, and not integratedinafull-scalemachinetranslationsystem.


