Using both sets of features, our topic-based model achieves state of the art performance ( = .5) on the ordering task, comparable with the mixture model of (Soricut and Marcu, 2006). 
Recently there has been a lot of work in discourse coherence modeling (Lapata, 2003; Barzilay and Lapata, 2005; Soricut and Marcu, 2006) that has used 173 information ordering to test the coherence models. 
Both of these models are very different from the lexical and entity-based models currently used for this task (Soricut and Marcu, 2006), and are probably capable of improving the state of the art. 
Our model performs the ordering task competitively with (Soricut and Marcu, 2006), and significantly better than either of the models it is based on. 
Recently, the discourse coherence modeling community has started using the information ordering task as a testbed to test their discourse coherence models (Barzilay and Lapata, 2005; Soricut and Marcu, 2006). 
