One may think of using semantic roles in textual inference as exemplied by, for example, Tatu and Moldovan (2006).


While many approaches have addressed this problem, our work is most closely related to that of (Raina et al., 2005; MacCartney and Manning, 2007; Tatu and Moldovan, 2006; Braz et al., 2005), which convert the inputs into logical forms and then attempt to prove H from T plus a set of axioms.


