E09-1091:1	169:186	(Munteanu and Marcu, 2006; Quirk et al., 2007) addresses mining of parallel sentences and fragments from nearly parallel sentences.
---------------------------------------------------
P08-1049:2	177:184	(2006) and references therein) as both are trying to introduce generalization into MT. At last, the goal that we aim to exploit monolingual corpora to help MT is in-spirit similar to the goal of using non-parallel corpora to help MT as aimed in a large amount of work (see Munteanu and Marcu (2006) and references therein).
---------------------------------------------------
W09-0430:3	30:224	2 Mining a comparable text corpus In (Munteanu and Daniel Marcu, 2006), the authors present a method for extracting parallel sub-sentential fragments from comparable bilingual corpora.
---------------------------------------------------
C08-1030:4	204:209	Munteanu and Marcu (2006) proposed a method for extracting parallel subsentential fragments from very non-parallel bilingual corpora.
---------------------------------------------------
W08-1403:5	95:187	In order to detect non-parallel sections we have used a simpler algorithm than in for instance Munteanu & Marcu (2006).
---------------------------------------------------
D07-1036:6	213:249	Others extract parallel sentences from comparable or non-parallel corpora (Munteanu and Marcu 2005, 2006).
---------------------------------------------------
W08-1911:7	42:160	(Munteanu and Marcu, 2006)).
---------------------------------------------------
