The measures can be based on inter-lingual or on intra-lingual comparison of phonetic forms (Ellison and Kirby, 2006). 
It may be noted that Ellison and Kirby (Ellison and Kirby, 2006) have shown that scaling by distance does give significantly better results. 
Other possible applications could be for language reconstruction, classification, dialectology etc. Better versions of the two cognate based measures can be defined by using the idea of confusion probabilities (Ellison and Kirby, 2006) and the idea of distributional similarity. 
Ellison and Kirby (Ellison and Kirby, 2006) argue that even if there is a common space, language specific categorization of sound often restructures this space. 
Like in other disciplines, computational methods are increasingly being combined with other more conventional approaches (Dyen et al. , 1992; Nerbonne and Heeringa, 1997; Kondrak, 2002; Ellison and Kirby, 2006). 
