We generalize the standard deterministic stepwise framework to probabilistic parsing, with the use of a best-first search strategy similar to the one employed in constituent parsing by Ratnaparkhi (1997) and later by Sagae and Lavie (2006); 3. 
An existing method to combine multiple parsing algorithms is the ensemble approach (Sagae and Lavie, 2006a), which was reported to be useful in improving dependency parsing (Hall et al., 2007). 
The usual way of preventing early error commitment is to enable a k-best or beam-search strategy (Huang and Chiang 2005, Sagae and Lavie 2006). 
The algorithm is essentially a dependency version of the data-driven constituent parsing algorithm for probabilistic GLR-like parsing described by Sagae and Lavie (2006). 
The bestfirst search proposed by Sagae and Lavie (2006) was also tried out but there was similar drop in accuracy. 
