4 Experiment We evaluated our method on six large-scale natural language data sets (Table 1): Penn Treebank3 for part-of-speech tagging (PTB), phrase chunking data4 (CoNLL00), named entity recognition data5 (CoNLL03), grapheme-to-phoneme conversion data6 (NetTalk), spoken language understanding data (Communicator) (Jeong and Lee, 2006), and finegrained named entity recognition data (Encyclopedia) (Lee et al., 2007).


