The realization module works in the opposite direction, verbalizing the results of the execution of the command from the semantic representation using the TAG surface realizer GenI (Gardent and Kow, 2007) (illustrated in the Figure 2 by ).


p: fatal/legal(x) S a8a8a8 a72a72a72NP arg:x VP a8a8 a72a72V is A fatal (il)legal Figure 3: Elementary TAG trees for semantic formulas 5 Directions for further research A possible way to control the generator is to enrich the input representation by adding restrictions on the types of trees that are allowed to be selected, similarly to (Gardent and Kow, 2007) (e.g., if a rhetorical relation is restricted to selecting initial trees for its satellite then it wont be generated as a parenthetical).


