We take the correlation rates of the metrics reported in Albrecht and Hwa (2007) and a standard automatic metric BLEU as a baseline comparison. 
More recently, Albrecht and Hwa (2007a; 2007b) re-examined the SVM classification approach by Kulesza and Shieber (2004) and, inspired by the work of Quirk (2004), suggested a regression-based learning approach to metric combination, with and without human references. 
4.4 Discussions Albrecht and Hwa (2007) and this paper both adopted a regression-based learning method. 
Moreover, the experiments show that our metric can reach a correlation with human judgments nearly as good as the metric described in Albrecht and Hwa (2007), with a much lower computation cost. 
In the last few years, several approaches to metric combination have been suggested (Kulesza and Shieber, 2004; Liu and Gildea, 2007; Albrecht and Hwa, 2007a). 
