The basic framework for the current study develops around two such complex networks namely, the Phoneme-Language Network or PlaNet (Choudhury et al., 2006) and its onemode projection, the Phoneme-Phoneme Network or PhoNet (Mukherjee et al.2007a).


Therefore, it turns out that the groups of consonants that largely co-occur in the languages of a linguistic generation are actually driven by the principle of feature economy (see (Clements, 2008; Mukherjee et al.2007a) for details).


The primary reason for this deviation in the results is that PhoNet exhibits strong patterns of co-occurrences (Mukherjee et al.2007a) and this fact is not taken into account by Model I. In order to circumvent the above 4Mean error is defined as the average difference between the ordinate pairs (say y and yprime) where the abscissas are equal.


The quantification process, which is a refinement of the idea presented in (Mukherjee et al.2007b), is as follows.


