Anextensiontothemodelsdescribedsofarwould be to iteratively integrate the two parsers in the spirit of pipeline iteration (Hollingshead and Roark, 2007).


Recent results making use of finite-state chunkers early in a syntactic parsing pipeline have shownbothanefficiency(GlaysherandMoldovan, 2006) and an accuracy (Hollingshead and Roark, 2007) benefit to the use of such constraints in a parsing system.


Hollingshead and Roark (2007) demonstrated that high precision constraints on early stages of the Charniak and Johnson (2005) pipelinein the form of base phrase constraints derived either from a chunker or from later stages of an earlier iteration of the c2008.


This accuracy improvement is similar to results obtained in Hollingshead and Roark (2007), where base phrase constraints from a finite-state chunker were used to achieve improved parse accuracy.


(2007), Hollingshead and Roark (2007), and Roark and Hollingshead (2008).


