Rosenfeld and Feldman (2007) presented a method for improving semi-supervised relation extraction from the Web using corpus statistics on entities.


Additionally, ensuring that relation arguments are of certain, expected types can help mitigate the promotion of incorrect instances (Pasca et al., 2006; Rosenfeld and Feldman, 2007).


Other NLP tasks where it has been explored include semi-supervised relation extraction (Rosenfeld and Feldman, 2007), IE (Culotta and McCallum, 2004), QA (Chu-Carroll et al., 2003), and dialog systems (Lin and Weng, 2008).


