The forest concept is also used in machine translation decoding, for example to characterize the search space of decoding with integrated language models (Huang and Chiang, 2007). 
Decoding used beam search with the cube pruning algorithm (Huang and Chiang, 2007). 
13Huang and Chiang (2007) give an informal example, but do not elaborate on it. 
6 Related Work In machine translation, the concept of packed forest is first used by Huang and Chiang (2007) to characterize the search space of decoding with language models. 
We also use Cube Pruning algorithm (Huang and Chiang 2007) to speed up the translation process. 
