Effect of further languages on CLIR Generally, these results confirm the finding of Chew and Abdelali (2007) about adding more languages; doing so enhances the ability to identify translations across language boundaries. 
(2007) and Chew and Abdelali (2008). 
It has since been confirmed that LSA can be applied not just to pairs of languages, but also simultaneously to groups of languages, again given the existence of a multi-parallel corpus (Chew and Abdelali 2007). 
(2007) or Chew and Abdelali (2008): multilingual precision at 5 documents (hereafter MP5). 
In previous results (Chew et al. 2007, Chew and Abdelali 2008) it is noticeable in particular that the results for Arabic and Russian (the two most morphologically complex languages for which they present results) are consistently poorer than they are for other languages. 
