It also outperforms balanced bootstrapping, an approach designed for domain adaptation (Jiang and Zhai, 2007). 
Standard bootstrapping: (Jiang and Zhai, 2007) the selection-criterion is based on selecting the top k most-confidently labeled instances in Rt. 
We systematically explored the feature space for relation extraction (Jiang and Zhai, 2007b) . Kernel methods allow a large set of features to be used without being explicitly extracted. 
Jiang and Zhai (2007) recently proposed an instance re-weighting framework to take domain shift into account. 
Instance weighting (Jiang and Zhai, 2007) and active learning (Chan and Ng, 2007) are also employed in domain adaptation. 
