Recently, Crego and Marino (2007b) employ POS tags to automatically learn reorderings in training.


As in (Zhang et al., 2007), (Costa-juss`a and Fonollosa, 2006) and (Crego and Marino, 2007b), we employ a word graph for a tight coupling between reordering and decoding.


Crego and Marino (2007c) extend their previous work using syntax trees (dependency parsing) to learn reorderings on a Chinese-English task.


SMT decoding is done using MARIE,7 a freely available N-gram-based decoder implementing a beam search strategy with distortion/reordering capabilities (Crego and Marino, 2007a).


