C08-1132:1	105:161	Using good parse selection (Reichart and Rappoport, 2007; Yates et al., 2006) on the syntactic analysis of Chinese Gigaword is a probable way to construct more case structures without decreasing their accuracy.
---------------------------------------------------
P08-1098:2	109:197	For each sentence in the unlabeled pool, the agreement between the committee members was calculated using the function reported by Reichart and Rappoport (2007): AF(s) = 1N summationdisplay i,l[1N],inegationslash=l fscore(mi,ml) (2) Where mi and ml are the committee members and N = k2(k21)2 is the number of pairs of different committee members.
---------------------------------------------------
W09-1120:3	166:237	We do this for every k from 1 to the number of sentences of length L. Following Reichart and Rappoport (2007), we use two measures to evaluate the quality of a set of parses: the constituent F-score (the traditional Fscore used in the parsing literature), and the average F-score of the parses in the set.
---------------------------------------------------
W09-1120:4	130:237	Quality assessment of a learning algorithms output and selection of high quality instances have been addressed for supervised algorithms (see (Caruana and Niculescu-Mizil, 2006) for a survey) and specifically for supervised constituency parsers (Yates et al., 2006; Reichart and Rappoport, 2007; Ravi et al., 2008).
---------------------------------------------------
W09-1120:5	50:237	As in (Reichart and Rappoport, 2007), the quality of a set selected from the parsers output is evaluated using two measures: constituent F-score5 and average sentence F-score.
---------------------------------------------------
W09-1120:6	47:237	(2008) are supervised (Section 3), the ensemble based SEPA algorithm (Reichart and Rappoport, 2007) can be applied to unsupervised parsers in a way that preserves the unsupervised nature of the selection task.
---------------------------------------------------
W09-1120:7	56:237	4This is in contrast to algorithms for selection from the results of supervised constituency parsers, which were evaluated only for English (Yates et al., 2006; Reichart and Rappoport, 2007; Ravi et al., 2008).
---------------------------------------------------
W09-1120:8	185:237	Based on the analysis of SEPA performance with different assignments of its parameters given by Reichart and Rappoport (2007) (see Section 3), we ran the SEPA algorithm with sample size (SEPA parameter S) of 30% and 80%, and with 2  10 committee members (N)6.
---------------------------------------------------
W09-1120:9	23:237	Assessing the quality of a learning algorithms output and selecting high quality instances has been addressed for supervised algorithms (Caruana and Niculescu-Mizil, 2006) and specifically for supervised parsers (Yates et al., 2006; Reichart and Rappoport, 2007; Kawahara and Uchimoto, 2008; Ravi et al., 2008).
---------------------------------------------------
W09-1120:10	137:237	However, the SEPA algorithm of Reichart and Rappoport (2007), an algorithm for supervised constituency parsers, can be applied to unsupervised parsers in a way that preserves the unsupervised nature of the selection task.
---------------------------------------------------
W09-1120:11	44:237	Such a prediction can be given by supervised parsers in terms of the parse likelihood, but this was shown to be of medium quality (Reichart and Rappoport, 2007).
---------------------------------------------------
I08-2097:12	44:160	Reichart and Rappoport applied selftraining to domain adaptation using a small set of in-domain training data (Reichart and Rappoport, 2007b).
---------------------------------------------------
I08-2097:13	30:160	Reichart and Rappoport also proposed an ensemble method to select high-quality parses from the outputs of constituency parsers (Reichart and Rappoport, 2007a).
---------------------------------------------------
