N09-1023:1	55:189	Our work is also related to text segmentation (Ji et al., 2003) and meeting segmentation (Malioutov et al., 2006; Malioutov et al., 2007; Galley et al., 2003; Eisenstein et al., 2008).
---------------------------------------------------
P09-1062:2	30:212	This method has been successfully applied to tasks such as word detection (Park and Glass, 2006) and topic boundary detection (Malioutov et al., 2007).
---------------------------------------------------
P09-1062:3	111:212	The version of SDTW employed by (Malioutov et al., 2007) and Park and Glass (2008) employed an algorithm of complexity O(Klog(L)) from (Lin et al., 2002) to find subpaths.
---------------------------------------------------
P09-1062:4	81:212	This method is similar to standard DTW, except that it computes multiple constrained alignments, each within predetermined bands of the similarity matrix (Park and Glass, 2008).2 SDTW has been successfully applied to problems such as topic boundary detection (Malioutov et al., 2007) and word detection (Park and Glass, 2006).
---------------------------------------------------
