Our technique of generating negative examples is similar to the approach of Okanohara and Tsujii (2007). 
Examples are Andersen (2006; 2007), Okanohara and Tsujii (2007), Sun et al. 
As shown in (Okanohara and Tsujii, 2007), using this representation, a linear classifier cannot distinguish sentences sampled from a trigram and real sentences. 
Okanohara and Tsujii (2007) generate ill-formed sentences by sampling a probabilistic language model and end up with pseudo-negative examples which resemble machine translation output more than they do learner texts. 
Both Okanohara and Tsujii (2007) and Wagner et al. 
