N09-1015:1	19:212	Most of the previous triangulation approaches (Kumar et al., 2007; Cohn and Lapata, 2007; Filali and Bilmes, 2005; Simard, 1999; Och and Ney, 2001) add information obtained from a third language.
---------------------------------------------------
P09-1021:2	159:191	4Choice of Germanic and Romance for our experimental setting is inspired by results in (Cohn and Lapata, 2007) unpopularity in L, which is measured by P(x|U)P(x|L).
---------------------------------------------------
P09-1021:3	185:191	Finally, we briefly note that triangulation (see (Cohn and Lapata, 2007)) is orthogonal to the use of co-training in our work, since it only enhances each MT system in our ensemble by exploiting the multilingual data.
---------------------------------------------------
E09-1082:4	186:216	This finding might also carry over to phrase-table triangulation (Cohn and Lapata, 2007), where multi-parallel data is used in training to augment a standard translation 725 Approach test2006 test2007 French Only 29.72 30.21 French + Swedish MAX 29.86 30.13 LATTICE 29.33 29.97 MULTILATTICE 29.55 29.88 SYSCOMB 31.32 31.77 French + Swedish + Spanish MAX 30.18 30.33 LATTICE 29.98 30.45 MULTILATTICE 30.50 30.50 SYSCOMB 33.77 33.87 6 Languages MAX 28.37 28.33 LATTICE 30.22 30.91 MULTILATTICE 30.59 30.59 SYSCOMB 35.47 36.03 Table 6: BLEU scores for multi-source translation systems into English trained on Europarl.
---------------------------------------------------
N09-1010:5	49:223	A related thread of research is multi-source machine translation (Och and Ney, 2001; Utiyama and Isahara, 2006; Cohn and Lapata, 2007) where the goal is to translate from multiple source languages to a single target language.
---------------------------------------------------
P09-1089:6	59:234	2.2 Paraphrasing in MT A recent strategy to broadly deal with the problem of unknown terms is to paraphrase the source text with terms whose translation is known to the system, using paraphrases learnt from multilingual corpora, typically involving at least one pivot language different from the target language of immediate interest (Callison-Burch et 792 al., 2006; Cohn and Lapata, 2007; Zhao et al., 2008; Callison-Burch, 2008; Guzman and Garrido, 2008).
---------------------------------------------------
P08-2041:7	17:104	Another method is to use multi-parallel corpora (Cohn and Lapata, 2007; Utiyama and Isahara, 2007) to improve phrase coverage and translation quality.
---------------------------------------------------
P09-1018:8	13:234	To circumvent the data bottleneck, some researchers have investigated to use a pivot language approach (Cohn and Lapata, 2007; Utiyama and Isahara, 2007; Wu and Wang 2007; Bertoldi et al., 2008).
---------------------------------------------------
P09-1018:9	17:234	The first is based on phrase table multiplication (Cohn and Lapata 2007; Wu and Wang, 2007).
---------------------------------------------------
