Table 9 shows thattheaveragenaturalnessis3.98outof7, whichis significantly lower (p < .05) than the naturalness of handcrafted and randomly generated utterances reported by Mairesse and Walker (2007). 
Parameters are detailed in previous work (Mairesse and Walker, 2007). 
(2006) and Mairesse and Walker (2007) also propose a personality generation method, in which a data-driven personality model selects the best utterance from a large candidate set. 
Even though the parameters of PERSONAGE-PE were suggested by psychological studies (Mairesse and Walker, 2007), some of them are not modeled successfully by our approach, and thus omitted from Tables 3 and 4. 
In previous work, we presented PERSONAGE, apsychologically-informedrule-basedgenerator based on the Big Five personality model, and we showed that PERSONAGE can project extreme personality on the extraversion scale, i.e. both introverted and extraverted personality types (Mairesse and Walker, 2007). 
