W09-2506:1	9:90	Natural-language inference is highly context-sensitive, the applicability of inference rules depending on word sense and even finer grained contextual distinctions in usage (Szpektor et al., 2007).
---------------------------------------------------
E09-3004:2	175:188	It is in the range reported by the authors of the TEASE system (Szpektor et al., 2004) but well below the extrapolated figures of over 20 relations in Szpektor et al., 2007.
---------------------------------------------------
E09-3004:3	126:188	We then re-evaluate our best score using the Szpektor et al. method (2007), which we think is more suited for checking true substitutability.
---------------------------------------------------
E09-1064:4	219:230	Previous works assessing rule application via human annotation include (Pantel et al., 2007; Szpektor et al., 2007), which evaluate acquisition methods for lexical-syntactic rules.
---------------------------------------------------
E09-1064:5	103:230	These figures correspond to substantial agreement (Landis and Koch, 1997) and are comparable with related semantic annotations (Szpektor et al., 2007; Bhagat et al., 2007).
---------------------------------------------------
I08-1070:6	142:198	4.3 Criteria of paraphrasability To assess by human the paraphrasability discussed in Section 3, we designed the following four questions based on (Szpektor et al., 2007): Q sc : Is s a correct phrase in Japanese?
---------------------------------------------------
E09-1025:7	46:201	(Basili et al., 2007) and (Szpektor et al., 2008) propose attaching selectional preferences to inference rules.
---------------------------------------------------
E09-1025:8	96:201	For such a rule to be eliminated the two patterns have to be identical (with respect to edge labels and content words) except from the antonymous words; an example of a rule eliminated this way is X have confidence in Y X lack confidence in Y. As pointed out by (Szpektor et al., 2007) a thorough evaluation of a rule collection is not a trivial task; however due to our methodology we can assume that the percentage of rules eliminated this way that are indeed contradictions gets close to 100%.
---------------------------------------------------
E09-1025:9	28:201	In our work we use the DIRT collection because it is the largest one available and it has a relatively good accuracy (in the 50% range for top generated paraphrases, (Szpektor et al., 2007)).
---------------------------------------------------
E09-1025:10	38:201	Most confident paraphrases of X put emphasis on Y Such rules can be informally defined (Szpektor et al., 2007) as directional relations between two text patterns with variables.
---------------------------------------------------
P08-1078:11	141:216	Comparing with previous evaluation methodologies, in (Szpektor et al., 2007; Pantel et al., 2007) proper context matching was evaluated by post-hoc judgment of a sample of rule applications for a sample of rules.
---------------------------------------------------
P08-1078:12	201:216	Recently, the need for context-aware inference was raised (Szpektor et al., 2007).
---------------------------------------------------
