The feasibility of this approach was demonstrated by Gordon and Swanson (2007) for syntactically similar verbs. 
The generalization procedures developed by Gordon and Swanson (2007) for PropBank SRL and Pado et al. 
(2008) and Gordon and Swanson (2007), we do not aim to handle novel verbs, although this would be a natural extension of our method. 
Pradhan et al., 2005), analyzing the complex input  syntax trees (Moschitti, 2004; Liu and Sarkar, 2007), exploiting the complicated output  the predicate-structure (Toutanova et al., 2005), as well as capturing paradigmatic relations between predicates (Gordon and Swanson, 2007). 
Gordon and Swanson (2007) proposed a generalization method for the PropBank roles based on syntactic similarity in frames. 
