In a similar vein, Hogan (2007b) inspected WORDNET similarity and relatedness measures and investigated their role in conjunct identification.


(2005), Nakov and Hearst (2005)), similarity-based approaches incorporating orthographical, morpho-syntactic, and syntactic similarity criteria (e.g., Agarwal and Boggess (1992), Okumura and Muraki (1994)), as well as a combination of distribution information and syntactic criteria (Hogan, 2007a).


Some researchers (e.g., Hogan (2007a)) had recently found several inconsistencies in its annotation of the bracketing of coordinations in NPs.


Hogan (2007a) presented a method for the disambiguation of noun phrase coordination by modelling two sources of information, viz.


