Figure 1 gives examples of semantic molecules for an adjective, a noun and a noun phrase, as presented in (Muresan and Rambow, 2007).


The theoretical learning model is Grammar Approximation by Representative Sublanguage (GARS) introduced in (Muresan, 2006; Muresan and Rambow, 2007).


First, we review our grammar formalism introduced in (Muresan, 2006; Muresan and Rambow, 2007), called Lexicalized Well-Founded Grammars.


2 Grammar Formalism Lexicalized Well-Founded Grammars (LWFGs) introduced in (Muresan, 2006; Muresan and Rambow, 2007) are a type of De nite Clause Grammars (Pereira and Warren, 1980) where: (1) the context-free backbone is extended by introducing a partial ordering relation among nonterminals (the basis for  well-founded ); (2) each string is associated with a syntactic-semantic representation called a semantic molecule; and (3) grammar rules have two types of constraints: one for semantic composition and one for ontology-based semantic interpretation.


