Devitt and Ahmad (2007) explore a computable metric of positive or negative polarity in financial news text.


For example, Devitt and Ahmad (2007) gave a computable metric of polarity in financial news text consistent with human judgments.


Devitt and Ahmad (2007) explore a computable metric of positive or negative polarity in financial news text.


2 Related Work Previous work on polarity disambiguation has used contextual clues and reversal words (Wilson et al., 2005; Kennedy and Inkpen, 2006; Kanayama and Nasukawa, 2006; Devitt and Ahmad, 2007; Sadamitsu et al., 2008).


