Using an intermediate pivot language with bilingual translation in which a given language pair is low-resourced has led to improvements in translation performance (Wu and Wang, 2007; Bertoldi et al., 2008), but to our knowledge this approach has not been applied to full sentence paraphrasing. 
Wu and Wang (2007) focused on phrase pivoting. 
Recently, several researchers proposed the use of the pivot language for phrase-based SMT (Utiyama and Isahara, 2007; Wu and Wang, 2007). 
The first is based on phrase table multiplication (Cohn and Lapata 2007; Wu and Wang, 2007). 
To circumvent the data bottleneck, some researchers have investigated to use a pivot language approach (Cohn and Lapata, 2007; Utiyama and Isahara, 2007; Wu and Wang 2007; Bertoldi et al., 2008). 
