P08-1070:1	22:177	Other research has looked at using dependencies to restrict the parsing process (Sagae et al., 2007), but the most well known filtering method is supertagging.
---------------------------------------------------
W08-2102:2	54:209	See also (Sagae et al., 2007) for a method that uses a dependency parser to restrict the search space of a more complex HPSG parser.
---------------------------------------------------
W09-1305:3	58:213	The system then identifies syntactic structures of sentences in an input corpus by utilizing the ENJU parser (Sagae et al., 2007).
---------------------------------------------------
