This includes the hierarchy of article categories (Strube and Ponzetto, 2006; Zesch et al., 2007) and links between articles in the same language (Milne and Witten, 2008) and across languages (Schonhofen et al., 2007; Potthast et al., 2008; Sorg and Cimiano, 2008; Muller and Gurevych, 2008).


In recent work, collaborative knowledge bases (CKB) like Wikipedia have been used in IR for judging the document relevance by computing the semantic relatedness (SR) of queries and documents (Gurevych et al., 2007; Egozi et al., 2008; Muller and Gurevych, 2008) and have shown promising results.


