Our experiment 1, reranking 50-best parses, is similar to the approaches of Charniak and Johnson (2005) and of Hogan (2007). 
Such work is extremely useful, given the harmfulness of annotation errors for training, including the learning of noise (e.g., Hogan, 2007; Habash et al., 2007), and for evaluation (e.g., Padro and Marquez, 1998). 
Hogan (2007a) presented a method for the disambiguation of noun phrase coordination by modelling two sources of information, viz. 
Hogan (2007) uses bi-lexical headhead co-occurrences in order to identify nominal heads of conjuncts more reliably than by syntactic information alone. 
Likewise, it is not clear how to learn from consistently misannotated data; studies often only note the presence of errors or eliminate them from evaluation (e.g., Hogan, 2007), and a previous attempt at correction was limited to POS annotation (Dickinson, 2006). 
