The split into interand inter-sentential examples in the current system seems justified as they have quite different characteristic, but there may also be a case for splitting the intra-sententials further, into intraand inter-clausals, as suggested by Maslennikov and Chua (2007), and then treating inter-clausals and inter-sententials together.


Maslennikov and Chua (2007) use discourse trees and local syntactic dependencies in a pattern-based framework to incorporate wider context.


