0.9595 0.9590 0.9611 0.9085 0.9134 0.9152 Table 8: Comparison of F1 results of our baseline model with Nakagawa and Uchimoto (2007) and Zhang and Clark (2008) on CTB 3.0. 
Nakagawa and Uchimoto (2007) proposed a hybrid model for word segmentation and POS tagging using an HMM-based approach. 
Table 8 compares the F1 results of our baseline model with Nakagawa and Uchimoto (2007) and Zhang and Clark (2008) on CTB 3.0. 
First, we do word segmentation and postagging for the sentences in Chinese Gigaword by a Chinese morphological  analyzer (Nakagawa and Uchimoto, 2007). 
Nakagawa and Uchimoto (2007) provided empirical evidence that the characterbased model is not always better than the wordbased model. 
