We apply an automatic conversion process using the gold-standard NP data annotated by Vadas and Curran (2007a). 
Recently, Vadas and Curran (2007a) annotated internal NP structure for the entire Penn Treebank, providing a large gold-standard corpus for NP bracketing. 
The Vadas and Curran (2007a) annotation scheme inserts NML and JJP brackets to describe the correct NP structure, as shown below: (NP (NML (NN lung) (NN cancer) ) (NNS deaths) ) We use these brackets to determine new goldstandard CCG derivations in Section 3. 
3 Conversion Process This section describes the process of converting the Vadas and Curran (2007a) data to CCG derivations. 
Fortunately, a re-annotated version has been provided by Vadas and Curran (2007), with a focus 90 on the internal structure of NPs. 
