2.3 Word Reordering Some previous work (Costa-juss and Fonollosa, 2006; Li et al., 2007) have shown that reordering a source sentence to match the word order in its cor Figure 1: Self-enhancement system structure, where TM is translation model, LM is language model, and RM is reordering model. 
A negative consequence of source order (SO) scoring as done by (Zhang et al., 2007) and (Li et al., 2007) is that they bias against the valuable phrase internal reorderings by only promoting the source sentence reordering. 
(Collinsetal., 2005; Wang et al., 2007) do this using manually created rules, and (Xia and McCord, 2004) and (Habash, 2007) use automatically extracted rules. 
(Crego and Marino, 2007; Zhang et al., 2007; Li et al., 2007) are more in the spirit of PSMT, in that multiple reorderings are presented to the PSMT system as (possibly weighted) options. 
(Li et al., 2007) use weighted n-best lists as input for the decoder. 
