P09-1015:1	10:221	Numerous studies have contributed to the development of increasingly accurate L2P systems (Black et al., 1998; Kienappel and Kneser, 2001; BisaniandNey, 2002; Dembergetal., 2007; Jiampojamarn et al., 2008).
---------------------------------------------------
P09-1014:2	27:284	Moreover, when combining our stress predictions with a state-ofthe-art L2P system (Jiampojamarn et al., 2008), we set a new standard for the combined prediction of phonemes and stress.
---------------------------------------------------
P09-1014:3	215:284	5.1 The L2P system We combine stress prediction with a state-of-theart L2P system (Jiampojamarn et al., 2008).
---------------------------------------------------
N09-3016:4	18:150	The current state of the art systems give as much as 90% (Jiampojamarn et al., 2008) accuracy forlanguageslikeDutch,GermanandFrench.
---------------------------------------------------
N09-3016:5	58:150	An online model MIRA (Crammer and Singer, 2003) which updates parameters is used for the L2P task by Jiampojamarn et al (2008).
---------------------------------------------------
D09-1111:6	31:259	We demonstrate that despite recent successes in discriminative character transduction using indicator features (Jiampojamarn et al., 2008; Dreyer et al., 2008), our generative hybrid performs surprisingly well, producing our highest transliteration accuracies.
---------------------------------------------------
D09-1111:7	112:259	Indicator Features Previous approaches to discriminative character transduction tend to employ only sparse indicators (Jiampojamarn et al., 2008; Dreyer et al., 2008).
---------------------------------------------------
W09-2211:8	5:28	Perhaps more importantly, discriminative models have been shown to offer competitive performance on a variety of sequential and structured learning tasks in NLP that are traditionally tackled via generative models , such as letter-to-phoneme conversion (Jiampojamarn et al., 2008), semantic role labeling (Toutanova et al., 2005), syntactic parsing (Taskar et al., 2004), language modeling (Roark et al., 2004), and machine translation (Liang et al., 2006).
---------------------------------------------------
W09-0106:9	40:125	(Jiampojamarn et al., 2008) and (Bartlett et al., 2008) do worse on the English test data than they do on German, Dutch, or French.
---------------------------------------------------
