Equation (5) is an instance of generalized expectation criteria (Mann and McCallum, 2008) that penalizes the divergence of a specific model expectation from a given target value. 
(2005) (CRR07) and Mann and McCallum (2008) (MM08). 
Generalized expectation criteria (Mann and McCallum, 2008) represent prior knowledge as labeled features, and use such information to regularize semi-supervised learning for CRFs. 
Our model is trained without the need for labeled word alignments by using generalized expectation (GE) criteria (Mann and McCallum, 2008) that penalize the divergence of specific model expectations from target expectations. 
3.1 Learning with feature-label distributions Mann and McCallum (2008) apply GE to a linearchain, first-order CRF. 
