(2007), and the models of Chiang (2005) and Marton 231 and Resnik (2008). 
Soft syntactic constraints Neither of our systems uses source-side syntactic information; hence, both could potentially benefit from soft syntactic constraints as described by Marton and Resnik (2008). 
Experiments show that our model achieves substantial improvements over baseline and significantly outperforms (Marton and Resnik, 2008)s XP+. 
Marton and Resnik (2008) introduced features defined on constituent labels to improve the Hiero system (Chiang, 2005). 
3 Soft syntactic constraints The first features we explore are based on a line of research introduced by Chiang (2005) and improved on by Marton and Resnik (2008). 
