This decision model is essentially equivalent to the transliteration models used in (Klementiev and Roth, 2006a; Goldwasser and Roth, 2008), in which a linear transliteration model was trained using a feature extraction method equivalent to AF. 
For Hebrew, we compare to the model presented in (Goldwasser and Roth, 2008b), a supervised model trained using 250 labeled examples. 
UCDL is our method, KR06 is described in (Klementiev and Roth, 2006b) and GR08 in (Goldwasser and Roth, 2008b). 
Several papers have followed up on this basic approach and focused on semi-supervised approaches to this problem or on extracting better features for the discriminative classifier (Klementiev and Roth, 2006b; Bergsma and Kondrak, 2007; Goldwasser and Roth, 2008). 
The results of two supervised models (Goldwasser and Roth, 2008b) are also included here. 
