Recently, Chang and Lai (2004), Lee (2005), Chang and Teng (2006), Li and Yarowsky (2008) have investigated this task.


2.2 Abbreviation and Acronym A Chinese abbreviation of a formal phrase is obtained by selecting one or more characters from this formal phrase, and the selected characters can be at any position in the formal phrase (Li and Yarowsky, 2008; Lee, 2005; Yin, 1999).


Li and Yarowsky (2008) propose an unsupervised method to extract the relations between full-form phrases and their abbreviations.


There has been a considerable amount of research on extracting full-name and abbreviation pairs in the same document for obtaining abbreviations (Li and Yarowsky, 2008; Sun et al., 2006; Fu et al., 2006).


