Contrary to Chambers and Jurafsky (2008) we do not learn global narrative chains over an entire corpus. 
2.1 Narrative Event Chains Narrative Event Chains are partially ordered sets of events that all involve the same shared participant, the protagonist (Chambers and Jurafsky, 2008). 
Chambers and Jurafsky (2008) extracted narrative event chains based on common protagonists. 
In Chambers and Jurafsky (2008), narrative chains add the beste,dbased on the following: maxj:0<j<mchainsim(c,vj,gj) (6) where m is the number of seen event slots in the corpus and vj,gj is the jth such possible event slot. 
2.1.1 The Case for Arguments The Chambers and Jurafsky (2008) narrative chains do not specify what type of argument fills the role of protagonist. 
