Our approach is similar to that of Mitchell and Lapata (2008) in that we compared additive and multiplicative models to non-compositional models in terms of their ability to model human data. 
Current vector space approaches typically compare the target words token vector to the type vector of the potential paraphrase (Mitchell and Lapata, 2008; Erk and Pado, 2008). 
Mitchell and Lapata (2008) found this method to yield the best results. 
In a study by (Mitchell and Lapata, 2008) on a sentence similarity task, a multiplicative combination model performs better than the additive one. 
Mitchell and Lapata (2008) presented a framework for representing the meaning of phrases and sentences in vector space. 
