E09-1078:1	156:181	(Polifroni and Walker, 2008) B4: SUMMARY followed by RECOMMEND, e.g.
---------------------------------------------------
E09-1078:2	50:181	(Walker et al., 2004; Demberg and Moore, 2006; Polifroni and Walker, 2008).
---------------------------------------------------
E09-1078:3	10:181	For example, the CG to present database results to the user can be realized as a summary (Polifroni and Walker, 2008; Demberg andMoore, 2006), orbycomparingitems (Walker et al., 2004), or by picking one item and recommending it to the user (Young et al., 2007).
---------------------------------------------------
E09-1078:4	73:181	However, SUMMARY has different qualities from COMPARE and RECOMMEND, as it gives users a general overview of the domain, and probably helps the user to feel more confident when choosing an item, especially when they are unfamiliar with the domain, as shown by (Polifroni and Walker, 2008).
---------------------------------------------------
