Nenkova and Louis (2008) investigate how summary length and the characteristics of the input influence the summary quality in multi-document summarization.


4 Features For our experiments we use the features proposed, motivated and described in detail by (Nenkova and Louis, 2008).


For the first set of experiments, we divide all inputs based on the mean value of the average system scores as in (Nenkova and Louis, 2008).


Only recently the issue has drawn attention: (Nenkova and Louis, 2008) present an initial analysis of the factors that influence system performance in content selection.


204 4.2.2 Correlation between TREC nuggets and non-text features Analyzing the features used could let us understand summarization better (Nenkova and Louis, 2008).


