Other linear functions have been explored for MBR, including Taylor approximations to the logarithm of BLEU (Tromble et al., 2008) and counts of matching constituents (Zhang and Gildea, 2008), which are discussed further in Section 3.3. 
A related MBR-inspired approach for hypergraphs was developed by Zhang and Gildea (2008). 
Recent innovations have greatly improved the efficiency of language model integration through multipass techniques, such as forest reranking (Huang and Chiang, 2007), local search (Venugopal et al., 2007), and coarse-to-fine pruning (Petrov et al., 2008; Zhang and Gildea, 2008). 
Specific instances of this generalalgorithmhaverecentlybeenproposedfortwo linear similarity measures (Tromble et al., 2008; Zhang and Gildea, 2008). 
Zhang and Gildea (2008) describes a coarse-to-fine approach that iteratively increases the order of the LM. 
