(Schulte im Walde, 2006; Sun et al., 2008; Li and Brew, 2008; Korhonen et al., 2008).


2.2 Feature sets The first feature set F1 includes information about the lexical context (co-occurrences) of verbs which has proved useful for supervised verb classification (Li and Brew, 2008): F1: Co-occurrence (CO): We adopt the best method of Li and Brew (2008) where collocations are extracted from the four words immediately preceding and following a lemmatized verb.


645 On T1, the best performing supervised method reported so far is that of Li and Brew (2008).


In recent years, a variety of approaches have been proposed for automatic induction of verb classes from corpus data (Schulte im Walde, 2006; Joanis et al., 2008; Sun et al., 2008; Li and Brew, 2008; Korhonen et al., 2008; O Seaghdha and Copestake, 2008; Vlachos et al., 2009).


F5 which combines a SCF with CO information proved the best feature set in the supervised verb classification experiment of Li and Brew (2008).


