Snyder and Barzilay (2008) study the task of unsupervised morphological segmentation of multiple languages. 
Snyder and Barzilay (2008) uses a set of aligned phrases across related languages to learn how to segment words with a Bayesian model and is otherwise fully unsupervised. 
4.3 Bilingual Experiments Leveraging information from one language for the task of disambiguating another language has received considerable attention (Dagan, 1991; Smith and Smith, 2004; Snyder and Barzilay, 2008; Burkett and Klein, 2008). 
Others model segmentation using a joint probabilistic distribution (Goldwater et al., 2006; Creutz and Lagus, 2007; Snyder and Barzilay, 2008b); they learn the model parameters from unlabeled data and produce the most probable segmentation as the final output. 
Using a fraction of the labeled data, it already outperforms Snyder & Barzilays supervised results (2008a), which further demonstrates the benefit of using a log-linear model. 
