D09-1054:1	37:240	Our graphical representation has two advantages over previous work (Ding et al., 2008): unifying sentence relations and incorporating question interactions.
---------------------------------------------------
D09-1054:2	209:240	In comparison, the 2D model in Figure 2(c) used in previous work (Ding et al., 2008) can only model the interaction between adjacent questions.
---------------------------------------------------
D09-1054:3	168:240	We made use of the same data set as introduced in (Cong et al., 2008; Ding et al., 2008).
---------------------------------------------------
D09-1054:4	124:240	Note that apart from previous work (Ding et al., 2008) we use complete skip-chain (contextanswer) edges in hc(x,y).
---------------------------------------------------
D09-1054:5	8:240	1 Introduction Recently, extracting questions, contexts and answers from post discussions of online forums incurs increasing academic attention (Cong et al., 2008; Ding et al., 2008).
---------------------------------------------------
D09-1054:6	47:240	We design special inference algorithms, instead of general-purpose inference algorithms used in previous works (Cong et al., 2008; Ding et al., 2008), by taking advantage of special properties of our task.
---------------------------------------------------
D09-1054:7	193:240	The suffixes C* and V* denote the models using incomplete skip-chain edges and vertical sequential edges proposed in (Ding et al., 2008), as shown in Figures 2(a) and 2(c).
---------------------------------------------------
D09-1054:8	43:240	Previous work (Ding et al., 2008) performs the extraction of contexts and answers in multiple passes of the thread (with each pass corresponding to one question), which cannot address the interactions well.
---------------------------------------------------
