E09-1092:1	170:181	Katrenko and Adriaans (2008) explored a con8Banko and Etzioni abstracted over subsets of preclustered terms, built using corpus-wide distributional frequencies strained version of the task considered here.
---------------------------------------------------
W09-2415:2	48:179	As a first step, SemEval2007 Task 4 offered many useful insights into the performance of different approaches to semantic relation classification; it has also motivated followup research (Davidov and Rappoport, 2008; KatrenkoandAdriaans, 2008; NakovandHearst, 2008; O Seaghdha and Copestake, 2008).
---------------------------------------------------
