(Zhao et al., 2008b) acquire paraphrase patterns from bilingual corpora and report the various types obtained.3 (Callison-Burch, 2008) improves the pivot paraphrase acquisition technique by using syntactic constraints at the level of constituents during phrase extraction. 
To address this problem, we have tried combining multiple resources to improve the SMT-based PG model (Zhao et al., 2008a). 
One can refer to (Zhao et al., 2008b) for the details. 
Recently, there are also a number of studies that extract paraphrases from multilingual corpora (Bannard and CallisonBurch, 2005; Zhao et al., 2008). 
Thus the SPG model should be able to easily combine different resources and thereby solve the data shortage problem (Zhao et al., 2008a). 
