2.2 Right-Corner Transform The work described above by Miller and Schuler (2008) uses a right-corner transform. 
Finally, this work is most directly related to that of Miller and Schuler (2008). 
This transformation has been shown to represent the structure of unfinished constituents like those seen in speech repair in a natural way, leading to improved detection of speech repair (Miller and Schuler, 2008). 
This model makes use of the right-corner transform, which has been shown to increase non-incremental parsing accuracy on transcribed spontaneous speech (Miller and Schuler, 2008), using trees transformed in this manner to train the HHMM parser. 
662 Right Corner) is a reproduction of the results from Miller and Schuler (2008). 
