During 20062008, the TRECBlog06 collection has been used for the topical blog post retrieval task (Weerkamp and de Rijke, 2008a) at the TREC Blog track (Ounis et al., 2007): to retrieve postsabout agiventopic.


Finally, Weerkamp and de Rijke (2008b) study 1058 external expansion in the setting of blog retrieval touncoveradditionalperspectivesofagiventopic.


However, when working with user generated content, expanding a query with terms taken from the very corpus in which one is searching tends to be less effective (Arguello et al., 2008a; Weerkamp and de Rijke, 2008b)topic drift is a frequent phenomenon here.


