f5b: POSofthewordwhichthe rightmost constituent word of idiom is the dependent of f6: Hypernyms of words in the surrounding context f7: Domains of words (Hashimoto and Kurohashi, 2007; Hashimoto and Kurohashi, 2008) in the surrounding context  Idiom-Specific Features f8: Adnominal modification flag f9: Topic case marking flag f10: Voice alternation flag f11: Negation flag f12: Volitional modality flag f13: Adjacency flag We used JUMAN, 14 a morphological analyzer of Japanese, and KNP to extract these features.


