Previous studies classify sentences as speculative or not, therefore implicitly assigning the scope of a speculation to the whole sentence (Light et al., 2004; Medlock and Briscoe, 2007; Szarvas, 2008; Kilicoglu and Bergler, 2008). 
They state that this approach works accurately for clinical free texts, but no any results are reported (Szarvas, 2008). 
While Medlock & Briscoe use words as features, Szarvas (2008) extends their work to n-grams. 
In addition, by following the annotation guidelines of Medlock and Briscoe (2007), Szarvas (2008) made available the BMC Bioinformatics data set, by annotating four full text papers from the open access BMC Bioinformatics website. 
Szarvas (2008) follows Medlock and Briscoe (2007) in classifying sentences as being speculative or nonspeculative. 
