Automatically determining the degree of antonymy between words has many uses including detecting and generating paraphrases (The dementors caught Sirius Black / Black could not escape the dementors) and detecting contradictions (Marneffe et al., 2008; Voorhees, 2008) (Kyoto has a predominantly wet climate / It is mostly dry in Kyoto). 
The recent CoNLL shared tasks (Surdeanu et al., 2008; Hajic et al., 2009) have been focusing on semantic dependency parsing along with the traditional syntactic dependency parsing. 
Some other researchers also work on detecting negative cases, i.e. contradiction, instead of entailment (de Marneffe et al., 2008). 
Automatic discovery of functional relations has been addressed in the database literature as Functional Dependency Mining (Huhtala et al., 1999; Yao and Hamilton, 2008). 
This can be the base of a principled method for detecting structural contradictions (de Marneffe et al., 2008). 
