For this data set, it is not clear that improving alignment error rate beyond that of GIZA++ is useful for translation (Ganchev et al., 2008).


Languages or language Number of papers pairs considered 0 3 1 95 2 13 3 3 4 2 5 1 12 1 13 1 Total 119 Table 1: Number of languages/language pairs considered The two papers looking at the widest variety of languages were (Ganchev et al., 2008) and (Nivre and McDonald, 2008).


