W09-2502:1	49:218	The RTE-3 PILOT (Voorhees, 2008) reported someaccuracymeasuresconditionedongoldstandard labels as follows: Aa493a0L;G, ga8 a16 a176N ia1611 a0a114La112x ia113a1153 a16 a114Ga112xia113a1153 a16 g a8 a176N ia1611 a0a114Ga112x ia113a1153 a16 g a8 , Aa492a0L;G, ga8 a16 a176N ia1611 a0a114La112x ia113a1152 a16 a114Ga112xia113a1152 a16 g a8 a176N ia1611 a0a114Ga112x ia113a1152 a16 g a8 . Assuming the usual analogy with IR, we note that Aa492a0L;G,trianglea8 is akin to recall.
---------------------------------------------------
W09-2502:2	16:218	1see the reports on RTE-1 (Dagan et al., 2005), RTE-2 (Bar-Haim et al., 2006), RTE-3 (Giampiccolo et al., 2007), the RTE-3 PILOT (Voorhees, 2008), RTE-4 (Giampicolo et al., 2008), and RTE-5 (TAC, 2009) The problem of bias is quite general and widely known.
---------------------------------------------------
D08-1002:3	200:218	RTE-3 included an optional task, requiring systems to make a 3-way distinction: {entails, contradicts, neither}(Voorhees, 2008).
---------------------------------------------------
D08-1002:4	10:218	They report 23% precision and 19% recall at detecting contradictions in the RTE-3 data set (Voorhees, 2008).
---------------------------------------------------
