In (Duh and Kirchhoff, 2008), MERT is used to boost the BLEU score on Table 1: Corpus statistics for three text translation sets: Arabic-to-English (aren), Chinese-to-English (zhen), and English-to-Chinese (enzh).


(Duh and Kirchhoff, 2008) ingeniously uses MERT as a weak learner in a boosting algorithm that is applied to the n-best reranking task, with good results (a gain of about 0.8 BLEU on the test set).


