For example, presenting differing numbers of attributes to the user, and making the user more or less likely to choose an item, as shown by (Rieser and Lemon, 2008b) for multimodal interaction.


Simulation-based RL allows to explore unseen actions which are not in the data, and thus less initial data is needed (Rieser and Lemon, 2008b).


689 We are currently collecting data in targeted Wizard-of-Oz experiments, to derive a fully datadriven training environment and test the learnt policy with real users, following (Rieser and Lemon, 2008b).


(Singh et al., 2002; Henderson et al., 2008; Rieser and Lemon, 2008a) and conversation as action under uncertainty (Paek and Horvitz, 2000).


