To address this problem, we have tried combining multiple resources to improve the SMT-based PG model (Zhao et al., 2008a). 
(Zhao et al., 2008b) acquire paraphrase patterns from bilingual corpora and report the various types obtained.3 (Callison-Burch, 2008) improves the pivot paraphrase acquisition technique by using syntactic constraints at the level of constituents during phrase extraction. 
The details of the corpora, methods, and score functions are presented in (Zhao et al., 2008a). 
Thus the SPG model should be able to easily combine different resources and thereby solve the data shortage problem (Zhao et al., 2008a). 
When attempting paraphrasing on a higher level, such as arbitrary phrases or full sentences (Barzilay and Lee, 2003; Pang et al., 2003; Quirk et al., 2004; Bannard and Callison-Burch, 2005; Zhao et al., 2008a), a first issue concerns the acquisition of elementary units, which in the general case do not exist in predefined dictionaries. 
