Recently, CRF using tree structures were used in (Finkel et al., 2008) in the case of parsing. 
Once we have converted our sentences into parse trees, we train a discriminative constituency parser similar to that of (Finkel et al., 2008). 
796 Recall Precision F-score Time (min) This work (deterministic) 86.3 87.5 86.9 0.5 This work (search, beam width = 4) 88.2 88.7 88.4 1.7 Huang (2008) 91.7 Unk Finkel et al. 
SGD was recently used for NLP tasks including machine translation (Tillmann and Zhang, 2006) and syntactic parsing (Smith and Eisner, 2008; Finkel et al., 2008). 
Once each sentence has been converted into a tree, we train a discriminative constituency parser, based on (Finkel et al., 2008). 
