We have proposed an example-based dialog modeling (EBDM) framework using an agenda graph as prior knowledge (Lee et al., 2008).


In the spoken dialog systems, these are manually designed for various purposes including dialog modeling (Bohus and Rudnicky, 2003, Lee et al., 2008), search space reduction (Young et al., 2007), domain knowledge (Roy and Subramaniam, 2006), and user simulation (Schatzmann et al., 2007).


