Elsner and Charniak (2008) propose the task of conversation disentanglement from internet chatroom logs. 
This represents a moderate improvement on the inference scheme described in Elsner and Charniak (2008). 
9The F-score metric is not used in Elsner and Charniak (2008); we compute it ourselves on the result produced by their software. 
Elsner and Charniak (2008) address the related problem of disentanglement (which we explore in Section 5.3), doing inference with the voting greedy algorithm. 
Elsner and Charniak (2008) specify a list of cue phrases by hand; the cue phrases are used as a feature in a maximum-entropy classifier for conversation disentanglement. 
