Plan-based approaches (Allen and Perrault 1979; Litman 1986; Carberry 1990; Lambert and Carberry 1991) start by applying context-independent inference rules to identify the agent's task-related plan, possibly favoring alternatives that extend a previously recognized plan.


Allen and Perrault (1979), Perrault and Allen (1980) show how plan recognition can be used to understand indirect speech acts (such as the use of "Can you pass the salt"?


6 In defining linguistic intentions, which are shown in Figure 1, we have followed existing speech act taxonomies, especially those given by Bach and Harnish (1979), Allen (1983), and Hinkelman (1990).


