Kwasny aod Sondheimer (1979) present techniques for understanding several classes of syntactically ill-formed input. 
(1978) and Kwasny and Sondheimer (1979). 
Devices for designing more "friendly" systems, such as the work on graceful interaction (Kaplan 1978, Hayes and Reddy 1979, Weischedel and Sondheimer 1981) are relevant to the question of relating sublanguage-specific phenomena to those of the whole language. 
Pattern-matching as an alternative to a top-down, left-to-right parser, has often been suggested as a means of processing ill-formed input, as discussed in Kwasny and Sondheimer (1979), for example. 
,1978; Weischedel and Black, 1980; Kwasny and Sondheimer, 1979). 
