J83-3003:1	522:696	Some initial steps in this direction have been taken in Carbonell (1979), but there is much to be done.
---------------------------------------------------
C80-1008:2	162:223	Somewhat similar processing can be seen in dealing with typographic errors (Biermann and Ballard, 1978), learning new names (Codd et al. , 1978), and learning new words (Carbonell, 1979, and Miller, 1975).
---------------------------------------------------
J83-3001:3	123:708	So, for instance, such techniques are likely to be more effective using a semantic grammar (Hendrix 1977, Brown and Burton 1975) or case frame instantiation (Dejong 1979, Hayes and Carbonell 1981) approach, than in an approach using a syntactic ATN (Woods, Kaplan and Nash-Webber 1972), where the expectations are never more specific than membership in one or more general syntactic categories.
---------------------------------------------------
J83-3001:4	57:708	Apply the project and integrate method (Carbonell 1979) to infer the meaning and syntactic category of the word from context.
---------------------------------------------------
J83-3001:5	10:708	Other researchers have attempted to deal with ungrammatical input through network-based semantic grammar techniques (Hendrix 1977), through extensions to pattern matching parsing in which partial pattern matching is allowed (Hayes and Mouradian 1981), through conceptual case frame instantiation (Dejong 1979, Schank, Lebowitz, and Birnbaum 1980), and through approaches involving multiple cooperating parsing strategies (Carbonell and Hayes 1984, Carbonell et al. 1983, Hayes and Carbonell 1981).
---------------------------------------------------
P80-1025:6	2:37	For instance, Carbonell (1979) discusses inferring the meaning of new words.
---------------------------------------------------
W97-0313:7	200:264	Some systems learn the meanings of unknown words using expectations derived from other word definitions in the surrounding context (e.g. , (Granger, 1977; Carbonell, 1979; Jacobs and Zernik, 1988; Hastings and Lytinen, 1994)).
---------------------------------------------------
