There has been a long tradition on the use of graphs for this kind of sentence representation, such as Sowas Conceptual Graphs (Sowa, 1979), and Quillians Semantic Nets (Quillian, 1968).


Considering that text information as complex as syntactic information or even logic and semantic information can be expressed in graphs (Quillian, 1968; Schank, 1972; Sowa, 1979), we are convinced that the time is ripe to explore the use of graphs for question answering.


In contrast, other theories (such as Sowa (1979)s Conceptual Graphs) would represent the sentence as a graph containing vertices that are themselves graphs.


