Weischedel and Black (1980) discuss techniques for interacting with the linguist/developer to identify insufficiencies in the grammar.


This frees us from pre-specifying either all "correct" linguistic possibilities for constraint satisfaction at all levels of representation, or all possible errors or recognized omissions as in more flexible approaches (Hayes and Mouradian, 1981; Kwasny and Sondheimer, 1981; Lehnert, Dyer, Johnson, Yong, and Hurley, 1983; Weischeidel and Black, 1980).


Other ideas such as passing infox~nation in the case of failure (Weisohedel and Black, 1980) or relaxing conditions on aras in certain oirotvastances (Kwasny and Sondheimet, 1979) do not seem to be satisfying solutions for our px~bl~.


