Wilensky, R. and Y. Arens, "PHRAN: A Knowledge-Based Approach to Natural Language Analysis," in Proceedings 18th Annual Meeting of the Asosciation for Computational Linguistics, Philadelphia, PA (1980). 
In PHRAN (Wilensky and Arens 1980), specificity plays a role, but only in suggesting patterns that match the input: evaluation takes place on the basis of length and order of the patterns. 
Other aspects of the UC system are described in Arens (1982}, Faletti (1982}, Jacobs (1983}, Rau {1983), and Wilensky and Arens (1980a and b). 
Intuitively, some sort of pattern matching seems to be appropriate for analysing idioms (see e.g. Wilensky and Arens, 1980). 
, e.g., 9 Wilks 1977 and Wilensky & Arens 1980). 
