P83-1023:1	87:315	Slocum (1981) shows that a left-corner parser inspired by Griffiths and Petrick's algorithm performs quite well when compared with parsers based on a Cocke-KasamiYounger algorithm (see Younger 1967).
---------------------------------------------------
E87-1037:2	101:207	Descriptions of top-down filtering are given for example in Kay (1982) (~directed bottom-up parsing") and in Slocum (1981:2).
---------------------------------------------------
E87-1037:3	32:207	As for empirical studies, Slocum (1981) is a rich source.
---------------------------------------------------
P90-1038:4	155:217	A strategy called top-down filtering in order to circumvent such a problem has been stated, and it is adopted within bottom-up parsers (Kay, 1982; Pratt, 1975; Slocum, 1981; Wir6n, 1987) where it simulates a top-down parser together with the bottom-up parser.
---------------------------------------------------
J84-2001:5	218:378	Experiments with the LDC Grammar and Parser Having completed the parser and constructed a suitably broad grammar for use in several layered domains, we have begun to experiment with our parser in the manner of Slocum (1981) to see how significantly certain of our Computational Linguistics Volume 10, Number 2, April-June 1984 89 Bruce W. Ballard and Nancy L. Tinkham A Phrase-Structured Grammatical Framework for Transportable NLP pruning methods can reduce the time complexity of parsing.
---------------------------------------------------
J84-3001:6	79:379	For an empirical comparison of various parsing methods, see Slocum (1981).
---------------------------------------------------
C82-1054:7	6:144	Slocum (1981) shows that a left-corner parser inspired by Griffiths and Petrick's algorithm and by Chester's performs quite well when compared with parsers based on a Cocke-KasamiYounger algorithm (see Younger 1967).
---------------------------------------------------
C82-1054:8	143:144	Slocum, J. , A practical comparison of parsing strategies, Proceedings of the 19th Annual Meeting of the ACL, (1981) 1-6.
---------------------------------------------------
