Once more, see Cohen (1981) for further examples.


12 Computational Linguistics, Volume 13, Numbers I-2, January-June 1987 Robin Cohen Analyzing the Structure of Argumentative Discourse The associated reception algorithms for preand postorder are described in detail in Cohen (1981).


Various types of content units and structures needed to account for knowledge processing have been proposed in the general context of modeling discourse understanding (e.g. , Allen 1981; Cohen 1981; Dyer 1982; Wilensky 1980).


