J83-3001:1	51:708	In the first situation, there is no meaningful recovery strategy other than focused interaction (Hayes 1981) to inform the user of the precise difficulty.
---------------------------------------------------
J83-3001:2	469:708	Our earliest experiments in robust parsing were conducted through the FlexP parsing system (Hayes and Mouradian 1981).
---------------------------------------------------
J83-3001:3	471:708	Indeed, many of our ideas on the importance of those characteristics were developed though observation of FlexP's shortcomings as described in 3.5.2, and more fully in Hayes and Carbonell (1981).
---------------------------------------------------
J83-3001:4	123:708	So, for instance, such techniques are likely to be more effective using a semantic grammar (Hendrix 1977, Brown and Burton 1975) or case frame instantiation (Dejong 1979, Hayes and Carbonell 1981) approach, than in an approach using a syntactic ATN (Woods, Kaplan and Nash-Webber 1972), where the expectations are never more specific than membership in one or more general syntactic categories.
---------------------------------------------------
J83-3001:5	429:708	As Hayes and Carbonell (1981) show, parsers based on case frame instantiation are particularly well suited to generating ambiguity representations of this kind.
---------------------------------------------------
J83-3001:6	297:708	This process is also responsible for noticing when information is either missing or ambiguously determined, thereby initiating a focused clarificational dialogue (Hayes 1981).
---------------------------------------------------
J83-3001:7	10:708	Other researchers have attempted to deal with ungrammatical input through network-based semantic grammar techniques (Hendrix 1977), through extensions to pattern matching parsing in which partial pattern matching is allowed (Hayes and Mouradian 1981), through conceptual case frame instantiation (Dejong 1979, Schank, Lebowitz, and Birnbaum 1980), and through approaches involving multiple cooperating parsing strategies (Carbonell and Hayes 1984, Carbonell et al. 1983, Hayes and Carbonell 1981).
---------------------------------------------------
J83-3001:8	269:708	It is possible to accept any permutation of elements of a pattern as a match, but this provides so much flexibility that many spurious recognitions are likely to be obtained as well as the correct ones (see Hayes and Mouradian 1981).
---------------------------------------------------
J83-3001:9	278:708	See Hayes and Carbonell (1981) for a fuller discussion of this point.
---------------------------------------------------
J83-3001:10	478:708	Our initial experiments in realizing these advantages were conducted through the CASPAR parser (Hayes and Carbonell 1981).
---------------------------------------------------
J83-3001:11	694:708	Even assuming that the above example had a unique result, since it involved several significant assumptions, we would need to use focused interaction techniques (Hayes 1981) to present a paraphrase of our interpretation to the user for approval before acting on it.
---------------------------------------------------
P95-1034:12	11:264	Although robustness has been heavily studied in natural language understanding (Weischedel and Black, 1980; Hayes, 1981; Lavie, 1994), it has received much less attention in NLG (Robin, 1995).
---------------------------------------------------
