This treatment of the logical form of quantifiers follows that employed in many previous systems (e.g. , LUNAR (Woods, 1977), Moore (1981), Barwise and Cooper (1981), and Hobbs and Shieber (1987)). 
Moore, R. C: (1981): "Problems in Logical Form". 
This reflects observations of Moore (1981) and others that determiners rarely have a direct correlation with the existential and universal quantifiers of first-order logic. 
Moore, R. C. [1981] "Problems in Logical Form," in Proceedings of the 19th Annual Meeting of the Association for Computaional Linguistics, pp. 
The separation of these two semantic roles of range and scope into restriction and body as an important fact of the logical structure of English can be seen, for example, in Woods's four-part quantifier structures (Woods 1977), in the recommendations of Moore (1981), and in the generalized quantifier research of Barwise and Cooper and others. 
