Recent work on treating departures from grammaticality (Sondheimer and Weischedel 1980, Hayes and Mouradian 1980, McKeown 1980, Kwasny and Sondheimer 1981, Miller et al. 1981) can be use in handling specialized language that deviates syntactically from the standard language.


Devices for designing more "friendly" systems, such as the work on graceful interaction (Kaplan 1978, Hayes and Reddy 1979, Weischedel and Sondheimer 1981) are relevant to the question of relating sublanguage-specific phenomena to those of the whole language.


