These include Kaplan (1979), Harris (1979), Hendrix and Lewis (1981), and Grosz et.


A new technique for developing transportable systems for natural-language interfaces to databases (Hendrix and Lewis 1981) elicits from the user a language for querying the contents at the same time that information about the domain is being entered.


Accordingly, prototype systems that permit user customizations or rapid customizations by a designer have included REL, POL and ASK (Thompson and Thompson 1975, 1981, 1983), CONSUL (Mark 1981; Wilczynski 1981), IRUS (Bates and Bobrow 1983), KLAUS (Haas and Hendrix 1980), TEAM (Hendrix and Lewis 1981; Grosz 1983), a system developed at Bell Labs (Ginsparg 1983), and our own LDC system (Ballard 1982, 1984; Ballard and 1 This research was supported in part by the National Science Foundation under Grant Numbers MCS-81-16607 and IST-83-01994 and in part by the Air Force Office of Scientific Research under Grant Number 81-0221.


