3.2 The semantic control of a system: choosers and inquiries Now, we can organize a semantic interface in terms of the system network, which is what Bill Mann and I did in the development of the chooser and inquiry framework for one particular systemic generation grammar, the Nigel grammar developed at USC/ Information Sciences Institute (Matthiessen, 1981; Mann, 1982; Matthiessen, 1988); this framework was then adopted and extended for the systemic generator of Japanese and Chinese by John Bateman and associates at Kyoto University (Bateman & Matthiessen, forthcoming).


