One is by Rosenschein & Shieber (1982), another by Gawron et al.


The HPSG system differs from its predecessor GPSG, reported on at the 1982 ACL meeting (Gawron et al. 119821), in four significant respects: syntax, lexical representation, parsing, and semantics.


Gawron et al (1982) have implemented a database interface based on GFSG.


Hendler and Phillips (1981; Phillips and Hendler 1982) have implemented a control structure for NLU 18Gawron et al produce all poslible trees and their tranilations for the input sentence, s.nd then throw away any that don't make sense to the database.


