Rosenschein, S.J. and Shieber, S.M.(1982): Translating English into Logical Form, Proc. 
1981, Schubert & Pelletier 1982, Gawron et al 1982, Rosenschein & Shieber 1982). 
Rosenschein, S. & S. Shieber (1982) "Translating English into Logical Form" Proc. 
One is by Rosenschein & Shieber (1982), another by Gawron et al. 
Schubert and Peiletier (1982) have also sought to simplify the semantic output of a GPSG to a more ~conventional" logical form; and Rosenschein and Shieber (1982) describe a similar translation process into extensional logical forms, using a context-free grammar intended to be similar to a GPSG. 
