W00-1437:1	17:111	(In many other approaches, speed is a function of the grammar size, because it is searched during realization (Elhadad, 1992; Elhadad, 1993; Mann, 1983; McKeown, 1982; McKeown, 1985)).
---------------------------------------------------
J86-2002:2	397:618	The approach taken in McKeown's (1982) TEXT system is also appealing in this regard since its area of application is data bases (albeit describing database structure rather than database contents).
---------------------------------------------------
J86-2002:3	20:618	McCoy (1982) and McKeown (1982) attempt to provide answers to questions about the structure of the data base rather than extensional information as to its contents.
---------------------------------------------------
