Together with the heuristics, they give our system many of the abilities of McCoy's (1982) ENHANCE system to reflect a user's preconceived notions as to which patterns of data are meaningful and which are not.


McCoy (1982) and McKeown (1982) attempt to provide answers to questions about the structure of the data base rather than extensional information as to its contents.


The interesting patterns are similar to McCoy's (1982) "distinguishing descriptive attributes", although we use them to produce summary responses rather than to answer questions on database structure.


In this sense they are very similar to McCoy's (1982) "very specific axioms", although how they interact with heuristics to produce summary responses is different.


Preferred attributes perform for our system the same function that McCoy's (1982) "important attributes list" does for the ENHANCE system.


