P92-1007:1	25:232	Mumble-86 is one of the foremost sentence generation systems and it (or its predecessors) has been used as the sentence generation components of a number of natural language generation projects (e.g. , (McDonald, 1983; McCoy, 1989; Conklin & McDonald, 1982; Woolf& McDonald, 1984; Rubinoff, 1986)).
---------------------------------------------------
P06-1131:2	133:192	The salience ordering of the landmarks is inspired by (Conklin and McDonald, 1982) who found that the higher the salience of an object the more likely it appears in the description of the scene it was embedded in.
---------------------------------------------------
J89-4002:3	216:518	We can see elements of such a language in the "realization specifications" of McDonald and Conklin (1982) and in the "protosentences" of Mann and Moore (1981).
---------------------------------------------------
J84-1001:4	63:369	3 Conklin and McDonald (1982) have used salience as a means of solving the selection problem in natural language generation using KL-ONE as the representation language.
---------------------------------------------------
