P84-1026:1	136:308	For example, an infinite intersection with a regular set having the form of a triple-counting language or a string matching language (Pullum 1983) would suffice.
---------------------------------------------------
C86-1014:2	14:184	The Immediate dominance and linear precedence (ID/LP) framework~ developed by Gazdar and Pullum~ is one of the most debated theories in the study of word order variation (Pullum 1982~ Uszkorelt 1082, Shieber 1983, Barton 1985).
---------------------------------------------------
