A92-1009:1	140:147	 Transparency of Capabilities: NL understandinl systems are in general only capable of answering subset of the questions the user is able to pose, an( the user may become confused if he is not aware o the boundaries of this subset \[Tennant et al. , 1983\] This problem does not arise with hypertext, whet, the user is only allowed to issue questions that th, system can answer.
---------------------------------------------------
W08-1118:2	16:212	Natural language approaches include GINO (Bernstein and Kaufmann, 2006), an ontology editor with an approach reminiscent of Natural Language Menus (Tennant et al., 1983), and using Controlled languages such as PENG-D (Schwitter and Tilbrook, 2004).
---------------------------------------------------
J07-1006:3	7:422	Introduction Where early attempts to build natural language question-answering systems focused on accessing and presenting information held in (closed domain) databases (e.g., Hendrix et al. 1978; Templeton and Burger 1983; Kaplan 1984; Hafner and Godden 1985), the advent of the World Wide Web has led to a shift towards (open domain) collections of texts.
---------------------------------------------------
J07-1006:4	47:422	Broadly, research in NLIDBs has addressed the following issues: 2 a114 domain knowledge acquisition (Frank et al. 2005) a114 interpretation of the NL input query, including parsing and semantic disambiguation, semantic interpretation, and transformation of the query to an intermediate logical form (Hendrix et al. 1978; Zhang et al. 1999; Tang and Mooney 2001; Popescu, Etzioni, and Kautz 2003; Kate, Wong, and Mooney 2005) a114 translation to a database query language (Lowden et al. 1991; Androutsopoulos 1992) a114 portability (Templeton and Burger 1983; Kaplan 1984; Hafner and Godden 1985; Androutsopoulos, Ritchie, and Thanitsch 1993; Popescu, Etzioni, and Kautz 2003) 1 Leaving aside here the possibility of errors in parsing and interpretation.
---------------------------------------------------
P98-2173:5	181:184	Feedback texts with menus have been used before in the NL-Menu system (Tennant et al. , 1983), but only as a means of presenting syntactic options.
---------------------------------------------------
J87-1004:6	327:411	NLMenu (Tennant et al. 1983) adopted on-line parsing for a menu-based system but not for typed inputs.
---------------------------------------------------
C92-4206:7	6:137	, 1983), and forms (Cohen et al. , 1989).
---------------------------------------------------
