The WoEd Expmrt Parser (WEP) b~iefly described The Word Expert Parser (WEP, Small 1980) is a natural language understanding program in the AI tradition of semantic parsing (see also Hirst 1983v Hahn 1986, Cottrell 1985, Adriaens 1986a/b for WEP-inspired or -related work).


This concept is intuitive when reasoning about the link between syntax and semantics, and it has been used earlier in semantic interpreters such as Absity (Hirst, 1983).


