Recognition for such 'off-line parsable' grammars is decidable (Pereira and Warren, 1983). 
1.1 Dynamic programming as deduction The parsing as deduction framework (Pereira and Warren, 1983) is now over 20 years old. 
It is exactly this mismatch between structure of the traversal and 2Pereira and Warren (1983) point out that Earley deduction is not restricted to a left-to-right expansion of goals, but this suggestion was not followed up with a specific algorithm addressing the problems discussed here. 
Some of the constraints (Pereira and Warren, 1983; Kaplan and Bresnan, 1982; Johnson, 1988; Kuhn, 1999) apply only to skeletal grammars since they use the term category which is not well de ned for general unication grammars. 
and D.H.D. Warren (1983), "Parsing as Deduction", Prec. 
