4For justification for this kind of logical form for sentences with quantifiers and inteusional operators, see Hobbs(1983) and Hobbs (1985a). 
It may prevent the anaphoric binding of pronouns, as in (78), but this is part of a more general problem for which there is no satisfactory theory at the moment (see Lepore & Garson 1983; Schubert & Pelletier 1987a,1987b; Hobbs & Shieber 1987). 
To this end, the logical framework includes the notion of typical element (from Hobbs (1983, 1995, 1998)). 
But we can get around this if, following the approach taken by Hobbs (1983), we take a donkey to be generic, take it to refer to the unique generic donkey that m owns, and assume that to beat a generic donkey is to beat all its instances. 
Quantifier Scope Ambiguity in Logical Form Quantifier scope ambiguity has been handled by some researchers by using an intermediate scope-neutral LF (e.g. , Hobbs 1983; Schubert and Pelletier 1984; Allen 1987) for the initial representation of sentences. 
