Nigel (Mann, 1983) is a fourth system that makes use of functional information and is based on systemic grammar (Hudson, 1974).


A generation goal and the sentence it produces are shown in Figure I. 4.2 Functional Grammars Another formalism that has been used in previous.generation systems (McKeown, 1982; Appelt, 1983) is the functional grammar formalism (Kay, 1979) 4 . In a functional, grammar, functional information such as focus and protagonist are treated in the same manner as syntactic and grammatical information such as subject and NP.


These include devices such as interleaving the components (McDonald 1983; Appelt 1983), backtracking on failure (Appelt 1985; Nogier 1989), allowing the linguistic component to interrogate the planner (Mann 1983; Sondheimer and Nebel 1986), and Hovy's notion of restrictive (i.e. , bottom-up) planning (Hovy 1988a, 1988c).


