112 Computational Linguistics Volume 10, Number 2, April-June 1984 Philip R. Cohen The Pragmatics of Referring and the I~lodality of Communication 6.2 Analyzing indirect identification requests Perrault and Allen (1980) have proposed the following plan-recognition inferences:  Action-effect: If the observer thinks the agent wants to do an action, the observer can posit that the agent wants that action done in order to achieve its typical effect.


8.5 Searle vs. Russell Using the propositional act of referring, Searle argues against Russell's (1905) theory of descriptions, which holds that the uttering of an expression "the if" is equiv3, The analysis of referring in Cohen (1984) makes use of a theory of communication of Cohen and Levesque (1980, in preparation) that does not require the recognition of illocutionary acts.


Ochs et al. suggest that the presence of sequential Computational Linguistics Volume 10, Number 2, April-June 1984 109 Philip R. Cohen The Pragmatics of Referring and the Modality of Communication Table 1.


118 Computational Linguistics Volume 10, Number 2, April-June 1984 Philip R. Cohen The Pragmatics of Referring and the Modality of Communication 8.1 Referring as a propositional speech act Revising Austin's (1962) locutionary/illocutionary dichotomy, Searle distinguishes between illocutionary acts (IAs) and propositional acts (PAs) of referring and predicating.


t6 For a formal analysis that does make such a claim, see section 8.4 and Cohen (1984).


