See Karttunen (1984). 
For example, "negative values" and "disjunctive values" allow grammars and lexical entries to be written much more succinctly, as the following examples show (based on Karttunen 1984). 
On this interpretation, unification of two sets of categories can be defined as the set of categories each of whose members is the unification of a pair in their Cartesian product (again, see Karttunen (1984) for relevant discussion of this kind of approach). 
And, in a discussion of possible enhancements to the PATR II formalism, Karttunen (1984) provides a number of very relevant examples that illustrate the issues that arise when a unification-based formalism is augmented in order to encompass disjunction. 
Karttunen, Laud (1984) "Features and Values", in Proceedings of Coling84, Association for Computational Linguistics, Morristown, NJ, pp. 
