, 1984; Zuckerman, 1990), and particular inferences have been considered in lexical choice (Reiter, 1990) and in generating narrative summaries (Cook et al. , 1984).


This study is just a beginning of lot of exciting research ! References \[Cook84\] Cook, M.E. et al. 1984.Conveying implicit content in narrative summaries Proceedings of lOth International Conference on Computational Linguistics, (COLING-84), pp 5-7, Stanford University.


