For example, (Briscoe and Carroll, 1993) train an LR parser based on a general grammar to be able to distinguish between likely and unlikely sequences of parsing actions; (Andry et al. , 1994) automatically infer sortal constraints, that can be used to rule out otherwise grammatical constituents; and (Grishman et al. , 1984) describes methods that reduce the size of a general grammar to include only rules actually useful for parsing the training corpus.


Examples of sublanguages that have been studied are weather reports (Chevalier et al. 1978), aircraft maintenance manuals (Lehrberger 1983), medical reports (Hirschman and Sager 1983), and equipment failure reports (Marsh, Hamburger, and Grishman 1984).


