Typical planners will be concerned with chunking into sentences, topic selection and word choice (see, e.g., Appelt(1985), Danlos (1984), Hovy(1985), Kukich (1983), McKeown (1985), McDonald (1984)), and Mann (1983)). 
In this regard, the system within which PHRED operates does not promote the desirable interaction among text planning and structural choices, as suggested by Appelt (1982) and Danlos (1984). 
~SSee Danlos (1984) for examples of how the order of execution of tasks can favour a certain textual result over another. 
Apparently, this was due to the well known fact that elements of the linguistic structure are strongly correlated with one another (see e.g. [Danlos, 1984]). 
e.g. [Danlos, 1984]). 
