The conversational maxims of H. Paul Grice \[1977\] are a well-known set of observations about human discourse frequently used in computational dialogue research (for example \[Joshi et al 1984\], \[Moore and Paris 1989\], \[Reichman 1985\]).


1 Introduction The notion of a cooperative response has been the focus of considerable research in natural language and spoken dialogue systems (Allen and Perrault, 1980; Mays, 1980; Kaplan, 1981; Joshi et al., 1984; McCoy, 1989; Pao and Wilpon, 1992; Moore, 1994; Seneff et al., 1995; Goddeau et al., 1996; Pieraccini et al., 1997).


CT's response is more cooperative since identifying the source of a query failure can help block incorrect user inferences (Pieraccini et al., 1997; Pao and Wilpon, 1992; Joshi et al., 1984; Kaplan, 1981; Mays, 1980).


