J87-3001:1	113:176	This parsing technique is different in kind from the more common approach to robust parsing in which exact grammar rules are tried first before being relaxed by the parser (see e.g. Weischedel and Black, 1980, Kwasny and Sondheimer, 1981, and Pulman, 1984).
---------------------------------------------------
E87-1008:2	9:110	In contrast to other approaches (c.f. Barchan et al. 1985, Pulman 1984, Schwind 1987) we concentrate our efforts more on the handling of fragmentory utterances, instead of trying to analyse the correctness of complete sentences.
---------------------------------------------------
C88-2127:3	7:174	Related research has been carried out by \[MENZEL 1986; PULMAN 1984; WEISCHEDEL et al. 1978\].
---------------------------------------------------
