Such systems are very efficient but are limited to the domain they are built for: interpretation rules are inferred from the observation of specific semantic patterns (Marsh, 1984) or from a fine-grained conceptual representation (Ter Stal, 1996).


Because compounds can be used as a text compression device (Marsh 1984), it is plausible that pragmatic inference is required to supply the compounds interpretation.


This finding is not entirely unexpected, considering that compounds are typically used as a text compression device (Marsh 1984), that is, to pack meaning into a minimal amount of linguistic structure.


But since the sentence graphs, as mentioned above, are currently large, we have restricted the chains recognized to simple noun and verb chunks (Abney, 1991) rather than the more complex chains (Marsh, 1984) we recognize for European languages.


