An earlier version of the parser is briefly described in Briscoe & Boguraev (1984). 
Briscoe & Boguraev (1984) and Briscoe (in press) propose a different account of the relationship between parsing and other components of comprehension than that entailed by the Determinism Hypothesis, dubbed the Interactive Determinism Hypothesis (IDH). 
In addition, Briscoe & Boguraev (1984) and Briscoe (in press) propose that a bounded context, deterministic parser in conjunction with an extended categorial grammar will also model these strategies. 
In the final section, we evaluate these predictions in the light of the Determinism Hypothesis (Marcus, 1980) and the Interactive Determinism Hypothesis (Briscoe & Boguraev, 1984; Briscoe, in press) and argue that the Lexicat parser in conjunction with the Interactive Determinism Hypothesis provides the most psychologically plausible and unified account of the parsing of unbounded dependencies. 
Adapted from (Briscoe & Boguraev 1984). 
