One proposal addressing (4) explicitly is to include expert system modules in addition to linguistic rules (Boitet & Gerber, 1984) or to divide the system into expert tasks (Johnson & Whitelock, 1985).


Grammar writing systems (GWS) used in Natural Language Processing (NLP) work have been compared to expert systems (Boitet and Gerber, 1984) by equating the knowledge base to the grammar, and the problem-solving activity to the transformation performed on the text representation structure.


