The idea of a linguistic hierarchy is not novel, having roots in both linguistics \[Lockwood, 1972, Halliday, 1978\] and Artificial Intelligence \[Sondheimer et al. , 1984\].


In one, case constraints are expressed as sets of logical formulas; in the other, KL-ONE is used to encode case frames (Sondheimer et al. 1984).


Semantic constraints may be expressed in several formalisms, such as semantic nets (Bobrow and Webber 1980a,b; Sondheimer et al. 1984), first-order logic, and production rules (for example, PROLOG, Warren et al. 1977).


yes, some monkey hasenemy cheetah hyena jackal leopard lion because <monkeys inhabit at-loc ground> has-enemy cheetah hyena jackal leopard lion 7 Related Work In (Sondheimer et al. , 1984), frame-like structures, KL-ONE structures in fact, are also used to guide semantic interpretation in an application domain.


Most systems that perform semantic interpretation \[Bobrow and Webber, 1980, Sondheimer et al. , 1984, Lytinen, 1984, Hirst, 1987\] address this imprecision by offering means of selecting among alternative interpretations.


