C86-1108:1	13:250	The Importance of Case Frame Information Following Ballard and Tinkham (1984), TELI seeks to enable domain-independent English processing by maintaining detailed case frame information about the phrase types provided for by the system.
---------------------------------------------------
C86-1108:2	9:250	The current prototype of TELI, which runs on a Symbolics Lisp Machine, derives from work at Duke University on the LDC project (Ballard, 1982; Ballard, 1984; Ballard, Lusth, and Tinkharn, 1984; Ballard and Tinkham, 1984).
---------------------------------------------------
C86-1108:3	184:250	1 (1984), 1-23, Ballard, B. and Stumberber, D. Semantic Acquisition in TELl: A Transportable, User-Customized Natural Language Processor.
---------------------------------------------------
J84-2001:4	11:378	Accordingly, prototype systems that permit user customizations or rapid customizations by a designer have included REL, POL and ASK (Thompson and Thompson 1975, 1981, 1983), CONSUL (Mark 1981; Wilczynski 1981), IRUS (Bates and Bobrow 1983), KLAUS (Haas and Hendrix 1980), TEAM (Hendrix and Lewis 1981; Grosz 1983), a system developed at Bell Labs (Ginsparg 1983), and our own LDC system (Ballard 1982, 1984; Ballard and 1 This research was supported in part by the National Science Foundation under Grant Numbers MCS-81-16607 and IST-83-01994 and in part by the Air Force Office of Scientific Research under Grant Number 81-0221.
---------------------------------------------------
J84-2001:5	205:378	The syntactic processing of a representative input for LDC was indicated in Figure 1, and information of the scope of the current syntactic and semantic coverage of LDC can be found in Ballard (1984).
---------------------------------------------------
J84-2001:6	368:378	Our approach differs in that we have built our own retrieval processor and endowed it with the ability o act as a knowledge-base by directly processing complex semantics of English modifiers (Ballard 1984).
---------------------------------------------------
J84-2001:7	204:378	Our current grammar is eight pages in length and, due to consolidations made possible by enhancements to the formalism, allows both whand yes-no questions, imperatives, passives, deep raisings, several forms of fronting, a few discontinuous constituents, and some exotic modifier types mentioned in Ballard (1984).
---------------------------------------------------
J84-2001:8	318:378	The system is loosely based upon strategies developed for our English-language programming system NLC (Ballard and Biermann 1979; Biermann and Ballard 1980; Sigmon 1981; Fink 1982; Geist, Kraines and Fink 1982; and Biermann, Ballard and Sigmon 1983), and has been designed to provide a natural language query capability for office domains whose data are stored on the computer as informally structured textedited data files (Ballard and Lusth 1984).
---------------------------------------------------
J84-2001:9	320:378	We now summarize the operation of the knowledge acquisition and English processing components, referring the reader to Ballard and Lusth (1984) for details concerning retrieval processing.
---------------------------------------------------
J84-2001:10	15:378	0362-613X/84/020081-16503.00 Computational Linguistics Volume 10, Number 2, April-June 1984 81 Bruce W. Ballard and Nancy L. Tinkham A Phrase-Structured Grammatical Framework for Transportable NLP Lusth 1983, 1984; Ballard, Lusth and Tinkham 1984a, 1984b).
---------------------------------------------------
J84-2001:11	218:378	Experiments with the LDC Grammar and Parser Having completed the parser and constructed a suitably broad grammar for use in several layered domains, we have begun to experiment with our parser in the manner of Slocum (1981) to see how significantly certain of our Computational Linguistics Volume 10, Number 2, April-June 1984 89 Bruce W. Ballard and Nancy L. Tinkham A Phrase-Structured Grammatical Framework for Transportable NLP pruning methods can reduce the time complexity of parsing.
---------------------------------------------------
J84-2001:12	120:378	Computational Linguistics Volume 10, Number 2, April-June 1984 85 Bruce W. Ballard and Nancy L. Tinkham A Phrase-Structured Grammatical Framework for Transportable NLP Since the problem of mis-recognitions is especially troublesome in our projected voice-input environment (Biermann et al. 1983), this distinction can be important.
---------------------------------------------------
P86-1005:13	17:247	and Ballard and Tinkham (1984).
---------------------------------------------------
P86-1005:14	16:247	By way of overview, we note that the TELI system derives from previous work on the LDC project, as documented in Ballard (1982), Ballard (1984), Ballard, Lusth and Tinkham (1984).
---------------------------------------------------
P86-1005:15	25:247	By providing for an "extendible" class of constructs, we make the knowledge acquisition module of TELl independent of the natural language portion of the system, whose earlier version has been described in Ballard and Tinkham (1984) and Ballard.
---------------------------------------------------
P86-1005:16	64:247	Concerning the latter assumption, we note that (a) some important disambiguations, including problems of word sense, will have been made during parsing by reference to selectional restrictions (Ballard and Tinkham, 1984), and (b) minimal re-ordering does occur in converting parse trees into internal representations.
---------------------------------------------------
