i55-i69 R.L. Johnson, S. Krauwer, M.A. Rosner, G.B. Varlle (1984) The design of the Kernel Architecture for the Eurotra Software In : Proceedings of COLING 84, ACL, pp.


A more detailed description can be fou0d in Johnson, Krauwer, Rosner, and Varile (1984).


We have argued elsewhere, and at some length (Johnson, Krauwer, Rosner, and Varile 1984, Johnson and Rosner 1984) that it is in the nature of problem-oriented software to embody some theory of the problem domain, and we shall not repeat the detailed arguments here.


