Grosz and Sidner (1986) discuss how DMs are built up, and Chin (1986), Litman and Allen (1984), Carberry (1983), and Allen and Perrault (1980), among others, discuss this process for different aspects of UMs.


Dialog structure is not represented in terms of some actions the user might want to perform as did Grosz (1977), Allen (1979), Litman,Allen (1984) nor in terms of information goals of the user as did Pollack (1984), but we represent and use knowledge about a dialog type.


Litman and Allen (1984) have presented a model for recognizing plans in such situations.


3.1.5 DISCOURSE KNOWLEDGE IN PREFERENCE Discourse knowledge concerns discourse structure, the flow of discourse, and the use of discourse to highlight parts of the real world (see Grosz (1977), Reichman (1978, 1981), Sidner (1979), Allen, Frisch, and Litman (1982), Litman (1983), and Polanyi and Scha (1984~ for detailed treatments on discourse).


