Carberry (1983, 1984, 1985a, 1985b) has extended that into a plan-tracking model for use in interpreting pragmatic ill-formedness and intersentential ellipsis.


We have begun research on how to use pragmatic knowledge in an information-seeking environment for this purpose; see Carberry (1983, 1984) and Ramshaw and Weischedel (1984).


Kaplan (1979), Mays (1980e), and Carberry (1984) have each worked on strategies for dealing wltb particular classes of such praamatlc failures.


Several systems that do assess object similarity (Rumelhart and Abrahamson 1973, McKeown 1982, Carberry 1984, Weiner 1984) use a metric based on distance in some space.


