Such re-representation would be necessary for Amsler's (1984a:458) 'lexical knowledge base \[which\] is a repository of computational information about concepts' and which contains information derived from machine-readable dictionaries, the full text of reference books, the results of statistical analysis of text usages, and data manually obtained from human world knowledge'.


The work in lexicon has centered on a) studies concerned with the utilization of conventional humanoriented dictionaries, newly available in machine-readable form, for computational tasks (e.g. , Amsler 1984a,b; Chodorow et al. 1985; Ahlswede 1985; Markowitz et al. 1986) improving the ancillary capabilities for lexicon systems, such as, for instance, morphological processors and descriptions (e.g. , Nirenburg and Ben Asher 1984; Byrd et al. 1986; Boguraev et al. 1987); c) hand-building of lexicons necessary for natural language systems, often with considerations about extensibility (e.g. , Zernik and Dyer 1985; Bessemer and Jacobs 1987).


Recent work on machine-readable dictionaries offers new and interesting possibilities both for the computerassisted lexicology (see Walker 1984) and for constructing lexical databases derived from the definitions in machine-readable dictionaries and utilized in NLP along with other fields (see Amsler 1982, 1984a; Walker, Amsler 1986, Calzolari 1984a,b).


Much of the MRD-based research has focused on the analysis and exploitation of the sense definitions in MRDs (Amsler 1984a, 1984b, 1987; Alshawi 1987; Alshawi, Boguraev, and Carter 1989; Vossen, Meijs, and denBroeder 1989).


