The presentation of the solution we adopted is based on the classification of sentences containing conjunctions reported in (Huang, 1984) : we will start from the simpler cases and introduce the more ccmplex examples later. 
%~e fragment of grammar reported in (Huang, 1984) gives the i~pression of a set of rules "flatter" than the ones that normally appear in standard grammars (this is not a negative aspect; it is a feature of the ATNs too). 
4b results from the application of the metarule "coord-unit" to the primitive ! 6 The term "unit coordination" for the full constituent coordination comes from (Huang 1984). 
Computationally, it is possible to describe the grammar and heuristic rules for these constraints by ATN networks, logic grarnmars~ HPSG~ and categorical grammars(Kosy, 1986; Fong and Berwick, 1985; Huang, 1984; Boguraev et al. , 1983; Blackwell, 1981; Niimi et al. , 1986). 
X.Huang (1984) : Dealing with Conjunctions in a Machine Translation Environment. 
