Zernik, Uri and Michael G. Dyer, "Learning Phrases in Context," in Proceedings The 3rd Machine Learning Workshop, NewBrunswick NJ (June 1985) . 
Zernik, Uri and Michael G. Dyer, "Towards a Self-Extending Phrasal Lexicon," in Proceedings 23rd Annual Meeting of the Association for Computational Linguistics, Chicago IL (July 1985). 
Zernik, Lift and Michael G. Dyer, "Learning Phrases in Context," in Proceedings The 3rd Machine Learning Workshop, New-Brunswick NJ (June 1985). 
Zernik, Uri and Michael G. Dyer, "Towards a Self-Extending Phrasal Lexicon," in Proceedings 23rd Annual Meeting of the Aso sociation for Coml)utational Linguistics, Chicago IL (July 1985). 
Zemik, Uri and Michael G. Dyer, "FailureDriven Aquisition of Figurative Phrases by Second Language Speakers," in Proceedings of the 7th Annual Conference of the Cognitive Science Society, Irvine CA (August 1985). 
