A94-1007:1	13:167	Computationally, it is possible to describe the grammar and heuristic rules for these constraints by ATN networks, logic grarnmars~ HPSG~ and categorical grammars(Kosy, 1986; Fong and Berwick, 1985; Huang, 1984; Boguraev et al. , 1983; Blackwell, 1981; Niimi et al. , 1986).
---------------------------------------------------
J94-4001:2	29:465	Nevertheless, most work in this area (e.g. , Dahl and McCord 1983; Fong and Berwick 1985; Hirschman 1986; Kaplan and Maxwell 1988; Sag et al. 1985; Sedogbo 1985; Steedman 1990; Woods 1973) has concerned the problem of creating candidate conjunctive structures or explaining correct conjunctive structures, and not the method for selecting correct structures among many candidates.
---------------------------------------------------
