Various efforts at using TAG for generation (McDonald and Pustejovsky, 1985; Joshi, 1987; Yang et al. , 1991; Nicolov et al. , 1995; Wahlster et al. , 1991) enjoy many of these advantages. 
Previous authors (McDonald and Pustejovsky, 1985; Joshi, 1987) have noted that TAG has many advantages for generation as a syntactic formalism, because of its localization of argument structure. 
McDonald, David & Pustejovsky, James (1985) "TAGs as a Grammatical Formalism for Generation", proc. 
Previous authors (McDonald and Pustejovsky, 1985; Joshi, 1987) have noted that TAG has many advantages for generation as a syntactic formalism, because of its localization of argument structure. 
The same observation runs as an undercurrent in the work of McDonald and Pustejovsky (1985), who apply TAGs to the task of generation. 
