As is shown by psychological experiments (an detailed overview is given by Guindon 1985), a very limited number of discourse referents are focussed. 
A cognitive model of anaphora resolution and focusing is provided in Guindon (1985) and Kintsch and van Dijk (1978). 
The allocation of short-term memory during discourse comprehension corresponds to the concept of attentional state (Grosz and Sidner, 1985) and is described in more detail in Guindon (1985). 
The a priori restriction on the set of potential antecedents for anaphora resolution has been called focusing (Grosz, 1977; Guindon, 1985; Reichman, 1981; Sidner, 1983). 
The last structure, the attentional structure, is not discussed here but has been discussed in Guindon (1985). 
