An interesting perspective on the field is given in Miller (1985).


Miller 1985; Beckwith et al. 1989; Miller and Fellbaum 1991.


Following Miller and JohnsonLaird (1976), \[Miller 1985\], and most psychologists, we assume the prelinguistic child is already able to discern spatial orientations, causation, and temporal dependencies.


This has been argued recently by Jackendoff (1983, 1985) and was an assumption in the pioneering work of Miller and Johnson-Laird (1976).


This difference in attitudes regarding the knowledge acquisition bottleneck is reflected in a lnng-standing difference between two alternative methods of lexicon building: the demo approach and the book approach (Miller 1985; a similar distinction appears in Amsler 1982).


