It is interesting to compare this technique to the restriction proposal in Shieber (1985). 
246 2 The Algorithm Our approximation method applies to any context-free grammar (CFG), or any unificationbased grammar (Shieber, 1985a) that can be fully expanded into a context-free grammar. 
This resembles Shieber's method of restriction (Shieber 1985b).Or following Sato et.al. 
1994) or PATR-II (Shieber, 1985) into context-free grammars (CFG). 
This amounts to the simplest case of the restriction technique of Shieber (1985). 
