Individual tools and their use in that project have been described elsewhere (Chodorow, et a1.(1985), Byrd and Chodorow(1985), Byrd, et al.(1986b), Chodorow and Ravin(1987), Neff and Byrd(1987)).


Thus IBM's WordSmith system (Byrd and Chodorow, 1985) is concerned primarily with providing a browsing functionality which supports retrieval of words ~close ~ to a given word along the dimensions of spelling, meaning and sound, while a group at Bell Labs has several large dictionaries on-line used only for research on stress assignment (Church, 1985).


(eds.), Automating the lezicon: theory and practice in a multilingual environment, Cambridge University Press, Cambridge Byrd, R.J. and Chodorow, M.S.(1985) 'Using an online dictionary to tlnd rhyming words and pronunciations for unknown words', Proceedings of the eSth Annual Meeting of the ACL, Chicago, Illinois, pp.277-284 Byrd, R.3.


See also the work of Byrd and Chodorow (1985), which considers computer-based pronunciation by analogy but does not mention the possible application to text-to-speech synthesis.


