Alternative approaches have either avoided defining axioms for mutual belief, e.g. Taylor and Whitehill (1981) or defined it as a primitive operator without reference to simple beliefs, e.g. Cohen and Levesque (1985).


Allen's (1983) work in recognizing intentions from natural language utterances makes the assumption that "people are rational agents who are' capable of forming and executing plans to achieve their goals" (see also Cohen and Levesque 1985).


Following Hovy (1988a), we use the terminology for expressing beliefs developed by Cohen and Levesque (1985) in their theory of rational interaction, but have found the need to extend the terminology to represent the types of intentional goals necessary for the kinds of responses desired in an advisory setting.


19 Following Cohen and Levesque (1985), we limit the surface language to the acts surface-request, surface-inform, surface-informref, and surface-informif.


Perrault (1987, forthcoming) and Cohen & Levesque (1985) have also recently explored a belief and speech act logic based on a single explicit default axiom.


