How the context model can be used to interpret elliptical utterances is discussed in Carberry (1985). 
Our work on understanding ellipsis is presented in Carberry (1985). 
Carberry (1983, 1984, 1985a, 1985b) has extended that into a plan-tracking model for use in interpreting pragmatic ill-formedness and intersentential ellipsis. 
This section describes our approach to the first of these; our framework for handling ellipsis is described in Carberry (1985). 
The real estate, pets, and financial planning (Harry Gross Transcripts 1982) dialogues were transcribed from radio talk shows, the taxes and travel (SRI Transcripts 1992) dialogues were transcribed from tapes of simulated interactions, and the university courses dialogues (Columbia University Transcripts, 1985) were Carberry and Lambert Modeling Negotiation Subdialogues transcribed from student advisement sessions. 
