In (Proudian and Pollard, 1985) a head-driven algorithm based on active chart parsing is described. 
Proudian & Pollard 1985). 
Second, there is an interpretation in terms of headdriven parsing (Proudian and Pollard 1985). 
6Basic ideas of the approach are influenced by the head-driven parser of Proudian and Pollard (1985). 
In this way, the parser is head-driven (Proudian and Pollard 1985); the head determines the course of f~irther parsing. 
