This paper is meant to be viewed as furthering the exploration of the utility of higher-order logic programming for computational linguistics see, for example, (Miller & Nadathur, 1986), (Pareschi, 1989), and (Pereira, 1990).


Determining whether an equivalence applies to a QLF or an RLF is done by higher-order unification (henceforth, HOU) (Huet 1975; Miller and Nadathur 1986; Pulman 1991; Dalrymple, Shieber, and Pereira 1991; Gawron 1992) of the logical form with the relevant pattern.


