Thus, TEAM (Grosz et al. 1985), TEL1 (Ballard and Stumberger, 1986), IRACQ (Ayuso et al. 1987) and some others are devoted to facilitating customizations in the framework of database query systems; INKA (Phillips et al. 1986) and CYC (Lenat et al. 1986) are examples of knowledge acquisition systems aimed at expert system design.


Such acquisition tools include the acquisition component of TEAM (Grosz, 1983), the LapltUp lexical acquisition package for the JANUS system (Cumming and Albano, 1986), and the TELI system's semantic acquisiton facility (Ballard and Stumberger, 1986).


Due to the space limitations endemic to conference papers, we refer the reader to Ballard and Stumberger (1986) for some substantive comparisons, largely related to semantic issues, between TELl and each of TEAM, IRUS, TQA, and ASK.


