Thk means that RGPSG parses can always be verified efficiently, while GPSG parsee cannot, in gener~h 248 Barton (1986) proposes a constraint-based computational solution to intractability in the two-level Kinuno morphological analyzer.


As (Barton 1986b) points out, FSTS used as aeceptors are finite-state machines (FSM) with an alphabet of pairs of characters.


(Barton 1986b), (Barton 1986a)).


