Pollack (1986) has recently proposed that plans be viewed as mental phenomena. 
A common, generally applicable'approach is to use plan-inference as a basis for reasoning:about intentions of the user as proposed by, for instance, Allen & Perrault (1980), Litman (1986), Carberry (1989) and Pollack (1986). 
28 Pollack (1986a) calls this the "is-a-way-to" relation. 
The library of generic recipes (Pollack 1986) contains templates for performing actions. 
We reserve tlhe term mental phenomenon approach for those approaches, such as SharedPlans 536 Lochbaum A Collaborative Planning Model and Pollack's individual plans (Pollack 1986b, 1990; Grosz and Kraus 1996), that take mental states to be primary. 
