Dyer and Zernik 1986).


A recent work on idioms with a similar perspective is Dyer and Zernik (1986).


Instances of the tools introduced above are the LFG environment, which was probably the first of its kind, an environment built by Ron Kaplan for iexical-functional grammars, D-PATR, built by Lauri Karttunen (Karttunen 1986) and conceived as an environment that would suit linguists of a number of different schools all committed to a view of parsing as a process that makes use of a unification algorithm.


A recent work on idioms with a similar perspective and with particular attention to the problem of learning idioms is Dyer and Zernik (1986).


