In Ristad (1986a), the finite closure problem is used to determine the cost of metarule application. 
Ristad (1986b) shows how this causes NP-hardnees, when coupled with lexical ambiguity or null transitions. 
Ristad (1986a) observes that finite feature closure admits a surprisingly large number of possible categories: 9(36"bT) where a is the number of atomic-valued features and b the number of category-valued features. 
Third, unrestricted null transitions in ID rules are a source of intractability because they allow GPSGs to generate enormous phrase structure trees whose yield is the empty string (see Ristad, 1986a). 
3 The total GKPS category set is finite, but naturally, it is extremely large (Ristad (1986) calculates that it is in excess of 10774). 
