Part One of the Algorithms Computing Temporal Structure The input used to compute the temporal structure of a situation consists of the grammatical aspect of the verb, that is, whether it is progressive, and the decomposition produced by PUNDIT's semantic interpreter (Palmer et al. , 1986).


Whereas, in (4) the protagonist making the mistake is only existentially bound within the discourse (instance of indefinite null 3Palmer et al.s (1986) treatment of uninstantiated essential roles is very similar (see also Palmer (1990)).


The system being developed in LISP by NYU is called PROTEUS (PROtotype TExt Understanding System) (Grishman et al. , submitted for publication); the SDC system is called PUNDIT (Prolog UNDerstander of Integrated Text) (Palmer et al. 1986).


Processing Complex Sentences: A Reason for Extending Focusing Algorithms Although complex sentences are prevalent in written English, most other local focusing research (focusing: Sidner \[1979\] and Carter \[1987\]; centering: Grosz, Joshi, and Weinstein \[1983, 1995\], Brennan, Friedman, and Pollard \[1987\], Walker \[1989, 1993\], Kameyama \[1986\] 2, Walker, Iida, and Cote \[1994\], Brennan \[1998\], Kameyama, Passonneau, and Poesio \[1993\], Linson \[1993\] and Hoffman \[1998\]; and PUNDIT: Dahl \[1986\], Palmer et al. \[1986\], and Dahl and Ball \[1990\]) did not explicitly and/or adequately address how to process complex sentences.


