1.1 PREVIOUS WORK ON USER MODELING IN QUESTION ANSWERING PROGRAMS In studying the factors involved in tailoring the content of an answer to a user, research to date has focused mainly on the problems of inferring and using user goals, plans, and beliefs (Appelt 1982, 1985; Carberry 1983, and this issue; McKeown et al. 1985), recognizing and dealing with misconceptions (Kaplan 1982; McCoy 1983; McCoy 1986, and this issue; Quilici et al. , this issue), and superposing various stereotypes (Rich 1979).


Related work from generation includes the correction of misconceptions in the work of McCoy (1986) and the explicit representation of information about a system's own knowledge and planning activities that is found in the Explainable Expert Systems system of Swartout and Smoliar (1987).


Kaplan (1982) and McCoy (1986) investigated misconceptions about domain knowledge and proposed responses intended to remove the misconceptions.


 Department of Electrical Engineering and Computer Science, Milwaukee, WI 53201, mcroy@cs.uwm.edu t Department of Computer Science, Toronto, Canada M5S 1A4, gh@cs.toronto.edu @ 1995 Association for Computational Linguistics Computational Linguistics Volume 21, Number 4 McCoy (1989), Calistri-Yeh (1991), Pollack (1986b), Pollack (1990), and others have studied the problem of how one participant can determine the misconceptions of another during a conversation (see Section 5.3 below).


Several correction strategies have been suggested:  Generalize a description by selectively ignoring some constraints (see Goodman 1985; McCoy 1985, 1986, 1988; Carberry 1988; Calistri-Yeh 1991; Eller and Carberry 1992),  Make a description more specific by adding extra constraints (see Eller and Carberry 1992), and  Choose a conceptual "sibling", by combining generalization and constraint operations.


