Thus, grammars such as wrapping grammars (Bach (1979)), TAGs (e.g. , Joshi (1987)), head grammars, LFG (e.g. , Sells (1985)) and queue grammars (Manaster-Ramer (1986)), all of which can generate such a language, all fail to have systematic semantics for it.


A. Manaster-Ramer (1986).


Examples include the respectively construct in English (Bar-Hillel and Shamir 1964), noun-stem reduplication and incorporation in Mohawk (Postal 1964), noun reduplication in Bambara (Culy 1985), cross-serial dependency of verbs and objects :in certain subordinate clause constructions in Dutch (Huybregts 1976; Bresnan et al. 1982) and in Swiss-German (Shieber 1985), and various reduplication constructs in English, including the X or no X construction as in: "reduplication or no reduplication, I want a parse tree" (Manaster-Ramer 1983, 1986).


