Sidner (1983, 1985) and Litman (1986) developed enhanced models of plan inference.


Work by Litman (1986) attempts to overcome some of the limitations of Allen and Perrault's approach by extending the plan hierarchy to include discourselevel metaplans, in addition to domain-level plans.


Plan-based approaches (Allen and Perrault 1979; Litman 1986; Carberry 1990; Lambert and Carberry 1991) start by applying context-independent inference rules to identify the agent's task-related plan, possibly favoring alternatives that extend a previously recognized plan.


