There are two versions of the centering theory that have been applied to Japanese zero pronoun resolution: Kameyama's(Kameyama, 1986) and Walker's(Walker et al. , 1994). 
Several algorithms have been proposed with regard to this problem (Kameyama, 1986; Walker et al. , 1990; oshimoto, 1988; Dousa~a, 1994). 
Recently a number of researchers have indicated that temporal expressions such as tense morphemes and temporal adverbials can be regarded as referring expressions and have proposed models for temporal reference resolution (Hinrichs 1986; Hwang and Schubert 1992; Kameyama, Passonnean and Poesio 1993; Lascarides 1.992; Partee 1984; Song and Cohen 1991; Webber 1988). 
7 Note also that these results were achieved without having recourse to extra constraints, e.g., the shared property constraint to account for anaphora parallelism (Kameyama, 1986). 
(1983), Kameyama (1986), Brennan et al. 
