Structural Completeness In the next section we present a grammatical calculus, which is more flexible than the systems considered by Wittenburg (1987) and Pareschi & Steedman (1987), and therefore is attractive for linguistic purposes. 
4 The CCG parsing algorithms that have been proposed so far follow this strategy (Pareschi and Steedman 1987; Tomita 1988). 
Pareschi & Steedman (1987) propose an efficient chart-parsing algorithm for categorial grammars with spurious ambiguity. 
There are many problems with the completeness and soundness Pareschi and Steedman's proposal (Hepple 1987; Niv 1993a). 
Whereas Wittenburg (1987) tries to do away with ambiguous phrase structure as much as possible (it only arises where you need it) and Pareschi & Steedman (1987) use a chart parsing technique to recover implicit constituents efficiently, the strategy in this paper has been to go for complete ambiguity. 
