P94-1048:1	27:88	It plays an important role in machine translation (Pustejovsky and 325 L1 Verbal System f -~ V I Association Network L2 Verbal System f V 2 Association Nelwork VI I Connections V 2 I Connections Imagery System Figure 1: Bilingual Dual-Coding Representation Nirenburg, 1987).
---------------------------------------------------
C88-2110:2	148:191	See/Pustejovsky 1987/for discussion.
---------------------------------------------------
C88-2110:3	94:191	Assuming a first-order, partial-decomposition model of lexical semantics, as given in /Pustejovsky 1987/, the translations for this class would be as follows: 6 It should be pointed out here that these are not case~ of metonymy.
---------------------------------------------------
C88-2110:4	75:191	b. His cigarette is bothering me. 3 See /Pustejovsky 1984/, /Safir 1987/, and /WilliamB 1985/ for further discu6slon.
---------------------------------------------------
C88-2110:5	155:191	Appropriate word choice is, of course, a function of numerous factors and considerations (/Ward 1988/, /Pustejovsky and Nirenburg 1987/,/Danlos 1987/), but, in any case, the selection process makes sense only if the incoming semantic representation provides for there to be a distinction that is later reflected as a lexical distinction.
---------------------------------------------------
C88-2110:6	184:191	We explore such a technique in /Pustejovsky and Anick 1988/and compare our approach to/Hirst 1987/and other lexical disambiguation systems.
---------------------------------------------------
C88-2110:7	123:191	Within the calculus of aspect outlined in/Pustejovsky 1987/, play(z) and read(x,y) fall into different event-types, activity and ac.complishment, respectively, and license different temporal predicates.
---------------------------------------------------
W90-0104:8	26:145	Discrimination nets (e.g. , Goldman 1975; Pustejovsky and Nirenburg 1987) are basically decision trees.
---------------------------------------------------
C88-2149:9	235:323	Commnnly distinguished are open-class words and closed-class words /Pustejovsky and Nirenburg 1987/or content words and function words /Kempen and Hoenkamp 1987/, phrase-heads and modifiers/Goldman 1974/, and words with valence and words without.
---------------------------------------------------
C88-2149:10	23:323	However, most research so far has focused on syntactic choice; word choice has received little attention/Pustejovsky and Nirenburg 1987/.
---------------------------------------------------
