The first is Wittenburg (1987). 
Our approach is an extension of the predictive combinator compilation method discussed in Wittenburg (1987). 
Although similar work has been attempted in the past, with varying degrees of success (Karttunen, 1986; Wittenburg, 1986; Pareschi & Steedman, 1987; Bouma, 1989; Hepple & Morrill, 1989; KSnig, 1989; Vijay-Shanker & Weir, 1990; Hepple, 1990; Moortgat, 1990; ttendriks, 1993; Niv, 1994), this appears to be the first full normal-form result for a categorial formalism having more than contextfree power. 
Structural Completeness In the next section we present a grammatical calculus, which is more flexible than the systems considered by Wittenburg (1987) and Pareschi & Steedman (1987), and therefore is attractive for linguistic purposes. 
We actually use predictive versions of combinators in our runtime system (Wittenburg 1987). 
