Others tried to infer and utilize users goals to generate responses adapted to the user (van Beek, 1987; Paris, 1988).


Others tried to infer and utilize users goals to generate responses adapted to the user (van Beek, 1987; Paris, 1988).


Finally, the research reported in (Joshi et al. , 1984; van Beek, 1987; Zukerman and McConachy, 2001) considers the addition of information to planned discourse to prevent a users erroneous inferences from this discourse.


