The work in lexicon has centered on a) studies concerned with the utilization of conventional humanoriented dictionaries, newly available in machine-readable form, for computational tasks (e.g. , Amsler 1984a,b; Chodorow et al. 1985; Ahlswede 1985; Markowitz et al. 1986) improving the ancillary capabilities for lexicon systems, such as, for instance, morphological processors and descriptions (e.g. , Nirenburg and Ben Asher 1984; Byrd et al. 1986; Boguraev et al. 1987); c) hand-building of lexicons necessary for natural language systems, often with considerations about extensibility (e.g. , Zernik and Dyer 1985; Bessemer and Jacobs 1987).


5.1 Jacobs and Martin In a series of papers (Besemer and Jacobs, 1987; Jacobs, 1986; Jacobs, 1987), Paul Jacobs has developed a relationship he calls a view.


