Most prior work on event nominals does not try to classify them as events or non-events, but instead focuses on labeling the argument roles based on extrapolating information about the argument structure of the verbal root (Dahl et al. , 1987; Lapata, 2002; Pradhan et al. , 2004).


6 Related Work Other computational linguistics work on decoding nominalizations includes (Hobbs and Grishman, 1976), (DaM et al. , 1987) and (Hull and Gomez, 1996).


(1987) and Macleod et al.


Then, classification rules were crafted by hand, or detected from relation-tagged examples by a machine learning technique (Shimazu et al. , 1987; Sumita et al. , 1990; Tomiura et al. , 1995; Kurohashi et al. , 1998).


(Dahl et al. , 1987; Hull and Gomez, 1996) use hand-coded slot-filling rules to determine the semantic roles of the arguments of a nominalization.


