Poesio et al. supplemented the identity relation with three different possible semantic relations between Cfs in the utterances: set membership, subset, and generalized possession. Murata, Ishara, and Nagao induced a number of possible relations between bridging reference and anchor using a verb case frame dictionary and a corpus of Japanese AnoBexpressions (where A and B are nominal arguments and the AnoBconstruction encodes a wide variety of semantic relations between the two nominal arguments [Shimazu, Naito, and Nomura 1987]).


In contrast with the preceding research analyzing "NI no N2" (Shimazu et al. 1987; Hirai and Kitahashi 1986), deep semantic analysis is avoided because it is assumed that translations appropriate for given domain can be obtained using domain-specific examples (pairs of source md target expressions).


Then, classification rules were crafted by hand, or detected from relation-tagged examples by a machine learning technique (Shimazu et al. , 1987; Sumita et al. , 1990; Tomiura et al. , 1995; Kurohashi et al. , 1998).


