The analysis is based on a higher-order intensional logic described in detail in Hinrichs (1987a).


Enc (1981) and Hinrichs (1987) both argue convincingly that there are many instances in which a temporally dependent element is interpreted with respect to a time that is neither the during time nor now.


Hinrichs (1987) also proposes that noun phrases be interpreted relative to a time restricted by the context; the difference between his analysis and ours is that, of the three options presented above, he offers only the last.


