J87-3007:1	9:287	Thus, TEAM (Grosz et al. 1985), TEL1 (Ballard and Stumberger, 1986), IRACQ (Ayuso et al. 1987) and some others are devoted to facilitating customizations in the framework of database query systems; INKA (Phillips et al. 1986) and CYC (Lenat et al. 1986) are examples of knowledge acquisition systems aimed at expert system design.
---------------------------------------------------
J87-3007:2	53:287	The recognized necessity to describe the concept lexicon prior to dealing with natural languages is a feature which clearly distinguishes our approach from Computational Linguistics, Volume 13, Numbers 3-4, July-December 1987 277 Sergei Nirenburg and Victor Raskin The Subworld Concept Lexicon and the Lexicon Management System other work on lexical aids (e.g. , Ahlswede 1985) and brings us closer to some non-NL work on knowledge acquisition (e.g. , Lenat et al. 1986).
---------------------------------------------------
J87-3007:3	5:287	The work in lexicon has centered on a) studies concerned with the utilization of conventional humanoriented dictionaries, newly available in machine-readable form, for computational tasks (e.g. , Amsler 1984a,b; Chodorow et al. 1985; Ahlswede 1985; Markowitz et al. 1986) improving the ancillary capabilities for lexicon systems, such as, for instance, morphological processors and descriptions (e.g. , Nirenburg and Ben Asher 1984; Byrd et al. 1986; Boguraev et al. 1987); c) hand-building of lexicons necessary for natural language systems, often with considerations about extensibility (e.g. , Zernik and Dyer 1985; Bessemer and Jacobs 1987).
---------------------------------------------------
J87-3007:4	10:287	We would like to address some important methodological and strategic points in providing the lexicon support in the context of a text processing system, such as the machine translation system TRANSLATOR (Nirenburg et al. 1987).
---------------------------------------------------
J87-3007:5	49:287	In the area of machine translation the analysis and generation lexicons involve two different natural languages, which creates the task of building such resources as, say, an Englishsubworld and subworld -Russian lexicons, as is the case, for example, in TRANSLATOR, the knowledge-based machine translation project for the computer subworld (see Nirenburg et al. 1985, 1986, 1987).
---------------------------------------------------
A97-1052:6	95:163	3 Experimental Evaluation 3.1 Lexicon Evaluation Method In order to test the accuracy of our system (as developed so far) and to provide empirical feedback for further development, we took the Susanne, SEC (Taylor & Knowles, 1988) and LOB corpora (Garside et al. , 1987)--a total of 1.2 million words--and extracted all sentences containing an occurrence of one of fourteen verbs, up to a maximum of 1000 citations of each.
---------------------------------------------------
P88-1026:7	14:180	Word Tagging The system devised for automatic word tagging or part of speech selection for processing nmn/ng Enfli~ text, known as the Constituent-Likelihood Automatic Word-tagging System (CLAWS) (Garside et aL, 1987) serves as the basis for the current work.
---------------------------------------------------
P88-1026:8	44:180	But these are assessed critically rather thaa adop~ wholesale (see for instanoe Akkenmm et al. , 1985 and Boguraev et al. , 1987, for a discussion of the strengths and wea~____~_ of the LDOCE grammar codes).
---------------------------------------------------
P05-1076:9	37:162	Some fairly extensive frame sets can be found in large syntax dictionaries, such as COMLEX (31 SCFs) (Wolff et al. , 1998) and ANLT (24 SCFs) (Boguraev et al. , 1987).
---------------------------------------------------
P03-1009:10	41:183	We expect the use of this system to be beneficial: it employs a robust statistical parser (Briscoe and Carroll, 2002) which yields complete though shallow parses, and a comprehensive SCF classifier, which incorporates 163 SCF distinctions, a superset of those found in the ANLT (Boguraev et al. , 1987) and COMLEX (Grishman et al. , 1994) dictionaries.
---------------------------------------------------
J05-3003:11	104:532	Briscoe and Carroll (1997) predefine 163 verbal subcategorization frames, obtained by manually merging the classes exemplified in the COMLEX (MacLeod, Grishman, and Meyers 1994) and ANLT (Boguraev et al. 1987) dictionaries and adding around 30 frames found by manual inspection.
---------------------------------------------------
W04-2606:12	63:243	This fairly comprehensive classi cation incorporates 163 different subcategorization frames (SCFs), a superset of those listed in the ANLT (Boguraev et al. , 1987) and COMLEX Syntax dictionaries (Grishman et al. , 1994).
---------------------------------------------------
W00-1327:13	107:157	This was obtained by analysing up to a maximum of 300 occurrences for each test verb in BN or LOB (Garside et al. , 1987), Susanne and SEC (Taylor and Knowles, 1988) corpora.
---------------------------------------------------
W00-1327:14	47:157	The estimate for the correct distribution of SCFs over all English verbs was obtained by extracting the number of verbs which are members of each SCF class in the ANLT dictionary (Boguraev et al. , 1987).
---------------------------------------------------
P07-1115:15	55:160	2.2 SCF Classifier SCF Frames The SCFs recognized by the classifier were obtained by manually merging the frames exemplified in the COMLEX Syntax (Grishman et al. , 1994), ANLT (Boguraev et al. , 1987) and/or NOMLEX (Macleod et al. , 1997) dictionaries and including additional frames found by manual inspection of unclassifiable examples during development of the classifier.
---------------------------------------------------
W00-1325:16	97:178	This was obtained by analysing up to a maximum of 300 occurrences for each of the 14 test verbs in LOB (Garside et al. , 1987), Susanne and SEC (Taylor and Knowles, 1988) corpora.
---------------------------------------------------
