-6s A NP0$ VP V NPI~, PP2/VA I A takes P2 NP2NA I I into N2/VA I account Figure 10: Tree for NPo takes NP1 into account NPo VP No V NPI I A A Jean Aux V Dt N1 I I I I a casse sa pipe literal S NP o VP No V NPINA I A A Jean Aux V D t NINA I I I 1 a casse sa pipe idiom Figure 11: Jean a cassg sa pipe 5 Recognizing Discontinuous Idioms Parsing flexible idioms has received only partial solutions so far (Stock 1987, Laporte 1988).


