/Abney 1986/, /Berwick 1987/, /Correa 1987/, /Kashket 1987/,/Kuhns 1986/,/Sharp.1985/,/Stabler 1987/,/Thiersch 1988/, and/%'ehrli I984/.


Attribute grammar has been used in the past by the author to define computational models of Chomsky's Government-binding theory, from which practical parsing programs were developed (Correa, 1987a).


In this paper research is continued on the use of attribute grammars to provide a fully explicit and computationally oriented statement of the Governmc.nt-binding (GB) theory /Correa, 1987/.


