There is a vast literature of these subjects including works by \[Vendler 1967, Mourelatos 1978, Dowty 1986, Hinrichs 1986, Moens et al. 1987, Passonneau 1987\] to mention some.


Most accounts of the anaphoric nature of tense have invoked Reichenbach's (1947) trinity of underlying times, and his concept of the "positional" use of the reference time which he 2 A similar ~ent structure is proposed by Passonneau (1987).


