Hovy's text structurer (Hovy 1988b), for example, uses rhetorical relations as defined in Rhetorical Structure Theory (RST) (Mann and Thompson 1987) to order a set of propositions to be expressed. 
While it is recognized that this division is problematic (Hovy, et al. 1988), nearly all generation systems today make this division. 
Hovy has described another text planner that builds similar plans (Hovy 1988b). 
Itecently, Hovy (1988b) built a text structurer which produces a coherent text when given a set of inputs to express. 
33 Something like this approach is in fact used in some systems (e.g. , Elhadad and Robin 1992; PenMan 1989; Hovy 1988a). 
