Earlier versions of several of the results herein have already been published in Banks (1986), Rayner and Banks (1986), Banks and Rayner (1987), and Rayner and Banks (1988a; 1988b). 
A relatively simp\]\[e example is 12a), which we quoted in Rayner and Banks (1988); the sentence is also discussed at length by Friedmann. 
Two exceptions are the recent papers of Ballard (1988) and Rayner and Banks (1988). 
1.2.2 SPECIFIC SYNTACTIC AND SEMANTIC ASSUMPTIONS The basic scheme, or some not too distant relative, is the one used in many large-scale implemented systems; as examples, we can quote TEAM (Grosz et al. 1987), PUNDIT (Dahl et al. 1987), TACITUS (Hobbs et al. 1988), MODL (McCord 1987), CLE (Alshawi et al. 1989), and SNACK-85 (Rayner and Banks 1986). 
Rayner and Banks (1988) describe a logic programming approach to obtaining a parse and an initial logical formula for sentences containing a fairly broad range of CEs. 
