Wiebe & Rapaport (1988) and Wiebe (in progress) present an outline of a detailed computational investigation of narrative perspecfive and reference. 
There s This observation is predicted by Nakhimovsky's work on the discourse structure of narrative text, in which it is suggested that paragraph breaks accompany discontinuities (Nakhimovsky & Rapaport 1988; Naldaimovsky 1988). 
Banfield 1982, Wiebe & Rapaport 1988). 
Nakhimovsky and Rapaport (1988) suggest that in narrative, paragraph breaks accompany changes in POV, but they did not investigate this hypothesis experimentally. 
For example, certain values of focalization and point of view can cause unusual referring expressions: personal pronouns might be used for initial reference [Harweg, 1968: 163 166], or indefinite referring expressions for subsequent reference [Ushie, 1986; Wiebe and Rapaport, 1988]. 
