where the pro N-BAR, left completely unspecified during semantic interpretation, is free to generate all sorts of combinations with the possessive, including those in which the possession is appropriate to various "relational" interpretations of the pro N-BAR (de Bruin and Scha (1988)).


(1980)) and has been used in ~'eating several difficult semantic phenomena (de Bruin and Scha (1988); Scha and Stallard (1988)).


