Two main approaches have generally been considered: rule-based (Klein and Simmons 1963; Brodda 1982; Paulussen and Martin 1992; Brill et al. 1990) probabilistic (Bahl and Mercer 1976; Debili 1977; Stolz, Tannenbaum, and Carstensen 1965; Marshall 1983; Leech, Garside, and Atwell 1983; Derouault and Merialdo 1986; DeRose 1988; Church 1989; Beale 1988; Marcken 1990; Merialdo 1991; Cutting et al. 1992).


7.1 Text Data We use the "treebank" data described in Beale (1988).


These include the availability of efficient and high precision word segmentation methods for Chinese text \[Chang et al. , 1991; Sproat and Shih, 1990; Wang et al. , 1990\], the availability of statistical analysis of a Chinese corpus \[Liu et al. , 1975\] and large-scale electronic Chinese dictionaries with partof-speech information \[Chang et al. , 1988; BDC, 1992\], the corpus-based statistical part-of-speech tagger \[Church, 1988; DeRose, 1988; Beale, 1988\], as well as phrasal and clausal analyzers \[Church 1988; Ejerhed 1990\] 2.


