Maeda, H. et al. , 1988, "Parsing Japanese honorifics in unificationbased grammar".


For example, the lexical description of a subject-honorific auxiliary reru is as follows (the feature specification depends on that for honorifics by Maeda et al. 1988) (DEFI_EX re VSTEM () \[\[HEAD \[\[POS V\] \[crYPE VOW(vowel-st,)m-type, i .e. itidan)\] \[CFORM STEM\] \[MODL(modat) \[\[DEAC(doactlve) SHON(sbj--honorific)\]\]\]\]\] \[SUBCAF {\[\[IIEAD \[\[POS P\]\[FORM Ra\]\[GRF SUBJ\]\]\] \[SUBCAT {}\] \[SEM ?x\]\] \[\[HEAD \[\[POS VII \[CTYPE (:OR CONS-UV CON~-V SURU)\] \[CFORM VONG(vuice-negtive, i.e. tnizen,~I~ei)\] \[MODL IDEAC~\]\]\] \[SUBCAT {\[\[HEAD \[\[POS P\]\[FDRM ga\]\[GRF SUDJ\]\]\] \[SUBCAT {}\] \[SEM ?x\]\]}\] \[SEM ?SE~\]\]}\] \[SEM ?SEM\] \[PIRAG (p ragmatics) \[\[SPEAKER ?SPEAKER\] \[HEARER ?HEARER\] \[RESIRS(restrictions) {\[\[RELN RESPECI'\] \[AGEN ?SPEAKER\] \[OBJE ?X\]\]}\]\]\]\] (?X =d ?SPEAKER)) N.B. Tile feature structure of the verbal stem of the auxiliary is given above.


This was partly done by Maeda et al. 1988 by means of Discourse Representation Theory.


This topic description along with other parts of the 779' fundamental grammar of Japanese was implemented on a unificaion-based parser built up by my colleagues Kiyoshi Kogure and Susumu Kat6 (Maeda et al. 1988).


