Kameyama (1988) describes a prototype shared grammar for the syntax of simple nominal expressions for five languages, but the focus of the effort is only on the noun phrase, which makes the approach not applicable to a large-scale effort.


Kameyama (1988) uses PATR-style templates to build a multiple inheritance multilingual lexicon to support Categorial Unification Grammar descriptions of Arabic, English, French, German, and Japanese nominals.


