These include devices such as interleaving the components (McDonald 1983; Appelt 1983), backtracking on failure (Appelt 1985; Nogier 1989), allowing the linguistic component to interrogate the planner (Mann 1983; Sondheimer and Nebel 1986), and Hovy's notion of restrictive (i.e. , bottom-up) planning (Hovy 1988a, 1988c). 
33 Something like this approach is in fact used in some systems (e.g. , Elhadad and Robin 1992; PenMan 1989; Hovy 1988a). 
The interactions between text planning and linguistic realization in modular systems have been handled in several ways, including backtracking (Appelt, 1985), interleaving the two components (McDonald, 1983) and restrictive planning (Hovy, 1988). 
Hut, as Hovy (1988) points out, "be polite" is not a decomposable goal; the objective of being polite is achieved through local decisions. 
Hovy has described another text planner that builds similar plans (Hovy 1988b). 
