H91-1024:1	7:170	Recently, an elegant approach to inference in discourse interpretation has been developed at a number of sites (e.g. , Charniak and Goldman, 1988; Hobbs et al. , 1990; Norvig, 1987), all based on the notion of abduction, and we have begun to explore its potential application to machine translation.
---------------------------------------------------
C90-3040:2	86:216	Probability Based Commensurability Charniak and Goldman (1988) started out with a model very similar to Hobbs et al. , but became concerned with 227 the lack of theoretical grounding for Ihe number, in rules, much as we we.re.
---------------------------------------------------
C90-3051:3	136:160	Charniak and Goldman (1988) provide an example of how ATMS techniques could be used for comparisons (eft section a.1).
---------------------------------------------------
J91-4003:4	57:625	Hobbs et al. 1988; Charniak and Goldman 1988).
---------------------------------------------------
C90-2035:5	142:167	metaphoric inferences studied by Martin (1988), ok: the abductive inferences of Charniak & Goldman (11988) or Hobbs et al.
---------------------------------------------------
C90-3028:6	9:186	Recently, an elegant approach to inference in discourse interpretation has been developed at a number of sites (e.g. , ltobbs et al. , 1988; Charniak and Goldman, 1988; Norvig, 1987), all based on tim notion of abduction, and we have begun to explore its potential application to machine translation.
---------------------------------------------------
C00-1040:7	202:226	We clearly want to point out that while this rule system covers a wide variety of standard syntactic constructions (such as genttives, prepositional phrases, various tense and modal forms), it currently does not account fbr quantificational issues (like scope ambiguities) for which entirely logic-based approach (Charniak and Goldman, 1988; Moore, 1989; Pereira and Pollack, 1991) provide quite sophisticated solutions.
---------------------------------------------------
J95-4001:8	168:639	Abduction has been applied to the solution of local pragmatics problems (Hobbs et al. 1988, 1993) and to story understanding (Charniak and Goldman 1988).
---------------------------------------------------
P92-1041:9	53:64	This is the reason why more recent works have focussed on ATMS techniques (Charniak, Goldman 1988) and their relations to chart parsing (Wiren 1990).
---------------------------------------------------
A00-2043:10	5:326	1 Introduction Semantic interpretation has been an actively investigated issue on the research agenda of the logic-based paradigm of NLP in the late eighties (e.g. , Charniak and Goldman (1988), Moore (1989), Pereira and Pollack (1991)).
---------------------------------------------------
A00-2043:11	185:326	4 Related Work After a period of active research within the logicbased paradigm (e.g. , Charniak and Goldman (1988), Moore (1989), Pereira and Pollack (1991)), work on semantic interpretation has almost ceased with the emergence of the empiricist movement in NLP (cf.
---------------------------------------------------
