The resulting system is related to the earlier system of conditional interpretation rules developed by Pollack and Pereira (1988), but avoids that system's use of formal conditions on the order of assumption discharge. 
On the other hand, one can make certain portions of syntactic information available for semantic processing (proposals are made in Pollack/Pereira 1988, Latecki/Pinkal 1990). 
We speculate that one may be able to do this in a framework like that described in Pereira and Pollack (1988), which allows conditional interpretation. 
The resulting system is related to the earlier system of conditional interpretation rules developed by Pollack and Pereira (1988), but avoids that system's use of formal conditions on the order of assumption discharge. 
We will not be discussing the process of quantifier scoping here: a scoping mechanism for the CLE has already been described by Moran (1988), and a later version is described by Pereira in Alshawi et al. 
