W99-0104:1	43:264	Such computational methods were presented in (Grosz et al. , 1995) and (Webber, 1988).
---------------------------------------------------
J97-1003:2	153:581	The work described here makes use only of lexical distribution information, in lieu of prosodic cues such as intonational pitch, pause, and duration (Hirschberg and Nakatani 1996), discourse markers such as oh, well, ok, however (Schiffrin 1987; Litman and Passonneau 1995), pronoun reference resolution (Passonneau and Litman 1993; Webber 1988) and tense and aspect (Webber 1987; Hwang and Schubert 1992).
---------------------------------------------------
P96-1038:3	14:138	that discourse structural information can be inferred from orthographic cues in text, such as paragraphing and punctuation; from linguistic cues in text or speech, such as cue PHI~.ASES 1 (Cohen, 1984; Reichman, 1985; Grosz and Sidner, 1986; Passonneau and Litman, 1993; Passonneau and Litman, to appear) and other lexical cues (Hinkelman and Allen, 1989); from variation in referring expressions (Linde, 1979; Levy, 1984; Grosz and Sidner, 1986; Webber, 1988; Song and Cohen, 1991; Passonneau and Litman, 1993), tense, and aspect (Schubert and Hwang, 1990; Song and Cohen, 1991); from knowledge of the domain, especially for taskoriented discourses (Grosz, 1978); and from speaker intentions (Carberry, 1990; Litman and Hirschberg, 1990; Lochbaum, 1994).
---------------------------------------------------
H89-1049:4	94:133	Now, \[Webber 88\] argues that demonstrative reference of this type is sensitive to the right frontier of the discourse tree: that is, 'the set of nodes comprising the most recent closed segment and all currently open segments' (Webber 1988:114).
---------------------------------------------------
P89-1030:5	147:152	We would like to address the problem of event reference and its interaction with temporal information, using ideas such as those in (Webber, 1988) and in the special issue of ComputationaJ Linguistics on tense and aspect (Vol.
---------------------------------------------------
C04-1007:6	100:191	However, previous research has found that demonstrative anaphors rarely refer to NPs, while it rarely refers to discourse segments (Webber (1988a)).
---------------------------------------------------
C04-1007:7	97:191	Webber (1988a)).
---------------------------------------------------
C04-1007:8	84:191	Tense often serves as a cue for discourse structure (Lascarides and Asher, 1993; Webber, 1988b).
---------------------------------------------------
W97-1307:9	149:264	Pronouns: Of the four pronoun resolution errors, one is due to a parse error (American in 7-1 was incorrectly parsed as a person entity, to which she in 8-1 was resolved), that in 6-2 is a discourse deixis (Webber, 1988), beyond the scope of the current approach, and two errors (it in 3-1 and its in 7-1) were due to the left-right ordering of intrasentential candidates.
---------------------------------------------------
J94-4002:10	414:488	556 Shalom Lappin and Herbert J. Leass An Algorithm for Pronominal Anaphora Resolution Brennan, Friedman, and Pollard (1987), and Webber (1988) present different versions of this approach.
---------------------------------------------------
J94-4002:11	153:488	Our use of "coreference" is in the spirit of Sidner's (1981) "co-specification" and Webber's (1988) "referencem".
---------------------------------------------------
