Such an organization of a grammar is the starting point of a class of generation algorithms that have become popular recently (Calder et al. , 1989; Shieber et al. , 1989; Shieber el al. , 1990). 
(1989) and Shieber et al. 
 Definite-clause Grammar (Pereira and Warren, 1980) for Dutch to illustrate semantic-headdriven generation (Shieber et al. , 1989), and to compare different parsers for speed (Bouma and van Noord, 1993). 
Shieber et al. , 1989). 
The parser is a generalization of the left-corner parser (Matsumoto et al. , 1983) and can be used for grammars written in powerful formalisms such as non-concatenative versions of HPSG (Pollard, 1984; Reape, 1989). 
