In previous corpus-based studies of centering (Walker 1989; Passonneau 1993; Byron and Stent 1998; Di Eugenio 1998; Kameyama 1998; Strube and Hahn 1999; Tetreault 2001), only a few instantiations of centering were compared. 
Following Walker (1989), a discourse segment is defined as a paragraph unless its first sentence has a pronoun in subject position or a pronoun whose syntactic features do not match the syntactic features of any of the preceding sentence-internal noun phrases. 
In this case the data suggest that perhaps intrasentential candidates should be preferred (Walker 1989). 
Unlike Walker (1989), we do not account for false positives or error chains; instead, we use a "location'-based evaluation procedure. 
 Centering algorithms: Baldwin (1993); Brennan, Friedman, and Pollard (1987); Kehler (1993); Walker (1989); Walker, Iida, and Cote (1994). 
