This is particularly crucial in spoken NL diMog, where speakers expect fast response times (Oviatt and Cohen, 1989).


However, as (Oviatt and Cohen, 1989) caution, speakers expect fast response times in a system that provides spoken interaction.


In the Wizard-of-Oz (WOZ) approach, a human wizard simulates the behavior of a program interacting with a human to carry out a particular task in a particular domain (Dahlb~ick and Jonsson 1989; Hirschman et al. 1993; Oviatt and Cohen 1989; Whittaker and Stenton 1989).


For example, the wizard may follow a proto4 Walker and Moore Empirical Studies in Discourse col that includes particular system limitations or error-handling strategies, to explore potential problems before implementation, e.g. determining how the program's level of interactivity affects the complexity of the instructions it is given (Oviatt and Cohen 1989).


