This paper is a revised and expanded version of "A Calculus for Semantic Composition and Scoping" presented at the 1989 meeting of the Association for Computational Linguistics (Pereira 1989).


Finally, the fact that we are interested in assumptions sets rather than assumption sequences is encoded by the following three structural rules (Girard et al. 1989): r, A, B, A k C \[exchange\] : F, B, A, A lC Computational Linguistics Volume 16, Number 1, March 1990 3 Fernando C. N. Pereira Categorial Semantics and Scoping A,A, FF B \[contraction\] . A, FFB FbB \[weakening\] : A, F b B The exchange rule allows us to ignore assumption order, so the collection of assumptions forms a bag rather than a set.


