H91-1006:1	89:149	also Carlson & Vilkuna, 1990 and Zajac, 1989); its advantages are the well understood formal aspects and the declarative nature of the rule schema for a given implementation.
---------------------------------------------------
C92-2116:2	243:265	551-553 \[EmelefZajac 89\]: M. Emele, R. Zajac, "RETIF: A Rewriting System lot Typed Feature Structures", ATR Technical Report TR-I-0071 1989 \[Gazdar et al. 851: G. G~dar, E. Klein, G. Pullum and I. Sag: "Generalized Phrase Structure Grammar", Oxford, Blackwell 1985 lHauenschild/Bnsemann 88\]: Ch.
---------------------------------------------------
P91-1025:3	36:232	(1989), typed feature structure rewriting system of Zajac (1989), and abduction-based system of Hobbs and Kameyama (1990).
---------------------------------------------------
J92-2002:4	380:555	Emele, Martin, and Zajac, R6mi (1989).
---------------------------------------------------
J92-2002:5	234:555	We apply a similar technique for specifying transfer rules for machine translation, which we prefer to call "contrastive rules" since there is no directionality involved (Zajac 1989; 1990a).
---------------------------------------------------
J92-2002:6	74:555	The early work presented in Emele and Zajac (1989a) was an attempt to directly implement the ideas presented in Ait-Kaci (1984, 1986); Emele and Zajac (1989b) was already a departure from Ait-Kaci's KBL language, implementing a different evaluation strategy that allowed the use of cyclic feature structures.
---------------------------------------------------
J92-2002:7	377:555	Emele, Martin, and Zajac, R6mi (1989).
---------------------------------------------------
J92-2002:8	514:555	Zajac, R6mi (1989).
---------------------------------------------------
