J92-4004:1	548:619	Another way to explain the domination of s3 over sl could be done by using the notions of maximal government domains discussed by Kroch (1989) and using it now to define the characteristics of the domination links such as that between s3 and s4.
---------------------------------------------------
D07-1128:2	31:76	We have argued in (Schneider, 2005) that LFG f-structures can be parsed for in a completely context-free fashion, except for embedded WH-questions, where a device such as functional uncertainty (Kaplan and Zaenen, 1989) or the equivalent Tree-Adjoining Grammar Adjoining operation (Joshi and Vijay-Shanker, 1989) is used.
---------------------------------------------------
