The conclusions we draw can also be applied to more efficient parsers (Earley 1970; Schabes 1991) that produce other logical representations (e.g. , Alshawi and Crouch 1992; Hirst 1987; Weischedel 1989) in more compact forests (Nederhof 1993).


57 nonlinguistic linguistic reahty knowledge meaning form cognitive'psychological' situational -'socio/psycho-logical' grammatical semantics inquiry semantics clause-based lexicai semantics word senses word-based syntactic realization classes syntax Weischedel (1989) Langacker (1987) Steiner (fc) Halllday & Matthiessen (fc) PENMAN UPPER MODEL Jackendoff (1983), LVG Mel'euk & ~holkovskij (1970) Steiner et al.


, 1990\]; certain of the Domain and Text Structure Objects of SPOKESMAN: \[Meteer, 1989\]; TRANSLATOR: \[Nixenberg et aL, 1987\]; the Semantic Relations of ~UROTa^-D: \[Steiner et al. , 1987\]; JANUS: \[Weischedel, 1989\].


Weischedel (1989) uses the taxonomic language NKL (based on KL-ONE) to express selectional restrictions, while Andry et al.


