7 Related Work This work has parallels to MAIMRA, a system for word learning from non-linguistic input (Siskind, 1990).


Most existing computational natural language acquisition models also assumed various kinds of the extra input (e.g. semantic associations \[Siskind, 1990; Webster & Marcus, 1989; Zernik, 1987\] and syntactic structures \[Berwick, 1985; Liu & Soo, 1992a\] of input sentences) and human intervention (e.g. information interactively given by the trainer \[tang & Ilirschman, 1988; Velardi et al. , 1991\]) during learning.


(1990, 1994) and Siskind (1990, 1992, 1994), which is also the work closest to our own.


In the human language acquisition literature, Grimshaw (1981) and Pinker (1989) advocate this approach; others have described partial computer implementations: Pustejovsky (1988) and Siskind (1990).


Some of these systems generate structures that are similar to templates, for exaanple GENESIS (Mooney, 1985), and others acquire domain specific semantic representations, for example MAIMRA (Siskind, 1990).


