H93-1049:1	140:159	Smadja F.A. and McKeown, K.R., (1990) "Automatically Extracting and Representing Collocations for Language Generation," Proceedings of the 28th Annual Meeting of the ACL, pp.
---------------------------------------------------
J92-1001:2	208:480	Our use of the term is thus similar to that of Smadja and McKeown, who partition collocations into open compounds, predicative relations, and idiomatic expressions (Smadja and McKeown 1990).
---------------------------------------------------
J92-1001:3	233:480	Church and Hanks 1990; Smadja and McKeown 1990).
---------------------------------------------------
J92-1001:4	241:480	These entries differ from similar representations of collocations or idioms in Smadja and McKeown (1990) and Stock (1989), in that they are sense-based rather than wordbased.
---------------------------------------------------
P93-1022:5	11:178	Statistical data about these various cooccurrence relations is employed for a variety of applications, such as speech recognition (Jelinek, 1990), language generation (Smadja and McKeown, 1990), lexicography (Church and Hanks, 1990), machine translation (Brown et al. , ; Sadler, 1989), information retrieval (Maarek and Smadja, 1989) and various disambiguation tasks (Dagan et al. , 1991; Hindle and Rooth, 1991; Grishman et al. , 1986; Dagan and Itai, 1990).
---------------------------------------------------
P91-1027:6	108:189	Three recent papers in this area are Church and Hanks (1990), Hindle (1990), and Smadja and McKeown (1990).
---------------------------------------------------
E91-1039:7	22:118	These observations have led ~everal researchers, including Hindle (1990) and Smadja and McKeown (1990), to begin investigating automatic acquisition of semantics.
---------------------------------------------------
C92-2070:8	160:216	Other research, such as Smadja and McKeown (1990), have shown more general ways of identifying and handling these fixed expressions and collocations.
---------------------------------------------------
C94-2202:9	14:143	Also, the use of collocations in different applications has been discussed by various authors ((McRoy, 1992), (Pnstejovsky et al. , 1992), (Smadja and McKeown, 1990) etc.).
---------------------------------------------------
C94-2202:10	95:143	For other Imatlnents of collocations in language generation see (Nirenburg et al. , 1988) and (Smadja and McKeown, 1990).
---------------------------------------------------
J06-3001:11	110:790	For the three areas Fish, Mushrooms, and Neurology, the secondary corpora were retrieved using the following refined procedure: Starting from a small tagged seed corpus for the given domain, we mechanically extracted terminological open compounds for English (Sornlertlamvanich and Tanaka 1996; Smadja and McKeown 1990) and compound nouns for German.
---------------------------------------------------
W93-0309:12	15:178	The work described in Smadja and McKeown (1990) and Smadja (1991a.b) is along the same lines as ours, though he uses a different statistical calculation, a z-score, and tagged, lemmatized corpora.
---------------------------------------------------
J93-1007:13	44:754	Preliminary results obtained with parts of Xtract have been described in the past (e.g. , Smadja and McKeown 1990); this paper gives a complete description of the system and the results obtained.
---------------------------------------------------
A92-1013:14	30:225	In (Smadj~ and McKeown, 1990) statistically collectec associations provide pragmatic cues for lexical choic( in sentence generation.
---------------------------------------------------
P92-1032:15	18:229	(to appear), Hearst (1991), Lesk (1986), Smadja and McKeown (1990), Walker (1987), Veronis and Ide (1990), Yarowsky (1992), Zemik (1990, 1991).
---------------------------------------------------
C92-2082:16	106:201	Work on acquisition of syntactic information from text corpora includes Brent's (Brent 1991) verb subcategorization frame recognition technique and Smadja's (Smadja & McKeown 1990) collocation acquisition algorithm.
---------------------------------------------------
C04-1141:17	117:152	Collocation acquisition is, of course, not a goal by itself, but rather aims at creating collocation lexicons for both language processing and generation (Smadja and McKeown, 1990).
---------------------------------------------------
W94-0101:18	92:275	'/'he study of collocations for generation fits in more naturally with sl.atistical techniques, as illustrated by Smajda and McKeown (1990).
---------------------------------------------------
P90-1020:19	8:297	In particular, one type of unification formalism, functional unification grammar (FUG) is widely used for text generation (Kay, 1979, McKeown, 1985, Appelt, 1985, Paris, 1987, McKeown & Elhadad, 1990) and is beginning to be used for parsing (Kay, 1985, Kasper, 1987).
---------------------------------------------------
P90-1020:20	142:297	The extended formalism described in this paper is implemented in Common Lisp using the Union-Find algorithm (Elhadad, 1988), as suggested in (Huet, 1976, Ait-Kaci, 1984, Escalada-Imaz & Ghallab, 1988) and is used in several research projects (Smadja & McKeown, 1990, Elhadad et al, 1989, McKeown & Elhadad, 1990, McKeown et al, 1991).
---------------------------------------------------
W91-0212:21	170:242	The next set of lookup levels described, in which the structural word is no longer the primary entity but just a handle for indexing graphs, can be built on the basis of knowledge assembled from large volumes of text; the methodology employed by Smadja and McKeown (1990) would be one of many techniques possible for obtaining and organizing the various levels of model graphs.
---------------------------------------------------
W91-0212:22	230:242	Reading, MA: Addison-Wesley Publishing Co. \[16\] Smadja, F. A., and K. McKeown (1990).
---------------------------------------------------
W04-1112:23	53:195	Previous studies have proposed many promising ways for this purpose, for instance, Smadja and McKeown (1990), and Frantzi and Ananiadou (1996) tried to treat more general structures like collocations.
---------------------------------------------------
