Note that LR-like parsing algorithms were proposed by Schabes and Vijay-Shanker (1990) and Nederhof (1998). 
The complete construction of LR-style parser for TAGs can be found in Schabes and Vijay-Shanker (1990). 
2The algorithm described here can be extended to use SLR(1) tables (Schabes and Vijay-Shanker, 1990). 
The algorithm from Schabes and Vijay-Shanker (1990) however also accepts adb~ec ~ and aPdbec. 
Parser generation here is taken to be the construction of LR(0) tables (i.e. , without any lookahead) for a particular TAG z. The moves made by the parser can be explained by an automaton which is weakly equivalent to TAGs called Bottom-Up Embedded Pushdown Automata (BEPDA) (Schabes and Vijay-Shanker, 1990) 3. 
