Finally, Fong (1990) performs a combinatorial analysis of the paradigm of free indexation, as proposed in (Chomsky, 1981); he shows that free indexation gives rise to an exponential number of alternatives and argues for the necessity of interleaving indexing and structure computation.


As discussed in Correa (1988), this procedure is grossly inefficient: its complexity was shown in Fong (1990) to be of exponential order.


