ESSENTIAL ARGUMENTS: AN EXTENSION The notion of an essential argument in a PROLOG literal has been first introduced in (Strzalkowski, 1989), and subsequently extended in (Strzalkowski, 1990bc; Sttzalkowski and Peng, 1990). 
Strzalkowski (1990) and Strzalkowski/Peng (1990) describe a compiler that transforms a grammar originally written for parsing into an efficient generator. 
5 Below is the general procedure MSEAS for computing the active sets of essential arguments in the head literal of a clause as proposed in (Strzalkowski and Peng, 1990). 
We have completed a first implementation of the system and used it to derive both a parser and a generator from a single DCG grammar for English (Strzalkowski and Peng, 1990). 
The general algorithm has been described in (StrTalkowski, 1990c; Strzalkowski and Peng, 1990). 
