C90-2045:1	29:111	The grammar rules are based on Constraint Dependency Grammar (Maruyama 1990), and are essentially constraints between modifications.
---------------------------------------------------
W98-0504:2	7:228	Not only do all linguistic theories refer to some reformulation of the traditional notion of valency (in the form of 0grid, subcategorization list, argument list, or extended domain of locality); there is a growing number of parsers based on binary relations between words (Eisner, 1997; Maruyama, 1990).
---------------------------------------------------
P06-1041:3	32:175	3 WCDG An architecture which fulfills this requirement is Weighted Constraint Dependency Grammar, which was based on a model originally proposed by Maruyama (1990) and later extended with weights (Schroder, 2002).
---------------------------------------------------
W04-0311:4	50:147	3 Basic Dependency Parsing Using constraint satisfaction techniques for natural language parsing was introduced rst in (Maruyama, 1990) by de ning a constraint dependency grammar (CDG) that maps nicely on the notion of a CSP.
---------------------------------------------------
D07-1013:5	6:290	1 Introduction Syntactic dependency representations have a long history in descriptive and theoretical linguistics and many formal models have been advanced (Hudson, 1984; Melcuk, 1988; Sgall et al. , 1986; Maruyama, 1990).
---------------------------------------------------
C92-4184:6	133:148	As an application <>f the meta:inference capability, let us describe the interactive Japanesp parser of the Japanese t<FEnglish m;u:hine translation system JETS (Maruyama, Watanabe, & Oginn 1990).
---------------------------------------------------
C92-4184:7	11:148	The parsing method of Constraint Dependency Grammar (Maruyama 1990) axldressed exactly these issues.
---------------------------------------------------
P98-1086:8	25:141	Maruyama (1990) describes full parsing by means of constraint satisfaction for the first time.
---------------------------------------------------
P98-1026:9	9:150	Not only do all linguistic theories refer to some reformulation of the traditional notion of valency (in the form of 0grid, subcategorization list, argument list, or extended domain of locality); there is a growing number of parsers based on binary relations between words (Eisner, 1997; Maruyama, 1990).
---------------------------------------------------
W98-0509:10	81:227	The original definition of constraint dependency grammars by Maruyama (1990) is extended to graded constraint dependency grammars which are represented by a tuple (~, L, C, ~) The lexicon !~ is a set of word forms each of which has some lexical information associated with it.
---------------------------------------------------
W98-0509:11	24:227	Maruyama (1990) first tried to extend the idea to allow the treatment of complete dependency structures.
---------------------------------------------------
C02-1104:12	26:149	1 Property Grammars The notion of constraints is of deep importance in linguistics, see for example Maruyama (1990), Pollard (1994), Sag (1999).
---------------------------------------------------
J92-2001:13	289:441	Dependency grammar has been applied in the experimental parsing systems of Hellwig (1986), Sigurd (1989), and Covington (1991); in the 'Kielikone' natural language interface of Jappinen, Lassila, and Lahtola (1988); in the machine translation systems of EUROTtLA (Johnson, King, and des Tombe 1985), DLT (Schubert 1987), Charles University (Sgall and Panevov~ 1987), and IBM Tokyo (Maruyama 1990); and in the speech recognition system of Giachin and Rullent (1989).
---------------------------------------------------
A00-2014:14	69:344	An arity of two suffices to represent a grammar at least as powerful as a context-free grammar (Maruyama, 1990a; Maruyama, 1990b).
---------------------------------------------------
A00-2014:15	35:344	Our NLP component is implemented using a CDG parser (Harper and Helzerman, 1995; Maruyama, 1990a; Maruyama, 1990b) because of its power and flexibility, in particular:  It supports the use of syntactic, semantic, and domain-specific knowledge in a uniform framework.
---------------------------------------------------
A00-2014:16	46:344	3.1 Introduction to CDG Constraint Dependency Grammar (CDG), first introduced by Maruyama (Maruyama, 1990a; Maruyama, 1990b), uses constraints to determine the grammatical dependencies for a sentence.
---------------------------------------------------
A00-2014:17	86:344	Building upon this concept of role value partitioning, it is possible to construct another way of representing unary and binary constraints because CDG constraints do not need to reference the exact position of a word or a modifiee in the sentence to parse sentences (Harper and Helzerman, 1995; Maruyama, 1990a; Maruyama, 1990b; Menzel, 1994; Menzel, 1995).
---------------------------------------------------
W06-0403:18	17:209	Maruyamas Constraint Dependency Grammar (CDG) (Maruyama, 1990) is the first formalism to introduce the parsing process as a CSP solver.
---------------------------------------------------
W02-1031:19	39:215	During parsing, the grammaticality of a sentence in a language de ned by a CDG is determined by applying a set of constraints to the possible role value assignments (Harper and Helzerman, 1995; Maruyama, 1990).
---------------------------------------------------
W02-1031:20	40:215	Originally, the constraints were comprised of a set of hand-written rules specifying which role values (unary constraints) and pairs of role values (binary constraints) were grammatical (Maruyama, 1990).
---------------------------------------------------
