Although we have not shown this here, the LCG account extends straightforwardly to the cases of coordination and morphological neutralization discussed by Zaenen and Kartunen (1984), Pullum and Zwicky (1986) and Ingria (1990).


(5) a. * Er findet und hilft Miinner he find-ACC and help-DAT men-ACC b. * Er findet und hilft Kindern he find-ACC and help-DAT children-DAT c. Er findet und hilft he find-ACC and help-DAT Frauen women-ACC+DAT Contrary to the claim by Ingria (1990), these examples can be accounted for straight-forwardly using the standard feature subsumption-based account of coordination.


In the process we provide analyses for a number of constructions that have been recognized as problematic for 'unification-based' accounts of agreements (Zaenen and Karttunen, 1984; Pullum and Zwicky, 1986; Ingria, 1990).


Consider the German examples in (5), cited by Pullum and Zwicky (1986) and Ingria (1990).


