IMPLEMENTATION The procedure for selecting connectives is part of FUF, a larger surface generator using the functional unification formalism (Elhadad, 1988, Elhadad, 1990b, McKeown&Elhadad, 1990). 
The deep module we are currently developing (Elhadad, 1990a) will use politeness constraints (Brown & Levinson, 1987) to decide which thematization is most appropriate. 
By using these descriptions, we have constructed the system network of simple sentences and we have implemented a sentence generator in Functional Unification Formalism (FUF) (Elhadad, 19902) to perform the linguistic resources. 
Using Ana (Kukich 1983) as a deep generator, Cook is implemented in FUF (Elhadad 1990), an extended implementation of FUG, and uniformly represents the lexicon and syntax as originally suggested by Halliday (1966). 
The realization component is implemented in FUF, all extended functional unification grammar formalism which we have implemented (Elhadad, 1990, Elhadad, 1992). 
