In DeMarcken (1990), the test set is included in the training set, and so it is difficult to know how this system would do on fresh text. 
The best previously reported error rate based on probabilistic models was 75% (Kuhn and DeMori 1990). 
De Marcken (1990) developed an approximate method for finding multiple tags for each word given the preceding words and one following word. 
Part-of-speech tagging is of interest for a number of applications, for example access to text data bases (Kupiec, 1993), robust parsing (Abney, 1991), and general parsing (deMarcken, 1990; Charniak et al. , 1994). 
While these models may suggest the existence of strong syntactic preferences in effect during sentence understanding, other studies provide clear evidence that purely syntactic heuristics for prepositional phrase attachment will not work (see (Whittemore, Ferrara, & Brunner, 1990), (Taraban, & McClelland, 1988)). 
