See Gibson (1990) for explanations of further gardenpath effects inside a similar framework.


4This paper extends work reported in Gibson (1990) by ap114 1 2 The Underlying Parse~ -~ The parser to which the memory limitation constraints apply must construct representations in such a way so that incomplete input will be associated with structure.


5 A similar approach has been taken by Gibson (1990) and is supported by the psychological experiments of Kurtzman (1984).


