J07-3004:1	181:503	We therefore follow the approach of Aone and Wittenburg (1990) and implement these type-changing 367 Computational Linguistics Volume 33, Number 3 Figure 3 Type-changing rules reduce the number of lexical category types required for complex adjuncts.
---------------------------------------------------
J91-3003:2	106:169	A similar 306 Carpenter CG and HPSG with Lexical Rules restriction allows Aone and Wittenburg (1990) to pre-compile the results of closing a categorial lexicon under a set of morphological operations.
---------------------------------------------------
J91-3003:3	65:169	Moortgat (1987) and Aone and Wittenburg (1990) have presented systems that allow extended categorial grammars to operate at both the morphological and syntactic levels, but the operations that can be carried out by their extended sets of rules produce results very similar to the lexical operations we allow here.
---------------------------------------------------
D09-1126:4	86:235	4.2 Lexical Rules and Zero Morphemes The CCGbank PSG extension is closely related to the zero morpheme categories proposed by Aone and Wittenburg (1990), which they suggest be compiled into unary type-changing rules for processing.
---------------------------------------------------
