The first two constraints of the schema are satisfied by creating node N3 such that its activity's agent and time are the 4The technicM report (Lochbaum, 1991) contains a more detailed discussion of the derivation of these schemas from the definitions given by Balkanski (1990).


Future work includes: (1) adding other types of constraints (e.g. restrictions on the parameters of actions) to the representation; (2) using the augmented rgraph representation in identifying, on the basis of unsatisfiable constraints, particular discrepancies in the agents' beliefs; (3) identifying information conveyed in Gi's utterances as to how he believes two acts are related (Balkanski, 1991) and incorporating that information into our model of Gj's reasoning.


However, Jackendoff's semantic decomposition doesn't go beyond the construction of the logical form of a sentence, and he doesn't pursue the issue of what the relation between the actions described in the matrix and adjunct really is. The only other work that mentions purpose clauses in a computational setting is (Balkanski, 1991).


Balkanski (1991) does mention that purpose clauses express generation or enablement, but she doesn't provide evidence to support this claim.


