A number of automatic sentence alignment techniques have been proposed (Kay and Rscheisen, 1993; Gale and Church, 1991; Brown et al. , 1991; Debili and Samouda, 1992; Papageorgiou et al. , 1994; Gaussier, 1995; Melamed, 1996; Fluhr et al. , 2000). 
A number of alignment techniques have been proposed, varying from statistical methods (Brown et al. , 1991; Gale and Church, 1991) to lexical methods (Kay and RSscheisen, 1993; Chen, 1993). 
2.2 Word Alignment Aligning below the sentence level is usually done using statistical models for machine translation (Brown et al. , 1991; Brown et al. , 1993; Hiemstra, 1996; Vogel et al. , 1999) where any word of the targetlanguageistakentobeapossibletranslation for each source language word. 
Like Gale & Church (1991) and Brown et al. 
Several automatic sentence alignment approaches have been proposed based on sentence length (Brown et al., 1991) and lexical information (Kay and Roscheisen, 1993). 
