2 Background Default unification has been investigated by many researchers (Bouma, 1990; Russell et al. , 1991; Copestake, 1993; Carpenter, 1993; Lascarides and Copestake, 1999) in the context of developing lexical semantics.


As other researchers pursued efficient default unification (Bouma, 1990; Russell et al. , 1991; Copestake, 1993), we also propose another definition of default unification, which we call lenient default unification.


This would not be possible with some previous versions of default unification, including Russell, Carroll, and Warwick-Armstrong (1991), Russell et al.


1.2 Previous Definitions of Default Operations on Feature Structures There have been a number of previous definitions of default unification, including those given by: van den Berg and Pr6st (1991), Bouma (1990, 1992), Calder (1991), Carpenter (1993), Copestake (1992, 1993), Russell, Carroll, and Warwick-Armstrong (1991), and Russell et al.


We omit the details, since we want to keep the definition of the default operation as general as possible, and there are a number of different constraint languages within feature structure frameworks (e.g. , Alshawi et al. 1991; 70 Lascarides and Copestake Default Representation Carpenter 1992; D6rre and Eisle 1991; Emele and Zajac 1990; Gerdemann and King 1994; Krieger and Sch/ifer 1994; de Paiva 1993; Smolka 1989).


