W91-0105:1	162:280	A major aspect of the BiLD project is that a specific parametrization of the deduction process is represented in the lexicon as well as in the grammar to obtain efficient structures of control (Uszkoreit, 1991).
---------------------------------------------------
P92-1026:2	48:196	Since it is a well established fact that only one constituent can be fronted, the flat structure can account for the German examples in (1), but not for the ones in (2), (1) sollte der Kurier nachher einem Spion den Brief zustecken zustecken sollte der Kurier nachher einem Spion den Brief den Brief sollte der Kurier nachher einem Spion zustecken 1Further reasons are discussed in Uszkoreit (1991b).
---------------------------------------------------
P92-1026:3	196:196	But until we have developed a well-founded theory of degrees of acceptability, and explored appropriate formal means such as weighted feature structures, as proposed in (Uszkoreit 1991a), we will either have to ignore ordering principles or treat them as absolute constraints.
---------------------------------------------------
P92-1026:4	190:196	Uszkoreit (1991b) applies LP principles to head domains but employs a finite-state automaton for the encoding of LP constraints.
---------------------------------------------------
P92-1026:5	189:196	For a discussion, see Uszkoreit (1991b).
---------------------------------------------------
W97-1503:6	103:197	For instance, it is possible to force the unifier to consider in the first place the paths that have been observed to cause more frequent failures (Uszkoreit, 1991).
---------------------------------------------------
