Heylen [1997], in which the grammar rule imposes a fixed partial order, e.g., X/Y combines with Z if 12 This coincides with Steedmans (1991b) observation that directionality of the main functors slash is also a property of the same argument. 
As one reviewer noted, CCG formulation of the syntax-phonology interface moved from autonomous prosodic types (Steedman 1991a) to syntax-directed prosodic features (Steedman 2000b). 
This approach is exemplified by Combinatory Categorial Grammar, CCG (Steedman 1991), which takes a basic CG with just application, and adds various new ways of combining elements together 2. 
Our lexical type assignment to case morphemes (24ef) departs from other CCG analyses of case (e.g. , Steedman 1985, 1991a, Bozsahin 1998). 
7 We will not elaborate on the theoretical consequences of having this level of representation; see, for instance, Dowty (1991) and Steedman (1996). 
