Moreover, a similar experiment was performed with two other grammars: the English MiMo2 grammar (van Noord et al. 1991), and the English Alvey NL Tools grammar (Grover, Carroll, and Briscoe 1993). 
(1990) and van Noord (1991). 
In van Noord (1991, 1993) I argue that head-corner parsing is especially useful for parsing with nonconcatenative grammar formalisms. 
van Noord (1990b) and also Thompson (1991, this volume). 
In Lavelli and Satta (1991) and van Noord (1994) head-driven parsing strategies for Lexicalized Tree Adjoining Grammars are presented. 
