It employs constraint projection (Nakano, 1991) as an efficient constraint transformation method. 
unification of disjunctive feature structures (Kasper and Rounds, 1986; Hasida, 1986; DSrre and Eisele, 1990; Nakano, 1991; Blache, 1997; Blache, 1998). 
Some constraint transformation methods whose resulting constraints are compact have been proposed (Hasida, 1986; Nakano, 1991). 
There are also several disjunctive unification algorithms that exploit independence, such as constraint unification (Hasida 1986; Nakano 1991), contexted unification (Maxwell and Kaplan 1989), and unification based on disjunctive feature logic (D6rre and Eisele 1990). 
Unification operations are performed by using constraint projection,,Ul efficient method for unifying disjunctive lhature descriptions (Nakano, 1991). 
