Grosz, Lochbaum, and Sidner (Grosz and Sidner 1990; Lochbaum, Grosz, and Sidner 1990; Lochbaum 1991) have specified a system in which two agents are working to accomplish some common goal by building a "shared plan" in which each agent holds certain beliefs and intentions.


Other collaborative models assume that two participants are working together to achieve a common goal (Cohen and Levesque 1990a, 1991a, 1991b; Lochbaum, Grosz, and Sidner 1990; Lochbaum 1991; Grosz and Sidner 1990; Searle 1990).


A comparison of our representation and algorithms with Kautz's can be found elsewhere (Lochbaum 1991, 1994).


We then compare our approach to discourse 528 Lochbaum A Collaborative Planning Model processing with previous plan-based approaches (Litman 1985; Litman and Allen 1987; Lambert and Carberry 1991; Ramshaw 1991) and show that our approach is aimed at recognizing and reasoning with a different type of intention.


