We will use a representation framework for discourse structure called SDRT (standing for Segmented Discourse Representation Theory) (Asher 1993), and a theory of discourse attachment called DICE (standing for Discourse and Commonsense Entailment), which is designed to compute temporal implicatures for natural language texts (Lascarides and Asher 1991). 
They 3The formal details of how the logic CB models these interpretations are given in Lascarides and Asher (1991b). 
Inference of coherence relations has been used in modeling temporal (Lascarides and Asher 1991; Lascarides, Asher, and Oberlander 1992) and other defeasible discourse inferences (Hobbs 1978; Dahlgren 1989). 
Lascarides and Asher (1991) use DICE to yield the discourse structures and temporal structures for simple discourses. 
Lascarides, Asher, and Oberlander (Lascarides & Asher, 1991; Lascarides & Oberlander, 1992) described the interpretation and generation of temporal implicatures. 
