P94-1018:1	106:291	5.2 Previous Approaches Following up on the work of Lambek (1958) who proposed that the process of deriving the grammaticality of a string of categories be viewed as a proof, there have been quite a few proposals put forth for computing only normal forms of derivations or proofs (KSnig 1989; Hepple and Morrill 1989; Hepple 1991; inter alia).
---------------------------------------------------
P94-1018:2	114:291	4In the case of Hepple's (1991) proposal, a leftbranching normal form is indeed computed.
---------------------------------------------------
C92-1024:3	171:220	The modified chart method instead allows for the construction of incremental constituents in a manner that most closely relates to tim notion of dependency constituency argued for by Barry & Pickering (1990) (see also Hepple, 1991), although since the modified parser is still a complete parser for L it cannot be viewed as implementing a notion of dependency constituency.
---------------------------------------------------
C92-1061:4	8:181	We may quote for instance works by Hudson (1984, 1990), Barry & Picketing(1990), Hausser (1990), Hepple (1991).
---------------------------------------------------
C92-1061:5	76:181	23-28, 1992 figure (4): a/ (c\b) (c\b) /d c\b d > a a/(c\b) (c\b)/d a/d d >B a / Moreover, a connection system provides us with a semantics for Dependency-Constituency Grammars, in the tradition of Barry and Picketing (1990) and Mark Hepple (1991).
---------------------------------------------------
W05-1605:6	79:240	4.2 Avoiding spurious derivations Categorical grammars often allow so called spurious derivations in that one and the same syntactic structure can be derived in several different ways [Hepple, 1991].
---------------------------------------------------
