This, in itself, provides sufficient motiw~tion for opting for such representations rather than, say, feature structures or the recursive QLFs (Alshawi et al., 1991) of CLE (Alshawi, 1992).


The translation task of the SICS-SRI l:/ilin-gnal Conversation Interpreter, BCI (Alshawi et al. , 1991) is quite similar to that of Verbmobil.


The primary, rule-based translation mechanism performs transfer at the level of Quasi-Logical Form (QLF), a type of predicate/argument style notation (Alshawi et al. , 1991).


