J03-4002:1	144:694	(Further discussion of such examples can be found in Isard [1975]; Dale [1992]; and Webber and Baldwin [1992]).
---------------------------------------------------
C94-2186:2	118:372	Second, Webber and Baldwin (1992) discussed the integration of two independent mechanisms for context-change by entity introduction and by event simulation.
---------------------------------------------------
J95-3001:3	822:965	Webber and Baldwin (1992) have examined the phenomenon called "context change" in discourse, which refers to the movement from subdialog to subdialog (or from segment to segment).
---------------------------------------------------
