Similarly, some grammar induction algorithms, such as those used by Pereira and Schabes (1992) do not produce meaningful labels. 
In (Pereira and Schabes, 1992), 90.36% bracketing accuracy was reported using a stochastic CFG trained on bracketings from the ATIS corpus. 
This is the same general procedure as used by (Lari and Young, 1990; Briscoe and Waegner, 1992; Pereira and Schabes, 1992) and others. 
Earlier research on inside-outside estimation of PCFG models has reported some positive results as well 193 (Pereira and Schabes, 1992; Carroll and Rooth, 1998; Beil et al., 1999; imWalde, 2002). 
5.1 Experiment with Grammar Induced by Pereira and Schabes Method The experiment of Pereira and Schabes (1992) was duplicated. 
