In (Agarwal and Boggess, 1992) the task is to identify pre-CC conjuncts which appear in text that has been part-of-speech (POS) tagged and semiparsed, as well as tagged with semantic labels specific to the domain. 
Previous studies on coordination disambiguation suggested that conjuncts in coordinate structures have syntactic or semantic similarities, and dealt with coordination ambiguities using (sub-)string matching, part-ofspeech matching, semantic similarities, and so forth(AgarwalandBoggess,1992). 
Agarwal and Boggess (1992) focus on the identification of the conjuncts of coordinate conjunctions. 
In English, conversely, the phrase following the conjunction is the posthead, and the pre-head is searched for in the same way (Agarwal and Boggess 1992). 
Other studies on coordination include (Agarwal and Boggess, 1992; Chantree et al., 2005; Goldberg, 1999; Okumura and Muraki, 1994). 
