Resnik (1992, 1997) defines an informationtheoretic measure of the association between a verb and nominal WordNet classes: selectional association. 
However, it is very difficult to gather sufficient co-occurrences to calculate similarities reliably \[Resnik, 1992; Basili et al. , 1992\]. 
In (Schubert, 2002) we made some comparisons between our project and earlier work in knowledge extraction (e.g. , (muc, 1993; muc, 1995; muc, 1998; Berland and Charniak, 1999; Clark and Weir, 1999; Hearst, 1998; Riloff and Jones, 1999)) and in discovery of selectional preferences (e.g. , (Agirre and Martinez, 2001; Grishman and Sterling, 1992; Resnik, 1992; Resnik, 1993; Zernik, 1992; Zernik and Jacobs, 1990)). 
(1991), or with hyponym extraction based on entirely syntactic criteria as in Hearst (1992) or lexico-semantic associations (e.g., Resnik (1992) or Sekine et al. 
2. Resnik, P. , (1992) "A Class-based Approach to Lexical Discovery," Proceedings of the 30th Annual Meeting of the ACL, pp. 
