In the CLE-QLF approach, as ra519 Computational Linguistics Volume 26, Number 4 tionally reconstructed by Alshawi and Crouch (1992) and Crouch and Pulman (1994), the context-independent meaning of a sentence is given by one or more QLFs that are built directly from syntactic and semantic rules. 
F-structures are either interpreted indirectly in terms of a homomorphic embedding into Quasi Logical Form (QLF) (Alshawi, 1992; Alshawi & Crouch, 1992; Cooper et al. , 1994a) representations or directly in terms of adapting QLF interpretation clauses to f-structure representations. 
Terms and indices not dischargeable in this manner lead to uninterpretable QLFs (Alshawi and Crouch, 1992). 
When Sforns axe described in (Alshawi and Crouch, 1992). 
1 Introduction Underspecification is the standard approach to dealing with scope ambiguity (Alshawi and Crouch, 1992; Pinkal, 1996). 
