P95-1029:1	28:159	213 (Park, 1992) proposes a solution within first-order unification that can handle not only sentence (la), but also more complex examples with determiners.
---------------------------------------------------
P95-1029:2	146:159	Also, whereas (Park, 1992) requires careful consideration of handling of determiners with coordination, here such sentences are handled just like any others.
---------------------------------------------------
P95-1028:3	137:332	One is to use elementary categories, such as np or s, in encoding both syntactic types and logical forms (Jowsey, 1990; Steedman, 1990; Park, 1992).
---------------------------------------------------
P95-1028:4	153:332	This value of !1 is transferred to the expression s:evory(X,li,S) by partial execution (Pereira Shieber, 1987; Steedman, 1990; Park, 1992).
---------------------------------------------------
P95-1028:5	171:332	This is exactly predicted by the present CCG framework, extending Geach's observation regarding (6) (a), since the coordination forces the two NPs, most customers and three cars, to be composed first (Dowty, 1988; Steedman 1990; Park 1992).
---------------------------------------------------
