For instance, Kamei and Wakao (Kamei, 1992) approached the question from the perspective of machine translation and conducted a comparative survey of the acceptability of metonymic expressions in English, Chinese and Japanese consisting of 25 test sentences.


2 Related Work Analysis of metonymies as a linguistic phenomenon dates back at least to the 1930s (Stern, 1931), and are increasingly recognized as an important phenomenon to tackle in the interest of higher level language processing tasks, such as anaphora resolution (Harabagiu, 1998; Markert and Hahn, 2002), question answering (Stallard, 1993) or machine translation (Kamei and Wakao, 1992).


For example, a direct translation of 'he read Mao', which is acceptable in English an(1 Japanese, is comt)letely unacceptal)le in Chinese (Kamei and Wakao, 1992).


(1) Ask seat 19 whetherhewantstoswap The importance of resolving metonymies has been shown for a variety of NLP tasks, e.g., machine translation (Kamei and Wakao, 1992), question answering (Stallard, 1993) and anaphora resolution (Harabagiu, 1998; Markert and Hahn, 2002).


