The data structure of the discourse memory is based on the ideas presented in LuperFoy (1992), Salmon-Alt (2000). 
Another system (Luperfoy 1992) uses "discourse pegs" to model referents and was applied successfully to a man-machine dialogue task. 
~1--7--7 -~-77~'---?~  Back~End InterfaCe :: Context Trackin~ pragmatic Adaptation Dialogue Manager TrueTalk (Entropie) Simulated ::: Simulated (LuperFoy 1992) Currently, Simulated Current Development Table 5. 
14 This distinction is similar to the one made by Luperfoy (1992). 
Recent advances in dialogue management and multidomain systems enable approaches that are more flexible than slot-filling, e.g. using discourse pegs, dialogue games and overlay operations for handling multiple tasks and cross-modal references (LuperFoy, 1992; Lockelt et al. , 2002; Pfleger et al. , 2002; Alexandersson and Becker, 2003). 
