Related Formalisms Based on word-order facts from Turkish, Hoffman (1992) proposes an extension to CCG called {}-CCG, in which arguments of functors form sets, rather than being represented in a curried notation. 
Hoffman, in her thesis (Hoffman, 1995a, Hoffman, 1995b), has used the MultisetCombinatory Categorial Grammar formalism (Hoffman, 1992), an extension of Combinatory Categorial Grammar to handle free word order languages, to develop a generator for Turkish. 
In future research, I will investigate whether VAR-CCGs is an adequate linguistic formalism in capturing all aspects of free word order languages or whether a formalism such as {}-CCGs (Hoffman 1992), which allows sets of arguments in function categories, is better suited. 
The following application rules allow a function 3A preliminary version of the syntactic component of the grammar was presented in (Hoffman, 1992). 
See (Hoffman, 1992) for a CCG based approach to this phenomenon. 
