This kind of reasoning that leads to the formation of complex tree structures is given by Rogers and Vijay-Shanker (1992). 
D-trees are descriptions of trees, in particular, certain types of expressions in a tree description language such as that of Rogers and Vijay-Shanker (1992). 
The language of this description and its semantic is given by Rogers and Vijay-Shanker (1992). 
They use monotonic inheritance to build up partial descriptions of trees: each description is a finite set of dominance, immediate dominance and linear precedence statements about tree nodes in a tree description language developed by Rogers & Vijay-Shanker (1992), and category information is located in the node labels. 
Rogers and Vijay-Shanker (1992) describe a proof system that can be used to perform the type of reasoning involved in constructing the structure o~23 as described above. 
