The planning approach has been used by some scientists to produce speech acts in the context of a dialogue (Allen 1983, Appelt 1985, Litman and Allen 1987, Lambert and Carberry 1992). 
This is also true of Lambert and Carberry's (1992) more recent work on modeling negotiation subdialogues. 
10 Carberry and Lambert Modeling Negotiation Subdialogues Galliers (1991, 1992) has specified a nonnumeric theory of belief revision that relates strength of belief to persistence of belief. 
23 Tree structures are often used to represent discourse, but usually the hierarchical structure of the discourse, rather than its temporal structure (see Lambert and Carberry 1991, 1992). 
Subsequent work by Lambert and Carberry (1991, 1992) introduces an intermediate, problem-solving level of plans that link the discourse-level acts to domain plans. 
