E93-1040:1	9:127	Baker (1979) describes a training algorithm for stochastic context-free grammars (SCFG) which can be used for grammar reestimation (Fujisaki et al. 1989, Sharrnan et al. 1990, Black et al. 1992, Briscoe and Waegner 1992) or grammar inference from scratch (Lari and Young 1990).
---------------------------------------------------
P09-1041:2	7:264	Later approaches avoided grammar writing by learning the grammar from sentences explicitly annotated with their syntactic structure (Black et al., 1992).
---------------------------------------------------
P93-1006:3	66:194	(1992) and Wojcik et al.
---------------------------------------------------
C94-1079:4	190:192	Even though the lexicon is derived from machine readable dictionaries and contains a \]a.rge number of senses for many words, the ratio between the number of parse trees and the sentence length here is well bellow the ratio reported in (Black et al. , 1992).
---------------------------------------------------
C94-1079:5	152:192	I"or example, the average number of parses pet' word is 1.35 in (l\]lack et al. , 1992).
---------------------------------------------------
