The SRI group (Bear et al. , 1992) employed simple pattern matching techniques for detecting and correcting modification repairs. 
(1992) and Bear et al. 
(Hindle, 1983) and (Bear et al. , 1992) performed speech repair identification in their parsers, and removed the corrected material (reparandum) from consideration. 
Because of the availability of the Switchboard corpus [Godfrey et al. 1992] and other conversational telephone speech (CTS) corpora, there has been an increasing interest in improving the performance of identifying the edited regions for parsing disfluent sentences [Charniak and Johnson 2001, Johnson and Charniak 2004, Ostendorf et al. 2004, Liu et al. 2005]. 
4.1 Before parsing Detection of self corrections on transcriptions before parsing has been explored (Bear et al., 1992; Nakatani and Hirschberg, 1993), but it is not clear that it will be feasible on WHGs, since recognition errors interfere and the search space may explode due to the number of paths. 
