ASR is done using CMU Sphinx6, from which the n-best list of results are passed to SRIs Gemini parser (Dowding et al. , 1993). 
3 Language Interpretation and Generation The language used in CommandTalk is derived from a single grammar using Gemini (Dowding et al. , 1993), a unification-based grammar formalism. 
In a test set containing 26 repairs Dowding et al. 1993, they obtained a detection recall rate of 42% with a precision of 85%, and a correction recall rate of 31% with a precision of 62%. 
Initial language processing is carried out Using the SRI Gemini system (Dowding et al. , 1993), using a domain-independent unification. 
2 Typed Unification Grammars Typed Unification Grammars (TUG), like HPSG (Pollard and Sag 1994) and Gemini (Dowding et al. 1993) are a more expressive formalism in which to write formal grammars1. 
