C00-1078:1	62:146	These transtbr rules are pairs of corresponding rooted substructures, where a substructure (Matsumoto et al. , 1993) is a connected set of arcs and nodes.
---------------------------------------------------
C04-1154:2	30:166	(Matsumoto et al. , 1993) and (Imamura, 2001) focus on using alignments to help resolve parsing ambiguities.
---------------------------------------------------
C04-1154:3	13:166	(Matsumoto et al. , 1993) align source,target dependency trees, with a view to resolve parsing ambiguities, but their approach cannot deal with complex or compound sentences.
---------------------------------------------------
W01-1511:4	20:203	In particular, for MT, we expect it will benefit procedures which learn translation rules from syntactically analyzed parallel corpora, such as (Matsumoto et al. , 1993; Meyers et al. , 1996).
---------------------------------------------------
P04-1083:5	162:203	This kind of synchronizer stands in contrast to more ad-hoc approaches (e.g. , Matsumoto, 1993; Meyers, 1996; Wu, 1998; Hwa et al. , 2002).
---------------------------------------------------
C96-2163:6	9:141	Especially if the two languages have different syntactic structures and word meanings (such as English and Japanese), this approach has proved to be most effective in disambiguation (Matsumoto et al. , 1993; Utsuro et al. , 1993).
---------------------------------------------------
C94-2175:7	46:134	So fitr, we have implemented the following,: sentence ~dignment btLsed-on word correspondence information, word correspondence estimation by cooccnl'rence-ffequency-based methods in GMe mid Church (19.~H) and Kay and R6scheisen (1993), structured Imttehlng of parallel sentences (Matsumoto et a l. , 1993), and case Dame acquisition of Japanese verbs (Utsuro et al. , 1993).
---------------------------------------------------
W95-0106:8	87:153	It is interesting to constrast this method with the "parse-parse-match" approaches that have been reported recently for producing parallel bracketed corpora (Sadler & Vendelmans 1990; Kaji et al. 1992; Matsumoto et al. 1993; Cranias et al. 1994; Gfishman 1994).
---------------------------------------------------
W95-0106:9	102:153	More sophisticated "parse-parse-match" procedures postpone ambiguity resolution until the matching stage (Kaji et al. 1992; Matsumoto et al. 1993; Grishman 1994).
---------------------------------------------------
C96-1078:10	137:234	9 This precision measure was previously used in (Matsumoto et al. , 1993) a.nd ((h:ishman, 71994).
---------------------------------------------------
C96-1078:11	10:234	(Sate and Nagao, 1990), (Klawms and Tzoukermann, 1990), (Grishman and Kosaka, 1992), (Kaji et al. , 1992), (Matsumoto et al. , 11993) and (Grishman, 11994)).
---------------------------------------------------
P96-1018:12	11:249	1 Introduction Corpus-based approaches based on bilingual texts are promising for various applications(i.e. , lexical knowledge extraction (Kupiec, 1993; Matsumoto et al. , 1993; Smadja et al. , 1996; Dagan and Church, 1994; Kumano and Hirakawa, 1994; Haruno et al. , 1996), machine translation (Brown and others, 1993; Sato and Nagao, 1990; Kaji et al. , 1992) and information retrieval (Sato, 1992)).
---------------------------------------------------
C02-1010:13	22:202	1 Related Works Most of the previous works conduct structure alignment with complex, hierarchical structures, such as phrase structures (e.g. , Kaji, Kida & Morimoto, 1992), or dependency structures (e.g. , Matsumoto et al. 1993; Grishman, 1994; Meyers, Yanharber & Grishman 1996; Watanabe, Kurohashi & Aramaki 2000).
---------------------------------------------------
C02-1010:14	26:202	Then the correspondent structures in different languages are aligned (e.g. , Kaji, Kida & Morimoto 1992; Matsumoto et al. 1993; Grishman 1994; Meyers, Yanharber & Grishman 1996; Watanabe, Kurohashi & Aramaki 2000).
---------------------------------------------------
C04-1155:15	11:128	In structural example-based machine translation systems (Grishman, 1994; Meyers et al. , 1998; Watanabe et al. , 2000), examples in the knowledge base are normally annotated with their constituency (Kaji et al. , 1992) or dependency structures (Matsumoto et al. , 1993; Aramaki et al. , 2001; AlAdhaileh et al. , 2002), which allows the corresponding relations between source and target sentences to be established at the structural level.
---------------------------------------------------
C04-1155:16	51:128	In many phrasal matching approaches, such as constituency-oriented (Kaji et al. , 1992; Grishman, 1994) and dependencyoriented (Matsumoto et al. , 1993; Watanabe et al. , 2000; Aramaki et al. , 2001), crossing constraints are deployed implicitly in finding the structural correspondences between pair of representation trees of a source sentence and its translation in target.
---------------------------------------------------
C04-1155:17	59:128	Therefore, such schema can serve as a mean to represent translation examples, and find structural correspondences for the purpose of transfer grammar learning (Watanabe et al. , 2000; Matsumoto et al. , 1993; Meyers et al. , 1998).
---------------------------------------------------
A94-1006:18	114:178	3 Bilingual Task: An Application for Word Alignment 3.1 Sentence and word alignment Bilingual alignment methods (Warwick et al. , 1990; Brown et al. , 1991a; Brown et al. , 1993; Gale and Church, 1991b; Gale and Church, 1991a; Kay and Roscheisen, 1993; Simard et al. , 1992; Church, 1993; Kupiec, 1993a; Matsumoto et al. , 1993; Dagan et al. , 1993).
---------------------------------------------------
C96-1089:19	148:193	The technique we use is similar to the parsing-b~sed methods for extracting bilingual collocation(Matsumoto et al. , 1993).
---------------------------------------------------
C00-2135:20	14:148	Previous methods mostly use rule-based parsers for preprocessing(Matsumoto et al. , 1993), (Kitamura and Matsumoto, 1995).
---------------------------------------------------
C96-1037:21	15:214	The resolution of alignment can vat3, from low to high: section, paragraph, sentence, phrase, and word (Gale and Church 1993; Matsumoto et al. 1993).
---------------------------------------------------
W97-0114:22	35:203	Several methods have been proposed with regard to aligning sentences (Brown et al. , 1991; Gale and Church, 1991; Haruno and Yamazaki, 1996; Kay and l~osche/sen, 1993), alJs~nlng words (Church, 1993; Kupiec, 1993; Matsumoto et al. , 1993; Wu, 1995; Yamada et al. , 1996) and acquiring rules from bilingual corpora (Dagan et al. , 1991; Dagan and Church, 1994; Fung and Church, 1994; Tana~, 1994; Yamada et al. , 1995).
---------------------------------------------------
C94-2178:23	7:102	Motivation There have been quite a number of recent papers on parallel text: Brown et al (1990, 1991, 1993), Chen (1993), Church (1993), Church et al (1993), Dagan et al (1993), Gale and Church (1991, 1993), Isabelle (1992), Kay and Rgsenschein (1993), Klavans and Tzoukermann (1990), Kupiec (1993), Matsumoto (1991), Ogden and Gonzales (1993), Shemtov (1993), Simard et al (1992), WarwickArmstrong and Russell (1990), Wu (to appear).
---------------------------------------------------
W93-0301:24	6:185	1 Introduction Aligning parallel texts has recently received considerable attention (Warwick et al. , 1990; Brown et al. , 1991a; Gale and Church, 1991b; Gale and Church, 1991a; Kay and Rosenschein, 1993; Simard et al. , 1992; Church, 1993; Kupiec, 1993; Matsumoto et al. , 1993).
---------------------------------------------------
W02-1601:25	136:162	Synchronous correspondence sn G41 st G41 (0-1,0-1) (0-4 0-1 2-3 34, 0-6 0-1 2-3 3-4 4-5) (0-1,0-1) (2-3,2-3) (2-3,2-3) beschenkte [v] (1-2/0-4) Er [n] (0-1/0-1) reichlich[adj] (3-4/3-4) Hans [n] (2-3/2-3) 0 Er 1 beschenkte 2 Hans 3 reichlich 4 give[v] (1-2/0-6) He [n] (0-1/0-1) John [n] (2-3/2-3) present [n] (5-6/3-6) an[det] (3-4/3-4) expansive[adj] (4-5/4-5) 0 He 1 gave 2 John 3 an 4 expansive 5 5 present 6 (3-4,4-5) (0-4,0-6) (3-4,4-5) 2000), (Meyers et al. , 2000), (Matsumoto et al. , 1993) and (kaji et al. , 1992).
---------------------------------------------------
W02-1601:26	71:162	For example, such schema can serve as a mean to represent translation examples, or find structural correspondences for the purpose of transfer grammar learning (Menezes & Richardson, 2001), (Aramaki et al. , 2001), (Watanabe et al. , 2000), (Meyers et al. , 2000), (Matsumoto et al. , 1993), (kaji et al. , 1992), and example-base machine translation EBMT 3 (Sato & Nagao, 1990), (Sato, 1991), (Richardson et al. , 2001), (Al-Adhaileh & Tang, 1999).
---------------------------------------------------
