Krieger, Pirker, and Nerbonne (1993), who reconstruct finite-state automata in a feature description language.


As an illustration, consider the data from German verb inflections analyzed by Krieger, Pirker, and Nerbonne (1993).


6 A similar approach is envisaged by Krieger, Pirker, and Nerbonne (1993).


While it is clearly possible to integrate an essentially generative model into the mold of constraint-based grammar (Krieger, Pirker, and Nerbonne 1993), it is less clear that this is the approach most phonologists would wish to take nowadays.


