Stallard (1993) indirectly addresses the second aspect by taking into account scoping relations and impacts on pronominal reference. 
(1) Ask seat 19 whetherhewantstoswap The importance of resolving metonymies has been shown for a variety of NLP tasks, e.g., machine translation (Kamei and Wakao, 1992), question answering (Stallard, 1993) and anaphora resolution (Harabagiu, 1998; Markert and Hahn, 2002). 
This prompts Stallard to state that "predicative I (Or), (Q2), ({~LFt) and (qLF2) are borrowed from (StaJlard, 1993) 143 metonymy can be loosely thought of as coercion of a predicate place, rather than that of the argument NP itself". 
 (Stallard 1993) indirectly addresses the second aspect by taking into account scoping relations and consequences for pronominal reference. 
The identification of metonymy becomes important for NLP tasks such as question answering (Stallard, 1993) or geographic information retrieval (Leveling and Hartrumpf, 2006). 
