In recent years, reranking techniques have been successfully applied to the so-called history-based models (Black et al. , 1993), especially to parsing (Collins, 2000; Collins and Duffy, 2002). 
In many ways, this strategy is similar to the strategies employed by Hindle and Rooth (1993) and by Kinoshita et al. 
Previous research in sample selection has used either sequential selection (Seung, Opper, and Sompolinsky, 1992; Freund et al. , 1993; Dagan and Engelson, 1995), or batch selection (Lewis and Catlett, 1994; Lewis and Gale, 1994). 
Most of the methods that are being suggested include some kind of Machine Learning, such as history based grammars and decision tree models (Black et al. , 1993; Magerman, 1995), training or inducing statistical grammars (Black, Garside and Leech, 1993; Pereira and Schabes, 1992; Schabes et al. , 1993), or other techniques (Bod, 1993). 
History-based models of parsing were first introduced in (Black et al. , 1993). 
