It has often been pointed out, however, that there can be an additional requirement of syntactic parallelism (see for example, Kehler 1993 and Asher 1993). 
In future work we will address other forms of ellipsis and event reference, as well as integrate a previous account of strict and sloppy ambiguity into this framework (Kehler, 1993a). 
resolution to an account of discourse structure and coherence, namely our previous account (Kehler, 1993b) and the accounts of Priist (1992) and Asher (1993). 
In 2These examples have been taken or adapted from Kehler (1993b). 
2.6 Comparisons The use of terms and indices has parallels to proposals due to Kehler and Kamp (Kehler, 1993a; Gawron and Peters, 1990). 
