Previously (Aone and McKee, 1993), we reported our data-driven multilingual anaphora resolution system, which is robust, exteusible, and manually trainable.


The MDR applies different sets of generators, filters and orderers to resolve different anaphoric types (Aone and McKee, 1993).


Against the background of a growing interest in multilingual NLP, multilingual anaphora/coreference resolution has gained considerable momentum in recent years (Aone and McKee 1993; Azzam, Humphreys, and Gaizauskas 1998; Harabagiu and Maiorano 2000; Mitkov and Barbu 2000; Mitkov 1999; Mitkov and Stys 1997; Mitkov, Belguith, and Stys 1998).


