Second, a number of studies take particular (RST-)relati0ns as a starting-point, and examine how these relations are signalled on the linguistic surface; examples are the PURPOSE, RESULT and PRECONDITION relations \[Vander Linden 1994\], the CONCESSION relation \[Grote et al. 1997\], and the subject-matter relations occurring in a technical domain \[RSsner and Stede 1992, Delin et al. 1996\].


This reflects the greater diversity of procedural contexts in which preconditions arise and the corresponding diversity of the forms used to express them (see Vander Linden 1994).


For example, works on discourse marker choice (Scott and de Souza, 1990; Vander Linden, 1994; Grote and Stede, 1998; Oates, 1999), generation of referring expressions (Dale, 1992), and clause aggregation based on discourse relation (Dalianis and Hovy, 1996; Show, 1998) are all related to linguistic realization of cohesive relations.


