A sel)arate paper (Gasser, 1994) looks in detail at the model's performance for particular categories of morI)hology, in particular, template morphology and reduplication.


Connectionist work on the acquisition of morphology has been more concerned with implementing psychologically motivated models, than with acquisition of rules for a practical system ((Sproat, 1992, p.216) and (Gasser, 1994)).


