For mutual information (MI), we use two different equations: one for two-element compound nouns (Church and Hanks, 1990) and the other for three-element compound nouns (Suet al. , 1994). 
The boundary correction process utilizes well-known term extraction methods, e.g., (Su, Wu et al. 1994). 
(Su et al. , 1994) showed that the average mutual information of a compound noun tends to be higher than that of a noncompound noun, so we try to use the mutual information as the measure for identifying the compound nouns. 
Corpus-based correction of entity boundaries Our entity boundaries correction mechanism is similar to the known statistical term extraction techniques (Su, Wu et al. 1994). 
For the three-element compound nouns, the MI part is replaced with the three-element MI equation 3 (Su et al. , 1994). 
