Further details of the text grammar are given in Briscoe ~ Carroll (1994, 1995). 
We considered two possible techniques for speeding up parsing: speeding up uni cation using the techniques similar to the LINGO system (Copestake and Flickinger, 2000), or using backbone extraction (Maxwell and Kaplan, 1994; Rose and Lavie, 2001; Briscoe and Carroll, 1994). 
Our less-tightly integrated grammar is described in more detail in Briscoe & Carroll (1994). 
Its left corner chart parsing algorithm is similar to that described by Briscoe and Carroll (1994). 
Further details of the PoS grammar are given in Briscoe & Carroll (1994, 1995). 
