Another significant difference between the models is the predictions they make about the proportion 1Lauer and Dras (1994) give a formal construction motivating the algorithm given in Lauer (1994). 
An analogous approach to compounds is used in Lauer (1994) and constitutes one scheme evaluated below. 
Also, the work reported in Lauer and Dras (1994) uses simplistic estimates of the probability of a word given its thesaurus category. 
The equations presented above for the dependency model differ from those developed in Lauer and Dras (1994) in one way. 
Lauer and Dras (1994) show that under a dependency model, left-branching compounds should occur twice as often as right-branching compounds (that is twothirds of the time). 
