4 Parallelism and Inference Selecting ellipsis antecedents and parallel elements within them is an open problem (Priist, 1992; Prfist et al. , 1994; Kehler, 1993b; Grover et al. , 1994).


1 Introduction The application of default unification (Carpenter, 1993) or priority union (Kaplan, 1987; Calder, 1991) to discourse is attractive, because these related concepts meet the intuition that new information extends, corrects, or modifies old information, instead of deleting it, by keeping what is consistent.1 The use of default unification as a means for ellipsis resolution has been discussed in the first half of the nineties (Prust et al. , 1994; Grover et al. , 1994).


The most common linguistic application for default inheritance is to encode lexical generalizations (e.g. , Boguraev and Pustejovsky 1990; Briscoe, Copestake, and Boguraev 1990; Vossen and Copestake 1993; Daelemans 1987; Evans and Gazdar 1989a, 1989b, 1996; Flickinger, Pollard, and Wasow 1985; Flickinger 1987; Flickinger and Nerbonne 1992; Kilgarriff 1993; Krieger and Nerbonne 1993; Sanfilippo 1993; Shieber 1986a), but defaults have also been used for specification in syntactic theory (e.g. , Gazdar 1987; Shieber 1986b), and for the analysis of gapping constructions (Kaplan 1987) and ellipsis (Grover et al. 1994).


YADU could not replace asymmetric default unification in Grover et al.'s (1994) treatment of ellipsis.


