1 SEGMENTER: Linear Segmentation For the purposes of discourse structure identification, we follow a formulation of the problem similar to Hearst (1994), in which zero or more segment boundaries are found at various paragraph separations, which identify one or more topical text segments. 
Hearst (1994) used the similarity of word distributions as measured by the cosine to gauge cohesion. 
This variation of the TextTiling algorithm is explored and evaluated in Hearst (1994b). 
Cosine similarity is commonly used in text segmentation (Hearst, 1994). 
The method of Hearst (1994, 1997) uses cosine similarity in a word vector space as an indicator of topic similarity. 
