P97-1054:1	22:200	In particular, the definition of atomic categories needs extending to deal with featural variation (e.g. Bouma and van Noord, 1994), and the rule schemata, especially composition and weak permutation, must be restricted in various parametric ways so that overgeneration is prevented for specific languages.
---------------------------------------------------
P97-1054:2	32:200	The in2Bouma and van Noord (1994) and others demonstrate that CGs can be embedded in a constraint-based representation.
---------------------------------------------------
E95-1017:3	55:183	Although it is still used for linguistic description (e.g. Bouma and van Noord, 1994), it has been somewhat overshadowed in recent years by HPSG (Pollard and Sag 1994), and by Lambek Categorial Grammars (Lambek 1958).
---------------------------------------------------
P95-1014:4	14:198	2 Lexical rules in Categorial Grammar This section reviews Bouma and van Noord's (1994) (BN henceforth) constraint-based categorial grammar analysis of modification in Dutch, which we use as our primary example in this paper.
---------------------------------------------------
P95-1014:5	3:198	Prolog code for a simple application of our technique to Bouma and van Noord's (1994) categorial grammar analysis of Dutch is provided.
---------------------------------------------------
P95-1010:6	116:123	For example, Bouma and van Noord (1994) show that assuming that heads subcategorize for adjuncts (rather than the other way around, as is standard) permits a particularly elegant account of the double infinitive construction in Dutch.
---------------------------------------------------
W97-1513:7	85:168	 Constraint-based Categorial Grammar, with delayed evaluation of constraints (Bouma and van Noord, 1994).
---------------------------------------------------
W97-1513:8	20:168	The flexibility is illustrated by the fact that Hdrug has been used both for the development of grammars and parsers for practical systems (Boves et al. , 1995; van Noord et al. , 1996), but also as a tool to experiment with new theoretical notions and alternative processing strategies, such as those discussed by (Carpenter, 1992), (van Noord and Bouma, 1994), (van Noord, 1994).
---------------------------------------------------
W97-1513:9	86:168	 HPSG with lexical rules as delayed constraints (van Noord and Bouma, 1994).
---------------------------------------------------
J99-4002:10	65:580	Bouma and van Noord (1994) and Johnson and Dorre (1995) propose techniques for delayed evaluation of lexical rules so that they apply "on demand" at parse time.
---------------------------------------------------
J99-4002:11	13:580	Recently, Bouma and van Noord (1994) have proposed a lexical rule of Adjunct Introduction, which can recursively add adverbial categories to the SUBCAT list of a verbal category.
---------------------------------------------------
J99-4002:12	544:580	A rule such as Adjunct Introduction (Bouma and van Noord 1994), which adds adjunct categories to the SUBCAT lists of verb entries recursively creating a potentially infinite set of derived entries, seems to us to be a clear example of a nonlexical unary syntactic rule.
---------------------------------------------------
W96-0303:13	7:172	For example, Bouma & van Noord (1994) and Johnson & Dorre (1995) propose techniques for delayed evaluation of lexical rules so that they apply 'on demand' at parse time.
---------------------------------------------------
