This approach improves upon earlier work on discourse structure such as (Lascarides and Asher, 1991) and (Kehler, 1994) in reducing the number of possible ambiguities; it is also more precise than the Kamp/Hinrichs/Partee approach in that it takes into account ways in which the apparent defaults can be overridden and differentiates between events and activities, which behave differently in narrative progression.


As Kehler (1994) points out, if forward movement of time is considered a default with consecutive event sentences, then the use of "because" in (5) should cause a temporal clash-whereas it is perfectly felicitous.


