Our method is based on a decision list proposed by Yarowsky (Yarowsky, 1994; Yarowsky, 1995). 
Yarowsky (1994) notes that conceptual spelling correction is part of a closely related class of problems which include word sense disambiguation, word choice selection in machine translation, and accent and capitalization restoration. 
Yarowsky (1994) defined a basic set of features that has been widely used (with some variations) by other WSD systems. 
A supervised algorithm based on this property is given in (Yarowsky, 1994). 
As a statistical learning method, we employ the decision list learning method of Yarowsky (1994). 
