Discourse units range from referring expressions and syntactic constructions (Fox 1987; Kroch and Hindle 1982; Prince 1985), to words or phrases (Heeman and Allen 1994; Hirschberg and Litman 1993; Novick and Sutton 1994), to utterances and relationships among them (Dahlback 1991; Reithinger and Maier 1995; Moser and Moore 1995; Nagata 1992; Rose et al. 1995), to multiutterance units identified by a range of criteria such as speaker intention or initiative (Flammia and Zue 1995a; Hirschberg and Nakatani 1996; Whittaker and Stenton 1988).


Dialogue grammars have previously been used to manage dialogue (Bunt, 1989; Bilange, 1991; Traum and Hinkelman, 1992; JSnsson, 1993; Mast et al. , 1994; Novick and Sutton, 1994; Chino and Tsuboi, 1996), but we are not aware of an approach where speech acts are translated into a collection of primitives with propositional content.


Acknowledgments also play a role in managing turn-taking in mixed-initiative dialogue; although acknowledgments may preface a new contribution by the same speaker (Novick & Sutton, 1994), often they occur alone as a single-phrase turn that appears to serve the purpose of explicitly declining an opportunity to take a turn (Sacks et al, 1974).


