The first sentence alignment model used to align English-Chinese bilingual texts is proposed by Wu (1994). 
We have been using a lexicon that was automatically learned from the HKUST English-Chinese Parallel Bilingual Corpus via statistical sentence alignment (Wu 1994) and statistical Chinese word and collocation extraction (Fung and Wu 1994; Wu and Fung 1994), followed by an EM word-translation-learning procedure (Wu and Xia 1994). 
The text, drawn from the HKUST English-Chinese Parallel Bilingual Corpus (Wu 1994), consists of transcripts from the parliamentary proceedings of the Hong Kong Legislative Council. 
E-mail: dekai@cs.ust.hk  1997 Association for Computational Linguistics Computational Linguistics Volume 23, Number 3 Fung and Church 1994; Wu and Xia 1994; Fung and McKeown 1994). 
However, current sentence alignment models, (Brown et al 1991; Gale & Church 1991; Wu 1994; Chen 489 1993; Zhao and Vogel, 2002; etc). 
