6 Acknowledgements This work was supported by  The Commission of the European Communities through the project LRE-61-061 "Reusable Gratnmatical Resources", where it has been (ab-)used in creative ways to prototype extensions for the ALEP formalism such as set descriptions, linear precedence constraints and guarded constraints (Manandhat, 1994; Manandhar, 1995).


Constraint Programming (CP) has been used in computational linguislics in several areas, for example in (typed) featut'e-lmsed systems (Smolka, 1995), or condio tional constraints (Matiasek, 1994), or adwmccd compilation techniques (G6tz and Meurcrs, 1997) or specialized constraint solvers (Manandhar, 1994).


In paxticulax subset constraints (Manandhar, 1994) are employed to construct larger domains from smaller ones.


