Others use various linguistic information (Simard et al. , 1992 ; Papageorgiou et al. , 1994).


The method proposed in (Debili and Sammouda, 1992) is based on the preliminary alignment of words using a conventional bilingual lexicon and the method described in (Papageorgiou et al. , 1994) added grammatical labeling based on the assumption that the same parts of speech tend to be employed in the translation.


A number of automatic sentence alignment techniques have been proposed (Kay and Rscheisen, 1993; Gale and Church, 1991; Brown et al. , 1991; Debili and Samouda, 1992; Papageorgiou et al. , 1994; Gaussier, 1995; Melamed, 1996; Fluhr et al. , 2000).


