We leave incorporating a more sophisticated response understanding model, such as (Green and Carberry, 1994), into our system for future work.


However, as discussed in (Green and Carberry, 1994; Hockey et al., 1997), respouses to yes-no questions may not explicitly contain a yes or no term.


To understand conversationM implicatures associated with indirect replies one must consider discourse expectations, discourse plans, and discourse relations (Green, 1992; Green and Carberry, 1994).


However, as discussed in Green and Carberry, (1994) and Hockey et al.


We leave incorporating a more sophisticated response understanding model, such as Green and Carberry (1994), into our system for future work.


