For arguments requiring a non-canonical order, we need type shifting and composition (hence the third clause in (7)): 3As suggested in (Bozsahin and Gocmen, 1995), morphological and syntactic composition can be distinguished by associating several attachment calculi with functors and arguments (e.g., affixation, concatenation, clitics, etc.) NPa:x T (SINP1)/(SINPIINPa):Tx ~ (SINP1 INP2)/(SINPt \[NP3 INP2): B (Tx) = BBTx Once syntactic category of the argument is fixed, its semantics is uniquely determined by (7).


