A parser is often unable to analyze long sentences owing to their complexity, though they have no grammatical errors (Nasukawa, 1995).


Furthermore, by assuming dis('ourse I)reference, namely, a tendency for each word to modify or be modified by similar words within a discourse, structural infornmtion on all other words with the same lemma within the discourse 1)rovides clue for determining the modifiees of structurally mnl)iguous 1)hrases (Nasukawa and Uramoto, 1995).


