In this method, the decision list (DL) learning algorithm (Yarowsky, 1995) is used. 
(Yarowsky, 1995) and (Mihalcea and Moldovan, 2001) utilized bootstrapping for word sense disambiguation. 
Yarowsky (1995) used this method for word sense disambiguation. 
Most recently, Yarowsky used an unsupervised learning procedure to perform WSD (Yarowsky, 1995), although this is only tested on disambiguating words into binary, coarse sense distinction. 
One example is the algorithm for word sense disambiguation in (Yarowsky, 1995). 
