Under these circumstances, one may use language-specific heuristics first, before resorting to error-tolerant recognition, along the lines suggested by morphological-analysis-based approaches (Aduriz et al. 1993; Bowden and Kiraz 1995).


More recently, Bowden and Kiraz (1995) have used a multitape morphological analysis technique for spelling correction in Semitic languages which, in addition to insertion, deletion, substitution, and transposition errors, allows for various language-specific errors.


scribe t;he morphology of Syria(: and other Semitic languages, arrd by (Bowden an(t Kiraz, 1995) for error dete(',tion in noncon(:atenative strings.


addresses various issues in the domain of non-linear morphology: It has been used in analysing rootand-pattern morphology (Kiraz, 1994), the Arabic broken plural phenomenon (Kiraz, 1996a), and error detection in non-concatenative strings (Bowden and Kiraz, 1995).


