C08-1032:1	183:184	These features also markedly distinguish XMG from existing formalisms used to encode tree based grammars such as the nonmonotonic encoding of TAG proposed in (Evans et al., 1995) (in contrast, XMG is fully monotonic) and the tree descriptions based approaches proposed in (Candito, 1996; Xia et al., 1998) where in particular, tree descriptions can only be conjoined (not disjoined) and where identification across tree fragments is restricted to nodes.
---------------------------------------------------
P95-1008:2	12:163	In more recent work, the language has been used to provide a concise encoding of Lexicalised Tree Adjoining Grammar (Evans et al. , 1994; Evans et al. , 1995).
---------------------------------------------------
C96-2109:3	12:145	In more recent work, DATR has been used to provide a concise, inheritance-based encoding of Lexiealized Tree Adjoining Grammar (Evans et al. , 1995).
---------------------------------------------------
E99-1029:4	22:142	However, the problem of grammar size in TAG has to some extent been addressed both with respect to grammar encoding (Evans et al. , 1995; Candito, 1996) and parsing (Joshi and Srinivas, 1994; Evans and Weir, 1998).
---------------------------------------------------
C02-1153:5	18:188	Several approaches have been proposed in the literature describing compact representations methods for LTAGs, perhaps the best known being (VijayShanker and Schabes, 1992), (Candito, 1996; Candito, 1998), (Evans et al. , 1995; Evans et al. , 2000), (Xia et al. , 1998; Xia, 2001), and (Becker, 1993; Becker, 1994; Becker, 2000).
---------------------------------------------------
C02-1153:6	181:188	For LTAGs, in particular, there has been quite a few proposals, as we have already mentioned (Vijay-Shanker and Schabes, 1992; Becker, 1993; Candito, 1996; Evans et al. , 1995; Xia, 2001), and even large-scale grammars built with them, e.g., the French grammar in (Abeille and Candito, 2000) and an English one in (Xia, 2001).
---------------------------------------------------
W98-0507:7	36:216	Hierarchical representations of LTAG have been proposed: (VijayShanker and Schabes, 1992), (Becker, 1993), (Evans et al. , 1995), (Candito, 1996), (Doran et al. , 1997).
---------------------------------------------------
P06-2032:8	6:183	The tree fragment approach is advocated in (Evans et al. , 1995) which proposes to encode lexicalised TAGs using the DATR representation language1.
---------------------------------------------------
