Although asymptotically faster methods can be constructed, as discussed in (Rajasekaran and Yooseph, 1995), these methods are not of practical interest, due to large hidden constants.


Surprisingly, it has been claimed by Schabes and Waters (1995) that this property is problematic for the mildly contextsensitive languages represented by tree-adjoining grammars (TAGs): the best practical parsing algorithms for TAGs have time complexity Cg(n 6) (Vijay-Shankar and Joshi \[1985\]; see Satta \[1994\] and Rajasekaran and Yooseph \[1995\] for lower theoretical upper bounds), whereas the only published algorithm with the correct-prefix property--that by Schabes and Joshi (1988)--has complexity O(n9).


Then there are V + 1 parameters associated with node 1The best theoretical upper bound on time complexity for the recognition of Tree Adjoining Languages is O(M(n2)), where M(k) is the time needed to multiply two k x k boolean matrices.(Rajasekaran and Yooseph, 1995) 558 E|ementtt T Tt. Sets: t tnlt twrd l twrd 2 twrd n X word I X word 2 X word E * * , n Figure 1: A set of elementary LTIG trees that represent a bigram grammar.


