There are techniques for analyzing agreement when annotations involve segment boundaries (Litman and Passonneau 1995; Marcu, Romera, and Amorortu 1999), but our focus in this article is on words. 
Indeed, there is a risk that the automatically derived list of cue phrases could be too specific to the word usage in 9As in (Litman and Passonneau, 1995), we restrict ourselves to the first lexical item of any utterance, plus the second one if the first item is also a cue word. 
Litman and Passonneau (1995) addressed the usefulness of a "multiple knowledge source" in human and automatic discourse segmentation. 
However, in later work (Litman and Passonneau 1995), three out of seven judges marking a boundary was considered sufficient to classify, that point as a "major" boundary. 
6.2 Agreement Among Taggers There are techniques for analyzing agreement when annotations involve segment boundaries (Litman and Passonneau, 1995;; Marcu et al. , 1999), but our focus in this paper is on words. 
