For this preprocessing of the HPSG grammar, we adapted the 'HPSG to TAG compilation' process described in \[Kasper et al. 1995\]. 
The idea of supertagging can also be applied to a grammar in HPSG formalism indirectl~ by compiling the HPSG grammar into an LTAG grammar (Kasper et al. 1995). 
Kasper c.t al. 1)resented an idea similar to this @line raising in their work on HPSG-TAG compiler(Kasper et al. , 1995). 
Other works (Kasper et al. , 1995; Becker and Lopez, 2000) convert HPSG grammars into LTAG grammars. 
(1993), Roche (1993), Grishman (1995), Hobbs et al. 
