(Viegas et al., 1996) used derivational lexical rules to extend a Spanish lexicon. 
We find less antithetical to our viewpoint the emphasis on the computational value of lexical rules (Viegas et al. , 1996) and on ellipsis recovery as triggered by syntactic/lexical cues and accomplished through contextual means (Viegas & Nirenburg, 1995). 
Several of the LRs discovered manually in the pilot project turned out to be "large," in the sense of their massive productiveness (see, for instance, Viegas et al. 1996), such as the comparativedegree LR, applicable to every one of the 4,000-plus gradable adjectives. 
Both of these core lexicons can be expanded with lexical rules to contain around 30,000 entries (\[Viegas et al.1996\]). 
Formally, we use the conceptual tool of lexical rules as described in (Viegas et al. , 1996). 
