Alshawi (1996) uses dependency information in a machine translation system. 
Schemes like (Alshawi, 1996) tacitly make this approximation. 
The model is a probabilistic head automaton grammar (Alshawi, 1996) with a split form that renders it parseable in cubic time (Eisner, 1997). 
2 Overview 2.1 Lexlcal head transducers In our training method, we follow tile simple lexical head transduction model described by Alshawi (1996b) which can be regarded as a type of .~ta.tistical dependency gra.ntmar trans41 duction. 
Early examples of this work include (Alshawi, 1996; Wu, 1997); more recent models include (Yamada and Knight, 2001; Eisner, 2003; Melamed, 2004; Zhang and Gildea, 2005; Chiang, 2005; Quirk et al., 2005; Marcu et al., 2006; Zollmann and Venugopal, 2006; Nesson et al., 2006; Cherry, 2008; Mi et al., 2008; Shen et al., 2008). 
