Strube (1996)). 
Our own work on the centering model 1 (Strube and Hahn 1996; Hahn and Strube 1996) brings in evidence from German, a free-word-order language in which grammatical role information is far less predictive of the organization of centers than for fixed-word-order languages such as English. 
The ordering constraints we supply account for all of the above mentioned types of anaphora in a precise way, including (pro)nominal anaphora (Strube & Hahn, 1995; Hahn & Strube, 1996). 
1 This article is an extended and revised version of our contribution to the 1996 Annual Meeting of the Association for Computational Linguistics (Strube and Hahn 1996). 
We use an approach as described by Strube (1996) for the evaluation. 
