The rules and lexiea samples reproduced here are based on a larger morphological grammar written for the SemHe implementation (a multitape two-level system) for a full description of the system, see (Kiraz, 1996c; Kiraz, 1996b). 
This work departs from two-level morphology, which has been at the center of computational morphology since the implementation of URKIMMO (Koskenniemi 1983) and was applied to Arabic morphology first by Kay (1987), then by Beesley (1989, 1996), Kiraz (1994, 1996a) and to Syriac morphology by Kiraz (1996b). 
The interpretation of the latter condition is based on Grimley-Evans, Kiraz, and Pulman (1996). 
For example, the Syriac grammar reported in (Kiraz, 1996) contains 48 rules. 
Although particularly suited to concatenative morphology, this approach has been extended to other types of morphologies, and more precisely to templatic morphology first by Kay (1987), then by Beesley (1991,1996) and Kiraz (1994, 1996) among others. 
