For NLP finite state calculi (Karttunen et al. , 1996; van Noord, 1997) this is unacceptable. 
Backreferencing has been implicit in previous research, such as in the "batch rules" of Kaplan and Kay (1994), bracketing transducers for finite-state parsing (Karttunen, 1996), and the "LocalExtension" operation of Roche and Schabes (1995). 
The major components of the algorithm are not new, but straightforward modifications of components presented in Karttunen (1996) and Mohri and Sproat (1996). 
Improvements and extensions to this algorithm have been provided by Karttunen (1995), Karttunen (1997), Karttunen (1996) and Mohri and Sproat (1996). 
These transducers are compiled from regular expressions that use finite-state calculus operators, mainly the Replace operators (Karttunen, 1996). 
