As shown in (Minnen, 1996) *The presented research was carried out at the University of Tfibingen, Germany, as part of the Sonderforschungsbereich 340.


Magic templates introduce top-down filtering into the search strategy and can be used to derive Earleys algorithm (Minnen, 1996), to introduce left-corner filters, and to restrict FSM constructions to build only accessible states.


Our approach may be most closely related to deductive databases, which even in their heyday were apparently ignored by the CL community (except for Minnen, 1996).


