The proposed extension of the centering model builds on the methodological framework of functional centering (Strube & Hahn, 1996). 
Strube and Hahn 1996)? 
The result is as follows: UI : Cb f a, Cp = a U2:Cb=a, Cp=b U3 : Cb f b, Cp = b U4 : Cb = b, Cp = b In terms of the conventional transitions this works out as U~/U2: RET^IN U2/U3: SMOOTH SHIFT us/u~: COnTINUa This is consistent with Strube and Hahn's (1996) observation that "a II~rAIN transition ideally predicts a SMOOTH ssw'r in the following utterance". 
Strube & Hahn (1996) use the centering data structures to redefine Dane~'s trichotomy between given information, theme and rheme in terms of the centering model. 
Strube and Hahn (1996) developed a heuristic of ranking transition pairs by cost to evaluate different Cf-ranking schemes. 
