Our presentation relies on definitions from (Nederhof and Satta, 1996).


This is an experimental implementation of a generalization for Definite Clause Grammars of the parser described in Nederhof and Satta (1996).


First, construction of an LR automaton, of which the size is exponential in the size of the grammar, may be a prohibitively expensive task (Nederhof and Satta 1996).


See also a related formulation of tabular LR parsing by (Nederhof and Satta, 1996).


