Our algorithm is based on Goodmans (1996) labelled recall algorithm for the phrase-structure PARSEVAL measures. 
The orthogonal technique of minimum Bayes risk decoding has achieved gains on parsing (Goodman, 1996) and machine translation (Kumar and Byrne, 2004). 
In parsing, Goodman (1996) developed parsing algorithms that are appropriate for specific parsing metrics. 
While the most probable parse problem is NP-complete (Simaan, 1992), several approximate methods exist, including n-best reranking by parse likelihood, the labeled bracket algorithm of Goodman (1996), and a variational approximation introduced in Matsuzaki et al. 
This procedure is equivalent to minimum Bayes risk (MBR) parsing (Goodman, 1996) with a dependency accuracy loss function. 
