3 For this case, and for many other types of restrictions currently handled by conditions, more elegant solutions are available using the "sorted" and "colored" versions of higher-order unification developed by Michael Kohlhase and colleagues (Gardent and Kohlhase 1996b, 1997; Gardent Kohlhase, and van Leusen 1996; Gardent, Kohlhase, and Konrad 1999).


For a proposal on how to solve this over-generation problem, see (Gardent and Kohlhase, 1996b; Gardent et al. , 1999).


Only few methodological proposals for semantic computations were made since then (e.g. , higherorder colored unification as a mechanism to avoid over-generation inherent to unconstrained higherorder unification (Gardent and Kohlhase, 1996)).


