There have been considerable amount of efforts to improve the reordering model in SMT systems, ranging from the fundamental distance-based distortion model (Och and Ney, 2004; Koehn et al. , 2003), flat reordering model (Wu, 1996; Zens et al. , 2004; Kumar et al. , 2005), to lexicalized reordering model (Tillmann, 2004; Kumar et al. , 2005; Koehn et al. , 2005), hierarchical phrase-based model (Chiang, 2005), and maximum entropy-based phrase reordering model (Xiong et al. , 2006). 
Another approach to statistical machine translation using DP was presented in (Wu, 1996). 
(Wu, 1996) formulates a DP search for stochastic bracketing transduction grammars. 
3 The Model Following Wu (1996) and Xiong et al. 
Another simple model is flat reordering model (Wu, 1996; Zens et al. , 2004; Kumar et al. , 2005) which is not content dependent either. 
