W98-0720:1	12:176	Following the lessons learned from the WordNetbased inference of Gricean implicatures, reported in (Harabagiu et al. , 1996), a novel methodology of producing metonymic paths was devised.
---------------------------------------------------
W98-0720:2	71:176	The interpretation of this prepositional relation is produced when it is matched against WordNetbased classes of prepositional attachments collected from large treebanks, following the methodology described in (Harabagiu, 1996).
---------------------------------------------------
