These methods can be extended slightly to include the compilation of probabilistic or weighted rules into weighted finitestate-transducers (WFSTs -see (Pereira et al. , 1994)): Mohri and Sproat (1996) describe a rulecompilation algorithm which is more efficient than the Kaplan-Kay algorithm, and which has been extended to handle weighted rules. 
There is no reason to believe that our multitiered rewrite rules component cannot be applied to other rewrite rules systems (Koskenniemi 1983; Kaplan and Kay 1994; Mohri and Sproat 1996; Karttunen 1997). 
Improvements and extensions to this algorithm have been provided by Karttunen (1995), Karttunen (1997), Karttunen (1996) and Mohri and Sproat (1996). 
These observations can be extended to the case of weighted rewrite rules (Mohri and Sproat 1996). 
It should also be borne in mind that the size explosion evident in Table 4 also characterizes rules that are compiled from hand-built rewrite rules (Kaplan and Kay, 1994; Mohri and Sproat, 1996). 
