P98-2231:1	99:140	Here, (1) indicates the performance obtained using the principle of Closest Attachment (Kimball, 1973); (2) shows the performance obtained using the lowest observed class co-occurrence (Weischedel et al. , 1993); (3) is the result from the maximum mutual information over all pairs of classes corresponding to the words in the co-occurrence (Resnik, 1993; Alves, 1996); and (4) shows the performance of our method 7.
---------------------------------------------------
P98-2231:2	125:140	SAs another way of reducing the sparse data problem, we clustered prepositions using the method described in "~Vu and Furugori (1996).
---------------------------------------------------
