have + + march, paint + + destroy + notice, win Table 2: Privative Featural Identification of Aspectual Classes (Dorr and Jones, 1996; Dorr, To appear) and assigned LCS templates from a database built as Lisplike structures (Dorr, 1997).


Other researchers have proposed corpusbased approaches to acquiring lexical aspect information with varying data coverage: Klavans and Chodorow (1992) focus on the event-state distinction in verbs and predicates; Light (1996) considers the aspectual properties of verbs and affixes; and McKeown and Siegel (1996) describe an algorithm for classifying sentences according to lexical aspect.


This research is close in spirit to the work of Light (1996) on classifying the semantics of derivational affixes, and Siegel and McKeown (2000) on learning verb aspect.


Other lexical semantic features such telicity, sentience and changeof-state can also be induced from morphological cues (Light, 1996).


