W06-1320:1	9:156	Since it is elusive what mental representations humans use in order to distinguish a coherent text, different surface markers (Hirschberg and Nakatani, 1996; Passonneau and Litman, 1997) and external knowledge sources (Kozima and Furugori, 1994) have been exploited for the purpose of automatic thematic segmentation.
---------------------------------------------------
J01-1002:2	59:426	Major shifts in topic typically show longer pauses, an extra-high F0 onset or "reset," a higher maximum accent peak, greater range in F0 and intensity (Brown, Currie, and Kenworthy 1980; Grosz and Hirschberg 1992; Nakajima and Allen 1993; Geluykens and Swerts 1993; Ayers 1994; Hirschberg and Nakatani 1996; Nakajima and Tsukada 1997; Swerts 1997) and shifts in speaking rate (Brubaker 1972; Koopmans-van geinum and van Donzel 1996; Hirschberg and Nakatani 1996).
---------------------------------------------------
J97-1005:3	654:736	For example, using a threshold of seven subjects yields the set of consensus boundaries, as defined in Hirschberg and Nakatani (1996).
---------------------------------------------------
J97-1005:4	101:736	Similar results are reported in Nakatani, Hirschberg, and Grosz (1995) and Hirschberg and Nakatani (1996) for spontaneous speech as well.
---------------------------------------------------
J97-1005:5	97:736	The types of linguistic features investigated indude prosody (Grosz and Hirschberg 1992; Nakatani, Hirschberg, and Grosz 1995; Hirschberg and Nakatani 1996; Swerts 1995; Swerts and Ostendorf 1995), term repetition (Hearst 1994), cue words (Moser and Moore 1995; Whittaker and Stenton 1988), and discourse anaphora (Walker and Whittaker 1990).
---------------------------------------------------
J97-1005:6	61:736	In Hirschberg and Nakatani (1996), average reliability (measured using the kappa coefficient discussed in Carletta \[1996\]) of segmentinitial labels among 3 coders on 9 monologues produced by the same speaker, labeled using text and speech, is.8 or above for both read and spontaneous speech; values of at least .8 are typically viewed as representing high reliability (see Section 3.2).
---------------------------------------------------
J97-1005:7	59:736	Several studies have used trained coders to locally and globally structure spontaneous or read speech using the model of Grosz and Sidner (1986), including Grosz and Hirschberg 1992; Nakatani, Hirschberg, and Grosz 1995; Stifleman 1995; Hirschberg and Nakatani 1996.
---------------------------------------------------
J97-1005:8	488:736	Other studies have shown that when both speech and text are available to labelers, segmentation is clearer (Swerts 1995) and reliability improves (Hirschberg and Nakatani 1996).
---------------------------------------------------
W97-0601:9	156:212	Preliminary studies indicate that reliability for human tagging is higher for AVM attribute tagging than for other types of discourse segment tagging (Passonneau and Litman, 1997; Hirschberg and Nakatani, 1996).
---------------------------------------------------
W06-0607:10	180:213	Speech was found to improve inter-annotator agreement in discourse segmentation of monologs (Hirschberg and Nakatani 1996).
---------------------------------------------------
P99-1049:11	237:251	Hirschberg and Nakatani (1996) showed that prosodic information helps human discourse segmentation.
---------------------------------------------------
J97-1003:12	153:581	The work described here makes use only of lexical distribution information, in lieu of prosodic cues such as intonational pitch, pause, and duration (Hirschberg and Nakatani 1996), discourse markers such as oh, well, ok, however (Schiffrin 1987; Litman and Passonneau 1995), pronoun reference resolution (Passonneau and Litman 1993; Webber 1988) and tense and aspect (Webber 1987; Hwang and Schubert 1992).
---------------------------------------------------
J97-1003:13	398:581	Proposals have recently been made for protocols for the collection of human discourse segmentation data (Nakatani et al. 1995) and for how to evaluate the validity of judgments so obtained (Carletta 1996; Isard and Carletta 1995; Ros6 1995; Passonneau and Litman 1993; Litman and Passonneau 1995).
---------------------------------------------------
J97-1003:14	399:581	Recently, Hirschberg 52 Hearst TextTiling and Nakatani (1996) have reported promising results for obtaining higher interjudge agreement using their collection protocols.
---------------------------------------------------
C04-1020:15	23:199	2.1 Discourse segments Discourse segments can be defined as nonoverlapping spans of prosodic units (Hirschberg & Nakatani, 1996), intentional units (Grosz & Sidner, 1986), phrasal units (Lascarides & Asher, 1993), or sentences (Hobbs, 1985).
---------------------------------------------------
W97-0320:16	76:311	A ~ value of 0.8 or greater indicates a high level of reliability among raters, with values between 0.67 and 0.8 indicating only moderate agreement (Hirschberg ~ Nakatani 1996; Carletta 1996).
---------------------------------------------------
W97-0320:17	63:311	As in much recent empirical work in discourse processing (e.g. , Arhenberg et al. 1995; Isard & Carletta 1995; Litman & Passonneau 1995; Moser & Moore 1995; Hirschberg & Nakatani 1996), we performed an intercoder reliability study investigating agreement in annotating the times.
---------------------------------------------------
W97-0320:18	65:311	Passonneau & Litman 1993, Condon & Cech 1995, and Hirschberg & Nakatani 1996), where reliability is measured in terms of the amount of agreement among annotators.
---------------------------------------------------
P07-1046:19	233:259	Average (standard deviation) for objective metrics in the first problem 6 Related work Discourse structure has been successfully used in non-interactive settings (e.g. understanding specific lexical and prosodic phenomena (Hirschberg and Nakatani, 1996), natural language generation (Hovy, 1993), essay scoring (Higgins et al. , 2004) as well as in interactive settings (e.g. predictive/generative models of postural shifts (Cassell et al. , 2001), generation/interpretation of anaphoric expressions (Allen et al. , 2001), performance modeling (Rotaru and Litman, 2006)).
---------------------------------------------------
J05-2005:20	42:651	Whereas some argue that discourse segments should be prosodic units (Hirschberg and Nakatani 1996), others argue for intentional units (Grosz and Sidner 1986), phrasal units (Lascarides and Asher 1993; Longacre 1983; Webber et al. 1999), or sentences (Hobbs 1985).
---------------------------------------------------
P03-1071:21	129:177	Silences: previous work has found that major shifts in topic typically show longer silences (Passonneau and Litman, 1993; Hirschberg and Nakatani, 1996).
---------------------------------------------------
P03-1071:22	26:177	In work on segmentation of spoken documents, intonational, prosodic, and acoustic indicators are used to detect topic boundaries (Grosz and Hirschberg, 1992; Nakatani et al. , 1995; Hirschberg and Nakatani, 1996; Passonneau and Litman, 1997; Hirschberg and Nakatani, 1998; Beeferman et al. , 1999; Tur et al. , 2001).
---------------------------------------------------
W97-0210:23	6:170	Recent work in this vein includes identification of lexical constraints from textual tutorial dialogue (Moser and Moore, 1995), constraints on illocutionary act type from spoken task-oriented dialogue (Allen et al. , 1995), prosodic constraints from spoken information-seeking monologues (Hirschberg and Nakatani, 1996), and constraints on referring expressions from spoken narrative monologue (Passonneau, 1996).
---------------------------------------------------
P07-1128:24	26:162	Other prosodic cues (e.g. , pitch contour, energy) have been studied for their correlation with story segments in read speech (Tur et al. , 2001; Levow, 2004; Christensen et al. , 2005) and with theory-based discourse segments in spontaneous speech (e.g. , directiongiven monologue) (Hirschberg and Nakatani, 1996).
---------------------------------------------------
N07-1001:25	22:201	We report results on the Boston University (BU) Radio Speech Corpus (Ostendorf et al. , 1995) and Boston Directions Corpus (BDC) (Hirschberg and Nakatani, 1996), two publicly available speech corpora with manual ToBI annotations intended for experiments in automatic prosody labeling.
---------------------------------------------------
N07-1001:26	46:201	Prosody labeling on spontaneous speech corpora like Boston Directions corpus (BDC), Switchboard (SWBD) has garnered attention in (Hirschberg and Nakatani, 1996; Gregory and Altun, 2004).
---------------------------------------------------
W06-1611:27	13:230	The discourse structure hierarchy has been shown to be useful for other tasks: understanding specific lexical and prosodic phenomena (Hirschberg and Nakatani, 1996; Levow, 2004), natural language generation (Hovy, 1993), predictive/generative models of postural shifts (Cassell et al. , 2001), and essay scoring (Higgins et al. , 2004).
---------------------------------------------------
W06-1611:28	80:230	Also, while a human annotation of the discourse structure will be more complex but more time consuming (Hirschberg and Nakatani, 1996; Levow, 2004), its advantages are outweighed by the automatic nature of our discourse structure annotation.
---------------------------------------------------
W00-1005:29	19:177	Swerts 1997, Nakatani et al 1995, Hirchberg & Nakatani 1996).
---------------------------------------------------
J97-1001:30	54:165	For example, this method has been used to identify features for predicting accent assignment in text-tospeech (Hirschberg 1993), for repairing disfluencies (Nakatani and Hirschberg 1993), cue vs. noncue uses of discourse cue words (Litman 1996; Siegel and McKeown 1994), discourse segment boundaries (Grosz and Hirschberg 1992; Passonneau and Litman, this volume), intonational phrase boundaries (Wang and Hirschberg 1992), and the Computational Linguistics Volume 23, Number 1 most likely antecedents for anaphors (Aone and Bennet 1995; Connolly, Burger, and Day 1994).
---------------------------------------------------
J97-1001:31	36:165	Discourse units range from referring expressions and syntactic constructions (Fox 1987; Kroch and Hindle 1982; Prince 1985), to words or phrases (Heeman and Allen 1994; Hirschberg and Litman 1993; Novick and Sutton 1994), to utterances and relationships among them (Dahlback 1991; Reithinger and Maier 1995; Moser and Moore 1995; Nagata 1992; Rose et al. 1995), to multiutterance units identified by a range of criteria such as speaker intention or initiative (Flammia and Zue 1995a; Hirschberg and Nakatani 1996; Whittaker and Stenton 1988).
---------------------------------------------------
J97-1001:32	120:165	Generalizations of this work arise from other research on different speech genres In different environments that also found that coreferential relationships, pausing, and intonation are correlated with discourse structure (Cahn 1992; Fox 1987; Hirschberg and Nakatani 1996).
---------------------------------------------------
J97-1001:33	105:165	Future work could test further generalizations; term repetition may also indicate subtopics in other discourse or dialogue environments, and may interact with other features that correlate with topic boundaries, such as pauses, intonation, or cue words (Cahn 1992; Hirschberg and Nakatani 1996).
---------------------------------------------------
C08-1129:34	144:215	(Nakajima and Allen, 1993; Hirschberg and Nakatani, 1996)).
---------------------------------------------------
C08-1129:35	65:215	In spontaneous monologue, Butterworth (1972) found that the beginning of a discourse segment exhibited slower speaking rate; Swerts (1995), and Passonneau and Litman (1997) found that pause length correlates with discourse segment boundaries; Hirschberg and Nakatani (1996) found that the beginning of a discourse segment correlates with higher pitch.
---------------------------------------------------
P98-2155:36	85:155	Expert discourse structure analyses are used to derive CONSENSUS SEGMENTATIONS, consisting of discourse boundaries whose coding all three labelers agreed upon (Hirschberg and Nakatani, 1996).
---------------------------------------------------
W06-1612:37	16:186	Since it correlates with word order and pitch accent (Lambrecht, 1994; Hirschberg and Nakatani, 1996), for instance, incorporating knowledge on information status would be helpful for natural language generation, and in particular text-tospeech systems.
---------------------------------------------------
P07-1064:38	209:217	Multiple studies of discourse structure, however, have shown that prosodic cues are highly predictive of changes in topic structure (Hirschberg and Nakatani, 1996; Shriberg et al. , 2000).
---------------------------------------------------
P07-1064:39	40:217	In parallel, researchers extensively study the relationship between discourse structure and intonational variation (Hirschberg and Nakatani, 1996; Shriberg et al. , 2000).
---------------------------------------------------
P97-1035:40	128:328	Preliminary studies indicate that reliability for human tagging is higher for AVM attribute tagging than for other types of discourse segment tagging (Passonneau and Litman, 1997; Hirschberg and Nakatani, 1996).
---------------------------------------------------
P04-1049:41	67:207	3.1 Representing coherence structures 3.1.1 Discourse segments Discourse segments can be defined as nonoverlapping spans of prosodic units (Hirschberg & Nakatani (1996)), intentional units (Grosz & Sidner (1986)), phrasal units (Lascarides & Asher (1993)), or sentences (Hobbs (1985)).
---------------------------------------------------
C96-1001:42	22:26	It will then tbcus on a new corpus of directiongiving monologues, the Boston Directions Corpus (Nakatani et al. , 1995a; Hirschberg and Nakatani, 1996).
---------------------------------------------------
J02-1002:43	18:283	Sometimes segmentation is done at the clause level, for the purposes of detecting nuances of dialogue structure or for more sophisticated discourse-processing purposes (Morris and Hirst 1991; Passonneau and Litman 1993; Litman and Passonneau 1995; Hirschberg and Nakatani 1996; Marcu 2000).
---------------------------------------------------
W99-0313:44	160:187	Following the methodology in (ttirschberg and Nakatani, 1996), we measured the reliability of coding for a linearized version of the IU tree, by calculating the reliability of coding of IU beginnings using the kappa metric.
---------------------------------------------------
W04-2323:45	48:226	2.1 Flat vs. Hierarchical Approaches Most previous work that has combined multiple annotations has used linear segmentations, i.e. discourse segmentations without hierarchies (Hirschberg and Nakatani, 1996).
---------------------------------------------------
W04-2323:46	19:226	Other attempts have had more success using improved annotation tools and more precise instructions (Grosz and Hirschberg, 1992; Hirschberg and Nakatani, 1996).
---------------------------------------------------
W04-2323:47	14:226	Indeed, much of the work on automatic recognition of discourse structure has focused on linear, rather than hierarchical segmentation (Hearst, 1997; Hirschberg and Nakatani, 1996), because of the difficulties of obtaining consistent hierarchical annotations.
---------------------------------------------------
W04-2323:48	60:226	F H I J KA B C D E G M L Flat GS1 2 3 Full GS Figure 2: An example where FullCNS and FlatCNS create different gold standards proach (Hirschberg and Nakatani, 1996).
---------------------------------------------------
