Second, we show how the underspecified semantic interpretation approach developed in Genabith and Crouch (1997) can be exploited to interface f-structure representations directly with the named semantic-based transfer approach.


It turns out that there are important structural similarities between f-structures and UDRSs: f-structures can be "read" as UDRSs and hence be assigned an underspecified truth-conditional interpretation (Genabith and Crouch, 1997).


There are some similarities between the UDRS and the glue language approaches, as detailed in Crouch and van Genabith (1997).


