We obtained a list of achievement verbs from the LCS lexicon of (Dorr and Olsen 1997) 3 . Achievements can be marked as having durations of PTXS, i.e., an unspecified number of seconds.


Following the model of (Dorr and Olsen, 1997), each Levin+ class is associated with a thematic grid (henceforth abbreviated a6 -grid), which summarizes a verbs syntactic behavior by specifying its predicate argument structure.


LCS rePresentations also include temporal information, where available in the source language: recent revisions include, for example (Dorr and Olsen, 1997a) standardizing LCS representations for the aspectual (un)boundedness ((A)TELICITY) of events, either lexically or sententially represented.


(Dorr and Olsen, 1997b) \[156\]).


