In our full model, we add three variables to account for the correction of speech repairs (Heeman and Allen, 1997b; Heeman, 1997). 
They use intonation (Wang and Hirschberg, 1992; Traum and Heeman, 1997; Heeman and Allen, 1997) and probabilistic language models (Stolcke et al. , 1998; Ramaswamy and Kleindienst, 1998; Cettolo and Falavigna, 1998). 
We introduce null tokens between each pair of words ~./)i-1 and wi (Heeman and Allen, 1997b), which will be tagged as to the occurrence of these events. 
Heeman and Allen (1997) has shown that doing so also aids in identifying speech repairs and intonational boundaries in spontaneous speech. 
The fourth column reports the results using the full model, which accounts for interactions with speech repairs and the benefit of using silence information (Heeman and Allen, 1997b). 
