Several previous studies have used both a corpus and a machine readable dictionary for WSD (Litkowski, 2002; Rigau et al. , 1997; Stevenson and Wilks, 2001). 
There are also hybrid methods that combine several sources of knowledge such as lexicon information, heuristics, collocations and others (McRoy, 1992) (Bruce and Wiebe, 1994) (Ng and Lee, 1996) (Rigau et al. , 1997). 
Within NLP, ensemble classifiers have been applied, for instance, to genus term disambiguation in machinereadable dictionaries (Rigau et al. , 1997), using a majority voting scheme upon several heuristics, and to part of speech tagging, by combining the class predictions of different algorithms (van Halteren et 177 Levels Full Ac. 
We performed experiments directly on the taxonomies extracted by (Rigau et al. , 1997), as well as on slight variations of them. 
It is true that they have similar context and co-occurrence information when words are used with the same sense (Rigau, et al. , 1997). 
