(1996) Automatic Detection of Omissions in Transaltions, In Proceedings of the 16th International Conference on Computational Linguistics, Copenhagen, Denmark ISLE, International Standards for Language Engineering http://www.ilc.pi.cnr.it/EAGLES96/isle/ISLE _Home_Page.htm J.S. Chang and M. H. Chen (1997) An alignment method for noisy parallel corpora based on image processing techniques, In Proceedings of the 35th Meeting of the Association for Computational Linguistics, Madrid, pp.


