This view is clearly shared by other workers who are actively developing analogical methods for natural language processing tasks (Pirrelli and Federici, 1995; Jones, 1996; Yvon, 1996; 1997; Bagshaw, 1998; Pirrelli and Yvon, 1999).


Also, D&N's claimed results on this pseudoword test set have proved impossible to replicate (Damper and Eastmond 1996, 1997; Yvon 1996; Bagshaw 1998).


The impact of implementational choices on performance has been studied by Sullivan and Damper (1993), Damper and Eastmond (1996, 1997), and Yvon (1996, 1997).


In spite of opinions to the contrary expressed in the literature (see above), there is accumulating evidence that PbA easily outperforms linguistic rewrite rules (Damper and Eastmond 1996, 1997; Yvon 1996; Bagshaw 1998).


