H05-1055:1	14:135	(Knight and Graehl, 1997) proposed a generative transliteration model to transliterate foreign names in Japanese back to English using finite state transducers.
---------------------------------------------------
N09-3011:2	9:108	Both machine translation (Knight and Graehl, 1997) and cross-language information retrieval (Jeong et al., 1999; Virga and Khudanpur, 2003; Abdul-Jaleel and Larkey, 2003) can benefit by explicitly translating such words from one language into another.
---------------------------------------------------
W98-1005:3	13:224	(Knight and Graehl, 1997) present a computational treatment of Japanese/English transliteration, which we adapt here to the case in Arabic.
---------------------------------------------------
W98-1005:4	95:224	Resolving that ambiguity is bonus when going in the backwards direction--English T, for example, can be safely posited for Arabic t or T without losing any information 4 New Model for Arabic Fortunately, the first two models of (Knight and Graehl, 1997) deal with English only, so we can reuse them directly for Arabic/English transliteration.
---------------------------------------------------
W98-1005:5	105:224	We applied the EM learning algorithm described in (Knight and Graehl, 1997) on this data, with one variation.
---------------------------------------------------
W98-1005:6	57:224	Extending this notion, (Knight and Graehl, 1997) built five probability distributions: 1.
---------------------------------------------------
W98-1005:7	37:224	(Knight and Graehl, 1997) describe a backtransliteration system for Japanese.
---------------------------------------------------
N06-1011:8	56:160	(Knight and Graehl, 1997) build a generative model for backward transliteration from Japanese to English.
---------------------------------------------------
I08-6004:9	8:161	Transliteration of a name, for the purpose of this work, is defined as its transcription in a different language, preserving the phonetics, perhaps in a different orthography [Knight and Graehl, 1997] 1 .  While traditional transliteration systems have relied on hand-crafted linguistic rules, more recently, statistical machine learning techniques have been shown to be effective in transliteration tasks [Jung et al., 2000] [AbdulJaleel and Larkey, 2003] [Virga  and Kudhanpur , 2003] [Haizhou et al., 2004].
---------------------------------------------------
C04-1102:10	18:195	However, backtransliteration is known to be a very dif cult task(Knight and Graehl, 1997).
---------------------------------------------------
C04-1102:11	188:195	There are several studies on transliteration (e.g. , (Knight and Graehl, 1997)), and they tell us that machine transliteration of language pairs that employ very different alphabets and sound systems is extremely dif cult, and that the technology is still to immature for use in practical processing.
---------------------------------------------------
W09-0418:12	23:82	For example, in order to translate names and technical terms, (Knight and Graehl, 1997) introduced a probabilistic model that replaces Japanese 105 katakana1 words with phonetically equivalent English words.
---------------------------------------------------
P09-1089:13	56:234	To translate across languages with different alphabets approaches such as (Knight and Graehl, 1997; Habash, 2008) use transliteration techniques to tackle proper nouns and technical terms.
---------------------------------------------------
N07-1046:14	20:233	Knight and Graehl (1997) introduced finite state transducers that implement back-transliteration from Japanese to English, which was then extended to Arabic-English in (Stalls and Knight, 1998).
---------------------------------------------------
C00-1056:15	210:212	\[119\] Knight, Kevin and Jonathan Graehl (1997) Machine Transliteration, Proc.
---------------------------------------------------
H05-1109:16	35:233	(Knight and Graehl, 1997; Kumar and Byrne, 2003)).
---------------------------------------------------
I08-1030:17	21:242	Using machine transliteration can resolve part of UNK translation (Knight and Graehl, 1997).
---------------------------------------------------
I08-1030:18	229:242	Other proposed methods include paraphrasing (Callison-Burch et al., 2006) and transliteration (Knight and Graehl, 1997) that uses the feature of phonetic similarity.
---------------------------------------------------
P06-1103:19	66:269	(Knight and Graehl, 1997) build a generative model for backward transliteration from Japanese to English.
---------------------------------------------------
W03-1508:20	19:177	Finite state transducers that implement transformation rules for back-transliteration from Japanese to English have been described by Knight and Graehl (1997), and extended to Arabic by Glover-Stalls and Knight (1998).
---------------------------------------------------
P08-1045:21	11:197	Here are four reference translations taken from the same corpus, with mistakes underlined: Ref1 composers such as Bach, missing name Chopin, Beethoven, Shumann, Rakmaninov, Ravel and Prokoviev Ref2 musicians such as Bach, Mozart, Chopin, Bethoven, Shuman, Rachmaninoff, Rafael and Brokoviev Ref3 composers including Bach, Mozart, Schopen, Beethoven, missing name Raphael,Rahmaniev and Brokofien Ref4 composers such as Bach, Mozart, missing name Beethoven, Schumann, Rachmaninov, Raphael and Prokofiev The task of transliterating names (independent of end-to-end MT) has received a significant amount of research, e.g., (Knight and Graehl, 1997; Chen et al., 1998; Al-Onaizan, 2002).
---------------------------------------------------
P08-1045:22	70:197	Unlike various generative approaches (Knight and Graehl, 1997; Stalls and Knight, 1998; Li et al., 2004; Matthews, 2007; Sherif and Kondrak, 2007; Kashani et al., 2007), we do not synthesize an English spelling from scratch, but rather find a translation in very large lists of English words (3.4 million) and phrases (47 million).
---------------------------------------------------
P08-2014:23	17:91	Previous works usually take a generative approach, (Knight and Graehl, 1997).
---------------------------------------------------
W02-1809:24	68:186	Knight and Graehl (1997) have proposed to compose a set of weighted finite state transducers to solve the much more complicated problem of back-transliteration from Japanese Katakana to English.
---------------------------------------------------
W08-1402:25	166:182	A related thread of research is work on automatic transliteration, where training sets are typically used to compute probabilities for mappings in weighted finite state transducers (Al-Onaizan and Knight 2002; Gao et al. 2004) or source-channel models (Knight and Graehl 1997; Li et al. 2004).
---------------------------------------------------
I08-6006:26	33:152	Knight and Graehl (Knight and Graehl , 1997) developed a five stage statistical model to do back transliteration, that is, recover the original English name from its transliteration into Japanese Katakana.
---------------------------------------------------
W03-0104:27	70:208	3 Mapping Pinyin to Chinese Character Back-transliteration is a difficult problem as exemplified in (Knight and Graehl 1997, Chen, et.al. 1998).
---------------------------------------------------
E09-1050:28	32:257	As a result, the following homographs may be interpreted as either a proper name, a noun, or a verb: alwn alon oak alwn alun I will sleep alwn alon Alon (name) One usually distinguishes between two types of transliteration (Knight and Graehl, 1997): Forward transliteration, where an originally Hebrew term is to be transliterated to English; and Backward transliteration, in which a foreign term that has already been transliterated into Hebrew is to be recovered.
---------------------------------------------------
