They do not have grouping or smoothing facilities (Haruno and Matsumoto, 1997).


In choosing adequate levels of abstraction or specification of POS in the context, we grouped together those POS tags which influence the choice of POS of a focus word in a similar lnanner as one super-POS tag, as in (Haruno & Matsumoto 1997).


1 Introduction In Japanese, around 95% word segmentation accuracy is reported by using a word-based language model and the Viterbi-like dynamic programming procedures (Nagata, 1994; Yamamoto, 1996; Takeuchi and Matsumoto, 1997; Haruno and Matsumoto, 1997).


