P04-1059:1	229:233	The use of TBL for Chinese word segmentation was first suggested in Palmer (1997).
---------------------------------------------------
J00-3004:2	82:379	Hockenmaier and Brew (1998) present an algorithm, based on Palmer's (1997) experiments, that applies a symbolic machine learning technique--transformation-based error-driven learning (Brill 1995)--to the problem of Chinese word segmentation.
---------------------------------------------------
W06-0128:3	7:102	In general, the word segmentation program utilizes the word entries, part-of-speech (POS) information (Chen and Liu, 1992) in a monolingual dictionary, segmentation rules (Palmer, 1997), and some statistical information (Sproat, et al. , 1994).
---------------------------------------------------
W04-1118:4	15:191	For example, (Palmer, 1997) developed a Chinese word segmenter using a manually segmented corpus.
---------------------------------------------------
W03-1724:5	59:86	This links our disambiguation strategy to the application of Brills (1993) transformation-based error-driven learning to Chinese word segmentation (Palmer, 1997; Hockenmaier and Brew, 1998).
---------------------------------------------------
A00-2032:6	146:159	In a later paper, Palmer (1997) presents a transformation-based algorithm, which requires pre-segmented training data.
---------------------------------------------------
W03-1025:7	180:199	Palmer (1997) uses transform-based learning (TBL) to correct an initial segmentation.
---------------------------------------------------
W03-1708:8	45:186	Following (Hockenmaier and Brew, 1998; Palmer, 1997) we divide the error repairing operations of word segmentation into three types, that is, concat, split and slide.
---------------------------------------------------
J05-4005:9	118:855	Though the use of TBL for Chinese word segmentation is not new (see Palmer [1997]; Hockenmaier and Brew [1998]), none of the previous work is aimed at standards adaptation.
---------------------------------------------------
P98-2206:10	17:148	Palmer(1997) conducted a Chinese segrnenter which merely made use of a manually segmented corpus(without referring to any lexicon).
---------------------------------------------------
E09-1031:11	76:210	The first attempts to employ TBL to solve the problem of Chinese word segmentation go back to Palmer (1997) and Hockenmaier and Brew (1998).
---------------------------------------------------
