Finite mixture models have been used in a variety of applications in text processing (e.g. , (Li and Yamanishi, 1997; Nigam et al. , 2000; Hofmann, 1999)), indicating that they are essential to text processing.


For example, Li and Yamanishi propose to employ in text classification a mixture model (Li and Yamanishi, 1997) defined over categories: P(WIC) = ~ P(klc)P(wlk),w e W,c e C, kEK where W denotes a set of words, and C a set of categories.


