While the empirical approach of this study is close to that of (Eugenio et al. , 1997), they apply a machine learning technique to predicating cue occurrence and placement, not cue phrase selection. 
There have been many studies of domain identification which used term weighting (J.McDonough et al., 1994; Yokoi et al., 1997). 
Moser and Moore \[1995\] and DiEugenio et al. \[1997\] also take a broader view on marker production in that they try to determine general factors that influence the use of markers in text, and in that they consider more than pairs of propositions. However, they are largely  concerned with marker occurrence and placement, not with marker selection. 
First, discourse structure is indispensable for selecting cue phrase as claimed in previous studies (Grosz and Sidner, 1986; Cohen, 1984; Eugenio et al. , 1997). 
We conducted domain identification and keyword extraction experiment (Suzuki et al., 1997) for radio news. 
