It is inherent to the use of local corpora that can lead to poor estimation of parameters or weights; and  Assumption of independence and normality of word distribution are two of the many problems in language modelling (Franz, 1997).


The mutual information for two words a and b is defined as: MI(a,b) = log2 p(a,b)p(a)p(b) (1) where p(a) and p(b) are the probabilities of occurrence of a and b. Many measures that apply statistical techniques assuming strict normal distribution, and independence between the word occurrences (Franz, 1997) do not fare well.


This assumption has been shown to be wrong in certain applications (Franz, 1997).


