If we mechanically mirror this pattern of proof over the original glue terms (with meanings, but quantifier-free), a role/meaning 9See (Fry, 1997), who uses a proof net method for glue language deduction, for relevant discussion.


1 Introduction Polarity sensitivity (Ladusaw, 1979) has been a popular linguistic phenomenon to analyze in the categorial (Dowty, 1994), lexical-functional (Fry, 1997, 1999), and type-logical (Bernardi, 2002; Bernardi and Moot, 2001) approaches to grammar.


