Copestake and Lascarides (1997) and Lascarides and Copestake (1998) make the same observation for a variety of constructions such as compound nouns, adjective-noun combinations and verb-argument relations.


Our model provides plausible alternatives to the default, and it augments the general semantic type in the interpretation thats assigned by these theories with a plausible range of more specific values, although, in contrast to the hybrid model of interpretation described in Copestake and Lascarides (1997), it does not predict the contexts in which a statistically dispreferred interpretation is the correct one.


Previous approaches have focused on descriptive (Vendler 1968) or theoretical (Pustejovsky 1991, 1995; Briscoe, Copestake, and Boguraev 1990) accounts, on the linguistic constraints on the phenomenon (Godard and Jayez 1993; Pustejovsky and Bouillon 1995; Copestake and Briscoe 1995; Copestake 2001), and on the influence of discourse context on the interpretation of metonymies (Briscoe, Copestake, and Boguraev 1990; Lascarides and Copestake 1998; Verspoor 1997).


MWE research has focussed largely on their implications in language understanding, fluency and robustness (Pearce, 2001; Sag et al. , 2002; Copestake and Lascarides, 1997; Bannard et al. , 2003; McCarthy et al. , 2003; Widdows and Dorow, 2005).


use semantics and/or pragmatics to carry out deep analysis of the source NN compound, and map it into some intermediate (i.e. interlingual) semantic representation (Copestake and Lascarides, 1997; Barker and Szpakowicz, 1998; Rosario and Hearst, 2001) 2.


