The first attempt to derive paraphrasing rules from corpora was undertaken by (Jacquemin et al. , 1997), who investigated morphological and syntactic variants of technical terms. 
According to (Jacquemin et al. , 1997), there are three types of syntactic variations in French: coordinations (Coot), insertions of modifiers (Modif), and compounding/decompounding (Comp). 
As shown in this example, the paraphrases generated based on Japanese word formation rule cannot be classified in terms of the past paraphrase classification (Jacquemin et al. , 1997). 
2 Previous Work There has been a rich body of research on automatically deriving paraphrases, including equating morphological and syntactic variants of technical terms (Jacquemin et al. , 1997), and identifying equivalent adjective-noun phrases (Lapata, 2001). 
In fact, a similar representation was used by (Jacquemin et al. , 1997) to describe term variations. 
