J00-3005:1	251:943	In addition to the discourse relation signaled by a marker such as Although, which introduces expectations (Cristea and Webber 1997), I also found it useful to annotate the rhetorical relation that held between the sentence to which an expectation-based marker belonged and the text span that went before.
---------------------------------------------------
J00-3005:2	36:943	On one hand, the theories developed in the traditional, truth-based semantic perspective (Kamp 1981; Lascarides and Asher 1993; Asher 1993; Hobbs et al. 1993; Kamp and Reyle 1993; Asher and Lascarides 1994; Kameyama 396 Marcu Rhetorical Parsing of Unrestricted Texts 1994; Polanyi and van den Berg 1996; van den Berg 1996; Gardent 1997; Schilder 1997; Cristea and Webber 1997; Webber et al. 1999) take the position that discourse structures can be built only in conjunction with fully specified clause and sentence syntactic structures.
---------------------------------------------------
J00-3005:3	383:943	The action DUAL is usually associated with cue phrases that can introduce some expectations about the discourse (Cristea and Webber 1997).
---------------------------------------------------
W99-0307:4	166:185	4 Tagging style The vast majority of the computational approaches to discourse parsing rely on models that implicitly or explicitly assume that parsing is incremental (Polanyi, 1988; Lascarides and Asher, 1993; Gardent, 1997; Schilder, 1997; van den Berg, 1996; Cristea and Webber, 1997).
---------------------------------------------------
P99-1006:5	27:194	2 Framework In previous papers (Cristea and Webber, 1997; Webber and Joshi, 1998; Webber et al. , 1999), we have argued for using the more complex structures (elementary trees) of a Lexicalized Tree-Adjoining Grammar (LTAG) and its operations (adjoining and substitution) to associate structure and semantics with a sequence of discourse clauses.
---------------------------------------------------
W98-0301:6	76:169	The action DUAL is usually associated with cue phrases that can introduce some expectations about the discourse (Cristea and Webber, 1997).
---------------------------------------------------
W98-0315:7	4:209	More recently, Cristea and Webber (1997) have argued that a Tree-Adjoining Grammar for discourse would also need the substitution operation found in a lexicalized TAG (Schabes, 1990).
---------------------------------------------------
P99-1047:8	79:168	These features specify whether a discourse marker that introduces expectations (Cristea and Webber, 1997) (such as although) was used in the sentence under consideration, whether there are any commas or dashes before the estimated end of the sentence, and whether there are any verbs in the unit under consideration.
---------------------------------------------------
