This representation is inspired by the earlier works (Johnston et al. , 1997; Johnston, 1998) and offers a flexibility to accommodate complex inputs. 
The basic multimodal integration strategy of Johnston et al 1997 is now just one rule among many (Figure 7). 
Meanwhile, (Johnston et al. , 1997; Johnston, 1998) describe a formalism for tightly-coupled interpretation which uses a grammar and semantic constraints to analyze input from speech and pen. 
The approach of Johnston et al 1997 also faces fundamental architectural problems. 
To realize their full potential, multimodal interfaces need to support not just input from multiple modes, but synergistic multimodal utterances optimally distributed over the available modes (Johnston et al. , 1997). 
