Primitive OT (Eisner, 1997) already restricts OT to something like a bare minimum of constraints, allowing just two simple constraint families that are widely used by practitioners of OT. 
Following Eisner (1997), each candidate (x;z) is also represented as a string y. The notation (x;z) that we have been using so far for candidates is actually misleading, since in fact the candidatesy that are compared encode more than justxandz. 
(Ellison, 199d; Eisner, 1997a) frmne ()T wit\]fin this tradition, t)y modeling Gen mM the (:onsl;ra.illtS :ts w(;ig\]lt(;d tinit(>sl;~t(; m~mhin(;s (see {}3.2). 
However, for certain types of constraints, translation into the primitives of OTP (Eisner (1997b)) can only be accomplished by adding to the grammar a number of ad hoc phonological tiers. 
Equation (1) defines Optimality Theory as an optimisation problem, but finding the optimal candidate can be NP-hard (Eisner, 1997). 
