Neuhaus and Broker (1997) have recently showed that the general recognition problem for non-projective dependency grammars (what they call discontinuous DG) is NP-complete. 
Parsing algorithms able to treat completely unrestricted long-distance dependencies are NPcomplete (Neuhaus and Broker, 1997). 
Since Gaifman (1965) proved that his projective dependency grammar is weakly equivalent to context-free grammar, Neuhaus and Broker (1997) have shown that the recognition problem for a dependency grammar that can define arbitrary non-projective structures is NP complete, but there are no results for systems of intermediate complexity. 
2.4 Long-distance Dependencies Long-distance dependencies exponentially increase parsing complexity (Neuhaus and Broker, 1997). 
The introduction of non lexical categories also permits the resolution of the inconsistencies pointed out by Neuhaus and Broker in Word Grammar (1997). 
