This paper extends a novel approach to constraint-based tagging first applied for Turkish (Oflazer and Tiir, 1997), which relieves the rule developer from worrying about contlicting rule ordering requirements and constraints.


Previous ai)proaches to morphological dismnbiguation of Turkish text; had employed a constraintbased approach (Otlazer and KuruSz, 1994; Oflazer and Tiir, 1996; Oflazer and Tiir, 1997).


This is slightly 1)etter than the precision figures that is reported earlier on morphological disambiguation of Turkish using constraintbased techniques (Oflazer and T/Jr, 1997).


Also (Bick, 2000) uses manually written disambiguation rules for tagging Brazilian Portuguese, (Karlsson, 1985) and (Koskenniemi, 1990) for Finish and (Oflazer, 1997) reports the same for Turkish.


