5 Related Work The work presented in the current article is related to previous work on corpus-based grammar specialization as presented in (Rayner, 1988; Salnuelsson and Rayner, 1991; Rayner and Carter, 1996; Samuelsson, 1994; Srinivas a.nd Joshi, 1995; Neumann, 1997).


(Srinivas and aoshi, 1995) and (Neumann, 1997) apply EBL to speed up parsing with tree-adjoining grammars and sentence generation with HPSGs respectively, though they do so by introducing new components in their systems rather then by modifying the grammars they use.


2002) has a machine learning approach for realization similar to (Neumann, 1997): Transformation rules are learned offline from examples in a corpus.


In (Neumann, 1997) a training phase with an appropriate corpus is needed, while we perform generation at runtime without such a corpus.


