D08-1109:1	42:232	Examples of such efforts include work on the induction of synchronous grammars (Wu and Wong, 1998; Chiang, 2005) and learning multilingual lexical resources (Genzel, 2005).
---------------------------------------------------
P01-1050:2	10:154	With a few exceptions (Wu and Wong, 1998), most SMT systems are couched in the noisy channel framework (see Figure 1).
---------------------------------------------------
D07-1003:3	39:243	2 Related Work To model the syntactic transformation process, researchers in these fieldsespecially in machine translationhave developed powerful grammatical formalisms and statistical models for representing and learning these tree-to-tree relations (Wu and Wong, 1998; Eisner, 2003; Gildea, 2003; Melamed, 2004; Ding and Palmer, 2005; Quirk et al. , 2005; Galley et al. , 2006; Smith and Eisner, 2006, inter alia).
---------------------------------------------------
I05-2021:4	135:135	In particular, more grammatically structured statistical MT models that are better equipped to handle long distance dependencies, such as the ITG based grammatical channel translation model (Wu and Wong, 1998), might make better use of the WSD predictions.
---------------------------------------------------
J04-4002:5	480:482	A promising avenue is to gradually extend the model to take into account to some extent the recursive structure of natural languages using ideas from Wu and Wong (1998) or Alshawi, Bangalore, and Douglas (2000).
---------------------------------------------------
D07-1007:6	218:218	It would also be interesting to assess whether a more grammatically structured statistical MT model that is less reliant on an n-gram language model, such as the syntactic ITG based grammatical channel translation model of (Wu and Wong, 1998), could make more effective use of WSD predictions.
---------------------------------------------------
D07-1080:7	54:227	We applied an Earley-style top-down parsing approach (Wu and Wong, 1998; Watanabe et al. , 2006b; Zollmann and Venugopal, 2006).
---------------------------------------------------
H05-1101:8	18:170	Among the several proposals, we mention here the models presented in (Wu, 1997; Wu and Wong, 1998), (Alshawi et al. , 2000), (Yamada and Knight, 2001), (Gildea, 2003) and (Melamed, 2003).
---------------------------------------------------
H05-1101:9	124:170	The most general definition of the translation problem for PSCFG is this: for an input PSCFG Gp = (G,pG) and an input string w, produce a representation of all possible parse trees, alongwiththeirprobabilities, thatareassigned byGto a string in the setT(G,w)under some translation of w. Variant of this definition can be found where the input is a single parse tree for w (Yamada and Knight, 2001), or where the output is a single parse tree, chosen according to some specific criteria (Wu andWong, 1998).
---------------------------------------------------
H05-1101:10	132:170	This has been shown for instance in (Wu and Wong, 1998; Yamada and Knight, 2001; Melamed, 2004).
---------------------------------------------------
P05-2016:11	17:31	 Stochastic Inversion Transduction Grammars (Wu and Wong, 1998): This formalism uses a grammar for English and from it derives a possible grammar for the foreign language.
---------------------------------------------------
W99-0630:12	120:131	Wu and Wong apply them in their SITG channel model to give better performance in their translation application (Wu and Wong, 1998).
---------------------------------------------------
P05-1048:13	160:160	A more grammatically structured statistical MT model that less ngram oriented, such as the ITG based grammatical channel translation model (Wu and Wong, 1998), might make more effective use of the WSD models predictions.
---------------------------------------------------
N04-1021:14	129:293	6 Tree-Based Feature Functions Syntax-based MT has shown promise in the work of, among others, Wu and Wong (1998) and Alshawi, Bangalore, and Douglas (2000).
---------------------------------------------------
D07-1079:15	9:289	Approaches include word substitution systems (Brown et al. , 1993), phrase substitution systems (Koehn et al. , 2003; Och and Ney, 2004), and synchronous context-free grammar systems (Wu and Wong, 1998; Chiang, 2005), all of which train on string pairs and seek to establish connections between source and target strings.
---------------------------------------------------
