W99-0603:1	42:169	That is:  The starting point is a sense disambiguated Spanish taxonomy-automatically extracted from a monolingual dictionary (Rigau et al. , 1998)-.
---------------------------------------------------
W99-0603:2	78:169	These taxonomies were automatically assigned to a WordNet semantic file (Rigau et al. , 1997; Rigau et al. , 1998).
---------------------------------------------------
W99-0603:3	18:169	The method has been applied to attach substantial fragments of the Spanish taxonomy derived from DGILE (Rigau et al. , 1998) to the English WordNet using a bilingual dictionary for connecting both hierarchies.
---------------------------------------------------
