W03-1728:1	46:81	In that paper, pairwise voting (van Halteren et al. , 1998) has been used to combine the results of two supertaggers that scan the input in the opposite directions.
---------------------------------------------------
W02-1004:2	84:156	A very common technique for combination in such a case is by voting (Brill and Wu, 1998; van Halteren et al. , 1998; Sang et al. , 2000).
---------------------------------------------------
W02-1004:3	77:156	An alternative method for estimating the parameters AL CZ is to approximate them with the performance of the CZ th classifier (a performance-based combiner) (van Halteren et al. , 1998; Sang et al. , 2000) AL CZ B4DCBNCSB5BPC8 B4BV CZ _is_correctCYDCBNCSB5 (4) therefore giving more weight to classifiers that have a smaller classification error (the method will be referred to as PB).
---------------------------------------------------
W02-1004:4	5:156	1 Introduction Classifier combination has been extensively studied in the last decade, and has been shown to be successful in improving the performance of diverse NLP applications, including POS tagging (Brill and Wu, 1998; van Halteren et al. , 2001), base noun phrase chunking (Sang et al. , 2000), parsing (Henderson and Brill, 1999) and word sense disambiguation (Kilgarriff and Rosenzweig, 2000; Stevenson and Wilks, 2001).
---------------------------------------------------
A00-2007:5	76:180	Like (Van Halteren et al. , 1998), we have used different input versions: one containing only the classifier output and another containing both classifier output and a compressed representation of the classifier input.
---------------------------------------------------
A00-2007:6	6:180	By combining the results with voting techniques described in (Van Halteren et al. , 1998) we manage to improve the best reported performances on standard data sets for base noun phrases and arbitrary noun phrases.
---------------------------------------------------
A00-2007:7	10:180	With the best voting technique, the combined results decrease the lowest error rate of the component taggers by as much as 19% (Van Halteren et al. , 1998).
---------------------------------------------------
A00-2007:8	7:180	1 Introduction (Van Halteren et al. , 1998) and (Brill and Wu, 1998) describe a series of successful experiments for improving the performance of part-of-speech taggers.
---------------------------------------------------
A00-2007:9	112:180	Halteren et al. , 1998), the best voting technique did not outperform the best stacked classifier.
---------------------------------------------------
A00-2007:10	63:180	For this purpose we have evaluated different voting mechanisms, effectively the voting methods as described in (Van Halteren et al. , 1998).
---------------------------------------------------
A00-1031:11	198:207	According to current tagger comparisons (van Halteren et al. , 1998; Zavrel and Daelemans, 1999), and according to a comparsion of the results presented here with those in (Ratnaparkhi, 1996), the Maximum Entropy framework seems to be the only other approach yielding comparable results to the one presented here.
---------------------------------------------------
A00-1031:12	11:207	Recent comparisons of approaches that can be trained on corpora (van Halteren et al. , 1998; Volk and Schneider, 1998) have shown that in most cases statistical aproaches (Cutting et al. , 1992; Schmid, 1995; Ratnaparkhi, 1996) yield better results than finite-state, rule-based, or memory-based taggers (Brill, 1993; Daelemans et al. , 1996).
---------------------------------------------------
A00-1031:13	192:207	For example, the Markov model tagger used in the comparison of (van Halteren et al. , 1998) yielded worse results than all other taggers.
---------------------------------------------------
W02-2031:14	37:93	Compared to the previous systems (van Halteren et al. , 1998; Kudo and Matsumoto, 2000; Yamada et al. , 2001), our system is: (i) employing more than two levels stacking, (ii) using only one algorithm and training only one learner at each level, (iii) using the surrounding tag given by the lower level learner.
---------------------------------------------------
P01-1032:15	116:166	5 Mapping Strategies Recent work (Van Halteren et al. , 1998) has demonstrated improvement in part-of-speech tagging when the outputs of multiple taggers are combined.
---------------------------------------------------
P01-1005:16	49:133	4 The Efficacy of Voting Voting has proven to be an effective technique for improving classifier accuracy for many applications, including part-of-speech tagging (van Halteren, et al, 1998), parsing (Henderson and Brill, 1999), and word sense disambiguation (Pederson, 2000).
---------------------------------------------------
P03-1064:17	115:231	Then we combine the results via pairwise voting as in (van Halteren et al. , 1998; Chen et al. , 1999) as the final supertag.
---------------------------------------------------
W05-1518:18	90:283	Parallel to (van Halteren et al. , 1998), we ran experiments with two stacked classifiers, Memory-Based, and Decision-Tree-Based.
---------------------------------------------------
W05-1518:19	11:283	Combination techniques have been successfully applied to part of speech tagging (van Halteren et al. , 1998; Brill and Wu, 1998; van Halteren et al. , 2001).
---------------------------------------------------
W05-1518:20	13:283	Similar advances have been made in machine translation (Frederking and Nirenburg, 1994), speech recognition (Fiscus, 1997), named entity recognition (Borthwick et al. , 1998), partial parsing (Inui and Inui, 2000), word sense disambiguation (Florian and Yarowsky, 2002) and question answering (Chu-Carroll et al. , 2003).
---------------------------------------------------
W05-1518:21	106:283	In all experiments, the TotPrecision voting scheme of (van Halteren et al. , 1998) has been used.
---------------------------------------------------
W99-0608:22	24:185	More recently, two parallel works (van Halteren et al. , 1998; Brill and Wu, 1998) combined, with a remarkable success, the output of a set of four tuggers based on different principles and feature modelling.
---------------------------------------------------
W99-0608:23	181:185	There are several features that should be further studied with respect to the used methods for constructing the ensembles of decision trees, the way they are combined and included in the tuggers, etc. However, we are now more interested on experimenting with the inclusion of our tagger as a component in an ensemble of preexisting tuggers, in the style of (Brill and Wu, 1998; van Halteren et al. , 1998).
---------------------------------------------------
W01-0712:24	126:210	And finally, TAGPAIR uses classification pair weights based on the probability of a classification for some predicted classification pair (van Halteren et al. , 1998).
---------------------------------------------------
P99-1023:25	10:186	Much research has been done to improve tagging accuracy using several different models and methods, including: hidden Markov models (HMMs) (Kupiec, 1992), (Charniak et al. , 1993); rule-based systems (Brill, 1994), (Brill, 1995); memory-based systems (Daelemans et al. , 1996); maximum-entropy systems (Ratnaparkhi, 1996); path voting constraint systems (Tiir and Oflazer, 1998); linear separator systems (Roth and Zelenko, 1998); and majority voting systems (van Halteren et al. , 1998).
---------------------------------------------------
C00-1051:26	23:162	Recently, there have been various attempts to at)ply committee-based techniques to NLP tasks such as POS tagging (Halteren et al. , 1998; Brill et al. , 1998), parsing (Henderson and Brill, 1999), word sense disambiguation (Pedersen, 2000), machine translation (lh'ederking and Nirenburg, 1994), and speech recognition (Fiscus, 1997).
---------------------------------------------------
W00-0733:27	20:79	We will evaluate nine different methods for combining the output of our five chunkers (Van Halteren et al. , 1998).
---------------------------------------------------
W00-0733:28	28:79	The most advanced voting method examines output values of pairs of classifiers and assigns weights to tags based on how often they appear with this pair in the tuning data (TagPair, Van Halteren et al. , (1998)).
---------------------------------------------------
W00-0733:29	34:79	For this purpose we have used the part-of-speech tag of the current word as compressed representation of the first stage input (Van Halteren et al. , 1998).
---------------------------------------------------
W02-1029:30	8:174	Ensemble learning has been successfully applied to numerous NLP tasks, including POS tagging (Brill and Wu, 1998; van Halteren et al. , 1998), chunking (Tjong Kim Sang, 2000), word sense disambiguation (Pederson, 2000) and statistical parsing (Henderson and Brill, 1999).
---------------------------------------------------
W99-0623:31	10:158	Similar advances have been made in machine translation (Frederking and Nirenburg, 1994), speech recognition (Fiscus, 1997) and named entity recognition (Borthwick et al. , 1998).
---------------------------------------------------
W99-0623:32	8:158	Recently, combination techniques have been investigated for part of speech tagging with positive results (van Halteren et al. , 1998; Brill and Wu, 1998).
---------------------------------------------------
P06-2060:33	38:122	Halteren et al (1998) compare a number of voting methods including a Majority Vote scheme with other combination methods for part of speech tagging.
---------------------------------------------------
W02-1036:34	10:135	Previously studied techniques for collecting such systems include: i) using several existing real systems (van Halteren et al. , 1998; Brill and Wu, 1998; Henderson and Brill, 1999; Tjong Kim Sang, 2000), ii) bagging/boosting techniques (Henderson and Brill, 1999; Henderson and Brill, 2000), and iii) switching the data expression and obtaining several models (Tjong Kim Sang, 2000).
---------------------------------------------------
W02-1036:35	15:135	Proceedings of the Conference on Empirical Methods in Natural combining outputs of classifiers at the first stage (van Halteren et al. , 1998; Brill and Wu, 1998; Tjong Kim Sang, 2000).
---------------------------------------------------
W02-1036:36	6:135	1 Introduction In the recent corpus-based NLP research, system combination techniques have been successfully applied to several tasks such as parts-of-speech tagging (van Halteren et al. , 1998), base noun phrase chunking (Tjong Kim Sang, 2000), and parsing (Henderson and Brill, 1999; Henderson and Brill, 2000).
---------------------------------------------------
W02-1036:37	12:135	Combine the outputs of the several systems: previously studied techniques include: i) voting techniques (van Halteren et al. , 1998; Tjong Kim Sang, 2000; Henderson and Brill, 1999; Henderson and Brill, 2000), ii) switching among several systems according to confidence values they provide (Henderson and Brill, 1999), iii) stacking techniques (Wolpert, 1992) which train a second stage classifier for Association for Computational Linguistics.
---------------------------------------------------
P06-2013:38	128:216	In the weighted voting method, we can assign different weights to the results of the individual system(van Halteren et al. , 1998).
---------------------------------------------------
W00-0704:39	14:121	This paper expands on an empirical comparison (van Halteren et al. , 1998) in which TRIGRAM tagging, BRILL tagging, MAXIMUM ENTROPY and MEMORY BASED tagging were compared on the LOB corpus.
---------------------------------------------------
W00-0704:40	95:121	Also note that the results report in Table 5 differ significantly from those reported for MXPOST in (van Halteren et al. , 1998).
---------------------------------------------------
A00-1024:41	42:236	(van Halteren et al. , 1998) who found that combining the results of several part of speech taggers increased performance).
---------------------------------------------------
