W99-0621:1	25:205	These problems formulations are similar to those studied in (Ramshaw and Marcus, 1995) and (Church, 1988; Argamon et al. , 1998), respectively.
---------------------------------------------------
W99-0621:2	158:205	As reported in (Argamon et al. , 1998), most base NPs present in ~he data are less or equal than 4 words long.
---------------------------------------------------
W99-0621:3	59:205	Of the several slightly different definitions of a base NP in the literature we use for the purposes of this work the definition presented in (Ramshaw and Marcus, 1995) and used also by (Argamon et al. , 1998)and others.
---------------------------------------------------
W99-0621:4	9:205	The observation that shallow syntactic information can be extracted using local information by examining the pattern itself, its nearby context and the local part-of-speech information has motivated the use of learning methods to recognize these patterns (Church, 1988; Ramshaw and Marcus, 1995; Argamon et al. , 1998; Cardie and Pierce, 1998).
---------------------------------------------------
W99-0621:5	61:205	For example: presented \[last year \] in \[Illinois\] in front of  SV phrases, following the definition suggested in (Argamon et al. , 1998), are word phrases starting with the subject of the sentence and ending with the first verb, excluding modal verbs 2.
---------------------------------------------------
W99-0621:6	98:205	This approach has been studied in (Church, 1988; Argamon et al. , 1998).
---------------------------------------------------
W99-0621:7	139:205	4 Methodology 4.1 Data In order to be able to compare our results with the results obtained by other researchers, we worked with the same data sets already used by (Ramshaw and Marcus, 1995; Argamon et al. , 1998) for NP and SV detection.
---------------------------------------------------
P99-1009:8	8:119	Among the machine learning algorithms studied, rule based systems have proven effective on many natural language processing tasks, including part-of-speech tagging (Brill, 1995; Ramshaw and Marcus, 1994), spelling correction (Mangu and Brill, 1997), word-sense disambiguation (Gale et al. , 1992), message understanding (Day et al. , 1997), discourse tagging (Samuel et al. , 1998), accent restoration (Yarowsky, 1994), prepositional-phrase attachment (Brill and Resnik, 1994) and base noun phrase identification (Ramshaw and Marcus, In Press; Cardie and Pierce, 1998; Veenstra, 1998; Argamon et al. , 1998).
---------------------------------------------------
A00-2007:9	145:180	(Argamon et al. , 1998) use Memory-Based Sequence Learning for recognizing both NP chunks and VP chunks.
---------------------------------------------------
E99-1016:10	202:231	Results for chunking Penn Treebank data were previously presented by several authors (Ramshaw and Marcus, 1995; Argamon et al. , 1998; Veenstra, 1998; Cardie and Pierce, 1998).
---------------------------------------------------
W01-0706:11	9:129	Thus, over the past few years, along with advances in the use of learning and statistical methods for acquisition of full parsers (Collins, 1997; Charniak, 1997a; Charniak, 1997b; Ratnaparkhi, 1997), significant progress has been made on the use of statistical learning methods to recognize shallow parsing patterns  syntactic phrases or words that participate in a syntactic relationship (Church, 1988; Ramshaw and Marcus, 1995; Argamon et al. , 1998; Cardie and Pierce, 1998; Munoz et al. , 1999; Punyakanok and Roth, 2001; Buchholz et al. , 1999; Tjong Kim Sang and Buchholz, 2000).
---------------------------------------------------
W99-0706:12	189:255	Except for the object precision score of 77% in \[Argamon et al. , 1998\], both finders have grammatical relation recall and precision scores in the 80s.
---------------------------------------------------
W99-0706:13	193:255	The system in \[Argamon et al. , 1998\] only finds a subset of the surface subjects and objects.
---------------------------------------------------
W99-0706:14	184:255	Some examples for English include the English parser used in tide SPARKLE project \[Briscoe et al. , \] \[Carroll et al. , 1997b\] \[Carroll et al. , 1998b\] and the finder built with a memory-based approach \[Argamon et aI.
---------------------------------------------------
W99-0706:15	202:255	The figures given above were the original (1998) results for the system in \[Argamon et al. , 1998\], which came from training and testing on data derived from the Penn Treebank corpus \[Marcus et al. , 1993\] in which the added null elements (like null subjects) were left in.
---------------------------------------------------
W99-0707:16	129:186	Chunking For NP chunking, \[Argamon et al. , 1998\] used data extracted from section 15-18 of the WS.J as a fixed train set and section 20 as a fixed test set, the same data as \[Ramshaw and Marcus, 1995\].
---------------------------------------------------
W99-0707:17	133:186	We also present the results of \[Argamon et al. , 1998\], \[Ramshaw and Marcus: 1995\] and \[Cardie and Pierce, 1998\] in Table 4.
---------------------------------------------------
W99-0707:18	181:186	We also extensively compared our approach to a recently proposed new memory-based learning algorithm, memory-based sequence learning (MBSL, \[Argamon et al. , 1998\] and showed that MBL, which is a computationally simpler algorithm than MBSL, is able to readl similar precision and recall when restricted to the MBSL definition of the NP chunking, subject detection and object detection tasks.
---------------------------------------------------
W99-0707:19	3:186	Introduction Recently, there has been an increased interest in approaches to automatically learning to recognize shallow linguistic patterns in text \[Ramshaw and Marcus, 1995, Vilain and Day, 1996, Argamon et al. , 1998, Buchholz, 1998, Cardie and Pierce, 1998, Veenstra, 1998, Daelemans et aI.
---------------------------------------------------
W99-0707:20	121:186	Discussion and Related Research In \[Argamon et al. , 1998\], an alternative approach to memox3'-based learning of shallow patterns, memorybased sequence learning (MBSL), is proposed.
---------------------------------------------------
W99-0707:21	136:186	As \[Argamon et al. , 1998\] used only POS informaSubjects # subsequences  Method A,D&K  IGTcee IBI-IG "IBI-IG POS only IBI-IG without chunks IBI-IG with treebank chunks Objects 3044 1626 I prec.
---------------------------------------------------
E99-1023:22	72:160	We will follow (Argamon et al. , 1998) and use a combination of the precision and recall rates: F~=I = (2" precision*recall) / (precision+recall).
---------------------------------------------------
E99-1023:23	145:160	The algorithm is very fast and it reaches the same performance as (Argamon et al. , 1998) (F,~=1=91.6).
---------------------------------------------------
E99-1023:24	131:160	(Argamon et al. , 1998) introduce Memory-Based Sequence Learning and use it for different chunking experiments.
---------------------------------------------------
E99-1023:25	137:160	177 Proceedings of EACL '99 IOB1 IOB2 IOE1 IOE2 \[+\] \[+ IO IO +\] (Ramshaw and Marcus, 1995) (Veenstra, 1998) (Argamon et al. , 1998) (Cardie and Pierce, 1998) accuracy 97.58% 96.50% 97.58% 96.77% 97.37% 97.2% precision 92.50% 91.24% 92.41% 91.93% 93.66% 91.47% 91.25% 91.80% 89.0% 91.6 % 90.7% recall F~=I 92.25% 92.37 92.32% 91.78 92.04% 92.23 92.46% 92.20 90.81% 92.22 92.61% 92.04 92.54% 91.89 92.27% 92.03 94.3% 91.6 91.6% 91.6 91.1% 90.9 Table 6: The F~=I scores for the (Ramshaw and Marcus, 1995) test set after training with their training data set.
---------------------------------------------------
C00-2089:26	76:178	Tile Memory-Based Sequence Learning (MBSL) algorithm (Argamon et al. , 1998) learns substrings or sequences of POS and brackets.
---------------------------------------------------
