A00-1006:1	5:127	ture that uses '% pragmatic adaptation" (LuperFoy and others, 1998), and Mima et al. proposed a method that uses "situational information" (Mima and others, 1997).
---------------------------------------------------
W02-0216:2	61:202	We choose to focus on building this class of dialogue systems because we share with (Allen et al. , 2001), a version of the the Practical Dialogue 5Compare this with the motivation behind the Pragmatic Adapter idea of (LuperFoy et al. , 1998).
---------------------------------------------------
