C08-1067:1	13:167	There is a long tradition of research into bilingual terminology extraction (Kupiec, 1993), (Gaussier,1998).
---------------------------------------------------
P02-1052:2	30:169	A different approach was proposed by Gaussier (1998).
---------------------------------------------------
W04-2207:3	19:171	The alignment between terms is obtained either by computing association probabilities (Gaussier, 1998 ; Daille, Gaussier and Lang, 1994) or by identifying, for a given source term, a sequence of words in the target language which is likely to contain or to correspond to its translation (Hull, 2001).
---------------------------------------------------
W04-2207:4	20:171	In so far as the precision rate may be affected by the number of alignments obtained (Daille, Gaussier and Lang, 1994; Gaussier, 1998), the results achieved basically range between 80% and 90%, for the first 500 alignments.
---------------------------------------------------
W04-2207:5	18:171	On the other hand, only source terms are extracted and the target ones are discovered through the alignment process (Gaussier, 1998; Hull, 2001).
---------------------------------------------------
W04-2207:6	161:171	Daille, Gaussier and Lang (1994), as well as Gaussier (1998) and Hull (2001), were interested in bilingual terminology extraction so that word alignment could not be considered as an end in itself but rather as a basis for term alignment.
---------------------------------------------------
