This is implemented as a cascade of simple strategies, which were briefly described in Mikheev (1999). 
4 Enhanced Feature Set (Mikheev, 1999) described a new approach to the disambiguation of capitalized words in mandatory positions. 
A proper solution for categorising Primoten is derived from this as well, since the coordinative conjunction i will usually connect the NEs from the same category (Mikheev, 1999). 
By collecting sequences and unigrams of unambiguously capitalized and lowercased words in the document and imposing special ordering of their applications (Mikheev, 1999) reports that the document-centered approach achieved a 0.4-0.7% error rate with coverage of about 90% on the disambiguation of capitalized words in mandatory positions. 
3.3 Global word sequence checking This strategy is used for solving complex ambiguities (Mikheev, 1999). 
