Several other studies tried to filter out noise expansion (or translation) terms by considering the relations between them (Gao et al. , 2002; 558 Jang et al. 1999; Qiu and Frei, 1993; Bai et al. 2005).


This is standard; see, for example, Jang et al. 1999.


So while word choice may be a significant consideration for a system like that of Jang et al. , 1999, its impact on PictureQuest is minimal.


Query translation methods (Hull and Grefenstette, 1996; Davis, 1996; Eichmann et al, 1998; Yang et al, 1998; Jang et al, 1999; Chun, 2000) based on bilingual dictionaries, multilingual ontology or thesaurus are much more practical.


One way of resolving query ambiguities is to use the statistics, such as mutual information (Church and Hanks, 1990), to measure associations of query terms, on the basis of existing corpora (Jang et al, 1999).


