Recent research has shown that by exploiting the structure of discourse, one can decrease storage space in information retrieval applications (CorstonOliver and Dolan 1999) and address discourse-specific problems in machine translation (Marcu, Carlson, and Watanabe, 2000).


Dolan (S.H. Olivers and W.B.Dolan, 1999) proposed removing clauses in sentences before indexing document for information retrieval.


Examples include text summarisation (Jing 2000), subtitle generation from spoken transcripts (Vandeghinste and Pan 2004) and information retrieval (Olivers and Dolan 1999).


(Corston-Oliver and Dolan, 1999) proposed to remove clauses in sentences before indexing documents for Information Retrieval.


