WIT features an incremental understanding method (Nakano et al. , 1999b) that makes it possible to build a robust and real-time system. 
The understanding module utilizes ISSS (Incremental Significant-utterance Sequence Search) (Nakano et al. , 1999b), which is an integrated parsing and discourse processing method. 
For example, speech repairs, particle omission, and fillers can be dealt with in the framework of unification grammar (Nakano et al. , 1994; Nakano and Shimazu, 1999). 
Since the language generation module works in parallel with the language understanding module, utterance generation is possible even while the system is listening to user utterances and that utterance understanding is possible even while it is speaking (Nakano et al. , 1999a). 
The priorities are used for disambiguating interpretation in the incremental understanding method (Nakano et al. , 1999b). 
