J00-3005:1	36:943	On one hand, the theories developed in the traditional, truth-based semantic perspective (Kamp 1981; Lascarides and Asher 1993; Asher 1993; Hobbs et al. 1993; Kamp and Reyle 1993; Asher and Lascarides 1994; Kameyama 396 Marcu Rhetorical Parsing of Unrestricted Texts 1994; Polanyi and van den Berg 1996; van den Berg 1996; Gardent 1997; Schilder 1997; Cristea and Webber 1997; Webber et al. 1999) take the position that discourse structures can be built only in conjunction with fully specified clause and sentence syntactic structures.
---------------------------------------------------
W05-0305:2	19:201	2 Overview of the PDTB The PDTB builds on the DLTAG approach to discourse structure (Webber and Joshi, 1998; Webber et al. , 1999; Webber et al. , 2003) in which connectives are discourse-level predicates which project predicate-argument structure on a par with verbs at 29 the sentence level.
---------------------------------------------------
J03-4002:3	516:694	In several previous papers (Webber, Knott, and Joshi, 2001; Webber et al. , 1999a, 1999b), we described how our approach fits into the framework of tree-adjoining grammar. This led to the initial version of a discourse parser (Forbes et al. 2001) in which the same parser that builds trees for individual clauses using clause-level LTAG trees then combines them using discourse-level LTAG trees.
---------------------------------------------------
J03-4002:4	77:694	As we have pointed out in earlier papers (Webber, Knott, and Joshi 2001; Webber et al. , 1999a, 1999b), structural connectives have two relevant properties: (1) they admit stretching of predicate-argument dependencies; and (2) they do not admit crossing of those dependencies.
---------------------------------------------------
J02-3003:5	404:880	Each subordinate conjunction may anchor a family of trees to reflect variations in the surface order of the substituted argument clauses, but the predicateargument relation remains the same (Webber and Joshi 1998; Webber et al. , 1999a, 1999b).
---------------------------------------------------
C04-1020:6	12:199	Hobbs, 1985; Marcu, 2000; Webber et al. , 1999).
---------------------------------------------------
C04-1020:7	74:199	1 Other accounts also acknowledge examples that cannot be represented in tree structures (Webber et al. , 1999).
---------------------------------------------------
C04-1020:8	63:199	3 Data structures for representing coherence relations Most accounts of discourse coherence assume tree structures to represent coherence relations between discourse segments in a text (Carlson et al. , 2002; Corston-Oliver, 1998; Lascarides & Asher, 1993; Longacre, 1983; Grosz & Sidner, 1986; Mann & Thompson, 1988; Marcu, 2000; Polanyi, 1988; van Dijk & Kintsch, 1983; Walker, 1998; Webber et al. , 1999).
---------------------------------------------------
W00-1006:9	175:191	(Webber et al. , 1999) apply operations on trees for incorporating cue-phrases in a grammar-driven approach to discourse structure.
---------------------------------------------------
W00-1006:10	162:191	Only recently, there have been some approaches (Webber et al. , 1999) that acknowledge the need to incorporate both a treatment of cue-phrase approaches and inferences.
---------------------------------------------------
J05-2005:11	285:651	(1999): According to Webber et al.
---------------------------------------------------
J05-2005:12	15:651	Other accounts aim to represent the informational structure of a discourse; in these accounts, coherence relations reflect how the meaning conveyed by one discourse segment relates to the meaning conveyed by another discourse segment (e.g. , Hobbs 1985; Marcu 2000; Webber et al. 1999).
---------------------------------------------------
J05-2005:13	42:651	Whereas some argue that discourse segments should be prosodic units (Hirschberg and Nakatani 1996), others argue for intentional units (Grosz and Sidner 1986), phrasal units (Lascarides and Asher 1993; Longacre 1983; Webber et al. 1999), or sentences (Hobbs 1985).
---------------------------------------------------
J05-2005:14	264:651	also Polanyi 1996; Polanyi and Scha 1984; Webber et al. 1999).
---------------------------------------------------
J05-2005:15	291:651	(1999), or at least claims that seem to be very similar to those in Webber et al.
---------------------------------------------------
E06-1024:16	13:188	This treats user utterances as explicit instructions for how they are to be incorporated into the unfolding discoursean approach that can itself be accomodated within much current discourse semantic work whereby potential discourse interpretation is facilitated by drawing tighter structural and semantic constraints from each discourse contribution (Webber et al. , 1999; Asher and Lascarides, 2003).
---------------------------------------------------
W04-0212:17	17:198	(1999b) and Webber et al.
---------------------------------------------------
W04-0212:18	9:198	Work on the PDTB is grounded in a lexicalized approach to discourse  DLTAG (Webber and Joshi, 1998; Webber et al. , 1999a; Webber et al. , 2000; Webber et al. , 2003).
---------------------------------------------------
W04-0212:19	54:198	What we describe to annotators as arguments to discourse connectives are actually the textual span from which the argument is derived (Webber et al. , 1999a; Webber et al. , 2003).
---------------------------------------------------
W05-0312:20	12:125	Like the Penn English Discourse Treebank (Miltsakaki et al. , 2004a; Miltsakaki et al. , 2004b), the CDTB project adopts the general idea presented in (Webber and Joshi, 1998; Webber et al. , 1999; Webber et al. , 2003) where discourse connectives are considered to be predicates that take abstract objects such as propositions, events and situations as their arguments.
---------------------------------------------------
W04-2703:21	31:239	(1999b) and Webber et al.
---------------------------------------------------
W04-2703:22	136:239	The annotators are also informed that in some cases, an argument of a connective must be derived from the selected textual span (Webber et al. , 1999a; Webber et al. , 2003).
---------------------------------------------------
W04-2703:23	16:239	(1999a), Webber et al.
---------------------------------------------------
W04-0203:24	33:234	These relations have syntactic aspects, such that single utterances can be grouped together and combined into segments recursively and are often modeled as a hierarchical tree structure (Grosz and Sidner, 1986; Webber et al. , 1999).
---------------------------------------------------
