The work of (Hirschman et al. , 1999) initiated this series of work, and it reported an accuracy of 36.3% on answering the questions in the test stories. 
1 Introduction Recognizing and classifying entities and relations in text data is a key task in many NLP problems such as information extraction (IE) (Califf and Mooney, 1999; Freitag, 2000; Roth and Yih, 2001), question answering (QA) (Voorhees, 2000) and story comprehension (Hirschman et al. , 1999). 
The Deep Read reading comprehension system (Hirschman et al. , 1999) uses a statistical bag-ofwords approach, matching the question with the lexically most similar sentence in the story. 
In prior work (Hirschman et al. , 1999; Charniak et al. , 2000; Riloffand Thelen, 2000) the number and type of information sources used for computation is specific to and rlifFerent for each question type. 
This metric is originally proposed by (Hirschman et al. , 1999). 
