N07-3003:1	55:65	This includes extracting semantic relations expressed in the encyclopedic definitions by means of Hearst patterns (Hearst, 1992), detection of semantic variations (Morin & Jacquemin, 1999) between category labels, as well as using the categorized pages as bag-of-words to compute scores of idf-based semantic overlap (Monz & de Rijke, 2001) between categories.
---------------------------------------------------
W02-1113:2	102:146	This generalization process is close to the one imagined by Morin and Jacquemin (1999) for terminology analysis.
---------------------------------------------------
W02-1113:3	63:146	The method is close to the one of E. Morin et C. Jacquemin (1999), who first locate couples of relevant terms and then try to apply relevant patterns to analyse the nature of their relationship.
---------------------------------------------------
W02-0904:4	38:220	The work most similar to ours is that of Morin & Jacquemin (1999).
---------------------------------------------------
W02-0904:5	54:220	Had we worked with domain-specific data (see e.g. Morin and Jaquemin (1999)), it would have been possible to assume only one sense per word or phrase.
---------------------------------------------------
P05-2009:6	38:193	Morin (1999) reported a semiautomatic implementation of Hearsts algorithm.
---------------------------------------------------
P05-2009:7	52:193	Hearst and others learn relations between either noun phrases or single words, while Morin (1999) discusses how hypernyms learnt between single words can be projected onto multi-word terms.
---------------------------------------------------
W03-1802:8	10:127	(Morin and Jacquemin, 1999; Hamon and Nazarenko, 2001) structure complex terms (multiword terms) with the help of lexical databases or general dictionaries.
---------------------------------------------------
W06-0507:9	18:168	Generalising textual patterns (both manually and automatically) for the identification of relations has been proposed since the early nineties (Hearst, 1992), and it has been applied to extendingontologieswithhyperonymyandholonymyrelations (Morin and Jacquemin, 1999; Kietz et al. , 2000; Cimiano et al. , 2004; Berland and Charniak,1999).
---------------------------------------------------
W06-0507:10	19:168	Finkelstein-LandauandMorin(1999) learn patterns for company merging relations with exceedingly good accuracies.
---------------------------------------------------
C04-1092:11	62:133	The method is close to the one of Morin and Jacquemin (1999), who first try to locate couples of relevant terms and then apply relevant patterns to analyse the nature of their relationship.
---------------------------------------------------
C04-1092:12	105:133	This generalization process is close to the one imagined by Morin and Jacquemin (1999) for terminology analysis but, as we already said, we cover sequences that are not only nominal ones.
---------------------------------------------------
