We can generalize this result using the notion of a meta-level grammar (Dras, 1999).


The basic idea of using synchronous TAG for machine translation dates from the original definition (Shieber and Schabes, 1990), and has been pursued by several researchers (Abeille et al. , 1990; Dras, 1999; Prigent, 1994; Palmer et al. , 1999), but only recently in its probabilistic form (Nesson et al. , 2006).


(1999) provide an approach to STAG that attempts to address this particular problem as does the extension of Dras (1999).


