C04-1135:1	5:222	1 Introduction Hyponymy relations can play a crucial role in various NLP systems, and there have been many attempts to develop automatic methods to acquire hyponymy relations from text corpora (Hearst, 1992; Caraballo, 1999; Imasumi, 2001; Fleischman et al. , 2003; Morin and Jacquemin, 2003; Ando et al. , 2003).
---------------------------------------------------
P06-1038:2	44:240	Caraballo (1999) uses conjunction and appositive annotations in the vector representation.
---------------------------------------------------
D07-1034:3	35:213	Caraballo (1999) selected head nouns from conjunctions and appositives in noun phrases, and used the cosine similarity measure with a bottomup clustering technique to construct a noun hierarchy from text.
---------------------------------------------------
C08-1058:4	33:158	One is automatic thesaurus acquisition, that is, to identify synonyms or topically related words from corpora based on various measures of similarity (e.g. Riloff and Shepherd, 1997; Lin, 1998; Caraballo, 1999; Thelen and Riloff, 2002; You and Chen, 2006).
---------------------------------------------------
N07-1031:5	30:321	Another thread of work is on finding synonymous terms and word associations, as well as automatic acquisition of IS-A (or genus-head) relations from dictionary definitions and free text (Hearst, 1992; Caraballo, 1999).
---------------------------------------------------
W02-0904:6	50:220	The built-in ambiguity in the hyponymy hierarchy presented in (Caraballo, 1999) is primarily an effect of the fact that all information is composed into one tree.
---------------------------------------------------
W02-0904:7	193:220	Caraballo (1999) let three judges evaluate ten internal nodes in the hyponymy hierarchy, that had at least twenty descendants.
---------------------------------------------------
W02-0904:8	190:220	It is difficult to compare these results with results from other studies such as that of Caraballo (1999), as the data used is not the same.
---------------------------------------------------
W02-0904:9	30:220	Caraballo (1999) uses a hierarchical clustering technique to build a hyponymy hierarchy of nouns.
---------------------------------------------------
W02-0904:10	187:220	As was also reported by Caraballo (1999), the judges sometimes found proper nouns (as hyponyms) hard to evaluate.
---------------------------------------------------
J06-2003:11	336:682	IS-A hierarchies have been learned automatically from MRDs (Hearst 1992) and from corpora (Caraballo [1999] among others).
---------------------------------------------------
W08-2113:12	9:194	So, many attempts have been made to automatically produce taxonomies (Grefenstette, 1994), but (Caraballo, 1999) is certainly the first work which proposes a complete overview of the problem by (1) automatically building a hierarchical structure of nouns based on bottom-up clustering methods and (2) labeling the internal nodes of the resulting tree with hypernyms from the nouns clustered underneath by using patterns such as B is a kind of A.
---------------------------------------------------
W08-2113:13	8:194	As stated in (Caraballo, 1999), WordNet has been an important lexical knowledge base, but it is insufficient for domain specific texts.
---------------------------------------------------
W08-2113:14	18:194	Similarly, (Caraballo, 1999) uses predefined patterns such as X is a kind of Y or X, Y, and other Zs to identify hypernym/hyponym relationships.
---------------------------------------------------
W05-1006:15	32:148	Such hierarchical examples are quite sparse, and greater coverage was later attained by Riloff and Shepherd (1997) and Roark and Charniak (1998) in extracting relations not of hierarchy but of similarity, by finding conjunctions or co-ordinations such as cloves, cinammon, and nutmeg and cars and trucks. This work was extended by Caraballo (1999), who built classes of related words in this fashion and then reasoned that if a hierarchical relationship could be extracted for any member of this class, it could be applied to all members of the class.
---------------------------------------------------
D09-1099:16	96:211	Work in automated ontology construction has created lexical hierarchies (Caraballo, 1999; Cimiano and Volker, 2005; Mann, 2002), and learned semantic relations such as meronymy (Berland and Charniak, 1999; Girju et al., 2003).
---------------------------------------------------
W03-0404:17	216:226	In recent years several techniques have been developed for semantic lexicon creation (e.g. , (Hearst, 1992; Riloff and Shepherd, 1997; Roark and Charniak, 1998; Caraballo, 1999)).
---------------------------------------------------
C02-1090:18	9:182	Its previous applications (e.g. , Grefenstette 1993, Hearst and Schuetze 1993, Takunaga et al 1997, Lin 1998, Caraballo 1999) demonstrated that cooccurrence statistics on a target word is often sufficient for its automatical classification into one of numerous classes such as synsets of WordNet.
---------------------------------------------------
W02-1111:19	126:167	Caraballo and Charniak (1999) and Caraballo (1999) augmented these lexical patterns with more general lexical co-occurrence statistics (such as relative entropy).
---------------------------------------------------
W09-1108:20	39:257	Caraballo (1999) uses conjunction and appositive annotations in the vector representation.
---------------------------------------------------
C00-2104:21	49:269	In the same vein, researchers at Brown University (Caraballo and Charniak, 1999)~ (Berland and Charniak, 1999), (Caraballo, 1999) and (Roark and Charniak, 1998) focused on target constructions, in particular complex noun t)hrases, and searched for information not only on identifying classes of nouns, lint also hypernyms, noun specificity and meronymy.
---------------------------------------------------
W04-2103:22	10:185	The approach is now being actively explored for a wide range of semantics-related tasks including automatic construction of thesauri (Lin, 1998; Caraballo, 1999), their enrichment (Alfonseca and Manandhar, 2002; Pekar and Staab, 2002), acquisition of bilingual lexica from nonaligned (Kay and Rscheisen, 1993) and nonparallel corpora (Fung and Yee, 1998), learning of information extraction patterns from un-annotated text (Riloff and Schmelzenbach, 1998).
---------------------------------------------------
C04-1111:23	46:301	Caraballo (1999) was the first to use clustering for labeling is-a relations using conjunction and apposition features to build noun clusters.
---------------------------------------------------
P07-2038:24	15:88	The idea that nouns co-occurring in conjunctions tend to be semantically related has been noted in (Riloff and Shepherd, 1997) and used effectively to automatically cluster semantically similar words (Roark and Charniak, 1998; Caraballo, 1999; Widdows and Dorow, 2002).
---------------------------------------------------
E09-1021:25	46:270	Caraballo (1999) uses conjunction and appositive annotations in the vector representation.
---------------------------------------------------
J05-3004:26	127:629	10 One approach to the extraction of instances of a particular lexical relation is the use of patterns that express lexical relations structurally explicitly in a corpus (Hearst 1992; Berland and Charniak 1999; Caraballo 1999; Meyer 2001), and this is the approach we focus on here.
---------------------------------------------------
J05-3004:27	126:629	This includes the extraction of hyponymy and synonymy relations (Hearst 1992; Caraballo 1999, among others) as well as meronymy (Berland and Charniak 1999; Meyer 2001).
---------------------------------------------------
N04-4030:28	27:97	There has also been extensive work on finding synonymous terms and word associations, as well as automatic acquisition of IS-A (or genus-head) relations from dictionary definitions and glosses (Klavans and Whitman, 2001) and from free text (Hearst, 1992; Caraballo, 1999).
---------------------------------------------------
W02-0903:29	211:225	These types of models have been used for hyponym discovery (Hearst, 1992; Roark and Charniak, 1998), meronym discovery (Berland and Charniak, 1999), and hierarchy building (Caraballo, 1999).
---------------------------------------------------
W02-1028:30	98:187	Caraballo (Caraballo, 1999) and Hearst (Hearst, 1992) created techniques to learn hypernym/hyponym relationships.
---------------------------------------------------
W02-0908:31	16:172	These systems extract related terms directly by recognising linguistic patterns (e.g. X, Y and other Zs) which link synonyms and hyponyms (Hearst, 1992; Caraballo, 1999).
---------------------------------------------------
D09-1089:32	42:251	Caraballo (1999) uses conjunction and appositive annotations in the vector representation.
---------------------------------------------------
P06-1015:33	43:192	Caraballo (1999) proposed the first attempt, which used conjunction and apposition features to build noun clusters.
---------------------------------------------------
W03-0415:34	99:204	This problem has been addressed by Caraballo (1999), who describes a system that first builds an unlabelled hierarchy of noun clusters using agglomerative bottom-up clustering of vectors of noun coordination information.
---------------------------------------------------
W03-0415:35	21:204	Another definition is given by Caraballo (1999): .
---------------------------------------------------
W03-0415:36	17:204	In Section 4, we show how correctly extracted relationships can be used as seed-cases to extract several more relationships, thus improving recall; this work shares some similarities with that of Caraballo (1999).
---------------------------------------------------
W03-0415:37	197:204	First of all, it would be interesting to apply LSA to a system for building an entire hypernym-labelled ontology in roughly the way described in (Caraballo, 1999), perhaps by using an LSA-weighted voting method to determine which hypernym would be used to label each node.
---------------------------------------------------
P09-1031:38	74:255	Agglomerative clustering (Brown et al., 1992; Caraballo, 1999; Rosenfeld and Feldman, 2007; Yang and Callan, 2008) iteratively merges the most similar clusters into bigger clusters, which need to be labeled.
---------------------------------------------------
P09-1031:39	67:255	Besides contextual features, the vectors can also be represented by verb-noun relations (Pereira et al., 1993), syntactic dependency (Pantel and Ravichandran, 2004; Snow et al., 2005), co-occurrence (Yang and Callan, 2008), conjunction and appositive features (Caraballo, 1999).
---------------------------------------------------
C04-1146:40	19:161	Previous work on this problem (Caraballo, 1999; Lin et al. , 2003) involves identifying speci c phrasal patterns within text e.g., \Xs and other Ys" is used as evidence that X is a hyponym of Y. Our work explores the connection between relative frequency, distributional generality and semantic generality with promising results.
---------------------------------------------------
D09-1028:41	37:250	Caraballo (1999) uses conjunction and appositive annotations in the vector representation.While efforts have been made for improving the computational complexity of these methods (Gorman and Curran, 2006), they remain data and computation intensive.
---------------------------------------------------
W99-0609:42	17:143	In Caraballo (1999), we construct a hierarchy of nouns, including hypernym relations.
---------------------------------------------------
W99-0609:43	13:143	See Caraballo (1999) for a detailed description of a method to construct such a hierarchy.
---------------------------------------------------
W05-1003:44	10:196	On the other hand, the only work on the extraction of lexical semantic relations we are aware of has concentrated on the type of relations found in WordNet: hyponymy (Hearst, 1998; Caraballo, 1999) and meronymy (Berland and Charniak, 1999; Poesio et al, 2002).
---------------------------------------------------
P02-1030:45	30:170	Instead, these systems recognise terms within certain linguistic patterns (e.g. X, Y and other Zs) which associate synonyms and hyponyms (Hearst, 1992; Caraballo, 1999).
---------------------------------------------------
P04-2001:46	26:186	(Caraballo, 1999A) (Grefenstette, 1994) (Hearst, 1992) (Pereira, 1993) and (Sanderson, 1999) used contextual information to find hyponymy relation between terms.
---------------------------------------------------
P03-2011:47	6:174	Other previous research has focused on features related to unknown word contexts (Caraballo 1999; Roark and Charniak 1998).
---------------------------------------------------
P03-2011:48	20:174	The Caraballo (1999)s system adopted the contextual information to assign nouns to their hyponyms.
---------------------------------------------------
W09-1703:49	54:188	Another related line of work is automated ontology construction, which aims to create lexical hierarchies based on semantic classes (e.g., (Caraballo, 1999; Cimiano and Volker, 2005; Mann, 2002)).
---------------------------------------------------
W04-1806:50	71:174	For example, the cue-phrase such as (Hearst 1992) (Caraballo 1999) suggest a kind-of relation, e.g., a ligand such as triethylphosphine tells us that triethylphosphene is a kind of ligand.
---------------------------------------------------
W04-1806:51	161:174	For example, based on (Caraballo 1999), each parent of a leaf node could be viewed as a cluster label for its children, with the weight of a parent-child link being determined based on how strongly the child is associated with the cluster.
---------------------------------------------------
W04-1806:52	144:174	Other approaches use natural language data, sometimes just by analyzing the corpus (Sanderson and Croft 1999), (Caraballo 1999) or by learning to expand WordNet with clusters of terms from a corpus, e.g., (Girju et al. 2003).
---------------------------------------------------
N04-1010:53	7:218	We do not use particular lexicosyntactic patterns, as previous attempts have (Hearst, 1992; Caraballo, 1999; Imasumi, 2001; Fleischman et al. , 2003; Morin and Jacquemin, 2003; Ando et al. , 2003).
---------------------------------------------------
P08-1119:54	33:202	Another related line of work is automated ontology construction, which aims to create lexical hierarchies based on semantic classes (e.g., (Caraballo, 1999; Cimiano and Volker, 2005; Mann, 2002)), and learning semantic relations such as meronymy (Berland and Charniak, 1999; Girju et al., 2003).
---------------------------------------------------
P04-3015:55	14:102	In previous research, ways of extracting from definition sentences in dictionaries (Tsurumaru et al. , 1986; Shoutsu et al. , 2003) or from a corpus by using patterns such as a part of, is-a, or and (Berland and Charniak, 1999; Caraballo, 1999) have been proposed.
---------------------------------------------------
W09-2508:56	45:234	The first work that introduced co-occurrence methods to the field is that of Caraballo (1999).
---------------------------------------------------
W02-1017:57	40:176	Caraballo (Caraballo, 1999) also exploited these syntactic structures and applied a cosine vector model to produce semantic groupings.
---------------------------------------------------
D09-1097:58	68:239	Pattern-based method (Hearst 1992, Pantel et al. 2004a, Ando et al. 2003, Snow et al. 2005, Snow et al. 2006, and Etzioniet al. 2005) Clustering-based method (Caraballo 1999, Pantel et al. 2004b, Shinzato et al. 2004, and Etzioniet al. 2005) DocumentsCorpus/documents Co-occurrences in a pattern are needed hypernym such as word hypernym    word word word wordword Word  Class word The same hypernym is selected for all words in a class.
---------------------------------------------------
D09-1097:59	47:239	Caraballo (1999), Pantel et al.
---------------------------------------------------
J05-4002:60	39:515	A further problem for distributional similarity methods for automatic thesaurus generation is that they do not offer any obvious way to distinguish between linguistic relations such as synonymy, antonymy, and hyponymy (see Caraballo [1999] and Lin et al. [2003] for work on this).
---------------------------------------------------
