1.1 Translation-based approach A second approach to multilingual interrogation is to use existing machine translation (MT) systems to automatically translate the queries (Davis, 1998), or even the entire textual database (Oard and Hackett, 1998) (McCarley, 1999) from one language to another, thereby transforming the CLIR problem into a monolingual information retrieval (MLIR) problem.


Applications where word order is not essential include  cross-language information retrieval (e.g. , McCarley 1999),  multilingual document filtering (e.g. , Oard 1997),  computer-assisted language learning (e.g. , Nerbonne et al. 1997),  certain machine-assisted translation tools (e.g. , Macklovitch 1994; Melamed 1996a),  concordancing for bilingual lexicography (e.g. , Catizone, Russell, and Warwick 1989; Gale and Church 1991), 222 Melamed Models of Translational Equivalence  corpus linguistics (e.g. , Svartvik 1992),  "crummy" machine translation (e.g. , Church and Hovy 1992; Resnik 1997).


