2 Methodology Isahara and Kanzaki (1999) classified semantic relations between adjectives and their head nouns from the viewpoints of syntax, semantics and computational treatment.


We used syntactic and semantic patterns in our previous work (Isahara and Kanzaki 1999) in order to extract these types of examples from large corpora semi-automatically.


We extracted 134 abstract nouns used as this kind of head noun semi-automatically by using syntactic patterns that Isahara and Kanzaki(1999) and Kanzaki et al.


Isahara and Kanzaki (Isahara and Kanzaki, 1999) treated a much wider range of phenomena of adnominal constituents.


In our previous research on adjectives (Isahara and Kanzaki, 1999) we used Pustejovsky's theory to classify adjectives in Japanese.


