Goldberg applied a cooccurrence-based probabilistic model to determine the attachments of ambiguous coordinate phrases with the form n1 p n2 cc n3 (Goldberg, 1999). 
Other studies on coordination include (Agarwal and Boggess, 1992; Chantree et al., 2005; Goldberg, 1999; Okumura and Muraki, 1994). 
Goldberg (1999) resolves the attachment of ambiguous coordinate phrases of the kind n1 p n2 c n3, e.g., box/n1 of/p chocolates/n2 and/c roses/n3. 
Previous work on coordination disambiguation has focused on the task of addressing the scope ambiguity (e.g. , (Agarwal and Boggess, 1992; Goldberg, 1999; Resnik, 1999; Chantree et al. , 2005)). 
A probabilistic approach is presented in (Goldberg, 1999), where an unsupervised maximum entropy statistical model is used to disambiguate coordinate noun phrases of the form n1 preposition n2 cc n3. 
