Multiple translations of a Chinese word is disambiguated by looking at the context of the sentences this word appears in (Fung et al. , 1999). 
Different sentence alignment algorithms based on both sentence and lexical information can be found in Manning and Sch tze (1999), Wu (2000), Dale et al. 
These methods look at the context words and discourse surrounding the source word and use methods ranging from boostrapping (Li & Li 2003), EM iterations (Cao and Li, 2002; Koehn and Knight 2000), and the cohesive relation between the source sentence and translation candidates (Fung et al. 1999; Kikui 1999). 
When a Chinese word has multiple possible translations in English, it is disambiguated using an extension of Fung et al.s (1999) method [13]. 
This omission is also done in applications such as word sense dismnbiguation (Yarowsky: 1994; FUNG et al. , 1999). 
