N06-1019:1	11:159	In this paper we propose the use of annotated data in the new domain, but only partially annotated data, which reduces the annotation effort required (Hwa, 1999).
---------------------------------------------------
W01-0521:2	9:115	#281996#29 for results on Switchboard, as well as Collins et al. #281999#29 for results on Czech and Hwa #281999#29 for bootstrapping from WSJ to ATIS#29.
---------------------------------------------------
P06-1043:3	49:213	However, the work which is most directly comparable to ours is that of (Ratnaparkhi, 1999; Hwa, 1999; Gildea, 2001; Bacchiani et al. , 2006).
---------------------------------------------------
W07-2203:4	170:177	These findings may not hold if the level of bracketing available does not adequately constrain the parses considered  see Hwa (1999) for a related investigation with EM.
---------------------------------------------------
W00-1306:5	15:185	There are two possible directions: one might attempt to reduce the amount of annotations in each sentence, as was explored by Hwa (1999); alternatively, one might attempt to reduce the number of training sentences.
---------------------------------------------------
N03-1027:6	12:172	Hwa (1999) used a variant of the inside-outside algorithm presented in Pereira and Schabes (1992) to exploit a partially labeled out-of-domain treebank, and found an advantage to adaptation over direct grammar induction.
---------------------------------------------------
N03-1027:7	11:172	Hwa (1999) and Gildea (2001) looked at adapting parsing models trained on large amounts of annotated data from outside of the domain of interest (out-of-domain), through the use of a relatively small amount of in-domain annotated data.
---------------------------------------------------
C04-1055:8	13:119	It has been reported that stochastic parsers degrade in performance on domains different than what they were trained on (Hwa, 1999; Gildea, 2001), so there really was an issue whether the output would be good enough.
---------------------------------------------------
W06-1520:9	7:78	Large scale handcrafted grammars for many languages have been built based on this paradigm (Joshi, 2001; XTAG Research Group, 2001; Kroch and Joshi, 1985; Abeille and Candito, 2000; Candito, 1998; Becker, 1993; Frank, 2002; Joshi and Schabes, 1997; Abeille and Rambow, 2000) as well as grammars extracted from corpora (Chen and Vijay-Shanker, 2000; Chiang, 2000; Hwa, 1999; Xia et al. , 2001; Xia, 2001).
---------------------------------------------------
