1w 2w 3w 4w0 1 2 3 4 b c e g h d f a :2 :2 :2:2 :1 :1 :1 i 8:1 : Figure 2: Shortest path partial parses with heuristically assigned edge weights However, (Kasper et al. , 1999) did not provide any sophisticated estimation functions based on the shortest path approach. 
In this paper, we adopt the same definition for partial parse as in (Kasper et al. , 1999) and define the task of partial parse selection. 
(Kasper et al. , 1999) did point out that the weights of the edges can be assigned by an estimation function. 
This definition of partial parse is effectively the same to the view of partial analyses in (Kasper et al. , 1999). 
Thus, AUTOSEM operates efficiently, free of any hand coded repair rules or any knowledge specifically dedicated to repair unlike other approaches to recovery from parser failure (Danieli and Gerbino, 1995; Van Noord, 1997; Kasper et al. , 1999). 
