512 Tetreault Centering and Pronoun Resolution 3.2 Method The evaluation (Byron and Tetreault 1999) consisted of two steps: (1) parsing Penn Treebank utterances and (2) running the four algorithms. 
2.4 Left-Right Centering Algorithm Left-Right Centering (Tetreault 1999) is an algorithm built upon centering theory's constraints and rules as detailed in Grosz, Joshi, and Weinstein (1995). 
There is less consensus on the preference order: (sentence-wise) left-to-right (Hobbs, 1978; Strube, 1998; Strube and Hahn, 1999; Tetreault, 1999) or right-to-left (recency) (Lappin and Leass, 1994). 
1999; Tetreault, 1999) for results of pronoun resolution experiments run within the testbed. 
Some of them are based on centering theory (Strube, 1998; Strube and Hahn, 1999; Tetreault, 2001), others on Machine Learning (Aone and Bennett, 1995; Ge et al. , 1998; Soon et al. , 2001; Ng and Cardie, 2002; Yang et al. , 2003). 
