This eliminates any doubts about the computational practicability of dominance constraints which were raised by the NPcompleteness result for the general language (Koller et al. , 1998) and expressed e.g. in (Willis and Manandhar, 1999).


It is interesting to speculate finally on the relation of the above account of the available scope readings with proposals to minimize search during processing by building "underspecified" logical forms by Reyle (1992), and others cited in Willis and Manandhar (1999).


