Berland and Charniak (1999) also used Hearsts algorithm to find partwhole patterns. 
Hearst (1992) explored the use of lexical patterns for extracting hyponym relations, with patterns such as such as. Berland and Charniak (1999) extract part-of relations. 
Lexical patterns have been successfully used to represent various semantic relations between words such as hypernymy (Hearst, 1992), and meronymy (Berland and Charniak, 1999). 
(See, e.g., Riloff and Shepherd (1997), Roark and Charniak (1998), Carahallo (1999), and Berland and Charniak (1999)). 
Berland and Charniak (1999) used a similar method for extracting instances of meronymy relation. 
