There are several examples of researches that focused on high portability and ex- pansibility (Kaspar and Hoffmannn, 1998; Brond- sted et al., 1998; Sutton et al., 1998; Sasajima et al., 1999; Abella and Gorin, 1999; Levin et al., 2000).


Previous work on dialog management (Abella and Gorin, 1999) shows how an object inheritance hierarchy is a convenient way of representing the task knowledge and the relationships among the objects.


Once the task has been determined, the information needed for completing the caller's request is obtained using dialogue submodules that are specific for each task (Abella and Gorin, 1999).


The system modules that we collected information from were the acoustic processer/automatic speech recognizer (ASR) (Riccardi and Gorin, to appear), the natural language understanding (NLU) module (Gorin et al. , 1997), and the dialogue manager (DM) (Abella and Gorin, 1999).


