This is sufiqcient for the extraction of lexical infornlation, e.g. the subcategorisation of verbs (see (Beil et al. , 1999)).


The NEWS-SC corpus is part the corl)uS of verb-final sentences used by (Beil et al. , 1999).


Earlier research on inside-outside estimation of PCFG models has reported some positive results as well 193 (Pereira and Schabes, 1992; Carroll and Rooth, 1998; Beil et al., 1999; imWalde, 2002).


1 Introduction Recent research on German statistical parsing has shown that lexicalization adds little to parsing performance in German (Dubey and Keller, 2003; Beil et al. , 1999).


