An interesting observation that we can make about q_hrkish is that when a word is considere(l as a sequence of IGs, syntactic relations are between the last IG of a (dependent) word and with some (including the last) IG of the (head) word on the right (with nfinor eXCel)tions) (Oflazer, 1999).


We represent each word as a sequence of inflectional groups (IGs hereafter), separated by "DBs denoting derivation boundaries, as described by Oflazer (1999).


Some relatively recent rule-based full dependency parsers are Kurohashi and Nagao (1994) for Japanese, Oflazer (1999) for Turkish, Tapanainen and Jarvinen (1997) for English and Elworthy (2000) for English and Japanese.


