N07-1063:1	21:163	(Galley et al. , 2006) use syntactic constituents for the PSCFG nonterminal set and (Zollmann and Venugopal, 2006) take advantage of CCG (Steedman, 1999) categories, while (Chiang, 2005) uses a single generic nonterminal.
---------------------------------------------------
W07-0731:2	17:149	(2004) use syntactic constituents for the PSCFG nonterminal set, and Zollmann and Venugopal (2006) take advantage of CCG (CombinatorialCategoricalGrammar)(Steedman, 1999)inspired?slash?and?plus?categories,focusingontarget (rather than source side) categories to generate well formed translations.
---------------------------------------------------
E09-1049:3	39:164	The set of non-terminals is extended by means of conditional and additive categories according to Combinatory Categorical Grammar (CCG) (Steedman, 1999).
---------------------------------------------------
C08-1144:4	61:207	These heuristics first consider concatenation operations, forming categories such as NP+V, and then resort to CCG (Steedman, 1999) style slash categories such as NP/NN. or DT\NP.
---------------------------------------------------
C04-1026:5	11:207	One way is to recast semantic ambiguity as syntactic ambiguity by compiling semantic distinctions into the syntax (Montague, 1974; Steedman, 1999; Moortgat, 2002).
---------------------------------------------------
