Others proposed distributional similarity measures between words (Hindle, 1990; Lin, 1998; Lee, 1999; Weeds et al., 2004). 
, Lee 1999). 
Instead, it is based on the assumption that if a word w prime 1 is similar to word w 1, then w prime 1 can provide information about the frequency of unseen word pairs involving w 1 (Dagan, Lee, and Pereira 1999). 
4.4 The -skew Divergence Measure The -skew divergence measure (Lee 1999, 2001) is a popular approximation to the Kullback-Leibler divergence measure 8 (Kullback and Leibler 1951; Cover and Thomas 1991). 
Similar methods have been developed for predicting the similarity of nouns and verbs on the basis of their distributional similarity, and many distributional similarity functions have been proposed for these tasks (Lee, 1999). 
