J00-3005:1	36:943	On one hand, the theories developed in the traditional, truth-based semantic perspective (Kamp 1981; Lascarides and Asher 1993; Asher 1993; Hobbs et al. 1993; Kamp and Reyle 1993; Asher and Lascarides 1994; Kameyama 396 Marcu Rhetorical Parsing of Unrestricted Texts 1994; Polanyi and van den Berg 1996; van den Berg 1996; Gardent 1997; Schilder 1997; Cristea and Webber 1997; Webber et al. 1999) take the position that discourse structures can be built only in conjunction with fully specified clause and sentence syntactic structures.
---------------------------------------------------
J00-3005:2	934:943	Recent research has shown that by exploiting the structure of discourse, one can decrease storage space in information retrieval applications (CorstonOliver and Dolan 1999) and address discourse-specific problems in machine translation (Marcu, Carlson, and Watanabe, 2000).
---------------------------------------------------
J00-3005:3	832:943	6 For research that uses part-of-speech tags in order to identify elementary unit boundaries, see Marcu (1999a).
---------------------------------------------------
J00-3005:4	100:943	In my previous work (Marcu 1996, 1997a, 1997b, 1999b, 2000), I have argued that rhetorical relations that hold between large textual spans can be explained in terms of similar relations that hold between their most important elementary units.
---------------------------------------------------
W03-1119:5	21:142	(D. Magerman, 1995)(Ulf Hermijakob and J.Mooney, 1997) to define the rhetorical of text documents (Daniel Marcu, 1999).
---------------------------------------------------
J00-4003:6	169:766	14 See, however, Marcu (1999).
---------------------------------------------------
W05-0613:7	24:224	Marcu (1999) uses a decision-tree learner and shallow syntactic features 96 to create classi ers for discourse segmentation and for identifying rhetorical relations.
---------------------------------------------------
W05-0613:8	23:224	One exception is Marcus work (Marcu, 1997, 1999) (see also Soricut and Marcu (2003) for constructing discourse structures for individual sentences).
---------------------------------------------------
W05-0613:9	211:224	It is hard to compare these models with Marcus (1999) rhetorical parsing model.
---------------------------------------------------
W05-0613:10	213:224	Even so, it is interesting that the scores reported in Marcu (1999) for labelled and unlabelled relations are similar to our scores for Model 4.
---------------------------------------------------
C00-2130:11	46:110	More specifically, a discourse entity is considered as potential antecedent for a definite 2See, howeve,, (Marcu, 1999).
---------------------------------------------------
W06-3401:12	22:142	2 Previous Research Early work on automatic RST analysis relied heavily on discourse cues to identify relations (CorstonOliver, 1998; Knott and Sanders, 1998; Marcu, 1997; Marcu, 1999; Marcu, 2000) (e.g. , however signaling an antithesis or contrast relation.
---------------------------------------------------
N03-2011:13	68:72	But contrary to Marcu (1999) and also to Schilder (2002) we use a full-fledged discourse grammar and a standard parsing algorithm, which makes it, in our opinion, unnecessary to propose special rhetorical tree building operations, as suggested e.g. by Marcu (1999).
---------------------------------------------------
A00-2002:14	57:182	We used Marcu's discourse annotation tool (1999) in order to manually construct the discourse structure of all Japanese and English texts in the corpus.
---------------------------------------------------
A00-2002:15	129:182	For our corpus, in order to enable a discoursebased transfer module to derive any English discourse tree starting from any Japanese discourse tree, it is sufficient to implement: * one SHIFT operation;  3 x 2  85 REDUCE operations; (For each of the three possible pairs of nuclearity assignments NUCLEUS-SATELLITE (NS), SATELLITE-NUCLEUS (SN), AND NUCLEUSNUCLEUS (NN), there are two possible ways to reduce two adjacent trees (one results in a binary tree, the other in a non-binary tree (Marcu, 1999)), and 85 relation names).
---------------------------------------------------
