W05-0905:1	103:165	Mani (Mani et al. , 36 0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 1 2 3 41=FB1, 2=LSA, 3=MMR, 4=FB2 ROUGE-1-MANROUGE-2-MAN ROUGE-L-MANROUGE-1-ASR ROUGE-2-ASRROUGE-L-ASR Figure 1: ROUGE Scores for the Summarization Approaches 1999) is one of the few papers to have discussed measuring summary readability automatically.
---------------------------------------------------
W03-1205:2	191:217	In general, rules are applied to revise summaries produced by a summarisation system (Mani et al. , 1999; Otterbacher et al. , 2002).
---------------------------------------------------
W04-2611:3	79:165	Abstraction, on the other hand, relies either on linguistic processing followed by structural compaction (Mani et al. , 1999) or on interpretation of the source text into a semantic representation, which is then condensed to retain only the most important information asserted in the source.
---------------------------------------------------
I05-2009:4	151:176	5.3 Related works and discussion Our two-step model essentially belongs to the same category as the works of (Mani et al. , 1999) and (Jing and McKeown, 2000).
---------------------------------------------------
W09-2808:5	10:308	Unlike many other methods that directly utilize noun phrase (NP) coreference (Nenkova 2008; Mani et al. 1999), we propose a method that employs insertion and substitution of phrases that modify the same chunk in the lead and other sentences.
---------------------------------------------------
A00-2024:6	187:205	6 Related work (Mani et al. , 1999) addressed the problem of revising summaries to improve their quality.
---------------------------------------------------
J02-4005:7	377:526	Our evaluation mirrors the TIPSTER SUMMAC categorization task (Firmin and Chrzanowski 1999; Mani et al. 1998) in which given a generic summary (or a full document), the human participant chooses a single category (out of five categories) to which the document is relevant.
---------------------------------------------------
P05-1036:8	12:201	Others have performed the sentence compression task using syntactic approaches to this problem (Mani et al. , 1999) (Zajic et al. , 2004), but we focus exclusively on the K&M formulation.
---------------------------------------------------
J05-3002:9	480:557	While earlier approaches for text compression were based on symbolic reduction rules (Grefenstette 1998; Mani, Gates, and Bloedorn 1999), more recent approaches use an aligned corpus of documents and their human written summaries to determine which constituents can be reduced (Knight and Marcu 2002; Jing and McKeown 2000; Reizler et al. 2003).
---------------------------------------------------
J05-3002:10	471:557	In addition to sentence fusion, compression algorithms (Chandrasekar, Doran, and Bangalore 1996; Grefenstette 1998; Mani, Gates, and Bloedorn 1999; Knight and Marcu 2002; Jing and McKeown 2000; Reizler et al. 2003) and methods for expansion of a multiparallel corpus (Pang, Knight, and Marcu 2003) are other instances of such methods.
---------------------------------------------------
W02-0404:11	159:199	In revising single-document summaries, [Mani et al, 1999] employed rules such as the referencing of pronouns with the most recently mentioned noun phrase.
---------------------------------------------------
W02-0404:12	40:199	Previous research has addressed revision in single-document summaries [Jing & McKeown, 2000] [Mani et al, 1999] and has suggested that revising summaries can make them more informative and correct errors.
---------------------------------------------------
W02-0404:13	66:199	2.3 Revision of single-document summaries [Mani et al, 1999] focused on the revision of single-document summaries in order to improve their informativeness.
---------------------------------------------------
J02-4002:14	10:704	Extracts are often useful in an information retrieval environment since they give users an idea as to what the source document is about (Tombros and Sanderson 1998; Mani et al. 1999), but they are texts of relatively low quality.
---------------------------------------------------
J02-4002:15	11:704	Because of this, it is generally accepted that some kind of postprocessing should be performed to improve the final result, by shortening, fusing, or otherwise revising the material (Grefenstette 1998; Mani, Gates, and Bloedorn 1999; Jing and McKeown 2000; Barzilay et al. 2000; Knight and Marcu 2000).
---------------------------------------------------
P00-1041:16	20:138	More recently, summarizers using sophisticated postextraction strategies, such as revision (McKeown et al. , 1999; Jing and McKeown, 1999; Mani et al. , 1999), and sophisticated grammar-based generation (Radev and McKeown, 1998) have also been presented.
---------------------------------------------------
J02-4001:17	43:155	Some research uses the degree of lexical connectedness between potential passages and the remainder of the text; connectedness may be measured by the number of shared words, synonyms, or anaphora (e.g. , Salton et al. 1997; Mani and Bloedorn 1997; Barzilay and Elhadad 1999).
---------------------------------------------------
J02-4001:18	106:155	The largest task-oriented evaluation to date, the Summarization Evaluation Conference (SUMMAC) (Mani et al. 1998; Firmin and Chrzanowski 1999) included three tests: the categorization task (how well can humans categorize a summary compared to its full text?), the ad hoc task (how well can humans determine whether a full text is relevant to a query just from reading the summary)?
---------------------------------------------------
