D09-1151:1	49:264	Analyze the relation between Nm and Nh by Kurohashi and Sakais method (1999) that exploits an ordinary language dictionary.
---------------------------------------------------
W02-1411:2	30:212	Of course, similarity of meaning and paraphrasability are very closely correlated with each other, and Kurohashi and Sakai (1999) utilize this feature to paraphrase Japanese expressions (in order to comprehend them more easily).
---------------------------------------------------
C00-2128:3	42:166	The Japanese noun phrase A no B roughly corresponds to the English noun phrase B of A, lint it has a nmch broader range of usage (Kurohashi and Sakai, 1999).
---------------------------------------------------
C00-2128:4	148:166	If we need such semantic relations, we must semantically analyze the noun phrases (Kurohashi and Sakai, 1999).
---------------------------------------------------
C04-1174:5	28:198	As a response to these problems and following the work in (Kurohashi and Sakai, 1999), we propose a method to construct Japanese nominal case frames from large corpora, based on an accurate analysis of Nm no Nh phrases using an ordinary dictionary and a thesaurus.
---------------------------------------------------
C04-1174:6	39:198	Based on such an observation, (Kurohashi and Sakai, 1999) proposed a semantic analysis method of Nm no Nh, consisting of the two modules: dictionary-based analysis (abbreviated to DBA hereafter) and semantic featurebased analysis (abbreviated to SBA hereafter).
---------------------------------------------------
