Mostotherworkinthisareaminesrawtext, rather than a database automatically populated via extraction (Hearst, 1999; Craven et al. , 1998).


Semantic roles could also act as an important intermediate representation in statistical machine translation or automatic text summarization and in the emerging field of text data mining (TDM) (Hearst 1999).


This means that the approach for SA should be switched from the rather shallow analysis techniques used for text mining (Hearst, 1999; Nasukawa and Nagano, 2001), where some errors can be treated as noise, into deep analysis techniques such as those used for machine translation (MT) where all of the syntactic and semantic phenomena must be handled.


The emerging technology of information extraction (Appelt and Israel 1997, Hearst 1999) provides a means of gaining access to this information.


Consequently, the goal of text mining (also known as literature mining) systems and algorithms is to assist users find such needles, if these exist at all in the literature haystacks (Hearst 1999).


