When there is no parse rooted in the start category, the parser returns a connected sequence of partial parses which covers the input based on subanalysis probability and a preference for longer and non-lexical subanalysis combinations (e.g. Kiefer et al. , 1999). 
That analysis, rule filtering (Kiefer et al. , 1999), reduces parse times by filtering out mother-daughter unifications that can be determined to fail at compile-time. 
Another option for speeding up parsing that we have not discussed in detail is using a typed grammar without disjunction and speeding up uni cation as done in HPSG grammars (Kiefer et al. , 1999). 
The criteria are partial parse probability and a preference for longer but non-lexical combinations (Kiefer et al. , 1999). 
Secondly, we use techniques developed in (Kiefer et al. , 1999), namely the so-called rule filter and the quick-check method. 
