A review of this literature would be out of place here; but we would like to indicate that the case against decomposition (and hence against conventional translations) is not closed, by offering the fol9 With regard to our system-building objectives, such resort to lexical decomposition is no liability: the need for some use of lexical decomposition to obtain "canonical" representations that facilitate inference is widely acknowledged by AI researchers, and carried to extremes by some (e.g. , Wilks 1974, Schank 1975).


