GLP, a descendant of a version of GSP by M. Kay (1975), has been implemented in InterLISP.


In addition to exploiting the formal MRL grammar, our approach also allows the same learned grammar to be used for both parsing and generation, an elegant property that has been widely advocated (Kay, 1975; Jacobs, 1985; Shieber, 1988).


One of the earliest espousals of the notion of grammar reversability can be found in Kay (1975).


