Current theories propose that the speaker's intentions underlying the use of indirect speech acts can be recognized as a by-product of a more general, independently motivated process of inferring a speaker's plans (Bruce 1983, Cohen and Perrault 1979, Cohen and Levesque 1980, Perrault and Allen 1980, Schmidt 1975, Sidner and Israel 1981).


\["and in the bottom of the blue cap on the main tube (pause) there is a hole"\] 12% 6% D. NEARLY DIRECT REQUESTS \["Look at the bottom of the tube"\] \["The next thing you're gonna look for is" 1% 1% E. LET'S REQUESTS \["Let's go to the little tiny blue cap"\] 5% Recent work of this type (Allen 1979, Appelt 1981, Bruce 1983, Bruce and Newman 1978, Bruce and Schmidt, Cohen 1978, Cohen and Levesque 1980, Cohen and Perrault 1979, Perrault and Allen 1980, Schmidt 1975, Sidner and Israel 1981) has resulted in formal and computational models of communication that have been applied in analyzing dialogues about tasks and stories.


