Bridging anaphora (Clark, 1975) represents a special part of the general problem of anaphora resolution, which has been studied and discussed for various languages and domains (Hahn et al., 1996; Murata et al., 1999; Poesio et al., 2004; Gasperin and Vieira, 2004; Gasperin and Briscoe, 2008). 
Clark (1975)). 
(Clark, 1975), who introduced the term bridging) as the background of our discussion. 
Clark (1975)). 
Also, several researchers have applied it to resolving different types of bridging anaphora (Clark, 1975). 
