For example, Charniak's (1975) paper at this conference raises questions about the "supermarket frame"~ The shopper must get items to the checkout counter with the sometime instrumentality of a shopping cart.


Since we wadted to experiment wlth generality in this system, we wished to separate general knowledge from linguistic knowledge, and for that reason, the actual extraction of items is done using the frame technique (Minaky, 1975; Charniak, 1975).


Other similar kinds of theoretical constructs for organizing multiple srntcnces of stories have been proposed called: "frames" (Minsky, 1975: Charniak, 1975), "scripts" (Schank Q Abelson, 1975), and "commonsense algorithms" (Ricgcr, 1975).


Knowledge structures must possess some capability for detecting the pragmatic, as well as logical, implications of the incomplete data contained in discourse (c.f. , Charniak, 1974; Mlnsky, 1975; Rumelhart & Ortony, 1977; Schank & Abelson, 1977).


