By "semantic primitives" I mean the general sort of item proposed within Artificial Intelligence (AI) by Wllks (1972, 1977), Schank (1973) and within linguistics by Fodor and Katz (1963), Jackendoff (1975) among many others, in both cases.


This thrust of argumentation has sought to establish the central role of spatial concepts in linguistics, and among its best known proponents are Anderson (1971), Fillmore (1977) and Jackendoff (1975).


