Many syntactic formalisms have a similar framework for expressing rules: these include context-free grammars, augmented phrase structure grammars (Heidorn 1975), Programmar (Winograd 1972), the linguistic string parser (Sager 1981), Lifer (Hendrix et al. 1978), and augmented transition networks (ATNs) (Woods 1970). 
Heidorn's (1972, 1975) Natural Language Processor (NLP) is being used to implement the theory of conceptual graphs. 
In computational linguistic background, the system is most closely related to the augmented phrase structure grammars (APSG's) of George Heidorn (1972,1975). 
The system that provides these facilities is PLNLP, or the Programming Language for Natural Language Processing (Heidorn 1975). 
Augmented phrase structure grammars (Heidorn, 1975) encode parsers and translators specifically in this way. 
