Becker, Joe (1975) "The Phrasal Lexicon", in Schank & Webber (eds). 
Operations triggered by the identify of a word include forming initials and known abbreviations, and particularly the recognition of multi-word fixed phrases which we call "polywords" following Becker (1975). 
Becker (1975) presents the idea of the phrasal lexicon as a means of handling canned and idiomatic phrases. 
We have long agreed with Becker's (1975) assertion that many phrases are best treated as lexical units. 
It is well known that thesauri that include phrases are much more effective than those without, and we are believers in the phrasal lexicon described by Becker (1975). 
