Researchers such as Davidson (1982), Grosz (1977), Sidner and Israel (1981), and Webber (1978) have tackled problems such as the resolution of anaphoric references, the tracking of the user's focus of attention, and the generation of cooperative responses.


Pioneering front-end systems such as REL (Thompson and Thompson 1975), LUNAR (Woods, Kaplan, and Nash-Webber 1972), ROBOT (Harris 1977), "PLANES (Waltz 1978), REQUEST (Plath 1976), TORUS (Mylopoulos et al. 1976), and RENDEZVOUS (Codd et al. 1978) experimented with, among other things, various parsing formalisms (e.g. semantic grammars, transformational grammars, and augmented transition networks); different knowledge representation schemes (e.g. using production systems or semantic networks); and the use of clarification dialogues in disambiguating a user's query.


An alternative approach has been suggested by Bonnie \[Nash-\]Webber (Nash-Webber and Reiter 1977; Webber 1978a, 1978b), wherein a set of rules is applied to a logical-form representation of the text to derive the set of entities that that text makes available for subsequent reference.


