These inferences have been studied in the context of natural language query systems in Kaplan (1978), Kaplan and Joshi (1978), and Kaplan (1979). 
Kaplan (1978) suggests an alternative heuristic for false extensional presuppositions in a data base environment. 
Consider the following example from Kaplan and Joshi (1978): "Which programmers in Administration work on project 6471"? 
In data base access, the system might inform the user of the false presupposition and suggest alternative queries (Kaplan, 1978), since the user does not usually benefit from the empty set as a response. 
This characteristic of natural language updates suggests that the generation of candidate updates can be performed as a language driven inference (Kaplan 1978) without severely limiting the class of updates to be examined. 
