Fred J. Damerau References Charniak, Eugene (1978).


A good deal of experimental and theoretical work has gone into determining how to make inferences, what inferences to make, how to stop making inferences, etc. For recent examples, see Charniak (1978), Minsky (1975), Schank and Abelson (1977).


Charniak (1978) points out that (4-5) is somehow sufficient to invoke the MAGICIAN frame: (4-5) The woman waved as the man on stage sawed her in half.


Charniak (1978) has shown that the frameselection problem (which is here identical to the initial focus selection problem, since the focus is just the frame representing the theme of the discourse) is in fact extremely difficult, and is not in the most general case amenable to solution by either strictly top-down or bottom-up methods.


