History of the Problem This note discusses the problem of logical-form equivalence, a problem in natural language generation first noted in print by Douglas Appelt (1987). 
Bidirectional grammar is helpful in maintaining tile grammar/lexicon (Appelt, 1987). 
1 Logic in GRE A key question regarding the foundations of Natural Language Generation (NLG) is the problem of logical form equivalence (Appelt 1987). 
This is mainly due to the clear theoretical and practical advantages of bidirectional grammar use (see, among others, Appelt, 1987). 
Appelt 1987; Mann 1987; McDonald 1987; Shieber 1988; Jacobs 1988). 
