However, like some leading researchers in generation, we argue that it is of paramount importance to first know the kind of information that should be coded in the lexicon, which means to pay more attention to "the nature of words" (McDonald, 1988) and to have a "real knowledge of \[the\] lexical semantics", as was pointed out by Marcus (1987): "In some important sense, \[the\] systems have no real knowledge of lexical semantics They use fragments of linguistic structure which eventually have words as their frontiers, but have little or no explicit knowledge of what these words mean".


