TEMPORAL REASONING IN NATURAL LANGUAGE UNDERSTANDING: THE TEMPORAL STRUCTURE OF THE NARRATIVE Alexander Nakhimovsky Department of Computer Science Colgate University Hamilton, NY 13346 USA CSNet: sasha@colgate Abstract This paper proposes a new framework for discourse analysis, in the spirit of Grosz and Sidner (1986), Webber (1987a,b) but differentiated with respect to the type or genre of discourse.


This paper concentrates on narratives and introduces the notions of temporal focus (proposed also in Webber (1987b)) and narrative move.


