4 MERCURY Analysis We have been collecting MERCURY data over the telephone for the past several years (Seneff and Polifroni, 2000), involving user interactions with the system to make flight reservations. 
Some other systems in the program are Ward and Pellom (1999), Seneff and Polifroni (2000) and Rudnicky et al (1999). 
MITs Mercury flight reservation system uses a dialogue control strategy based on a set of ordered rules as a mechanism to manage complex interactions (Seneff and Polifroni, 2000). 
Some other systems in the program are Ward and Pellom (1999), Seneff and Polifroni (2000) and Rudnicky et al (1999). 
In Sections 3 and 4, we describe the error detection and recovery strategies that have been adopted in our MERCURY flight reservation system (Seneff, 2002; Seneff and Polifroni, 2000), and we provide an analysis of the degree to which error recovery was successful, specifically for the case of entering a source or destination city name. 
