Bikel 629 Collins Head-Driven Statistical Models for NL Parsing (2000) has developed generative statistical models that integrate word sense information into the parsing process. 
An approach similar to this is taken by Bikel (2000), in the context of statistical parsing. 
Based on the lexicalized grammars, Bikel (2000) attempts at combining parsing and word sense disambiguation in a unified model, using a subset of SemCor (Miller et al., 1994). 
Bikel (2000) evaluates this model in a parsing context with sense information from WordNet, but does not get improvements on parsing performance. 
Recently, in order to continue our work combining word sense with parsing (Bikel 2000) and the study of language-dependent and -independent parsing features (Bikel and Chiang 2000), we built a multilingual parsing engine that is capable of instantiating a wide variety of generative statistical parsing models (Bikel 2002). 
