Chen and Lin (2000) is the only study that used contextual information for the same task.


While contextual information is the primary source of information used in WSD research and has been used for acquiring semantic lexicons and classifying unknown words in other languages (e.g. , Roark and Charniak 1998; Ci190 aramita 2003; Curran 2005), it has been used in only one previous study on semantic classification of Chinese unknown words (Chen and Lin, 2000).


According to the data in (Chen and Lin, 2000), about 5.51% of unknown words is encountered in their sense-tagging task of Chinese corpus.


