The first step in the linguistic analysis module lemmatises the inflected words using Minnen et al.s (2000) morpha lemmatiser. 
Tokenisation, species word identification and chunking were implemented in-house using the LTXML2 tools (Grover and Tobin, 2006), whilst abbreviation extraction used the Schwartz and Hearst abbreviation extractor (Schwartz and Hearst, 2003) and lemmatisation used morpha (Minnen et al. , 2000). 
term is modi ed by a prepositional phrase The relation tuple is then converted to root form using the Sussex morphological analyser (Minnen et al. , 2000) and the POS tags are removed. 
The first step in the linguistic analysis module lemmatises the inflected words using Minnen et al.s (2000) morpha lemmatiser. 
The tokenisation, sentence boundary detection, head word identification and chunking components were implemented with the lt-xml2 tools (Grover and Tobin, 2006), and the lemmatisation used morpha (Minnen et al., 2000). 
