Except for one base chunker, which uses the memory-based machine learning systern TiMBL, 1 all modules are based on WPDV models (van Halteren, 2000a).


van Halteren (2000a).


5) In the LOB WPDV model, the Penn wordclass tags (as produced by the Brill tagger) are replaced by the output of a WPDV tagger trained on 90% of the LOB corpus (van Halteren, 2000b).


WPDV has since evolved, using more parameters and more involved weighting schemes, and also been tested on tasks other than tagger combination (van Halteren 2000a, 2000b).


