We applied majority voting to the output of the six systems while using the same approach as Tjong Kim Sang (2000b): combining start and end positions of chunks separately and restoring the chunks from these results. 
Tjong Kim Sang (2000a) has applied a combination of memory-based learners to this data set and obtained Fa25a33a26a29a28 = 94.90, an improvement on Ramshaw and Marcuss 93.3. 
3.1 Chunking Chunking was the shared task of CoNLL-2000, the workshop on Computational Natural Language Learning, held in Lisbon, Portugal in 2000 (Tjong Kim Sang and Buchholz, 2000). 
In the course of this project we have evaluated another combination method: BEST-N MAJORITY VOTING (Tjong Kim Sang et al. , 2000). 
Various machine learning approaches have been proposed for chunking (Ramshaw and Marcus, 1995; Tjong Kim Sang, 2000a; Tjong Kim Sang et al. , 2000; Tjong Kim Sang, 2000b; Sassano and Utsuro, 2000; van Halteren, 2000). 
