Many standard ML techniques have been tried, such as Bayesian learning, Exemplar based learning, Decision Lists, and recently margin-based classifiers like Boosting and Support Vector Machines (Escudero et al. , 2000a, 2000b, 2000c, 2000d, 2001; Martnez and Agirre, 2000).


Several supervised ML algorithms have been applied to WSD (Ide and Veronis, 1998), (Escudero et al. , 2000): Decision Lists, Neural Networks, Bayesian classifiers, Boosting, Exemplarbased learning, etc. We report here the exemplar-based approach developed by UNED and tested at the Senseval-3 competition in the lexical sample tasks for English, Spanish, Catalan and Italian.


