6.3 Text Segmentation A number of researchers, (e.g. , Li and Yamanishi (2000); Hearst (1997)), have developed text segmentation systems.


We compared the use of different initializations on 500 documents created from Reuters-21578, in a manner similar to Li and Yamanishi (2000).


Research projects on text segmentation have focused on broadcast news stories (Beeferman et al. , 1999), expository texts (Hearst, 1994) and synthetic texts (Li and Yamanishi, 2000; Brants et al. , 2002).


