WPDV has since evolved, using more parameters and more involved weighting schemes, and also been tested on tasks other than tagger combination (van Halteren 2000a, 2000b). 
Van Halteren (2000) used Weighted Probability Distribution Voting (WPDV) for combining the results of four WPDV chunk taggers and a memory-based chunk tagger. 
The previously second best system was a combination of five different WPDV models, with an overall a132a21a133 a110a76a37 value of a209 a204 a41a204a136a145 (van Halteren, 2000). 
Various machine learning approaches have been proposed for chunking (Ramshaw and Marcus, 1995; Tjong Kim Sang, 2000a; Tjong Kim Sang et al. , 2000; Tjong Kim Sang, 2000b; Sassano and Utsuro, 2000; van Halteren, 2000). 
In addition, our method also outperforms other methods based on the weighted voting(van Halteren, 2000; Tjong Kim Sang, 2000b). 
