also a prior version of the system reported in Teufel and Moens [2000] and Teufel [1999]).


Knowledge of subjective language would also be useful in ame recognition (Spertus, 1997;; Kaufer, 2000), email classi cation (Aone et al. , 2000), intellectual attribution in text (Teufel and Moens, 2000), recognizing speaker role in radio broadcasts (Barzilayet al. , 2000), review mining (Terveen et al. , 1997), generation and style (Hovy, 1987), clustering documents by ideological point of view (Sack, 1995), and any other application that would bene t from knowledgeofhowopinionatedthe languageis, and whether or not the writer purports to objectively present factual material.


Our task is closer to the work of Teufel and Moens (2000), who looked at the problem of intellectual attribution in scientific texts.


The ability to explicitly identify these sections in unstructured text could play an important role in applications such as document summarization (Teufel and Moens, 2000), information retrieval (Tbahriti et al. , 2005), information extraction (Mizuta et al. , 2005), and question answering.


This has lent itself to automatic text summarisation because documents of this genre tend to be structured in predictable ways and to contain formalised language which can aid the summarisation process (e.g. cue phrases such as the importance of, to summarise, we disagree) (Teufel and Moens, 2002), (Teufel and Moens, 2000).


