The resulting approach is related to [Stone and Doran, 1997; Cassell et al. , 2000].


My own slow progress (Cassell et al., 2000; Stone et al., 2003; Koller and Stone, 2007) shows that theres still lots of hard work needed to develop suitable techniques.


In previous studies of multimodal generation, gestures were determined according to the instruction content (Andre, Rist, & Muller, 1999; Rickel & Johnson, 1999), the task situation in a learning environment (Lester, Stone, & Stelling, 1999), or the agents communicative goal in conversation (Cassell et al. , 1994; Cassell, Stone, & Yan, 2000).


