It was originally proposed in (Li and Abe, 1998), and then adopted in our previous method for automatically extracting systematic polysemy(Tomuro, 2000).


3 Clustering Systematic Polysemy Using the tree-cut technique described above, our previous work (Tomuro, 2000) extracted systematic polysemyfromWordNet.


In our previous work (Tomuro, 2000), we applied this method to a small subset of WordNet nouns and showed potential applicability.


