7.3 : so we ship one 7.4 : boxcar 7.5 : of oranges to Elmira 7.6 : and that takes another 2 hours Previous studies of discourse deixis annotation showed that these are extremely difcult judgments to make (Eckert and Strube 2000; Navarretta 2000; Byron 2002), except perhapsforidentifyingthetypeofobject(PoesioandModjeska2005),sowesimplied the task by only requiring our participants to identify the boundaries of the area of text in which the antecedent was introduced.


