W09-0613:1	4:89	1 Introduction Over the past several years, a significant consensus has emerged over the definition of the realisation task, through the development of realisers such as REALPRO (Lavoie and Rambow, 1997), ALETHGEN (Coch, 1996), KPML (Bateman, 1997), FUF/SURGE (Elhadad and Robin, 1996), HALOGEN (Langkilde, 2000), YAG (McRoy et al., 2000), and OPENCCG (White, 2006).
---------------------------------------------------
W09-0613:2	37:89	This is a feature that SimpleNLG shares with YAG (McRoy et al., 2000).
---------------------------------------------------
