Systems developed under this program include CMUs script-based dialogue manager, in which the travel itinerary is a hierarchical composition of frames (Xu and Rudnicky, 2000).


The University of Colorado framework also has a form-based architecture (Pellom et al. 2001), while CMU and Bell Labs frameworks allow the specification of deep task hierarchies (Wei and Rudnicky 2000, Potamianos et al. 2000).


DITE or frame-based, with no explicit dialogue model, but task is explicitly represented as a frame or a form (Goddeau et al. , 1996), a task description table (Lin et al. , 1998), a topic forest (Wu et al. , 2000), or an agenda (Xu and Rudnicky, 2000), etc. Both system and user may take the initiative.


