P06-2013:1	15:216	Chinese chunking is a difficult task, and much work has been done on this topic(Li et al. , 2003a; Tan et al. , 2005; Wu et al. , 2005; Zhao et al. , 2000).
---------------------------------------------------
W02-1818:2	147:149	Zhao et al. , (2000) Tie-jun ZHAO, et al. Statistics Based Hybrid Approach to Chinese Base Phrase Identification, In Proceedings of the Second Chinese Language Processing Workshop, ACL 2000, 73-77.
---------------------------------------------------
