W01-0802:1	98:184	5 Evidence from Other Projects After making the above observations, we examined think-aloud transcripts from an earlier project at the University of Aberdeen, STOP (Reiter et al 2000), which involved building an NLG system that produced smoking-cessation letters from smoking questionnaires.
---------------------------------------------------
W01-0802:2	28:184	Human experts are often consulted with regard to the details of content rules, especially when schemas are used for content determination (Goldberg et al 1994, McKeown et al 1994, Reiter et al 2000); but they rarely seem to be consulted (as far as we can tell) when deciding on the general algorithm or strategy to use for content determination.
---------------------------------------------------
W01-0802:3	18:184	This model is based on extensive knowledge acquisition (KA) activies that we have carried out in the SUMTIME project (Sripada, 2001), and also matches observations made during KA activities carried out in the STOP project (Reiter et al 2000).
---------------------------------------------------
W03-0611:4	111:143	Perhaps in retrospect this should not have been a surprise, because we have also observed changes over time in how people write in a previous project (Reiter et al. , 2000).
---------------------------------------------------
P01-1057:5	175:203	6 Other Evaluation Techniques in STOP The clinical trial was by far the biggest evaluation exercise in STOP, but we also performed some smaller evaluations in order to test our algorithms and knowledge acquisition methodology (Reiter, 2000; Reiter et al. , 2000).
---------------------------------------------------
P01-1057:6	192:203	While many speech recognition and natural-language understanding applications can be tested by comparing their output to a human-produced gold standard' (for example, speech recogniser output can be compared to a human transcription of a speech signal), this to date has been harder to do in NLG, especially in applications such as STOP where there are no human experts (Reiter et al. , 2000) (there are many experts on personalised oral communication with smokers, but none on personalised written communication, because no one currently writes personalised letters to smokers).
---------------------------------------------------
