Systems such as (Ng et al. , 2000) make explicit use of relative rank in their algorithms and now we understand why this is effective.


In addition, a number of researchers have built systems to take reading comprehension examinations designed to evaluate childrens reading levels (Charniak et al. , 2000; Hirschman et al. , 1999; Ng et al. , 2000; Riloff and Thelen, 2000; Wang et al. , 2000).


As was observed by (Riloff and Thelen, 2000) and (Charniak et al. , 2000), the correct answer sentence often precedes/follows the sentence with the highest number of matching words.


Subsequently, (Ng et al. , 2000) used a machine learning approach of decision tree and achieved the accuracy of 39.3%.


For example, it has been pointed out by (Charniak et al. 2000) that the verb seems to be especially important for recognizing that a passage sentence is related to a specific question.


