Roland et al. #282000#29 #0Cnd that subcategorization frequencies for certain verbs vary signi#0Ccantly between the Wall Street Journal corpus and the mixed-genre Brown corpus, but that they vary less so between genre-balanced British and American corpora.


However, this sense can vary across corpora (Roland et al. , 2000), and assuming a single sense is inadequate for an important group of medium and high frequency verbs whose distribution of senses in balanced corpus data is flat rather than zipfian (Preiss and Korhonen, 2002).


