Yang et al (2000) pioneered this work by using sememe co-occurrence information in sentences from a large corpus to achieve an accuracy of 71%.


Unlike the work of Yang et al (2000) and Wang (2002) that applied unsupervised methods using sense definitions in HowNet, the paper is the first study to use a supervised learning method with the availability of the HowNet sense tagged corpus.


There are, however, several difficulties to WSD (Yang et al, 2000): (i) The evaluation of word sense disambiguation system is not yet standardized.


