These include systems for machine translation (Viegas et al. , 1998), question answering, (Harabagiu et al. , 2001; Clark et al. , 2003), and information retrieval (Mihalcea and Moldovan, 2000).


Accuracy without and with the help of WordNet 2-level hypernym on 100,000 news titles for training set Method SOM SOM with WordNet 1 88.85% 89.94% 2 91.07% 90.65% Discussion and Conclusion In the past there had been no consistent conclusions about the value of WordNet for information retrieval tasks (Mihalcea and Moldovan 2000).


This semantic dictionary is useful in extracting the real concept of a word, a query or a document in the field of text mining (Richardson 1994; Richardson and Smeaton 1995; Voorhees 1993; Voorhees 1998; Scott and Matwin 1998; Gonzalo et al. 1998; Moldovan and Mihalcea 1998; Moldovan and Mihalcea 2000).


