Note that unsupervised segmentation is different from, if not more complex than, word extraction, in that the former must carry out the segmentation task for a text, for which a segmentation (decoding) algorithm is indispensable, whereas the latter only acquires a word candidate list as output (Chang and Su, 1997; Zhang et al., 2000).


We take the logarithm of FSR 3Although there have been many existing works in this direction (Lua and Gan, 1994; Chien, 1997; Sun et al., 1998; Zhang et al., 2000; SUN et al., 2004), we have to skip the details of comparing MI due to the length limitation of this paper.


Some research has dealt with other languages, such as French (Michiels and Dufour, 1998) or Chinese (Zhang et al. , 2000), but there has been no computationally tractable research on the topic for Russian.


