7 Related Work While there have been many successful computeraided translation systems both for research and as commercial products (Bowker, 2002; Langlais et al., 2000), collaborative translation has not been as widely explored.


3 Interactive Machine Translation The idea of interactive machine translation has been greatly advanced by work carried out in the TransType project (Langlais et al., 2000), with the focus on a sentence-completion paradigm.


An interesting approach was pioneered by the TransType project (Langlais et al., 2000).


