The work described in this paper is closely related to the area of multi-document summarization (Barzilay et al. , 1999; Mani and Bloedorn, 1999; McKeown and Radev, 1995; Radev, 2000), where related documents are analyzed to use frequently occurring segments for identifying relevant information that has to be included in the summary. 
Inspired by RST, Radev (2000) proposed the cross-document structure theory (CST) for multidocument analysis, such as multi-document summarization, and topic detection and tracking. 
2.2 Informativity (Radev, 2000) describes 24 cross-document relations that can hold between their segments, one of which is the subsumption (or entailment) relation. 
Inspired by RST, [Radev, 2000] endeavored to establish a Cross-document Structure Theory (CST) that is more appropriate for MDS. 
LexRank uses crosssentence informational subsumption (Radev, 2000) to this end, but MMR (Carbonell and Goldstein, 1998) has also been widely used in the text summarization community. 
