This resource has already been used on Word Sense Disambiguation (Magnini and Strapparava, 2000), but it has not made use of glosses information.


Still, the approach can be very useful for language engineering applications in which only domain disambiguation (versus sense disambiguation) is required, such as information retrieval (Gonzalo et al. 1998) and content-based user modeling (Magnini and Strapparava 2000).


This resource has already been used on Word Sense Disambiguation (Magnini and Strapparava, 2000), but it has not made use of glosses information.


The most notable exceptions are the work of Magnini and Strapparava (2000) and Suarez & Palomar (2002).


