We have considered three types of semantic relation, previously introduced in (Gonzalo et al. , 2000): a0 metonymy (semantic contiguity), for example, yew-tree and yew-wood or post-letters and postsystem.


Conceptual relations can be used to define measures of semantic distance (Sussna, 1993; Agirre and Rigau, 1996; Resnik, 1995), but topic relatedness is not well captured by wordnet relations, and this is a fundamental parameter to estimate sense similarity in many NLP applications (Gonzalo et al. , 2000).


5.3.4 Metonymy As for metonymy, the distribution of proximity indexes indicates that this kind of relation seems to include different subpatterns (Gonzalo et al. , 2000).


Thus it is useful in knowledge-intensive NLP tasks such as discourse analysis, IE and MT. More recently, (Gonzalo et al. , 2000)alsodiscussespotential usefulnessof systematic polysemy for clustering word senses for IR.


