W00-0726:1	99:150	Vilain and Day (2000) approached the shared task in three different ways.
---------------------------------------------------
L08-1457:2	18:52	SUMMAC (Mani et al., 1998) and DUC (TIDES, 2000) were organised in the field of automatic summarisation, TREC conferences5 evaluate different aspects of text retrieval, whilst CLEF campaigns6 attempt the similar tasks in a mu</context> </contexts> <marker>Mani, Firmin, House, Chrzanowski, Klein, Hirshman, Sundheim, Obrst, 1998</marker> <rawString>Inderjeet Mani, Therese Firmin, David House, Michael Chrzanowski, Gary Klein, Lynette Hirshman, Beth Sundheim, and Leo Obrst.
---------------------------------------------------
