The MDA system developed at XRCE (Dymetman et al. , 2000; Brun et al. , 2000) uses a formalism inspired from Definite Clause Grammars (Pereira and Warren, 1980) that encodes both the abstract semantic syntax of well-formed documents and the concrete syntax for the documents in several languages.5 MDA grammars contain the definition of semantic objects of a given semantic type, which are used to build typed abstract semantic trees.


2 MDA: A semantics-based document authoring system The MDA (Multilingual Document Authoring) system [Brun et al 2000] is an instance (descended from Rantas Grammatical Framework [Ranta 2002]) of a text-mediated interactive natural language generation system, a notion introduced by [Power and Scott 1998] under the name of WYSIWYM.


der development at Xerox Research Centre Europe (see (Brun et al. , 2000) for a more extended description of this project).


