W03-1715:1	142:190	Sections of the Chinese Sinica Treebank (Huang et al. , 2000) are used as seed-treebank and gold standard for parsing evaluation.
---------------------------------------------------
I05-6003:2	28:256	The brief introductions of the CCTB and the PCTB are given as below (Table 1 is a brief comparison between the CCTB and the PCTB): (1) CCTB: the CCTB is developed in traditional Chinese texts (BIG5 encoded) taken from the Academia Sinica Balanced Corpus 3.0 (ASBC3) at the Academia Sinica, Taiwan (Chen et al. , 1996; Chen et al. , 1999; Huang et al. , 2000, Chen et al. , 2003; Chen et al. , 2004).
---------------------------------------------------
