As an architecture designed to facilitate diverse and integrative research on IS, ANNIS can import formats from a broad variety of tools from NLP and manual annotation, the latter including EXMARaLDA (Schmidt, 2004), annotate (Brants and Plaehn, 2000), Synpathy (www.lat-mpi.eu/tools/synpathy/), MMAX2 (Mller and Strube, 2006), RSTTool (O'Donnell, 2000), PALinkA (Orasan, 2003), Toolbox (Busemann & Busemann, 2008) etc. These tools allow researchers to annotate data for syntax, semantics, morphology, prosody, phonetics, referentiality, lexis and much more, as their research questions require.


