2.2 The 100M Words of the BNC One hundred million words is a large enough corpus for many empirical strategies for learning about language, either for linguists and lexicographers (Baker, Fillmore, and Lowe 1998; Kilgarriff and Rundell 2002) or for technologies that need quantitative information about the behavior of words as input (most notably parsers [Briscoe and Carroll 1997; Korhonen 2000]).


