1 Introduction As part of the RAGS (Reference Architecture for Generation Systems) project, Mellish et al (2000) introduces a framework for the representation of data in NLG systems, the RAGS data model.


In order to accommodate this result, a process model was sketched which aimed to support both pipelines and more complex control regimes in a flexible but structured way (see (Cahill et al. , 1999),(RAGS, 2000)).


This is not the first such realisation: Cahill et al. , (2000) describes a partial re-implementation of the Caption Generation System (Mittal et al. , 1999) which includes an objects and arrows whiteboard.


