We use existing generation resources for English  SURGE [Elhadad, 1992] for syntactic realization and the lexical chooser described in [Jing et al. , 2000] and the HUGG grammar for syntactic realization in Hebrew [Netzer, 1997].


In Verbnet, verbs are classified following Levins classes [Levin, 1993] and thus its representation is easily adjustable with our verb lexicon [Jing et al. , 2000], which combined information on argument structure of verbs from Levin, Comlex [Macleod and Grishman, 1995] and WordNet.


