W02-1304:1	50:125	Research in the acquisition of subcategorization information, selectional preferences, in thematic role assignments and diathesis alternations (Agirre and Martnez 2001, 2002, McCarthy and Korhonen, 1998; Korhonen et al. , 2000; McCarthy 2001), domain information (Magnini and Cavagli 2000), topic signatures (Agirre et al. 2001b), lexico-semantic relations between words (Agirre et al. 2002) etc. has obtained encouraging results.
---------------------------------------------------
C02-1040:2	64:173	Along with the techniques given in these papers, (Sarkar and Zeman, 2000; Korhonen et al. , 2000) also discuss other methods for hypothesis testing such the use of the t-score statistic and the likelihood ratio test.
---------------------------------------------------
C02-1040:3	10:173	This is often termed as the classification of verb diathesis roles or the lexical semantics of predicates in natural language (see (Levin, 1993; McCarthy and Korhonen, 1998; Stevenson and Merlo, 1999; Stevenson et al. , 1999; Lapata, 1999; Lapata and Brew, 1999; Schulte im Walde, 2000)).
---------------------------------------------------
P08-3010:4	111:124	The Cambridge system has been regularly improved and evaluated; and it represents the state-of-the-art perfomance on the task (Briscoe and Carroll, 1997; Korhonen et al., 2000; Preiss et al., 2007).
---------------------------------------------------
