Finally, MEAD is a widely used multi-document summarization and evaluation platform (Radev et al., 2000). 
3.1 Evaluation methods We use the Relative Utility (RU) method (Radev et al. , 2000) to compare our various summaries. 
3.2 Extractive Summarizer: MEAD* The  extractive  approach  is  represented  by MEAD*, which is adapted from the open source summarization framework MEAD (Radev et al., 2000). 
3.1.3 Relative Utility Relative Utility (RU) (Radev et al. , 2000) is tested on a large corpus for the first time in this project. 
(2000), Deerwester et al. 
