The formula for calculating both the expected values (E) and the Log-Likelihood have been described in detail by (Rayson and Garside, 2000).


We have implemented the procedure described in (Rayson and Garside, 2000) using unigrams only.


For instance, the frequency of occurrence of a word in a domain-specific corpus can be compared with its frequency of occurrence in a reference corpus (Rayson and Garside, 2000; Baroni and Bernardini, 2004).


This table also gives the number of key words, i.e., single-word terms extracted by comparing the frequency of occurrence of words in both corpora for each language (Rayson and Garside, 2000).


We implemented the formula for both the expected values and the Log-Likelihood values as described by (Rayson and Garside, 2000).


