Prior research in Chinese unknown words mostly focused on proper nouns (Lee 1993, Lee, Lee and Chen 1994, Huang, Hong and Chen 1994, Chen and Chen 2000).


The focus of most other Chinese unknown word research is on identification of proper nouns such as proper names (Lee 1993), personal names (Lee, Lee and Chen 1994), abbreviation (Huang, Hong and Chen 1994), and organization names (Chen & Chen 2000).


