Automatic detection of such argument alternations is important to acquisition of verb lexical semantics (Dang et al. , 2000; Dorr and Jones, 2000; Merlo and Stevenson, 2001; Schulte im Walde and Brew, 2002; Tsang et al. , 2002), and moreover, may play a role in automatic processing of language for applied tasks, such as question-answering (Katz et al. , 2001), information extraction (Riloff and Schmelzenbach, 1998), detection of text relations (Teufel, 1999), and determination of verbparticle constructions (Bannard, 2002).


Furthermore, we note that recent work indicates that verb alternations may also play a role in automatic processing of language for applied tasks, such as question-answering (Katz et al. , 2001), detection of text relations (Teufel, 1999), and determination of verb-particle constructions (Bannard, 2002).


