They are based mainly on descriptions in Bickmore (et al. , 2004) and Cassell (et al. , 2000), and on recommendations in Cassell and Thorisson (1999), Cassell (et al. , 2001), Chovil (1992), Kendon (1990) and San-Segundo (et al. , 2001), to which we have added a few suggestions of our own.


Different strategies are taken depending on the level of confidence in the correctness of the user locution as captured by the speech recognition unit (San-Segundo et al. , 2001).


(San-Segundo et al. , 2001), inter alia).


