With advances in speech technology, several projects have begun to incorporate basic spoken language capabilities into their systems (Mostow and Aist, 2001; Fry et al. , 2001; Graesser et al. , 2001; Rickel and Johnson, 2000).


Other research projects (Mostow and Aist, 2001; Fry et al. , 2001) have shown that basic spoken natural language capabilities can be implemented quite effectively in computer tutoring systems.


