P02-1053:1	45:216	Past work has demonstrated that adjectives are good indicators of subjective, evaluative sentences (Hatzivassiloglou 2 http://www.epinions.com & Wiebe, 2000; Wiebe, 2000; Wiebe et al. , 2001).
---------------------------------------------------
P02-1053:2	118:216	Other related work is concerned with determining subjectivity (Hatzivassiloglou & Wiebe, 2000; Wiebe, 2000; Wiebe et al. , 2001).
---------------------------------------------------
C04-1145:3	35:195	SO can be used to classify reviews (e.g. , movie reviews) as positive or negative (Turney, 2002), and applied to subjectivity analysis such as recognizing hostile messages, classifying emails, mining reviews (Wiebe et al. , 2001).
---------------------------------------------------
P08-1034:4	39:177	For example, it has been observed that texts often contain multiple opinions on different topics (Turney, 2002; Wiebe et al., 2001), which makes assignment of the overall sentiment to the whole document problematic.
---------------------------------------------------
