Several works have addressed the problems of representing temporal information in natural language (Setzer, 2001; Hobbs and Pan, 2004; Saur et al. , 2006), extracting and/or anchoring (normalizing) temporal and event related expressions (Wiebe et al. , 1998; Mani and Wilson, 2000; Schilder and Habel, 2001; Vazov, 2001; Filatova and Hovy, 2001), and discovering the ordering of events (Mani et al. , 2003).


A few tasks can be distinguished in that respect: detecting dates and temporal markers detecting event descriptions finding the date of events described figuring out the temporal relations between events in a text The first task is not too difficult when looking for dates, e.g. using regular expressions (Wilson et al. , 2001), but requires some syntactic analysis in a larger framework (Vazov, 2001; Shilder and Habel, 2001).


