Our new feature will be: CCBYA3C1BWBY CRD3D2CUCTD6CTD2CRCT B7CCBYA3 C1BWBY DBD3D6CZD7CWD3D4 B7 CCBY A3 C1BWBY CPD2D2D3D9D2CRCTD1CTD2D8.Giving these linguistic observations we divided the set of features into three groups, as we mentioned also in (Tzoukermann et al. , 2001): 1) one associated with the head of the noun phrase; 2) one associated with the whole NP and 3) one that represents the new TF*IDF measure discussed above.


