From the side of the Language Engineering there are initiatives for describing standards and (Calzolari et al. , 2001) present such an initiative, the ISLE project, which is the continuation of the EAGLES initiative.


While (Calzolari et al. , 2001) concentrate on the description of the task of the ISLE computational lexicon working group and address the topic of metadata for encoding multilingual lexical resources, (Broeder and Wittenburg, 2001) presents the work of the ISLE Metadata initiative (IMDI), which is directly relevant for the topic addressed here.


