REG is helpful for tasks such as text generation and information summarization (Kan et al., 2001).


OSU-2: Generating Referring Expressions with a Maximum Entropy Classifier Emily Jamison Department of Linguistics The Ohio State University Columbus, OH 43210, USA jamison@ling.osu.edu Dennis Mehay Department of Linguistics The Ohio State University Columbus, OH 43210, USA mehay@ling.osu.edu Abstract Selection of natural-sounding referring expressions is useful in text generation and information summarization (Kan et al., 2001).


