W01-1402:1	64:164	Moore (2001) describes this technique in detail, while Pinkham & Corston-Oliver (2001) describes its integration with MSR-MT and investigates its effect on translation quality.
---------------------------------------------------
W01-1411:2	136:168	The improvements in end-to-end performance due to these additions in a French-to-English translation task are described elsewhere (Pinkham and Corston-Oliver, 2001).
---------------------------------------------------
