1 Extraction of Temporal Information and Scene Visualization Carsimisaprogram thatgenerates 3Dscenes from narratives describing road accidents (Johansson et al. , 2005; Dupuy et al. , 2001).


3 Carsim Carsim (Egges et al. , 2001; Dupuy et al. , 2001) is a program that analyzes texts describing car accidents and visualizes them in a 3D environment.


We started from a first incomplete model (Dupuy et al. , 2001) and we manually constructed the representation of about 50 texts until we had reached a sufficient degree of expressivity.


