1 Introduction Much work on paraphrase generation has focussed on lexical variation and syntactic transformation within individual sentences (Barzilay and McKeown, 2001; Carroll et al. , 1999; Dras, 1999; Inui and Nogami, 2001; Kozlowski et al. , 2003; Langkilde and Knight, 1998; Takahashi et al. , 2001; Stede, 1999).


This is in contrast to most existing paraphrase generators, which are constrained to vary only the first or second of these levels (Barzilay and McKeown, 2001; Carroll et al. , 1999; Dras, 1999; Inui and Nogami, 2001; Kozlowski et al. , 2003; Langkilde and Knight, 1998; Takahashi et al. , 2001; Stede, 1999).


2 Motivation, target, and related work 2.1 Motivation One of the critical issues that we face in paraphrase generation is how to develop and maintain knowledge resources that covers a sufficiently wide range of paraphrasing patterns such as those indicating that to make an attempt can be paraphrased into to attempt, and that potential can be paraphrased into possibility. Several attempts have been made to develop such resources manually (Sato, 1999; Dras, 1999; Inui and Nogami, 2001); those work have, however, tended to restrict their scope to specific classes of paraphrases, and cannot be used to construct a sufficiently comprehensive resource for practical applications.


Textual aspects of readability will also need to be considered, as discussed in (Inui and Nogami, 2001; Siddahrthan, 2003).


