C02-1011:1	40:167	Nagata et al (2001), for example, proposed to collect partial parallel corpus data on the web to create a translation dictionary.
---------------------------------------------------
W06-1905:2	43:193	Instead of combining multiple translation candidates with a disjunctive query operator (Isozaki et al. , 2005), the TM selects the best combination of translated keywords from several sources: Machine Readable Dictionaries (MRDs), Machine Translation systems (MTs) and Web-mining-Based Keyword Translators (WBMTs) (Nagata et al. , 2001, Li et al. , 2003).
---------------------------------------------------
P06-1081:3	30:271	2 Concept Unification The essence of the concept unification of terms in different languages is similar to that of the query translation for cross-language information retrieval (CLIR) which has been widely explored (Cheng et al. , 2004; Cao and Li, 2002; Fung et al. , 1998; Lee, 2004; Nagata et al. , 2001; Rapp, 1999; Zhang et al. , 2005; Zhang and Vine, 2004).
---------------------------------------------------
W06-1703:4	138:139	One of them is that based on collecting partially bilingual texts through the search engine (Nagata and others, 2001; Huang et al. , 2005).
---------------------------------------------------
N09-1005:5	13:180	 Extraction of parallel examples from web queries, using bootstrap dictionaries, e.g., (Nagata et al., 2001; Oh and Isahara, 2006; Kuo et al., 2006; Wu and Chang, 2007).
---------------------------------------------------
