For example, (Uchimoto et al. , 2001) embeded OOV models in MEMM-based word segmenter (with POS tagging). 
There is also a related work on this line in Japanese (Uchimoto et al. , 2001). 
They proposed a morphological analysis method based on a maximum entropy (ME) model (Uchimoto et al. , 2001). 
First and second OOV extraction modules use the output of a Maximam Entropy Markov Model (MEMM)-based word segmenter (McCallum et al. , 2000) (Uchimoto et al. , 2001). 
We thank Xiaodan Zhu for his early contribution, and the three reviewers, one of whom alerted us the related work of (Uchimoto et al. , 2001). 
