We do this with a clause identifier (Hachey, 2002) built using the CoNLL-2001 shared task data (Sang and Dejean, 2001). 
Many studies have been made on clause segmentation (Carreras and Marquez, 2002, Leffa, 1998, Sang and Dejean,2001). 
From 2000 to 2005, several different chunking-related tasks, such as text chunking (Sang and Buchholz, 2000), clause identification (Sang and Dejean, 2001), semantic role labeling (Carreras and Marquez, 2005), were defined in the CoNLL conferences. 
We do this with a clause identifier (Hachey, 2002) built using the CoNLL-2001 shared task data (Sang and Dejean, 2001). 
The parsing methods using clause-based segmentation have been studied to improve the parsing performance and the parsing complexity (Kim et al. , 2000; Lyon and Dickerson, 1997; Sang and Dejean, 2001). 
