To the best of our knowledge, only (Li et al. , 2001) and (Mani and Wilson, 2000) mention having tried this kind of annotation, as a side job for their temporal expressions mark-up systems.


The issue has started to generate some interest in computational linguistics (Harper et al. , 2001), as it is potentially an important component in information extraction or question-answer systems.


So we have chosen relations similar to that of (Bruce, 1972) (as in (Li et al. , 2001)), who inspired Allen; these relations are equivalent to certain sets of Allen relations, as shown Table 2.


