Schone & Jurafsky (2001) evaluated a number of co-occurrence-based metrics for identifying MWEs, showing that, as suggested by Lins results, there was need for improvement in this area. 
Schone and Jurafsky (2001) applied LSA to the analysis of MWEs in the task of MWE discovery, by way of rescoring MWEs extracted from a corpus. 
2 Related Work Most previous work using distributional approaches to compositionality either contrasts distributional information of candidate phrases with constituent words (Schone and Jurafsky, 2001; Bannard et al. , 2003; Baldwin et al. , 2003; McCarthy et al. , 2003) or uses distributionally similar words to detect nonproductive phrases (Lin, 1999). 
Thus it was not judged necessary to replicate results for all methods covered in Schone & Jurafsky (2001). 
Schone and Jurafsky (Schone and Jurafsky, 2001) applied Latent-Semantic Analysis (LSA) to the analysis of MWEs in the task of MWE discovery, by way 900 of rescoring MWEs extracted from the corpus. 
