As (Krahmer et al. , 2001) observed, it is unlikely that someone would describe an object as the dog next to the tree in front of the garage in a situation where the dog next to the tree would suffice.


While the task of constructing singular definite descriptions on the basis of positive properties has received much attention in the generation literature (Dale and Haddock, 1991; Dale and Reiter, 1995; Horacek, 1997; Krahmer et al. , 2001), for a long time, a more general statement of the task at hand remained outstanding.


It also differs from (Krahmer et al. , 2001), who use graphs and graph algorithms for computing DDs  while graphs provides a transparent encoding of unary and binary relations, they lose much of their intuitive appeal when applied to relations of higher arity.


