Our choice of the algorithm in (Even-Zohar and Roth, 2001) was done in light of this requirement.


The sequential model algorithm presented by Even-Zohar and Roth (2001) directly supports this requirement.


Regarding the multi-stage methods, cascading (Alpaydin and Kaynak, 1998) is well known, and Even-Zohar and Roth (2001) proposed the sequential learning model and applied it to POS tagging.


The question classifier makes use of a sequence of two simple classifiers (Even-Zohar and Roth, 2001), each utilizing the Winnow algorithm within SNoW.


Pos tags are extracted using a SNoW-based pos tagger (Even-Zohar and Roth, 2001).


