5 Discussion As Muller (2001a), we presented a method for prediction of syllable boundaries using phonological probabilistic context-free grammars for German. However, our approach performs slightly better (96.88% word accuracy on word tokens versus 96.49%). 
In contrast to Muller (2001a), we did not investigate smaller training corpora, since we are interested in maximal phonological knowledge about internal word structure. 
If compared to the most successful grammar constructed by Muller (2001a), our grammar is enriched with an additional feature: the size of the onsets and codas. 
2 Method We build on the novel approach of Muller (2001a) which aims to combine the advantages of treebank and bracketed corpora training. 
We train the context-free grammar for German on the transcribed and syllabified training corpus with a simple supervised training method (Muller, 2001a). 
