The tagger we used, implemented by Megyesi (2001) for Swedish, is the TnT-tagger (Brants, 2000), trained on the SUC Corpus (Ejerhed et al. , 1992).


5 Comments and possible extensions It has been remarked that HMM trigram taggers using single multivalued context features can perform better and run faster than MaxEnt taggers trying to combine conditional probabilities for a multitude of binary features (Brants, 2000; Megyesi, 2001), even for large structured tagsets and Slavonic free word-order (Hajic et al., 2001).


This approach allows to combine strengths of generality of context attributes as in n-gram models (Brants, 2000; Megyesi, 2001) with their specificity as for binary features in MaxEnt taggers (Ratnaparkhi, 1996; Hajic and Hladk, 1998).


(van Halteren et al., 2001; Megyesi, 2001; Loftsson, 2006).


