C02-1160:1	14:163	Statistical MT systems have relied on bi-texts to automatically create word-alignments; in many statistical MT systems however, the authors state that use of a conventional bilingual dictionary enhances the performance of the system (Al-Onaizan et al. 1999, Koehn & Knight 2001).
---------------------------------------------------
E09-1021:2	73:270	Many MT tasks require automated creation or improvement of dictionaries (Koehn and Knight, 2001).
---------------------------------------------------
H05-1110:3	31:185	They use a variety of approaches (a good overview is Koehn and Knight (2001)), many of which require advanced tools for both languages which we are not able to use.
---------------------------------------------------
J04-2003:4	58:412	The use of dictionaries to augment or replace parallel corpora has already been examined by Brown, Della Pietra, Della Pietra, and Goldsmith (1993) and Koehn and Knight (2001), for instance.
---------------------------------------------------
W02-0902:5	30:199	For experiments on training probabilistic translation lexicons from parallel corpora and similar tasks on the same test corpus, refer to our earlier work [Koehn and Knight, 2000, 2001].
---------------------------------------------------
C02-1016:6	18:163	Cognates have been employed for sentence and word alignment in bitexts (Simard et al. , 1992; Melamed, 1999), improving statistical machine translation models (Al-Onaizan et al. , 1999), and inducing translation lexicons (Koehn and Knight, 2001).
---------------------------------------------------
W05-0606:7	180:196	For the baseline method, we selected the Longest Common Subsequence Ratio (LCSR), a measure of orthographic word similarity often used for cognate identification (Brew and McKelvie, 1996; Melamed, 1999; Koehn and Knight, 2001).
---------------------------------------------------
W05-0606:8	9:196	In statistical machine translation, cognates are helpful in inducing translation lexicons (Koehn and Knight, 2001; Mann and Yarowsky, 2001), sentence alignment (Melamed, 1999), and word alignment (Tiedemann, 2003).
---------------------------------------------------
