This technique of using subsequences as independent examples is used both in the corpora used in Merlo and Leybold (2001) and (Merlo, Crocker, and Berthouzoz 1997), and to an even larger extent in the corpus used in Collins and Brooks (1995), who would also have in their corpus the artificially constructed sequence using crocidolites in 1956. 
6.1 On the Automatic Distinction of Arguments and Adjuncts A few other pieces of work attempt to distinguish PP arguments from adjuncts automatically (Buchholz 1999; Merlo and Leybold 2001; Villavicencio 2002). 
Merlo and Leybold (2001) used the head dependence as a diagnostic to determine the argument (or adjunct) status of a PP. 
In recent preliminary work, however, we have succeeded in distinguishing arguments from adjuncts using corpus evidence (Merlo and Leybold 2001; Merlo 2003). 
As also noticed in Merlo and Leybold (2001), this is not always the case: some adjuncts frequently co-occur with certain heads too. 
