P09-1076:1	31:158	Such features are of similar interest in text processing  in particular, automated genre classification (Dewdney et al., 2001; Finn and Kushmerick, 2006; Kessler et al., 1997; Stamatatos et al., 2000; Wolters and Kirsten, 1999)  which relies on there being reliably detectable features that can beusedtodistinguishoneclassfromanother.
---------------------------------------------------
P09-1076:2	154:158	Fortunately, there is a growing body of work on genre-based text classification, including (Dewdney et al., 2001; Finn and Kushmerick, 2006; Kessler et al., 1997; Stamatatosetal.,2000; WoltersandKirsten, 1999).
---------------------------------------------------
