7.2 Evaluation of Final Ordering We evaluated the final ordering with the method proposed by Setzer and Gaizauskas (2001).


These values correspond to the relations described by Setzer and Gaizauskas (2001).


C2 = {Ea < Ee, Eb < Ec} Note that the partial ordering C can be extended using T and temporal closure axioms (Setzer and Gaizauskas 2001), (Verhagen 2004), so that in the case of <T2, C2>, we can infer, for example, that Eb < Ed, Ed < Ee, and so forth.


Temporal reasoning algorithms have also been developed, that apply transitivity axioms to expand the links using temporal closure algorithms (Setzer and Gaizauskas 2001), (Pustejovsky et al. 2003).


This is partly due to the absence of readily available corpora annotated with temporal information, although efforts are underway to develop treebanks marked with temporal relations (Katz and Arosio, 2001) and devise annotation schemes that are suitable for coding temporal relations (Ferro et al. , 2000; Setzer and Gaizauskas, 2001).


