It is well known that spoken humancomputer interaction differs from its humanhuman counterpart in various dimensions (Doran et al. , 2001) including linguistic complexity.


Furthermore, users in the HC dialogues rarely took initiative and their utterances showed very little variation (Doran et al. , 2001).


In order to label the HH corpus of 1062 utterances, we started with 10 dialogues (305 utterances) labelled with the CSTAR dialogue act tagging scheme (Finke et al. , 1998; Doran et al. , 2001).


Previous research has used dialogue act tagging for tasks such as improving recognition performance (Shriberg et al. , 2000), identifying important parts of a dialogue (Finke et al. , 1998), evaluating and comparing spoken dialogue systems (Walker et al. , 2001c; Cattoni et al. , 2001; Hastie et al. , 2002), as a constraint on nominal expression generation (Jordan, 2000), and for comparing HH to HC dialogues (Doran et al. , 2001).


