We call this dimension extent.3 2(Purver et al. , 2001) investigates such a mapping, based on the classification discussed below in Section 2.2.


This reading therefore takes the form Did you utter X?. (Purver et al. , 2001).


2.2 Previous Analyses In a number of papers (Ginzburg and Cooper, 2001; Purver et al. , 2001), Jonathan Ginzburg and colleagues have developed an influential analysis of CR.


