525 In the following, we will discuss the so-called training problem (Ney, 2001): how do we train the free parameters M1 of the model?


1 Introduction Once we specified the Bayes decision rule for statistical machine translation, we have to address three problems (Ney, 2001):  the search problem, i.e. how to find the best translation candidate among all possible target language sentences;  the modeling problem, i.e. how to structure the dependencies of source and target language sentences;  the training problem, i.e. how to estimate the free parameters of the models from the training data.


