(Broeder and Wittenburg, 2001) is also proposing a scheme for connecting the descriptions of tools and resources.


(Broeder and Wittenburg, 2001) give a good overview of metadata initiatives for Language Resources and propose a contrastive description of OLAC and IMDI, where the main distinction can be seen in the top-down versus bottom-up approach.


While (Calzolari et al. , 2001) concentrate on the description of the task of the ISLE computational lexicon working group and address the topic of metadata for encoding multilingual lexical resources, (Broeder and Wittenburg, 2001) presents the work of the ISLE Metadata initiative (IMDI), which is directly relevant for the topic addressed here.


