We adopt the OLAC metadata set which uses the fifteen elements defined in the Dublin Core metadata standard (Bird and Simons, 2003a; Bird and Simons, 2001).


Therefore the classification can be enriched by the products submitted 1 As (Bird and Simons, 2001) names it.


And this need was getting even more urgent after the Registry Team was asked for permission of harvesting the ACL repository for the purpose of creating a prototype service provider in the context of an Open Archive Initiative for Language Resources, which is called OLAC (Open Language Archives Community) and described in (Bird and Simons, 2001).


Thus addressing also one point mentioned in (Bird and Simons, 2001), where 3 main classes of providers are described: DATA, TOOLS and ADVICE providers.


