Zukerman and George (2002) developed the initial probabilistic model for applying the MML principle to argument interpretation.


We incorporate attentional focus into the discourse-interpretation formalism described in (Zukerman and George, 2002), which uses the Minimum Message Length (MML) Principle (Wallace and Boulton, 1968) to evaluate candi- date discourse interpretations.


6 Related Research Our research builds on work described in (Zuker- man, 2001; Zukerman and George, 2002), which in- tegrates plan recognition for discourse understand- ing with BNs.


