Many different dialogue systems have been built according to this general approach (e.g. , (Cooper and Larsson, 1999; Matheson et al. , 2000; Lemon et al. , 2001; Johnston et al. , 2002; Traum and Rickel, 2002; Purver, 2002)).


However, the method is close to that of (Purver et al., 2002) (and the corpus is identical), where re- liability was examined and found to be acceptable.


These fig- ures are comparable with (Purver et al., 2002)s ob- servations for the BNC.


How- ever, as systems become more human-like, it seems likely that we will have to cope with user CRs at some stage; and the ability to generate system CRs can be useful in order to repair misunderstanding, disambiguate other utterances, and learn new words  see (Knight, 1996; Dusan and Flanagan, 2002; Purver, 2002).


