1 Introduction Numerous studies have tackled gene and protein names recognition (Collier et al, 2002), (Tanabe and Wilbur, 2002).


It is described in Tanabe and Wilbur (2002b).


We apply it to five molecular biology EI and information extraction systems: ABGene (Tanabe and Wilbur 2002a, Tanabe and Wilbur 2002b); KeX/PROPER (Fukuda et al. 1997); Yapex (Franzn et al. 2002); the stochastic POS tagging-based system described in Cohen et al.


Tanabe and Wilbur (2002) looked at the performance on full-text articles of an entity identification system that had originally been developed and tested using abstracts.


