After that, we were paying more attention on the problems of extracting and identifying unknown words (Chen et.al 1997, Chen & Bai 1998, Chen & Ma 2002, Tseng & Chen 2002, Ma & Chen 2003).


Therefore, we (Chen et.al 1997, Tseng & Chen 2002) use association strength between morphemes and syntactic categories to predict the category of a new word.


Lack of a large morphological knowl124 Sixth SIGHAN Workshop on Chinese Language Processing edge base is a major obstacle to Chinese morphological analysis (Tseng and Chen, 2002).


According to (Tseng and Chen, 2002), new words can be divided into two major categories: Words with high or low semantic transparency (ST), which describes the correlation of semantic meanings between a word and its morphemes.


4.2 An example-base semantic classification The algorithm for the nearest neighbor classifier is as follows: 1) An unknown word is parsed by a morphological analyzer (Tseng and Chen 2002).


