system (Lavie et al., 2002).


In  the past six years, we have been successful in  using domain specific domain actions as the ba- sis for translation of limited-domain task- oriented spoken language (Levin et al., 1998,  Levin et al. 2002; Langley and Lavie, 2003)  4 Scalability and Portability of Domain  Actions  Domain actions, like speech acts, convey speaker  intention.


Our memory-based classifiers were imple- mented using TiMBL (Daelemans et al., 2002).


Our hy- brid analyzer uses the output of each classifier  along with the interlingua specification to iden- tify the DA (Langley et al., 2002; Langley and  Lavie, 2003).


