Finally, the Natural Language Toolkit (NLTK) is a package of NLP components implemented in Python (Loper and Bird, 2002). 
2.2 Coding Requirements As discussed in Loper & Bird (2002), the priorities for NLTK code focus on its teaching role. 
To identify content words, we used the NLTK-Lite tagger to assign a part of speech to each word (Loper and Bird, 2002). 
In the end I decided to require the students to learn python because I wanted to use NLTK, the Natural Language Toolkit (Loper and Bird, 2002). 
If evaluated against the requirements for teaching environments discussed in (Loper and Bird, 2002), GATE covers them all quite well. 
