The features are integrated in a Naive Bayes classifier, which was selected mainly for its performance in previous work showing that it can lead to a state-of-the-art disambiguation system given the features we consider (Lee and Ng, 2002). 
For each ambiguous word in ELS task of SENSEVAL-3, we used three types of features to capture contextual information: part-of-speech of neighboring words with position information, unordered single words in topical context, and local collocations (as same as the feature set used in (Lee and Ng, 2002) except that we did not use syntactic relations). 
Much of the description follows that of Lee and Ng (2002). 
In this paper, we used the WSD program reported in (Lee and Ng, 2002). 
Local Collocations We adopt the same 11 collocation features as (Lee and Ng, 2002), namely C??,??, C1,1, C??,??, C2,2, C??,??, C??,1, C1,2, C??,??, C??,1, C??,2, and C1,3. 
