4 Desiderata To better understand the needs of grammar developers we carefully explored two existing grammars: the LINGO grammar matrix (Bender et al. , 2002), which is a basis grammar for the rapid development of cross-linguistically consistent gram146 mars; and a grammar of a fragment of Modern Hebrew, focusing on inverted constructions (Melnik, 2006).


Such grammars are developed not only for purposes of theoretical linguistic research, but also for natural language applications such as machine translation, speech generation, etc. Wide-coverage grammars are being developed for various languages (Oepen et al. , 2002; Hinrichs et al. , 2004; Bender et al. , 2005; King et al. , 2005) in several theoretical frameworks, e.g., LFG (Dalrymple, 2001) and HPSG (Pollard and Sag, 1994).


