In this paper, we use the features proposed in Kudo and Matsumoto (2002). 
5 We used the statistical Japanese dependency parser CaboCha (Kudo and Matsumoto, 2002) for parsing. 
2.1 Dependency Parsing Using Cascaded Chunking (CaboCha) Our method is based on the cascaded chunking method (Kudo and Matsumoto, 2002) proposed as the CaboCha parser 1. 
The sentences were dependencyparsed with Cabocha (Kudo and Matsumoto, 2002), and cooccurrence samples of event mentions were extracted. 
The features are the same as those used in Kudo and Matsumoto (2002). 
