In general, rules are applied to revise summaries produced by a summarisation system (Mani et al. , 1999; Otterbacher et al. , 2002). 
This idea of employing n-gram co-occurrence statistics to score the output of a computer system against one or more desired reference outputs has its roots in the BLEU metric for machine translation (Papineni et al. , 2002) and the ROUGE (Lin and Hovy, 2003) metric for summarization. 
The recent flurry of work on semantic analysis, based on resources such as FrameNet (Baker et al. , 1998) and PropBank (Kingsbury et al. , 2002), provide the substrate for reasoning engines. 
The articles were morphologically analyzed by Mecab (Kudo et al., 2003) and syntactically parsed by Cabocha (Kudo and Matsumoto, 2002). 
4 Putting the Relevance in Summarization The definition of a meaningful extrinsic evaluation metric (e.g. , a task-based measure) is an issue that the summarization community has long grappled with (Mani et al. , 2002). 
