1 Introduction Since Chinese Word Segmentation was firstly treated as a character-based tagging task in (Xue and Converse, 2002), this method has been widely accepted and further developed by researchers (Peng et al., 2004), (Tseng et al., 2005), (Low et al., 2005), (Zhao et al., 2006).


Since CWS was firstly treated as a characterbased tagging task (we call it CT for short hereafter) in (Xue and Converse, 2002), this method has been widely accepted and further developed by researchers (Peng et al., 2004), (Tseng et al., 2005), (Low et al., 2005), (Zhao et al., 2006).


Word segmentation by characterbased tagging is firstly introduced by (Xue and Converse, 2002).


One of the solutions is character-based tagging (Xue and Converse, 2002) (Goh et al. , 2004a).


