W06-3405:1	74:75	We are actively investigatingalternativeapproachestosub-classifiercombination: better performance (and a more robust and trainable overall system) might be obtained by using a Bayesian network, or a maximum entropy classifier as used by (Klein et al. , 2002).
---------------------------------------------------
W06-3405:2	37:75	But if the utterances related to these properties form distinct sub-classes which have their own distinct features, treating them separately and combining the results (along the lines of (Klein et al. , 2002)) might allow better performance, while also identifying the utterances where each propertys value is extracted.
---------------------------------------------------
