Cucerzan and Yarowsky (2002) approached the shared task by using word-internal and contextual information stored in character-based tries.


Since the introduction of this task in MUC-6 (Grishman and Sundheim, 1996), numerous systems using various ways of exploiting entity-specific and local context features were proposed, from relatively simple characterbased models such as Cucerzan and Yarowsky (2002) and Klein et al.


