However, as discussed in (Toutanova et al. 2002),the word dependent selftransition model can be viewed as an approximation of fertility model. 
The use of POS information for improving statistical alignment quality of the HMM-based model is described in (Toutanova et al. , 2002). 
This is similar to the approach in (Toutanova et al. , 2002), in which the null word model is part of an extended HMM using left context only. 
95.2 95.3 4.7 93.6 90.8 7.5 (Toutanova et al. , 2002), extensions to the HMM-based alignment model are presented. 
These properties have made this model suitable for extensions (Toutanova et al. , 2002) and integration in a phrase-based model (Deng and Byrne, 2005) in the past. 
