C04-1033:1	155:192	In both trees, the string-similarity features occur on the top portion, which supports the arguments by (Strube et al. , 2002) and (Yang et al. , 2004) that string-matching is a crucial factor for NP coreference resolution.
---------------------------------------------------
C04-1033:2	37:192	Inspired by the work of (Strube et al. , 2002) and (Yang et al. , 2004), we use two features, StrSim1 (f17) and StrSim2 (f18), to measure the string-matching degree of NPj and NPi.
---------------------------------------------------
W03-1902:3	124:143	The heuristics to be applied to resolve coreference are based on previous studies about resolution of referring expressions (Vieira and Poesio, 2000; Lappin and Leass, 1994; Strube et al. , 2002) and they are not discussed here.
---------------------------------------------------
J05-3004:4	69:629	The performance of these approaches on definite NPs is often substantially worse than on pronouns and/or named entities (Connolly, Burger, and Day 1997; Strube, Rapp, and Mueller 2002; Ng and Cardie 2002b; Yang et al. 2003).
---------------------------------------------------
W09-1901:5	90:147	Other works have used a different strategy to reduce the imbalance between positive and negative samples (Soon et al., 2001; Ng and Cardie, 2002; Strube et al., 2002), where only samples composed by a negative antecedent that is closer than the annotated one are considered.
---------------------------------------------------
P03-1022:6	8:230	This paper describes the extensions and adaptations needed for applying our anaphora resolution system (Muller et al. , 2002; Strube et al. , 2002) to pronoun resolution in spoken dialogue.
---------------------------------------------------
P04-2010:7	110:130	The classification results of the gold standard data, which are much lower than the ones in Table 2 also PPER PPOS (Strube et al. , 2002) 82.8 84.9 our system 87.4 86.9 Table 2: Comparison of classification performance (Fa0a2a1a4a3 ) with (Strube et al. , 2002) demonstrate the importance of the semantic features.
---------------------------------------------------
P04-2010:8	102:130	5 Evaluation Before evaluating the actual system, we compared the performance of boosting to that of C4.5, as reported in (Strube et al. , 2002).
---------------------------------------------------
P04-2010:9	77:130	Due to lack of resources, the semantic class attribute cannot be annotated automatically, and is therefore used only for comparison with (Strube et al. , 2002).
---------------------------------------------------
P04-2010:10	33:130	The experiment presented in (Strube et al. , 2002) is one of the few dealing with the application of machine learning to German coreference resolution covering definite noun phrases, proper names and personal, possessive and demonstrative pronouns.
---------------------------------------------------
P04-2010:11	35:130	(Strube et al. , 2002) used 15 features modeled after those used by state-of-the-art resolution systems for English.
---------------------------------------------------
C08-1033:12	154:187	We also compared our model to a system based on decision trees, since this approach has been taken by several corpus-based anaphora resolution systems (Soon et al., 2001; Ng and Cardie, 2002; Strube et al., 2002).
---------------------------------------------------
C08-1033:13	105:187	Other works have used a different strategy to reduce the imbalance between positive and negative samples (Soon et al., 2001; Ng and Cardie, 2002; Strube et al., 2002), where only samples composed by a negative antecedent that is closer than the annotated one are considered.
---------------------------------------------------
P02-1045:14	153:229	In previous work (Strube et al. , 2002) we obtained quite different results for different types of anaphora, i.e. if we split the data according to the ana np feature into personal and possessive pronouns (PPER PPOS), proper names (NE), and definite NPs (def NP).
---------------------------------------------------
D08-1067:15	163:242	Nominals (especially definite descriptions), though more sensitive to salience than names, can also be resolved by simple stringmatching heuristics in many cases (Vieira and Poesio, 2000; Strube et al., 2002).
---------------------------------------------------
P05-1020:16	90:212	(2002), Strube and Muller (2003), Yang et al.
---------------------------------------------------
P05-1020:17	6:212	(2001), Ng and Cardie (2002b), Strube et al.
---------------------------------------------------
W03-1023:18	64:225	4 Naive Bayes without the Web First, we trained and tested the NB classifier with a set of 9 features motivated by our own work on other-anaphora (Modjeska, 2002) and previous ML research on coreference resolution (Aone and Bennett, 1995; McCarthy and Lehnert, 1995; Soon et al. , 2001; Ng and Cardie, 2002; Strube et al. , 2002).
---------------------------------------------------
