The EU MEANING project (Rigau et al. 2002) takes forward the exploration of the Web as a data source for word sense disambiguation, working from the premise that within a domain, words often have just one meaning, and that domains can be identified on the Web.


In fact, the cycling arquitecture of the MEANING4 project demonstrated that acquiring better knowledge allow to perform better Word Sense Disambiguation (WSD) and that having improvedWSD systems we are able to acquire better knowledge(Rigau et al., 2002).


It is worth noticing that two of the main ongoing projects addressing the construction of multilingual resources, that is MEANING (Rigau et al. 2002) and BALKANET (see web site), make use of WORDNET DOMAINS.


