This research task has been defined quite recently (Dagan et al. , 2002), and has not been explored extensively yet.


In an earlier line of research we have formulated the above problem and addressed it within a probabilistic vector-based setting, presenting two related heuristic algorithms (Dagan et al. , 2002; Marx et al. , 2004).


Here we term the three variations involving priors CPI (prior added in step (1) only, which is the same as the method described in Dagan et al. , 2002), CPII (prior added in step (3) only) and CPIII (prior added in both steps; as the method in Marx et al. , 2004).


