These new tasks include identification of semantic roles as in FrameNet (Gildea and Jurafsky 2002), disambiguation of WordNet glosses (Miller 1990; Fellbaum 1998; Harabagiu, Miller et al. 1999), automatic acquisitio n of subcategorisation frames (Korhonen 2002; Preiss and Korhonen 2002), and Logic al Form Identific ation (LFI) (Rus 2002; Rus and Moldovan 2002).


However, this sense can vary across corpora (Roland et al. , 2000), and assuming a single sense is inadequate for an important group of medium and high frequency verbs whose distribution of senses in balanced corpus data is flat rather than zipfian (Preiss and Korhonen, 2002).


We are also investigating the disambiguation of verb senses in running text before subcategorization information for the verbs is acquired, in order to produce a subcategorization lexicon specific to sense (Preiss and Korhonen 2002).


