1 Introduction Lexical substitution is defined as the task of identifying the most likely alternatives (substitutes) for a target word, given its context (McCarthy, 2002). 
2 Background: The English Lexical Substitution Task The English Lexical substitution task (hereafter referred to as LEXSUB) was run at SemEval-2007 following earlier ideas on a method of testing WSD systems without predetermining the inventory (McCarthy, 2002). 
This allows us to define an instance-based learning approach for fine-grained 1Lexical substitution consists in identifying the most likely alternatives (substitutes) of a target word given its context (McCarthy, 2002). 
A highly related task was proposed in (McCarthy, 2002). 
Finding alternative words that can occur in given contexts would potentially be useful to many applications such as question answering, summarisation, paraphrase acquisition (Dagan et al. , 2006), text simplification and lexical acquisition (McCarthy, 2002). 
