The first four transformations are derived from (Cohen et al. , 2002).


To amend potential boundary errors of tagged mentions, or to match the variants of the synonyms, four 3ftp://ftp.cs.cornell.edu/pub/smart/English.stop mention reductions (Cohen et al. , 2002) were also applied to the mentions or synonyms: 1.


It has already been noticed (Cohen et al. , 2002) that there is great variation in the naming conventions, and noun phrase constructions in the literature.


