We then used a common technique to reduce this set by only considering NPs headed by or modified by a frequent head or modifier from within the set of component terms (Bodenreider et al. , 2002).


And second, because adjectival modification often denotes a hyponymic relation between a phrase without modifier and a modified phrase, the modified phrase can be linked as a candidate hyponym to the phrase without modifier (Bodenreider et al. , 2002).


1 Introduction In previous studies, we demonstrated the feasibility of using NLP techniques such as shallow parsing of adjectival modification for identifying hierarchical relations among biomedical terms (Bodenreider et al. , 2001) and for extending an existing biomedical terminology (Bodenreider et al. , 2002).


(2002), Bodenreider et al.


