W04-3009:1	15:174	Another group investigated the performance of spoken queries in NTCIR collections (Fujii et al. , 2002A).
---------------------------------------------------
W04-3009:2	150:174	5.2 Results To measure error correction performance, we use word error rate (WER) and term error rate (TER): WER = jSwj + jIwj + jDwjjW truthj (10) TER = jStj + jItj + jDtjjT truthj (11) jWtruthj is the number of original words, and jTtruthj is the number of query term (or keyword) in original words, that is, an error rate of content words directly related to the performance of IR and QA system (Fujii et al. , 2002A).
---------------------------------------------------
W04-3009:3	117:174	(Fujii et al. , 2002B) have shown the importance of the language model which well describes the domain knowledge, we reflect the domain information with a template database: database of template queries of the source statements which are used Figure 5: Process of Semantic-oriented Error Correction for the actual error detection and correction task after speech recognition.
---------------------------------------------------
W04-3009:4	19:174	So, they introduced a method to improve the precision of speechdriven IR by suggesting a new type of IR system tightlyintegrated with a speech input interface (Fujii et al. , 2002B).
---------------------------------------------------
