Version V1.1 of GENIA has been also annotated with LTG tools (Grover et al. , 2002).


6See for example (Grover et al. , 2002) for a discussion of the utility of a named entitiy recognition preprocessing stage for robust symbolic parsing.


As for the robust analysis side, (Grover et al. , 2002), also use a similar preprocessing pipeline in combination with parsing.


An XML-based NLP tool suite for analyzing and annotating medical language in an NLP pipeline was also proposed by (Grover et al. , 2002).


