(2002) and Kit et al.


The details of computing this similarity can be found in (Kit et al. , 2002).


We participated in the bakeoff with a segmentation system that is designed to integrate a general-purpose ngram model for probabilistic segmentation and a caseor example-based learning approach (Kit et al. , 2002) for disambiguation.


Our recent study (Kit et al. , 2002) shows that case-based learning is an effective approach to disambiguation.


