All the systems use the JACCARD similarity metric and TTEST weighting function that were found to be most effective for thesaurus extraction by Curran and Moens (2002a). 
2 Related Work Monolingual syntax-based distributional similarity is used in many proposals to nd semantically related words (Curran and Moens (2002), Lin (1998), van der Plas and Bouma (2005)). 
Curran and Moens (2002) introduces a vector of canonical attributes (of bounded length k m), selected from the full vector, to represent the term. 
4.1.1 Lexical co-occurrences Lexical co-occurrences have previously been shown to be useful for discourse level learning tasks (Lapata and Lascarides, 2004; Marcu and Echihabi, 2002). 
Curran and Moens (2002a) introduced the TTEST weight function, which is used in collocation extraction. 
