I05-4007:1	71:148	Huang et al (2002) claimed that LSR y can be inferred as a functional combination of the three LSRs i, x and ii.
---------------------------------------------------
I05-4007:2	17:148	In our current line of work, we (Huang et al. 2002) refer to low-density languages as those which do not have enough existing resources for semi-automatic construction of monolingual wordnet.
---------------------------------------------------
I05-4007:3	41:148	The semantic relation between an English synset and its Chinese translation is based on The English-Chinese Translation Equivalents Database (ECTED, Huang et al. 2002).
---------------------------------------------------
