Markert and Nissims (2002a) and Nissim and Markerts (2003) study is the only one to approach metonymy recognition from a data-driven, statistical perspective. 
To this goal, Markert and Nissim extracted from the BNC a corpus of possibly metonymical words from two categories: country names (Markert and Nissim, 2002b) and organization names (Nissim and Markert, 2005). 
However, as Markert and Nissim (2002a) argue, the sense distinctions between the literal and metonymical meanings of a word are not of a topical 3With SVD, I set the number of dimensions to 300, as in Purandare & Pedersen (2004). 
Markert and Nissim (2002) and Nissim and Markert (2003) have shown that conventional metonymies can be effectively resolved using a supervised machine learning approach. 
3.2 Experiments I again applied this IB1-IG algorithm to Markert and Nissims (2002b) location corpora. 
