W03-1203:1	30:232	Various heuristics and revision strategies have been applied to the general sentence selection schema to take into consideration text cohesion (White & Cardie (2002), Mani and Bloedorn (1999), Aone et.
---------------------------------------------------
W03-1203:2	23:232	Story segmentation, document and sentence and classification can often be accomplished by unsupervised, clustering methods, with little or no requirement of human labeled data (Deerwester (1991), White & Cardie (2002), Jing et.
---------------------------------------------------
J02-4001:3	76:155	Recent work also follows this approach, using enhanced information extraction and additional forms of contrasts (White and Cardie 2002).
---------------------------------------------------
