4 The Alignment-capable Microplanner SPUD prime The previously described priming-based model of alignment has been implemented by extending the integrated microplanning system SPUD lite (Stone, 2002).


We describe how this model has been incorporated into the existing SPUD lite system (Stone et al., 2003; Stone, 2002) to yield the alignment-capable microplanner SPUD prime.


First, while Chiangs model includes both full adjunction and sister adjunction operations, our grammar has only sister adjunction (left and right), exactly as in the TAGLETgrammarformalismof(Stone,2002).


In fact, Stone advocated more or less this at the 2002 TNLP workshop (2002).


