The dialogues, provided by the Interact project (Jokinen et al. , 2002), had been transcribed into text by a person listening to the tapes.


For example, in interactive dialogue systems that attempt to carry out and answer requests made by customers, the response strategy employed may depend on the topic of the request (Jokinen et al. , 2002).


If a small set of relevant semantic concepts can be defined, and if the sentence structures allowed are strictly limited, the semantic concept identification problem can be solved, at least to some degree, by manually designed rule-based systems (Jokinen et al. , 2002).


