In contrast to the realistic model described in (Foster et al. , 2002b), this assumes that users accept predictions only at the beginnings of words, and only when they are correct in their entirety. 
7 Related work Several CAT systems have been proposed in the TransType projects (SchlumbergerSema S.A. et al. , 2001): In (Foster et al. , 2002) a maximum entropy version of IBM2 model is used as translation model. 
For this type of translator, facilitating target text input can be important, as is shown in the TransType system (Foster et al. , 2002; Macklovitch, 2006). 
An important contribution to interactive CAT technology was carried out around the TransType (TT) project (Langlais et al., 2002; Foster et al., 2002; Foster, 2002; Och et al., 2003). 
The second model, called Maxent2 below, is similar to Maxent1 but with the addition of extra parameters to limit this behaviour (Foster et al. , 2002a). 
