Figure 3 : LF analysis of (1) Modifications to any of the analysis components are tested using monolingual regression files containing thousands of analyzed sentences; differences caused by the modification are examined manually by the linguist responsible for the change (Suzuki, 2002).


The overall architecture and basic component structure 2 LF as described here corresponds to the PAS representation of Campbell and Suzuki (2002).


