H05-1030:1	34:172	Most prior work has focused on handling disfluencies and continued to rely on hand-annotated transcripts that include punctuation, case, and known sentence boundaries (Hindle, 1983; Core and Schubert, 1999; Charniak and Johnson, 2001; Engel et al. , 2002).
---------------------------------------------------
N06-2019:2	60:84	It is still worth noting, however, that the parser does perform better when fillers are absent, consistent with Engel et al.s findings (2002).
---------------------------------------------------
N06-2019:3	20:84	While one study has shown that the presence of interjection and parenthetical constituents in conversational speech reduces parse accuracy (Engel et al. , 2002), these constituent types are defined to cover both fluent and disfluent speech phenomena (Taylor, 1996), leaving the impact of fillers alone unclear.
---------------------------------------------------
W05-1519:4	26:152	[Engel et al. 2002] also showed detailed distributions of the interregnum, including interjections and parentheticals.
---------------------------------------------------
N04-1011:5	19:140	Even though this seems linguistically highly unnatural (e.g. , punctuation might indicate suprasegmental prosodic properties), statistical parsers generally perform signi cantly better when their training and test data contains punctuation represented in this way than if the punctuation is stripped out of the training and test data (Charniak, 2000; Engel et al. , 2002; Johnson, 1998).
---------------------------------------------------
N04-1011:6	83:140	2.2 Parse corpus construction We tried to incorporate the binned prosodic information described in the previous subsection in a manner that corresponds as closely as possible to the way that punctuation is represented in this corpus, because previous experiments have shown that punctuation improves parser performance (Charniak and Johnson, 2001; Engel et al. , 2002).
---------------------------------------------------
