Although n-gram modelling has not always been successful as a lone method of classification (Burger et al. , 2002), for the reasons outlined above it is a more flexible modelling technique than Tries. 
The papers from the CoNLL-2002 shared task which used such methods (e.g. Malouf (2002), Burger et al. 
A boosted decision tree method obtained the best performance on both data sets (Carreras et al. , 2002). 
Orthographic Tries (Cucerzan and Yarowsky, 1999; Whitelaw and Patrick, 2003; Whitelaw and Patrick, 2002) and character n-gram modelling (Patrick et al. , 2002) are two methods for capturing orthographic features. 
Some studies found that gazetteers did not improve performance (e.g. Malouf (2002)) whilst others gained significant improvement using gazetteers and triggers (e.g. Carreras et al. 
