also Rapp (1999) or Koehn and Knight (2002)). 
As a consequence the same entities will be denoted with the same words in different languages, allowing to automatically detect couples of translation pairs just by looking at the word shape (Koehn and Knight, 2002). 
2 Related Work The literature on translation lexicon induction for low-density languages falls in to two broad categories: 1) Effectively utilizing similarity between languages by choosing a high-resource bridge language for translation (Mann and Yarowsky, 2001; Schafer and Yarowsky, 2002) and 2) Extracting noisy clues (such as similar context) from monolingual corpora with help of a seed lexicon (Rapp, 1999; Koehn and Knight, 2002; Schafer and Yarowsky, 2002, Haghighi et al., 2008). 
This evaluation criterion is similar to the setup used by Koehn and Knight (2002). 
Unlike previous work (Koehn and Knight, 2002), we evaluate all words, not just nouns. 
