3.1 Examples Here we work with two basic activities of the WITAS robot helicopter (see (Lemon et al. , 2002)) which our dialogue system interfaces to  moving and searching. 
We saw that many of the insights of deterministic approaches (e.g. the WITAS Project, see (Lemon et al. , 2002)) can be preserved, often in less brittle forms, in a probabilistic setting. 
Activities are the joint tasks managed by the dialogue: e.g. booking a  ight or moving a robot  again, see (Lemon et al., 2002b) for details. 
2001; Lemon et al. , 2002)) which use deterministic context update rules. 
There are several spoken dialogue agents and robots that can handle interruptions thanks to their asynchronous control (Asoh et al., 1999; Boye et al., 2000; Blaylock et al., 2002; Lemon et al., 2002), they do not focus on making it easy to add new dialogue domains with a variety of dialogue strategies. 
