W04-0508:1	106:182	In previous work this approach has proved to be particularly effective, bringing a reduction in the complexity of parsing of 46% (Rinaldi et al. , 2002).
---------------------------------------------------
W04-0508:2	82:182	We have described in (Rinaldi et al. , 2002) some approaches that might be taken towards terminology extraction for a specific domain.
---------------------------------------------------
W04-0508:3	24:182	In the Biomedical domain, an example of a system that deals with terminological variants (also called aliases) can be found in (Pustejovsky et al. , 2002).
---------------------------------------------------
W09-1309:4	129:206	For the few remaining ones possible expansions were taken from the Medstract database (Pustejovsky et al., 2002).
---------------------------------------------------
W09-1309:5	127:206	For example, the sentence The adsorption behavior of bovine serum albumin (BSA) on a Sepharose based hydrophobic interaction support has been studied. becomes The adsorption behav74 BSA AND body surface area NOT bovine serum albumin BSA AND bovine serum albumin NOT body surface area Figure 1: Example queries for abbreviation BSA ior of BSA on a Sepharose based hydrophobic interaction support has been studied. We used this approach to create a corpus of sense tagged abbreviations in biomedical documents using a set of 21 three letter abbreviations used in previous research on abbreviation disambiguation (Liu et al., 2001; Liu et al., 2002; Liu et al., 2004).
---------------------------------------------------
W09-1309:6	97:206	Medical Subject Headings (MeSH) (Nelson et al., 2002) is a controlled vocabulary for indexing biomedical and health-related information and documents.
---------------------------------------------------
W09-1309:7	17:206	(2002) reported that abbreviations in biomedical journal articles consisting of six characters or less have an average of 4.61 possible meanings and Pustejovsky et al.
---------------------------------------------------
W06-3304:8	81:138	Another possibility is to use Information Extraction algorithms tailored to the biomedical domain such as Medstract (http://www.medstract.org, Pustejovsky et al. 2002) to extract entity-relationship structures of relevance.
---------------------------------------------------
W06-3304:9	138:138	We also intend to compare the advantages provided by the GoPubMed term extraction process with Information Extraction tools created for the biomedical domain such as Medstract (Pustejovsky et al. 2002), and develop a methodology for integrating a variety of Information Extraction processes into XOA.
---------------------------------------------------
W06-3304:10	13:138	One approach assesses GO code similarity in terms of shared hierarchical relations within each gene ontology (BP, MF, or CC) (Lord et al. 2002, 2003; Couto et al. 2003; Azuaje et al. 2005).
---------------------------------------------------
W04-3110:11	189:211	For example, for a gene or protein name recognized in a text, Termino will return the database identifiers of this term in the HUGO Nomenclature database (Wain et al. , 2002) and the OMIM database (Online Mendelian Inheritance in Man, OMIM (TM), 2000).
---------------------------------------------------
W04-3110:12	9:211	This has led to an increased interest in the application of natural language processing techniques for the automatic capture of biomedical content from journal abstracts, complete papers, and other textual documents (Gaizauskas et al. , 2003; Hahn et al. , 2002; Pustejovsky et al. , 2002; Rindflesch et al. , 2000).
---------------------------------------------------
W06-3312:13	33:246	In fact, the only recent BioNLP system found in the literature that makes any mention of PP attachment is Medstract (Pustejovsky et al. , 2002), an automated information extraction system for Medline abstracts.
---------------------------------------------------
W05-1306:14	6:324	1 Introduction A small number of data sets for evaluating the performance of biomedical language processing (BLP) systems on a small number of task types have been made publicly available by their creators (Blaschke et al. 19991, Craven and Kumlein 19992, Pustejovsky et al. 20023, Franzen et al. 20024, Collier et al. 19995, Tanabe et al. 20056).
---------------------------------------------------
W05-1306:15	193:324	It seems likely that the continued development and maintenance reflected in the three major releases of GENIA (Ohta et al. 2002, Kim et al. 2003) have contributed to its improved quality and continued use over the years.
---------------------------------------------------
C08-1083:16	78:166	It is unrealistic to compute the partition factor of the formula directly; therefore, the factor has been computed by dynamic programing (McCallum et al., 2005; Blunsom and Cohn, 2006; Shimbo and Hara, 2007) or approximated by the n-best list of highly probable alignments (Och and Ney, 2002; Liu et al., 2005).
---------------------------------------------------
C08-1083:17	16:166	Numerous researchers have proposed a variety of heuristics for recognizing abbreviation definitions, e.g., the use of initials, capitalizations, syllable boundaries, stop words, lengths of abbreviations, and co-occurrence statistics (Park and Byrd, 2001; Wren and Garner, 2002; Liu and Friedman, 2003; Okazaki and Ananiadou, 2006; Zhou et al., 2006; Jain et al., 2007).
---------------------------------------------------
C08-1083:18	14:166	Furthermore, abbreviation recognition is also crucial for disambiguating abbreviations (Pakhomov, 2002; Gaudan et al., 2005; Yu et al., 2006), providing sense inventories (lists of abbreviation definitions), training corpora (context information of full forms), and local definitions of abbreviations.
---------------------------------------------------
C08-1083:19	106:166	3 Experiments 3.1 Aligned abbreviation corpus The Medstract Gold Standard Corpus (Pustejovsky et al., 2002) was widely used for evaluating abbreviation recognition methods (Schwartz and Hearst, 2003; Adar, 2004).
---------------------------------------------------
W05-1302:20	10:176	This is also called semantic integration, e.g., (Li et al. , 2005), reference grounding, e.g., (Kim and Park, 2004) or normalization, e.g., (Pustejovsky et al. , 2002; Morgan et al. , 2004).
---------------------------------------------------
W05-1302:21	16:176	It has already been noticed (Cohen et al. , 2002) that there is great variation in the naming conventions, and noun phrase constructions in the literature.
---------------------------------------------------
W05-1302:22	13:176	The importance of edit distance algorithms has already been noticed, (Muller et al. , 2002) and the importance of string similarity techniques in the biomedical domain has also been acknowledged, e.g., (Yang et al. , 2004).
---------------------------------------------------
W05-1302:23	28:176	2 Background 2.1 Entity Extraction and Reference Resolution in the Biomedical Domain Most of the work related to reference resolution in this domain has been done in the following areas: a) Intra-document Reference resolution, e.g (Castano et al. , 2002; Lin and Liang, 2004) b) Intra-document Named entity recognition (e.g Biocreative Task 1A (Blaschke et al. , 2003), and others), also called classification of biological names (Torii et al. , 2004) c) Intra-document alias extraction d) cross-document Acronym-expansion extraction, e.g., (Pustejovsky et al. , 2001).
---------------------------------------------------
