However, since we also have in our group an XML-based lexicon of German connectives at our disposal (Berger et al. , 2002), why not use this resource to speed up the rst phase of the annotation?


Our Discourse Marker Lexikon DiMLex (Berger et al. , 2002) assembles information on 140 German connectives, giving a range of syntactic, semantic, and pragmatic features, including the coherence relations along the lines of (Mann, Thompson, 1988).


