Research in the acquisition of subcategorization information, selectional preferences, in thematic role assignments and diathesis alternations (Agirre and Martnez 2001, 2002, McCarthy and Korhonen, 1998; Korhonen et al. , 2000; McCarthy 2001), domain information (Magnini and Cavagli 2000), topic signatures (Agirre et al. 2001b), lexico-semantic relations between words (Agirre et al. 2002) etc. has obtained encouraging results.


But in order to make significant advances in WSD system accuracy, systems need to be able to use types of lexical knowledge that are not currently available in wide-coverage lexical knowledge bases: for example subcategorisation frequencies for predicates (particularly verbs) rely on word senses, selectional preferences of predicates for classes of arguments, amongst others (Carroll and McCarthy, 2000; McCarthy et al. , 2001; Agirre and Martnez, 2002;).


