JACY (Siegel and Bender, 2002) is a broadcoverage linguistically precise HPSG-based grammar of Japanese. 
The grammars used for the experiments reported here are the LinGO English Resource Grammar (ERG; Flickinger (2000)) and JACY (Siegel and Bender, 2002), precision grammars of English and Japanese, respectively. 
By using a Japanese grammar (JACY: Siegel and Bender, 2002) based on a monostratal theory of grammar (HPSG: Pollard and Sag, 1994) we could simultaneously annotate syntactic and semantic structure without overburdening the annota330 tor. 
In HPSG, the most extensive grammars are those of English (Flickinger, 2000), German (Muller & Kasper, 2000), and Japanese (Siegel, 2000; Siegel & Bender, 2002). 
By using a Japanese grammar (JACY: Siegel and Bender (2002)) based on a monostratal theory of grammar (HPSG: Pollard and Sag (1994)) we could simultaneously annotate syntactic and semantic structure without overburdening the annotator. 
