system (Lavie et al., 2002).


In  the past six years, we have been successful in  using domain specific domain actions as the ba- sis for translation of limited-domain task- oriented spoken language (Levin et al., 1998,  Levin et al. 2002; Langley and Lavie, 2003)  4 Scalability and Portability of Domain  Actions  Domain actions, like speech acts, convey speaker  intention.


Our hy- brid analyzer uses the output of each classifier  along with the interlingua specification to iden- tify the DA (Langley et al., 2002; Langley and  Lavie, 2003).


We have, however, conducted crosssite evaluations (Lavie et al. , 2002), in which the analyzer and generator were written at di erent sites.


Nespole evaluations so far show a loss of cross-site reliability: intra-site evaluations are noticeably better than cross-site evaluations, as reported in (Lavie et al. , 2002).


