(1999), Pedersen (2001), Yarowsky and Florian (2002)) as well as maximum entropy models (e.g. , Dang and Palmer (2002), Klein and Manning (2002)).


We have been training automatic WSD systems on the English sense-tagged training data based on WordNet that we supplied to SENSEVAL2 (Dang & Palmer, 2002).


Grouping the highly polysemous verb senses in WordNet (on average reducing the >16 senses per verb to 8) provides an important first step a more flexible granularity for WordNet senses that improves both inter-annotator agreement (71% to 82%) and system performance (60.2% to 69%) (Dang & Palmer, 2002).


(1999), Pedersen (2001), Yarowsky and Florian (2002)) as well as maximum entropy models (e.g. , Dang and Palmer (2002), Klein and Manning (2002)) in particular have shown a large degree of success for WSD, and have established challenging state-of-the-art benchmarks.


The maximum entropy system performed competitively with the best systems on the English verbs in SENSEVAL-1 and SENSEVAL-2 (Dang and Palmer, 2002).


