4.1 Initial Considerations for Mapping Out the Inheritance Hierarchy Of the 847 senses described in Litkowski (2002), and used as the starting point for the analysis in TPP, most follow the prototypical form of a prepositional phrase followed by a terminal (dangling) preposition, e.g., for sense 1 of about, on the subject of. 
Litkowski (2002) provided a graph-theoretical analysis that arranged prepositions into a hierarchy. 
Litkowski (2002) presents manuallyderived rules for disambiguating prepositions, in particular for of. 
Most of these remaining senses, in fact, are the ones that gave rise to the definitional cycles and hierarchical analysis of the digraph described in Litkowski (2002). 
However, viewed from the perspective of the digraph analysis performed in Litkowski (2002), this inheritance analysis provides confidence that there is an ordering relationship within the preposition sense inventory that can be exploited. 
