Syllable statistics have been also used for automatic word spacing (Shim, 1996; Kang and Woo, 2001; Lee et al. , 2002).


It is a necessary in the information retrieval system for the Korean language (Kang and Woo, 2001; Lee et al, 2002).


4.4 Sequence Tagging Since natural language sentences are sequential as their nature, the word spacing can be considered as a special POS tagging task (Lee et al. , 2002) for which a hidden Markov model is usually adopted.


This results coincide with the previous report (Lee et al. , 2002).


According to the previous work (Lee et al. , 2002), the hidden Markov model shows the best performance when it sees two previous tags and two previous syllables.


