For instance, Mann (2002) extracted is-a relations for proper nouns by Hearststyle patterns. 
Another related line of work is automated ontology construction, which aims to create lexical hierarchies based on semantic classes (e.g., (Caraballo, 1999; Cimiano and Volker, 2005; Mann, 2002)), and learning semantic relations such as meronymy (Berland and Charniak, 1999; Girju et al., 2003). 
Mann (2002) and Fleischman et al. 
Mann (2002) describes a method for extracting instances from text by means of part-of-speech patterns involving proper nouns. 
Another related line of work is automated ontology construction, which aims to create lexical hierarchies based on semantic classes (e.g., (Caraballo, 1999; Cimiano and Volker, 2005; Mann, 2002)). 
