The third voting model, a boosting model (Freund and Schapire, 1997), was built as boosting has consistently turned in very competitive scores on related tasks such as named entity classification (Carreras et al. , 2002)(Wu et al. , 2002). 
Other more sophisticated representations and tagging schemes, studied in the past edition (Carreras et al. , 2002a), did not improve the performance at all. 
Additionally, a NERC system based on the AdaBoost algorithm obtained the best results in the CoNLL02 Shared Task competition (Carreras et al. , 2002). 
The third voting model is a boosting model (Freund and Schapire, 1997), since has consistently turned in very competitive scores on related tasks such as named entity classification (Carreras et al. , 2002). 
They have been used in some previous works allowing significant improvements for the Spanish NERC task (Carreras et al. , 2002; Carreras et al. , 2003). 
