The feature I focus on, following Ciaramita (2002), is morphological similarity to words whose semantic category is known. 
Ciaramita (2002) compared several models in classifying nouns with respect to a simplified version of WordNet and signified the gain in performance with morphological features. 
There have been a few studies (e.g. , Lin, 1998; Ciaramita, 2002; Alfonseca and Manandhar, 2002) where word representations are modified through this or that kind of feature weighting. 
4.2 Classification algorithms Two classification algorithms were used in the study: k nearest neighbors (kNN) and Nave Bayes, which were previously shown to be quite robust on highly dimensional representations on tasks including word classification (e.g. , Ciaramita 2002). 
The feature I focus on, following Ciaramita (2002), is morphological similarity to words whose semantic category is known. 
