These frequencies can be used to calculate probability estimates P(c | a1a2 an) for each category c. Tries have previously been used in both supervised (Patrick et al. , 2002) and unsupervised (Cucerzan and Yarowsky, 1999) named entity recognition.


While the use of multiple subsets can increase overall accuracy, the recombination of models has been shown to propagate errors (Carreras et al. , 2002; Patrick et al. , 2002).


Orthographic Tries (Cucerzan and Yarowsky, 1999; Whitelaw and Patrick, 2003; Whitelaw and Patrick, 2002) and character n-gram modelling (Patrick et al. , 2002) are two methods for capturing orthographic features.


