Then discourse level processing attempts to resolve nominal and temporal anaphora and ellipsis to produce the candidate FOPL representation for a sentence (Jordan and VanLehn, 2002).


Thus, we are currently developing a speech based dialogue system that uses a text based system for tutoring conceptual physics (VanLehn et al. , 2002) as its back-end.


We are thus currently developing a speech based dialogue system that uses a text based system (VanLehn et al. , 2002) as its back-end . These systems and their goals will be discussed in Section 2.


2 Why2-Atlas and ITSPOKE Dialogue Systems Why2-Atlas is a text based intelligent tutoring dialogue system (Rose et al. , 2002a; VanLehn et al. , 2002).


In recent years tutorial dialogue systems have become more and more prevalent, most of which are text based (Evens et al. , 2001; Rose and Aleven, 2002; Zinn et al. , 2002; Aleven et al. , 2001; VanLehn et al. , 2002).


