(Zhang et al. , 2002) suggest a method that is based on role tagging for unknown words recognition.


During the past decades, great success has been achieved in Chinese word segmentation (Nie, et al, 1995; Yao, 1997; Fu and Wang, 1999; Wang et al, 2000; Zhang, et al, 2002).


The approach adopted here is reminiscent of the line of research that employs the idea of character-based tagging for Chinese word segmentation and/or unknown word identification (Goh et al. , 2003; Xue, 2003; Zhang et al. , 2002).


