To maintain a robust analysis in the presence of noise, multiple similarity measures were used to compare the verb and SCF distributions (Korhonen and Krymolowski, 2002).


Our subcategorization acquisition method, based on predominant sense heuristics, is less adequate for these verbs rather, a method based on word sense disambiguation and the use of multi3For the details of these measures and their application to this task see Korhonen and Krymolowski (2002).


The details of these measures and their application to subcategorization acquisition can be found in (Korhonen and Krymolowski, 2002).


The great advantage of the Bhattacharyya coe cient over various entropy based similarity measures which are usually used to compare SCF distributions (Korhonen and Krymolowski, 2002), is that it is guaranteed to lie between 0 and 1, unlike the entropy based measures which are not easily comparable between di erent word pairs.


