Systems that have been developed so far can be divided into those for use in the doctors office  notably, MedSLT (Rayner and Bouillon, 2002), CCLINC (Lee et al. , 2002), and (honourable mention) the early work done at CMU (Tomita et al. , 1988)1  and those for use for first contact with medical professionals in the field, developed under DARPAs CAST programme:2 MASTOR (Zhou et al. , 2004), Speechalator (Waibel et al. , 2003), Transonics (Narayanan et al. , 2004) and SRIs system (Precoda et al. , 2004).


