W03-1211:1	25:189	Examples of using NLP and IE in Question Answering include shallow parsing [Kupiec 1993] [Srihari & Li 2000], deep parsing [Li et al. 2002] [Litkowski 1999] [Voorhees 1999], and IE [Abney et al. 2000] [Srihari & Li 2000].
---------------------------------------------------
W03-1211:2	51:189	2 Question Answering Based on IE We use a QA system supported by increasingly sophisticated levels of IE [Srihari & Li 2000] [Li et al. 2002].
---------------------------------------------------
