Baldwin and Villavicencio (2002) extract a simple list of VPCs from corpus data, while Baldwin (2005) extracts VPCs with valence information under the umbrella of deep lexical acquisition.1 The method of Baldwin (2005) is aimed at VPC extraction and takes into account only the syntactic features of verbs. 
In addition, this method 5Similar assumption or experiment data can be also found in (Baldwin and Villavicencio, 2002; Bannard et al. , 2003; Dias, 2003). 
Extraction of the VPCs was based on the method of Baldwin and Villavicencio (2002). 
As the particles in verb + particle MWVs are often intransitive (Baldwin and Villavicencio, 2002; McCarthy et al. , 2003), which are different from the transitive prepositions followed by a noun chunk, we use this feature and a nearest assumption to extract non-contiguous MWV candidates. 
Using the methods described in Baldwin and Villavicencio (2002), 8,751 VPC entries were extracted from the BNC. 
