As pointed out in Litkowski (2002), the amount of information available in WordNet is problematic.


1 The SENSEVAL-3 All-Words Task Our procedures for performing this task and our results were largely unchanged from SENSEVAL-2 (Litkowski, 2001; Litkowski, 2002).


We intended to use the training data, not for use as in supervised systems, but to analyze our results using methods we had established for identifying factors significant in disambiguation (Litkowski, 2002).


Several previous studies have used both a corpus and a machine readable dictionary for WSD (Litkowski, 2002; Rigau et al. , 1997; Stevenson and Wilks, 2001).


