8 Related Projects Apart from a few small word lists involving several European languages, the only other major current project attempting to compile a comprehensive multilingual database is the Papillon project (e.g. Boitet et al, 2002).


An interesting approach is the Papillon Project that focuses on building a multilingual lexical data base to construct large, detailed and principled dictionaries (Boitet et al. , 2002).


1 AutoPat, APTrans, AutoRead, computer systems for authoring, translation and improving readability of paten claims, correspondingly (Sheremetyeva, 2003) 2 Related work A vast amount of research in the field of electronic dictionaries concentrate on data unification, representation, organization and management with the major focus on multilingual dictionaries as, for example, in (Wong, 2000; Boitet et al. ,2002).


Webelievethatprojectssuch as(Boitet et al.2002)and(Wiktionary),whicharecurrentlygeneratingtranslationdictionariesbyhandcould benefitgreatlyfromusingourmethod.


