Despite the POS-tagging improvement, the results can hardly said to be fully satisfactory due to the following reasons: * The result of automatic word-alignment is only 87% (Dinh Dien et al. , 2002a).


The result of this word-aligned parallel corpus has been used in various Vietnamese NLP tasks, such as in training the Vietnamese word segmenter (Dinh Dien et al. , 2001a), word sense disambiguation (Dinh Dien, 2002b), etc. Remarkably, this EVC includes the SUSANNE corpus (Sampson, 1995)  a golden corpus has been manually annotated such necessary English linguistic annotations as lemma, POS tags, chunking tags, syntactic trees, etc. This English corpus has been translated into Vietnamese by English teachers of Foreign Language Department of Vietnam University of HCM City.


The accuracy of word-alignment of this parallel corpus has been reported approximately 87% in (Dinh Dien et al. , 2002b).


This EVC has been automatically word-aligned (Dinh Dien et al. , 2002a).


For full details of word alignment of this EVC corpus (precision, recall, coverage, etc.), please refer to (Dinh Dien et al. , 2002a).


