W04-1311:1	58:329	The only work described in a recent review (Roberts and Atwell, 2002) as completely unsupervised  the GraSp model (Henrichsen, 2002)  does attempt to induce syntax from raw transcribed speech, yet it is not completely data-driven in that it makes a prior commitment to a particular theory of syntax (Categorial Grammar, complete with a pre-specified set of allowed categories).
---------------------------------------------------
P07-3008:2	28:172	Recently, several word-based grammar induction algorithms have been developed: Alignment-Based Learning (van Zaanen, 2002), Adios (Solan et al. , 2005), Emile (Adriaans, 1992; Adriaans and Vervoort, 2002) and GraSp1 (Henrichsen, 2002).
---------------------------------------------------
P07-3008:3	60:172	One of them is visual inspection (Henrichsen, 2002).
---------------------------------------------------
