P04-1088:1	182:194	We are also exploring whether FLSA can be used as the basis for semi-automatic annotation of dialogue acts, to be incorporated into MUP, an annotation tool we have developed (Glass and Di Eugenio, 2002).
---------------------------------------------------
P04-1088:2	80:194	It has been annotated for a variety of features, including four DAs3 (Glass et al. , 2002): problem solving, the tutor gives problem solving directions; judgment, the tutor evaluates the students actions or diagnosis; domain knowledge, the tutor imparts domain knowledge; and other, when none of the previous three applies.
---------------------------------------------------
