Some morphology discovery algorithms learn relationships between words by comparing the orthographic or semantic similarity of the words (Schone and Jurafsky, 2000; Neuvel and Fulop, 2002; Baroni et al. , 2002). 
As far as we know, all the other perform some sort of segmentation even when the goal is not to find morphemes as in (Neuvel and Fulop, 2002). 
In (Neuvel and Fulop, 2002), a morphological learner based on the theory of Whole Word Morphology is outlined. 
This process is similar to the idea of registering signatures (Goldsmith, 2001; Neuvel and Fulop, 2002). 
The Whole Word Morphologizer (Neuvel and Fulop, 2002) uses a POS-tagged lexicon as input, induces morphological relationships without attempting to discover or identify morphemes. 
