There are also other works (Nakagawa and Mori, 2002; Frantzi and Ananiadou, 1998) that introduced better method to weigh the term candidates.


Even if a noun is split into two or more morphemes in morphological analysis, they are chunked to form a phrasal unit called bunsetsu in dependency parsing, and to extract a keyword (Nakagawa and Mori, 2002).


These candidates are then submitted to frequencyor statistically-based evidence measures 1Nakagawa and Mori (2002) claim that more than 85% of domain-speci c terms are multi-word units.


Given a word sequence a to be examined for unithood, the Cvalue is defined as: Cvalue(a) = braceleftBigglog 2 |a|fa if |a| = g log2 |a|(fa  summationtext lLa fl |La| ) otherwise (3) where |a| is the number of words in a, La is the set of longer term candidates that contain a, g is the longest n-gram considered, fa is the frequency of occurrence of a, and a / La. While certain researchers (Kit, 2002) consider Cvalue as a termhood measure, others (Nakagawa and Mori, 2002) accept it as a measure for unithood.


