To implement Xenon, 242 Inkpen and Hirst A Lexical Knowledge Base of Near-Synonym Differences Figure 9 Lexical analysis and choice in machine translation; adapted from Edmonds and Hirst (2002). 
The higher the scores the better the classification is. 3.2 Precision-recall curves Since choosing a classification threshold depends primarily on the intended application and there is no principled way of finding it (Inkpen and Hirst, 2002), we can measure performance of association measures by precisionrecall scores within the entire interval of possible threshold values. 
Most of these methods were originally applied in large text corpora, but more recently the web has been used as a corpus (Pearce, 2001; Inkpen and Hirst, 2002). 
Also, we would learn from a method of lexical choice with knowledge about collocational behavior (Inkpen and Hirst, 2002). 
We outline the three steps below; a more-detailed discussion is presented by Inkpen and Hirst (2002). 
