865 (= 93% of fragments) other 66 (= 7% of fragments) Table 3: Results of Annotation Discussion The overall percentage of fragments we have found seems to confirm the results of earlier studies (Thompson, 1980; Fernandez and Ginzburg, 2002), which also classified as frag- ments around 10% of the utterances in the dialogues they looked at.


(Fernandez and Ginzburg, 2002) also offers a taxonomy of fragment types; the au- thors claim to have reached a coverage which is much higher than what we achieved (99% com- pared to our 93%).


1 Introduction Non-sentential utterances (NSUs) as in (1) are pervasive in dialogue: recent studies put the proportion of such utterances at around 10% across different types of dialogue (Fernandez and Ginzburg, 2002; Schlangen and Lascarides, 2003).


