Recently, machine learning approaches are widely used in NER, including the hidden Markov model (Zhou and Su, 2000; Miller and Crystal, 1998), maximum entropy model (Borthwick, 1999), decision tree (Qin and Yuan, 2004), transformation-based learning (Black and Vasilakopoulos, 2002), boosting (Collins, 2002; Carreras et al. , 2002), support vector machine (Takeuchi and Collier, 2002; Yu et al. , 2004; Goh et al. , 2003), memory-based learning (Sang, 2002).


Black and Vasilakopoulos (2002) have evaluated two approaches to the shared task.


