W05-0615:1	38:205	The first model class, described in Muller (2002), encodes information about the positions within a word or syllable in which each phoneme is likely to appear.
---------------------------------------------------
W05-0615:2	30:205	A number of different supervised machine learning techniques have been applied to the task of automatic syllable boundary detection, including decision-tree classifiers (van den Bosch et al. , 1998), weighted finite state transducers (Kiraz and Mobius, 1998), and PCFGs (Muller, 2001; Muller, 2002).
---------------------------------------------------
W06-3202:3	4:234	The grammar used by Muller (2002) serves as point of comparison.
---------------------------------------------------
W06-3202:4	103:234	14 (17) Word Sylone.I a8a8 a8a8 a72a72 a72a72 Onsetone.I.3 Onone.s.3.1 Rhymeone.I a8a8a8 a72a72a72Nucleus one.I I Codaone.I.1 Coone.N.1.1 N 3 Experiments In this section, we report on our experiments with four different phonotactic grammars introduced in Section 2.1 (see grammar 2.1.3-2.1.6), as well as with a re-implementation of Mullers less complex grammar (Muller, 2002).
---------------------------------------------------
W06-3202:5	8:234	ComparedtothegrammarofMuller (2002), syllable boundary accuracy increases from 95.8% to 97.2% for English, and from 95.9% to 97.2% for German. Moreover, our experiments with different syllable structures point out that there are dependencies between the onset on the nucleus for German but not for English.
---------------------------------------------------
W06-3202:6	59:234	Hence, we change the rules of the syllable complexity grammar (Muller, 2002) such that phonotactic dependencies are modeled.
---------------------------------------------------
W06-3202:7	50:234	2.1 Grammar development Our point of comparison is (i) the syllable complexity grammar which was introduced by Muller (2002).
---------------------------------------------------
W06-3202:8	72:234	2.1.2 Syllable complexity grammar (Muller, 2002) The syllable complexity grammar distinguishes between onsets and codas which contain a different number of consonants.
---------------------------------------------------
W06-3202:9	20:234	The syllabification accuracy increases if the onset and coda is more fine-grained (Muller, 2002).
---------------------------------------------------
W06-3202:10	71:234	For comparison reasons, we briefly describe the grammar of Muller (2002) first.
---------------------------------------------------
W06-3202:11	217:234	The most direct point of comparison are the results presented by Muller (2002).
---------------------------------------------------
W06-3202:12	151:234	accuracy accuracy accuracy baseline 10.33% (Muller, 2002) 89.27% 91.84% 95.84% phonot.
---------------------------------------------------
W06-3202:13	157:234	accuracy accuracy accuracy baseline 1.59% (Muller, 2002) 86.06% 91.96% 95.90% phonot.
---------------------------------------------------
N09-1035:14	222:247	With a hand-crafted grammar, Muller (2002) achieves 96.88% word accuracy on CELEX-derived syllabifications, with a training corpus of two million tokens.
---------------------------------------------------
N09-1035:15	7:247	Although some work has been done on syllabifying orthographic forms (Muller et al., 2000; Bouma, 2002; Marchand and Damper, 2007; Bartlett et al., 2008), syllables are, technically speaking, phonological entities that can only be composed of strings of phonemes.
---------------------------------------------------
P08-1046:16	118:184	3.3 Unigram syllable adaptor grammar PCFG estimation procedures have been used to model the supervised and unsupervised acquisition of syllable structure (Muller, 2001; Muller, 2002); and the best performance in unsupervised acquisition is obtained using a grammar that encodes linguistically detailed properties of syllables whose rules are inferred using a fairly complex algorithm (Goldwater and Johnson, 2005).
---------------------------------------------------
