(2003) and the approach of Zhang and Johnson (2003) were not significantly worse than the best result for German. 
5.3 Named entity chunking results methods Our feature representation is a slight modification of a simpler configuration (without any gazetteer) in (Zhang and Johnson, 2003), as shown in Figure 2. 
(2003) and Zhang and Johnson (2003). 
1 Introduction Given the usefulness of Named Entities (NEs) in many natural language processing tasks, there has been a lot of work aimed at developing accurate named entity extractors (Borthwick, 1999; Velardi et al. , 2001; Arevalo et al. , 2002; Zhou and Su, 2002; Florian, 2002; Zhang and Johnson, 2003). 
With the exception of the result of Zhang and Johnson (2003), there is not much difference in the German results between the gains obtained by using gazetteers and those obtained by using unannotated data. 
