InfoXtract [Srihari et al. 2003]. 
Before the bootstrapping is started, a large raw training corpus is parsed by the English parser from our InfoXtract system (Srihari et al. 2003). 
CoNLL</booktitle> <contexts> <context>on of possible designs yielded the following pipelines:  The chunking pipeline uses a classical tagger/chunker combination, with the Stanford POS tagger (Toutanova et al., 2003), the YamCha chunker (Kudoh and Matsumoto, 2000) and the Stanford BART. 
Figure 1 presents the underlying IE engine InfoXtract [Srihari et al. 2003] that forms the basis for the QA system. 
The InfoXtract parser supports dependency parsing based on the linguistic units constructed by our shallow parser (Srihari et al. 2003). 
