W04-1215:1	18:167	Several works employing SVM classifier have been done (Kazama et al. , 2002; Lee et al. , 2003; Takeuchi and Collier, 2003; Yamamoto et al. , 2003), and will be discussed further in the rest of this paper.
---------------------------------------------------
W07-1022:2	185:197	Yamamoto et al (2003) describe an SVM approach to protein name recognition, one of whose features is the output of a baseNP recognizer.
---------------------------------------------------
W08-0609:3	145:160	(Yamamoto et al., 2003) used SVMs for characterbased protein name recognition and sequential labelling.
---------------------------------------------------
W08-0609:4	129:160	Machine learning-based approaches are taken in (Collier et al., 2000; Lee et al., 2003; Kazama et al., 2002; Tanabe and Wilbur, 2002; Yamamoto et al., 2003; Tsuruoka, 2006; Okanohara et al., 2006).
---------------------------------------------------
W07-1012:5	31:172	(Yamamoto et al. , 2003) proposed the use of morphological analysis to improve protein name tagging.
---------------------------------------------------
W07-1012:6	20:172	Rule-based systems (Fukuda et al. , 1998; Hanisch et al. , 2003; Yamamoto et al. , 2003) that use dictionaries tend to exhibit high precision in tagging named entities but generally with lower tagging recall.
---------------------------------------------------
W04-1202:7	28:165	Beyond these well-known targets, researchers (see de Bruijn and Martin, 2002, or Hirschman and al. 2002, for a survey) interested in information extraction and retrieval for biomedical applications have mostly focused on studying specific biological interactions (Stapley and Benoit, 2000; Ndellec et al. , 2002; Dobrokhotov et al. , 2003) and related entities (Collier et al. , 2000; Humphreys et al. , 2000; Yu et al. , 2002; Yamamoto et al. , 2003; Albert et al. , 2003) or using terms in biomedical vocabularies (Nazarenko et al. , 2001; Ruch et al. , 2004; Srinivasan and Hristovski, 2004).
---------------------------------------------------
