For preprocessing we used an off-theshelf Chinese lexical analysis system, the open source ICTCLAS (Zhang et al. , 2003), to segment and POS tag the training and test corpora. 
Zhang et al (2003) use a hierarchical hidden Markov Model to incorporate lexical knowledge. 
Instead, we use an off-the-shelf Chinese lexical analysis system, the open source ICTCLAS (Zhang et al., 2003), to segment and POS tag the corpus. 
2001]s pseudo trigram integrated model, [Fu Guohong et al. 2001]s analyzer which incorporates backward Dynamic Programming and A* algorithm, [Sun Maosong, et al. 2003]s Divide and Conquer integration, [Zhang Huaping, et al. 2003]s hierarchical hidden Markov model and so on. 
The Chinese text processing uses word segmentation with the ICTCLAS segmenter (Zhang et al. , 2003). 
