Details of this approach to text processing can be found, e.g., in Nirenburg and Raskin 2004, Beale et al 2003, Nirenburg et al 2003a,b. The ontology itself, a brief ontology tutorial, and an extensive lexicon tutorial can be viewed at http://ilit.umbc.edu.


The acquisition of the fact repository is mixed, with some of it carried out manually and The approach to semantic analysis in OntoSem is described in some detail in, e.g., Nirenburg and Raskin 2004, Nire some of it resulting from the operation of the fact extractor on the results of semantic a nburg et al. 2003, Beale et al of pre-semantic text processing modules.


