To the best knowledge of the authors, the only other attempt to use computational inference methods for this task is Whitelaw and Patrick (2003).


Orthographic Tries (Cucerzan and Yarowsky, 1999; Whitelaw and Patrick, 2003; Whitelaw and Patrick, 2002) and character n-gram modelling (Patrick et al. , 2002) are two methods for capturing orthographic features.


All participants used lexical features (words) except for Whitelaw and Patrick (2003) who implemented a character-based method.


A majority vote of five systems (Chieu and Ng, 2003; Florian et al. , 2003; Klein et al. , 2003; McCallum and Li, 2003; Whitelaw and Patrick, 2003) performed best on the English development data.


Hidden Markov Models were employed by four of the systems that took part in the shared task (Florian et al. , 2003; Klein et al. , 2003; Mayfield et al. , 2003; Whitelaw and Patrick, 2003).


