The range of reports for any given patient at any given point in their illness thus present a special class of paraphrase, with a looser adherance to semantic equivalence between versions than is typically found in other paraphrase generators, for example Kozlowski et al (2003), McKeown et al (1994), Power, Scott and Bouyaad-Agha (2003), Rosner and Stede (1994),(1996), and Scott and Souza (1990).


1 Introduction Much work on paraphrase generation has focussed on lexical variation and syntactic transformation within individual sentences (Barzilay and McKeown, 2001; Carroll et al. , 1999; Dras, 1999; Inui and Nogami, 2001; Kozlowski et al. , 2003; Langkilde and Knight, 1998; Takahashi et al. , 2001; Stede, 1999).


This is in contrast to most existing paraphrase generators, which are constrained to vary only the first or second of these levels (Barzilay and McKeown, 2001; Carroll et al. , 1999; Dras, 1999; Inui and Nogami, 2001; Kozlowski et al. , 2003; Langkilde and Knight, 1998; Takahashi et al. , 2001; Stede, 1999).


NLG-based methods: NLG-based methods (Kozlowski et al., 2003; Power and Scott, 2005) generally involve two stages.


Lexical synonymy (She esteemed him highly vs. She respected him greatly), syntactic variation (John paid the bill vs. The bill was paid by John), overlapping meanings (Anna turned at Elm vs. Anna rounded the corner at Elm), and other phenomena interact to produce a broad range of choices for most language generation tasks (Hirst, 2003; Rinaldi et al. , 2003; Kozlowski et al. , 2003).


