C04-1090:1	155:186	We then performed word-align on the parsed corpus with the ProAlign system (Cherry&Lin 2003, Lin&Cherry 2003b).
---------------------------------------------------
C04-1090:2	50:186	Examples of transfer rules extracted from a word-aligned corpus 3.1 Spans The rule extraction algorithm makes use of the notion of spans (Fox 2002, Lin&Cherry 2003).
---------------------------------------------------
C04-1090:3	55:186	We used the word-alignment algorithm in (Lin&Cherry 2003a), which enforces a cohesion constraint that guarantees that if two spans overlap one must be fully contained in the other.
---------------------------------------------------
W03-0301:4	89:139	Team System name Description Language Technologies Institute, CMU BiBr (Zhao and Vogel, 2003) MITRE Corporation Fourday (Henderson, 2003) RALI Universite the Montreal Ralign (Simard and Langlais, 2003) Romanian Academy Institute of Artificial Intelligence RACAI (Tufis et al. , 2003) University of Alberta ProAlign (Lin and Cherry, 2003) University of Minnesota, Duluth UMD (Thomson McInnes and Pedersen, 2003) Xerox Research Centre Europe XRCE (Dejean et al. , 2003) Table 1: Teams participating in the word alignment shared task We conducted therefore 14 evaluations for each submission file: AER, Sure/Probable Precision, Sure/Probable Recall, and Sure/Probable F-measure, with a different figure determined for NULL-Align and NO-NULL-Align alignments.
---------------------------------------------------
P05-2022:5	141:149	In approaches such as Lin and Cherrys (2003), linguistic knowledge is considered secondary to statistical information even if it improves the alignment quality.
---------------------------------------------------
P05-2022:6	6:149	Mainly dedicated to machine translation, purely statistical systems have gradually been enriched with syntactic knowledge (Wu, 2000; Yamada & Knight, 2001; Ding et al. , 2003; Lin & Cherry, 2003).
---------------------------------------------------
W04-2207:7	165:171	However, concerning the approach proposed by Lin and Cherry (2003), it should be pointed out that linguistic knowledge is considered secondary to statistical information.
---------------------------------------------------
W04-2207:8	58:171	In this respect, the alignment method proposed is different from the ones developed by Wu (2000) as well as Lin and Cherry (2003): the former is based on synchronous parsing while the letter uses a dependency tree generated only in the source language.
---------------------------------------------------
W04-2207:9	163:171	Finally, Arhenberg, Andersson and Merkel (2000) as well as Lin and Cherry (2003) addressed the problem of full word alignment without restricting themselves to content words.
---------------------------------------------------
W04-2207:10	25:171	Various and more or less complex sources of linguistic knowledge are exploited: morphological, lexical (Arhenberg, Andersson and Merkel, 2000) and syntactic knowledge (Wu, 2000; Lin and Cherry, 2003).
---------------------------------------------------
W04-2207:11	27:171	However, as pointed out by Arhenberg, Andersson and Merkel (2000) as well as Lin and Cherry (2003), the introduction of linguistic knowledge leads to a significant improvement in alignment quality.
---------------------------------------------------
