The label and string position method is useful if one sees the task as inserting empty nodes into a string, and thus is quite useful for evaluating systems that detect empty categories without parse trees, as in Dienes and Dubey (2003a). 
This was the approach taken by Dienes and Dubey (2003a,b) and Dienes (2003); it is also practiced in recent work on broad-coverage CCG parsing (Hockenmaier, 2003). 
Jn is Johnson (2002); DD is Dienes and Dubey (2003b); Pres is the present work. 
Dienes and Dubey (2003) recover empty nodes as a preprocessing step and pass strings with gaps to their parser. 
This is important, since making parsers aware of non-local relations need not improve the overall performance: Dienes and Dubey (2003) report a decrease in PARSEVAL fscore from 88.2% to 86.4% after modifying Collins parser to resolve traces internally, although this allowed them to achieve high accuracy for traces. 
