Figure 1 shows the differences among the performances, indicated by the Receiver Operating Characteristics (ROC) curve (Section 4.1), of the existing RSCM on each of three MT systems (Section 4.2.1): D3, HPAT, and SAT (Doi and Sumita, 2003; Imamura et al. , 2003; Watanabe et al. , 2003).


D3 (DP-match Driven transDucer) is an example-based MT system using onlinegenerated translation patterns (Doi and Sumita, 2003).


Among them, the technique of splitting an input sentence and translating the split sentences appears promising (Doi and Sumita, 2003).


