ESL users have significantly more problems with determiner usage than native speakers because the use and omission of definite and indefinite articles varies across different languages (Schneider and McCoy, 1998)(Lonsdale and Strong-Krause, 2003).


Some researchers have begun to apply statistical techniques to identify learner errors in the context of essay evaluation (Chodorow & Leacock, 2000; Lonsdale & Strong-Krause, 2003), to detect non-native text (Tomokiyo & Jones, 2001), and to support lexical selection by ESL learners through first-language translation (Liu et al. , 2000).


Such applications include tutorial dialogue systems (Zinn et al. , 2002; Popescue et al. , 2003) and writing coaches that perform detailed assessments of writing content (Rose et al. , 2003; Wiemer-Hastings et al. , 1998; Malatesta et al. , 2002) as opposed to just grammar (Lonsdale and Strong-Krause, 2003), and provide detailed feedback rather than just letter grades (Burstein et al. , 1998; Foltz et al. , 1998).


