The banking corpus of several hundred calls has been collected first and it forms the basis of our initial multilingual triaging application, implemented for English, French and German (Hardy et al. , 2003a); as well as our prototype automatic financial services system, presented in this paper, which completes a variety of tasks in English.


For our corpus, we have used a modified DAMSL tag set (Allen and Core, 1997) to capture the functional layer of the dialogues, and a frame-based semantic scheme to record the semantic layer (Hardy et al. , 2003b).


Most of these strategies are rule-based, i.e., the dialogue strategy is defined by rules that are usually defined by a human expert (Gorin et al. , 1997; Hardy et al. , 2003).


