Supersense (PreBuilt Ontology) We borrow the idea of using WordNet lexicographer filenames as broad supersenses from Ciaramita and Johnson (2003). 
Results We have used the WORDNET 1.6 test set to experiment with different parameter settings and have kept the WORDNET 1.7.1 test set as a final comparison of best results with Ciaramita and Johnson (2003). 
Using this approach we have significantly outperformed the supervised multi-class perceptron Ciaramita and Johnson (2003). 
grained distinctions of WN (Hearst and Schutze, 1993) (Peters et al. , 1998) (Mihalcea and Moldovan, 2001) (Agirre et al. , 2003) and on using predefined sets of sense-groupings for learning class-based classifiers for WSD (Segond et al. , 1997) (Ciaramita and Johnson, 2003) (Villarejo et al. , 2005) (Curran, 2005) (Ciaramita and Altun, 2006). 
Ciaramita and Johnson (2003) call the noun lex-file classes supersenses. 
