6 Related Work Work related to toponym tagging has included harvesting of gazetteers from the Web (Uryupina 2003), hand-coded rules to place name disambiguation, e.g., (Li et al. 2003) (Zong et al. 2005), and machine learning approaches to the problem, e.g., (Smith and Mann 2003).


We will also study the effect of other window sizes and the combination of this unsupervised approach with minimally-supervised approaches such as (Brill 1995) (Smith and Mann 2003).


(Smith and Mann 2003) use a minimally supervised method that exploits as training data toponyms that are found locally disambiguated, e.g., Nashville, Tenn.; their disambiguation task is to identify the state or country associated with the toponym in test data that has those disambiguators stripped off.


