8http://translate.google.com 35 5 Related Work Most of the work in QA and paraphrasing focused on folding paraphrasing knowledge into the question analyzer or the answer locator (Rinaldi et al. , 2003; Tomuro, 2003).


Different technologies, such as definitions of different sets of question types, templates and sentence patterns (Noriko Tomuro, 2003) (Hyo-Jung Oh et al, 2005) machine learning methods (Radu Soricut and Eric Brill, 2004), language translation model (Jiwoon Jeon, W et al, 2005), composition of information needs of the complex question (Sanda Harabagiu et al, 2006) and so on, have been experimented on the processing of complex question, gearing the acquired information to the facility of other Q&A modules.


Several solutions to this problem have been proposed including query expansion (Riezler et al., 2007; Fang, 2008), query reformulation or paraphrasing (Hermjakob et al., 2002; Tomuro, 2003; Zukerman and Raskutti, 2002) and semantic information retrieval (Muller et al., 2007).


There are many previous work on paraphrase examples extraction or combining them with some applications such as information retrieval and question answering (Agichtein et al. , 2001; Florence et al. , 2003; Rinaldi et al. , 2003; Tomuro, 2003; Lin and Pantel, 2001;), information extraction (Shinyama et al. , 2002; Shinyama and Sekine, 2003), machine translation (Hiroshi et al. , 2003; Zhang and Yamamoto, 2003), multi-document (Barzilay et al. , 2003).


