A lot of machine learning techniques have been applied to resolve this problem, the n-gram language model is one of the most popular ones among them (Fu and Luke, 2003; Li et al. , 2005).


In our current system, we apply a known word bigram model to perform this task (Fu and Luke, 2003; Fu and Luke, 2004; Fu and Luke, 2005).


This strategy is obviously simple and more easily applicable (Fu and Luke, 2003).


