On limited resources, Ralign.EF.1 (Simard and Langlais, 2003) produced the best F-score, as well as the best AER when NULL alignments were taken into account, while XRCE.Nolem.EF.3 (Dejean et al. , 2003) produced the best AER when NULL alignments were discounted.


Team System name Description Language Technologies Institute, CMU BiBr (Zhao and Vogel, 2003) MITRE Corporation Fourday (Henderson, 2003) RALI Universite the Montreal Ralign (Simard and Langlais, 2003) Romanian Academy Institute of Artificial Intelligence RACAI (Tufis et al. , 2003) University of Alberta ProAlign (Lin and Cherry, 2003) University of Minnesota, Duluth UMD (Thomson McInnes and Pedersen, 2003) Xerox Research Centre Europe XRCE (Dejean et al. , 2003) Table 1: Teams participating in the word alignment shared task We conducted therefore 14 evaluations for each submission file: AER, Sure/Probable Precision, Sure/Probable Recall, and Sure/Probable F-measure, with a different figure determined for NULL-Align and NO-NULL-Align alignments.


Another approach is the binary segmentation method described in (Simard and Langlais, 2003), (Xu et al. , 2005) and (Deng et al. , 2006), which separates a long sentence pair into two sub-pairs recursively.


