J05-4005:1	671:855	(Li et al. 2003).
---------------------------------------------------
J05-4005:2	226:855	The segmentation of the gold test set depends upon a reference lexicon, which is the combination of several lexicons that are used in Microsoft applications, including a Chinese text input system (Gao et al. 2002), ASR (Chang et al. 2001), TTS (Chu et al. 2003), and the MSR-NLP Chinese parser (Wu and Jiang 2000).
---------------------------------------------------
