N06-1055:1	121:170	Our parser is similar to (Luo, 2003) and is trained and tested on the same data partition as the semantic role labeling system.
---------------------------------------------------
N06-1055:2	123:170	The results are comparable with those reported in Luo (Luo, 2003), but they cannot be directly compared with most of the results reported in the literature, where correct segmentation is assumed.
---------------------------------------------------
W06-0138:3	16:91	Ng and Low (2004) and Luo (2003) also trained single joint models over the Chinese segmentation and POS tagging subtasks.
---------------------------------------------------
D08-1060:4	136:222	The Chinese side of these two corpora were parsed using a constituency parser (Luo, 2003).
---------------------------------------------------
P06-1054:5	192:237	Luo (2003) and Fung et al.
---------------------------------------------------
P06-1054:6	77:237	Maximum-entropy models have been used for Chinese character-based parsing (Fung et al. , 2004; Luo, 2003) and POS tagging (Ng and Low, 2004).
---------------------------------------------------
C08-1113:7	58:177	In addition, the boundary agreement is even lower in Chinese (Luo, 2003).
---------------------------------------------------
E09-1031:8	181:210	Among these, we would like to mention Luo (2003), who reports an SF 96.0% on Chinese Treebank (CTB) data, and (Fung et al., 2004), who achieve a word segmentation precision/recall performance of 93/94%.
---------------------------------------------------
