E06-3004:1	9:290	(Klein et al. , 2003), (Mayfield et al. , 2003), (Wu et al. , 2003), (Kozareva et al. , 2005c) among others, combined several classifiers to obtain better named entity coverage rate.
---------------------------------------------------
W03-0419:2	84:153	Two teams used AdaBoost.MH (Carreras et al. , 2003b; Wu et al. , 2003) and two other groups employed memory-based learning (De Meulder and Daelemans, 2003; Hendrickx and Van den Bosch, 2003).
---------------------------------------------------
W03-0419:3	102:153	Most of the systems employed part-of-speech tags and two of them have recomputed the English tags with better taggers (Hendrickx and Van den Bosch, 2003; Wu et al. , 2003).
---------------------------------------------------
W03-0419:4	103:153	Othographic information, affixes, gazetteers and chunk information were also incorporated in most systems although one group reports that the available chunking information did not help (Wu et al. , 2003) Other features were used less frequently.
---------------------------------------------------
N04-4010:5	11:168	There has been a considerable amount of work on English NER yielding good performance (Tjong Kim Sang et al. 2002, 2003; Cucerzan & Yarowsky 1999; Wu et al. 2003).
---------------------------------------------------
