Third, in many current segmenters, OOV identification is considered a separate process from segmentation (e.g. , Chen 2003; Wu and Jiang 2000; Chen and Bai 1998). 
The other is to detect new words on-line, i.e., to spot new words in a sentence on the fly during the process of word segmentation (e.g. , Chen 2003; Wu and Jiang 2000). 
Those differences are considered as segmentation inconsistencies by some researchers (Wu, 2003; Chen, 2003). 
Same as (Chen, 2003), we divided the training data as training data and developing data to find an exactly value of the threshold. 
More details on the segmentation algorithm and the preprocessors and postprocessors can be found in (Chen, 2003). 
