Figure 1 shows an example of summary sentences and original sentences from TSC-2 (Text Summarization Challenge 2) multiple document summarization data (Okumura et al. , 2003).


4 Experiments on identifying EQ pairs We used the Text Summarization Challenge (TSC) 2 and 3 corpora (Okumura et al., 2003) and the Workshop on Multimodal Summarization for Trend Information (Must) corpus (Kato et al., 2005).


Multiple document summarization was included for the first time as one of the tasks at TSC2 (in 2002) (Okumura et al. , 2003).


