The tag set for Chinese and English PropBanks are to a large extent similar and more details can be found in (Xue and Palmer, 2003). 
The same annotation philosophy has been extended to the Penn Chinese Proposition Bank (Xue and Palmer, 2003). 
After the PropBank (Xue and Palmer 2003) was built, Xue and Palmer (2005) and Xue (2008) have produced more complete and systematic research on Chinese SRL. 
The functional tags for Chinese and English PropBanks are to a large extent similar and more details can be found in (Xue and Palmer, 2003). 
The PropBank annotation philosophy has been extended to the Penn Chinese Proposition Bank (Xue and Palmer, 2003). 
