But the most striking characteristic of this domain is the frequency of MultiWord Terms (MWT) which are known to cause serious problems for NLP systems (Sag et al. , 2002), (Dowdall et al. , 2003).


We have focused our attention in particular to the relations of synonymy and hyponymy, which are detected as described in (Dowdall et al. , 2003) and gathered in a Thesaurus.


In an initial phase all multi-word expressions from the domain are collected and structured in an external resource, which we will refer to as the TermBase (Rinaldi et al. , 2003; Dowdall et al. , 2003).


