W06-3301:1	146:155	For example, researchers (Turney 2002; Yu and Hatzivassiloglou 2003) have identified semantic correlation between words and views: positive words tend to appear more frequently in positive movie and product reviews and newswire article sentences that have a positive semantic orientation and vice versa for negative reviews or sentences with a negative semantic orientation.
---------------------------------------------------
W06-0302:2	12:190	(2004), Yu and Hatzivassiloglou (2003), Wiebe and Riloff (2005)) have shown that sentiment information can be extracted at the sentence, clause, or individualopinionexpressionlevel(fine-grainedopinion information).
---------------------------------------------------
W06-0302:3	45:190	(2004), Yu and Hatzivassiloglou (2003), Wiebe and Riloff (2005)).
---------------------------------------------------
W06-1652:4	185:189	Lexical cues of differing complexities have been used, including single words and Ngrams (e.g. , (Mullen and Collier, 2004; Pang et al. , 2002; Turney, 2002; Yu and Hatzivassiloglou, 2003; Wiebe et al. , 2004)), as well as phrases and lexico-syntactic patterns (e.g, (Kim and Hovy, 2004; Hu and Liu, 2004; Popescu and Etzioni, 2005; Riloff and Wiebe, 2003; Whitelaw et al. , 2005)).
---------------------------------------------------
D08-1049:5	158:180	Sentencelevel subjectivity classification (e.g., (Riloff and Wiebe, 2003; Yu and Hatzivassiloglou, 2003)) and sentiment classification (e.g., (Yu and Hatzivassiloglou, 2003; Kim and Hovy, 2004; Hu and Liu, 2004; Popescu and Etzioni, 2005)) is the research in text most closely related to our work.
---------------------------------------------------
N06-3005:6	29:72	So far research in automatic opinion recognition has primarily addressed learning subjective language (Wiebe et al. , 2004; Riloff et al. , 2003; Riloff and Wiebe, 2003), identifying opinionated documents (Yu and Hatzivassiloglou, 2003) and sentences (Yu and Hatzivassiloglou, 2003; Riloff et al. , 2003; Riloff and Wiebe, 2003), and discriminating between positive and negative language (Yu and Hatzivassiloglou, 2003; Turney and Littman, 2003; Pang et al. , 2002; Dave et al. , 2003; Nasukawa and Yi, 2003; Morinaga et al. , 2002).
---------------------------------------------------
P06-1134:7	36:194	The second is subjectivity classification of sentences, clauses, phrases, or word instances in the context of a particular text or conversation, either subjective/objective classifications or positive/negative sentiment classifications (e.g. ,(Riloff and Wiebe, 2003; Yu and Hatzivassiloglou, 2003; Dave et al. , 2003; Hu and Liu, 2004)).
---------------------------------------------------
P06-1134:8	188:194	Second, a number of methods for subjectivity or sentiment analysis start with a set of seed words and then search through WordNet to find other subjective words (Kamps and Marx, 2002; Yu and Hatzivassiloglou, 2003; Hu and Liu, 2004; Kim and Hovy, 2004; Esuli and Sebastiani, 2005).
---------------------------------------------------
P06-1134:9	39:194	and question answering (e.g. , (Yu and Hatzivassiloglou, 2003; Stoyanov et al. , 2005)).
---------------------------------------------------
H05-1116:10	34:241	(2004), Yu and Hatzivassiloglou (2003), Wiebe and Riloff (2005)).
---------------------------------------------------
D09-1140:11	36:237	Yu and Hatzivassiloglou (2003) addressed three challenges in the news article domain: discriminating between objective documents and subjective documents such as editorials, detecting subjectivity at the sentence level, and determining polarity at the sentence level.
---------------------------------------------------
C04-1200:12	8:153	We wish to study opinion in general; our work most closely resembles that of (Yu and Hatzivassiloglou 2003).
---------------------------------------------------
C04-1200:13	11:153	For example, the following opinions contain Claims but no Sentiments: I believe the world is flat The Gap is likely to go bankrupt Bin Laden is hiding in Pakistan Water always flushes anti-clockwise in the southern hemisphere Like Yu and Hatzivassiloglou (2003), we want to automatically identify Sentiments, which in this work we define as an explicit or implicit expression in text of the Holders positive, negative, or neutral regard toward the Claim about the Topic.
---------------------------------------------------
N09-1001:14	27:199	2 Related Work There has been a large and diverse body of research in opinion mining, with most research at the text (Pang et al., 2002; Pang and Lee, 2004; Popescu and Etzioni, 2005; Ounis et al., 2006), sentence (Kim and Hovy, 2005; Kudo and Matsumoto, 2004; Riloff et al., 2003; Yu and Hatzivassiloglou, 2003) or word (Hatzivassiloglou and McKeown, 1997; Turney and Littman, 2003; Kim and Hovy, 2004; Takamura et al., 2005; Andreevskaia and Bergler, 2006; Kaji and Kitsuregawa, 2007) level.
---------------------------------------------------
D07-1114:15	80:239	Open-domain opinion extraction is another trend of research on opinion extraction, which aims to extract a wider range of opinions from such texts as newspaper articles (Yu and Hatzivassiloglou, 2003; Kim and Hovy, 2004; Wiebe et al. , 2005; Choi et al. , 2006).
---------------------------------------------------
P05-1015:16	9:189	Most prior work on the speci c problem of categorizing expressly opinionated text has focused on the binary distinction of positive vs. negative (Turney, 2002; Pang, Lee, and Vaithyanathan, 2002; Dave, Lawrence, and Pennock, 2003; Yu and Hatzivassiloglou, 2003).
---------------------------------------------------
W06-1650:17	33:189	Yu and Hatzivassiloglou (2003) identified the polarity of opinion sentences using semantically oriented words.
---------------------------------------------------
P09-1029:18	27:211	While these features are usually employed by data-driven approaches, there are unsupervised approaches for sentiment analysis that make use of a set of terms that are semantically oriented toward expressing subjective statements (Yu and Hatzivassiloglou, 2003).
---------------------------------------------------
W06-0305:19	48:177	Most of the annotation approaches tackling these issues, however, are aimed at performing classifications at either the document level (Pang et al. , 2002; Turney, 2002), or the sentence or word level (Wiebe et al. , 2004; Yu and Hatzivassiloglou, 2003).
---------------------------------------------------
N07-1038:20	32:212	2 Related Work Sentiment Classi cation Traditionally, categorization of opinion texts has been cast as a binary classication task (Pang et al. , 2002; Turney, 2002; Yu and Hatzivassiloglou, 2003; Dave et al. , 2003).
---------------------------------------------------
N07-1038:21	9:212	1 Introduction Previous work on sentiment categorization makes an implicit assumption that a single score can express the polarity of an opinion text (Pang et al. , 2002; Turney, 2002; Yu and Hatzivassiloglou, 2003).
---------------------------------------------------
D07-1113:22	52:290	Yu and Hatzivassiloglou (2003) identified the polarity of opinion sentences using semantically oriented words.
---------------------------------------------------
D09-1020:23	217:249	They may rely only on this information (e.g., (Turney, 2002; Whitelaw et al., 2005; Riloff and Wiebe, 2003)), or they may combine it with additional information as well (e.g., (Yu and Hatzivassiloglou, 2003; Kim and Hovy, 2004; Bloom et al., 2007; Wilson et al., 2005a)).
---------------------------------------------------
D09-1020:24	40:249	Second, benefits for sentiment analysis can be realized by decomposing the problem into S/O (or neutral versus polar) and polarity classification (Yu and Hatzivassiloglou, 2003; Pang and Lee, 2004; Wilson et al., 2005a; Kim and Hovy, 2006).
---------------------------------------------------
E09-1004:25	44:247	2 Literature Survey The task of sentiment analysis has evolved from document level analysis (e.g., (Turney., 2002); (Pang and Lee, 2004)) to sentence level analysis (e.g., (Hu and Liu., 2004); (Kim and Hovy., 2004); (Yu and Hatzivassiloglou, 2003)).
---------------------------------------------------
W06-0306:26	24:190	In analyzing opinions (Cardie et al. , 2003; Wilson et al. , 2004), judging document-level subjectivity (Pang et al. , 2002; Turney, 2002), and answering opinion questions (Cardie et al. , 2003; Yu and Hatzivassiloglou, 2003), the output of a sentence-level subjectivity classification can be used without modification.
---------------------------------------------------
D09-1063:27	21:211	Automatic approaches to creating a semantic orientation lexicon and, more generally, approaches for word-level sentiment annotation can be grouped into two kinds: (1) those that rely on manually created lexical resourcesmost of which use WordNet (Strapparava and Valitutti, 2004; Hu and Liu, 2004; Kamps et al., 2004; Takamura et al., 2005; Esuli and Sebastiani, 2006; An1http://www.wjh.harvard.edu/ inquirer 599 dreevskaia and Bergler, 2006; Kanayama and Nasukawa, 2006); and (2) those that rely on text corpora (Hatzivassiloglou and McKeown, 1997; Turney and Littman, 2003; Yu and Hatzivassiloglou, 2003; Grefenstette et al., 2004).
---------------------------------------------------
E06-1025:28	12:169	This amounts to performing binary text categorization under categories Objective and Subjective (Pang and Lee, 2004; Yu and Hatzivassiloglou, 2003); 2.
---------------------------------------------------
P07-1123:29	32:193	3 A Lexicon-Based Approach Many subjectivity and sentiment analysis tools rely on manually or semi-automatically constructed lexicons (Yu and Hatzivassiloglou, 2003; Riloff and Wiebe, 2003; Kim and Hovy, 2006).
---------------------------------------------------
P07-1123:30	19:193	First, even when sentiment is the desired focus, researchers in sentiment analysis have shown that a two-stage approach is often beneficial, in which subjective instances are distinguished from objective ones, and then the subjective instances are further classified according to polarity (Yu and Hatzivassiloglou, 2003; Pang and Lee, 2004; Wilson et al. , 2005; Kim and Hovy, 2006).
---------------------------------------------------
P07-1123:31	17:193	2 Motivation Automatic subjectivity analysis methods have been used in a wide variety of text processing applications, such as tracking sentiment timelines in online forums and news (Lloyd et al. , 2005; Balog et al. , 2006), review classification (Turney, 2002; Pang et al. , 2002), mining opinions from product reviews (Hu and Liu, 2004), automatic expressive text-to-speech synthesis (Alm et al. , 2005), text semantic analysis (Wiebe and Mihalcea, 2006; Esuli and Sebastiani, 2006), and question answering (Yu and Hatzivassiloglou, 2003).
---------------------------------------------------
P07-1123:32	105:193	This approach builds a subjectivity-annotated corpus for the target language through projection, and then trains a statistical classifier on the resulting corpus (numerous statistical classifiers have been trained for subjectivity or sentiment classification, e.g., (Pang et al. , 2002; Yu and Hatzivassiloglou, 2003)).
---------------------------------------------------
W06-1640:33	50:223	(2004), Yu and Hatzivassiloglou (2003), Choi et al.
---------------------------------------------------
W05-0408:34	37:174	Yu and Hatzivassiloglou (2003) extend this approach by (1) applying it at the sentence level (instead of the document-level), (2) taking into account non-adjectival parts-of-speech, and (3) 1 For domain-specificity of sentiment classification see Engstrm (2004) and Aue and Gamon (2005).
---------------------------------------------------
W05-0408:35	10:174	1 Introduction The field of sentiment classification has received considerable attention from researchers in recent years (Pang and Lee 2002, Pang et al. 2004, Turney 2002, Turney and Littman 2002, Wiebe et al. 2001, Bai et al. 2004, Yu and Hatzivassiloglou 2003 and many others).
---------------------------------------------------
W06-2915:36	35:149	So far, research in automatic opinion recognition has primarily addressed learning subjective language (Wiebe et al. , 2004; Riloff et al. , 2003), identifying opinionated documents (Yu and Hatzivassiloglou, 2003) and sentences (Yu and Hatzivassiloglou, 2003; Riloff et al. , 2003), and discriminating between positive and negative language (Pang et al. , 2002; Morinaga et al. , 2002; Yu and Hatzivassiloglou, 2003; Turney and Littman, 2003; Dave et al. , 2003; Nasukawa and Yi, 2003; Popescu and Etzioni, 2005; Wilson et al. , 2005).
---------------------------------------------------
C08-1135:37	26:153	Yu and Hatzivassiloglou (2003) use semanticallyoriented words for identification of polarity at the sentence level.
---------------------------------------------------
I05-2011:38	59:161	Following the insight of Yu and Hatzivassiloglou (2003), we made the basic and rough assumption that words that appear more often in newspaper editorials and letters to the editor than in non-editorial news articles could be potential opinion-bearing words (even though editorials contain sentences about factual events as well).
---------------------------------------------------
P09-1083:39	44:211	(Yu and Hatzivassiloglou, 2003) discusses a necessary component for an opinion question answering system: separating opinions from fact at both the document and sentence level.
---------------------------------------------------
P09-1083:40	116:211	We extract several types of features, including a set of pattern features, and then design a classifier to identify sentiment polarity for each question (similar as (Yu and Hatzivassiloglou, 2003)).
---------------------------------------------------
N09-1056:41	38:259	(Yu and Hatzivassiloglou, 2003; Wiebe et al., 2004; Finn and Kushmerick, 2006; Ni et al., 2007; Stepinski and Mittal, 2007).
---------------------------------------------------
W09-1904:42	28:182	While manual intervention for compiling lexicons has been significantly lessened by bootstrapping techniques (Yu and Hatzivassiloglou, 2003; Wiebe and Riloff, 2005), manual intervention in the annotation process is harder to avoid.
---------------------------------------------------
H05-1045:43	19:194	(2004), Yu and Hatzivassiloglou (2003)).
---------------------------------------------------
H05-1045:44	14:194	(2004), Yu and Hatzivassiloglou (2003), Wiebe and Riloff (2005)).
---------------------------------------------------
P06-1133:45	44:268	There are studies on learning subjective language (Wiebe et al. , 2004), identifying opinionated documents (Yu and Hatzivassiloglou, 2003) and sentences (Riloff et al. , 2003; Riloff and Wiebe, 2003), and discriminating between positive and negative language (Turney and Littman, 2003; Pang et al. , 2002; Dave et al. , 2003; Nasukawa and Yi, 2003; Morinaga et al. , 2002).
---------------------------------------------------
N09-1002:46	41:226	In fact, researchers in sentiment analysis have realized benefits by decomposing the problem into S/O and polarity classification (Yu and Hatzivassiloglou, 2003; Pang and Lee, 2004; Wilson et al., 2005; Kim and Hovy, 2006).
---------------------------------------------------
W07-2022:47	9:73	While such categorization at the sentence level remains relatively unexplored1, the two related sentence-level, binary classification tasks ??positive vs. negative and subjective vs. objective ??have attracted considerable attention in the recent years (Hu and Liu, 2004; Kim and Hovy, 2005; Riloff et al. , 2006; Turney and Littman, 2003; Yu and Hatzivassiloglou, 2003).
---------------------------------------------------
W07-2022:48	11:73	These approaches rely on presence and scores of sentiment-bearing words that have been acquired from dictionaries (Kim and Hovy, 2005) or corpora (Yu and Hatzivassiloglou, 2003).
---------------------------------------------------
W06-1642:49	42:252	For example, Yu and Hatzivassiloglou (2003) separated facts from opinions and assigned polarities only to opinions.
---------------------------------------------------
E06-1027:50	39:146	The first group includes methods that rely on syntactic or co-occurrence patterns of words in large texts to determine their sentiment (e.g. , (Turney and Littman, 2002; Hatzivassiloglou and McKeown, 1997; Yu and Hatzivassiloglou, 2003; Grefenstette et al. , 2004) and others).
---------------------------------------------------
W05-0308:51	209:216	In addition to Appraisal Theory, subjectivity annotation of text in context has also been performed in Yu and Hatzivassiloglou (2003), Bruce and Wiebe (1999), and Wiebe et al.
---------------------------------------------------
W05-0308:52	211:216	The annotations in Yu and Hatzivassiloglou (2003) are sentence-level subjective vs. objective and polarity judgments.
---------------------------------------------------
C04-1057:53	72:156	This approach has been recently applied to the construction of paragraph-long answers (e.g. , (Blair-Goldensohn et al. , 2003; Yu and Hatzivassiloglou, 2003)).
---------------------------------------------------
H05-1044:54	180:197	Yu and Hatzivassiloglou (2003), Kim and Hovy (2004), Hu and Liu (2004), and Grefenstette et al.
---------------------------------------------------
P06-2059:55	281:288	6.3 Unsupervised sentiment classification Turney proposed the unsupervised method for sentiment classification (Turney, 2002), and similar method is utilized by many other researchers (Yu and Hatzivassiloglou, 2003).
---------------------------------------------------
P04-1035:56	53:149	Interestingly, Yu and Hatzivassiloglou (2003) compared an individual-preference classifier against a relationship-based method, but didnt combine the two; the ability to coordinate such algorithms is precisely one of the strengths of our approach.
---------------------------------------------------
P04-1035:57	21:149	Yu and Hatzivassiloglou (2003) provide methods for sentencelevel analysis and for determining whether a document is subjective or not, but do not combine these two types of algorithms or consider document polarity classification.
---------------------------------------------------
C04-1121:58	18:115	There is also a considerable amount of research on classification of text as subjective or objective (Wiebe et al 2001, Yu and Hatzivassiloglou 2003), a task that is not relevant for the processing of very brief pieces of direct customer feedback.
---------------------------------------------------
N06-1026:59	16:213	Yu and Hatzivassiloglou (2003) identified the polarity of opinion sentences using semantically oriented words.
---------------------------------------------------
D09-1019:60	291:344	Another important direction is classifying sentences as subjective or objective, and classifying subjective sentences or clauses as positive or negative (Wiebe et al, 1999; Wiebe and Wilson, 2002, Yu and Hatzivassiloglou, 2003; Wilson et al, 2004; Kim and Hovy, 2004; Riloff and Wiebe, 2005; Gamon et al 2005; McDonald et al, 2007).
---------------------------------------------------
D09-1019:61	13:344	There are many research directions, e.g., sentiment classification (classifying an opinion document as positive or negative) (e.g., Pang, Lee and Vaithyanathan, 2002; Turney, 2002), subjectivity classification (determining whether a sentence is subjective or objective, and its associated opinion) (Wiebe and Wilson, 2002; Yu and Hatzivassiloglou, 2003; Wilson et al, 2004; Kim and Hovy, 2004; Riloff and Wiebe, 2005), feature/topic-based sentiment analysis (assigning positive or negative sentiments to topics or product features) (Hu and Liu 2004; Popescu and Etzioni, 2005; Carenini et al., 2005; Ku et al., 2006; Kobayashi, Inui and Matsumoto, 2007; Titov and McDonald.
---------------------------------------------------
D08-1098:62	201:220	For example, reference (Yu, H., and Hatzivassiloglou, V. 2003; Somasundaran et 944 al. 2007) attempted to classify sentences into those reporting facts or opinions.
---------------------------------------------------
P06-2079:63	34:254	(2003), Yu and Hatzivassiloglou (2003), Kim and Hovy (2004), Gamon et al.
---------------------------------------------------
P06-2079:64	93:254	Admittedly, the high accuracy achieved using such a simple set of features is somewhat surprising, although it is consistent with previous results on document-level subjectivity classification in which accuracies of 94-97% were obtained (Yu and Hatzivassiloglou, 2003; Wiebe et al. , 2004).
---------------------------------------------------
P06-2079:65	30:254	There have been attempts on tackling this so-called document-level subjectivity classification task, with very encouraging results (see Yu and Hatzivassiloglou (2003) and Wiebe et al.
---------------------------------------------------
P06-2079:66	62:254	Indeed, recent work has shown that benefits can be made by first separating facts from opinions in a document (e.g, Yu and Hatzivassiloglou (2003)) and classifying the polarity based solely on the subjective portions of the document (e.g. , Pang and Lee (2004)).
---------------------------------------------------
