4 Related Work A large body of literature related to statistical methods for coreference resolution is available (Ng and Cardie, 2003; Yang et al., 2003; Ng, 2008; Poon and 5 Table 3: Results of document-level boosting Iteration Accuracy (%) 1 78.53 2 78.82 3 79.08 4 78.37 Domingos, 2008; McCallum and Wellner, 2003).


The experiments described in this paper could be seen as providing 57 a bootstrapped model (Riloff and Jones, 1999; Ng and Cardie, 2003)in ML, bootstrapping requires to seed the classifier with a small number of well chosen target examples.


