The underlying data model for LMF follows the general principles of the linguistic annotation scheme design stated in Ide & Romary, 2003 and implemented in the context of ISO standard 16642 for the representation of terminological data (Romary, 2001).


It is also in the spirit of the proposal for a Linguistic Annotation Framework (LAF) under development by Working Group 1-1 of ISO TC 37 SC 4 [www.tc37sc4.org] (Ide and Romary, 2003; Ide, Romary and de la Clergerie, 2003), but differs from it in some significant ways.


The data categories of the LAF correspond to the concepts in GOLD; however the creation of an ontology of annotation classes and types is not yet part of the LAF (Ide, Romary and de la Clergerie 2003).


