An example from Schubert and Tong (2003) of factoids obtained from a sentence in the Brown corpus by their KNEXT system is the following: Rilly or Glendora had entered her room while she slept, bringing back her washed clothes.


Methods currently exist for extracting simple factoids like those about ice cream and children just mentioned (see in particular (Schubert, 2002; Schubert and Tong, 2003)), but these are quite weak as general claims, and  being unconditional  are unsuitable for inference chaining.


In the same year, Schubert (2002) described a project aimed directly at the extraction of general world knowledge from Treebank text, and Schubert and Tong (2003) providedthe results of hand-assessment of the resulting propositions.


Initial evaluation was done using the method proposed in Schubert and Tong (2003), in which judges were asked to label propositions according to their category of acceptability; abbreviated instructions may be seen in Figure 1.7 Under this framework, category one corresponds to a strict assessment of acceptability, while an assignment to any of the categories between one and three may be interpreted as a weaker level of acceptance.


The quality of resulting propositions has been assessed by the hand-judging methodology of Schubert and Tong (2003), yielding positive judgements almost as frequently as for the Brown Treebank corpus.


