3.2 Using a General Corpus In the experiments presented in Hulth (2003a), only the documents present in the training, validation, and test set respectively are used for calculating the collection frequency. 
More linguistic knowledge has been explored by Hulth (2003). 
The result of Hulths method listed in this table is the best one reported in (Hulth, 2003) on the same dataset. 
3.1 Refining the NP-chunk Approach It was noted in Hulth (2003b) that when extracting NPchunks, the accompanying determiners are also extracted (per definition), but that determiners are rarely found at the initial position of keywords. 
As indicated in (Hulth, 2003; Mihalcea and Tarau, 2004), in uncontrolled manually assigned keyphrases, only the ones that occur in the corresponding abstracts are considered in evaluation. 
