The architecture employed in this paper improves on (Crysmann et al. , 2002) by providing a central Whiteboard Annotation Transformer (WHAT) that supports flexible and powerful access to and transformation of XML annotation based on standard XSLT engines 6 (see (Schafer, 2003) for more details on WHAT).


The general idea has already been presented in (Schafer, 2003), but the developments and experiences since then have encouraged us to proceed in that direction and Heart of Gold can be considered as a successful, more elaborated proof of concept.


In the workshop, we hope to further report on the combination of WHAT (Schafer, 2003), an XSLT-based annotation transformer, with SDL.


