On the other hand, the existing machine learning-based methods (Aone and Bennett, 1995; McCarthy and Lehnert, 1995; Soon et al., 2001; Ng and Cardie, 2002; Seki et al., 2002; Isozaki and Hirao, 2003; Iida et al., 2005; Iida et al., 2007a, etc.) have been developed with less attention given to such a problem.


Isozakiand Hirao (2003) and Iida et al.


Accordingly, anaphora resolution, which is positioned as the next step of parsing, has been studied actively (Ng and Cardie, 2002; Yang et al. , 2003; Iida et al. , 2003; Isozaki and Hirao, 2003; Kawahara and Kurohashi, 2004).


