10 most frequent 3-grams extracted from 290,000 words of learner interview data 4 Discontinuous MWEs and n-grams are nevertheless important, which is reflected in the development of more refined extraction methods (e.g. positional n-grams (Gil and Dias, 2003) and ConcGrams (Chen et al. 2006)).


The choice of n-grams, described as one of the most successful statistical models (Gil and Dias, 2003), was based on several reasons.


2.4 Mutual expectation An interesting proposal which seeks to overcome the variable-length issue is the mutual expectation metric presented in Dias, Guillor, and Lopes (1999) and implemented in the SENTA system (Gil and Dias 2003a).


The availability of new techniques for handling large sets of n-gram data (e.g. Gil & Dias 2003b) make this a relatively feasible task.


