Mann & Yarowsky (2003) extracted local biographical information as features. 
2.2 CDC Using Fuzzy Relational Clustering 2.2.1 Preliminaries Traditionally, hard clustering algorithms (where uij  {0,1}) such as complete linkage hierarchical agglomerative clustering (Mann and Yarowsky, 2003) have been applied to the disambiguation problem. 
Several similar approaches have been proposed (Brin, 1998; Agichtein and Gravano, 2000; Ravichandran and Hovy, 2002), with various applications: Question-Answering (Ravichandran and Hovy, 2002), multi-document Named Entity Coreference (Mann and Yarowsky, 2003), and generating biographical information (Mann and Yarowsky, 2005). 
This work follows on the work of Bagga & Baldwin (1998), Mann & Yarowsky (2003), Niu et al. 
2 Related Work (Mann and Yarowsky, 2003) first extract biographical information, such as birthdates, birthplaces, occupations, and so on. 
