W06-0302:1	43:190	(2003), Riloff and Wiebe (2003), Bethard et al.
---------------------------------------------------
W06-0302:2	12:190	(2004), Yu and Hatzivassiloglou (2003), Wiebe and Riloff (2005)) have shown that sentiment information can be extracted at the sentence, clause, or individualopinionexpressionlevel(fine-grainedopinion information).
---------------------------------------------------
W06-0302:3	10:190	Several research efforts (e.g. Riloff and Wiebe (2003), Bethard et al.
---------------------------------------------------
W06-0302:4	20:190	Our work is concerned with fine-grained expressions of opinions and assumes that a system can rely on the results of effective opinion and source extractors such as those described in Riloff and Wiebe (2003), Bethard et al.
---------------------------------------------------
W06-0302:5	45:190	(2004), Yu and Hatzivassiloglou (2003), Wiebe and Riloff (2005)).
---------------------------------------------------
P08-1041:6	150:250	The major source of this list is from (Riloff and Wiebe, 2003) with additional words from other sources.
---------------------------------------------------
W06-1652:7	32:189	(Riloff and Wiebe, 2003) explored the idea of using extraction patterns to represent more complex subjective expressions that have noncompositional meanings.
---------------------------------------------------
W06-1652:8	43:189	AutoSlog has been used to learn IE patterns for the domains of terrorism, joint ventures, and microelectronics (Riloff, 1996), as well as for opinion analysis (Riloff and Wiebe, 2003).
---------------------------------------------------
W06-1652:9	37:189	For example: stepped on <mods> toes Ex: stepped on the boss toes dealt <np> <mods> blow Ex: dealt the company a decisive blow brought <np> to <mods> knees Ex: brought the man to his knees (Riloff and Wiebe, 2003) also showed that syntactic variations of the same verb phrase can behave very differently.
---------------------------------------------------
W06-1652:10	185:189	Lexical cues of differing complexities have been used, including single words and Ngrams (e.g. , (Mullen and Collier, 2004; Pang et al. , 2002; Turney, 2002; Yu and Hatzivassiloglou, 2003; Wiebe et al. , 2004)), as well as phrases and lexico-syntactic patterns (e.g, (Kim and Hovy, 2004; Hu and Liu, 2004; Popescu and Etzioni, 2005; Riloff and Wiebe, 2003; Whitelaw et al. , 2005)).
---------------------------------------------------
D08-1049:11	158:180	Sentencelevel subjectivity classification (e.g., (Riloff and Wiebe, 2003; Yu and Hatzivassiloglou, 2003)) and sentiment classification (e.g., (Yu and Hatzivassiloglou, 2003; Kim and Hovy, 2004; Hu and Liu, 2004; Popescu and Etzioni, 2005)) is the research in text most closely related to our work.
---------------------------------------------------
W05-0305:12	53:201	3 3 Annotation of attribution Wiebe and her colleagues have pointed out the importance of ascribing beliefs and assertions expressed in text to the agent(s) holding or making them (Riloff and Wiebe, 2003; Wiebe et al. , 2004; Wiebe et al. , 2005).
---------------------------------------------------
D09-1131:13	19:270	Riloff and Wiebe (2003) learned the extraction patterns for subjective expressions.
---------------------------------------------------
W06-0303:14	28:185	For process (2), existing methods aim to distinguish between subjective and objective descriptions in texts (Kim and Hovy, 2004; Pang and Lee, 2004; Riloff and Wiebe, 2003).
---------------------------------------------------
N06-3005:15	29:72	So far research in automatic opinion recognition has primarily addressed learning subjective language (Wiebe et al. , 2004; Riloff et al. , 2003; Riloff and Wiebe, 2003), identifying opinionated documents (Yu and Hatzivassiloglou, 2003) and sentences (Yu and Hatzivassiloglou, 2003; Riloff et al. , 2003; Riloff and Wiebe, 2003), and discriminating between positive and negative language (Yu and Hatzivassiloglou, 2003; Turney and Littman, 2003; Pang et al. , 2002; Dave et al. , 2003; Nasukawa and Yi, 2003; Morinaga et al. , 2002).
---------------------------------------------------
N06-3005:16	36:72	We evaluate the subjectivity of each sentence using the patterns automatically extracted from foreign news documents (Riloff and Wiebe, 2003), and find that 65.6% of Palestinian sentences and 66.2% of Israeli sentences are classified as subjective.
---------------------------------------------------
P06-1134:17	155:194	We use the rule-based subjective sentence classifier of (Riloff and Wiebe, 2003) to assign an S, O, or B label to all the training and test examples pertaining to these ambiguous words.
---------------------------------------------------
P06-1134:18	36:194	The second is subjectivity classification of sentences, clauses, phrases, or word instances in the context of a particular text or conversation, either subjective/objective classifications or positive/negative sentiment classifications (e.g. ,(Riloff and Wiebe, 2003; Yu and Hatzivassiloglou, 2003; Dave et al. , 2003; Hu and Liu, 2004)).
---------------------------------------------------
D08-1058:19	55:180	Other related work includes subjective/objective analysis (Hatzivassiloglon and Wiebe, 2000; Riloff and Wiebe, 2003) and opinion mining and summarization (Liu et al., 2005; Popescu and Etzioni.
---------------------------------------------------
D08-1058:20	103:180	A majority of the clues were collected as part of work reported in Riloff and Wiebe (2003).
---------------------------------------------------
H05-1116:21	161:241	Riloff and Wiebe (2003) use a bootstrapping algorithm to perform a sentence-based opinion classification on the MPQA corpus.
---------------------------------------------------
H05-1116:22	32:241	(2003), Riloff and Wiebe (2003), Bethard et al.
---------------------------------------------------
H05-1116:23	160:241	We investigate whether such information can be useful for MPQA by using the automatic sentence level opinion classifiers of Riloff and Wiebe (2003) and Wiebe and Riloff (2005).
---------------------------------------------------
H05-1116:24	34:241	(2004), Yu and Hatzivassiloglou (2003), Wiebe and Riloff (2005)).
---------------------------------------------------
H05-1116:25	158:241	For our gold standard of manual opinion classifications (dubbed MANUAL for the rest of the paper) we will follow Riloff and Wiebes (2003) convention (also used by Wiebe and Riloff (2005)) and consider a sentence to be opinion if it contains at least one opinion of intensity medium or higher, and to be fact otherwise.
---------------------------------------------------
D09-1140:26	127:237	Believing that the current approach may offer benefits over state-of-the-art pattern-based subjectivity detection, we also implement the AutoSlogTS method of Riloff and Wiebe (2003) for extracting subjective extraction patterns.
---------------------------------------------------
D09-1140:27	74:237	We consider significant patterns to be those where the conditional probability is greater than 0.65 and the pattern occurs more than five times in the entire document set (slightly higher than probability >= 0.60 and frequency >= 2 used by Riloff and Wiebe (2003)).
---------------------------------------------------
D09-1140:28	71:237	All trigrams are then scored according to their prevalence in relevant versus irrelevant documents (e.g. subjective vs. non-subjective sentences), following the scoring methodology of Riloff and Wiebe (2003).
---------------------------------------------------
N07-1039:29	9:46	Sentiment analysis includes a variety of different problems, including: sentiment classification techniques to classify reviews as positive or negative, based on bag of words (Pang et al. , 2002) or positive and negative words (Turney, 2002; Mullen and Collier, 2004); classifying sentences in a document as either subjective or objective (Riloff and Wiebe, 2003; Pang and Lee, 2004); identifying or classifying appraisal targets (Nigam and Hurst, 2004); identifying the source of an opinion in a text (Choi et al. , 2005), whether the author is expressing the opinion, or whether he is attributing the opinion to someone else; and developing interactive and visual opinion mining methods (Gamon et al. , 2005; Popescu and Etzioni, 2005).
---------------------------------------------------
H05-2018:30	19:41	2.2 Document Processing For general document processing, OpinionFinder first runs the Sundance partial parser (Riloff and Phillips, 2004) to provide semantic class tags, identify Named Entities, and match extraction patterns that correspond to subjective language (Riloff and Wiebe, 2003).
---------------------------------------------------
H05-2018:31	25:41	2.3.1 Subjective Sentence Classification The first component is a Naive Bayes classifier that distinguishes between subjective and objective sentences using a variety of lexical and contextual features (Wiebe and Riloff, 2005; Riloff and Wiebe, 2003).
---------------------------------------------------
W06-1650:32	32:189	Riloff and Wiebe (2003) extracted subjective expressions from sentences using a bootstrapping pattern learning process.
---------------------------------------------------
D09-1020:33	217:249	They may rely only on this information (e.g., (Turney, 2002; Whitelaw et al., 2005; Riloff and Wiebe, 2003)), or they may combine it with additional information as well (e.g., (Yu and Hatzivassiloglou, 2003; Kim and Hovy, 2004; Bloom et al., 2007; Wilson et al., 2005a)).
---------------------------------------------------
D09-1020:34	130:249	4.2.1 Rule-based Classifier We first apply SWSD to the rule-based classifier from (Riloff and Wiebe, 2003).
---------------------------------------------------
E09-1004:35	52:247	(2005) use a lexicon of over 8000 subjectivity clues, gathered from three sources ((Riloff and Wiebe, 2003); (Hatzivassiloglou and McKeown, 1997) and The General Inquirer2).
---------------------------------------------------
W06-0306:36	16:190	Sentence-level subjectivity/objectivity classification in some of the previous research (Riloff and Wiebe, 2003; Wiebe and Riloff, 2005) can identify subjective statements that include speculation in addition to positive/negative evaluations.
---------------------------------------------------
P07-1123:37	32:193	3 A Lexicon-Based Approach Many subjectivity and sentiment analysis tools rely on manually or semi-automatically constructed lexicons (Yu and Hatzivassiloglou, 2003; Riloff and Wiebe, 2003; Kim and Hovy, 2006).
---------------------------------------------------
P07-1123:38	81:193	3.2 Rule-based Subjectivity Classifier Using a Subjectivity Lexicon Starting with the Romanian lexicon, we developed a lexical classifier similar to the one introduced by (Riloff and Wiebe, 2003).
---------------------------------------------------
W06-1640:39	48:223	(2003), Riloff and Wiebe (2003), Bethard et al.
---------------------------------------------------
W06-1640:40	13:223	In particular, while recent research efforts have shown that fine-grained opinions (e.g. Riloff and Wiebe (2003), Bethard et al.
---------------------------------------------------
W06-2915:41	56:149	We evaluated the subjectivity of each sentence using the automatic subjective sentence classifier from (Riloff and Wiebe, 2003), and find that 65.6% of Palestinian sentences and 66.2% of Israeli sentences are classified as subjective.
---------------------------------------------------
W06-2915:42	35:149	So far, research in automatic opinion recognition has primarily addressed learning subjective language (Wiebe et al. , 2004; Riloff et al. , 2003), identifying opinionated documents (Yu and Hatzivassiloglou, 2003) and sentences (Yu and Hatzivassiloglou, 2003; Riloff et al. , 2003), and discriminating between positive and negative language (Pang et al. , 2002; Morinaga et al. , 2002; Yu and Hatzivassiloglou, 2003; Turney and Littman, 2003; Dave et al. , 2003; Nasukawa and Yi, 2003; Popescu and Etzioni, 2005; Wilson et al. , 2005).
---------------------------------------------------
I05-2011:43	31:161	(2003) extracted nouns and Riloff and Wiebe (2003) extracted patterns for subjective expressions using a bootstrapping process.
---------------------------------------------------
N09-1056:44	202:259	OpinionFinder uses two subjective sentence classifiers (Riloff and Wiebe, 2003; Wiebe and Riloff, 2005).
---------------------------------------------------
N09-1056:45	49:259	In particular, the OpinionFinder system (Riloff and Wiebe, 2003; Wiebe and Riloff, 2005) is a state-ofthe-art knowledge-rich sentiment-analysis system.
---------------------------------------------------
P09-2039:46	42:98	We have surveyed many studies about opinion mining (Lee et al., 2008; Kim and Hovy, 2006; Wilson and Wiebe, 2003; Riloff and Wiebe, 2003; Esuli and Sebastiani, 2006).
---------------------------------------------------
H05-1045:47	14:194	(2004), Yu and Hatzivassiloglou (2003), Wiebe and Riloff (2005)).
---------------------------------------------------
H05-1045:48	22:194	To illustrate the nature of this problem, consider the examples below: S1: Taiwan-born voters favoring independence 1In related work, we investigate methods to identify the opinion expressions (e.g. , Riloff and Wiebe (2003), Wiebe and Riloff (2005), Wilson et al.
---------------------------------------------------
P06-2022:49	164:187	(Mihalcea, 2003; Riloff and Wiebe, 2003).
---------------------------------------------------
P06-1133:50	48:268	We utilize the subjectivity patterns automatically extracted from foreign news documents (Riloff and Wiebe, 2003), and find that the percentages of the subjective sentences in the bitterlemons corpus (see Section 4) are similar (65.6% in the Palestinian documents and 66.2% in the Israeli documents).
---------------------------------------------------
P06-1133:51	44:268	There are studies on learning subjective language (Wiebe et al. , 2004), identifying opinionated documents (Yu and Hatzivassiloglou, 2003) and sentences (Riloff et al. , 2003; Riloff and Wiebe, 2003), and discriminating between positive and negative language (Turney and Littman, 2003; Pang et al. , 2002; Dave et al. , 2003; Nasukawa and Yi, 2003; Morinaga et al. , 2002).
---------------------------------------------------
N09-1002:52	58:226	3 Related Work Many methods have been developed for automatically identifying subjective (opinion, sentiment, attitude, affect-bearing, etc.) words, e.g., (Turney, 2002; Riloff and Wiebe, 2003; Kim and Hovy, 2004; Taboada et al., 2006; Takamura et al., 2006).
---------------------------------------------------
C08-2019:53	32:87	2.2 Comparison algorithms OpinionFinder is a state-of-the-art publicly available software package for sentiment analysis that can be applied to determining sentence-level subjectivity (Riloff and Wiebe, 2003; Wiebe and Riloff, 2005).
---------------------------------------------------
C08-1031:54	74:290	Sentiment classification at the sentence-level has also been studied (e.g., Riloff and Wiebe 2003; Kim and Hovy 2004; Wilson et al 2004; Gamon et al 242 2005; Stoyanov and Cardie 2006).
---------------------------------------------------
W06-1642:55	48:252	Inter-sentential contexts as in our approach were used as a clue also for subjectivity analysis (Riloff and Wiebe, 2003; Pang and Lee, 2004), which is two-fold classification into subjective and objective sentences.
---------------------------------------------------
H05-1044:56	71:197	To compile the lexicon, we began with a list of subjectivity clues from (Riloff and Wiebe, 2003).
---------------------------------------------------
P06-2059:57	278:288	Although this work aims at learning only nouns, in the subsequent work, they also proposed a bootstrapping method that can deal with phrases (Riloff and Wiebe, 2003).
---------------------------------------------------
P04-1035:58	69:149	Riloff and Wiebe (2003) state that It is [very hard] to obtain collections of individual sentences that can be easily identified as subjective or objective; the polarity-dataset sentences, for example, have not 4Available at www.cs.cornell.edu/people/pabo/moviereview-data/ (review corpus version 2.0).
---------------------------------------------------
N09-3013:59	13:119	Other research has been conducted in analysing sentiment at a sentence level using bootstrapping techniques (Riloff and Wiebe, 2003), finding strength of opinions (Wilson, Wiebe and Hwa, 2004), summing up orientations of opinion words in a sentence (Kim and Hovy, 2004), and identifying opinion holders (Stoyanov and Cardie, 2006).
---------------------------------------------------
I08-1038:60	118:128	On identifying opinion words, Morinaga et al (2002)has utilized information gain to extract classification features with a supervised method; Hatzivassiloglou and Wiebe (1997) used textual  junctions such as fair and legitimate or simplistic but well-received to separate similarityand oppositely-connoted words; Other methods are present in (Riloff et al, 2003; Riloff and Wiebe, 2003; Gamon and Aue, 2005; Wilson et al, 2006) The principal difference from previous work is that, they have considered extracting opinion words as a separate work but we have combined identifying features and opinion words in a unified process.
---------------------------------------------------
N06-1026:61	15:213	Riloff and Wiebe (2003) extracted subjective expressions from sentences using a bootstrapping pattern learning process.
---------------------------------------------------
D09-1019:62	291:344	Another important direction is classifying sentences as subjective or objective, and classifying subjective sentences or clauses as positive or negative (Wiebe et al, 1999; Wiebe and Wilson, 2002, Yu and Hatzivassiloglou, 2003; Wilson et al, 2004; Kim and Hovy, 2004; Riloff and Wiebe, 2005; Gamon et al 2005; McDonald et al, 2007).
---------------------------------------------------
D09-1019:63	13:344	There are many research directions, e.g., sentiment classification (classifying an opinion document as positive or negative) (e.g., Pang, Lee and Vaithyanathan, 2002; Turney, 2002), subjectivity classification (determining whether a sentence is subjective or objective, and its associated opinion) (Wiebe and Wilson, 2002; Yu and Hatzivassiloglou, 2003; Wilson et al, 2004; Kim and Hovy, 2004; Riloff and Wiebe, 2005), feature/topic-based sentiment analysis (assigning positive or negative sentiments to topics or product features) (Hu and Liu 2004; Popescu and Etzioni, 2005; Carenini et al., 2005; Ku et al., 2006; Kobayashi, Inui and Matsumoto, 2007; Titov and McDonald.
---------------------------------------------------
