This method calculates word similarity by using a bilingual dictionary, which is first introduced by Wu and Zhou (2003). 
Wu and Zhou (2003) extracted synonyms with multiple resources, including a monolingual dictionary, a bilingual corpus, and a monolingual corpus. 
This is in contrast with the results reported by Wu and Zhou (2003). 
(Wu and Zhou, 2003) just extract the synonymy collocation, such as <turn on, OBJ, light> and <switch on, OBJ, light> using both monolingual corpora and bilingual corpora to get an optimal result, but do not generalize them. 
Wu and Zhous (2003) paper is most closely related to our study. 
