Villavicencio (2003) used class-based knowledge to extend a VPC lexicon, but assumed that an unobserved VPC is not acceptable. 
such an approach to verb particle constructions by Villavicencio, 2003). 
For productive VPCs, one possibility is then to use the entries of verbs already listed in a lexical resource to productively generate VPC entries by combining them with particles according to their semantic classes, as discussed by Villavicencio (2003). 
Some research has concentrated on the automatic acquisition of semantic knowledge about certain classes of MWEs, such as compound nouns or verb particle constructions (VPCs) (e.g. , Lin, 1999; McCarthy et al. , 2003; Villavicencio, 2003). 
In the case that the object is pronominal, however, the VPC must occur in split word order (c.f. *He handed in it) (Huddleston and Pullum, 2002; Villavicencio, 2003). 
