Several researches have been reported on title generation (Jin and Hauptmann, 2000) (Berger and Mittal, 2000) and readability of texts (Minel et al. , 1997) (Hartley and Sydes, 1997) (Inui et al. , 2003).


Another interesting research is Inui et al.s lexical and syntactical paraphrasing system for deaf students (Inui et al. , 2003).


For example, a system that is capable of simplifying a given text, or showing the user several alternative expressions conveying the same content, would be useful for assisting a reader (Carroll et al. , 1999; Inui et al. , 2003).


There are no similar attempts, although a variety of applications have been discussed so far, for example question-answering (Lin and Pantel, 2001; Hermjakob et al. , 2002; Duclaye and Yvon, 2003) or text-simplification (Inui et al. , 2003).


