One solution to this problem could use a named entity extractor to recognize proper names; this was found to be very helpful in Wu (2003).


Wu (2003) also used the training data to tune the segmentation parameters of their MSR-NLP Chinese system.


Those differences are considered as segmentation inconsistencies by some researchers (Wu, 2003; Chen, 2003).


The task may sound simple, but has been the focus of considerable research efforts (e.g. Webster and Kit, 1992; Guo 1997; Wu, 2003).


