1 Overview Dialogue systems are built for many different purposes, including information gathering (e.g. , (Aust et al. , 1995)), performing simple transactions (e.g, (Walker and Hirschman, 2000)), collaborative interaction (e.g. , (Allen et al. , 1996)), tutoring (e.g. , (Rose et al. , 2003)), and training (e.g.


Sphinx2s best hypothesis is then sent to Why2-Atlas for syntactic and semantic analysis (Rose, 2000), discourse and domain processing (Jordan et al. , 2003), and nite-state dialogue management (Rose et al. , 2001).


Information in the speech signal such as prosody has been shown to be a rich source of information for predicting emotional states in other types of dialogue interactions (Ang et al. , 2002; Lee et al. , 2002; Batliner et al. , 2003; Devillers et al. , 2003; Shafran et al. , 2003).


