W06-1660:1	10:202	The relevant algorithms include Maximum Entropy (Borthwick, 1999; Klein et al. , 2003), Hidden Markov Model (HMM) (Bikel et al. , 1999; Klein et al. , 2003), AdaBoost (Carreras et al. , 2003), Memorybased learning (Meulder and Daelemans, 2003), Support Vector Machine (Isozaki and Kazawa, 2002), Robust Risk Minimization (RRM) Classification method (Florian et al. , 2003), etc. For Chinese NER, most of the existing approaches use hand-crafted rules with word (or character) frequency statistics.
---------------------------------------------------
W03-0419:2	84:153	Two teams used AdaBoost.MH (Carreras et al. , 2003b; Wu et al. , 2003) and two other groups employed memory-based learning (De Meulder and Daelemans, 2003; Hendrickx and Van den Bosch, 2003).
---------------------------------------------------
W03-0419:3	107:153	Four groups examined the usability of unannotated data, either for extracting training instances (Bender et al. , 2003; Hendrickx and Van den Bosch, 2003) or obtaining extra named entities for gazetteers (De Meulder and Daelemans, 2003; McCallum and Li, 2003).
---------------------------------------------------
