The human language technology (HLT) society in Europe has been particularly zealous for the standardization, making a series of attempts such as EAGLES 1, PAROLE/SIMPLE (Lenci et al. , 2000), ISLE/MILE (Calzolari et al. , 2003) and LIRICS 2.


We are in the process of mapping the list to DOLCE(Descriptive Ontology for Linguistic and Cognitive Engineering) (Masolo et al. , 2003).


Its applicability to diverse annotation types, including terminology, dictionaries and other lexical data (Ide, et al. , 2000), morphological annotation (Ide and Romary, 2002) and syntactic annotation (Ide and Romary, 2001b, 2003) demonstrates its generality.


The overall design of the architecture and the data model that it will instantiate have been described in Ide et al. , 2003.


For example, the syntactic feature defined in the ISLE/MILE format for lexical entries (Calzolari, et al. 2003) can be represented in RDF as follows 1 : 1 For brevity, this representation does not include the full information necessary for the RDF representation.


