The efficacy of this approach has been well-established in many areas, including automated evaluation of machine translation systems (Kauchak and Barzilay, 2006), text summarization (Kittredge, 2002), question answering (Rinaldi et al. , 2003), document retrieval (Zukerman and Raskutti, 2002), and many others.


8http://translate.google.com 35 5 Related Work Most of the work in QA and paraphrasing focused on folding paraphrasing knowledge into the question analyzer or the answer locator (Rinaldi et al. , 2003; Tomuro, 2003).


ExtrAns (Extracting answers from technical texts) by (Molla et al, 2003) and (Rinaldi et al, 2003) uses minimal logical forms (MLF) to represent both texts and questions.


There are many previous work on paraphrase examples extraction or combining them with some applications such as information retrieval and question answering (Agichtein et al. , 2001; Florence et al. , 2003; Rinaldi et al. , 2003; Tomuro, 2003; Lin and Pantel, 2001;), information extraction (Shinyama et al. , 2002; Shinyama and Sekine, 2003), machine translation (Hiroshi et al. , 2003; Zhang and Yamamoto, 2003), multi-document (Barzilay et al. , 2003).


Lexical synonymy (She esteemed him highly vs. She respected him greatly), syntactic variation (John paid the bill vs. The bill was paid by John), overlapping meanings (Anna turned at Elm vs. Anna rounded the corner at Elm), and other phenomena interact to produce a broad range of choices for most language generation tasks (Hirst, 2003; Rinaldi et al. , 2003; Kozlowski et al. , 2003).


