Similar methods for this problem have been employed by Barzilay and Lapata (2005) and Duboue and McKeown (2003). 
Duboue and McKeown (2003) were the first to propose a method for learning content selection rules automatically, thus going beyond mere corpus analysis. 
This result compares favorably with Duboue and McKeown (2003) whose best model has an F-score of 51.00% on a simpler domain. 
Similarly to Duboue and McKeown (2003), we view content selection as a classification task and learn selection rules from a database and its corresponding corpus. 
This property distinguishes our corpus from more stylistically homogeneous collections of biographies used in text generation research (Duboue and McKeown, 2003). 
