We have recently developed the capability to utilize a pronounced version of a word to greatly enhance the accuracy of a letter recognition task, and have successfully integrated this technology into a personal name enrollment task (Seneff et al. , 2003; Chung et al. , 2003).


1 Introduction Spoken dialogue systems are emerging as an intuitive interface for providing conversational access to online information sources (Eckert et al. , 1997; Gorin et al. , 1997; Dahlback et al. , 1999; Zue et al. , 2000; Walker et al. , 2001; Glass and Seneff, 2003; Pieraccini et al. , 1997; Quast et al. , 2003; J. Gustafson, 1999; Polifroni and Chung, 2002; Denecke, 2002; Seneff, 2002; Zue and Glass, 2000).


