This might be achieved by introducing orientation sequences over phrase types that have been used in ((Schafer and Yarowsky, 2003)).


See (Och and Ney, 2000), (Yamada and Knight, 2001), (Koehn and Knight, 2002), (Koehn et al. , 2003), (Schafer and Yarowsky, 2003) and (Gildea, 2003).


The approach which is closest to ours is that by Schafer and Yarowsky (2003) who suggested a combination of models based on shallow syntactic analysis (part-of-speech tagging and phrase chunking).


We hope that such features can combine the strengths of tagand chunk-based translation systems (Schafer and Yarowsky, 2003) with our baseline system.


