Cascaded Entity Name Resolution It is found (Shen et al 2003) that 16.57% of entity names in GENIA V3.0 have cascaded constructions, e.g. <RNA><DNA>CIITA</DNA> mRNA</RNA>. 
(2003), Shen et al. 
2.2 Cascaded Entity Name Resolution It is found (Shen et al 2003) that 16.57% of entity names in GENIA V3.0 have cascaded constructions, e.g. <RNA><DNA>CIITA</DNA> mRNA</RNA>. 
The typical explorations include Kazama et al 2002, Lee et al 2003, Tsuruoka et al 2003, Shen et al 2003. 
In the biomedical domain, we care about entities like gene, protein, virus, etc. In recent years, many explorations have been done to port existing named entity recognition systems into the biomedical domain (Kazama et al 2002; Lee et al 2003; Shen et al 2003; Zhou et al 2004). 
