 Background information: includes date, location, and forecaster We do not currently use the NWP data (other than for reconstructing SUMTIME-MOUSAM texts), although we hope in the future to include it in our analyses, in a manner roughly analogous to Reiter and Sripada [2003].


SUMTIME-MOUSAM uses rules for this that are derived from corpus analysis and other knowledge acquisition activities [Reiter et al, 2003; Sripada et al, 2003].


