Three systems used Maximum Entropy Models in isolation (Bender et al. , 2003; Chieu and Ng, 2003; Curran and Clark, 2003). 
By taking inspiration from the literature (Bender et al. , 2003; Borthwick, 1999; Koeling, 2000), a set of standard binary features is introduced. 
2 Related Work To date, the most successful language independent approaches to English NER are systems that employ Maximum Entropy (ME) techniques in a supervised setting (Bender et al., 2003). 
The most prominent NER systems approach the problem as a classification task: identifying the named entities (NE) in the text and then classifying them according to a set of designed features into one of a predefined set of classes (Bender et al., 2003). 
Most existing work has focused on supervised learning approaches, employing models such as HMMs (Zhou and Su, 2002), MEMMs (Bender et al. , 2003; Finkel et al. , 2005), and CRFs (McCallum and Li, 2003). 
