I08-1033:1	10:155	In these languages, word segmentation (Chen and Liu, 1992; Chen and Bai, 1998; Chen and Ma, 2002; Ma and Chen, 2003; Gao et al., 2005) is often carried out firstly to identify words before word alignment (Wu and Xia, 1994).
---------------------------------------------------
W03-1726:2	12:95	After that, we were paying more attention on the problems of extracting and identifying unknown words (Chen et.al 1997, Chen & Bai 1998, Chen & Ma 2002, Tseng & Chen 2002, Ma & Chen 2003).
---------------------------------------------------
W03-1726:3	15:95	A bottom-up merging algorithm was proposed in (Ma & Chen 2003), which utilizes hybrid statistical and linguistic information to extract unknown words effectively.
---------------------------------------------------
W03-1726:4	56:95	We adopt a bottom-up merging algorithm (Ma & Chen 2003), which utilizes hybrid statistical and linguistic information, to extract unknown words.
---------------------------------------------------
