Other systems define relationships between web page extracts or texts containing possible answers: for example, (Radev and McKeown, 1998) and (Harabagiu and Lacatusu, 2004) define agreement (when two sources report the same information), addition (when a second source reports additional information), contradiction (when two sources report conflicting information), etc. These relations can be classified into the 4 relations defined by (Webber et al. , 2002), i.e. inclusion, equivalence, aggregation and alternative which we present below.


(2004) or Harabagiu and Lacatusu (2004) that use FAQ data to learn how to expand query terms by answer terms.


Recently, advanced QA systems defined relationships (equivalence, contradiction, ) between Web page extracts or texts containing possible answers in order to combine them and to produce a single answer (Radev and McKeown, 1998), (Harabagiu and Lacatusu, 2004), (Webber et al. , 2002).


