1 Introduction The Multilingual Chinese-English lexical sample task is designed following the leading ideas of the Senseval-3 Multilingual English-Hindi lexical sample task (Chklovski et al. , 2004).


Many of the Senseval-type 124 WSD system are not language specific and the presentation of the results in the English lexical sample task (Midhalcea et al. , 2004), English-Hindi multilingual task (Chklovski et al. , 2004), or any of the lexical sample tasks defined in other languages, give a good overview of the variety of approaches to WSD.


Note that Senseval-3 also defined a translation or multilingual lexical sample task (Chklovski et al. , 2004), which is just like the English lexical sample task, except that the WSD systems are expected to predict Hindi translations instead of WordNet senses.


This is thus similar to the multilingual lexical sample task in SENSEVAL-3 (Chklovski et al. , 2004), except that our training and test examples are collected without manually annotating each individual ambiguous word occurrence.


