This approach, however, precludes using the corpus to compare possible definitions of utterance, one of the goals of the GNOME annotation (Poesio et al. , 2004b). 
5.1 Annotating Discourse Models Anaphoric annotation raises a number of difficult and, sometimes, unresolved semantic issues (Poesio, 2004b). 
1 Introduction The GNOME corpus was created to study the aspects of discourse that appear to affect generation, especially salience (Pearson et al. , 2000; Poesio and Di Eugenio, 2001; Poesio and Nissim, 2001; Poesio et al. , 2004b). 
Researchers at Essex were responsible for the coreference markup scheme developed in MATE (Poesio et al, 1999; Poesio, 2004a) and have annotated corpora using this scheme including a subset of the Penn Treebank (Poesio and Vieira, 1998), and the GNOME corpus (Poesio, 2004a). 
This type of annotation raises, however, a number of difficult (and sometimes unresolved) semantic issues (Poesio 2004). 
