Finally, in (Benamara et al. 2004), we define a conceptual metrics that determines the distance between two concepts, evaluated in terms of distance in the hierarchy between the two concepts and property differences (nature of properties and values associated).


The implementation relies on the conceptual metrics, also used for concept relaxation (Benamara et al 2004a) and also on manually marked really complex concepts in the ontology.


2 The WEBCOOP project and its environment This research is part of the WEBCOOP system (Benamara et al. 2004), that makes a heavy use of a rich domain ontology, which is a concept ontology structured by means of several semantic relations (Cruse 1986).


Cooperative know-how involves several forms of responses that include relaxations, intensional calculus, expression of restrictions, of warnings and conditional responses (Benamara et al. 2004).


We manually integrated these ontologies in WEBCOOP (Benamara et al. 2004a) and added ourselves most properties by hand.


