The WSD system based on this formula participated at the Senseval-3 competition as the CIAOSENSO system (Buscaldi et al. , 2004), obtaining 75.3% in precision over nouns in the allwords task (baseline: 70.1%).


1 Introduction One of the lessons learned from our previous experience at Senseval-31 (Buscaldi et al. , 2004; Vazquez et al. , 2004) is that the integration of different systems usually works better than a standalone system.


