In contrast, most previous work on multidocument summarization has focused on factual text (e.g. , news (McKeown et al. , 2002), biographies (Zhou et al. , 2004)). 
A biography, for example, might contain the date of birth, occupation, or nationality of the person in question (Duboue and McKeown, 2003; Zhou et al. , 2004; Weischedel et al. , 2004; Filatova and Prager, 2005). 
Instead, we follow a simplified form of previous work on biography creation, where a classifier is trained to distinguish biographical text (Zhou et al., 2004; Biadsy et al., 2008). 
One might collect training data by manually annotating a suitable corpus containing biographical and nonbiographical data about a person, as in (Zhou et al., 2004). 
These domains have been commonly used in prior work on summarization (Weischedel et al., 2004; Zhou et al., 2004; Filatova and Prager, 2005; DemnerFushman and Lin, 2007; Biadsy et al., 2008). 
