(%) 1 htsa3 (Grozea, 2004) 72.9 2 IRST-kernels (Strapparava et al. , 2004) 72.6 3 nusels (Lee et al. , 2004) 72.4 4 SENSEVAL-3 contest baseline 55.2 5 Niu et al.


2 Background Several graph-based learning techniques have recently been developed and applied to NLP problems: minimum cuts (Pang and Lee, 2004), random walks (Mihalcea, 2005; Otterbacher et al. , 2005), graph matching (Haghighi et al. , 2005), and label propagation (Niu et al. , 2005).


It is developed by Vapnik and has been applied into WSD (Lee et al. , 2004).


