Chelba and Acero (2004) use the parameters of the source domain maximum entropy classifier as the means of a Gaussian prior when training a new model on the target data. 
This is a recapitalization task introduced by Chelba and Acero (2004) and also used by Daume III and Marcu (2006). 
His method improves or equals over previously explored more sophisticated methods (Daume III and Marcu, 2006; Chelba and Acero, 2004). 
Chelba and Acero (2004) use the parameters of the maximum entropy model learned from the source domain as the means of a Gaussian prior when training a new model on the target data. 
In particular, Chelba and Acero (2004) showed how this technique can be effective for capitalization adaptation. 
