We evaluated against the TiGer Dependency Bank (Forst et al., 2004) (TiGerDB), a dependency-based gold standard for German parsers that encodes grammatical relations similar to, though more fine-grained than, the ones in the TIGER Treebank as well as morphosyntactic features.


In order to bridge this gap, we construct an RMRS treebank from a subset of the TIGERDependencyBank (Forst et al. , 2004), which can serve as a gold standard for HPSG parsing for evaluation, and for training of stochastic HPSG grammar models.


2.2 Treebank Conversion Similar to the TIGER to TIGER-DB conversion (Forst, 2003; Forst et al. , 2004), we are using the term rewriting system of Crouch (2005) for treebank conversion.


A more theory-neutral dependency representation is currently derived from this TIGER-LFG treebank for cross-framework parser evaluation (Forst et al. , 2004).


A dependency-based evaluation of the analyses produced by the grammar on the TiGer Dependency Bank (Forst et al. , 2004) results in an F-score between 80.42% on all gram17 matical relations and morphosyntactic features (or 72.59% on grammatical relations only) and 85.50% (or 79.36%).


