Fleischman and Hovy (2004) propose a Maximum Entropy model trained to give the probability that 64 two names refer to the same individual 1.


Research on multi-document person name resolution (Bagga and Baldwin, 1998; Mann and Yarowsky, 2003; Fleischman and Hovy, 2004) focuses on the related problem of determining if 2http://flink.sematicweb.org/.


Fleischman and Hovy (2004) constructs a maximum entropy classifier to learn distances between documents that are then clustered.


Fleischman and Hovy (2004) introduce the ?maximum entropy model??


