H05-1025:1	6:189	Previous studies have shed light on the predictability of the next unix command that a user will enter (Motoda and Yoshida, 1997; Davison and Hirsch, 1998), the next keystrokes on a small input device such as a PDA (Darragh and Witten, 1992), and of the translation that a human translator will choose for a given foreign sentence (Nepveu et al. , 2004).
---------------------------------------------------
H05-1025:2	34:189	Computer aided translation systems combine a translation and a language model in order to provide a (human) translator with a list of suggestions (Langlais et al. , 2000; Langlais et al. , 2004; Nepveu et al. , 2004).
---------------------------------------------------
