The corpus is parsed using Bikels parser (Bikel, 2004) and the Verb-Object Collocations are extracted. 
Furthermore, Bikel (2004) provides evidence that lexical information (in the form of bi-lexical dependencies) only makes a small contribution to the performance of parsing models such as Collinss (1997). 
376 tained using the same BNC dataset used by Venkatapathy and Joshi which was obtained using Bikels parser (Bikel, 2004). 
2It has recently been questioned whether these bilexical features actually contribute much to parsing performance (Klein and Manning, 2003; Bikel, 2004), at least when one has only a million words of training. 
A lexicalized statistical parser (Bikel, 2004) is applied to the parsing task. 
