The systems working with Maximum Entropy Models (Baldewein et al. , 2004; Lim et al. , 2004) use beam search to find taggings that maximize the probability of the output sequence. 
3.3 Discriminative model Discriminative models have been found to outperform generative models for many different tasks including SRL (Lim et al., 2004). 
Two teams used the Maximum Entropy (ME) statistical framework (Baldewein et al. , 2004; Lim et al. , 2004). 
(2) General machine learning algorithms (Pradhan et al. , 2003) (Lim et al. , 2004) and (3) Generative model (Thompson et al. , 2003). 
However, some of the systems restrict the search for arguments only to the immediate clause (Park et al. , 2004; Williams et al. , 2004) and others use the clause hierarchy to guide the exploration of the sentence (Lim et al. , 2004; Carreras et al. , 2004). 
