In fact (Williams et al. , 2004) and (Baldewein et al. , 2004) even improved the results on the test set.


Two teams used the Maximum Entropy (ME) statistical framework (Baldewein et al. , 2004; Lim et al. , 2004).


The systems working with Maximum Entropy Models (Baldewein et al. , 2004; Lim et al. , 2004) use beam search to find taggings that maximize the probability of the output sequence.


We recently studied semantic role labelling in the context of the CoNLL shared task (Baldewein et al. , 2004).


