In addition, Ng and Low (2004) find that, compared with POS tagging after word segmentation, Joint S&T can achieve higher accuracy on both segmentation and POS tagging. 
In this bakeoff, our models built for the tasks are similar to that in the work of Ng and Low (2004). 
The character features are instantiations of the following templates, similar to those described in (Ng and Jin, 2004), C refers to a Chinese hanzi. 
Ng and Low (2004) studied Chinese word segmentation and POS tagging. 
Ng and Low (2004) (N&L04) used CTB 3.0. 
