However, previous work (Marcu, 2000; Polanyi et al. , 2004; Soricut and Marcu, 2005; Sporleder and Lascarides, 2005) in discourse parsing has relied on syntactic and lexical information, and shallow semantics only. 
After sentential parsing is complete, the XLE sentence parse trees are segmented into BDUs using a set of robust sentence and discourse level rules described in detail in Polanyi et al 2004a, b. After parsing, BDUs (which need not be contiguous) are recombined into one or more discourse trees corresponding to (parts of) the sentence, called BDUtrees. 
Of course, since semantic information is hard to come by, it is not surprising that previous work on discourse parsing did not use it, or only used shallow word level ontological semantics as specified in WordNet (Polanyi et al. , 2004). 
This issue is discussed in detail in Polanyi et al. , 2004a,b ; Thione et al. 2004. 
(Polanyi et al. , 2004) do not provide any evaluation results at all. 
