We build upon the Extensible Dependency Grammar (XDG) (Debusmann et al. , 2004b; Debusmann et al. , 2004a; Debusmann et al. , 2005) model and its CP implementation in Oz (Van Roy and Haridi, 2004), namely the XDG Development Toolkit1 (XDK) (Debusmann et al. , 2004c).


In a dependency framework, XDG followed this path (Debusmann et al. , 2004), however it remains unknown to us whether this approach remains computationally tractable for parsing with real scale grammars.


With the eXtended Dependency Grammar (XDG) (Debusmann et al. , 2004) the notion of dependency tree is further extended to multi-dimensional dependency graph, where each dimension (e.g. Immediate Dominance and Linear Precedence) is associated with its own set of well-formedness conditions (called principles).


