I08-4025:1	21:87	In our approach, N-best candidates for each training example are produced with the CRF++ software (Kudo et al., 2004).
---------------------------------------------------
I08-4025:2	16:87	The N-best list is produced using a character-based conditional random field (CRF) (Lafferty et al., 2001; Kudo et al., 2004) tagger.
---------------------------------------------------
D07-1022:3	51:273	Lately a few supervised disambiguation methods have come about, including hidden Markov models (Hakkani-Tur et al. , 2000; Hajic et al. , 2001), conditional random fields (Kudo et al. , 2004; Smith et al. , 2005b), and local support vector machines (Habash and Rambow, 2005).
---------------------------------------------------
D07-1022:4	178:273	4.2.3 Conditional Random Field The second morphology model, pcrfL, which is based on the same morphological lexicon L, uses a second-order conditional random field (Lafferty et al. , 2001) to disambiguate the full sentence by modeling local contexts (Kudo et al. , 2004; Smith et al. , 2005b).
---------------------------------------------------
D08-1045:5	12:238	This area of research may be considered almost completed, as previous studies reported the F-score of nearly 99% (Kudo et al., 2004).
---------------------------------------------------
D08-1045:6	10:238	Japanese morphological analysis has successfully adopted dictionary-based approaches (Kurohashi et al., 1994; Asahara and Matsumoto, 2000; Kudo et al., 2004).
---------------------------------------------------
P09-1058:7	203:223	Conditional random fields (CRFs) (Lafferty et al., 2001) further improve the performance (Kudo et al., 2004; Shi and Wang, 2007) by performing whole-sequence normalization to avoid label-bias and length-bias problems.
---------------------------------------------------
C08-1113:8	39:177	Previous work (Kudo et al., 2004) showed CRFs outperform generative Markov models and discriminative history-based methods in JWS.
---------------------------------------------------
W08-0609:9	64:160	(Kudo et al., 2004), we adapted the core engine of the CRF-based morphological analyzer, MeCab1, to our POS/PROTEIN tagging task.
---------------------------------------------------
C08-2034:10	106:141	Figure 2: Attaching neighbor relations with sequental taggers  Figure 3: Attaching root words with sequential taggers  The sequential tagger used in this paper is CRF++ (Kudo et al., 2004).
---------------------------------------------------
D07-1131:11	52:154	As conventional sequential tagging problems, such part-of-speech tagging and phrase chunking, we employ the conditional random fields (CRF) as learners (Kudo et al. , 2004).
---------------------------------------------------
