Indeed (Helmreich et al. , 2004) explores the question of integration across languages, as well as levels of annotation.


The sixth, seventh and eighth papers (Baumann et al. , 2004; C mejrek et al. , 2004; Helmreich et al. , 2004) explore questions of multilingual annotation of syntax and semantics, beginning to answer the question of how annotation systems can be made compatible across languages.


