We build upon the Extensible Dependency Grammar (XDG) (Debusmann et al. , 2004b; Debusmann et al. , 2004a; Debusmann et al. , 2005) model and its CP implementation in Oz (Van Roy and Haridi, 2004), namely the XDG Development Toolkit1 (XDK) (Debusmann et al. , 2004c).


The trick also comes in handy when tackling, for instance, multiword expressions (Debusmann, 2004), which involve worthy syntactic nodes that conceptually have no semantic counterparts.


There are approaches that aim at encoding such units with the rules of an existing formal grammar, such as the approach described by Debusmann (2004).


