Conversely, output annotated with more informative labels, such as function or semantic labels, underlies all domain-independent question answering (Jijkoun et al. , 2004) or shallow semantic interpretation systems (Collins and Miller, 1998; Ge and Mooney, 2005).


In particular, recent models of semantic role labelling separate input indicators of the correlation between the structural position in the tree and the semantic label, such as path, from those indicators that encode constraints on the sequence, such as the previously assigned role (Kwon et al. , 2004).


Our results also confirm the importance of lexical information, the lesson drawn from (Thompson et al. , 2004), who find that correctly modelling sequence information is not sufficient.


