W05-1509:1	22:202	Conversely, researchers interested in producing richer semantic outputs have concentrated on two-stage systems, where the semantic labelling task is performed on the output of a parser, in a pipeline architecture divided in several stages (Gildea and Jurafsky, 2002; Nielsen and Pradhan, 2004; Xue and Palmer, 2004).
---------------------------------------------------
P07-1026:2	34:194	Most of the following work focused on feature engineering (Xue and Palmer, 2004; Jiang et al. , 2005) and machine learning models (Nielsen and Pradhan, 2004; Pradhan et al. , 2005a).
---------------------------------------------------
P07-1026:3	35:194	Some other work paid much attention to the robust SRL (Pradhan et al. , 2005b) and post inference (Punyakanok et al. , 2004).
---------------------------------------------------
P06-2010:4	36:184	Some other works paid much attention to the robust SRL (Pradhan et al. , 2005b) and post inference (Punyakanok et al. , 2004).
---------------------------------------------------
P06-2010:5	35:184	Most of the following works focused on feature engineering (Xue and Palmer, 2004; Jiang et al. , 2005) and machine learning models (Nielsen and Pradhan, 2004; Pradhan et al. , 2005a).
---------------------------------------------------
P06-2010:6	18:184	Many researchers (Gildea and Jurafsky, 2002; Pradhan et al. , 2005a) use feature-based methods Figure 1: Semantic role labeling in a phrase structure syntactic tree representation for argument identification and classification in building SRL systems and participating in evaluations, such as Senseval-3 1, CoNLL-2004 and 2005 shared tasks: SRL (Carreras and M`arquez, 2004; Carreras and M`arquez, 2005), where a flat feature vector is usually used to represent a predicate-argument structure.
---------------------------------------------------
J06-3002:7	40:757	This task is fundamentally syntactic in nature and complements the task of assigning thematic role labels (Gildea and Jurafsky 2002; Nielsen and Pradhan 2004; Xue and Palmer 2004; Swier and Stevenson 2005).
---------------------------------------------------
