Semantic parsing enables logic reasoning and is critical in many practical tasks, such as speech understanding (Zue and Glass, 2000), question answering (Lev et al. , 2004) and advice taking (Kuhlmann et al. , 2004).


In (Lev et al. , 2004), a syntax-driven approach is used to map logic puzzles described in NL to an MRL.


Despite some recent advances in this direction (Bos et al. , 2004), it is still the case that it is hard to obtain deep semantic analyses which are accurate enough to support logical inference (Lev et al. , 2004).


