I08-2105:1	133:147	For Senseval 3 data, using a graph method with the Key Player Problem to measure vertex relevance, Navigli and Lapata (2007) report very close results to (Strapparava et al., 2004) on nouns and adjectives, and lower scores for verbs (F1-scores: 61.9% for nouns, 62.8% for adjectives, 36.1% for verbs compared with 62.2% for nouns, 66.9% for adjectives, 50.4% for verbs).
---------------------------------------------------
P06-1070:2	67:164	In the literature, Domain Models have been introduced to represent ambiguity and variability (Gliozzo et al. , 2004) and successfully exploited in many NLP applications, such as Word Sense Disambiguation (Strapparava et al. , 2004), Text Categorization and Term Categorization.
---------------------------------------------------
D07-1108:3	146:175	1020 Bayes (Soft Tag) 73.6 SVM-topic 73.0 SVM baseline 72.4 NB baseline 69.8 ASO(Ando, 2006) 74.1 SVM-LSA (Strapparava et al. , 2004) 73.3 Senseval-3 Best System(Grozea, 2004) 72.9 Table 5: Results compared to previous best systems on Senseval-3 English lexical sample task.
---------------------------------------------------
W06-2911:4	198:209	[G04] Grozea (2004); [SGG04] Strapparava et al.
---------------------------------------------------
W05-0802:5	59:160	In the literature, Domain Models have been introduced to represent ambiguity and variability (Gliozzo et al. , 2004) and successfully exploited in many NLP applications, such us Word Sense Disambiguation (Strapparava et al. , 2004), Text Categorization and Term Categorization.
---------------------------------------------------
N07-1026:6	175:191	(%) 1 htsa3 (Grozea, 2004) 72.9 2 IRST-kernels (Strapparava et al. , 2004) 72.6 3 nusels (Lee et al. , 2004) 72.4 4 SENSEVAL-3 contest baseline 55.2 5 Niu et al.
---------------------------------------------------
P05-1050:7	36:170	We identi ed kernel methods as a viable framework in which to implement the assumptions above (Strapparava et al. , 2004).
---------------------------------------------------
W06-2608:8	11:157	, 2005a) and WordSenseDisambiguation (WSD) (Strapparava et al. , 2004).
---------------------------------------------------
W06-2608:9	121:157	Indeed, we followed this approach in the participation to Senseval-3 competition, reaching the state-of-theart in many lexical-sample tasks (Strapparava et al. , 2004).
---------------------------------------------------
P06-1014:10	149:205	F1 F1flne Gambl 0.779 0.779 0.779 0.652 SenseLearner 0.769 0.769 0.769 0.646 KOC Univ. 0.768 0.768 0.768 0.641 SSI 0.758 0.758 0.758 0.612 IRST-DDD 0.721 0.719 0.720 0.583 FS baseline 0.769 0.769 0.769 0.624 Random BL 0.497 0.497 0.497 0.340 University (Yuret, 2004)  and the best unsupervised system, namely IRST-DDD (Strapparava et al. , 2004).
---------------------------------------------------
W05-0608:11	34:158	1The idea of exploiting a Domain Kernel to help a supervised classi cation framework, has been pro tably used also in other NLP tasks such as word sense disambiguation (see for example (Strapparava et al. , 2004)).
---------------------------------------------------
