To demonstrate the effect that a ner-grained tokenisation can have on POS and NER tagging, we performed a series of experiments on the NER annotated data provided for the Coling BioNLP evaluation (Kim et al. , 2004), which was derived from the GENIA corpus (Kim et al. , 2003).


2 An XML-based Standoff Annotation Tool In a number of recent projects we have explored the use of machine learning techniques for Named Entity Recognition (NER) and have worked with data from a number of different domains, including data from biomedicine (Finkel et al. , in press; Dingare et al. , 2004), law reports (Grover et al. , 2004), social science (Nissim et al. , 2004), and astronomy and astrophysics (Becker et al. , 2005; Hachey et al. , 2005).


In all experiments we discarded the original POS tags and performed POS tagging using the C&C tagger trained on the MedPost data (Smith et al. , 2004).


