The most frequently applied 72 models were SVMs with totally ve systems adopting SVMs as the classi cation models either in isolation (Park et al. , 2004; Lee et al. , 2004) or in combination with other models (Zhou and Su, 2004; Song et al. , 2004; R ossler, 2004).


Similarly, CRFs were employed by one system in isolation (Settles, 2004) and by another system in combination with SVMs (Song et al. , 2004).


Part-of-speech information was incorporated in ve systems: four of them utilized domainspecialized part-of-speech taggers (Zhou and Su, 2004; Finkel et al. , 2004; Song et al. , 2004; Park et al. , 2004) and the other utilized generalpurpose taggers (Lee et al. , 2004).


68 Table 3: Conventional results for protein name recognition Authors R P F Tsai et al.(Tsai et al., 2006) 71.31 79.36 75.12 Our system 79.85 68.58 73.78 Zhou and Su(Zhou and Su, 2004) 69.01 79.24 73.77 Kim and Yoon(Kim and Yoon, 2007) 75.82 71.02 73.34 Okanohara et al.(Okanohara et al., 2006) 77.74 68.92 73.07 Tsuruoka(Tsuruoka, 2006) 81.41 65.82 72.79 Finkel et al.(Finkel et al., 2004) 77.40 68.48 72.67 Settles(Settles, 2004) 76.1 68.2 72.0 Song et al.(Song et al., 2004) 65.50 73.04 69.07 Rossler(Rossler, 2004) 72.9 62.0 67.0 Park et al.(Park et al., 2004) 69.71 59.37 64.12


Various machine learning approaches such as ME (Kazama et al. , 2002), SVM (Kazama et al. , 2002; Song et al. , 2004), HMM (Zhao, 2004) are applied to NER.


