Animacy Each noun and pronoun is labeled for the animacy of its referent (Zaenen et al. , 2004).


Each word was manually labeled for presence or absence of pitch accent1, as well as additional features including information status (or givenness), contrast and animacy distinctions, (Nissim et al. , 2004; Calhoun et al. , 2005; Zaenen et al. , 2004), features that linguistic literature suggests are predictive of prominence (Bolinger, 1961; Chafe, 1976).


(Zaenen et al. , 2004) describe an encoding scheme for the manual encoding of animacy information in part of the English Switchboard corpus.


The small amount of variation in the human annotation for animacy clearly supports a type-level approach to animacy, however, underline the influence of the linguistic context on the conception of animacy, as noted in the literature (Zaenen et al., 2004; Rosenbach, 2008).


There are clear similarities between the annotation for human reference found in Talbanken05 and the annotation scheme for animacy discussed 631 ANIM CONC NCONC TIME PLACE ORG HUM InanimateOtheranimate Figure 1: Animacy classification scheme (Zaenen et al., 2004).


