Issues include managing clarification dialogues in order to disambiguate users intentions and interests; and question decomposition to obtain simpler and more tractable questions (Small et al.2003)(Hickl et 9 al.2004).


Following work in (Hickl et al. , 2004), we believe complex questions can be answered in one of two ways: either by (1) using techniques (similar to the ones proposed in (Harabagiu et al. , 2006)) for automatically decomposing complex questions into sets of informationally-simpler questions, or by (2) using a multi-document summarization (MDS) system (such as the one described in (Lacatusu et al. , 2006)) in order to assemble a ranked list of passages which contain information that is potentially relevant to the users question.


Passages are then submitted to an Information Extraction module, which annotates texts with a wide 1 TechniquesusedbyhumanannotatorsforcreatingQUABs were first described in (Hickl et al. , 2004); full details of FERRETsautomaticQUABgenerationcomponentsareprovidedin (Harabagiuetal.


In past experiments with users of interactive Q/A systems (Hickl et al. , 2004), we have found that a users access to sources of domain-specific knowledge significantly affects the types of questions that auserislikelytosubmittoaQ/Asystem.


Inpreviouswork(Hickletal.,2004;Harabagiuet al. ,2005a),wehavearguedthatinteractivequestionanswering systems should be based on a predictive dialogue architecture which can be used to provide userswithbothpreciseanswerstotheirquestionsas well as suggestions of relevant research topics that couldbeexploredthroughoutthecourseofaninteractiveQ/Adialogue.


