We are not aware of any machine-learning approach to Arabic morphology, but find related issues treated in (Daya et al. , 2004), who propose a machine-learning method augmented with linguistic constraints to identifying roots in Hebrew words  a related but reverse task to ours.


, Daya et al. , 2004, who modeled interdigitation in Hebrew).


Some present-day research in machine learning of morpho-phonology indeed focuses on satisfying linguistically-motivated constraints as a postprocessing or filtering step; e.g., see (Daya et al. , 2004) on identifying roots in Hebrew word forms.


