A description of the LIDAS system and the U-LDM as well as a summary of an article from the New Yorker are described in earlier work (Polanyi et al, 2004a, b, Thione 2004).


This issue is discussed in detail in Polanyi et al. , 2004a,b ; Thione et al. 2004.


(Polanyi et al 2004; Thione et al 2004) Much work remains to be done.


4 Palo Alto, CA 94304 {polanyi|culy|vdberg|thione}@fxpal.com, ahn@science.uva.nl Abstract 1 In this paper, we describe how the LIDAS System (Linguistic Discourse Analysis System), a discourse parser built as an implementation of the Unified Linguistic Discourse Model (U-LDM) uses information from sentential syntax and semantics along with lexical semantic information to build the Open Right Discourse Parse Tree (DPT) that serves as a representation of the structure of the discourse (Polanyi et al. , 2004; Thione 2004a,b).


