Work indicating acceptability of MWEs is largely limited to collocational analysis using PMI-based measures (Lin, 1999; Stevenson et al. , 2004).


Previous research on LVCs, on the other hand, has primarily focused on their automatic extraction (e.g. , Grefenstette and Teufel 1995; Dras and Johnson 1996; Moiron 2004; though see Stevenson et al. 2004).


As such, previous computational research had proposed that the lightness of a LVC might be best modeled as a continuum as opposed to a binary class (Stevenson et al. , 2004).


This is in accordance with the observation that different light verbs have different properties (Stevenson et al. , 2004).


