More information about the addressee of a dialogue can be induced by combining the dialogue act information with some lexical markers that are used as addressee indicators (e.g. you, we, everybody, all of you) (Jovanovic and op den Akker, 2004).


In meeting conversations, the contribution of the gaze direction to addressee prediction is also affected by the current meeting activity and seating arrangement (Jovanovic and op den Akker, 2004).


As utterance features, we used a subset of lexical features presented in (Jovanovic and op den Akker, 2004) as useful cues for determining whether the utterance issingle or group addressed.


