One of the solutions is character-based tagging (Xue and Converse, 2002) (Goh et al. , 2004a).


Model b is our previous method proposed in (Goh et al. , 2004b): First, a MaxEnt classifier is used to perform character-based tagging to identify OOV words in the test data.


We did not use the word and character classes as features in Model b unlike in the case of Models a and c. The details of the model can be found in (Goh et al. , 2004b).


Defining some hand written rules to prune false OOV words will help to improve the IV word segmentation (Goh et al. , 2004b), because the precision of OOV word extraction becomes higher.


