Research in summarisation has also addressed the problem of generating non-verbatim sentences; see [Jing and McKeown, 1999], [Barzilay et al. , 1999] and more recently [Daume III and Marcu, 2004].


This is also supported by the work of Knight and Marcu [2002] (cited by [Daume III and Marcu, 2004]), which nds that only 2.7% of human summary sentences are extracts.


Summarization researchers have also studied the problem of generating non-verbatim sentences: see (Jing and McKeown, 1999), (Barzilay et al. , 1999) and more recently (Daume III and Marcu, 2004).


This is supported by evidence presented in (Jing and McKeown, 1999) and (Daume III and Marcu, 2004).


Work on phrasebased statistical machine translation has been applied to paraphrase generation (Bannard and Callison-Burch, 2005) and multi-sentence alignment in summarisation (Daume III and Marcu, 2004).


