1 Introduction One of the lessons learned from our previous experience at Senseval-31 (Buscaldi et al. , 2004; Vazquez et al. , 2004) is that the integration of different systems usually works better than a standalone system.


In our previous participation with the R2D2 project (Vazquez et al. , 2004) the selection was rule-based, with hand-made rules that attempted to take into account the reliability of the various method.


