These need to be merged, split or maybe thrown out again, depending on their utility, similarity etc. 5.3 Ambiguity Currently the problem of ambiguity is solved by endowing the analyzer with a chart and employing the semantic density algorithm described in (Bryant, 2004).


(2002) and Bryant (2004).


6 Following Bryants (2004) division of constructions into 5 levels of different degrees of schematicity.


