P06-2118:1	138:163	Niu et al (2004) applied a Naive Bayesian model to Chinese WSD and experimented with different window sizes for extracting local and topical features and different types of local features (e.g. , bigram templates, local words with position or parts-ofspeech information).
---------------------------------------------------
I05-2021:2	118:135	Apart from the voted WSD system described in section 4, and the unsupervised system (Cabezas et al. , 2004) mentioned in section 6.4, systems built and optimized for the Senseval-3 Chinese lexical sample task, include Niu et al.
---------------------------------------------------
