Future research should investigate questions such as whether there are structural constraints on coherence graphs (e.g. , as proposed by Danlos [2004]) or whether there are systematic structural differences between the coherence graphs of texts that belong to different genres (e.g. , as proposed by Bergler [1991]).


3 Other accounts assume less constrained graphs that allow crossed dependencies as well as nodes with multiple parents (e.g. , Bergler 1991; Birnbaum 1982; Danlos 2004; Hobbs 1985; McKeown 1985; Reichman 1985; Zukerman and McConachy 1995; for dialogue structure, Penstein Rose et al. 1995).


