2 As a second example, consider the WordNet definition of motorcycle: (b) Motorcycle: a motor vehicle with two wheels and a strong frame In the Gloss Word Sense Disambiguation task at Senseval-3 (Litkowski 2004), the human annotators assigned the first sense to the word frame (a structure supporting or containing something), unintentionally neglecting that the dictionary encodes a specific sense of frame concerning the structure of objects (e.g., vehicles, buildings, etc.).


Based on the eXtended WordNet, a gloss disambiguation task was organized at Senseval-3 (Litkowski, 2004).


For WordNet gloss disambiguation, we employed the dataset used in the Senseval-3 Gloss WSD task (Litkowski, 2004), which contains 15,179 content words from 9,257 glosses5.


