It differs from the many approaches where (1) is defined by a stochastic synchronous grammar (Wu, 1997; Alshawi et al. , 2000; Yamada and Knight, 2001; Eisner, 2003; Gildea, 2003; Melamed, 2004) and from transfer-based systems defined by context-free grammars (Lavie et al. , 2003).


One might doubt the use of dependency trees for alignment, since Gildea (2004) found that constituencytreesalignedbetter.


Other approaches treat rewrite rules not as a preprocessing step (e.g. , for reordering source strings), but as a part of the translation model itself (Gildea, 2003; Gildea, 2004).


Finally, we are investigating several avenues for using this system output for Machine Translation (MT) including: (1) aiding word alignment for other MT system (Wang et al., 2007); and (2) aiding the creation various MT models involving analyzed text, e.g., (Gildea, 2004; Shen et al., 2008).


