Overall, the extraction of both entities and single-sentence-embodied inter-entity relationships has proved far more difficult in the biomedical domain than in other domains such as newspaper text (Ndellec, 2005; Jing et al, 2003; Pyysalo, 2004).


Other improvements we may incorporate in future include augmenting the parsers dictionary to include biomedical terms (Slozovits, 2003), pre-processing so as to split long and complex sentences into shorter, simpler ones (Ding et al, 2003), modifying the grammar to handle with unknown constructs, and changing the link parsers ranking system (Pyysalo, 2004).


