In order to implement automatic paraphrasing, some studies (Iida et al., 2001; Tsuchiya et al., 2004) use a set of paraphrasing rules, and others (Tanabe et al., 2001; Shudo et al., 2004) use semantic equivalence classes.


Others are proposed for paraphrasing in natural language processing (Tanabe et al., 2001; Shudo et al., 2004), but these are not available in public.


In fact, most of them only create catalogs of Japanese idiom: collecting idioms as many as possible and classifying them based on some general linguistic properties (Tanaka, 1997; Shudo et al. , 2004).


posed framework has advantages over an approach based on manually created rules such as the one in (Shudo et al. , 2004), in that it requires human cost to manually create and maintain those rules.


Previous studies have mostly focused on the idiom type identification (Lin, 1999; Krenn and Evert, 2001; Baldwin et al., 2003; Shudo et al., 2004; Fazly and Stevenson, 2006).


