6 Penn Discourse Treebank (Bonnie Webber, Edinburgh) The Penn Discourse TreeBank (Miltsakaki et al. , 2004; Prasad et al. , 2004; Webber, 2005) annotates discourse relations over the Wall Street Journal corpus (Marcus et al. , 1993), in terms of discourse connectives and their arguments.


(2004b), Prasad et al.


Recent work has shown the importance of recognizing such perspectivization of information for several NLP applications, such as information extraction, summarization, question answering (Wiebe et al. , 2004; Stoyanov et al. , 2005; Riloff et al. , 2005) and generation (Prasad et al. , 2005).


This paper describes an extended annotation scheme for marking the attribution of discourse relations and their arguments annotated in the Penn Discourse TreeBank (PDTB) (Miltsakaki et al. , 2004; Prasad et al. , 2004; Webber et al. , 2005), the primary goal being to capture the source and degrees of factuality of abstract objects.


