The feasibility of automatically identifying outcome statements in secondary sources has been demonstrated by Niu and Hirst (2004), but our workdiffersinitsfocusontheprimarymedicalliterature.


Although individual components that attempt to operationalize principles of evidencebased medicine do exist (Mendonca and Cimino, 2001; Niu and Hirst, 2004), complete endto end clinical question answering systems are dif847 ficult to find.


