It has been successfully applied to the identification of semantic relations (Ahn et al. , 2004), using FrameNet as the training corpus.


Since the grammatical functions are not directly available from the parse trees, we investigated two approximations of dependency arc labels: first, the POSs of the head tokens; secondly, the PTs of the head node and its immediate parent (such labels were used in (Ahn et al. , 2004)).


