(Allauzen et al. , 2004) introduces a general indexation framework by indexing expected term frequencies (expected counts) instead of each individual keyword occurrence or lattice arcs.


As shown in (Allauzen et al., 2004), the path with input of string x and output of label i has a weight corresponding to the negative log of the expected count of x in utterance ui.


We adopt the weighted automata indexation algorithm reported in (Allauzen et al., 2004), which is optimal for searching subword sequences, as it takes time linear in the sum of the query size and the number of speech media entries where it appears.


This is achieved by factor selection in (Allauzen et al., 2004).


