1.2 Prague Dependency Treebank The Prague Dependency Treebank (PDT) presents a language resource containing a deep manual analysis of texts(Sgall et al., 2004).


1.1 Prague Dependency Treebank The Prague Dependency Treebank is a language resource containing a deep manual analysis of text (Sgall et al. , 2004).


1 Introduction Cedit is a part of a project to create a rich resource of manually annotated semantic structures (Novak, 2007) as a new layer of the Prague Dependency Treebank (Sgall et al. , 2004).


The rst six papers describe linguistic annotation in four languages: Spanish (Alcantara and Moreno, 2004), English (Miltsakaki et al. , 2004; Babko-Malaya et al. , 2004; Meyers et al. , 2004), Czech (Sgall et al. , 2004) and German(Baumann et al. , 2004).


