We base our candidate generation on a method that Fung and Cheung (2004) developed for extracting loose translations (comparable sentence pairs) from quasi-comparable corpora [9], as shown in Figure 2. 
The research reported by Fung and Cheung (2004a; 2004b), Cheung and Fung (2004) and Wu and Fung (2005) is aimed explicitly at very non-parallel corpora. 
Another approach focused on sentence extraction (Fung and Cheung, 2004). 
The approach of Fung and Cheung (2004) is a simpler version of ours. 
Fung and Cheung (2004) present an extraction method similar to ours but focus on very-non-parallel corpora, aggregations of Chinese and English news stories from different sources and time periods. 
