(Tan et al. , 2004) applied SVMs to Chinese chunking. 
The CKIP (Chinese Knowledge Information Processing) Chinese-Treebank (CCTB) and the Penn Chinese Treebank (PCTB) are two of most important Chinese Treebank resources for Treebank-derived NLP tasks in Chinese (CKIP, 1995; Xia et al. , 2000; Xu et al. , 2000; Li et al. , 2004). 
Furthermore, compared with the other languages, there are some special problems for Chinese chunking(Li et al. , 2004). 
CKIP Chinese-Treebank (CCTB) and Penn Chinese Treebank (PCTB) are two important resources for Treebank-derived Chinese NLP tasks (CKIP, 1995; Xia et al. , 2000; Xu et al. , 2002; Li et al. , 2004). 
For English (Sang and Buchholz, 2000) and Chinese (Li et al. , 2004) languages, the top 3 most frequent chunk types are NP, VP and PP chunks. 
