The latter is currently dominating in NER amongst which the most popular methods are decision tree (Sekine et al. , 1998; Pailouras et al. , 2000), Hidden Markov Model (Zhang et al. , 2003; Zhao, 2004), maximum entropy (Chieu and Ng, 2002; Bender et al. , 2003), and support vector machines (Isozaki and Kazawa, 2002; Takeuchi and Collier, 2002; Mayfield, 2003).


HMMs were employed by one system in isolation (Zhao, 2004) and by two systems in combination with SVMs (Zhou and Su, 2004; R ossler, 2004).


Zhao (2004) reports about the usefulness of unlabeled MEDLINE corpus as a complement to expensive and limited size of labeled corpus.


Various machine learning approaches such as ME (Kazama et al. , 2002), SVM (Kazama et al. , 2002; Song et al. , 2004), HMM (Zhao, 2004) are applied to NER.


