NC interpretation has been studied in the context of applications including question-answering and machine translation (Moldovan et al. , 2004; Cao and Li, 2002; Baldwin and Tanaka, 2004; Lauer, 1995).


Baldwin and Tanaka (2004) calculated that 3.9% and 2.6% of the tokens in the Reuters corpus and the British National Corpus (BNC), respectively, are part of a noun compound.


This is similar to the generation and selection procedures used in the literature (Baldwin and Tanaka (2004), Cao and Li, Langkilde and Knight (1998)).


4 Pattern switching The compositional translation presents problems which have been reported by (Baldwin and Tanaka, 2004; Brown et al., 1993): Fertility SWTs and MWTs are not translated by a term of a same length.


This has been done by either just concatenating the translations of component words to form a candidate (Grefenstette, 1999; Cao and Li, 2002), or using syntactic templates such as E2 in E1, E1 of E2 to form translation candidates from the translation of the component words E2 and E1 (Baldwin and Tanaka, 2004), or using synsets of the component word translations to include synonyms in the compositional candidates (Navigli et al., 2003).


