P07-2053:1	54:70	Hungarian We evaluated the different models by tenfold cross-validation on the Szeged Corpus (Csendes et al. , 2004), with the relevant data in presented Table 3.
---------------------------------------------------
W06-1701:2	79:143	For example the word nem, can mean both not and gender, so both ADV and NOUN are valid analyses, but the adverbial reading is about five orders of magnitude more frequent than the noun reading, (12596 vs. 4 tokens in the 1 m word manually annotated Szeged Korpusz (Csendes et al. , 2004)).
---------------------------------------------------
W06-1701:3	73:143	Hungarian is particularly challenging in this regard, both because the number of ambiguous tokens is high (reaching 50% in the Szeged Corpus according to (Csendes et al. , 2004) who use a different MA), and because the ratio of tokens that are not seen during training (unseen) can be as much as four times higher than in comparable size English corpora.
---------------------------------------------------
W06-1701:4	74:143	But if larger training corpora are available, significant disambiguation is possible: with a 1 m word training corpus (Csendes et al. , 2004) the TnT (Brants, 2000) architecture can achieve 97.42% overall precision.
---------------------------------------------------
