See (Escudero et al. , 2004) for more details on the set of features used.


The need for multiple knowledge sources has become a golden rule, and the ?lexical sensitivity??once remarked by Resnik and Yarowsky (1997) is addressed by various means in statistical classifiers, such as learning an optimal combination of the various knowledge sources for individual target words (e.g. Mihalcea, 2002; Escudero et al. , 2004).


