Very few approaches, like (Alam, 2004; SaintDizier and Vazquez, 2001), consider both, the head (modified) and the complement (modifier) information, to decide the sense of the preposition.


(Alam, 2004) make use of contextual information to determine the meanings of over.


2.2 Feature Extraction Following OHara and Wiebe (2003) and Alam (2004), we assumed that there is a meaningful connection between syntactically related words on both sides of the preposition.


Some research has focused on the sense disambiguation of specific prepositions (e.g. , Alam, 2004), while other work has classified preposition tokens according to their semantic role (OHara and Wiebe, 2003).


