The most frequently applied 72 models were SVMs with totally ve systems adopting SVMs as the classi cation models either in isolation (Park et al. , 2004; Lee et al. , 2004) or in combination with other models (Zhou and Su, 2004; Song et al. , 2004; R ossler, 2004).


Part-of-speech information was incorporated in ve systems: four of them utilized domainspecialized part-of-speech taggers (Zhou and Su, 2004; Finkel et al. , 2004; Song et al. , 2004; Park et al. , 2004) and the other utilized generalpurpose taggers (Lee et al. , 2004).


