The CKIP (Chinese Knowledge Information Processing) Chinese-Treebank (CCTB) and the Penn Chinese Treebank (PCTB) are two of most important Chinese Treebank resources for Treebank-derived NLP tasks in Chinese (CKIP, 1995; Xia et al. , 2000; Xu et al. , 2000; Li et al. , 2004).


As per the reports (Menzel, 1995; Sang and Buchholz, 2000; Basili and Zanzotto, 2002; Knutsson et al. , 2003; Li et al. , 2004; Xu et al. , 2004; Johnny et al. , 2005), there are three important trends in the study of Chinese text chunking and parsing.


