Some of these component models were also evaluated on other Senseval-3 tasks: the Basque, Catalan, Italian, and Romanian Lexical Sample tasks (Wicentowski et al. , 2004), as well as Semantic Role Labeling (Ngai et al. , 2004).


The two-tiered voting was performed to ensure equal voting in the case of our joint work (Wicentowski et al. , 2004) where the five systems that needed to be combined were run on different numbers of feature subsets.


Details on this joint effort can be found in (Wicentowski et al. , 2004).


