One line of work has primarily focused on grammaticality and naturalness, scoring the overgeneration phase with a SLM, and evaluating against a gold-standard corpus, using string or tree-match metrics (Langkilde-Geary, 2002; Bangalore and Rambow, 2000; Chambers and Allen, 2004; Belz, 2005; Isard et al., 2006).


Chambers [Chambers and Allen, 2004] used HALogen in a dialogue system and performed a human evaluation of the mixed syntax/semantic input.


This approach was first used in a dialogue system in [Chambers and Allen, 2004] as an attempt to create a domain independent surface realizer.


[Chambers and Allen, 2004] Nathanael Chambers and James Allen.


