However, volunteer (and in some case freelance) translators do not tend to use these systems (Fulford and Zafra, 2004; Fulford, 2001; Kageura et al. , 2006), for a variety of reasons: most of them are too expensive for volunteer translators2; the available functions do not match the translators needs and work style; volunteer translators are under no pressure from clients to use the system, etc. This does not mean, however, that volunteer translators are satised with their working environment.


