Two other groups applied Memory-Based Learning (MBL) (van den Bosch et al. , 2004; Kouchnir, 2004).


Many research efforts utilize machine learning (ML) approaches; such as support vector machines (Moschitti et al. , 2004; Pradhan et al. , 2004), perceptrons (Carreras et al. , 2004), the SNoW learning architecture (Punyakanok et al. , 2004), EMbased clustering (Baldewein et al. , 2004), transformation-based learning (Higgins, 2004), memory-based learning (Kouchnir, 2004), and inductive learning (Surdeanu et al. , 2003).


The basic kNN in the fourth row, trained by four datasets (WSJ 15 to 18 in CoNLL 2004) for the RL task (to label arguments by giving the known arguments) on the test data WSJ 21, increases F1:6.68 compared to the result of Kouchnir (2004) in the third row.


Illustration of results by PML with different methods on WSJ 24 with known arguments System Train Test Tasks P R F1 Lacc T Palmer (2005) W02-21 W23 BR+RL 68.60 57.80 62.74 81.70 3.785 PARA+PML W02-21 W23 BR+RL 71.24 70.79 71.02 88.77 0.941 Kouchnir (2004) W15-18 W21 RL 75.71 74.60 75.15 kNN W15-18 W21 RL 81.86 81.79 81.83 83.57 0.242 Table 12.


Many existing SRL systems are also memory-based (Bosch et al. , 2004;Kouchnir, 2004), implemented using TilMBL software (http://ilk.kub.nl/software.html) with advanced methods such as Feature Weighting, and so forth.


