Similar categories areproposedbyTsovaltziandKaragjosova(2004), and may be taken up.


We follow Tsovaltzi and Karagjosova (2004) by splitting the task dimension into two subdivisions which relate to the parallel tasks being carried out and the roles of the dialogue participants.


Tsovaltzi and Karagjosova (2004) proposed an extension of the DAMSL classification based on an analysis of tutorial dialogue corpora.


