Furthermore, we discuss structural cohesion measured via Entropy-based statistics on the basis of distributional properties for unsupervised syntactic structure induction ( Cavar et al., 2004c) from raw text, and compare the results with syntactic corpora like the Penn Treebank.


In this article we will discuss in detail several experiments of morphological cue induction for lexical classification ( Cavar et al., 2004a) and ( Cavar et al., 2004b) using Vector Space Models for category induction and subsequent rule formation.


