1In our corpus of newspaper commentaries (Stede, 2004), we found that 35% of the coherence relations are signalled by a connective. 
But discourse structures cannot always be described completely, either due to genuine ambiguity (Stede, 2004) or to the limitations of a discourse parser. 
Two examples of such corpora are the RST Tree Corpus by (Marcu et al. , 1999) for English and the Potsdam Commentary Corpus (Stede, 2004) for German. 
1 Introduction Discourse structures cannot always be described completely, either because they are ambiguous (Stede, 2004), or because a discourse parser fails to analyse them completely. 
2 Overview of Chinese RST treebank under construction 2.1 Corpus data For the purpose of language engineering and linguistic investigation, we are constructing a Chinese corpus comparable to the English WSJ-RST treebank and the German Potsdam Commentary Corpus (Carlson et al. 2003; Stede 2004). 
