Two teams used Brills Transformation-based Error-driven Learning (TBL) (Higgins, 2004; Williams et al. , 2004).


Many research efforts utilize machine learning (ML) approaches; such as support vector machines (Moschitti et al. , 2004; Pradhan et al. , 2004), perceptrons (Carreras et al. , 2004), the SNoW learning architecture (Punyakanok et al. , 2004), EMbased clustering (Baldewein et al. , 2004), transformation-based learning (Higgins, 2004), memory-based learning (Kouchnir, 2004), and inductive learning (Surdeanu et al. , 2003).


