 Character Error Rate (CER): Edit distance in terms of characters between the target sentence provided by the system and the reference translation (Civera et al. , 2004).


A desirable feature of the iterative machine translation system is the possibility of producing a list of target suffixes, instead of only one (Civera et al. , 2004).


In (Civera et al. , 2004) finite state transducers are presented as a candidate technology in the CAT paradigm.


Now, Equation (5) is rewritten as  t s = argmax t s Pr(t p ,t s ,s)(7) which allows the use of the same models as in Equation (4) as long as the search procedure is changed appropriately (Cubel et al. 2003, 2004; Civera et al. 2004a, 2004b).


Some of these results may differ from results presented in previous works (Cubel et al. 2003; Och, Zens, and Ney 2003; Civera et al. 2004a; Cubel et al. 2004; Bender et al. 2005).


