Each word is tagged with B-X, I-X, or O to indicate that the word is at the beginning (B) or inside (I) of a named entity of type X, or 1http://research.nii.ac.jp/collier/ workshops/JNLPBA04st.htm System F1 (Zhou and Su, 2004) 72.55 Online Cascaded 72.16 (Okanohara et al., 2006) 71.48 (Kim et al., 2005) 71.19 (Finkel et al., 2004) 70.06 (Settles, 2004) 69.80 Table 1: Comparisons with other systems on overall performance (in percentage).


