(Gasperin and Vieira, 2004) tested the use of word similarity lists on resolving indirect anaphora, reporting 33% of recall.


Additionally, we included an approach due to Gasperin and Vieira (2004), who tackle the problem of similarity by using lists of most similar words to a certain word, based on a similarity measure closely related to Lins. They allow resolution if either (i) the candidate is among the words most similar to the anaphor, (ii) the anaphor is among the words most similar to the candidate, (iii) the similarity lists of anaphor and candidate share a common item.


(1998) use a general word association metric based on common terms occuring in a fixed-width window, Gasperin and Vieira (2004) use syntactic contexts of words in a large corpus to induce a semantic similarity measure (similar to the one introduced by Lin, 1998), and then use lists of the n nouns that are (globally) most similar to a given noun.


Starting with the combination of GermaNet and patternbased search on the World Wide Web, we begin by adding the distance-bounded semantic similaritybased resolver (LinBnd) and resolution based on the list of 25 most similar words (following the 502 approach of Gasperin and Vieira 2004).


Bridging anaphora (Clark, 1975) represents a special part of the general problem of anaphora resolution, which has been studied and discussed for various languages and domains (Hahn et al., 1996; Murata et al., 1999; Poesio et al., 2004; Gasperin and Vieira, 2004; Gasperin and Briscoe, 2008).


