These represent a subset of features used in previous works (Gildea and Jurafsky, 2002; Florian et al. , 2002; Surdeanu et al. , 2003; Xue and Palmer, 2004; Bejan et al. , 2004; Pradhan et al. , 2005) for automatic semantic role labeling and word sense disambiguation.


The sub-tasks TWFD and GFLC are natural extensions of the approach described in (Bejan et al. , 2004) for the task of semantic role labeling at Senseval-03.


For this task, we extended our previous work at Senseval-3 (Bejan et al. , 2004) by (1) experimenting with additional features, (2) adding new classi cation sub-tasks to accomplish all the requirements, and (3) integrating these sub-tasks into a pipeline architecture.


