(Baumann et al. , 2004) annotated a simpler information structure and prosodic events in a small German corpus.


(Baumann et al. , 2004) also describes how a number of different linguistic levels can be related in annotation (pragmatic and prosodic) among two languages (English and German).


The rst six papers describe linguistic annotation in four languages: Spanish (Alcantara and Moreno, 2004), English (Miltsakaki et al. , 2004; Babko-Malaya et al. , 2004; Meyers et al. , 2004), Czech (Sgall et al. , 2004) and German(Baumann et al. , 2004).


The sixth, seventh and eighth papers (Baumann et al. , 2004; C mejrek et al. , 2004; Helmreich et al. , 2004) explore questions of multilingual annotation of syntax and semantics, beginning to answer the question of how annotation systems can be made compatible across languages.


