Among the current similar works, Table 4 shows that our system outperforms Chen(2004) in VV compounds, and approximates the Chen and Chen(2000) in NN compounds. 
Chen (2004) proposed a model that retrieves the word with the greatest association with the target word. 
4.4 Circumventing Head-oriented Presupposition As remarked in Chen (2004), the previous research concerning the automatic semantic classification of Chinese compounds (Lua 1997; Chen and Chen 2000) presupposes the endocentric feature of compounds. 
Chen (2004) used the  2 measure to compute character-character and word-word associations, but not word-category associations. 
To solve above-mentioned problems, Chen (2004) proposed a non head-oriented charactersense association model to retrieve the latent senses of characters and the latent synonymous compounds among characters by measuring similarity of semantic template in compounding by using a MRD. 
