Kim and Park (Kim and C.Park, 2004) introduced BioAR, a biomedical anaphora resolution system that relates entity mentions in text with their corresponding Swiss-Prot entries.


Kim and Park (2004), however, detect 53 pronominal and 26 nominal anaphora in 87 anaphoric expressions.


1Term mapping is also called term grounding, amongst others by Kim and Park (2004).


This is also called semantic integration, e.g., (Li et al. , 2005), reference grounding, e.g., (Kim and Park, 2004) or normalization, e.g., (Pustejovsky et al. , 2002; Morgan et al. , 2004).


e) Protein names resolution against database entries in SwissProt, protein name grounding, in the context of a relation extraction task (Kim and Park, 2004).


