3 Experimental Settings 3.1 Training We applied the Vector Space Model (VSM) algorithm on the two different kinds of sense examples (i.e. , dictionary translated ones vs. MT software translated ones), as it has been shown to perform well with the features described below (Agirre and Martinez, 2004a).


In the future, we would like to combine our approach with other systems based on automatic acquisition of sense examples that can provide local context (Agirre and Martinez, 2004b).


