This task is reminiscent of the well-known War of the Ghosts experiment used in psychology for studying memory (Bartlett, 1932) and related to work in fields such as summarization (Lemaire et al. , 2005) and narration (Halpin et al. , 2004).


Unlike previous work, the use of both the plot comparison results and LSA did not improve performance for Naive Bayes, so the results of using Naive Bayes with both are not reported (Halpin et al. , 2004).


Pronoun resolution is carried out using the Glencova Pronoun Resolution algorithm (Halpin et al. , 2004), based on a series of rules similar to the CogNIAC engine (Baldwin, 1997), but without gender informationbased rules since this is not provided by the Penn Treebank tagset.


The natural language processing and story conversion pipeline are improvements over a pipeline that was shown to successfully compare stories in a manner similar to a teacher (Halpin et al. , 2004).


