First, a lexicon from NICT (National Institute of Information and Communications Technology, Japan) is used as the basic lexicon, which is extracted from Peking University Corpus of the second SIGHAN Bakeoff (T.Emerson, 2005), Penn Chinese Treebank 4.0 (N.Xue et al. ,2002), a Chinese-to-English Wordlist1 and part of NICT corpus (K.Uchimoto et al. ,2004; Y.J.Zhang et al. ,2005).


The National Institute of Information and Communications Technology therefore started a project to build multilingual parallel corpora in 2002 (Uchimoto et al. , 2004).


