W04-0863:1	16:71	The component models were also used in other Senseval-3 tasks: Semantic Role Labeling (Ngai et al. , 2004) and the lexical sample tasks for Chinese and English, as well as the Multilingual task (Carpuat et al. , 2004).
---------------------------------------------------
W04-0822:2	41:102	Some of these component models were also evaluated on other Senseval-3 tasks: the Basque, Catalan, Italian, and Romanian Lexical Sample tasks (Wicentowski et al. , 2004), as well as Semantic Role Labeling (Ngai et al. , 2004).
---------------------------------------------------
W04-0862:3	103:107	In addition, the decision list system described here was used in the Semantic Role Labeling task submitted by (Ngai et al. , 2004).
---------------------------------------------------
