(Byron and Allen, 1998) and even more in Danish (Navarretta, 2004).


To resolve IPAsandAPAsinDanishtexts and dialogues Navarretta (2004) has proposed the so-called dar-algorithm (Navarretta, 2004).


Resolving Individual and Abstract Anaphora in Texts and Dialogues Costanza Navarretta Center for Sprogteknologi, University of Copenhagen Njalsgade 80 2300 Copenhagen S costanza@cst.dk Abstract This paper describes an extension of the dar-algorithm (Navarretta, 2004) for resolving intersentential pronominal anaphors referring to individual and abstract entities in texts and dialogues.


