 An AR model that carries out antecedent identification before anaphoricity determination, the decision whether a given NP is anaphoric or not (i.e. discourse-new), significantly outperforms a model that executes those subtasks in the reverse order or simultaneously (Poesio et al. , 2004; Iida et al. , 2005).


The two-step model (Ng, 2004; Poesio et al. , 2004; Iida et al. , 2005), on the other hand, carries out anaphoricity determination in a separate step from antecedent identification.


