1020 Bayes (Soft Tag) 73.6 SVM-topic 73.0 SVM baseline 72.4 NB baseline 69.8 ASO(Ando, 2006) 74.1 SVM-LSA (Strapparava et al. , 2004) 73.3 Senseval-3 Best System(Grozea, 2004) 72.9 Table 5: Results compared to previous best systems on Senseval-3 English lexical sample task.


[G04] Grozea (2004); [SGG04] Strapparava et al.


(%) 1 htsa3 (Grozea, 2004) 72.9 2 IRST-kernels (Strapparava et al. , 2004) 72.6 3 nusels (Lee et al. , 2004) 72.4 4 SENSEVAL-3 contest baseline 55.2 5 Niu et al.


The best system in Senseval-3 (Mihalcea et al. , 2004; Grozea, 2004) achieved 72.9% fine grained, 79.3% coarse grained accuracy.


