P05-1073:1	180:185	(Punyakanok et al. , 2004) use a linear programming framework to ensure that the only argument frames which get probability mass are ones that respect global constraints on argument labels.
---------------------------------------------------
W04-2412:2	146:292	(2004) used Voted Perceptrons (VP) also with polynomial kernels, and finally, Punyakanok et al.
---------------------------------------------------
W04-2412:3	198:292	(2004) and Punyakanok et al.
---------------------------------------------------
