We evaluate our methods on the ICSI meeting recorder dialog act (MRDA) (Shriberg et al. , 2004) corpus, and nd that our novel hidden backoff model can signi cantly improve dialog tagging accuracy. 
Apart from the data recently available in the IM2 project, results reported in this paper make use of the ICSI Meeting Recording (MR) corpus of transcribed and annotated dialogues (Morgan et al. , 2003; Shriberg et al. , 2004)3. 
All the meetings have been transcribed and annotated with dialog acts (DA) (Shriberg et al., 2004), topics, and extractive summaries (Murray et al., 2005). 
4 Experimental Results We evaluated our hidden backoff model on the ICSI meeting recorder dialog act (MRDA) corpus (Shriberg et al. , 2004). 
First, it is rare to have subDAs labeled in training data, and indeed this is true of the corpus (Shriberg et al. , 2004) that we use. 
