MWU processing in Turkic languages involves more than the usual lexicalized collocations and involves detection of mostly unlexicalized intraword morphological patterns (Oflazer et al. , 2004).


With regard to syntactic and morphological flexibility, MWEs are classified into three types: fixed, semi-fixed and syntactically flexible expressions (Baldwin 2004; Oflazer et al 2004; Sag et al 2001).


