We manuallybuilt patternsfor each event type by examiningthe training data and by using native speaker intuitionsabout likely ways of expressingrelationships,similar to the technique describedin (Cohenet al., 2004).


Although there seems to be a distinction between test collections and test suites (Cohen et al., 2004) (the former defined as pieces of text and associated with corpora, the latter, as lists of specially constructed sentences, or sentence sequences, or sentence fragments (Balkan et al., 1994)), evaluation of answers to clinical questions crosses this boundary and requires the availability of carefully generated sentence fragments as well as suitable document collections.


(Cohen et al., 2004) describes a methodology for generating test suites for molecular biology named entity recognition systems, and (Johnson et al., 2007) describes the development of a fault model for linguistically-based ontology mapping, alignment, and linking systems.


