SUMMARISE : D,k 1 S{} 2 whilesummationtextt iS LENGTH(ti) < k 3 tj EXTRACT(D) 4 SStj 5 DUPDATE(D,tj) 6 returnS Figure 1: Generalised function for Filatova and Hatzivassiloglou (2004) approach to extractive summarisation. 
This representation 1) models a type of generic IE that includesrelations,2)usesaconnectormodelthatabstracts away from surface-level event descriptors used by Filatova and Hatzivassiloglou (2004) and 3) does not rely on domain-specific resources like WordNet.6 For the purpose of comparison, relation triples are weighted in the same way as event triples using Equations 3 and 4 above. 
3 Algorithm for Set Cover Extraction For the sake of comparison, the current evaluation adopts the Filatova and Hatzivassiloglou (2004) summarisation framework. 
4.2 Event Representation (EV) We also compare to Filatova and Hatzivassiloglou (2004) atomic events (EV). 
1 Introduction Event-based extractive summarization has emerged recently (Filatova and Hatzivassiloglou, 2004). 
