The semantic tags we use can be seen as a form of semantic categorization acting in a similar manner to the semantic class of a word in the system of (Lamjiri et al. , 2004).


(Lamjiri et al. , 2004) also developed an ME-based system that used a very simple set of features: the article before; the POS before and after; the preposition before and after, and the syntactic category before and after the word being labeled.


CLaC1 (Lamjiri et al. , 2004) uses a Naive Bayes algorithm with a dynamically adjusted context window around the target word.


Unsurprisingly, it has been found that this is a parameter which can have a significant impact upon performance (Yarowsky and Florian, 2002; Lamjiri et al., 2004; Wang, 2005).


