For a fair comparison, our system was among the best at CoNLL-04, where the best system (Hacioglu et al. , 2004) achieve a 69.49 F1 score. 
Our target application is node relation labeling, which includes NLP tasks such as semantic role labeling (SRL) (Gildea and Jurafsky, 2002; Moschitti, 2004; Hacioglu et al. , 2004). 
SRL feature extraction has relied on various syntactic representations of input sentences, such as syntactic chunks (Hacioglu et al. , 2004) and full syntactic parses (Gildea and Jurafsky, 2002). 
The best performance was obtained by the SVMbased IOB tagger of (Hacioglu et al. , 2004), which almost reached the performance of 70 in F1 on the test. 
5.2 Chunk-based Semantic Labeler Hacioglu has previously described a chunk based semantic labeling method (Hacioglu et al. , 2004). 
