However, some of the systems restrict the search for arguments only to the immediate clause (Park et al. , 2004; Williams et al. , 2004) and others use the clause hierarchy to guide the exploration of the sentence (Lim et al. , 2004; Carreras et al. , 2004).


Two teams used Brills Transformation-based Error-driven Learning (TBL) (Higgins, 2004; Williams et al. , 2004).


In fact (Williams et al. , 2004) and (Baldewein et al. , 2004) even improved the results on the test set.


