For example, (Harman and Over, 2004) noted that a human summary can vary in its level of granularity, whether the summary has a very high-level analysis or primarily contains details.


In their examination of summary evaluations, van Halteren and Teufel (2003) suggest that it is necessary to use at least 30 to 40 model summaries for a stable evaluation; however, Harman and Over (2004) argue that a stable evaluation can be conducted even with a single model, as long as there is an adequate number of topics.


This result agrees with DUCs additional evaluation results (Harman and Over, 2004).


The evaluation metric follows DUCs SEE evaluation scheme (Harman and Over, 2004).


We have seen the development of manual methods for evaluation developed both within DUC (Harman and Over, 2004) and without.


