The dependency relations provided by a parser such as Pro3Gres, combined with domain specific axioms, allow the creation of (some of) the semantic annotations, as described in (Rinaldi et al. , 2003; Kaljurand et al. , 2004).


5 Applications and Evaluation Pro3Gres is currently being applied in a Question Answering system specifically targeted at Figure 3: Dependency Tree output of the SWI Prolog graphical implementation of the parser technical domains (Rinaldi et al. , 2004b).


The modified QA system (using Pro3Gres) is being exploited in the area of Life Sciences, for applications concerning Knowledge Discovery over Medline abstracts (Rinaldi et al. , 2004a; Dowdall et al. , 2004).


The trees obtained from parsing can be decompressed into traditional constituency trees including empty nodes and co-indexation, or into shallow semantic structures such as Minimal Logical Forms (MLF) (Rinaldi et al. , 2004b; Schneider et al. , 2000; Schwitter et al. , 1999).


