In (Hana et al. , 2004), Czech data is used to develop a morphological analyzer for Russian. 
3.1) for easier detailed evaluation and for comparison with our previous work that used a similar approach for tagging (Hana et al. , 2004; Feldman et al. , 2006). 
Is the processing of Portuguese via Spanish different from the processing of Russian via Czech (Hana et al. , 2004; Feldman et al. , 2006)? 
We extend the similar work that we have done (Hana et al. , 2004; Feldman et al. , 2006) by proposing an alternative algorithm for cognate transfer that effectively projects the Spanish emission probabilities into Portuguese. 
We have previously shown that this approach can work for Czech and Russian (Hana et al. , 2004; Feldman et al. , 2006). 
