Details on this have been described in (Leusch et al. , 2005).


(Leusch et al. , 2005) investigate preprocessing and normalisation methods for improving the evaluation using the standard measures WER, PER, BLEU and NIST.


Let the length of the hypothesis sentence hypk be denoted as Nhypk, and the reference lengths of each sentence Nref k,r. Then, the total hypothesis length of the document is Nhyp =summationtextk Nhypk, and the total reference length is Nref = summationtextk N?ref k where N?ref k is defined as the length of the reference sentence with the lowest sentence-level error rate as shown to be optimal in (Leusch et al. , 2005).


102 a certain range (e.g. in the mid-range or only extreme values), which constitute an additional difficulty when carrying out the evaluation (Leusch et al. , 2005).


