Four of them with the standard polynomial kernels (Mitsumori et al. , 2005; Tjong Kim Sang et al. , 2005; Tsai et al. , 2005; Pradhan et al. , 2005b), another one using Gaussian kernels (Ozgencil and McCracken, 2005), and a last group using tree-based kernels specifically designed for the task (Moschitti et al. , 2005).


(2005b) and Mitsumori et al.


Differently, other systems have captured features from the left/right tokens surrounding the argument, which are typically words, but can be chunks or general phrases in systems that sequentialize the task (M`arquez et al. , 2005; Pradhan et al. , 2005b; Mitsumori et al. , 2005).


