Perhaps the most interesting account of overspecification so far is the one proposed by Horacek (2005), where logically redundant properties enter the descriptions generated when the combined certainty of other properties falls short of what is contextually required.


Someofthisworkismainlyorexclusively experimental (Jordan and Walker, 2000; Arts, 2004), but algorithmic consequences are also being explored (Horacek, 2005; Paraboni and van Deemter, 2002; van der Sluis and Krahmer, 2005).


For example, the approach of (Horacek, 2005) to GRE allows degrees of uncertainty about the effectiveness of properties to affect their selection.


The simplest estimation of Pr(o|p,a) following this conventional Boolean domain modeling is Pr(o|p,a)  { ||1 (p in o has a) 0 (p in o does not have a) (8) where  is the subset of , each member of which has attribute value a in its part of p. As Horacek (2005) pointed out, however, this standard approach is problematic in a real environmentbecausemanyphysicalattributesarenondiscrete and the symbolization of these continuous attributes have uncertainties.


Figure 1: An example scene 191 2 Related work Horacek (2005) proposes to introduce probabilities to overcome uncertainties due to discrepancies in knowledge and cognition between subjects.


