Four of them with the standard polynomial kernels (Mitsumori et al. , 2005; Tjong Kim Sang et al. , 2005; Tsai et al. , 2005; Pradhan et al. , 2005b), another one using Gaussian kernels (Ozgencil and McCracken, 2005), and a last group using tree-based kernels specifically designed for the task (Moschitti et al. , 2005). 
The details of SEROW system are described in (Tsai et al. , 2005) and (Tsai et al. , 2006b). 
In particular, 8 teams used the Maximum Entropy (ME) statistical framework (Che et al. , 2005; Haghighi et al. , 2005; Park and Rim, 2005; Tjong Kim Sang et al. , 2005; Sutton and McCallum, 2005; Tsai et al. , 2005; Yi and Palmer, 2005; Venkatapathy et al. , 2005). 
Detailed descriptions of these features can be found in (Tsai et al. , 2005). 
In the second step, we first use an SRL system (Tsai et al. , 2005) trained on the Wall Street Journal (WSJ) to automatically tag our corpus. 
