Yi and Palmer (2005) retrained a constituent parser in which phrases were annotated with argument information to improve SRL, however this didnt improve over the output of the basic parser. 
(Yi and Palmer, 2005) share the motivation of our work, although they apply it to a different task. 
Interestingly, Yi and Palmer (2005) retrained Ratnaparkhis parser using the WSJ training sections enriched with semantic information coming from PropBank annotations. 
(Yi and Palmer, 2005) share the motivation of our work. 
Yi and Palmer (2005) did also a greedy merging of arguments but taking into account not complete solutions but all candidate arguments labeled by base systems (ac-join). 
