Further results using this set are reported in Almuhareb and Poesio (2005b).


Whereas dependency based semantic spaces have been shown to surpass other word space models for a number of problems (Pad and Lapata, 2007; Lin, 1998), for the task of categorisation simple pattern based spaces have been shown to perform equally good if not better (Poesio and Almuhareb, 2005b; Almuhareb and Poesio, 2005b).


3.2 Results for 402 words from Almuhareb and Poesio (2005a) In Poesio and Almuhareb (2005a) a larger evaluation set is introduced that comprises 402 nouns sampled from the hierarchies under the 21 unique beginners in WordNet.


association measure g-score t-score t-score+ dependency based space 67.9% 67.2% 79.1% window based space 65.7% 60.7% 67.9% pattern based space 70.9% Table 4: Categorisation results for the 402 concepts and 21 classes proposed in Almuhareb and Poesio (2005a) which is also the source of the result for the pattern based space.


Poesio and Almuhareb (Poesio and Almuhareb, 2005) present a machine learning based approach to classifying attributes into the six categories: quality, part, related-object, activity, related-agent and non-attribute.


