(Gliozzo and Strapparava, 2005).


In the literature, this task has been proposed quite recently (Bel et al. , 2003; Gliozzo and Strapparava, 2005).


For further details see (Gliozzo and Strapparava, 2005).


A few novel models have been proposed to address the problem, e.g. the EM-based algorithm (Rigutini et al., 2005), the information bottleneck approach (Ling et al., 2008), the multilingual domain models (Gliozzo and Strapparava, 2005), etc. To the best of our knowledge, cotraining has not yet been investigated for crossdomain or cross-lingual text classification.


