Our results may seem to contradict the results of many previous RTE studies such as (Bar-Haim et al., 2005) which found paraphrases to make an important contribution.


A number of papers have suggested that paraphrase knowledge plays a very important role (Bar-Haim et al., 2005; Marsi et al., 2007; Dinu and Wang, 2009).


(Bar-Haim et al., 2005; Garoufi, 2007)) indicate that frame semantics plays a central role in Recognizing Textual Entailment (RTE).


