Others have also drawn on the notion of syntactic fixedness for idiom detection, though specific to a highly constrained type of idiom (Widdows and Dorow, 2005).


MWE research has focussed largely on their implications in language understanding, fluency and robustness (Pearce, 2001; Sag et al. , 2002; Copestake and Lascarides, 1997; Bannard et al. , 2003; McCarthy et al. , 2003; Widdows and Dorow, 2005).


