A complete description of the annotation guidelines can be found in (Calhoun et al. , 2005).


Each word was manually labeled for presence or absence of pitch accent1, as well as additional features including information status (or givenness), contrast and animacy distinctions, (Nissim et al. , 2004; Calhoun et al. , 2005; Zaenen et al. , 2004), features that linguistic literature suggests are predictive of prominence (Bolinger, 1961; Chafe, 1976).


In fact, with help from the authors of (Calhoun et al. , 2005), I did incorporate their analysis into the latest version (number 6) of the Pie in the Sky annotation.


The 5th through 7th papers (Inui and Okumura, 2005; Calhoun et al. , 2005; Wilson and Wiebe, 2005) investigate some additional types of annotation that were not part of the distributed version of Pie in the Sky, but which could be added in principle.


3 Whats in the Latest Pie in the Sky Analysis As of this writing, the latest Pie in the Sky analysis includes: (1) argument structure of all parts of speech (verbs, nouns, adjectives, determiners, conjunctions, etc.) using the PropBank/NomBank/Discourse Treebank argument labels (ARG0, ARG1, ARG2, a0a1a0a2a0 ), reminiscent of Relational Grammar of the 1970s and 1980s (Perlmutter, 1984), (2) some more speci cally labeled FrameNet (Baker et al. , 1998) roles for these same constituents; (3) morphological and part of speech features; (4) pointers to gazetteers, both real and hypothetical (thanks to B. Sundheim); (5) Veracity/According-To features based on NYUs proposed FactBank annotation scheme; (6) various coreference features including some based on a proposed extension to NomBank; (7) temporal features based on Timex2 (Ferro et al. , 2002) and TimeML (Pustejovsky et al. , 2004); and (8) Information Structure features based on (Calhoun et al. , 2005).


