Remarkably, Park and Rim (2005) parametrize the pruning procedure and then study the effect of being more or less aggressive at filtering constituents.


In particular, 8 teams used the Maximum Entropy (ME) statistical framework (Che et al. , 2005; Haghighi et al. , 2005; Park and Rim, 2005; Tjong Kim Sang et al. , 2005; Sutton and McCallum, 2005; Tsai et al. , 2005; Yi and Palmer, 2005; Venkatapathy et al. , 2005).


