Within SDRT, Baldridge and Lascarides (2005b) also take a data-driven approach to the tasks of segmentation and identification of discourse relations. 
(Baldridge and Lascarides, 2005) reports 43.2% FScore on parsing 10 dialogues using a probabilistic head-driven parsing model. 
The work on discourse parsing that is most similar to ours is that of Baldridge and Lascarides (2005). 
They create a probabilistic discourse parser based on dialogues from the Redwoods Treebank, annotated with SDRT rhetorical relations (Baldridge and Lascarides, 2005a). 
More recently, Baldridge and Lascarides (2005) successfully implemented a probabilistic parser that uses headed trees to label discourse relations. 
