A more recent work that applies Conditional Random Fields to segment and part of speech tag Amharic words is done by Fissaha (Adafre, 2005).


In spite of the relatively large number of speakers, Amharic is still a language for which very few computational linguistic resources have been developed, and previous efforts to create language processing tools for Amharice.g., Alemayehu and Willett (2002) and Fissaha (2005)have been severely hampered by the lack of large-scale linguistic resources for the language.


More recently, CRFs have been applied to segment and tag Amharic words (Fissaha, 2005), giving an accuracy of 84% for word segmentation, using character, morphological and lexical features.


Thirdly, for comparison reasons, the full tagset was mapped to the 10 tags used by Fissaha (2005).


