6 Model CONLL 23 Comments P R F (Surdeanu and Turmo, 2005) 80.3 73.0 76.5 Propbank frames to filter output, boosting (Liu et al., 2005) 80.5 72.8 76.4 Single system + simple post-processing (Moschitti et al., 2005) 76.6 75.2 75.9 Specialised kernels for each kind of role This paper 87.6 65.8 75.1 Single system and model, locality features (Ozgencil and McCracken, 2005) 74.7 74.2 74.4 Simple system, no external knowledge (Johansson and Nugues, 2005) 75.5 73.2 74.3 Uses only 3 sections for training Table 3: Final Semantic Role Labelling results on test section 23 of Propbank as encoded in the CONLL shared task for those CONLL 2005 participants not using ensemble learning or external resources.


Four of them with the standard polynomial kernels (Mitsumori et al. , 2005; Tjong Kim Sang et al. , 2005; Tsai et al. , 2005; Pradhan et al. , 2005b), another one using Gaussian kernels (Ozgencil and McCracken, 2005), and a last group using tree-based kernels specifically designed for the task (Moschitti et al. , 2005).


