5 Experiments We use the phrase-based SMT system, Portage (Sadat et al. , 2005). 
This operation is conceptually not very different from a target-to-target translation; for this task, we used the PORTAGE system, a state-of-the-art statistical phrase-based machine translation system developed at the National Research Council of Canada (NRC).1 A general description of PORTAGE can be found in (Sadat et al. , 2005). 
5.1 Portage We use an off-the-shelf phrase-based SMT system, Portage (Sadat et al. , 2005). 
Portage is a phrase-based, statistical machine translation system, developed at the National Research Council of Canada (NRC) (Sadat et al. , 510 2005). 
2 Our Approach Before going into details of our approach, an overview of Portage (Sadat et al, 2005), the machine translation system that we used for our experiments and some of its properties should be provided. 
