The 5th through 7th papers (Inui and Okumura, 2005; Calhoun et al. , 2005; Wilson and Wiebe, 2005) investigate some additional types of annotation that were not part of the distributed version of Pie in the Sky, but which could be added in principle.


However, when we analyzed the data, we found that more than half of the causal adjuncts contain explicit cues such as because. Since causes are reported to be expressed by a wide variety of linguistic phenomena, not just explicit cues (Inui and Okumura, 2005), further verification is needed before SRL can be safely used for why-QA.


Such patterns include typical cue phrases and POS-tag sequences related to causality, such as because ofandby reasonof. However,as notedin (InuiandOkumura, 2005), causes are expressed in various forms, and it is difficult to cover all such expressions by hand.


