P09-1010:1	30:228	2 Related Work Grounded Language Acquisition Our work fits into a broader class of approaches that aim to learn language from a situated context (Mooney, 2008a; Mooney, 2008b; Fleischman and Roy, 2005; Yu and Ballard, 2004; Siskind, 2001; Oates, 2001).
---------------------------------------------------
N07-2010:2	14:98	The framework for the current model is derived from previous work on computational models of verb learning (Fleischman & Roy, 2005).
---------------------------------------------------
