5.2 Gene Name Annotation and Normalization For the annotation of gene names and their normalization, we use a dictionary-based approach similar to (Cohen, 2005).


For gene NER, various scoring methods have been favored (Crim et al. , 2005; Cohen et al. , 2003; Wellner et al. , 2005).


Several approaches have been proposed for gene normalization, including classification techniques (Crim et al. , 2005; McDonald et al. , 2004), rule-based systems (Hanisch et al. , 2005), text matching with dictionaries (Cohen, 2005), and combinations of these approaches.


Extracting gene synonyms automatically from online databases has several benefits (Cohen, 2005).


