Some approaches simply report that a relation exists between two proteins but do not determine which relation holds (Bunescu et al. , 2005; Marcotte et al. , 2001; Ramani et al. , 2005), while most others start with a list of interaction verbs and label only those sentences that contain these trigger words (Blaschke and Valencia, 2002; Blaschke et al. , 1999; Rindflesch et al. , 1999; Thomas et al. , 2000; Sekimizu et al. , 1998; Ahmed et al. , 2005; Phuong et al. , 2003; Pustejovsky et al. , 2002).


Some systems use link grammars in conjunction with trigger verbs instead of templates (Ahmed et al. , 2005; Phuong et al. , 2003).


