Freitag (2005) uses a mutual information derived measure to learn the syntactic similarity between words and clusters them. 
Unsupervised approaches have achieved considerable success for English and many European languages (e.g. Goldsmith (2001), Schone and Jurafsky (2001), Freitag (2005)). 
This group is the only one to evaluate against CELEX (Schone and Jurafsky, 2000; Schone and Jurafsky, 2001; Freitag, 2005). 
(Freitag 2005) constructs a morphological automaton, where nodes are clustered word types and arcs are suffixation rules. 
Admittedly, several unsupervised morphological induction methodologies have been proposed, e.g., the recent approach in Freitag (2005). 
