Stroppa and Yvon (2005) applied analogical learning to several morphological tasks also involving analogies on words. 
This is the selector used as a default in several studies on analogical learning (Lepage and Denoual, 2005; Stroppa and Yvon, 2005). 
Stroppa and Yvon (2005) applied analogical learning to several morphological tasks also involving analogies on words. 
Also, we plan comparisons to the work of Stroppa and Yvon (2005) and Damper and Eastmond (1997) on sequence-global analogy-based models for morpho-phonological processing, since the main difference between this related work and ours is that both alternatives are based on working units of variable width, rather than our fixedwidth n-grams, and also their analogical reasoning is based on interestingly different principles than our k-nearest neighbor classification rule, such as the use of analogical proportions by Stroppa and Yvon (2005). 
formal analogies on words (Lepage, 1998; Stroppa and Yvon, 2005). 
