N09-2057:1	8:86	For languages with less rigid word order, LM-based approaches have been shown to perform poorly (e.g., Marsi & Krahmer (2005) for Dutch), and methods relying on a range of linguistic features have been successfully applied instead (see Uchimoto et al.
---------------------------------------------------
W07-1429:2	8:169	Sentence Compression takes an important place for Natural Language Processing (NLP) tasks where specific constraints must be satisfied, such as length in summarization (Barzilay & Lee, 2002; Knight & Marcu, 2002; Shinyama et al. , 2002; Barzilay & Lee, 2003; Le Nguyen & Ho, 2004; Unno et al. , 2006), style in text simplification (Marsi & Krahmer, 2005) or sentence simplification for subtitling (Daelemans et al. , 2004).
---------------------------------------------------
W07-1429:3	16:169	2 Related Work Two different approaches have been proposed for Sentence Compression: purely statistical methodologies (Barzilay & Lee, 2003; Le Nguyen & Ho, 2004) and hybrid linguistic/statistic methodologies (Knight & Marcu, 2002; Shinyama et al. , 2002; Daelemans et al. , 2004; Marsi & Krahmer, 2005; Unno et al. , 2006).
---------------------------------------------------
D08-1019:4	200:217	Our method can also be applied to non-trivial sentence compression, whereas the baseline and similar methods, such as Marsi & Krahmer (2005), would then boil down to a few very general pruning rules.
---------------------------------------------------
D08-1019:5	88:217	We prefer this very simple method to bottom-up ones (Barzilay & McKeown, 2005; Marsi & Krahmer, 2005) for two main reasons.
---------------------------------------------------
D08-1019:6	43:217	Marsi & Krahmer (2005) extend the approach of Barzilay & McKeown to do not only intersection but also union fusion.
---------------------------------------------------
P09-1053:7	9:248	For natural language engineers, the problem bears on information management systems like abstractive summarizers that must measure semantic overlap between sentences (Barzilay and Lee, 2003), question answering modules (Marsi and Krahmer, 2005) and machine translation (Callison-Burch et al., 2006).
---------------------------------------------------
P07-1041:8	276:325	Marsi, E. & E. Krahmer (2005).
---------------------------------------------------
P07-1041:9	9:325	E.g., in text-to-text generation (Barzilay & McKeown, 2005; Marsi & Krahmer, 2005; Wan et al. , 2005), new sentences are fused from dependency structures of input sentences.
---------------------------------------------------
P08-2049:10	19:99	Marsi and Krahmer (2005) propose an algorithm which is capable of producing both fusion types.
---------------------------------------------------
P08-2049:11	17:99	Marsi and Krahmer (2005) refer to this latter strategy as union fusion (as opposed to intersection fusion, as in (3)).
---------------------------------------------------
