Some additional considerations are taken into account for efficiency reasons, see (Vilar and Vidal, 2005) for details.


95 2 The MAR We provide here a brief description of the model, a more detailed presentation can be found in (Vilar and Vidal, 2005).


A detailed presentation can be found in (Vilar and Vidal, 2005).


Vilar and Vidal (2005) used ITG-like dynamic programming to drive both training and alignment for their recursive translation model, but they employed a conditional model that did not maintain a phrasal lexicon.


