A shared task on word alignment was organized as part of the ACL 2005 Workshop on Building and Using Parallel Texts (Martin et al. , 2005). 
The second data set is the Romanian-English parallel corpus from the 2005 ACL shared task (Martin et al. , 2005). 
2 Related Work A shared task on word alignment was organized as part of the ACL 2005 Workshop on Building and Using Parallel Texts (Martin et al. , 2005). 
The Romanian results are close to the best reported result of 26.10 from the ACL shared task (Martin et al. , 2005). 
At the Shared Task on Word Alignment organized by the ACL2005 Workshop on Building and Using Parallel Corpora: Data-driven Machine Translation and Beyond (Martin, et al. 2005), we participated (on the Romanian-English track) with the two aligners and the combined one (COWAL). 
