2.3 Predicate-Argument Recognition Algorithm (PARA) Lin & Smith (2005; 2006) describe a tree-based predicate-argument recognition algorithm (PARA).


As a special case, Lin and Smith (2005) used the GT-PARA analyzer for converting parse trees into a flat representation of all predicates including argument boundaries.


Finally, Lin and Smith (2005) presented a proposal radically different from the rest, with very light learning components.


