Although developed independently, the same division between alignment and classification has also been proposed by Marsi and Krahmer (2005), whose textual system is developed and evaluated on parallel translations into Dutch.


3 The NatLog System Our natural logic system, dubbed the NatLog system, has a three-stage architecture similar to those in (Marsi and Krahmer, 2005; MacCartney et al. , 2006), comprising (1) linguistic pre-preprocessing, (2) alignment, and (3) entailment classification.


3 The NatLog system Our implementation of natural logic, the NatLog system, uses a multi-stage architecture like those of (Marsi and Krahmer, 2005; MacCartney et al., 2006), comprising (1) linguistic analysis, (2) alignment, (3) lexical entailment classification, (4) entailment projection, and (5) entailment composition.


Marsi and Krahmer (2005) and MacCartney et al.


