We are proposing a machine learning approach which depends on a training on a collection of manually made questions (Hoshino and Nakagawa, 2005).


This demo presents an novel approach of question generation using machine learning we have introduced in (Hoshino and Nakagawa, 2005).


Most recently, Hoshino and Nakagawa (2005) established a real-time system which automatically generates vocabulary questions by utilizing machine learning techniques.


