In the one domain in which we have a reasonable amount of training data (about 9300 utterances), we experimented with a PCFG using trained probabilities with the Collins algorithm, but were not able to improve on the hand-tuned preferences in overall performance (Elsner et al. , 2005).


To achieve parsing ef ciency, TRIPS uses a bestrst beam search algorithm based on the scores from a parse selection model (Dzikovska et al. , 2005; Elsner et al. , 2005).


