1 Introduction A small number of data sets for evaluating the performance of biomedical language processing (BLP) systems on a small number of task types have been made publicly available by their creators (Blaschke et al. 19991, Craven and Kumlein 19992, Pustejovsky et al. 20023, Franzen et al. 20024, Collier et al. 19995, Tanabe et al. 20056).


Such corpora have made it possible for standardized evaluations such as Task 1A of the first BioCreative Workshop (Yeh et al. , 2005).


34 standard knowledge sources like the UMLS (Lindberg et al. , 1993), the Gene Ontology (GO) (The Gene Ontology Consortium, 2000), Entrez Gene (Maglott et al. , 2005), and GENIA, as well as from the World Wide Web.


Advances in the area of gene and protein named entity recognition (NER) have been accelerated by freely available tagged corpora (Kim et al. , 2003, Cohen et al. , 2005, Smith et al. , 2005, Tanabe et al. , 2005).


