The evaluation 888 presented here is thus much more extensive than our previous one (Cimiano and Wenderoth, 2005), in which only 7 words were used.


Our approach directly builds on our previous work (Cimiano and Wenderoth, 2005) an adheres to the principled idea of learning ranked qualia structures.


5.4 A posteriori Evaluation In order to check whether the automatically learned qualia structures are reasonable from an intuitive point of view, we also performed an a posteriori 893 evaluation in the lines of (Cimiano and Wenderoth, 2005).


