The full system can be extended in a variety of ways  for example, by pruning PoS tags but allowing multiple tag possibilities per word as input to the parser, by incorporating lexical subcategorization into parse selection, by computing GR weights based on the proportion and probability of the n-best analyses yielding them, and so forth  broadly trading accuracy and greater domaindependence against speed and reduced sensitivity to domain-specific lexical behaviour (Briscoe and Carroll, 2002; Carroll and Briscoe, 2002; Watson et al. , 2005; Watson, 2006).


corresponding normalized inside-outside weight for each node (Watson et al. , 2005).


A weighted set of GRs from the parse forest is now computed efficiently using a variant of the inside-outside algorithm (Watson et al. , 2005).


