An example in the context of wide coverage unification-based parsing is the beam thresholding technique employed in the Enju HPSG parser for English (Tsuruoka et al., 2004; Ninomiya et al., 2005). 
time (%) (%) (%) (%) (%) (%) (ms) Miyao and Tsujii (2005)s model 84.96 84.25 84.60 89.55 88.80 89.17 674 Ninomiya et al. 
4 Experiments 4.1 Implementation We implemented the iterative parsing algorithm (Ninomiya et al. , 2005) for the probabilistic HPSG models. 
time (%) (%) (%) (%) (%) (%) (ms) Miyao and Tsujii (2005)s model 84.96 84.25 84.60 89.55 88.80 89.17 674 Ninomiya et al. 
7.3 Iterative parsing We also tried an iterative parsing strategy, which was successfully used in probabilistic HPSG parsing (Ninomiya et al. , 2005). 
