(3) Since the two streams are conditionally independent given the current state, the extended EM is straightforward, with only small modifications of the standard forward-backward algorithm (Zhao et al. , 2005), for parameter estimation.


Recent investigations along this line includes using word-disambiguation schemes (Carpua and Wu, 2005) and non-overlapping bilingual word-clusters (Wang et al. , 1996; Och, 1999; Zhao et al. , 2005) with particular translation models, which showed various degrees of success.


