diamondmath2diamondmath UNALIGNED CHUNK: This feature represents the number of chunks in one text that are not aligned with a chunk from the other diamondmath3diamondmath LEXICAL ENTAILMENT PROBABILITY: This feature is de ned in (Glickman and Dagan, 2005).


2 UNALIGNED CHUNK: This feature represents the number of chunks in one text that are not aligned with a chunk from the other 3 LEXICAL ENTAILMENT PROBABILITY: Defined as in (Glickman and Dagan, 2005).


Glickman and Dagan (2005) do not use this measure, possibly because the problem of data sparseness makes it useless for long strings.


The context theory can also be adapted to incorporate a measure of lexical overlap between strings, an approach that, although simple, performs comparably to more complex techniques in tasks such as recognising textual entailment (Dagan et al., 2005) 3.2 Lexical Entailment Model Glickman and Dagan (2005) define their own model of entailment and apply it to the task of recognising textual entailment.


