This reflects two facts: First, there is only a small amount of syntactically treebanked data in the MTC, and secondly, as has been discovered for English, one can not assume that discourse units map directly to syntactic units (Dinesh et al, 2005). 
193 Also annotated in the PDTB is the attribution of each discourse relation and of its arguments (Dinesh et al. , 2005; Prasad et al. , 2007). 
(Bies et al. , 2005) discusses possible con icts between named entity analyses and syntactic structure and (Dinesh et al. , 2005) discusses a con ict between discourse structure and syntactic structure. 
The ways in which the arguments of a discourse connective may diverge from syntactic units must be characterized for Turkish as is being done for English (Dinesh et al, 2005). 
The proposed scheme is an extension of the core scheme used for annotating attribution in the first release of the PDTB (Dinesh et al. , 2005; PDTB-Group, 2006). 
