This observation suggests that our logical deep parsing should fulfill better than concept spotting the needs of complex application domains such as general purpose tourist information or collaborative planning (Allen J. et al., 2002), or even multi-domain applications (Dzikovska M. et al., 2005).


Whereas many works have investigated a prosodic-based detection (Devillers et al., 2005), word-based approaches remain quite original.


The TRIPS grammar (Dzikovska et al. , 2005) is a wide-coverage uni cation grammar that has been used very successfully in several task-oriented dialogue systems.


To achieve parsing ef ciency, TRIPS uses a bestrst beam search algorithm based on the scores from a parse selection model (Dzikovska et al. , 2005; Elsner et al. , 2005).


