P06-1051:1	7:203	However, previous work (e.g. , (Zaenen et al. , 2005)) suggests that determining whether or not a text T entails a hypothesis H is quite complex even when all the needed information is explicitly asserted.
---------------------------------------------------
W07-1402:2	132:145	The observation that standard logical entailment and textual entailment deviate in certain respects is not surprising and has also been addressed in a discussion initiated by (Zaenen et al. , 2005).
---------------------------------------------------
