Previous work (Barzilay, Elhadad, and McKeown 2002; Lapata 2003; Karamanis and Mellish 2005) has shown that there may be many acceptable orders for a set of informationbearing items, although topically related sentences seem to appear together (Barzilay, Elhadad, and McKeown 2002).


Indeed, several studies have adopted Kendalls  as a performance measure for evaluating the output of information-ordering components both in the context of concept-to-text generation (Karamanis and Mellish 2005; Karamanis 2003) and summarization (Lapata 2003; Barzilay and Lee 2004; Okazaki, Matsuo, and Ishizuka 2004).


However, this information is necessary to estimate reliably the performance of an information ordering approach, as we discuss in Karamanis and Mellish (2005a) in more detail.


The orderings produced by this expert were shown to be very close to those produced by two other archeologists (Karamanis and Mellish 2005b).


Karamanis and Mellish (2005b) conducted an experiment in the MPIRO domain using Lapatas methodology which supplements the work reported in this article.


