I05-5012:1	26:201	Previous preliminary evaluations (Wan et al. , 2005) indicate that the generated sequences contain less fragmented text as measured by an off-the-shelf dependency parser; more fragments would indicate a grammatically problematic sentence.
---------------------------------------------------
I05-5012:2	62:201	We direct the interested reader to our technical paper (Wan et al. , 2005) for full details.
---------------------------------------------------
P07-1041:3	9:325	E.g., in text-to-text generation (Barzilay & McKeown, 2005; Marsi & Krahmer, 2005; Wan et al. , 2005), new sentences are fused from dependency structures of input sentences.
---------------------------------------------------
E09-1017:4	12:229	Considerations of sentence fluency are also key in sentence simplification (Siddharthan, 2003), sentence compression (Jing, 2000; Knight and Marcu, 2002; Clarke and Lapata, 2006; McDonald, 2006; Turner and Charniak, 2005; Galley and McKeown, 2007), text re-generation for summarization (Daume III and Marcu, 2004; Barzilay and McKeown, 2005; Wan et al., 2005) and headline generation (Banko et al., 2000; Zajic et al., 2007; Soricut and Marcu, 2007).
---------------------------------------------------
E09-1017:5	19:229	In contrast, the work of (Wan et al., 2005) and (Mutton et al., 2007) directly sets as a goal the assessment of sentence-level fluency, regardless of content.
---------------------------------------------------
E09-1017:6	20:229	In (Wan et al., 2005) the main premise is that syntactic information from a parser can more robustly capture fluency than language models, giving more direct indications of the degree of ungrammaticality.
---------------------------------------------------
