 Metrics based on syntactic similarities such as the head-word chain metric (HWCM) (Liu and Gildea, 2005). 
Our method follows and substantially extends the earlier work of Liu and Gildea (2005), who use syntactic features and unlabelled dependencies to evaluate MT quality, outperforming BLEU on segment-level correlation with human judgement. 
CP-STM(i)-l This metric corresponds to the STM metric presented by Liu and Gildea (2005). 
For example, Liu and Gildea (2005) developed the Sub-Tree Metric (STM) over constituent parse trees and the Head-Word Chain Metric (HWCM) over dependency parse trees. 
Although evaluated on a different test set, our method also outperforms the correlation with human scores reported in Liu and Gildea (2005). 
