W06-1320:1	29:156	2 Comparison of Systems Combinations of different features (derived for example from linguistic, prosodic information) have been explored in previous studies like (Galley et al. , 2003) and (Kauchak and Chen, 2005).
---------------------------------------------------
W06-2914:2	46:169	(Kauchak and Chen, 2005) employed SVMs using features (derived for instance from information given by the presence of paragraphs, pronouns, numbers) that can be reliably used for topic 102 segmentation of narrative documents.
---------------------------------------------------
W06-2914:3	47:169	Aside from the fact that we consider the TS task on different datasets (not only on narrative documents), our approach is different from the approach proposed by (Kauchak and Chen, 2005) mainly by the data representation we propose and by the fact that we put the emphasis on deriving the thematic structure merely from word distribution, while (Kauchak and Chen, 2005) observed that the block similarities provide little information about the actual segment boundaries on their data and therefore they concentrated on exploiting other features.
---------------------------------------------------
