The first grammar, named GT>N, is a variant of the CFG backbone of a large-coverage LFG grammar for French used in the French LFG parser described in (Boullier and Sagot, 2005).


To achieve this, we applied (Boullier, 2000)s algorithm on the unfolded version of (Villemonte de La Clergerie, 2005)s factorized TAG.


This is indeed what we have achieved with a TAG automatically extracted from (Villemonte de La Clergerie, 2005)s large-coverage factorized French TAG, as we will see in Section 4.


We intend to follow the approach laid out in Crabbe (2005) in order to generate top and bottom feature structures on the nodes of the TAG grammar.


In Proceedings of the 9th European Conference on Speech Communication and Technology (Interspeech 2005), pages 3293 3296, Lisbon, Portugal.</rawString> </citation> <citation valid="true"> <authors> <author>Eiichiro Sumita</author> <author>Fumiaki Sugaya</author> </authors> <title>Word pronunciation disambiguation using the Web</title> <date>2006</date> <booktitle>In Proceedings of the Human Language Technology Conference of the NAACL, Companion Volume: Short Papers</booktitle> <pages>165--168</pages> <location>New York City</location> <contexts> <context>n the study of automatic morphological analysis of Japanese, although a few studies on text-to-speech systems addressed this problem as a problem of pronunciation disambiguation (Nagano et al., 2005; Sumita and Sugaya, 2006).


