N06-2027:1	67:87	This provides a reliable approximation of the learning curve and usability of the system in general (Biller et al. , 2005).
---------------------------------------------------
N06-2027:2	28:87	3 Generating Messages via Semantic Authoring Our approach differs from previous NLG-AAC systems in that, with the model of semantic authoring (Biller et al. , 2005), we intervene during the process of composing the input sequence, and thus can provide early feedback (in the form of display composition and partial text feedback), while preventing the need for parsing a telegraphic sequence.
---------------------------------------------------
N06-2027:3	49:87	Figure 1: A snapshot of the Bliss Lexicon Web Application The core of the processing machinery of the AAC message generation system is based on SAUT (Biller et al. , 2005)  an authoring system for logical forms encoded as conceptual graphs (CG).
---------------------------------------------------
