I08-4001:1	146:153	One way is to merge EBMT and SMT resources, such as Groves and Way (2005).
---------------------------------------------------
W07-0412:2	159:166	These tree pairs might be manually generated, automatically reconstructed from repurposed bilingual dictionaries, or automatically induced from aligned bilingual treebanks (Groves et al. , 2004; Groves and Way, 2005) or even unannotated bilingual corpora (Chiang, 2005).
---------------------------------------------------
