This tech390 nique has since been used for other languages and tasks, e.g. morphological analysis (Yarowsky et al. , 2001), fine-grained POS tagging for Czech (Drabek and Yarowsky, 2005), and tagging and inducing syntactic dependencies for Polish (Ozdowska, 2006).


Drabek and Yarowsky (2005) create a finegrained tagger for Czech and French by enriching the tagset for parallel English text with additional morphological information, which, though not directly attested by the impoverished English morphological system (e.g. number on adjectives), typically does appear in other languages.


