Most related to our approach, Wu (2005) used inversion transduction grammarsa synchronous context-free formalism (Wu, 1997)for this task. 
Wu (2005)s approach relies on the generative framework of Inversion Transduction Grammar (ITG) to measure how similar two sentences arrange their words based on edit distance. 
It has already been applied in this way by Corley & Mihalcea (2005) and Wu (2005). 
Similar stories can also be found in paraphrasing (Quirk et al. , 2004; Wu, 2005) and textual entailment (Harabagiu and Hickl, 2006; Wu, 2005). 
2 Related Work To model the syntactic transformation process, researchers in these fieldsespecially in machine translationhave developed powerful grammatical formalisms and statistical models for representing and learning these tree-to-tree relations (Wu and Wong, 1998; Eisner, 2003; Gildea, 2003; Melamed, 2004; Ding and Palmer, 2005; Quirk et al. , 2005; Galley et al. , 2006; Smith and Eisner, 2006, inter alia). 
