W09-0607:1	29:197	(Varges, 2005) also generate landmark based spatial descriptions using maps from the map task dialogue corpus.
---------------------------------------------------
W06-1405:2	195:212	Varges (2005) suggests that a word similarity-based ranker could align the generation output (i.e. the highest-ranked candidate) with previous utterances in the discourse context, but there is no report yet on an implementation of this proposal.
---------------------------------------------------
W09-0610:3	79:215	Another interesting work related to referring expression generation in spatial environments can be found in (Varges, 2005).
---------------------------------------------------
