There are several available analyzers for Hebrew, including Yona and Wintner (2005) and Segal (2000).


In contrast to English tag sets whose sizes range from 48 to 195, the number of tags for Hebrew, based on all combinations of the morphological attributes (part-of-speech, gender, number, person, tense, status, and the affixes properties2), 1The Knowledge Center for Hebrew processing is developing such corpora: http://mila.cs.technion.ac.il/ 2The list of morphological attributes is described in (Yona and Wintner, 2005).


Recent analyzers provide good performance and documentation of this process (Yona and Wintner, 2005; Segal, 2000).


372 3 Previous Work on Hebrew Processing Morphological analyzers for Hebrew that analyze a surface form in isolation have been proposed by Segal (2000), Yona and Wintner (2005), and recently by the knowledge center for processing Hebrew (Itai et al., 2006).


A morphological analyzer for Hebrew, based on finite-state calculi, already exists (Yona and Wintner 2005), but is very space-inefficient and, therefore, hard to maintain.


