This human involvement has been identified as a bottleneck in the evaluation process, although we have recently developed an automatic scoring metric called POURPRE that correlates well with human judgments (Lin and Demner-Fushman, 2005a).


Previously, we have argued that the vital/okay distinction is a source of instability in the nuggetbased evaluation methodology, especially given the manner in which F-score is calculated (Hildebrandt et al. , 2004; Lin and Demner-Fushman, 2005a).


The nugget-based paradigm has been previously detailed in a number of papers (Voorhees, 2003; Hildebrandt et al. , 2004; Lin and Demner-Fushman, 2005a); here, we present only a short summary.


As an example of this intellectual discourse, the recently-developed POURPRE metric for automatically evaluating answers to complex questions (Lin and Demner-Fushman, 2005a) employs n-gram overlap to compare system responses to reference output, an idea originally implemented in the ROUGE metric for summarization evaluation (Lin and Hovy, 2003).


