As in Mackay and Kondrak (2005) and described above, we use the Forward and Viterbi algorithms in both their regular (normalised for length) and log-odds form to calculate similarity scores for every word pair. 
Image courtesy of Mackay and Kondrak (2005). 
3.4 Pair HMM Mackay and Kondrak (2005) propose to computing similarity between pairs of words with a technique adapted from the eld of bioinformatics. 
Image courtesy of Mackay and Kondrak (2005). 
It should also be noted that Profile HMMs are generalizations of Pair HMMs, which have been used for cognate identification and word similarity (Mackay and Kondrak, 2005) between pairs of words. 
