W07-0720:1	8:94	1 Introduction Based on estimating a joint-probability model between the source and the target languages, Ngram-based SMT has proved to be a very competitive alternatively to phrase-based and other state-of-the-art systems in previous evaluation campaigns, as shown in (Koehn and Monz, 2005; Koehn and Monz, 2006).
---------------------------------------------------
N07-2009:2	50:91	periments on a English-French subset of the Europarl corpus used for the ACL 2005 SMT evaluations (Koehn and Monz, 2005).
---------------------------------------------------
W06-3121:3	67:69	Using only the baseline system, we obtain +0.68 on DEEN, +0.43 on FREN and -0.18 on ESEN difference in BLEU score compared to WPT05s best system (Koehn and Monz, 2005).
---------------------------------------------------
W07-0718:4	10:240	Previous ACL Workshops on Machine Translation were more limited in scope (Koehn and Monz, 2005; Koehn and Monz, 2006).
---------------------------------------------------
W06-3114:5	9:303	The shared task is a follow-up to the one we organized in the previous year, at a similar venue (Koehn and Monz, 2005).
---------------------------------------------------
E06-1006:6	77:157	1http://snowball.tartarus.org 5 Data Our data consists of the Europarl training, development and test definitions for German-English and Finnish-English of the 2005 ACL shared data task (Koehn and Monz, 2005).
---------------------------------------------------
