We refer the reader to (Koller and Striegnitz, 2002; Gardent and Kow, 2005) for more details.


The proposal draws on ideas from (Koller and Striegnitz, 2002; Gardent and Kow, 2005) and aims to determine whether for a given input (a set of TAG elementary trees whose semantics equate the input semantics), syntactic requirements and resources cancel out.


This second measure is based on optimisation known as polarity filtering (Gardent and Kow, 2005).


This toolbox combines existing software and aims at facilitating grammar development, More precisely, this toolbox includes1:  XMG: a grammar compiler which supports the generation of a TAG from a factorised TAG (Crabbe and Duchier, 2004),  LLP2 and DyALog: two chart parsers, one with a friendly user interface (Lopez, 2000) and the other optimised for efficient parsing (Villemonte de la Clergerie, 2005)2  GenI: a chart generator which has been tested on a middle size grammar for French (Gardent and Kow, 2005) 1All these tools are freely available, more information and links at http://trac.loria.fr/semtag.


Both of these algorithms integrate a number of optimisations such as delayed adjunction and polarity filtering (Kow, 2005; Gardent and Kow, 2005).


