(McShane et al. , 2005) discusses the issue of human-aided annotation (human correction of a machine-generated analysis) as it pertains to a single-integrated annotation scheme, similar in many ways to Pie in the Sky, although it has been in existence for a lot longer.


(McShane et al. , 2005; Poesio and Artstein, 2005) (the ninth and tenth papers) both pertain to issues about improving the annotation process.


Other work presented assumes that the integrated framework is the object of the annotation rather than the result of merging annotations (E. W. Hinrichs and S. Kcurrency1ubler and K. Naumann, 2005; McShane et al. , 2005).


