P07-1017:1	157:192	The algorithm is similar to the one described in (Toutanova, 2006).
---------------------------------------------------
P07-1017:2	61:192	The framework suggested here is most closely related to (Suzuki and Toutanova, 2006), which uses a probabilistic model to generate Japanese case markers for English-to-Japanese MT. This work can be viewed as a generalization of (Suzuki and Toutanova, 2006) in that our model generates inflected forms of words, and is not limited to generating a small, closed set of case markers.
---------------------------------------------------
D09-1111:3	213:259	However, this is not unprecedented: discriminatively weighted generative models have been shown to outperform purely discriminative competitors in various NLP classification tasks (Raina et al., 2004; Toutanova, 2006), and remain the standard approach in statistical translation modeling (Och, 2003).
---------------------------------------------------
W09-2211:4	7:28	See Ng and Jordan (2002) and Toutanova (2006) for insightful comparisons of generative and discriminative models.
---------------------------------------------------
W09-2211:5	5:28	Perhaps more importantly, discriminative models have been shown to offer competitive performance on a variety of sequential and structured learning tasks in NLP that are traditionally tackled via generative models , such as letter-to-phoneme conversion (Jiampojamarn et al., 2008), semantic role labeling (Toutanova et al., 2005), syntactic parsing (Taskar et al., 2004), language modeling (Roark et al., 2004), and machine translation (Liang et al., 2006).
---------------------------------------------------
