We measured the impact the translations produced by ANALOG have on a state-of-the-art phrase-based translation engine, which is described in (Patry et al. , 2006).


There has been other phrase-based decoders such as PORTAGE (Sadat et al. 2005), Phramer (Olteanu et al. 2006), the MITLL/AFRL system (Shen et al. 2005), ITC-irst (Bertoldi et al. 2004), Ramses/Mood (Patry et al. 2006) to name but a few.


103 ID Participant cmu Carnegie Mellon University, USA (Zollmann and Venugopal, 2006) lcc Language Computer Corporation, USA (Olteanu et al. , 2006b) ms Microsoft, USA (Menezes et al. , 2006) nrc National Research Council, Canada (Johnson et al. , 2006) ntt Nippon Telegraph and Telephone, Japan (Watanabe et al. , 2006) rali RALI, University of Montreal, Canada (Patry et al. , 2006) systran Systran, France uedin-birch University of Edinburgh, UK  Alexandra Birch (Birch et al. , 2006) uedin-phi University of Edinburgh, UK  Philipp Koehn (Birch et al. , 2006) upc-jg University of Catalonia, Spain  Jesus Gimenez (Gimenez and M`arquez, 2006) upc-jmc University of Catalonia, Spain  Josep Maria Crego (Crego et al. , 2006) upc-mr University of Catalonia, Spain  Marta Ruiz Costa-juss`a (Costa-juss`a et al. , 2006) upv University of Valencia, Spain (Sanchez and Bened, 2006) utd University of Texas at Dallas, USA (Olteanu et al. , 2006a) Figure 2: Participants in the shared task.


