W09-1705:1	87:233	The clustering method employed is Chinese Whispers (CW) (Biemann, 2006).
---------------------------------------------------
P07-3015:2	79:170	We use ChineseWhispers (Biemann, 2006), a special case of MCL that performs the iteration in a more aggressive way, with an optimized linear complexity with the number of graph edges.
---------------------------------------------------
P06-3002:3	58:172	For assigning classes, we use the Chinese Whispers (CW) graph-clustering algorithm, which has been proven useful in NLP applications as described in (Biemann 2006).
---------------------------------------------------
P06-3002:4	55:172	(van Dongen, 2000; Biemann 2006), find the number of clusters automatically 1.
---------------------------------------------------
P09-2017:5	57:127	Graph clustering uses Chinese Whispers2 (Biemann, 2006) to cluster the graph.
---------------------------------------------------
N07-3010:6	69:83	More detailed results are reported in Biemann (2006a).
---------------------------------------------------
N07-3010:7	61:83	In Biemann (2006b), the tagger output was directly compared to supervised taggers for English, German and Finnish via information-theoretic measures.
---------------------------------------------------
N07-3010:8	49:83	The system presented in Biemann (2006b) uses CW clustering on graphs constructed by distributional similarity to induce a lexicon of supposedly non-ambiguous words w.r.t. POS by selecting only safe bets and excluding questionable cases from the lexicon.
---------------------------------------------------
N07-3010:9	35:83	In Biemann and Teresniak (2005) and more detailed in Biemann (2006a), the Chinese Whispers (CW) Graph Clustering algorithm is described, which is a randomized algorithm with edge-linear run-time.
---------------------------------------------------
