First, based on the classification of 300 English adjectives presented in (Amoia and Gardent, 2006), which identifies 17 different adjectival subclasses for the four main classes proposed by (Kamp, 1975; Kamp and Partee, 1995), we have built a test suite of about 150 examples in the following way.


(6) |= something is a book |= x.[book(x)] (6) |= something is about gastronomy |= xea.[about(x,ea)  gastronomy(ea)] (6) negationslash|= something is a book and a gastronomy negationslash|= x[book(x)  gastronomy(x)] (6) negationslash|= something is gastronomical negationslash|= x[gastronomical(x)] As shown in (Amoia and Gardent, 2006), subsective adjectives can be further divided into at least four classes.


We then show that the proposed semantics correctly predicts the inferential patterns observed to hold of the various adjective subclasses identified in the literature (Chierchia and Connell-Ginet, 1990; Kamp, 1975; Kamp and Partee, 1995; Amoia and Gardent, 2006).


First, previous work (Amoia and Gardent, 2006) has shown that the classification presented here can be further detailed and even finer-grained classes identified thereby permitting the creation of syntactically and semantically homogeneous adjectival 191 classes.


2 Inferential patterns and adjective classes In the literature (Chierchia and Connell-Ginet, 1990; Kamp, 1975; Kamp and Partee, 1995; Amoia and 185 Gardent, 2006), adjectives are usually divided into four main classes namely, intersective, subsective, privative and plain non subsective depending on whether or not the [Adj N]AP phrase entails the properties expressed by the noun and/or the adjective.


