(Moschitti et al. , 2006a) and (Moschitti et al. , 2006b) defined several classes of structured features that were successfully employed with tree kernels for the different stages of an SRL process.


This choice is justified by previous studies (Moschitti et al. , 2006b) showing that the accuracy of classification is higher for lower nodes;  if only two nodes are involved, i. e. they dominate each other, then keep the one with the highest classification score.


The solution of a monolithic boundary classifier that we previously employed (Moschitti et al. , 2006b) is noticeably more accurate though much less efficient, especially for training.


