In experiments on other language pairs reported elsewhere (Johnson et al. 2006), we applied a heuristic: DT training and decoding involved source sentences with 60 or fewer tokens, while longer sentences were handled with the distortion penalty.


We plan to implement an alignment algorithm with smoothed phrase tables (Johnson et al. 2006) to achieve segment alignment on 100% of the training data.


103 ID Participant cmu Carnegie Mellon University, USA (Zollmann and Venugopal, 2006) lcc Language Computer Corporation, USA (Olteanu et al. , 2006b) ms Microsoft, USA (Menezes et al. , 2006) nrc National Research Council, Canada (Johnson et al. , 2006) ntt Nippon Telegraph and Telephone, Japan (Watanabe et al. , 2006) rali RALI, University of Montreal, Canada (Patry et al. , 2006) systran Systran, France uedin-birch University of Edinburgh, UK  Alexandra Birch (Birch et al. , 2006) uedin-phi University of Edinburgh, UK  Philipp Koehn (Birch et al. , 2006) upc-jg University of Catalonia, Spain  Jesus Gimenez (Gimenez and M`arquez, 2006) upc-jmc University of Catalonia, Spain  Josep Maria Crego (Crego et al. , 2006) upc-mr University of Catalonia, Spain  Marta Ruiz Costa-juss`a (Costa-juss`a et al. , 2006) upv University of Valencia, Spain (Sanchez and Bened, 2006) utd University of Texas at Dallas, USA (Olteanu et al. , 2006a) Figure 2: Participants in the shared task.


We provide a basic description of this system here; for more details see (Johnson et al. , 2006).


Note that we did not use the decision-treebased distortion models described in (Johnson et al. , 2006) here because they did not improve translation quality.


