Stevenson and Greenwood (2006) showed that the choice of pattern model has important implications for IE algorithms including significant differences between the various models in terms of their ability to identify information of interest in text. 
The rule representation models for automatic or unsupervised pattern rule extraction discussed by 586 Stevenson and Greenwood (2006) do not account for these considerations. 
Stevenson and Greenwood (2006) compared the four pattern models described in Section 2 in terms of their complexity and ability to represent relations found in text. 
In the context of pattern extraction, there exist many approaches as summarized in (Stevenson and Greenwood, 2006). 
Stevenson and Greenwood (2006) also analysed the representational power of each model by measuring how many of the relations found in a standard IE corpus they are expressive enough to represent. 
