More sophisticated methods have been proposed, including bidirectional translation (Wang and Oard, 2006) and use of more than one translation candidate per query term (Pirkola et al., 2003).


Reports advocating the use of religious texts for general purpose CLIR may have been overly optimistic (Chew et al., 2006).


However, recent work (Resnik et al. 1999, Chew et al. 2006) has challenged this idea.


