As a result, most work on search has focused on non-optimal methods, such as beam search or pruning based on approximate models (Collins, 1999), though in certain cases admissible heuristics are known (Och and Ney, 2000; Zhang and Gildea, 2006).


Zhang and Gildea (2006) offer a different heuristic for A parsing of ITG grammars that provides a forward estimate of the cost of aligning the unparsed words in both sentences.


Given such a model, both our optimization heuristic and the lexical heuristic of Zhang and Gildea (2006) can be computed independently.


This heuristic function was one of the admissible heuristics used by Zhang and Gildea (2006).


Zhang and Gildea (2006) describe A* for ITG and develop admissible heuristics for both alignment and decoding.


