Let?s start with the typical examples, which are similar to those used in Crain (1991), MacWhinney (2005), Clark and Eyraud (2006) and many others: (8) The man is hungry If we turn sentence (8) into a (polar) interrogative, the auxiliary is is fronted, resulting in sentence (9).


The major difference between our model and other computational learning models (such as Klein and Manning 2005 or Clark and Eyraud 2006) is that we start with trees.


Our approach is more congenial to Clark and Eyraud (2006) who show that by distributional analysis in the vein of Harris (1954) auxiliary fronting can be correctly predicted.


