(2006) are six and Schiehlen and Spranger (2006) even eight ranks higher for Dutch than overall, while Riedel et al.


 Allow during parsing under certain conditions, e.g. for tokens with certain properties (Riedel et al. , 2006; Bick, 2006) or if no alternative projective arc has a score above the threshold 157 (Bick, 2006) or if the classifier chooses a special action (Attardi, 2006) or the parser predicts a trace (Schiehlen and Spranger, 2006).


(2006) 64.2 51.1 Schiehlen and Spranger (2006) 61.6 49.8 Dreyer,Smith,and Smith (2006) 60.5 46.1 Liu et al.


