Current state of art in metaphor detection therefore tends to be localistic  the distributional profile of the target word in its immediate grammatical or collocational context in a background corpus or a database like WordNet is used to determine metaphoricity (Mason, 2004; Krishnakumaran and Zhu, 2007; Birke and Sarkar, 2006; Gedigian et al., 2006; Fass, 1991).


It complements the traditionally localistic outlook on metaphors that is based on the observation that a metaphorically used item creates a local incongruity because there is a violation of a selectional restrictions between verbs and their arguments (Fass, 1991; Mason, 2004; Gedigian et al., 2006; Birke and Sarkar, 2006) or in the adjective-noun pairs (Krishnakumaran and Zhu, 2007).


Our method is different from automated work on metaphor recognition such as (Mason, 2004) and (Gedigian et al. , 2006) in that it includes nouns as parts of speech.


We will also investigate the use or adaptation of other researchers automated detection/mining techniques (e.g. Birke and Sarkar, 2006; Gedigian et al., 2006).


