This technique can be used along with annealing or quadratic regularization and can achieve additional accuracy gains, which we report elsewhere (Dreyer et al. , 2006).


Stepwise approaches can use an explicit probability model over next steps, e.g. a generative one (Eisner, 1996; Dreyer et al. , 2006), or train a machine learner to predict those.


(2006) 64.2 51.1 Schiehlen and Spranger (2006) 61.6 49.8 Dreyer,Smith,and Smith (2006) 60.5 46.1 Liu et al.


