The best system (Corston-Oliver & Aue, 2006), a variant of the MST algorithm, obtained 89.54 UAS, while the second system (Nivre, 2006) obtained 89.50; cf.


Bick (2006) used the lowercased FORM if the LEMMA is not available, Corston-Oliver and Aue (2006) a prefix and Attardi (2006) a stem derived by a rule-based system for Danish, German and Swedish.


Within the first approach, each dependency can be labeled independently (Corston-Oliver and Aue, 2006) or a 29Thanks to Joakim Nivre for explaining this.


(2006) 75.8 65.7 Johansson and Nugues (2006) 73.6 63.4 McDonald,Lerman,and Pereira (2006) 74.7 63.2 Corston-Oliver and Aue (2006) 73.1 61.7 Cheng,Asahara,and Matsumoto (2006) 74.5 61.2 Chang,Do,and Roth (2006) 73.2 60.5 Y uret (2006) 71.5 60.3 Riedel,C akc,and Meza-Ruiz (2006) 74.1 58.6 Carreras,Surdeanu,and Marquez (2006) 70.1 58.1 Wu,Lee,and Yang (2006) 69.3 55.1 Shimizu (2006) 68.8 54.2 Bick (2006) 65.5 53.9 Canisius et al.


