1 Introduction Over the past several years, a significant consensus has emerged over the definition of the realisation task, through the development of realisers such as REALPRO (Lavoie and Rambow, 1997), ALETHGEN (Coch, 1996), KPML (Bateman, 1997), FUF/SURGE (Elhadad and Robin, 1996), HALOGEN (Langkilde, 2000), YAG (McRoy et al., 2000), and OPENCCG (White, 2006).


Additionally, to realize a wide range of paraphrases, OpenCCG implements an algorithm for efficiently generating from disjunctive logical forms (White, 2006a).


OpenCCG implements a symbolic-statistical chartrealizationalgorithm(Kay, 1996; Carrolletal., 1999; White, 2006b) combining (1) a theoretically groundedapproachtosyntaxandsemanticcomposition with (2) factored language models (Bilmes and Kirchhoff, 2003) for making choices among the options left open by the grammar.


These graphs have been suggested as representations for discourse structure, and have their own underlying semantics (White, 2006b).


Such disjunctive LFs can be efficiently realized using the OpenCCG realizer (White, 2004; White, 2006b; White, 2006a).


