5 Random walks The computational side of the method is based on the estimation of the proximity between words represented in a lexical graph (Gaume et al., 2002; Gaume et al., 2005; Muller et al., 2006).


the representation of the lexicon as a graph and its exploration through random walks, along the line of (Gaume et al., 2002; Gaume et al., 2005; Muller et al., 2006), and 2.


In the approaches based on monolingual dictionaries, the similarities of denitions of lexical items are important clues for identifying synonyms (Blondel et al., 2004; Muller et al., 2006).


Graph representations for word similarity have also been proposed by several researchers (Jannink and Wiederhold, 1999; Galley and McKeown, 2003; Muller et al., 2006).


