We have found as have (Aqeel et al. , 2006) and (Zobel and Dart, 1996) that it is better to encode all letters, rather than only the rst four characters; for brevity, we show only the results for coding all characters, under the label Soutex . 5.3 Arabic Editex Based on groups identi ed in Table 4, we have modi ed the Editex algorithm of Zobel and Dart (1996).


2.1 Foreign Words From an information retrieval (IR) perspective, foreign words in Arabic can be classi ed into two general categories: translated and transliterated (Nwesri et al. , 2006).


(2005; 2006), and Han et al.


Nwesri et al.(2006) propose a method for identifying foreign words in Arabic text.


