I08-1050:1	38:142	Various classifiers for text categorization, Nave Bayesian Model (NBM) (Teufel and Moens, 2002; Ruch et al., 2007), Hidden Markov Model (HMM) (Wu et al., 2006; Lin et al., 2006), and Support Vector Machines (SVM) (McKnight and Arinivasan, 2003; Shimbo et al., 2003; Ito et al., 2004; Yamamoto and Takagi, 2005) were applied.
---------------------------------------------------
I08-1050:2	58:142	(2006) HMM B O M R C 80.54% precision Lin et al.
---------------------------------------------------
J07-1005:3	163:684	As will be described herein, the population, problem, and the intervention extractors are based largely on recognition of semantic types and a few manually constructed rules; the outcome extrac70 Demner-Fushman and Lin Answering Clinical Questions tor, in contrast, is implemented as an ensemble of classifiers trained using supervised machine learning techniques (Demner-Fushman et al. 2006).
---------------------------------------------------
J07-1005:4	624:684	For example, McKnight and Srinivasan (2003) describe a machine learning approach to automatically label sentences as belonging to introduction, methods, results, or conclusion using structured abstracts as training data (see also Lin et al. 2006).
---------------------------------------------------
J07-1005:5	162:684	The extraction of each PICO element relies to a different extent on an annotated corpus of MEDLINE abstracts, created through an effort led by the first author at the National Library of Medicine (Demner-Fushman et al. 2006).
---------------------------------------------------
