Proposed features for the binary classification of tokens include both features similar to those used in (Hacioglu, 2004; Tsai et al., 2006; Ahn, 2006) and novel ones.


The most similar work to that describe in this paper is detailed in (Ahn, 2006), who treats the task of finding all event triggers (used to identify each event) as a word classification task where the task is to classify every term in a document with a label defined by 34 classes.


Almost all the current event extraction systems focus on processing single documents and, except for coreference resolution, operate a sentence at a time (Grishman et al., 2005; Ahn, 2006; Hardy et al., 2006).


Various supervised learning approaches  1  http://www.nist.gov/speech/tests/ace/ have been explored for ACE multi-lingual event extraction (e.g. Grishman et al., 2005; Ahn, 2006; Hardy et al., 2006; Tan et al., 2008; Chen and Ji, 2009).


The ACE program defines the following terminology for event extraction task: z Trigger: the word that most clearly expresses an events occurrence z Argument:  an entity, or a temporal expression or a value that plays a certain role in the event instance z Event mention: a phrase or sentence with a distinguished trigger and participant arguments Some English event extraction systems based on supervised learning have been reported by researchers (Ahn, 2006; Ji and Grishman, 2008).


