In recent years, with the advent of the TimeML markup language (Pustejovsky et al., 2003) and the creation of the TimeBank resource (Pustejovsky et al., 2003) interest has focussed on the application of a variety of automatic techniques to this task (Boguraev and Ando, 2005; Mani et al., 2006; Bramsen et al., 2006; Chambers et al., 2007; Lee and Katz, 2008).


We employ Integer Linear Programming to address the first factor, drawing from related work in paragraph ordering (Bramsen et al., 2006).


