Based on the work of Johansson and Nugues (2006), Johansson and Nugues (2007) studied global training with an approximated large-margin algorithm. 
For example, Johansson and Nugues (2006) and Yuret (2006) are seven ranks higher for Turkish than overall, while Riedel et al. 
2.4 Beam Search As in our previous parser (Johansson and Nugues, 2006), we used a beam-search extension to Nivres original algorithm (which is greedy in its original formulation). 
To make better use of the training set, we applied the algorithm in both directions as Johansson and Nugues (2006) and Sagae and Lavie (2006) for all languages except Catalan and Hungarian. 
Existing efforts to add search to deterministic parsing include Sagae 569 and Lavie (2006b), which applied best-first search to constituent parsing, and Johansson and Nugues (2006) and Duan et al. 
