The primary source is the syntactic comparison of Nerbonne and Wiersma (2006), which uses a permutation test, explained in Good (1995) and in particular for linguistic purposes in Kessler (2001). 
In fact, even though leaf-ancestor paths should provide finer distinctions than trigrams and thus require more data for detectable significance, the regional corpora presented here were smaller than the Norwegian speakers corpora in Nerbonne and Wiersma (2006) by up to a factor of 10. 
TheprincipaldifferencebetweentheworkofNerbonne and Wiersma (2006) and ours is the use of leaf-ancestor paths. 
A measure of syntactic distance is the obvious next step: Nerbonne and Wiersma (2006) provide one such method. 
Fortunately, the permutation test used by Nerbonne and Wiersma (2006) is alreadydesignedtonormalizetheeffectsofdiffering sentence length when combining POS trigrams into a single vector per region. 
