5.2 Bos and Nissim (2006) In contrast to Jindal and Liu (2006), Bos and Nissims (2006) approach to superlatives is explicitly semantic.


(Bos and Nissim 2006) Bos and Nissims system, called DLA (Deep Linguistic Analysis), uses a wide-coverage parser to produce semantic representations of superlative sentences, which are then exploited to select the comparison set among attributive cases.


1 Introduction Although superlatives are frequently found in natural language, with the exception of recent work by Bos and Nissim (2006) and Jindal and Liu (2006), they have not yet been investigated within a computational framework.


Bos and Nissim (2006) proposes a method to extract some useful items from superlative sentences.


One existing focused study is on comparative and superlative sentences (Jindal and Liu, 2006; Bos and Nissim, 2006; Fiszman et al, 2007; Ganapathibhotla and Liu, 2008).


