7 Symmetric Cross Entropy (SCE) The first measure is purely a letter n-gram based measure similar to the one used by Singh (Singh, 2006b) for language and encoding identification. 
The method for fuzzy string matching is based on the Computational Phonetic Model of Scripts or CPMS (Singh, 2006b), which models scripts (specifically Indic scripts) in terms of phonetic (articulatory) and orthographic features. 
The language-encoding identification tool is based on byte based n-gram models using a distributional similarity measures (Singh, 2006a). 
For identifying cognates, we are using the computational model of scripts or CPMS (Singh, 2006a). 
Can automatically identify language-encoding of the text using a byte based n-gram modeling (Singh, 2006a). 
