In the current implementation this is achieved by a version of polarity filtering where we associate not only the syntactic categories of root, substitution and foot nodes with a positive or negative value (Gardent and Kow, 2006) but also add the semantic variable associated with these nodes.


Having done this, we show that by integrating discourse-level representations into a syntactic grammar we can extend an optimization technique  polarity filtering (Kow, 2007; Gardent and Kow, 2006)  from syntactic realization to the discourse level.


