Web-based statistics have also had an impact on these wider analysis tasks, including work on interpretation of verb nominalisations (Nicholson and Baldwin, 2006) and NC coordination (Nakov and Hearst, 2005b).


Recent innovations have been to use statistics beyond the Ngram, such as counting the number of web pages where a pair of words w, x participate in a genitive relationship ( ws x ), occur collapsed as a single 820 phrase ( wx ) (Nakov and Hearst, 2005a) or have a de nite article as a left-boundary marker ( the w x ) (Nicholson and Baldwin, 2006).


4 Acquiring MWEs The automatic acquisition of specific types of MWE has attracted much interest (Pearce, 2002; Baldwin and Villavicencio, 2002; Evert and Krenn, 2005; Villavicencio, 2005; van der 1035 Beek, 2005; Nicholson and Baldwin, 2006).


Nicholson and Baldwin (2006) investigated the prediction of the inherent semanticrelation of agiven compound nominalization using as statistical measure the confidence interval.


