The reason seems to be because Espresso and the von Neumann kernels use pointwise mutual information as a weighting factor so that the principal eigenvector of A may not always represent the most frequent sense.7 We also show the results of previous graph-based methods (Agirre et al., 2006), based on HyperLex (Veronis, 2004) and PageRank (Brin and Page, 1998). 
For further information on how these measures are calculated refer to (Agirre et al. , 2006a; Agirre et al. , 2006b). 
This process is thoroughly explained in (Agirre et al. , 2006b). 
HyperLex (Veronis, 2004) and the adaptation of PageRank (Brin and Page, 1998) in (Agirre et al. , 2006) have been shown to outperform the most frequent sense (MFS) baseline in terms of supervised recall, but they still fall short of supervised WSD systems. 
Following the example in (Agirre et al. , 2006), only nouns are kept and lemmatised. 
