c2007 Association for Computational Linguistics A Constraint Satisfaction Approach to Dependency Parsing Sander Canisius ILK / Communication and Information Science Tilburg University, P.O. Box 90153, NL-5000 LE Tilburg, The Netherlands S.V.M.Canisius@uvt.nl Erik Tjong Kim Sang ISLA, University of Amsterdam, Kruislaan 403, NL-1098 SJ Amsterdam, The Netherlands erikt@science.uva.nl Abstract We present an adaptation of constraint satisfaction inference (Canisius et al. , 2006b) for predicting dependency trees.


The method is an adaptation of earlier work using constraint satisfaction techniques for predicting sequential outputs (Canisius et al. , 2006b).


