 Always allow non-projective arcs, by not imposing any projectivity constraint (Shimizu, 2006; Canisius et al. , 2006).


(2006) 75.8 65.7 Johansson and Nugues (2006) 73.6 63.4 McDonald,Lerman,and Pereira (2006) 74.7 63.2 Corston-Oliver and Aue (2006) 73.1 61.7 Cheng,Asahara,and Matsumoto (2006) 74.5 61.2 Chang,Do,and Roth (2006) 73.2 60.5 Y uret (2006) 71.5 60.3 Riedel,C akc,and Meza-Ruiz (2006) 74.1 58.6 Carreras,Surdeanu,and Marquez (2006) 70.1 58.1 Wu,Lee,and Yang (2006) 69.3 55.1 Shimizu (2006) 68.8 54.2 Bick (2006) 65.5 53.9 Canisius et al.


