Titov and Henderson (2006) also took this type of approach.


Of these, Roark and Bacchiani (2003) and Titov and Henderson (2006) deal specifically with syntactic parsing.


(2004), Chelba and Acero (2004), Daume and Marcu (2006), and Titov and Henderson (2006).


Concerning the use of kernels for NLP, interesting models and results are described, for example, in (Collins and Duffy, 2002), (Moschitti et al., 2008), (Kudo and Matsumoto, 2003), (Cumby and Roth, 2003), (Shen et al., 2003), (Cancedda et al., 2003), (Culotta and Sorensen, 2004), (Daume III and Marcu, 2004), (Kazama and Torisawa, 2005), (Kudo et al., 2005), (Titov and Henderson, 2006), (Moschitti et al., 2006), (Moschitti and Bejan, 2004) or (Toutanova et al., 2004).


