Several sentiment information retrieval models were proposed in the framework of probabilistic language models by Eguchi and Lavrenko (2006).


Polarity orientation identification has many useful applications, including opinion summarization (Ku et al., 2006) and sentiment retrieval (Eguchi and Lavrenko, 2006).


Eguchi & Lavrenko (2006) propose the use of probabilistic language models for ranking the results not only by sentiment but also by the topic relevancy.


