This procedure was described in some detail elsewhere (Zuidema, 2006b); here I only sketch the basic idea.


Zuidema (2006a) shows that also the estimator (Bod, 2003) uses is biased and inconsistent, and will, even in the limit of in nite data, not correctly identify many possible distributions over trees.


In Zuidema (2006b) we give a qualitative analysis of the subtrees with the highest scores as induced from the ATIS treebank, which include many of its frequent constructions including show me NP, I would like NP, ights from NP to NP.


As initial probabilities we use the subtrees' relative frequencies as described in section 2 (smoothed by Good-Turing -see Bod 1998), though it would also be interesting to see how the model works with other initial parameters, in particular with the usage frequencies proposed by Zuidema (2006).


