In (Tao et al., 2006) a dataset which contains about 600 English NEs and 700 Chinese candidates is used. 
The substitution/insertion/deletion cost for the string alignment algorithm is based on the baseline cost from (Tao et al, 2006). 
We are investigating transliterations among several language pairs, and are extending these methods to Korean, Arabic, Russian and Hindi  see (Tao et al. , 2006). 
NETE mining from comparable corpora using phonetic mappings was proposed in (Tao et al., 2006), but the need for language specific knowledge restricts its applicability across languages. 
Other approaches exploit similarities in aligned bilingual corpora; for example, (Tao et al., 2006) combine two unsupervised methods. 
