Following (Matsuo et al., 2006), we exploit the Newman clustering (Newman, 2004) to partition the graph into such dense subgraphs.


Considerable efforts have been devoted to measure word similarity based on cooccurrence frequency of two words in a window (Church and Hanks, 1989; Turney, 2001; Terra and Clarke, 2003; Matsuo et al., 2006).


Matsuo et al. , (2006a) propose the use of Web hits for the extraction of communities on the Web.


4.4 Named Entity Clustering Measuring semantic similarity between named entities is vital in many applications such as query expansion (Sahami and Heilman, 2006) and community mining (Matsuo et al. , 2006a).


