Fortunately, its memory cost with the six n-gram feature templates remains very close to that of the 2and 4-tag sets with the n-gram feature template sets from (Tsai et al., 2006; Xue, 2003).


7The templates for the 2-tag set, adopted from (Tsai et al., 2006), include C2, C1, C0, C1, C3C1, C2C0, C2C1, C1C0, C1C1 and C0C1.


For the purpose of comparison, the word segmentation performance of our system on Bakeoff-4 data using the 2and 4-tag sets and the best corresponding n-gram feature templates as in (Tsai et al., 2006; Low et al., 2005) are presented in Table 8.7 This comparison reconfirms the conclusion in (Zhao et CityU data sets in any other situation than the Bakeoff.


