The corpus of Vlachos and Gasperin (2006) contains 80 abstracts (600 sentences) annotated with gene names. 
In order to verify the reliability of baseNP annotation, two computational linguists (re)annotated the 600 sentences (6300 tokens) of Vlachos and Gasperin (2006) with baseNPs and heads using the published guidelines. 
In this spirit, we didn?t attempt any of the improvements discussed by Vlachos & Gasperin (2006) because they were based on observations on the behavior of the HMM-based system. 
noisy golden full abstracts abstracts papers abstracts / 16,609 82 5 papers sentences 111,820 600 1,220 tokens 2,923,199 15,703 34,383 gene names 117,279 629 2,057 unique 16,944 326 336 gene names unique non60,943 3,018 4,113 gene tokens Table 1: Statistics of the datasets The gene names in both manually created corpora were annotated using the guidelines presented in Vlachos & Gasperin (2006). 
Naturally, in the live system, an automated NER process is used (Vlachos and Gasperin, 2006). 
