Infrequent rules in one genre may be quite frequent in another (Sekine, 1997) and their frequency may be unrelated to their usefulness for parsing (Foth and Menzel, 2006).


1 Introduction and Motivation When extracting rules from constituency-based treebanks employing flat structures, grammars often limit the set of rules (e.g., Charniak, 1996), due to the large number of rules (Krotov et al., 1998) and leaky rules that can lead to mis-analysis (Foth and Menzel, 2006).


Finally, the texts are parsed with the CDG dependency parser (Foth & Menzel, 2006).


