However, last years top scoring system for Chinese (Riedel et al. , 2006), which did not participate this year, had a score that was more than 3 percentage points higher than the second best system for Chinese.


(2006) are six and Schiehlen and Spranger (2006) even eight ranks higher for Dutch than overall, while Riedel et al.


 Allow during parsing under certain conditions, e.g. for tokens with certain properties (Riedel et al. , 2006; Bick, 2006) or if no alternative projective arc has a score above the threshold 157 (Bick, 2006) or if the classifier chooses a special action (Attardi, 2006) or the parser predicts a trace (Schiehlen and Spranger, 2006).


For example, Johansson and Nugues (2006) and Yuret (2006) are seven ranks higher for Turkish than overall, while Riedel et al.


(2006) 75.8 65.7 Johansson and Nugues (2006) 73.6 63.4 McDonald,Lerman,and Pereira (2006) 74.7 63.2 Corston-Oliver and Aue (2006) 73.1 61.7 Cheng,Asahara,and Matsumoto (2006) 74.5 61.2 Chang,Do,and Roth (2006) 73.2 60.5 Y uret (2006) 71.5 60.3 Riedel,C akc,and Meza-Ruiz (2006) 74.1 58.6 Carreras,Surdeanu,and Marquez (2006) 70.1 58.1 Wu,Lee,and Yang (2006) 69.3 55.1 Shimizu (2006) 68.8 54.2 Bick (2006) 65.5 53.9 Canisius et al.


