(Heeringa et al. , 2006).


Different researchers have argued about the importance of order sensitivity and scaling in using string comparison algorithms (Heeringa et al. , 2006; Ellison and Kirby, 2006).


Like in other disciplines, computational methods are increasingly being combined with other more conventional approaches (Dyen et al. , 1992; Nerbonne and Heeringa, 1997; Kondrak, 2002; Ellison and Kirby, 2006).


1Another possibility is normalization by the length of the longest alignment (Heeringa et al. , 2006).


