P08-1089:1	192:250	To conduct the evaluation, we parsed the Chinese sentences of the corpus with a Chinese dependency parser (Liu et al., 2006).
---------------------------------------------------
J08-3003:2	419:443	(2006) 64.2 51.1 Schiehlen and Spranger (2006) 61.6 49.8 Dreyer,Smith,and Smith (2006) 60.5 46.1 Liu et al.
---------------------------------------------------
J08-3003:3	51:443	Previous work on Turkish (HakkaniT ur,Oazer,and T ur 2002; Oazer 2003; Oazer et al. 2003; Eryigit and Oazer 2006) has represented the morphological structure of Turkish words by splitting them into inectional groups (IGs).
---------------------------------------------------
