A diverse set of 28 features is used in (Jiang and Ng, 2006) for argument classification. 
Jiang and Ng (2006) and Liu and Ng (2007) have tested the hypothesis that methodologies and representations used in PropBank SRL (Pradhan et al., 2005) can be ported to the task of NomBank SRL. 
The J&N column presents the result reported in (Jiang and Ng, 2006) using both baseline and additional features. 
Nominal SRL also typically draws on feature sets that are similar to those for verbs, i.e., comprising mainly syntactic and lexical-semantic information (Liu and Ng, 2007; Jiang and Ng, 2006). 
Following the evaluation methodology used by Jiang and Ng (2006) and Liu and Ng (2007), we obtained sig1The syntactic parse can be based on ground-truth annotation or derived automatically, depending on the evaluation. 
