Machine learning-based word segmentation method is quite similar to the word sequence inference techniques, such as part-of-speech (POS) tagging (Clark et al., 2003; Gimenez and Marquez, 2003), phrase chunking (Lee and Wu, 2007) and word dependency parsing (Wu et al., 2006, 2007). 
In this paper, we used the similar IOB2 representation style (Wu et al. , 2006a) to express the Chinese word structures. 
Machine learning-based word segmentation method is quite similar to the word sequence inference techniques, such as part-of-speech (POS) tagging, phrase chunking (Wu et al. , 2006a) and named entity recognition (Wu et al. , 2006b). 
Now we compare the adopted parsing algorithm in this year to the one we employed last year (Wu et al. , 2006a). 
2.1 Word Sequence Classification Similar to English text chunking (Ramshaw and Marcus, 1995; Wu et al. , 2006a), the word sequence classification model aims to classify each word via encoding its context features. 
