Existing studies (Kim et al, 2006; Zhang and Varadarajan, 2006) used these users votes for training ranking models to assess the quality of reviews, which therefore are subject to these biases. 
Kim et al (2006) used the percentage of helpful votes as the measure of evaluating the quality of reviews in their experiments. 
2 Related Work 2.1 Evaluating Helpfulness of Reviews The problem of evaluating helpfulness of reviews (Kim et al, 2006), also known as learning utility of reviews (Zhang and Varadarajan, 2006), is quite similar to our problem of assessing the quality of reviews. 
(2006) and Kim et al. 
The same argument applies to the automatic assessment of product review usefulness (Kim et al. , 2006c): 125 Stars Label on the website Number star Poor Post 1251 starstar Below Average Post 44 starstarstar Average Post 69 starstarstarstar Above Average Post 183 starstarstarstarstar Excellent Post 421 Table 1: Categories and their usage frequency. 
