6 Future work Besides annotating and using more dialogue data as more people talk to our IQA system, we plan to implement a state-of-the-art topic-shift detection algorithm as proposed in (Yang et al., 2006), training and testing it on our own FU Q data. 
The method of finding follow-up questions (Yang et al., 2006) from TREC context track could be adapted for context detection. 
Therefore, a first task in IQA is to detect whether a FU Q is a topic shift or a topic continuation (Yang et al., 2006). 
Answers is comparable to contexts in fo1The semantic similarity between sentences is calculated as in (Yang et al., 2006). 
Real IQA data yield chal13 lenges for an automatic processing approach (Yang et al., 2006). 
