Our evaluation metric is 11-pt average precision on the score-sorted pair lists (also used by Kondrak and Sherif (2006)).


This is in contrast to previous comparisons which have only demonstrated minor improvements with adaptive over traditional similarity measures (Kondrak and Sherif, 2006).


There is considerable previous work in the area of alignment, most recently summarized by Kondrak and Sherif (2006).


An example of a major work on text based similarity is the paper by Kondrak and Sherif (Kondrak and Sherif, 2006).


Kondrak and Sherif (2006) use phonetic similarity models for cognate word identification.


