The fact that our model defines a probability model over parse trees, unlike the previous state-ofthe-art methods (Nivre et al. , 2006; McDonald et al. , 2006), makes it easier to use this model in applications which require probability estimates, e.g. in language processing pipelines. 
4.1 Base Dependency Parser We used the MSTParser (McDonald et al., 2006), which achieved top results in the CoNLL 2006 (CoNLL-X) shared task, as a base dependency parser. 
A second labeling stage can be applied to get labeled dependency structures as described in (McDonald et al. , 2006). 
(2006), McD = McDonald et al. 
The fact that our model defines a probability model over parse trees, unlike the previous stateof-the-art methods (Nivre et al. , 2006; McDonald et al. , 2006), makes it easier to use this model in applications which require probability estimates, such as in language processing pipelines or for language modeling. 
