Compared to European-language NER, Chinese NER seems to be more difficult (Yu et al., 2006).


In particular, reasonable Chinese NER results were still obtained using Boosting, even though there was no Chinese-specific tuning and the model was only trained on one-third of the provided corpora in SIGHAN bakeoff-3 (Yu et al. , 2006).


Compared to European-language NER, Chinese NER seems to be more difficult (Yu et al. , 2006).


