The system proposed by (Georgescul et al., 2006) is based on support vector machines (SVMs) and is labeled in the table as SVMs.


Then, we use these posterior probabilities as a threshold to identify the boundaries of thematic episodes via support vector classification (Georgescul et al., 2006).


More recent work use techniques from graph theory (Malioutov and Barzilay, 2006) and machine learning (Galley et al., 2003; Georgescul et al., 2006; Purver et al., 2006) in order to find patterns in vocabulary use.


We also reproduce the results reported on in the literature by (Galley et al., 2003) and (Georgescul et al., 2006), when the evaluation of their systems was also done on ICSI data.


