The few token-based approaches include a study by Katz and Giesbrecht (2006), who devise a supervised method in which they compute the meaning vectors for the literal and non-literal usages of a given expression in the training data. 
Much research has addressed the non-compositionality of MWEs as an important property related to their idiomaticity, and has used it in the classification of both MWE types and tokens (Baldwin et al. , 2003; McCarthy et al. , 2003; Katz and Giesbrecht, 2006). 
to those of Katz and Giesbrecht (2006) using this method on their German data (BJBEB1). 
We also compare our unsupervised methods against the supervised method proposed by Katz and Giesbrecht (2006). 
The few token-based approaches include a study by Katz and Giesbrecht (2006), who devise a supervised method in which they compute the meaning vectors for the literal and non-literal usages of a given expression in the training data. 
