In the experiments, we examine our approaches for actual errors which are given by the HPSG parser Enju (Miyao and Tsujii, 2005; Ninomiya et al., 2006). 
(2006)s model 1 87.23 86.47 86.85 90.05 89.27 89.66 129 Ninomiya et al. 
We also compared with a probabilistic model in (Ninomiya et al. , 2006). 
In the experiments, we applied both of our approaches to an HPSG parser Enju (Miyao and Tsujii, 2005; Ninomiya et al., 2006), and then evaluated the obtained error classes. 
(2006)s model 1 87.23 86.47 86.85 90.05 89.27 89.66 129 Ninomiya et al. 
