To align a bilingual training corpus, some take a phonological approach, in which the crafted mapping rules encode the prior linguistic knowledge about the source and target languages directly into the system (Wan and Verspoor, 1998; Meng et al., 2001; Jiang et al., 2007; Xu et al., 2006).


Some recent work (Li et al. , 2006; Xu et al. , 2006) has attempted to introduce preference into a probabilistic framework for selection of Chinese characters in phonetic transliteration.


As a Chinese transliteration can arouse to certain connotations, the choice of Chinese characters becomes a topic of interest (Xu et al. , 2006).


