Originally, this scenario was developed to enhance the access to heterogeneously annotated corpora, as part of the development of a sustainable archive of linguistic resources (Schmidt et al., 2006).


Given a pair of document collections A and B, our goal is not to construct classifiers that can predict if a document was written from the perspective of A or B (Lin et al. , 2006), but to determine if the document collection pair (A,B) convey opposing perspectives.


