1 Introduction Parallel treebanks are increasingly seen as a valuable resource for many different tasks, including machine translation, word alignment, translation studies and contrastive linguistics ( Cmejrek et al. , 2004; Cyrus, 2006; Hansen-Schirra et al. , 2006).


The requirements are also indirectly satisifed by parallel treebanks with a constituent layer and a word alignment, eg (Han et al. , 2002; Cyrus, 2006; Hansen-Schirra et al. , 2006; Samuelsson and Volk, 2006), since it is possible to transform constituent structures into dependency structures  a procedure used in the CoNLL shared tasks in 2006 and 2007 (Buchholz and Marsi, 2006).


Similar projects include Croco (Hansen-Schirra et al. , 2006) which is aimed at building a GermanEnglish parallel treebank for translation studies, LinES an English-Swedish parallel treebank (Ahrenberg, 2007), and the Czech-English parallel dependency treebank built in Prague (Cmejrek et al. , 2005).


