The early designed system (Feng et al., 2006) is used for the MSRA NER open track this year.


3  Chinese NER Using CRFs Model Integrating Multiple Features Besides the text feature(TXT), simplified part-ofspeech (POS) feature, and small-vocabularycharacter-lists (SVCL) feature, which use in the early system (Feng et al., 2006), some new features such as word boundary, adjoining state bigram  observation and early NE output are also combined under the unified CRFs framework.


