In the meantime, the Annotation Compatibility Working Group (Meyers, 2006) began to concentrate its activities on the mutual compatibility of annotation schemata for, e.g., POS tagging, treebanking, role labeling, time annotation, etc. The goal of these initiatives, however, has never been to design an annotation scheme for a complete 2http://www.tei-c.org 3http://dublincore.org 4http://www.w3.org/2001/sw 5http://www.ilc.cnr.it/EAGLES96/ 6http://bioie.ldc.upenn.edu NLP pipeline as needed, e.g., for information extraction or text mining tasks (Hahn and Wermter, 2006).


