Some other researchers have taken a similar line, for example (Hasan et al., 2006), which only uses a parser on the target, and attempts to improve the fluency of the translation produced, and especially (Och et al., 2003) that reports experiments using a large number of syntactic features.


Reranking n-best lists using POS has also been explored by (Hasan et al. , 2006).


This result corresponds to known work in the literature (Kirchhoff and Yang, 2005; Hasan et al. , 2006), when using POS only as a post-processing step during reranking.


