Experimental results from (Feldman and Rosenfeld, 2006) indicate that named entity recognizers can boost the performance of weakly supervised extraction of class instances, but only for a few coarse-grained types such as Person and only if they are simpler to recognize in text (Feldman and Rosenfeld, 2006).


Such methods are naturally much less precise and produce many entityrecognition errors (Feldman and Rosenfeld 2006).


The details of the patterns language and the process of pattern learning are not significant for this paper, and are described fully in (Feldman and Rosenfeld 2006).


We evaluate the methods using SRES (Feldman and Rosenfeld 2006)  a Web RE system, designed to extend and improve KnowItAll (Etzioni, Cafarella et al. 2005).


Since the supervised training stage needs to be run only once, it is a part of the system development, and the complete system remains unsupervised, as demonstrated in (Feldman and Rosenfeld 2006).


