Examples of rule/pattern-based approaches to information extraction are FASTUS (Hobbs et al. , 1997), PALKA (Kim and Moldovan, 1993), LIEP (Huffman, 1996), CRYSTAL (Soderland et al. , 1995), AutoSlog/AutoSlog-TS (Riloff, 1993; Riloff, 1996), RAPIER (Califf and Mooney, 1999), WHISK (Soderland, 1999), ExDisco (Yangarber et al. , 2000), SNOWBALL (Agichtein and Gravano, 2000), (LP)2 (Ciravegna, 2001), subtree patterns (Sudo et al. , 2003), predicate-argument rules (Yakushiji et al. , 2006) and KnowItAll (Popescu et al. , 2004).


