(Belz and Reiter, 2006), and there is a lot of scepticism among NLG researchers regarding automatic evaluation.


The past year has seen a groundswell of interest in comparative evaluation among NLG researchers, the first comparative results are being reported (Belz and Reiter, 2006), and the move towards some form of comparative evaluation seems inevitable.


A specific proposal of a set of tasks can be found elsewhere in this volume (Reiter and Belz, 2006).


