Systems based on Eisner algorithm (Carreras et al., 2006; Carreras, 2007) showed a competitive performance in the syntactic parsing of the English language in some past CoNLL shared tasks. 
These features are borrowed from existing and widely-known systems (Xue and Palmer, 2004; McDonald et al., 2005; Carreras et al., 2006; Surdeanu et al., 2007). 
(2006) as input for the syntactic parsing phase, except for the dynamic features from Carreras et al. 
(2006) and Carreras (2007) achieved state-of-the-art performance for English in the CoNLL-2007 Shared Task (Nivre et al., 2007). 
2.2 Features The first-order features 1(x, h, m) are the exact same implementation as in previous CoNLL system (Carreras et al. , 2006). 
