This framework could be extended to permit paraphrase generation, or to exploit other linguistic annotations, such as representations of semantics (see, e.g., Qiu et al., 2006).


As noted, the most successful work has used edit distance (Zhang and Patrick, 2005) or bag-of-words features to measure sentence similarity, along with shallow syntactic features (Finch et al., 2005; Wan et al., 2006; Corley and Mihalcea, 2005).


To compute a continuous similarity Sim(ta;tb) of tuples ta and tb, we use the similarity measure described in (Qiu et al., 2006), which linearly combines similarities between the semantic roles shared by the two tuples.


Its input is identical to that of CSC  the tuples extracted from relevant news articles and are not excluded from being clustered by CSC in the initialization stage (refer to Section 3)  and employs the same tuple similarity measure (Qiu et al., 2006).


