N07-1026:1	168:191	These synthesized nodes are akin to the dongle nodes (Goldberg and Zhu, 2006).
---------------------------------------------------
N07-1026:2	44:191	In NLP, label propagation has been used for word sense disambiguation (Niu et al. , 2005), document classi cation (Zhu, 2005), sentiment analysis (Goldberg and Zhu, 2006), and relation extraction (Chen et al. , 2006).
---------------------------------------------------
N07-1026:3	123:191	The approach of setting different limits among different kinds of nodes is also used in related work (Goldberg and Zhu, 2006).
---------------------------------------------------
N07-1038:4	33:212	More recent work (Pang and Lee, 2005; Goldberg and Zhu, 2006) has expanded this analysis to the ranking framework where the goal is to assess review polarity on a multi-point scale.
---------------------------------------------------
P09-1028:5	48:191	(Goldberg and Zhu, 2006) adapt semi-supervised graph-based methods for sentiment analysis but do not incorporate lexical prior knowledge in the form of labeled features.
---------------------------------------------------
D09-1017:6	39:229	Specifically, aspect rating as an interesting topic has also been widely studied (Titov and McDonald, 2008a; Snyder and Barzilay, 2007; Goldberg and Zhu, 2006).
---------------------------------------------------
N09-1014:7	68:223	Thus, instead of directly learning a classification function, we learn a regression function similar to (Goldberg and Zhu, 2006)that is then used for ranking the hypotheses.
---------------------------------------------------
N09-1014:8	53:223	In natural language processing, label propagation has been used for document classification (Zhu, 2005), word sense disambiguation (Niu et al., 2005; Alexandrescu and Kirchhoff, 2007), and sentiment categorization (Goldberg and Zhu, 2006).
---------------------------------------------------
W06-1639:9	158:176	Previous sentiment-analysis work in different domains has considered inter-document similarity (Agarwal and Bhattacharyya, 2005; Pang and Lee, 2005; Goldberg and Zhu, 2006) or explicit 333 inter-document references in the form of hyperlinks (Agrawal et al. , 2003).
---------------------------------------------------
W06-1639:10	25:176	A few others incorporate various measures of inter-document similarity between the texts to be labeled (Agarwal and Bhattacharyya, 2005; Pang and Lee, 2005; Goldberg and Zhu, 2006).
---------------------------------------------------
D09-1018:11	32:233	Some of the work is not related to discourse at all (e.g., lexical similarities (Takamura et al., 2007), morphosyntactic similarities (Popescu and Etzioni, 2005) and word-based measures like TFIDF (Goldberg and Zhu, 2006)).
---------------------------------------------------
