Average (standard deviation) for objective metrics in the first problem 6 Related work Discourse structure has been successfully used in non-interactive settings (e.g. understanding specific lexical and prosodic phenomena (Hirschberg and Nakatani, 1996), natural language generation (Hovy, 1993), essay scoring (Higgins et al. , 2004) as well as in interactive settings (e.g. predictive/generative models of postural shifts (Cassell et al. , 2001), generation/interpretation of anaphoric expressions (Allen et al. , 2001), performance modeling (Rotaru and Litman, 2006)).


Discourse Structure Depth/Transition: In prior work we showed that the discourse structure Depth and Transition for each ITSPOKE turn can be automatically annotated (Rotaru and Litman, 2006).


