 NB: We implemented the unsupervised Nave Bayes model described in (Glickman et al., 2006) to estimate the probability that the unknown term entails the RHS in the given context.


1 Introduction The lexical substitution (Glickman et al. , 2006a) can be regarded as a subtask of the lexical entailment, in which for a given word in context the system is asked to select an alternative word that can be replaced in that context preserving the meaning.


Lexical Entailment, and in particular lexical reference (Glickman et al. , 2006b)1, is in turn a subtask of textual entailment, which is formally de ned as a relationship between a coherent text T and a language expression, the hypothesis H. T is said to entail H, denoted by T !H, if the meaning of H can be inferred from the meaning of T (Dagan et al. , 2005; Dagan and Glickman.


In the literature, slight variations of this problem are also referred to as sense matching (Dagan et al. , 2006), lexical reference (Glickman et al. , 2006a) and lexical substitution (Glickman et al. , 2006b).


