Supersense tagging A WordNet-based supersense tagger (Ciaramita and Altun, 2006). 
A detailed description of the features used and the tagger can be found in (Ciaramita and Altun, 2006). 
1http://www.senseval.org 2http://wordnet.princeton.edu 3http://www.wikipedia.org 389 In contrast, some research have been focused on using predefined sets of sense-groupings for learning class-based classifiers for WSD (Segond et al., 1997), (Ciaramita and Johnson, 2003), (Villarejo et al., 2005), (Curran, 2005) and (Ciaramita and Altun, 2006). 
We used Ciaramita and Altuns Super Sense Tagger (Ciaramita and Altun, 2006) to tag the supersenses. 
Columns 13 were predicted using the tagger of Ciaramita and Altun (2006). 
