Recognition-only systems are often based on machine learned classifiers (Hacioglu et al. , 2005; Bethard and Martin, 2006), although some do use finite-state methods (Boguraev and Ando, 2005).


Annotators selected the best paraphrase of and from the following options: CAUSAL and as a result, and as a consequence, and enabled by that NO-REL andindependently,andforsimilarreasons To build the corpus, we first identified verbs that represented events by running the system of (Bethard and Martin, 2006) on the TreeBank.


