Usually bridging anaphora considers two types:1 associative anaphors are noun phrases (NPs) that have an antecedent that is necessary to their interpretation but the relation between the anaphor and its antecedent is different from identity; and indirect anaphors are those that have an identity relation with their antecedents but the anaphor and its antecedent have different head 1The terminology that we use here is introduced by Hawkins (1978), which is also used in (Vieira et al., 2006).


