While the focus of our paper is not on the method of evaluation, it is worth pointing out that the performance on the synthetic data set is a very poor guide to the performance on naturally occurring data (Georgescul et al. , 2006).


This means probably that algorithms with good results on a corpus built as the Choi corpus will not necessarily have good results on true texts, which agrees with (Georgescul et al. , 2006).


