W09-1704:1	7:147	Various supervised learning approaches  1  http://www.nist.gov/speech/tests/ace/ have been explored for ACE multi-lingual event extraction (e.g. Grishman et al., 2005; Ahn, 2006; Hardy et al., 2006; Tan et al., 2008; Chen and Ji, 2009).
---------------------------------------------------
W09-1704:2	127:147	As Ji and Grishman (2006) pointed out, both self-training and bootstrapping methods require good data selection scheme.
---------------------------------------------------
