W06-1640:1	73:223	More details about why heuristics are needed and the process used to map sources to NPs can be found in Stoyanov and Cardie (2006).
---------------------------------------------------
W06-1640:2	186:223	More details on the different parameter settings and instance selection algorithms as well as trends in the performance of different settings can be found in Stoyanov and Cardie (2006).
---------------------------------------------------
C08-1031:3	74:290	Sentiment classification at the sentence-level has also been studied (e.g., Riloff and Wiebe 2003; Kim and Hovy 2004; Wilson et al 2004; Gamon et al 242 2005; Stoyanov and Cardie 2006).
---------------------------------------------------
N09-3013:4	13:119	Other research has been conducted in analysing sentiment at a sentence level using bootstrapping techniques (Riloff and Wiebe, 2003), finding strength of opinions (Wilson, Wiebe and Hwa, 2004), summing up orientations of opinion words in a sentence (Kim and Hovy, 2004), and identifying opinion holders (Stoyanov and Cardie, 2006).
---------------------------------------------------
