In a parallel development, interest in incorporating semantic computation into the TAG framework has led to the use of STAG for this purpose (Nesson and Shieber, 2007; Han, 2006b; Han, 2006a; Nesson and Shieber, 2006).


and Gildea, 2007; Zhang et al., 2006; Gildea, Satta, and Zhang, 2006).


1 Introduction Nesson and Shieber (2006) showed how a nowstandard variant of the tree-adjoining grammar (TAG) formalism (multi-component, multiple adjunction, finite-feature-based TAG), when synchronized, leads to a natural analysis of the syntaxsemantics relation, including handling of syntactic movement phenomena such as wh questions and relativization, semantic movement phenomena such as quantification, quantifier scope ambiguity, and even their interactions as found in pied-piped relative clauses.1 phenomena were previously viewed 1ThisworkwassupportedinpartbygrantIIS-0329089from the National Science Foundation.


Independently, Han (2006a) developed a similar synchronous TAG analysis of piedpiping, providing evidence for the naturalness of the analysis.


Previous work by Han (2006a; 2006b) and Nesson and Shieber (2006) describe this approach in detail, showing its applicability to a range of semantic phenomena.


