The unigram of an OOV word is estimated as: Unigram(OOV Word)=p l (7) where p is the minimal value of unigram scores in the language model; l is the length of the OOV word, which is used as a punishment factor to avoid overemphasizing the long OOV words (Xinhao Wang et al., 2006).


2.3 Post-Processing Strategies The division and combination rule, which has been proved to be useful in our system of Bakeoff 2006 (Xinhao Wang et al., 2006), is adopted for the postprocessing in the system.


