Such exercises are now common in most areas of NLP, and have had a major impact on many areas, including machine translation and information extraction (see discussion of history of shared-task initiatives and their impact in Belz and Kilgarriff (2006)).


We are planning to increase the number and complexity of tasks from one round to the next, as this has been useful in other NLP evaluations (Belz and Kilgarriff, 2006); for example, we will add surface realisation as a separate task in round 2 and layout/structuring task in round 3.


We intend to use a fairly standard organisation (Belz and Kilgarriff, 2006).


3 Our Proposal We intend to apply for funding for a three-year projecttocreatemoresharedinput/outputdatasets (we are focusing on data-to-text tasks for the reasons discussed in Belz and Kilgarriff (2006)), organise shared task workshops, and create and test a range of methods for evaluating submitted systems.


(2006), Belz and Kilgarriff (2006), Belz and Reiter (2006), Paris et al.


