ASO has been shown to be effective on the following natural language processing tasks: text categorization, named entity recognition, part-of-speech tagging, and word sense disambiguation (Ando and Zhang, 2005a; Ando and Zhang, 2005b; Ando, 2006). 
Ando (2006) used Alternative Structured Optimization. 
1020 Bayes (Soft Tag) 73.6 SVM-topic 73.0 SVM baseline 72.4 NB baseline 69.8 ASO(Ando, 2006) 74.1 SVM-LSA (Strapparava et al. , 2004) 73.3 Senseval-3 Best System(Grozea, 2004) 72.9 Table 5: Results compared to previous best systems on Senseval-3 English lexical sample task. 
With well-designed auxiliary problems, the method has been applied to text classification, text chunking, and word sense disambiguation (Ando, 2006). 
Ando (2006) used Alternative Structured Optimization, which is closely related to Structural Learning (cited above). 
