It has been used for a variety of tasks, such as wide-coverage parsing (Hockenmaier and Steedman, 2002; Clark and Curran, 2007), sentence realization (White, 2006), learning semantic parsers (Zettlemoyer and Collins, 2007), dialog systems (Kruijff et al., 2007), grammar engineering (Beavers, 2004; Baldridge et al., 2007), and modeling syntactic priming (Reitter et al., 2006).


In a previous corpus-study, using transcriptions of spontaneous, task-oriented and non-task-oriented dialogue, utterances were annotated with syntactic trees, which we then used to determine the phrasestructure rules that licensed production (and comprehension) of the utterances (Reitter et al. , 2006b).


Specific competing constructions such as active/passive, verbal particle placement or thatdeletion in English are often the object of study (Szmrecsanyi, 2005; Gries, 2005; Dubey et al. , 2005; Jager, 2006), but the effect can also be generalized to syntactic phrase-structure rules or combinatorial categories (Reitter et al. , 2006a).


Classical priming effects are strong: around 10% for syntactic rules (Reitter et al. , 2006b).


In our previous study (Reitter et al. , 2006b), we found more syntactic priming in the task-oriented dialogues of the Map Task corpus than in the spontaneous conversation collected in the Switchboard corpus.


