Most prior work on relation sense identification reports results obtained on data consisting of both explicit and implicit relations (Wellner et al., 2006; Soricut and Marcu, 2003).


Recent work has shown promising preliminary results for recognizing and labeling relations of GraphBank structures (Wellner et al. , 2006), in the case that the algorithm is provided with 494 manually segmented sentences.


First-Last, First3: The first and last words of a relations arguments have been found to be particularly useful for predicting its sense (Wellner et al., 2006).


