In the health care area, for instance, such products as Converser (Dillinger & Seligman, 2006), S-MINDS (www.fluentialinc.com), and Med-SLT (Bouillon et al, 2005) are coming into use.


The facility is described in (Seligman and Dillinger, 2006).


We have described these interactive techniques in (Dillinger and Seligman, 2004; Zong and Seligman, 2005; Dillinger and Seligman, 2006; and Seligman and Dillinger, 2006).


