(van Deemter et al., 2006) present methods to collect data (the TUNA corpus) for REG using artificially constructed pictures of furniture and photographs of real people.


Unfortunately, both in the Viethen and Dale dataset and in the TUNA corpus (van Deemter et al., 2006), only a minority of referring expressions is relational, maybe because these domains lend themselves very well to row/column style propositional REs.


