352 Table 1: Examples of entity pairs after hypernym expansion President Sothebys Chief Executive Sothebys Decision maker Sothebys leader Sothebys Table 2: Examples of extracted text from Google The 40 year old former president travels incognitio to Sothebys Brooks was named president of Sothebys Inc. Subsidiary President at Sothebys Bill Ruprecht, chief executive of Sothebys, agreed that September 11 had been The Duke will also remain leader of Sothebys Germany 3.1.2 Web search (Geleijnse and Korst, 2006) use Google as their search engine for extracting surface patterns from Web documents.


