These works annotated temporal relations between events and times, but low inter-annotator agreement made many TimeBank and TempEval tasks difficult (Boguraev and Ando, 2005; Verhagen et al., 2007). 
See (Verhagen et al. , 2007) for a full tabulation of results for all systems.3 4 Future Directions SIGNALs and SLINKs are possible candidates as additional features  signals obviously so, whereas the benefits of exploiting subordination information are less clear. 
A first attempt to standardize this task was the 2007 TempEval competition(Verhagen et al., 2007). 
In order to drive forward research on temporal relation identification, the SemEval 2007 shared task (Verhagen et al., 2007) (TempEval) included the following three tasks. 
Accordingly, the performance results given in (Verhagen et al. , 2007) are reported using metrics of precision, recall and F-measure. 
