Similarly, Yoshida and Tsujii (2007) use an nbest MEMM to generate multiple analyses for a sentence, and re-rank the analyses based on information extracted from neighbouring sentences.


Machine learners are widely used in biomedical named entity recognition and have outperformed the rule based systems (Zhou et al., 2004; Tsai et al., 2006; Yoshida and Tsujii, 2007).


This named-entity tagger program is based on a first order Maximum Entropy Markov Model (MEMM) and is described in Yoshida and Tsujii (2007).


