Krishnakumaran and Zhu (2007) focused on three syntactically constrained sub-types of metaphors: nouns joined by be, nouns following verbs, and nouns following adjectives.


Krishnakumaran and Zhu (2007) considered only a few different syntactic constructions, but we need to consider all the ways a metaphor may be expressed to evaulate overall metaphor frequency.


Current state of art in metaphor detection therefore tends to be localistic  the distributional profile of the target word in its immediate grammatical or collocational context in a background corpus or a database like WordNet is used to determine metaphoricity (Mason, 2004; Krishnakumaran and Zhu, 2007; Birke and Sarkar, 2006; Gedigian et al., 2006; Fass, 1991).


It complements the traditionally localistic outlook on metaphors that is based on the observation that a metaphorically used item creates a local incongruity because there is a violation of a selectional restrictions between verbs and their arguments (Fass, 1991; Mason, 2004; Gedigian et al., 2006; Birke and Sarkar, 2006) or in the adjective-noun pairs (Krishnakumaran and Zhu, 2007).


Tasks under this heading include computational humor (Mihalcea and Strapparava, 2005), genre classification (Boese and Howe, 2005), authorship attribution (Argamon and Shimoni, 2003), and metaphor detection (Krishnakumaran and Zhu, 2007), among others (Mishne et al., 2007; Mihalcea and Liu, 2006).


