Recent work on parser evaluation using dependency graphs in the biomedical domain confirms 6 that researchers regard dependency-based evaluation as a more useful surrogate for extrinsic task-based evaluation (Clegg and Shepherd, 2007; Pyysalo et al., 2007a). 
(2007) for Greek to English, and in Dirix et al. 
Predicate-argument structure identified in this way can then be used in tasks like information extraction (Surdeanu et al., 2003) and question answering (Kaisser and Webber, 2007). 
The open information extraction system TEXTRUNNER (Banko et al., 2007) also makes use of the SD graph representation: its first module uses the Stanford parser and the dependency tool to automatically identify and label trustworthy and untrustworthy extractions. 
These are described in detail in Melero and Badia (2007) for Spanish to English, in Carl (2007) for German to English, in Markantonatou et al. 
