1Recently, a similar task has been addressed by the Affective Text Task at SemEval-1 where even shorter units  headlines  were classified into positive, negative and neutral categories using a variety of techniques (Strapparava and Mihalcea, 2007).


In 2007, the SemEval-2007 workshop organized a task on the unsupervised annotation of news headlines with emotions (Strapparava and Mihalcea, 2007).


