A number of papers have suggested that paraphrase knowledge plays a very important role (Bar-Haim et al., 2005; Marsi et al., 2007; Dinu and Wang, 2009).


Other work on RTE has targeted specifically this observation and has described paraphrases on a dependency level (Marsi et al., 2007; Dinu and Wang, 2009).


As a consequence, the CoNLL shared tasks of 2006 (Buchholz and Marsi, 2006) and 2007 (Nivre et al., 2007) focused on multilingual dependency parsing using dependency-based treebanks, something that has led to a further increase in the popularity of dependency-based parsing </context> </contexts> <marker>Buchholz, Marsi, 2006</marker> <rawString>Sabine Buchholz and Erwin Marsi.


In (Marsi et al., 2007), the focus is on the usefulness of DIRT.


For this reason, 1) instead of forcing the anchor values to be identical as most previous work, we allow more flexible rule matching (similar to (Marsi et al., 2007)) and 2) furthermore, we control the rule application process using a text representation based on dependency structure.


