Given a text T (several sentences) and a hypothesis H (one sentence), the goal is to detect if H can be inferred from T. Studies such as (Clark et al., 2007) attest that lexical substitution (e.g. synonyms, antonyms) or simple syntactic variation account for the entailment only in a small number of pairs.


In (Clark et al., 2007)s approach, semantic parsing to clause representation is performed and true entailment is decided only if every clause in the semantic representation of T semantically matches some clause in H. The only variation allowed consists of rewritings derived from WordNet and DIRT.


Other studies have shown similar evidences for Recognizing Textual Entailment (RTE) (Clark et al., 2007; Burchardt et al., 2008): most examples of the RTE challenges corpora can be solved at the predicate-argument structure level, but FrameNet coverage is still a major problem.


