W09-2602:1	122:154	In our system, the veridicality inferences that these embeddings exhibit are computed by further knowledge representation modules that explicitely represent the speaker commitment of a context (Bobrow et al., 2007b).
---------------------------------------------------
W09-2602:2	44:154	Given this skolemized first-order language, the task of textual entailment can be conceived as matching the hypothesis representation against the semantic representation of the text where higher-order reasonning is approximated by explicit entailment rules (e.g. all entails some, past does not entail present), see (Bobrow et al., 2007b) for a presentation of an RTE system based on this semantic representation.
---------------------------------------------------
W09-2602:3	15:154	In the context of the ParGram project, a number of high quality, broad-coverage grammars for several languages have been produced over the years (Butt et al., 2002; Butt and King, 2007).1 The projects research methodology particularly focusses on parallelism which means that the researchers rely on a common syntactic theory as well as development tools, but which also concerns parallelism on the level of syntactic analyses.
---------------------------------------------------
W09-2602:4	116:154	Thus, the real semantic interpretation of these phenomena is deferred to later representation or processing layers, as in this framework, to the definition of entailment relations (Bobrow et al., 2007b).
---------------------------------------------------
W09-2602:5	30:154	The representation simplifies many phenomena usually discussed in the formal semantic literature (see the next section), but is tailored for use in Question Answering (Bobrow et al., 2007a) or Textual Entailment (Bobrow et al., 2007b) applications.
---------------------------------------------------
P08-1111:6	48:146	The current project is also situated within a broader trend of using computational linguistics in the service of endangered language documentation (e.g., Robinson et al., 2007, see also www.emeld.org).
---------------------------------------------------
P08-1111:7	12:146	The Grammar Matrix was developed initially on the basis of broadcoverage grammars for English (Flickinger, 2000) and Japanese (Siegel and Bender, 2002), and has since been extended and refined as it has been used in the development of broad-coverage grammars for Norwegian (Hellan and Haugereid, 2003), Modern Greek (Kordoni and Neu, 2005), and Spanish (Marimon et al., 2007), as well as being applied to 42 other languages from a variety of language families in a classroom context (Bender, 2007).
---------------------------------------------------
P08-1111:8	6:146	Nevertheless, they are key to various NLP applications, including those benefiting from deep natural language understanding (e.g., textual inference (Bobrow et al., 2007)), generation of wellformed output (e.g., natural language weather alert systems (Lareau and Wanner, 2007)) or both (as in machine translation (Oepen et al., 2007)).
---------------------------------------------------
P08-1111:9	44:146	2.3 Related Work There are currently many multilingual grammar engineering projects under active development, including ParGram, (Butt et al., 2002; King et al., 2005), the MetaGrammar project (Kinyon et al., 2006), KPML (Bateman et al., 2005), Grammix (Muller, 2007) and OpenCCG (Baldridge et al., 2007).
---------------------------------------------------
