Sections 3 and 4 presents in more detail the implementation of the framework for the Semeval2007 WEPS task (Artiles et al. , 2007) and Semeval2007 sense induction task (Agirre and Soroa, 2007), respectively. 
1 Introduction We consider the problem of disambiguating person names in a Web searching scenario as described by the Web People Search Task in SemEval 2007 (Artiles et al. , 2007). 
The Semeval07 Web People Search challenge (Artiles et al. , 2007) formally evaluated systems on this task. 
Hence the performance reported here is comparable to the official evaluation results (Artiles et al., 2007). 
task (Artiles et al. , 2007). 
