5 The development environment Our final demo highlights the new Regulus development environment (Kron et al., 2007), which has over the last few months acquired a large amount of new functionality designed to facilitate rapid prototyping of spoken language applications3.


4 Speech and text in the online development environment The Regulus GUI (Kron et al., 2007) is intended as a complete redesign of the development environment, which simultaneously attacks all of the central issues.


Cut subtrees can be recombined for debugging purposes (Kron et al., 2007).


also (Kron et al., 2007)), and load and test translation rules in the Translate window (Figure 2).


