4 Evaluation For evaluation, we used utterances collected from 204 users of Microsoft Voice Command, a grammar-based command-and-control (C&C) application for high-end mobile devices (see Paek et al., 2007 for details).


Furthermore, because recognition of part of an utterance can increase the odds of ultimately achieving task completion (Paek et al., 2007), we carried out separate evaluations for the functional constituents of a C&C utterance (i.e., keyword and slot) as well as the complete phrase (keyword + slot).


This idea is very complementary with a two-pass recognition approach where the goal is to get utterances correctly recognized by a CFG on the first pass so as to minimize computational expenses (Paek et al., 2007).


One way to accomplish this is by constructing a backoff CFG using filler models (Paek et al., 2007), which when applied to the same command-andcontrol task in Section 4 can result in a 35% relative reduction in semantic error rate for OOG utterances.


