(Hickl and Bensley, 2007)) are typically resource intensive, and cannot scale to large retrieval tasks if a brute force approach is used.


We also hope to investigate applying alignment techniques introduced for entailment recognition (Hickl and Bensley, 2007).


In addition, an alignment-based approach has the advantage of generality: Almost all existing RTE models align the linguistic material of the premise 1 and hypothesis and base at least part of their decision on properties of this alignment (Burchardt et al., 2007; Hickl and Bensley, 2007; Iftene and Balahur-Dobrescu, 2007; Zanzotto et al., 2007).


(2006) and Hickl and Bensley (2007).


