D08-1088:1	181:219	Both Zens and Ney (2005) and Dreyer et al (2007) use a greedy approach here; the latter estimated the impact of this to be insignificant in random sampling experiments.
---------------------------------------------------
D08-1088:2	17:219	Dreyer et al (2007) examined a special class of word graphs, namely those that denote constrained reorderings of single sentences.
---------------------------------------------------
D08-1064:3	113:146	If one wants to select the minimum-Bayes-risk translation from a lattice (or shared forest) instead of an n-best list (Tromble et al., 2008), or to select an oracle translation from a lattice (Tillmann and Zhang, 2006; Dreyer et al., 2007; Leusch et al., 2008), or to perform discriminative training on all the examples containedinalattice(Taskaretal.,2004),onewould need a metric that can be calculated on the edges of the lattice.
---------------------------------------------------
E09-1044:4	89:206	Relative to the complex movement and translation allowed by Hiero and other models, MJ1 is clearly inferior (Dreyer et al., 2007); MJ1 was developed with efficiency in mind so as to run with a minimum of search errors in translation and to be easily and exactly realized via WFSTs.
---------------------------------------------------
D08-1024:5	85:186	For every derivation e in the forest, we calculate a vector c(e) of counts as in Section 2.2 except using unclipped counts of n-gram matches (Dreyer et al., 2007), that is, the number of matches for an ngram can be greater than the number of occurrences of the n-gram in any reference translation.
---------------------------------------------------
