2.2 Domain Adaptation In our previous findings (Nakov and Hearst, 2007), we found that using in-domain and out-of-domain language models is the best way to perform domain adaptation. 
Some other systems that avoided using the labels used WN as a supporting resource for their algorithms (Costello, 2007; Nakov and Hearst, 2007; Kim and Baldwin, 2007). 
Following Nakov and Hearst (2007), we used two language models (LM)  an in-domain one (trained on a concatenation of the provided monolingual Spanish News Commentary data and the Spanish side of the training News Commentary bi-text) and an out-ofdomain one (trained on the provided monolingual Spanish Europarl data). 
Since (Hearst, 1992), numerous works have used patterns for discovery and identification of instances of semantic relationships (e.g., (Girju et al., 2006; Snow et al., 2006; Banko et al, 2007)). 
The idea was introduced in (Nakov and Hearst, 2007), and is described in more detail in (Nakov, 2007). 
