W09-0404:1	15:155	Other proposalsuse structural informationsuchasdependency edges (Owczarzak et al., 2007).
---------------------------------------------------
W09-0440:2	9:145	For instance, we may find metrics which compute similarities over shallow syntactic structures/sequences (Gimenez and M`arquez, 2007; Popovic and Ney, 2007), constituency trees (Liu and Gildea, 2005) and dependency trees (Liu and Gildea, 2005; Amigo et al., 2006; Mehay and Brew, 2007; Owczarzak et al., 2007).
---------------------------------------------------
I08-1042:3	15:165	For instance, we may find metrics based on full constituent parsing (Liu and Gildea, 2005), and on dependency parsing (Liu and Gildea, 2005; Amigo et al., 2006; Mehay and Brew, 2007; Owczarzak et al., 2007).
---------------------------------------------------
