In fact, this has been done by Bethard and Martin (2007): they first solve task B and then use this information as features for Tasks AandC.Whiletheydoreportimprovements(0.7% 411 Table 7: Comparison with Other Systems TaskA TaskB TaskC strict relaxed strict relaxed strict relaxed TempEvalBest 0.62 0.64 0.80 0.81 0.55 0.64 TempEvalAverage 0.56 0.59 0.74 0.75 0.51 0.58 CU-TMP 0.61 0.63 0.75 0.76 0.54 0.58 LocalModel 0.62 0.67 0.74 0.75 0.53 0.60 GlobalModel 0.65 0.69 0.76 0.78 0.57 0.63 GlobalModel(Task-Adjusted) (0.66) (0.70) (0.76) (0.79) (0.58) (0.64) on Task A, and about 0.5% on Task C), generally these improvements do not seem as significant as ours.


The third row shows the results of CU-TMP (Bethard and Martin, 2007), an SVM-based system that achievedthesecondhighestscoresinTempEvalfor all three tasks.


The local formulae are based on features employed in previous work (Cheng et al., 2007; BethardandMartin,2007)andarelistedinTable1.


There has been a fair amount of recent research on extraction of temporal relations, including (Chambers et al., 2007; Lapata and Lascarides, 2006; Bramsen et al., 2006; Bethard and Martin, 2007; Min et al., 2007; Puscasu, 2007).


