(2007) use a CRF to identify 339 a guest comedian Victor Borge NP[nb]/N N/N N/N N/N N >N >N >N >NP a guest comedian Victor Borge NP[nb]/N N/N N (NP\NP)/(NP\NP) NP\NP > >N NP\NP >NP <NP (a) (b) Figure 4: CCGbank derivations for apposition with DT coordinate structure in biological named entities.


Lewin (2007) experiments with detecting base-NPs using NER information, while Buyko et al.


We consider such an adjustment domain-independent given that NER is available in many domains (Lewin, 2007).


