This has produced a body of publications that includes Oepens work on test suitedesign(Oepenetal., 1998), Volksworkontest suite encoding (Volk, 1998), Oepen et al.s work on the Redwoods project (Oepen et al., 2002), Butt and Kings discussion of the importance of testing (Butt and King, 2003), Flickinger et al.s work on semantics debugging with Redwoods data (Flickinger et al., 2005), and Bender et al.s recent work on test suite generation (Bender et al., 2007).


It achieved the highest performance on one measure of the protein-protein interaction task in the BioCreative II shared task (Krallinger et al., 2007).


(Cohen et al., 2004) describes a methodology for generating test suites for molecular biology named entity recognition systems, and (Johnson et al., 2007) describes the development of a fault model for linguistically-based ontology mapping, alignment, and linking systems.


Another very valuable one is the found/fixed or open/closed graph (Black, 1999; Baumgartner Jr. et al., 2007).


