Binarization also attracts attention in the syntaxbased models for machine translation, where translation can be modeled as a parsing problem and binarization is essential for efficient parsing (Zhang et al., 2006; Huang, 2007). 
Forest reranking with a language model can be performed over this n-ary forest using the cube growing algorithm of Huang and Chiang (2007). 
model reranking has also been established, both for synchronous binarization (Zhang et al., 2006) and for target-only binarization (Huang, 2007). 
We rerank derivations with cube growing, a lazy beam search algorithm (Huang and Chiang, 2007). 
Target-side binarization is another binarization method which is proposed by Huang (2007). 
