More recently, good results on lexical substitution and word sense disambiguation using language models have also been reported (Hawker, 2007; Yuret, 2007). 
For evaluation, we compared our results to those of the three systems that participated in the task (MELB: Ye and Baldwin (2007); KU: Yuret (2007); IRST: Popescu et al. 
More recently, good results on lexical substitution and word sense disambiguation using language models have also been reported (Hawker, 2007; Yuret, 2007). 
System Accuracy kNN 684 SVM (RBF Kernel) 692 J48 decision trees 712 Multinomial Nave Bayes 731 Maximum Entropy 751 Most Frequent Sense 396 IRST (Popescu et al., 2007) 496 KU (Yuret, 2007) 547 MELB (Ye and Baldwin, 2007) 693 Table 1. 
Yuret (2007) used a n-gram model based on word substitution by synonyms or antonyms. 
