They used these DPCs to implement an unsupervised nave Bayes word sense classifier that placed first among all unsupervised systems taking part in the Multilingual Chinese English Lexical Sample Task (task #5) of SemEval07 (Jin et al. , 2007).


5.3.2 Discussion Our nave Bayes classifier scored highest of all unsupervised systems taking part in the task (Jin et al. , 2007).


English Lexical Sample Task (Jin et al. , 2007) is to select from a given list a suitable English translation of a Chinese target word in context.


4.3 Multilingual Chinese?English Lexical Sample Task The Multilingual Chinese?English Lexical Sample Task training and test data (Jin et al. , 2007) have 2686 and 935 instances respectively for 40 target words (19 nouns and 21 verbs).


