Several studies investigated mixture model adaptation for both translation model and language model in SMT (Civera and Juan, 2007; Foster and Kuhn, 2007).


138 ID Participant cmu-uka Carnegie Mellon University, USA (Paulik et al. , 2007) cmu-syntax Carnegie Mellon University, USA (Zollmann et al. , 2007) cu Charles University, Czech Republic (Bojar, 2007) limsi LIMSI-CNRS, France (Schwenk, 2007) liu University of Linkoping, Sweden(Holmqvist et al. , 2007) nrc National Research Council, Canada (Ueffing et al. , 2007) pct a commercial MT provider from the Czech Republic saar Saarland University & DFKI, Germany (Chen et al. , 2007) systran SYSTRAN, France & U. Edinburgh, UK (Dugast et al. , 2007) systran-nrc National Research Council, Canada (Simard et al. , 2007) ucb University of California at Berkeley, USA (Nakov and Hearst, 2007) uedin University of Edinburgh, UK (Koehn and Schroeder, 2007) umd University of Maryland, USA (Dyer, 2007) upc University of Catalonia, Spain (Costa-Juss`a and Fonollosa, 2007) upv University of Valencia, Spain (Civera and Juan, 2007) Table 1: Participants in the shared task.


Using a mixture of topicdependent Viterbi alignments was proposed in (Civera and Juan, 2007).


In (Civera and Juan, 2007) mixture models are instead employed to adapt a word alignment model to in-domain parallel data.


