Our system participates in 414 SemEval-2007 word sense induction and discrimination task (SWSID) (Agirre and Soroa, 2007). 
The first effort to evaluate WSI methods under a common framework (evaluation schemes & dataset) was undertaken in the SemEval-2007 WSI task (SWSI) (Agirre and Soroa, 2007), where two separate evaluation schemes were employed. 
According to Agirre & Soroa (2007), supervised evaluation seems to be more neutral regarding the number of induced clusters, because clusters are mapped into a weighted vector of senses, and therefore inducing a number of clusters similar to the number of senses is not a requirement for good results. 
For evaluation, we used the Semeval-2007 benchmark dataset released as part of the sense induction and discrimination task (Agirre and Soroa, 2007). 
2 SemEval-2007 WSI evaluation setting The SemEval-2007 WSI task (Agirre and Soroa, 2007) evaluates WSI systems on 35 nouns and 65 verbs. 
