Van Noord extracted bilexical preferences from a Dutch parsed corpus of 500M words without selection(vanNoord, 2007).


The use of word pairs in auto-parsed data was tried in van Noord (2007) and Chen et al.


While the parser normally operates on an accuracy level of roughly 88-89% (van Noord, 2007) on its own domain (newspaper text), the accuracy on these subdomains drops to around 85%.


Then, CA = Dosummationtext i max(Dig,Dip) If we want to compare the performance of disambiguation models, we can employ the  measure (van Noord and Malouf, 2005; van Noord, 2007).


Thus, one conclusion from that line of work is that as soon as there is a reasonable (often even small) amount of labeled target data, it is often more fruitful to either just use that, or to apply simple adaptation techniques (Daume III, 2007; Plank and van Noord, 2008).


