We have previously shown (Agirre et al., 2005; Agirre and Lopez de Lacalle, 2007) that performing SVD on the feature-to-documents matrix is a simple technique that allows to improve performance with and without unlabeled data. 
We set k to 5 based on previous results (Agirre and Lopez de Lacalle, 2007). 
5.1 k-NN combinations Our k-NN combination method (Agirre et al., 2005; Agirre and Lopez de Lacalle, 2007) takes 45 advantage of the properties ofk-NN classifiers and exploit the fact that a classifier can be seen as k points (number of nearest neighbor) each casting one vote. 
The methods used in this paper originated in (Agirre et al., 2005; Agirre and Lopez de Lacalle, 2007), where SVD over a feature-to-documents matrix improved WSD performance with and without unlabeled data. 
We set k to 5 based on previous results published in (Agirre and Lopez de Lacalle, 2007). 
