W09-0906:1	37:149	Not only is this shown to achieve state-of-the art results compared to other unsupervised parsing methods (Bod2006b, 2007a), it is also shown to outperform state-of-the-art supervised parsing techniques when evaluated as a language model for a practical application (Machine Translation), rather than using the rather academical and the 3  Air Transport Information System  part of the Penn Treebank.
---------------------------------------------------
W09-0906:2	35:149	2.2 Unsupervised DOP Unsupervised DOP (UDOP, Bod 2006b, 2007a, 2007b) extends the DOP approach to bootstrap language without recourse to a training corpus of manually annotated language data as a representation of prior experience.
---------------------------------------------------
W09-0906:3	3:149	1  1 Introduction Data-Oriented Parsing (DOP) is a state-of-the art approach to both supervised and unsupervised parsing (Bod1992, 1998, 2006a, 2006b, 2007a, 2007b, Zollman and Simaan 2005), which has mostly been developed within a technologicallyoriented computer science context.
---------------------------------------------------
W09-0906:4	42:149	Bod (2007a) shows that these methods applied to miniature toy corpora can be used to explain linguistically interesting phenomena, such as long-distance agreement and movement, as emerging out of simpler structures without themselves being found in either experience or hardwired grammar.
---------------------------------------------------
W09-0906:5	38:149	43 ory-laden standard of agreement with the judgements of manual annotations on a corpus (Bod 2007b).
---------------------------------------------------
