W09-0213:1	44:189	The most comparable work to ours is the research by (Cook et al., 2007) and (Fazly and Stevenson, 2007).
---------------------------------------------------
W09-0213:2	66:189	Previous work, (Fazly and Stevenson, 2007), restricted context to within the boundaries of the sentences in which the tokens of interest occurred.
---------------------------------------------------
W09-0213:3	15:189	To date, most research has addressed the problem of MWE type classification for VNC expressions in English (Melamed, 1997; Lin, 1999; Baldwin et al., 2003; na Villada Moiron and Tiedemann, 2006; Fazly and Stevenson, 2007; Van de Cruys and Villada Moiron, 2007; McCarthy et al., 2007), not token classification.
---------------------------------------------------
W09-0213:4	56:189	They report an overall system performance accuracy of 72.4%.1 (Fazly and Stevenson, 2007) correlate compositionality with idiomaticity.
---------------------------------------------------
W09-0213:5	63:189	Inspired by works of (Katz and Giesbrecht, 2006; Fazly and Stevenson, 2007), our approach is to compare the context vector of a VNC with the composed vector of the verb and noun (V-N) component units of the VNC when they occur in isolation of each other (i.e., not as a VNC).
---------------------------------------------------
