The approach presented here combines the strengths of multiple systems and is different from recent work on post-correction of RBMT output as presented in (Simard et al., 2007; Dugast et al., 2007), which focuses on the improvement of a single RBMT system by correcting typical errors via SMT techniques.


Acknowledgments We would like to thank Michel Simard, Roland Kuhn, George Foster and Pierre Isabelle from NRC, Canada for their collaboration on this work (Simard et al. 2007).


138 ID Participant cmu-uka Carnegie Mellon University, USA (Paulik et al. , 2007) cmu-syntax Carnegie Mellon University, USA (Zollmann et al. , 2007) cu Charles University, Czech Republic (Bojar, 2007) limsi LIMSI-CNRS, France (Schwenk, 2007) liu University of Linkoping, Sweden(Holmqvist et al. , 2007) nrc National Research Council, Canada (Ueffing et al. , 2007) pct a commercial MT provider from the Czech Republic saar Saarland University & DFKI, Germany (Chen et al. , 2007) systran SYSTRAN, France & U. Edinburgh, UK (Dugast et al. , 2007) systran-nrc National Research Council, Canada (Simard et al. , 2007) ucb University of California at Berkeley, USA (Nakov and Hearst, 2007) uedin University of Edinburgh, UK (Koehn and Schroeder, 2007) umd University of Maryland, USA (Dyer, 2007) upc University of Catalonia, Spain (Costa-Juss`a and Fonollosa, 2007) upv University of Valencia, Spain (Civera and Juan, 2007) Table 1: Participants in the shared task.


The interested reader is referred to (Simard et al. , 2007).


5 Architecture of the SPE system During the last years statistical post-editing systems have shown to achieve very competitive performance (Simard et al., 2007; Dugast et al., 2007).


