Inference systems often incorporated this information, typically as top-k or threshold-based filters (Pantel and Lin, 2003; Roth and Sammons, 2007).


(Roth and Sammons, 2007).


Works that do provide quantitative information regarding resources utility have focused on few particular resources (Kouylekov and Magnini, 2006; Roth and Sammons, 2007) and evaluated their impact on a specific system.


