The oracle translations are obtained by using the metric of sentence-level BLEU score (Ye et al., 2007).


(Yang et al., 2007) formulates MT evaluation as a ranking problems leading to greater correlation with human assessment at the sentence level.


4.2 Measuring Correlation Following (Ye et al., 2007), we first compute the Spearman correlation between the human rankings and Meteor rankings of the translation hypotheses corresponding to a single source sentence.


