Our second demo, an early version of which is described in (Bouillon et al., 2007), supports bidirectional translation for the sore throat domain, in the English  Spanish pair.


Details are provided in (Bouillon et al., 2007).


Prominent examples are Geneva Universitys MedSLT medical speech translator (Bouillon et al., 2005), NASAs Clarissa procedure browser (Rayner et al., 2005) and Ford Researchs experimental SDS in-car spoken dialogue system, which was awarded first prize at the 2007 Ford internal demo fair.


A third example is contextual bidirectional speech translation (Bouillon et al., 2007).


