Augmenting ParaMors Segmentations With its focus on the paradigm, ParaMor specializes at analyzing inflectional morphology (Monson et al., 2007a). 
For this reason, the baseline ParaMor algorithm already discarded schemes that likely misplace a boundary steminternally (Monson et al., 2007b). 
Second, ParaMor decouples the task of paradigm identification from that of word segmentation (Monson et al., 2007b). 
Relaxing restrictions on ParaMors clustering algorithm (Monson et al., 2007a) may address this paradigm fragmentation. 
We incorporate the segmentations from Morfessor into the segmentations that the ParaMor system produces by straightforwardly adding the Morfessor segmentation for each word as an additional separate analysis to those ParaMor produces (Monson et al., 2007b). 
