The training, development, and test data for German-English and Hungarian-English systems used were distributed as part of the 2009 EACL Workshop on Machine Translation,4 and the Turkish-English data corresponds to the training and test sets used in the work of Oflazer and Durgar ElKahlout (2007).


However, although several effective segmenters and analyzers for specific languages exist, and even unsupervised language-neutral versions such as Morfessor (Creutz and Lagus, 2007), only recently have similar approaches been successfully used in the context of machine translation to improve the BLEU score (Oflazer and El-Kahlout, 2007), and none yet in Finnish.


