These results include the median of all participating systems, the top system not using training data (UPVWSD) (Buscaldi and Rosso, 2007), and the top system using training data (NUS-PT) (Chan et al., 2007).


Our overall results were just below that of the top system not utilizing training data, (UPV-WSD (Buscaldi and Rosso, 2007)), and a little over 6 percentage points below the top supervised system (NUSPT (Chan et al., 2007)).


UPV-WSD NUS-PT SSI 78.63 82.50 83.21 Table 3: Results as F1 Values of top performing systems for the SemEval07 Task07 (UPV = (Buscaldi and Rosso, 2007), NUS-PT = (Chan et al., 2007), and SSI = a task organizers system (Navigli and Velardi, 2005)).


