NO-EDGE model uses only the vertex features, while each of the Sn-EDGE models makes use of the edge features associated with System Recall PNNL (Tratz et al., 2007) 67.0% Simil-Prime (Kohomban and Lee, 2005) 66.1% ALL-EDGE 65.5% GAMBL (Decadt et al., 2004) 65.2% SENSELEARNER (Mihalcea et al.,2004) 64.6% BASELINE 62.2% Table 3: The comparison of the performance of WSD systems evaluated on the SENSEVAL-3 English all-words test set.


