Many existing RTE systems, e.g., (Adams et al., 2007; Chambers et al., 2007) largely work by statistically scoring the match between T and H, but this to an extent sidesteps deep languageunderstanding,namely building a coherent, internal representation of the overall scenario the input text was intended to convey.


Alignment weights were learned using manually annotated RTE development sets (see Chambers et al., 2007).


For this purpose, we used the alignment component of the Stanford RTE system (Chambers et al., 2007).


