Since 2002, the grammar has been extended and modified by Berthold Crysmann (Crysmann, 2003; Crysmann, 2005; Crysmann, 2007).


The deep processing platform used in the project is the PET parser (Callmeier, 2000) operating on wide-coverage English and German HPSG grammars, the English Resource Grammar (ERG) (Copestake and Flickinger, 2000) and the German Grammar (GG) (Muller and Kasper, 2000; Crysmann, 2005; Crysmann, 2007), respectively.


