Markert and Nissim (2002) outlined a corpusbased approach to proper name metonymy as a semantic classification problem that forms the basis of the 2007 SemEval metonymy resolution task. 
SemEval best gives the best results obtained on each task in the SemEval 2007 task (Markert and Nissim, 2007). 
For more details on the data sets, see the task description paper Markert and Nissim (2007). 
The supervised approach to resolving metonymies was encouraged by the metonymy resolution task at the semantic evaluation exercise SemEval 2007 (Markert and Nissim, 2007). 
Tables 3 and Table 4 show the results obtained, and the baseline and the best results from the SemEval task for comparison (Markert and Nissim, 2007). 
