Inmoredetail,wefirst pre-processed the dataset and marked up gene entities with an NER system (Alex et al., 2007; Grover et al., 2007).16 The entities were also tagged with the 15This assumption is not strictly true because each dataset may contain genes of other species, and it would be hard to assesshowtrueitisasabstractsintheBioCreAtIvE GN datasets are not normalised to an entity level.


Several techniques for nested NER in GENIA where presented in (Alex et al., 2007).


