However, the semantic interpretation of thematic roles is generally inconsistent across verbs (Lowe et al., 1997; Kaisser and Webber, 2007).


Kaisser and Webber (2007) apply semantic c2008.


Recent work (Shen and Lapata, 2007; Kaisser and Webber, 2007) that falls outside the scope of this paper, but that is worth mentioning successfully applies semantic roles to question answering.


Predicate-argument structure identified in this way can then be used in tasks like information extraction (Surdeanu et al., 2003) and question answering (Kaisser and Webber, 2007).


