Previous standalone WSD tasks based on parallel data have obtained distinct translations for senses as listed in a dictionary (Ng and Chan, 2007).


This sense inventory is then used to collect training from parallel data (Ng and Chan, 2007).


Resnik and Yarowsky (2000) also conducted their experiments using words in context, rather than a predefined 77 sense-inventory as in (Ng and Chan, 2007; Chan and Ng, 2005), however in these experiments the annotators were asked for a single preferred translation.


