(Pestian et al., 2007) To the best of our knowledge, the systems reported were all adopting a flat classification approach in which a dedicated classifier has been built for every targeted ICD-9-CM code.


(Pestian et al., 2007) The ICD-9-CM 1, which stands for International Classification of Diseases, 9th Revision, Clinical Modification, is an international standard which is used for classifying common medical concepts, such as diseases, symptoms and signs, by hospitals, insurance companies, and other health organizations.


(Goldstein et al., 2007; Farkas and Szarvas, 2007; Crammer et al., 2007; Aronson et al., 2007; Patrick et al., 2007) Aronson et al.


(Liu et al., 2005; Yang et al., 2003) 67 2 Related Works Most top systems in the 2007 Computational Medicine Challenge have benefited from incorporating domain knowledge of free-text clinical notes, such as negation, synonymy, and hypernymy, either as hand-crafted rules in a symbolic approach, or as carefully engineered features in a machinelearning component.


Other work addressed the identification of medical problems in clinical text (Aronson et al. 2007; Meystre and Haug, 2005).


