138 ID Participant cmu-uka Carnegie Mellon University, USA (Paulik et al. , 2007) cmu-syntax Carnegie Mellon University, USA (Zollmann et al. , 2007) cu Charles University, Czech Republic (Bojar, 2007) limsi LIMSI-CNRS, France (Schwenk, 2007) liu University of Linkoping, Sweden(Holmqvist et al. , 2007) nrc National Research Council, Canada (Ueffing et al. , 2007) pct a commercial MT provider from the Czech Republic saar Saarland University & DFKI, Germany (Chen et al. , 2007) systran SYSTRAN, France & U. Edinburgh, UK (Dugast et al. , 2007) systran-nrc National Research Council, Canada (Simard et al. , 2007) ucb University of California at Berkeley, USA (Nakov and Hearst, 2007) uedin University of Edinburgh, UK (Koehn and Schroeder, 2007) umd University of Maryland, USA (Dyer, 2007) upc University of Catalonia, Spain (Costa-Juss`a and Fonollosa, 2007) upv University of Valencia, Spain (Civera and Juan, 2007) Table 1: Participants in the shared task.


This basic architecture of the system is identical to the one used in the 2007 WMT evaluation(Schwenk, 2007a).


This approach was successfully used in large vocabulary continuous speech recognition (Schwenk, 2007b) and in a phrase-based SMT systems (Schwenk et al., 2006; Dechelotte et al., 2007).


