(2008) proposed an ITGbased method for hypothesis alignment, Rosti et al. 
One approach to system combination uses confusion networks (Rosti et al., 2008; Karakos et al., 2008). 
On NIST MT05 test set, the lattice-based system gave better results with an absolute improvement of 1.23 BLEU points over the confusionnetwork-based system (He et al., 2008) and 3.73 BLEU points over the best single system. 
(2008)) and the ITG-based alignment (Karakos et al. 
One uses confusion network decoding to combine translation systems as described in (Rosti et al., 2008) and (Karakos et al., 2008). 
