A similar approach at the level of unigram matching has been used by the well-known METEOR metric (Agarwal and Lavie, 2008), which proved its qualities during the previous MT evaluation task in 2008 (CallisonBurch et al., 2008). 
Only the METEOR-System (Agarwal & Lavie, 2008) is a step in this direction. 
 Meteor (Agarwal and Lavie, 2008)Meteor measures precision and recall for unigrams and applies a fragmentation penalty. 
In this paper we report case-insensitive Bleu scores (Papineni et al., 2002), unless otherwise stated, calculated with the NIST tool, and caseinsensitive Meteor-ranking scores, without WordNet (Agarwal and Lavie, 2008). 
However, at the sentence level, due to data sparseness the results tend to be unsatisfactory (Agarwal & Lavie, 2008; Callison-Burch et al., 2008). 
