Word alignments were generated using Model 4 (Brown et al., 1993) using the multi-threaded implementation of GIZA++ (Och and Ney, 2003; Gao and Vogel, 2008).


After parsing, we re-extracted the leaf nodes of the parse trees and statistically word-aligned the corpus using a multi-threaded implementation (Gao and Vogel, 2008) of the GIZA++ program (Och and Ney, 2003).


We used a multi-threaded version of the GIZA++ tool (Gao and Vogel, 2008).2 This speeds up the process and corrects an error of GIZA++ that can appear with rare words.


