Specifically, we follow the pre-translation reordering approach of Elming (2008). 
One particular variety of this approach, proposed by Elming (2008), uses a large set of linguistic features to automatically learn reordering rules. 
By contrast, other studies (Crego and Mario, 2007; Zhang et al., 2007; Li et al., 2007; Elming, 2008) are more in the spirit of PSMT, in that multiple reorderings are presented to the PSMT system as (possibly weighted) options that are allowed to contribute alongside other parameters. 
5.1 The reordering approach Similar to Elming (2008), the integration of the rule-based reordering in our PSMT system is carried out in two separate stages: 1. 
This is a new result compared to Elming (2008), where results on manual alignments only are reported. 
