W08-1117:1	137:215	ich hatte gerne) 133 5 Results The results concerning users attitudes and alignment are presented in detail in (Kruijff-Korbayova and Kukina, 2008).
---------------------------------------------------
W08-1117:2	118:215	The setup (see Figure 2), participants, procedure and collected data are described in detail in (Kruijff-Korbayova and Kukina, 2008), and summarized below.
---------------------------------------------------
W08-1117:3	143:215	(A detailed description of the indices including the contributing factors from the questionnaires can be found in (Kruijff-Korbayova and Kukina, 2008).)
---------------------------------------------------
