P09-1018:1	39:234	This is achieved by optimizing the regression learning models output to correlate against a set of training examples, where the source sentences are provided with several reference translations, instead of manually labeling the translations produced by various systems with quantitative assessments as described in (Albrecht and Hwa, 2007; Duh, 2008).
---------------------------------------------------
P09-1018:2	102:234	Duh (2008) proposed a ranking method to compare the translations proposed by several systems.
---------------------------------------------------
