W09-0405:1	18:116	Accordingly, we are not able to restrict ourselves to a certain class of systems as (Eisele et al., 2008) did.
---------------------------------------------------
W09-0405:2	7:116	Previous work on building hybrid systems includes, among others, approaches using reranking, regeneration with an SMT decoder (Eisele et al., 2008; Chen et al., 2007), and confusion networks (Matusov et al., 2006; Rosti et al., 2007; He et al., 2008).
---------------------------------------------------
W09-0405:3	16:116	2 Integrating Multiple Systems of Unknown Type and Quality When comparing (Eisele et al., 2008) to the present work, our proposal is more general in a way that the requirement for knowledge about the systems is minimum.
---------------------------------------------------
W09-0405:4	8:116	The approach by (Eisele et al., 2008) aimed specifically at filling lexical gaps in an SMT system with information from a number of RBMT systems.
---------------------------------------------------
W09-0405:5	21:116	While (Eisele et al., 2008) included translations from all of a fixed number of RBMT systems and added one feature to the translation model for each system, integrating all given system outputs in this way in our case could expand the search space tremendously.
---------------------------------------------------
W09-0405:6	51:116	In contrast to the prior approach presented in (Chen et al., 2007) and (Eisele et al., 2008) which concatenates the phrase tables and adds new features as system markers, our extension method avoids duplicate entries in the final combined table.
---------------------------------------------------
