Later, they improved the combination of their various lexical and grammatical features using regression methods (Heilman et al., 2008).


However they conflict with Heilman et al.s (2008) conclusion that the PO model performed better than the MLR one.


Recent NLP perspective have either considered difficulty as an ordinal variable (Heilman et al., 2008), making use of logistic regression, or as a nominal one, implementing classifiers such as the naive Bayes, SVM or decision tree.


The document word frequency vector is comparable to the semantic component of the machine learning approach used by (Heilman et al., 2008).


Further recent refinements in methods for readability prediction include using machine learning methods such as Support Vector Machines (Schwarm and Ostendorf, 2005), log-linear models (Heilman et al., 2008), k-NN classifiers and combining semantic and grammatical features (Heilman et al., 2007).


