W09-1304:1	73:243	3 Hedge cues in the BioScope Corpus The system has been developed using the BioScope corpus (Szarvas et al., 2008; Vincze et al., 2008)2, a freely available resource that consists of medical and biological texts.
---------------------------------------------------
W09-1304:2	20:243	This means that for a sentence like the one in Example (1) taken from the BioScope corpus (Szarvas et al., 2008), the system performs two actions: first, it detects that suggest, might, and or are hedge signals; second, it detects that suggest has as its scope expression of c-jun, jun B and jun D genes might be involved in terminal granulocyte differentiation or in regulating granulocyte functionality, that might has as its scope be involved in terminal granulocyte differentiation or in regulating granulocyte functionality, and that or has as its scope in regulating granulocyte functionality.
---------------------------------------------------
D08-1075:3	75:253	3 Corpus The corpus used is a part of the BioScope corpus (Szarvas et al., 2008)1, a freely available resource that consists of medical and biological texts.
---------------------------------------------------
D09-1145:4	135:257	4.1.3 Surrounding Words Recent studies showed that using machine learning with variants of the bag-of-words feature representation is effective in classifying sentences as speculative vs. non-speculative (Light et al., 2004; Medlock and Briscoe, 2007; Szarvas, 2008).
---------------------------------------------------
D09-1145:5	19:257	Previous studies focus on identifying speculative sentences (Light et al., 2004; Medlock and Briscoe, 2007; Szarvas, 2008; Kilicoglu and Bergler, 2008).
---------------------------------------------------
D09-1145:6	238:257	Previous studies classify sentences as speculative or not, therefore implicitly assigning the scope of a speculation to the whole sentence (Light et al., 2004; Medlock and Briscoe, 2007; Szarvas, 2008; Kilicoglu and Bergler, 2008).
---------------------------------------------------
W09-1105:7	12:254	For a sentence like the one in Example (1) taken from the BioScope corpus (Szarvas et al., 2008), the system detects that lack, neither, and nor are negation signals; that lack has as its scope lack of CD5 expression, and that the discontinuous negation signal neither  nor has as its scope neither to segregation of human autosome 11, on which the CD5 gene has been mapped, nor to deletion of the CD5 structural gene.
---------------------------------------------------
W09-1105:8	66:254	3 Negation in the BioScope Corpus The system has been developed using the BioScope corpus (Szarvas et al., 2008; Vincze et al., 2008)1, a freely available resource that consists of medical and biological texts.
---------------------------------------------------
