Proceedings of the 22nd International Conference on Computational Linguistics (Coling 2008), pages 153160 Manchester, August 2008 Hybrid processing for grammar and style checking Berthold Crysmann, Nuria Bertomeu, Peter Adolphs, Dan Flickinger, Tina Kluwer  Universitat Bonn, Poppeldorfer Allee 47, D-53115 Bonn, {bcr,tkl}@ifk.uni-bonn.de  Zentrum fur Allgemeine Sprachwissenschaft, Berlin, nuria.bertomeu@dfki.de  DFKI GmbH, Berlin, {peter.adolphs,kluewer}@dfki.de  CSLI, Stanford University, danf@csli.stanford.edu Abstract This paper presents an implemented hybrid approach to grammar and style checking, combining an industrial patternbased grammar and style checker with bidirectional, large-scale HPSG grammars for German and English.


For German, we have not created a specific statistical model yet, but, instead, we have used an existing parse selection model (Crysmann, 2008) and combined it with some heuristics which enable us to select the best error hypothesis.


