Natural examples test interactions between phenomena such as noun complementation and copular constructions, while hand-crafted examples allow isolation of the phenomenon and show that all cases are being tested (Cohen et al., 2008), e.g., that the correct entailments emerge under negation as well as in the positive case.


The majority of the testsuites are organized by syntactic and semantic phenomena and are designed to test all known variants of that phenomenon (see (Cohen et al., 2008) on the need to use testsuites designed to test system coverage as well as real-world corpora).


