This breaks down a coherent distribution over morphosyntactic representations realizing grammatical relations to arbitrary position-dependent fragments, which results in larger grammars and inferior performance.14 13The startegy of adding grammatical functions as statesplits is used in, e.g., German (Rafferty and Manning, 2008).


842 Rafferty and Manning, 2008).


Empirically quantifying the effects of different modeling choices has been addressed for English by, e.g., (Johnson, 1998; Klein and Manning, 2003), and for German by, e.g., (Dubey, 2004; 1Consider, e.g., The PaGe shared task on parsing German (Kubler, 2008), reporting F175,F179,F183 for the participating parsers.


