2 Related Work Knowledge-rich methods Models employing manual crafting of (typically complex) representations of content have generally captured one of three types of knowledge (Rambow, 1990; Kittredge et al. , 1991): domain knowledge [e.g. , that earthquakes have magnitudes], domainindependent communication knowledge [e.g. , that describing an event usually entails specifying its location]; and domain communication knowledge [e.g. , that Reuters earthquake reports often conclude by listing previous quakes2].


Formalisms exemplifying each of these knowledge types are DeJongs (1982) scripts, McKeowns (1985) schemas, and Rambows (1990) domain-specific schemas, respectively.


Rambow (1990) argues that domain-specific communication knowledge must be used (whether implicitly or explicitly) in all planned communica676 Johanna D. Moore and C6cile L. Paris Planning Text for Advisory Dialogs tion, and advocates that domain communication knowledge be represented explicitly.


While we were able to exploit existing research for many of the design issues, it turned out that we needed to develop our own approach to text planning (Rambow 1990).


