Classification of Machine Translation Divergences The divergence problem in machine translation has received increasingly greater attention in recent literature (see, for example, Barnett et al. 1991a, 1991b; Beaven 1992a, 1992b; Dorr 1990a, 1990b; Kameyama et al. 1991; Kinoshita, Phillips, and Tsujii 1992; Lindop and Tsujii 1991; Tsujii and Fujita 1991; Whitelock 1992; related discussion can also be found in work by Melby \[1986\] and Nirenburg and Nirenburg \[1988\]).


(See Barnett et al. 1991a, 1991b; Carbonell and Tomita 1987; Meyer, Onyshkevych, and Carlson 1990; Nirenburg, Raskin, and Tucker 1987; Nirenburg and Goodman 1990; Nirenburg and Levin 1989; Wilks 1973; among others, for descriptions of interlingual machine translation approaches that take into account knowledge outside of the domain of lexical semantics).


