The undecidability of the generation problem in (3) was shown for definite clause grammars by Dymetman (1991), who reduced the problem to Hilbert's Tenth Prob* Institute for Natural Language Processing, University of Stuttgart, Azenbergstr.


Our proof dei)ends on the fact that the int)ut F--and hence the range of q5-is fully specified; Dymetman (1991), van Noord (1993), and Wedekind (1.999) have shown that the general probleln of generating froln an underspecified input is unsolvable.


