A92-1012:1	57:217	The differentia can be partially interpreted relative to the RQS type; in this example < rqs : origin > = "kip" is an indication that kippevlees comes from kip; eventually this will allow their lexical entries to be linked automatically by the appropriate lexical rule (Copestake and Briscoe, 1991; Copestake et al. , 1992).
---------------------------------------------------
C94-2110:2	6:126	Some illustrative examples are given in (1) where  move can be interpreted as a psychological verb when used transitively with a sentient direct object, * enjoy can take either a noun or verb phrase complement when used in the expeT~ence sense (Pustejovsky, 1991, 1993; Briscoe, Copestake & Boguraev, 1990),, accord is synonymous with either agree or give/granl depending on its valency (Poznafiski & Sanfilippo, 1993), and * the occurrence of a directional argument with swim triggers a shift in aspectual interpretation.
---------------------------------------------------
J92-2004:3	187:213	5 Their approach is further elaborated in Briscoe and Copestake (1991) and Copestake and Briscoe (1991).
---------------------------------------------------
W96-0308:4	47:335	(1987) who posit an underspecified and impoverished lexical semantic representation which is enriched through an open-ended process of abductive or deductive reasoning with world (or domain) knowledge" (Copestake & Briscoe, 1991:88).
---------------------------------------------------
W96-0308:5	103:335	Copestake and Briscoe (1991) mention that they regard the metaphoric extension involving use of a word denoting an animal to refer to humans as involving a core component that should be expressed as a lexical rule (1991:89).
---------------------------------------------------
W96-0308:6	21:335	Within this class would fall the Lexical Implication Rules (LIRs) of Ostler and Atkins (1991), the lexical rules of Copestake and Briscoe (1991), the Generative Lexicon of Pustejovsky (1995), and the ellipsis recovery procedUres of Viegas and Nirenburg (1995).
---------------------------------------------------
W96-0308:7	233:335	For example, Copestake and Briscoe (1991) discusses primarily the grinding rule, which creates a mass noun denoting substance out of a count noun.
---------------------------------------------------
P96-1005:8	16:157	It has been lately incorporated into computational lexicography in (Atkins, 1991), (Ostler and Atkins, 1992), (Briscoe and Copestake, 1991), (Copestake and Briscoe, 1992), (Briscoe et al. , 1993)).
---------------------------------------------------
