In Dorr (1991), we discussed the selection of the lexical connective when on the basis of the temporal relation between the main or matrix clause and the subordinate or adjunct clause.


The system includes a two-level model of knowledge representation (KR) (see figure 2(a)) in the spirit of Dorr (1991).


INTRODUCTION This paper discusses how the two-level knowledge representation model for machine translation presented by Dorr (1991) integrates aspectual information with lexical-semantic information by means of parameterization.


See Dorr (1991) and Dorr and Gaasterland (submitted) for more details about the relationship between temporal information and aspectual information and the actual procedures that are used for the selection of temporal connectives.


