A discussion of this may be found elsewhere (Vander Linden 1993a).


IMAGENE contains a sub-network implementing these two processes that is currently very preliminary (Vander Linden 1993c).


More detail on the database can be found elsewhere (Vander Linden 1993c).


The current study has conflated them, as the instructional texts have not tended to display the complex intentional structure common to persuasive texts and interactive discourses (Vander Linden 1993b).


