Grishman & Sterling (1992), Poznanski & Sanfilippo (1993), Resnik (1993), Ribas (1994) and others have shown that it is possible to acquire selection preferences from (partially) parsed data.


So although it is now possible to extract at least subcategorisation data from large corpora 2 with 2Grishman & Sterling (1992), Poznanski & Sanfilippo (1993), Resnik (1993), Pdbas (1994), McCarthy (1997) and others have shown that it is possible also to a119 some degree of reliability, it would be difficult to integrate the data into this type of parsing system.


