Structuring Two-Medium Dialog for Learning Language and Other Things Henry Hamburger George Mason University; Fairfax, VA, USA Dan Tufts Research Institute for Informatics; Bucharest, Romania Raza Hashim Bridgewater College; Bridgewater, VA, USA OVERVIEW: Naturalistic two-medium communication with a computational system, using both language and interactive graphics (Cohen, 1991; Maier, 1993; McKeown, 1993), is an important practical complement to studies that involve only language, only graphics and/or only people.


