A concept-based model for WSD requires less parameter and has an element of generality built in (Liddy and Paik 1993).


Liddy, E.D., McVenrry, K. , Paik, W. , Yu, E.S. & McKenna, M, (1993).


One effort is to extend the symbolic level of natural language processing developed during Phase I of TIPSTER by such efforts as the extension of the subject code vector algorithm into the multi-lingual environment (Liddy et al, 1993a); the development of new corpus analysis techniques for the expansion of complex nominals into their synonymous phrasings, and; the automatic construction of proper noun knowledge bases over time and multiple texts, for the purpose of cross-document inferencing in response to complex queries requiring extensive relational information (Paik, In press).


