TFP stands for Tagged Text Parser, and it has I:een described in detail in (Strzalkowski, 1992) and ev~duated in (Strzalkowski & Scheyen, 1993).


5 Full details of TTP parser have been described in the TREC-1 report (Strzalkowski, 1993a), as well as in other works (Strzalkowski, 1992; Strzalkowski & Scheyen, 1993).


This design has already shown some promise in producing a better performance than the base statistical system (Strzalkowski, 1993b).


