(Basili et al.1993a), Basili, R. , M.T. Pazienza, P. Velardi, (19931.


(Basill et al.1993b), Basili, R. , M.T. Pazienza, P. Velardi, (19931.


Among the applications of collocational analysis for lexical acquisition are: the derivation of syntactic disambiguation cues (Basili et al. 1991, 1993a; Hindle and Rooths 1991,1993; Sekine 1992) (Bogges et al. 1992), sense preference (Yarowski 1992), acquisition of selectional restrictions (Basili et al. 1992b, 1993b; Utsuro et al. 1993), lexical preference in generation (Smadjia 1991), word clustering (Pereira 1993; Hindle 1990; Basili et al. 1993c), etc. In the majority of these papers, even though the (precedent or subsequent) statistical processing reduces the number of accidental associations, very large corpora (10,000,000 words) are necessary to obtain reliable data on a "large enough" number of words.


In (Basili et al., 1997), the lexical knowledge base WordNet (Miller et al., 1993) is used as a bootstrap for verb disambiguation.


Wrong links due to the polysemy can be easily eliminated with exception rules by comparing selectional patterns and generalized contexts (Basili et al., 1993; Grishman and Sterling, 1994).


