Most proper name recognizers that have been reported on in print either take as input text tagged by part-of-speech (e.g. , the systems of (Paik et al. 1993) and (Mani et al. 1993)) or perform syntactic and/or morphological analysis on all words, including capitalized ones, that are part of candidate proper names (e.g. , (Coates-Stephens 1993) and (McDonald 1993)).


Several (e.g. , (McDonald 1993), (Mani et al. 1993), (Paik et al. 1993) and (Cowie et al. 1992)) look in the local context of the candidate proper name for external information such as appositives (e.g. , in a sequence such as Robin Clark, presiden~ of Clark Co).


1 Introduction Name searching, matching, and recognition have been active areas of research for a number of years \[Hickey 1981, Carroll 1985, Rau 1991, Borgman and Siegfried 1992, Paik et al. 1993, Hayes 1994, Proceedings 1995, Pfeiffer et al. 1996\], but relatively little evaluation of either the effectiveness of name searching tools or of the effect of name recognition on relrieval performance has been published.


