(1993)), an intention which has manifested itself in a number of standardized, domain-specific forms of expression commonly used by technical writers (termed Domain Communication Knowledge by Kittredge et al.


This problem may be only rarely encountered in a monolingual context, but is exceedingly common in a multilingual enviromnent (Delin et al. , 1993).


If work in qualitative process theory, using functional-specifications such as those in e.g., (Iwasaki et al. , 1993), can yield the device and world knowledge that are required for text pianning, then the need for cost effectiveness would be met.


