For example, Hindle and Rooth (1993) and Resnik and Hearst (1993) give experimental results on the effectiveness of functions based on lexical associations, or lexical-class associations, at selecting appropriate prepositional phrase attachments. 
In (Resnik and Hearst, 1993) class-based trigrams are obtained by generalizing the PP head, using WordNet synonymy sets. 
Resnik and Hearst (1993) use a similar approach to calculate preferences for prepositional phrase attachment. 
Clusters are created by means of distributional techniques in (Ratnaparkhi et al, 1994), while in (Resnik and Hearst, 1993) low level synonim sets in WordNet are used. 
Subsequently, Hindle and Rooth's work has been extended by Resnik and Hearst (1993). 
