The rhetorical connection between a sentence and surrounding discourse should also be described with adjuncts (Huang, 1994).


Some support for the cache model predictions about popped entities is that (1) rules proposed for deaccenting noun phrases treat popped entities as accessible (Davis and Hirschberg 1988); and (2) rules for referring expressions in argumentative texts treat the conclusions of popped sisters as salient (Huang 1994).


