Our definition of the task elements is based on the concepts and relations commonly chosen to represent a task structure (a goal and its associated plan), e.g., (Fikes and Nilsson, 1971; Sacerdoti, 1977), and on related research, e.g., (Kosseim and Lapalme, 1994).


196 Non-modal Modal Procedure Ready-Reference Elaboration 100.0% 75.0% 72.6% 0.0% 25.0% 28.4% Figure 4: Genre-related differences in the modal system for goal Negative Positive Ready-Reference Elaboration 0.0% 41.7% 100% 58.3% Figure 5: Genre-related differences in the polarity system for constraint Imperative Declarative Procedure Ready-Reference Elaboration 97.3% 44.4% 77.6% 2.7% 55.6% 22.4% Figure 6: Genre-related differences in the mood system for substep 9 Related Work The results from our linguistic analysis are consistent with other research on sublanguages in the instructions domain, in both French and English, e.g., (Kosseim and Lapalme, 1994; Paris and Scott, 1994).


, 1990; Ghadessy, 1993; Kosseim and Lapalme, 1994).


In terms of Rhetorical Structure Theory (RST) (Mann and Thompson, 1987), it is considered that the basic structure of such kind of discourse is constructed by connecting segments that refer to goals or primitive actions with "sequence" relation (RSsner and Stede, 1992; Kosseim and Lapalme, 1994).


