For example, discussing the possible adaptation of Phillips' algorithm to incremental generation, Lager and Black (1994) point out that some versions of Categorial Grammar (CG) would make the generator more talkative, by giving rise to "a more generous notion of constituency".


Lager and Black (1994), discussing"the PLUS surface generator, suggest that the algorithm and the QLF are suitable for incremental generation.


