P95-1025:1	180:187	However, fully automatic lexically based approaches 3 Hatzivassiloglou (1994) shows that the introduction of linguistic cues improves the performance of a statistical semantic knowledge acquisition system in the context of word grouping.
---------------------------------------------------
J96-1001:2	93:576	Other recent related work aims at using statistical techniques to produce translations of single words (Fung and McKeown 1994; Wu and Xia 1994; Fung 1995b) Smadja, McKeown, and Hatzivassiloglou Translating Collocations for Bilingual Lexicons as opposed to collocations or phrases.
---------------------------------------------------
