Note that the notion of core is related to the notions of nucleus in RST, intended effect in (Young and Moore, 1994), and of point of a move in (Elhadad and McKeown, 1990), and that text generators representing these notions exist.


2 Towards a solution Our solution is based on the integration of a principled discourse planner, LONGBOW \[Young and Moore, 1994; Young et al. , 1994\], with a formalism that represents both lexical semantic knowledge about verbs and planning knowledge about tim actions that the verbs denote \[Di Eugenio, 1993: Di Eugenio and Webber, 1996\].


For this process, we use LONCBOW, a domain-independent discourse planner originally developed as part of a project aimed at generating tutorial explanations (Young and Moore 1994).


For a complete definition of the algorithm, its computational properties, and its utility for discourse planning, see Young, Pollack, and Moore (1994), and Young and Moore (1994).


It describes an implemented system that integrates two robust systems: SAGE--an intelligent graphics presentation system (Roth et al. 1994), and a natural language generator, consisting of a text planner (Young and Moore 1994; Young 1997), a microplanner implementing tactical decisions, and a sentence realizer (Elhadad and Robin 1992).


