(Viegas and Bouillon, 1994) showed that we can reduce the set of what are conventionally considered as idiosyncrasies by difl>rentiating "true" idiosyncrasies (difficult to derive or calculate) from expressions which have well-defined calculi, being compositional in nature, and that have been called semantic collocations.


We further distinguished the notion of idiosyncrasies as defined in (Viegas and Bouillon, 1994), into restricted semantic co.occurrenccs and restricted lexical co-occurrences.


We build on the existing insights of linguists (including (Pustejovsky, 1991; Mel'Euk and Polgu~re, 1987; Nunberg et al. , 1994)) and implementations (including (Reiter and Dale, 1992; Viegas and Bouillon, 1994; Smadja and McKeown, 1991)).


For example, (Viegas and Bouillon, 1994) handle semantic collocations by implementing Pustejovsky's Generative Lexicon Theory (GLT); modifiers take on specialized meanings derived from salient processes and characteristics associated with the heads they modify.


