Other theoretical frameworks that have been implemented to a greater or lesser extent include lexical phonology (Williams 1991), autosegmental phonology (Bird 1990; Albro 1994; Bird and Ellison 1994), diachronic phonology (Hewson 1974; Eastlack 1977; Lowe and Mazaudon 1989), inheritance-based models (Daelemans 1987; Reinhard and Gibbon 1991) and connectionist models (see the next paragraph on learning).


(~) 1994 Association for Computational Linguistics Computational Linguistics Volume 20, Number 3 parsing (e.g. chart parsing \[Church 1987\]), or where a formal system developed for semantic representations of tense is applied to the temporal structure of phonology (Bird and Klein 1990), or where complex arrangements of phonological features are represented in the familiar notation of attribute-value matrices (Wiese 1990).


Other work in this area is to be found in the Proceedings of the First Meeting of the ACL Special Interest Group in Computational Phonology, published by the ACL in 1994, and in two edited collections (Bird 1991; Ellison and Scobbie 1993).


Rather, I shall loosely classify a selection of the work based on the formal method used: unification (Carson 1988; Chung 1990; Coleman 1991; Scobbie 1991; Broe 1993; Walther 1993), predicate logic (Bird 1990; Bouma 1991; Russell 1993), modal logic (Bird and Blackburn 1991; Calder and Bird 1991), type theory (Klein 1991; Mastroianni 1993), categorial grammar/logic (Wheeler 1981; Dogil 1984; van der Linden 1991; Oehrle 1991; Steedman 1991; Moortgat and Morrill to appear), finite-state devices (Kay 1987; Kornai 1991; Wiebe 1992; Bird and Ellison 1994), electrical circuitry (Gilbers 1992), and formal language theory (Ristad 1990; Kornai 1991; Ritchie 1992; Wiebe 1992).


Examples of the second type are all symbolic (Johnson 1984; Dresher and Kaye 1990; Ellison 1993; Bird 1994).


