P97-1030:1	92:188	The context tree was originally introduced in the field of data compression (Rissanen, 1983; Willems et al. , 1995; Cover and Thomas, 1991) to represent how many times and in what context each symbol appeared in a sequence of symbols.
---------------------------------------------------
P97-1030:2	170:188	6 Related Work Although statistical natural language processing has mainly focused on Maximum Likelihood Estimators, (Pereira et al. , 1995) proposed a mixture approach to predict next words by using the Context Tree Weighting (CTW) method .(Willems et al. , 1995).
---------------------------------------------------
P97-1030:3	120:188	p(ats) _ n(als) ~bc_.a n(bls) We introduce an information-theoretical criteria A(sb) (Weinberger et al. , 1995) to evaluate the gain of expanding a node s by its daughter sb.
---------------------------------------------------
W96-0102:4	128:379	The window size used by the algorithm will also dynamically change depending on the information present in the context for the disambiguation of a particular focus symbol (see Schfitze et al. , 1994, and Pereira et al. , 1995 1ACL Data Collection Initiative CD-ROM 1, September 1991.
---------------------------------------------------
