The Collins and Brooks (1995) model scores 84.5% accuracy on this task, and is one of the most accurate models that do not use additional supervision. 
3 Back-off Estimation The PP attachment model presented by Collins and Brooks (1995) determines the most likely attachment for a particular prepositional phrase by estimating the probability of the attachment. 
Our notation fol1Other relevant parsers simultaneously consider two or more words that are not necessarily in a dependency relationship (Lafferty et al. , 1992; Magerman, 1995; Collins and Brooks, 1995; Chelba and Jelinek, 1998). 
et al., 1994; Brill and Resnik, 1994; Collins and Brooks, 1995; Merlo et al., 1997). 
Statistical and information theoretic approaches (Hindle and Rooth, 1993), (Ratnaparkhi et al. , 1994),(Collins and Brooks, 1995), (Franz, 1996) Using lexical collocations to determine PPA with statistical techniques was first proposed by (Hindle and Rooth, 1993). 
