Information Content Resnik (1995) proposed a word sense disambiguation algorithm which determ~ the senses of words in noun groupings. 
Resnik (1993; 1995) use classes in Wordnet (Fellbaum, 1998) and a measure of conceptual association to generalize over the nouns. 
This is based on the technique Resnik (1995) uses for disambiguating noun groups. 
At present, we are trying to integrate the word sense disambiguation method proposed in (Resnik, 1995) into our system. 
An adaptation of Lesk dictionary-based WSD algorithm has been used to disambiguate adjectives and adverbs (Banerjee and Pedersen, 2002), an adaptation of the Resnik algorithm has been used to disambiguate nouns (Resnik, 1995), while the algorithm we developed for disambiguating verbs exploits the nouns in the context of the verb as well as the nouns both in the glosses and in the phrases that WordNet utilizes to describe the usage of a verb. 
