6, Communications of COLIFS \[ 13 \] Wang Kai-zhu, et al, ~ff1~ ~'~7h~r~ (Study of Nondictionay Chinese Segmentation), ~t'~f~-~ ~~ ( Advances and Applications on Computational Linguistics), Tsinghua University Press, 1995, 359 \[ 14 \] Zhang Shu-wu, et al, ~i~i~-~'~qf~/lflffzd=~s37~l~~'~'~'~r~ (An Automat*c Buildng Method of Electronic Dictionary Used for Chinese Speech Recognition), "bt'~ ~ ~-~I~ ( Advances and Applications on Computational Linguistics), T$inghua University Press, 1995, 219 -224 \[ 15 \] Zhou J. and Dapkus P. , Automatic suggestion ofszgnificant terms for a predefined topic, Proceedings of Third the Workshop on Very Large Corpora, I31-147, 1995


(For a complete description of the algorithm and preliminary experiments, please refer to Zhou and Dapkus 1995).


