1 The DOP1 model, and some variations of it, have been tested by Bod (1993-1995), Sima'an (1995-1996), Sekine & Grishman (1995), Goodman (1996), and Charniak (1996). 
A second layer was added to the framework to map from phonemes to speech; these extensions are described in more detail in (de Marcken, 1995b). 
The latter approach has become increasingly popular (e.g. Schabes et al. , 1993; Weischedel et al. , 1993; Briscoe, 1994; Magerman, 1995; Collins, 1996). 
Estimating phrase structure grammars by minimizing the training corpus on41 tropy does not lead to the desired grammars which is consistent with human intuitions (de Marcken, 1995). 
1 Introduction The Data-Oriented Parsing (DOP) method suggested in Scha (1990) and developed in Bod (19921995) is a probabilistic parsing strategy which does not single out a narrowly predefined set of structures as the statistically significant ones. 
