At first, Fung (1995) utilized context heterogeneity for bilingual dictionary extraction. 
(Rapp, 1995; Fung and McKcown, 1997) suggest that a content word is closely associated with some words in its context. 
Some of the early statistical terminology translation methods are (Brown et al., 1993; Wu and Xia, 1994; Dagan and Church, 1994; Gale and Church, 1991; Kupiec, 1993; Smadja et al., 1996; Kay and RSscheisen, 1993; Fung and Church, 1994; Fhmg, 1995b). 
The work by Fung and McKeown (1994) and Fung (1995b) is notable for its use of techniques suitable to Asian/Romance language pairs as well as Romance language pairs. 
Among these, (Rapp, 1995) proposes that the association between a word and its close collocate is preserved in any language, and (Fung and McKeown, 1997) suggests that the associations between a word and many seed words are also preserved in another language. 
