Melamed (1995) used the ratio (LCSR) between the length of the LCS of two words and the length of the longer word of the two words to measure the cognateness between them. 
SABLE uses token co-occurrence statistics to induce an initial translation lexicon, using the method described in (Melamed, 1995). 
Following Melamed (1995), we measured the orthographic similarity using longest common subsequence ratio (LCSR), which is defined as follows: LCSR(s1,s2) = |LCS(s1,s2)|max(|s1|,|s2|) where LCS(s1,s2) is the longest common subsequence of s1 and s2, and |s| is the length of s. Following Nakov et al. 
In other cases, they can be constructed automatically or semi-automatically using any of several methods (Fung, 1995; Melamed, 1996c; Resnik & Melamed, 1997). 
Acuracy and coverage roughly correspond to Melameds precision and percent correct respectively (Melamed, 1995). 
