The only prohibited arrangements are "inside-out" transformations (Wu, 1995b), which we have been unable to find any examples of in our corpus. 
For instance, we previously reported a method for improving search times in channel translation models that exploits bracketing information (Wu and Ng, 1995). 
We summarize here; details are given elsewhere (Wu, 1995b). 
Specifically, the model employs a bracketing transduction grammar or BTG (Wu, 1995a), which is a special case of inversion transduction grammars or ITGs (Wu, 1995c; Wu, 1995c; Wu, 1995b; Wu, 1995d). 
The corpus was sentence-aligned statistically (Wu, 1994); Chinese words and collocations were extracted (Fung and Wu, 1994; Wu and Fung, 1994); then translation pairs were learned via an EM procedure (Wu and Xia, 1995). 
