Interesting results on applicability of semantic filtering to synt~tic data, for the purpose of acquiring verb argument information is reported in (Dorr and Jones,1996).


2.1 Ambiguities in Levin classes It is not clear how much WordNet synsets should be expected to overlap with Levin classes, and preliminary indications are that there is a wide discrepancy (Dorr and Jones, 1996), (Jones and Onyshkevych, 1997), (Doff, 1997).


