In other cases, the text is mapped onto predetermined genre-specific layout patternsfor example, for verbalizing mathematical proofs (Huang and Fiedler 1997) or producing letters for customers (Coch 1996).


265 We reserve a more detailed comparison with PENMAN and FUF, as well as with AlethGen/GL (Coch, 1996) (which is perhaps the system most similar to REALPRO, since they are based on the same linguistic theory and are both implemented with speed in mind), for a more extensive paper.


It uses GSi-Erli's AlcthGen text generation toolbox (see (Coch, 1996)).


