1 Introduction In Japanese, around 95% word segmentation accuracy is reported by using a word-based language model and the Viterbi-like dynamic programming procedures (Nagata, 1994; Yamamoto, 1996; Takeuchi and Matsumoto, 1997; Haruno and Matsumoto, 1997).


Other approaches bootstrap from an initial segmentation provided by a baseline algorithm such as Juman (Matsukawa et al. , 1993; Yamamoto, 1996).


al. 1993; Brill 1994; Nagata 1994; Yamamoto 1996).


