Cardie (1996) presents an attribute selection approach to natural language processing (relative pronoun disambiguation) incorporating a small set of linguistic biases (to be determined by experts).


The following essential factors motivate our definition for relation features:  The relation features should be selected from multiple linguistic levels, i.e., morphology, grammar and semantics (Cardie, 1996);  They can help us to identify NERs using positive and negative case-based machine learning as their information do not only deal with NERs but also with non-NERs; and  They should embody the crucial information of Chinese language processing (Dang et al. , 2002), such as word order, the context of words, and particles etc. There are a total of 13 relation features shown in Table 2, which are empirically defined according to the above motivations.


But if we have information about feature relevance, we can add linguistic bias to weight or select different features (Cardie, 1996).


But if we do have some information about feature relevance one possibility would be to add linguistic bias to weight or select different features (Cardie, 1996).


