5 Realizing Summaries To realize the summaries in natural language, we use the FUF/SURGE surface realizer (Elhadad and Robin, 1996) with some changes made to address a few problems encountered with respect to the use of conjunctions and subject-ellipsises. 
FUF comes available with a reusable grammar of English(Elhadad and Robin, 1996). 
Specifically, three linguistic realization packages, FUF/SURGE (Elhadad 1993a, 1993b; Elhadad and Robin 1996), PENMAN/NIGEL (Penman group 1989), and its descendant KPML/NIGEL (Bateman 1997), are widely used in the field. 
SURGE (Elhadad and Robin, 1996) is a comprehensive English Grammar written in FUF. 
Instead, such projects use an off-the-shelf realizer, among which PENMAN (Bateman, 1996) and SURGE/FUF (Elhadad and Robin, 1996) are probably the most popular. 
