The only technique that Caraballo and Charniak (1996) give that took into account the scores of other nodes in the priority function, the "prefix model," required O(n 5) time to compute, compared to our O(n 3) system. 
Comparing Figures of Merit Using a Treebank Grammar 7.1 Background To verify that our results are not an artifact of the particular grammar we chose for testing, we also tested using a treebank grammar introduced in Charniak (1996). 
Collins (personal communication) independently observed the usefulness of this modification, and Caraballo and Charniak (1996) used a related technique in a best-first parser. 
The treebank grammar was introduced in Charniak (1996), and the parser in. 
The best comparison of these functions is due to Caraballo and Charniak (1996; 1997), who tried various prioritization methods. 
