In language modeling for speech recognition improvements in perplexity and word error rate have been observed on English corpora when using language models trained separately for the topic and the focus part of the sentence (Meteer and Iyer, 1996; Ma et al. , 1998).


For example in (Meteer and Iyer, 1996), the division point is placed before the first strong verb, or, in the absence of such a verb, behind the last weak verb of the sentence.


Meteer and Iyer (1996) investigated whether modeling linguistic segments, segments with a single independent clause, improves language modeling.


