We tackle additional examples in (Stone and Doran, 1996).


For example, in (Stone and Doran, 1996), we use reference to properties, actions and belief contexts (Ballim et al. , 1991) to describe semantic collocations (Pustejovsky, 1991) and idiomatic composition (Nunberg et al. , 1994).


In (Stone and Doran, 1996) we explore the use of additional factors, such as attentional state and lexical preferences, in this step.


