 POSTGRAPHE takes tabular data (of the sort found in a typical spreadsheet) and generates a report integrating both graphics and text (Fasciano and Lapalme, 1996).


Conversely, simply placing textual and graphical information together is no guarantee that one view is supportive of another: if the perspective on the data taken in a graphic and that taken in a text have no relation (or, worse, even clash), then the result is incoherence rather than synergy--cf, the discussions by authors such as Arens, Hovy, and Vossers (1993), Fasciano and Lapalme (1996), Green et al.


The rank of instances on an axis, the scales of axes, and visual prompts such as labels and arrows are also dimensions which should be considered (Mittal, 1998; Fasciano and Lapalme, 1996).


Our perspective plays a similar role to that of intention in PostGraphe (Fasciano and Lapalme, 1996).


The POSTGRAPttE system (Fasciano 1996; Fasciano and Lapalme 1996) is the closest related research effort.


