J97-4003:1	304:450	27 Briscoe and Copestake (1996) argue that semi-productivity of lexical rules, which can be understood as a generalization of exceptions to lexical rules, can be integrated with our approach by assigning probabilities to the automaton associated with a particular lexical entry.
---------------------------------------------------
A00-2034:2	45:232	Estimations of productivity have been suggested for controlling the application of alternations (Briscoe and Copestake, 1996).
---------------------------------------------------
P97-1018:3	233:256	Lascarides, A. , E.J. Briscoe, N. Asher and A. Copestake (1996) 'Persistent and Order Independent Typed Default Unification', Linguistics and Philosophy, voi.19:1, 1-89.
---------------------------------------------------
P97-1018:4	18:256	Briscoe and Copestake (1996) argue that a differential estimation of the productivity of derivation processes allows an approximation of the probabilities of previously unseen derived uses.
---------------------------------------------------
P97-1018:5	71:256	As we will see in 4, this means pragmatics 138 Unseen-prob-mass(cmp-form) = number-of-applicable-schemata(cmp-form) I ~eq( cmp-form ) + number-of-applicable-schemata( cmp-form ) Prod(csl) Estimated-freq(interpretationi with cmp-formj) = Unseen-prob-mass(cmp-formj) x ~ Prod(csl)  Prod(cs.,) (where csl  cs, are the compound schemata needed to derive the n unattested entries for the form j) Figure 4: Probabilities for unseen compounds: adapted from Briscoe and Copestake (1996) must find a contextual interpretation.
---------------------------------------------------
P97-1018:6	82:256	We use the following estimate for productivity (adapted from Briscoe and Copestake (1996)): M+I Prod(cmp-schema) N (where N is the number of pairs of senses which match the schema input and M is the number of attested two-noun output forms -we ignore compounds with more than two nouns for simplicity).
---------------------------------------------------
P97-1018:7	77:256	For derived forms, the applicable lexical rules or schemata determine possible senses (Briscoe and Copestake, 1996).
---------------------------------------------------
P97-1018:8	215:256	Briscoe, E.J. and A. Copestake (1996) 'Controlling the application of lexical rules', Proceedings of the A CL SIGLEX Workshop on Breadth and Depth of Semantic Lexicons, Santa Cruz, CA.
---------------------------------------------------
P97-1018:9	234:256	Lascarides, A. and A. Copestake (in press) 'Pragmatics and Word Meaning', Journal of Linguistics, Lascarides, A. , A. Copestake and E. J. Briscoe (1996) 'Ambiguity and Coherence', Journal of Semantics, vol.13.1, 41-65.
---------------------------------------------------
P97-1018:10	109:256	Lascarides, Copestake and Briscoe (1996).
---------------------------------------------------
P99-1051:11	180:212	18 1 0.05 0.648 SLIDE 5 0 0 0 Benefactive alternation Class Total Alt Prod Typ GET 33 17 0.51 0.54 PREPARE 26 9 0.346 0.55 BUILD 35 12 0.342 0.34 PERFORMANCE 19 1 0.05 0.56 CREATE 20 2 0.1 0.05 Table 6: Productivity estimates and typicality values for the dative and benefactive alternation to produce a novel form (Briscoe and Copestake, 1996).
---------------------------------------------------
P99-1051:12	170:212	5 Productivity The relative productivity of an alternation for a se20 mantic class can be estimated by calculating the ratio of acquired to possible verbs undergoing the alternation (Aronoff, 1976; Briscoe and Copestake, Z l0 1996): (5) P(acquired\[class) = f (acquired, class) f (class) o We express the productivity of an alternation for o =.
---------------------------------------------------
J99-4002:13	285:580	Dative Constructions Lascarides, Copestake, and Briscoe (1996) present an account of the dative alternation that illustrates the utility of the TDFS framework for encoding defeasible lexical semantic entailments in terms of Dowty's (1989) proto thematic roles, and the interac4 We omit a formal proof as this would require more detailed specification of the syntactic component than is warranted in the rest of the paper.
---------------------------------------------------
J99-4002:14	472:580	This approach to deriving estimates of the productivity of lexical rules is applied to four denominal verb forma516 Briscoe and Copestake Lexical Rules tion rules in Briscoe and Copestake (1996), where the probabilities of the basic and derived word forms are estimated from part-of-speech tagged textual corpora.
---------------------------------------------------
