(Burstein, et al. , 1996) describe techniques for using lexical semantics to classify responses to test questions.


Until recently, ETS's automated scoring efforts were primarily devoted to the development of computer programs used to score short-answer constructed-responses of up to 15 words (Burstein and Kaplan, 1995 and Burstein et al. , 1996).


I. The scoring technique used in this study was based on a previous method used to score sentence-length responses (Burstein, et al, 1996).


