(Litman, 1996; Mooney, 1996; Vander Linden and Di Eugenio, 1996).


We are currently using this information to drive the generation of warning messages in the DRAFTER system (Vander Linden and Di Eugenio, 1996).


6 Application We have successfully used the correlations discussed here to support the generation of warning messages in the DRAFTER project (Paris and Vander Linden, 1996).


This is discussed in more detail elsewhere (Vander Linden and Di Eugenio, 1996), but in short, we input our 350 coded examples to Quinlan's C4.5 learning algorithm (Quinlan, 1993), which induces a decision tree mapping from the functional features to the appropriate form.


