We present a system, called SUMMONS 1 (McKeown and Radev 1995; Radev 1996; Radev and McKeown 1997), shown in Figure 1, which introduces novel techniques in the following areas:  It briefs the user on information of interest using tools related to information extraction, conceptual combination, and text generation.


1 Introduction In our work to date on news summarization at Columbia University (McKeown and Radev, 1995; Radev, 1996), information is extracted from a series of input news articles (MUC, 1992; Grishman et al. , 1992) and is analyzed by a generation component to produce a summary that shows how perception of the event has changed over time.


