In principle, even a "complete" algorithm that establishes the conceptually superior degree of robustness by means of interaction between structural disambiguation and anaphor resolution is feasible (Stuckardt 1997).


An alternative solution, which is based on the possibly partial but potentially more comprehensive and reliable output of a conventional parser, has been suggested in Stuckardt (1997).


