Additionally, our parser is in some ways similar to the maximum-entropy parser of Ratnaparkhi (1997). 
Such word-based lexicalizations of probability models are used successfully in the statistical parsing models of, e.g., Collins (1997), Charniak (1997), or Ratnaparkhi (1997). 
See Ratnaparkhi (1997) for one example of a method using this approach. 
Finally, our parser is in many ways similar to the parser of Ratnaparkhi (1997). 
criminative models described in (Magerman, 1995; Ratnaparkhi, 1997), the lexicalized PCFG models in (Collins, 1999), the generative model in (Charniak, 2000), the lexicalized TAG extractor in (Xia, 1999) and the stochastic lexicalized TAG models in (Chiang, 2000; Sarkar, 2001; Chen and VijayShanker, 2000). 
