Another line of research, which is more closely related to the current study, is to extend existing thesauri by classifying new words with respect to their given structures (e.g. Tokunaga et al., 1997; Pekar, 2004). 
3 Related Work ~brm Semantic Ca, teg'orizat, ion is on several aspects similar to _Th(;sam'us l~2xtension (Uramoto, 1996; Tokunaga et al. , 1997). 
Another line of research, which is more closely related with the current study, is to extend existing thesauri by classifying new words with respect to their given structures (e.g. Tokunaga et al. , 1997; Pekar, 2004). 
We adopted an evaluation scheme similar to that detlned in (Tokunaga et al. , 1997) for thesaux'us extension. 
For example, in (Tokunaga et al.~ 1997), the thesaurus to be extended contains lnore than 500 categories. 
