Related effects for words are reported in (Lau, 1994; Beeferman et al., 1997).


The corpus, a subset s of the ATl{\]Lancaster (~eneralEnglish Treebank (Black et al., 1996), consists of a sequence of sentences which have been tagged and parsed by human experts in terms of the ATR English Grammar, a broad coverage granmtar of English with a high level of analytic detail (Black et al., 1996; Black et al., 1997).


2 Background Trigger-pair modelling research has been pursued within the field of language modelling for speech recognition over the last decade (Beeferman et ah, 1997; Della Pietra et al., 1992; Kupiec, 1989; Lau, 1994; Lau et ah, 1993; Rosenfeld, 1996).


The choice to use sentences as the unit of distance is motivated by our intention to incorporale triggers of this form into a probabilistie treebank based parser and tagger, sneh as (Black et al., 1998; Black et al., 1997; Brill, 1994; Collins, 1996: aelinek et al., 1994; Magerman, 1995; blatnaparkhi, 1997).


