(Brants et al. , 1997) describes an effort to minimize human effort in the annotation of raw text with comparable PRED-ARG information.


The Negra Corpus (Brants et al. , 1997) provides PRED-ARG information for German, similar in granularity to GLARF.


(Brants et al. , 1997).


The present paper offers a similarity1With the exception of dependency-grammar-based parsers (Tapanainen and Jarvinen, 1997; Broker et al. , 1994; Lesmo and Lombardo, 2000), where functional labels are treated as first-class citizens as relations between words, and recent work on a semi-automatic method for treebank construction (Brants et al. , 1997), little has been reported on based algorithm for assigning functional labels such as subject, object, head, complement, etc. to complete syntactic structures on the basis of pre-chunked input.


Moreover, there have been also efforts to extend the use of HMMs to word sense disambiguation (Segond et al 1997) and shallow/full parsing (Brants et al 1997; Skut et al 1998; Zhou et al 2000).


