(1992) and Marcu (1997) focus on discourse structure in summarization using the Rhetorical Structure Theory (RST). 
Some summarization systems assume that the importance of a sentence is derivable from a rhetorical representation of the source text (Marcu, 1997). 
This result outperforms significantly the previous 52.77% recall and 50.00% precision figures that were obtained by Marcu using only the shape-based heuristic (1997c; 1997a). 
A variety of approaches exist for determining the salient sentences in the text: statistical techniques based on word distribution (Salton et al. , 1991), symbolic techniques based on discourse structure (Marcu, 1997), and semantic relations between words (Barzilay and Elhadad, 1997). 
Marcu (1997b) provides a full description of the algorithm. 
