W02-1506:1	118:170	The Xerox calculus includes the composition, ignore, and substitution operator discussed by Kaplan and Kay (1994) and the priority-union operator of Kaplan and Newman (1997).
---------------------------------------------------
W02-1506:2	81:170	In addition to the basic priority overrides, XLE provides for edit lexical entries (Kaplan and Newman, 1997) that give finer control over the construction of the lexicon.
---------------------------------------------------
