Based on this scenario, for each concept, different degrees of generalization can be achieved by adjusting the distance between this concept and the most general concept in the WordNet hierarchy (Bagga et al. , 1997).


Viegas, Mahesh, and Nirenburg (forthcoming) describe a similar approach to WSD undertaken in the context of their work on machine translation (see also Mahesh et al. \[1997\] and Mahesh, Nirenburg, and Beale \[1997\]).


Also, the Cognitive Science Laboratory at Princeton has undertaken the hand-tagging of 1,000 words from the Brown Corpus with WordNet senses (Miller et al. 1993) (so far, 200,000 words are available via ftp), and hand-tagging of 25 verbs in a small segment of the Wall Street Journal (12,925 sentences), is also underway (Wiebe et al. 1997).


The need for sense disambiguation in such analysis, in order to include only those instances of a word in its proper sense, has long been recognized (see, for instance, Stone et al. \[1966\], Stone \[1969\], Kelly and Stone \[1975\]; for a more recent discussion see Litowski \[1997\]).


Recently, a class-based bootstrapping method for semantic tagging in specific domains has been proposed (Basili et al. 1997).


