A methodology for calculating homogeneity has been described and the accuracy and usefulness of this is further described in Kilgarriff (1997).


Homogeneity within each of the corpora is important here since we may find that the results reflect sections within one of the corpora which are unlike other sections in either of the corpora under consideration (Kilgarriff 1997).


A measure of homogeneity or self-similarity of a corpus can be calculated, by dividing the corpus into two frequency lists based on the term frequency and then calculating the  2 statistic between them (Kilgarriff, 1997).


