(2001), with some claiming performance equivalent to lexicon-based methods, while Kwok (1997) reports good results with only a small lexicon and simple segmentor.


(2001), with some claiming performance equivalent to lexicon-driven methods, while Kwok (1997) reports good results with only a small lexicon and simple segmentor.


The various attempts to tackle these tasks by statistical and algorithmic methods (Kwok 1997) have had only limited success.


The various attempts to tackle these tasks by statistical and algorithmic methods (Kwok 1997) have had only limited success.


(2001), with some claiming performance equivalent to lexicon-driven methods, while Kwok (1997) reports good results with only a small lexicon and simple segmentor.


