3 Robustness Robustness in the face of ill-formed input and recognition errors is tackled by means of a "multiengine" strategy (Frederking and Nirenburg, 1994; Rayner and Carter, 1997), combining two different translation methods. 
See (Alshawi and Carter, 1994) and (Carter, 1997) for details. 
As computational grammars and parsers have increased in coverage and accuracy, an alternate approach has become feasible, in which utterances are parsed and the annotator selects the best parse Carter (1997); Oepen et al. 
(3) The statistical information used in analysis is entirely derived from the results of supervised training on corpora carried out using the TreeBanker (Carter, 1997), a graphical tool that presents a non-expert user with a display of the salient differences between alternative analyses in order that the correct one may be identified. 
Further details can be found in (Rayner, Carter et al, 1997). 
