There are already other grammar developing tools, such as a grammar writer of XTAG (Paroubek et al. , 1992), ALEP (Schmidt et al. , 1996), ConTroll (Gotz and Meurers, 1997), a tool by Nara Institute of Science and Technology (Miyata et al. , 1999), and [incr tsdb()] (Oepen et al. , 2002).


The course is taught in an interactive fashion in a computer laboratory and combines background lectures with practical exercises on how to specify grammars in ConTroll11 (Gotz and Meurers, 1997), a processing system for constraint-based grammars intended to process with HPSG theories directly from the form in which they are constructed by linguists.


3.3 Advanced Top-down Control Non-parse type goals are interpreted using the standard interpreter of the ConTroll grammar development system (G5tz and Meurers, 1997b) as developed and implemented by Thilo GStz.


Some simply do not use a parser, such as the work based on ConTroll (Gotz and Meurers, 1997); as a consequence, the eciency and termination properties of parsers cannot be taken for granted in such approaches.


