Another approach would be to develop a syllable-based phonotactic model (Coleman and Pierrehumbert, 1997).


Learning the phonotactic patterns of a language is usually modeled 65 separately from word segmentation; e.g., current phonotactic learners such as Coleman and Pierrehumbert (1997), Heinz (2007), or Hayes and Wilson (2008) are given word-sized units as input.


1 In this respect, this work departs from (or is a special case of) gradient phonotactic models (Coleman and Pierrehumbert, 1997; Frisch et al. , 2000; Albright, 2006; Hayes and Wilson, 2006) 21 There are 27 types of QI stress systems found in Gordons (2002) typology.


