Our purpose here is to show how a simplified computational model of discourse reference can be implemented and give significant results for reference resolution; we showed previously (Popescu-Belis and Robba 1997) that it was also relevant for pronoun resolution.


Some past reports give no coverage details at all, while others (e.g. , Popescu-Belis and Robba 1997, page 97) precisely state their coverage: "/il/,/elle/,/le/,/la/,/1'/,/lui/,/ils/,~/elles/.


