This contrasts with approaches where there are essentially no explicit rules, such as neural networks (e.g. \[Buo 1996\]), or approaches where the machine learning algorithms attempt to infer--via deduction (e.g. \[Samuelsson 1994\]), induction (e.g. \[Theeramunkong et al. 1997\]; \[Zelle & Mooney 1994\]) under user cooperation (e.g. \[Simmons & Yu 1992\]; \[Hermjakob & Mooney 1997\]), transformation-based error-driven learning (e.g. \[Brill 1993\]), or even decision trees (e.g. \[Magerman 1995\])--a grammar from raw or preprocessed data.


