D08-1039:1	24:197	In language modeling, monolingual trigger approaches have been presented (Rosenfeld, 1996; TillmannandNey,1997)aswellassyntacticalmethods that parse the input and model long-range dependencies on the syntactic level by conditioning on the predecessing words and their corresponding parent nodes (Chelba and Jelinek, 2000; Roark, 2001).
---------------------------------------------------
D08-1039:2	69:197	The resulting training procedure is analogous to the one presented in (Brown et al., 1993) and (Tillmann and Ney, 1997).
---------------------------------------------------
W03-1003:3	55:162	In a monolingual setting, the mutual information between lexical pairs co-occurring anywhere within a long window of each-other has been used to capture statistical dependencies not covered by a1 -gram LMs (Rosenfeld, 1996; Tillmann and Ney, 1997).
---------------------------------------------------
D09-1022:4	56:248	Furthermore, since the second trigger can come from any part of the sentence, there is a link to long-range monolingual triggers as presented in (Tillmann and Ney, 1997) where a trigger language model was trained using the EM algorithm and helped to reduce perplexities and word error rates in a speech recognition experiment.
---------------------------------------------------
