We use a two stage strategy (Ros@ and Lavie, 1997) corresponding to two sets of rules: the first one is the set for a bottom-up parsing of LTAG using FSA and connected routes (Lopez, 1998b), the second one gathers the repair rules presented in this paper.


Previous interactive approaches to robust interl)retation have either required excessive amounts of interaction (II.os~ and Wail)el, 1994), depended upon domain dependent repair rules (Van Noord, 1996; l)anieli and Gerbino, 1995), or relied on the rninimum distance parsing approach (Hipp, 1992; Smith, 1992; Lehman, 11989) which has been shown to be intractable in a largescale system (F/.os~ and Lavie, 1997).


Our genetic programming approach has been shown previously to be orders of magnitude more efficient than the mininmm distance parsing approach (Rosd and Lavie, 1997).


