I05-6004:1	225:233	6 Future Work We are currently experimenting with moving some of the information (in particular the type name and criteria) into the actual grammar files, in the same way as Dini and Mazzini (1997).
---------------------------------------------------
I05-6004:2	202:233	Hypertextual Grammar development (Dini and Mazzini, 1997) attempted a similar task, but focused on documenting the grammar, not on linking it to a dynamic treebank.
---------------------------------------------------
