2 Word prediction for AAC Word prediction systems based on n-gram statistics are an important component of AAC devices, i.e., software and possibly hardware typing aids for disabled users (Copestake, 1997; Carlberger, 1998).


Our particular goal is to be able to use an article generator in conjunction with a symbolic generator for AAC (Copestake, 1997; Carroll et al. , 1999).


This analysis demonstrates a limit to keystroke savings, but this limit is slightly different than Copestake (1997) and Lesher et al.


Copestake (1997) discussed the entropy of English to conclude that 5060% keystroke savings may be the most we can expect in practice.


