Resnik and Yarowsky (1997b) also point out that a binary evaluation (correct/incorrect) for WSD is not sufficient, and propose that errors be penalized according to a distance matrix among senses based on a hierarchical organization.


Resnik and Yarowsky (1997b) have proposed that for WSD evaluation, 25 Computational Linguistics Volume 24, Number 1 it may be practical to retain only those sense distinctions that are lexicalized crosslinguistically.


