W99-0104:1	58:264	The CogNIAC algorithm (Baldwin, 1997) uses six heuristic rules to resolve coreference, whereas the algorithm presented in (Mitkov, 1998) is based on a limited set of preferences (e.g. definitiveness, lexical reiteration or immediate reference).
---------------------------------------------------
A00-1020:2	24:217	Section 5 summarizes the 2The name of COCKTAIL is a pun on CogNIAC because COCKTAIL combines a larger number of heuristics than those reported in (Baldwin, 1997).
---------------------------------------------------
A00-1020:3	32:217	For example, CogNIAC (Baldwin, 1997), a system based on seven ordered heuristics, generates high-precision resolution (over 90%) for some cases of pronominal reference.
---------------------------------------------------
W04-0714:4	19:154	Our method is an inexpensive, fast and reliable procedure for anaphora resolution, which relies on cheaper and more reliable NLP tools such as partof-speech (POS) tagger and shallow parsers (Baldwin, 1997; Ferrndez et al. , 1998; Kennedy and Boguraev, 1996; Mitkov, 1998; Yeh and Chen, 2003).
---------------------------------------------------
P98-2143:5	127:152	3.3 Comparison to similar approaches: comparative evaluation of Breck Baldwin's CogNIAC We felt appropriate to extend the evaluation of our approach by comparing it to Breck Baldwin's CogNIAC (Baldwin 1997) approach which features "high precision coreference with limited knowledge 873 and linguistics resources".
---------------------------------------------------
P98-2143:6	131:152	This result is comparable with the results described in (Baldwin 1997).
---------------------------------------------------
P98-2143:7	132:152	For the training data from the genre of technical manuals, it was rule 5 (see Baldwin 1997) which was most frequently used (39% of the cases, 100% success), followed by rule 8 (33% of the cases, 33% success), rule 7 (11%, 100%), rule I (9%, 100%) and rule 3 (7.4%, 100%).
---------------------------------------------------
P98-2143:8	14:152	Several proposals have already addressed the anaphora resolution problem by deliberately limiting the extent to which they rely on domain and/or linguistic knowledge (Baldwin 1997; Dagan & Itai 1990; Kennedy & Boguraev 1996; Mitkov 1998; Nasukawa 1994; Williams et al. 1996).
---------------------------------------------------
J01-4004:9	423:460	Among the papers that have reported quantitative evaluation results, most are not based on learning from an annotated corpus (Baldwin 1997; Kameyama 1997; Lappin and Leass 1994; Mitkov 1997).
---------------------------------------------------
P01-1006:10	86:113	It is logical to assume that good anaphora resolution approaches should 4This definition is slightly different from the one used in (Baldwin, 1997) and (Gaizauskas and Humphreys, 2000).
---------------------------------------------------
P01-1006:11	62:113	We selected for comparative evaluation three approaches extensively cited in the literature: Kennedy and Boguraevs parserfree version of Lappin and Leass RAP (Kennedy and Boguraev, 1996), Baldwins pronoun resolution method (Baldwin, 1997) and Mitkovs knowledge-poor pronoun resolution approach (Mitkov, 1998b).
---------------------------------------------------
P01-1006:12	73:113	Baldwins Cogniac CogNiac (Baldwin, 1997) is a knowledgepoor approach to anaphora resolution based on a set of high confidence rules which are successively applied over the pronoun under consideration.
---------------------------------------------------
P01-1006:13	8:113	Our paper discusses a particular configuration of this new evaluation environment incorporating three approaches sharing a common knowledge-poor philosophy: Kennedy and Boguraevs (1996) parser-free algorithm, Baldwins (1997) CogNiac and Mitkovs (1998b) knowledge-poor approach.
---------------------------------------------------
P01-1006:14	65:113	Since the original version of CogNiac is non-robust and resolves only anaphors that obey certain rules, for fairer and comparable results we implemented the resolve-all version as described in (Baldwin, 1997).
---------------------------------------------------
P01-1006:15	106:113	pronouns, referential distance, average number of candidates for antecedent per pronoun and types of anaphors.7 As expected, the results reported in Table 1 do not match the original results published by Kennedy and Boguraev (1996), Baldwin (1997) and Mitkov (1998b) where the algorithms were tested on different data, employed different pre-processing tools, resorted to different degrees of manual intervention and thus provided no common ground for any reliable comparison.
---------------------------------------------------
W06-1807:16	25:129	Pronoun resolution is carried out using the Glencova Pronoun Resolution algorithm (Halpin et al. , 2004), based on a series of rules similar to the CogNIAC engine (Baldwin, 1997), but without gender informationbased rules since this is not provided by the Penn Treebank tagset.
---------------------------------------------------
J01-4005:17	56:399	The most important proposals for anaphora resolution--such as those of Baldwin (1997), Lappin and Leass (1994), Hobbs (1978), or Kennedy and Boguraev (1996)--are based on a separation between constraints and preferences.
---------------------------------------------------
J01-4005:18	284:399	Other approaches, however, give equal 559 Computational Linguistics Volume 27, Number 4 importance to each kind of knowledge and generally distinguish between constraints and preferences (Baldwin 1997; Lappin and Leass 1994; Carbonell and Brown 1988).
---------------------------------------------------
J01-4001:19	10:53	A number of proposals in the 1990s deliberately limited the extent to which they relied on domain and/or linguistic knowledge and reported promising results in knowledge-poor operational environments (Dagan and Itai 1990, 1991; Lappin and Leass 1994; Nasukawa 1994; Kennedy and Boguraev 1996; Williams, Harvey, and Preston 1996; Baldwin 1997; Mitkov 1996, 1998b).
---------------------------------------------------
P98-1064:20	11:200	As a consequence, current anaphor resolution implementations mainly rely on constraints and preference heuristics which employ information originated from morphosyntactic or shallow semantic analysis, e.g. in Baldwin (1997).
---------------------------------------------------
W99-0634:21	155:181	Among the work that reported quantitative evaluation results, most are not based on learning from an annotated corpus (Baldwin, 1997; Kameyama, 1997; Lappin and Leass, 1994; Mitkov, 1997).
---------------------------------------------------
