According to Wilks and Stevenson (1997), a task assigning broad sense tags like HUMAN, ANIMATE in WordNet is referred to as semantic tagging, different from sense tagging, which assigns more particular sense tags.


It is supposed to provide semantic information useful to the application tasks like IR and MT. As generally acknowledged, sense tagging is to assign a certain sense to a word in a certain context by using a semantic lexicon (Yarowsky, 1992, Wilks and Stevenson, 1997).


1 Introduction This paper is about two things: a novel hybrid sense tagger for unrestricted text (Wilks and Stevenson, 1997), and the experience of developing this system within GATE a General Architecture for Text Engineering (Cunninham et al. , 1997; Cunningham, Wilks, and Gaizauskas, 1996a).


