Linguistic Indicators Aspectually categorizing verbs is the first step towards aspectually classifying clauses, since many clauses in certain domains can be categorized based on their main verb only (Siegel 1997, 1998b, 1999).


600 Siegel and McKeown Improving Aspectual Classification 2.6 Applications of Aspectual Classification Aspectual classification is a required component of applications that perform natural language interpretation, natural language generation, summarization, information retrieval, and machine translation tasks (Moens and Steedman 1988; Klavans and Chodorow 1992; Klavans 1994; Dorr 1992; Wiebe et al. 1997).


However, previous work that numerically evaluates aspectual classification has looked at verbs in isolation (Klavans and Chodorow, 1992; Siegel, 1997).


(Hirschberg & Litman 1993)); and words that suggest states versus events (Siegel 1997).


