In this paper we will discuss the proposed knowledge modeling architecture of ICICLE (Interactive Computer Identification and Correction of Language Errors), a system under development (McCoy and Masterman (Michaud), 1997) whose goal is to provide deaf students with constructive tutoring on their written English.


As a subpart of their research aimed at developing the ICICLE system (McCoy and Masterman, 1997), a language-tutoring application for deaf learners of written English, Michaud and McCoy developed an architecture for modeling the writing proficiency of a user called SLALOM.


