For further details on the topics of customization and multilin73 guality, see (Rayner, Bretan et al, 1996; Rayner, Carter et al, 1997); and on robustness, see (Rayner and Carter, 1997).


However, we have found that the amount of work involved in developing new grammars for Swedish, French, Spanish and most recently Danish has always been at least an order of magnitude less than the effort required for the original grammar (Gambgck and Rayner, 1992; Rayner, Carter and Bouillon, 1996; Rayner, Carter et al, 1997).


These points will be discussed in the context of the Spoken Language Translator (SLT) (Rayner, Alshawi eta/, 1993; Agn~s et al. , 1994; Rayner and Carter, 1997), a customizable speech translator built as a pipelined sequence of generalpurpose components.


We tackle the N-squared problem by means of transfer composition (Rayner, Carter and Bouillon, 1996; Rayner, Carter et al, 1997).


Further details can be found in (Rayner, Carter et al, 1997).


