proc compare(A, B) for each non-terminal node X in A: search node Y in B such that yield(X) = yield(Y) if Y exists: emit different labels if any if Y does not exist: emit X and its yield end end Figure 4: Basic asymmetric algorithm to compare annotation A with annotation B of the same sentence (Calder, 1997) presents a method of comparing the structure of context free trees found in different annotations.


(Calder, 1997) points out possible solutions to this problem.


