3.2 Integration of processors Differently from the activity of creation and editing of projects, only the final part of the work involved in the integration of processors is accomplished via the SISSA graphical interface (more written in C and running under Windows: (Prodanof et al. , 1998; Prodanof et al. , 2000)) and the preprocessor and the parser of GEPPETTO (ITC-irst, written in Common Lisp and running under Solaris: (Ciravegna et al. , 1997; Ciravegna et al. , 1998)).


