Nerbonne and Heeringa (1997) use phonetic transcriptions to measure the phonetic distance between different dialects. 
1 Both Gildea and Jurafsky (1996) and Nerbonne and Heeringa (1997) use distance functions based on binary features. 
Nerbonne and Heeringa (1997), for example, weighted each feature by information gain, or entropy reduction. 
Nerbonne and Heeringa (1997) employed a similar procedure to compute relative distance between words from various Dutch dialects. 
Heeringa and others have also done related work on phonological distance in Nerbonne and Heeringa (1997) and Gooskens and Heeringa (2004). 
