P98-1036:1	19:166	The paper (Thompson and Dozier, 1997) reported an experiment over periods of several days in 1995.
---------------------------------------------------
W02-1809:2	129:186	Thompson & Dozier (1997) have also shown that correctly indexing names in monolingual English retrieval leads to better retrieval.
---------------------------------------------------
W02-0405:3	94:180	This is consistent with our observations of customer search topics applied to news data, and this user behavior has also been reported elsewhere (e.g. , Thompson & Dozier, 1997).
---------------------------------------------------
