Distributionally-based semantic similarity A semantic similarity measure computed on the basis of distributional evidence is at work in SENSE, an example-based word sense disambiguation (WSD) system carrying out the task on the basis of a representative set of typical patterns of use (Federici et al. 1997).


The similarity between an IP and some known examples is not simply based on a a-priori 2 In fact, SENSE is also able to go beyond the evidence provided by an attested example as illustrated in Federici et al. 1997.


