TBL has some attractive qualities that make it suitable for the language-related tasks: it can automatically integrate heterogeneous types of knowledge, without the need for explicit modeling (similar to Snow (Dagan et al. , 1997), Maximum Entropy, decision trees, etc); it is errordriven, thus directly minimizes the ultimate evaluation measure: the error rate.


That algorithm has been applied for natural language disambiguation tasks and related problems and perform remarkably well (Golding and Roth, 1996; Dagan et al. , 1997; Roth and Zelenko, 1998).


One method that has been quite successful in many applications is the SNoW architecture (Dagan et al. , 1997; Khardon et al. , 1999).


