In recent years, many statistical solutions have been proposed: lexical associations (see (Hindle and Rooth, 1993)); error-driven transformation learning (see (Brill and Resnik, 1994), extensions by (Ye h and Vilain, 1998)); backedoff estimation (see (Collins and Brooks, 1995), extended to the multiple PP attachment problem by (Merlo et al. , 1997)); loglinear model (see (Franz, 1996b), (Franz, 1996a, pp. 
Set It2 is the data used in (Merlo et al., 1997) and has about 26000 entries. 
3 Table 1 shows how likely the attachments in 7x9x that belong to each category are  to attach to the left adjacent group (A) 2This attachment preference also appears in the large data set used in (Merlo et al., 1997). 
4 4(Merlo et al., 1997) searches the Pelm Treebank for data samples that they can handle. 
(Merlo et al. , 1997) evaluate the attachment of multiple prepositions in the same sentence for English; 85.3% accuracy is achieved for the first PP, 69.6% for the second and 43.6% for the third. 
