W98-0307:1	10:152	As a result, many researchers have turned to sentence extraction (Kupiec, Pedersen, & Chen 1995; Brandow, Mitze, & Rau 1995; Hovy & Lin 1997).
---------------------------------------------------
W98-0307:2	81:152	For the computational linguistics corpus, we additionally had a collection of 948 sentences that had been identified as relevant by a human annotator in a prior experiment (Teufel & Moens 1997).
---------------------------------------------------
P00-1038:3	157:173	Hovy and Lin (1997) present another system that learned how the position of a sentence affects its suitability for inclusion in a summary of the document.
---------------------------------------------------
P00-1038:4	66:173	Stochastic models of language have been used extensively in speech recognition, optical character recognition, and machine translation (Jelinek, 1997; Berger et al. , 1994).
---------------------------------------------------
H05-1001:5	5:277	1 Introduction Many approaches to summarization can be very broadly characterized as TERM-BASED: they attempt to identify the main topics, which generally are TERMS, and then to extract from the document the most important information about these terms (Hovy and Lin, 1997).
---------------------------------------------------
P98-2151:6	78:219	Present summarization systems (Watanabe, 1996: Hovy and Lin, 1997) use such clues to calculate an importance score for each sentence, choose sentences 918 according to the score, and simply put the selected sentences together in order of their occurrences in the original document.
---------------------------------------------------
P07-1070:7	32:166	The scores are usually computed based on a combination of statistical and linguistic features, including term frequency, sentence position, cue words, stigma words, topic signature (Hovy and Lin, 1997; Lin and Hovy, 2000), etc. Machine learning methods have also been employed to extract sentences, including unsupervised methods (Nomoto and Matsumoto, 2001) and supervised methods (Kupiec et al. , 1995; Conroy and OLeary, 2001; Amini and Gallinari, 2002; Shen et al. , 2007).
---------------------------------------------------
W03-1202:8	73:249	(1999), Jing and McKeown (1999), and Hovy and Lin (1997).
---------------------------------------------------
J98-3005:9	100:614	Mani and Bloedorn (1997) link similar words and phrases from a pair of articles using WordNet (Miller et al. 1990) semantic relations.
---------------------------------------------------
J98-3005:10	96:614	Alternatives to the use 473 Computational Linguistics Volume 24, Number 3 of frequency of key phrases included the identification and representation of lexical chains (Halliday and Hasan 1976) to find the major themes of an article followed by the extraction of one or two sentences per chain (Barzilay and Elhadad 1997), training over the position of summary sentences in the full article (Hovy and Lin 1997), and the construction of a graph of important topics to identify paragraphs that should be extracted (Mitra, Singhal, and Buckley 1997).
---------------------------------------------------
J98-3005:11	431:614	If the summarization system can find the needed information in other on-line sources, then it can produce an improved summary by merging information extracted from the input articles with information from the other sources (Radev and McKeown 1997).
---------------------------------------------------
W00-0405:12	34:197	to linguistic units such as tokens, names, anaphora, etc. More recently, other approaches have investigated the utility of discourse structure (Marcu, 1997), the combination of information extraction and language generation (Klavans and Shaw, 1995; McKeown et al. , 1995), and using machine learning to find patterns in text (Teufel and Moens, 1997; Barzilay and Elhadad, 1997; Strzalkowski et al. , 1998).
---------------------------------------------------
W00-0405:13	10:197	Many of these documents are likely to repeat much the same information, while differing in certain i Most of these were based on statistical techniques applied to various document entities; examples include frait, 1983; Kupiec et al. , 1995; Paice, 1990, Klavans and Shaw, 1995; MeKeown et al. , 1995; Shaw, 1995; Aon et al. , 1997; Boguraev and Kennedy, 1997; Hovy and Lin, 1997; Mitra et al. , 1997; Teufel and Moens, 1997; Barzilay and Elhadad, 1997; Carbonell and Goldstein, 1998; Baldwin and Mortbn, 1998; Radev and McKeown, 1998; Strzalkowski et al. , 1998).
---------------------------------------------------
P00-1041:14	95:138	It is likely that more sophisticated language models, such as structure models (Chelba, 1997; Chelba and Jelinek, 1998), or longer ngram models would lead to the system generating headlines that were more similar in phrasing to real headlines because longer range dependencies shelf Carnegie Mellon University summarizer, which was the top ranked extraction based summarizer for news stories at the 1998 DARPA-TIPSTER evaluation workshop (Tip, 1998).
---------------------------------------------------
P00-1041:15	115:138	traction (Hovy and Lin, 1997; Mittal et al. , 1999).
---------------------------------------------------
W03-0506:16	40:204	A lot of approaches were proposed in text summarization, such as word frequency based method (Luhn, 1958), cue phrase method (Edmundson, 1969), Positionbased methods (Edmundson, 1969; Hovy and Lin, 1997; Teufel and Moens, 1997).
---------------------------------------------------
W04-3013:17	35:123	Semantic relations currently in OMCSNet Prior research in text summarization has recognized the need for general world knowledgein SUMMARIST (1997), Hovy & Lin describe how the words gun, mask, money, caught, and stole together would indicate the topic of robbery, but they note that that WordNet and other dictionary-like resources did not contain enough such knowledge.
---------------------------------------------------
W00-1108:18	22:109	Several techniques for text summarization have been reported in the literature, including methods based on position (Edmundson, 1969; Hovy and Lin, 1997; Teufel and Moens, 1997), cue phrase (McKeown and Radev, 1995; Mahesh, 1997), word frequency (Teufel and Moens, 1997), and discourse segmentation (Boguraev and Kennedy, 1997).
---------------------------------------------------
W00-1108:19	8:109	Many different approaches have been applied to this task, including nearest neighbor classifiers (Masand, Linoff and Waltz, 1992; Yang, 1994; Lain and Ho, 1998; Yang, 1999), Bayesian independence classifiers (Lewis and Ringuette, 1994; Baker and McCallum, 1998; McCallum and Nigam, 1998), decision trees (Fuhr et al. , 1991; Lewis and Ringuette, 1994; Apte et al. , 1998), induction rule learning (Apte et al. , 1994; Cohen and Singer, 1996; Mouilinier et al. , 1996), neural networks (Wiener, Pedersen and Weigend, 1995; Ng, Gob and Low, 1997), and support vector machines (Joachims, 1998).
---------------------------------------------------
W00-1108:20	24:109	In this research we combine these two approaches to investigate the efforts for categorization In regard to the position method, Hovy and Lin (1997) considered the title is the most likely to bear topics.
---------------------------------------------------
