In best-first parsing, this priority is called a figure-of-merit (FOM), and is based on various approximations to P(e|s), the fraction of parses of a sentence s which include an edge e (though see Goodman (1997) for an alternative notion of FOM). 
The terms  and  are the thresholds of the number and the beam width of lexical entries, and  is the beam width for global thresholding (Goodman, 1997). 
For purposes of pruning, and only for purposes of pruning, the prior probability of each constituent category is multiplied by the generative probability of that constituent (Goodman, 1997). 
The next section describes their work in more detail, Besides C&C the work that is most directly comparable to ours is that of Goodman (1997) and Ratnaparki (1997). 
The terms  and  are the thresholds of the number and the beam width of lexical entries, and  is the beam width for global thresholding (Goodman, 1997). 
