al. 1999, Plan-Based vs. templatebased NLG: a false opposition?, Becker and Busemann (1999) McCoy K. 1997, Simple NLP Techniques for Expanding Telegraphic Sentences Natural Language Processing for Communication Aids,1997 Rambow Owen, Bangalore Srinivas, Walker Marilyn 2001,Natural Language Generation in Dialog System, Proceedings of the first international conference on Human language technology research HLT '01 Pasero Robert, Nathalie Richardet and Paul Sabatier; Guided Sentences Composition for Disabled People; Proceedings of the fourth conference on Applied natural language processing October 1994 Project SANYOG Available at: http://www.mla.iitkgp.ernet.in/projects/sanyog.htm Stephanidis, C. et.


In Compansion project (McCoy, 1997), a novel approach was taken to enhance the communication rate.


Similar methods were used for AAC applications, COMPANSION (McCoy, 1997) for example  where the telegraphic text is expanded to full sentences, using a word order parser, and a semantic parser to build the case frame structure of the verb in the utterance, filling the slots with the rest of the content words given.


In the last decade, several systems that integrate NLG techniques for AAC systems have been developed ((McCoy, 1997), (Vaillant, 1997) for example).


