An analysis of the semantic annotation task performed by novice taggers as part of the SemCor project (Fellbaum et al. , 1997) revealed an agreement of about 82.5% among novice taggers, and 75.2% among novice taggers and lexicographers.


2.2 Polysemy, POS, and sense order In their 1997 paper, Fellbaum et al. analyzed the results of the SEMCOR project, in which part of the Brown Corpus (Kucera and Francis, 1967) was tagged to WordNet 1.4 senses.


