However, the semantic interpretation of thematic roles is generally inconsistent across verbs (Lowe et al., 1997; Kaisser and Webber, 2007).


Putting FrameNet Data into the ISO Linguistic Annotation Framework Srinivas Narayanan Miriam R. L. Petruck Collin F. Baker Charles J. Fillmore a0snarayan, miriamp, collinb, fillmore a1@icsi.berkeley.edu International Computer Science Institute 1947 Center St. , Berkeley, California 1 Abstract This paper describes FrameNet (Lowe et al. , 1997; Baker et al. , 1998; Fillmore et al. , 2002), an online lexical resource for English based on the principles of frame semantics (Fillmore, 1977a; Fillmore, 1982; Fillmore and Atkins, 1992), and considers the FrameNet database in reference to the proposed ISO model for linguistic annotation of language resources (ISO TC37 SC4 )(ISO, 2002; Ide and Romary, 2001b).


A fuller bibliography may be found in (Lowe et al., 1997) :Our main corpus is the British National Corpus.


However, the field has yet to develop a clear consensus on guidelines for a computational lexicon that could provide a springboard for such methods, although attempts are being made (Pustejovsky, 1991), (Copestake and Sanfilippo, 1993), (Lowe et al., 1997), (Dorr, 1997).


Despite many different lexicon development approaches (Mel'cuk, 1988; Copestakc and Sanfilippo, 1993; Lowe et al. , 1997), the field has yet to develop a clear conseusus on guidelines for a colnputational lexicon.


