Several researches have been reported on title generation (Jin and Hauptmann, 2000) (Berger and Mittal, 2000) and readability of texts (Minel et al. , 1997) (Hartley and Sydes, 1997) (Inui et al. , 2003).


Using an approach similar to (Minel et al. , 1997) we consider that a discourse rupture occurs when a sentence seems completely isolated from the rest of the text.


The coherence and cohesion were quantified through direct evaluation using a methodology similar to the one proposed in (Minel et al. , 1997).


This can involve user judgments of fluency of the summary (Minel et al. 1997), (Brandow et al. 1994), coverage of stipulated "key/essential ideas" in the source (Paice 1990), (Brandow et al. 1994), or similarity to an "ideal" summary, e.g., (Edmundson 1969), (Kupiec et al. 1995).


Some authors used French texts (Minel et al. , 1997; Char et al. , 2004), Korean texts (Myaeng and Jang, 1999) or Japanese texts (Nanba and Okumura, 2000).


