For example, frequent words are translated less consistently than rare words (Melamed, 1997). 
H(Ts|s) =  summationdisplay tTs P(t|s)logP(t|s) (1) This measure is equivalent to translational entropy (Melamed, 1997b). 
1.3 Related work Melamed (1997b) measures the semantic entropy of words using bitexts. 
Some applications that would benefit from knowing this distinction are machine translation (Imamura et al. , 2003), finding paraphrases (Bannard and Callison-Burch, 2005), (multilingual) information retrieval (Melamed, 1997a), etc. The purpose of this paper is to explore to what extent word-alignment in parallel corpora can be used to distinguish idiomatic multiword expressions from more transparent multiword expressions and fully productive expressions. 
Promising features for classification include part of speech, frequency of co-occurrence, relative word position, and translational entropy (Melamed, 1997). 
