Several researchers have used WordNet as a lexical and semantic resource for certain types of bridging anaphora (Poesio et al. , 1997; Meyer and Dale, 2002). 
4 Related work Previous approaches to solve associative anaphora havemadeuseofknowledgeresourceslikeWordNet (Poesio et al. , 1997), the Internet (Bunescu, 2003) and a corpus (Poesio et al. , 2002) to check if there is an associative link between the anaphor and a possible antecedent. 
The technique presented in (Schulte im Walde, 1997) based on lexical acquisition from the British National Corpus was evaluated against the same cases in (Poesio et al. , 1997). 
Knowledge might be encoded in many different ways in a lexical hierarchy, and this can pose a problem for anaphora resolution (Humphreys et al. 1997; Poesio, Vieira, and Teufel 1997). 
8 Related work An evaluation of the use of WordNet for treating bridging descriptions is presented in (Poesio et al. , 1997). 
