The corpus was prepared using an encoding scheme for discourse structure (Cristea, Ide, and Romary, 1998) based on the Corpus Encoding Standard (CES) tide (1998)).


In the following sections we briefly describe the Multext-East corpora (text, speech) and the Multext-East lexicons and language-specific resources, 1 The Multext-East corpora 1.1 Encoding format Based on the principle that its corpus encoding format should be standardized and homogeneous both for interchange and for facilitating openended retrieval tasks, Multext-East adopted the l http://nl.ijs.si/ME 2http://www.lpl.univ-aix.fr/ projects/Multext/ 315 Corpus Encoding Standard (CES) 3 (Ide, 1998), which has been developed to be optimally suited for use in language engineering and corpusbased work.


The Multext-East lexicons Distribution of sentence alignments and MSDs are fully described in Tufts, Ide, and Erjavec (1998).


