P06-2028:1	19:163	Typically, the local context around the 215 word to be sense-tagged is used to disambiguate the sense (Yarowsky, 1993), and it is common for linguistic resources such as WordNet (Li et al. , 1995; Mihalcea and Moldovan, 1998; Ramakrishnan and Prithviraj, 2004), or bilingual data (Li and Li, 2002) to be employed as well as more longrange context.
---------------------------------------------------
J04-1003:2	440:472	Prior knowledge about the likelihood of different senses or semantic classes is derived heuristically by submitting queries (e.g. , great hurricane) to the AltaVista search engine and extrapolating from the number of returned documents the frequency of the adjective-noun pair (see Mihalcea and Moldovan [1998] for details of this technique).
---------------------------------------------------
C00-1023:3	49:203	3.1 The Sparse Data Problem The techuique used to address data sI)arsity, as first proposed by Mihalcea and Moldovan (1998), treal;s the Internet as a cortms to automatically (lisambiguate word 1)airs.
---------------------------------------------------
