The KB can be used, among others, for monolingual and cross-lingual information retrieval, which was demonstrated by (Gonzalo et al. , 1998). 
Our plan is to apply this classifter to the whole EWN InterLingual Index, and then perform precision/recall tests in the environment described in (Gonzalo et al. , 1998; Gonzalo et al. , 1999). 
In (Gonzalo et al. , 1998), we used the manual annotations in the IR-Semcor collection to show that indexing with WordNet synsets can give significant improvements to Text Retrieval, even for large queries. 
Some WSD evaluations have been done using the Brown Corpus as training and testing resources and comparing the results against SemCor 3, the sense-tagged version of the Brown Corpus (Agirre and Rigau, 1996; Gonzalo et al. , 1998). 
The LKB can be used, among others, for monolingual and cross-lingual information retrieval, which has been demonstrated in other projects (Gonzalo et al. , 1998). 
