This label set has been shown to be of particular utility for indicating which segments are more important to include in an automatically created summary or compressed sentence (Sporleder and Lapata, 2005; Marcu, 1998; Marcu, 1999; Cristea et al. , 2005).


1 Introduction Discourse structure annotations have been demonstrated to be of high utility for a number of NLP applications, including automatic text summarization (Marcu, 1998; Marcu, 1999; Cristea et al. , 2005), sentence compression (Sporleder and Lapata, 2005), natural language generation (Prasad et al. , 2005) and question answering (Verberne et al. , 2006).


