Sunmmrization of dialogues within limilcd domains ha.s been attempted within the context of the VERBMOBII, pl:ojcct ("protocol generation", (Alexandersson and Poller, 1998)) or by SRI's MIMI summarizer (Kameyama et ~d. , 1996).


Within VERBMOBIL, a more knowledge-rich approach is used (Alexandersson and Poller 1998; Reithinger et al. 2000).


Within Verbmobil, the generation component will also be used for text generation when producing protocols as described in (Alexandersson and Poller, 1998).


In this paper we report on a new system functionality within the scope of VERBMOBIL (Bub et al. , 1997), a fully implemented speech-to-speech translation system, that generates German or English dialogue scripts (Alexandersson and Poller, 1998) as well as German or English summaries of a multilingual negotiation dialogue held with assistance of the system.


