In previous literatures, some researchers used knowledge bases for text understanding tasks(Scott et al. , 1998), such as WordNet for English and HowNet for Chinese.


The WordNet ontology has been widely useful, with applications in information retrieval (Sussna, 1993), text classification (Scott and Matwin, 1998), and question answering (Pasca and Harabagiu, 2001).


This semantic dictionary is useful in extracting the real concept of a word, a query or a document in the field of text mining (Richardson 1994; Richardson and Smeaton 1995; Voorhees 1993; Voorhees 1998; Scott and Matwin 1998; Gonzalo et al. 1998; Moldovan and Mihalcea 1998; Moldovan and Mihalcea 2000).


