Further details regarding the measurement of these indicators, and the linguistic constraints that motivate them, can be found in Siegel (1998b). 
Clauses with have as their main verb, composing 8.0% of the corpus, are highly ambiguous, and have been addressed separately by considering the direct object of such clauses (Siegel 1998a, 1998b). 
Furthermore, indicators measured over multiple clausal constituents (e.g. , main verb-object pairs) alleviate verb ambiguity and sparsity and improve classification performance (Siegel 1998b). 
This incompleteness has been illustrated empirically by showing that some indicators help for only a subset of verbs (Siegel, 1998b). 
For example, in a separate study, optimizing for F-measure resulted in a more dramatic tradeoff in recall values as compared to those attained when optimizing for accuracy (Siegel, 1998b). 
