Flaubert was the first GTAG implementation, conducted by Cora SA ((Meunier and Danlos, 1998), (Meunier 1997)).


To further pursue, V. Lux (Lux, 1998) has developed a proof of concept generator using Flaubert (Meunier, 1997; Meunier-and "Danlos.


We chose Lexicalized Tree Adjoining Grammar (LTAG) for the following reasons: * A text generation formalism inspired from LTAG, called G-TAG, has been designed, implemented and used in several applications (Danlos and Meunier, 1996; Meunier, 1997; Danlos, 1998; Meunier and Danlos, 1998; Danlos, 2000).


