We first present our classical generator architecture (see also (Becker et al. , 1998; Becker et al. , 2000)) in terms of the RAGS architecture and then discuss its extension to the task-inherent problems. 
The processing is .based,on a fully lexicatized TreeAdjoining Grammar derived from the HPSG grammar used in the deep-processing parser module (Kasper~et aL, 1995; Becker, 1998). 
Some techniques can be used to partially make up for the problem, for example the memoization ((Nicolov, 1998), \[ 2,d_order (Becker, 1998)), but it does not \[ relations LB solve the problem. 
Picking up on this idea, the generation component in SmartKom is based on fully lexicalized generation (Becker, 1998), using partial derivation trees of a Tree-Adjoining Grammar (TAG). 
For an easy adaptation to other domains and languages, we have emphasized an organization based on a general kernel system and the declarativity of knowledge sources (Becker et al. , 1998). 
