Consider the following example: cat head classifier possessor common lex "Simlah"/"dress" \] lex "Sabat" \] cat common \] lex "yalda"/"girl" If only the possessor is provided in the following input, it can be mapped to a construct state: Simlat ha-yaldah dress-cs the-girl the girl's dress If a classifier is provided in addition, the construct-state slot is not available anymore 1, and the free genitive construct must be used: Simlat ha-Sabat Sel ha-yaldah dress-cs the-Shabat of the-girl The Shabat dress of the girl l If the classifier had been specified in the input as a semantic relation as discussed in (Dahan-Netzer and Elhadad, 1998b), an alternative realization (The girl's dress/or Shabat) could have been obtained.


(Dahan-Netzer and Elhadad, 1998b) for an even more abstract proposal).


But, in addition to these pragmatic factors and as is the case for the English genitive, the construct state can realize a wide variety of semantic relations (Dahan-Netzer and Elhadad, 1998b), (Azar, 1985), (Levi, 1976).


For example, we have shown in (Dahan-Netzer and Elhadad, 1998b) that the semantic relations that can be realized by a construct state are the ones defined as classifier in SURGE.


In (Dahan-Netzer, 1997) and (DahanNetzer and Elhadad, 1998a), we have refined the D/Q classification and preferred using functional criteria: we map the Q quantitiers to the "amount" category defined by Glinert, and the D set is split into the partitive and determiner categories each with a different function.


