Introduction Research and development in automated essay scoring has begun to flourish in the past five years or so, bringing about a whole new field of interest to the NLP community (Burstein, et al (1998a, 1998b and 1998c), Foltz, et al (1998), Larkey (1998), Page and Peterson (1995)).


In previous studies of holistically scored essays (Burstein, et al (1998a, 1998b and 1998c)), we have examined e-rater's agreement with two individual human readers.


E-rater (Burstein et al. , 1998) uses a combination of statistical and natural language processing techniques for the purpose of extracting linguistic features of the essays to be graded.


