Several lexical resources and techniques are combined in (Atserias et al. , 1997) to map Spanish words from a bilingual dictionary to WordNet, and in (Farreres et al. , 1998) the use of the taxonomic structure derived from a monolingual MaD is proposed as an aid to this mapping process.


In (Farreres et al. , 1998), use of a taxonomic structure derived from a monolingual MRD is proposed as an aid to the mapping process.


In fact the work presented here can be considered an extension of (Atserias et al. , 1997; Farreres et al. , 1998) that was the base of the approach to building the Spanish WordNet within EuroWordNet2 project.


