Measures of local coherence specify which ordering of the sentences makes for the most coherent discourse, and can be based e.g. on Centering Theory (Walker et al. , 1998; Brennan et al. , 1987; Kibble and Power, 2000; Karamanis and Manurung, 2002) or on statistical models (Lapata, 2003). 
The SPR is automatically trained by applying RankBoost (Freund et al. , 1998) to learn ranking rules from training data. 
Here is the preferences concerning the use of relations, where "A>B" means that A is preferred over B: 1In (Mellish et al. , 1998), a Joint relation is used to connect every two text spans that do not have a normal semantic relation in between. 
403 Kibble and Power Optimizing Referential Coherence those collected in Walker, Joshi, and Prince (1998a) as well as Poesio et al. 
For better coordination, we adopt the text planner based on a Genetic Algorithm (GA) as described in (Mellish et al. , 1998a). 
