This processing is not straightforward: it necessitates expert knowledge in Arabic language word morphology (Al-Shalabi and Evens, 1998).


It compares favorably to other stemming or root extraction algorithms (Yates and Neto, 1999; Al-Shalabi and Evens, 1998; and Houmame, 1999), with a performance of over 97% for extracting the correct root in web documents, and it addresses the challenge of the Arabic broken plural and hollow verbs.


This is mainly due to the fact that Arabic is a non-concatenative language (Al-Shalabi and Evens, 1998), and that the stem/infix obtained by suppression of infix and prefix add-ons is not the same for words derived from the same origin called the root.


Permutation algorithms (Al-Shalabi and Evens, 1998) usetheinputwordsletterstogenerate all possible trilateral or quadrilateral sequences without violation of the original order of the letters whichisthencomparedwithitemsinadictionaryof roots until a match is found.


