The base NP is either a simple NP as defined by Wacholder (1998) or a conjunction of two simple NPs. 
2 The two techniques for automatic identification were the technical terms algorithm of Justeson and Katz (1995) and the head sorting method (Dagan and Church (1994); Wacholder (1998). 
 Simplex or complex NPs (e.g. , Church 1988; Hindle and Rooth 1991; Wacholder 1998) identify simplex or base NPs  NPs which do not have any component NPs -at least in part because this bypasses the need to solve the quite difficult attachment problem, i.e., to determine which simpler NPs should be combined to output a more complex NP. 
Wacholder, Nina (1998) "Simplex NPS sorted by head: a method for identifying significant topics within a document", Proceedings of the Workshop on the Computational Treatment of Nominals, pp.70-79. 
As considered by Wacholder (1998), the simple NPs are the maximal NPs that contain premodifiers but not post-nominal constituents such as prepositions or clauses. 
