2 Rare dialogue acts We take as our point of comparison the corpus of some 200,000+ utterances from the Switchboard corpus tagged with the SWBD-DAMSL tagset (Jurafsky et al, 1998).


Note The research described here is based on a project at the 1997 Workshop on Innovative Techniques in LVCSR at the Center for Speech and Language Processing at Johns Hopkins University (Jurafsky et al. 1997; Jurafsky et al. 1998).


About 200,000 SWBD utterances were rst annotated with DAMSL tags: it was observed that only 220 combinations of tags occurred (Jurafsky et al. , 1998).


4.3 Dialogue Act and Adjacency Pair Features A number of discourse features were extracted, drawing from the conversation analysis, disfluency and dialog act literature (Sacks et al., 1974; Jurafsky et al., 1998; Jurafsky, 2001).


