The problem of how to adapt a general lexicon to a particular application domain and merge domain ontologies with a general lexicon is out of the scope of this paper but discussed in (Jing, 1998).


For a detailed description of the combination process, refer to (Jing and Mchieown, 1998).


Jing (1998) presents an algorithm for converting WordNet into a domain-specific taxonomy of replaceable words.


