7.1 Application of Zipf's work Zipf's concept of 'least effort' may be relevant here (Zipf, 1947; Powers, 1998): Zipf argues that the simpler a construct is, the more often humans will want to use it or the more often they need it, the simpler they will make it.


(Karlssen, 1990), (Tapanainen and Entwisle and Powers 215 Use of Statistics in the Evaluation of NLP Parsers Jim Entwisle and David Powers (1998) The Present Use of Stalisties in the Evaluation of NLP Parsers.


