The literature offers discussions on patterns for coding nominalisations and their arguments (Meyers et al. , 1998), (Badia and Sanri, 1998).


To test this observation we re-ran C99 and TextTiling experiments on the Reuters and CNN C B A collections, using only nouns, adjectives, nominalized verbs (provided by the NOMLEX (Meyers et al. 1998)), and nominalized adjectives as input.


Using techniques similar to those described in (Meyers et al. , 1998) in combination with our work on GLARF (Meyers et al. , 2001a; Meyers et al. , 2001b), we expect to build a hand-coded PROPBANKER a program designed to produce a PropBank/NomBank style analysis from Penn Treebank style input.


A lexicon of nominalisations based on NOMLEX (Meyers et al. , 1998) is used for the most important cases.


While type (1) can be dealt with using a resource such as WordNet (Fellbaum, 1998), type (2) needs e ective parsing and mapping of syntactic structures into a common deeper structure, possibly using a repository of nominalisations like NOMLEX (Meyers et al. , 1998).


