P98-2186:1	107:220	The SNOW approach has been successfully applied to other problems of natural language processing(Golding and Roth, 1998; Krymolowski and Roth, 1998; Roth, 1998).
---------------------------------------------------
W00-0103:2	44:96	3.2 The Algorithm The algorithm works example for nouns): as follows (for 3.1 A More Flexible Approach The CoreLex database has been used and/or evaluated in a number of projects, leading to some criticisms of the approach in (Krymolowski and Roth 1998) (Peters, Peters and Vossen 1998) (Tomuro 1998) and in personal communication.
---------------------------------------------------
W00-0103:3	86:96	Similarly, in shallow syntactic processing tasks, like statistical disambiguation of PP-attachment, the use of underspecified senses may be preferable as shown in experiments by (Krymolowski and Roth 1998).
---------------------------------------------------
W00-0103:4	10:96	The approach for finding systematic polysemous classes is based on that of (Buitelaar 1998a, Buitelaar 1998b), but takes into account some shortcomings as pointed out in (Krymolowski and Roth 1998) (Peters, Peters and Vossen 1998) (Tomuro 1998).
---------------------------------------------------
W03-0412:5	19:250	In many cases, reported (and unreported) problems are due to the fact that WordNet enumerates all the senses of polysemous words; attempts to use this resource automatically often result in noisy and non-uniform information (Brill and Resnik, 1994; Krymolowski and Roth, 1998).
---------------------------------------------------
W03-0412:6	232:250	always work as successfully as researchers have expected (Krymolowski and Roth, 1998; Montemagni and Pirelli, 1998).
---------------------------------------------------
