In our approach \[Kerpedjiev etal.1997a, Kerpedjiev et al.1997b, Green et a1.1998, This work was supported by DARPA contract number DAA-1593K0005.


Whereas previous research has made this point convincingly for graphical and textual representations-particularly, for example, in the WIP (Andr4 et al. 1993), COMET (Feiner and McKeown 1993), and SAGE (Kerpedjiev et al. 1997; Green, Carenini, and Moore 1998) systems--we take this further and demonstrate that the same commonalities extend to include overall page layout, an area that has not previously received sufficient attention.


This has been explored extensively in systems such as WIP (Andr~ et al. 1993), PPP (AndrG Rist, and Mfiller 1998), and COMET (Feiner and McKeown 1993).


(Green et al. , 1998a; Green et al. , 1998b) show how such descriptions may be represented and formulated in NLG at a high-level process of content or rhetorical planning.


