The intermediate representations are usually notated as logic expressions such as a quasi-logical form (Klein et al. , 1998) and a customized language (Androutsopoulos et al. , 1998; Nelken and Francez, 2000).


The system in (Klein et al. , 1998) interprets noun phrase queries such as 5 in German: (5) Ersatzzeiten wegen Kindererziehung (Exemption times because of child raising) While the system can analyze noun phrases with various adverbial phrases, it is not reported to handle more complex noun phrase queries such as those with subordinate or coordinate constructions.


Although we propose to construct the system without an intermediate representation language, we show that our Combinatory Categorial Grammar (CCG) framework is compatible with the approaches with an intermediate representation (Nelken and Francez, 2000; Androutsopoulos et al. , 1998; Klein et al. , 1998).


