Applications where the data is available in a database include report generators (e.g. , ANA [Kukich, 1983], PlanDoc [Shaw et al. , 1994], Multimeteo [Coch, 1998], FOG [Goldberg et al. , 1994]).


The benefits of MLG over translation from single language source were documented in the past and include the high cost of human translation and the inaccuracy of automatic machine translation [Stede, 1996], [Coch, 1998], [Bateman, 1997].


