While we have demonstrated exhaustive parsing efficiency, our model could be used with any of the efficient search best-first approaches documented in the literature, from those used in the Charniak parser (Charniak et al. , 1998; Blaheta and Charniak, 1999) to A parsing (Klein and Manning, 2003a). 
This binarization process is similar to the one described in (Charniak et al. , 1998). 
Chitrao and Grishman (1990), Caraballo and Charniak (1998), Charniak et al. 
To speed up Viterbi parsing, sophisticated search strategies have been developed which nd the most probable analysis without examining the whole set of possible analyses (Charniak et al. , 1998; Klein and Manning, 2003a). 
With respect to chart parsing, (Charniak et al. , 1998) report that their parser can achieve good results while producing about three times tile mininmm number of edges required to produce the final parse. 
