Indeed, many recent text generation systems, including MOOSE (Stede 1999), ADVISOR II (Elhadad, McKeown, and Robin 1997), and Hunter-Gatherer (Beale et al. 1998), among others (see Reiter and Dales [1997] survey), adopt this view, yet their lexical-choice components do not account for near-synonymy.


1 Focus and word order determination as sentence planning tasks This paper addresses aspects of the control of intonation belonging to the area of sentence planning \[Beale et al. , 1998: Wanner and Hovy, 1996\].


