Whereas previous research has made this point convincingly for graphical and textual representations-particularly, for example, in the WIP (Andr4 et al. 1993), COMET (Feiner and McKeown 1993), and SAGE (Kerpedjiev et al. 1997; Green, Carenini, and Moore 1998) systems--we take this further and demonstrate that the same commonalities extend to include overall page layout, an area that has not previously received sufficient attention.


This has been explored extensively in systems such as WIP (Andr~ et al. 1993), PPP (AndrG Rist, and Mfiller 1998), and COMET (Feiner and McKeown 1993).


Dalianis and Hovy (1996) and Shaw (1998)); however Bateman et al.


Finally, since the use of aggregation lattices has been argued for other generation tasks (Bateman et al. , 1998), some of the 'cost' of deployment may in fact turn out to be shared, making a direct comparison solely with the RE-task in any case inappropriate.


On the other hand, recent computational work on sentence planning \[Bateman et al. 1998; Shaw 1998b\] indicates that generation research has progressed to a point where hard problems such as ellipsis, conjunctions, and ordering of paradigmatically related constituents are addressed.


