W05-1509:1	48:202	Conversely, output annotated with more informative labels, such as function or semantic labels, underlies all domain-independent question answering (Jijkoun et al. , 2004) or shallow semantic interpretation systems (Collins and Miller, 1998; Ge and Mooney, 2005).
---------------------------------------------------
C04-1109:2	13:263	There are also statistical approaches (Miller et al. , 1998) (Collins et al. , 1998) trying to encode event patterns in statistical CFG grammars.
---------------------------------------------------
P06-2086:3	42:206	Some of the systems are rule-based (Fisher, Soderland et al. 1995; Soderland 1999), some are statistical (Bikel, Miller et al. 1997; Collins and Miller 1998; Manning and Schutze 1999; Miller, Schwartz et al. 1999) and some are based on inductive-logic-based (Zelle and Mooney.
---------------------------------------------------
H05-1078:4	13:199	swering (Jijkoun et al. , 2004) or shallow semantic interpretation systems (Collins and Miller, 1998; Ge and Mooney, 2005).
---------------------------------------------------
