4.2 Type-Finder Module The main function of this module is to read the document and find the part of speech of the word: noun, verb, adjective, particle or proper noun by running several tests: Database lookup, particle check, check on adjectives derived from proper nouns, parse of noun phrases and verb phrases, the affix check and the pattern check This module was built by Abuleil and Evens (1998, 2001).


Some of them are solid (inert) nouns some of them are derived [Abuleil and Evens 1998].


