Related Work TIPSTER Phase III first identified cross-document coreference as an area for research since it is a central tool to drive the process of producing summaries from multiple documents and for information fusion (Bagga and Baldwin, 1998). 
6.1 John Smith Corpus Results Our main goal for the John Smith corpus is to demonstrate that we have successfully approximated the algorithm of Bagga and Baldwin (1998). 
Incremental vector space Our intent with the incremental vector space model is to approximate the work reported by Bagga and Baldwin (1998). 
We use the B-CUBED scoring algorithm (Bagga and Baldwin 1998) because it is the one used in the published research. 
Corpora To evaluate the effectiveness of our various techniques for cross document coreference, we use the same John Smith corpus created by Bagga and Baldwin (1998). 
