3.2 The Algorithm The algorithm works example for nouns): as follows (for 3.1 A More Flexible Approach The CoreLex database has been used and/or evaluated in a number of projects, leading to some criticisms of the approach in (Krymolowski and Roth 1998) (Peters, Peters and Vossen 1998) (Tomuro 1998) and in personal communication.


The approach for finding systematic polysemous classes is based on that of (Buitelaar 1998a, Buitelaar 1998b), but takes into account some shortcomings as pointed out in (Krymolowski and Roth 1998) (Peters, Peters and Vossen 1998) (Tomuro 1998).


This work is linked to the finding of systematic polysemy classes in (Buitelaar, 1998; Buitelaar, 2000; Tomuro, 1998) and others.


