Skut and Brants (1998) used Negra to train a maximum entropy-based chunker, and report LR and LP of 84.4% for NP and PP chunking. 
A basic identification of markables (i.e. NPs) was obtained by using the NP-Chunker Chunkie (Skut and Brants, 1998). 
(Skut and Brants, 1998) report 84.4% recall and 84.2% for NP and PP chunking without case labels. 
A basic identification of markables (i.e. NPs) was obtained by using the NP-Chunker Chunkie (Skut and Brants, 1998). 
While Negra has been used to build probabilistic chunkers (Becker and Frank, 2002; Skut and Brants, 1998), the research reported in this paper is the first attempt to develop a probabilistic full parsing model for German trained on a treebank (to our knowledge). 
