While the recognition of discourse structure has been studied in the context of explicit relations (Marcu, 1998) in the past, little published work has yet attempted to recognize implicit discourse relations between text spans.


(Corston, Oliver, 1998) enlarges the cue-phrase approach of (Marcu, 1998) in a vein sJmi\]ar to the one presented in Section 5.


As prepositions (and cue-phrases in general) can signal different coherence relations, the presented computational approach couples a cue-phrase approach like (Marcu, 1998) with inferences using the computed semantic representation.


Previous approaches to (automatically) deriving a text's discourse structure either tried to rely on purely surface-based criteria (cuephrases, (Marcu, 1998)) or concentrated on inferences about representations of discourse units (Asher, 1993; Hobbs et al. , 1993).


