These approaches can be further categorized into ones that use conditional entropy between letters to detect segment boundaries (Harris, 1955; Hafer and Weiss, 1974; Dejean, 1998; Monson et al. , 2004; Bernhard, 2006; Keshava and Pitler, 2006; Bordag, 2006), approaches that use minimal description length and thereby minimize the size of the lexicon as measured in entries and links between the entries to constitute a word form (Goldsmith, 2001; Creutz and Lagus, 2006).


e.g., (Dejean, 1998).


Often words are assumed to consist of one stem followed by one, possibly empty, suffix as in, e.g., (Dejean, 1998; Snover and Brent, 2001).


Dejean (1998) concentrates on the problem of finding the list of frequent affixes for a language rather than attempting to produce a morphological analysis of each word.


