The hybrid POS tagging system will not l)e explained in this paper, and the interested readers can see (Cha et al. , 1998) tbr further reference.


Other fairly representative examples are described in (Shin et al. , 1995; Park et al. , 1998) and in (Lee et al. , 1997a; Cha et al. , 1998; Lee et al. , 2002).


In the morphological analysis stage, a unknown word treatment nmthod based on a morpheme pattern dictionary and syllable bigrams is used after (Cha et al. , 1998).


5.1 Compound Noun Indexing To index compound nouns from documents, we use a natural language processing engine, SKOPE (Standard KOrean Processing Engine) (Cha et al. , 1998), which processes documents by analysing words into morphemes and tagging part-of-speeches.


