Anticipating that growing interest, over the last years, a significant part of LabELs research has been devoted to the development of large-scale, linguistically precise language resources, namely to the construction of computational lexicons for simple and multiword units (Eleutrio et al. , 1995; Ranchhod et al. , 1999; Ranchhod et al. , 2004).


Two smaller texts, one obtained from the on-line edition of the Expresso weekly newspaper 7 and the other a composite text 8 obtained from several sources and used on the MorphOlimpics evalua6 We also used an electronic dictionary of simple words of Portuguese (Ranchhod et al. 1999), from the public linguistic resources built by LabEL: http://label.ist.utl.pt.


