This approach was suggested by Kibble (1999), proposing that text and sentence planning should be driven by the goal of realising the designated topic in positions where it will be interpreted as the Cb. 
Kibble (1999) dubbed these principles cohesion and salience respectively. 
4 This separation among a center of coherence and a center of salience is independently motivated by considerations about the division of labor between the text planner and the sentence planner in a generation system; see, e.g., (Kibble, 1999). 
Kibble (1999) dubbed these principles cohe404 Computational Linguistics Volume 30, Number 4 Table 1 Centering transitions. 
Centering Theory has been adapted to NLG by Kibble (1999; 2001), and implemented in Kibble and Power (2004). 
