Ide (1999), for example, analyzes translations of English words into four different languages, in order to check if the different senses of an English word are lexicalized by different words in all the other languages.


Ide (1999)investigatesthe information made available by a translation of George Orwells Nineteen Eighty-four into six languages, using this to analyse the related senses of nine ambiguous English words into hierarchical clusters.


