The tools of MATE project(Carletta and Isard, 1999), which also directs multi-level annotation, can be a good candidate for our project.


MATE envisions three levels of user: coders, researchers for whom the coding task is performed and who need to view and manipulate the results, and experts who are able to configure the software (Carletta and Isard, 1999).


According to their respective objectives, we define five user profiles.3 The annotator Annotators assign linguistic features to language data, according to criteria and 2http://www.ling.uni-potsdam.de/sfb/ 3In a similar way, Carletta and Isard (1999) define three user types: the coder, the coding consumer, and the coding developer.


