Previous work on morphological disambiguation of in ectional or agglutinative languages include unsupervised learning for of Hebrew (Levinger et al. , 1995), maximum entropy modeling for Czech (Haji c and Hladka, 1998), combination of statistical and rule-based disambiguation methods for Basque (Ezeiza et al. , 1998), transformation based tagging for Hungarian (Megyesi, 1999).


Megyesi (1999) reports a 95.53% accuracy on Hungarian (a language whose features relevant to this task are very close to those of Turkish), with just the POS tags 1)eing correct.


Morphology-based POS tagging of some languages like Turkish (O azer and Kuruoz, 1994), Arabic (Guiassa, 2006), Czech (Hajic et al. , 2001), Modern Greek (Orphanos et al. , 1999) and Hungarian (Megyesi, 1999) has been tried out using a combination of hand-crafted rules and statistical learning.


(Megyesi, 1998) The weak part of her rst implementation was the lexical module of the tagger, as described in (Megyesi, 1999).


Megyesi (Megyesi, 1999) and Kuba et al.


