Also, studies by Harabagiu, Moldovan, and Maiorano (Harabagiu and Maiorano 1996; Harabagiu and Moldovan 1999) show that cohesion can be used to determine rhetorical relations that hold between smaller discourse constituents as well.


Details of the top performing heuristics of COCKTAIL were reported in (Harabagiu and Maiorano, 1999).


SWIZZLE is a multilingual enhancement of COCKTAIL (Harabagiu and Maiorano, 1999), a coreference resolution system that operates on a mixture of heuristics that combine semantic and textual cohesive information 2.


