Berland and Charniak (1999) use Hearst style techniques to learn meronym relationships (part-whole) from corpora.


Caraballo and Charniak (1999) and Caraballo (1999) augmented these lexical patterns with more general lexical co-occurrence statistics (such as relative entropy).


In the same vein, researchers at Brown University (Caraballo and Charniak, 1999)~ (Berland and Charniak, 1999), (Caraballo, 1999) and (Roark and Charniak, 1998) focused on target constructions, in particular complex noun t)hrases, and searched for information not only on identifying classes of nouns, lint also hypernyms, noun specificity and meronymy.


Caraballo and Charniak (1999) have explored determining noun specificity from raw text.


