It is however then surprising that this result is not made maximld use of in the Sltb.sc,,(lttent generaISonorient, cA work of McCoy an(1 Strube (1999). 
The algorithm l)ehind gnome-np is conlpared with the most recent pronoun generation algorithm of McCoy and Strube (1999). 
McCoy, K. E & M. Strube (1999a)'. 
This approach also means that Strube and Hahns (1999) principle of cheapness can be naturally incorporated as an additional constraint: This is a requirement that Cp(U n1 )=Cb(U n ). 
However, as McCoy and Strube (1999) observe, few researchers have developed sophisticated algorithms for pronoun generation. 
