Features may include specific discourse cues or markers, coreference links, identification of rhetorical relations, etc. The scope of the annotation refers to the levels of analysis within the document, and can be characterized as follows:  sentential: annotation of features at the intra-sentential or inter-sentential level, at a single level of depth (Sundheim, 1995; Tsou et al. , 2000; Nomoto and Matsumoto, 1999; Rebeyrolle, 2000).


So far, the annotation of discourse structure of documents has been applied primarily to identifying topical segments (Hearst, 1997), inter-sentential relations (Nomoto and Matsumoto, 1999; Tsou et al. , 2000), and hierarchical analyses of small corpora (Moser and Moore, 1995; Marcu et al. , 1999).


