One exception to this line of research is the use of Hidden Markov Models (HMM) for pitch accent prediction (Pan and McKeown, 1999; Conkie et al. , 1999). 
Pan and McKeown (1999) demonstrate the effectiveness of a sequence model over a rule induction system, RIPPER, that treats each label independently by showing that HMMs outperform RIPPER when the same variables are used. 
Various measures of a words informativeness, such as the information content (IC) of a word (Pan and McKeown, 1999) and its collocational strength in a given context (Pan and Hirschberg, 2001) have also proven to be useful models of pitch accent. 
Resolving this dilemma has been the topic of several studies in pitch accent placement (Hirschberg, 1993; Black, 1995; Pan and McKeown, 1999; Pan and Hirschberg, 2000; Marsi et al. , 2002) and in prosodic boundary placement (Wang and Hirschberg, 1997; Taylor and Black, 1998). 
Note that Pan and McKeown (1999) reported 74% accuracy with their HMM model. 
