N09-2009:1	26:97	The simplest version for step 1 is manual generation of the keyword lists (McCallum and Nigam, 1999).
---------------------------------------------------
P09-1095:2	211:221	McCallum and Nigam (1999) suggest that the initial labeled examples can be obtained using a list of keywords rather than through annotated data, yielding an unsupervised algorithm.
---------------------------------------------------
P09-1051:3	166:229	6.1.1 Experimental Setting Our categorization experiment follows a typical keywords-based text categorization scheme (McCallum and Nigam, 1999; Liu et al., 2004).
---------------------------------------------------
H05-1017:4	42:192	Some works (McCallum and Nigam, 1999; Liu et al. , 2004) performed an additional Expectation Maximization algorithm over the training data, but reported rather small incremental improvements that do not seem to justify the additional effort.
---------------------------------------------------
H05-1017:5	43:192	(McCallum and Nigam, 1999) reported categorization results close to human agreement on the same task.
---------------------------------------------------
H05-1017:6	165:192	Most IL data sets used for training and evaluation are either not available (McCallum and Nigam, 1999) or are composed by somewhat arbitrary subsets of a standard data set.
---------------------------------------------------
H05-1017:7	167:192	As a baseline system, we implemented a rule based approach in the spirit of (McCallum and Nigam, 1999).
---------------------------------------------------
H05-1017:8	32:192	The approach of categorizing texts based on lists of keywords has been attempted rather rarely in the literature (McCallum and Nigam, 1999; Ko and Seo, 2000; Liu et al. , 2004; Ko and Seo, 2004).
---------------------------------------------------
H05-1017:9	36:192	Similarity may be determined as a binary criterion, considering each seed keyword as a classification rule (McCallum and Nigam, 1999), or by applying an IR style vector similarity measure.
---------------------------------------------------
