In (Vossen et al. , 1999) we performed a conceptbased IR experiment where using the ILI with clusters was slightly worse than using the ILI without the clusters. 
The problem is that, when the granularity of the abstract classes is too coarse, systematic relations defined at that level may not hold uniformly at more fine-grained levels (Vossen et al. , 1999). 
Vossen, Peters, and Gonzalo (1999) find that approximately 4455% of ambiguous words in Spanish, Dutch and Italian have relatively high overlaps in concept and the sense packaging of polysemous words (Vossen et al. , 1999). 
Researchers building EuroWordNet have been able to devise a number of consistent metonymic relations that hold cross linguistically such as fabric/material, animal/food, building/organization (Vossen et al. , 1999; Wim Peters and Wilks, 2001). 
A similar effort was also made in the EuroWordnet project (Vossen et al. , 1999). 
