By avoiding tile need to segment text;, we: (a) alleviate computational overhead; (b) avoid the need to commit ourselves to a particular analysis type in the case of ambiguity; (c) avoi(1 the issue of' how to deal with unknown words; (d) avoid the need for stemming/lenlmatisation; and (e) to a large extent get around problems related to the nornmlisation of lexical alternation (see Baldwin and Tanaka (1999) for a discussion of problems related to lexical alternation in Jal)anese).


