On one hand, the theories developed in the traditional, truth-based semantic perspective (Kamp 1981; Lascarides and Asher 1993; Asher 1993; Hobbs et al. 1993; Kamp and Reyle 1993; Asher and Lascarides 1994; Kameyama 396 Marcu Rhetorical Parsing of Unrestricted Texts 1994; Polanyi and van den Berg 1996; van den Berg 1996; Gardent 1997; Schilder 1997; Cristea and Webber 1997; Webber et al. 1999) take the position that discourse structures can be built only in conjunction with fully specified clause and sentence syntactic structures.


(Similar strategies seem to be 632 van Deemter and Kibble On Coreferring adopted by most practitioners of coreference annotation, e.g., Cristea et al. \[1999\]).


