In several previous papers (Webber, Knott, and Joshi, 2001; Webber et al. , 1999a, 1999b), we described how our approach fits into the framework of tree-adjoining grammar. This led to the initial version of a discourse parser (Forbes et al. 2001) in which the same parser that builds trees for individual clauses using clause-level LTAG trees then combines them using discourse-level LTAG trees.


As we have pointed out in earlier papers (Webber, Knott, and Joshi 2001; Webber et al. , 1999a, 1999b), structural connectives have two relevant properties: (1) they admit stretching of predicate-argument dependencies; and (2) they do not admit crossing of those dependencies.


