W00-0802:1	61:214	2 Cluster evidence from Semcor One of our goals within the EuroWordNet and ITEM projects was to provide sense clusterings for WordNet (and, in general,for the EuroWordNet InterLingual Index, (Gonzalo et al. , 1999) that leave only the sense distinctions in wordnets that indicate different (semantic) indexing units for Information Retrieval.
---------------------------------------------------
W00-0802:2	92:214	Our plan is to apply this classifter to the whole EWN InterLingual Index, and then perform precision/recall tests in the environment described in (Gonzalo et al. , 1998; Gonzalo et al. , 1999).
---------------------------------------------------
W00-0802:3	6:214	In particular, we have used EuroWordNet in a Cross-Language Text Retrieval (CLTR) application (Verdejo et al. , 2000) and a number of CLTR experiments (Gonzalo et al. , 1999; Vossen et al. , 1999), confirming that it is crucial to apply certain sense clusters to Wordnet (WN) and EuroWordNet (EWN) to take real advantage of them in Information Retrieval applications.
---------------------------------------------------
