(Osborne, 1999) extended a definite clause grammar with rules induced by a learner that was based upon the maximum description length principle.


Osborne (1999) argues (correctly) that the hypothesis space of grammars is sufficiently large that some form of bias is required.


In (Osborne, 1999), the DCG is mapped to a SCFG to compute probabilities, in very recent work a stochastic attribute-value grammar is used (Osborne, 2000).


We have applied MDL to the task of learning broad-covering definite-clause grammars from either raw text, or else from parsed corpora (Osborne, 1999a).


Osborne (1999b) used a Definite Clause Grammar learner based on Minimum Description Length for finding noun phrases in samples of Penn Treebank material (MDL).


