3.4 SNOW The fourth of our individual systems is based on SNOW  Sparse Network Of Winnows (Munoz et al. , 1999). 
We solve this problem by using a shallow parser to extract noun phrase chunks from the original text (Munoz et al., 1999). 
Many machine learning techniques have been successfully applied to chunking tasks, such as Regularized Winnow (Zhang et al. , 2001), SVMs (Kudo and Matsumoto, 2001), CRFs (Sha and Pereira, 2003), Maximum Entropy Model (Collins, 2002), Memory Based Learning (Sang, 2002) and SNoW (Munoz et al. , 1999). 
The shallow parser used is the SNoW-based CSCL parser (Punyakanok and Roth, 2001; Munoz et al. , 1999). 
In (Munoz et al. , 1999), SNoW was used for text chunking. 
