Every account in which bridging references are addressed restricts allowable relationships to a small, relatively well-defined set (Vieira and Poesio 2001; Poesio et al. 2000; Murata, Isahara, and Nagao 1999; Strube and Hahn 1999).


Bridging anaphora (Clark, 1975) represents a special part of the general problem of anaphora resolution, which has been studied and discussed for various languages and domains (Hahn et al., 1996; Murata et al., 1999; Poesio et al., 2004; Gasperin and Vieira, 2004; Gasperin and Briscoe, 2008).


We used Japanese noun phrases of the fornl A no B to extract nouns that were syntactically related to A. Nouns in such a syntactic relation are usually close semantic relatives of each other (Murata et al. , 1999), and occur relatively infrequently.


