Labels were placed using the GUI-based annotation tool REFEREE (DeCristofaro et al. , 1999).


(1999) use two kinds of factors: (1) factors related to the NP under consideration such as agreement information, semantic factors, and discourse factors, and (2) factors related to the antecedent, such as animacy, clause type, thematic role, proximity, etc. Poesio et al.


Referee, a Tcl/Tk program for coreference annotation (DeCristofaro et al. , 1999), is better in this respect in that it writes the annotations to a separate file, leaving the annotated text itself unaltered.


