This may be overcome by using discriminative training procedures (Warnke et al. 1999; Ohler, Harbeck, and Niemann 1999).


This result is somewhat surprising since unigram dialogue grammars are able to detect speaker gender with 63% accuracy (over 350 Stolcke et al. Dialogue Act Modeling a 50% baseline) on Switchboard (Ries 1999b), indicating that there are global variables in the DA distribution that could potentially be exploited by a cache dialogue grammar.


In related work DAs are used as a first processing step to infer dialogue games (Carlson 1983; Levin and Moore 1977; Levin et al. 1999), a slightly higher level unit that comprises a small number of DAs.


Dialogue acts have been used to benefit tasks such as machine translation (Tanaka and Yokoo, 1999) and the automatic detection of dialogue games (Levin et al. , 1999).


