A Prolog based TBL tool, TBL (Lager, 1999) 2 is used in this study. 
While TBL gave the best results, the software we used (Lager, 1999) ran into memory problems and proved problematic with larger datasets. 
The full #-TBL system presented in (Lager, 1999) is even faster, uses less memory, and is in certain respects more general. 
While TBL gave the best results, the software we used (Lager, 1999) ran into memory problems and proved problematic with larger datasets. 
4.2 The experiments For the experiments with TBL we used the #-TBLpackage (Lager, 1999). 
