Simard (1999) describes a sentence aligner of this type that improves alignment on a trilingual parallel text. 
Simard (1999); seeSection5). 
Simard (1999) described a sentence aligner that makes simultaneous decisions in a trilingual parallel text. 
Simards (1999) trilingual (rather than multiparallel)corpusmethod,whichalsocomputesMSAs, is a notable exception, but he reports mixed experimental results. 
Simard (1999) showed how to adapt a bilingual method to align more than two c2008. 
