(2) <CC chemokine receptor 1> BINDS <leukocyte chemoattractant> <CC chemokine receptor 1> BINDS <hematopoiesis regulator macrophage inflammatory protein1 alpha> <CC chemokine receptor 1> BINDS <related CC chemokine> Considerable interest in information extraction has concentrated on identifying named entities in text pertaining to current events (for example, Wacholder et al. 1997, Voorhees and Harman 1998, and MUC-7); however, several recent efforts have been directed at biomolecular data (Blaschke et al. 1999, Craven and Kumlien 1999, and Rindflesch et al. 2000, for example).


To assess our ranking quality, we measure for each event the commonly used Average Precision (AP) measure (Voorhees and Harmann, 1998), which is the area under the non-interpolated recallprecision curve, while considering for each setup all correct extracted matches as 100% Recall.


